### PR TITLE
EvapCooler crash with autosized field and no design days run

### LINKED ISSUE #7083: EvapCooler crash with autosized field and no design days
Issue overview
--------------
EnergyPlus 9.0.1 crashes when there is a `EvaporativeCooler:Direct:ResearchSpecial` object that is autosized but there are no design days. Example file: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/2633284/in.idf.txt)

(Context: we were hardsizing the evap cooler object in OpenStudio, but a [bug in OpenStudio](https://github.com/NREL/OpenStudio/issues/3363) caused the airflow rate not to be written to the IDF, triggering this crash.)

cc @jmarrec @mpathak24

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
This fixes #7083. This crash is caused when EvapCooler trying to retrieve flow rate from system sizing variable (FinalSysSizing) when the system sizing did not run and FinalSysSizing not allocated. This fix checks system sizing run before allowing evaporative cooler accessing final system sizing variable. The fix avoids crash, instead fatal out with appropriate error message. The fix was applied to six evaporator cooler types. Diffs are not expected based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Performance: This pull request includes code changes that are directed at improving the runtime 
### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things

### CODE REVIEW

**Comment by shorowit** [comment]
Thanks @Nigusse!

File: src/EnergyPlus/EvaporativeCoolers.cc [hunk 1]
```diff
@@ -1498,6 +1501,7 @@ namespace EvaporativeCoolers {
                                            EvapCond(EvapCoolNum).IndirectPadArea);
                     }
                 } else { // Autosize or hardsize with design data
+                    CheckSysSizing(CompType, EvapCond(EvapCoolNum).EvapCoolerName);
```
Comment (Myoldmopar) [inline src/EnergyPlus/EvaporativeCoolers.cc:1504]: This is a great, simple fix.

File: tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc [hunk 2]
```diff
@@ -761,4 +761,65 @@ TEST_F(EnergyPlusFixture, DefaultAutosizeDirEvapCoolerTest)
...
+    std::string const error_string = delimited_string({
+        "   ** Severe  ** For autosizing of EvaporativeCooler:Direct:ResearchSpecial DIRECTEVAPCOOLER, a system sizing run must be done.",
+        "   **   ~~~   ** The \"SimulationControl\" object did not have the field \"Do System Sizing Calculation\" set to Yes.",
+        "   **  Fatal  ** Program terminates due to previously shown condition(s).",
+        "   ...Summary of Errors that led to program termination:",
+        "   ..... Reference severe error count=1",
+        "   ..... Last severe error=For autosizing of EvaporativeCooler:Direct:ResearchSpecial DIRECTEVAPCOOLER, a system sizing run must be done.",
+    });
+
+    EXPECT_TRUE(compare_err_stream(error_string, true));
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc:822]: Compact unit test that quickly gets to the point.  Thanks @Nigusse!

**Review by Myoldmopar — APPROVED** [review]
Code changes looks great, I'll test it locally and this should be able to go right in.

**Comment by Myoldmopar** [comment]
@Nigusse do you have a defect file available for this to quickly demonstrate the bug and the fix?  Or is there an example file that has an evaporative cooler file that can be modified by simply setting the evaporative cooler to autosize without design days?  My first attempt was taking the design days out of DirectIndirectEvapCoolers.idf but of course there's other stuff that requires them in that file so it fails before I can demonstrate this particular issue.

**Comment by Myoldmopar** [comment]
Ahh, nevermind, just realized the defect has a test file in the issue itself, just a minute...

**Comment by Myoldmopar** [comment]
OK, verified the crash on develop branch:

```
$ ./energyplus -w /eplus/epw/golden.epw 7083.idf
EnergyPlus Starting
EnergyPlus, Version 9.2.0-cbf96ed229, YMD=2019.06.04 06:28
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Segmentation fault (core dumped)
```

And verified the fatal and error message on this branch:

```
$ ./energyplus -w /eplus/epw/golden.epw 7083.idf 
EnergyPlus Starting
EnergyPlus, Version 9.2.0-dabf5d2968, YMD=2019.06.04 06:29
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Program terminated: EnergyPlus Terminated--Error(s) Detected.
```

This is good to go, thanks @Nigusse
