### PR TITLE
Fix distribution of internal gains to spaces

### LINKED ISSUE #11045: Fatal error in zones without floor
### Issue overview

When `Lights` with `LightingLevel` is added to `ZoneList` including zones without floor, the simulation terminates with the following fatal error.

```
   ** Severe  ** GetInternalHeatGains: Zone floor area is zero when allocating Lights loads to Spaces.
   **   ~~~   ** Occurs for Lights object =OFFICE::OFFICE_OPEN_LGT in Zone=2F_ZONE_1
   ** Severe  ** GetInternalHeatGains: Zone floor area is zero when allocating Lights loads to Spaces.
   **   ~~~   ** Occurs for Lights object =OFFICE::OFFICE_OPEN_LGT in Zone=2F_ZONE_2
   **  Fatal  ** GetInternalHeatGains: Errors found in Getting Internal Gains Input, Program Stopped
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=2
   ..... Last severe error=GetInternalHeatGains: Zone floor area is zero when allocating Lights loads to Spaces.
```

### Operating System (Multiple choices)

Windows

### Operating System Version

11

### Version of EnergyPlus

24.2.0

### Unmethours link or helpdesk ticket number

https://unmethours.com/question/101581/fatal-error-in-zones-without-floor/

### Defect file

(https://drive.google.com/drive/folders/1IkyA1hBbzlVTjUnevHmxy-C2x8-HVfck?usp=sharing)

This and more test files in EnergyPlusDevSupport\DefectFiles

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #11045 
- Consolidate multiple Design Level Method if ladders for People, Lights, ElectricEquipment, GasEquipment, HotWaterEquipment, SteamEquipment, and OtherEquipment into a new `setDesignLevel` function.
- Move some internal gains schedule checks up before the loop that applies a given input object to one or more spaces.
- If an internal gains object specifies a SpaceList name, with the "DesignLevel" method, the same level will be applied to every space in the list.
- If an internal gains object specifies a Zone (or a Zone within a ZoneList) that has only a single space, the full level will be applied to that space (regardless of floor areas).
- If an internal gains object specifies a Zone that has more than one space, and the zone has zero floor area, a severe/fatal error will still be issued, because there is not enough information to allocate the zone value to multiple spaces.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] ~If any diffs are expected, author must demonstrate they are justified using plots and descriptions~
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] ~If structural output changes, add to output rules file and add OutputChange label~
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Results for original defect file (UnmetHours_Test_AirBoundary.idf), where 1000W of lighting is expect in these two zones which have no floor surface and have on space per zone.
```
ZoneList,
    Void,                    !- Name
    2F_Zone_1,               !- Zone 1 Name
    2F_Zone_2;               !- Zone 2 Name

Lights,
    Office::office_open_lgt, !- Name
    Void,                    !- Zone or ZoneList or Space or SpaceList Name
    LEED_v4_Office_lighting, !- Schedule Name
    LightingLevel,           !- Design Level Calculation Method
    1000,                    !- Lighting Level {W}

```
Before, fatal error:
```
   ** Warning ** No floor exists in Zone="2F_ZONE_1", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
   ** Warning ** No floor exists in Zone="2F_ZONE_2", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
   ** Severe  ** GetInternalHeatGains: Zone floor area is zero when allocating Lights loads to Spaces.
   **   ~~~   ** Occurs for Lights object =OFFICE::OFFICE_OPEN_LGT in Zone=2F_ZONE_1
   ** Severe  ** GetInternalHeatGains: Zone floor area is zero when allocating Lights loads to Spaces.
   **   ~~~   ** Occurs for Lights object =OFFICE::OFFICE_OPEN_LGT in Zone=2F_ZONE_2
   **  Fatal  ** GetInternalHeatGains: Errors found in Getting Internal Gains Input, Program Stopped
 ```

After fix, no fatal error and 1000W of lighting in each of the 2 zones.
```
   ** Warning ** No floor exists in Zone="2F_ZONE_1", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
   ** Warning ** No floor exists in Zone="2F_ZONE_2", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
```

image

**Comment by mjwitte** [comment]
Second defect file, 5ZoneAirCooledWithSpaces-LightsToSpaceList, expect 100 W of lighting in every space.
```
Lights,
    All Spaces 100W,         !- Name
    AllConditionedSpaces,    !- Zone or ZoneList or Space or SpaceList Name
    LIGHTS-1,                !- Schedule Name
    LightingLevel,           !- Design Level Calculation Method
    100,                     !- Lighting Level {W}
SpaceList,
    AllConditionedSpaces,    !- Name
    Space 1,                 !- Space 1 Name
    Space 2,                 !- Space 2 Name
    Space 3 Open Office 1,   !- Space 3 Name
    Space 3 Open Office 2,   !- Space 4 Name
    Space 3 Storage,         !- Space 5 Name
    Space 4,                 !- Space 6 Name
    Space 5 Office,          !- Space 7 Name
    Space 5 Conference;      !- Space 8 Name
```

Before, lighting levels are incorrect for any space in a multi-space zone.
image

After fix, 100W in every space:
image

File: src/EnergyPlus/InternalHeatGains.hh [hunk 1]
```diff
@@ -65,6 +65,21 @@ struct EnergyPlusData;
 
 namespace InternalHeatGains {
 
+    enum class DesignLevelMethod
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.hh:68]: New enum for internal gains design level method.

File: src/EnergyPlus/InternalHeatGains.hh [hunk 2]
```diff
@@ -91,6 +106,17 @@ namespace InternalHeatGains {
                                 bool &errors,
                                 const bool zoneListNotAllowed = false);
 
+    Real64 setDesignLevel(EnergyPlusData &state,
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.hh:109]: New function to consolidate setting the design level by method into one place (instead of 7 if ladders).

File: src/EnergyPlus/InternalHeatGains.cc [hunk 3]
```diff
@@ -377,8 +383,40 @@ namespace InternalHeatGains {
                                                                          IHGNumericFieldNames);
 
                 ErrorObjectHeader eoh{routineName, peopleModuleObject, IHGAlphas(1)};
-                // Create one People instance for every space associated with this People input object
+                Sched::Schedule *schedPtr = Sched::GetSchedule(state, IHGAlphas(3));
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:379]: Also moved schedule checks out of the spaces loop, only need to check this once per input object. (Moved for all 7 internal gains).

File: src/EnergyPlus/InternalHeatGains.cc [hunk 4]
```diff
@@ -377,8 +383,40 @@ namespace InternalHeatGains {
...
+                case DesignLevelMethod::AreaPerPerson: {
+                    fieldNum = 3;
+                } break;
+                default: {
+                    assert(false);
+                } break;
+                }
+                Real64 const levelValue = IHGNumbers(fieldNum);
+                bool const levelBlank = IHGNumericFieldBlanks(fieldNum);
+                std::string_view const levelField = IHGNumericFieldNames(fieldNum);
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:410]: Set up arguments for `setDesignLevel`.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 5]
```diff
@@ -387,131 +425,11 @@ namespace InternalHeatGains {
...
-                                                       IHGAlphas(1),
-                                                       IHGAlphaFieldNames(4),
-                                                       IHGAlphas(4)));
-                                ShowContinueError(state, "...Valid values are \"People\", \"People/Area\", \"Area/Person\".");
-                                ErrorsFound = true;
-                            }
-                        }
-                    }
+                    thisPeople.NumberOfPeople = setDesignLevel(
+                        state, ErrorsFound, peopleModuleObject, thisPeopleInput, levelMethod, zoneNum, spaceNum, levelValue, levelBlank, levelField);
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:425]: Call `setDesignLevel`. (Repeat this pattern for 7 internal gain types.)

File: src/EnergyPlus/InternalHeatGains.cc [hunk 6]
```diff
@@ -2564,6 +2023,8 @@ namespace InternalHeatGains {
                     thisZoneITEq.Name = thisITEqInput.names(Item1);
                     thisZoneITEq.spaceIndex = spaceNum;
                     thisZoneITEq.ZonePtr = zoneNum;
+                    thisZoneITEq.operSched = opSchedPtr;
+                    thisZoneITEq.cpuLoadSched = cpuSchedPtr;
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:2051]: For IT equipment, moved the schedule checks, but did not replace it's design level calculation, because it is different from the others.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 7]
```diff
@@ -3914,6 +3354,138 @@ namespace InternalHeatGains {
...
+    Real64 setDesignLevel(EnergyPlusData &state,
+                          bool &ErrorsFound,
+                          std::string_view objectType,
+                          InternalHeatGains::GlobalInternalGainMiscObject &inputObject,
+                          DesignLevelMethod const method,
+                          int const zoneNum,
+                          int const spaceNum,
+                          Real64 inputValue,
+                          bool inputBlank,
+                          std::string_view fieldName)
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc]: The new `setDesignLevel` function.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 8]
```diff
@@ -3914,6 +3354,138 @@ namespace InternalHeatGains {
...
+    {
+        static constexpr std::string_view RoutineName("GetInternalHeatGains: "); // Use this for now to avoid error diffs
+
+        Real64 designLevel = 0.0; // return value
+
+        // Check input value
+        if (inputBlank) {
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:3422]: Check for blank value field, same check for all methods.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 9]
```diff
@@ -3914,6 +3354,138 @@ namespace InternalHeatGains {
...
+        switch (method) {
+        case DesignLevelMethod::People:
+        case DesignLevelMethod::LightingLevel:
+        case DesignLevelMethod::EquipmentLevel: {
+            // No check
+        } break;
+        case DesignLevelMethod::PeoplePerArea:
+        case DesignLevelMethod::WattsPerArea:
+        case DesignLevelMethod::PowerPerArea: {
+            if (inputValue < 0.0) {
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:3442]: Check for input values that are `<0` or `<=0` depending on the field.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 10]
```diff
@@ -3914,6 +3354,138 @@ namespace InternalHeatGains {
...
+            }
+        } break;
+        }
+        if (ErrorsFound) return designLevel;
+
+        switch (method) {
+        case DesignLevelMethod::People:
+        case DesignLevelMethod::LightingLevel:
+        case DesignLevelMethod::EquipmentLevel: {
+            // Set space load fraction
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:3470]: Main switch block to calculate the design level based on the specified `method`.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 11]
```diff
@@ -3914,6 +3354,138 @@ namespace InternalHeatGains {
...
+            Real64 spaceFrac = 1.0;
+            if (inputObject.numOfSpaces > 1) {
+                auto &zone = state.dataHeatBal->Zone(zoneNum);
+                if (inputObject.spaceListActive) {
+                    spaceFrac = 1.0; // apply the full amount to every space in the SpaceList
+                } else if (zone.numSpaces == 1) {
+                    spaceFrac = 1.0; // apply the full amount to the space in the zone
+                } else {
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:3478]: These lines are the real fix for #11045. These checks weren't done previously.

File: tst/EnergyPlus/unit/InternalHeatGains.unit.cc [hunk 12]
```diff
@@ -3484,3 +3485,159 @@ TEST_F(EnergyPlusFixture, ITE_Env_Class_Update_Class_H1)
     EXPECT_NE(thisspaceRpt.ITEqTimeBelowRH, state->dataGlobal->TimeStepZone);
     EXPECT_EQ(thisspaceRpt.ITEqTimeOutOfOperRange, state->dataGlobal->TimeStepZone);
 }
+TEST_F(EnergyPlusFixture, InternalHeatGains_SpaceAllocation)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/InternalHeatGains.unit.cc:3488]: New unit test.

**Review by mjwitte — COMMENTED** [review]
Walk-thru...

**Comment by nrel-bot-2** [comment]
@mjwitte @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@mjwitte @myoldmopar it has been 34 days since this pull request was last updated.

**Comment by rraustad** [comment]
Quick test using 5ZoneAirCooledWithSpaces-LightsToSpaceList lighting power density of 1.7256 to see if 800 W was the result:

image

File: src/EnergyPlus/InternalHeatGains.cc [hunk 13]
```diff
@@ -3914,6 +3354,138 @@ namespace InternalHeatGains {
...
+                    }
+                }
+            }
+            designLevel = inputValue * spaceFrac;
+        } break;
+        case DesignLevelMethod::PeoplePerArea:
+        case DesignLevelMethod::WattsPerArea:
+        case DesignLevelMethod::PowerPerArea: {
+            if (spaceNum != 0) {
+                auto &space = state.dataHeatBal->space(spaceNum);
```
Comment (rraustad) [inline src/EnergyPlus/InternalHeatGains.cc]: [src/EnergyPlus/InternalHeatGains.cc:3440]:(style),[constVariableReference],Variable 'space' can be declared as reference to const
[src/EnergyPlus/InternalHeatGains.cc:3455]:(style),[constVariableReference],Variable 'space' can be declared as reference to const
[src/EnergyPlus/InternalHeatGains.cc:3471]:(style),[constVariableReference],Variable 'space' can be declared as reference to const

File: src/EnergyPlus/InternalHeatGains.cc (hunk 7 above)
Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: The 3rd and last 3 arguments don't change, const these?

File: src/EnergyPlus/InternalHeatGains.cc (hunk 13 above)
Comment (mjwitte) [reply src/EnergyPlus/InternalHeatGains.cc]: Added some `const`s

**Comment by nrel-bot-2c** [comment]
@mjwitte @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by mitchute** [comment]
@mjwitte a couple of build errors here.

```
/Users/mmitchel/Projects/EnergyPlus/src/EnergyPlus/InternalHeatGains.cc:3436:17: error: enumeration values 'Invalid' and 'Num' not handled in switch [-Werror,-Wswitch]
 3436 |         switch (method) {
      |                 ^~~~~~
/Users/mmitchel/Projects/EnergyPlus/src/EnergyPlus/InternalHeatGains.cc:3436:17: note: add missing switch cases
 3436 |         switch (method) {
      |                 ^
/Users/mmitchel/Projects/EnergyPlus/src/EnergyPlus/InternalHeatGains.cc:3466:17: error: enumeration values 'Invalid' and 'Num' not handled in switch [-Werror,-Wswitch]
 3466 |         switch (method) {
      |                 ^~~~~~
/Users/mmitchel/Projects/EnergyPlus/src/EnergyPlus/InternalHeatGains.cc:3466:17: note: add missing switch cases
 3466 |         switch (method) {
      |                 ^
```

**Comment by mjwitte** [comment]
@mitchute Ok, I think this is cleaned up now.

**Review by mitchute — APPROVED** [review]
This all looks great. Merging.
