### PR TITLE
Heat Pump Plant Loop EIR refactoring

### LINKED ISSUE #10403: EIRFuelFiredHeatPump object electric energy consumption output variable reports zero value
Issue overview
--------------
Refactoring `EIRPlantLoopHeatPump` module revealed that the electric energy consumption of the `EIRFuelFiredHeatPump` object is reported as zero value because of incorrect equation [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L2253) or as shown below:

current code:
    `this->powerEnergy = this->powerEnergy * reportingInterval;`
	
Should have been:
    `this->powerEnergy = this->powerUsage * reportingInterval;`

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, any)
 - Version of EnergyPlus (Develop, [19484de](https://github.com/NREL/EnergyPlus/commit/19484de37080ef08352d024a1b7a6ea5ede3f1aa))

Use the example file `PlantLoopHeatPump_Fuel-Fired.idf` as a defect file.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Refactoring as part of a new feature
 - Refactoring the `HeatPump:PlantLoop:EIR:*` module as part of a new feature that adds Heat Recovery capability to Air-to-water heat pump
 - Fix #10403

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Nigusse** [comment]
This is a refactoring effort; hence, diffs are not expected. However, a diff was found in one example file (`PlantLoopHeatPump_Fuel-Fired.idf`) because the refactoring process addressed a defect described [here](https://github.com/NREL/EnergyPlus/issues/10403).

**Comment by Nigusse** [comment]
An existing unit test failed due to the new `report()` function. This function should have been declared as virtual. I will push the branch with a fix along with the clang formatting change shortly.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 1]
```diff
@@ -136,13 +137,8 @@ void EIRPlantLoopHeatPump::simulate(
...
 
-    // update nodes
-    PlantUtilities::SafeCopyPlantNode(state, this->loadSideNodes.inlet, this->loadSideNodes.outlet);
-    state.dataLoopNodes->Node(this->loadSideNodes.outlet).Temp = this->loadSideOutletTemp;
-    if (this->waterSource) {
-        PlantUtilities::SafeCopyPlantNode(state, this->sourceSideNodes.inlet, this->sourceSideNodes.outlet);
-    }
-    state.dataLoopNodes->Node(this->sourceSideNodes.outlet).Temp = this->sourceSideOutletTemp;
+    // update report variables and nodes
+    this->report(state);
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:141]: Moved the node update to newly created function `report()`.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 2]
```diff
@@ -198,6 +194,7 @@ void EIRPlantLoopHeatPump::resetReportingVariables()
     this->fractionalDefrostTime = 0.0;
     this->partLoadRatio = 0.0;
     this->cyclingRatio = 0.0;
+    this->defrostPowerMultiplier = 1.0;
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:197]: Since defrost calculation is refactored to a new function I added a new member variable `defrostPowerMultiplier` for use else where.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 3]
```diff
@@ -315,12 +312,6 @@ void EIRPlantLoopHeatPump::setOperatingFlowRatesASHP(EnergyPlusData &state, bool
 
 void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
 {
-
-    Real64 constexpr RH90 = 90.0;
-    Real64 constexpr RH60 = 60.0;
-    Real64 constexpr rangeRH = 30.0;
-    Real64 const reportingInterval = state.dataHVACGlobal->TimeStepSysSec;
-
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:323]: Moved to a new function `heatingCapacityModifierASHP`.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 4]
```diff
@@ -329,15 +320,68 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
         return;
     }
 
+    // dispatch to specific physics calculations based on the heat pump type
+    if (this->waterSource) {
+        this->doPhysicsWSHP(state, currentLoad);
+    } else if (this->airSource) {
+        this->doPhysicsASHP(state, currentLoad);
+    }
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:328]: Now we have two separate functions `doPhysicsWSHP()` and `doPhysicsASHP()` that are wrapped in existing `doPhysics()`. The `doPhysics()` is a virtual function used for `EIRFuelFiredHeatPump` module as well.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 5]
```diff
@@ -329,15 +320,68 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+    // evaluate the actual current operating load side heat transfer rate
+    this->calcLoadSideHeatTransfer(state, availableCapacity);
+
+    // no defrost calculation for WSHP
+    // calculate power usage from EIR curves
+    this->calcPowerUsage(state);
+
+    // evaluate the source side heat transfer rate
+    this->calcSourceSideHeatTransferWSHP(state);
+}
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:351]: The WSHP do physics new function `doPhysicsWSHP()`, which is a wrapper for all water source calculations. No defrost calculation call here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 6]
```diff
@@ -329,15 +320,68 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+    // evaluate the actual current operating load side heat transfer rate
+    this->calcLoadSideHeatTransfer(state, availableCapacity);
+
+    //  calculate power usage from EIR curves
+    this->calcPowerUsage(state);
+
+    // evaluate the source side heat transfer rate
+    this->calcSourceSideHeatTransferASHP(state);
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:375]: The ASHP do physics new function `doPhysicsASHP()`, which is a wrapper for all air-source calculations. Has defrost calculation call.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 7]
```diff
@@ -329,15 +320,68 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+{
     // get setpoint on the load side outlet
     Real64 loadSideOutletSetpointTemp = this->getLoadSideOutletSetPointTemp(state);
     Real64 originalLoadSideOutletSPTemp = loadSideOutletSetpointTemp;
 
     // add free cooling at some point, compressor is off during free cooling, temp limits restrict free cooling range
 
     Real64 capacityModifierFuncTemp = 1.0;
-    Real64 availableCapacity = this->referenceCapacity;
-    Real64 partLoadRatio = 0.0;
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:340]: removed these local Variables; they are now arguments of the new function `calcAvailableCapacity()`.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 8]
```diff
@@ -347,18 +391,8 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
-            Real64 dryCorrectionFactor = std::min(1.0, Curve::CurveValue(state, this->capacityDryAirCurveIndex, state.dataEnvrn->OutDryBulbTemp));
-            if (state.dataEnvrn->OutRelHum <= RH60) {
-                // dry heating capacity correction factor is a function of outdoor dry-bulb temperature
-                availableCapacity *= dryCorrectionFactor;
-            } else {
-                // interpolation of heating capacity between wet and dry is based on outdoor relative humidity over 60%-90% range
-                Real64 semiDryFactor = dryCorrectionFactor + (1.0 - dryCorrectionFactor) * (1.0 - ((RH90 - state.dataEnvrn->OutRelHum) / rangeRH));
-                availableCapacity *= semiDryFactor;
-            }
-        }
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:361]: These codes are now moved to a new function `heatingCapacityModifierASHP()`. This function is with air-source HP in heating mode only.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 9]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
         }
     }
 
+    // check the curve values, reset to zero if negative
+    this->capModFTCurveCheck(state, loadSideOutletSetpointTemp, capacityModifierFuncTemp);
+}
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:436]: Created a capacity modifier curve value check function and used in `calcAvailableCapacity()` only.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 10]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+            // interpolation of heating capacity between wet and dry is based on outdoor relative humidity over 60%-90% range
+            Real64 semiDryFactor = dryCorrectionFactor + (1.0 - dryCorrectionFactor) * (1.0 - ((RH90 - state.dataEnvrn->OutRelHum) / rangeRH));
+            return semiDryFactor;
+        }
+    } else {
+        // no correction needed, use full capacity
+        return 1.0;
+    }
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:460]: refactored new member function.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 11]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+        // Adjust cycling ratio and set part load ratio to minimum
         cyclingRatio = partLoadRatio / this->minimumPLR;
         partLoadRatio = this->minimumPLR;
-        operatingPLR = partLoadRatio * cyclingRatio;
     }
+
+    // update class member variables
     this->partLoadRatio = partLoadRatio;
     this->cyclingRatio = cyclingRatio;
+}
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:476]: This refactored new member function checks the PLR and sets to minimum value and updates the `CyclingRatio` when needed.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 12]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+    Real64 const operatingPLR = this->partLoadRatio * this->cyclingRatio;
+    this->loadSideHeatTransfer = availableCapacity * operatingPLR;
+
+    // calculate load side outlet conditions
+    Real64 const loadMCp = this->loadSideMassFlowRate * CpLoad;
+    this->loadSideOutletTemp = this->calcLoadOutletTemp(this->loadSideInletTemp, this->loadSideHeatTransfer / loadMCp);
+
+    // now what to do here if outlet water temp exceeds limit based on HW supply temp limit curves?
+    // currentLoad will be met and there should? be some adjustment based on outlet water temp limit?
+}
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:497]: New member function for calculating the load side heat transfer and the load side outlet temperature.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 13]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+    Real64 eirModifierFuncPLR = Curve::CurveValue(state, this->powerRatioFuncPLRCurveIndex, this->partLoadRatio);
+
+    // check curves value and resets to zero if negative
+    this->eirModCurveCheck(state, eirModifierFuncTemp, eirModifierFuncPLR);
+
+    // compute power usage
+    this->powerUsage = (this->loadSideHeatTransfer / this->referenceCOP) * eirModifierFuncPLR * eirModifierFuncTemp * this->defrostPowerMultiplier *
+                       this->cyclingRatio;
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:513]: New member function for calculating the power usage.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 14]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+            // just send it all to skin losses and leave the fluid temperature alone
+            this->sourceSideOutletTemp = this->sourceSideInletTemp;
+        } else if (this->sourceSideOutletTemp > this->sourceSideInletTemp) {
+            this->sourceSideOutletTemp = this->sourceSideInletTemp + 100.0; // cap it at 100C delta
+
+        } else if (this->sourceSideOutletTemp < this->sourceSideInletTemp) {
+            this->sourceSideOutletTemp = this->sourceSideInletTemp - 100.0; // cap it at 100C delta
+        }
+    }
+}
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:544]: New member function for calculating the source side heat transfer and the source side outlet temperature for WSHP.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 15]
```diff
@@ -397,16 +431,131 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+{
+    // energy balance on heat pump
+    this->sourceSideHeatTransfer = this->calcQsource(this->loadSideHeatTransfer, this->powerUsage);
+
+    // calculate source side outlet conditions
+    Real64 const CpSrc = Psychrometrics::PsyCpAirFnW(state.dataEnvrn->OutHumRat);
+    Real64 const sourceMCp = this->sourceSideMassFlowRate * CpSrc;
+    this->sourceSideOutletTemp = this->calcSourceOutletTemp(this->sourceSideInletTemp, this->sourceSideHeatTransfer / sourceMCp);
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:556]: New member function for calculating the source side heat transfer and the source side outlet temperature for ASHP.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 16]
```diff
@@ -427,10 +576,53 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
                                        capacityModifierFuncTemp);
         capacityModifierFuncTemp = 0.0;
     }
+}
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:579]: New member function for checking the capacity modifier curve value, resets the value to 0.0 if negative and throws error message.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 17]
```diff
@@ -427,10 +576,53 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
+                                       format("{} \"{}\": EIR Modifier curve (function of PLR) output is negative warning continues...",
+                                              DataPlant::PlantEquipTypeNames[static_cast<int>(this->EIRHPType)],
+                                              this->name),
+                                       this->eirModFPLRErrorIndex,
+                                       eirModifierFuncPLR,
+                                       eirModifierFuncPLR);
+        eirModifierFuncPLR = 0.0;
+    }
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:620]: New member function for checking the EIR modifier curve values, resets the value to 0.0 if negative and throws error message.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 18]
```diff
@@ -506,102 +699,8 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
         this->fractionalDefrostTime = 0.0;
     }
     availableCapacity *= HeatingCapacityMultiplier;
-    this->defrostEnergy = this->defrostEnergyRate * reportingInterval;
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:509]: energy related report variables update has moved to the new member report() function.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 19]
```diff
@@ -506,102 +699,8 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
-        }
-        ShowRecurringWarningErrorAtEnd(state,
-                                       format("{} \"{}\": EIR Modifier curve (function of PLR) output is negative warning continues...",
-                                              DataPlant::PlantEquipTypeNames[static_cast<int>(this->EIRHPType)],
-                                              this->name),
-                                       this->eirModFPLRErrorIndex,
-                                       eirModifierFuncPLR,
-                                       eirModifierFuncPLR);
-        eirModifierFuncPLR = 0.0;
-    }
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:568]: Curve checks has moved to the new functions.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 20]
```diff
@@ -506,102 +699,8 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
-
-    this->powerUsage =
-        (this->loadSideHeatTransfer / this->referenceCOP) * eirModifierFuncPLR * eirModifierFuncTemp * InputPowerMultiplier * this->cyclingRatio;
-    this->powerEnergy = this->powerUsage * reportingInterval;
-
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:573]: Power usage calculation has moved to a new member function `calcPowerUsage()` and the `powerEnergy` is calculation moved to report() functio.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 21]
```diff
@@ -506,102 +699,8 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
-            this->sourceSideOutletTemp = this->sourceSideInletTemp;
-        } else if (this->sourceSideOutletTemp > this->sourceSideInletTemp) {
-            this->sourceSideOutletTemp = this->sourceSideInletTemp + 100.0; // cap it at 100C delta
-
-        } else if (this->sourceSideOutletTemp < this->sourceSideInletTemp) {
-            this->sourceSideOutletTemp = this->sourceSideInletTemp - 100.0; // cap it at 100C delta
-        }
-    }
+    // update class member variables
+    this->defrostPowerMultiplier = InputPowerMultiplier;
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:703]: The new member variable `defrostPowerMultiplier` is set here and used in the `calcPowerUsage()` function.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 22]
```diff
@@ -1832,6 +1931,25 @@ void EIRPlantLoopHeatPump::oneTimeInit(EnergyPlusData &state)
...
+
+    // update nodes
+    PlantUtilities::SafeCopyPlantNode(state, this->loadSideNodes.inlet, this->loadSideNodes.outlet);
+    state.dataLoopNodes->Node(this->loadSideNodes.outlet).Temp = this->loadSideOutletTemp;
+    if (this->waterSource) {
+        PlantUtilities::SafeCopyPlantNode(state, this->sourceSideNodes.inlet, this->sourceSideNodes.outlet);
+    }
+    state.dataLoopNodes->Node(this->sourceSideNodes.outlet).Temp = this->sourceSideOutletTemp;
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1952]: New member report() function.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 23]
```diff
@@ -2249,13 +2366,9 @@ void EIRFuelFiredHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
     }
     this->powerUsage += this->standbyElecPower;
 
-    this->fuelEnergy = this->fuelRate * reportingInterval;
-    this->powerEnergy = this->powerEnergy * reportingInterval;
-
     // energy balance on heat pump
     // this->sourceSideHeatTransfer = this->calcQsource(this->loadSideHeatTransfer, this->powerUsage);
     this->sourceSideHeatTransfer = this->calcQsource(this->loadSideHeatTransfer, this->fuelRate + this->powerUsage - this->standbyElecPower);
-    this->sourceSideEnergy = this->sourceSideHeatTransfer * reportingInterval;
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:2371]: Report variables update has moved to the new member `report()` function.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 24]
```diff
@@ -3058,4 +3171,19 @@ void EIRFuelFiredHeatPump::oneTimeInit(EnergyPlusData &state)
...
+    this->loadSideEnergy = this->loadSideHeatTransfer * reportingInterval;
+    this->powerEnergy = this->powerUsage * reportingInterval;
+    this->sourceSideEnergy = this->sourceSideHeatTransfer * reportingInterval;
+
+    // update nodes
+    PlantUtilities::SafeCopyPlantNode(state, this->loadSideNodes.inlet, this->loadSideNodes.outlet);
+    state.dataLoopNodes->Node(this->loadSideNodes.outlet).Temp = this->loadSideOutletTemp;
+    state.dataLoopNodes->Node(this->sourceSideNodes.outlet).Temp = this->sourceSideOutletTemp;
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:3187]: Add similar new member report() function for `EIRFuelFiredHeatPump` module as well.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.hh [hunk 25]
```diff
@@ -229,12 +230,38 @@ namespace EIRPlantLoopHeatPumps {
...
+        void calcLoadSideHeatTransfer(EnergyPlusData &state, Real64 const availableCapacity);
+
+        void calcPowerUsage(EnergyPlusData &state);
+
+        void calcSourceSideHeatTransferWSHP(EnergyPlusData &state);
+
+        void calcSourceSideHeatTransferASHP(EnergyPlusData &state);
+
+        virtual void report(EnergyPlusData &state);
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.hh:252]: The various refactored member functions.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.hh [hunk 26]
```diff
@@ -229,12 +230,38 @@ namespace EIRPlantLoopHeatPumps {
...
         void sizeSrcSideWSHP(EnergyPlusData &state);
 
         void sizeSrcSideASHP(EnergyPlusData &state);
 
+        void doDefrost(EnergyPlusData &state, Real64 &AvailableCapacity);
+
+        void capModFTCurveCheck(EnergyPlusData &state, const Real64 loadSideOutletSPTemp, Real64 &capModFTemp);
+
+        void eirModCurveCheck(EnergyPlusData &state, Real64 &eirModFTemp, Real64 &eirModFPLR);
+
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.hh:264]: Same as above.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 27]
```diff
@@ -3499,6 +3499,7 @@ TEST_F(EnergyPlusFixture, Test_Curve_Negative_Energy)
     thisCoolingPLHP->loadSideInletTemp = 20;
     thisCoolingPLHP->sourceSideInletTemp = 20;
     thisCoolingPLHP->doPhysics(*state, curLoad);
+    thisCoolingPLHP->report(*state);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:3502]: called the new `report()` function here to update the report variables for testing.

**Review by Nigusse — COMMENTED** [review]
Code refactoring walkthrough for `EIRPlantLoopHeatPump`

**Comment by Nigusse** [comment]
This branch is ready for review, and it includes the fix for issue #10403. Because of this fix, diff is expected in `PlantLoopHeatPump_Fuel-Fired.idf` example file.

**Comment by Myoldmopar** [comment]
@Nigusse this is now conflicted, looks like maybe you made a similar-but-not-quite-the-same change in your heat pump fix branch?  I'm going to hold off on this for now, but feel free to merge up develop and resolve that small conflict.

**Comment by Nigusse** [comment]
I am going to work on it now.

**Comment by Nigusse** [comment]
@Myoldmopar Merged in develop and resolved conflict. Run regression tests on five example files (with EIR Heat Pump) and found no diffs. Diffs were not expected for this branch.

**Comment by Myoldmopar** [comment]
Thanks @Nigusse, I'll let CI run, but this will merge if CI is green.

**Comment by Myoldmopar** [comment]
All green, thanks @Nigusse, merging.
