### PR TITLE
Correct crash with DOAS VS DX coils and fix system name in Coil Sizing tables

### LINKED ISSUE #10332: Multiple DOAS systems can report incorrect system type and name in Coil Sizing tables
Issue overview
--------------
User file shows incorrect HVAC Type and HVAC Name for 1 of 3 DOAS systems for coils GUID11_SYS4OACC-1 and GUID11_SYS4OAHC-1. This result is after initial code corrections were made to get the file to run successfully.

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      GUID11_SYS4,
      GUID11_SYS4OA System,
      GUID11_SYS4DOASAHUSchedule1,
      GUID11_SYS4Mixer,
      GUID11_SYS4Splitter,
      35,
      0.000301701135445576,
      12.7777777777778,
      0.00912926351867603,
      1,
      GUID11_SYS1;

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      GUID11_SYS3,
      GUID11_SYS3OA System,
      GUID11_SYS3DOASAHUSchedule1,
      GUID11_SYS3Mixer,
      GUID11_SYS3Splitter,
      35,
      0.000301701135445576,
      12.7777777777778,
      0.0144901770124886,
      1,
      GUID11_SYS2;

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      GUID11_SYS5,
      GUID11_SYS5OA System,
      GUID11_SYS5DOASAHUSchedule1,
      GUID11_SYS5Mixer,
      GUID11_SYS5Splitter,
      35,
      0.000301701135445576,
      12.7777777777778,
      0.00912926351867603,
      4,
      GUID26_Zn_Room_00_02_SZVAV,
      GUID26_Zn_Room_00_01_SZVAV,
      GUID26_Zn_Room_00_00_SZVAV,
      GUID26_Zn_Room_00_03_SZVAV;

image

Issue description courtesy of Trane North America.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([MultipleDOASSystems-CoilSizingTable.idf.txt](https://github.com/NREL/EnergyPlus/files/13689696/MultipleDOASSystems-CoilSizingTable.idf.txt))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #10332
 - A user file with multiple DOAS systems using variable speed DX coolig coils did not run in EnergyPlus and when corrected showed incorrect HVAC Type and HVAC Name in Coil Details tables.

**Reporting corrections:**
 - HVAC Type and HVAC Name are reported for DOAS system
 - DOAS coil air flow is reported
 - System Sizing Method Concurrence method added Combination for when air loops used different sizing methods
 - TU heating coil air flow rate

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -853,7 +853,6 @@ namespace AirLoopHVACDOAS {
         if (state.dataGlobal->BeginEnvrnFlag && this->MyEnvrnFlag) {
             bool ErrorsFound = false;
             Real64 rho;
-            state.dataSize->CurSysNum = this->m_OASystemNum;
```
Comment (rraustad) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:856]: Underlying problem with the table reporting issues. This line reset CurSysNum to CurOASysNum which confused table reports. The component variables CurSysNum and CurOASysNum are set in SizingAirLoopDOAS as:

    state.dataSize->CurSysNum = state.dataHVACGlobal->NumPrimaryAirSys + this->m_AirLoopDOASNum + 1;
    state.dataSize->CurOASysNum = this->m_OASystemNum;

Whether these initializations should be moved to SimAirLoopHVACDOAS to emulate SimAirLoops is another question. I'm not sure these variables are used in anything other than sizing.

File: src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc [hunk 2]
```diff
@@ -451,7 +451,7 @@ Real64 HeatingCapacitySizer::size(EnergyPlusData &state, Real64 _originalValue,
 
     this->selectSizerOutput(state, errorsFound);
 
-    if (this->isCoilReportObject && this->curSysNum <= state.dataHVACGlobal->NumPrimaryAirSys) {
+    if (this->isCoilReportObject) {
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc:454]: Many of these issues. The DOAS indexes are currently appended to the number of air loops (i.e., CurSysNum = 6 for a DOAS with 5 AirLoopHVAC objects). When code uses CurSysNum to access air loop arrays there is an access violation when DOAS components are sized. These subtle changes were made to get this defect file to run.

File: src/EnergyPlus/ReportCoilSelection.cc [hunk 3]
```diff
@@ -149,7 +150,9 @@ void ReportCoilSelection::writeCoilSelectionOutput(EnergyPlusData &state)
             OutputReportPredefined::PreDefTableEntry(state,
                                                      state.dataOutRptPredefined->pdchHeatCoilAirloopName,
                                                      c->coilName_,
-                                                     c->airloopNum > 0 ? state.dataAirSystemsData->PrimaryAirSystems(c->airloopNum).Name : "N/A");
+                                                     c->airloopNum > 0 && c->airloopNum <= state.dataHVACGlobal->NumPrimaryAirSys
+                                                         ? state.dataAirSystemsData->PrimaryAirSystems(c->airloopNum).Name
+                                                         : "N/A");
```
Comment (rraustad) [inline src/EnergyPlus/ReportCoilSelection.cc:155]: DOAS index violation. The thing I don't like about the if (airloopNum < NumPrimaryAirSys) is that DOAS information is not reported. This is of course fixable.

File: src/EnergyPlus/ReportCoilSelection.cc [hunk 4]
```diff
@@ -543,7 +548,7 @@ void ReportCoilSelection::doAirLoopSetup(EnergyPlusData &state, int const coilVe
 {
     // this routine sets up some things for central air systems, needs to follow setting of an airloop num
     auto &c(coilSelectionDataObjs[coilVecIndex]);
-    if (c->airloopNum > 0 && allocated(state.dataAirSystemsData->PrimaryAirSystems)) {
+    if (c->airloopNum > 0 && c->airloopNum <= state.dataAirSystemsData->PrimaryAirSystems.size()) {
```
Comment (rraustad) [inline src/EnergyPlus/ReportCoilSelection.cc]: DOAS index violation within this block.

File: src/EnergyPlus/ReportCoilSelection.cc [hunk 5]
```diff
@@ -735,7 +740,12 @@ void ReportCoilSelection::doFinalProcessingOfCoilData(EnergyPlusData &state)
             }     // if (zoneEquipList.numOfEquipTypes > 0)
         }         // if (c->ZoneEqNum > 0)
 
-        if (c->airloopNum > 0 && c->zoneEqNum == 0) {
+        if (c->airloopNum > state.dataHVACGlobal->NumPrimaryAirSys && c->oASysNum > 0) {
+            c->coilLocation = "DOAS AirLoop";
+            c->typeHVACname = "AirLoopHVAC:DedicatedOutdoorAirSystem";
+            int DOASSysNum = state.dataAirLoop->OutsideAirSys(c->oASysNum).AirLoopDOASNum;
+            c->userNameforHVACsystem = state.dataAirLoopHVACDOAS->airloopDOAS[DOASSysNum].Name;
+        } else if (c->airloopNum > 0 && c->zoneEqNum == 0) {
```
Comment (rraustad) [inline src/EnergyPlus/ReportCoilSelection.cc:748]: Correct Coil Sizing tables to report DOAS type and name correctly.

File: src/EnergyPlus/ReportCoilSelection.cc [hunk 6]
```diff
@@ -1276,7 +1286,8 @@ void ReportCoilSelection::setCoilCoolingCapacity(
     //    if ( c->zoneEqNum > 0 ) doZoneEqSetup( index );
     c->oASysNum = curOASysNum;
 
-    if (curSysNum > 0 && c->zoneEqNum == 0 && allocated(state.dataSize->FinalSysSizing) && allocated(SysSizPeakDDNum)) {
+    if (curSysNum > 0 && c->zoneEqNum == 0 && allocated(state.dataSize->FinalSysSizing) && allocated(SysSizPeakDDNum) &&
+        curSysNum <= state.dataHVACGlobal->NumPrimaryAirSys) {
```
Comment (rraustad) [inline src/EnergyPlus/ReportCoilSelection.cc:1294]: DOAS index violation within this if block.

File: src/EnergyPlus/UnitarySystem.cc [hunk 7]
```diff
@@ -15933,7 +15933,9 @@ namespace UnitarySystems {
                         thisOASysEqSizing.HeatingCapacity = false;
                         this->m_FirstPass = false;
                     } else if (state.dataSize->CurSysNum > 0) {
-                        state.dataAirLoop->AirLoopControlInfo(state.dataSize->CurSysNum).UnitarySysSimulating = false;
+                        if (state.dataSize->CurSysNum <= state.dataHVACGlobal->NumPrimaryAirSys) {
+                            state.dataAirLoop->AirLoopControlInfo(state.dataSize->CurSysNum).UnitarySysSimulating = false;
+                        }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:15938]: Protect access array violation when CoilSystem is used in DOAS systems.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 8]
```diff
@@ -4748,10 +4748,16 @@ namespace VariableSpeedCoils {
...
+                    auto &thisAirloopDOAS =
+                        state.dataAirLoopHVACDOAS->airloopDOAS[state.dataAirLoop->OutsideAirSys(state.dataSize->CurOASysNum).AirLoopDOASNum];
+                    RatedAirVolFlowRateDes = thisAirloopDOAS.SizingMassFlow / state.dataEnvrn->StdRhoAir;
                 } else {
-                    RatedAirVolFlowRateDes = 0.0;
+                    if (state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).DesMainVolFlow >= DataHVACGlobals::SmallAirVolFlow) {
+                        RatedAirVolFlowRateDes = state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).DesMainVolFlow;
+                    } else {
+                        RatedAirVolFlowRateDes = 0.0;
+                    }
```
Comment (rraustad) [inline src/EnergyPlus/VariableSpeedCoils.cc:4760]: Add to VS DX coil sizing for coils in a DOAS. I did not update this code to use the sizing classes. Probably should have but was trying to get this file to run.

**Review by rraustad — COMMENTED** [review]
Walk-thru

**Comment by rraustad** [comment]
Defect file results:

image

File: src/EnergyPlus/DataSizing.hh [hunk 9]
```diff
@@ -120,6 +120,7 @@ namespace DataSizing {
     // parameters for sizing
     constexpr int NonCoincident(1);
     constexpr int Coincident(2);
+    constexpr int Combination(3);
```
Comment (rraustad) [inline src/EnergyPlus/DataSizing.hh:123]: If 1 airloop on a DOAS system sizes coincident and others size noncoincident then reporting for System Sizing Method Concurrence needs an alternate notation.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 10]
```diff
@@ -5014,6 +5043,8 @@ namespace VariableSpeedCoils {
             state.dataRptCoilSelection->coilSelectionReportObj->setCoilLvgAirTemp(state, varSpeedCoil.Name, varSpeedCoil.VarSpeedCoilType, SupTemp);
             state.dataRptCoilSelection->coilSelectionReportObj->setCoilLvgAirHumRat(
                 state, varSpeedCoil.Name, varSpeedCoil.VarSpeedCoilType, SupHumRat);
+            state.dataRptCoilSelection->coilSelectionReportObj->setCoilAirFlow(
+                state, varSpeedCoil.Name, varSpeedCoil.VarSpeedCoilType, varSpeedCoil.RatedAirVolFlowRate, RatedAirFlowAutoSized);
```
Comment (rraustad) [inline src/EnergyPlus/VariableSpeedCoils.cc:5047]: Heating coils in OA systems were not reporting air flow in Coil Sizing tables. Or maybe it's just DOAS system, but there are times when air flow = -999 and this corrects that.

**Comment by rraustad** [comment]
5Zone_Unitary_HXAssistedCoil table diffs. Both develop and this branch used TermUnitSizing(this->curTermUnitSizingNum).AirVolFlow = 0.129526 to size the zone heating coil, but develop reported the FinalZoneSizing heating volume flow = 0.15108.

image

**Comment by EnergyArchmage** [comment]
I have reviewed the code changes here and they look good.

File: src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc:454]: Interesting.  Should we actually use a separate counter for DOAS systems rather than keeping them magically in line with the other air loops?  That's something for later, but just curious how you'd like to proceed in the future.

**Review by Myoldmopar — APPROVED** [review]
These look good to me, I'll double check locally with other develop changes, but expect this to merge soon if clean.

File: src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc:454]: We have CurZoneEqNum, CurSysNum, and CurOASysNum. I think we do need a CurDOASNum. While making this change I was also wondering what the long term fix was. Still not sure if `if (this->isCoilReportObject && this->curDOASNum == 0)` is any better than what is here now.

**Comment by Myoldmopar** [comment]
Table diffs are quite expected and reasonable.  Otherwise this is happy and ready to merge.  Thanks @rraustad
