### PR TITLE
Correction of Outside Face Conductive Flux Output Variable

### LINKED ISSUE #10089: Incorrect Reporting for Outside Face Surface Heat Flux for Interzone Partitions
Issue overview
--------------
A user posted a comment on #8234 that mentioned what appeared to be a similar problem in that heat storage was building up over time when it should not have.  Essentially, when looking at the heat storage in a wall (difference between the inside face conduction heat flux and the outside face conduction heat flux), over an annual simulation, the sum of the heat storage should be relatively small.  The user was seeing a trend that consistently increased over time.  This seemed similar to #8234, but it is actually a completely different problem.  #8234 is specific to the finite difference solution scheme whereas this problem relates back to a reporting issue in the heat balance.  As they are two completely separate issues, this defect is being separated out for clarity.  The user's post on unmet hours can be found here:

https://unmethours.com/question/93625/infinite-heat-stored-in-ceiling/

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #10089 
 - From a post on unmet hours, a user noticed that the heat stored in a ceiling surface was increasing consistently.  The heat storage was measured by adding the inside and outside conductive flux together at each time step.  Over time, the value should rise and fall, not increase without end.  The problem was traced back to the fact that the surface was an interzone partition and the outside flux was not being calculated.  A switch in the code was skipping all partitions (regular and interzone).  It makes sense to skip the outside calculation for a regular partition because there is technically no "outside".  However, an interzone partition does have an outside and there should be a non-zero conductive flux.  This has been fixed and the user's input file now shows that the stored energy in the interzone surface energy level goes up and down rather than increase non-stop.  Due to the fact that an output variable changed, there are four files where the output has changed.  All four have interzone surfaces and request either the outside flux or the average flux (which is the sum of the inside and outside flux).  So, these changes in the output are expected and should take place.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 1]
```diff
@@ -5175,7 +5175,9 @@ void UpdateThermalHistories(EnergyPlusData &state)
                         state.dataHeatBalFanSys->CTFTuserConstPart(SurfNum);
                 }
 
-                if (surface.ExtBoundCond > 0) continue; // Don't need to evaluate outside for partitions
+                // Don't need to evaluate outside for partitions (so continue),
+                // but do need to do remaining calculations for interzone partitions.
+                if (surface.ExtBoundCond > 0 && surface.ExtBoundCond == SurfNum) continue;
```
Comment (EnergyArchmage) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: interesting. This seems closely related to issue #9466, code changes in the same area anyway.   I had found that self-referencing partitions were also not reporting those outside face variables accurately, for similar reasons as here.  But the code I suggested is different.  

`if (surface.ExtBoundCond > 0 && surface.ExtBoundCond != SurfNum) `

perhaps need to get rid of the entire if -> continue, turns out the calculations can't be saved without reporting errors.

Comment (Myoldmopar) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @EnergyArchmage do you think it's worth talking about this on tomorrow's call?

File: tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc [hunk 2]
```diff
@@ -8552,4 +8552,79 @@ TEST_F(EnergyPlusFixture, HeatBalanceSurfaceManager_TestUpdateVariableAbsorptanc
...
+    state->dataSurface->Surface(2).ExtBoundCond = 1;
+    state->dataHeatBalSurf->SurfOpaqInsFaceCondFlux = 0.0;
+    state->dataHeatBalSurf->SurfOpaqOutFaceCondFlux = 0.0;
+
+    UpdateThermalHistories(*state); // Test to make sure that the outside surface flux is being set properly for interzone surfaces
+
+    EXPECT_EQ(15.0, state->dataHeatBalSurf->SurfOpaqInsFaceCondFlux(1));
+    EXPECT_EQ(-15.0, state->dataHeatBalSurf->SurfOpaqOutFaceCondFlux(1));
+    EXPECT_EQ(-15.0, state->dataHeatBalSurf->SurfOpaqInsFaceCondFlux(2));
+    EXPECT_EQ(15.0, state->dataHeatBalSurf->SurfOpaqOutFaceCondFlux(2));
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc:8628]: 😍 I love unit tests that aren't littered with inputs, and instead just set up the necessary structures and do the tests.

**Review by Myoldmopar — COMMENTED** [review]
OK, so I'm going to withhold approval for a moment in case we need to discuss this further on the next technicalities call.  Not saying it's wrong, just wanting to pause a second.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc (hunk 1 above)
Comment (RKStrand) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Sorry--I guess I never responded to @EnergyArchmage here.  My reason for skipping the partitions (when ExtBoundCond = SurfNum) is that the "outside" is really the centerline of those surfaces.  So, the outside flux should be zero because it is adiabatic.  That isn't the case for an interzone partition.  If the partitions also assign the outside surface, I'm not even sure what it will report because there is no outside surface solution for a partition.  That's why I felt like the correct solution was to do what I did.  What were the reporting errors that you noticed?

Comment (EnergyArchmage) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: The output variables Surface Outside Face Conduction Heat Transfer Rate  and Surface Average Face Conduction Heat Transfer Rate never get calculated and Surface Heat Storage Rate has erroneous values.  

I think just remove the if -> continue line altogether.  I believe I put that in way back to save calculation time but it was a mistake.

Comment (RKStrand) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Ok, I can remove the if -> continue line.  That's not a problem (may have to adjust the unit test--can't remember as it's been a while).  Are you saying that these output variables are not valid and should be eliminated?  Or is there some other clarification that is needed for the IO Ref?

Comment (EnergyArchmage) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: I think the output variables for outside face are useful. It is just that the underlying calcs need to happen for each surface.

Comment (RKStrand) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Ok, I'll work to eliminate that line (and the new comments that went with it) and then make sure the unit tests are still doing what they need to do.  I'll post here again once I've finished all that and it's ready for another look.

**Comment by nrel-bot-2c** [comment]
@RKStrand it has been 7 days since this pull request was last updated.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc (hunk 1 above)
Comment (RKStrand) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @EnergyArchmage @Myoldmopar Ok, I've done as suggested, fixed the unit test, and clang-formatted everything.  This was just pushed up to GitHub.  Hopefully everything comes back as expected and this is good to go.

**Comment by Myoldmopar** [comment]
Conflict here was just the addition of unit tests in the same spot in multiple branches.  I merged develop in, and resolved it by simply keeping all the unit tests.  Everything builds and tests happily.  I'll let CI do a quick run on it while I break for dinner, but this will merge later if it's happy.

**Comment by Myoldmopar** [comment]
Diffs would certainly be expected in the files that use that output variable.  Otherwise all clean.  Merging, thanks @RKStrand
