### PR TITLE
Fix #11050 - Schedule initialization error in HighTempRadiantSystem

### LINKED ISSUE #11050: Schedule initialization error in HighTempRadiantSystem
### Issue overview

* Similar to https://github.com/NREL/EnergyPlus/issues/11018

This is a regression, that test used to run fine.

```
Performing Zone Sizing Simulation
...for Sizing Period: #2 CHICAGO OHARE INTL AP ANN HTG 99.6% CONDNS DB
Process 2955838 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x4c)
    frame #0: 0x00007ffff26b9656 libenergyplusapi.so.25.1.0`EnergyPlus::Sched::Schedule::getCurrentVal(this=0x0000000000000000) const at ScheduleManager.hh:275:20
   272 	
   273 	        Real64 getCurrentVal() const
   274 	        {
-> 275 	            return EMSActuatedOn ? EMSVal : currentVal;
   276 	        }
   277 	
   278 	        // Looks up a given Schedule value for an hour & timestep, minding whether DST is enabled or not
(lldb) bt
error: libenergyplusapi.so.25.1.0 0x0041d21a: DW_TAG_member '_M_local_buf' refers to type 0x000000000047d90b which extends beyond the bounds of 0x0041d210
* thread #1, name = 'energyplus', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x4c)
  * frame #0: 0x00007ffff26b9656 libenergyplusapi.so.25.1.0`EnergyPlus::Sched::Schedule::getCurrentVal(this=0x0000000000000000) const at ScheduleManager.hh:275:20
    frame #1: 0x00007ffff3c81a2d libenergyplusapi.so.25.1.0`EnergyPlus::HighTempRadiantSystem::CalcHighTempRadiantSystem(state=0x00007fffffffa8c0, RadSysNum=1) at HighTempRadiantSystem.cc:803:65
    frame #2: 0x00007ffff3c7ad59 libenergyplusapi.so.25.1.0`EnergyPlus::HighTempRadiantSystem::SimHighTempRadiantSystem(state=0x00007fffffffa8c0, CompName=(_M_len = 36, _M_str = "ZONE HVAC HIGH TEMPERATURE RADIANT 1"), FirstHVACIteration=true, LoadMet=0x00007fffffffa010, CompIndex=0x00005555568657c0) at HighTempRadiantSystem.cc:178:38
    frame #3: 0x00007ffff3132777 libenergyplusapi.so.25.1.0`EnergyPlus::ZoneEquipmentManager::SimZoneEquipment(state=0x00007fffffffa8c0, FirstHVACIteration=true, SimAir=0x00007fffffffa33b) at ZoneEquipmentManager.cc:3830:64
    frame #4: 0x00007ffff3110d6f libenergyplusapi.so.25.1.0`EnergyPlus::ZoneEquipmentManager::ManageZoneEquipment(state=0x00007fffffffa8c0, FirstHVACIteration=true, SimZone=0x00007fffffffa33c, SimAir=0x00007fffffffa33b) at ZoneEquipmentManager.cc:159:25
    frame #5: 0x00007ffff2d8155b libenergyplusapi.so.25.1.0`EnergyPlus::SizingManager::ManageSizing(state=0x00007fffffffa8c0) at SizingManager.cc:438:28
    frame #6: 0x00007ffff2d49cad libenergyplusapi.so.25.1.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffffa8c0) at SimulationManager.cc:233:36
    frame #7: 0x00007ffff2441b54 libenergyplusapi.so.25.1.0`RunEnergyPlus(state=0x00007fffffffa8c0, filepath="") at EnergyPlusPgm.cc:421:56
    frame #8: 0x00007ffff2440b7a libenergyplusapi.so.25.1.0`EnergyPlusPgm(args=size=1, filepath="") at EnergyPlusPgm.cc:242:25
    frame #9: 0x0000555555580bf6 energyplus`main(argc=1, argv=0x00007fffffffbfe8) at main.cc:60:25
    frame #10: 0x00007ffff102a1ca libc.so.6`__libc_start_call_main(main=(energyplus`main at main.cc:54:1), argc=1, argv=0x00007fffffffbfe8) at libc_start_call_main.h:58:16
    frame #11: 0x00007ffff102a28b libc.so.6`__libc_start_main_impl(main=(energyplus`main at main.cc:54:1), argc=1, argv=0x00007fffffffbfe8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffbfd8) at libc-start.c:360:3
    frame #12: 0x0000555555580a45 energyplus`_start + 37
```

### Operating System (Multiple choices)

Any

### Operating System Version

N/A

### Version of EnergyPlus

25.1.0, develop

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[autosize_hvac.rb.idf.txt](https://github.com/user-attachments/files/20053772/autosize_hvac.rb.idf.txt)

### PR DESCRIPTION
**Pull request by amirroth**
Pull request overview
---------------------

- Fixes #11050 

One line fix. Should be self-explanatory.

### CODE REVIEW

File: src/EnergyPlus/HighTempRadiantSystem.cc [hunk 1]
```diff
@@ -451,6 +451,7 @@ namespace HighTempRadiantSystem {
             }
 
             if (state.dataIPShortCut->lAlphaFieldBlanks(7)) {
+                highTempRadSys.setptSched = Sched::GetScheduleAlwaysOff(state);
```
Comment (amirroth) [inline src/EnergyPlus/HighTempRadiantSystem.cc]: Empty field means "AlwaysOff" schedule, so initialize with pointer to "AlwaysOff" schedule object. Not sure how "AlwaysOff" is a setpoint exactly, but that was the previous behavior. There could be a few more of these stragglers and this is the fix for all of them.

Comment (jmarrec) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: Seems like it's dependent on the "Temperature control type" field.

```
    MeanAirTemperature
    MeanRadiantTemperature
    OperativeTemperature
    MeanAirTemperatureSetpoint
    MeanRadiantTemperatureSetpoint
    OperativeTemperatureSetpoint
```

One could argue that it should probably fatal out if the ControlType is a Setpoint one and the schedule is missing, but I think it just makes the HighTempRadiant to never do anything,

https://github.com/NREL/EnergyPlus/blob/09a25d0d10d3a69ef2dc1bb8b45a82d898bed64a/src/EnergyPlus/HighTempRadiantSystem.cc#L915

**Review by jmarrec — APPROVED** [review]

File: src/EnergyPlus/HighTempRadiantSystem.cc (hunk 1 above)
Comment (amirroth) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: If one can argue that it should fatal out than I will make it fatal out. If one can argue that this should be a warning that the system will be disabled then I will do that. I would like to handle this the "right" way. Silently disabling this system if the schedule is empty does not seem like the "right" way.

Comment (mjwitte) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: > If one can argue that it should fatal out than I will make it fatal out. If one can argue that this should be a warning that the system will be disabled then I will do that. I would like to handle this the "right" way. Silently disabling this system if the schedule is empty does not seem like the "right" way.

@RKStrand ?

Comment (jmarrec) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: One could start by checking what's really happening if this is blank.  https://github.com/NREL/EnergyPlusDevSupport/commit/a18bcf32f0b43ff92a9ebc39169c4e3c30afd854

One could perhaps start by creating four MCVEs:

* TEMP_CTRL_TYPES = ['Operative', 'OperativeSetpoint']
* HAS_SCH = [True, False]

image

Then run them, then parse the end use by fuel table.

Something like this: https://github.com/NREL/EnergyPlusDevSupport/blob/a18bcf32f0b43ff92a9ebc39169c4e3c30afd854/DefectFiles/11000s/11050/One_could_start_by_checking_what_is_happening_now.ipynb

image

Comment (jmarrec) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: The schedule is also used if it's not a SetpointControl temperature control type.

I/O Ref states this:
> Field: Heating Setpoint Temperature Schedule Name[[LINK]](https://bigladdersoftware.com/epx/docs/24-2/input-output-reference/group-radiative-convective-units.html#field-heating-setpoint-temperature-schedule-name-1)

> This field specifies the heating setpoint or control temperature for the radiant system in degrees Celsius.

https://github.com/NREL/EnergyPlus/blob/09a25d0d10d3a69ef2dc1bb8b45a82d898bed64a/src/EnergyPlus/HighTempRadiantSystem.cc#L804

**One could draw the conclusion that the E+ IDD should probably just make this schedule `\required-field`.**

Comment (amirroth) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: I just noticed this too when trying to change the error condition. An empty schedule essentially disables the whole system silently. That's not the right thing to do.

Comment (jmarrec) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: I redid the analysis by checking all possible combinations

```
TEMP_CTRL_TYPES = [
    'MeanAirTemperature',
    'MeanRadiantTemperature',
    'OperativeTemperature',
    'MeanAirTemperatureSetpoint',
    'MeanRadiantTemperatureSetpoint',
    'OperativeTemperatureSetpoint'
]
HAS_SCH = [True, False]
```


image

Comment (amirroth) [reply src/EnergyPlus/HighTempRadiantSystem.cc]: TemperatureControlType (A6) is also not a required field. And when it is left empty, there are is no error message but there are asserts.

**Comment by RKStrand** [comment]
Sorry, all, that I have not been able to keep up on this thread.  I'm not sure why the code is currently the way that it is.  It's been around for a while (I think this was implemented in the early 2000s), and I honestly can't remember why I would have done it this way.  If there is not temperature control type, this is a pointless system that won't do anything.  Same goes for the lack of a control temperature schedule.  The only reason I can think of to allow the user to do this would be if someone is doing a bunch of iterations and wants an easy way to lock out this system without having to delete the whole thing.  I'm not sure that's a good enough reason to allow this unless @mjwitte thinks there is merit to that.  I think I would vote for requiring both the control type and the schedule with a severe followed by a fatal error if one or both are missing.

**Comment by mjwitte** [comment]
Temperature control type has a default, so that's covered.
```
   A6 , \field Temperature Control Type
        \default OperativeTemperature
```

But the Heating Setpoint Temperature Schedule should be required. One could argue that this should have a transition rule, but it's a pointless simulation without one. So, we could emit a transition warning about it or just let it fly by.

BTW this idd note is wrong:
```
   A7 , \field Heating Setpoint Temperature Schedule Name
        \note This setpoint is an "operative temperature" setpoint
```
Should be?
```
        \note This setpoint is mean air temperature, radiant temperature or operative temperature depending on the Temperature Control Type.
```

**Comment by amirroth** [comment]
Ok, I made the changes suggested by @mjwitte and @RKStrand. @jmarrec, your file is now going to fatal out at the epJSON parser. If you still want to run it, one way to do that is to make the Setpt Schedule Name `Constant-0.0` (that's the name of the builtin "AlwaysOff" schedule. Is this satisfactory?

**Comment by Myoldmopar** [comment]
I'll get the branch fixed up and pushed.  @mjwitte are you satisfied with this change now?

File: src/EnergyPlus/HighTempRadiantSystem.cc [hunk 2]
```diff
@@ -440,7 +440,14 @@ namespace HighTempRadiantSystem {
             }
 
             // Process the temperature control type
-            highTempRadSys.ControlType = static_cast<RadControlType>(getEnumValue(radControlTypeNamesUC, state.dataIPShortCut->cAlphaArgs(6)));
+            if (state.dataIPShortCut->lAlphaFieldBlanks(6)) {
+                ShowWarningEmptyField(state, eoh, state.dataIPShortCut->cAlphaFieldNames(6), "OperativeTemperature");
+                highTempRadSys.ControlType = RadControlType::OperativeControl;
```
Comment (rraustad) [inline src/EnergyPlus/HighTempRadiantSystem.cc:445]: A6 will never be blank since it has a default. Old line 443 is all that is needed.

    A6 , \field Temperature Control Type
        \note Temperature type used to control unit
        \type choice
        \key MeanAirTemperature
        \key MeanRadiantTemperature
        \key OperativeTemperature
        \key MeanAirTemperatureSetpoint
        \key MeanRadiantTemperatureSetpoint
        \key OperativeTemperatureSetpoint
        \default OperativeTemperature

File: src/EnergyPlus/HighTempRadiantSystem.cc [hunk 3]
```diff
@@ -451,6 +458,12 @@ namespace HighTempRadiantSystem {
...
             if (state.dataIPShortCut->lAlphaFieldBlanks(7)) {
+                ShowSevereEmptyField(state,
+                                     eoh,
+                                     state.dataIPShortCut->cAlphaFieldNames(7),
+                                     state.dataIPShortCut->cAlphaFieldNames(6),
+                                     state.dataIPShortCut->cAlphaArgs(6));
+                ErrorsFound = true;
             } else if ((highTempRadSys.setptSched = Sched::GetSchedule(state, state.dataIPShortCut->cAlphaArgs(7))) == nullptr) {
                 ShowSevereItemNotFound(state, eoh, state.dataIPShortCut->cAlphaFieldNames(7), state.dataIPShortCut->cAlphaArgs(7));
                 ErrorsFound = true;
```
Comment (rraustad) [inline src/EnergyPlus/HighTempRadiantSystem.cc:469]: A7 is now a required field so it can't be blank (I think) but it can have an invalid name, so 467 should be the only conditional?

**Comment by mjwitte** [comment]
> I'll get the branch fixed up and pushed. @mjwitte are you satisfied with this change now?

What @rraustad said.

**Comment by Myoldmopar** [comment]
OK, this was blessed as-is, with an understanding that maybe we can clean up some unnecessary error checking later.  @rraustad suggested checking the unit/integration test coverage to find get-input lines that aren't covered by any test, and use that as a starting point for detecting unnecessary checks.  Seems like as reasonable a jumping off point as any.

Merging this, thanks @amirroth and reviewers.
