### PR TITLE
Fix kiva clockwise geometry rule issue

### LINKED ISSUE #9103: Kiva problem when using clockwise geometry rule
Issue overview
--------------
The “Clockwise” rule is a much less frequently used option to most users, although it is still allowed and used by some users for some specifical needs. It was recently identified from an input file supplied by a user that used “clockwise” geometry rule, that would cause some essential lines of code block to be skipped inadvertently (and apparently incorrectly skipped). This will further cause EnergyPlus to crash due to floating-point overflow errors. 

The code that is apparently wrong is the condition statement of `i <= 0` in the following line: 
https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/HeatBalanceKivaManager.cc#L733

The correct statement should be `i >=0`. A temporary fix is placed to fix the apparent code errors above. It is not clear if this would be a full fix to the issue yet.

It is expected that the specific problem should not occur if a default “CounterClockWise” geometry rule (and the correct geometry specification and also other “correct” inputs). So sticking to the default and more commonly used “CounterClockWise” should avoid the problem. 

The above line is the obvious one that needs to be fixed (actually tried to fix in PR #9104). However, it seems that change alone would not fully fix the problem--the defect file would not go through and still encounters problems in other part of the foundation calculations. There could be more deeper changes needed for the Kiva foundation part that would be needed to make the defect file finally work (@nealkruis). Another test was conducted by changing the geometry rule to CounterClockWise and reverting all the surface vertex input orders from the orignal defect file---that actually yield a case that could run through without any problems. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): at least from v9.4 to v9.6
 - Unmethours link or helpdesk ticket number 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9103/9103_Kiva_Clockwise.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9103
 - Also, along with the conditional statement fix it is necessary to change the `auto i = 0` to `int i = 0` as the auto-cast will get an unsigned integer. Otherwise, it will cause a problem since `i` will very large positive number when `i` decreases one more tick from 0---which will not end the loop and point to some elements way out of bound.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceKivaManager.cc [hunk 1]
```diff
@@ -730,7 +730,7 @@ bool KivaManager::setupKivaInstances(EnergyPlusData &state)
                     }
                 }
             } else {
-                for (auto i = surface.Vertex.size() - 1; i <= 0; --i) {
+                for (int i = surface.Vertex.size() - 1; i >= 0; --i) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatBalanceKivaManager.cc:733]: I'd probably keep it a `size_t` to match the other side of the IF block.

Comment (jcyuan2020) [reply src/EnergyPlus/HeatBalanceKivaManager.cc:733]: Here it clearly needs a signed integer as it needs to get to the value of -1 to stop. The `size_t` seems to be an unsigned one--any signed counterpart of it?

Comment (nealkruis) [reply src/EnergyPlus/HeatBalanceKivaManager.cc:733]: @jcyuan2020, you can get around this with:

```cpp
for (auto i = surface.Vertex.size() - 1; i < surface.Vertex.size() /* i>=0 */; --i)
```

This exploits the unsigned int underflow that occurs at `0 - 1` while preserving the type comparison.

Otherwise this change makes sense to me. It's a good catch and probably something I should have tested better originally.

Comment (jcyuan2020) [reply src/EnergyPlus/HeatBalanceKivaManager.cc:733]: @nealkruis Thanks! I was just writing some notes address to you to take a look at this issue--see the comments under #9103. It seems that additional fixes might be needed to fix this.

Comment (Myoldmopar) [reply src/EnergyPlus/HeatBalanceKivaManager.cc:733]: Gah, OK, yeah I see the signed integer is needed, sorry about that.

**Comment by Myoldmopar** [comment]
So is there additional work on this then?  For now it can stay an int as far as I'm concerned.  Oh and do you anticipate drafting up a test for this?

**Comment by jcyuan2020** [comment]
Some further work needed in order to let the defect file run after the fix. See the comments in the original issue post #9103. For the existing part, I am not sure for now whether modified function would be executed to complete a unit test (or say, if the unit test would be dependent on the further fixes)--I will take a check on this soon.

**Comment by jcyuan2020** [comment]
Based on debugging run of the defect file, the further work would be here inside the same function as the current fix: 
https://github.com/NREL/EnergyPlus/blob/658dce2e15c1c689281203426bf0f5cf48a13539/src/EnergyPlus/HeatBalanceKivaManager.cc#L1015
This might mean it could be a little difficult to get pass through (at a first glance) in a unit test. Any comments or suggestions before jumping into creating a unit test?

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jcyuan2020 if you want to just wrap this one up as-is, and then do a follow-up PR that addresses the remaining issue and adds more testing that is fine.  I'd like to get this one merged in soon though, so if you plan to do that, we can review this and call this piece done when you feel it is ready (it's obviously a good step).

**Comment by nealkruis** [comment]
@Myoldmopar, we had talked about me taking this one over and addressing the other part of the issue too. I'm fine either way though. @jcyuan2020 how would you like to proceed?

**Comment by jcyuan2020** [comment]
@Myoldmopar @nealkruis Thanks! I've updated it with the most recent develop and it should be ok to go in as is, but obviously without a unit test since the function would not pass without further fixes.

**Comment by Myoldmopar** [comment]
OK, I'm going to go ahead and merge this.  I pulled it down and tested with latest develop, no problem.  I hope a follow-up PR can address any remaining issues and add testing to cover this change.  Thanks @jcyuan2020 and @nealkruis
