### PR TITLE
Protect WSHP from incorrect or missing curve names

### LINKED ISSUE #11025: Hard crash in WAHP CurveValue lookup
### Issue overview

# Summary
There is a hard crash occurring in a defect file when CurveValue is evaluated in the WAHP code.  I tracked down the issue, but I'm not able to provide the defect file just yet in case it contains anything proprietary. It's pretty easy to see what's going on though.

# Detective Work
In the `WaterToAirHeatPumpSimple.cc` file, inside `GetSimpleWatertoAirHPInput()`, the curves are retrieved from the curve manager.  If the curve lookup is invalid, it sets `ErrorsFound` to `true`.  This occurs in both develop and the curve API branch:
- `develop`: https://github.com/NREL/EnergyPlus/blob/68a4a7c7744c380886913a92e061aba3d4a3fc54/src/EnergyPlus/WaterToAirHeatPumpSimple.cc#L317
- `CurveAPI`: https://github.com/NREL/EnergyPlus/blob/81b1cbde1b34e99b631f5b7f8d7402c9a7c4ec7c/src/EnergyPlus/WaterToAirHeatPumpSimple.cc#L316

This is all good, except that just a little while later in the same get input routine, there is a call to `CheckSimpleWAHPRatedCurvesOutput`:
- `develop`: https://github.com/NREL/EnergyPlus/blob/68a4a7c7744c380886913a92e061aba3d4a3fc54/src/EnergyPlus/WaterToAirHeatPumpSimple.cc#L424
- `CurveAPI`: https://github.com/NREL/EnergyPlus/blob/81b1cbde1b34e99b631f5b7f8d7402c9a7c4ec7c/src/EnergyPlus/WaterToAirHeatPumpSimple.cc#L393

The `CheckSimpleWAHPRatedCurvesOutput` ends up making an attempted call to CurveValue on develop, or `wahp.TotalCoolCapCurve->v` on the CurveAPI branch, which causes the hard crash.  

# Fix
I'm guessing that we just need to check `ErrorsFound` before making the call to `CheckSimpleWAHPRatedCurvesOutputs`, and I think the rest of the get input could continue "successfully".  It should still respect the `ErrorsFound` variable and give a fatal error, but it should be OK to continue processing the remaining objects.

# Verify
I will try to get a defect file, but if it turns out I can't, the assignee can work up an example file that misspells the total cooling capacity curve on the simple WAHP.   Alternatively, I can just verify the fix locally on the actual defect file and report back.  Either way, a unit test should be moderately easy to set up to confirm.

### Operating System (Multiple choices)

Any

### Operating System Version

Any

### Version of EnergyPlus

Reported with 24.2, transitioned and confirmed still occurs with 25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------

- Fixes #11025

### Description of the purpose of this PR

Incorrect curve name leads to a crash when curves are evaluated in function CheckSimpleWAHPRatedCurvesOutputs.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Defect file previously crashed and showed a blank err file. This file now exits gracefully and err file shows cause of crash:

    ** Severe  ** GetSimpleWatertoAirHPInput: Coil:Cooling:WaterToAirHeatPump:EquationFit = SYS 1 HEAT PUMP COOLING MODE
    **   ~~~   ** Total Cooling Capacity Curve Name = TOTCOOLCAPCURV, item not found.
    ** Severe  ** GetSimpleWatertoAirHPInput: Coil:Cooling:WaterToAirHeatPump:EquationFit = SYS 1 HEAT PUMP COOLING MODE
    **   ~~~   ** Sensible Cooling Capacity Curve Name = COOLSENSCAPCURV, item not found.
    ** Severe  ** GetSimpleWatertoAirHPInput: Coil:Cooling:WaterToAirHeatPump:EquationFit = SYS 1 HEAT PUMP COOLING MODE
    **   ~~~   ** Cooling Power Consumption Curve Name = COOLPOWCURV, item not found.
    **  Fatal  ** GetSimpleWatertoAirHPInput:  Errors found getting input. Program terminates.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc [hunk 1]
```diff
@@ -3995,6 +3995,9 @@ namespace WaterToAirHeatPumpSimple {
         auto &wahp = state.dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(WhichCoil);
         if (wahp.WAHPType == WatertoAirHP::Cooling) {
             if (wahp.RatedEntAirWetbulbTemp != DataSizing::AutoSize) {
+                if (wahp.TotalCoolCapCurve == nullptr || wahp.CoolPowCurve == nullptr) {
+                    return;
+                }
```
Comment (rraustad) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:4000]: Protect calls to curves with null pointers (i.e., misspelled curve names or missing curve objects)

File: tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc [hunk 2]
```diff
@@ -568,6 +568,26 @@ TEST_F(EnergyPlusFixture, WaterToAirHeatPumpSimple_TestAirFlow)
...
+    state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).CoolPowCurve = nullptr;
+    WaterToAirHeatPumpSimple::CheckSimpleWAHPRatedCurvesOutputs(*state, state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).Name);
+
+    HPNum = 2;
+    // ensure RatedEntAirDry/WetbulbTemp is not autosize so code will test valid versus null curve pointer
+    EXPECT_NE(state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).RatedEntAirDrybulbTemp, DataSizing::AutoSize);
+    EXPECT_NE(state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).RatedEntAirWetbulbTemp, DataSizing::AutoSize);
+    state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).HeatCapCurve = nullptr;
+    state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).HeatPowCurve = nullptr;
+    WaterToAirHeatPumpSimple::CheckSimpleWAHPRatedCurvesOutputs(*state, state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(HPNum).Name);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc:590]: Check that function does not crash with null curve pointers.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc [hunk 3]
```diff
@@ -4031,7 +4016,7 @@ namespace WaterToAirHeatPumpSimple {
             }
 
         } else if (wahp.WAHPType == WatertoAirHP::Heating) {
-            if (wahp.RatedEntAirDrybulbTemp != DataSizing::AutoSize) {
+            if (wahp.RatedEntAirDrybulbTemp != DataSizing::AutoSize && wahp.HeatCapCurve != nullptr && wahp.HeatPowCurve != nullptr) {
```
Comment (rraustad) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:4019]: Issue correction is here on these 3 lines above in function CheckSimpleWAHPRatedCurvesOutputs

File: src/EnergyPlus/WaterToAirHeatPump.cc [hunk 4]
```diff
@@ -93,8 +92,6 @@ namespace WaterToAirHeatPump {
     // Jin, H. 2002. Parameter Estimation Based Models of Water Source Heat Pumps. Phd Thesis.
     // Oklahoma State University.
 
-    using namespace DataLoopNode;
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterToAirHeatPump.cc:96]: Getting rid of using...yes.

File: src/EnergyPlus/WaterToAirHeatPump.cc [hunk 5]
```diff
@@ -185,21 +181,13 @@ namespace WaterToAirHeatPump {
...
 
         // METHODOLOGY EMPLOYED:
         // Uses "Get" routines to read in data.
 
-        // Using/Aliasing
-        using namespace NodeInputManager;
-        using BranchNodeConnections::TestCompSet;
-        using GlobalNames::VerifyUniqueCoilName;
-        using PlantUtilities::RegisterPlantCompDesignFlow;
-        using namespace OutputReportPredefined;
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterToAirHeatPump.cc:201]: Getting rid of using...yes.

File: src/EnergyPlus/WaterToAirHeatPump.cc [hunk 6]
```diff
@@ -997,41 +985,17 @@ namespace WaterToAirHeatPump {
...
-        // DERIVED TYPE DEFINITIONS
-        // na
-
-        // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
-        int AirInletNode;   // air inlet node number
-        int WaterInletNode; // water inlet node number
-        int PlantOutletNode;
-        Real64 rho; // local fluid density
-        Real64 Cp;  // local fluid specific heat
-        bool errFlag;
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterToAirHeatPump.cc:1034]: Localized variables...yes.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc [hunk 7]
```diff
@@ -1403,7 +1392,7 @@ namespace WaterToAirHeatPumpSimple {
                     "Design Size Rated Air Flow Rate [m3/s]",
                     RatedAirVolFlowRateDes);
             } else {
-                if (simpleWatertoAirHP.RatedAirVolFlowRate > 0.0 && RatedAirVolFlowRateDes > 0.0 && !HardSizeNoDesRun) {
+                if (simpleWatertoAirHP.RatedAirVolFlowRate > 0.0 && RatedAirVolFlowRateDes > 0.0) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:1395]: I see, this is already inside the `!HardSizeNoDesRun` if condition, so no need to extra check it.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:4019]: Got it.  The function will be fine skipping this part, because it doesn't need to check the curves that don't exist.

File: tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc (hunk 2 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc:590]: Excellent.

**Review by Myoldmopar — APPROVED** [review]
This looks great to me, I'm happy to get this tested and merged.

**Comment by Myoldmopar** [comment]
This is good, thanks @rraustad, merging.
