### PR TITLE
Minimal fix for VS Furnace Flow Rate when Fan is Off

### LINKED ISSUE #9919: Variable speed furnace systems set inlet mass flow when fan is off which can cause max iterations and incorrect reporting
Issue overview
--------------
Variable speed furnaces ignore the fan availability status and set the furnace inlet node mass flow rate (to something >0) when it should be zero. Because some furnace/unitary systems set the air mass flow rate for the system using the inlet node mass flow rate, this can result in max iteration warnings and/or preventing OA-related output variables from resetting to zero.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v23.1.0
 - Noticed this while working on #8802

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles\9919 9919-VSHeatPumpWaterToAirWithRHControl-Sys1OffAfterNoon.idf (Miami FL weather)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #9919
 - `Furnaces::SetAverageAirFlow` sets the inlet node mass flow rate to zero if the [furnace schedule or fan schedule is zero, or if the availability manager has set `TurnFansOff`](https://github.com/NREL/EnergyPlus/blob/d642102ef1e1a084b175b4ddb261cf8bd1afafa4/src/EnergyPlus/Furnaces.cc#L10212-L10214). This is all well and good.
 - `Furnaces::SetVSHPAirFlow` has a [similar check](https://github.com/NREL/EnergyPlus/blob/d642102ef1e1a084b175b4ddb261cf8bd1afafa4/src/EnergyPlus/Furnaces.cc#L12509-L12520) but only looks at the furnace schedule, not the fan schedule or the availability manager signal. This creates a mismatch between the furnace inlet and outlet mass flow rates after the fan is simulated (which will set outlet mass flow to zero if the fan is off).
 - This fix adds the other conditions to `Furnaces::SetVSHPAirFlow`, instead of changing from inlet mass flow to outlet mass flow in various place as in https://github.com/NREL/EnergyPlus/pull/9897/commits/ec6bb267a67b00340f896b807bd1880540dd1927 and https://github.com/NREL/EnergyPlus/pull/9897/commits/a7cc94a1ee841cb00a306fa79e2bbca06686533f
 - This fixes OA reporting issues, and some max iteration issues in the defect file, but not all of the max iteration issues. That's still a mystery.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/Furnaces.cc [hunk 1]
```diff
@@ -12506,7 +12506,8 @@ namespace Furnaces {
             }
         }
 
-        if (GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).SchedPtr) == 0.0) {
+        if ((GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).SchedPtr) == 0.0) || state.dataHVACGlobal->TurnFansOff ||
+            (GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).FanAvailSchedPtr) == 0.0 && !state.dataHVACGlobal->TurnFansOn)) {
```
Comment (rraustad) [inline src/EnergyPlus/Furnaces.cc:12510]: Wouldn't the TurnFansOff flag turn off constant fan mode? I'm pretty sure if the fan avail schedule value is > 0, these flags don't apply. I haven't thought about these flags in some time and could easily be wrong but I think you want?

    if ((GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).SchedPtr) == 0.0) || 
        (GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).FanAvailSchedPtr) == 0.0 &&
            state.dataHVACGlobal->TurnFansOff && !state.dataHVACGlobal->TurnFansOn)) {

Comment (mjwitte) [reply src/EnergyPlus/Furnaces.cc:12510]: My understanding is if `TurnFansOff` is true, then the fan should be off, no matter what the schedule says. Likewise, if `TurnFansOn` is true, then the fan should be on, no matter what the schedule says. That's how I read the code in Fans.cc [here](https://github.com/NREL/EnergyPlus/blob/d642102ef1e1a084b175b4ddb261cf8bd1afafa4/src/EnergyPlus/Fans.cc#L183-L187) and [here](https://github.com/NREL/EnergyPlus/blob/d642102ef1e1a084b175b4ddb261cf8bd1afafa4/src/EnergyPlus/Fans.cc#L1708-L1709) for simple fan, and similar code for variable flow and onoff.

**Comment by mjwitte** [comment]
Defect file 9919-VSHeatPumpWaterToAirWithRHControl-Sys1OffAfterNoon improvements. 
Develop on left, this branch on right.

Fewer max iteration warnings.
image

image

When system availability manager is off after 12pm, OA-related outputs are now zero as they should be.
image

File: tst/EnergyPlus/unit/Furnaces.unit.cc [hunk 2]
```diff
@@ -188,6 +188,18 @@ TEST_F(EnergyPlusFixture, SetVSHPAirFlowTest_VSFurnaceFlowTest)
     EXPECT_DOUBLE_EQ(1.0, OnOffAirFlowRatio);
     EXPECT_DOUBLE_EQ(1.0, state->dataLoopNodes->Node(state->dataFurnaces->Furnace(FurnaceNum).FurnaceInletNodeNum).MassFlowRate);
 
+    // Test availability manager signal
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/Furnaces.unit.cc:191]: This is the new unit test section for VS furnaces.

File: tst/EnergyPlus/unit/Furnaces.unit.cc [hunk 3]
```diff
@@ -1192,6 +1204,15 @@ TEST_F(EnergyPlusFixture, UnitaryHeatPumpAirToAir_MaxSuppAirTempTest)
     EXPECT_FALSE(state->dataFurnaces->CoolingLoad);
     // check if the air-to-air heat pump outlet temperature is capped at 45.0C
     EXPECT_NEAR(45.0, state->dataLoopNodes->Node(state->dataFurnaces->Furnace(1).FurnaceOutletNodeNum).Temp, 0.000001);
+    EXPECT_NEAR(0.3326, state->dataLoopNodes->Node(state->dataFurnaces->Furnace(1).FurnaceOutletNodeNum).MassFlowRate, 0.0001);
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/Furnaces.unit.cc:1207]: This new test section actually passes without any code changes, because it's not a VS furnace. But leaving it in anyway.

**Review by mjwitte — COMMENTED** [review]
Tiny code walkthru.

One-line change in SetVSHPAirFlow, see existing comments.

File: src/EnergyPlus/Furnaces.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/Furnaces.cc:12510]: That certainly looks like the logic used. I still question whether a constant fan can be turned off by an avail manager. The outdoor air unit looks like an outlier.

// turn on logic

    if ((GetCurrentScheduleValue(state, Fan(FanNum).AvailSchedPtrNum) > 0.0 || state.dataFans->LocalTurnFansOn) &&
        !state.dataFans->LocalTurnFansOff && MassFlow > 0.0) {

    if (((GetCurrentScheduleValue(state, FanCoil(FanCoilNum).SchedPtr) > 0.0 && GetCurrentScheduleValue(state, FanCoil(FanCoilNum).fanAvailSchIndex) > 0.0) ||
         state.dataHVACGlobal->ZoneCompTurnFansOn) && !state.dataHVACGlobal->ZoneCompTurnFansOff) {

    if (OpMode == ContFanCycCoil && GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).SchedPtr) > 0.0 &&
        ((GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).FanAvailSchedPtr) > 0.0 || state.dataHVACGlobal->TurnFansOn) &&
         !state.dataHVACGlobal->TurnFansOff)) {

    // IF the furnace is scheduled on or nightime cycle overrides fan schedule. Uses same logic as fan.
    if (GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).SchedPtr) > 0.0 &&
        ((GetCurrentScheduleValue(state, state.dataFurnaces->Furnace(FurnaceNum).FanAvailSchedPtr) > 0.0 || state.dataHVACGlobal->TurnFansOn) &&
         !state.dataHVACGlobal->TurnFansOff)) {


    // set the mass flow rates from the input volume flow rates
    if (OAFrac > 0.0 || (ZoneCompTurnFansOn && !ZoneCompTurnFansOff)) { // fan is available
        OutAirUnit(OAUnitNum).OutAirMassFlow = RhoAir * OAFrac * OutAirUnit(OAUnitNum).OutAirVolFlow;
    } else {
        OutAirUnit(OAUnitNum).OutAirMassFlow = 0.0;
    }

    // if the terminal unit and fan are scheduled on then set flow rate
    if (GetCurrentScheduleValue(state, state.dataHVACVarRefFlow->VRFTU(VRFTUNum).SchedPtr) > 0.0 &&
        (GetCurrentScheduleValue(state, state.dataHVACVarRefFlow->VRFTU(VRFTUNum).FanAvailSchedPtr) > 0.0 ||
         state.dataHVACGlobal->ZoneCompTurnFansOn) &&
        !state.dataHVACGlobal->ZoneCompTurnFansOff) {

    if (ScheduleManager::GetCurrentScheduleValue(state, this->m_SysAvailSchedPtr) > 0.0 && ((FanOn || turnFansOn) && !turnFansOff)) { // UnitarySystem


// turn off logic

    if (GetCurrentScheduleValue(state, state.dataPowerInductionUnits->PIU(PIUNum).SchedPtr) <= 0.0) PriOn = false;
    if ((GetCurrentScheduleValue(state, state.dataPowerInductionUnits->PIU(PIUNum).FanAvailSchedPtr) <= 0.0 || PIUTurnFansOff) && !PIUTurnFansOn)
        UnitOn = false;

    if ((std::abs(state.dataUnitVentilators->QZnReq) < DataHVACGlobals::SmallLoad) ||
        (state.dataZoneEnergyDemand->CurDeadBandOrSetback(ZoneNum)) ||
        (ScheduleManager::GetCurrentScheduleValue(state, unitVent.SchedPtr) <= 0) ||
        ((ScheduleManager::GetCurrentScheduleValue(state, unitVent.FanAvailSchedPtr) <= 0 && !ZoneCompTurnFansOn) || ZoneCompTurnFansOff)) {
        // Unit is off or has no load upon it; set the flow rates to zero and then

File: tst/EnergyPlus/unit/Furnaces.unit.cc (hunk 3 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/Furnaces.unit.cc:1207]: I assume this is the fan/furnace design flow rate. In the future (no change requested) I would rather see something that would change with future updates. For example` EXPECT_NEAR(state->dataFurnaces->Furnace(1).DesignMassFlowRate, ,,,` (or DesignMassFlowRate * PLR for cycling fan). Not sure if that works here or not but these high precision targets can easily change with various fixes and then the unit tests needs updating.

**Review by rraustad — APPROVED** [review]
This looks very reasonable. I am a little surprised that Furnace didn't check these flags but it's an old model. This fan control logic seems to conform to other models so whether it's right or wrong is out of scope.

**Comment by rraustad** [comment]
There is certainly a change in results and since this is a 1 line change it must be due to the avail manager.

image

**Comment by rraustad** [comment]
I checked the avail manager and as it's name suggests, turns off the fan after noon. This does happen on the first day of this sim, but on subsequent days, the fan turns off after noon? Is this something else that needs fixing?

  Schedule:Compact,
    FanAndCoilAvailSchedOffAfterNoon,    !- Name
    Fraction,                !- Schedule Type Limits Name
    Through: 12/31,           !- Field 1
    For: AllDays,            !- Field 6
    Until: 12:00,1.0,        !- Field 9
    Until: 24:00,0.0;        !- Field 11

image

**Comment by rraustad** [comment]
Actually, it does look like the air flow is shutting down at 12 PM. So this looks like it's working as intended. I just don't understand the graph I was looking at. Maybe it's an issue with the detailed time step reporting that skews the data on the figure?

image

**Comment by rraustad** [comment]
I am good with merging this. I'll just wait on @mjwitte to look at this and confirm before merging. The defect file now runs much faster.

**Comment by rraustad** [comment]
If I change the X-axis on this plot to be from the fixed branch results (this branch), the fan turns off at 12 PM each day. This is good to go.

image

**Comment by rraustad** [comment]
Unit tests run clean, the results show the fan tuning off at 12 PM, the code change conforms to other models, and the defect file runs much faster, all good. Merging this.

File: src/EnergyPlus/Furnaces.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/Furnaces.cc:12510]: I just ran into this again. The night cycle avail manager object set up is that the coils need to be available when the fans turn on. The avail manager overrides the fan avail schedule. But the coils won't turn on if they are not available. Your right that TurnFansOn overrides the fan schedule (constant or cycling fan op mode).
