### PR TITLE
Calculate a mixed air humrat for heating when no heating load exists and system humidifiers are used

### LINKED ISSUE #10924: The order of SizingPeriod:DesignDay objects in IDF affects humidification. Converting to epJSON prevents humidification.
### Issue overview

The two attached IDFs (working & non-working) are exactly the same, except for the order in which the SizingPeriod:DesignDay objects are listed. In the working IDF, the heating design day is listed first; in the non-working IDF the cooling design day is listed first. The working IDF results show humidification energy, as expected. The non-working IDF shows zero humidification energy. 

When converting either IDF to epJSON format, the results of the epJSON simulation are consistent with the non-working IDF; zero humidification energy. Even if I change the order of the SizingPeriod:DesignDay objects in the epJSON, it still shows zero humidification energy. When converting epJSON to IDF, it always puts the cooling design day first, hence humidification does not work. Simply changing the order of the design days in the IDF (which was converted from the epJSON) restores the humidification functionality, and humidification energy is shown in the results.

This is a pervasive bug which prevents epJSON-formatted input files (and IDFs converted from epJSON) from accurately modeling humidification.

[ASHRAE901_OutPatientHealthCare_STD2016_Tampa - notworking.idf.txt](https://github.com/user-attachments/files/18697147/ASHRAE901_OutPatientHealthCare_STD2016_Tampa.-.notworking.idf.txt)
[ASHRAE901_OutPatientHealthCare_STD2016_Tampa - working.idf.txt](https://github.com/user-attachments/files/18697148/ASHRAE901_OutPatientHealthCare_STD2016_Tampa.-.working.idf.txt)

### Operating System (Multiple choices)

Windows

### Operating System Version

Windows 10 Enterprise. Also reproduced on Red Hat Enterprise Linux Workstation release 6.6.

### Version of EnergyPlus

24.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[ASHRAE901_OutPatientHealthCare_STD2016_Tampa - notworking.idf.txt](https://github.com/user-attachments/files/18697190/ASHRAE901_OutPatientHealthCare_STD2016_Tampa.-.notworking.idf.txt)
[ASHRAE901_OutPatientHealthCare_STD2016_Tampa - working.idf.txt](https://github.com/user-attachments/files/18697191/ASHRAE901_OutPatientHealthCare_STD2016_Tampa.-.working.idf.txt)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------

- Fixes #10924

### Description of the purpose of this PR

System humidifier sizing changed when DesignDay order changed. This is due to no system heating loads in the simulation where the system mixed air humidity ratio winds up as the last time step in the last design day object.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
There is no difference in humidifier sizing between the Working and NotWorking defect files. However, there are still diffs in Sky Daylight Factors and Zone Sizing Heating OA conditions when no zone heating loads exist. This change attempts to correct system humidifier sizing when there are no system heating loads. Maybe there is a better way to do this/select information used for sizing (i.e., the changes in this branch)?

image

Same results with both defect files:

    Component Sizing Information, Humidifier:Steam:Electric, AHU-1 HUMIDIFIER, Design Size Nominal Capacity Volume [m3/s], 1.63341E-005          
    Component Sizing Information, Humidifier:Steam:Electric, AHU-1 HUMIDIFIER, Design Size Rated Power [W], 42350.46523

File: src/EnergyPlus/SimAirServingZones.cc [hunk 1]
```diff
@@ -6752,6 +6752,31 @@ void UpdateSysSizing(EnergyPlusData &state, Constant::CallIndicator const CallIn
...
+                        SysHeatRetHumRat = state.dataSize->SysSizing(curSimDay, AirLoopNum).SysHeatRetHumRatSeq(ts);
+                        OutAirHumRat = state.dataSize->SysSizing(curSimDay, AirLoopNum).SysHeatOutHumRatSeq(ts);
+                        SysHeatMixHumRat = OutAirHumRat * OutAirFrac + SysHeatRetHumRat * (1.0 - OutAirFrac);
+                        if (OutAirHumRat < SysHeatMixHumRat) {
+                            state.dataSize->CalcSysSizing(AirLoopNum).HeatMixHumRat = OutAirHumRat;
+                        }
+                    }
+                }
+            }
+        }
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:6779]: The system humidifier uses supply air humrat (Sizing:System input) - mixed air humrat (calculated) as the sizing deltaW and was selecting the last time step on the last design day to choose mixed air humrat, So, if there was no system heating load, I chose to use the minimum OA humidity ratio as a surrogate for mixed air humrat so that the humidifier will size. There is no system heating load therefore no design day and time of peak so there is really no good way to choose the humidifier entering air humidity ratio. This is a very rare corner case.

Comment (mitchute) [reply src/EnergyPlus/SimAirServingZones.cc:6779]: Thanks @rraustad. This looks like an appropriate assumption for this condition.

**Review by mitchute — APPROVED** [review]
