### PR TITLE
Make EnergyPlus-generated RVI and MVI use non-quoted paths

### LINKED ISSUE #8840: ReadVarsESO Fails when RVI and MVI missing
Issue overview
--------------
EnergyPlus' calls to ReadVarsESO fail when user-defined rvi and mvi files are not present because the energyplus-generated rvi and mvi files contain quoted paths; however, ReadVars is expecting a non-quoted path.

The code here

https://github.com/NREL/EnergyPlus/blob/82e97f1c21b8e7dd30a4278a93ad22bd284a7eb7/src/EnergyPlus/CommandLineInterface.cc#L886-L887

and here

https://github.com/NREL/EnergyPlus/blob/82e97f1c21b8e7dd30a4278a93ad22bd284a7eb7/src/EnergyPlus/CommandLineInterface.cc#L897-L898

should be using ```.string()``` for a non-quoted path. https://en.cppreference.com/w/cpp/filesystem/path/string

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac, 10.15.7)
 - Version of EnergyPlus (V9.6.0 82e97f1c21)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
Fixes #8840

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by jmarrec — APPROVED** [review]

File: src/EnergyPlus/CommandLineInterface.cc [hunk 1]
```diff
@@ -883,8 +883,8 @@ namespace CommandLineInterface {
             if (!ofs.good()) {
                 ShowFatalError(state, "EnergyPlus: Could not open file \"" + RVIfile.string() + "\" for output (write).");
             } else {
-                ofs << state.files.eso.filePath << '\n';
-                ofs << state.files.csv.filePath << '\n';
+                ofs << state.files.eso.filePath.string() << '\n';
```
Comment (jmarrec) [inline src/EnergyPlus/CommandLineInterface.cc:886]: yes. ostream operator<< with a filesystem path will double quote the path. Moving to the string overload alleviates the problem.

**Review by jmarrec — APPROVED** [review]

**Comment by mitchute** [comment]
Thanks for the review, @jmarrec! Merging.

**Comment by mitchute** [comment]
FYI @Myoldmopar @jmarrec 

```
  ================ RUNNING XELATEX THE FIRST TIME =====================
  xelatex: security risk: running with elevated privileges
  This is XeTeX, Version 3.141592653-2.6-0.999993 (MiKTeX 21.6.28)
  initexmf: security risk: running with elevated privileges
  
  Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:
  
    MiKTeX could not remove the file 'C:\Users\runneradmin\AppData\Local\MiKTeX\miktex\data\le\df2c24cb21984fa85003c1ecc818ff83.fndb-5'.
  
  Remedy:
  
    Close running MiKTeX programs and try again.
```

I don't think it's related to this PR. Also, have you tried turning GHA off and on again?
