### PR TITLE
EnergyPlus crashes with Optimum Start availability managers used for VRF (or for any zone equipment not connected to an air loop)

### LINKED ISSUE #11446: EnergyPlus Crashes with Optimum Start for VRF
### Issue overview

User posted a file that does crash when OptimumStart availability manager crashes when used with VRT terminal unit.

### Operating System (Multiple choices)

Windows

### Operating System Version

26.1

### Version of EnergyPlus

26.1

### Unmethours link or helpdesk ticket number

https://unmethours.com/question/103118/energyplus-crashes-with-optimum-start-for-vrf/

### Defect file

[UnmetHours-OptimumStart-VariableRefrigerantFlow_5Zone_rev.idf.txt](https://github.com/user-attachments/files/25724665/UnmetHours-OptimumStart-VariableRefrigerantFlow_5Zone_rev.idf.txt)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------

- Fixes #11446

### Description of the purpose of this PR

Zone optimum start availability managers expected to find an air loop attached to the zone.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SystemAvailabilityManager.cc [hunk 1]
```diff
@@ -2436,17 +2439,23 @@ namespace Avail {
             }
 
             // Pass the start time to ZoneTempPredictorCorrector
-            for (int counter = 1; counter <= state.dataAirLoop->AirToZoneNodeInfo(PriAirSysNum).NumZonesCooled; ++counter) {
-                int actZoneNum = state.dataAirLoop->AirToZoneNodeInfo(PriAirSysNum).CoolCtrlZoneNums(counter);
-                auto &optStart = state.dataAvail->OptStart(actZoneNum);
-                optStart.OccStartTime = FanStartTime;
-                optStart.ActualZoneNum = actZoneNum;
-            }
```
Comment (rraustad) [inline src/EnergyPlus/SystemAvailabilityManager.cc:2457]: Crash occurred here. The code assumed the zone index was found in the air loop array AirToZoneNodeInfo which is allocated to number of primary air systems. When no primary air systems exist or the zone with the availability manager is not connected to an air system the avail manager crashes, cannot find the zone, or does not work correctly.

    state.dataAirLoop->AirToZoneNodeInfo.allocate(NumPrimaryAirSys);

File: src/EnergyPlus/SystemAvailabilityManager.cc [hunk 2]
```diff
@@ -1670,6 +1671,14 @@ namespace Avail {
...
                 e.isSimulated = false;
             }
+            if (!allocated(state.dataAvail->OptStart)) {
+                state.dataAvail->OptStart.allocate(state.dataGlobal->NumOfZones);
+            }
+
+            // OptStartFlag needs to be reset each timestep to not stay set to true post-occupancy
+            for (auto &optStart : state.dataAvail->OptStart) {
+                optStart.OptStartFlag = false;
+            }
```
Comment (rraustad) [inline src/EnergyPlus/SystemAvailabilityManager.cc:1689]: This was moved to Init because it was called for zone optimum start availability managers AFTER it was called for system availability managers and erased what the system availability manager did. Also, it broke the unit test after I updated it which is how I knew it needed to be moved to init.

File: tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc [hunk 3]
```diff
@@ -343,14 +376,18 @@ TEST_F(EnergyPlusFixture, SysAvailManager_OptimumStart)
...
+    EXPECT_TRUE(state->dataAvail->OptStart(7).OptStartFlag); // ZoneHVAC avail manager set to cycle on for Zone 7
 
     // #8013 - Check that the optimum start is available during the correct times when using a partial hour fan start
     state->dataGlobal->CurrentTime = 5.00; // set the current time to 5:00 AM, before max optimum start time
     Avail::ManageSystemAvailability(*state);
     EXPECT_FALSE(state->dataAvail->OptStart(6).OptStartFlag); // avail manager should be set to no action for Zone 6
+    EXPECT_FALSE(state->dataAvail->OptStart(7).OptStartFlag); // ZoneHVAC avail manager set to no action for Zone 7
     state->dataGlobal->CurrentTime = 6.50;                    // set the current time to 6:30 AM when occupancy begins
     Avail::ManageSystemAvailability(*state);
     EXPECT_TRUE(state->dataAvail->OptStart(6).OptStartFlag); // avail manager should be set to cycle on for Zone 6
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc:389]: This line of the unit test was failing on this branch, i.e., line 389 OptStartFlag = false, so I knew there was something wrong with setting these flags. Moving the initialization of the OptStartFlag corrected this line of the unit test. See line 2380 of SystemAvailabilityManager.cc.

File: tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc [hunk 4]
```diff
@@ -124,6 +124,22 @@ TEST_F(EnergyPlusFixture, SysAvailManager_OptimumStart)
...
+        "   ,                        !- Zone List Name",
+        "   6,                       !- Maximum Value for Optimum Start Time {hr}",
+        "   ConstantStartTime,       !- Control Algorithm",
+        "   3,                       !- Constant Temperature Gradient during Cooling {deltaC/hr}",
+        "   3,                       !- Constant Temperature Gradient during Heating {deltaC/hr}",
+        "   3,                       !- Initial Temperature Gradient during Cooling {deltaC/hr}",
+        "   3,                       !- Initial Temperature Gradient during Heating {deltaC/hr}",
+        "   1.5,                     !- Constant Start Time {hr}",
+        "   2;                       !- Number of Previous Days {days}",
+
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc:142]: This unit test adds an OptimumStart availability manager for zone equipment for a zone that is not connected to an air loop. It also mixes air loop and zone equipment availability managers which revealed another issue with flag initialization.

**Comment by rraustad** [comment]
After the crash was corrected (develop figures) the optimum start availability manager did not work correctly and was subsequently fixed with more code changes.

image

File: src/EnergyPlus/SystemAvailabilityManager.cc [hunk 5]
```diff
@@ -2373,14 +2384,6 @@ namespace Avail {
...
             DayValues.allocate(state.dataGlobal->TimeStepsInHour, Constant::iHoursInDay);
             DayValuesTmr.allocate(state.dataGlobal->TimeStepsInHour, Constant::iHoursInDay);
-            if (!allocated(state.dataAvail->OptStart)) {
-                state.dataAvail->OptStart.allocate(state.dataGlobal->NumOfZones);
-            }
-
-            // OptStartFlag needs to be reset each timestep to not stay set to true post-occupancy
-            for (auto &optStart : state.dataAvail->OptStart) {
-                optStart.OptStartFlag = false;
-            }
```
Comment (rraustad) [inline src/EnergyPlus/SystemAvailabilityManager.cc:2396]: Moved to init.

File: src/EnergyPlus/SystemAvailabilityManager.cc [hunk 6]
```diff
@@ -163,7 +163,7 @@ namespace Avail {
         int ZoneEquipType;              // Type of ZoneHVAC:* component
         int CompNum;                    // Index of ZoneHVAC:* component
         int ZoneCompAvailMgrNum;        // Index of availability manager associated with the ZoneHVAC:* component
-        int constexpr DummyArgument(1); // This variable is used when SimSysAvailManager is called for a ZoneHVAC:* component
+        int constexpr DummyArgument(0); // This variable is used when SimSysAvailManager is called for a ZoneHVAC:* component
```
Comment (rraustad) [inline src/EnergyPlus/SystemAvailabilityManager.cc:166]: This is a dummy argument for the PriAirSysNum argument when calling SimSysAvailManager for zone availability managers. It was arbitrarily set to 1 to avoid a crash. I set it to 0 to be explicit that an air system was not associated with a zone availability manager.

File: tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc [hunk 7]
```diff
@@ -343,14 +376,18 @@ TEST_F(EnergyPlusFixture, SysAvailManager_OptimumStart)
     EXPECT_EQ(1.5, state->dataAvail->OptimumStartData(1).NumHoursBeforeOccupancy);                  // 1.5 hours = 3C from SP divided by 2C/hour
 
     EXPECT_EQ((int)Avail::Status::CycleOn, (int)state->dataAvail->OptimumStartData(2).availStatus); // avail manager should be set at 6 AM
+    EXPECT_EQ((int)Avail::Status::CycleOn, (int)state->dataAvail->OptimumStartData(4).availStatus); // ZoneHVAC avail manager set at 6 AM
+    EXPECT_TRUE(state->dataAvail->OptStart(7).OptStartFlag); // ZoneHVAC avail manager set to cycle on for Zone 7
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc:380]: Copied unit test to develop and fails here.

**Comment by rraustad** [comment]
Updated example file fails in develop with same crash. Passes in this branch and shows correct operation of optimum start avail manager. Zone 1 fan is set to operate from 7 - 18 and optimum start avail manager starts fan at 5 AM. Diffs are expected for this file.

    Schedule:Compact,
      Zone1FanSched,           !- Name
      Fraction,                !- Schedule Type Limits Name
      Through: 12/31,          !- Field 1
      For: AllDays,            !- Field 2
      Until: 7:00, 0.0,        !- Field 3
      Until: 18:00, 1.0,       !- Field 4
      Until: 24:00,0.0;        !- Field 5

image

File: tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc (hunk 7 above)
Comment (mitchute) [reply tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc:380]: Confirmed

File: src/EnergyPlus/SystemAvailabilityManager.cc [hunk 8]
```diff
@@ -272,6 +272,7 @@ namespace Avail {
                                                          zcam.availManagers(ZoneCompAvailMgrNum).Num,
                                                          DummyArgument,
                                                          previousAvailStatus,
+                                                         zcam.ZoneNum,
```
Comment (mitchute) [inline src/EnergyPlus/SystemAvailabilityManager.cc:275]: It makes good sense to pass this on through rather than what it was doing before to figure it out.

**Review by mitchute — APPROVED** [review]
I confirmed the test IDF crashes with develop and run successfully here. I didn't cross check your plots, but I trust you on those.

**Comment by mitchute** [comment]
All good here. Merging.
