### PR TITLE
Fix zone multipliers for OA proportional control and design load per area reporting

### LINKED ISSUE #10799: Incorrect accounting for zone multipliers in the Outdoor Air Details report
Issue overview
--------------
When zone multipliers are used with zone multipliers, incorrect values show up in the ```Mechanical Ventilation Parameters by Zone``` table in the ```Outdoor Air Details``` Report. This may only be occurring for some, not all system types.

In this example model [DOAS_WSHP_multipliers.zip](https://github.com/user-attachments/files/17481569/DOAS_WSHP_multipliers.zip), ```CORE_MID ZN``` (and other ```MID``` zones) have a zone multiplier of 10. ```CORE_MID ZN``` has the same load assumptions as ```CORE_BOTTOM ZN``` and ```CORE_TOP ZN```. ```CORE_BOTTOM ZN``` and ```CORE_TOP ZN``` have a zone multiplier of 1.

image

```Average Number of Occupants```,```Nominal Number of Occupants```,```Zone Volume [m3]```, and ```Zone Area``` are the same for all ```CORE``` zones. ```Design Zone Outdoor Airflow - Voz [m3/s]``` and ```Minimum Dynamic Target Ventilation - Voz-dyn-min [m3/s]``` are different, apparently already accounting for the zone multiplier. In the ```Total Facility``` line, the ```MID``` zone multipliers are applied again to calculate the total, giving incorrect totals for ```Design Zone Outdoor Airflow - Voz [m3/s]``` and ```Minimum Dynamic Target Ventilation - Voz-dyn-min [m3/s]```. The code [here](https://github.com/NREL/EnergyPlus/blob/ec7398adcfbd2ba6bc71e72b57e3febb6cd99708/src/EnergyPlus/OutputReportTabular.cc#L6327) fails to account for the zone multipliers already being included in the total.

### Details
 - EnergyPlus 24.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([defect file here](https://github.com/user-attachments/files/17481569/DOAS_WSHP_multipliers.zip)).
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #10799 
    - Add Zone Multiplier column to Outdoor Air Details report "by zone" tables.
    - Fix "User Design Load per Area" in HVAC Sizing Summary table (load was multiplied but area was not).
    - Fix floor area and number of occupants in eio output for "Zone Sizing Information" (load was multiplied but area and occupants were not).
- Fixes double-counting of zone mulipliers for OA control types ProportionalControlBasedOnDesignOccupancy and ProportionalControlBasedOnOccupancySchedule.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
@mjwitte I don't see anything in these changes to comment on. Looks good so far.

**Comment by mjwitte** [comment]
Using example file RefBldgSmallOfficeNew2004_Chicago with 10x multipliers. Here is a sample of the new Outdoor Air Details report with new Zone Multiplier Column.
image
image

**Comment by mjwitte** [comment]
Using example file RefBldgSmallOfficeNew2004_Chicago with 1x vs 10x multipliers. Here's an example of the corrected "User Design Load per Area" with multipliers.

1x output (with develop and this branch):
image

10x output with develop (incorrect):
image

10x output with this branch (correct):
image

**Comment by mjwitte** [comment]
All files with multipliers show eio diffs like this, e.g. 5ZoneSwimmingPoolZoneMultipliers.
image

A bit hard to see, but at the far right, for the first zone "Floor Area" and "# Occupants" were
`99.16000, 11.00000` and are now `297.48000, 33.00000`.

**Comment by mjwitte** [comment]
Zone multipliers were being double-counted for the OA proportional control options. Using example file DOAToUnitarySystem, here are the 1x and 10x outdoor air details with develop, then with this branch.

1x-develop
image

10x-develop - OA quantities are way more than 10x
image

10x-this branch - now OA quantities are 10x
image

File: src/EnergyPlus/DataSizing.cc [hunk 1]
```diff
@@ -1183,9 +1183,9 @@ OARequirementsData::calcOAFlowRate(EnergyPlusData &state,
     case DataSizing::OAFlowCalcMethod::PCDesOcc: {
         ZoneOAPeople = 0.0;
         if (this->OAFlowMethod != DataSizing::OAFlowCalcMethod::PCDesOcc) {
-            ZoneOAPeople = curNumOccupants * thisZone.Multiplier * thisZone.ListMultiplier * this->OAFlowPerPerson;
+            ZoneOAPeople = curNumOccupants * this->OAFlowPerPerson;
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:1186]: Remove multipliers in this case block, because multipliers are applied at the end for all cases.

File: src/EnergyPlus/DataSizing.cc [hunk 2]
```diff
@@ -1370,7 +1367,6 @@ OARequirementsData::calcOAFlowRate(EnergyPlusData &state,
     }
 
     // Apply zone multipliers and zone list multipliers
-    // TODO MJW: this looks like it's double-counting the multipliers - it *is* double counting for methods PCOccSch and PCDesOcc
     OAVolumeFlowRate *= thisZone.Multiplier * thisZone.ListMultiplier;
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:1370]: Multipliers are applied here for all OA control types.

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 3]
```diff
@@ -775,8 +776,10 @@ namespace OutputReportPredefined {
         s->pdchZnClPkOAHum = newPreDefColumn(state, s->pdstZoneClSize, "Outdoor Humidity Ratio at Peak Load [kgWater/kgDryAir]");
         s->pdchZnClPkOAMinFlow = newPreDefColumn(state, s->pdstZoneClSize, "Minimum Outdoor Air Flow Rate [m3/s]");
         s->pdchZnClPkDOASHeatGain = newPreDefColumn(state, s->pdstZoneClSize, "Heat Gain Rate from DOAS [W]");
-        addFootNoteSubTable(
-            state, s->pdstZoneClSize, "The Design Load is the zone sensible load only. It does not include any system effects or ventilation loads.");
+        addFootNoteSubTable(state,
+                            s->pdstZoneClSize,
+                            "The Design Load is the zone sensible load only. It does not include any system effects or ventilation loads. Values "
+                            "shown include multipliers.");
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportPredefined.cc:782]: Extend the footnote for HVAC Sizing Summary tables "Value shown include multipliers."

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 4]
```diff
@@ -1193,6 +1199,7 @@ namespace OutputReportPredefined {
         s->pdchOaMvZoneArea = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Zone Area [m2]");
         s->pdchOaMvDesZnOa = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Design Zone Outdoor Airflow - Voz [m3/s]");
         s->pdchOaMvMinDynTrgVent = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Minimum Dynamic Target Ventilation - Voz-dyn-min [m3/s]");
+        s->pdchOaMvZoneMult = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Zone Multiplier");
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportPredefined.cc:1202]: New multiplier column for Outdoor Air Details "by Zone" subtables.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 5]
```diff
@@ -6372,14 +6372,16 @@ void FillRemainingPredefinedEntries(EnergyPlusData &state)
...
-                        totalAverageOccupants += avgOcc * zoneMult;
-                    }
+                if ((thisZone.isNominalOccupied) && (thisZonePreDefRep.NumOccAccumTime > 0)) {
+                    Real64 const avgOcc = thisZonePreDefRep.NumOccAccum / thisZonePreDefRep.NumOccAccumTime;
+                    PreDefTableEntry(state, state.dataOutRptPredefined->pdchOaoAvgNumOcc1, thisZone.Name, avgOcc);
+                    PreDefTableEntry(state, state.dataOutRptPredefined->pdchOaoAvgNumOcc2, thisZone.Name, avgOcc);
+                    PreDefTableEntry(state, state.dataOutRptPredefined->pdchOaMvAvgNumOcc, thisZone.Name, avgOcc);
+                    totalAverageOccupants += avgOcc * zoneMult;
+                } else {
+                    PreDefTableEntry(state, state.dataOutRptPredefined->pdchOaoAvgNumOcc1, thisZone.Name, 0.0);
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc:6382]: Fille some table values with zeros for unoccupied zones (previously the cells were left blank).

File: src/EnergyPlus/SizingManager.cc [hunk 6]
```diff
@@ -575,12 +575,15 @@ void ManageSizing(EnergyPlusData &state)
...
+                auto const &thisZone = state.dataHeatBal->Zone(state.dataHeatBal->space(spaceNum).zoneNum);
+                Real64 const mult = thisZone.Multiplier * thisZone.ListMultiplier;
                 reportZoneSizing(state,
                                  state.dataHeatBal->space(spaceNum),
                                  state.dataSize->FinalSpaceSizing(spaceNum),
                                  state.dataSize->CalcFinalSpaceSizing(spaceNum),
                                  state.dataSize->CalcSpaceSizing,
                                  state.dataSize->SpaceSizing,
+                                 mult,
                                  isSpace);
```
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:587]: Pass new parameter for multiplier to `reportZoneSizing`.

File: src/EnergyPlus/SizingManager.cc [hunk 7]
```diff
@@ -4208,17 +4215,19 @@ void reportZoneSizing(EnergyPlusData &state,
                             zsCalcFinalSizing.CoolPeakDateHrMin,
                             TempAtPeak,
                             HumRatAtPeak,
-                            zoneOrSpace.FloorArea,
-                            zoneOrSpace.TotOccupants,
+                            zoneOrSpace.FloorArea * zoneMult,
+                            zoneOrSpace.TotOccupants * zoneMult,
```
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:4219]: Apply the multiplier to `FloorArea` and `TotOccupants`.

File: src/EnergyPlus/SizingManager.cc [hunk 8]
```diff
@@ -4208,17 +4215,19 @@ void reportZoneSizing(EnergyPlusData &state,
...
         OutputReportPredefined::PreDefTableEntry(
             state, shift + state.dataOutRptPredefined->pdchZnClCalcDesLd, curName, zsCalcFinalSizing.DesCoolLoad);
         OutputReportPredefined::PreDefTableEntry(state, shift + state.dataOutRptPredefined->pdchZnClUserDesLd, curName, zsFinalSizing.DesCoolLoad);
         if (zoneOrSpace.FloorArea != 0.0) {
-            OutputReportPredefined::PreDefTableEntry(
-                state, shift + state.dataOutRptPredefined->pdchZnClUserDesLdPerArea, curName, zsFinalSizing.DesCoolLoad / zoneOrSpace.FloorArea);
+            OutputReportPredefined::PreDefTableEntry(state,
+                                                     shift + state.dataOutRptPredefined->pdchZnClUserDesLdPerArea,
+                                                     curName,
+                                                     zsFinalSizing.DesCoolLoad / (zoneOrSpace.FloorArea * zoneMult));
```
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:4230]: Also need to apply the multiplier here for "User Design Load per Area".

File: src/Transition/OutputRulesFiles/OutputChanges25-1-0-to-25-2-0.md [hunk 9]
```diff
@@ -85,12 +85,6 @@ New table output showing fraction of full load fan power vs flow fraction.
 
 See Pull Request [#11153](https://github.com/NREL/EnergyPlus/pull/11153).
 
-### EIO and HTML Table Output: Initialization Summary
```
Comment (mjwitte) [inline src/Transition/OutputRulesFiles/OutputChanges25-1-0-to-25-2-0.md:88]: OutputChanges was a bit messed up, so it's cleaned up here, along with a new section at the end for this PR.

**Review by mjwitte — COMMENTED** [review]
Code walkthru

File: src/Transition/OutputRulesFiles/OutputChanges25-1-0-to-25-2-0.md [hunk 10]
```diff
@@ -309,3 +310,15 @@ Several new columns were added to the ElectricComponentsOfPeakDemandMonthly repo
...
+
+### Table and eio Output Changes Related to Zone Multipliers
+
+* eio "Zone Sizing Information" - The values for "Floor Area {m2}" and "# Occupants" are now reported with multipliers applied to be consistent with the other values reported for zone sizing.
+
+* Outdoor Air Details table output has a new column for "Zone Multiplier".
+
+* HVAC Sizing Summary table output values for "User Design Load per Area" have been corrected to properly account for zone multipliers.
+
+See pull request [#11259](https://github.com/NREL/EnergyPlus/pull/10259)
```
Comment (mitchute) [inline src/Transition/OutputRulesFiles/OutputChanges25-1-0-to-25-2-0.md]: @mjwitte I think this is supposed to be referencing #11259, right?

Comment (mjwitte) [reply src/Transition/OutputRulesFiles/OutputChanges25-1-0-to-25-2-0.md]: Whoops, yes.

**Review by mitchute — APPROVED** [review]
