### PR TITLE
Energy Meters Table and Increase Decimals for Air Flow (bug fixes to issues #9642 and #9589)

### LINKED ISSUE #9589: Energy Meters table output annual values do not agree with ABUPS with multiple RunPeriods
Issue overview
--------------
If there is more than one RunPeriod in the simulation, it appears that the Energy Meters table report resets and reports only the results for the final RunPeriod. See attached defect file, 5ZoneAirCooled-2RunPeriods (Jan 1-Jun 30, Jul1-Dec 31).
ABUPS, Electricity 156.4 GJ, NaturalGas 69.11 GJ
Energy Meters, Annual, Electricity:Facility 81.70 GJ, NaturalGas:Facility 28.89 GJ

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v22.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] v22.1 Defect file attached (v22.2 transition is a moving target at the moment): [5ZoneAirCooled-2RunPeriods.idf.txt](https://github.com/NREL/EnergyPlus/files/9271445/5ZoneAirCooled-2RunPeriods.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9642: Zone Component Load Summary - Increase decimals reported for Air Flow
Issue overview
--------------
The Cooling Peak Conditions table and the Heating Peak Conditions table include two air flow results: Main Fan Air Flow [m3/s] and Outside Air Flow [m3/s]. These are reported with only two decimals. However when converting to IP units (CFM) this leads to a lost of data as the stored value is rounded to two decimals. The difference in the actual flow rate can be observed for Outside Air Flow by comparing the resultant Zone Ventilation: Sensible - Instant [W] value. In the attached .osm there are two rooms: 203-Shell 2C (OFFICE) and 202-Shell 2B (OFFICE) which show the same value for Heating Peak Conditions: Outside Air Flow [m3/s] - 0.04, and different values for the Zone Ventilation which is -814.1 and and -940.9 respectively. 
Note when the report is produced in IP units the Outside Air Flow [ft3/min] show as 74.76 and 86.4 respectively, confirming that the values are in fact different. 
[idf and report.zip](https://github.com/NREL/EnergyPlus/files/9480927/idf.and.report.zip)

To resolve show at least 4 total decimals when air flow is reported as m3/s.

### Details

 - Windows 10 Pro, 21H1
 - Version of EnergyPlus 9.5
 - Run via OpenStudio Application v 1.2.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by KarenWGard**
Pull request overview
---------------------
 - Fixes #9642
 - Fixes #9589
 - Addresses 9589 by changing the calls to update and reset meters.  Previously, meters were updated on every timestep, regardless of whether the simulation was in warmup mode.  Then, on completion of warmup, all meters were reset to zero.  This meant that with multiple run periods, all accumulated data from previous run periods was wiped when `ResetAccumulationWhenWarmupComplete `was called.  The bug fix removes the function `ResetAccumulationWhenWarmupComplete` and instead does a check within `UpdateMeters` and only updates meters when the simulation is not in warmup mode.
 - Addresses 9642 by increasing the number of digits for `mainFanAirFlow` and `outsideAirFlow` in the Cooling Peak Conditions table (modified lines 16474 and 16475 in file OutputReportTabular.cc)

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by KarenWGard** [comment]
Updates related to [defect 9589](https://github.com/NREL/EnergyPlus/issues/9589)

ABUPS Before:
image

Energy meters Before:
image

Note total electricity does not match between the two reports

ABUPS After:
image

Energy Meters After:
image

ABUPS and Energy meter values now match.


Updates related to [defect 9642](https://github.com/NREL/EnergyPlus/issues/9642)

Cooling Peak Conditions Before:
image
(airflows rounded to two decimal points)

Cooling Peak Conditions:
image
(airflows rounded to four decimal points)

File: src/EnergyPlus/OutputProcessor.cc [hunk 1]
```diff
@@ -2117,6 +2119,11 @@ namespace OutputProcessor {
         // from calling program.
 
         // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
+
+        if (state.dataGlobal->WarmupFlag) {
+            return;
+        }
+
```
Comment (KarenWGard) [inline src/EnergyPlus/OutputProcessor.cc:2124]: instead of clearing the meters after warmup, this check allows us to update the meters only if when the simulation is not in warmup mode.

File: src/EnergyPlus/OutputProcessor.cc [hunk 2]
```diff
@@ -2200,77 +2207,6 @@ namespace OutputProcessor {
...
-        for (int Loop = 1; Loop <= op->NumOfIVariable; ++Loop) {
-            auto &iVar = op->IVariableTypes(Loop).VarPtr;
-            if (iVar.frequency == ReportingFrequency::Monthly || iVar.frequency == ReportingFrequency::Yearly ||
-                iVar.frequency == ReportingFrequency::Simulation) {
-                iVar.StoreValue = 0;
-                iVar.NumStored = 0;
-            }
-        }
-    }
-
```
Comment (KarenWGard) [inline src/EnergyPlus/OutputProcessor.cc:2273]: this function is no longer referenced, so I have deleted it instead of leaving a deprecated and unused function in the code.

File: src/EnergyPlus/OutputProcessor.hh [hunk 3]
```diff
@@ -655,8 +655,6 @@ namespace OutputProcessor {
 
     void UpdateMeters(EnergyPlusData &state, int TimeStamp); // Current TimeStamp (for max/min)
 
-    void ResetAccumulationWhenWarmupComplete(EnergyPlusData &state);
-
```
Comment (KarenWGard) [inline src/EnergyPlus/OutputProcessor.hh:659]: delete deprecated function

File: src/EnergyPlus/OutputReportTabular.cc [hunk 4]
```diff
@@ -16471,8 +16471,8 @@ void OutputCompLoadSummary(EnergyPlusData &state,
         if (kind == OutputType::AirLoop) {
             tableBody(1, 9) = RealToStr(curCompLoad.mixAirTemp, 2); // mixed air temperature - not for zone or facility
         }
-        tableBody(1, 10) = RealToStr(curCompLoad.mainFanAirFlow, 2);     // main fan air flow
-        tableBody(1, 11) = RealToStr(curCompLoad.outsideAirFlow, 2);     // outside air flow
+        tableBody(1, 10) = RealToStr(curCompLoad.mainFanAirFlow, 4);     // main fan air flow
+        tableBody(1, 11) = RealToStr(curCompLoad.outsideAirFlow, 4);     // outside air flow
```
Comment (KarenWGard) [inline src/EnergyPlus/OutputReportTabular.cc]: this change addresses 9642

File: src/EnergyPlus/SimulationManager.cc [hunk 5]
```diff
@@ -434,7 +434,6 @@ namespace SimulationManager {
                     }
                     static constexpr std::string_view Format_700("Environment:WarmupDays,{:3}\n");
                     print(state.files.eio, Format_700, state.dataReportFlag->NumOfWarmupDays);
-                    OutputProcessor::ResetAccumulationWhenWarmupComplete(state);
```
Comment (KarenWGard) [inline src/EnergyPlus/SimulationManager.cc:437]: no longer using ResetAccumulationWhenWarmupComplete

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 6]
```diff
@@ -5277,153 +5277,6 @@ namespace OutputProcessor {
...
-            {
-                "2,365,12,31, 0,24, 0.00,10.00,Tuesday",
-                "7,100.0",
-                "2,365,12,31, 0,24,10.00,20.00,Tuesday",
-                "7,200.0",
-                "5,365",
-                "56,300.0,100.0,12,31,24,10,200.0,12,31,24,20",
-            },
-            "\n"));
-    }
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc]: this test was for the deprecated function, so it has been removed

**Comment by rraustad** [comment]
If I run 1ZoneDataCenterCRAC_wApproachTemp, with Chicago Ohare, simulating only the sizing periods...

    SimulationControl,
    No,                      !- Do Zone Sizing Calculation
    No,                      !- Do System Sizing Calculation
    No,                      !- Do Plant Sizing Calculation
    Yes,                     !- Run Simulation for Sizing Periods
    No,                     !- Run Simulation for Weather File Run Periods
    No,                      !- Do HVAC Sizing Simulation for Sizing Periods
    1;                       !- Maximum Number of HVAC Sizing Simulation Passes

I get 0 for energy use:

image

and if I run only the weather file run periods I get:

  SimulationControl,
    No,                      !- Do Zone Sizing Calculation
    No,                      !- Do System Sizing Calculation
    No,                      !- Do Plant Sizing Calculation
    No,                     !- Run Simulation for Sizing Periods
    Yes,                     !- Run Simulation for Weather File Run Periods
    No,                      !- Do HVAC Sizing Simulation for Sizing Periods
    1;                       !- Maximum Number of HVAC Sizing Simulation Passes

image

and if I run both the sizing period and the weather file I get the same answer:

  SimulationControl,
    No,                      !- Do Zone Sizing Calculation
    No,                      !- Do System Sizing Calculation
    No,                      !- Do Plant Sizing Calculation
    Yes,                     !- Run Simulation for Sizing Periods
    Yes,                     !- Run Simulation for Weather File Run Periods
    No,                      !- Do HVAC Sizing Simulation for Sizing Periods
    1;                       !- Maximum Number of HVAC Sizing Simulation Passes

image

So the question is whether energy data should be provided for the sizing periods. If I want to run only the sizing periods to get the input file working as I desire, shouldn't the energy used during that period be reported? How do I know if the inputs provide the desired result if the energy is not reported. Yes, I can look at the Facility* reports in the output results file, but why do I need to go to that length to see results?

I think the energy data for sizing periods should be recorded. And if there are weather file runs, the sizing period data should be zero'd to then record only weather period data. If I see 0's for energy data when I run only the sizing periods, what am I to make of that result? I do understand why this change was needed, I am just questioning whether this result gives a snapshot of what simulation just occurred.

**Comment by KarenWGard** [comment]
@rraustad - yes, post-fix, the Energy Meters table reports ALL energy used in the simulation including simulations run during sizing periods.  This is consistent with the way variables are reported to output.csv.  However, this means that the EnergyMeters report will not report the exact same energy use as ABUPS if `Run Simulation For Sizing Periods` is set to `Yes`

The question is whether this is an acceptable (or desired?) outcome:

Simulation run for sizing periods only:

ABUPS
image

Energy Meters
image

Simulation run for sizing periods AND Weather File:
ABUPS
image

Energy Meters
image

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 7]
```diff
@@ -5277,18 +5278,14 @@ namespace OutputProcessor {
             "\n"));
     }
 
-    TEST_F(EnergyPlusFixture, OutputProcessor_ResetAccumulationWhenWarmupComplete)
+    TEST_F(EnergyPlusFixture, OutputProcessor_UpdateMeters)
     {
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5282]: `OutputProcessor_ResetAccumulationWhenWarmupComplete `is deprecated, replace with a test for `UpdateMeters`, which did not previously have a test.  This test was adapated from `OutputProcessor_GenOutputVariablesAuditReport`, which calls `UpdateMeters `during it's test

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 8]
```diff
@@ -5313,117 +5310,59 @@ namespace OutputProcessor {
...
-                "2,365,12,31, 0,24,50.00,60.00,Tuesday",
-                "7,1.9",
-                "2,365,12,31, 0,24,60.00,70.00,Tuesday",
-                "7,2.2",
-                "5,365",
-                "56,9.7,1.1,12,31,24,20,2.2,12,31,24,70",
+                "2,1,Electricity:Facility [J] !TimeStep",
+                ",365,12,31, 0,24,50.00,60.00,Tuesday",
+                "2,0.0",
             },
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5350]: line 5349 represents the warmup day and shows 0 energy consumption.  Should there even be a line in the ESO file for the warmup day? (newbie question)

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 9]
```diff
@@ -5313,117 +5310,59 @@ namespace OutputProcessor {
...
-
-        PurchAir(1).TotHeatEnergy = 2.4;
+                            "Electricity",
+                            "InteriorLights",
+                            "GeneralLights",
+                            "Building",
+                            "SPACE1-1",
+                            1,
+                            1);
+        state->dataGlobal->WarmupFlag = true;
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5341]: set WarmupFlag = true so the `UpdateMeters `function returns without changing any of the meter data

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 10]
```diff
@@ -5313,117 +5310,59 @@ namespace OutputProcessor {
...
-        PurchAir(1).TotHeatEnergy = 100.0;
-        UpdateMeterReporting(*state);
-        UpdateDataandReport(*state, OutputProcessor::TimeStepType::System);
-
-        PurchAir(1).TotHeatEnergy = 200.0;
-        UpdateMeterReporting(*state);
-        UpdateDataandReport(*state, OutputProcessor::TimeStepType::System);
-
-        PurchAir(1).TotHeatEnergy = 300.0;
+        state->dataGlobal->WarmupFlag = false;
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5353]: change the `WarmupFlag `to false so `UpdateMeters `will execute

**Review by KarenWGard — COMMENTED** [review]
first pass on the code for these bug fixes

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc (hunk 8 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/OutputProcessor.unit.cc:5350]: If user has specified `OutputDiagnostics:ReportDuringWarmup`, then yes.

File: src/EnergyPlus/OutputProcessor.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/OutputProcessor.cc:2124]: I would suggest this. Add `Output:Diagnostics, ReportDuringWarmup;`, run the ismulation, and then view the results. Is all the data there for the warmup days? is the meter data there? is the meter data needed? I think the anwer is yes this data is needed in this case.

Comment (rraustad) [reply src/EnergyPlus/OutputProcessor.cc:2124]: There are times when the simulation terminates during the warmup days (e.g., surface temperature out of bounds, plant loop temps getting too hot/cold, etc.), before the actual day is simulated and there is no data to view to clue in on what went wrong. When ReportDuringWarmup was added a long time ago the idea was to provide the user with information. So certainly some information needs to be collected during warmup days when the user requests it. Is the meter data needed? not sure on that one. The user would certainly like to see node data, zone temps, HVAC energy, plant operation, etc.

Comment (KarenWGard) [reply src/EnergyPlus/OutputProcessor.cc:2124]: @rraustad - thanks for the feedback.  I ran the test file with `Output:Diagnostics,ReportDuringWarmup,,,,;` in both version 23.1 and in this branch, then compared the eso files.  Both eso files have the same output variables listed and appear to have the same data, though a kdiff is difficult to perform as the variables have different reference numbers.  The two eso files are linked here:

[test file run in V23.1](https://www.dropbox.com/scl/fi/z1r6za6mrkjhds240alqs/5ZoneAirCooled-2RunPeriods_V23_1.eso?rlkey=b10ociendw8no4nuxxya2nmvl&dl=0)

[test file run in this branch](https://www.dropbox.com/scl/fi/l0yau7dqwk8mhs8593m6x/5ZoneAirCooled-2RunPeriods_bug_fix.eso?rlkey=jenau5m06zssemgedhh6gwm2h&dl=0)

Comment (mjwitte) [reply src/EnergyPlus/OutputProcessor.cc:2124]: This is where comparing csv output can be useful - no reference numbers, just names and values.

Comment (rraustad) [reply src/EnergyPlus/OutputProcessor.cc:2124]: There are 2 types of meters. One that reports to the eso (and also the mtr), Output:Meter, and the other reports to the mtr file (a meter eso). If you were to run ReadVarsESO.exe you will get eplusout.csv from the eso file (when OutputControl:Files, CSV = No, if CSV = yes, the csv will be produced by the program). You should be able to diff the csvs. I'm not sure how to process the mtr file to get a csv.

    Output:Meter,
       \memo Each Output:Meter command picks meters to be put onto the standard output file (.eso)
       \memo and meter file (.mtr). Not all meters are reported in every simulation. A list of meters
       \memo that can be reported are available after a run on the meter dictionary file (.mdd) if
       \memo the Output:VariableDictionary has been requested.

    Output:Meter:MeterFileOnly,
       \memo Each Output:Meter:MeterFileOnly command picks meters to be put only onto meter file (.mtr).
       \memo Not all meters are reported in every simulation. A list of meters that can be reported
       \memo a list of meters that can be reported are available after a run on
       \memo the meter dictionary file (.mdd) if the Output:VariableDictionary has been requested.

Comment (mjwitte) [reply src/EnergyPlus/OutputProcessor.cc:2124]: Also, I think it's fine for meters to not accumulate during warmup (it sounds like they never did anyway). And I think it's fine for the meters report and ABUPS to vary. The documentation should be updated to be very clear on what's included in ABUPS and in the Meter Reports and other types of accumulating reports (like Output:Table:Monthly and Output:Table:Annual). Suggested footnote for Meter report(s):
*Values are accumulated for all RunPeriods and SizingPeriods.*
For ABUPS and others:
*Values are accumulated for all RunPeriods.*

This raises a new question for multi-year RunPeriods - does ABUPs and other outputs include the total across all years?

Comment (KarenWGard) [reply src/EnergyPlus/OutputProcessor.cc:2124]: @mjwitte - how do I add these footnotes to this branch?

Also, I just ran the test file with multi-year run periods.  ABUPS in both V23.1 and this branch.  When there is a a run period of more than a year, ABUPS and the LEED reports include the total across all run periods, but Energy Meters reports 0.  This seems like a separate issue, though a fix could be tied into this branch.

Comment (mjwitte) [reply src/EnergyPlus/OutputProcessor.cc:2124]: Here's a sample from OutputReportsPredefined.cc:
`addFootNoteSubTable(state, s->pdstOAavgOcc, "Values shown for a single zone without multipliers");`
You can search the code for the report names to find the correct report value to pass.

The zero meter reports for a multiyear runperiod seems wrong. We should try to fix that here.

Comment (KarenWGard) [reply src/EnergyPlus/OutputProcessor.cc:2124]: thanks @mjwitte - the tables in the Energy Meters report now all include the note:

"Values shown are for all completed run periods - including any simulations run during sizing periods"

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 11]
```diff
@@ -916,6 +923,7 @@ namespace OutputReportPredefined {
 
         // Other J SubTable
         s->pdstEMotherJvalues = newPreDefSubTable(state, s->pdrEnergyMeters, "Annual and Peak Values - Other");
+        addFootNoteSubTable(state, s->pdstEMotherJvalues, "Values shown are for all completed run periods - including any simulations run during sizing periods");
```
Comment (KarenWGard) [inline src/EnergyPlus/OutputReportPredefined.cc]: footnotes added to clarify what is included in the EnergyMeters report

File: src/EnergyPlus/OutputProcessor.cc [hunk 12]
```diff
@@ -2188,89 +2194,18 @@ namespace OutputProcessor {
...
-                if (op->EnergyMeters(Meter).TSValue < op->EnergyMeters(Meter).FinYrSMMinVal) {
-                    op->EnergyMeters(Meter).FinYrSMMinVal = op->EnergyMeters(Meter).TSValue;
-                    op->EnergyMeters(Meter).FinYrSMMinValDate = TimeStamp;
-                }
+            //if (op->isFinalYear) {
+            if (op->EnergyMeters(Meter).TSValue < op->EnergyMeters(Meter).FinYrSMMinVal) {
+                op->EnergyMeters(Meter).FinYrSMMinVal = op->EnergyMeters(Meter).TSValue;
+                op->EnergyMeters(Meter).FinYrSMMinValDate = TimeStamp;
             }
+            //}
```
Comment (KarenWGard) [inline src/EnergyPlus/OutputProcessor.cc:2202]: the isFinalYear flag is unreliable - it only checks whether the last runperiod is less than or equal to one year - it will report more than one year if that year is made up of multiple run periods that are each less than or equal to a year, and it will not report if the runperiod is longer than one year.

UpdateMeters is the only function to use the isFinalYear flag.  If my approach is accepted, we should discuss removing this flag entirely.

**Review by KarenWGard — COMMENTED** [review]
developer review #2

**Review by Myoldmopar — APPROVED** [review]
It looks like this has been scrutinized quite a bit.  The fix to the decimals, change to warmup reporting, and removal of a now unnecessary function are all good.  And good job re-purposing the unit test.  I don't have any issues here, I'll pull develop and build/test.

**Comment by Myoldmopar** [comment]
Pulled develop, built and tested fine, applied formatting, and pushed.  I'll let some of the CI run on it to confirm and then get this merged if it's all clean.

**Comment by Myoldmopar** [comment]
That's enough CI for me.  I'm going to go ahead and merge, and delete the branch.  FYI @KarenWGard, this will result in some false test failures when Decent CI finally gets around to continuing on this branch, because the branch is no longer there....but just ignore them.  Thanks for this, merging.

**Comment by EnergyArchmage** [comment]
I noticed that this is causing problems when running eplus_regression_runner with Force Annual simulations turned on.  Now if there are two RunPeriods you get the second added to the full annual for more than 8760 hours in the annual summary.  

Implementation here didn't account for `state.dataSysVars->FullAnnualRun`

**Comment by mjwitte** [comment]
> I noticed that this is causing problems when running eplus_regression_runner with Force Annual simulations turned on. Now if there are two RunPeriods you get the second added to the full annual for more than 8760 hours in the annual summary.
> 
> Implementation here didn't account for `state.dataSysVars->FullAnnualRun`

Rather than modify this, shouldn't we fix `FullAnnualRun` to only do a single annual run regardless of the number of RunPeriods? Or is there some reason we want every RunPeriod expanded to a full year?

**Comment by EnergyArchmage** [comment]
Yes, `FullAnnualRun ` should do a single annual run.  Now it only expands the first RunPeriod, then the extra time in the second RunPeriod as input get added.   Before this it didn't matter much that the second RunPeriod would run because the time didn't get added into the summary.
