### PR TITLE
Correct zone temperature history terms for ThirdOrderBackwardDifference heat balance equation

### LINKED ISSUE #9845: Zone Air Temperature interpolation errors for history terms (DownInterpolate4HistoryValues) when adaptive system time steps are present
Issue overview
----------------
This issue affects fundamental predictor-corrector zone air heat balance calculations, where adaptive system timesteps were necessary (subject to 'PerformancePrecisionTradeoffs' and 'ConvergenceLimits' and described in **Engineering Documentation Sections 2.1** and **2.8.3**). Combined, these issues may have implications for any models with adaptive system time steps and rapid transient behavior; however, the issue appears isolated to those short-duration periods, with minimal impact on the long-duration aggregate results and more steady-state periods.

This two-part issue appears due to incorrect interpolation (`Real64 DownInterpolate4HistoryValues`), used to populate zone air temperature history values for the first step down (flag 'ShortenTimeStepSys'), when previous DS data cannot be re-used (and therefore, this issue affects following timesteps as well, though with diminishing impact). The issue can lead to incorrect "**Zone Air Temperature**" outputs, especially during transitional periods (e.g. when heating systems shut off and the zone temp is allowed to float). This can even directly result in oscillating zone air temperatures, highlighted by adding an Output:Variable object "**Zone Oscillating Temperatures Time**" at a 'detailed' timestep.

This issue was isolated through code review, when zone temperature changes at the adaptive system timestep were found inconsistent with direct (spreadsheet) calculations replicating the engineering documentation and coded methods.

## Part 1 - shifted index assignments in `Real64 DownInterpolate4HistoryValues`
within [ZoneTempPredictorCorrector.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc)

`ZTM[0]`, `ZTM[1]` and `ZTM[2]` are the immediately preceding zone air temperature history terms used to solve for current "**Zone Air Temperature**" in both the main predictor and corrector methods (`Real64 ZoneSpaceHeatBalanceData::correctAirTemp` and `void ZoneSpaceHeatBalanceData::predictSystemLoad`) using the 3rd Order Backward Difference method [_line 4237, etc._]. When adaptive system time steps are used, these are set as follows:

- [_line 4273 and 7198_] `this->ZTM = this->DSXMAT;` 

and DSXMAT is in turn assigned `newVals` through
- [_line 7125_] `this->MAT = DownInterpolate4HistoryValues(PriorTimeStep, state.dataHVACGlobal->TimeStepSys, this->XMAT, this->DSXMAT);` 

which calls
- [_line 5068_] `Real64 DownInterpolate4HistoryValues(Real64 OldTimeStep, Real64 NewTimeStep, std::array<Real64, 4> const &oldVals, std::array<Real64, 4> &newVals)`  

However, `ZTM[0]` _should_ be the immediately preceding zone temp (i.e. `XMAT[0]` or `oldVals[0]` or `MAT`). Instead, 
- `ZTM[0]` = `DSXMAT[0]` = `newVals[0]`

and `newVals[0]` is set to be a full system time step (`newTime1`) past when it should be per:
- [_line 5104_] `newVals[0] = oldVals[0] + delta10 * ((oldTime0 - newTime1) / OldTimeStep); `

### Proposed fix
For each of the `newVals` calculations in each of the `if-else` cases in `Real64 DownInterpolate4HistoryValues`, shift the `newTime` constants one increment back (e.g. `newTime1` becomes `newTime0`, etc.). Note that this does not appear to affect `void DownInterpolate4HistoryValues`

## Part 2 - equivalent OldTimeStep and NewTimeStep in `Real64 DownInterpolate4HistoryValues`
`Real64 DownInterpolate4HistoryValues()` should be taking in the following time step information:

- `Real64 OldTimeStep` = `PriorTimeStep` = `state.dataGlobal->TimeStepZone`*
- `Real64 NewTimeStep` = `state.dataHVACGlobal->TimeStepSys`

*[_line 247_] in [HVACManager.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACManager.cc)

However, somehow the function ends up with the following incorrect assumption: 

- `OldTimeStep` = `NewTimeStep`

This results in the use of the final "`else`" case and _greatly_ overestimated **Zone Air Temperatures** for the previous system time steps (`DSXMAT`) due to these values being interpolated mis-assuming (in effect) full zone time steps.

This could not be directly verified, but would cleanly resolve the remaining discrepancy for all time steps, and is strongly suspected. 

### Proposed fix
The root cause and other implications are undetermined. It may also impact the other `void DownInterpolate4HistoryValues()` function. With developer access, it is proposed some test cases be run to:

- insert a check to determine which value (`OldTimeStep` or `NewTimeStep`) is being passed and/or handled incorrectly
- trace the source of the error and resolve the issue

## Other Details

For context, this issue was isolated on the simulation side using the following model set-up:

- very simple 5-zone box model in EnergyPlus v22.2.0 with no internal gains or windows, and only one exterior wall
- served by single-zone RTUs, scheduled heating to 30C for portions of the day, otherwise allowed to float
- 3-5 minute zone timesteps, primarily using default CTF and 3rdOrderDifference methods

Some additional details for this issue (if relevant):

- troubleshooting runs were done on Windows 10 Home Version 21H1
- Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz Processor with 16.0 GB RAM
- Version of EnergyPlus: defect appears still present in https://github.com/NREL/EnergyPlus/releases/tag/v22.2.0
- [reviewed on 2023-02-12]

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9845
 - Closes #10135 as original branch with discussion and testing. This branch is created to allow continuous integration to test for differences in results. See issue description and #10135 for further discussion.
 - During interpolation in `Real64 DownInterpolate4HistoryValues` the indexes are incorrectly assigned.
For example, on line 5054 of ZoneTempPredictorCorrector.cc, 
`newVals[0] = oldVals[0] + delta10 * ((oldTime0 - newTime1) / OldTimeStep);`
when it should really be the immediately preceding zone temp
`newVals[0] = oldVals[0];`
This error caused incorrect interpolation of certain values. This has been fixed by changing each of the `newVals` values according the the following table  (where each row represents values that are equal).

| Value **after** this edit | Value **before** this edit |
|---------------------------|----------------------------|
| newVals[0]                | -                          |
| newVals[1]                | newVals[0]                 |
| newVals[2]                | newVals[1]                 |
| newVals[3]                | newVals[2]                 |
| -                          | newVals[3]                 |

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 1]
```diff
@@ -5012,114 +5012,96 @@ void DownInterpolate4HistoryValues(Real64 const OldTimeStep,
...
-    Real64 const newTime4 = newTime3 - NewTimeStep;
-
+    // old math variables
+    // Real64 const oldTime0 = 0.0;
+    // Real64 const oldTime1 = oldTime0 - OldTimeStep;
+    // Real64 const newTime0 = 0.0;
+    // Real64 const newTime1 = newTime0 - NewTimeStep;
+    // Real64 const newTime2 = newTime1 - NewTimeStep;
+    // Real64 const newTime3 = newTime2 - NewTimeStep;
+    // Real64 const newTime4 = newTime3 - NewTimeStep;
```
Comment (rraustad) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc:5022]: I thought this math was important enough to allow a good understanding of what these functions do so I left in the old math as a future guide.

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 2]
```diff
@@ -5012,114 +5012,96 @@ void DownInterpolate4HistoryValues(Real64 const OldTimeStep,
...
+
+    Real64 constexpr realTWO = 2.0;
+    Real64 constexpr realTHREE = 3.0;
```
Comment (rraustad) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc:5025]: I don't really know if constexpr for these is advantageous but though it couldn't hurt.

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 3]
```diff
@@ -5012,114 +5012,96 @@ void DownInterpolate4HistoryValues(Real64 const OldTimeStep,
...
-        // last point lie between oldVals[1] and oldVals[2]
-        Real64 delta21 = (oldVals[2] - oldVals[1]) / OldTimeStep;
-        newVals[3] = oldVals[1] + delta21 * ((oldTime1 - newTime4) / OldTimeStep);
+    } else if (std::abs(DSRatio - realTHREE) < 0.01) { // DSRatio = 3
+        // first two points lie between (oldVals[0] and oldVals[1])
+        Real64 delta10 = (oldVals[1] - oldVals[0]) / realTHREE;
+        newVals[1] = oldVals[0] + delta10;
+        newVals[2] = newVals[1] + delta10;
+        // last point is oldVals[1]
+        newVals[3] = oldVals[1];
```
Comment (rraustad) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc:5095]: Moved denominator up to delta10 equation so as not to divide by the same number multiple times. Hopefully saving a few clock cycles. Here and below.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 4]
```diff
@@ -23690,7 +23690,7 @@ TEST_F(EnergyPlusFixture, UnitarySystemModel_MultiSpeedFanWSHP_Test)
                      latOut);
     // first speed heating
     EXPECT_NEAR(thisSys.m_SpeedRatio, 0.0, 0.0001);
-    EXPECT_NEAR(thisSys.m_CycRatio, 0.81485929, 0.0001);
+    EXPECT_NEAR(thisSys.m_CycRatio, 0.81485980, 0.0001);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:23693]: Verified this unit test calls the modified function and therefore the answer changes slightly.

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 5]
```diff
@@ -5012,114 +5012,96 @@ void DownInterpolate4HistoryValues(Real64 const OldTimeStep,
...
-        newVals[1] = oldVals[0] + delta10 * ((oldTime0 - newTime2) / OldTimeStep);
-        newVals[2] = oldVals[0] + delta10 * ((oldTime0 - newTime3) / OldTimeStep);
-        newVals[3] = oldVals[0] + delta10 * ((oldTime0 - newTime4) / OldTimeStep);
+        // all new points lie between (oldVals[0] and oldVals[1])
+        Real64 delta10 = (oldVals[1] - oldVals[0]) / DSRatio;
+        newVals[1] = oldVals[0] + delta10;
+        newVals[2] = newVals[1] + delta10;
+        newVals[3] = newVals[2] + delta10;
     }
     return oldVals[0];
```
Comment (rraustad) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc:5104]: Interesting that a value that has not changed is returned, as example:

    this->MAT = DownInterpolate4HistoryValues(PriorTimeStep, TimeStepSys, this->XMAT, this->DSXMAT);

and is the same as this->MAT = this->XMAT[0], but since this also downinterpolates, it resets MAT for the next "downstepped" simulation to come. When I hit "step", MAT reverts to what is was before this last time step simulation, so that a new "shorter" time step simulation can proceed. So this also makes sense.

image

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 6]
```diff
@@ -5012,114 +5012,96 @@ void DownInterpolate4HistoryValues(Real64 const OldTimeStep,
...
+
+    Real64 constexpr realTWO = 2.0;
+    Real64 constexpr realTHREE = 3.0;
+    // first determine the ratio of system time step to zone time step
     Real64 const DSRatio = OldTimeStep / NewTimeStep; // should pretty much be an integer value 2, 3, 4, etc.
 
     newVal0 = oldVal0;
 
-    if (std::abs(DSRatio - 2.0) < 0.01) { // DSRatio = 2
+    if (std::abs(DSRatio - realTWO) < 0.01) { // DSRatio = 2
```
Comment (rraustad) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc:5031]: It would be nice to get rid of the std::abs. If DSRatio is expected to be 2, 3, 4, 5, etc, then I would think this would work just as well, but not sure if it has any potential to improve execution speed.

    if (DSRatio < 2.5) {
    } else if (DSRatio < 3.5) {
    } else {
    }

The ratio of new time step to old time step must be an integer:

    if (ZoneTempChange > state.dataConvergeParams->MaxZoneTempDiff && !state.dataGlobal->KickOffSimulation) {
        // determine value of adaptive system time step
        // model how many system timesteps we want in zone timestep
        int ZTempTrendsNumSysSteps = int(ZoneTempChange / state.dataConvergeParams->MaxZoneTempDiff + 1.0); // add 1 for truncation
        state.dataHVACGlobal->NumOfSysTimeSteps = min(ZTempTrendsNumSysSteps, state.dataHVACGlobal->LimitNumSysSteps);
        // then determine timestep length for even distribution, protect div by zero
        if (state.dataHVACGlobal->NumOfSysTimeSteps > 0) {
            state.dataHVACGlobal->TimeStepSys = state.dataGlobal->TimeStepZone / state.dataHVACGlobal->NumOfSysTimeSteps;
        }
        state.dataHVACGlobal->TimeStepSys = max(state.dataHVACGlobal->TimeStepSys, state.dataConvergeParams->MinTimeStepSys);

**Comment by rraustad** [comment]
Diff snap shot of 5ZoneAirCooled:

image

**Comment by Myoldmopar** [comment]
Aaaand I don't think this can be rushed in.  Big ESO diffs across the board.  I'm going to mark this for the next release because we need time to digest and prove the results.  If someone disagrees, feel free to chime in, but I don't see how we can rush that big of a set of diffs in to a release coming in a matter of a few days.

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 7]
```diff
@@ -5012,114 +5012,96 @@ void DownInterpolate4HistoryValues(Real64 const OldTimeStep,
...
+        // first point lies exactly between (oldVals[0] and oldVals[1])
+        newVals[1] = (oldVals[0] + oldVals[1]) / realTWO;
+        // 2nd point is oldVal[1] and last point lies exactly between (oldVals[1] and oldVals[2])
+        newVals[2] = oldVals[1];
+        newVals[3] = (oldVals[1] + oldVals[2]) / realTWO;
 
-    if (std::abs(DSRatio - 2.0) < 0.01) { // DSRatio = 2
-        // first two points lie between oldVals[0] and oldVals[1]
-        Real64 delta10 = oldVals[1] - oldVals[0];
-        newVals[0] = oldVals[0] + delta10 * ((oldTime0 - newTime1) / OldTimeStep);
```
Comment (rraustad) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc:5070]: The underlying problem in this function is changing the anchor point, newVals[0]. This point should not change and should be equal to oldVals[0] as in the function above (line 5027/5029). This correction will change results in files that down interpolate the history terms. The decay curves shown in [this figure from the parallel branch](https://github.com/NREL/EnergyPlus/pull/10135#issuecomment-1664725227) shows why the answers will/should change.

    void DownInterpolate4HistoryValues(Real64 const OldTimeStep, ... )

        newVal0 = oldVal0;

Comment (rraustad) [reply src/EnergyPlus/ZoneTempPredictorCorrector.cc:5070]: Here's a figure to show that newVal[0] = oldVal[0] when down interpolating (i.e., I think this should be merged):

image

**Comment by nrel-bot-2c** [comment]
@rraustad @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @rraustad @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @rraustad @myoldmopar it has been 29 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@Myoldmopar @rraustad Because the new version of `DownInterpolate4HistoryValues` which as originally flagged in the issue was introduced by moi in #9394, I was initially concerned that the error was introduced then. But going back to v22.2 shows the same temperature pattern, and diffs like this would have been seen during #9394 development. Looking at the v22.2 code, it's not so obvious that there's a mistake (even though the output shows the same glitch in temperature). I started a spreadsheet to compare before and after, but of course that's kind of moot. More important would be to understand how the mistake crept in prior to v22.2 or has it always been this way. I'm attaching the spreadsheet here just for reference, but my present position in reviewing this is that I still have some doubts, but I can't find anything wrong. 
[DownInterpolateCodeComparison.xlsx](https://github.com/NREL/EnergyPlus/files/13846788/DownInterpolateCodeComparison.xlsx)

**Comment by rraustad** [comment]
[The figure above](https://github.com/NREL/EnergyPlus/pull/10226#discussion_r1331793514) shows what I believe is the correct down interpolation. When you realize T0 must be the same in both arrays then this becomes clear. When down interpolation occurs, T0 does not change and the other data points are pulled towards T0 proportional to the change in time step (so that the differential equation uses the temperatures that correspond to the downstepped time increment).

**Comment by mjwitte** [comment]
@Myoldmopar @rraustad Feel free to merge this if you see fit.

**Comment by Myoldmopar** [comment]
OK, I think this has lingered long enough.  I'm going to pull and test and let's get this in.

**Comment by Myoldmopar** [comment]
This has definitely got some pretty widespread diffs, but as tough as it is to get past, I think we need to.  The change has been described and reviewed enough to feel it's the right move.  The diffs tend to be very small and down in the deeper decimal points.  There are some bigger diffs, but they tend to be washed out when you report at longer time intervals.  There are actually several files that are showing a reduction in the number of required warmup days, indicating it is converging at steady periodic a little quicker.  I am OK dropping this in, note that it will cause diffs in any upcoming CI runs that haven't started yet.  Final thoughts anyone?  If none, this will merge soon.

**Comment by Myoldmopar** [comment]
Nothing happening, so merging this now.  Thanks @rraustad and @mjwitte
