### PR TITLE
Bug Fix (Linux Build Warning) to WeatherManager.cc

### LINKED ISSUE #7314: Build Warning on Linux Release
Issue overview
--------------
```
/eplus/repos/jmarrec/src/EnergyPlus/WeatherManager.cc: In function ‘void EnergyPlus::WeatherManager::SetCurrentWeather()’:
/eplus/repos/jmarrec/src/EnergyPlus/WeatherManager.cc:2490:34: warning: ‘%02d’ directive writing between 2 and 11 bytes into a region of size between 0 and 4 [-Wformat-overflow=]
         std::sprintf(time_stamp, "%02d/%02d %02d:", Month, DayOfMonth, HourOfDay - 1);
                                  ^~~~~~~~~~~~~~~~~
/eplus/repos/jmarrec/src/EnergyPlus/WeatherManager.cc:2490:34: note: directive argument in the range [-2147483648, 2147483646]
In file included from /usr/include/stdio.h:873,
                 from /usr/include/c++/8/cstdio:42,
                 from /usr/include/c++/8/ext/string_conversions.h:43,
                 from /usr/include/c++/8/bits/basic_string.h:6391,
                 from /usr/include/c++/8/string:52,
                 from /usr/include/c++/8/stdexcept:39,
                 from /usr/include/c++/8/array:39,
                 from /eplus/repos/jmarrec/src/EnergyPlus/WeatherManager.cc:49:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:34: note: ‘__builtin___sprintf_chk’ output between 10 and 37 bytes into a destination of size 10
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Details
Some additional details for this issue (if relevant):
 - Platform: Ubuntu 18.10
 - GCC: 8.2.0

### PR DESCRIPTION
**Pull request by YanfeiNREL**
Pull request overview
---------------------
Fix #7314 

The build warning in Linux 18.10 are: 

/eplus/repos/jmarrec/src/EnergyPlus/WeatherManager.cc: In function ‘void EnergyPlus::WeatherManager::SetCurrentWeather()’:
/eplus/repos/jmarrec/src/EnergyPlus/WeatherManager.cc:2490:34: warning: ‘%02d’ directive writing between 2 and 11 bytes into a region of size between 0 and 4 [-Wformat-overflow=]
         std::sprintf(time_stamp, "%02d/%02d %02d:", Month, DayOfMonth, HourOfDay - 1);
                                  ^~~~~~~~~~~~~~~~~
### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
   - Defect: This pull request repairs a github defect issue.  
                 The issue is: "Month, DayOfMonth, HourOfDay" are all integers; while the "%02d/%02d %02d" 
                 formatting is trying to compress those integers into 2 digitals. However, the compiler is not 
                 smart enough to recognize this behavior. Basically i cast them into short integer.  
                 (Input file for test: 5ZoneAirCooled.idf)  [Environment setup: Linux 18.10, Gcc 8.3.0.]

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ x ] Functional code review (it has to work!)
 - [ x ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

File: src/EnergyPlus/WeatherManager.cc [hunk 1]
```diff
@@ -2486,8 +2486,9 @@ namespace WeatherManager {
         }
 
         UpdateScheduleValues();
-
-        std::sprintf(time_stamp, "%02d/%02d %02d:", Month, DayOfMonth, HourOfDay - 1);
+        
+		std::sprintf(time_stamp, "%hu/%hu %hu:",(unsigned short) Month, (unsigned short)DayOfMonth, (unsigned short)(HourOfDay - 1));
```
Comment (mbadams5) [inline src/EnergyPlus/WeatherManager.cc]: You still need the `%02` in front to pad zeros so it will be 01 instead of 1 for january. `"%02hu/%02hu %02hu:"`

And honestly, it is probably only complaining about the `HourOfDay - 1` part of the original statement since below the compiler didn't complain about `std::sprintf(day_stamp, "%02d/%02d", Month, DayOfMonth);`. Also if HourOfDay is ever zero, it will underflow when cast to unsigned short. However, I don't think HourOfDay will be 0 in E+.

Comment (YanfeiNREL) [reply src/EnergyPlus/WeatherManager.cc]: u r correct! The only complaining is HourOfDay. Its ranges are 1~24. It is better to cast HourOfDay only. Thank you.

**Comment by Myoldmopar** [comment]
@YanfeiNREL I pulled this branch locally and verified that I am now seeing a clean build of WeatherManager with no compiler warning.  I pulled the latest develop branch into here and also applied Clang-Format to the source.  I added the Defect label to this PR.  With all this done, the next build on CI should be completely green and this can go right in.  Thanks.

**Comment by Myoldmopar** [comment]
Yep, good to go.  Merging.  Thanks @YanfeiNREL
