### PR TITLE
Handling unknown extensions for schedules

### LINKED ISSUE #10675: Error in `Schedule:File` when reading an external file
Issue overview
--------------
Version 24.1.0 of the software has introduced a novel incompatibility: files lacking an explicit `.csv` extension are no longer recognized as valid inputs. 

A temporary workaround involves manually altering the file extension of external data. Specifically, the file name must be either replaced with or appended by `.csv`. 

For instance, the following block will produce an error:
```fortran
Schedule:File, 
    Rainfall Data from EPW file,          !- Name
    Any Number,                           !- Schedule Type Limits Name
    weather-file.rain,                    !- File Name
    1,                                    !- Column Number
    1,                                    !- Rows to Skip at Top
    8760;                                 !- Number of Hours of Data
```

The error is rectified upon modification of the file and its corresponding reference:
```fortran
Schedule:File, 
    Rainfall Data from EPW file,          !- Name
    Any Number,                           !- Schedule Type Limits Name
    weather-file.rain.csv,                !- File Name
    1,                                    !- Column Number
    1,                                    !- Rows to Skip at Top
    8760;                                 !- Number of Hours of Data
```

Prior to this release, the system successfully processed files with alternative extensions. Not sure what the purpose of the `src/EnergyPlus/InputProcessing/CsvParser.cc` is, but for now it represents a regression in software functionality from previous versions, where this issue had been previously resolved.

### Details
Some additional details for this issue (if relevant):
 - Platform : macOS 14
 - Version of EnergyPlus : 24.1.0
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by GaryMarksBigladder**
Pull request overview
---------------------

- Fixes #10675 

### Pull Request Author

 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ScheduleManager.cc [hunk 1]
```diff
@@ -1642,11 +1678,47 @@ namespace Sched {
...
+                                isJSON = false;
+                            }
+                        }
+                        if (!isCSV && !isJSON) {
+                            ShowSevereCustom(
+                                state,
+                                eoh,
+                                format("{} = {} has an unknown file extension and cannot be read by this program.", cAlphaFields(3), Alphas(3)));
+                            ShowFatalError(state, "Program terminates due to previous condition.");
+                        }
```
Comment (rraustad) [inline src/EnergyPlus/ScheduleManager.cc:1749]: Certainly better than it was.

**Review by mitchute — APPROVED** [review]
All good here. Looks lovely.

**Comment by mitchute** [comment]
We'll let CI take one last pass and then merge.

**Comment by mitchute** [comment]
Okey-dokey. All good here. Merging.
