### PR TITLE
Fix #7135 - Transition: Handle case where Number of vertices isn't an integer instead of failing

### LINKED ISSUE #7135: Error transitioning Shading:Building:Detailed objects from 8.9.0 to 9.0.1
Issue overview
--------------
The below error message appears when updating a working v8.9.0 IDF to v9.0.1 using IDFVersionUpdater. This appears to be caused by three Shading:Building:Detailed objects, after removing which the error disappears.

A simple IDF that can replicate the issue is attached: [updater_error_example.zip](https://github.com/NREL/EnergyPlus/files/2793408/updater_error_example.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10 Enterprise Version 10.0.16299 Build 16299
 - Version of EnergyPlus: v9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [DefectFiles/7000s/7135](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7135)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7135 - Transition: Handle case where Number of vertices isn't an integer instead of failing

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

File: src/Transition/VCompareGlobalRoutines.f90 [hunk 1]
```diff
@@ -749,14 +790,27 @@ SUBROUTINE CheckSpecialObjects(DifUnit,ObjectName,CurArgs,OutArgs,FieldNames,Fie
...
-          CALL WriteOutPartialIDFLines(DifUnit,ObjectName,10,OutArgs,FieldNames,FieldUnits)
           IF (MakeUPPERCase(OutArgs(10)) == 'AUTOCALCULATE') THEN
             NVert=(CurArgs-10)/3
           ELSEIF (OutArgs(10) == '') THEN
             NVert=(CurArgs-10)/3
           ELSE
-            READ(OutArgs(10),*) NVert
+            ! Try to read the number of vertices as an integer
+            NVert = ProcessNumber(OutArgs(10),ErrFlag)
+            IF (ErrFlag) THEN
```
Comment (mjwitte) [inline src/Transition/VCompareGlobalRoutines.f90:809]: ErrFlag is only true is OutArgs(10) is not a number, s0 4.0 and 4.1 pass through unchanged. Transition completes without crashing now, so that's good, but the non-integer values are not replaced.

File: src/Transition/VCompareGlobalRoutines.f90 [hunk 2]
```diff
@@ -749,14 +790,27 @@ SUBROUTINE CheckSpecialObjects(DifUnit,ObjectName,CurArgs,OutArgs,FieldNames,Fie
...
+              ! If failed, default to autocalculate instead
+              NVert=(CurArgs-10)/3
+              ! Replace in existing with Autocalculate
+              OutArgs(10) = 'Autocalculate'
+              CALL DisplayString('For ' // TRIM(ObjectName) // ' named ''' // TRIM(OutArgs(1)) // &
+                  ''', Number of vertices is not an integer, defaulting to Autocalculate (N='// &
+                  TRIM(TrimSigDigits(NVert)) //')')
+            ENDIF
           ENDIF
```
Comment (mjwitte) [inline src/Transition/VCompareGlobalRoutines.f90:821]: Add an ELSE here to set OutArgs(10) = TrimSigDigits(NVert) when ErrFlag is false. This will silently clean up any non-integer values.

File: src/Transition/VCompareGlobalRoutines.f90 [hunk 3]
```diff
@@ -749,14 +790,27 @@ SUBROUTINE CheckSpecialObjects(DifUnit,ObjectName,CurArgs,OutArgs,FieldNames,Fie
...
-            READ(OutArgs(10),*) NVert
+            ! Try to read the number of vertices as an integer
+            NVert = ProcessNumber(OutArgs(10),ErrFlag)
+            IF (ErrFlag) THEN
+              ! If failed, default to autocalculate instead
+              NVert=(CurArgs-10)/3
+              ! Replace in existing with Autocalculate
+              OutArgs(10) = 'Autocalculate'
+              CALL DisplayString('For ' // TRIM(ObjectName) // ' named ''' // TRIM(OutArgs(1)) // &
+                  ''', Number of vertices is not an integer, defaulting to Autocalculate (N='// &
```
Comment (mjwitte) [inline src/Transition/VCompareGlobalRoutines.f90]: Call ShowWarningError instead of DisplayString so the message goes into the audit output.

Change the message to ". . . vertices is not ~an integer~ *a number*, defaulting . . . "

**Review by mjwitte — COMMENTED** [review]
Tested this with different values for Number of Vertices: 4.0, 4.1, <blank>, autocalculate, xyz.

**Comment by jmarrec** [comment]
@mjwitte Addressed your review comments in the last two commits

**Comment by mjwitte** [comment]
Ran some additional tests to cover more object types: BuildingSurface:Detailed, Fenestration:Detailed, Wall:Detailed, RoofCeiling:Detailed, Floor:Detailed, Shading:Site:Detailed, and Shading:Zone:Detailed. All good.

**Review by mjwitte — APPROVED** [review]

**Comment by mjwitte** [comment]
Merging this now since it's only transition code.
