### PR TITLE
Fix Basement Warnings Due to gcc 15.2

### LINKED ISSUE #11298: 3DBasement.f90 warnings with gcc 15.2
### Issue overview

Some new warning popping out when compiling the basement preprocessor.

```sh
/Users/mmitchel/Projects/EnergyPlus/src/Basement/3DBasementHT.f90:10587:142:

10587 |             & 'INSULATION IS PARTIAL LENGTH')
      |                                                                                                                                              1
Warning: Legacy Extension: Missing comma in FORMAT string at (1)
/Users/mmitchel/Projects/EnergyPlus/src/Basement/3DBasementHT.f90:10594:0:

10594 |      & 'SNOW:',2X,F5.2//5X'VEGETATION HEIGHT (CM):'/                         &
Warning: Legacy Extension: Missing comma in FORMAT string at (1)
/Users/mmitchel/Projects/EnergyPlus/src/Basement/3DBasementHT.f90:10613:119:

10613 |      & 'BASEMENT DIMENSIONS:'//5X,'DENSITY (KG/M**3):',2X,                   &
      |                                                                                                                       1
Warning: Legacy Extension: Missing comma in FORMAT string at (1)
/Users/mmitchel/Projects/EnergyPlus/src/Basement/3DBasementHT.f90:10644:181:

10644 |      & ' COEFFICIENTS, CONVECTION AND RADIATION (W/M**2/K):'/                &
      |                                                                                                                                                                                     1
Warning: Legacy Extension: Missing comma in FORMAT string at (1)
/Users/mmitchel/Projects/EnergyPlus/src/Basement/3DBasementHT.f90:11392:0:

11392 |       &  'FOUNDATION WALL:  ',F15.1/,'BASEMENT:  '7X,F15.1)
Warning: Legacy Extension: Missing comma in FORMAT string at (1)
/Users/mmitchel/Projects/EnergyPlus/src/Basement/3DBasementHT.f90:12890:72:

12890 | 4301 FORMAT (7X,'XZ Wall TS',9X,'Inside'6X,'XZ Heat flux',5X,'Base T')
      |                                                                        1
Warning: Legacy Extension: Missing comma in FORMAT string at (1)
```

### Operating System (Multiple choices)

MacOS

### Operating System Version

15.5

### Version of EnergyPlus

25.2.0

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------

- Fixes #11298

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mjwitte — APPROVED** [review]
Code changes look good. My compiler is old, so I don't see the warnings before or after, but I built the new code and tested it with LgOffVAVusingBasement.

File: src/Basement/3DBasementHT.f90 [hunk 1]
```diff
@@ -10583,15 +10583,14 @@ SUBROUTINE PrelimOutput(ACEIL,AFLOOR,ARIM,ASILL,AWALL,PERIM,RUNID,TDBH,TDBC)
        WRITE (InputEcho,600)
      END IF
 500  FORMAT (/5X,'EXTERIOR INSULATION IS FULL LENGTH')
-600  FORMAT (/5X,'IF INSULATED ON EXTERIOR, '                                &
-            & 'INSULATION IS PARTIAL LENGTH')
+600  FORMAT (/5X,'IF INSULATED ON EXTERIOR, ','INSULATION IS PARTIAL LENGTH')
```
Comment (rraustad) [inline src/Basement/3DBasementHT.f90:10586]: You no longer need `','` if all on the same line

Comment (mitchute) [reply src/Basement/3DBasementHT.f90:10586]: Ah, that is true. Is this fine enough without another commit?

Comment (rraustad) [reply src/Basement/3DBasementHT.f90:10586]: Yes. I'm not up to speed on latest Fortran syntax (e.g., the `&` location in column 7 at 11391) so if it compiles without warnings and runs fine (as @mjwitte confirmed) then go ahead and merge.
