### PR TITLE
Fix epJSON minfields and extensible input processing

### LINKED ISSUE #8441: epJSON input file generated by converting an IDF triggers fatal simulation errors
Issue overview
--------------
Running simulations for input files in the epJSON format that have been generated by converting IDF files can lead to fatal errors. The reason appears to be that fields that have a default value in EnergyPlus, and that are not explicitly specified in the IDF file used as the basis for the conversion to the epJSON format, are not present in the converted epJSON file.

For example, in the attached IDF file the `Central Cooling Capacity Control Method` and `Heating Design Capacity Method` fields in the `Sizing:System` objects aren't specified. The converted epJSON file does not include these fields, and as a result it triggers a fatal simulation error. If one specifies the default value for these fields in the epJSON file (`"central_cooling_capacity_control_method": "OnOff"` and `"heating_design_capacity_method": "None"`), the simulation runs successfully.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10.
 - Version of EnergyPlus:  9.4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [defect_files.zip](https://github.com/NREL/EnergyPlus/files/5752674/defect_files.zip)

### LINKED ISSUE #8654: epJSON input processing errors - related to minfields and extensible fields
Issue overview
--------------
I have an IDF that runs successfully in E+ 9.5. If I then call `energyplus --convert-only` to generate the epJSON followed by `energyplus in.epJSON` to run it, I get strange errors in the err file that suggest it might not have been read in correctly at all.

```
   ** Severe  ** GetProjectControlData: Building: loads_convergence_tolerance_value value invalid, [0.000]
   ** Severe  ** GetProjectControlData: Building: loads_convergence_tolerance_value value invalid, [0.000]
   ** Severe  ** GetProjectControlData: Building: solar_distribution invalid=
   ** Warning ** Shading:Building:Detailed="WINDOWEAST SHADING SURFACE", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** Shading:Building:Detailed="WINDOWNORTH SHADING SURFACE", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** Shading:Building:Detailed="WINDOWSOUTH SHADING SURFACE", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** Shading:Building:Detailed="WINDOWWEST SHADING SURFACE", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** Foundation:Kiva="FOUNDATION KIVA 1", number of Block fields not even multiple of 4. Will read in 0
   ** Warning ** BuildingSurface:Detailed="FLOORBELOWATTIC", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** BuildingSurface:Detailed="FOUNDATIONWALL", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** BuildingSurface:Detailed="RIMJOISTFOUNDATION:0", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** BuildingSurface:Detailed="RIMJOISTFOUNDATION:90", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** BuildingSurface:Detailed="RIMJOISTFOUNDATION:180", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** BuildingSurface:Detailed="RIMJOISTFOUNDATION:270", number_of_vertices not even multiple of 3. Will read in 3
   ** Warning ** BuildingSurface:Detailed="ROOF:0", number_of_vertices not even multiple of 3. Will read in 3
   ...
   ...
   ...
```

Interestingly, the epJSON sample file (RefBldgMediumOfficeNew2004_Chicago) that ships with EnergyPlus does run successfully. And it runs successfully even if I take the IDF version of the file, convert it to epJSON myself, and run it. So maybe it's unique to our models somehow?

Files to reproduce the issue:
[test.zip](https://github.com/NREL/EnergyPlus/files/6199685/test.zip)

I can reproduce the issue on both Windows and Linux.

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #8654
 - Fixes #8441
 - For input in epJSON
    * Modified `getObjectItem` to return all values up to `\minfields` so that defaults are applieds.
    * For objects with unused fields (not present in the epJSON input) prior to `\extensible` fields (which *are* present in the input), fixed `setObjectItemValue` to set the correct values for `NumAlphas` and `NumNumbers`.
  - Fixes incorrect field name reference in error message for Building "Temperature Convergence Tolerance Value".
  - Fixes old output variable names in some table reports in the epJSON test file (... Electric Power --> ... Electricity Rate")

**Note this only affects input processing for an epJSON input file when using the `getObjectItem` method. Input processing which accesses the epJSON data structure directly has not changed and does not have defaults filled in. See #7632.**

Diffs
--------
Diffs weren't expected here, but there are major diffs for the RefBldgMediumOfficeNew2004_Chicago_epJSON.epJSON test file. The main symptom here is that the plant was sizing to zero flow and now it's not. 
```
   ** Warning ** SizePlantLoop: Calculated Plant Sizing Design Volume Flow Rate=[0.00] is too small. Set to 0.0
   **   ~~~   ** ..occurs for PlantLoop=SWHSYS1
   ** Warning ** SizePump: Calculated Pump Nominal Volume Flow Rate=[0.00] is too small. Set to 0.0
   **   ~~~   ** ..occurs for Pump=SWHSYS1 PUMP
   ** Warning ** Check input. Pump nominal power or motor efficiency is set to 0, for pump=SWHSYS1 PUMP
   ** Warning ** Check input. Pump nominal flow rate is set or calculated = 0, for pump=SWHSYS1 PUMP
```
This error is gone now and so the results have changed significantly.  

I have not traced which object was not processing correctly, but RefBldgMediumOfficeNew2004_Chicago.idf and RefBldgMediumOfficeNew2004_Chicago_epJSON.epJSON now have identical results. Attached zip shows selected output for both test files with develop and this branch (annual simulations). Compare mainly the err and table outputs before and after fix.
[8654-epJSON input problems.zip](https://github.com/NREL/EnergyPlus/files/6212503/8654-epJSON.input.problems.zip)

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/InputProcessing/InputProcessor.cc [hunk 1]
```diff
@@ -577,6 +578,8 @@ InputProcessor::MaxFields InputProcessor::findMaxFields(EnergyPlusData &state, j
         }
     } else {
         auto const &legacy_idd_fields = legacy_idd["fields"];
+        // start with at least min_fields as the number of fields
+        maxFields.max_fields = min_fields;
```
Comment (mjwitte) [inline src/EnergyPlus/InputProcessing/InputProcessor.cc:582]: `max_fields` set initially to `min_fields` so all fields up to that point will be filled with default values if they are not present in the epJSON input.

File: src/EnergyPlus/InputProcessing/InputProcessor.cc [hunk 2]
```diff
@@ -691,13 +694,13 @@ void InputProcessor::setObjectItemValue(EnergyPlusData &state,
         }
     }
     if (field_type == "a") {
-        if (within_max_fields) NumAlphas++;
+        if (within_max_fields) NumAlphas = alpha_index;
```
Comment (mjwitte) [inline src/EnergyPlus/InputProcessing/InputProcessor.cc:697]: If the value is being place in the alpha array at `alpha_index` then `NumAlphas` has to match that so that the function calling `getObjectItem` knows about it. If there were unused fields before this, the `NumAlphas` got behind.

File: src/EnergyPlus/InputProcessing/InputProcessor.cc [hunk 3]
```diff
@@ -691,13 +694,13 @@ void InputProcessor::setObjectItemValue(EnergyPlusData &state,
...
         if (is_AlphaFieldNames) {
             AlphaFieldNames()(alpha_index) = (state.dataGlobal->isEpJSON) ? field : legacy_field_info.at("field_name").get<std::string>();
         }
         alpha_index++;
     } else if (field_type == "n") {
-        if (within_max_fields) NumNumbers++;
+        if (within_max_fields) NumNumbers = numeric_index;
```
Comment (mjwitte) [inline src/EnergyPlus/InputProcessing/InputProcessor.cc:703]: Same for numbers.

File: src/EnergyPlus/InputProcessing/InputProcessor.cc [hunk 4]
```diff
@@ -764,6 +767,11 @@ void InputProcessor::getObjectItem(EnergyPlusData &state,
     auto const &legacy_idd_fields = legacy_idd["fields"];
     auto const &schema_name_field = epJSON_schema_it_val.find("name");
     auto const has_idd_name_field = schema_name_field != epJSON_schema_it_val.end();
+    auto const &found_min_fields = epJSON_schema_it_val.find("min_fields");
+    size_t min_fields = 0;
+    if (found_min_fields != epJSON_schema_it_val.end()) {
+        min_fields = found_min_fields.value();
+    }
```
Comment (mjwitte) [inline src/EnergyPlus/InputProcessing/InputProcessor.cc:774]: get `minfields` if present.

**Review by mjwitte — COMMENTED** [review]
Still need a unit test, but otherwise this is ready for testing and review.

**Comment by mjwitte** [comment]
So, it turns out the existing epJSON test file wasn't running properly. This fixes that. See Diffs section in the [top comment](https://github.com/NREL/EnergyPlus/pull/8661#issue-601206296).
No unit test yet, hopefully later today. Otherwise this is ready for review.

**Comment by mjwitte** [comment]
New unit test fails with develop:
```
[ RUN      ] InputProcessorFixture.epJSONgetObjectItem_minfields
C:\MJWGit\EnergyPlus\tst\EnergyPlus\unit\InputProcessor.unit.cc(4282): error: Expected equality of these values:
  numAlphas
    Which is: 2
  3
```
Passes here.
@Myoldmopar @mbadams5 This is ready for final review.

**Comment by Myoldmopar** [comment]
This looks great to me.  It would be awesome if @mbadams5 could give it a very quick look over, but if not I'll take a slightly deeper dive before merging.  CI is happy with it though, so that is great!

**Review by Myoldmopar — APPROVED** [review]
I think I'm tracking all this here.  And the unit test helps a lot.  This is good to go in now.  Thanks!

**Comment by mjwitte** [comment]
Just to be clear:
Note this only affects input processing for an epJSON input file when using the `getObjectItem` method. Input processing which accesses the epJSON data structure directly has not changed and does not have defaults filled in. See #7632.
