### PR TITLE
Fix Integrated Heat Pump Output Variable Setup

### LINKED ISSUE #9248: Integrated Heat Pump Outputs Vars Only Being Set for Last Instance
Issue overview
--------------
`GetIHPInput`  uses the `CoilCounter` var for loop indexing, and then uses a separate `DXCoilNum` var for accessing all of the IHP data. 

https://github.com/NREL/EnergyPlus/blob/0474bcff0f09143605459c4168e69a17d49e7dd1/src/EnergyPlus/IntegratedHeatPump.cc#L1222-L1224

Later, it uses this same `DXCoilNum` var to access the IHP data for setting output variables; however, this is now outside of the scope of that original `for` loop.

https://github.com/NREL/EnergyPlus/blob/0474bcff0f09143605459c4168e69a17d49e7dd1/src/EnergyPlus/IntegratedHeatPump.cc#L1970-L1984

So, it appears that the IHP output vars are only available for the last coil read into E+.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file - N/A
 - [x] Ticket added to Pivotal - N/A
 - [x] Pull request created

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Fixes #9248 (d2a575391ac0e4e67432467210bbd4f2423eec73)
 - Performs some obvious, but minor, cleanups in IHP

### CODE REVIEW

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 1]
```diff
@@ -1967,119 +1967,119 @@ void GetIHPInput(EnergyPlusData &state)
...
         state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).MaxCoolAirVolFlow = 1e10;
-    }
 
-    if (ErrorsFound) {
-        ShowFatalError(state,
-                       std::string{RoutineName} + "Errors found in getting " + CurrentModuleObject +
-                           " input.  Preceding condition(s) causes termination.");
-    } else {
-        // set up output variables, not reported in the individual coil models
-        SetupOutputVariable(state,
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc]: I moved this chunk into the `for` loop. The rest is indentation formatting.

Comment (rraustad) [reply src/EnergyPlus/IntegratedHeatPump.cc]: So E+ will fatal out on the first IHP with an input error? i.e., ErrorsFound will be true for that IHP and the rest will not be read in. We typically loop through all instances of an equipment type to allow the warnings to print to the error file so the user can fix all at once instead of one at a time. It would be better to move this back and for loop inside the else to set up report vars for all IHPs.

Comment (mitchute) [reply src/EnergyPlus/IntegratedHeatPump.cc]: Thanks, @rraustad. I moved the fatal error call outside of the get input and SetupOutputVars now happens all at once after that.

**Review by mitchute — COMMENTED** [review]
@Myoldmopar @rraustad @mjwitte I'd be interested to have your comments on this commit (4af38ceec864ad0240e070e97ae80c403305daf9).

Sizing of the various variable speed coils in here was doing some weird stuff with showing an error message and then setting the error flag to false. I'm pretty sure most of the error messages in here were unreachable. I think I "fixed" it, although I'm pretty sure this is going to cause at least one unit test failure that will have to be handled if we keep this in.

**Comment by rraustad** [comment]
The ErrorsFound flag (the king) is the getInput function flag for any errors found and should terminate the program after processing all objects. The local errFlag (the soldier) is used for the mining calls where some mining calls use to set errFlag false inside the mining function and then set back to true if an issue was found, I think we got rid of all those, so the King could get reset to false, part way through getInput, if it were used. So to be safe, a local errFlag is set to false before calling a mining function, because it could have been set to true from a previous mining call, and then if there is an error inside the mining function (i.e., errFlag = true for this call) then a warning is issued and ErrorsFound is set true.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 2]
```diff
@@ -71,6 +71,8 @@ namespace EnergyPlus::IntegratedHeatPump {
 // Using/Aliasing
 using namespace DataLoopNode;
 
+Real64 constexpr WaterDensity(986.0); // standard water density at 60 C
+
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:75]: This was hardcoded into a couple of functions. I just pulled it up here and made it `constexpr`

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 3]
```diff
@@ -104,20 +106,17 @@ void SimIHP(EnergyPlusData &state,
...
         GetIHPInput(state);
-        //    WaterIndex=FindGlycol('WATER') !Initialize the WaterIndex once
         state.dataIntegratedHP->GetCoilsInputFlag = false;
     }
 
     if (CompIndex == 0) {
         DXCoilNum = UtilityRoutines::FindItemInList(CompName, state.dataIntegratedHP->IntegratedHeatPumps);
         if (DXCoilNum == 0) {
-            ShowFatalError(state, "Integrated Heat Pump not found=" + std::string{CompName});
+            ShowFatalError(state, format("Integrated Heat Pump not found={}", CompName));
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:119]: `format` all the things.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 4]
```diff
@@ -138,21 +137,22 @@ void SimIHP(EnergyPlusData &state,
         }
     };
 
-    if (!state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).IHPCoilsSized) SizeIHP(state, DXCoilNum);
+    auto &ihp = state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum);
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:140]: Using `auto &iph = ...` everywhere to shorten lines.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 5]
```diff
@@ -1161,19 +1156,13 @@ void GetIHPInput(EnergyPlusData &state)
...
-    std::string InNodeName;  // Name of coil inlet node
-    std::string OutNodeName; // Name of coil outlet node
-
+    int NumAlphas;                   // Number of variables in String format
+    int NumNums;                     // Number of variables in Numeric format
+    int NumParams;                   // Total number of input fields
+    int MaxNums(0);                  // Maximum number of numeric input fields
+    int MaxAlphas(0);                // Maximum number of alpha input fields
+    std::string InNodeName;          // Name of coil inlet node
+    std::string OutNodeName;         // Name of coil outlet node
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:1165]: Rescope or eliminate local vars where possible.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 6]
```diff
@@ -1863,223 +1726,206 @@ void GetIHPInput(EnergyPlusData &state)
...
-             InNode) ||
-            (state.dataVariableSpeedCoils->VarSpeedCoil(state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SHDWHWHCoilIndex).AirOutletNodeNum !=
-             OutNode)) {
-            ShowContinueError(state,
-                              "Mistaken air node connection: " + CurrentModuleObject +
-                                  state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SHDWHWHCoilName + "-wrong coil node names.");
+        // why was this here
+        //        state.dataVariableSpeedCoils->VarSpeedCoil(ihp.SHDWHWHCoilIndex).AirInletNodeNum = InNode;
+        //        state.dataVariableSpeedCoils->VarSpeedCoil(ihp.SHDWHWHCoilIndex).AirOutletNodeNum = OutNode;
+
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:1778]: The coil inlet and outlet node nums were begin set here, but as far as I can tell they should have already been set elsewhere. I'm not seeing any diffs currently by leaving this out, but I left it commented out in case someone needs to do a forensics deep-dive on this code later.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 7]
```diff
@@ -1863,223 +1726,206 @@ void GetIHPInput(EnergyPlusData &state)
...
-                       std::string{RoutineName} + "Errors found in getting " + CurrentModuleObject +
-                           " input.  Preceding condition(s) causes termination.");
-    } else {
+                       format("{} Errors found in getting {} input. Preceding condition(s) causes termination.", RoutineName, CurrentModuleObject));
+    }
+
+    for (int CoilCounter = 1; CoilCounter <= NumASIHPs; ++CoilCounter) {
+
+        auto &ihp = state.dataIntegratedHP->IntegratedHeatPumps(CoilCounter);
+
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:1822]: The real reason I started this whole thing... the output variables were only being set up of the last coil. This should be corrected now.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 8]
```diff
@@ -2110,120 +1956,110 @@ void SizeIHP(EnergyPlusData &state, int const DXCoilNum)
...
 
-    SizeVarSpeedCoil(state, state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCCoilIndex); // size cooling coil
-    if (ErrorsFound) {
-        ShowFatalError(state, "SizeIHP: failed to size SC coil\"" + state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCCoilName + "\"");
-        ErrorsFound = false;
+    errFlag = false;
+    SizeVarSpeedCoil(state, ihp.SCCoilIndex, errFlag); // size cooling coil
+    if (errFlag) {
+        ShowSevereError(state, format("SizeIHP: failed to size SC coil\"{}\"", ihp.SCCoilName));
+        ErrorsFound = true;
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.cc:1973]: Better error handling on the sizing calls.

File: src/EnergyPlus/IntegratedHeatPump.hh [hunk 9]
```diff
@@ -70,15 +70,15 @@ namespace IntegratedHeatPump {
...
-        SHDWHElecHeatOnMode,
+        Idle,
+        SpaceClg,          // Space Cooling
+        SpaceHtg,          // Space Heating
+        DedicatedWaterHtg, // Dedicated Water Heating
+        SCWHMatchSC,       // Space Cooling Water Heating
+        SCWHMatchWH,
+        SpaceClgDedicatedWaterHtg,
+        SHDWHElecHeatOff,
+        SHDWHElecHeatOn,
```
Comment (mitchute) [inline src/EnergyPlus/IntegratedHeatPump.hh:81]: Remove `Mode` and rename so the values are somewhat intelligible.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 10]
```diff
@@ -3829,7 +3828,11 @@ namespace VariableSpeedCoils {
         if (state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).VSCoilTypeOfNum == CoilDX_HeatPumpWaterHeaterVariableSpeed &&
             state.dataVariableSpeedCoils->MySizeFlag(DXCoilNum)) {
 
-            SizeVarSpeedCoil(state, DXCoilNum);
+            ErrorsFound = false;
+            SizeVarSpeedCoil(state, DXCoilNum, ErrorsFound);
+            if (ErrorsFound) {
+                ShowFatalError(state, format("{}: Failed to size variable speed coil.", RoutineName));
+            }
```
Comment (mitchute) [inline src/EnergyPlus/VariableSpeedCoils.cc:3835]: Better sizing error handling here.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 11]
```diff
@@ -3873,7 +3876,11 @@ namespace VariableSpeedCoils {
         if (!state.dataGlobal->SysSizingCalc && state.dataVariableSpeedCoils->MySizeFlag(DXCoilNum) &&
             !state.dataVariableSpeedCoils->MyPlantScanFlag(DXCoilNum)) {
             // for each furnace, do the sizing once.
-            SizeVarSpeedCoil(state, DXCoilNum);
+            ErrorsFound = false;
+            SizeVarSpeedCoil(state, DXCoilNum, ErrorsFound);
+            if (ErrorsFound) {
+                ShowFatalError(state, format("{}: Failed to size variable speed coil.", RoutineName));
+            }
```
Comment (mitchute) [inline src/EnergyPlus/VariableSpeedCoils.cc:3883]: Same

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 12]
```diff
@@ -4440,7 +4447,7 @@ namespace VariableSpeedCoils {
         state.dataHeatBal->HeatReclaimVS_DXCoil(DXCoilNum).AvailCapacity = 0.0;
     }
 
-    void SizeVarSpeedCoil(EnergyPlusData &state, int const DXCoilNum)
+    void SizeVarSpeedCoil(EnergyPlusData &state, int const DXCoilNum, bool &ErrorsFound)
```
Comment (mitchute) [inline src/EnergyPlus/VariableSpeedCoils.cc:4450]: Let `SizeVarSpeedCoil` propagate its errors back up to the caller.

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 13]
```diff
@@ -10139,22 +10140,30 @@ void WaterThermalTankData::CalcHeatPumpWaterHeater(EnergyPlusData &state, bool c
...
-    } else if (this->WaterThermalTankType == DataPlant::PlantEquipmentType::WtrHeaterStratified) {
+        break;
+    case DataPlant::PlantEquipmentType::WtrHeaterStratified:
         this->CalcWaterThermalTankStratified(state);
-    } else {
+        break;
+    default:
         assert(false);
     }
 }
```
Comment (mitchute) [inline src/EnergyPlus/WaterThermalTanks.cc:10153]: `if/else` to `switch/case` here, and below.

**Review by mitchute — COMMENTED** [review]
The scope blew up well beyond the original issue, but this seems like a good set of cleanups.

**Comment by mitchute** [comment]
The Windows build here looks like a fluke since it failed in the Transition project. I've built and run unit tests locally and it's looking just like the results from the other platforms.

**Comment by Myoldmopar** [comment]
@mitchute so there seems to be something up with that failing unit test.  I think it's the one that occasionally fails on Mac, but now it's failing across the board, so that's new.  I remember talking with you about some of this PR, but I can't remember if that aspect was part of it.  Let me know if you want me to run it to reproduce and/or find the issue so that I can get this in.  Thanks!

**Comment by mitchute** [comment]
@Myoldmopar `SizeVarSpeedCoil` wasn't propagating its errors back up to the caller. Now that it is, that unit test fails because that sizing function fails.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 14]
```diff
@@ -1240,171 +1221,155 @@ void GetIHPInput(EnergyPlusData &state)
         // ErrorsFound will be set to True if problem was found, left untouched otherwise
         VerifyUniqueCoilName(state, CurrentModuleObject, AlphArray(1), ErrorsFound, CurrentModuleObject + " Name");
 
-        state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).Name = AlphArray(1);
-        state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).IHPtype = "AIRSOURCE_IHP";
+        auto &ihp = state.dataIntegratedHP->IntegratedHeatPumps(CoilCounter);
+
+        ihp.Name = AlphArray(1);
+        ihp.IHPtype = "AIRSOURCE_IHP";
```
Comment (amirroth) [inline src/EnergyPlus/IntegratedHeatPump.cc:1227]: Should be an `enum` that can be converted to string for display purposes using a `constexpr std::array<std::string_view>`.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 15]
```diff
@@ -1240,171 +1221,155 @@ void GetIHPInput(EnergyPlusData &state)
...
 
         // AlphArray( 2 ) is the water sensor node
 
-        state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCCoilType = "COIL:COOLING:DX:VARIABLESPEED";
-        state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCCoilName = AlphArray(3);
-        Coiltype = state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCCoilType;
-        CoilName = state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCCoilName;
+        ihp.SCCoilType = "COIL:COOLING:DX:VARIABLESPEED";
```
Comment (amirroth) [inline src/EnergyPlus/IntegratedHeatPump.cc:1231]: Is there a need to store this string? Will it ever be used other than in the `ValidateComponent` call below?

Comment (mitchute) [reply src/EnergyPlus/IntegratedHeatPump.cc:1231]: I'm working more on further propagating the component type enum around. These will eventually go away.

File: src/EnergyPlus/IntegratedHeatPump.hh (hunk 9 above)
Comment (amirroth) [reply src/EnergyPlus/IntegratedHeatPump.hh:81]: You should rename the remaining values to be somewhat intelligible too. I know `SpaceHtgDedicatedWaterHtgElecHeatOff` is long, but it's still better than `SHDWHElecHeatOff`. These long acronyms are crazy making.

File: src/EnergyPlus/IntegratedHeatPump.cc [hunk 16]
```diff
@@ -387,16 +387,16 @@ void SimIHP(EnergyPlusData &state,
...
+        ihp.TankSourceWaterMassFlowRate = 0.0;
         break;
-    case IHPOperationMode::DWHMode:
+    case IHPOperationMode::DedicatedWaterHtg:
         if (IsCallbyWH) // process when called from water loop
         {
             SimVariableSpeedCoils(state,
                                   std::string(),
-                                  state.dataIntegratedHP->IntegratedHeatPumps(DXCoilNum).SCDWHCoolCoilIndex,
+                                  ihp.SCDWHCoolCoilIndex,
```
Comment (amirroth) [inline src/EnergyPlus/IntegratedHeatPump.cc:399]: You may be able to make these into a loop using the `enum OperationMode` as the index.

**Comment by mjwitte** [comment]
@mitchute Is this ready for final review? It's a ways behind develop, so please merge it up.

**Comment by mitchute** [comment]
@mjwitte @Myoldmopar done. There's one failing unit test - see here: https://github.com/NREL/EnergyPlus/pull/9249#issuecomment-1036677937

IMO, that unit test has some deeper issues that this work exposed. So, we either hold this up and address that first or disable the unit test and figure it out after.

**Comment by Myoldmopar** [comment]
Thanks @mitchute.  I'm not a fan of disabling tests willy-nilly, but this fix needs to get in, and your work here just revealed that the test shouldn't have been passing.  No big deal, sometime I'll get some energy to re-enable any disabled unit tests and figure out why they aren't working.  Assuming this continues to be clean I'll merge it tonight.

**Comment by Myoldmopar** [comment]
Tested with latest develop, no problems.  Love these fast running unit test suites..... :)   Anyway, all good here, thanks @mitchute , merging.

**Comment by nealkruis** [comment]
@mitchute, I am making changes that impact the IDF snippets for the test disabled here. I am going to leave this alone for now, but I imagine we should make a new issue to make sure we don't lose track of re-enabling the test down the road.

**Comment by mitchute** [comment]
@nealkruis good idea. I don't remember the particulars here but feel free to make an issue so we don't lose track of it.

**Comment by nealkruis** [comment]
@mitchute I don't really know the context here or why the test had to be disabled. I just noticed that there was an intention to follow up, but it might have been lost. I'll let you and @Myoldmopar sort out how to follow up on this.
