### PR TITLE
AirloopHVAC:UnitarySystem uses outdoor air temperature to size water source dx cooling coils and incorrectly reports autosized supplemental heating coil capacity for CoolReheat control

### LINKED ISSUE #9497: AirloopHVAC:UnitarySystem uses outdoor air temperature to size a water source coil and incorrectly reports autosized supplemental heating coil capacity for CoolReheat control
Issue overview
--------------
Testing of the example file ZoneVSWSHP_wDOAS has confirmed that the water-to-air coils used in UnitarySystems are using outdoor temperature instead of the coil entering water temperature as a sizing parameter. Water coils should use the inlet water temp with the associated cooling capacity as a function of temperature performance curve. The coil model was recently updated to use water temperature but the AirloopHVAC:UnitarySytsem model also requires this update.

Also noticed when a supplemental heating coil is present in AirloopHVAC:UnitarySystem the size of that heating coil should represent the dehumidification control type. For CoolReheat systems, the supplemental heating coil should be at least the size of the cooling coil to offset excess sensible cooling capacity.

Review of supplemental heating coil sizing also identified an issue with how supplemental heaters are identified and differentiated from regular heating coils. This is a simple function argument in the call to the heating coil model.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (ZoneVSWSHP_wDOASe)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes https://github.com/NREL/EnergyPlus/issues/9497
 - The water-source coil capacity calculated by UnitarySystem is now correct and in sync with how the variable speed coil model calculates capacity for this coil type.
 - When a supplemental heating coil is present in AirloopHVAC:UnitarySystem the size of that heating coil should represent the dehumidification control type. For CoolReheat systems, the supplemental heating coil should be at least the size of the cooling coil to offset excess sensible cooling capacity.
 - Partially addresses #9512 for gas and electric coils.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [x] Check any new function arguments for performance impacts
 - [x] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
This branch is a pre-cursor to other maintenance changes that require uniformity in component sizing. Some zone coil models use the zone return air temperature for coil sizing, this is not accurate since the actual zone temperature is what enters the component because the zone models draw air directly from the zone. Additionally, a new method to determine the variable-speed water source coil source temperature (i.e., outdoor temperature or water entering temperature) was implemented that is included here.

File: src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc [hunk 1]
```diff
@@ -140,8 +140,7 @@ Real64 CoolingCapacitySizer::size(EnergyPlusData &state, Real64 _originalValue,
                                     CoilInTemp = this->finalZoneSizing(this->curZoneEqNum).DesCoolCoilInTemp;
                                     CoilInHumRat = this->finalZoneSizing(this->curZoneEqNum).DesCoolCoilInHumRat;
                                 } else {
-                                    CoilInTemp = this->finalZoneSizing(this->curZoneEqNum)
-                                                     .ZoneRetTempAtCoolPeak; // Question whether zone equipment should use return temp for sizing
+                                    CoilInTemp = this->finalZoneSizing(this->curZoneEqNum).ZoneTempAtCoolPeak;
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc]: This has been wrong and ripe for change for some time. Zone equipment draws directly from the zone via the zone exhaust node, hence, zone temp.

File: src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc [hunk 2]
```diff
@@ -167,6 +166,7 @@ Real64 CoolingCapacitySizer::size(EnergyPlusData &state, Real64 _originalValue,
                             if (DDNum > 0 && TimeStepNumAtMax > 0) {
                                 OutTemp = state.dataSize->DesDayWeath(DDNum).Temp(TimeStepNumAtMax);
                             }
+                            if (this->dataCoolCoilType > -1) OutTemp = GetCoilSourceTempUsedForSizing(this->dataCoolCoilType, OutTemp);
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc]: Protected call to new function that mimics GetVSCoilRatedSourceTemp added 7 days ago. If a parent object (or unit test) does not set the coil type, notihng happens, and OutTemp remains unchanged.

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -1534,6 +1534,8 @@ namespace UnitarySystems {
         } else {
             state.dataHVACGlobal->DXCT = 1; // uses normal DX coil flow limits
         }
+        // sizing may need to know what type of coil is being sized
+        state.dataSize->DataCoolCoilType = this->m_CoolingCoilType_Num;
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1538]: UnitarySystem sets this to mimic the sizing of the VS coil model. Currently only cooling is accounted for.

File: src/EnergyPlus/UnitarySystem.cc [hunk 4]
```diff
@@ -15211,6 +15213,9 @@ namespace UnitarySystems {
             } else {
                 this->m_FirstPass = false;
             }
+            // reset the global system type flags
+            state.dataSize->ZoneEqDXCoil = false;
+            // state.dataSize->ZoneEqFanCoil = false; // not used yet
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: These should have been set to false, as is normally done in parent objects.

File: tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc [hunk 5]
```diff
@@ -3827,7 +3827,7 @@ TEST_F(EnergyPlusFixture, VRFTest_SysCurve)
     state->dataZoneEnergyDemand->ZoneSysEnergyDemand(CurZoneNum).RemainingOutputReqToHeatSP = 0.0;
     state->dataAirLoop->AirLoopInputsFilled = true;
 
-    state->dataSize->FinalZoneSizing(state->dataSize->CurZoneEqNum).ZoneRetTempAtCoolPeak = 26.66667;
+    state->dataSize->FinalZoneSizing(state->dataSize->CurZoneEqNum).ZoneTempAtCoolPeak = 26.66667;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc:3830]: Other major change for zone equipment (connected to zone via zone exhaust node), use zone temp, not zone return temp.

File: src/EnergyPlus/Autosizing/BaseSizerWithScalableInputs.cc [hunk 6]
```diff
@@ -155,6 +156,65 @@ void BaseSizerWithScalableInputs::initializeWithinEP(EnergyPlusData &state,
...
+        sourceTemp = RatedAmbAirTempHeat; // overwrite for time being until this gets fixed
+    } break;
+    default: {
+        // catches all parent objects that do not set coilType, do nothing
+        // catches all unit tests that set a different source temp without setting coilType, do nothing
+    } break;
+    }
+    return sourceTemp;
+}
+
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/BaseSizerWithScalableInputs.cc]: This new sizing member function mimics the VS coil model function used to set the coil source temperature (e.g., OAT or entering water T). That function will need to be modified in the near future. This function sets up a method for a parent object (i.e., UnitarySystem) to gather the same information used for sizing calculations. There will obviously be more changes here as the VS coil model sizing calculations evolve.

**Comment by rraustad** [comment]
Diffs in DOAToPTAC_DrawReturnAir.

    - Component Sizing Information, Coil:Cooling:DX:SingleSpeed, SPACE2-1 PTAC CCOIL, Design Size Gross Rated Total Cooling Capacity [W], 3079.87455
    - Component Sizing Information, Coil:Cooling:DX:SingleSpeed, SPACE2-1 PTAC CCOIL, Design Size Gross Rated Sensible Heat Ratio, 0.80041
    + Component Sizing Information, Coil:Cooling:DX:SingleSpeed, SPACE2-1 PTAC CCOIL, Design Size Gross Rated Total Cooling Capacity [W], 3079.88046
    + Component Sizing Information, Coil:Cooling:DX:SingleSpeed, SPACE2-1 PTAC CCOIL, Design Size Gross Rated Sensible Heat Ratio, 0.80040
    - Component Sizing Information, Coil:Cooling:DX:SingleSpeed, SPACE5-1 PTAC CCOIL, Design Size Gross Rated Total Cooling Capacity [W], 6223.85405
    + Component Sizing Information, Coil:Cooling:DX:SingleSpeed, SPACE5-1 PTAC CCOIL, Design Size Gross Rated Total Cooling Capacity [W], 6223.81921

**Comment by mjwitte** [comment]
> This is inaccurate for zone coils since the actual coil inlet temperature is the zone temp (or zone temp mixed with outdoor air), without inclusion of lighting heat gain

Are you sure this is not stepping on the changes to let zone equipment draw from a plenum? See https://github.com/NREL/EnergyPlus/pull/8719

**Comment by Myoldmopar** [comment]
I'll hold from diving in until @mjwitte's comment is addressed.

**Comment by rraustad** [comment]
No, this is not stepping on that change. ZoneRetTempAtCoolPeak was used long before #8719.

I agree that IF the zone system is drawing from the return node the coil should be sized based on the zone temperature adjusted for the heat gain applied to the return node using the operating mass flow rates of the zone system at the time of peak. ZoneRetTempAtCoolPeak is calculated during sizing based on autosized zone mass flow rate and is really an air loop sizing variable (used incorrectly for zone equipment). If the zone equipment air flow is hard-sized and capacity is autosized, this T variable is incorrect. ZoneRetTempAtCoolPeak is also used in setCoolCoilInletTempForZoneEqSizing, but only if an ATMixer is used. This is also wrong because OAfrac can be different from that used during sizing calculations. However it is here where the proper mixing calculation is performed and where I believe the zone inlet node connection can be addressed. 

    if (zoneEqSizing.ATMixerVolFlow > 0.0) {
        // adjust for central DOAS AT mixer mixed inlet temp
        coilInTemp = (1.0 - outAirFrac) * finalZoneSizing.ZoneRetTempAtCoolPeak + outAirFrac *
        zoneEqSizing.ATMixerCoolPriDryBulb;
    } else if (zoneEqSizing.OAVolFlow > 0.0) {
        // adjust for raw OA mixed inlet temp
        coilInTemp = (1.0 - outAirFrac) * finalZoneSizing.ZoneTempAtCoolPeak + outAirFrac * finalZoneSizing.OutTempAtCoolPeak;
    } else {
        // use zone condition for sizing zone equipment
        coilInTemp = finalZoneSizing.ZoneTempAtCoolPeak;
    }

There should not be a selective calling ladder based on the equipment type or whether an ATMixer or OA mixer is used. This calling ladder will be whittled down to where only the setCool(Heat)CoilInletTempForZoneEqSizing function is used to calculate coil inlet temp for all zone equipment. It's then that return air heat gain can be applied correctly using the hard-sized or autosized air flow rate and hard-sized or autosized OA or ATMixer flow rate with a mixing equation (QHeatGainToReturn will need to be saved during sizing).

    setCoolCoilInletTempForZoneEqSizing()

    if (state.dataSize->ZoneEqDXCoil) {
        if (this->zoneEqSizing(this->curZoneEqNum).ATMixerVolFlow > 0.0) { // NEW ATMixer coil sizing method
            Real64 DesMassFlow = DesVolFlow * state.dataEnvrn->StdRhoAir;
            CoilInTemp = setCoolCoilInletTempForZoneEqSizing(
                setOAFracForZoneEqSizing(state, DesMassFlow, zoneEqSizing(this->curZoneEqNum)),
                zoneEqSizing(this->curZoneEqNum),
                finalZoneSizing(this->curZoneEqNum));
            CoilInHumRat = setCoolCoilInletHumRatForZoneEqSizing(
                setOAFracForZoneEqSizing(state, DesMassFlow, zoneEqSizing(this->curZoneEqNum)),
                zoneEqSizing(this->curZoneEqNum),
                finalZoneSizing(this->curZoneEqNum));
        } else if (this->zoneEqSizing(this->curZoneEqNum).OAVolFlow > 0.0) {
            CoilInTemp = this->finalZoneSizing(this->curZoneEqNum).DesCoolCoilInTemp;
            CoilInHumRat = this->finalZoneSizing(this->curZoneEqNum).DesCoolCoilInHumRat;
        } else {
            CoilInTemp = this->finalZoneSizing(this->curZoneEqNum)
                         .ZoneRetTempAtCoolPeak; // Question whether zone equipment should use return temp for sizing
            CoilInHumRat = this->finalZoneSizing(this->curZoneEqNum).ZoneHumRatAtCoolPeak;
        }
    } else if (this->zoneEqFanCoil) {
        // use fan coil flow (i.e., set by parent) or flow used during sizing?
        Real64 DesMassFlow = this->finalZoneSizing(this->curZoneEqNum).DesCoolMassFlow;
        CoilInTemp = setCoolCoilInletTempForZoneEqSizing(
            setOAFracForZoneEqSizing(state, DesMassFlow, zoneEqSizing(this->curZoneEqNum)),
            zoneEqSizing(this->curZoneEqNum),
            finalZoneSizing(this->curZoneEqNum));
        CoilInHumRat = setCoolCoilInletHumRatForZoneEqSizing(
            setOAFracForZoneEqSizing(state, DesMassFlow, zoneEqSizing(this->curZoneEqNum)),
            zoneEqSizing(this->curZoneEqNum),
            finalZoneSizing(this->curZoneEqNum));
    } else {
        CoilInTemp = this->finalZoneSizing(this->curZoneEqNum).DesCoolCoilInTemp;
        CoilInHumRat = this->finalZoneSizing(this->curZoneEqNum).DesCoolCoilInHumRat;
    }

These variables are wrong when zone equipment hard-sizes air flow rate and/or outdoor air flow rate and autosizes capacity and the reason for creating the setCool(Heat)CoilInletTempForZoneEqSizing functions.

    state.dataSize->FinalZoneSizing(CtrlZoneNum).DesCoolCoilInTemp =
          OAFrac * state.dataSize->DesDayWeath(DDNum).Temp(TimeStepAtPeak) +
          (1.0 - OAFrac) * state.dataSize->FinalZoneSizing(CtrlZoneNum).ZoneTempAtCoolPeak;


    CalcZoneLeavingConditions

    // Add heat-to-return from lights
    TempRetAir += QRetAir / (MassFlowRA * CpAir);

This is a long explaination to say that this little tweak to change ZoneRetTempAtCoolPeak to ZoneTempAtCoolPeak is a move towards unifying the sizing routines. As you can see there will be plenty more changes in the future. One little step at a time.

**Comment by rraustad** [comment]
I'll put this change to which coil inlet temp to use in a different branch. That leaves only the new VS coil function in this branch.

**Comment by rraustad** [comment]
>> Are you sure this is not stepping on the changes to let zone equipment draw from a plenum? See https://github.com/NREL/EnergyPlus/pull/8719

I'm sure now

**Comment by mjwitte** [comment]
@rraustad Is there a defect file for this 9497?

**Comment by rraustad** [comment]
Yes, and no. This change is to correct the last eio diff in #9273. ZoneVSWSHP_wDOAS uses ZoneHVAC:WaterToAirHeatPump (PTUnit). I guess I could try to create one using UnitarySystem if it were necessary. When I merge this in with 9273 the diff should be gone. You want an example file to see the coil size change?

**Comment by mjwitte** [comment]
@rraustad I didn't understand the connection between this an #9273. I can run ZoneVSWSHP_wDOAS  with the 9273 branch to see the change.

**Comment by rraustad** [comment]
No, you can't. You'll only see the change when UnitarySystem manages the PTUnit. I am making a defect file now.

**Comment by rraustad** [comment]
Are you going to merge this branch into 9273 locally to see the change?

**Comment by mjwitte** [comment]
> No, you can't. You'll only see the change when UnitarySystem manages the PTUnit. I am making a defect file now.

Now I'm more confused. I thought that's what 9273 did (switch to UnitarySystem running the PTUnit). 

> Are you going to merge this branch into 9273 locally to see the change?

I wasn't planning to. I'm still misunderstanding the connections here.

**Comment by mjwitte** [comment]
> Are you going to merge this branch into 9273 locally to see the change?

Oh, I see. Running ZoneVSWSHP_wDOAS  doesn't exercise the changed code unless it's merged with 9273 so that it's actually running UnitarySystem. If you've made a Unitary idf version of this, I'll use that. Otherwise I may make one here.

**Comment by rraustad** [comment]
I see example file UnitarySystem_VSHeatPumpWaterToAirEquationFit. So I guess with this branch I will create a diff in that file.

**Comment by mjwitte** [comment]
Actually, it won't because that one isn't autosized. I'm borrowing from that to make a unitary version that is autosized.

**Comment by mjwitte** [comment]
Here's my attempt at [Unitary-ZoneVSWSHP_wDOAS.idf.txt](https://github.com/NREL/EnergyPlus/files/8943701/Unitary-ZoneVSWSHP_wDOAS.idf.txt). It's not equivalent to ZoneVSWSHP_wDOAS.idf, because, well, I don't know why, but this sizes to a much larger airflow rate (1.45) than the ZoneHVAC:WaterToAirHeatPump version (0.938). More confusing is this idf has the same sizing results with develop and this branch.

**Comment by rraustad** [comment]
This is a tangled web. First, the CapFT term was missing for this coil in this branch. I took this from the #9273 branch. Once this was added to this branch, the capacity the UnitarySystem found was the same as the VS cooling coil.

    if (this->m_CoolingCoilType_Num == DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit) {
        state.dataSize->DataTotCapCurveIndex = VariableSpeedCoils::GetVSCoilCapFTCurveIndex(state, this->m_CoolingCoilIndex, ErrFound);
        // VS coil model does not check for flow/capacity ratio, this will disable that test in Capacity sizer
        // state.dataSize->DataIsDXCoil = true;
    }

The above, and this branch, allow the UnitarySystem to get the same capacity as the VS coil. But here, where the VS coil is called, the VS coil capacity resets what the UnitarySystem found and then reports the UnitarySystem correctly after this point. 

    state.dataSize->DXCoolCap = VariableSpeedCoils::GetCoilCapacityVariableSpeed(
        state, DataHVACGlobals::cAllCoilTypes(this->m_CoolingCoilType_Num), this->m_CoolingCoilName, ErrFound);
    EqSizing.DesCoolingLoad = state.dataSize->DXCoolCap;
    EqSizing.DesHeatingLoad = state.dataSize->DXCoolCap;

image

What you can't see is that the UnitarySystem needs to find the same air flow and capacity as the child components to set the correct capacity (e.g., capacity = max(coolingCapacity, heatingCapacity). The way this is set up now, to mine data from the VS coil after the UnitarySystem air flow is sized, the VS coil model eio results are in the middle of the UnitarySystem eio reports.

    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supply Air Flow Rate [m3/s], 1.44475
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 1.44475
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 1.44475
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size No Load Supply Air Flow Rate [m3/s], 1.44475
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Total Cooling Capacity [W], 16786.10120
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Water Flow Rate [m3/s], 9.48087E-004
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Sensible Cooling Capacity [W], 13001.89608
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16786.10120
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Air Flow Rate [m3/s], 0.70309
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Water Flow Rate [m3/s], 7.10865E-004
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Cooling Capacity [W], 16786.10120
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Heating Capacity [W], 16786.10120
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Maximum Supply Air Temperature [C], 30.00000

There is one more chunk of code in the #9273 branch that is needed here. I'll do that now and report back.

**Comment by rraustad** [comment]
I had the cheat to get this UnitarySystem file to act as if it were a PTUnit file. For example this chunk of code shown above should have had the sysType included. Because this branch did not have those enums I took them out. But I can't take them out because that could change the answer in other UnitarySystem files which would be a never ending battle to get diffs to 0. When I include the correct enums, I also had to add `this->m_sysType == SysType::Unitary` here to get this defect file to show the correct results. It would have been easier to pull this branch into #9273 to see the difference in results.

                if ((this->m_sysType == SysType::PackagedWSHP || this->m_sysType == SysType::Unitary) &&
                    this->m_CoolingCoilType_Num == DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit) {
                    state.dataSize->DataTotCapCurveIndex = VariableSpeedCoils::GetVSCoilCapFTCurveIndex(state, this->m_CoolingCoilIndex, ErrFound);
                    // VS coil model does not check for flow/capacity ratio, this will disable that test in Capacity sizer
                    // state.dataSize->DataIsDXCoil = true;
                }

There was another chunk of code added (3A) which adjusts the UnitarySystem air flow rate according to the VS coil model's air flow to capacity ratio, not shown here.

And finally now you can see the correct result. Now I need to pull those `this->m_sysType == SysType::Unitary` back out of here so I only affect specific results. When these branches are finally merged, all the sysType checks need to be pulled out systematically.

    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size No Load Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Total Cooling Capacity [W], 16786.10120
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Water Flow Rate [m3/s], 9.48087E-004
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Sensible Cooling Capacity [W], 13001.89608
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16786.10120
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Air Flow Rate [m3/s], 0.70309
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Water Flow Rate [m3/s], 7.10865E-004
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Cooling Capacity [W], 16786.10120
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Heating Capacity [W], 16786.10120
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Maximum Supply Air Temperature [C], 30.00000
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, User-Specified Maximum Supply Air Temperature [C], 60.00000
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supplemental Heating Coil Nominal Capacity [W], 16786.10120
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, User-Specified Supplemental Heating Coil Nominal Capacity [W], 32000.00000
    Component Sizing Information, Fan:OnOff, ZONE 1 FAN, Design Size Maximum Flow Rate [m3/s], 0.93772
    Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 16786.10120
    Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, User-Specified Nominal Capacity [W], 32000.00000

**Comment by rraustad** [comment]
@mjwitte if you feel compelled to run the defect file, you would need to add `this->m_sysType == SysType::Unitary` in a few key places. The CapFT get and in 3A so that code gets executed. I think showing how this code affects the answer (above) is good enough as far as documenting  this defect. These `if (sysType)` blocks will be one of the first things removed since I doubt they will affect many UnitarySystem files (i.e., easy review of simple changes).

File: src/EnergyPlus/UnitarySystem.cc [hunk 7]
```diff
@@ -1866,7 +1874,34 @@ namespace UnitarySystems {
...
+                this->m_MaxHeatAirVolFlow == DataSizing::AutoSize) {
+                int normSpeed = state.dataVariableSpeedCoils->VarSpeedCoil(this->m_HeatingCoilIndex).NumOfSpeeds;
+                Real64 heatingAirFlowToCapacityRatio =
+                    state.dataVariableSpeedCoils->VarSpeedCoil(this->m_HeatingCoilIndex).MSRatedAirVolFlowPerRatedTotCap(normSpeed);
+                // is this a coincidence or does VS coil apply FlowToCap ratio to adjusted heating = cooling coil capacity?
+                EqSizing.DesHeatingLoad *= coolingToHeatingCapRatio;
+                EqSizing.HeatingAirVolFlow = EqSizing.DesHeatingLoad * heatingAirFlowToCapacityRatio;
+            }
+        }
+
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1903]: Needs to include this->m_sysType == SysType::Unitary in the outer if as a minimum and possibly the 2nd if for heating coils (but I don't think it would be needed since the heating load is smaller) to see diffs in the defect file.

File: src/EnergyPlus/UnitarySystem.hh [hunk 8]
```diff
@@ -224,6 +224,9 @@ namespace UnitarySystems {
             Unitary,          // AirloopHVAC:UnitarySystem
             CoilCoolingDX,    // CoilSystem:Cooling:DX
             CoilCoolingWater, // CoilSystem:Cooling:Water
+            PackagedAC,       // ZoneHVAC:PackagedTerminalAirConditioner
+            PackagedHP,       // ZoneHVAC:PackagedTerminalHeatPump
+            PackagedWSHP,     // ZoneHVAC:WaterToAirHeatPump
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.hh]: Needed to pull these over as well to use specific system type logicals.

File: src/EnergyPlus/UnitarySystem.cc [hunk 9]
```diff
@@ -1696,6 +1698,12 @@ namespace UnitarySystems {
                     state.dataSize->DataTotCapCurveIndex = VariableSpeedCoils::GetVSCoilCapFTCurveIndex(state, this->m_CoolingCoilIndex, ErrFound);
                     state.dataSize->DataIsDXCoil = true;
                 }
+                if ((this->m_sysType == SysType::PackagedWSHP) &&
+                    this->m_CoolingCoilType_Num == DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit) {
+                    state.dataSize->DataTotCapCurveIndex = VariableSpeedCoils::GetVSCoilCapFTCurveIndex(state, this->m_CoolingCoilIndex, ErrFound);
+                    // VS coil model does not check for flow/capacity ratio, this will disable that test in Capacity sizer
+                    // state.dataSize->DataIsDXCoil = true;
+                }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1706]: Would need to include this->m_sysType == SysType::Unitary here since the CapFT term is what gets modified by the function GetCoilSourceTempUsedForSizing (actually this function modifies OAT that is used in the CapFT equation).

File: src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc]: OutTemp is only used in the CapFT equation at line 189 below.

    TotCapTempModFac = CurveManager::CurveValue(state, this->dataTotCapCurveIndex, CoilInWetBulb, OutTemp);

File: src/EnergyPlus/UnitarySystem.cc (hunk 9 above)
Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:1706]: Why does this check system type?
```
 if ((this->m_sysType == SysType::PackagedWSHP) &&
                    this->m_CoolingCoilType_Num == DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit) {
```
Shouldn't any system type with `Coil_CoolingWaterToAirHPVSEquationFit` fetch the `CoilCapFTCurveIndex`? I still feel that this PR is making way too many changes. If UnitarySystem with Coil_CoolingWaterToAirHPVSEquationFit is not sizing correctly, it seems this should have changes only in UnitarySystem.cc and CoolingCapacitySizing.cc, nothing more.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:1706]: > Shouldn't any system type with Coil_CoolingWaterToAirHPVSEquationFit fetch the CoilCapFTCurveIndex?

Yes it should. But if I do that the answers in #9273 example files without diffs at this point could now have diffs. I think I'll just merge these changes into 9273 and delete this PR.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:1706]: Don't be hasty. My point is if unitary system with VS water-to-air is doing something incorrectly, then we should fix it without any consideration of 9273.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:1706]: Then I can remove the sysType in this branch and in 9273. Either way these changes are needed for the last diff in 9273.

 > it seems this should have changes only in UnitarySystem.cc and CoolingCapacitySizing.cc

And this comment?

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:1706]: There's the new function `BaseSizerWithScalableInputs::GetCoilSourceTempUsedForSizing` as part of this PR. Isn't there an existing function that can be called here?

**Comment by rraustad** [comment]
Defect file results:

develop:

     Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supply Air Flow Rate [m3/s], 1.44475
     Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 1.44475
     Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 1.44475
     Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size No Load Supply Air Flow Rate [m3/s], 1.44475
     Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Total Cooling Capacity [W], 16786.10120
     Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Air Flow Rate [m3/s], 0.93772
     Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16786.10120
     Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Air Flow Rate [m3/s], 0.70309
     Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Cooling Capacity [W], 16786.10120
     Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Heating Capacity [W], 16786.10120

this branch:

    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size No Load Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Total Cooling Capacity [W], 16786.10120
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16786.10120
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Air Flow Rate [m3/s], 0.70309
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Cooling Capacity [W], 16786.10120
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Nominal Heating Capacity [W], 16786.10120

**Comment by rraustad** [comment]
Both diff files look the same and the UnitarySystem air flow now matches the VS coil air flow:

    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supply Air Flow Rate [m3/s], 2.62985
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Heating Supply Air Flow Rate [m3/s], 2.62985
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Cooling Supply Air Flow Rate [m3/s], 2.62985
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size No Load Supply Air Flow Rate [m3/s], 2.62985
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supply Air Flow Rate [m3/s], 5.51175
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Heating Supply Air Flow Rate [m3/s], 5.51175
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Cooling Supply Air Flow Rate [m3/s], 5.51175
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size No Load Supply Air Flow Rate [m3/s], 5.51175
      Component Sizing Information, COIL:COOLING:DX:VARIABLESPEED, MAIN COOLING COIL 1, Design Size Rated Total Cooling Capacity [W], 53995.63164
      Component Sizing Information, COIL:COOLING:DX:VARIABLESPEED, MAIN COOLING COIL 1, Design Size Rated Air Flow Rate [m3/s], 5.51175
    - Component Sizing Information, Fan:VariableVolume, SUPPLY FAN 1, Design Size Maximum Flow Rate [m3/s], 2.62985
    + Component Sizing Information, Fan:VariableVolume, SUPPLY FAN 1, Design Size Maximum Flow Rate [m3/s], 5.51175

**Comment by rraustad** [comment]
ZoneVSWSHP_wDOAS result in develop:

    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Total Cooling Capacity [W], 16786.10120
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Water Flow Rate [m3/s], 9.48087E-004
    Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Sensible Cooling Capacity [W], 13001.89608
    Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 0.93772
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16786.10120
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Air Flow Rate [m3/s], 0.70309
    Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Water Flow Rate [m3/s], 7.10865E-004
    Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 0.70309
    Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, User-Specified No Load Supply Air Flow Rate [m3/s], 0.00000
    Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, Design Size Maximum Supply Air Temperature from Supplemental Heater [C], 30.00000
    Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, User-Specified Maximum Supply Air Temperature from Supplemental Heater [C], 60.00000
    Component Sizing Information, Fan:OnOff, ZONE 1 FAN, Design Size Maximum Flow Rate [m3/s], 0.93772

    ZoneHVAC:WaterToAirHeatPump,
      Zone1WTAHP,              !- Name
      FanAndCoilAvailSched,    !- Availability Schedule Name
      Zone 1 Outlet Node,      !- Air Inlet Node Name
      Zone 1 Inlet Node,       !- Air Outlet Node Name
      OutdoorAir:Mixer,        !- Outdoor Air Mixer Object Type
      Zone 1 Mixer,            !- Outdoor Air Mixer Name
      Autosize,                !- Cooling Supply Air Flow Rate {m3/s}
      Autosize,                !- Heating Supply Air Flow Rate {m3/s}
      ,                        !- No Load Supply Air Flow Rate {m3/s}
      0.0,                     !- Cooling Outdoor Air Flow Rate {m3/s}
      0.0,                     !- Heating Outdoor Air Flow Rate {m3/s}
      ,                        !- No Load Outdoor Air Flow Rate {m3/s}

**Comment by mjwitte** [comment]
@rraustad Much better. So, this has a huge impact on the airflow sizing for unitary. I'm not seeing the impact of the source temperature, but maybe that gets lost in the weeds here? I'll look at this a bit more shortly, but for now please update the issue and PR titles/descriptions to include the air flow changes.

**Comment by rraustad** [comment]
The source temperature issue is hidden in UnitarySystem because the call to VS coils (or any cooling coil) overwrites the capacity found by UnitarySystem as shown here. This is after UnitarySystem determines the air flow and capacity used to make a decision on final system air flow and capacity but before UnitarySystem reports capacity. That's why the eio shows UnitarySystem air flow rates (now they match), then VS coil sizing info, and then more UnitarySystem eio results including capacity (capacity matched before this change).

            state.dataSize->DXCoolCap = VariableSpeedCoils::GetCoilCapacityVariableSpeed(
                state, DataHVACGlobals::cAllCoilTypes(this->m_CoolingCoilType_Num), this->m_CoolingCoilName, ErrFound);
            EqSizing.DesCoolingLoad = state.dataSize->DXCoolCap;
            EqSizing.DesHeatingLoad = state.dataSize->DXCoolCap;

**Comment by mjwitte** [comment]
ZoneVSWSHP_wDOAS has different flow rates for heating and cooling in the parent unit, but the unitary version here does not.
```
 Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 0.93802
 Component Sizing Information, ZoneHVAC:WaterToAirHeatPump, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 0.70332

 Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supply Air Flow Rate [m3/s], 0.93802
 Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Heating Supply Air Flow Rate [m3/s], 0.93802
 Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Cooling Supply Air Flow Rate [m3/s], 0.93802
```

**Comment by rraustad** [comment]
So for a heat pump which one is correct? Should PTUnit have the same air flow or should UnitarySystem allow different flow rates for heating and cooling? And only for WSHP? or for all HPs?

**Comment by rraustad** [comment]
I do recall that example file having different cooling/heating flow rates, and it was working when if (sysType) was used in step 3A. And then I pulled it out to treat all system types the same. So I guess I'll put it back in.

**Comment by rraustad** [comment]
Well, I tried. The defect file is a UnitarySystem, and the ZoneVSWSHP_wDOAS is a PTUnit.

Line 1913 is the new line I added. I certainly can't open that up to all UnitarySystems.
I could probably get them to match using if (this->sysType == Unitary && VSCoil && ZoneEquipment)

image

File: src/EnergyPlus/UnitarySystem.cc [hunk 10]
```diff
@@ -1866,15 +1880,44 @@ namespace UnitarySystems {
...
+        // STEP 3B: use the greater of cooling and heating air flow rates for system flow
         // previous version of E+ used maximum flow rate for unitary systems. Keep this methodology for now.
         // Delete next 2 lines and uncomment 2 lines inside next if (HeatPump) statement to allow non-heat pump systems to operate at different flow
         // rates (might require additional change to if block logic).
-        EqSizing.CoolingAirVolFlow = max(EqSizing.CoolingAirVolFlow, EqSizing.HeatingAirVolFlow);
-        EqSizing.HeatingAirVolFlow = EqSizing.CoolingAirVolFlow;
+        if (state.dataSize->CurZoneEqNum == 0 || !isVarSpeedCoolCoil) {
+            EqSizing.CoolingAirVolFlow = max(EqSizing.CoolingAirVolFlow, EqSizing.HeatingAirVolFlow);
+            EqSizing.HeatingAirVolFlow = EqSizing.CoolingAirVolFlow;
+        }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1916]: I'm not at all sure about this logic here at 1913 or below at 1920. CI will show if problems exist.

**Comment by mjwitte** [comment]
@rraustad This is looking good. Yet another one more thing. The supplemental heating coil design size is different between the WSHP and Unitary versions.
```
ZoneVSWSHP_wDOAS 
 Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16791.58984
 Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 13049.00059
 Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, User-Specified Nominal Capacity [W], 32000.00000

Unitary-ZoneVSWSHP_wDOAS
 Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 16791.58984
 Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 16791.58984
 Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, User-Specified Nominal Capacity [W], 32000.00000
```
The main heating coil sizes match, so this case appears that the WSHP is incorrect?

**Comment by rraustad** [comment]
This is a question of whether a non-DX coil should match the DX coil (usually cooling). For UnitarySystem, if not cool-reheat dehum control, then the supp coil could be sized to meet the heating load. Same can be said for the non-DX heating coil. I can't recall what happens now for supp heating coils regarding size. I'll look to see where this happens.

**Comment by rraustad** [comment]
@mjwitte this last change depends on CI results and whether/how to allow supp coils to meet only the heating load.

    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, Design Size Supplemental Heating Coil Nominal Capacity [W], 13049.00059
    Component Sizing Information, AirLoopHVAC:UnitarySystem, ZONE1WTAHP, User-Specified Supplemental Heating Coil Nominal Capacity [W], 32000.00000
    Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 13049.00059
    Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, User-Specified Nominal Capacity [W], 32000.00000

File: src/EnergyPlus/UnitarySystem.cc [hunk 11]
```diff
@@ -2722,7 +2765,11 @@ namespace UnitarySystems {
             state.dataSize->UnitaryHeatCap = EqSizing.DesHeatingLoad;
 
         } else {
-            state.dataSize->UnitaryHeatCap = this->m_DesignHeatingCapacity;
+            if (state.dataSize->CurZoneEqNum == 0 || !isVarSpeedCoolCoil) {
+                state.dataSize->UnitaryHeatCap = this->m_DesignHeatingCapacity;
+            } else {
+                EqSizing.HeatingCapacity = false;
+            }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: To be clear, I believe this needs to be like this but am weary of diffs. UnitarySystem always sets the supp heater size = heating coil size. For HPs this is the same size as the cooling coil. For non-HPs this is the same size as the heating coil which should be sized to meet only the heating load. The above works for the defect file and causes no diffs, but ... Maybe I should try this while its fresh in our minds?

    if (this->m_DehumidControlType_Num == DehumCtrlType::CoolReheat) {
        set same size as cooling coil
    } else {
        let heating load dictate size regardless of HP configuration (I was offered a 5, 10 or 15 kW strip heat for my 3 ton HP (10 kW))
    }

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc]: This looks more general than ` if (state.dataSize->CurZoneEqNum == 0 || !isVarSpeedCoolCoil) {`. But the CoolReheat block needs to set to the max of cooling coil or heating load.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: OK, will give it a shot.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: This still works for the UnitarySystem file. Am running unit tests now. Anything stand out?

            if (this->m_DehumidControlType_Num == DehumCtrlType::CoolReheat) {
                state.dataSize->UnitaryHeatCap = max(this->m_DesignCoolingCapacity, this->m_DesignHeatingCapacity);
            } else {
                EqSizing.HeatingCapacity = false;
            }

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc]: No, other than I don't understand why the else isn't `state.dataSize->UnitaryHeatCap = this->m_DesignHeatingCapacity;`

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: Well, I guess it could be. Resetting EqSizing.HeatingCapacity lets the heating coil size normally instead of using the parent data.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: No, that's the way it was before.

    state.dataSize->UnitaryHeatCap = this->m_DesignHeatingCapacity;

**Comment by rraustad** [comment]
5Zone_Unitary_HXAssistedCoil supp heater "design size" increase by 2x:

    AirLoopHVAC:UnitarySystem,
      GasHeat DXAC Furnace 1,  !- Name
      Setpoint,                !- Control Type
      ,                        !- Controlling Zone or Thermostat Location
      CoolReheat,              !- Dehumidification Control Type

But why doesn't it match the cooling coil size? Gone fishin'

      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Nominal Heating Capacity [W], 28151.00449
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supplemental Heating Coil Nominal Capacity [W], 28151.00449
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supplemental Heating Coil Nominal Capacity [W], 56749.30407
      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, User-Specified Supplemental Heating Coil Nominal Capacity [W], 32000.00000
      Component Sizing Information, COIL:COOLING:DX:VARIABLESPEED, MAIN COOLING COIL 1, Design Size Rated Total Cooling Capacity [W], 53882.19699

**Comment by rraustad** [comment]
This is bad, ASHRAE901_HotelSmall_STD2019_Denver. This is not a supplemental heater, there are no supplemental heaters in this example file. So the last code change is incorrect.

    - Component Sizing Information, Coil:Heating:Fuel, SAC_FRONTOFFICE HEATING COIL, Design Size Nominal Capacity [W], 9914.82495
    + Component Sizing Information, Coil:Heating:Fuel, SAC_FRONTOFFICE HEATING COIL, Design Size Nominal Capacity [W], 0.00000

**Comment by rraustad** [comment]
@mjwitte I am trying to resolve how a heating coil and supp heating coil size in UnitarySystem vs PackagedTerminalHeatPump. The problem is that both these coil applications (main vs supp coil) call HeatingCapacitySizing and setting globals like ZoneEqSizing().HeatingCapacity and ZoneEqSizing().DesHeatingLoad affect both coils.

**Comment by rraustad** [comment]
@mjwitte this seems like a good place to stop. 2 files had a large increase in UnitarySystem air flow to match the cooling coil air flow size. 1 had an increase in supp heater size since it was a CoolReheat application. 1 added a design-size supp heater capacity to compare to the user specified value.

5Zone_Unitary_VSDesuperheatWaterHeater
5Zone_Unitary_VSDesuperheater

    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supply Air Flow Rate [m3/s], 2.62064
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Heating Supply Air Flow Rate [m3/s], 2.62064
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Cooling Supply Air Flow Rate [m3/s], 2.62064
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size No Load Supply Air Flow Rate [m3/s], 2.62064
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supply Air Flow Rate [m3/s], 5.50017
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Heating Supply Air Flow Rate [m3/s], 5.50017
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Cooling Supply Air Flow Rate [m3/s], 5.50017
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size No Load Supply Air Flow Rate [m3/s], 5.50017
    - Component Sizing Information, Fan:VariableVolume, SUPPLY FAN 1, Design Size Maximum Flow Rate [m3/s], 2.62064
    + Component Sizing Information, Fan:VariableVolume, SUPPLY FAN 1, Design Size Maximum Flow Rate [m3/s], 5.50017
      Component Sizing Information, COIL:COOLING:DX:VARIABLESPEED, MAIN COOLING COIL 1, Design Size Rated Total Cooling Capacity [W], 53882.19699
      Component Sizing Information, COIL:COOLING:DX:VARIABLESPEED, MAIN COOLING COIL 1, Design Size Rated Air Flow Rate [m3/s], 5.50017

5Zone_Unitary_HXAssistedCoil

    AirLoopHVAC:UnitarySystem,
      GasHeat DXAC Furnace 1,  !- Name
      Setpoint,                !- Control Type
      ,                        !- Controlling Zone or Thermostat Location
      CoolReheat,              !- Dehumidification Control Type


      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Nominal Cooling Capacity [W], 56749.30407
      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Nominal Heating Capacity [W], 28151.00449
      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Maximum Supply Air Temperature [C], 18.00000
      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, User-Specified Maximum Supply Air Temperature [C], 80.00000
    - Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supplemental Heating Coil Nominal Capacity [W], 28151.00449
    + Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, Design Size Supplemental Heating Coil Nominal Capacity [W], 56749.30407
      Component Sizing Information, AirLoopHVAC:UnitarySystem, GASHEAT DXAC FURNACE 1, User-Specified Supplemental Heating Coil Nominal Capacity [W], 32000.00000
    - Component Sizing Information, Coil:Heating:Fuel, HUMIDISTAT REHEAT COIL 1, Design Size Nominal Capacity [W], 28151.00449
    + Component Sizing Information, Coil:Heating:Fuel, HUMIDISTAT REHEAT COIL 1, Design Size Nominal Capacity [W], 56749.30407

Big change here same as above, 16.14 tons cooling = 193680 Btu/hr supp heating coil capacity.

image

UnitarySystem_MultiSpeedCoils_SingleMode

    + Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 35500.00000
      Component Sizing Information, Coil:Heating:Fuel, HEAT PUMP DX SUPP HEATING COIL 1, User-Specified Nominal Capacity [W], 45000.00000

File: src/EnergyPlus/UnitarySystem.cc [hunk 12]
```diff
@@ -2756,9 +2799,16 @@ namespace UnitarySystems {
                 state.dataSize->DataFractionUsedForSizing = 1.0;
                 SizingMethod = DataHVACGlobals::AutoCalculateSizing;
                 TempSize = DataSizing::AutoSize;
+                // pass design size to supplemental heater
+                state.dataSize->SuppHeatCap = max(this->m_DesignCoolingCapacity, this->m_DesignHeatingCapacity);
+            } else if (this->m_Humidistat && this->m_DehumidControlType_Num == DehumCtrlType::CoolReheat) {
+                state.dataSize->SuppHeatCap = max(this->m_DesignCoolingCapacity, this->m_DesignHeatingCapacity);
+            } else {
+                state.dataSize->SuppHeatCap = this->m_DesignHeatingCapacity;
             }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:2808]: The one issue with this is that this->m_DesignHeatingCapacity is the capacity of the heating coil. For a HP in a cooling dominated climate, this is the same size as the cooling coil (heating capacity was upsized to match). So this is not the raw heating load when a HP is used. If that HP does not use CoolReheat, do we want the supplemental heating coil capacity to match the heating coil, or be sized to meet the heating load? I just ran a local test suite to see what diffs this correction would cause (i.e., using saveRawHeatingCapacity here in the else). Only 1 additional example file had a diff, the HVACTemplate-5ZoneUnitarySystem file.

image

Not the diff I was expecting, I thought the supp heater would have a lower capacity. That means this HP is not meeting the heating load?

HVACTemplate-5ZoneUnitarySystem diff:

image

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:2808]: Ah, the UnitarySystem finds cooling = 5kW and heating = 10kW. The WSHP has it's own sizing routine and finds cooling = 5kW and sets heating cap = cooling cap. The UnitarySystem calls over to the WSHP and gets the coil sizes. So the 10 kW was the original heating capacity. Just another never ending thing that needs fixing. I'll post an issue.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:2808]: I'm surprised we can size anything in E+. Here's a single-zone HP of 5 kW size where total cooling = 5 kW and heating (supposedly) = 10 kW. The 5 kW HP has no problem meeting the winter design day zone load and holds Tstat temp. On the design days, the coils never exceed 3.5 kW although the cooling coil design sensible capacity is 3.8 kW, so that's close, and how these coils were sized. Is heating performance just luck? The heating size = 10 kW comes from a capacity calculation using the cooling design flow (e.g., main system flow = max(coolingFlow, heatingFlow) and a system Central Heating Design Supply Air Temperature = 50 C (Sizing:Zone SAT also = 50 C). The cooling air flow is 5 times larger than heating. At 5x flow, you don't need 50 C SAT to meet the zone heating load. That could be just dumb luck that the cooling size worked here. How often is the peak cooling load similar to the heating load? It seems HP sizing based on geography is a little more complex than first thought.

image

System heating flows for Sys 4 from 2 design days shown in eplusssz.csv and zone air flow from epluszsz.csv:

image

When I request the system heating flow rate in UnitarySystem this is what I get. Someone's messin with me.

image

File: src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc [hunk 13]
```diff
@@ -95,7 +95,12 @@ Real64 HeatingCapacitySizer::size(EnergyPlusData &state, Real64 _originalValue,
             } else if (this->zoneEqSizing(this->curZoneEqNum).DesignSizeFromParent) {
                 this->autoSizedValue = this->zoneEqSizing(this->curZoneEqNum).DesHeatingLoad;
             } else {
-                if (this->zoneEqSizing(this->curZoneEqNum).HeatingCapacity) {
+                if (this->dataCoilIsSuppHeater && this->suppHeatCap > 0.0) {
+                    NominalCapacityDes = this->suppHeatCap;
+                    if (this->dataFlowUsedForSizing > 0.0) {
+                        DesVolFlow = this->dataFlowUsedForSizing;
+                    }
+                } else if (this->zoneEqSizing(this->curZoneEqNum).HeatingCapacity) {
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc:103]: UnitarySystem now sets the flag in the HeatingCoils::SimulateHeatingCoilComponents call so that sizing knows this is a supplemental heating coil. With that information UnitarySystem can set the capacity of the coil according to whether CoolReheat dehumidification control is used.

File: src/EnergyPlus/DataSizing.cc [hunk 14]
```diff
@@ -322,6 +322,8 @@ void resetHVACSizingGlobals(EnergyPlusData &state,
     state.dataSize->DataCoilSizingAirInHumRat = 0.0;
     state.dataSize->DataCoilSizingAirOutTemp = 0.0;
     state.dataSize->DataCoilSizingAirOutHumRat = 0.0;
+    state.dataSize->DataCoolCoilType = -1;
+    state.dataSize->DataCoolCoilIndex = -1;
```
Comment (rraustad) [inline src/EnergyPlus/DataSizing.cc:326]: Needed to call over to VS coils to get T for CapFT curve.

File: src/EnergyPlus/UnitarySystem.cc [hunk 15]
```diff
@@ -1534,6 +1534,9 @@ namespace UnitarySystems {
         } else {
             state.dataHVACGlobal->DXCT = 1; // uses normal DX coil flow limits
         }
+        // sizing may need to know what type of coil is being sized
+        state.dataSize->DataCoolCoilType = this->m_CoolingCoilType_Num;
+        state.dataSize->DataCoolCoilIndex = this->m_CoolingCoilIndex;
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1539]: This information is set only in UnitarySystem.

File: src/EnergyPlus/UnitarySystem.cc (hunk 10 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:1916]: The WS VS coil sizing differently in PackagedTerminalHeatPump than the air-source VS coil. This logic, in Step 3A, 3B and 4 below, mimics that method.

File: src/EnergyPlus/UnitarySystem.cc [hunk 16]
```diff
@@ -1866,23 +1880,54 @@ namespace UnitarySystems {
...
-        EqSizing.HeatingAirVolFlow = EqSizing.CoolingAirVolFlow;
+        if (!isWSVarSpeedHeatCoil) {
+            EqSizing.CoolingAirVolFlow = max(EqSizing.CoolingAirVolFlow, EqSizing.HeatingAirVolFlow);
+            EqSizing.HeatingAirVolFlow = EqSizing.CoolingAirVolFlow;
+        }
 
         // STEP 4: set heat pump coil capacities equal to greater of cooling or heating capacity
-        if (this->m_HeatPump) { // if a heat pump, use maximum values and set main air flow and capacity variables
+        // if a heat pump, use maximum values and set main air flow and capacity variables
+        if (this->m_HeatPump && (state.dataSize->CurZoneEqNum == 0 || !isWSVarSpeedCoolCoil)) {
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1919]: Don't need CurZoneEqNum == 0 here. Will need to reevaluate this logic when this branch gets merged with #9273 so will address that then.

File: src/EnergyPlus/UnitarySystem.cc [hunk 17]
```diff
@@ -1866,23 +1880,54 @@ namespace UnitarySystems {
...
-            EqSizing.DesCoolingLoad = max(EqSizing.DesCoolingLoad, EqSizing.DesHeatingLoad);
-            EqSizing.DesHeatingLoad = EqSizing.DesCoolingLoad;
-            state.dataSize->DXCoolCap = EqSizing.DesCoolingLoad;
+            if (this->m_CoolingCoilType_Num != DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit &&
+                this->m_HeatingCoilType_Num != DataHVACGlobals::Coil_HeatingWaterToAirHPVSEquationFit) {
+                EqSizing.Capacity = true;
+                EqSizing.DesCoolingLoad = max(EqSizing.DesCoolingLoad, EqSizing.DesHeatingLoad);
+                EqSizing.DesHeatingLoad = EqSizing.DesCoolingLoad;
+                state.dataSize->DXCoolCap = EqSizing.DesCoolingLoad;
+            }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:1930]: The WS VS coil retains the cooling/heating coil size even though it's a heat pump.

File: testfiles/CMakeLists.txt [hunk 18]
```diff
@@ -616,6 +616,7 @@ add_simulation_test(IDF_FILE UnitarySystem_TwoStageDXWithHumidityControl.idf EPW
 add_simulation_test(IDF_FILE UnitarySystem_VSCoolingCoil.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
 add_simulation_test(IDF_FILE UnitarySystem_VSHeatPumpWaterToAirEquationFit.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
 add_simulation_test(IDF_FILE UnitarySystem_WaterCoils_wMultiSpeedFan.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
+add_simulation_test(IDF_FILE UnitarySystem_ZoneVSWSHP_wDOAS.idf EPW_FILE USA_CO_Golden-NREL.724666_TMY3.epw)
```
Comment (rraustad) [inline testfiles/CMakeLists.txt:619]: There were no WS VS coils wrapped in a UnitarySystem.

File: src/EnergyPlus/UnitarySystem.cc [hunk 19]
```diff
@@ -7461,7 +7523,7 @@ namespace UnitarySystems {
 
         if ((CoilType_Num == DataHVACGlobals::Coil_HeatingGasOrOtherFuel) || (CoilType_Num == DataHVACGlobals::Coil_HeatingElectric)) {
             HeatingCoils::SimulateHeatingCoilComponents(
-                state, CompName, FirstHVACIteration, _, this->m_SuppHeatCoilIndex, _, _, this->m_FanOpMode, this->m_SuppHeatPartLoadFrac);
+                state, CompName, FirstHVACIteration, _, this->m_SuppHeatCoilIndex, _, true, this->m_FanOpMode, this->m_SuppHeatPartLoadFrac);
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:7526]: In addition to being used in sizing this flag also selects the report variable in ReportHeatingCoil. Probably should eliminate the Supp variable here.

        if (coilIsSuppHeater) {
            state.dataHVACGlobal->SuppHeatingCoilPower = heatingCoil.ElecUseLoad;
        } else {
            state.dataHVACGlobal->ElecHeatingCoilPower = heatingCoil.ElecUseLoad;
        }

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:7526]: Well, can't get rid of that variable. These are used in Parent objects to sum the power for each component. So if there is a main heating coil and supplemental heating coil, these need to be kept separate.

**Comment by rraustad** [comment]
This is finally ready for review.

**Review by mjwitte — APPROVED** [review]
Ok, we're near the finish line (after about 20 laps around the track).
Unit tests run locally - check.
Sizing for Unitary-ZoneVSWSHP_wDOAS now aligns with ZoneVSWSHP_wDOAS - check.
CI diffs for 5Zone_Unitary_HXAssistedCoil show reheat coil cap matches cooling coil cap - check
CI diffs for UnitarySystem_MultiSpeedCoils_SingleMode, now the supp heat coil reports a design size that aligns with the UnitarySystem heating capacity (this has no reheat) - check.

The only things left are to clear up the build warning and make sure the top comment description aligns with the final answer here.

**Comment by rraustad** [comment]
high-five-dog-high-five-xiteb

**Comment by rraustad** [comment]
I went over the issue and PR descriptions last night. Reading again I don't see any missing discussion. Each of the 4 bullets is addressed in this PR.

**Comment by mjwitte** [comment]
Thanks @rraustad ! Merging.
