### PR TITLE
Address RC1 incorrect unused object warning issue

### LINKED ISSUE #11304: v25.2.0 RC1 incorrect unused object warning
### Issue overview

E+ 25.2 is creating a warning about an unused object (`Coil:WaterHeating:AirToWaterHeatPump:Wrapped`). The object is definitely used and did not produce a warning in E+ 25.1.

```
   ** Warning ** The following lines are "Unused Objects".  These objects are in the input
   **   ~~~   **  file but are never obtained by the simulation and therefore are NOT used.
   **   ~~~   **  Only the first unused named object of an object class is shown.  Use Output:Diagnostics,DisplayAllWarnings; to see all.
   **   ~~~   **  See InputOutputReference document for more details.
   ************* Object=Coil:WaterHeating:AirToWaterHeatPump:Wrapped=water heater coil
```

This change is most likely due to https://github.com/NREL/EnergyPlus/pull/11033.

### Operating System (Multiple choices)

Ubuntu

### Operating System Version

24.04

### Version of EnergyPlus

25.2.0 RC1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[in.idf.txt](https://github.com/user-attachments/files/23200719/in.idf.txt)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------

- Fixes #11304
- This warning error was introduced when the getinput method was translated into `JSON` input processing method for the `Coil:WaterHeating:AirToWaterHeatPump:Wrapped`  and `Coil:WaterHeating:AirToWaterHeatPump:Pumped` objects.

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -3005,6 +3005,7 @@ void GetDXCoils(EnergyPlusData &state)
             ++DXCoilNum;
             auto const &fields = instance.value();
             std::string const &thisObjectName = instance.key();
+            s_ip->markObjectAsUsed(CurrentModuleObject, thisObjectName);
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:3008]: Yes. If getObjectItem is removed, which marks the object as used, then that functionality must be restored in json processing.

**Review by rraustad — APPROVED** [review]
This is the correct fix.

**Review by mitchute — APPROVED** [review]
Thanks. This looks good. Merging.
