### PR TITLE
Fix Outdoor Air Summary Multipliers and Outdoor Air Details by Airloop

### LINKED ISSUE #8528: Outdoor air summary multipliers
Issue overview
--------------
- [ ] In the old Outdoor Air Summary - the AFN infiltration values are being multiplied when the should not be. See [code here](https://github.com/NREL/EnergyPlus/blob/ce2592345bd889eebaed53a32531dbba0e68c661/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L8512-L8518)
The multipliers were added in #5192, so need to test this with and without multipliers, but it looks wrong here based on code inspection.

- [ ] ~In the LEED Summary Report, the row order in the "EAp2-6. Energy Use Summary" and "EAp2-7. Energy Cost Summary" sub-tables is impacted if another table calls `PreDefTableEntry` for a row labeled "Total" in `FillRemainingPredefinedEntries`, because that becomes the first use of "Total" and it comes before any use of "Electricity" or "Gas" or other fuel type which first occur in `WriteBEPS`. It would be good to avoid this order dependency somehow. Perhaps prepopulate the unique label list or call `FillRemainingPredefinedEntries` after `WriteBEPS` or ???~

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.4
 - Found while working on #7629 - will fix after that merges.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9398: Table reports for Total Outdoor Air by AirLoop are not accurate
Issue overview
--------------
Looking at example file ASHRAE901_HotelSmall_STD2019_Denver the table reports for Total Outdoor Air by Airloop do not match the results for air loop outdoor air flow rate. Tracking this report through the code it looks like the OA mass flow rate is again multiplied by StdRhoAir when it should be divided by to get back to standard density volume flow rate (SystemReports line 5060). The units for this report is m3, but for natural and total ventilation the units are m3/s. From the code it looks like m3 is correct for all 3 columns. So there are 3 changes needed to fix this, use m3 in 2 places for natural and total ventilation heading and use divide by StdRhoAir.

    s->pdchOaTaAlMechVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Mechanical Ventilation [m3]");

    for (int iSys = 1; iSys <= state.dataHVACGlobal->NumPrimaryAirSys; ++iSys) {
        // Total Outdoor Air by Airloop
        PreDefTableEntry(state,
                         state.dataOutRptPredefined->pdchOaTaAlMechVent,
                         state.dataAirSystemsData->PrimaryAirSystems(iSys).Name,
                         state.dataSysRpts->SysPreDefRep(iSys).SysMechVentTotal);

    auto &curAirLoopFlow(state.dataAirLoop->AirLoopFlow(AirLoopNum));
    curAirLoopFlow.OAFlow = this->OAMassFlow;

    // loop over air loops
    for (int sysNum = 1; sysNum <= state.dataHVACGlobal->NumPrimaryAirSys; ++sysNum) {
        Real64 mechVentFlow = state.dataAirLoop->AirLoopFlow(sysNum).OAFlow * state.dataEnvrn->StdRhoAir;
        state.dataSysRpts->SysMechVentFlow(sysNum) = mechVentFlow;
        state.dataSysRpts->SysPreDefRep(sysNum).SysMechVentTotal += mechVentFlow * TimeStepSys * DataGlobalConstants::SecInHour;
        state.dataSysRpts->SysPreDefRep(sysNum).SysNatVentTotal +=
            state.dataSysRpts->SysNatVentFlow(sysNum) * TimeStepSys * DataGlobalConstants::SecInHour;

Compare the table report for mechanical ventilation of 405002.1 m3 to the spreadsheet sum of outdoor air in cell D3 of 423915.4. A discrepancy is also shown for the restroom as 2054017 versus 2149938 in cell D4.

image

The calculation in error is in SystemReports line 5060 and should be divide by StdRhoAir:

        Real64 mechVentFlow = state.dataAirLoop->AirLoopFlow(sysNum).OAFlow / state.dataEnvrn->StdRhoAir;

Results with corrected code using divide by StdRhoAir:

image

2 reports were added to the existing example file:

    Output:Variable, SAC_FrontOffice Outside Air Inlet, System Node Standard Density Volume Flow Rate, hourly;
    Output:Variable, SAC_Exc_EmpLge_RestRm Outside Air Inlet, System Node Standard Density Volume Flow Rate, hourly;

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (ASHRAE901_HotelSmall_STD2019_Denver)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #8528 
 - In the Outdoor Air Summary table report, add a new column for AFN Ventilation (AirflowNetwork) and fix issue with zone multipliers. Previously, AFN Ventilation and AFN Infiltration were combined, and the value was incorrect for zone multipliers > 1.
 - Fixes #9398 
 - Correct the values reported in the Outdoor Air Details report, Airloop subtables for Mechanical Ventilation. This also impacts the Total Ventilation and the Times Below/At/Above Voz-Sum-dyn.

### Diffs
All files with Outdoor Air Summary and/or Outdoor Air Details table reports will show table diffs due to the new column and corrected values.
All files have audit diffs due to the change in table size.

### Fixes
For #8528, values in the Outdoor Air Summary table are per zone, without multipliers, but the AFN infiltration changed with multipliers.
Defect files AirflowNetwork_MultiZone_SmallOffice-NoHVAC-AllMult1 and AirflowNetwork_MultiZone_SmallOffice-NoHVAC-AllMult10
image

After the fix, the new AFN Ventilation column is there, and the values are unchanged with multipliers
image

For #9398 use test file [ASHRAE901_HotelSmall_STD2019_Denver-Fixed.idf.txt](https://github.com/NREL/EnergyPlus/files/9144609/ASHRAE901_HotelSmall_STD2019_Denver-Fixed.idf.txt) this has a couple of extra output variables.  The target value for Mech Vent total is found by summing the output variables for the Outside Air Inlet, System Node Standard Density Volume Flow Rate for 2 of the systems:
image

image

With this branch, the values agree.
image

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SystemReports.hh [hunk 1]
```diff
@@ -331,8 +331,6 @@ struct SystemReportsData : BaseGlobalStruct
     Array1D<Real64> SysHCCompSteam;
     Array1D<Real64> SysDomesticH2O;
 
-    Array1D<Real64> ZoneOAMassFlow;               // zone mech vent mass flow rate {kg/s}
-    Array1D<Real64> ZoneOAMass;                   // zone mech vent total mass for time {kg}
     Array1D<Real64> ZoneOAVolFlowStdRho;          // zone mech vent volume flow rate at standard density {m3/s}
     Array1D<Real64> ZoneOAVolStdRho;              // zone mech vent total volume OA at standard density {m3}
     Array1D<Real64> ZoneOAVolFlowCrntRho;         // zone mech vent volume flow rate at current density {m3/s}
```
Comment (mjwitte) [inline src/EnergyPlus/SystemReports.hh]: SystemReports has many `Array1D` that are used primarily in one function, so I was hoping to make them local to `ReportMaxVentilationLoads` but many of them are also referenced as output variables, so they need to remain in `state`.

File: src/EnergyPlus/DataHeatBalance.hh [hunk 2]
```diff
@@ -1597,6 +1597,9 @@ namespace DataHeatBalance {
         Real64 OABalanceFanElec = 0.0;       // Fan Electricity {W} due to OA air balance
         Real64 SumEnthalpyM = 0.0;           // Zone sum of EnthalpyM
         Real64 SumEnthalpyH = 0.0;           // Zone sum of EnthalpyH
+        // Mechanical ventilation
+        Real64 ZoneOAMassFlow = 0.0; // zone mech vent mass flow rate {kg/s}
+        Real64 ZoneOAMass = 0.0;     // zone mech vent total mass for time {kg}
```
Comment (mjwitte) [inline src/EnergyPlus/DataHeatBalance.hh]: Two of these have been moved to `state.dataHeatBal->ZnAirRp` in commit https://github.com/NREL/EnergyPlus/pull/9519/commits/76cbe0c6fc7bca96fe4ac440ae235b7942649fb8 If this approach looks reasonable, then I'll proceed with moving more of these.

**Review by mjwitte — COMMENTED** [review]
@amirroth @Myoldmopar A quick check-in here before proceeding with more.

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 3]
```diff
@@ -760,11 +762,12 @@ namespace OutputReportPredefined {
...
         s->pdchOaOccBzTmAt = newPreDefColumn(state, s->pdstOAavgOccByZone, "Time At Voz-dyn [hr]");
         s->pdchOaOccBzTmAbove = newPreDefColumn(state, s->pdstOAavgOccByZone, "Time Above Voz-dyn [hr]");
+        addFootNoteSubTable(state, s->pdstOAavgOccByZone, "Values shown for a single zone without multipliers. Total Facility includes multipliers");
 
         s->pdstOAtotAirByLoop = newPreDefSubTable(state, s->pdrOutsideAirDetails, "Total Outdoor Air by AirLoop");
         s->pdchOaTaAlMechVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Mechanical Ventilation [m3]");
-        s->pdchOaTaAlNatVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Natural Ventilation [m3/s]");
-        s->pdchOaTaAlTotVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Total Ventilation [m3/s]");
+        s->pdchOaTaAlNatVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Natural Ventilation [m3]");
+        s->pdchOaTaAlTotVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Total Ventilation [m3]");
```
Comment (rraustad) [inline src/EnergyPlus/OutputReportPredefined.cc:770]: Addresses 9398

File: src/EnergyPlus/SystemReports.cc [hunk 4]
```diff
@@ -5057,7 +5051,7 @@ void ReportMaxVentilationLoads(EnergyPlusData &state)
 
     // loop over air loops
     for (int sysNum = 1; sysNum <= state.dataHVACGlobal->NumPrimaryAirSys; ++sysNum) {
-        Real64 mechVentFlow = state.dataAirLoop->AirLoopFlow(sysNum).OAFlow * state.dataEnvrn->StdRhoAir;
+        Real64 mechVentFlow = state.dataAirLoop->AirLoopFlow(sysNum).OAFlow / state.dataEnvrn->StdRhoAir;
```
Comment (rraustad) [inline src/EnergyPlus/SystemReports.cc:4617]: Addresses 9398

File: src/EnergyPlus/SystemReports.hh (hunk 1 above)
Comment (amirroth) [reply src/EnergyPlus/SystemReports.hh]: 📌 These should reorganized into two, three, or four arrays of `struct`s rather than 67 (not a made up number) of arrays of scalars.  

📌 This module could also use a `struct AirLoopLocation` that is analogous to the `struct PlantLocation` we are using now.

Comment (mjwitte) [reply src/EnergyPlus/SystemReports.hh]: Is there a limit to how large a single struct should be? I think everything here could be in either one struct by zone and another by airloop.

File: doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex [hunk 5]
```diff
@@ -1854,59 +1854,82 @@ \subsection{Component Sizing Summary}\label{component-sizing-summary}
...
+SPACE3-1 & 9.50 & 11.00 & 239.25 & 0.000 & 0.000 & 0.000 & 0.000 & 0.000 \tabularnewline
+SPACE4-1 & 4.32 & 5.00 & 103.31 & 0.000 & 0.000 & 0.000 & 0.000 & 0.000 \tabularnewline
+SPACE5-1 & 17.27 & 20.00 & 447.68 & 0.000 & 0.000 & 0.000 & 0.000 & 0.000 \tabularnewline
 \bottomrule
 \end{longtable}
+\textit{Values shown for a single zone without multipliers}
+\normalsize
+
+\begin{description}
+  \item[Average Number of Occupants] The average number of occupants in the zone during occupied hours.
```
Comment (mjwitte) [inline doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex:1916]: Add column-by-column descriptions for Outdoor Air Summary table.

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 6]
```diff
@@ -9335,12 +9335,13 @@ namespace AirflowNetwork {
...
                 m_state.dataHeatBal->ZonePreDefRep(i).AFNVentVolTotalOccStdDen += stdDensAFNNatVentVolume;
                 m_state.dataHeatBal->ZonePreDefRep(i).AFNInfilVolTotalOccStdDen += stdDensAFNInfilVolume;
-                m_state.dataHeatBal->ZonePreDefRep(i).AFNInfilVolTotalOcc +=
-                    (AirflowNetworkZnRpt(i).InfilVolume + AirflowNetworkZnRpt(i).VentilVolume) * Zone(i).Multiplier * Zone(i).ListMultiplier;
-                if ((AirflowNetworkZnRpt(i).InfilVolume + AirflowNetworkZnRpt(i).VentilVolume) <
-                    m_state.dataHeatBal->ZonePreDefRep(i).AFNInfilVolMin) {
-                    m_state.dataHeatBal->ZonePreDefRep(i).AFNInfilVolMin =
-                        (AirflowNetworkZnRpt(i).InfilVolume + AirflowNetworkZnRpt(i).VentilVolume) * Zone(i).Multiplier * Zone(i).ListMultiplier;
+                m_state.dataHeatBal->ZonePreDefRep(i).AFNInfilVolTotalOcc += AirflowNetworkZnRpt(i).InfilVolume;
+                m_state.dataHeatBal->ZonePreDefRep(i).AFNVentVolTotalOcc += AirflowNetworkZnRpt(i).VentilVolume;
```
Comment (mjwitte) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:9339]: Remove multipliers and separate AFN infiltration and ventilation for Outdoor Air Summary report (fixes for #8528).

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 7]
```diff
@@ -723,7 +722,7 @@ namespace OutputReportPredefined {
         s->pdchOaoMinInfil = newPreDefColumn(state, s->pdstOAminOcc, "Infiltration [ach]");
         s->pdchOaoMinAFNInfil = newPreDefColumn(state, s->pdstOAminOcc, "AFN Infiltration [ach]");
         s->pdchOaoMinSimpVent = newPreDefColumn(state, s->pdstOAminOcc, "Simple Ventilation [ach]");
-        // s->pdchOaoMinTotVent =   newPreDefColumn(state, s->pdstOAminOcc,'Total Ventilation [ach]')
+        s->pdchOaoMinAFNVent = newPreDefColumn(state, s->pdstOAminOcc, "AFN Ventilation [ach]");
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportPredefined.cc:725]: Add new column to Outdoor Air Summary table.

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 8]
```diff
@@ -737,6 +736,8 @@ namespace OutputReportPredefined {
         s->pdchOaMvZoneArea = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Zone Area [m2]");
         s->pdchOaMvDesZnOa = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Design Zone Outdoor Airflow - Voz [m3/s]");
         s->pdchOaMvMinDynTrgVent = newPreDefColumn(state, s->pdstOAmechVentParByZone, "Minimum Dynamic Target Ventilation - Voz-dyn-min [m3/s]");
+        addFootNoteSubTable(
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportPredefined.cc:739]: Add footnotes to Outdoor Air Details, zone subtables

File: src/EnergyPlus/SystemReports.cc [hunk 9]
```diff
@@ -5057,53 +4612,52 @@ void ReportMaxVentilationLoads(EnergyPlusData &state)
...
     // loop over air loops
     for (int sysNum = 1; sysNum <= state.dataHVACGlobal->NumPrimaryAirSys; ++sysNum) {
-        Real64 mechVentFlow = state.dataAirLoop->AirLoopFlow(sysNum).OAFlow * state.dataEnvrn->StdRhoAir;
-        state.dataSysRpts->SysMechVentFlow(sysNum) = mechVentFlow;
-        state.dataSysRpts->SysPreDefRep(sysNum).SysMechVentTotal += mechVentFlow * TimeStepSys * DataGlobalConstants::SecInHour;
-        state.dataSysRpts->SysPreDefRep(sysNum).SysNatVentTotal +=
-            state.dataSysRpts->SysNatVentFlow(sysNum) * TimeStepSys * DataGlobalConstants::SecInHour;
+        auto &thisSysVentRepVars = state.dataSysRpts->SysVentRepVars(sysNum);
+        auto &thisSysPreDefRep = state.dataSysRpts->SysPreDefRep(sysNum);
+        Real64 mechVentFlow = state.dataAirLoop->AirLoopFlow(sysNum).OAFlow / state.dataEnvrn->StdRhoAir;
```
Comment (mjwitte) [inline src/EnergyPlus/SystemReports.cc:4617]: This is the fix for #9398. Simply changing `*` to `\`.

File: src/EnergyPlus/SystemReports.hh [hunk 10]
```diff
@@ -128,26 +128,108 @@ namespace SystemReports {
         }
     };
 
+    struct ZoneVentReportVariables
+    {
+        Real64 CoolingLoadMetByVent = 0.0;
```
Comment (mjwitte) [inline src/EnergyPlus/SystemReports.hh:133]: Collected a bunch of separate `Array1D`s into a few `structs`.

**Review by mjwitte — COMMENTED** [review]
A few lines of fixes, some doc changes, and lots of code cleanup (eliminate `using`, reduced scope for local variables, & references for readability). SystemReports could use more work, but this is enough for this PR.

Walkthru . . .

File: src/EnergyPlus/OutputReportTabular.cc [hunk 11]
```diff
@@ -6511,122 +6528,122 @@ void FillRemainingPredefinedEntries(EnergyPlusData &state)
...
+                         state.dataSysRpts->SysPreDefRep(iSys).TimeAboveVozDynTotal);
         PreDefTableEntry(state,
                          state.dataOutRptPredefined->pdchOaTaAlTmAboveUnocc,
                          state.dataAirSystemsData->PrimaryAirSystems(iSys).Name,
-                         state.dataSysRpts->SysPreDefRep(iSys).SysTimeVentUnoccTotal);
+                         state.dataSysRpts->SysPreDefRep(iSys).TimeVentUnoccTotal);
 
         // Air loop times at OA limiting factors
         PreDefTableEntry(state,
                          state.dataOutRptPredefined->pdchOaTmFctNoLimit,
```
Comment (amirroth) [inline src/EnergyPlus/OutputReportTabular.cc:6563]: 🤔 Could this pdch0aTmFct variable group also be made into a `std::array` indexed by this `MixedAir::limitFactor` quasi-`enum` (I know it's not a real `enum`, it's not scoped and also I looked)? Because in that case ...

File: src/EnergyPlus/SystemReports.cc [hunk 12]
```diff
@@ -371,99 +291,96 @@ void InitEnergyReports(EnergyPlusData &state)
...
+                    for (int VarNum = 1; VarNum <= thisZoneEquipList.EquipData(AirDistUnitNum).NumMeteredVars; ++VarNum) {
+                        if (thisZoneEquipList.EquipData(AirDistUnitNum).MeteredVar(VarNum).ResourceType ==
                             DataGlobalConstants::ResourceType::EnergyTransfer) {
-                            state.dataZoneEquip->ZoneEquipList(ListNum).EquipData(AirDistUnitNum).EnergyTransComp = EnergyTransfer;
-                            CompType = state.dataZoneEquip->ZoneEquipList(ListNum).EquipData(AirDistUnitNum).TypeOf;
-                            CompName = state.dataZoneEquip->ZoneEquipList(ListNum).EquipData(AirDistUnitNum).Name;
-                            Idx = 0;
+                            thisZoneEquipList.EquipData(AirDistUnitNum).EnergyTransComp = EnergyTransfer;
+                            const std::string &CompType = thisZoneEquipList.EquipData(AirDistUnitNum).TypeOf;
+                            const std::string &CompName = thisZoneEquipList.EquipData(AirDistUnitNum).Name;
```
Comment (amirroth) [inline src/EnergyPlus/SystemReports.cc:322]: :+1:

File: src/EnergyPlus/SystemReports.cc [hunk 13]
```diff
@@ -371,99 +291,96 @@ void InitEnergyReports(EnergyPlusData &state)
...
+                            int Idx = 0;
+                            int MatchLoop = 0;
```
Comment (amirroth) [inline src/EnergyPlus/SystemReports.cc:324]: :pushpin:

**Comment by rraustad** [comment]
OutputDetailesAndExamples.pdf updated tables with foot notes and descriptions.

image
image

**Comment by rraustad** [comment]
UPDATE: this file has a date from last year do disregard as a result of this branch.
I've never looked at this file. eplustbl.txt. Some tables shows numeric data, others show None where data should be. For another day of course.

    ----------------------------------------------------------------------------------------------------
    REPORT:       Outdoor Air Summary
    FOR:          Entire Facility
    Average Outdoor Air During Occupied Hours

       Average Number of Occupants  Nominal Number of Occupants  Zone Volume [m3]  Mechanical Ventilation [ach]  Infiltration [ach]  AFN Infiltration [ach]  Simple Ventilation [ach]
      None
    Values shown for a single zone without multipliers

    Minimum Outdoor Air During Occupied Hours

       Average Number of Occupants  Nominal Number of Occupants  Zone Volume [m3]  Mechanical Ventilation [ach]  Infiltration [ach]  AFN Infiltration [ach]  Simple Ventilation [ach]
      None
    Values shown for a single zone without multipliers

    ----------------------------------------------------------------------------------------------------

**Comment by rraustad** [comment]
Defect files AirflowNetwork_MultiZone_SmallOffice-NoHVAC-AllMult1 and AirflowNetwork_MultiZone_SmallOffice-NoHVAC-AllMult10, in that order. North zone AFN ventilation looks like 1.935 and 1.938, but in the html they are both 1.938. So it appears that multipliers are not applied, as noted in footnote.

image

**Comment by rraustad** [comment]
Infiltration not allowed in this AFN file.

    Program Version,EnergyPlus, Version 22.2.0-425b7844ab, YMD=2022.07.19 20:19,
       ** Warning ** AirflowNetwork::Solver::get_input: AirflowNetwork:SimulationControl object, 
       **   ~~~   ** ..Specified AirflowNetwork Control = "MultizoneWithoutDistribution" and ZoneInfiltration:* objects are present.
       **   ~~~   ** ..ZoneInfiltration objects will not be simulated.

Results from PackagedTerminalAirConditionerVSAS which uses non-zero flow only for EAST zone:

    ZoneInfiltration:DesignFlowRate,
    WEST ZONE Infil 1,       !- Name
    WEST ZONE,               !- Zone or ZoneList Name
    INFIL-SCH,               !- Schedule Name
    flow/zone,               !- Design Flow Rate Calculation Method
    0.0,                     !- Design Flow Rate {m3/s}
    ,                        !- Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Flow per Exterior Surface Area {m3/s-m2}
    ,                        !- Air Changes per Hour {1/hr}
    0,                       !- Constant Term Coefficient
    0,                       !- Temperature Term Coefficient
    0.2237,                  !- Velocity Term Coefficient
    0;                       !- Velocity Squared Term Coefficient

    ZoneInfiltration:DesignFlowRate,
    EAST ZONE Infil 1,       !- Name
    EAST ZONE,               !- Zone or ZoneList Name
    INFIL-SCH,               !- Schedule Name
    flow/zone,               !- Design Flow Rate Calculation Method
    0.04,                    !- Design Flow Rate {m3/s}
    ,                        !- Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Flow per Exterior Surface Area {m3/s-m2}
    ,                        !- Air Changes per Hour {1/hr}
    0,                       !- Constant Term Coefficient
    0,                       !- Temperature Term Coefficient
    0.2237,                  !- Velocity Term Coefficient
    0;                       !- Velocity Squared Term Coefficient

    ZoneInfiltration:DesignFlowRate,
    NORTH ZONE Infil 1,      !- Name
    NORTH ZONE,              !- Zone or ZoneList Name
    INFIL-SCH,               !- Schedule Name
    flow/zone,               !- Design Flow Rate Calculation Method
    0.0,                     !- Design Flow Rate {m3/s}
    ,                        !- Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Flow per Exterior Surface Area {m3/s-m2}
    ,                        !- Air Changes per Hour {1/hr}
    0,                       !- Constant Term Coefficient
    0,                       !- Temperature Term Coefficient
    0.2237,                  !- Velocity Term Coefficient
    0;                       !- Velocity Squared Term Coefficient

image

**Comment by rraustad** [comment]
And now with 10x zone multiplier on all 3 zones in PackagedTerminalAirConditionerVSAS. Not sure why mechanical ventilation would change, all other columns are the same.

image

**Comment by rraustad** [comment]
Results from 5ZoneNightVent2 with ZoneVentilation:DesignFlowRate objects. Simple ventilation should be non-zero?

image

**Comment by rraustad** [comment]
Added output report to 5ZoneNightVent2:

    Output:Variable,*,Zone Ventilation Air Change Rate,hourly;

image

File: doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex [hunk 14]
```diff
@@ -1854,59 +1854,82 @@ \subsection{Component Sizing Summary}\label{component-sizing-summary}
 
 \subsection{Outdoor Air Summary}\label{outdoor-air-summary}
 
-The Outdoor Air Summary provides information for each zone on the average and minimum ventilation provided.
-
-The reports described so far in this section are displayed when specified in the Output:Table:SummaryReports object. They are either on or off and are not customizable. The next few types of tabular reports are customizable. You can specify the report variables being used in each one.
-
-Directly following is an example of the report. The key used to obtain this report is OutdoorAirSummary.
+The Outdoor Air Summary provides information for each zone on the average and minimum ventilation provided. Directly following is an example of the report. The key used to obtain this report is OutdoorAirSummary.
```
Comment (rraustad) [inline doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex:1858]: Do we need to include other possible keys for this table?

    Output:Table:SummaryReports,
      AllSummary;              !- Report 1 Name

File: src/EnergyPlus/SystemReports.cc [hunk 15]
```diff
@@ -488,40 +404,34 @@ void InitEnergyReports(EnergyPlusData &state)
...
+                int SubSubEquipNum = 0;
+                int CompNum = 0;
+                int SubCompNum = 0;
+                int SubSubCompNum = 0;
                 // Eliminate duplicates in the connection arrays
                 if (allocated(state.dataAirSystemsData->ZoneCompToPlant)) {
                     EquipNum = isize(state.dataAirSystemsData->ZoneCompToPlant);
-                } else {
-                    EquipNum = 0;
                 }
```
Comment (rraustad) [inline src/EnergyPlus/SystemReports.cc:416]: I don't know the answer so I will ask if this works the same.

int EquipNum = state.dataAirSystemsData->ZoneCompToPlant.size();

File: src/EnergyPlus/SystemReports.cc [hunk 16]
```diff
@@ -4924,130 +4486,123 @@ void ReportMaxVentilationLoads(EnergyPlusData &state)
...
-            state.dataSysRpts->ZoneOAVolFlowCrntRho(CtrlZoneNum) = state.dataSysRpts->ZoneOAMassFlow(CtrlZoneNum) / currentZoneAirDensity;
-        state.dataSysRpts->ZoneOAVolCrntRho(CtrlZoneNum) =
-            state.dataSysRpts->ZoneOAVolFlowCrntRho(CtrlZoneNum) * TimeStepSys * DataGlobalConstants::SecInHour;
-        if (ZoneVolume > 0.0)
-            state.dataSysRpts->ZoneMechACH(CtrlZoneNum) = (state.dataSysRpts->ZoneOAVolCrntRho(CtrlZoneNum) / TimeStepSys) / ZoneVolume;
+        Real64 currentZoneAirDensity = Psychrometrics::PsyRhoAirFnPbTdbW(state,
+                                                                         state.dataEnvrn->OutBaroPress,
+                                                                         state.dataHeatBalFanSys->MAT(ActualZoneNum),
+                                                                         state.dataHeatBalFanSys->ZoneAirHumRatAvg(ActualZoneNum));
+        if (currentZoneAirDensity > 0.0) thisZoneVentRepVars.OAVolFlowCrntRho = thisZoneVentRepVars.OAMassFlow / currentZoneAirDensity;
```
Comment (rraustad) [inline src/EnergyPlus/SystemReports.cc:4517]: Noting here if currentZoneAirDensity = 0 we got bigger problems.

File: src/Transition/OutputRulesFiles/OutputChanges22-1-0-to-22-2-0.md [hunk 17]
```diff
@@ -66,3 +66,20 @@ The Adaptive Comfort Summary/Report was renamed to match the HTML:
 ```
 
 See pull request [#9461](https://github.com/NREL/EnergyPlus/pull/9461) for more details.
+
+### Tabular Report Outdoor Air Summary - New Column
+In both subtables of the Outdoor Air Summary report, these is a new column at the far right for *AFN Ventilation [ach]*. AirflowNetwork infiltraion (cracks) and ventilation (openings) flow rates are now reported separately. Previously, they were combined in the AFN Infiltration column. 
+
```
Comment (rraustad) [inline src/Transition/OutputRulesFiles/OutputChanges22-1-0-to-22-2-0.md:72]: "these is a new column", infiltraion. There are 2 new columns.

File: tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc [hunk 18]
```diff
@@ -16301,4 +16301,160 @@ TEST_F(EnergyPlusFixture, AirflowNetwork_DuctSizingTest)
...
+    state->afn->exchangeData(1).SumMVCp = 2.4 * currentCpAir; // ventilation mass flow rate
+
+    state->dataEnvrn->OutBaroPress = 100000.0;
+    Real64 currentAirDensity = Psychrometrics::PsyRhoAirFnPbTdbW(
+        *state, state->dataEnvrn->OutBaroPress, state->dataHeatBalFanSys->MAT(1), state->dataHeatBalFanSys->ZoneAirHumRatAvg(1));
+    state->dataHVACGlobal->TimeStepSys = 1.0 / DataGlobalConstants::SecInHour;
+
+    state->dataHeatBal->ZonePreDefRep(1).isOccupied = false;
+    state->afn->report();
+    EXPECT_EQ(state->dataHeatBal->ZonePreDefRep(1).AFNInfilVolMin, 9.9e+09);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc:16422]: This threw me for a second. Real64 AFNInfilVolMin = 9.9e9

**Comment by rraustad** [comment]
Whew, that's a lot to review.

**Comment by rraustad** [comment]
I don't know how we are supposed to verify the diffs are accurate with this many files changing. 5ZoneAirCooledWithCoupledInGradeSlab_HorizInsThickness

image

**Comment by rraustad** [comment]
5ZoneAirCooledWithCoupledInGradeSlab_HorizInsThickness - develop then this branch to compare to absolute diffs above.

image

image

**Comment by rraustad** [comment]
I'm uneasy about the scope of changes like this. Maybe smaller changes would be more manageable. Changing variable names and adding structs, OK, should get 0 diffs. Mixing this with a change that will have obvious diffs is not the best course of action. Food for thought.

**Comment by rraustad** [comment]
There are no eso diffs but as a double check. using the EnergyPlus Regression Tool to quickly create the csv's for 5ZoneAirCooledWithCoupledInGradeSlab_HorizInsThickness, and binder plotting scripts to quickly plot the results, I see there are no csv diffs, wihch agrees with the CI. So AUD and Table diffs only is a good sign that changes only affect table reports.

image

**Comment by rraustad** [comment]
Verified #9398.

image
