### PR TITLE
Fix 11188 No match on WINDOW5 data file due to extra blank lines

### LINKED ISSUE #11188: No match on WINDOW5 data file due to extra blank lines
### Issue overview

The attached Window5DataFile_ExtraBlankLines.dat (generated by Berkeley Lab WINDOW 7) causes an error when running 1ZoneUncontrolled_Window5.idf.

```
  ** Severe ** No match on WINDOW5 data file for Construction=EXAMPLE B, or error in data file.
  **  ~~~  ** ...Looking on file=Window5DataFile_ExtraBlankLines.dat
```

The Window5 data file parser assumes line counts based on the "Window5 Data File for EnergyPlus" line, so the extra blank line causes EnergyPlus to fail to find the window name "Example B".

This defect is likely a one-off as it is unlikely any other applications are generating WINDOW5 data files with extra blank lines in random places. The broader issue is that the parsing logic doesn't handle extra whitespace in general and should be rewritten. I will open a separate enhancement issue to address this. #11194 

### Operating System (Multiple choices)

Any

### Operating System Version

Any

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[1ZoneUncontrolled_Window5.idf.txt](https://github.com/user-attachments/files/22127216/1ZoneUncontrolled_Window5.idf.txt)
[Window5DataFile_ExtraBlankLines.dat.txt](https://github.com/user-attachments/files/22127215/Window5DataFile_ExtraBlankLines.dat.txt)

### PR DESCRIPTION
**Pull request by kevin-moos**
Pull request overview
---------------------

- Fixes #11188 

### Description of the purpose of this PR

The file attached to the issue (Window5DataFile_ExtraBlankLines.dat, generated by Berkeley Lab WINDOW 7) causes an error when running EnergyPlus. The Window5 data file parser assumes line counts based on the "Window5 Data File for EnergyPlus" line, so the extra blank line causes EnergyPlus to fail to find the window name "Example B". This change will find the line that begins with "Window Name" instead of assuming a line count.

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceManager.cc [hunk 1]
```diff
@@ -3757,18 +3757,27 @@ namespace HeatBalanceManager {
         }
 
     Label10:;
-        for (LineNum = 2; LineNum <= 5; ++LineNum) {
+        NextLine = W5DataFile.readLine();
+        if (NextLine.eof) {
+            goto Label1000;
+        }
+        ++FileLineCount;
+        if (!has_prefixi(NextLine.data, "WINDOW NAME")) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatBalanceManager.cc:3765]: Although I'm not a big fan of adding another use of the Objexx utilities, this is totally fine.

File: tst/EnergyPlus/unit/HeatBalanceManager.unit.cc [hunk 2]
```diff
@@ -2316,6 +2316,23 @@ TEST_F(EnergyPlusFixture, Window5DataFileSpaceInName)
...
+    std::string ConstructName{"EXAMPLE B"};
+    bool ConstructionFound{false};
+    bool EOFonW5File{false};
+    bool ErrorsFound{false};
+    state->dataHeatBal->MaxSolidWinLayers = 2;
+
+    SearchWindow5DataFile(*state, window5DataFilePath, ConstructName, ConstructionFound, EOFonW5File, ErrorsFound);
+
+    EXPECT_EQ(ConstructName, "EXAMPLE B");
+    EXPECT_TRUE(ConstructionFound);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/HeatBalanceManager.unit.cc:2333]: 👍

**Review by Myoldmopar — APPROVED** [review]
All good here

**Comment by Myoldmopar** [comment]
@kevin-moos I ran Clang Format locally and it complained about a line comment line, so I adjusted that.  It tested happily here, and looks good, so I'm going to go ahead and get this merged.  Thanks!
