### PR TITLE
Coil:Heating:Desuperheater continually updates water inlet temperature during iterations causing high water tank energy use.

### LINKED ISSUE #7332: Got incorrect results running model with water heating desuperheater
Issue overview
--------------
Desuperheater gave crazy results for models with more "spiky" water use draw profiles. It seemed the function didn't control save properly when doing hvac iterations, which led to it advancing more than once per time step. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (v9.1.0)
 - [Unmethours link](https://unmethours.com/question/39085/unreasonable-results-for-water-heating-desuperheater/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yzhou601**
Pull request overview
---------------------
Fix #7332. The desuperheater model updates the coil inlet temperature based on the current iteration. This causes a higher than expected coil inlet temperature and the desuperheater does not recover as much heat as if the coil inlet temperature were saved from the previous time step. This has now been corrected.

CI result summary: 3 failure runs
Most of the large percentage differences (>0.1) occurred in water heating system outputs, only one model contains some differences regarding the condenser. Overall results looked reasonable because the water heater temperatures now reflect desuperheater energy transfer. 

Regression results
--
|Model | Big perc diff occurred(>0.1) | percentage difference | Category|
|-------|---------|---------|---------|
|5Zone_Unitary_VSDesuperheatWaterHeater | WATERHEATINGCOILTANK:Water Heater Total Demand Heat Transfer Rate   [W](Hourly) | 6.056285 | Water heating|
  | WATERHEATINGCOILTANK:Water Heater Total Demand Heat Transfer Energy   [J](Hourly) | 6.056285 | Water heating|
  | WATERHEATINGCOILTANK:Water Heater Net Heat Transfer Rate [W](Hourly) | 6.056285 | Water heating|
  | WATERHEATINGCOILTANK:Water Heater Net Heat Transfer Energy [J](Hourly) | 6.056285 | Water heating|
  | WATERHEATINGCOIL:Water Heater Off Cycle Parasitic Electric Power   [W](Hourly) | 0.232807 | Water heating|
  | WATERHEATINGCOIL:Water Heater Off Cycle Parasitic Electric Energy   [J](Hourly) | 0.232807 | Water heating|
CoilWaterDesuperheating | WATERHEATINGCOILTANK:Water Heater Source Side Mass Flow Rate   [kg/s](Hourly) | 0.17596 | Water heating|
  | WATERHEATINGCOILTANK:Water Heater Source Side Inlet Temperature   [C](Hourly) | 0.112753 | Water heating|
  | WATERHEATINGCOIL:Water Heater Part Load Ratio [](Hourly) | 0.175433 | Water heating|
  | WATERHEATINGCOIL:Water Heater On Cycle Parasitic Electric Power   [W](Hourly) | 0.175433 | Water heating|
  | WATERHEATINGCOIL:Water Heater On Cycle Parasitic Electric Energy   [J](Hourly) | 0.175433 | Water heating|
  | WATERHEATINGCOIL:Water Heater Off Cycle Parasitic Electric Power   [W](Hourly) | 0.148761 | Water heating|
  | WATERHEATINGCOIL:Water Heater Off Cycle Parasitic Electric Energy   [J](Hourly) | 0.148761 | Water heating
  | WATERHEATINGCOIL:Water Heater Pump Electric Power [W](Hourly) | 0.175433 | Water heating|
  | WATERHEATINGCOIL:Water Heater Pump Electric Energy [J](Hourly) | 0.175433 | Water heating|
  | WATERHEATINGCOIL:Water Heater Heating Rate [W](Hourly) | 0.183089 | Water heating|
  | WATERHEATINGCOILINLETNODE:System Node Mass Flow Rate [kg/s](Hourly) | 0.17596 | Water heating|
  | WATERHEATINGCOILOUTLETNODE:System Node Temperature [C](Hourly) | 0.112753 | Water heating|
  | WATERHEATINGCOILOUTLETNODE:System Node Mass Flow Rate [kg/s](Hourly) | 0.17596 | Water heating|
SuperMarketDetailed_DesuperHeatingCoil | LOWTEMPCONDENSER:Refrigeration System Condenser Total Recovered Heat   Transfer Rate [W](TimeStep) | 31.313 | HVAC|
  | LOWTEMPCONDENSER:Refrigeration System Condenser Non Refrigeration   Recovered Heat Transfer Rate [W](TimeStep) | 31.313 | HVAC|
  | LOWTEMPCONDENSER:Refrigeration System Condenser Total Recovered Heat   Transfer Rate [W](TimeStep) | 4.8544 | HVAC|
  | LOWTEMPCONDENSER:Refrigeration System Condenser Non Refrigeration   Recovered Heat Transfer Rate [W](TimeStep) | 4.8544 | HVAC|
  | LOWTEMPCONDENSER:Refrigeration System Condenser Fan Electric Power   [W](TimeStep) | 0.7019 | HVAC|
  | LOWTEMPSYSTEM:Refrigeration System Net Rejected Heat Transfer Rate   [W](TimeStep) | 0.3208 | HVAC|
  | LOWTEMPCONDENSER:Refrigeration System Condenser Heat Transfer Rate   [W](TimeStep) | 0.3208 | HVAC|
  | WATERHEATINGCOIL:Water Heater Part Load Ratio [](Hourly) | 0.7449 | Water heating|
  | WATERHEATINGCOIL:Water Heater Pump Electric Power [W](Hourly) | 0.7449 | Water heating|
  | WATERHEATINGCOIL:Water Heater On Cycle Parasitic Electric Power   [W](Hourly) | 0.7449 | Water heating|
  | WATERHEATINGCOIL:Water Heater Off Cycle Parasitic Electric Power   [W](Hourly) | 1 | Water heating|
  | WATERHEATINGCOIL:Water Heater Heating Rate [W](Hourly) | 0.7618 | Water heating|

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 1]
```diff
@@ -8673,12 +8673,13 @@ namespace WaterThermalTanks {
...
         // reset tank inlet temp from previous time step
-        WaterThermalTank(WaterThermalTankNum).SourceInletTemp = WaterThermalTank(WaterThermalTankNum).SourceOutletTemp;
+        WaterThermalTank(WaterThermalTankNum).SourceInletTemp = WaterThermalTank(WaterThermalTankNum).SavedSourceOutletTemp;
         WaterHeaterDesuperheater(DesuperheaterNum).DesuperheaterPLR = 0.0;
 
         Node(WaterInletNode).MassFlowRate = 0.0;
+        Node(WaterInletNode).Temp = WaterThermalTank(WaterThermalTankNum).SavedSourceOutletTemp;
         Node(WaterOutletNode).MassFlowRate = 0.0;
-        Node(WaterOutletNode).Temp = WaterThermalTank(WaterThermalTankNum).SourceOutletTemp;
+        Node(WaterOutletNode).Temp = WaterThermalTank(WaterThermalTankNum).SavedSourceOutletTemp;
```
Comment (rraustad) [inline src/EnergyPlus/WaterThermalTanks.cc:8681]: Two things changed here which makes me wonder which one corrected the problem or were both necessary. In any event these changes look reasonable and correct.

File: src/EnergyPlus/WaterThermalTanks.hh [hunk 2]
```diff
@@ -663,7 +664,7 @@ namespace WaterThermalTanks {
               OffCycParaFuelRate(0.0), Mode(0), SaveMode(0), SaveWHMode(0), BackupElementCapacity(0.0), DXSysPLR(0.0),
               ReclaimHeatingSourceIndexNum(0), ReclaimHeatingSource(0), SetPointError(0), SetPointErrIndex1(0), IterLimitErrIndex1(0),
               IterLimitExceededNum1(0), RegulaFalsiFailedIndex1(0), RegulaFalsiFailedNum1(0), IterLimitErrIndex2(0), IterLimitExceededNum2(0),
-              RegulaFalsiFailedIndex2(0), RegulaFalsiFailedNum2(0)
+              RegulaFalsiFailedIndex2(0), RegulaFalsiFailedNum2(0), FirstTimeThroughFlag(false)
```
Comment (rraustad) [inline src/EnergyPlus/WaterThermalTanks.hh]: This should be set to true? And added to clear_state.

**Comment by rraustad** [comment]
OK, so now do your test files show reasonable results? I assume you tested this so can you show the before and after results here like you did in the email from 6/11? This will help the reviewer find the correct results to look at in the output.

**Comment by rraustad** [comment]
There are 3 files with differences. It would be good to look at one of those to make sure something didn't break. Similar annual Facility Energy Use, tank temps still look roughly the same, comparison of desuperheater heating energy, etc. Anything you can think of to make sure these changes fix what you saw was broken and doesn't break anything that was working before. Nice job! Oh, and a unit test is required. If you don't have budget for this type of work let me or someone else know to pick up where you left off.

File: src/EnergyPlus/WaterThermalTanks.cc (hunk 1 above)
Comment (yzhou601) [reply src/EnergyPlus/WaterThermalTanks.cc:8681]: After fixing the save as what we talked about in the email, the water system energy use changed from 100+ to 40+, those points when desuperheater is "off" are working on well. But for those points when source side is "on", E+ is till giving extreme values. Then I found the ``Tank.SourceInletTemp`` still being calculated  based on the results from previous iteration(not the saved conditions) caused this problem, like the source outlet temperature (=``node(waterinletnode).temp``) is set the previous iterated tank temperature which is under extreme condition. So basically the most important change that fixed the problem is "Node(WaterInletNode).Temp = WaterThermalTank(WaterThermalTankNum).SavedSourceOutletTemp;" . Others are set just for consistency.

File: src/EnergyPlus/WaterThermalTanks.hh (hunk 2 above)
Comment (yzhou601) [reply src/EnergyPlus/WaterThermalTanks.hh]: Ok I set it to be true. And for the ``clear_state``, would the "WaterHeaterDesuperheater.deallocate();" take care of that?

Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.hh]: Duh. Yes deallocating the desuperheater struct will take care of that.

**Comment by yzhou601** [comment]
@rraustad Hi, Richard, thanks for your suggestions. Yes it now works well with my desuperheater model, and I'd very love to share the results. As for the unit test, I added one, it couldn't be better if there's someone reviewing the test to make sure it hitting the bug and verifying the fix. 

### Before
----

water systems   energy

|              | model1 | model2 |
| -------- |:---------:|---------:|
|baseline |  13.21   |  11.09    |
|desuperheater | 6.07 | 119.2|

Model 2 Variables plots

Jan Heater Energy

June Heater Energy

Jan Tank temp

June Tank Temp


### After
----

water systems   energy

|  |Model1|Model2|
|-|-|------:|
|baseline|13.21|11.09|
|desuperheater|5.61|8.21|

Model 2 Variable plots

image (6)

image (7)

image (4)

image (5)

Now it makes more sense to me, the Jan tank temperature results show a little bit difference between desuperheater and baseline models at the beginning, might be small difference between initialization of these two, and there's a small desuperheater period at 01/02 which is supposed to cause difference. But overall they overlapped a lot during water heater periods. And because the desuperheater have a higher setpoint schedule(0.5 higher in this case with deadband 0.2), its tank temperatures in June is higher than baseline model.

The energy variables are also looking much reasonable in this branch.

For the model 1 results, the changes didn't impact baseline model but makes desupereheater more beneficial by eliminating the previous iteration impact, which is also expected.

**Review by rraustad — APPROVED** [review]
The changes look reasonable and before and after results are as expected.

**Comment by rraustad** [comment]
This pull request is marked as draft status and cannot be merged. That's OK for now, a few more eyes on review wouldn't hurt.

**Comment by yzhou601** [comment]
@rraustad Thanks, Richard, I've switched this PR to open.

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 3]
```diff
@@ -8753,14 +8753,21 @@ namespace WaterThermalTanks {
...
             // Save conditions from end of previous system timestep
             // Every iteration that does not advance time should reset to these values
             WaterThermalTank(WaterThermalTankNum).SavedTankTemp = WaterThermalTank(WaterThermalTankNum).TankTemp;
+            WaterThermalTank(WaterThermalTankNum).SavedSourceOutletTemp = WaterThermalTank(WaterThermalTankNum).SourceOutletTemp;
             WaterHeaterDesuperheater(DesuperheaterNum).SaveMode = WaterHeaterDesuperheater(DesuperheaterNum).Mode;
+            WaterHeaterDesuperheater(DesuperheaterNum).FirstTimeThroughFlag = false;
+        }
+
+        if (!FirstHVACIteration) {
+            WaterHeaterDesuperheater(DesuperheaterNum).FirstTimeThroughFlag = true;
```
Comment (nmerket) [inline src/EnergyPlus/WaterThermalTanks.cc:8766]: Should this be an `else` to the previous `if` statement?

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 4]
```diff
@@ -2182,3 +2183,291 @@ TEST_F(EnergyPlusFixture, StratifiedTankSourceFlowRateCalc) {
...
+    Tank.TankTemp = 20.0;
+    DataHeatBalance::HeatReclaimDXCoil(DXNum).AvailCapacity = 500;
+    WaterThermalTanks::CalcDesuperheaterWaterHeater(TankNum,FirstHVAC);
+    // Flag changed from false to true
+    EXPECT_TRUE(Desuperheater.FirstTimeThroughFlag);
+    // Saved temperature not supposed to change
+    EXPECT_EQ(Tank.SavedTankTemp,50);
+    EXPECT_EQ(Node(Desuperheater.WaterInletNode).Temp, 50);
+    EXPECT_GT(Tank.SourceInletTemp, 50);
+    EXPECT_GT(Tank.TankTemp, 50);
```
Comment (nmerket) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:2471]: Nice unit test!

**Review by nmerket — APPROVED** [review]
Looks good to me.

File: src/EnergyPlus/WaterThermalTanks.cc (hunk 3 above)
Comment (yzhou601) [reply src/EnergyPlus/WaterThermalTanks.cc:8766]: @nmerket Good point, might be more clear if using ``else if`` ?

**Comment by yzhou601** [comment]
> @rraustad Hi, Richard, thanks for your suggestions. Yes it now works well with my desuperheater model, and I'd very love to share the results. As for the unit test, I added one, it couldn't be better if there's someone reviewing the test to make sure it hitting the bug and verifying the fix.
> 
> ### Before
> water systems energy
> 
> model1	model2
> baseline	13.21	11.09
> desuperheater	6.07	119.2
> Model 2 Variables plots
> 
> Jan Heater Energy
> 
> June Heater Energy
> 
> Jan Tank temp
> 
> June Tank Temp
> 
> ### After
> water systems energy
> 
> Model1	Model2
> baseline	13.21	11.09
> desuperheater	5.61	8.21
> Model 2 Variable plots
> 
> image (6)
> 
> image (7)
> 
> image (4)
> 
> image (5)
> 
> Now it makes more sense to me, the Jan tank temperature results show a little bit difference between desuperheater and baseline models at the beginning, might be small difference between initialization of these two, and there's a small desuperheater period at 01/02 which is supposed to cause difference. But overall they overlapped a lot during water heater periods. And because the desuperheater have a higher setpoint schedule(0.5 higher in this case with deadband 0.2), its tank temperatures in June is higher than baseline model.
> 
> The energy variables are also looking much reasonable in this branch.
> 
> For the model 1 results, the changes didn't impact baseline model but makes desupereheater more beneficial by eliminating the previous iteration impact, which is also expected.

The results for my test file didn't change after new commits, the same as quoted. I think it's ready to go.

File: src/EnergyPlus/WaterThermalTanks.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.cc:8766]: So why didn't clang catch the formatting at lines 8763 - 8765? Should have been "} else if () {" on 1 line. @yzhou601 do you have clang enabled?

Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.cc:8766]: Well, I just tried and clang did not change lines 8763-8765. So I guess this is OK.

**Comment by rraustad** [comment]
I have reviewed the changes in results for the defect file and results now look reasonable. The unit test accurately tests the saving of the previous iterations tank and source outlet temperature. This branch is ready for merge.

File: src/EnergyPlus/WaterThermalTanks.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.cc:8681]: These 2 lines are the only thing about these changes that are of concern. Lines 8676 and 8681. I would think that the water temperature entering the desuperheater is a result of what the tank did this iteration. So it would seem the Tank.SourceOutletTemp would be more accurate. It's important that the tank be simulated based on the final tank temperature from the previous iteration, but the desuperheater, I would think, should use the result from this time step. I know you told me the results looked more accurate after this change but I still have a concern that the desuperheater is not using the correct inlet water temp.

Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.cc:8681]: It wasn't these initialization lines, it was line 8770 below. When I changed that to use SourceOutletTemp, the water heater Water Heater Source Side Heat Transfer Energy did not match the coil's Water Heater Heating Energy report. So this does look like the correct fix for this issue. I can sleep better now.

Comment (yzhou601) [reply src/EnergyPlus/WaterThermalTanks.cc:8681]: @rraustad The water temperature entering the desuperheater is used for calculating the source side temperature entering the tank. Then it calls the ``CalcWaterThermalTankMixed`` function. So I think it should be based on the saved tank conditions from previous time step (if use the previous iteration tank condition, the source inlet temperature would still be crazy and not consistent with tank calculation which is using saved conditions). The lines you pointed out is the outlet node temperature from desuperheater (which enters tank), they would be updated in the following part of codes to make use of reclaimed heat, so it's just an initialization in this place.

Comment (yzhou601) [reply src/EnergyPlus/WaterThermalTanks.cc:8681]: @rraustad Ok I got it, yes this line is the most important one that fixed the issue. Thanks very much for your help!! Sorry for bringing additional worries 😝

Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.cc:8681]: Documenting what I found just now. Using this branch the desuperheater coil tracks water tank source energy transfer better (much better) than using the current iteration tank outlet temp as the desuperheater coil inlet temp. So what is done in this branch is very close.

image
