### PR TITLE
Fix AirLoop Component Loads Report Coincident Peak

### LINKED ISSUE #9451: AirLoop Component Load Summary not sizing for coincident
Issue overview
--------------
Here is a description from a user:

Cove Tool has a question about the component load summary reports.

Basically, the AirLoop Component Load Summary is showing the noncoincident peak (sum of zone peaks) rather than the coincident peak, regardless of the Concident/Nonconcident status in the Sizing:System object.

It is seemingly related to this issue: [https://github.com/NREL/EnergyPlus/issues/6337](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FEnergyPlus%2Fissues%2F6337&data=05%7C01%7CEdwin.Lee%40nrel.gov%7C33f08c4b734242c778ca08da3927fd6a%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637885142236592703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d7EJ%2FCeIWMagKmQ5Czovq1tZIrRoHmd%2FcKid%2B0dbJsI%3D&reserved=0)

Is there a way to see if the ‘else’ portion of this method ([https://github.com/NREL/EnergyPlus/blob/da69d5b3e21eeab7be9c29b19ec2a98e248abac5/src/EnergyPlus/OutputReportTabular.cc#L11846-L11870](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FEnergyPlus%2Fblob%2Fda69d5b3e21eeab7be9c29b19ec2a98e248abac5%2Fsrc%2FEnergyPlus%2FOutputReportTabular.cc%23L11846-L11870&data=05%7C01%7CEdwin.Lee%40nrel.gov%7C33f08c4b734242c778ca08da3927fd6a%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637885142236592703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXafc8BH%2ByADXqqzNx%2BKQbiDX70Z1tloW0tl%2BDz0soY%3D&reserved=0)) of the Air Loop Component Load is getting called?

Or is ‘iZone’ the correct argument here to get ‘coolDesSelected’ and ‘timeCoolMax’?
[https://github.com/NREL/EnergyPlus/blob/da69d5b3e21eeab7be9c29b19ec2a98e248abac5/src/EnergyPlus/OutputReportTabular.cc#L11851-L11852](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FEnergyPlus%2Fblob%2Fda69d5b3e21eeab7be9c29b19ec2a98e248abac5%2Fsrc%2FEnergyPlus%2FOutputReportTabular.cc%23L11851-L11852&data=05%7C01%7CEdwin.Lee%40nrel.gov%7C33f08c4b734242c778ca08da3927fd6a%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637885142236592703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=12%2BiVu26La6aYMCcWC%2BZubSyER3E7hPX4VUTe%2BAuzEo%3D&reserved=0) 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
Fixes #9451 

Cooling and heating peak loads reported in htm are not for coincident. The changes reported values are

Cooling Peak Conditions Table

Peak Sensible Load with Sizing Factor [W]
Difference Due to Sizing Factor [W]
Peak Sensible Load [W]
Difference Between Peak and Estimated Sensible Load [W]

Heating Peak Conditions Table

Peak Sensible Load with Sizing Factor [W]
Difference Due to Sizing Factor [W]
Peak Sensible Load [W]
Difference Between Peak and Estimated Sensible Load [W]

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [X ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
@lgu1234 I've been searching the testfiles looking for one that has AirLoopComponentLoadSummary or AllSummaryAndSizingPeriod or AllSummaryMonthlyAndSizingPeriod. Is there no example file that produces the AirLoopComponentLoadSummary?

**Comment by lgu1234** [comment]
@mjwitte I added one more output of AirLoopComponentLoadSummary in the Output:Tqable:SummaryReports object in the test file. The file was uploaded a while ago. Please check and let me know if you need more information for review.

**Comment by JasonGlazer** [comment]
This pull request is addressing #9451

**Comment by JasonGlazer** [comment]
@lgu1234 thanks for taking on fixing this bug. I was able to reproduce it (note the test file in the repo is really a 9.6 file not 9.5).

First, the fix needs to also be apply to the Facility Component Summary report as well. It is still showing the sum of the non-coincident peaks. 

Second, the fix that you provided which is overwriting the peakDesSensLoad and designPeakLoad doesn't seem right to me. The call to CombineLoadCompResults() a few lines above that combine the zone loads at the time of the peak. I suspect that the time of when this is happening is not working properly. Either way, I suspect the problem is lines before this. By just overwriting these, it is not fixing the fundamental problem that we probably don't have the right pieces to add up to the coincident peak.

**Comment by Myoldmopar** [comment]
@lgu1234 I pulled this branch, and added a new unit test that successfully reaches that new section of code inside OutputReportTabular.  At this point I'm not sure the best values to add to each member variable on each struct to fully exercise the changes, but the unit test is there, and I feel like with the right values, we could use it to exercise the effect of this PR.  However, with @JasonGlazer 's last comment, I'm not sure I should push my change up in case it's the wrong direction.  So I'll hold off and let that resolve first, then we can discuss the unit test.

Since I'm not pushing up my changes (yet), I'll just throw my unit test code here for now.  This is simply the minimal set of allocations and flags that I needed to set in order to reach the new code inside the `WriteLoadComponentSummaryTables` function.  I was planning on doing the same thing for the changes inside SimAirServingZones.

```
TEST_F(EnergyPlusFixture, OutputReportTabularTest_CoincidentStuff)
{
    state->dataSize->NumSysSizInput = 1;

    // Set up required surface data
    state->dataSurface->Surface.allocate(1);
    auto &thisSurf = state->dataSurface->Surface[0];
    thisSurf.ExtBoundCond = DataSurfaces::Ground;
    thisSurf.Class = DataSurfaces::SurfaceClass::Floor;
    thisSurf.GrossArea = 1.0;

    // Set up required zone data
    state->dataGlobal->NumOfZones = 1;
    state->dataHeatBal->Zone.allocate(state->dataGlobal->NumOfZones);
    state->dataZoneEquip->ZoneEquipConfig.allocate(state->dataGlobal->NumOfZones);

    // Set up required air loop data
    state->dataHVACGlobal->NumPrimaryAirSys = 1;
    state->dataSize->FinalSysSizing.allocate(state->dataHVACGlobal->NumPrimaryAirSys);
    state->dataSize->SysSizPeakDDNum.allocate(state->dataHVACGlobal->NumPrimaryAirSys);
    state->dataAirLoop->AirToZoneNodeInfo.allocate(state->dataHVACGlobal->NumPrimaryAirSys);
    state->dataSize->SysSizInput.allocate(state->dataHVACGlobal->NumPrimaryAirSys);
    auto &thisSysSizInput = state->dataSize->SysSizInput[0];
    thisSysSizInput.AirLoopNum = 1;
    thisSysSizInput.SizingOption = DataSizing::Coincident;

    // Set up flags for the function logic
    state->dataOutRptTab->displayAirLoopComponentLoadSummary = true;
    state->dataGlobal->CompLoadReportIsReq = true;
    WriteLoadComponentSummaryTables(*state);
}
```

**Comment by lgu1234** [comment]
@JasonGlazer Thanks for your comments. Here are my answers to your comments.

1. First, the fix needs to also be apply to the Facility Component Summary report as well. It is still showing the sum of the non-coincident peaks.

Thanks for pointing it to me. I also modify the code for Facility Component. Coincident peaks are also reported correctly. I will upload the code soon.

2. Second, the fix that you provided which is overwriting the peakDesSensLoad and designPeakLoad doesn't seem right to me. The call to CombineLoadCompResults() a few lines above that combine the zone loads at the time of the peak. I suspect that the time of when this is happening is not working properly. Either way, I suspect the problem is lines before this. By just overwriting these, it is not fixing the fundamental problem that we probably don't have the right pieces to add up to the coincident peak.

What I have done was to revise output variable values to show either Coincident or NonCoincident. I totally agree with you that fundamental changes may be needed. However, it is beyond the bug fix scope. We may need to raise an issue for a new feature. 

Here is my observation. For Zone loop is implemented at every level of zone, AirLoop, and Facility. My opinion is that in order to report outputs for each airLoop, it should only do a loop for each system. It should be true for Facility level also. It needs to sum output values for each AirLoop.

**Comment by Myoldmopar** [comment]
@JasonGlazer when you get a chance, could you respond to the latest update here?  I'm going to hold off from any effort on this until I know it is generally settled.  Thanks!

**Comment by JasonGlazer** [comment]
@lgu1234 I guess I'm not sure I agree with your approach. It seems like we are not really fixing the bug but just overwriting the value that is not being calculated correctly. Doesn't this mean that the component loads themselves are probably wrong since they are at the wrong time? This is a tricky bug but I still think the solution is to get the time that is being used correct rather than overwriting the totals.

**Comment by lgu1234** [comment]
@JasonGlazer Thanks for your comments. I would like to say this is a reporting issue. The current load calculations provide non-coincident load in the system and facility levels. What I have done was to recalculate component loads with coincident conditions and overwrite output variables to provide correct values. It may not be perfect. As I mentioned before, the fundamental change is beyond the scope of bug fix. Therefore, it is a temp fix and may need to be revised later. I think we allow these type of approach.

In addition, have you had a chance to verify if the component load values are correct or not.

**Comment by JasonGlazer** [comment]
@lgu1234 when I run the test file, I am still getting the facility total for the Peak Sensible Load with Sizing Factor to be the same as the sum of the three zones rather than the value from the AHU, so I suspect something still needs to be fixed.

As far as the component loads, they do seem to be working as expected. I looked at cooling sensible delayed for the roof, exterior wall, ground contact floor, fenestration total, and grand total for the three zones and for the AHU and Facility. The three zones when added up are significantly higher than the AHU and the Facility as you would expect. So the component loads seem to be working.

**Comment by lgu1234** [comment]
@JasonGlazer Thanks for taking time to look at simulation results. When I look at eplustbl.htm files, I find Peak Sensible Load with Sizing Factor are the same from both AHU and Facility.
AHU
AHU
Facility
Facility
 
Of course, heating peak loads are not changed, because loads are not varied with time.

Is it possible for you show me more specifically, which file and which location? 

" I am still getting the facility total for the Peak Sensible Load with Sizing Factor to be the same as the sum of the three zones rather than the value from the AHU, so I suspect something still needs to be fixed."

Thanks.

**Comment by JasonGlazer** [comment]
@lgu1234 sorry, you are right. I must have been looking at an older version of the file. Everything looks fine.

File: src/EnergyPlus/DataSizing.hh [hunk 1]
```diff
@@ -827,6 +827,10 @@ namespace DataSizing {
 
         Real64 SysCoolCoinSpaceSens; // sum of zone space sensible cooling loads at coincident peak
         Real64 SysHeatCoinSpaceSens; //  sum of zone space sensible heating loads at coincident peak
+        Real64 SysDesCoolLoad;       // system peak load with coincident
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataSizing.hh:830]: In general, when you add new member variables to classes, please initialize them right where you declare them `Real64 SysDesCoolLoad = 0.0;`.  This is OK for now assuming there are no other changes needed.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 2]
```diff
@@ -14526,30 +14526,39 @@ void WriteLoadComponentSummaryTables(EnergyPlusData &state)
                         CombineLoadCompResults(AirLoopHeatCompLoadTables(iAirLoop), AirLoopZonesHeatCompLoadTables(iZone), mult);
                     }
                 }
+                auto &airLoopCoolTable = AirLoopCoolCompLoadTables(iAirLoop);
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:14526]: References to object instances, :+1: Nice and clean.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 3]
```diff
@@ -14642,6 +14651,35 @@ void WriteLoadComponentSummaryTables(EnergyPlusData &state)
                 CombineLoadCompResults(FacilityHeatCompLoadTables, FacilityZonesHeatCompLoadTables(iZone), mult);
             }
 
+            bool CoincidentFlag = false;
+            for (int SysSizIndex = 1; SysSizIndex <= state.dataSize->NumSysSizInput; ++SysSizIndex) {
+                if (state.dataSize->SysSizInput(SysSizIndex).SizingOption == DataSizing::Coincident) {
+                    CoincidentFlag = true;
+                }
+            }
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc]: So if **any** system requests sizing, then they all report it this way?  Sorry if that's a silly question.

**Review by Myoldmopar — COMMENTED** [review]
Overall this seems like a clean minimal set of changes.  Adding a few new variables to track coincident data and tracking them is fine.  I am a little curious about the trigger for making them all coincident based on a single flag.  Otherwise I think this is good to go from a code inspection perspective.

File: src/EnergyPlus/DataSizing.hh (hunk 1 above)
Comment (lgu1234) [reply src/EnergyPlus/DataSizing.hh:830]: @Myoldmopar These new variables are initialized at 0 in the default contractor:

Start from Line 834
        // Default Constructor
        SystemSizingData()
            : LoadSizeType(0), SizingOption(0), CoolOAOption(0), HeatOAOption(0), DesOutAirVolFlow(0.0), SysAirMinFlowRat(0.0),
              SysAirMinFlowRatWasAutoSized(false), PreheatTemp(0.0), PrecoolTemp(0.0), PreheatHumRat(0.0), PrecoolHumRat(0.0), CoolSupTemp(0.0),
              HeatSupTemp(0.0), CoolSupHumRat(0.0), HeatSupHumRat(0.0), CoolAirDesMethod(0), HeatAirDesMethod(0), InpDesCoolAirFlow(0.0),
              InpDesHeatAirFlow(0.0), CoinCoolMassFlow(0.0), EMSOverrideCoinCoolMassFlowOn(false), EMSValueCoinCoolMassFlow(0.0),
              CoinHeatMassFlow(0.0), EMSOverrideCoinHeatMassFlowOn(false), EMSValueCoinHeatMassFlow(0.0), NonCoinCoolMassFlow(0.0),
              EMSOverrideNonCoinCoolMassFlowOn(false), EMSValueNonCoinCoolMassFlow(0.0), NonCoinHeatMassFlow(0.0),
              EMSOverrideNonCoinHeatMassFlowOn(false), EMSValueNonCoinHeatMassFlow(0.0), DesMainVolFlow(0.0), EMSOverrideDesMainVolFlowOn(false),
              EMSValueDesMainVolFlow(0.0), DesHeatVolFlow(0.0), EMSOverrideDesHeatVolFlowOn(false), EMSValueDesHeatVolFlow(0.0), DesCoolVolFlow(0.0),
              EMSOverrideDesCoolVolFlowOn(false), EMSValueDesCoolVolFlow(0.0), SensCoolCap(0.0), TotCoolCap(0.0), HeatCap(0.0), PreheatCap(0.0),
              MixTempAtCoolPeak(0.0), MixHumRatAtCoolPeak(0.0), RetTempAtCoolPeak(0.0), RetHumRatAtCoolPeak(0.0), OutTempAtCoolPeak(0.0),
              OutHumRatAtCoolPeak(0.0), MassFlowAtCoolPeak(0.0), HeatMixTemp(0.0), HeatMixHumRat(0.0), HeatRetTemp(0.0), HeatRetHumRat(0.0),
              HeatOutTemp(0.0), HeatOutHumRat(0.0), DesCoolVolFlowMin(0.0), SystemOAMethod(0), MaxZoneOAFraction(0.0), SysUncOA(0.0),
              OAAutoSized(false), ScaleCoolSAFMethod(0), ScaleHeatSAFMethod(0), CoolingCapMethod(0), HeatingCapMethod(0), ScaledCoolingCapacity(0.0),
              ScaledHeatingCapacity(0.0), FloorAreaOnAirLoopCooled(0.0), FloorAreaOnAirLoopHeated(0.0), FlowPerFloorAreaCooled(0.0),
              FlowPerFloorAreaHeated(0.0), FractionOfAutosizedCoolingAirflow(1.0), FractionOfAutosizedHeatingAirflow(1.0),
              FlowPerCoolingCapacity(0.0), FlowPerHeatingCapacity(0.0), FractionOfAutosizedCoolingCapacity(1.0),
              FractionOfAutosizedHeatingCapacity(1.0), CoolingTotalCapacity(0.0), HeatingTotalCapacity(0.0), CoolingPeakLoadType(0), // wfb
              CoolCapControl(0),                                                                                                     // wfb
              sysSizeHeatingDominant(false), sysSizeCoolingDominant(false), CoinCoolCoilMassFlow(0.0), CoinHeatCoilMassFlow(0.0),
              DesCoolCoilVolFlow(0.0), DesHeatCoilVolFlow(0.0), DesMainCoilVolFlow(0.0), SysHeatCoilTimeStepPk(0), SysHeatAirTimeStepPk(0),
              HeatDDNum(0), CoolDDNum(0), SysCoolCoinSpaceSens(0.0), SysHeatCoinSpaceSens(0.0), SysDesCoolLoad(0.0), SysCoolLoadTimeStepPk(0),
              SysDesHeatLoad(0.0), SysHeatLoadTimeStepPk(0)

File: src/EnergyPlus/OutputReportTabular.cc (hunk 3 above)
Comment (lgu1234) [reply src/EnergyPlus/OutputReportTabular.cc]: @Myoldmopar Good point. Let me look at this issue further.

File: src/EnergyPlus/DataSizing.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DataSizing.hh:830]: @lgu1234 yes, I know, and that's fine for now.  But in the future, if you add new variables, don't add them to the default constructor list, just initialize them right where you declare them.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 3 above)
Comment (lgu1234) [reply src/EnergyPlus/OutputReportTabular.cc]: @Myoldmopar I checked the code carefully and think CoincidentFlag is not necessary, because all variables of peak loads are overridden in the system level with coincident, while remain as is with noncoincident.

I am going to upload the change soon.

**Comment by lgu1234** [comment]
@Myoldmopar I upload the revision a while ago. Here is a test file with 3 AirLoops. The first one with coincident sizing , while other two have noncoincident sizing
[RefBldgMediumOfficeNew2004_Chicago1.idf.txt](https://github.com/NREL/EnergyPlus/files/9162021/RefBldgMediumOfficeNew2004_Chicago1.idf.txt)
.

File: src/EnergyPlus/DataSizing.hh (hunk 1 above)
Comment (lgu1234) [reply src/EnergyPlus/DataSizing.hh:830]: @Myoldmopar OK. I will do. Just curios, don't we need default constructor any more in the future?

Comment (Myoldmopar) [reply src/EnergyPlus/DataSizing.hh:830]: In almost all cases in the code, we don't need the default constructor.  Nearly all of them just have an initializer list and an empty body.  And all that does is separate the variable initial value from the declaration, making it hard to find, makes the compiler complain when you have things out of order in the initializer list, and cause line changes away from the variable itself when you modify one.  If the constructor needs to do some work, then yes, by all means, create a custom constructor.  But if it's just there with an initializer list and that's all, it should not be needed at all and just initialize at the declaration site.

**Comment by Myoldmopar** [comment]
@lgu1234 thanks for cleaning up that flag.  I'm glad it turned out to just not be needed at all.  Linux CI is trying to get going, but will be a while before it fully catches up.  This branch was all clean before, and Windows and Mac are completely green with your latest change.  I am going to go ahead and merge this one in as it looks like it won't cause any diffs to pop up for other branches as CI runs today.  Thanks.
