### PR TITLE
Fix Output:Table:SummaryReports monthly reports and Variable Name case-sensitivity in Output:Variable

### LINKED ISSUE #7019: SetpointsNotMetWithTemperaturesMonthly table report all zeros unless the corresponding output:variable objects are added to the idf
Issue overview
--------------
User noted that output for the SetpointsNotMetWithTemperaturesMonthly and ComfortReportSimple55Monthly were all zero, but the summary at the end of ABUPS was not.

### Workaround
Add the corresponding output:variable objects (any reporting frequency will work).
```
Output:Variable,*,Zone Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Heating Setpoint Not Met Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Heating Setpoint Not Met While Occupied Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Cooling Setpoint Not Met Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Cooling Setpoint Not Met While Occupied Time,annual; !- Zone Sum [hr]
```

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 9.0.1
 - Helpdesk ticket number 13082.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7019 Output:Table:SummaryReports doesn't work without variables.
Fix case-sensitivity in Output:Variable "Variable Name".

The main issue what that the `DataOutputs::FindItemInVariableList` that fails with different casing, so I made that all upper case.

I had originally actually requested the output variables needed for the report (so they show in SQL), but it isn't needed for the table to work correctly so I reverted this.

Added a unit test that fails without the fix and passes with it.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by jmarrec** [comment]
https://github.com/jmarrec/EnergyPlus/commit/b99e1c9dabb4a3b6c779f1f143da06f8c6cf336e is develop + unit test only. When running it it fails as expected.

```
[ RUN      ] EnergyPlusFixture.OutputReportTabularMonthlyPredefined_FindNeededOutputVars
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/OutputReportTabular.unit.cc:6695: Failure
      Expected: OutputReportTabular::MonthlyInput(1).numTables
      Which is: 0
To be equal to: 2
```

Also, I checked that that user defect file does work with it (and that I get actual, non zero unmet hours). I also created a simpler example : [1ZoneUncontrolled.idf.txt](https://github.com/NREL/EnergyPlus/files/2511341/1ZoneUncontrolled.idf.txt)

Without the fix, the HTML report is completely empty save for the header. With it, it works.

**Comment by jmarrec** [comment]
I’ll need to fix the unit tests that do fail regarding finditemInVariableList. Will do that tomorrow

**Comment by jmarrec** [comment]
Made DataOutputs::OutputVariableForSimulations a nested case-insensitive std::unordered_map by implementing case-insentive hasher and comparator. All tests pass now including one I (barely) extended that would check this new case-insentive behavior.

File: src/EnergyPlus/OutputProcessor.cc [hunk 1]
```diff
@@ -5550,7 +5547,9 @@ void SetupOutputVariable(std::string const &VariableName,           // String Na
 
     if (!OutputInitialized) InitializeOutput();
 
-    VarName = VariableName;
+    // Variable name without units
+    std::string VarName = VariableName;
+    //  CHARACTER(len=MaxNameLength) :: VariableNamewithUnits ! Variable name with units std format
```
Comment (mbadams5) [inline src/EnergyPlus/OutputProcessor.cc]: You don't need this line.

```suggestion
```

File: src/EnergyPlus/OutputProcessor.cc [hunk 2]
```diff
@@ -5785,7 +5783,9 @@ void SetupOutputVariable(std::string const &VariableName,           // String Na
...
```
Comment (mbadams5) [inline src/EnergyPlus/OutputProcessor.cc]: You don't need this line.

```suggestion
```

File: src/EnergyPlus/DataOutputs.hh [hunk 3]
```diff
@@ -94,14 +95,41 @@ namespace DataOutputs {
         std::unique_ptr<RE2> pattern;
         std::unique_ptr<RE2> case_insensitive_pattern;
     };
-    extern std::unordered_map<std::string, std::unordered_map<std::string, OutputReportingVariables>> OutputVariablesForSimulation;
+
+    // Two structs to have a case insensitive unordered_map. We need to have a case insenstive hasher and a case insensitive comparator
+    // (The default allocator for unordered_map is fine)
+    struct case_insensitive_hasher
```
Comment (mbadams5) [inline src/EnergyPlus/DataOutputs.hh]: These could potentially go to `UtilityRoutines.hh` since there could be other containers that could use these. However, this isn't critical since they are fine here as well.

**Review by mbadams5 — APPROVED** [review]
Looks good to me. I reviewed for potential impact to the regex Output:Variable usage but these changes don't appear to affect that.

File: src/EnergyPlus/OutputProcessor.cc (hunk 1 above)
Comment (jmarrec) [reply src/EnergyPlus/OutputProcessor.cc]: Just an FYI, I didn't add this comment, I just move the varName declaration (and the comment) to initialize on the spot rather than at the top of the file.

**Comment by jmarrec** [comment]
Thanks for the review @mbadams5. I deleted the two comments and move the comparators into UtilityRoutines (I put the actual implementation of the operators into the .cc file so we can change it without having to recompile all files referencing the UtilityRoutines.hh too)

I recompiled and ran the tests, they still pass just fine (though I know the bots will check that too)

**Comment by JasonGlazer** [comment]
@jmarrec this seems to fix all the issues that I was having with #6863

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 14 days since this pull request was last updated.

**Review by mjwitte — APPROVED** [review]
Tested with defect file, ran unit tests, all OK. Updated to current develop and will merge once CI reports back.

**Comment by mjwitte** [comment]
Looking at the CI diffs, noticed that 5ZoneWaterCooled_GasFiredSteamHumidifier.idf is showing a csv diff (but only on the detailed regression results page):
```
Not comparing field MAIN GAS HUMIDIFIER:Humidifier Gas Use Rate [W](Hourly), which appears in input files . . . 
```
Turns out that this test file has one `Output:Variable` object with a stray uppercase letter in the output variable name
```
  Output:Variable,*,Humidifier Gas USe Rate,hourly;
```
This variable has been missing from the eso and csv output. Now it's there. Just to confirm that `Output:Variable` "Variable Name" has been case-sensitive (probably since ???), pushed the entire output variable section of this idf to uppercase and only two variables showed up in the csv output using v9.0.1 - the two that are metered. With this branch, all of the variables appear (same as the non-uppercase idf). Title and description for this PR will be updated to include fixing case-sensitive variable names.

@Myoldmopar It's disappointing that none of these significant diffs (additional csv variable, table diffs, and additional tables) show in the CI summary comments. For this file, it's just a warning with
```
[decent_ci:test_result:message] AUD diffs.
[decent_ci:test_result:message] MTD diffs.
```
Will post some new issues in [regression tool](https://github.com/NREL/EnergyPlusRegressionTool/issues) to better flag these diffs so CI can report them.
