### PR TITLE
Plant sizing report and equipment summary fixes

### LINKED ISSUE #10987: Component Sizing Summary - PlantLoop incorrect table values
### Issue overview

The Component Sizing Summary - PlantLoop table does not show the design supply or return temperature for all example files, and sometimes, the return temperature for the cooling loop is lower. The sizing option column shows a number instead of either coincident or noncoincident as intended, and the minimum flow fraction shows zero when it should sometimes show a positive value. In addition, this table does not appear to be consistently populated.

Observed this with example files: ASHRAE901_HotelLarge_STD2019_Denver, HVACStandAloneERV_Economizer, 5ZoneVAV-Pri-SecLoop

### Operating System (Multiple choices)

Windows

### Operating System Version

10

### Version of EnergyPlus

24.2

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #10987
- Add new function `reportSizerStrOutput` that allows component sizing to output a string.
- For PlantLoop and CondenserLoop change component sizing output:
    - Always report sizing values whether autosized or hard-sized
    - Change "Sizing option (Coincident/NonCoincident), 1.00000" --> "Sizing Option, NonCoincident".
- Fix Table Output, Equipment Summary, PlantLoop or CondenserLoop subtable
    - Fix values reported for "Provides Heating", "Provides Cooling", "Maximum Loop Flow Rate", and "Minimum Loop Flow Rate".
    - Always report values whether autosized or hard-sized
    - Add columns for "Design Supply Temperature", "Design ReturnTemperature", and "Design Capacity".

## Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Here is an initial update to the relevant tables in the Component Sizing Summary for 5ZoneVAV-Pri-SecLoop.idf:
image
image



There is also this table in the Equipment Summary report which is somewhat redundant and also needs repairs:
image

For the component sizing summary:
* The reason the table wasn't populating before is that it only reported for values that were actually autosized. The changes at this point force reporting for hard-sized values as well. However, the proper way to do this would be to report both Design Size and User-Specifed values, the way most other components do:
image

* For the coincident/non-coincident field, the reporting functions used for component sizing (`BaseSizer::reportSizerOutput`, `OutputReportPredefined::AddCompSizeTableEntry`, and `OutputReportTabular::WriteComponentSizing`) all expect a numeric value, so wedging in a string value would require some extra effort. It would be easy to move this to the Equipment Summary table instead, even though it's related to sizing, but it's not an autosized value result (which is what Component Sizing is generally supposed to be reporting).
* This also applies to Supply Temperature, Return Temperature, and Minimum Loop Flow Rate which are not autosizable inputs.

**Comment by mjwitte** [comment]
1. Plant loops currently report sizing results only if autosized and don't use the "Design Size" "User-Specified" labels.
```
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Maximum Loop Flow Rate [m3/s], 5.96451E-004
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Plant Loop Volume [m3], 7.15741E-002
```
I plan to add the logic to report "Design Size" and "User-Specified" values.

2. These informationl values that aren't really autosized were added to the "Component Sizing" reporting to support RPD:
```
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Design Supply Temperature [C], 82.00000
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Design Return Temperature [C], 71.00000
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Sizing option (Coincident/NonCoincident), 1.00000
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Minimum Loop Flow Rate [m3/s], 0.00000
 Component Sizing Information, PlantLoop, HOT WATER LOOP, Design Capacity [W], 27539.63807
```
I'm planning to move these to the Equipment Summary table reports.

@JasonGlazer @rraustad @EnergyArchmage Please comment if you disagree.

**Comment by JasonGlazer** [comment]
Thanks for working on this.

**Comment by rraustad** [comment]
@mjwitte I am all for reporting data whether autosized or not. The user should not have to search for data that is not in the eio or tables, even though the user entered that data.

> However, the proper way to do this would be to report both Design Size and User-Specifed values, the way most other components do

I think the EIR chiller data shows user-specified only when hard-sized, or if no plant sizing is performed (i.e., the tables are dynamic). If autosized then the user-specified column would not show up? I don't see where user-specified comes from for autosized inputs. I searched for "User-Specified Reference Chilled Water Flow Rate" and only found it here and in the err file if difference > 10%.

            if (this->EvapVolFlowRateWasAutoSized) {
                this->EvapVolFlowRate = tmpEvapVolFlowRate;
                if (state.dataPlnt->PlantFinalSizesOkayToReport) {
                    BaseSizer::reportSizerOutput(
                        state, "Chiller:Electric:EIR", this->Name, "Design Size Reference Chilled Water Flow Rate [m3/s]", tmpEvapVolFlowRate);
                }

            } else { // Hard-size with sizing data
                if (this->EvapVolFlowRate > 0.0 && tmpEvapVolFlowRate > 0.0) {
                    Real64 EvapVolFlowRateUser = this->EvapVolFlowRate;
                    if (state.dataPlnt->PlantFinalSizesOkayToReport) {
                        BaseSizer::reportSizerOutput(state,
                                                     "Chiller:Electric:EIR",
                                                     this->Name,
                                                     "Design Size Reference Chilled Water Flow Rate [m3/s]",
                                                     tmpEvapVolFlowRate,
                                                     "User-Specified Reference Chilled Water Flow Rate [m3/s]",
                                                     EvapVolFlowRateUser);

        if (!this->EvapVolFlowRateWasAutoSized && state.dataPlnt->PlantFinalSizesOkayToReport && (this->EvapVolFlowRate > 0.0)) {
            BaseSizer::reportSizerOutput(
                state, "Chiller:Electric:EIR", this->Name, "User-Specified Reference Chilled Water Flow Rate [m3/s]", this->EvapVolFlowRate);
        }

**Comment by EnergyArchmage** [comment]
Reporting plant loop Design Capacity regardless of autosizing is a good idea.   

I guess moving reports to Equipment Summary table means they no longer also show up in the EIO as they do when called as Component Sizing Information?  If so, that is a drawback for us developers and anyone who prefers the EIO text for easy diff'ing.

**Comment by mjwitte** [comment]
> Reporting plant loop Design Capacity regardless of autosizing is a good idea.
> 
> I guess moving reports to Equipment Summary table means they no longer also show up in the EIO as they do when called as Component Sizing Information? If so, that is a drawback for us developers and anyone who prefers the EIO text for easy diff'ing.

* Maybe I'm being too much of a purist about what constitutes "component sizing" results and what doesn't. Perhaps I should leave things where they are and just make sure the values always get reported as a sizing result (whether autosized, or hard-sized, or calculated e.g. Design Capacity) and let these continue to report as a component sizing result without indicating "Design Size or User-Specified".

* And possibly duplicate some values in the Equipment Summary?

* Where would you like to see "Conicident/NonCoincident"? I could extend the report sizing functions to accept a string value, or simply move this to the equipment summary table.

**Comment by EnergyArchmage** [comment]
> I could extend the report sizing functions to accept a string value

This would be really useful I think.  I have wanted this for a while; perfect for Coincident/NonCoincident reporting.

**Comment by Myoldmopar** [comment]
@mjwitte now that the plant location and other PRs have been merged, do you want to pull develop in and update this branch with those changes?  It doesn't show conflicted, so you might not actually have to, but I can't tell immediately.  It does need clang formatting it looks like anyway.  Let me know if you want me to do anything here.

**Comment by mjwitte** [comment]
@Myoldmopar Thanks. There's more actual work to do here, and this doesn't really overlap with the plantloc work, because this PR is at the plant-loop level so plantloc doesn't even apply, duh.

**Comment by mjwitte** [comment]
Here's some current samples. For 5ZoneVAV-Pri-SecLoop which has `Sizing:Plant` objects:
Component Sizing report
image

Equipment Summary report
image


For CoolingTower.idf which does not have `Sizing:Plant` objects:
Component Sizing report
image

Equipment Summary report
image

File: src/EnergyPlus/SizingManager.cc [hunk 1]
```diff
@@ -3471,21 +3471,16 @@ void GetSystemSizingInput(EnergyPlusData &state)
...
-                ShowSevereError(state, format("{}=\"{}\", invalid data.", cCurrentModuleObject, state.dataIPShortCut->cAlphaArgs(iNameAlphaNum)));
-                ShowContinueError(state,
-                                  format("... incorrect {}=\"{}\".",
-                                         state.dataIPShortCut->cAlphaFieldNames(iSizingOptionAlphaNum),
-                                         state.dataIPShortCut->cAlphaArgs(iSizingOptionAlphaNum)));
-                ShowContinueError(state, "... valid values are Coincident or NonCoincident.");
-                ErrorsFound = true;
-            }
+        SysSizInput(SysSizIndex).SizingOption = static_cast<SizingConcurrence>(
+            getEnumValue(SizingConcurrenceNamesUC, Util::makeUPPER(state.dataIPShortCut->cAlphaArgs(iSizingOptionAlphaNum))));
```
Comment (rraustad) [inline src/EnergyPlus/SizingManager.cc:3475]: Only 2 possible values, Invalid isn't one of them (i.e., warning will never execute, before or after this change).

    Sizing:System,
      A3, \field Type of Zone Sum to Use
        \type choice
        \key Coincident
        \key NonCoincident
        \default NonCoincident

File: src/EnergyPlus/Plant/PlantManager.cc [hunk 2]
```diff
@@ -3041,327 +3041,237 @@ void SizePlantLoop(EnergyPlusData &state,
...
+            Real64 NumBrSizFac = 0.0;
+            Real64 LoopSizFac = 0.0;
+            Real64 MaxSizFac = 0.0;
+            auto &supplySide = loop.LoopSide(LoopSideLocation::Supply);
+            for (int BranchNum = 1; BranchNum <= supplySide.TotalBranches; ++BranchNum) {
+                auto &supplyBranch = supplySide.Branch(BranchNum);
+                Real64 BranchSizFac = 0.0;
+                supplyBranch.PumpSizFac = 1.0;
+                if (supplySide.NodeNumIn == supplyBranch.NodeNumIn) continue;
+                if (supplySide.NodeNumOut == supplyBranch.NodeNumOut) continue;
```
Comment (rraustad) [inline src/EnergyPlus/Plant/PlantManager.cc]: This is interesting because this excludes the inlet and outlet branch from the BranchSizFac calculation and this was happening before. I know heat recovery HP companions are usually installed on a plant inlet and outlet branch so I wonder how this would affect sizing for that configuration? Nothing to do here just thinking about the implication.

File: src/EnergyPlus/Plant/PlantManager.cc [hunk 3]
```diff
@@ -3041,327 +3041,237 @@ void SizePlantLoop(EnergyPlusData &state,
...
-                    OutputReportPredefined::PreDefTableEntry(state,
-                                                             state.dataOutRptPredefined->pdchPLCLMaxLoopFlowRate,
-                                                             state.dataPlnt->PlantLoop(LoopNum).Name,
-                                                             state.dataPlnt->PlantLoop(LoopNum).MaxVolFlowRate);
-                    OutputReportPredefined::PreDefTableEntry(state,
-                                                             state.dataOutRptPredefined->pdchPLCLMinLoopFlowRate,
-                                                             state.dataPlnt->PlantLoop(LoopNum).Name,
-                                                             state.dataPlnt->PlantLoop(LoopNum).MinVolFlowRate);
-                    // end std 229 plantloop equipment summary new table
                 }
```
Comment (rraustad) [inline src/EnergyPlus/Plant/PlantManager.cc]: Why was the conditional with open and close bracket left here?

**Comment by nrel-bot-2** [comment]
@mjwitte @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@JasonGlazer @rraustad @EnergyArchmage

Here are some final sample outputs. For 5ZoneVAV-Pri-SecLoop which has `Sizing:Plant` objects:
Component Sizing report
image
image

Equipment Summary report
image


For CoolingTower.idf which does not have `Sizing:Plant` objects, so supply and return temps and resulting capacity are unknown:
Component Sizing report
image
image

Equipment Summary report
image

**Comment by mjwitte** [comment]
The reasons for diffs are noted in the output rules [here](https://github.com/NREL/EnergyPlus/pull/10998/files#diff-2f276fa03ed8f80b8aa4a767fb88a679b42080521b54e691750712cc7707cd22)

**Comment by rraustad** [comment]
@mjwitte those tables look good.

File: src/EnergyPlus/DataSizing.hh [hunk 4]
```diff
@@ -1038,9 +1035,10 @@ namespace DataSizing {
         TypeOfPlantLoop LoopType = TypeOfPlantLoop::Invalid; // type of loop: 1=heating, 2=cooling, 3=condenser
         Real64 ExitTemp = 0.0;                               // loop design exit (supply) temperature [C]
         Real64 DeltaT = 0.0;                                 // loop design temperature drop (or rise) [DelK]
-        int ConcurrenceOption = 0;                           // sizing option for coincident or noncoincident
-        int NumTimeStepsInAvg = 0;                           // number of zone timesteps in the averaging window for coincident plant flow
-        int SizingFactorOption = 0;                          // option for what sizing factor to apply
+        DataSizing::SizingConcurrence ConcurrenceOption =
+            DataSizing::SizingConcurrence::NonCoincident; // sizing option for coincident or noncoincident (default)
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataSizing.hh:1039]: 👍

File: src/EnergyPlus/Autosizing/Base.cc [hunk 5]
```diff
@@ -341,6 +341,31 @@ void BaseSizer::reportSizerOutput(EnergyPlusData &state,
     }
 }
 
+void BaseSizer::reportSizerStrOutput(
+    EnergyPlusData &state, std::string_view CompType, std::string_view CompName, std::string_view VarDesc, std::string_view VarValue)
+{
```
Comment (Myoldmopar) [inline src/EnergyPlus/Autosizing/Base.cc:346]: No need for the optional parameters I guess? That's fine with me for sure.

File: src/EnergyPlus/Plant/Component.hh [hunk 6]
```diff
@@ -162,6 +162,107 @@ namespace DataPlant {
...
+        DataPlant::CtrlType::CoolingOp, //	"CoolingTower:VariableSpeed:Merkel"
+        DataPlant::CtrlType::Invalid,   //	"SwimmingPool:Indoor"
+        DataPlant::CtrlType::DualOp,    //	"GroundHeatExchanger:Slinky"
+        DataPlant::CtrlType::HeatingOp, //	"WaterHeater:HeatPump:WrappedCondenser"
+        DataPlant::CtrlType::Invalid,   //	"AirTerminal:SingleDuct:ConstantVolume:FourPipeBeam"
+        DataPlant::CtrlType::Invalid,   //	"ZoneHVAC:CoolingPanel:RadiantConvective:Water"
+        DataPlant::CtrlType::CoolingOp, //	"HeatPump:PlantLoop:EIR:Cooling"
+        DataPlant::CtrlType::HeatingOp, //	"HeatPump:PlantLoop:EIR:Heating"
+        DataPlant::CtrlType::HeatingOp  //   "DistrictHeating:Steam"
+    };
```
Comment (Myoldmopar) [inline src/EnergyPlus/Plant/Component.hh:264]: I have feelings about another list of things allocated to the same size as the others, but I will stop talking now.

File: src/EnergyPlus/SQLiteProcedures.cc [hunk 7]
```diff
@@ -1842,6 +1842,25 @@ void SQLite::addSQLiteComponentSizingRecord(std::string_view compType, // the ty
...
+        sqliteBindInteger(m_componentSizingInsertStmt, 1, m_componentSizingIndex);
+        sqliteBindText(m_componentSizingInsertStmt, 2, compType);
+        sqliteBindText(m_componentSizingInsertStmt, 3, compName);
+        sqliteBindText(m_componentSizingInsertStmt, 4, varDesc);
+        sqliteBindText(m_componentSizingInsertStmt, 7, varValue);
+
+        sqliteStepCommand(m_componentSizingInsertStmt);
+        sqliteResetCommand(m_componentSizingInsertStmt);
+    }
+}
```
Comment (Myoldmopar) [inline src/EnergyPlus/SQLiteProcedures.cc:1862]: 👍

**Review by Myoldmopar — APPROVED** [review]
Very good stuff here.  The new functions in the sizer code and the sql code are good, and lots of little cleanups along the way.  I resolved the minor conflict, and this should be good to go in.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @mjwitte @myoldmopar it has been 29 days since this pull request was last updated.

**Comment by mjwitte** [comment]
This was previously approved by @Myoldmopar and CI diffs are as expected, merging.
