### PR TITLE
Fix build error on gcc10, which has `Default to -fno-common`

### LINKED ISSUE #8459: Build error due to duplicate symbols in BCVTB utilXml
Hello all,

I've tried to compile EnergyPlus on fedora 33, gcc version: 10.2.1 20201125, and got a linking error at the very end of the process: the linker found some duplicate symbols.
After investigation, I found that these symbols come from global variables declared in utilXml.h. This header file is then included in multiple .c files. Even if the variable is not used in the .c, the compiler still defines the symbol in the corresponding .o elf file.
That obviously lead to multiple definitions of the same symbols, hence the linking errors.
How to correct this problem IMO:
move the "local global variables" out of utilXml.h, and put them all in utilXml.c.
(Buff, expStk, att, outputVarsName, ......)
After this change, everything linked fine on my system. I haven't run any simulation yet to check that it all works as expected though.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #8459

https://gcc.gnu.org/gcc-10/porting_to.html

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: third_party/BCVTB/utilXml.h [hunk 1]
```diff
@@ -76,6 +76,9 @@ derivative works thereof, in binary and source code form.
 ********************************************************************
 */
 
+#ifndef utilXml_h_INCLUDED
+#define utilXml_h_INCLUDED
```
Comment (Myoldmopar) [inline third_party/BCVTB/utilXml.h:80]: Weird, a header guard :+1:

File: third_party/BCVTB/utilXml.h [hunk 2]
```diff
@@ -136,27 +137,27 @@ typedef struct Stack2 {
 } Stack2;
 
 
-Stack2 expStk; ///< Variables for getxmlvalue function
+extern Stack2 expStk; ///< Variables for getxmlvalue function
```
Comment (Myoldmopar) [inline third_party/BCVTB/utilXml.h:140]: And extern-d globals

File: third_party/BCVTB/utilXml.c [hunk 3]
```diff
@@ -103,6 +103,32 @@ derivative works thereof, in binary and source code form.
...
+char *  outputVarsName; ///< the string pointer to the parsed output variable names
+char *  outputVarsType; ///< the string pointer to the parsed output variable types
+int *   numOutputVars;  ///< the integer pointer to the number of output variables
+char *  inputVars;      ///< the string pointer to the input variables
+int *   numInputVars;   ///< the integer pointer to the number of input variables
+int *   inputVarsType;  ///< the integer array to store the types of each input variables
+char ** inputKeys;      ///< the string array to store the types of input variable types
+int     numInputKeys;   ///< the number of input variable types
+int     source;         ///< flag for function /c getepvariables 0=EnergyPlus, 1=Ptolemy
+size_t const * strLen;     ///< the length of string parsed to this function
```
Comment (Myoldmopar) [inline third_party/BCVTB/utilXml.c:128]: With their actual declarations here.

**Review by Myoldmopar — APPROVED** [review]
Looks good to me!

**Comment by Myoldmopar** [comment]
All the CIs seem to be happy with this, as expected.  This is good to go in, thanks @jmarrec
