### PR TITLE
Fix Sizing:System Heating Design Capacity Method FractionOfAutosizedHeatingCapacity

### LINKED ISSUE #8730: Sizing:System Heating Design Capacity Method FractionOfAutosizedHeatingCapacity not working
Issue overview
--------------
When using FractionOfAutoSizedCooling or HeatingCapacity, the cooling coil size changes in the table report but the heating coil size does not.

image

The eio file shows the cooling coil size increased. The heating coil size also increased but the U-value decreased. It is suspected that the sizing for HW coil UA does not include the fraction of heating capacity factor.

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added ([5ZoneAirCooledHWCoilSizing.txt](https://github.com/NREL/EnergyPlus/files/6385036/5ZoneAirCooledHWCoilSizing.txt))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by matthew-larson**
Pull request overview
---------------------
 - Fixes #8730 
 - This pull request fixes the implementation of Sizing:System Heating Design Capacity Method FractionOfAutosizedHeatingCapacity.

FractionOfAutosizedHeatingCapacity = 1.0:
image

Before Fix:
image

After Fix:
image

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally

### CODE REVIEW

File: src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc [hunk 1]
```diff
@@ -130,6 +130,7 @@ Real64 HeatingWaterDesCoilLoadUsedForUASizer::size(EnergyPlusData &state, Real64
             }
         }
     } else if (this->curSysNum > 0) {
+        this->dataFracOfAutosizedHeatingCapacity = 1.0;
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc]: This line should not be needed since dataFracOfAutosizedHeatingCapacity is set in BaseSizerWithFanHeatInputs::initializeWithinEP as

    this->dataFracOfAutosizedHeatingCapacity = state.dataSize->DataFracOfAutosizedHeatingCapacity;

and state.dataSize->DataFracOfAutosizedHeatingCapacity is initialized to 1 in the DataSizing struct

    Real64 DataFracOfAutosizedHeatingCapacity = 1.0;

If you have a test file this is easily verified by putting a breakpoint at line 133 and checking what the value is before this line executes. If not test file, any example file with a HW coil that is autosized will do.

Comment (rraustad) [reply src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc]: I see this same thing at line 217 of HeatingCapacitySizing.cc. That line could be removed as well if this turns out the way I think it should.

File: src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc [hunk 2]
```diff
@@ -170,6 +171,9 @@ Real64 HeatingWaterDesCoilLoadUsedForUASizer::size(EnergyPlusData &state, Real64
                                            (this->finalSysSizing(this->curSysNum).PreheatTemp - CoilInTemp);
                 }
             } else {
+                if (this->finalSysSizing(this->curSysNum).HeatingCapMethod == DataSizing::FractionOfAutosizedHeatingCapacity) {
+                    this->dataFracOfAutosizedHeatingCapacity = this->finalSysSizing(this->curSysNum).FractionOfAutosizedHeatingCapacity;
+                }
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc:175]: This is inside the else for if (this->curOASysNum > 0). Couldn't the OA heating coil also be sized using this method? Is so, this conditional should be moved outside this if/else block.

**Comment by matthew-larson** [comment]
Thanks @rraustad, your comments all make sense.  I made the necessary adjustments and merged in develop.

**Comment by rraustad** [comment]
This looks better now. I or someone will need to do some final testing before this is merged.

**Comment by Myoldmopar** [comment]
I tested the defect file locally and ran all the usual tests.   I saw the coil size changing in the tabular output, CI is very happy, I think this should be ready to go in.  Thanks @rraustad and @matthew-larson !

**Comment by Myoldmopar** [comment]
Wait...debug CI isn't happy.  Looks like an array bounds issue.  That will need to be investigated.  @matthew-larson can you investigate?

**Comment by matthew-larson** [comment]
I'll check this out now.

**Comment by matthew-larson** [comment]
This failure arose when moving the statement outside the outside the else for if (this->curOASysNum > 0) block.  I also noticed that the statement is in the same else block in HeatingCapacitySizing.cc, where it's not used if this->curOASysNum > 0.  I'll see if I can track down the reason that it doesn't work if this->curOASysNum > 0.  Appears to only be in Linux too.

**Comment by Myoldmopar** [comment]
It's probably less about Linux and more about it being a debug build where array bounds are checked.

File: src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc:175]: This linux build error may show that either this sizing method applies only to air loops, or this method was not properly set up for OA systems. This input is in the System:Sizing object so that might mean it was only intended for air loop equipment. It would be OK to move this conditional back where it was and we can investigate if OA systems should also allow this same input to adjust sizing for both the air loop coil and OA system coil.

Comment (matthew-larson) [reply src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc:175]: That sounds like a plan, I'll move back into the else block and set the OA system question aside for now.

**Comment by matthew-larson** [comment]
@Myoldmopar I updated the PR based on @rraustad comment to just put the statement back in the else block to not include OA systems, as that seems to be another potential issue to look into as a bigger picture.  The ERR diff appears to be unrelated to this issue.

**Comment by Myoldmopar** [comment]
Yes, that ERR diff is a silly thing, nothing related here.  Integration coverage is all happy now, this looks super clean.  I'm willing to take this now, thanks for cleaning it up.  Merging, and goodnight!

**Comment by rraustad** [comment]
Documenting the inputs to this field. This certainly could be assumed to be air loop specific and OA coils are not included. Thank you @matthew-larson for putting this into a good place.

    Sizing:System,
     A10, \field Heating Design Capacity Method
      \type choice
      \key None
      \key HeatingDesignCapacity
      \key CapacityPerFloorArea
      \key FractionOfAutosizedHeatingCapacity
      \default HeatingDesignCapacity
      \note Enter the method used to determine the heating design capacity for scalable sizing.
      \note None is used when a heating coil not included in an airloop or this field may be blank.
      \note If this input field is left blank, then the design heating capacity is set to zero.
      \note HeatingDesignCapacity => selected when the design heating capacity value is specified or
      \note auto-sized. CapacityPerFloorArea => selected when the design heating capacity is determined
      \note from user specified heating capacity per flow area and total floor area of heated zones
      \note served by an airloop. FractionOfAutosizedHeatingCapacity => is selected when the design
      \note heating capacity is determined from a user specified fraction and the auto-sized design
      \note heating capacity of the system.

     N26, \field Fraction of Autosized Heating Design Capacity
      \type real
      \minimum 0.0
      \note Enter the fraction of auto-sized heating design capacity. Required field when capacity the
      \note heating design capacity method field is FractionOfAutosizedHeatingCapacity.
