### PR TITLE
Fix #10487 - Paths containing characters other than 7-bit ASCII cause failure on windows

### LINKED ISSUE #10487: Paths containing characters other than 7-bit ASCII cause failure
Issue overview
--------------
Running EnergyPlus with a command like the following will cause it to fail:

`energyplus.exe -d D:\ß D:\ß\sample.idf`

Output:
```
EnergyPlus Starting
EnergyPlus, Version 23.2.0-7636e6b3e9, YMD=2024.05.01 11:29
**FATAL:The SQLite database failed to open.
EnergyPlus Run Time=00hr 00min  0.19sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.
```

If however the folder were named `B` instead of `ß`, all else being equal, it would work normally.

The folder `D:\ß` actually has to exist for this error to occur. The contents of the IDF file don't seem to matter.

---

Notes - I think the problem occurs when using a folder path having any ASCII/Unicode character [over 7F](https://www.ascii-code.com/). Furthermore, varied higher bitness characters fail in different ways.

I tried the following examples as folder names (all char values in hex):

 - `B` (ASCII 42) - runs normally
 - `` (ASCII 7F or "del" - the last 7-bit value) - not a printable character, but still runs normally
 - `€` (ASCII 80 - the first 8-bit value) - fails with SQLite error
 - `Â` ([Unicode 00C2](https://unicode.scarfboy.com/?s=%C3%82)) - fails with SQLite error
 - `ß` ([Unicode 00DF](https://unicode.scarfboy.com/?s=%C3%9F)) - fails with SQLite error (the example given above)
 - `Б` ([Unicode 0411](https://unicode.scarfboy.com/?s=%D0%91)) - fails but in a different way - see below

For the example of `Б` which is 2 bytes in Unicode, EnergyPlus terminates without ever writing anything to the terminal, unlike the 128-bit ASCII and 1-byte Unicode examples which show the SQLite error.

---

**Note on relevance --** This was discovered because I support users who can have usernames containing Unicode characters, and therefore their local paths also contain that character. (_Just to point out that this is not at all a hypothetical problem._)

---

We used to use EnergyPlus 9.5 before updating to 23.2, and to my knowledge never ran into this before. Perhaps this is related to some of the command-line updates for CLI11 in 23.2 (mentioned in https://github.com/NREL/EnergyPlus/issues/10322) although that's just a guess and might not actually make sense given the SQLite error.  _[EDIT - maybe similar issues did exist earlier, I'll add a follow up post]_

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10, 11
 - Version of EnergyPlus: 23.2

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #10487

I have made a test release at https://github.com/jmarrec/EnergyPlus/releases/tag/v24.2.0-windows_non_ascii and @DaveInCaz tried it.

(`namespace fs = std::filesystem`)

As a reminder, Windows behaves differently than the rest of the world (Shocking, I know). Anyways, on all platforms we target, fs::path::value_type is `char`, except on windows where it's `wchar_t`.

With a char that has a 2 bytes unicode such as Б ([Unicode 0411](https://unicode.scarfboy.com/?s=%D0%91)), it just plain crashes everytime you call `fs::path::string()`.

The fix here is to avoid ever doing that. I narrow the path manually when either printing or passing it to for eg sqlite3 is needed.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/FileSystem.hh [hunk 1]
```diff
@@ -320,6 +313,43 @@ namespace FileSystem {
         }
     }
 
+    std::string toString(fs::path const &p);
+
+    std::string toGenericString(fs::path const &p);
+
+    fs::path appendSuffixToPath(fs::path const& outputFilePrefixFullPath, const std::string &suffix);
```
Comment (jmarrec) [inline src/EnergyPlus/FileSystem.hh]: New helpers

File: src/EnergyPlus/FileSystem.hh [hunk 2]
```diff
@@ -320,6 +313,43 @@ namespace FileSystem {
...
+
+        // Return an iterator past the end of the parsed range:
+        return it;
+    }
+
+    template <typename FormatContext> auto format(const fs::path &p, FormatContext &ctx) -> decltype(ctx.out())
+    {
+        return format_to(ctx.out(), "{}", presentation == 'g' ? EnergyPlus::FileSystem::toGenericString(p) : EnergyPlus::FileSystem::toString(p));
+    }
+};
```
Comment (jmarrec) [inline src/EnergyPlus/FileSystem.hh:353]: new formatter for fs::path, instead of using the std::string one.

Two presentation types are accepted: `s` (default), and `g`.

`s` uses toString (and is similar to fs::path::string() but with narrowing) and `g` uses toGenericString (and is sililar to fs::path::generic_string())

File: src/EnergyPlus/FileSystem.cc [hunk 3]
```diff
@@ -98,9 +101,13 @@ namespace FileSystem {
         // filename. Do we really need that though?
         // path.make_preferred();
         fs::path result = path;
+#ifdef _WIN32
+        result.make_preferred();
+#else
```
Comment (jmarrec) [inline src/EnergyPlus/FileSystem.cc:106]: in makeNativePath, avoid going to a string() if not needed (and will potentially crash)

File: src/EnergyPlus/FileSystem.cc [hunk 4]
```diff
@@ -113,13 +120,21 @@ namespace FileSystem {
...
     {
         // Note: this is needed because "/a/b/c".parent_path() = "/a/b/c/"
+#ifdef _WIN32
+        std::wstring pathStr = path.native();
+        if (!pathStr.empty()) {
+            while ((pathStr.back() == DataStringGlobals::pathChar) || (pathStr.back() == DataStringGlobals::altpathChar)) {
+                pathStr.erase(pathStr.size() - 1);
+            }
+        }
+#else
```
Comment (jmarrec) [inline src/EnergyPlus/FileSystem.cc:130]: Same in getParentDirectoryPath...

File: src/EnergyPlus/FileSystem.cc [hunk 5]
```diff
@@ -338,100 +346,89 @@ namespace FileSystem {
...
-        }
-        if (has_error != 0 || bytes_read != size) {
-            throw FatalError(fmt::format("Error reading file: {}", path));
+        const std::uintmax_t file_size = fs::file_size(filePath);
+        std::ifstream file(filePath, mode);
+        if (!file.is_open()) {
+            throw FatalError(fmt::format("Could not open file: {}", filePath));
         }
+        std::string result(file_size, '\0');
+        file.read(result.data(), file_size);
```
Comment (jmarrec) [inline src/EnergyPlus/FileSystem.cc:365]: Change readFile and readJSON to use ifstream (that handles fs::path) + avoid using path.string()

File: src/EnergyPlus/FileSystem.cc [hunk 6]
```diff
@@ -338,100 +346,89 @@ namespace FileSystem {
...
+    }
+
+    fs::path appendSuffixToPath(fs::path const &outputFilePrefixFullPath, const std::string &suffix)
+    {
+        if constexpr (std::is_same_v<typename fs::path::value_type, wchar_t>) {
+            return {outputFilePrefixFullPath.wstring() + CLI::widen(suffix)};
+        } else {
+            return {outputFilePrefixFullPath.string() + suffix};
+        }
+    }
```
Comment (jmarrec) [inline src/EnergyPlus/FileSystem.cc:431]: New helpers definitions

File: src/EnergyPlus/SQLiteProcedures.cc [hunk 7]
```diff
@@ -2605,18 +2607,33 @@ SQLiteProcedures::SQLiteProcedures(std::shared_ptr<std::ostream> const &errorStr
...
         int rc = -1;
         bool ok = true;
 
+        if constexpr (debug) {
+            // std::cout << "errorStream=" << errorStream << ", dbName=" << dbName << std::endl;
+            // std::cout << "dbName.string()=" << dbName.string() << std::endl;
+            // std::cout << "dbName.generic_string()=" << dbName.generic_string() << std::endl;
+            std::wcout << "dbName.generic_wstring()=" << dbName.generic_wstring() << std::endl;
+            std::cout << "narrow(dbName.generic_wstring())=" << FileSystem::toGenericString(dbName) << std::endl;
+        }
```
Comment (jmarrec) [inline src/EnergyPlus/SQLiteProcedures.cc]: I need to clean that up...

File: src/EnergyPlus/SQLiteProcedures.cc [hunk 8]
```diff
@@ -2652,11 +2679,15 @@ SQLiteProcedures::SQLiteProcedures(std::shared_ptr<std::ostream> const &errorStr
...
-                        ok = false;
+                    // rc = remove(dbName_utf8.c_str());
+                    if (fs::is_regular_file(dbName)) {
+                        std::error_code ec;
+                        if (!fs::remove(dbName, ec)) {
+                            // File operation failed. SQLite connection is not in an error state.
+                            *m_errorStream << "SQLite3 message, can't remove old database. code=" << ec.value() << ", error: " << ec.message()
+                                           << std::endl;
+                            ok = false;
+                        }
```
Comment (jmarrec) [inline src/EnergyPlus/SQLiteProcedures.cc:2668]: instead of calling the C stdio.h [remove](https://en.cppreference.com/w/c/io/remove), use the fs::remove one

File: src/EnergyPlus/SQLiteProcedures.cc [hunk 9]
```diff
@@ -2665,7 +2696,7 @@ SQLiteProcedures::SQLiteProcedures(std::shared_ptr<std::ostream> const &errorStr
 
         if (ok) {
             // Now open the output db for the duration of the simulation
-            rc = sqlite3_open_v2(dbName.string().c_str(), &m_connection, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, nullptr);
+            rc = sqlite3_open_v2(dbName_utf8.c_str(), &m_connection, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, nullptr);
```
Comment (jmarrec) [inline src/EnergyPlus/SQLiteProcedures.cc:2677]: When opening the sqlite database, same thing: don't call string(), but our narrowing one.

File: src/EnergyPlus/ScheduleManager.cc [hunk 10]
```diff
@@ -490,7 +490,7 @@ namespace ScheduleManager {
                                 ShowSevereError(state, error);
                             }
                         }
-                        ShowContinueError(state, fmt::format("Error Occurred in {}", state.files.TempFullFilePath.filePath.string()));
+                        ShowContinueError(state, fmt::format("Error Occurred in {}", state.files.TempFullFilePath.filePath));
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:493]: use the new fmt::formatter<fs::path> everywhere, so we don't call fs::path::string()

File: src/EnergyPlus/SQLiteProcedures.cc (hunk 7 above)
Comment (jmarrec) [reply src/EnergyPlus/SQLiteProcedures.cc]: Done in 48eb2eb3e40c43cc4a30faf4fc9848fbd5520d2f

File: src/EnergyPlus/FileSystem.hh (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/FileSystem.hh:353]: This looks great to me.  I'm like 23% surprised you had to make your own formatter for this.  So 77% not surprised because of wide char nonsense.

**Review by Myoldmopar — APPROVED** [review]
Looks good, I'll pull develop and test things out.  :) :g :)

**Comment by Myoldmopar** [comment]
Everything is totally happy locally, but I had to apply Clang Format.  I'll push that up real quick and let CI confirm that, and then merge.

**Comment by Myoldmopar** [comment]
CI seems all happy with it, and the only thing I did was apply Clang Format, so I'm not waiting on Decent to finish.  Merging.  Thanks @jmarrec
