### PR TITLE
Fix PTAC node connection error logic

### LINKED ISSUE #9717: PTAC inlet node not found error gets skipped
Issue overview
--------------
User file with PTAC connected to a return plenum, failed with this cryptic error message:
```
   **  Fatal  ** DX Coil not found=
```
With some trial and error trying to fix the input file and watching the debugger, the problem was finally traced to the PTAC inlet node not found, because the node had not been entered as an induced air node to the plenum. 

This should have resulted in the following fatal error, but this didn't trip due to a logic flaw in `UnitarySystem::processInputSpec`.
```
   ** Severe  ** Input errors for ZoneHVAC:PackagedTerminalAirConditioner:PTAC
   **   ~~~   ** Incorrect or misspelled Air Inlet Node Name or Exhaust Node Name or Induced Node Name. = PLENUM_EXITNODE
   **   ~~~   ** Air Inlet Node PLENUM_EXITNODE name does not match any controlled zone exhaust node name. Check ZoneHVAC:EquipmentConnections object inputs.
   **   ~~~   ** or Induced Air Outlet Node Name specified in AirLoopHVAC:ReturnPlenum object.
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs
```
Working on a fix.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.2.0
 - direct email

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #9717 
 - Fix logic error for PTAC (and other unitary zone equipment) so that inlet node connection errors will be reported.

Defect fixed
----------------------
Defect file Chamber_PTAC_SingleSpeedCoil.idf
Develop
```
   **  Fatal  ** DX Coil not found=
```
This branch
```
   ** Severe  ** Input errors for ZoneHVAC:PackagedTerminalAirConditioner:PTAC
   **   ~~~   ** Incorrect or misspelled Air Inlet Node Name or Exhaust Node Name or Induced Node Name. = PLENUM_EXITNODE
   **   ~~~   ** Air Inlet Node PLENUM_EXITNODE name does not match any controlled zone exhaust node name. Check ZoneHVAC:EquipmentConnections object inputs.
   **   ~~~   ** or Induced Air Outlet Node Name specified in AirLoopHVAC:ReturnPlenum object.
   ** Severe  ** ZoneHVAC:PackagedTerminalAirConditioner = PTAC
   **   ~~~   ** Did not find proper connections for AirLoopHVAC or ZoneHVAC system.
   **   ~~~   ** specified Controlling Zone or Thermostat Location name = MAINZONE
   ** Severe  ** ZoneHVAC:PackagedTerminalAirConditioner = PTAC
   **   ~~~   ** Did not find air node (zone with thermostat).
   **   ~~~   ** Both a ZoneHVAC:EquipmentConnections object and a ZoneControl:Thermostat object must be specified for this zone.
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs
```
Chamber_PTAC_SingleSpeedCoil-InputFileFixed.idf runs without error in both develop and this branch.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] ~If any diffs are expected, author must demonstrate they are justified using plots and descriptions~
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] ~If structural output changes, add to output rules file and add OutputChange label~
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
This change seems like a good first step in separating out the use cases. I envision something like this:

    If (ZoneEquipment) {
    } else if (AirLoopNum > 0) { // includes OA system?
    } else if (ZoneOAUnitNum) { // ZoneHVAC:OutdoorAirUnit
    } else {                    // in case OA system units are needed here
    }

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -14979,7 +14979,7 @@ void CalcTwoSpeedDXCoilStandardRating(EnergyPlusData &state, int const DXCoilNum
     bool ErrorsFound(false);
     Real64 FanHeatCorrection;
     Real64 FanPowerCorrection;
-    Real64 FanPowerPerEvapAirFlowRate;
+    Real64 FanPowerPerEvapAirFlowRate = 0.0;
```
Comment (mjwitte) [inline src/EnergyPlus/DXCoils.cc:14982]: This is an unrelated unit test repair.

File: src/EnergyPlus/UnitarySystem.cc [hunk 2]
```diff
@@ -3825,7 +3825,7 @@ namespace UnitarySystems {
         // if part of ZoneHVAC:OutdoorAirUnit bypass most checks for connection to air loop or OASystem
         if (ZoneOAUnitNum > 0) OASysFound = true;
 
-        if (!AirLoopFound && !OASysFound) {
+        if (ZoneEquipment) {
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:3828]: Use `ZoneEquipment` parameter.

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -3903,9 +3903,34 @@ namespace UnitarySystems {
                     }
                 }
             }
-        }
-
-        if (!ZoneEquipmentFound) {
+            if (!ZoneExhaustNodeFound && !InducedNodeFound) {
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:3906]: Move these tests up into `ZoneEquipment` block.

File: src/EnergyPlus/UnitarySystem.cc [hunk 4]
```diff
@@ -4018,20 +4015,32 @@ namespace UnitarySystems {
             }
         }
 
+        if (AirLoopNumber == 0 && !ZoneEquipmentFound &&
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:4018]: Move this up from below so it executes before the possible `return` below in line 4039.

File: src/EnergyPlus/UnitarySystem.cc [hunk 5]
```diff
@@ -4018,20 +4015,32 @@ namespace UnitarySystems {
...
-                this->m_OKToPrintSizing = true;
-                this->m_ThisSysInputShouldBeGotten = false;
-            } else if (ZoneEquipmentFound) {
-                this->m_OKToPrintSizing = true;
-                this->m_ThisSysInputShouldBeGotten = false;
-            } else if (OASysFound) {
-                this->m_OKToPrintSizing = true;
-                this->m_ThisSysInputShouldBeGotten = false;
-            }
+        } else if (ZoneEquipmentFound || OASysFound ||
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:4040]: Collapse three if blocks that all did the same thing into one big if.

File: src/EnergyPlus/UnitarySystem.cc [hunk 6]
```diff
@@ -4048,23 +4057,7 @@ namespace UnitarySystems {
...
-                ShowContinueError(state, "Did not find air node (zone with thermostat).");
-                // ShowContinueError(state, "specified " + cAlphaFields(iControlZoneAlphaNum) + " = " + Alphas(iControlZoneAlphaNum));
-                ShowContinueError(state,
-                                  "Both a ZoneHVAC:EquipmentConnections object and a ZoneControl:Thermostat object must be specified for this zone.");
-            }
-            errorsFound = true;
-        }
-
-        if (!ZoneEquipmentFound)
+        if (!ZoneEquipment)
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:4060]: If the system is zone equipment, then don't add a compset, even if there were errors that might leave `ZoneEquipmentFound=false`.

File: tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc [hunk 7]
```diff
@@ -358,7 +358,7 @@ TEST_F(EnergyPlusFixture, AirTerminalSingleDuctMixer_GetInputPTAC_InletSide)
     UnitarySystems::UnitarySys thisSys;
     UnitarySystems::UnitarySys::factory(*state, DataHVACGlobals::UnitarySys_AnyCoilType, "SPACE1-1 PTAC", true, 0);
     state->dataZoneEquip->ZoneEquipInputsFilled = true;
-    thisSys.getUnitarySystemInput(*state, "SPACE1-1 PTAC", false, 0);
+    thisSys.getUnitarySystemInput(*state, "SPACE1-1 PTAC", true, 0);
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc:361]: Several unit tests were not correctly setting the `ZoneEquipment` parameter.

File: tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc [hunk 8]
```diff
@@ -4067,4 +4068,292 @@ TEST_F(EnergyPlusFixture, PTACDrawAirfromReturnNodeAndPlenum_Test)
     EXPECT_NEAR(state->dataLoopNodes->Node(zone5InletNode1).MassFlowRate, state->dataLoopNodes->Node(zone5ReturnNode).MassFlowRate, 0.001);
 }
 
+TEST_F(EnergyPlusFixture, PTAC_ZoneEquipment_NodeInputTest)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc:4071]: New unit test.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 9]
```diff
@@ -11655,7 +11656,7 @@ TEST_F(EnergyPlusFixture, UnitarySystemModel_MultiSpeedCoils_SingleMode)
     state->dataZoneEquip->ZoneEquipList(1).EquipIndex(1) = 1; // initialize equipment index for ZoneHVAC
 
     std::string compName = "UNITARY SYSTEM MODEL";
-    bool zoneEquipment = true;
+    bool zoneEquipment = false;
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:11659]: Some cleanup to this existing unit test.

**Review by mjwitte — COMMENTED** [review]
Code walkthru

File: src/EnergyPlus/UnitarySystem.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:3828]: I wonder if there is an example file with UnitarySystem inside a ZoneHVAC:OutdoorAirUnit such that would test that this logic includes that configuration? Otherwise all these changes look correct to me.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:3828]: > I wonder if there is an example file with UnitarySystem inside a ZoneHVAC:OutdoorAirUnit such that would test that this logic includes that configuration? Otherwise all these changes look correct to me.

Both OutdoorAirUnit.idf and OutdoorAirUnitwithAirloopHVAC.idf have a CoilSystem:Cooling:DX in the ZoneHVAC:OutdoorAirUnit:EquipmentList, so I think this case is covered. I followed progress in the debugger using OutdoorAirUnit.idf, and it executed or skipped in the right places.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:3828]: OK, enough speculating whether these changes cover all cases. This branch is clean so is probably ready for testing the defect file and moving on.

File: src/EnergyPlus/UnitarySystem.cc (hunk 6 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:4060]: I didn't realize this nuance, that UnitarySystem zone equipment doesn't need to TestCompSet. I see that call in baseboards, fans, HXs, etc., but no zone parent objects. So what are the rules here? I thought it was a parent child relationship (i.e., a parent node must correspond to a child node) but obviously there is something else. There are no diffs here so this must be correct.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:4060]: The `compset` chain does not extend up to the ZoneHVAC:EquipmentList, so the components that go on that list don't need to register themselves. I suppose it could, but there is other code to warn about zone equipment that's not on a list. The node connection checking is a separate pass that uses the node connections list (set up by `GetOnlySingleNode` and the like. As for baseboards, water and steam baseboards need to chime in because they live on a plant branch. I'm fairly certain that electric baseboards do not call compsets.

**Comment by nrel-bot-2b** [comment]
@mjwitte @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/DXCoils.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DXCoils.cc:14982]: Interesting.  OK well no problem, obviously.

File: src/EnergyPlus/UnitarySystem.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/UnitarySystem.cc:3828]: :+1: thanks for your commentary here @rraustad

File: src/EnergyPlus/UnitarySystem.cc (hunk 5 above)
Comment (Myoldmopar) [reply src/EnergyPlus/UnitarySystem.cc:4040]: Interesting.  In this case it doesn't necessary make it easier to read or understand, but it's totally fine.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Confirmed all the described behavior.  The fixed input file runs in both branches.  The defect file fails in both branches, but with different reasons.  The branch runs locally with develop pulled in, passing unit tests and producing the more expected error text.  This seems good to go in.  Thanks @mjwitte
