### PR TITLE
Fix #6353 - Evap. condenser sizing output for Coil:Cooling:DX:SingleSpeed and TwoSpeed wrong labels

### LINKED ISSUE #6353: Evap. condenser sizing output for Coil:Cooling:DX:SingleSpeed and TwoSpeed wrong labels
Issue overview
--------------
The evaporative condenser outputs for Coil:Cooling:DX:SingleSpeed and Coil:Cooling:DX:TwoSpeed in the Initialization Summary -> Component Sizing Information have the wrong labels.

For the single speed coil below, per the I/O ref:
```
Cap = 127,473 W
Air Flow = 127,473 W * 0.000144 m3/s/W (autosized) = 18 m3/s
Pump Pwr = 127,473W * 0.004266 W/W (autosized) = 543 W
```

However, in the report:
```
543 is found labeled "Design Size Evaporative Condenser Air Flow Rate [W]"
14.5 is found labeled "Design Size Evaporative Condenser Effectiveness [m3/s]"
(not sure why the value is different than the autosized value, but probably a separate issue)
```

coilcoolingdxsinglespeedoutputerror

A similar pattern exists in the two speed coil:
coilcoolingdxtwospeedoutputerror

### Details
 - Platform (Windows 7)
 - Version of EnergyPlus (8.8)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #6353 - Evap. condenser sizing output for Coil:Cooling:DX:SingleSpeed and TwoSpeed wrong labels

Added two unit tests: one for `Coil:Cooling:DX:SingleSpeed` and one for `Coil:Cooling:DX:TwoSpeed`

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -7082,12 +7082,12 @@ namespace DXCoils {
                         SizingString = DXCoilNumericFields(DXCoilNum).PerfMode(Mode).FieldNames(FieldNum) + " [m3/s]";
                     } else {
                         CompName = DXCoil(DXCoilNum).Name;
-                        FieldNum = 11;
+                        FieldNum = 12; // (High Speed) Evaporative Condenser Air Flow Rate
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:7085]: Check, field 12 for single speed and two speed dx is high speed evap cond air flow

File: src/EnergyPlus/DXCoils.cc [hunk 2]
```diff
@@ -7140,7 +7140,7 @@ namespace DXCoils {
                 if (DXCoil(DXCoilNum).CondenserType(1) == EvapCooled && DXCoil(DXCoilNum).EvapCondAirFlow2 != 0.0 &&
                     DXCoil(DXCoilNum).DXCoilType_Num == CoilDX_CoolingTwoSpeed) {
                     CompName = DXCoil(DXCoilNum).Name;
-                    FieldNum = 14;
+                    FieldNum = 15; // Low Speed Evaporative Condenser Air Flow Rate
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:7143]: Field 15 is low speed evap cond air flow for 2 speed dx

File: src/EnergyPlus/DXCoils.cc [hunk 3]
```diff
@@ -7161,11 +7161,11 @@ namespace DXCoils {
 
                     if (DXCoil(DXCoilNum).DXCoilType_Num == CoilDX_CoolingTwoStageWHumControl) {
                         CompName = DXCoil(DXCoilNum).Name + ":" + DXCoil(DXCoilNum).CoilPerformanceName(Mode);
-                        FieldNum = 12;
+                        FieldNum = 12; // Evaporative Condenser Pump Rated Power Consumption
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:7164]: Field 12 evap cond pump power for 2-stage with hum control

File: src/EnergyPlus/DXCoils.cc [hunk 4]
```diff
@@ -7184,7 +7184,7 @@ namespace DXCoils {
                 if (DXCoil(DXCoilNum).CondenserType(1) == EvapCooled && DXCoil(DXCoilNum).EvapCondPumpElecNomPower2 != 0.0 &&
                     DXCoil(DXCoilNum).DXCoilType_Num == CoilDX_CoolingTwoSpeed) {
                     CompName = DXCoil(DXCoilNum).Name;
-                    FieldNum = 15;
+                    FieldNum = 16; // Low Speed Evaporative Condenser Pump Rated Power Consumption
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:7187]: Field 16 2-speed dx low speed evap cond pump power

File: src/EnergyPlus/DXCoils.cc [hunk 5]
```diff
@@ -7161,11 +7161,11 @@ namespace DXCoils {
 
                     if (DXCoil(DXCoilNum).DXCoilType_Num == CoilDX_CoolingTwoStageWHumControl) {
                         CompName = DXCoil(DXCoilNum).Name + ":" + DXCoil(DXCoilNum).CoilPerformanceName(Mode);
-                        FieldNum = 12;
+                        FieldNum = 12; // Evaporative Condenser Pump Rated Power Consumption
                         SizingString = DXCoilNumericFields(DXCoilNum).PerfMode(Mode).FieldNames(FieldNum) + " [W]";
                     } else {
                         CompName = DXCoil(DXCoilNum).Name;
-                        FieldNum = 12;
+                        FieldNum = 13; // (High Speed) Evaporative Condenser Pump Rated Power Consumption
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:7168]: Field 13 2-speed dx high speed evap cond pump power

**Comment by rraustad** [comment]
Looks all good to me. No diff's? There are no autosized example files for these fields?

**Comment by rraustad** [comment]
5ZoneAutoDXVAV.idf doesn't even report these fields so I guess no diff's is expected.

```
  Coil:Cooling:DX:TwoSpeed,
    Main Cooling Coil 1,     !- Name
    EvaporativelyCooled,     !- Condenser Type
    ,                        !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}
    ,                        !- High Speed Evaporative Condenser Effectiveness {dimensionless}
    ,                        !- High Speed Evaporative Condenser Air Flow Rate {m3/s}
    ,                        !- High Speed Evaporative Condenser Pump Rated Power Consumption {W}
    ,                        !- Low Speed Evaporative Condenser Effectiveness {dimensionless}
    ,                        !- Low Speed Evaporative Condenser Air Flow Rate {m3/s}
    ,                        !- Low Speed Evaporative Condenser Pump Rated Power Consumption {W}

```

```
 Component Sizing Information, Coil:Cooling:DX:TwoSpeed, MAIN COOLING COIL 1, Design Size High Speed Rated Air Flow Rate [m3/s], 2.38198
 Component Sizing Information, Coil:Cooling:DX:TwoSpeed, MAIN COOLING COIL 1, Design Size High Speed Gross Rated Total Cooling Capacity [W], 39430.25966
 Component Sizing Information, Coil:Cooling:DX:TwoSpeed, MAIN COOLING COIL 1, User-Specified High Speed Rated Sensible Heat Ratio, 0.80000
 Component Sizing Information, Coil:Cooling:DX:TwoSpeed, MAIN COOLING COIL 1, Design Size Low Speed Rated Air Flow Rate [m3/s], 0.79391
 Component Sizing Information, Coil:Cooling:DX:TwoSpeed, MAIN COOLING COIL 1, Design Size Low Speed Gross Rated Total Cooling Capacity [W], 13142.10554
 Component Sizing Information, Coil:Cooling:DX:TwoSpeed, MAIN COOLING COIL 1, User-Specified Low Speed Gross Rated Sensible Heat Ratio, 0.80000
```

**Comment by rraustad** [comment]
Had to add autosize for the blank fields. Not sure what the values were when left blank but that's out of scope here. 

Note the effectiveness values are not autosizable.
This is V9.1:

image

and this branch:

image

**Review by rraustad — APPROVED** [review]
Reviewed code and unit test. Ran example file in V9.1 and this branch to compare.
