### PR TITLE
Fix issue 9241 leap day monthly reporting

### LINKED ISSUE #9241: Leap day included w/ March when reporting frequency is monthly
Issue overview
--------------
See attached IDF and results. When the simulation uses a leap year and you request an `Output:Variable` with frequency of "monthly", the February results are still through 2/28 and the leap day ends up in the March results:

image

I've confirmed that a leap day is being simulated by switching to a frequency of "hourly":

image

Files to reproduce:
[test.zip](https://github.com/NREL/EnergyPlus/files/7891904/test.zip)

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #9241 
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WeatherManager.hh [hunk 1]
```diff
@@ -1284,6 +1285,7 @@ struct WeatherManagerData : BaseGlobalStruct
           DaylightSavingIsActive(false), WFAllowsLeapYears(false), curSimDayForEndOfRunPeriod(0), Envrn(0), NumOfEnvrn(0), NumEPWTypExtSets(0),
           NumWPSkyTemperatures(0), RptIsRain(0), RptIsSnow(0), RptDayType(0), HrAngle(0.0), SolarAltitudeAngle(0.0), SolarAzimuthAngle(0.0),
           HorizIRSky(0.0), TimeStepFraction(0.0), NumSPSiteScheduleNamePtrs(0), EndDayOfMonth(12, {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}),
+          EndDayOfMonthWithLeapDay(12, {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}),
```
Comment (rraustad) [inline src/EnergyPlus/WeatherManager.hh]: Would it be smarter to make these constexpr and not bait-n-switch the number of days in Feb from "28" to "29" in EndDayOfMonthWithLeapDay? Since this new array should already have the correct data? If you are adjusting the number of days in the month based on leap year, why not just do that to the existing array EndDayOfMonth and not add the new array (which would then not be const)? Just talking out loud here.

Comment (JasonGlazer) [reply src/EnergyPlus/WeatherManager.hh]: @rraustad no problem, I thought about a few different approaches including the ones you mentioned. I ended up going this way for a couple of reasons. First, there are a lot of completely untested functions that use EndDayOfMonth already, and they all seem to assume that even during a leap year, the return value is adjusted by 1, often by using another variable that acts as a flag called LeapYearAdd (containing either a 0 or 1). If you look at the code it is repetitive and I was going to replace it all but it would have meant adding lots of new unit tests so that I was sure I wasn't breaking anything. So that ruled out just modifying EndDayOfMonth for leap years since it might have ended up double counting leap days if I wasn't careful. Second, I assumed that if you just selected a year in RunPeriod that was a leap year it contained February 29 but it is more complicated than that and depends on the weather file containing Feb 29 and if its headers specify the year, if the user specifies in RunPeriod that "Treat Weather as Actual" is Yes, and if the "Day Of Week for Start Day" is correct for a year that is a leap year. Some special cases occur when only some of these are done. I don't know why it is so complicated, but that is how the code evolved. This just led me to the point of how do I solve this bug clearly. Honestly, all the leap year could use some rethinking and refactoring but that seemed a bigger task than just fixing the bug.

Comment (jasondegraw) [reply src/EnergyPlus/WeatherManager.hh]: I know why it is so complicated and I agree that it all needs to rethought and refactored, approximately one billion percent. Based on my experience working on the RunPeriod object a few years ago, the primary problem is that way the simulation tracks time (including end of day flags and the like) is shall we say "decentralized". As far as I can tell, there's no way to improve smaller portions of the code without touching all sorts of stuff that is only tangentially related. Leap days are pretty much special cases all the way down because the code had been pretty forgiving on whether or not the weather data is required (and it doesn't help that there are AMY files being sold for leap years without leap days 😱). I think I'll stop here before I start ranting about the Gregorian calendar and dominical letters.

**Comment by Myoldmopar** [comment]
This looks good to me.  I can appreciate you trying to find a minimal solution, and your new unit tests offer some confidence in what you've changed.  I agree with you and @jasondegraw both that this could use some clearing up, but that's for another day.  I'll pull develop in but expect this to merge if everything is clean.

**Comment by Myoldmopar** [comment]
Yep everything is all good enough here, it would be wonderful to dedicate a medium effort to cleaning up the leap day stuff, if for no other reason than it would put me in good graces with Leap Day Williams, shown here:

image
