### PR TITLE
#9000 - Average values for integer output variables fail debug assert and are rounded to 1 place

### LINKED ISSUE #9000: Average values for integer output variables fail debug assert and are rounded to 2 places
Issue overview
--------------
Defect file requests an integer output variable, Site Rain Status, for timestep, hourly, and monthly. When the averaged value is reported in a debug build, it trips on this [assert](https://github.com/NREL/EnergyPlus/blob/75c5e2b8a1690ae49cc6667c36be86ff0d216a6a/src/EnergyPlus/General.cc#L334) in `strip_trailing_zeros` which is called from [here in WriteReportIntegerData](https://github.com/NREL/EnergyPlus/blob/75c5e2b8a1690ae49cc6667c36be86ff0d216a6a/src/EnergyPlus/OutputProcessor.cc#L4846-L4854). Looks like this needs to use a different format for the actual integer timestep values vs the real averaged value.

When the defect file is run with a release build, the April average is reported as 0.03 while the average of the timestep values is 0.033529. Seems like averages of integers should report more than two decimal places?

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 9.6.0 (almost I/O Freeze)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: 
[1ZoneUncontrolled-RainStatus-ChicagoOHareApril.idf.txt](https://github.com/NREL/EnergyPlus/files/7035198/1ZoneUncontrolled-RainStatus-ChicagoOHareApril.idf.txt)

 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9000 
 - The debug assert is because `trim` was used instead of `strip`
 - a number between -1 and 1 would be formatted in WriteReportIntegerData to "{:N}" which sets precision to **1** (and prepend "0." to it)

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
This is definitely an improvement, and although we can have a broader discussion about the output significance, this one issue is not widespread in any sense of the word, and we should just take this cleanup as soon as it's ready.

File: src/EnergyPlus/IOFiles.hh [hunk 1]
```diff
@@ -380,6 +381,12 @@ public:
                 // The Fortran 'G' format insists on a leading 0, even though
                 // that actually means losing data
                 specs_.type = 'Z';
+
+                // We'll be formating a number between -1 and 1 as scientific notation, so we want some amount of decimals to be meaningful
+                if (specs_.precision == -1) {
+                    specs_.precision = 4;
+                }
```
Comment (jmarrec) [inline src/EnergyPlus/IOFiles.hh]: In the N case, default to precision = 4.

File: src/EnergyPlus/IOFiles.hh [hunk 2]
```diff
@@ -275,8 +275,9 @@ public:
             if (specs_.precision > 1) {
                 // reduce the precision to get rounding behavior
                 --specs_.precision;
-            } else {
+            } else if (specs_.precision != -1) {
                 // We need AT LEAST one in precision so we capture a '.' below
+                // If specs_.precision is -1, we don't need to do anything, keep the fmt defaults which are sane
```
Comment (jmarrec) [inline src/EnergyPlus/IOFiles.hh]: In the Z case, if the precision wasn't set already, then let fmt default it.

File: src/EnergyPlus/IOFiles.hh (hunk 1 above)
Comment (jmarrec) [reply src/EnergyPlus/IOFiles.hh]: I suppose if we were fine with having around 6 precision, we could delete that block and let fmt default it in the Z case which it forwards to.

File: src/EnergyPlus/OutputProcessor.cc [hunk 3]
```diff
@@ -4644,7 +4644,7 @@ namespace OutputProcessor {
             NumberOut = "0.0";
         } else {
             NumberOut = format("{:N}", repVal);
-            strip_trailing_zeros(trim(NumberOut));
+            strip_trailing_zeros(strip(NumberOut));
```
Comment (jmarrec) [inline src/EnergyPlus/OutputProcessor.cc:4647]: Actual crash. v9.3.0 uses strip. Then during the move away from gio::write, it was first removed then added back as trim instead of strip

cf https://github.com/NREL/EnergyPlus/blob/baff08990c9c4d12d8bbde0378073018a3ea6acf/src/EnergyPlus/OutputProcessor.cc#L5290

https://github.com/NREL/EnergyPlus/commit/5dee4a244ec0e1af3c46b4e2d1efc3ee37a8eed4#diff-bd9d5281a7fe99bacbcd3d7112772f7804d8e091f10a56a0954a7639c24384fcR4946

File: tst/EnergyPlus/unit/OutputFiles.unit.cc [hunk 4]
```diff
@@ -174,6 +174,11 @@ TEST_F(EnergyPlusFixture, OutputFiles_Expected_Formatting_Tests)
     //    EXPECT_EQ(format("{:N}", 999.9), "           999.9    ");
     EXPECT_EQ(format("{:N}", 61677162.0987027), "61677162.0987027    ");
 
+    // Tested with E+ 9.3.0
+    EXPECT_EQ(format("{:N}", 0.03576388888888889), "          0.3576E-01");
+    EXPECT_EQ(format("{:.3N}", 0.03576388888888889), "0.358E-01");
+    EXPECT_EQ(format("{:.4N}", 0.03576388888888889), "0.3576E-01");
+
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/OutputFiles.unit.cc]: New format test

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 5]
```diff
@@ -1083,6 +1083,9 @@ namespace OutputProcessor {
         WriteReportIntegerData(*state, 1, "1", 0, StoreType::Summed, 1, ReportingFrequency::TimeStep, 0, 0, 0, 0);
         EXPECT_TRUE(compare_eso_stream(delimited_string({"1,0.0"}, "\n")));
 
+        WriteReportIntegerData(*state, 1, "1", 25.75, StoreType::Averaged, 720, ReportingFrequency::Monthly, 0, 4010115, 1, 4011560);
+        EXPECT_TRUE(compare_eso_stream(delimited_string({"1,0.3576E-01,0, 1, 1,15,1, 1,15,60"}, "\n")));
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc]: This triggered the assert throw in debug mode before.

File: src/EnergyPlus/IOFiles.hh (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/IOFiles.hh]: Sounds reasonable, if we want control then we just need to be explicit about the precision we want.

File: src/EnergyPlus/IOFiles.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/IOFiles.hh]: Yeah I wouldn't care either way, but I think it's reasonable, and we don't need to belabor this corner case.

File: src/EnergyPlus/OutputProcessor.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/OutputProcessor.cc:4647]: :+1:

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
I'll go ahead and let the integration debug build finish but assuming it is fine then I'll merge this.  Thanks for the fix @jmarrec and the unit test and walkthrough.

File: tst/EnergyPlus/unit/OutputFiles.unit.cc (hunk 4 above)
Comment (mbadams5) [reply tst/EnergyPlus/unit/OutputFiles.unit.cc]: It says in the comments "Tested with E+ 9.3.0", does that mean `NumberOut` below will be "0.3576E-01"?

```c++
ObjexxFCL::gio::Fmt fmtLD("*");
std::string NumberOut;
ObjexxFCL::gio::write(NumberOut, fmtLD) << repVal;
strip_trailing_zeros(strip(NumberOut));
```

File: src/EnergyPlus/IOFiles.hh (hunk 1 above)
Comment (mbadams5) [reply src/EnergyPlus/IOFiles.hh]: Is this the default precision for the Fortran output? This whole code is to emulate Fortran output styles within the fmt library.

File: src/EnergyPlus/IOFiles.hh (hunk 2 above)
Comment (mbadams5) [reply src/EnergyPlus/IOFiles.hh]: Is this the default precision for the Fortran output? This whole code is to emulate Fortran output styles within the fmt library.

**Review by mbadams5 — COMMENTED** [review]
My overall comment is to make sure these changes are inline with Fortran output style. Since I said in my individual comments that this code is solely to emulate Fortran output within the fmt library. Turner originally wrote this code when he converted the GIO output to FMT.

If `NumberOut` should have a different precision or output style than Fortran, it might be better to just change it to a true `fmt::format("Foo", repVal);` instead of using this shim.

**Comment by Myoldmopar** [comment]
> My overall comment is to make sure these changes are inline with Fortran output style.

I hope that's no longer the guiding principle.  I would just say let's make sensible output, not try too hard to match Fortran.

**Comment by mbadams5** [comment]
I don't think we should write new code using the Fortran syntax either. Which is why I suggested rewriting `NumberOut = format("{:N}", repVal);` to use true FMT syntax `NumberOut = fmt::format("{:something.something}", repVal);` instead of changing the Fortran shim since we have good coverage of output changes but obviously not complete given the issue this PR is solving.

**Comment by mjwitte** [comment]
Looks like @Myoldmopar approved this and was ready to merge, but then @mbadams5 made some further comments. 
Is this ready or waiting on further changes?

**Comment by Myoldmopar** [comment]
OK, so in an effort to get this merged in, I reverted out the two latter commits which modified the output reporting.  This PR now just includes the unit test demonstrating the issue (that initially fails) plus the tiny code change to get the unit test passing.  We can have discussions about how to handle the other changes later, but I'd like to get this defect fixed at least.

I then pulled develop in, ran tests, including regressions, and it was entirely clean.  I'm inclined to wait for CI to verify that for me since I ran just one release build on just Linux.  I'll move on to other PRs while CI catches up here and go from there.

**Comment by Myoldmopar** [comment]
Looking good so far, I'll let the unit test debug build run, and I'll let the debug integration tests at least get started before merging.

**Comment by Myoldmopar** [comment]
No issues here, merging this in.  Won't cause any diffs for the rainfall PR which is staged for next merge.
