### PR TITLE
Fix calculation of window frame heat gain

### LINKED ISSUE #5095: Window frame heat gain not calculated correctly
There are two issues with the way frame heat gain is calculated:
1. If the interior projection depth is zero, then the interior convection is set to zero. `HInConv` is set to zero [here](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6073) and it is only set to a non-zero value ([here](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6084)) if the [frame projection depth is not zero](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6082). Note, [dividers](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6142) seem to handle this correctly.
2. The calculated frame heat gain only represents the convection. See the calculation [here](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6100). My understanding is that the `FrameHeatGain` variable is only used for surface, window, and frame output reporting purposes. But the [documentation](http://bigladdersoftware.com/epx/docs/8-3/input-output-reference/group-thermal-zone-description-geometry.html#surface-window-heat-gain-energy-j) is pretty explicit about the variables including the conduction through the frame, and not just the convection. Once again, [dividers](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6159) seem to handle this correctly.

The solution is pretty straight forward, in that we need to replicate the divider calculations in the frame section.

### PR DESCRIPTION
**Pull request by nealkruis**
Fixes #5095.

### CODE REVIEW

**Comment by nealkruis** [comment]
@mjwitte Let me know if you'd rather have someone else review and accept.

@vidanovic feel free to comment here. This is the bug I was mentioning via email. Feel free to continue the discussion here.

**Comment by mjwitte** [comment]
@nealkruis I will review - next week.  I see the logic, just hard to believe this was wrong for so long.  Perhaps there was a reason.  @hongtz68 ?

**Comment by mjwitte** [comment]
@nealkruis This will need a unit test before it can go in.

**Comment by nealkruis** [comment]
@mjwitte @Myoldmopar I'm working on putting together a unit test for this. Are there other examples of good unit tests for envelope routines? I'm working through all of the initialization steps needed to get to the point where CalcWinFrameAndDividerTemps can be called. I'll keep going, but please let me know if you know of anything that might help.

**Comment by Myoldmopar** [comment]
I'd say there are three possible patterns to fall into:
1. If possible, extract out the logic/code that you modified/added in order to call that function by itself without setting up anything external.  
2. Go ahead and call that whole function as-is, but you will likely have to set up some global arrays in E+ for all the `using` that goes on.  And if you allocate them manually like this, you'll have to clean them up.
3. Use the new logic added by @mbadams5 to enter idf snippets, and let E+ do all the get-input/etc. itself.  You may end up having to add clear_state() functions and calls for namespaces that do not yet have them.  This clear_state avoids the manual clean up mentioned in step 2.  

I'll try to document which unit tests are doing each approach, but right now that won't be high on the list.  If you can mention which approach you are leaning toward, I can probably find an example.

**Comment by nealkruis** [comment]
Ok. I think I've got it figured out. I was hoping there was an example that had all of the initializing functions and global variables specified for envelope routines. I'm happy to break the trail.

**Comment by Myoldmopar** [comment]
Good luck!

**Comment by nealkruis** [comment]
@mjwitte @Myoldmopar I added a unit test. Since there is a lot of setup involved it would be good to have someone look over it. I'm sure there are things we can do to make this setup more standard, perhaps even creating an EnvelopFixture.

Also, there is so much global setup here that calling this a "unit" test might be a bit of a stretch. Though, I can confirm that the test does cover the code where the fix was applied.

**Comment by Myoldmopar** [comment]
@nealkruis I'll look at it now.  I will say that based on your statement above, that will satisfy the requirement for covering the code changes and getting this merged in.

**Comment by mjwitte** [comment]
@Myoldmopar Note that I haven't had a chance to review/test the validity of the code changes yet - feel free If you want.  Otherwise this is on my list for this afternoon.

File: src/EnergyPlus/WindowManager.cc [hunk 1]
```diff
@@ -6097,7 +6097,7 @@ namespace WindowManager {
 			//  ( SurfaceWindow(SurfNum)%FrameEmis*(sigma*(SurfaceWindow(SurfNum)%FrameTempSurfIn+TKelvin)**4 - rmir) + &
 			//    hcin*(SurfaceWindow(SurfNum)%FrameTempSurfIn+TKelvin - tin) )
 
-			FrameHeatGain = SurfaceWindow( SurfNum ).FrameArea * ( 1.0 + SurfaceWindow( SurfNum ).ProjCorrFrIn ) * ( hcin * ( SurfaceWindow( SurfNum ).FrameTempSurfIn + TKelvin - tin ) );
+			FrameHeatGain = SurfaceWindow( SurfNum ).FrameArea * FrameCon * ( SurfaceWindow( SurfNum ).FrameTempSurfOut - SurfaceWindow( SurfNum ).FrameTempSurfIn );
```
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc]: @nealkruis Looking at the commented code, above, this used to include convection and radiation.  It was changed to convection only as part of CR 6872 Issue #1660 Commit is [here](https://github.com/NREL/EnergyPlusArchive/commit/f36e3ee157091b63ac8fa085ef1be4fc710f13a9)The notes in the CR description indicate there is more to the frame heat balance than just conduction. So, the convection connection to the zone air sounds correct.  Do dividers also exchange radiantly with the glass?  If so, maybe the dividers are wrong.  Just trying to follow all of this.  Do you have a test file that shows that the current result is wrong?

File: src/EnergyPlus/WindowManager.cc [hunk 2]
```diff
@@ -6070,7 +6070,7 @@ namespace WindowManager {
 			TInRadFr = TInRad * root_4( ( 1.0 + 0.5 * ProjCorrFrIn ) / ( 1.0 + ProjCorrFrIn ) );
 			FrameCon = SurfaceWindow( SurfNum ).FrameConductance;
 			HInRad = 0.5 * SurfaceWindow( SurfNum ).FrameEmis * sigma * pow_3( TInRadFr + SurfaceWindow( SurfNum ).FrameTempSurfIn + TKelvin );
-			HInConvFr = 0.0;
+			HInConvFr = HInConv;
```
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc:6230]: @nealkruis This one does definitely look wrong.  Calculations for the frame and divider projections were added [here](https://github.com/NREL/EnergyPlusArchive/commit/44454492611150b6406fbcb84ea19b9be432545c) back in 2000.  If you search down for HInConvFr, you'll see the old equations that used HInConv are replaced with ones that use HInConvFr with no intilalization of HInConvFr if there is not projection.

File: src/EnergyPlus/WindowManager.cc (hunk 1 above)
Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: @mjwitte as far as I can tell `FrameHeatGain` is used solely for reporting purposes. The [documentation](http://bigladdersoftware.com/epx/docs/8-3/input-output-reference/group-thermal-zone-description-geometry.html#surface-window-heat-gain-energy-j) is pretty explicit that the output variables represent the total heat transfer (= conduction) through the frame, and not just the convection to the zone.

I came across this though my ASHRAE 1588RP work when I was trying to use the `WindowHeatGain` (which includes both glazing and frame) to back out a U-factor under NFRC testing conditions. The sensitivity of U-factor to frame properties was counter-intuitive and contrary to published values in ASHRAE Fundamentals Chapter 15.

**Comment by mjwitte** [comment]
Added defect files from CR6872 [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5095)

File: src/EnergyPlus/WindowManager.cc (hunk 1 above)
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc]: But convection to the zone air is the final path for the heat flow between the frame and the zone (if it's correct that the frame does not interact radiantly with the zone surfaces).  So, the frame conduction and the frame radiant exchange with the glass would be included in the convection to the zone air.  The true test is comparing zone loads with and without frames to see if the change in load is equal to the reported frame heat gain.  The CR6872 defect files should show that.

Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: @mjwitte I see your point. I guess the question is, should the reported values represent the heat transfer through the window, or the heat transfer to the zone air?

Perhaps the best solution is to have two separate report variables: one for convection to the zone (that can be used to compare the sum of the loads as per the original CR), and another for heat transfer through the window (for calculating the U-factor).

I'm ok dropping this change for now, but then the divider heat gain should probably be changed for consistency. The documentation should probably also be adjusted to reflect that the frame heat gain is convection, and not conduction.

What do you think is best?

**Comment by Myoldmopar** [comment]
This hasn't been touched in 10 days and it appears there were still significant questions.  I'm reassigning to the 8.4.0+BugFix milestone.

File: src/EnergyPlus/WindowManager.cc (hunk 1 above)
Comment (EnergyArchmage) [inline src/EnergyPlus/WindowManager.cc]: Probably what is going on here is the convection to zone air is a (tricky) way of generating the report that rolls up all the other terms.

File: src/EnergyPlus/WindowManager.cc (hunk 2 above)
Comment (EnergyArchmage) [inline src/EnergyPlus/WindowManager.cc:6230]: I have always thought that the original design intent in EnergyPlus for window frames was never consistent with the usual approach taken when determining assembly U-factors.  (A complete rework has long been needed in this area to properly handle frames, edge-of-glass, dividers and assembly U-factor had been on the enhancment list for a long long time.)   

I believe the idea that is showing up here was that surrounding base surface would the part of the "frame" and what is calculated in E+ as "frame" is just the projecting perpendicular surface.  So if no projection, no frame and no extra convection.

Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc:6230]: @EnergyArchmage Doesn't EnergyPlus remove the frame area from the base surface area even if there is no frame projection? It seems like a bad assumption that no projection implies no frame. Maybe I'm not understanding you correctly.

File: src/EnergyPlus/WindowManager.cc (hunk 1 above)
Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: @EnergyArchmage The defect files from the CR that @mjwitte mentions do indicate that this came about because of the individual load terms not summing to the total. The problem is that this only represents the convection from the frame and not the total heat transfer through the frame (which I was hoping to use for a project, and is implied by some of the report variables that use FrameHeatGain).

File: src/EnergyPlus/WindowManager.cc (hunk 2 above)
Comment (EnergyArchmage) [inline src/EnergyPlus/WindowManager.cc:6230]: I agree it is/was a poor original design intent.  I worry that it isn't so easy to fix.

Comment (vidanovic) [inline src/EnergyPlus/WindowManager.cc:6230]: This is something I was look at two years ago. I did some THERM analysis and found out problems with frame projections. We have come up with equations to deal with frame projections. This is on our radar, however, still low priority.

File: src/EnergyPlus/WindowManager.cc (hunk 1 above)
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc]: @nealkruis What other heat transfer through the frame are you expecting to see?  I don't believe that the EnergyPlus model calculates conduction from the glass edge into the frame.  The convection to the zone is in series with the conduction through the frame to the outdoors, so I think that's all there is with the current model.

Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: I am expecting to see the radiation from the frame to the zone. The IR from the parent zone is used to calculate the surface temperatures of the frame (though I don't think the IR from the frame is used in the overall IR exchange between other zone surfaces--this is a separate problem, but I imagine it has a relatively small impact).

Because the IR from the parent zone is used to calculate the surface temperatures, the convection to the zone is not equal to the conduction through the frame.

File: src/EnergyPlus/WindowManager.cc (hunk 2 above)
Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc:6230]: This doesn't seem to be a problem with frame projections. It is only a problem when there is no frame projection (i.e., the frame is flush with the window and the wall). 

@EnergyArchmage what are your concerns with the one-line fix I'm proposing here? It seems to me that setting the convection to zero for the calculation of the surface temperatures, and then using a non-zero value to calculate the heat gain to the zone is disturbingly inconsistent. I don't see how this will have negative impacts elsewhere.

At a minimum, we should make the calculation for frames and dividers consistent.

File: src/EnergyPlus/WindowManager.cc (hunk 1 above)
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc]: OK, so this is IR from internal gains?  Not from surfaces?  That is a component that's not present in the series of 6872 defect files.  So, if you add, say, electric equipment or lights with a significant radiant fraction does that show a discrepancy then?

Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: It looks like the `IRfromParentZone` is calculated for each window ([here](https://github.com/NREL/EnergyPlus/blob/dd8dc05c1e7401e884567b7e9978be275459f504/src/EnergyPlus/HeatBalanceIntRadExchange.cc#L369)) from the accumulated incident long-wave radiation from the zone surfaces. I don't see the radiation from internal gains impacting `IRFromParentZone` anywhere in the source code.

Comment (EnergyArchmage) [inline src/EnergyPlus/WindowManager.cc]: I don't see the overall IR exchange as seperate problem here.  A total rework should make each frame have an instance in the main Surface data structure and participate in the ZHBM in all the usual ways.  Until that is done there is no clear cut solution to the current hot mess.

Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: @EnergyArchmage I might still be missing something here. Are you proposing it is better to leave things alone? Shouldn't the divider and frame calculations at least be made consistent?

Comment (EnergyArchmage) [inline src/EnergyPlus/WindowManager.cc]: I think the FrameHeatGain should be left to match what is really coupled to the zone air.  If they don't agree then the zone gains don't match the sum of all the contributions.  You could revise the frame temp calculation if you want.  I would not expect the frame and divider to have the exact same IR exchange with glazing surface.

Maybe you could add a new output variable for whatever it is you want to find for the project.

Comment (nealkruis) [inline src/EnergyPlus/WindowManager.cc]: I think a new report variable would be good, especially considering the current documentation says:

> ### Surface Window Heat Gain Energy [J]
> 
> The total heat flow to the zone from the glazing, frame and divider of an exterior window when the total heat flow is positive.
> 
> For a window without an interior shading device, this heat flow is equal to:
> - Surface Window Transmitted Solar Radiation Rate (see definition, above)
> - Convective heat flow to the zone from the zone side of the glazing
> - Net IR heat flow to the zone from zone side of the glazing
> - Short-wave radiation from zone transmitted back out the window
> - Conduction to zone from window frame and divider, if present

Currently this is not the case. This variable (and all related variables) use the [convection from the frame](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WindowManager.cc#L6108), and the [conduction from the divider](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WindowManager.cc#L6165).

I would suggest that we use the convection from both the frame and divider for these variables and create separate report variables for "Surface Window Net Heat Transfer Rate [W]", and "Surface Window Net Heat Transfer Energy [J]" using the conduction from both the frame and divider.

Comment (EnergyArchmage) [inline src/EnergyPlus/WindowManager.cc]: So the documentation should change the word "Conduction" to "Convection" in the fifth bullet.

**Comment by nrel-bot-3** [comment]
@mjwitte @nealkruis @lgentile it has been 14 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Any updates on work to wrap this up for the bug fix release?

**Comment by nealkruis** [comment]
@Myoldmopar I think we should postpone this until a future release as the changes we are proposing will change the output interface (adding a new output variable).

**Comment by Myoldmopar** [comment]
@nealkruis Adding a new output variable doesn't cause any problem.  It doesn't require any transition.  If you were renaming an output:variable, then yeah, that would be a problem.  But in this case, user's idf's would simply not have that output:variable anyway.

All that said, I don't care either way if this goes in or not, just curious.

**Comment by nrel-bot-3** [comment]
@mjwitte @nealkruis @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte @nealkruis @lgentile it has been 14 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @nealkruis @lgentile it has been 19 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @nealkruis @lgentile it has been 14 days since this pull request was last updated.

**Comment by nealkruis** [comment]
@mjwitte @Myoldmopar @lgentile This is a good example of code in need of refactoring. I found several files with different definitions of `WinHeatGain` ([1](https://github.com/NREL/EnergyPlus/pull/5099/files#diff-c10afc2ba60f4d2552b6510cdbbf5a95L5434), [2](https://github.com/NREL/EnergyPlus/pull/5099/files#diff-2c5805a62c110505a03bf7be31c17d3dR3772), [3](https://github.com/NREL/EnergyPlus/pull/5099/files#diff-72f298b1abf572558fe82dde7cb7f78dR1003), [4](https://github.com/NREL/EnergyPlus/pull/5099/files#diff-a89620a3d0823da31d16c75f5879a365R3538)). It makes adding the new report variable very inefficient, and also makes it difficult to review and test thoroughly. I did my best to dot my i's and cross my t's, but the effects are pretty wide reaching.

After digging around in the Window code for quite a while, I have some ideas for when/if we ever get around to refactoring this code.

We'll see what comes back from the CI, but diffs are expected in some test files with `WindowProperty:FrameAndDivider` objects.

**Comment by mjwitte** [comment]
@nealkruis If I'm following the latest changes correctly, this adds a new output variable for "Surface Window Net Heat Transfer Rate/Energy" and makes one small change to the existing frame convection as discussed [here](https://github.com/NREL/EnergyPlus/pull/5099/files#r39320941).  I'm ok with this going in for v8.5, but there is currently a failing unit test, EnergyPlusFixture.WindowFrameTest.
@Myoldmopar Handing off to you for final review/merge if the unit test gets fixed in time for v8.5.

**Comment by Myoldmopar** [comment]
@nealkruis I know you have been preoccupied with #5542, et al., so I don't anticipate you'll have time to wrap up the unit test issue @mjwitte mentioned above.  **However**, if you do, then this can still go in, barring any other issues.  I'll move this to the 8.6.0 milestone for planning purposes, but if you get a chance to work on it, it can still go in 8.5.  Thanks.

**Comment by nealkruis** [comment]
@Myoldmopar @mjwitte I plan to resolve the unit test issue today. I'll keep you posted.

File: tst/EnergyPlus/unit/WindowManager.unit.cc [hunk 3]
```diff
@@ -136,6 +137,7 @@ TEST_F(EnergyPlusFixture, WindowFrameTest )
 
 	DataHeatBalance::ZoneIntGain.allocate(1);
 
+	createFacilityElectricPowerServiceObject();
```
Comment (nealkruis) [inline tst/EnergyPlus/unit/WindowManager.unit.cc:140]: @EnergyArchmage Why should this be necessary for an envelope unit test? I noticed that this is used in several unit tests that don't relate to the Electric Power Service Manager. It seems that that shouldn't be necessary.

**Comment by Myoldmopar** [comment]
OK, this will now go in.  The additional output variable isn't something that should affect folks downstream.  The unit test question can be resolved later.  Thanks all.
