### PR TITLE
Protect Debug File from FatalError on processInput

### LINKED ISSUE #8238: IO File issues: segfaults or hanging
Issue overview
--------------

Running OpenStudio regression tests, I have two problems that seem related to IO:

* `refrigeration_system.rb.idf` segfaults after throwing a fatal (and therefore eplusout.err ends up empty.... not helpful)
* `utility_bill02.rb.idf` seems to hang indefinitely at the end of the simulation. By hang I mean after 15 minutes it's still stuck in the same rough location, either `readLine` or `ReadResults` (see Details below)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 18.04
 - Version of EnergyPlus (if using an intermediate build, include SHA): v940-IOFreeze, https://github.com/NREL/EnergyPlus/commit/908c5cedf506343fd08ab3ff5cb7974707d70f68

#### refrigeration_system.rb.idf

```
(py38)julien@temp$ lldb $ep_build/Products/energyplus -- refrigeration_system.rb.idf 
The "osname" command has been installed, type "help osname" for detailed help.
(lldb) target create "/home/julien/Software/Others/EnergyPlus-build/Products/energyplus"
Current executable set to '/home/julien/Software/Others/EnergyPlus-build/Products/energyplus' (x86_64).
(lldb) settings set -- target.run-args  "refrigeration_system.rb.idf"
(lldb) pro lau
Process 6063 launched: '/home/julien/Software/Others/EnergyPlus-build/Products/energyplus' (x86_64)
error: ld-2.27.so 0x7fffffff0005c587: adding range [0x1469a-0x1470a) which has a base that is less than the function's low PC 0x14e10. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0x7fffffff0005c587: adding range [0x14720-0x14726) which has a base that is less than the function's low PC 0x14e10. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0x7fffffff0005c5e8: adding range [0x1469a-0x1470a) which has a base that is less than the function's low PC 0x14e10. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0x7fffffff0005c5e8: adding range [0x14720-0x14726) which has a base that is less than the function's low PC 0x14e10. Please file a bug and attach the file at the start of this error message
EnergyPlus Starting
EnergyPlus, Version 9.4.0-908c5cedf5, YMD=2020.08.27 10:55
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
Process 6063 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff1c8caf0 libstdc++.so.6`std::istream::sentry::sentry(std::istream&, bool) + 16
libstdc++.so.6`std::istream::sentry::sentry:
->  0x7ffff1c8caf0 <+16>: movq   (%rsi), %rax
    0x7ffff1c8caf3 <+19>: movb   $0x0, (%rdi)
    0x7ffff1c8caf6 <+22>: movq   -0x18(%rax), %rdi
    0x7ffff1c8cafa <+26>: addq   %rsi, %rdi
(lldb) bt
* thread #1, name = 'energyplus', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x00007ffff1c8caf0 libstdc++.so.6`std::istream::sentry::sentry(std::istream&, bool) + 16
    frame #1: 0x00007ffff1c8e10b libstdc++.so.6`std::istream::tellg() + 43
    frame #2: 0x00007ffff44216d5 libenergyplusapi.so.9.4.0`EnergyPlus::InputOutputFile::position(this=0x00007fffffff9438) const at IOFiles.cc:242
    frame #3: 0x00007ffff4f2c76d libenergyplusapi.so.9.4.0`EnergyPlus::CloseMiscOpenFiles(ioFiles=0x00007fffffff90c8) at UtilityRoutines.cc:836
    frame #4: 0x00007ffff4f2b89c libenergyplusapi.so.9.4.0`EnergyPlus::AbortEnergyPlus(state=0x00007fffffff7a30) at UtilityRoutines.cc:727
    frame #5: 0x00007ffff3c5248a libenergyplusapi.so.9.4.0`commonRun(state=0x00007fffffff7a30) at EnergyPlusPgm.cc:292
    frame #6: 0x00007ffff3c526f8 libenergyplusapi.so.9.4.0`initializeEnergyPlus(state=0x00007fffffff7a30, filepath=" z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:326
    frame #7: 0x00007ffff3c52c36 libenergyplusapi.so.9.4.0`RunEnergyPlus(state=0x00007fffffff7a30, filepath=" z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:392
    frame #8: 0x00007ffff3c5219b libenergyplusapi.so.9.4.0`EnergyPlusPgm(state=0x00007fffffff7a30, filepath=" z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:224
    frame #9: 0x00005555555db3a4 energyplus`main(argc=2, argv=0x00007fffffffcd88) at main.cc:65
    frame #10: 0x00007ffff1595b97 libc.so.6`__libc_start_main(main=(energyplus`main at main.cc:55), argc=2, argv=0x00007fffffffcd88, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffcd78) at libc-start.c:310
    frame #11: 0x00005555555db1ca energyplus`_start + 42
```

#### utility_bill02.rb.idf

In a debugger, I stop the program every now and then (like 5 minutes appart), as you can see it's either in readLine or ReadResult all the time.

```
(lldb) bt
* thread #1, name = 'energyplus', stop reason = signal SIGSTOP
  * frame #0: 0x00007ffff3be35fd libenergyplusapi.so.9.4.0`std::unique_ptr<std::istream, std::default_delete<std::istream> >::operator bool(this=0x00007fffffff6420) const at unique_ptr.h:345
    frame #1: 0x00007ffff4420a54 libenergyplusapi.so.9.4.0`EnergyPlus::InputFile::readLine[abi:cxx11](this=0x00007fffffff9710) at IOFiles.cc:89
    frame #2: 0x00007ffff51a6fec libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::SkipEPlusWFHeader(ioFiles=0x00007fffffff90b8) at WeatherManager.cc:8344
    frame #3: 0x00007ffff51665d9 libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ReadEPlusWeatherForDay(ioFiles=0x00007fffffff90b8, DayToRead=262, Environ=3, BackSpaceAfterRead=false) at WeatherManager.cc:2854
    frame #4: 0x00007ffff5162c2b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ReadWeatherForDay(ioFiles=0x00007fffffff90b8, DayToRead=262, Environ=3, BackSpaceAfterRead=false) at WeatherManager.cc:2411
    frame #5: 0x00007ffff51602ad libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::InitializeWeather(ioFiles=0x00007fffffff90b8, printEnvrnStamp=0x00007ffff7da4d38) at WeatherManager.cc:1994
    frame #6: 0x00007ffff514b52b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ManageWeather(state=0x00007fffffff7a20) at WeatherManager.cc:521
    frame #7: 0x00007ffff4aa85cc libenergyplusapi.so.9.4.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffff7a20) at SimulationManager.cc:636
    frame #8: 0x00007ffff3c52c53 libenergyplusapi.so.9.4.0`RunEnergyPlus(state=0x00007fffffff7a20, filepath="\U00000010z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:395
    frame #9: 0x00007ffff3c5219b libenergyplusapi.so.9.4.0`EnergyPlusPgm(state=0x00007fffffff7a20, filepath="\U00000010z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:224
    frame #10: 0x00005555555db3a4 energyplus`main(argc=3, argv=0x00007fffffffcd78) at main.cc:65
    frame #11: 0x00007ffff1595b97 libc.so.6`__libc_start_main(main=(energyplus`main at main.cc:55), argc=3, argv=0x00007fffffffcd78, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffcd68) at libc-start.c:310
    frame #12: 0x00005555555db1ca energyplus`_start + 42
(lldb) c
Process 23310 resuming




Process 23310 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGSTOP
    frame #0: 0x00005555555ea9d2 energyplus`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string(this="0d\xff\xff\xff\U0000007f"...) at basic_string.h:647
   644 	       *  @brief  Destroy the string instance.
   645 	       */
   646 	      ~basic_string()
-> 647 	      { _M_dispose(); }
   648 	
   649 	      /**
   650 	       *  @brief  Assign the value of @a str to this string.
(lldb) bt
* thread #1, name = 'energyplus', stop reason = signal SIGSTOP
  * frame #0: 0x00005555555ea9d2 energyplus`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string(this="0d\xff\xff\xff\U0000007f"...) at basic_string.h:647
    frame #1: 0x00007ffff3bdedb8 libenergyplusapi.so.9.4.0`EnergyPlus::InputFile::ReadResult<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~ReadResult(this=0x00007fffffff6420) at IOFiles.hh:65
    frame #2: 0x00007ffff51a700b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::SkipEPlusWFHeader(ioFiles=0x00007fffffff90b8) at WeatherManager.cc:8344
    frame #3: 0x00007ffff51665d9 libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ReadEPlusWeatherForDay(ioFiles=0x00007fffffff90b8, DayToRead=262, Environ=3, BackSpaceAfterRead=false) at WeatherManager.cc:2854
    frame #4: 0x00007ffff5162c2b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ReadWeatherForDay(ioFiles=0x00007fffffff90b8, DayToRead=262, Environ=3, BackSpaceAfterRead=false) at WeatherManager.cc:2411
    frame #5: 0x00007ffff51602ad libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::InitializeWeather(ioFiles=0x00007fffffff90b8, printEnvrnStamp=0x00007ffff7da4d38) at WeatherManager.cc:1994
    frame #6: 0x00007ffff514b52b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ManageWeather(state=0x00007fffffff7a20) at WeatherManager.cc:521
    frame #7: 0x00007ffff4aa85cc libenergyplusapi.so.9.4.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffff7a20) at SimulationManager.cc:636
    frame #8: 0x00007ffff3c52c53 libenergyplusapi.so.9.4.0`RunEnergyPlus(state=0x00007fffffff7a20, filepath="\U00000010z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:395
    frame #9: 0x00007ffff3c5219b libenergyplusapi.so.9.4.0`EnergyPlusPgm(state=0x00007fffffff7a20, filepath="\U00000010z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:224
    frame #10: 0x00005555555db3a4 energyplus`main(argc=3, argv=0x00007fffffffcd78) at main.cc:65
    frame #11: 0x00007ffff1595b97 libc.so.6`__libc_start_main(main=(energyplus`main at main.cc:55), argc=3, argv=0x00007fffffffcd78, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffcd68) at libc-start.c:310
    frame #12: 0x00005555555db1ca energyplus`_start + 42
(lldb) c
Process 23310 resuming





Process 23310 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGSTOP
    frame #0: 0x00005555555eebfa energyplus`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data(this="`[\xda\xf7\xff\U0000007f"...) at basic_string.h:182
   179 	      _M_local_data()
   180 	      {
   181 	#if __cplusplus >= 201103L
-> 182 		return std::pointer_traits<pointer>::pointer_to(*_M_local_buf);
   183 	#else
   184 		return pointer(_M_local_buf);
   185 	#endif
(lldb) bt
* thread #1, name = 'energyplus', stop reason = signal SIGSTOP
  * frame #0: 0x00005555555eebfa energyplus`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data(this="`[\xda\xf7\xff\U0000007f"...) at basic_string.h:182
    frame #1: 0x00007ffff3bdeff4 libenergyplusapi.so.9.4.0`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(this="`[\xda\xf7\xff\U0000007f"..., __str="0c\xff\xff\xff\U0000007f"...) at basic_string.h:532
    frame #2: 0x00007ffff4420aea libenergyplusapi.so.9.4.0`EnergyPlus::InputFile::readLine[abi:cxx11](this=0x00007fffffff9710) at IOFiles.cc:95
    frame #3: 0x00007ffff51a6fec libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::SkipEPlusWFHeader(ioFiles=0x00007fffffff90b8) at WeatherManager.cc:8344
    frame #4: 0x00007ffff51665d9 libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ReadEPlusWeatherForDay(ioFiles=0x00007fffffff90b8, DayToRead=262, Environ=3, BackSpaceAfterRead=false) at WeatherManager.cc:2854
    frame #5: 0x00007ffff5162c2b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ReadWeatherForDay(ioFiles=0x00007fffffff90b8, DayToRead=262, Environ=3, BackSpaceAfterRead=false) at WeatherManager.cc:2411
    frame #6: 0x00007ffff51602ad libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::InitializeWeather(ioFiles=0x00007fffffff90b8, printEnvrnStamp=0x00007ffff7da4d38) at WeatherManager.cc:1994
    frame #7: 0x00007ffff514b52b libenergyplusapi.so.9.4.0`EnergyPlus::WeatherManager::ManageWeather(state=0x00007fffffff7a20) at WeatherManager.cc:521
    frame #8: 0x00007ffff4aa85cc libenergyplusapi.so.9.4.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffff7a20) at SimulationManager.cc:636
    frame #9: 0x00007ffff3c52c53 libenergyplusapi.so.9.4.0`RunEnergyPlus(state=0x00007fffffff7a20, filepath="\U00000010z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:395
    frame #10: 0x00007ffff3c5219b libenergyplusapi.so.9.4.0`EnergyPlusPgm(state=0x00007fffffff7a20, filepath="\U00000010z\xff\xff\xff\U0000007f"...) at EnergyPlusPgm.cc:224
    frame #11: 0x00005555555db3a4 energyplus`main(argc=3, argv=0x00007fffffffcd78) at main.cc:65
    frame #12: 0x00007ffff1595b97 libc.so.6`__libc_start_main(main=(energyplus`main at main.cc:55), argc=3, argv=0x00007fffffffcd78, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffcd68) at libc-start.c:310
    frame #13: 0x00005555555db1ca energyplus`_start + 42
```

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/8000s/8238
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #8253: Input errors cause segfault with empty err output
Issue overview
--------------
As noted by @Myoldmopar in https://github.com/NREL/EnergyPlus/pull/7904#issuecomment-678405079 , using an invalid object type in the idf will cause a crash with an empty err output file.

There is a message to the console:
```
EnergyPlus, Version 9.4.0-ff4b91794a, YMD=2020.09.03 13:38
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
```
But then it crashes [here](https://github.com/NREL/EnergyPlus/blob/ff4b91794ae3dc5b6c17b9015d93d84122596e26/src/EnergyPlus/IOFiles.cc#L242) with an access violation.

But this all sounds familiar - yes, *any* input error (like an incorrect key choice) has the same result. This is deja vu of https://github.com/NREL/EnergyPlus/issues/8180 which produced an empty err file but didn't crash. We need a way to catch this in CI - perhaps we need a testfile that purposely has an input error?

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file: [5ZoneAirCooled-BadObject.idf.txt](https://github.com/NREL/EnergyPlus/files/5170548/5ZoneAirCooled-BadObject.idf.txt) (Bad object is "Timesteps, 4;")
[5ZoneAirCooled-BadKeyChoice.idf.txt](https://github.com/NREL/EnergyPlus/files/5170644/5ZoneAirCooled-BadKeyChoice.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Fixes #8238 Part 1 - refrigeration_system.rb.idf
 - Fixes #8253 (same type of problem)
 - This is just a plain old mal-formed IDF. The real problem is that E+ hard crashed due to trying to access the non-existent debug file, which was causing the error file to be left blank. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UtilityRoutines.cc [hunk 1]
```diff
@@ -810,10 +810,12 @@ namespace UtilityRoutines {
         CloseReportIllumMaps(ioFiles);
         CloseDFSFile(ioFiles);
 
-        if (DebugOutput || ioFiles.debug.position() > 0) {
-            ioFiles.debug.close();
-        } else {
-            ioFiles.debug.del();
+        if (ioFiles.debug.good()) {
+            if (DebugOutput || ioFiles.debug.position() > 0) {
```
Comment (mbadams5) [inline src/EnergyPlus/UtilityRoutines.cc]: Really you can just do `if (DebugOutput || (ioFiles.debug.good() && ioFiles.debug.position() > 0)) {`.
`del()` will check if the stream is valid before attempting to use it.
Additionally, I believe it is hard crashing since `position()`  has `noexcept` but it clearly CAN throw an exception so it hard crashes instead (@Myoldmopar @lefticus).

**Comment by Myoldmopar** [comment]
Seems like this should be good to go now.  I'm building develop and this branch to test locally though.

**Comment by Myoldmopar** [comment]
Tested locally by breaking the input in a test file.  Develop leaves an empty error file due to the hard crash.  This branch provides a proper error file.  Nice!  Good fix, @mitchute, thanks!

**Comment by Myoldmopar** [comment]
@mitchute I'll let you open a new issue for the second half of #8238
