### PR TITLE
#7711 - Fix crash when using both WaterHeat:HeatPump:PumpedCondenser and WaterHeater:HeatPump:WrappedCondenser

### LINKED ISSUE #7711: Crash in InputProcessor due to bug in WaterThermalTanks.cc
Issue overview
--------------

I have a file that's crashing on this line.

https://github.com/NREL/EnergyPlus/blob/bae88904b5bac1f9f7fe6795242dbfc51cbba842/src/EnergyPlus/InputProcessing/InputProcessor.cc#L967

I think it should be `int targetIdfObjNum = idfObjNums[Number - 1];`

I end up with 

```
   ** Severe  ** vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
```

I have a file with one WaterHeater:HeatPump:PumpedCondenser (works for this one) and also a WaterHeater:HeatPump:WrappedCondenser (crashes for this one).

backtrace:

```
(lldb) bt
* thread #1, name = 'energyplus', stop reason = signal SIGSEGV: invalid address (fault address: 0x1)
  * frame #0: 0x00007ffff1e74231 libstdc++.so.6`___lldb_unnamed_symbol572$$libstdc++.so.6 + 17
    frame #1: 0x00007ffff1e750fd libstdc++.so.6`__gnu_debug::_Error_formatter::_M_error() const + 253
    frame #2: 0x00007ffff3d61e45 libenergyplusapi.so.9.3.0`std::__debug::vector<int, std::allocator<int> >::operator[](this=0x00007fffffff94a0 size=0, __n=1) at vector:417
    frame #3: 0x00007ffff3d3d037 libenergyplusapi.so.9.3.0`EnergyPlus::InputProcessor::getJSONObjNum(this=0x0000555555825080, Object="08\xa7VUU"..., Number=2) at InputProcessor.cc:967
    frame #4: 0x00007ffff3d3abf9 libenergyplusapi.so.9.3.0`EnergyPlus::InputProcessor::getObjectItem(this=0x0000555555825080, Object="08\xa7VUU"..., Number=2, Alphas=ObjexxFCL::Array1S_string @ 0x00007fffffffa3f0, NumAlphas=0x00007fffffff9ec4, Numbers=Array1S<double> @ 0x00007fffffffa440, NumNumbers=0x00007fffffff9ec8, Status=0x00007fffffff9ecc, NumBlank=Optional<ObjexxFCL::Array1D<bool>, void> @ 0x00007fffffffa2b0, AlphaBlank=Optional<ObjexxFCL::Array1D<bool>, void> @ 0x00007fffffffa300, AlphaFieldNames=Optional<ObjexxFCL::Array1D<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void> @ 0x00007fffffffa350, NumericFieldNames=Optional<ObjexxFCL::Array1D<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void> @ 0x00007fffffffa3a0) at InputProcessor.cc:731
    frame #5: 0x00007ffff5bfac75 libenergyplusapi.so.9.3.0`EnergyPlus::WaterThermalTanks::getHPWaterHeaterInput() at WaterThermalTanks.cc:1062
    frame #6: 0x00007ffff5c2212e libenergyplusapi.so.9.3.0`EnergyPlus::WaterThermalTanks::GetWaterThermalTankInput() at WaterThermalTanks.cc:4037
    frame #7: 0x00007ffff5bf4541 libenergyplusapi.so.9.3.0`EnergyPlus::WaterThermalTanks::CalcWaterThermalTankZoneGains() at WaterThermalTanks.cc:643
    frame #8: 0x00007ffff4f19170 libenergyplusapi.so.9.3.0`EnergyPlus::InternalHeatGains::InitInternalHeatGains() at InternalHeatGains.cc:6015
    frame #9: 0x00007ffff4e8584c libenergyplusapi.so.9.3.0`EnergyPlus::InternalHeatGains::ManageInternalHeatGains(InitOnly=ObjexxFCL::Optional_bool_const @ 0x00007fffffffbf10) at InternalHeatGains.cc:213
    frame #10: 0x00007ffff4d3231f libenergyplusapi.so.9.3.0`EnergyPlus::HeatBalanceSurfaceManager::InitSurfaceHeatBalance() at HeatBalanceSurfaceManager.cc:732
    frame #11: 0x00007ffff4d2fe5f libenergyplusapi.so.9.3.0`EnergyPlus::HeatBalanceSurfaceManager::ManageSurfaceHeatBalance() at HeatBalanceSurfaceManager.cc:236
    frame #12: 0x00007ffff4c9301c libenergyplusapi.so.9.3.0`EnergyPlus::HeatBalanceManager::ManageHeatBalance() at HeatBalanceManager.cc:368
    frame #13: 0x00007ffff3f80de3 libenergyplusapi.so.9.3.0`EnergyPlus::SizingManager::SetupZoneSizing(ErrorsFound=0x00007ffff7d69619) at SizingManager.cc:3998
    frame #14: 0x00007ffff3f56a12 libenergyplusapi.so.9.3.0`EnergyPlus::SizingManager::ManageSizing() at SizingManager.cc:326
    frame #15: 0x00007ffff3f2be7f libenergyplusapi.so.9.3.0`EnergyPlus::SimulationManager::ManageSimulation() at SimulationManager.cc:363
    frame #16: 0x00007ffff3c9227a libenergyplusapi.so.9.3.0`RunEnergyPlus(filepath=" ����) at EnergyPlusPgm.cc:467
    frame #17: 0x00007ffff3c90062 libenergyplusapi.so.9.3.0`EnergyPlusPgm(filepath=" ����) at EnergyPlusPgm.cc:230
    frame #18: 0x0000555555555542 energyplus`main(argc=4, argv=0x00007fffffffcf38) at main.cc:60
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7711/in.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #7720: Crash when using a WaterHeater:HeatPump and also a simple (standalone) WaterHeaterMixed
Issue overview
--------------

I get a hard crash, in calcStandardRatings. Will start by creating a proper unit test to isolate the bug, then fix it.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7711 
 - Fix crash happening in `InputProcessor` due to `WaterThermalTanks` when using both `WaterHeat:HeatPump:PumpedCondenser` and `WaterHeater:HeatPump:WrappedCondenser`
 - This is a case of a bad index variable being used, occurs only if you have **BOTH** types present in the IDF file (which explains why it wasn't caught until today while this has been in the code since version 8.4)
 - Added Gtest that crashes like in #7711 without fix and passes with fix. 

While in the process of fixing it:

- Found #7720, so Fixes #7720 too

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 1]
```diff
@@ -1042,25 +1045,30 @@ namespace WaterThermalTanks {
...
+                // Actual index of Pumped type
+                HPWaterHeaterNumOfSpecificType = HPWaterHeaterNum;
             } else {
                 // Wrapped Condenser
                 DataIPShortCuts::cCurrentModuleObject = cHPWHWrappedCondenser;
                 HPWH.TypeNum = DataPlant::TypeOf_HeatPumpWtrHeaterWrapped;
                 nNumPossibleAlphaArgs = 27;
                 nNumPossibleNumericArgs = 10;
+                // Actual index of Wrapped type
+                HPWaterHeaterNumOfSpecificType = HPWaterHeaterNum - NumPumpedCondenser;
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.cc:1065]: This is the actual fix basically.

Container `HPWaterHeater` stores both HPWH:Pumped and HPWH:Wrapped in that order. Before fix if you had 1 HPWH:Pumped and one HPWH:Wrapped it would call getObjectItem for the wrapped one passing an index of 2, which doesn't exist in InputProcessor since there's only one object of type HPWH:WrappedCondenser, so it would crash hard.

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 2]
```diff
@@ -1042,25 +1045,30 @@ namespace WaterThermalTanks {
...
             }
 
             int NumAlphas;
             int NumNums;
             int IOStat;
             inputProcessor->getObjectItem(DataIPShortCuts::cCurrentModuleObject,
-                                          HPWaterHeaterNum,
+                                          HPWaterHeaterNumOfSpecificType,
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.cc:1072]: Has to be an index specific to the type of object you want to get.

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 3]
```diff
@@ -3440,3 +3440,479 @@ TEST_F(WaterThermalTanksFixture, StratifiedTank_WarnPotentialFreeze)
...
+        "  ,                        !- Motor Loss Zone Name",
+        "  0,                       !- Motor Loss Radiative Fraction",
+        "  General,                 !- End-Use Subcategory",
+        "  1;                       !- Number of Speeds",
+
+    });
+
+    ASSERT_TRUE(process_idf(idf_objects));
+
+    EXPECT_TRUE(WaterThermalTanks::GetWaterThermalTankInput());
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc]: Before fix it crashes here.

**Review by jmarrec — COMMENTED** [review]
Added review comments for a walkthrough of code changes

**Comment by jmarrec** [comment]
Merged #7722 (fixes #7720) in this one as it's more convenient to review.

File: src/EnergyPlus/WaterThermalTanks.cc (hunk 1 above)
Comment (mitchute) [reply src/EnergyPlus/WaterThermalTanks.cc:1065]: @jmarrec thanks for the fix. Having just worked through the refactor on this file, I can attest that there are several things like this in here that need to get cleaned up.

**Comment by mitchute** [comment]
I verified that the unit tests pass locally. Assuming CI comes back clean, this can merge.

**Comment by mitchute** [comment]
CI is happy. Merging.
