### PR TITLE
Fix ashrae205chiller crashing/repeated warnings issue

### LINKED ISSUE #9662: Issues with Chiller:Electric:ASHRAE205
Issue overview
--------------

Disclaimer: I realize this is a brand new object and not all of the functionality (eg: Heat Recovery) is implemented.

I'm wrapping this object in the OS SDK, and running into a few issues, this is a running list:

* No warning if heat recovery nodes are set, while there are some warnings for other fields: https://github.com/NREL/EnergyPlus/blob/599c64df5584701dc1c2020f9667c5f7a720fb34/src/EnergyPlus/ChillerElectricASHRAE205.cc#L172-L175
    * Actually, this makes the simulation Fatal due to UNDEFINED nodes 
* Improper handling of autosizable fields resulting in `[json.exception.type_error.302] type must be number, but is string`: https://github.com/NREL/EnergyPlus/blob/599c64df5584701dc1c2020f9667c5f7a720fb34/src/EnergyPlus/ChillerElectricASHRAE205.cc#L268-L275
* When the CBOR representation file cannot be found, should set ErrorsFound = true and maybe just bail early instead of trying to do the pointer cast. https://github.com/NREL/EnergyPlus/blob/599c64df5584701dc1c2020f9667c5f7a720fb34/src/EnergyPlus/ChillerElectricASHRAE205.cc#L153
* There isn't enough checking done for loop/nodes. I messed up my input file, I have `A node that is not referenced anywhere else in the IDF` for 'Oil Cooler Inlet Node', and I can produce a hard crash here because `OCPlantLoc.loopNum` is zero. https://github.com/NREL/EnergyPlus/blob/599c64df5584701dc1c2020f9667c5f7a720fb34/src/EnergyPlus/ChillerElectricASHRAE205.cc#L612-L618

* `ASHRAE901_OfficeLarge_STD2019_Denver_Chiller205_Detailed.idf` issues a **ton** of `WARNING: A cubic interpolation method is not valid for grid axes with only one value. Interpolation method reset to linear.`

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.2.0-IOFreeze, develop at 599c64df5584701dc1c2020f9667c5f7a720fb34

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): https://github.com/NREL/EnergyPlusDevSupport/blob/d5e9115ce3117e552933c98e34edebbfd0a57962/DefectFiles/9000s/9662/ASHRAE901_OfficeLarge_STD2019_Denver_Chiller205_Detailed_wrongNodes.idf#L13874-L13896
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by tanaya-mankad**
Pull request overview
---------------------
 - Fixes #9662
 - This PR addresses suggestions made by @jmarrec in Issue 9662, including hiding repeated Btwxt warnings. Many of his fixes from branch [9662_ChillerElectricASHRAE205_Errors](https://github.com/NREL/EnergyPlus/compare/9662_ChillerElectricASHRAE205_Errors) were merged into this branch first.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ChillerElectricASHRAE205.cc [hunk 1]
```diff
@@ -151,9 +151,13 @@ void getChillerASHRAE205Input(EnergyPlusData &state)
 
         auto rep_file_name = ip->getAlphaFieldValue(fields, objectSchemaProps, "representation_file_name");
         fs::path rep_file_path = DataSystemVariables::CheckForActualFilePath(state, fs::path(rep_file_name), std::string(RoutineName));
+        if (rep_file_path.empty()) {
+            ErrorsFound = true;
+        }
```
Comment (Myoldmopar) [inline src/EnergyPlus/ChillerElectricASHRAE205.cc:156]: I guess the CheckForActualFilePath will emit warnings so that it is sufficient to just set the error flag to true here.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc [hunk 2]
```diff
@@ -151,9 +151,13 @@ void getChillerASHRAE205Input(EnergyPlusData &state)
...
         std::pair<EnergyPlusData *, std::string> callbackPair{&state,
                                                               format("{} \"{}\"", state.dataIPShortCut->cCurrentModuleObject, thisObjectName)};
         tk205::set_error_handler(tk205ErrCallback, &callbackPair);
+        Btwxt::LOG_LEVEL = static_cast<int>(Btwxt::MsgLevel::MSG_WARN);
```
Comment (Myoldmopar) [inline src/EnergyPlus/ChillerElectricASHRAE205.cc:160]: Feels a bit odd to have to static cast when both sides are Btwxt expressions, but that's not my concern here.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc [hunk 3]
```diff
@@ -263,15 +267,27 @@ void getChillerASHRAE205Input(EnergyPlusData &state)
...
-        if (thisChiller.CondVolFlowRate == DataSizing::AutoSize) {
-            thisChiller.CondVolFlowRateWasAutoSized = true;
+        {
+            auto tmpFlowRate = fields.at("condenser_maximum_requested_flow_rate");
+            if (tmpFlowRate == "Autosize") {
+                thisChiller.CondVolFlowRate = DataSizing::AutoSize;
+                thisChiller.CondVolFlowRateWasAutoSized = true;
+            } else {
+                thisChiller.CondVolFlowRate = tmpFlowRate.get<Real64>();
+            }
```
Comment (Myoldmopar) [inline src/EnergyPlus/ChillerElectricASHRAE205.cc:290]: :+1: I wasn't actually sure whether the input processor would translate the autosize string into the numeric value, this is fine.

**Review by Myoldmopar — APPROVED** [review]
This seems like a reasonable set of changes.

**Comment by Myoldmopar** [comment]
@tanaya-bigladder do you plan to push more commits?  So far this looks good, but it's still marked as draft so I will hold off any local testing for now.

**Comment by tanaya-mankad** [comment]
The Real64 additions were from Julien @jmarrec, which I adopted from his commits. I learned something new! I think I am finished adding commits, & was just waiting for the latest CI to return green before pulling it out of draft.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc (hunk 3 above)
Comment (jmarrec) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:290]: If you try to get<Real64> on a an "Autosize" string, you get `[json.exception.type_error.302] type must be number, but is string`. (nlohmann's `json` behaves like a variant)

**Comment by Myoldmopar** [comment]
It's looking green on CI, so if this is ready, please mark it as such and I'll try to get it merged in today.

**Comment by Myoldmopar** [comment]
FWIW, I pulled upstream develop and built and tested this successfully, so that is already done.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:290]: @jmarrec are you saying that as the code is right now, the call to get the value is going to fail for autosize inputs?  Or are you just clarifying what was changed?

File: src/EnergyPlus/ChillerElectricASHRAE205.cc [hunk 4]
```diff
@@ -263,15 +267,27 @@ void getChillerASHRAE205Input(EnergyPlusData &state)
...
-        if (thisChiller.SizFac <= 0.0) thisChiller.SizFac = 1.0;
+        if (thisChiller.SizFac <= 0.0) {
+            thisChiller.SizFac = 1.0;
+        }
 
-        thisChiller.EvapVolFlowRate = fields.at("chilled_water_maximum_requested_flow_rate").get<Real64>();
-        if (thisChiller.EvapVolFlowRate == DataSizing::AutoSize) {
-            thisChiller.EvapVolFlowRateWasAutoSized = true;
+        {
+            auto tmpFlowRate = fields.at("chilled_water_maximum_requested_flow_rate");
```
Comment (amirroth) [inline src/EnergyPlus/ChillerElectricASHRAE205.cc:275]: Killing me with this `auto` business. I'm serious.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc [hunk 5]
```diff
@@ -263,15 +267,27 @@ void getChillerASHRAE205Input(EnergyPlusData &state)
...
+            if (tmpFlowRate == "Autosize") {
+                thisChiller.EvapVolFlowRate = DataSizing::AutoSize;
```
Comment (amirroth) [inline src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: 📌 I don't expect this to be addressed in this PR (that's what 📌 means in case you were wondering), but ... overloading a single variable with an enumeration and a value is not good programming. Especially when the variable is not an integer and thus prone to precision issues and especially when you also have another variable that effectively duplicates the enumeration usage (`EvapFlowRateWasAutosized`). This idiom (which I have seen in a few other places, although mostly with integers which makes it slightly less terrible) needs to be purged.

Comment (mjwitte) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: Hmm, not sure why this field is causing so much trouble, we have autosized fields all over the place, but maybe not many places that are using the raw `fields.at` method instead of `getRealFieldValue` or `getObjectItem`. If I'm following what was done here, this needs at least a `samestring` to get a case-insensitive check for "autosize". Looking for an example to point to.

Comment (rraustad) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: We should not propogate this. Use getRealFieldValue instead. Plenty of examples.

Comment (mjwitte) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: So, this method is similar to [`EIRPlantLoopHeatPump::processInputForEIRPLHP`](https://github.com/NREL/EnergyPlus/blob/02282dbcc4999c8bfb1655b5c489fff7c94631b9/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L883-L896). Hmm, no autosized example for that component. But I see this pattern used in UnitarySystem, so it must work. Never mind.

Comment (rraustad) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: UnitarySystem will no longer use this method after I get time to clean it out.

Comment (mjwitte) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: @rraustad Don't bother with that. There are other epJSON input changes in the works.

Comment (mjwitte) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: Sorry for all of the chatter here, but just for the record and my own sanity, I see the IdfParser forces all variations of autosize or autocalculate to "Autosize" [here](https://github.com/NREL/EnergyPlus/blob/02282dbcc4999c8bfb1655b5c489fff7c94631b9/src/EnergyPlus/InputProcessing/IdfParser.cc#L620-L635) where the "anyof" enum value is coming from the schema, e.g.:
```
                        "maximum_total_cooling_capacity": {
                            "note": "This field is ignored if Cooling Limit = NoLimit",
                            "units": "W",
                            "anyOf": [
                                {
                                    "type": "number",
                                    "minimum": 0.0
                                },
                                {
                                    "type": "string",
                                    "enum": [
                                        "Autosize"
                                    ]
                                }
                            ]
                        },
```
Learned something new today.

Comment (amirroth) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: Me too! 

BTW, @mjwitte, that's called a TIL (today I learned). That's how the kids talk these days. I only discovered this in the past few months myself. I think from @jmarrec. Now you learned two things: this thing about epJSON and TIL. The second one is the very meta TIL TIL. It's a good day.

**Comment by Myoldmopar** [comment]
@tanaya-bigladder @nealkruis any chance you could comment on the conversation above to help push this toward completion?  I'd like to start making release candidates and this is one of the last pieces that should go in.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc (hunk 2 above)
Comment (nealkruis) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:160]: Yeah, this is not great. It's something we will address in a future version of Btwxt.

**Comment by nealkruis** [comment]
I don't have anything to add to this conversation other than that it will be nice when this fabled "other epJSON input changes in the works" arrives!

File: src/EnergyPlus/ChillerElectricASHRAE205.cc (hunk 5 above)
Comment (tanaya-mankad) [reply src/EnergyPlus/ChillerElectricASHRAE205.cc:277]: This exact change is one of those I pulled from Julien's branch, so I'm not sure what the best way to clean it up is (i.e. it will appear again).

**Comment by rraustad** [comment]
This seems OK for now. This is the same as used in UnitarySystem.

    if (fields.find("maximum_supply_air_temperature") != fields.end()) { // not required field, has default of 80 C
        auto tempFieldVal = fields.at("maximum_supply_air_temperature");
        if (tempFieldVal == "Autosize") {
            thisSys.input_specs.maximum_supply_air_temperature = DataSizing::AutoSize;
        } else {
            thisSys.input_specs.maximum_supply_air_temperature = fields.at("maximum_supply_air_temperature").get<Real64>();
        }
    }

**Comment by tanaya-mankad** [comment]
If we have today, I can update all the `fields.at()` calls to `getAlpha/RealFieldValue` calls - the best way was not 100% clear to me when we started this branch, and I'm sure Julien just corrected the buggy part of some of my calls without upgrading the calls themselves. I'm more than happy to make this canonical (at least until the Grand Unified Theory of epJSON inputs is proposed).

**Comment by mjwitte** [comment]
> If we have today, I can update all the `fields.at()` calls to `getAlpha/RealFieldValue` calls - the best way was not 100% clear to me when we started this branch, and I'm sure Julien just corrected the buggy part of some of my calls without upgrading the calls themselves. I'm more than happy to make this canonical (at least until the Grand Unified Theory of epJSON inputs is proposed).

No, that's not worth your time at this point. Let me do some quick tests to wrap this up.

**Comment by amirroth** [comment]
> I don't have anything to add to this conversation other than that it will be nice when this fabled "other epJSON input changes in the works" arrives!

They are not fabled. They are real and they will be presented and discussed shortly after the 22.2 release (first or second technicalities meeting). I will say that the more I think about them, the more confused I get about how we would actually use them within EnergyPlus. I sent @jasondegraw a series of questions describing the issues I foresee and he and @mbadams5 will address them during their presentation. Either way, I am optimistic that even if the "whole enchilada" approach is not practical that individual components of it would still dramatically simplify input processing.

File: src/EnergyPlus/ChillerElectricASHRAE205.cc [hunk 6]
```diff
@@ -151,9 +151,13 @@ void getChillerASHRAE205Input(EnergyPlusData &state)
...
         auto rep_file_name = ip->getAlphaFieldValue(fields, objectSchemaProps, "representation_file_name");
         fs::path rep_file_path = DataSystemVariables::CheckForActualFilePath(state, fs::path(rep_file_name), std::string(RoutineName));
+        if (rep_file_path.empty()) {
+            ErrorsFound = true;
+        }
         std::pair<EnergyPlusData *, std::string> callbackPair{&state,
                                                               format("{} \"{}\"", state.dataIPShortCut->cCurrentModuleObject, thisObjectName)};
         tk205::set_error_handler(tk205ErrCallback, &callbackPair);
+        Btwxt::LOG_LEVEL = static_cast<int>(Btwxt::MsgLevel::MSG_WARN);
         thisChiller.Representation =
```
Comment (mjwitte) [inline src/EnergyPlus/ChillerElectricASHRAE205.cc:161]: One remaining issue here, if the cbor file is not found, `rep_file_path.empty()` then this line throws an exception.
The err file looks like this:
```
   ** Severe  ** getChillerASHRAE205Input: "XYZCoolSys1-Chiller-Detailed.RS0001.a205.cbor" not found.
   **   ~~~   **   Paths searched:
   **   ~~~   **     Current Working Directory: "G:\My Drive\MJW Work-Network\Defect Test Files\9662-205Chiller\EPTEMP-00000001"
   **   ~~~   **     EnergyPlus Executable Directory: "C:\MJWGit\EnergyPlus-Review1\Build\Products\Debug"
   **   ~~~   **     "epin" Environment Variable: "G:\My Drive\MJW Work-Network\Defect Test Files\9662-205Chiller"
   **   ~~~   **     INI File Directory: "G:\My Drive\MJW Work-Network\Defect Test Files\9662-205Chiller\EPTEMP-00000001\Energy+.ini"
   **   ~~~   **     "program", "dir" from INI File: "C:\MJWGit\EnergyPlus-Review1\Build\EP-Launch-EnergyPlus-Review1-Debug"
   ** Severe  ** [json.exception.type_error.302] type must be string, but is null
```
That's enough info to fix the problem, but the exception should be avoided.
@Myoldmopar It's up to you if we want this fixed for release.

**Review by mjwitte — APPROVED** [review]
@tanaya-bigladder @Myoldmopar The input processing changes work as advertised. Bad node names generate a useful error message, and "autosize" works now without crashing.

**Comment by Myoldmopar** [comment]
> That's enough info to fix the problem, but the exception should be avoided.
> @Myoldmopar It's up to you if we want this fixed for release.

I was holding off for a little while to see if a fix appeared, but I think it's time.  I agree the exception should be avoided, but it's not the end of the world given that the severe does come out first.  I may end up doing a small fix for this in my final 22.2 branch, but for now I'll just leave it.  Thanks for reviewing this @mjwitte and @rraustad.  Merging this in now.
