### PR TITLE
Fixing some clear_state issues

### LINKED ISSUE #8138: Python `clear_all_states` function missing
`cClearAllStates` is implemented in the C API, but it isn't exposed through the Python bindings.

Add these lines to the Runtime constructor in runtime.py:
```
self.api.cClearAllStates.argtypes = []
self.api.cClearAllStates.restype = c_void_p
```

Then add a member function to call it:
```
def clear_all_states(self):
    self.api.cClearAllStates()
```

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
 - Fixes #8138 
 - This exposes the `cClearAllStates` function in the Python bindings and fixes some static variable usage in the code.  This won't fix all the static variable problems, as there are still many, but I don't want to let this PR get huge and conflict.

### CODE REVIEW

File: src/EnergyPlus/BaseboardElectric.cc [hunk 1]
```diff
@@ -102,12 +102,11 @@ namespace BaseboardElectric {
         using General::TrimSigDigits;
 
         int BaseboardNum;               // index of unit in baseboard array
-        static bool GetInputFlag(true); // one time get input flag
         Real64 QZnReq;                  // zone load not yet satisfied
 
-        if (GetInputFlag) {
+        if (state.dataBaseboardElectric.getInputFlag) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/BaseboardElectric.cc:107]: Use the `state` get input flag instead of a static local.

File: src/EnergyPlus/BaseboardRadiator.cc [hunk 2]
```diff
@@ -137,17 +137,16 @@ namespace BaseboardRadiator {
...
-        static bool GetInputFlag(true); // one time get input flag
         Real64 QZnReq;                  // zone load not yet satisfied
         Real64 MaxWaterFlow;
         Real64 MinWaterFlow;
         Real64 DummyMdot;
 
         auto &baseboard = state.dataBaseboardRadiator;
 
-        if (GetInputFlag) {
+        if (baseboard.getInputFlag) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/BaseboardRadiator.cc:147]: Use the `state` get input flag instead of a static local.

File: src/EnergyPlus/BaseboardRadiator.cc [hunk 3]
```diff
@@ -282,7 +281,7 @@ namespace BaseboardRadiator {
         int NumAlphas;
         int NumNums;
         int IOStat;
-        static bool ErrorsFound(false); // If errors detected in input
+        bool ErrorsFound(false); // If errors detected in input
```
Comment (Myoldmopar) [inline src/EnergyPlus/BaseboardRadiator.cc:284]: This just never needed to be static, it's a local variable.

File: src/EnergyPlus/BaseboardRadiator.cc [hunk 4]
```diff
@@ -524,10 +523,7 @@ namespace BaseboardRadiator {
         // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
         int WaterInletNode;
         int ZoneNode;
-        static bool MyOneTimeFlag(true);
```
Comment (Myoldmopar) [inline src/EnergyPlus/BaseboardRadiator.cc:527]: Moved some flags to the member struct so we didn't need to allocate anything in here, and we didn't need a static in here anymore.

File: src/EnergyPlus/BaseboardRadiator.cc [hunk 5]
```diff
@@ -609,11 +598,11 @@ namespace BaseboardRadiator {
             if (baseboard.Baseboard(BaseboardNum).AirMassFlowRate <= 0.0) {
                 baseboard.Baseboard(BaseboardNum).AirMassFlowRate = 2.0 * baseboard.Baseboard(BaseboardNum).WaterMassFlowRateMax;
             }
-            MyEnvrnFlag(BaseboardNum) = false;
+            baseboard.Baseboard(BaseboardNum).MyEnvrnFlag = false;
         }
 
         if (!BeginEnvrnFlag) {
-            MyEnvrnFlag(BaseboardNum) = true;
+            baseboard.Baseboard(BaseboardNum).MyEnvrnFlag = true;
```
Comment (Myoldmopar) [inline src/EnergyPlus/BaseboardRadiator.cc:605]: Many thousands of percent better.  Or maybe not that much.  But still nice.

File: src/EnergyPlus/EarthTube.cc [hunk 6]
```diff
@@ -533,12 +534,8 @@ namespace EarthTube {
         Real64 AirMassFlowRate;      // Actual Mass Flow Rate of Air inside Pipe
         Real64 AirSpecHeat;          // Specific Heat of Air
         Real64 AirDensity;           // Density of Air
-        static Array1D<Real64> EVF;  // DESIGN EARTHTUBE FLOW RATE (M**3/SEC)
 
-        // Allocate the EVF array
-        if (!allocated(EVF)) EVF.allocate(NumOfZones);
-
-        EVF = 0.0;
+        Real64 EVF;
```
Comment (Myoldmopar) [inline src/EnergyPlus/EarthTube.cc:538]: EVF never needed to be allocated, it is really just used as a scalar variable.

File: src/EnergyPlus/EvaporativeCoolers.cc [hunk 7]
```diff
@@ -154,7 +154,7 @@ namespace EvaporativeCoolers {
         // These are purposefully not in the header file as an extern variable. No one outside of this should
         // use these. They are cleared by clear_state() for use by unit tests, but normal simulations should be unaffected.
         // This is purposefully in an anonymous namespace so nothing outside this implementation file can use it.
-        bool InitEvapCoolerMyOneTimeFlag(true);
+        bool MySetPointCheckFlag(true);
```
Comment (Myoldmopar) [inline src/EnergyPlus/EvaporativeCoolers.cc:157]: Just pulled a single variable up to the global space for convenience and to get rid of the static quickly.

File: src/EnergyPlus/General.cc [hunk 8]
```diff
@@ -3219,7 +3224,6 @@ namespace General {
         static std::string VarDictOption2;
         //  LOGICAL,SAVE :: SchRpt = .FALSE.
         //  CHARACTER(len=MaxNameLength) :: SchRptOption
-        static bool GetReportInput(true);
```
Comment (Myoldmopar) [inline src/EnergyPlus/General.cc:3222]: There are other statics in here, but they appear to be controlled fully by the value of this flag, so I pulled this one out.

File: src/EnergyPlus/HVACMultiSpeedHeatPump.cc [hunk 9]
```diff
@@ -218,7 +218,33 @@ namespace HVACMultiSpeedHeatPump {
...
+        SaveLoadResidual = 0.0;
+        SaveCompressorPLR = 0.0;
+        CheckEquipName.clear();
+        MSHeatPump.clear();
+        MSHeatPumpReport.clear();
+        GetInputFlag = true; // Get input flag
+        FlowFracFlagReady = true;
+        ErrCountCyc = 0;
+        ErrCountVar = 0;
+    }
```
Comment (Myoldmopar) [inline src/EnergyPlus/HVACMultiSpeedHeatPump.cc:247]: Pulled a bunch of variables out from statics and added a clear_state.  Seriously how are there still files without clear state.  Crazy.

File: src/EnergyPlus/HVACMultiSpeedHeatPump.cc [hunk 10]
```diff
@@ -1790,13 +1813,6 @@ namespace HVACMultiSpeedHeatPump {
         int OutNode;                          // Outlet node number in MSHP loop
         int ZoneInNode;                       // Zone inlet node number in the controlled zone for MSHP
         Real64 RhoAir;                        // Air density at InNode
-        static bool MyOneTimeFlag(true);      // Initialization flag
-        static Array1D_bool MyEnvrnFlag;      // Used for initializations each begin environment flag
-        static Array1D_bool MySizeFlag;       // Used for sizing MSHP inputs one time
-        static Array1D_bool MyCheckFlag;      // Used to obtain the zone inlet node number in the controlled zone
-        static Array1D_bool MyFlowFracFlag;   // Used for calculatig flow fraction once
-        static Array1D_bool MyPlantScantFlag; // used for finding on heat recovery plant loop
-        static Array1D_bool MyStagedFlag;     // used for finding on staged thermostat
```
Comment (Myoldmopar) [inline src/EnergyPlus/HVACMultiSpeedHeatPump.cc:1799]: Pulled a _bunch_ of static arrays into the main component struct.  Eliminated all statics in here.

File: src/EnergyPlus/Photovoltaics.cc [hunk 11]
```diff
@@ -131,20 +131,12 @@ namespace Photovoltaics {
...
-    // The following subroutines and functions are used for only the EQUIVALENT ONE-DIODE model
-
-    // The following subroutines and functions are used for the Sandia model.
-
-    //  OO get set methods for coupling to exterior vented baffle cavity mounting configurations
-
-    // *************
-
-    // Functions
+    void clear_state() {
```
Comment (Myoldmopar) [inline src/EnergyPlus/Photovoltaics.cc:136]: Another static get input flag, another new clear state.

File: src/EnergyPlus/StateManagement.cc [hunk 12]
```diff
@@ -332,6 +341,7 @@ void EnergyPlus::clearAllStates(OutputFiles &outputFiles)
     OutputReportTabularAnnual::clear_state();
     OutsideEnergySources::clear_state();
     PackagedTerminalHeatPump::clear_state();
+    Photovoltaics::clear_state();
```
Comment (Myoldmopar) [inline src/EnergyPlus/StateManagement.cc:344]: 5 new clear_states added and called from the state reset manager.  And there are still more I'm sure.

File: src/EnergyPlus/api/runtime.py [hunk 13]
```diff
@@ -389,6 +391,14 @@ def callback_unitary_system_sizing(self, f: FunctionType) -> None:
         all_callbacks.append(cb_ptr)
         self.api.callbackUnitarySystemSizing(cb_ptr)
 
+    def clear_all_states(self) -> None:
```
Comment (Myoldmopar) [inline src/EnergyPlus/api/runtime.py:394]: This is where this all started, somehow this function never made it to the Python bindings.

File: tst/EnergyPlus/api/TestRuntime.c [hunk 14]
```diff
@@ -99,24 +99,24 @@ void errorHandler(const char * message) {
...
+//    callbackEndOfZoneTimeStepBeforeZoneReporting(EndOfZoneTimeStepBeforeZoneReportingHandler);
+//    callbackEndOfZoneTimeStepAfterZoneReporting(EndOfZoneTimeStepAfterZoneReportingHandler);
+//    callbackEndOfSystemTimeStepBeforeHVACReporting(EndOfSystemTimeStepBeforeHVACReportingHandler);
+//    callbackEndOfSystemTimeStepAfterHVACReporting(EndOfSystemTimeStepAfterHVACReportingHandler);
+//    callbackEndOfZoneSizing(EndOfZoneSizingHandler);
+//    callbackEndOfSystemSizing(EndOfSystemSizingHandler);
+//    callbackEndOfAfterComponentGetInput(EndOfAfterComponentGetInputHandler);
+//    callbackUnitarySystemSizing(UnitarySystemSizingHandler);
+//    registerProgressCallback(progressHandler);
+//    registerErrorCallback(errorHandler);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/api/TestRuntime.c:119]: Hushing up a bunch of messages, may revert this, not sure.

**Review by Myoldmopar — COMMENTED** [review]
So I wouldn't have been surprised if there were diffs in the MSHP because I made the biggest changes there.  One set of diffs in the GPU file seems suspicious.  Am I behind develop?

**Comment by Myoldmopar** [comment]
The SolarShading diffs are showing up in other places now, so that's not related to this one.  Anyone care to discuss this or review or merge?

**Review by mitchute — APPROVED** [review]
No problems from me. This all looks standard/straightforward. Feel free to merge.

**Comment by Myoldmopar** [comment]
I'll take it, thanks!
