### PR TITLE
Address 24.2 EMPD Issue

### LINKED ISSUE #10777: Segfault with MoisturePenetrationDepth
Issue overview
--------------

An OpenStudio-resources regression test that uses MoisturePenetrationDepth:

* Was working on 24.1.0
* Fails when transitioned to 24.2.0 (There is **ZERO** difference between the two files, aside from the `Version` object)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 24.04
 - Version of EnergyPlus (if using an intermediate build, include SHA): v24.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] #10780
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
 - Fixes #10777 

Most of the conversation can be found [here](https://github.com/NREL/EnergyPlus/issues/10777#issuecomment-2391655066), but basically, there was an incorrect check that let an invalid configuration pass before 24.2, accidentally segfaulted in 24.2.0, and now fails gracefully (in 24.2.1+).

I don't expect any diffs or failures, so if there are any, this won't be ready.  If it's all green, I think it's good to go.

### CODE REVIEW

File: src/EnergyPlus/MoistureBalanceEMPDManager.cc [hunk 1]
```diff
@@ -249,9 +249,9 @@ void GetMoistureBalanceEMPDInput(EnergyPlusData &state)
 
         auto const &constr = state.dataConstruction->Construct(surf.Construction);
         auto const *mat = dynamic_cast<const MaterialEMPD *>(s_mat->materials(constr.LayerPoint(constr.TotLayers)));
-        assert(mat != nullptr);
+        // assert(mat != nullptr);
```
Comment (Myoldmopar) [inline src/EnergyPlus/MoistureBalanceEMPDManager.cc:252]: The way things are structured now, it's totally fine for this to result in a nullptr.  If the material doesn't have any EMPD properties, that's fine.  So we shouldn't do a hard assertion.

File: src/EnergyPlus/MoistureBalanceEMPDManager.cc [hunk 2]
```diff
@@ -249,9 +249,9 @@ void GetMoistureBalanceEMPDInput(EnergyPlusData &state)
...
 
-        if (mat->mu > 0.0 && surf.Zone > 0) {
+        if (mat && mat->mu > 0.0 && surf.Zone > 0) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/MoistureBalanceEMPDManager.cc:254]: Instead, let's just check that mat is real before accessing it.  This will properly pass if the inside layer has EMPD stuff. And it will properly result in a warning message if the layer does not have EMPD stuff.  This works happily now.

**Review by Myoldmopar — COMMENTED** [review]
If CI is clean, this should be fine to drop in and we can start getting 24.2.1 out.

**Comment by Myoldmopar** [comment]
@jmarrec if you update your test to handle this graceful failure, let me know how it goes.

@amirroth your code indeed causes the test to fail now.  As it should have all along!  So thanks for that.  I'm happy to handle any comments you have on my changes here.

**Comment by Myoldmopar** [comment]
Everything is happy here.  OK, merging this and tagging v24.2.1-RC1.

Sorry about this, and thanks for reporting it, @jmarrec

File: src/EnergyPlus/MoistureBalanceEMPDManager.cc (hunk 2 above)
Comment (jmarrec) [reply src/EnergyPlus/MoistureBalanceEMPDManager.cc:254]: Just curious, why not not the hasEMPD boolean? isn't what it's for?
