### PR TITLE
Fix #11181 - Wrong Sunlit fractions for Detached Shading Surfaces when Sun is Down

### LINKED ISSUE #11181: Sunlit fractions for PV surfaces
While comparing Surface Sunlit Fraction across different surface types, I’m seeing physically impossible values for Shading:* surfaces and PV-panel host surfaces (used by Generator:Photovoltaic). Specifically: During timesteps when the sun is below the horizon (Site Solar Altitude Angle < 0 and Site Sun Is Up = 0), Surface Sunlit Fraction for Shading:* and PV surfaces is non-zero and sometimes exceeds 1.0.

Image

In the same timesteps, Surface Sunlit Fraction for BuildingSurface:Detailed and FenestrationSurface:Detailed is correctly 0.0.

Image

 

### Operating System (Multiple choices)

Windows

### Operating System Version

11

### Version of EnergyPlus

23

### Unmethours link or helpdesk ticket number

N/A

### Defect file

File to reproduce the issue:
[Shoebox.idf.txt](https://github.com/user-attachments/files/22031821/Shoebox.idf.txt)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix #11181 

Some solar shading arrays are not cleared.

### Description of the purpose of this PR

The issue with #11181 was that the arrays were NOT being cleared for the detached shading surfaces, so the previous values were retained when the Sun was down, because FigureSolarBeamAtTimestep returns early in that case

Original regression appeared in v9.6.0, and is due to https://github.com/NREL/EnergyPlus/pull/8820
Specifically the commit, the change in SolarShading.cc https://github.com/NREL/EnergyPlus/commit/c10a756a4fe766999e79518aac927105853c67f7#diff-18fbb8a5b1334b62513de2441bdb4bb4ef1fbe5fbec24d5dd0effcd019dfc33dR4795

Before, the ObjexxFCL assignment was used to reset everything this commit changed the initialization to explicit loop variables, BUT it does it only for heat transfer surfaces linked to a zone/space, and no longer does it for detached shading surfaces.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by jmarrec** [comment]
Running the Shoebox_v25.1.idf from DevSupport.

before fix, see https://github.com/NREL/EnergyPlus/issues/11181#issuecomment-3338703721

After fix:

image

**Comment by jmarrec** [comment]
Side by side comparison for Shoebox v25.1.idf

image

File: src/EnergyPlus/SolarShading.cc [hunk 1]
```diff
@@ -4918,78 +4918,73 @@ void CalcPerSolarBeam(EnergyPlusData &state,
 
     // Initialize some values for the appropriate period
     if (!state.dataSysVars->DetailedSolarTimestepIntegration) {
-        for (int zoneNum = 1; zoneNum <= state.dataGlobal->NumOfZones; ++zoneNum) {
-            for (int spaceNum : state.dataHeatBal->Zone(zoneNum).spaceIndexes) {
-                auto &thisSpace = state.dataHeatBal->space(spaceNum);
-                int firstSurf = thisSpace.OpaqOrIntMassSurfaceFirst;
-                int lastSurf = thisSpace.OpaqOrIntMassSurfaceLast;
```
Comment (jmarrec) [inline src/EnergyPlus/SolarShading.cc:4925]: This was only doing it for attached building surfaces

File: src/EnergyPlus/SolarShading.cc [hunk 2]
```diff
@@ -4918,78 +4918,73 @@ void CalcPerSolarBeam(EnergyPlusData &state,
...
+        // Array4D
+        for (int hour = 1; hour <= 24; ++hour) {
+            for (int timestep = 1; timestep <= state.dataGlobal->TimeStepsInHour; ++timestep) {
                 for (int backSurfNum = 1; backSurfNum <= state.dataBSDFWindow->MaxBkSurf; ++backSurfNum) {
-                    for (int surfNum = firstSurf; surfNum <= lastSurf; ++surfNum) {
-                        state.dataHeatBal->SurfWinBackSurfaces(state.dataGlobal->HourOfDay, state.dataGlobal->TimeStep, backSurfNum, surfNum) = 0;
-                        state.dataHeatBal->SurfWinOverlapAreas(state.dataGlobal->HourOfDay, state.dataGlobal->TimeStep, backSurfNum, surfNum) = 0.0;
+                    for (int surfNum = 1; surfNum <= state.dataSurface->TotSurfaces; ++surfNum) {
+                        state.dataHeatBal->SurfWinBackSurfaces(hour, timestep, backSurfNum, surfNum) = 0.0;
+                        state.dataHeatBal->SurfWinOverlapAreas(hour, timestep, backSurfNum, surfNum) = 0.0;
```
Comment (jmarrec) [inline src/EnergyPlus/SolarShading.cc:4958]: Do it for all arrays, keeping the explicit init instead of relying (like pre v9.6.0) on ObjexxFCL assign functors

File: src/EnergyPlus/SolarShading.cc [hunk 3]
```diff
@@ -4918,78 +4918,73 @@ void CalcPerSolarBeam(EnergyPlusData &state,
...
+            state.dataHeatBal->SurfSunlitFracWithoutReveal(state.dataGlobal->HourOfDay, state.dataGlobal->TimeStep, surfNum) = 0.0;
+            state.dataHeatBal->SurfCosIncAng(state.dataGlobal->HourOfDay, state.dataGlobal->TimeStep, surfNum) = 0.0;
+        }
+
+        // Array4D
+        for (int backSurfNum = 1; backSurfNum <= state.dataBSDFWindow->MaxBkSurf; ++backSurfNum) {
+            for (int surfNum = 1; surfNum <= state.dataSurface->TotSurfaces; ++surfNum) {
+                state.dataHeatBal->SurfWinBackSurfaces(state.dataGlobal->HourOfDay, state.dataGlobal->TimeStep, backSurfNum, surfNum) = 0;
+                state.dataHeatBal->SurfWinOverlapAreas(state.dataGlobal->HourOfDay, state.dataGlobal->TimeStep, backSurfNum, surfNum) = 0.0;
+            }
```
Comment (jmarrec) [inline src/EnergyPlus/SolarShading.cc:4987]: Same idea when DetailedSolarTimestepIntegration is on

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 4]
```diff
@@ -173,6 +173,218 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CalcPerSolarBeamTest)
...
+TEST_F(EnergyPlusFixture, SolarShadingTest_CalcPerSolarBeamTestResetsFrac)
+{
+    // Test for #11181 - Test inits for integrated and non-integrated shading calcs, including for DETACHED shading surfaces
+    // We are going to mimic the case where we have two surfaces:
+    // 1) A surface part a zone
+    // 2) A detached or building shading surface, not part of any zone
+    //
+    // We also assume we are in a case where we're starting a new environment, and the SurfSunlitFrac is already filled with numbers
+    // The issue with #11181 was that the arrays were NOT being cleared for the detached shading surfaces, so the previous values were retained when
+    // the Sun was down, because FigureSolarBeamAtTimestep returns early in that case
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:185]: New explicit test.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 5]
```diff
@@ -173,6 +173,218 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CalcPerSolarBeamTest)
...
+    // Ensure we have sun is Up working properly
+    for (int hour = 1; hour <= Constant::iHoursInDay; ++hour) {
+        for (int timestep = 1; timestep <= state->dataGlobal->TimeStepsInHour; ++timestep) {
+            if (isSunUp(hour, timestep)) {
+                EXPECT_GT(state->dataBSDFWindow->SUNCOSTS(timestep, hour).z, 0.0);
+            } else {
+                EXPECT_LT(state->dataBSDFWindow->SUNCOSTS(timestep, hour).z, 0.0);
+            }
+        }
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:309]: We prefill the arrays with some values (0.5 all around).

Then we call CalcPerSolarBeam.

I create a lambda that checks if the sun is up, and ensure it works like I expect it to. It does.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 6]
```diff
@@ -173,6 +173,218 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CalcPerSolarBeamTest)
...
+                    EXPECT_DOUBLE_EQ(1.0, state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)) << "Failed when Sun is Up";
+                } else {
+                    EXPECT_DOUBLE_EQ(0.0, state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)) << "Failed when Sun is Down";
+                }
+            }
+
+            EXPECT_EQ(1.0, state->dataSurface->SurfaceWindow(surfNum).OutProjSLFracMult[hour]);
+            EXPECT_EQ(1.0, state->dataSurface->SurfaceWindow(surfNum).InOutProjSLFracMult[hour]);
+        }
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:333]: It will fail a bunch on develop, when the SunIsDown, and only for the DETACHED shading surface.

```
[ RUN      ] EnergyPlusFixture.SolarShadingTest_CalcPerSolarBeamTestResetsFrac
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:319: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFracHR(hour, surfNum)
    Which is: 0.5
Failed when Sun is Down
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:315: Hour=1
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:313: Surface 2='SHADING'
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:326: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)
    Which is: 0.5
Failed when Sun is Down
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:322: Timestep=1
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:315: Hour=1
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:313: Surface 2='SHADING'
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:326: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)
    Which is: 0.5
Failed when Sun is Down
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:322: Timestep=2
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:315: Hour=1
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:313: Surface 2='SHADING'
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:326: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)
    Which is: 0.5
Failed when Sun is Down
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:322: Timestep=3
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:315: Hour=1
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:313: Surface 2='SHADING'
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:326: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)
    Which is: 0.5
Failed when Sun is Down
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:322: Timestep=4
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:315: Hour=1
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:313: Surface 2='SHADING'
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:319: Failure

[...]

```

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 7]
```diff
@@ -173,6 +173,218 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CalcPerSolarBeamTest)
...
+            for (int timestep = 1; timestep <= state->dataGlobal->TimeStepsInHour; ++timestep) {
+                SCOPED_TRACE(fmt::format("Timestep={}", timestep));
+                if (hour == state->dataGlobal->HourOfDay && timestep == state->dataGlobal->TimeStep) {
+                    EXPECT_DOUBLE_EQ(0.0, state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum));
+                } else {
+                    EXPECT_DOUBLE_EQ(0.5, state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum));
+                }
+            }
+        }
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:373]: Another pass with DetailedTimeStepIntegration. It fails as well for the shading surface on develop

```
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:358: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFracHR(hour, surfNum)
    Which is: 0.5
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:354: Hour=23
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:352: Surface 2='SHADING'
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:367: Failure
Expected equality of these values:
  0.0
    Which is: 0
  state->dataHeatBal->SurfSunlitFrac(hour, timestep, surfNum)
    Which is: 0.5
Google Test trace:
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:365: Timestep=3
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:354: Hour=23
/home/julien/Software/Others/EnergyPlus2/tst/EnergyPlus/unit/SolarShading.unit.cc:352: Surface 2='SHADING'
[  FAILED  ] EnergyPlusFixture.SolarShadingTest_CalcPerSolarBeamTestResetsFrac (1065 ms)
```

**Comment by jmarrec** [comment]
ExerciseOutput1 / ExerciseOutput1A have expected changes

image

Mir-Overhang is now properly working like the roof as we expect.

Left is develop, right is this branch. I am plotting a "regular" surface then the changed ones

image

**Review by mitchute — APPROVED** [review]
This all looks reasonable.
