### PR TITLE
Fix table min/max normalization

### LINKED ISSUE #7576: Warning in WaterToAirHeatPumpVariableSpeed when using Table:Lookup with Divisor
Issue overview
--------------

I'm having trouble following the new Table:Lookup object.

I'm getting this error:
```
   ** Warning ** GetVarSpeedCoilInput: Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit="COIL COOLING WATER TO AIR HEAT PUMP VARIABLE SPEED EQUATION FIT 68", curve values
   **   ~~~   ** ...Speed 2 Total Cooling Capacity Function of Temperature Curve Name output is not equal to 1.0 (+ or - 10%) at rated conditions.
   **   ~~~   ** ...Curve output at rated conditions = 6.095
```

If I track down the object:
```
Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit,
  Coil Cooling Water To Air Heat Pump Variable Speed Equation Fit 68, !- Name
  [...]
  Table Multi Variable Lookup 13,         !- Speed Total Cooling Capacity Function of Temperature Curve Name 2
```

Here are the revelant Table:Lookup and Table:IndependentVariable objects:

```
Table:Lookup,
  Table Multi Variable Lookup 13,         !- Name
  Table Multi Variable Lookup 13_IndependentVariableList, !- Independent Variable List Name
  DivisorOnly,                            !- Normalization Method
  8.630943895,                            !- Normalization Divisor
  6.09587888,                             !- Minimum Output {BasedOnField A4}
  11.34185157,                            !- Maximum Output {BasedOnField A4}
  Power,                                  !- Output Unit Type
  ,                                       !- External File Name
  ,                                       !- External File Column Number
  ,                                       !- External File Starting Row Number
  9.49550364,                             !- Output Value 1 {BasedOnField A4}
  9.14381832,                             !- Output Value 2 {BasedOnField A4}
  8.70421167,                             !- Output Value 3 {BasedOnField A4}
  8.17668369,                             !- Output Value 4 {BasedOnField A4}
  7.56123438,                             !- Output Value 5 {BasedOnField A4}
  6.88717085,                             !- Output Value 6 {BasedOnField A4}
  6.09587888,                             !- Output Value 7 {BasedOnField A4}
  10.43333116,                            !- Output Value 8 {BasedOnField A4}
  10.02303162,                            !- Output Value 9 {BasedOnField A4}
  9.55411786,                             !- Output Value 10 {BasedOnField A4}
  8.96797566,                             !- Output Value 11 {BasedOnField A4}
  8.29391213,                             !- Output Value 12 {BasedOnField A4}
  7.53192727,                             !- Output Value 13 {BasedOnField A4}
  6.68202108,                             !- Output Value 14 {BasedOnField A4}
  11.34185157,                            !- Output Value 15 {BasedOnField A4}
  10.90224492,                            !- Output Value 16 {BasedOnField A4}
  10.37471694,                            !- Output Value 17 {BasedOnField A4}
  9.75926763,                             !- Output Value 18 {BasedOnField A4}
  9.02658988,                             !- Output Value 19 {BasedOnField A4}
  8.2059908,                              !- Output Value 20 {BasedOnField A4}
  7.26816328;                             !- Output Value 21 {BasedOnField A4}
Table:IndependentVariableList,
  Table Multi Variable Lookup 13_IndependentVariableList, !- Name
  Table Multi Variable Lookup 13_IndependentVariable_0, !- Independent Variable Name 1
  Table Multi Variable Lookup 13_IndependentVariable_1; !- Independent Variable Name 2
Table:IndependentVariable,
  Table Multi Variable Lookup 13_IndependentVariable_0, !- Name
  Cubic,                                  !- Interpolation Method
  Linear,                                 !- Extrapolation Method
  17.2222222222222,                       !- Minimum Value {BasedOnField A4}
  21.6666666666667,                       !- Maximum Value {BasedOnField A4}
  ,                                       !- Normalization Reference Value {BasedOnField A4}
  Temperature,                            !- Unit Type
  ,                                       !- External File Name
  ,                                       !- External File Column Number
  ,                                       !- External File Starting Row Number
  17.2222222222222,                       !- Value 1
  19.4444444444444,                       !- Value 2
  21.6666666666667;                       !- Value 3
Table:IndependentVariable,
  Table Multi Variable Lookup 13_IndependentVariable_1, !- Name
  Cubic,                                  !- Interpolation Method
  Linear,                                 !- Extrapolation Method
  10,                                     !- Minimum Value {BasedOnField A4}
  43.3333333333333,                       !- Maximum Value {BasedOnField A4}
  ,                                       !- Normalization Reference Value {BasedOnField A4}
  Temperature,                            !- Unit Type
  ,                                       !- External File Name
  ,                                       !- External File Column Number
  ,                                       !- External File Starting Row Number
  10,                                     !- Value 1
  15.5555555555556,                       !- Value 2
  21.1111111111111,                       !- Value 3
  26.6666666666667,                       !- Value 4
  32.2222222222222,                       !- Value 5
  37.7777777777778,                       !- Value 6
  43.3333333333333;                       !- Value 7
```

I don't get why this warning is thrown, based on the I/O ref guide there: https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-performance-tables.html#field-normalization-method

> DivisorOnly: Normalize the output using only the value entered into the Normalization Divisor field, below.
> **Normalization applies to the Output Value fields as well as the Minimum and Maximum Output fields.**

Seems like the Divisor isn't applied.

### Details
Some additional details for this issue (if relevant):
 - Platform: Ubuntu
 - Version of EnergyPlus: 9.2.0
 - Unmethours link or helpdesk ticket number: N/A

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7576
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by ajscimone**
Pull request overview
---------------------
 - Fixes #7576 
 - This pull request fixes normalization behavior at the minimum and maximum values in a Table:Lookup object. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Is there a defect file that can be used to test/verify this?

**Comment by nealkruis** [comment]
@Myoldmopar This came from @jmarrec. He might be willing to share the file. I'm going to work with @ajscimone to get this ready for someone else on the team to review.

**Comment by jmarrec** [comment]
@Myoldmopar the issue (#7576) has the link to the Defectfile I added on Energyplusdevsupport: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7576

**Comment by nrel-bot-2b** [comment]
@ajscimone @lgentile it has been 28 days since this pull request was last updated.

**Comment by nealkruis** [comment]
@Myoldmopar @mjwitte @jmarrec This is ready for review.

File: src/EnergyPlus/CurveManager.cc [hunk 1]
```diff
@@ -2088,11 +2087,19 @@ namespace CurveManager {
                         ErrorsFound = true;
                     } else if (pointsSpecified) {
                         // normalizeGridValues normalizes to 1.0 at the reference values. We must redivide by passing in the 1.0/normalizationDivisor as the scalar here.
```
Comment (jmarrec) [inline src/EnergyPlus/CurveManager.cc]: Comment should probably be updated to match.

File: src/EnergyPlus/CurveManager.cc [hunk 2]
```diff
@@ -2088,11 +2087,19 @@ namespace CurveManager {
...
-                        btwxtManager.normalizeGridValues(gridIndex, PerfCurve(CurveNum).GridValueIndex, normalizeTarget, 1.0/normalizationDivisor);
+                        normalizationDivisor = btwxtManager.normalizeGridValues(gridIndex, PerfCurve(CurveNum).GridValueIndex, normalizeTarget, normalizationDivisor)*normalizationDivisor;
                     }
+                }
 
-              }
+                // Perform Divisor Normalization for methods: NM_DIVISOR_ONLY || NM_AUTO_WITH_DIVISOR
+                PerfCurve(CurveNum).NormalizationValue = normalizationDivisor;
 
+                if ((normalizeMethod == NM_DIVISOR_ONLY && PerfCurve(CurveNum).CurveMaxPresent) || (normalizeMethod == NM_AUTO_WITH_DIVISOR && PerfCurve(CurveNum).CurveMaxPresent)){
```
Comment (jmarrec) [inline src/EnergyPlus/CurveManager.cc]: Avoid potentially evaluating `CurveMaxPresent` twice. I'm choosing to evaluate the enum first since it's local... perhaps it'd be faster the other way around.

```c++
if ( ((normalizeMethod == NM_DIVISOR_ONLY) || (normalizeMethod == NM_AUTO_WITH_DIVISOR)) && PerfCurve(CurveNum).CurveMaxPresent )
```

File: src/EnergyPlus/CurveManager.cc [hunk 3]
```diff
@@ -2088,11 +2087,19 @@ namespace CurveManager {
...
+                    PerfCurve(CurveNum).CurveMax = PerfCurve(CurveNum).CurveMax / normalizationDivisor;
+                }
+                if ((normalizeMethod == NM_DIVISOR_ONLY && PerfCurve(CurveNum).CurveMinPresent) || (normalizeMethod == NM_AUTO_WITH_DIVISOR && PerfCurve(CurveNum).CurveMinPresent)){
```
Comment (jmarrec) [inline src/EnergyPlus/CurveManager.cc]: Same here, and should actually be merged into a block after checking normalizeMethod to avoid redoing it for nothing.

```c++
if ((normalizeMethod == NM_DIVISOR_ONLY) || (normalizeMethod == NM_AUTO_WITH_DIVISOR)) {
   if (PerfCurve(CurveNum).CurveMaxPresent) {
       PerfCurve(CurveNum).CurveMax = PerfCurve(CurveNum).CurveMax / normalizationDivisor
   } 
   if (PerfCurve(CurveNum).CurveMinPresent) {
       PerfCurve(CurveNum).CurveMin = PerfCurve(CurveNum).CurveMin / normalizationDivisor
  }
}
```

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 4]
```diff
@@ -76,13 +75,575 @@ TEST_F(EnergyPlusFixture, CurveExponentialSkewNormal_MaximumCurveOutputTest)
         "  1.;                      !- Maximum Curve Output",
     });
 
+    //documentation input output reference should tell me how to plot this equation
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc]: Leftover comment? 

Also, see https://github.com/NREL/EnergyPlus/pull/7666#issuecomment-581361460

**Review by jmarrec — COMMENTED** [review]
From a rapid sweep (checking it out out of curiosity), this looks good and with detailed tests too!

I'm leaving just some minor cosmetic comments, will leave thorough review for Mike or Edwin.

File: tst/EnergyPlus/unit/CurveManager.unit.cc (hunk 4 above)
Comment (ajscimone) [reply tst/EnergyPlus/unit/CurveManager.unit.cc]: Yes, this is a leftover commend. Good catch, thank you!

File: src/EnergyPlus/CurveManager.cc (hunk 1 above)
Comment (ajscimone) [reply src/EnergyPlus/CurveManager.cc]: Hi Julien. Can you elaborate on this? The above comment on line 2090 is new, I added it to help explain what is happening with the line below it. Hopefully it helps clarify the math behind multiplying by the normalizationDivsor inside of the calculation to reset it.

File: src/EnergyPlus/CurveManager.cc (hunk 3 above)
Comment (ajscimone) [reply src/EnergyPlus/CurveManager.cc]: Hi Julien. I agree that this looks like a better evaulation method. I have changed the code to match.

File: src/EnergyPlus/CurveManager.cc (hunk 1 above)
Comment (jmarrec) [reply src/EnergyPlus/CurveManager.cc]: I'm seeing the comment as existing:

image


Also, before it was indeed passing 1.0/normalizationDivisor below, now it does not.

image

Comment (ajscimone) [reply src/EnergyPlus/CurveManager.cc]: You are correct, I thought that I had changed this comment, but it appears that it did not make it in. I'm sorry for the confusion, thanks for clarifying. It is updated to be more descriptive now.

**Comment by mjwitte** [comment]
@ajscimone I'm reviewing this. Please merge in develop and push for a final CI round.

**Comment by ajscimone** [comment]
@mjwitte Develop merged and pushed. Thank you!

File: src/EnergyPlus/CurveManager.cc [hunk 5]
```diff
@@ -433,7 +434,7 @@ namespace CurveManager {
         NumBicubic = inputProcessor->getNumObjectsFound("Curve:Bicubic");
         NumTriQuad = inputProcessor->getNumObjectsFound("Curve:Triquadratic");
         NumExponent = inputProcessor->getNumObjectsFound("Curve:Exponent");
-        int NumTableLookup = inputProcessor->getNumObjectsFound("Table:Lookup");
+        NumTableLookup = inputProcessor->getNumObjectsFound("Table:Lookup");
```
Comment (mjwitte) [inline src/EnergyPlus/CurveManager.cc:437]: Nit-picking, but we're trying to move away from declaring variables loose at the top of functions. Prefer what was here. And even better, change the lines nearby to declare here instead of above. If there aren't any other changes required, then this can stay as-is. But noting this for future reference.

File: src/EnergyPlus/CurveManager.cc [hunk 6]
```diff
@@ -2087,12 +2086,23 @@ namespace CurveManager {
                         ShowContinueError("    b) no normalization reference values are defined.");
                         ErrorsFound = true;
                     } else if (pointsSpecified) {
-                        // normalizeGridValues normalizes to 1.0 at the reference values. We must redivide by passing in the 1.0/normalizationDivisor as the scalar here.
-                        btwxtManager.normalizeGridValues(gridIndex, PerfCurve(CurveNum).GridValueIndex, normalizeTarget, 1.0/normalizationDivisor);
+                        // normalizeGridValues normalizes curve values to 1.0 at the normalization target, and returns the scalar needed to perform this normalization.
+                        // The result is multiplied by the input normalizationDivisor again for the AutomaticWithDivisor case, in which normalizeGridValues returns a compound scalar.
+                        normalizationDivisor = btwxtManager.normalizeGridValues(gridIndex, PerfCurve(CurveNum).GridValueIndex, normalizeTarget, normalizationDivisor)*normalizationDivisor;
```
Comment (mjwitte) [inline src/EnergyPlus/CurveManager.cc:2091]: Seeing `normalizationDivisor` in three places on this line is rather confusing. Not clear why `normalizationDivisor` is an argument to `normalizeGridValues`, but I guess it works here.

File: third_party/btwxt/src/gridpoint.cpp [hunk 7]
```diff
@@ -294,15 +294,19 @@ void GridPoint::normalize_grid_values_at_target(const double scalar) {
...
-void GridPoint::normalize_grid_values_at_target(std::size_t table_num, const double scalar) {
+double GridPoint::normalize_grid_values_at_target(std::size_t table_num, const double scalar) {
   if (!target_is_set) {
     showMessage(MsgLevel::MSG_WARN,
                 stringify("Cannot normalize grid values. No target has been set."));
-    return;
+    return scalar;
   }
-  grid_data->normalize_value_table(table_num,results[table_num]*scalar);
+  // create a scalar which represents the product of the inverted normalization factor and the value in the table at the independent variable reference value
```
Comment (mjwitte) [inline third_party/btwxt/src/gridpoint.cpp:303]: Is it "inverted"? Not seeing where that happens.

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 8]
```diff
@@ -82,7 +81,567 @@ TEST_F(EnergyPlusFixture, CurveExponentialSkewNormal_MaximumCurveOutputTest)
...
+
+    EXPECT_TRUE(CurveManager::PerfCurve(1).CurveMaxPresent);
+    EXPECT_EQ(expected_curve_max, CurveManager::PerfCurve(1).CurveMax);
+
+    for (auto data_point : table_data ){
+        EXPECT_DOUBLE_EQ(data_point.first*data_point.second/expected_auto_divisor, CurveManager::CurveValue(1, data_point.first, data_point.second));
+    }
+}
+
+TEST_F(EnergyPlusFixture, NormalizationAutomaticWithDivisorAndSpecifiedDivisor)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:544]: A thorough set of unit tests.

File: src/EnergyPlus/CurveManager.cc (hunk 6 above)
Comment (mjwitte) [reply src/EnergyPlus/CurveManager.cc:2091]: After drilling down into the function layers, I see `total_scalar = results[table_num]*scalar;` [here in `GridPoint::normalize_grid_values_at_target`](https://github.com/NREL/EnergyPlus/blob/7f9be5852220488a0808f0ab9270f8f6eb1c913a/third_party/btwxt/src/gridpoint.cpp#L304)

If `total_scalar` is the product of the auto-normalization divisor and the incoming `scalar`, then it seems that `btwxtManager.normalizeGridValues` doesn't need to be multiplied again by `normalizationDivisor` here.

**Review by mjwitte — COMMENTED** [review]
Ran defect file before/after (which crashes, by the way, in debug builds with a divide by zero in the ventilation adjustments, unrelated to this PR) with release build and the warnings are gone.

Even though I have some questions/comments about the code, it seems to work as advertised.
Also ran the unit tests locally.
Will wait for all CI tests to complete before merging.

File: src/EnergyPlus/CurveManager.cc (hunk 5 above)
Comment (ajscimone) [reply src/EnergyPlus/CurveManager.cc:437]: That sounds good, I went back and forth on whether to choose the better coding practice versus the existing style. If any additional changes are required, I will hot fix that back to initializing during declaration.

File: third_party/btwxt/src/gridpoint.cpp (hunk 7 above)
Comment (ajscimone) [reply third_party/btwxt/src/gridpoint.cpp:303]: I think the comment here might be confusing you, and rightly so since it starts to become difficult to talk about the scalars inside of btwxt. Lets start by saying that the scalar here exists as it was entered. For example in the `NormalizationAutomaticWithDivisorAndSpecifiedDivisor` unit test, where the normalization divisor is 4, what is returned in `GridPoint::normalize_grid_values_at_target` is 4.

With that being said, btwxt is looking for that scalar to be inverted (e.g. 1.0/scalar). Before the update to btwxt inside this bug fix, we actually relied on the user to input the scalar this way: `btwxtManager.normalizeGridValues(gridIndex, PerfCurve(CurveNum).GridValueIndex, normalizeTarget, 1.0/normalizationDivisor);`
It's much easier on the user to just let them pass in their normalization divisor, so I did away with this. However, now inside of btwxt, what I am calling the "inverted divisor" is really the one that the user entered. Does that make sense? From the btwxt library user's perspective, the scalar is normal here. From btwxt's perspective, it is inverted.

File: tst/EnergyPlus/unit/CurveManager.unit.cc (hunk 8 above)
Comment (ajscimone) [reply tst/EnergyPlus/unit/CurveManager.unit.cc:544]: Thank you! We felt it was needed since this normalization math can start to become confusing pretty quickly.

File: src/EnergyPlus/CurveManager.cc (hunk 6 above)
Comment (nealkruis) [reply src/EnergyPlus/CurveManager.cc:2091]: @mjwitte The issue here is that the data going into btwxt has already been normalized by the divisor when lookupValues is set (around line 2059). Btwxt then does the autonormalization for the target based on the normalized results, then applies the scalar.

For example, for a single table value of 6 at the normalization target and a user-divisor of 3:
- The value is normalized by the user-divisor when it is read in: 6/3 = 2
- The value is then autonormalized to 1 in Btwxt making the auto-divisor = 2
- Btwxt then applies the user-divisor passed into the `normalizeGridValues` function: 1/3 = 0.333
- `normalizeGridValues` then returns its auto-divisor times the user-divisor: 2*3 = 6
- The actual divisor (between user input and the value used in Btwxt) is: 6/0.333 = 18
- To get to the actual divisor from what Btwxt returns you need to multiply the value from `normalizeGridValues` by the user-divisor: 18 = 6*3

I know this is convoluted, and maybe there is a better way to go about it by adding more functionality to btwxt, but there are complications related to when the btwxt objects are created and when normalization is performed.

Would it help to include this description in the comment?

File: third_party/btwxt/src/gridpoint.cpp (hunk 7 above)
Comment (mjwitte) [reply third_party/btwxt/src/gridpoint.cpp:303]: *Does that make sense?* To be honest, no, but I'll just accept that it works.

File: src/EnergyPlus/CurveManager.cc (hunk 6 above)
Comment (mjwitte) [reply src/EnergyPlus/CurveManager.cc:2091]: @nealkruis "The issue here is that the data going into btwxt has already been normalized by the divisor when lookupValues is set (around line 2059)." Ah, that's the key. That prior normalization seems premature, but so be it. Not holding this up for that. But if you make any other changes to this, a comment here that points to the earlier normalization would help. Or, better yet, seems it would be more clear to skip the earlier normalization and do it here.

**Review by mjwitte — APPROVED** [review]
CI is clean.
