### PR TITLE
Fix #10830 - incorrect curve unit type warning

### LINKED ISSUE #10830: Piping Correction Factor for Length Independent Variable Unit Type is Incorrect
Issue overview
--------------
In the object AirConditioner:VariableRefrigerantFlow, fields:

_41 !- Piping Correction Factor for Length in Cooling Mode Curve Name
44 !- Piping Correction Factor for Length in Heating Mode Curve Name_

point to a curve or lookup table.  Per the Input/Output reference (https://bigladdersoftware.com/epx/docs/24-2/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-piping-correction-factor-for-length-in-cooling-mode-curve-name) the input (independent variable) for these curves should be in units of length.

When unit type "Distance"

  _Table:IndependentVariable,
...
    Distance,                !- Unit Type_

is specified for these curves, EnergyPlus produces the following error:

**** Severe  ** Table:IndependentVariable "TBL LOOKUP P72TNU/YNU_PCFC_FN_L-INPUT_0": Unit Type [Distance] is invalid**

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) Windows 11
 - Version of EnergyPlus (if using an intermediate build, include SHA)  24.2
 - Unmethours link or helpdesk ticket number

Inputting a unit type of "Dimensionless" for this field will eliminate the error.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here) 
[in (2).txt](https://github.com/user-attachments/files/17838230/in.2.txt)

 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #10830 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/CurveManager.cc [hunk 1]
```diff
@@ -2297,7 +2299,7 @@ namespace Curve {
                         // TODO: Actually use this to define output variable units
                         if (indVarInstance.count("unit_type")) {
                             std::string unitType = indVarInstance.at("unit_type").get<std::string>();
-                            if (!IsCurveOutputTypeValid(unitType)) {
+                            if (!IsCurveInputTypeValid(unitType)) {
```
Comment (jmarrec) [inline src/EnergyPlus/CurveManager.cc:2356]: Specific fix for #10830 is here

File: src/EnergyPlus/CurveManager.cc [hunk 2]
```diff
@@ -798,8 +800,8 @@ namespace Curve {
                 }
             }
             if (NumAlphas >= 4) {
-                if (!IsCurveOutputTypeValid(Alphas(4))) {
-                    ShowWarningError(state, format("In {} named {} the OInput Unit Type for Z is invalid.", CurrentModuleObject, Alphas(1)));
+                if (!IsCurveInputTypeValid(Alphas(4))) {
+                    ShowWarningError(state, format("In {} named {} the Input Unit Type for Z is invalid.", CurrentModuleObject, Alphas(1)));
```
Comment (jmarrec) [inline src/EnergyPlus/CurveManager.cc:835]: Noticed another mistake here in Curve:ChillerPartLoadWithLift

File: src/EnergyPlus/CurveManager.cc [hunk 3]
```diff
@@ -2953,10 +2955,21 @@ namespace Curve {
             Distance,
             Wavelength,
             Angle,
+            VolumetricFlowPerPower,
```
Comment (jmarrec) [inline src/EnergyPlus/CurveManager.cc:3012]: Add Missing Input Type VolumetricFlowPerPower: used by Curve:QuadLinear &  Curve:QuintLinear

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 4]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+    const auto &object_schema = schema_properties.at(objectType);
+    auto const &schema_obj_props = getPatternProperties(object_schema);
+    auto const &schema_field_obj = schema_obj_props.at(fieldName);
+    std::vector<std::string> choices;
+    for (const auto &e : schema_field_obj.at("enum")) {
+        choices.push_back(e);
+    }
+
+    return choices;
+}
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:784]: Mine the json schema for the choices

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 5]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+        }
+    }
+    auto const &schema_obj_props = pattern_properties[pattern_property]["properties"];
+    return schema_obj_props;
+}
+
+std::vector<std::string> getPossibleChoicesFromSchema(const std::string &objectType, const std::string &fieldName)
+{
+    // Should consider making this public, at least to the EnergyPlusFixture, but maybe in the InputProcessor directly
+    // At which point, should handle the "anyOf" case, here I don't need it, so not bothering
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:772]: note

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 6]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+}
+
+TEST_F(EnergyPlusFixture, TableIndependentVariableUnitType_IsValid)
+{
+    std::vector<std::string> unit_type_choices = getPossibleChoicesFromSchema("Table:IndependentVariable", "unit_type");
+    for (const auto &input_unit_type : unit_type_choices) {
+        EXPECT_TRUE(Curve::IsCurveInputTypeValid(input_unit_type)) << input_unit_type << " is rejected by IsCurveInputTypeValid";
+    }
+    EXPECT_EQ(8, unit_type_choices.size());
+}
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:793]: Ensure it's valid

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 7]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+{
+    std::vector<std::string> unit_type_choices = getPossibleChoicesFromSchema("Table:Lookup", "output_unit_type");
+    for (const auto &output_unit_type : unit_type_choices) {
+        if (output_unit_type.empty()) {
+            continue;
+        }
+        EXPECT_TRUE(Curve::IsCurveOutputTypeValid(output_unit_type)) << output_unit_type << " is rejected by IsCurveOutputTypeValid";
+    }
+    EXPECT_EQ(6, unit_type_choices.size());
+}
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:805]: Same for TableLookup output.

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 8]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+        "  0.714,                     !- Minimum Value",
+        "  1.2857,                    !- Maximum Value",
+        "  ,                          !- Normalization Reference Value",
+        fmt::format("  {},             !-  Unit Type", unit_type),
+        "  ,                          !- External File Name",
+        "  ,                          !- External File Column Number",
+        "  ,                          !- External File Starting Row Number",
+        "  0.714286,                  !- Value 1",
+        "  1.0,",
+        "  1.2857;",
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:828]: Parametrized test

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 9]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+        "  1.0,",
+        "  1.1256;",
+    });
+
+    ASSERT_TRUE(process_idf(idf_objects));
+    EXPECT_EQ(0, state->dataCurveManager->NumCurves);
+
+    Curve::GetCurveInput(*state);
+    state->dataCurveManager->GetCurvesInputFlag = false;
+    EXPECT_TRUE(compare_err_stream("", true));
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:855]: That calls GetCurveInput specifically. That exhibits the issue where IsValidCurveInput is true, but it's IsValidCurveOUTPUT that's called by mistake

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 10]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+
+INSTANTIATE_TEST_SUITE_P(CurveManager,
+                         InputUnitTypeIsValid,
+                         testing::Values("", "Angle", "Dimensionless", "Distance", "MassFlow", "Power", "Temperature", "VolumetricFlow"),
+                         [](const testing::TestParamInfo<InputUnitTypeIsValid::ParamType> &info) -> std::string {
+                             if (info.param.empty()) {
+                                 return "Blank";
+                             }
+                             return std::string{info.param};
+                         });
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:866]: Instantiate the param tests... I could have used testing::ValuesIn(container) instead to make it fully dynamic but didn't

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 11]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+
+class OutputUnitTypeIsValid : public EnergyPlusFixture, public ::testing::WithParamInterface<std::string_view>
+{
+};
+TEST_P(OutputUnitTypeIsValid, TableLookup)
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:871]: Same stuff with TableLookup output unit type

File: tst/EnergyPlus/unit/CurveManager.unit.cc [hunk 12]
```diff
@@ -742,3 +744,233 @@ TEST_F(EnergyPlusFixture, CSV_CarriageReturns_Handling)
...
+        EXPECT_TRUE(Curve::IsCurveInputTypeValid(input_unit_type)) << input_unit_type << " is rejected by IsCurveOutputTypeValid";
+    }
+
+    for (const auto &output_unit_type : all_output_choices) {
+        if (output_unit_type.empty()) {
+            continue;
+        }
+        EXPECT_TRUE(Curve::IsCurveOutputTypeValid(output_unit_type)) << output_unit_type << " is rejected by IsCurveOutputTypeValid";
+    }
+}
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/CurveManager.unit.cc:978]: Dynamic test that collates ALL possible input/output unit types by mining the schema for all curve objects and tests that IsCurve<In/Out>putTypeValid is ok. It wasn't for VolumetricFlowPerPower

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jmarrec it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
OK, something just struck me as I was looking through your new parameterized tests.  I recalled our macro that actually parses through looking for unit tests to add as ctest entries with `add_test()`.  Unfortunately it looks like the ctest run isn't getting them.  Look here, and please correct me if I'm just making a silly mistake:

```
$ ctest -R InputUnitTypeIsValid
Test project /eplus/repos/2eplus/builds/r
No tests were found!!!

$ ./Products/energyplus_tests --gtest_filter="*InputUnitTypeIsValid*"
Note: Google Test filter = *InputUnitTypeIsValid*
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from CurveManager/InputUnitTypeIsValid
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Blank
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Blank (121 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Angle
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Angle (42 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Dimensionless
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Dimensionless (39 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Distance
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Distance (39 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/MassFlow
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/MassFlow (38 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Power
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Power (39 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Temperature
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/Temperature (39 ms)
[ RUN      ] CurveManager/InputUnitTypeIsValid.IndepentVariable/VolumetricFlow
[       OK ] CurveManager/InputUnitTypeIsValid.IndepentVariable/VolumetricFlow (39 ms)
[----------] 8 tests from CurveManager/InputUnitTypeIsValid (399 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test suite ran. (399 ms total)
[  PASSED  ] 8 tests.
```

The code that sets up the ctest entries is [here](https://github.com/NREL/EnergyPlus/blob/6fe61270cb6684215a4ebf9d1b766ac3973793fd/cmake/ProjectMacros.cmake#L3-L16), with specifically this section in question:

```
  string(REGEX MATCHALL "TEST_?F?\\(([A-Za-z_0-9 ,]+)\\)" found_tests ${contents})
  foreach(hit ${found_tests})
    string(REGEX REPLACE ".*\\(( )*([A-Za-z_0-9]+)( )*,( )*([A-Za-z_0-9]+)( )*\\).*" "\\2.\\5" test_name ${hit})
    add_test(NAME ${test_name} COMMAND "${executable}" "--gtest_filter=${test_name}")
  endforeach(hit)
```

It is looking for `TEST` or `TEST_F`.  I added a `P?` in the regex, and it found 3 more tests but not 8.  It looks like it needs some love to more intelligently find tests.  Or maybe there is a more modern way to do this?  I do like that the tests show up as individual tests in `ctest` rather than one enormous call to `energyplus_tests` so that it is easy to `ctest -j 31` the whole thing.  

I'm not inclined to hold this up to solve that, but I would like to solve it soon.  Let me know if you have any thoughts.

**Comment by Myoldmopar** [comment]
Oh, and anyway, your tests do pass.  So this is good.  I'll push the resolved commit and get this merged.  Thanks @jmarrec
