### PR TITLE
Fixes source side sizing calculation for HeatPump:PlantLoop:EIR:Heating issue

### LINKED ISSUE #10381: Source side sizing calculation for HeatPump:PlantLoop:EIR:Heating is incorrect
Issue overview
--------------
While reviewing the `sizeSrcSideASHP()` function code for another task I see incorrect capacity and flow rate calculation for source side. 

The current code uses the same equation for the `HeatPump:PlantLoop:EIR:Heating` or `HeatPump:PlantLoop:EIR:Cooling` coils [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L1102) and shown below:

`Real64 const designSourceSideHeatTransfer = tmpCapacity * (1 + 1 / this->referenceCOP);`

 But the above equation is applicable for `HeatPump:PlantLoop:EIR:Cooling` only.  I think the formulation of the equation must be dependent on the coil type as shown below:

        Real64 designSourceSideHeatTransfer = 0.0;
        if (this->EIRHPType == DataPlant::PlantEquipmentType::HeatPumpEIRHeating) {
            designSourceSideHeatTransfer = tmpCapacity * (1 - 1 / this->referenceCOP);
        } else {
            designSourceSideHeatTransfer = tmpCapacity * (1 + 1 / this->referenceCOP);
        } 
 
 The same change is required for the water source HP as well in [sizeSrcSideWSHP()](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L990) function.
 
 

 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus ([sha](https://github.com/NREL/EnergyPlus/commit/0c0cdaa269e7b5939c46b710f4dbdef68db8fdac))

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #10381
 - Corrected the source-side flow rate sizing calculation for `HeatPump:PlantLoop:EIR:Heating` Coils. This change impacts the `Source Side Reference Flow Rate` field only when it is auto-sized. The fix results in lower source side flow rate for   `AirSource` and `WaterSource` condenser types. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 1]
```diff
@@ -514,7 +514,7 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
                                                            thisLoadPlantLoop.FluidName,
                                                            state.dataLoopNodes->Node(this->loadSideNodes.inlet).Temp,
                                                            thisLoadPlantLoop.FluidIndex,
-                                                           "PLHPEIR::simulate()");
+                                                           "EIRPlantLoopHeatPump::doPhysics()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:517]: Updated function names used as an argument in several places.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 2]
```diff
@@ -580,7 +580,7 @@ void EIRPlantLoopHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
     if (this->waterSource) {
         auto &thisSourcePlantLoop = state.dataPlnt->PlantLoop(this->sourceSidePlantLoc.loopNum);
         CpSrc = FluidProperties::GetSpecificHeatGlycol(
-            state, thisSourcePlantLoop.FluidName, this->sourceSideInletTemp, thisSourcePlantLoop.FluidIndex, "PLHPEIR::simulate()");
+            state, thisSourcePlantLoop.FluidName, this->sourceSideInletTemp, thisSourcePlantLoop.FluidIndex, "EIRPlantLoopHeatPump::doPhysics()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:583]: Updated function names used as an argument.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 3]
```diff
@@ -702,12 +702,12 @@ void EIRPlantLoopHeatPump::sizeLoadSide(EnergyPlusData &state)
...
                                                    loadSideInitTemp,
                                                    state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidIndex,
-                                                   "EIRPlantLoopHeatPump::size()");
+                                                   "EIRPlantLoopHeatPump::sizeLoadSide()");
     Real64 Cp = FluidProperties::GetSpecificHeatGlycol(state,
                                                        state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidName,
                                                        loadSideInitTemp,
                                                        state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidIndex,
-                                                       "EIRPlantLoopHeatPump::size()");
+                                                       "EIRPlantLoopHeatPump::sizeLoadSide()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:710]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 4]
```diff
@@ -735,13 +735,13 @@ void EIRPlantLoopHeatPump::sizeLoadSide(EnergyPlusData &state)
...
                         state.dataPlnt->PlantLoop(compLoopNum).FluidIndex,
-                        "EIRPlantLoopHeatPump::size()");
+                        "EIRPlantLoopHeatPump::sizeLoadSide()");
                     compCp = FluidProperties::GetSpecificHeatGlycol(
                         state,
                         state.dataPlnt->PlantLoop(compLoopNum).FluidName,
                         this->EIRHPType == DataPlant::PlantEquipmentType::HeatPumpEIRCooling ? Constant::HWInitConvTemp : Constant::CWInitConvTemp,
                         state.dataPlnt->PlantLoop(compLoopNum).FluidIndex,
-                        "EIRPlantLoopHeatPump::size()");
+                        "EIRPlantLoopHeatPump::sizeLoadSide()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:744]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 5]
```diff
@@ -735,13 +735,13 @@ void EIRPlantLoopHeatPump::sizeLoadSide(EnergyPlusData &state)
...
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:738]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 6]
```diff
@@ -790,12 +790,12 @@ void EIRPlantLoopHeatPump::sizeLoadSide(EnergyPlusData &state)
                                                                              state.dataPlnt->PlantLoop(compLoopNum).FluidName,
                                                                              compLoadSideInitTemp,
                                                                              state.dataPlnt->PlantLoop(compLoopNum).FluidIndex,
-                                                                             "EIRPlantLoopHeatPump::size()");
+                                                                             "EIRPlantLoopHeatPump::sizeLoadSide()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:793]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 7]
```diff
@@ -790,12 +790,12 @@ void EIRPlantLoopHeatPump::sizeLoadSide(EnergyPlusData &state)
...
                     Real64 const compCp = FluidProperties::GetSpecificHeatGlycol(state,
                                                                                  state.dataPlnt->PlantLoop(compLoopNum).FluidName,
                                                                                  Constant::CWInitConvTemp,
                                                                                  state.dataPlnt->PlantLoop(compLoopNum).FluidIndex,
-                                                                                 "EIRPlantLoopHeatPump::size()");
+                                                                                 "EIRPlantLoopHeatPump::sizeLoadSide()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:798]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 8]
```diff
@@ -969,12 +969,12 @@ void EIRPlantLoopHeatPump::sizeSrcSideWSHP(EnergyPlusData &state)
                                                             state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidName,
                                                             sourceSideInitTemp,
                                                             state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidIndex,
-                                                            "EIRPlantLoopHeatPump::size()");
+                                                            "EIRPlantLoopHeatPump::sizeSrcSideWSHP()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:972]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 9]
```diff
@@ -969,12 +969,12 @@ void EIRPlantLoopHeatPump::sizeSrcSideWSHP(EnergyPlusData &state)
...
     Real64 const CpSrc = FluidProperties::GetSpecificHeatGlycol(state,
                                                                 state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidName,
                                                                 sourceSideInitTemp,
                                                                 state.dataPlnt->PlantLoop(this->loadSidePlantLoc.loopNum).FluidIndex,
-                                                                "EIRPlantLoopHeatPump::size()");
+                                                                "EIRPlantLoopHeatPump::sizeSrcSideWSHP()");
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:977]: The same change here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 10]
```diff
@@ -987,7 +987,12 @@ void EIRPlantLoopHeatPump::sizeSrcSideWSHP(EnergyPlusData &state)
         // First the definition of COP: COP = Qload/Power, therefore Power = Qload/COP
         // Then the energy balance:     Qsrc = Qload + Power
         // Substituting for Power:      Qsrc = Qload + Qload/COP, therefore Qsrc = Qload (1 + 1/COP)
-        Real64 const designSourceSideHeatTransfer = tmpCapacity * (1 + 1 / this->referenceCOP);
+        Real64 designSourceSideHeatTransfer = 0.0;
+        if (this->EIRHPType == DataPlant::PlantEquipmentType::HeatPumpEIRHeating) {
+            designSourceSideHeatTransfer = tmpCapacity * (1 - 1 / this->referenceCOP);
+        } else {
+            designSourceSideHeatTransfer = tmpCapacity * (1 + 1 / this->referenceCOP);
+        }
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: For the heating coil, the source side design capacity is basically the evaporator capacity (heat transfer). Derivation of the above equation for heating coil leads to `minus` sign. The previous equation is valid for cooling coil only. This fix is for water-source HP.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 11]
```diff
@@ -1099,7 +1104,12 @@ void EIRPlantLoopHeatPump::sizeSrcSideASHP(EnergyPlusData &state)
...
```
Comment (Nigusse) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1112]: This change is the same as the previous, but for the air-source HP.

**Review by Nigusse — COMMENTED** [review]
Code changes walk through:
- source side capacity and fluid flow rate calc changed for the heating coil only
- cleaned up function names as an argument in several places

**Comment by Nigusse** [comment]
Sample diffs. Only the heating coil source side flow rate was impacted as expected.

```
Component Sizing Information, Pump:VariableSpeed, HEATSYS1 PUMP, Design Power Consumption [W], 12547.22436
  Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Nominal Capacity [W], 3583772.55507
  Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Load Side Volume Flow Rate [m3/s], 0.11637
- Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Source Side Volume Flow Rate [m3/s], 408.24654
+ Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Source Side Volume Flow Rate [m3/s], 198.35115
  Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_2 HEATING SIDE, Design Size Nominal Capacity [W], 3583772.55507
  Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_2 HEATING SIDE, Design Size Load Side Volume Flow Rate [m3/s], 0.11637
- Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_2 HEATING SIDE, Design Size Source Side Volume Flow Rate [m3/s], 408.24654
+ Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_2 HEATING SIDE, Design Size Source Side Volume Flow Rate [m3/s], 198.35115
```

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 10 above)
Comment (rraustad) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: This should be `tmpCapacity / (1 + 1 / this->referenceCOP)` for heating. I tried both ways and don't get the same answer.

designSourceSideHeatTransfer = Hcap * (1 - 1/COP) = 1000 * (1 - 1/3) = 667
designSourceSideHeatTransfer = Hcap / (1 + 1/COP) = 1000 / (1 + 1/3) = 750

And as a test, if the cooling and heating EIR HP capacity is hardsized and the heating capacity is 1 + 1/COP the size of the cooling capacity (and the COPs are the same), then the autosized load side water flow rate on the cooling EIR HP should be the same size as the autosized source side water flow rate of the heating EIR HP.

Comment (Nigusse) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: The above formulations are based on the first-law energy balance equations and COP definition as shown below: 

`Qcond = Qevap + Power; COPc = Qevap / Power; COPh = Qcond / Power`

You can derive them from these three equations. The heat transfer should not be the same even if the COP are equal because the heat transfer at the condenser includes the power input while the heat transfer at the evaporator doesn't.

Comment (rraustad) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: Ah, that's what I was missing, the COPs are different:

COPh = COPc * (1 + 1/COPc) = 3 * (1 + 1/3) = 4  <-- is this COP conversion correct?

designSourceSideHeatTransfer = Hcap * (1 - 1/COPh) = 1000 * (1 - 1/4) = 750
designSourceSideHeatTransfer = Ccap * (1 + 1/COPc) = 750 * (1 + 1/3) = 1000

I think there are places where the divide by (1 + 1/COP) is used. Maybe those are wrong also.

**Comment by Nigusse** [comment]
Diffs are expected only if the `HeatPump:PlantLoop:EIR:Heating` has its `Source Side Reference Flow Rate` input field set to `autosize`.

**Comment by Nigusse** [comment]
The two example files shown below are expected to have diffs:
```
 PlantLoopHeatPump_EIR_LargeOffice-2-AWHP-AuxBoiler-Pri-Sec-4PipeBeam.idf
 PlantLoopHeatPump_EIR_Large-Office-2-AWHP-DedHR-AuxBoiler-Pri-Sec-HW.idf 
```

**Comment by Nigusse** [comment]
Modified three unit tests failed due to this fix.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 10 above)
Comment (Nigusse) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: The correct relationship is COPh = COPc + 1.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 12]
```diff
@@ -868,7 +870,7 @@ TEST_F(EnergyPlusFixture, TestSizing_FullyAutosizedCoolingWithCompanion_WaterSou
     thisCoolingPLHP->loadSideDesignVolFlowRate = expectedLoadFlow;
     thisCoolingPLHP->sourceSideDesignVolFlowRate = expectedSourceFlow;
     thisCoolingPLHP->referenceCapacity = expectedCapacity;
-    Real64 const designSourceSideHeatTransfer = expectedCapacity * (1 + 1 / thisHeatingPLHP->referenceCOP);
+    Real64 const designSourceSideHeatTransfer = expectedCapacity * (1 - 1 / thisHeatingPLHP->referenceCOP);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:873]: For heating coil, the source side heat transfer calc expression updated to match the correct expression in the code.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 13]
```diff
@@ -2647,13 +2647,16 @@ TEST_F(EnergyPlusFixture, TestSizing_FullyAutosizedCoolingWithCompanion_AirSourc
...
     state->dataPlnt->PlantLoop(1).PlantSizNum = 1;
 
+    Real64 const sourceSideInitTemp = 20.0;
+    Real64 const sourceSideHumRat = 0.0;
     Real64 expectedLoadCp = 4197.93;
     Real64 expectedLoadRho = 999.898;
-    Real64 expectedSourceCp = 1004.0;
-    Real64 expectedSourceRho = 1.2;
+    Real64 expectedSourceCp = Psychrometrics::PsyCpAirFnW(sourceSideHumRat);
+    Real64 expectedSourceRho = Psychrometrics::PsyRhoAirFnPbTdbW(*state, state->dataEnvrn->StdBaroPress, sourceSideInitTemp, sourceSideHumRat);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:2655]: Needed to match the sizing calculation assumptions to remove diffs.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 14]
```diff
@@ -2688,7 +2691,7 @@ TEST_F(EnergyPlusFixture, TestSizing_FullyAutosizedCoolingWithCompanion_AirSourc
     thisCoolingPLHP->sourceSideDesignVolFlowRate = expectedSourceFlow;
     thisCoolingPLHP->referenceCapacity = expectedCapacity;
     expectedCapacity = expectedLoadRho * expectedLoadFlow * expectedLoadCp * plantSizingLoadDeltaT;
-    expectedSourceLoad = expectedCapacity * (1 + 1 / COP);
+    expectedSourceLoad = expectedCapacity * (1 - 1 / thisHeatingPLHP->referenceCOP);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:2694]: For heating coil, the source side heat transfer calc expression updated to match the correct expression in the code.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 15]
```diff
@@ -2854,7 +2857,7 @@ TEST_F(EnergyPlusFixture, TestSizing_AutosizedFlowWithCompanion_AirSource)
                                                       "  0.005,",
                                                       "  Autosize,",
                                                       "  Autosize,",
-                                                      "  1.0,",
+                                                      "  2.0,",
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:2860]: Changed the heating coil `COP` to `2.0` from `1.0` to avoid `zero` source side flow rate.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 16]
```diff
@@ -2925,7 +2928,7 @@ TEST_F(EnergyPlusFixture, TestSizing_AutosizedFlowWithCompanion_AirSource)
     thisHeatingPLHP->onInitLoopEquip(*state, myHeatingLoadLocation);
 
     Real64 expectedClgSourceFlow = 86.71;
-    Real64 expectedHtgSourceFlow = 86.71;
+    Real64 expectedHtgSourceFlow = 21.68; // changed from 86.71 due to issue#10381;
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:2931]: The source side flow rate is now divided by 4 because of this fix and COP value assumption change.

**Review by Nigusse — COMMENTED** [review]
Modified failed unit tests.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 10 above)
Comment (Nigusse) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: The only places that needed to be changed were in source side sizing calculation functions: `sizeSrcSideASHP()` and `sizeSrcSideWSHP()`.

Comment (Nigusse) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: @rraustad I searched for `(1 + 1/COP)` and `(1.0 + 1.0 / this->referenceCOP)` but did not find any.

**Comment by Nigusse** [comment]
Uploaded defect file. 
[PLHP_EIR_AirSource_Issue10381.idf.txt](https://github.com/NREL/EnergyPlus/files/14086797/PLHP_EIR_AirSource_Issue10381.idf.txt)

**Comment by Nigusse** [comment]
Demonstration of change in `Source Side Reference Flow Rate` sizing calculation based on the attached defect file.

Develop:
```Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, HEATING COIL, Design Size Source Side Volume Flow Rate [m3/s], 8.69352```

Branch:
```Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, HEATING COIL, Design Size Source Side Volume Flow Rate [m3/s], 4.82974```

The ratio between these flow rates is `1.8 (= 8.69352/4.82974) or (= (1+1/COPh) / (1-1/COPh) = (1+1/3.5) / (1-1/3.5) ).`

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc (hunk 15 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:2860]: I have seen users set COP=1 on DX equipment for various reasons, mostly for ideal simulations. If a user sets COPh = 1 the new equation calculates 0 source heat transfer. If COPh < 1 then there is negative source side heat transfer and there would be heating on the load and source side. I'm not sure what that means or what the limit of COPh=1 represents other than non-DX equipment. If COPc = 1 you get twice the source heat transfer as the load side. It seems for an ideal run then COPh=2, as you have shown here. I am tempted to change all these COP limits in the idd to >=1 for cooling or >=2 for heating. Not for this issue but for clarity of operation for users.

    HeatPump:PlantLoop:EIR:Heating,
       N4,  \field Reference Coefficient of Performance
            \type real
            \minimum> 0.0
            \units W/W
            \default 3.0

**Comment by rraustad** [comment]
In the eio diffs I see that the source side volume flow rate did change due to your code correction so that's good. This is an air-source HP so the volume flow rates on the load and source side seem resonable (rho different by about 1000). I don't see any other issues.

      Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Load Side Volume Flow Rate [m3/s], 0.11637
    - Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Source Side Volume Flow Rate [m3/s], 408.24654
    + Component Sizing Information, HeatPump:PlantLoop:EIR:Heating, AWHP_1 HEATING SIDE, Design Size Source Side Volume Flow Rate [m3/s], 198.35115

**Review by rraustad — APPROVED** [review]
This change seems straight-forward and correct.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc (hunk 15 above)
Comment (Nigusse) [reply tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:2860]: If the heating coil (heating mode) design COPh is 1.0, it means the source side COPc is 0.0, i.e., there is no heat transfer at the evaporator coil. Also, it means the heat dissipated at the condenser is the same as the power input at the system (compressor). Can this operating condition be possible in the actual machine? To me, this implies the refrigeration cycle will not be complete; hence, it is not possible.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:517]: Good catch.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 10 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:995]: Thanks for working through this description, it's helpful.

**Review by Myoldmopar — APPROVED** [review]
This seems like a fine change.  I'll build and test locally.

**Comment by Myoldmopar** [comment]
I'm seeing only the same two regression diffs locally, and otherwise things are happy.  Merging this.  Thanks @Nigusse
