### PR TITLE
Fix Issue with Standard Ratings for Multi-Speed Coils

### LINKED ISSUE #10991: Flipped Parameters in Standard Ratings
### Issue overview

The various StandardRatings functions take both `CoilName` and `CoilType` as arguments, but take them in different orders. Half the functions take Name first and then Type, the others vice versa. As a result, in at least one callsite: 

https://github.com/NREL/EnergyPlus/blob/92df2f38cc3c4094086806b9724ae5b1e19e144e/src/EnergyPlus/StandardRatings.cc#L1278C1-L1282C125

the parameters are passed in reverse order than what is expected. Because the function determines whether this is a heating or cooling coil by searching for the string `"Cooling"` in `CoilType`, this effectively makes all ratings calculations for heating unless `CoilName` has the same string in it. 

This problem was discovered during the course of a refactor via diffs in the `EnergyPlusFixture.TestMultiSpeedCoilsAutoSizingOutput` unit test.

### Operating System (Multiple choices)

Any

### Operating System Version

Any

### Version of EnergyPlus

24.2.0

### Unmethours link or helpdesk ticket number

N/A

### Defect file

Unit test `EnergyPlusFixture.TestMultiSpeedCoilsAutoSizingOutput`.

### PR DESCRIPTION
**Pull request by amirroth**
This PR fixes issue #10991 and updates the associated unit test.

### CODE REVIEW

File: src/EnergyPlus/StandardRatings.cc [hunk 1]
```diff
@@ -1277,8 +1277,8 @@ namespace StandardRatings {
             }
             // Calculate the standard ratings for multispeed DX cooling coil
             std::map<std::string, Real64> StandardRatingsResult = MultiSpeedDXCoolingCoilStandardRatings(state,
-                                                                                                         DXCoilName,
                                                                                                          DXCoilType,
+                                                                                                         DXCoilName,
```
Comment (amirroth) [inline src/EnergyPlus/StandardRatings.cc:1281]: These parameters were flipped causing the routine to fail to recognize cooling coils as it was searching for the string `"Cooling"` in the coil name rather than the coil type.

**Comment by Myoldmopar** [comment]
This seems straightforward, anyone got any reason not to merge this in?

**Comment by Myoldmopar** [comment]
All happy with latest develop, let's get this in.  Thanks @amirroth
