### PR TITLE
Fixes #8372 - Incorrect transition of RoomAir:Node:AirflowNetwork:HVACEquipment from v9.2 to v9.3

### LINKED ISSUE #8372: Incorrect transition of RoomAir:Node:AirflowNetwork:HVACEquipment from v9.2 to v9.3
In EnergyPlus v9.3, class `AirTerminal:SingleDuct:Uncontrolled` has been converted to new class `AirTerminal:SingleDuct:ConstantVolume:NoReheat`. Looking through the corresponding transition code, I found that class `RoomAir:Node:AirflowNetwork:HVACEquipment` may not be treated correctly:

https://github.com/NREL/EnergyPlus/blob/74959091b81f488c791470fd5773fd24745aa2b4/src/Transition/CreateNewIDFUsingRulesV9_3_0.f90#L685-L702

The code above basically tries to append the original `AirTerminal:SingleDuct:Uncontrolled` node with suffix ` ATInlet` starting from 2nd field. However, according to IDD v9.2, the 2nd field is a choice field which can be `AirTerminal:SingleDuct:Uncontrolled`, and there is no way that any fields can be a node. The code above will do nothing if an `AirTerminal:SingleDuct:Uncontrolled` is referenced in Field 2 and Field 3.

```
#   1: Name
#   2: ZoneHVAC or Air Terminal Equipment Object Type 1
#   3: ZoneHVAC or Air Terminal Equipment Object Name 1
#   4: Fraction of Output or Supply Air from HVAC Equipment 1
#   5: Fraction of Input or Return Air to HVAC Equipment 1
#    ......
```

The proper way to transition this class is to follow the same logic as in the `ZoneHVAC:EquipmentList`:

https://github.com/NREL/EnergyPlus/blob/74959091b81f488c791470fd5773fd24745aa2b4/src/Transition/CreateNewIDFUsingRulesV9_3_0.f90#L473-L489

Hope above helps.

### Details

Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.2.0 to **9.3.0**

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file: https://github.com/NREL/EnergyPlusDevSupport/blob/ec4052601eebe20b3f9bf1bb59bd85866a9f5d53/DefectFiles/8000s/8372/RoomAirflowNetwork_mod.idf
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #8372
 - Incorrect transition of RoomAir:Node:AirflowNetwork:HVACEquipment from v9.2 to v9.3

The problem is due to how the move from `AirTerminal:SingleDuct:Uncontrolled` to `AirTerminal:SingleDuct:ConstantVolume:NoReheat` for this object.

## Testing 
See testing with https://github.com/NREL/EnergyPlusDevSupport/blob/ec4052601eebe20b3f9bf1bb59bd85866a9f5d53/DefectFiles/8000s/8372/RoomAirflowNetwork_mod.idf

### Before

```
./Transition-V9-2-0-to-V9-3-0 /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/8000s/8372/RoomAirflowNetwork_mod.idf
 Transition Starting
 Conversion 9.2 => 9.3
 Processing Old IDD -- V9-2-0-Energy+.idd
 Processing New IDD -- V9-3-0-Energy+.idd
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 F
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/8000s/8372/RoomAirflowNetwork_mod.idf
 ** Warning ** IP: IDF line~2883 Obsolete object=AirTerminal:SingleDuct:Uncontrolled, encountered.  Should be replaced with new object=AirTerminal:SingleDuct:ConstantVolume:NoReheat
 Processing IDF -- Processing idf objects . . .
At line 691 of file /home/julien/Software/Others/EnergyPlus/src/Transition/CreateNewIDFUsingRulesV9_3_0.f90
Fortran runtime error: Index '2' of dimension 1 of array 'atsdunodenames' above upper bound of 1

Error termination. Backtrace:
#0  0x489e7d in ???
#1  0x48a0b5 in ???
#2  0x48a487 in ???
#3  0x4184de in ???
#4  0x4029ac in ???
#5  0x40087e in ???
#6  0x4c0c48 in ???
#7  0x400e89 in ???
```

### After

```
 Transition Starting
 Conversion 9.2 => 9.3
 Processing Old IDD -- V9-2-0-Energy+.idd
 Processing New IDD -- V9-3-0-Energy+.idd
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 F
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/8000s/8372/RoomAirflowNetwork_mod.idf
 ** Warning ** IP: IDF line~2883 Obsolete object=AirTerminal:SingleDuct:Uncontrolled, encountered.  Should be replaced with new object=AirTerminal:SingleDuct:ConstantVolume:NoReheat
 Processing IDF -- Processing idf objects . . .
 Processing IDF -- Processing idf objects complete.
 ************* Conversion Completed Successfully-- 1 Warning; 0 Severe Errors
```

The resulting IDF has the correct transition of the RoomAir:Node:AirflowNetwork:HVACEquipment:

```diff
-RoomAir:Node:AirflowNetwork:HVACEquipment,
+  RoomAir:Node:AirflowNetwork:HVACEquipment,
     LeftUpper_HVAC,          !- Name
-    AirTerminal:SingleDuct:Uncontrolled,  !- ZoneHVAC or Air Terminal Equipment Object Type 1
+    AirTerminal:SingleDuct:ConstantVolume:NoReheat,  !- ZoneHVAC or Air Terminal Equipment Object Type 1
     NORTH_ZONE PTAC,         !- ZoneHVAC or Air Terminal Equipment Object Name 1
     0.04,                    !- Fraction of Output or Supply Air from HVAC Equipment 1
     0.04;                    !- Fraction of Input or Return Air to HVAC Equipment 1
 
-RoomAir:Node:AirflowNetwork:HVACEquipment,
+  RoomAir:Node:AirflowNetwork:HVACEquipment,
     CentralUpper_HVAC,       !- Name
-    AirTerminal:SingleDuct:Uncontrolled,  !- ZoneHVAC or Air Terminal Equipment Object Type 1
+    AirTerminal:SingleDuct:ConstantVolume:NoReheat,  !- ZoneHVAC or Air Terminal Equipment Object Type 1
     NORTH_ZONE PTAC,         !- ZoneHVAC or Air Terminal Equipment Object Name 1
     0.14,                    !- Fraction of Output or Supply Air from HVAC Equipment 1
     0.14;                    !- Fraction of Input or Return Air to HVAC Equipment 1
```

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/Transition/CreateNewIDFUsingRulesV9_3_0.f90 [hunk 1]
```diff
@@ -684,17 +684,18 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                 NoDiff = .true.
                  CALL GetNewObjectDefInIDD(ObjectName,NwNumArgs,NwAorN,NwReqFld,NwObjMinFlds,NwFldNames,NwFldDefaults,NwFldUnits)
-                 OutArgs(1) = InArgs(1)
-                 ! Loop through fields looking for  AirTerminal:SingleDuct:Uncontrolled node name
-                 DO nodeCount=2, CurArgs
-                   IF (SameString(TRIM(InArgs(nodeCount)), TRIM(ATSDUNodeNames(atCount)))) THEN
-                     OutArgs(nodeCount) = TRIM(InArgs(nodeCount)) // ' ATInlet'
-                   ELSE
-                     OutArgs(nodeCount) = InArgs(nodeCount)
+                 OutArgs(1:CurArgs) = InArgs(1:CurArgs)
```
Comment (jmarrec) [inline src/Transition/CreateNewIDFUsingRulesV9_3_0.f90:689]: Start up by copying everything, NoDiff is true.

File: src/Transition/CreateNewIDFUsingRulesV9_3_0.f90 [hunk 2]
```diff
@@ -684,17 +684,18 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                 ! "AirTerminal:SingleDuct:Uncontrolled" and replace with "AirTerminal:SingleDuct:ConstantVolume:NoReheat"
+                 ! Four extensible fields
+                 DO CurField=2, CurArgs-1, 4
+                   IF (SameString(TRIM(InArgs(CurField)),'AirTerminal:SingleDuct:Uncontrolled')) THEN
+                     OutArgs(CurField) = 'AirTerminal:SingleDuct:ConstantVolume:NoReheat'
+                     NoDiff = .false.
                    END IF
-                 ENDDO
-                NoDiff = .false.
+                 END DO
```
Comment (jmarrec) [inline src/Transition/CreateNewIDFUsingRulesV9_3_0.f90:698]: Then check every "ZoneHVAC or Air Terminal Equipment Object Type", if ATU:SngleDuct:Uncontrolled => replace and set NoDiff = false

**Comment by mjwitte** [comment]
@jmarrec The transition results look good, but the file fails:
```
   ** Severe  ** GetRoomAirflowNetworkData: The equipment listed in ZoneEquipList is not found in the lsit of RoomAir:Node:AirflowNetwork:HVACEquipment objects =
   **   ~~~   ** NORTH_ZONE PTAC ADU. Please check inputs of both objects.
```
My guess is that this object doesn't work with any of the airterminal units, because this code here is looking for the terminal unit type and name on the ZoneHVAC:EquipmentList. But air terminals don't live directly on the equipment list, they are a child of a ZoneHVAC:AirDistributionUnit. I'm going to merge this and open a new issue.
