### PR TITLE
Fix #11099 - Can't build on arm macs + lots of CMake warnings in newer cmake versions

### LINKED ISSUE #11099: Can't build on arm macs + lots of CMake warnings in newer cmake versions
### Issue overview

@yujiex (and  @RKStrand via email) reported this:

https://github.com/NREL/EnergyPlus/pull/11084#issuecomment-2964523973

I had an error like this in the debug build that might be related to changes in this PR. I'm on Mac M2. 
```
./EnergyPlus/src/EnergyPlus/ElectricPowerServiceManager.cc:4134:23: error: use of undeclared identifier 'fegetexcept'
    int old_excepts = fegetexcept();
                      ^
```
It seems mac doesn't have this function in fenv.h (https://github.com/mstg/iOS-full-sdk/blob/master/iPhoneOS9.3.sdk/usr/include/fenv.h) . Should we handle the case with something like this? Not sure if defaults to 0 is okay or do something else. Also according to the internet, Windows might not have this function either. I haven't tried to compile on windows though.
```
// Disable floating point exceptions around SSC battery calculations, which uses quiet_NaN in particular
#ifdef DEBUG_ARITHM_GCC_OR_CLANG
    #ifdef __APPLE__
        int old_excepts = 0; // Fallback for unsupported platforms
    #else
        int old_excepts = fegetexcept();
        fedisableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW);
    #endif
#endif
```

_Originally posted by @yujiex in https://github.com/NREL/EnergyPlus/issues/11084#issuecomment-2964523973_
            

### Operating System (Multiple choices)

MacOS

### Operating System Version

M-series (arm) macs

### Version of EnergyPlus

develop

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fixes #11099 

### Description of the purpose of this PR

- Add fegetexcept on mac+clang that don't have it
- Cleans up tons of CMake warnings and adds policy support up to 4.0.3

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/fenv_missing.h [hunk 1]
```diff
@@ -125,6 +132,17 @@
...
+    inline int fegetexcept()
+    {
+      static fenv_t fenv;
+      if (std::fegetenv(&fenv) != 0) {
+        return -1;
+      }
+      const unsigned long long old_fpcr = fenv.__fpcr;
+      const unsigned int old_excepts = (old_fpcr >> FPCR_EXCEPT_SHIFT) & unsigned(FE_ALL_EXCEPT);
+      return old_excepts;
+    }
```
Comment (jmarrec) [inline src/EnergyPlus/fenv_missing.h:144]: Fix build error on macs M-series when DEBUG ARITHM

File: CMakeLists.txt [hunk 2]
```diff
@@ -11,10 +11,6 @@ if(CCACHE_PROGRAM)
   set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_PROGRAM} CACHE FILEPATH "C compiler cache used")
 endif()
 
-cmake_policy(SET CMP0048 NEW) # handling project_version_* variables
-
-cmake_policy(SET CMP0087 NEW) # install(CODE) and install(SCRIPT) support generator expressions.
```
Comment (jmarrec) [inline CMakeLists.txt:16]: Remove explicit cmake_policy calls for stuff that was added prior to the version we support (3.19 here).

You can look at individual commit to see why I removed them.

File: CMakeLists.txt [hunk 3]
```diff
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 3.19)
+cmake_minimum_required(VERSION 3.19...4.0.3)  # policy_max is set, so that will impliclty invoke cmake_policy(VERSION <min>[...<max>])
```
Comment (jmarrec) [inline CMakeLists.txt:1]: I don't even need to do this:

```
if (POLICY CMP0177)
   cmake_policy(SET CMP0177 NEW) # Added in Cmake 3.31
endif()
```

Because it'll enable the NEW thing up to 4.0.3 (or the current CMake version, whichever is smallest)

cf https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-version

File: third_party/Windows-CalcEngine/CMakeLists.txt [hunk 4]
```diff
@@ -1,4 +1,4 @@
-cmake_minimum_required( VERSION 2.8.12...3.5)  # bumped max support to 3.5 to hush a cmake deprecation warning
+cmake_minimum_required( VERSION 2.8.12...4.0.3)  # bumped max support to hush a cmake deprecation warning
```
Comment (jmarrec) [inline third_party/Windows-CalcEngine/CMakeLists.txt:1]: Accross third_party, bump policies to 4.0.3.

```
CMake Deprecation Warning at third_party/gtest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
```

File: src/Basement/CMakeLists.txt [hunk 5]
```diff
@@ -1,12 +1,6 @@
 project(Basement Fortran)
 
-cmake_minimum_required(VERSION 3.5.1)
-
-cmake_policy(SET CMP0012 NEW) # if() recognizes boolean constants
-
-if(POLICY CMP0087)
-  cmake_policy(SET CMP0087 NEW) # install(CODE) and install(SCRIPT) support generator expressions.
-endif()
+cmake_minimum_required(VERSION 3.5.1...4.0.3)
```
Comment (jmarrec) [inline src/Basement/CMakeLists.txt:3]: Same in auxiliary directories. Bump max_policy to 4.0.3

```
CMake Deprecation Warning at src/ConvertInputFormat/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
```

File: src/Basement/CMakeLists.txt [hunk 6]
```diff
@@ -1,12 +1,6 @@
 project(Basement Fortran)
 
-cmake_minimum_required(VERSION 3.5.1)
-
-cmake_policy(SET CMP0012 NEW) # if() recognizes boolean constants
-
-if(POLICY CMP0087)
-  cmake_policy(SET CMP0087 NEW) # install(CODE) and install(SCRIPT) support generator expressions.
-endif()
```
Comment (jmarrec) [inline src/Basement/CMakeLists.txt:9]: And remove these old expliclit ones.

CMP0012 was aded in 2.8.0,
CMP0048 in 3.0
CMP0054 in 3.1

File: cmake/PythonSetupAPIinBuild.cmake [hunk 7]
```diff
@@ -1,26 +1,22 @@
...
-configure_file("${API_SOURCE_DIR}/state.py" "${API_TARGET_DIR}/state.py")
-configure_file("${API_SOURCE_DIR}/__init__.py" "${API_TARGET_DIR}/__init__.py")
+# These are copy only
+configure_file("${API_SOURCE_DIR}/common.py" "${API_TARGET_DIR}/common.py" COPYONLY)
+configure_file("${API_SOURCE_DIR}/datatransfer.py" "${API_TARGET_DIR}/datatransfer.py" COPYONLY)
+#configure_file( "${API_SOURCE_DIR}/autosizing.py" "${API_TARGET_DIR}/autosizing.py" )
+configure_file("${API_SOURCE_DIR}/runtime.py" "${API_TARGET_DIR}/runtime.py" COPYONLY)
+configure_file("${API_SOURCE_DIR}/plugin.py" "${API_TARGET_DIR}/plugin.py" COPYONLY)
+configure_file("${API_SOURCE_DIR}/state.py" "${API_TARGET_DIR}/state.py" COPYONLY)
+configure_file("${API_SOURCE_DIR}/__init__.py" "${API_TARGET_DIR}/__init__.py" COPYONLY)
```
Comment (jmarrec) [inline cmake/PythonSetupAPIinBuild.cmake:22]: Minor tweak to this one for clarity

File: src/EnergyPlus/CMakeLists.txt [hunk 8]
```diff
@@ -862,20 +862,29 @@ set_target_properties(energyplus PROPERTIES VERSION ${ENERGYPLUS_VERSION})
...
+  COMMENT "Generating Python API files next to energyplusapi"
+)
+
+# And a target that calls the above command. It is NOT called by default
+add_custom_target(setup_pyapi
+  DEPENDS "${PYAPI_STAMP}"
+)
+# When you build CLI, we want the api configuration to run, so add it as a dependency
+# which will ensure it's run (beforehand, at **build** not configure time)
+add_dependencies(energyplus setup_pyapi)
```
Comment (jmarrec) [inline src/EnergyPlus/CMakeLists.txt:887]: Fixup CMP0175: `add_custom_command TARGET does not support DEPENDS`, which would throw: https://cmake.org/cmake/help/latest/policy/CMP0175.html

* api.py and func.py have CMake configuration variables in there, the rests are plain python files
* Currently what's **silently** happening is that it will ignore the DEPENDS and will only reconfigure the files into `Products/$<CONFIG>/pyenergyplus` if the `energyplusapi `was rebuilt (and if it wasn't rebuilt, it's not done)
    * This is not that big of a deal and wouldn't happen often, but I did get bit by this more than once while tweaking a few things. I think that will affect probably just @Myoldmopar and I
     * Side note, but AFAIK, the `DEPENDS` should be a list of files, not a directory, so I don't think it was correct to begin with
* I understand the intent as being that it should always bring in any changes to these python files... So I did that

```
CMake Warning (dev) at src/EnergyPlus/CMakeLists.txt:865 (add_custom_command):
  The following keywords are not supported when using
  add_custom_command(TARGET): DEPENDS.

  Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
  Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by Myoldmopar** [comment]
Looks all clean here from CI, I'll take a deeper look at the changes just to make sure I understand them.

File: CMakeLists.txt (hunk 3 above)
Comment (Myoldmopar) [reply CMakeLists.txt:1]: > I don't even need to do this;

So are you saying that you want to undo the change?

File: CMakeLists.txt (hunk 2 above)
Comment (Myoldmopar) [reply CMakeLists.txt:16]: Sounds just fine to me.

File: cmake/PythonSetupAPIinBuild.cmake (hunk 7 above)
Comment (Myoldmopar) [reply cmake/PythonSetupAPIinBuild.cmake:22]: Sure, and COPYONLY makes good sense for these non-configured files.

File: src/EnergyPlus/CMakeLists.txt (hunk 8 above)
Comment (Myoldmopar) [reply src/EnergyPlus/CMakeLists.txt:887]: Indeed, this caught me once or twice.  This is much better, thank you.

File: src/EnergyPlus/fenv_missing.h (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/fenv_missing.h:144]: Excellent, thanks.

**Review by Myoldmopar — APPROVED** [review]
A great set of build rule updates.  Thanks @jmarrec

**Comment by Myoldmopar** [comment]
It's all testing happily here, thanks @jmarrec .  And I know @yujiex will be happy with this going in as she was seeing the Mac issue that you resolved.

File: CMakeLists.txt (hunk 3 above)
Comment (jmarrec) [reply CMakeLists.txt:1]: I'm saying that I don't need to handle cmp0177 explicitly
