### PR TITLE
 Fix VRFFluidCtrl heating cycling issue by moving cycling ratio calc in compressor spd calc

### LINKED ISSUE #10427: VRF heating issue: same heating power with different compressor speed at low heating load
Issue overview
--------------
Cycling issue at low speed for heating mode

From 12:30 to 13:00, the compressors are running at the lowest speed in both cases, zone temperature are the same but both system have cycling ratio = 1. This shouldn't happen as they have different compressor curves corresponding to the lowest speed.
From 1/12 14:40-16:40, the the two files with different minimum speed both have cycling ratio = 1 and the same zone air temperature, under the same outdoor condition. 

image

The defect files are attached here

[simulation_with_different_speeed_update.zip](https://github.com/user-attachments/files/16789553/simulation_with_different_speeed_update.zip)

The problem is likely related to two issues in the cycling ratio calculation.

1. The position of the cycling ratio calculation

Similar to the cycling ratio problem in the cooling side. Whether the demand is less than minimum speed capacity is checked at two places. The first one will short-circuit and prevent the Te adjustment step (orange box in the following simplified flow diagram)

image

The following is the diagram in the [documentation](https://bigladdersoftware.com/epx/docs/23-2/engineering-reference/variable-refrigerant-flow-heat-pumps.html#VRF-FluidTCtrl-HP)

image

2. Discontinuity

When the demand is very low, the cycling ratio is calculated as follows. When Q_h_TU_PL <= CompEvaporatingPWRSpdMin, it will enter branch 1. When Q_h_TU_PL > CompEvaporatingPWRSpdMin, it will enter branch 2. C_cap_operation is generally close to 1. However, when Q_h_TU_PL is close to CompEvaporatingPWRSpdMin, depending on which branch it ended up in, the result could be very different. If we assume CompEvaporatingPWRSpdMin and CompEvaporatingCAPSpdMin have similar magnitude, and C_cap_operation is indeed close to one, 
- when Q_h_TU_PL is slightly smaller than CompEvaporatingPWRSpdMin, then CyclingRatio is close to 1
- when Q_h_TU_PL is slightly larger than CompEvaporatingPWRSpdMin, then CyclingRatio is close to 0

```
        Q_c_OU = max(0.0, Q_h_TU_PL - CompEvaporatingPWRSpdMin);
        ...
            if (Q_c_OU == 0) { // branch 1
                // Q_h_TU_PL is less than or equal to CompEvaporatingPWRSpdMin
                CyclingRatio = Q_h_TU_PL / CompEvaporatingPWRSpdMin;
                this->EvaporatingTemp = OutdoorDryBulb;
            } else { // branch 2
                // Q_h_TU_PL is greater than CompEvaporatingPWRSpdMin
                CyclingRatio = Q_c_OU * C_cap_operation / CompEvaporatingCAPSpdMin;
                this->EvaporatingTemp = max(CapMinTe, RefTLow);
            }
```

```
02/20 13-1,branch 2 ----- cyclingRatio=0.5424031528859093,Q_h_TU_PL=772.3616736028802,CompEvaporatingPWRSpdMin=191.07128170025996,C_cap_operation=0.895930180163394
02/20 13-2,branch 2 ----- cyclingRatio=0.010679792435435032,Q_h_TU_PL=202.516754863906,CompEvaporatingPWRSpdMin=191.07128170025996,C_cap_operation=0.895930180163394
02/20 13-3,branch 1 ----- cyclingRatio=0.7196798169795096,Q_h_TU_PL=137.5101450440834,CompEvaporatingPWRSpdMin=191.07128170025996
02/20 13-4,branch 1 ----- cyclingRatio=0.9347582121695664,Q_h_TU_PL=178.6054496790826,CompEvaporatingPWRSpdMin=191.07128170025996
```

### Defect files
[US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF_minSpd900.idf.txt](https://github.com/NREL/EnergyPlus/files/14513453/US%2BSF%2BCZ4A%2Bhp%2Bcrawlspace%2BIECC_2006_VRF_minSpd900.idf.txt)
[US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF_minSpd1320.idf.txt](https://github.com/NREL/EnergyPlus/files/14513456/US%2BSF%2BCZ4A%2Bhp%2Bcrawlspace%2BIECC_2006_VRF_minSpd1320.idf.txt)
[USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw.txt](https://github.com/NREL/EnergyPlus/files/14513469/USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Fixes #10427 

The PR fixes the cycling ratio calculation of the VRF model in heating mode. 

image

It also enforces a lower bound on the outdoor unit's evaporating temperature. The older version uses the refrigerant lowest saturation temperature as the lower bound, which might not be realistically reachable.

```
        this->VRFOU_CalcCompH(state,
                              TU_HeatingLoad,
                              this->EvaporatingTemp,
                              Tdischarge,
                              h_IU_cond_out_ave,
                              this->IUCondensingTemp,
                              this->IUEvapTempLow,           
                              max(this->IUEvapTempLow, CapMinTe),    // <-- lower bound enforced here
                              Tfs,
                              Pipe_Q_h,
                              Q_c_OU,
                              CompSpdActual,
                              Ncomp_new,
                              CyclingRatio);
```

### Effect of the fix
Before the fix, the two files with different min speed curves both have cycling ratio = 1, however the zone temperature still remain the same. This is unreasonable as the two systems should provide different heating when running fulltime.

image

After the fix the two system both start to cycle, the one with higher capacity curve (1920) cycles more (lower cycling ratio).

image

### Regression diffs
The following files have regression diffs
- VariableRefrigerantFlow_FluidTCtrl_5Zone
- VariableRefrigerantFlow_FluidTCtrl_HR_5Zone
- VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone

#### table diff
The table diffs happen in the first two example files above. The following electricity and heating electricity related variables have diffs. These are expected as enable cycling in heating mode will cause changes in compressor power, which is part of heating and total electricity.

- Electricity:Facility
- ElectricityPurchased:Facility
- ElectricityPurchased:Plant
- Cogeneration:ElectricityPurchased
- General:Cogeneration:ElectricityPurchased
- ElectricityNet:Facility
- ElectricityNet:Plant
- Cogeneration:ElectricityNet
- General:Cogeneration:ElectricityNet
- Electricity:HVAC
- Heating:Electricity
- General:Heating:Electricity

#### eio diffs
The following variables differ in the eplusout.csv. Cycling ratio is multiplied to compressor power and evaporator heat extract, so VRF Heat Pump Compressor Electricity Rate and VRF Heat Pump Total Heating Rate are different. Heating electricity rate and Energy are also difference as a result of the difference in compressor power. Condensing and evaporating temperature changes are expected as previously these temperature used in OU calculation were not properly saved and reported. This feature fixes this. The Heating Heating Capacity at Max Compressor Speed diff is due to compressor suction temperature difference. This is expected.

- VRF HEAT PUMP:VRF Heat Pump Total Heating Rate 
- VRF HEAT PUMP:VRF Heat Pump Heating Electricity Rate 
- VRF HEAT PUMP:VRF Heat Pump Heating Electricity Energy 
- VRF HEAT PUMP:VRF Heat Pump Compressor Electricity Rate 
- VRF HEAT PUMP:VRF Heat Pump Outdoor Unit Condensing Temperature 
- VRF HEAT PUMP:VRF Heat Pump Outdoor Unit Evaporating Temperature 
- VRF Heat Pump Heating Capacity at Max Compressor Speed
- VRF Heat Pump Indoor Unit Piping Correction for Heating

The difference in Tsuction 
```
        this->HeatingCapacity =
            this->CoffEvapCap * this->RatedEvapCapacity * CurveValue(state, this->OUCoolingCAPFT(NumOfCompSpdInput), Tdischarge, Tsuction) +
            this->RatedCompPower * CurveValue(state,
                                              this->OUCoolingPWRFT(NumOfCompSpdInput),
                                              Tdischarge,
                                              Tsuction); // Include the piping loss, at the highest compressor speed
        this->PipingCorrectionHeating = TU_HeatingLoad / (TU_HeatingLoad + Pipe_Q_h);
        state.dataHVACVarRefFlow->MaxHeatingCapacity(VRFCond) =
            this->HeatingCapacity; // for report, maximum condensing capacity the system can provide

// debug print for feature branch
max heating capacity=84819.53148847456, Tdischarge=40, Tsuction=5
// debug print for develop branch
report max heating capacity=94676.23188865327, Tdischarge=40, Tsuction=8.7
```

The difference in suction temperature is due to the changes in the cycling calculation, where previously, it's calculated like this, while in this feature branch, the Te (suction temperature) update follows the low-load modification in `VRFOU_CalcCompH` function.

```
        } else if ((Q_c_OU * C_cap_operation) <= CompEvaporatingCAPSpdMin) {
            // Required heating load is smaller than the min heating capacity

            if (Q_c_OU == 0) {
                // Q_h_TU_PL is less than or equal to CompEvaporatingPWRSpdMin
                CyclingRatio = Q_h_TU_PL / CompEvaporatingPWRSpdMin;
                this->EvaporatingTemp = OutdoorDryBulb;
            } else {
                // Q_h_TU_PL is greater than CompEvaporatingPWRSpdMin
                CyclingRatio = Q_c_OU * C_cap_operation / CompEvaporatingCAPSpdMin;
                this->EvaporatingTemp = max(CapMinTe, RefTLow);
            }

            double CyclingRatioFrac = 0.85 + 0.15 * CyclingRatio;
            double HPRTF = CyclingRatio / CyclingRatioFrac;
            Ncomp = CompEvaporatingPWRSpdMin * HPRTF;
            CompSpdActual = this->CompressorSpeed(1);
```

#### meter diff

Meter diffs happen in the following two variables. As is discussed in the table diff, these electricity diffs are expected as a result of compressor power changes due to cycling enabled in this feature.

- Electricity:Facility 
- Electricity:HVAC 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 1]
```diff
@@ -14630,10 +14611,18 @@ void VRFCondenserEquipment::VRFOU_CalcCompH(
                     NumIteCcap = NumIteCcap + 1;
                     goto Label19;
                 }
-                if (CapDiff > (Tolerance * Cap_Eva0)) NumIteCcap = 999;
-
-                Ncomp = this->RatedCompPower * CurveValue(state, this->OUCoolingPWRFT(CounterCompSpdTemp), T_discharge, T_suction);
+                if (CapDiff > (Tolerance * Cap_Eva0)) {
```
Comment (yujiex) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: cycling ratio calculation is moved to here

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 2]
```diff
@@ -11856,80 +11856,60 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state)
                                                    CapMinTe + 8,
                                                    this->IUCondensingTemp - 5);
 
-        if ((Q_c_OU * C_cap_operation) <= CompEvaporatingCAPSpdMin) {
```
Comment (yujiex) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The cycling ratio calculation is removed here

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 3]
```diff
@@ -11856,80 +11856,60 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state)
...
+        this->SH = SH_OU;
+
+        // *VRF OU Compressor Simulation at heating mode: Specify the compressor speed and power consumption
+        this->VRFOU_CalcCompH(state,
+                              TU_HeatingLoad,
+                              this->EvaporatingTemp,
+                              Tdischarge,
+                              h_IU_cond_out_ave,
+                              this->IUCondensingTemp,
+                              this->IUEvapTempLow,
```
Comment (yujiex) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: enforces a lower bound to the outdoor unit evaporating temperature

**Comment by nrel-bot-2c** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I know the `goto Label20` was present in the original code but we should try to eliminate goto statements when possible. This does not need to change in this branch and is a suggestion for future code. I moved out of the loop any code that does not need to be calculated each iteration.

    Counter = 1;
    m_air = this->OUAirFlowRate * RhoAir;
    Ncomp_new = Ncomp;
    while (std::abs(Ncomp_new - Ncomp) > (Tolerance * Ncomp)) && (Counter < 30)) {
    }

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 4]
```diff
@@ -14630,10 +14611,19 @@ void VRFCondenserEquipment::VRFOU_CalcCompH(
...
                     goto Label19;
                 }
-                if (CapDiff > (Tolerance * Cap_Eva0)) NumIteCcap = 999;
-
-                Ncomp = this->RatedCompPower * CurveValue(state, this->OUCoolingPWRFT(CounterCompSpdTemp), T_discharge, T_suction);
+                if (CapDiff > (Tolerance * Cap_Eva0)) {
+                    NumIteCcap = 999;
+                    CyclingRatio = min(1.0, (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1);
+                } else {
+                    CyclingRatio = 1.0;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14355]: This looks odd. This appears to say if the calculation converged set CyclingRatio = 1 ?

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14355]: when it converges, the capacity `Cap_Eva1` and demand `Cap_Eva0` are close to each other, the system should run full-time, thus the cycling ratio should be 1.

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14355]: If `(TU_load + Pipe_Q) * C_cap_operation = Cap_Eva1` when this converges then I agree. I just can't follow the math well enough to see that clearly.

Before it converges:

    CyclingRatio = min(1.0, (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1);

and after it converges:

    CyclingRatio = 1.;

Then why can't the more detailed calculation happen all the time?

    if (CapDiff > (Tolerance * Cap_Eva0)) NumIteCcap = 999;
    CyclingRatio = min(1.0, (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1);

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: it feels more like a do-while loop, where the code inside label20 is executed once regardless of the condition, and then continues with a while loop. Although it is not a clean do-while loop as there's some operation inside the `if (condition) {goto label}` branch, especially for the label23 code, before goto, the `h_IU_cond_in` is recomputed differently. Let me think about it a bit.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14355]: I might have missed a "-Ncomp", it should be TU_load + Pipe_Q - Ncomp. TU_load + Pipe_Q - Ncomp and Q_evap_req should be equal. Maybe it's better to just use `Cap_Eva0 / Cap_Eva1` to compute cycling ratio like in the cooling mode branch https://github.com/NREL/EnergyPlus/pull/10353

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Would it be better to have a separate PR fixing goto ones? There are a few more instances in the physics-based VRF code. @rraustad

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The existing code is like the following after simplification. Let A = stuff A, B = stuff B and counter increment, C being the condition check, then this code will be evaluated to something like the following regex: A(CBA)*C. 
```
label:
    stuff A
if (some condition) {
    stuff B
    goto label
}
```
A while loop like this will evaluate to C(BAC)*
```
while (condition) {
    stuff B
    stuff A
}
```
a do-while loop like this will evaluate to (BAC)+
```
do {
    stuff B
    stuff A
} while (condition)
```
Maybe there's not a uniform clean transition, we'll need to reorganize the original code a little bit (some might be straightforward others might not).

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: That's fine to make goto changes in a different branch. I was just pointing that out.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Definitely. I will have a separate branch for goto fixes so that they could be tested separately. I feel it might have been more involved as label20 is nested inside label23. They probably should be considered together while making changes.

**Comment by nrel-bot-2b** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by dareumnam** [comment]
Since this PR is the heating version of the [previous PR](https://github.com/NREL/EnergyPlus/pull/10353), I believe it should be fine after you add some explanation about the regression test diffs and resolve merge conflicts. I'm happy to assist with resolving the merge conflicts if you need any help. @yujiex

**Comment by yujiex** [comment]
Thanks @dareumnam . I will resolve the conflicts and explain the diffs.

**Comment by yujiex** [comment]
@dareumnam  I've updated the code and explained the regression diff.

**Comment by rraustad** [comment]
@yujiex this looks good. The zone temperatures are identical before the fix and after the fix. That tells me it was just the cycling ratio that was calculated incorrectly and looks much better now. The heating rate before the fix is identical to after the fix for the lower speed test, there is a slight change to heating rate for the higher speed test. I would think this change alone would change the zone temp but it didn't change at all? Electricity rate is lower now and COP higher in both cases. I'm not sure which change to equations caused this. Let me ask this question: if the VRF is providing 300 W of heating at 900 RPM and 1920 RPM, which should have a higher COP? and what would drive the change in magnitude of COP? I think the answer to both questions is the change in cycling rate but I'm just not sure with this component model. I am not sure anything else needs to change in this branch but wanted to point out the change in COP and whether that change is expected/accurate/reasonable. I think the lower cycling rate answers the question of higher COP but just not sure of the magnitude. I have no further comments on this branch and it seems ready to merge.

**Comment by yujiex** [comment]
> @yujiex this looks good. The zone temperatures are identical before the fix and after the fix. That tells me it was just the cycling ratio that was calculated incorrectly and looks much better now. The heating rate before the fix is identical to after the fix for the lower speed test, there is a slight change to heating rate for the higher speed test. I would think this change alone would change the zone temp but it didn't change at all? Electricity rate is lower now and COP higher in both cases. I'm not sure which change to equations caused this. Let me ask this question: if the VRF is providing 300 W of heating at 900 RPM and 1920 RPM, which should have a higher COP? and what would drive the change in magnitude of COP? I think the answer to both questions is the change in cycling rate but I'm just not sure with this component model. I am not sure anything else needs to change in this branch but wanted to point out the change in COP and whether that change is expected/accurate/reasonable. I think the lower cycling rate answers the question of higher COP but just not sure of the magnitude. I have no further comments on this branch and it seems ready to merge.

**Both cases, COP increased comparing to the develop.**

After enabling cycling in this feature, compressor power of both cases reduced. COP is calculated as heat pump total heating rate / (compressor power + OU fan power). OU fan power here didn't change. There's slight changes in heating rate for the 1920 one, but the major change is in the compressor power. 

**changes in heating rate**

(modified)
After looking into it more closely. It seems the difference in heating rate between the two speed is due to difference in piping correction

`this->TotalHeatingCapacity` is "VRF Heat Pump Total Heating Rate"

`this->TotalHeatingCapacity = TotalCondHeatingCapacity * HeatingPLR;`

Difference between the two idf inputs are due to difference in HeatingPLR (calculated as `            HeatingPLR = min(1.0, (this->TUHeatingLoad / this->PipingCorrectionHeating) / TotalCondHeatingCapacity);
`), which is caused by difference in PipingCorrectionHeating.

```
// speed_900.idf
01/12 14-4, HeatingPLR = 0.1429658868110161 = 1808.52636398877 / 0.9585125135622209 / 13197.590067710878, defrost=0
01/12 14-4, TotalHeatingCapacity 1886.8051677985438 = 13197.590067710878 * 0.1429658868110161
// speed_1920.idf
01/12 14-4, HeatingPLR = 0.1448283978174752 = 1808.5263639886018 / 0.9461859247629643 / 13197.590067710878, defrost=0
01/12 14-4, TotalHeatingCapacity 1911.3858245583906 = 13197.590067710878 * 0.1448283978174752
```
Difference in `PipingCorrectionHeating` (`this->PipingCorrectionHeating = TU_HeatingLoad / (TU_HeatingLoad + Pipe_Q_h);`) is due to difference in `Pipe_Q_h`, which is from Pipe_T_IU_in (`h_IU_cond_in` input arg) difference inside function `VRFOU_PipeLossH`

```
Pipe_Q = max(0.0,
                     (Constant::Pi * this->RefPipLen) * (Pipe_T_IU_in - OutdoorDryBulb / 2 - Pipe_T_room / 2) /
                         (1 / Pipe_Coe_k1 + 1 / Pipe_Coe_k2 + 1 / Pipe_Coe_k3)); // [W]
```

`h_IU_cond_in` is different between the speed_900 and speed_1920 case is because the former only performed one iteration in the label23 loop while speed_1920 iterated 3 more times and its `h_IU_cond_in` got updated.

**which one should have higher COP** 
maybe the 900 one would have slightly higher COP?
See the plots here copied in from the cooling cycling branch, where the cooling/power multiplier is slightly larger for the curve 1 (900 one).

image
image

**Comment by rraustad** [comment]
What I see in the COP figure is that the COP is the same between these 2 curve sets at similar Te and Tc. And that makes sense. IIRC, 1 curve is for low speed and the other is from the next higher speed from the same equipment/chassis. The difference is that 1 curve has a higher capacity than the other but also a higher power, which gives a similar COP. The different cycling ratio should not change COP since PLR is applied to both capacity and power. But then there is condenser fan power that doesn't change with PLR and is not included in the power performance curves. Assuming Te and Tc are the same, If you multiply the cycling ratio and capacity/power at max speed (cycling ratio = 1), do you get the same numbers? If these numbers are the same, and condenser fan power is constant, then shouldn't COP be the same/similar? Is the indoor fan air flow/power the same? I would think so if Te is the same. One debugging trick I use is to run 2 simulations (2 local repos on this branch) at the same time with the different input files and single step each environment, at this current time, 1 line at a time and compare results of each line. You know your target capacity is 1800 W (which you are getting) and you know the target power from the numbers above. So where in the single stepping do the numbers not make sense? I hope this helps and not causing extra work.

**Comment by yujiex** [comment]
indoor air fan power is the same for both

The compressor power is calculated as RatedCompPower multiplied by the curve value. From the following debug print, we can see their discharge and suction temperature are the same for the two input idf. 
```
// speed_900
01/12 14-4, Ncomp=232.06887165758397 = 2937.7413 * 0.07899567999999998, T_discharge=40, T_suction=6)
01/12 14-4, Ncomp=198.31309188820177 = 232.06887165758397 * 0.8545441293859152
01/12 14-4, this->Ncomp=208.7506230402124 = 198.31309188820177 / 0.95
// speed_1920
01/12 14-4, Ncomp=334.57312864544394 = 2937.7413 * 0.11388787999999998, T_discharge=40, T_suction=6)
01/12 14-4, Ncomp=183.9043645929394 = 334.57312864544394 * 0.5496686638807379
01/12 14-4, this->Ncomp=193.58354167677834 = 183.9043645929394 / 0.95
```

I've added some investigation results on the heat pump total heating rate in the previous comment. Basically the heating rate difference between the two speeds are caused by piping correction differences. Not certain whether there's some issue with the piping correction calculation, which caused COP to differ like this. The compressor power difference seems to be expected.

**Comment by dareumnam** [comment]
@rraustad, I'm wondering about your thoughts on Yujie's latest response. If this PR needs more time for discussion, we can move it to the 25.1 bug freeze milestone, as we're planning to tag the first RC for 24.2 tomorrow.

**Comment by rraustad** [comment]
@dareumnam if the equations and results have been reviewed again and there is confidence in the results I am OK with these changes. I looked at the COPs again and VRF COP at low speed is 3.33 and changed to 3.43 at the higher speed. The VRF Heating COP changed from 5.74 to 6.09. These changes do not seem like that much of a difference now given all the changes here.

**Comment by yujiex** [comment]
I reviewed the COP numbers and they seem reasonable.

The two COP outputs compared are: "VRF Heat Pump Heating COP" and "VRF Heat Pump COP". The former is at the compressor side, the latter is at the air side.

Looking at debug prints at one timestep, we can see that
heating COP = VRF Heat Pump Total Heating Rate / VRF Heat Pump Heating Electricity Rate (the other three terms are 0)
COP = Heating Coil Heating Rate / (ParasiticHeatElecPower + TU1 VRF SUPPLY FAN:Fan Electricity Rate + VRF Heat Pump Heating Electricity Rate)
```
01/12 14-4,OperatingHeatingCOP=5.739751501649049 = 1886.8051677985438 / (328.7259330402124 + 0 + 0 + 0)
01/12 14-4,OperatingCOP=       3.331997110324534=(0 + 1808.52636398877) / 542.7754899261065
```
ParasiticHeatElecPower is a linear interpolation of "Zone Terminal Unit On Parasitic Electric Energy Use" and "Zone Terminal Unit Off Parasitic Electric Energy Use", using "Heating Coil Runtime Fraction".

The denominator are different as the air side one (COP) include TU fan power and parasitic electric power. The numerator are different as the air side (COP) removed piping loss (although there's still some difference even accounting for piping loss, to be fixed in (some other PR)[https://github.com/NREL/EnergyPlus/pull/10627]). 

According to @rraustad, the heating COP being 5.7 might be a bit high, but considering it being at very low speed, this seems reasonable, according to the fan/pump law where power changes cubicly with speed. Air-side COP being 3.3 is also reasonable.

**Comment by rraustad** [comment]
@yujiex good review of results. @Myoldmopar CI results can be reviewed and if as expected this can merge.

**Comment by Myoldmopar** [comment]
Well, CI has just two files with diffs, the VRF files as expected and described in the initial comment above.  I agree, we can drop this in.  I'll put it in the merge queue now.

**Comment by Myoldmopar** [comment]
All happy, really glad these are all getting merged in.  Thanks @yujiex @dareumnam @rraustad for all the help.
