### PR TITLE
Fix order of curve independent variables for GAHP

### LINKED ISSUE #11070: Gas-Fired absorption heat pump curve lookups use independent variables in the wrong order
### Issue overview

The engineering manual shows that for the gas-fired absorption heat pumps that the first independent variable is `T_amb` and then either `T_ret` (return water temperature) or `T_ent` (entering water temperature) is used. This is in-line with this paper: https://docs.lib.purdue.edu/cgi/viewcontent.cgi?article=1353&context=ihpbc. However, the code uses `T_ret`/`T_ent` first and then `T_amb`.

Here's an example: https://github.com/NREL/EnergyPlus/blob/2baa135f5395a22c25f474a7b2385084ec869252/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L2680

### Operating System (Multiple choices)

Windows

### Operating System Version

11

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11070

### Description of the purpose of this PR

Fix multi-variate curve lookups to be in-line with the documentation.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 1]
```diff
@@ -2677,7 +2677,7 @@ void EIRFuelFiredHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
     }
 
     // evaluate capacity modifier curve and determine load side heat transfer
-    Real64 capacityModifierFuncTemp = Curve::CurveValue(state, this->capFuncTempCurveIndex, waterTempforCurve, oaTempforCurve);
+    Real64 capacityModifierFuncTemp = Curve::CurveValue(state, this->capFuncTempCurveIndex, oaTempforCurve, waterTempforCurve);
```
Comment (rraustad) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: I think I would have voted for a change in documentation since all other models use Tamb as the second independent variable. It doesn't really matter except for consistency across models. I do see that the paper used Tamb as the first independent variable but when calculating biquadratic regression coefficients that order is subjective. It just means that the paper's coefficient a and b would become c and d in E+. Does the example file use these same coefficients? @mjwitte what are your thoughts on independent variable order for performance curves?

image

    EIR HP:
    capacityModifierFuncTemp = Curve::CurveValue(state, this->capFuncTempCurveIndex, loadSideOutletSetpointTemp, this->sourceSideInletTemp);

    DXCoils:
    TotCapTempModFac = CurveValue(state, thisDXCoil.CCapFTemp(Mode), InletAirWetBulbC, CondInletTemp);

Comment (mjwitte) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: @rraustad My initial advice was to follow the paper, but I didn't think about how other similar curves are done in EnergyPlus.
@lymereJ I don't see any changes here to the example file. Can you tell which variable order was used in those curves?

Comment (lymereJ) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: @mjwitte - The example file includes curves with only a constant coefficient:

```
  Curve:Biquadratic,
    EIRCurveFuncTemp,        !- Name
    1.0,                     !- Coefficient1 Constant
    0.0,                     !- Coefficient2 x
    0.0,                     !- Coefficient3 x**2
    0.0,                     !- Coefficient4 y
    0.0,                     !- Coefficient5 y**2
    0.0,                     !- Coefficient6 x*y
    5.0,                     !- Minimum Value of x
    10.0,                    !- Maximum Value of x
    24.0,                    !- Minimum Value of y
    35.0,                    !- Maximum Value of y
    ,                        !- Minimum Curve Output
    ,                        !- Maximum Curve Output
    Temperature,             !- Input Unit Type for X
    Temperature,             !- Input Unit Type for Y
    Dimensionless;           !- Output Unit Type

  Curve:Biquadratic,
    CapCurveFuncTemp,        !- Name
    1.0,                     !- Coefficient1 Constant
    0.0,                     !- Coefficient2 x
    0.0,                     !- Coefficient3 x**2
    0.0,                     !- Coefficient4 y
    0.0,                     !- Coefficient5 y**2
    0.0,                     !- Coefficient6 x*y
    5.0,                     !- Minimum Value of x
    10.0,                    !- Maximum Value of x
    24.0,                    !- Minimum Value of y
    35.0,                    !- Maximum Value of y
    ,                        !- Minimum Curve Output
    ,                        !- Maximum Curve Output
    Temperature,             !- Input Unit Type for X
    Temperature,             !- Input Unit Type for Y
    Dimensionless;           !- Output Unit Type
```

So, should I revert these changes and make the changes in the documentation? Here's perhaps another argument for modifying the documentation instead of the code: the EIR-f-T curves in the paper have to be renormalized because they describe not just a EIR modifier but the change in rated EIR as a function of the temperature. Please, let me know what you think is best.

Comment (mjwitte) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: I guess changing the documentation (and replacing these constant curves) is the better option. Sorry to send you down the wrong path.

Comment (lymereJ) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: Got it, no worries.

**Review by Myoldmopar — APPROVED** [review]
Looks like this is settled now.  Docs and example file and code agree.  Any final thoughts here before merging?

**Comment by rraustad** [comment]
So I see in the percdiff.csv a change of about 20% in load side heat transfer and roughly the same in fuel rate for the first few hours. I didn't run the example file so maybe this makes sense, for a water temp pull up or something during this time. And then during the day there is no change in load side heat transfer or inlet/outlet water temp or fuel rate, I can't tell if the unit is running or not but if it is, and the coefficients were changed, why isn't there diffs at this time? Then at the end of the day there is only a change in fuel rate? Is the unit running? I suspect it is running and the "load" is the same as before but the fuel use has changed. It's what you can't see in diffs that bring up more questions.

image

**Comment by lymereJ** [comment]
@rraustad - There's another PR ready for review https://github.com/NREL/EnergyPlus/pull/11068 which I think tackle some of that seemingly on/off behavior of the unit. Please, let me know what you think.

**Comment by Myoldmopar** [comment]
OK, so #11068 should go in before this, right?  In my mind, the first PR was causing an issue, so a follow-up PR was going to tackle the diffs....but the numbering doesn't match up with that.  I'm just wanting to confirm, and I can pull develop into the "second" PR to get cleaner results.

**Comment by lymereJ** [comment]
@Myoldmopar - That is correct. Although because the changes in this PR are now only documentation changes, I don't think that it matters since it shouldn't show any diffs. I think that the diffs that Rich was looking at were from the original proposed changes which involved code modifications instead of documentation modifications.

**Comment by Myoldmopar** [comment]
Ahh, that's right.  Cool, OK, merging this then.  Thanks.
