### PR TITLE
Fix vector error for when a zone or space has no surfaces

### LINKED ISSUE #10305: Vector error when zone has no surfaces
Program Version,EnergyPlus, Version 23.1.0-87ed9199d4, YMD=2023.11.20 18:36,
   ************* Beginning Zone Sizing Calculations
   ** Severe  ** vector too long
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 1 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.07sec

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #10305 
 - Protect against using invalid `AllSurfaceFirst/Last` as a subscript.
 - Clean up some related error messages.
 - Allow a space to have no surfaces.
 - But an enclosure with no surfaces will still fatal out.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Defect file error output before:
```
   ** Severe  ** vector too long
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
```
With this branch;
```
   ** Warning ** createSpaceSurfaceLists: Space=PLENUM-1 has no surfaces.
   ** Warning ** No floor exists in Zone="PLENUM-1", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
   ** Warning ** CheckUsedConstructions: There are 2 nominally unused constructions in input.
   **   ~~~   ** For explicit details on each unused construction, use Output:Diagnostics,DisplayExtraWarnings;
   ** Severe  ** InitSolarViewFactors: No surfaces in enclosure=PLENUM-1.
   ** Warning ** Surfaces in Zone/Enclosure="PLENUM-1" do not define an enclosure.
   **   ~~~   ** Number of surfaces <= 3, view factors are set to force reciprocity but may not fulfill completeness.
   **   ~~~   ** Reciprocity means that radiant exchange between two surfaces will match and not lead to an energy loss.
   **   ~~~   ** Completeness means that all of the view factors between a surface and the other surfaces in a zone add up to unity.
   **   ~~~   ** So, when there are three or less surfaces in a zone, EnergyPlus will make sure there are no losses of energy but
   **   ~~~   ** it will not exchange the full amount of radiation with the rest of the zone as it would if there was a completed enclosure.
   **  Fatal  ** InitSolarViewFactors: Errors found during initialization of diffuse solar distribution.  Program terminated.
 ```

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 1]
```diff
@@ -499,7 +500,10 @@ namespace HeatBalanceIntRadExchange {
             thisEnclosure.NumOfSurfaces = numEnclosureSurfaces;
             state.dataHeatBalIntRadExchg->MaxNumOfRadEnclosureSurfs =
                 max(state.dataHeatBalIntRadExchg->MaxNumOfRadEnclosureSurfs, numEnclosureSurfaces);
-            if (numEnclosureSurfaces < 1) ShowFatalError(state, "No surfaces in an enclosure in InitInteriorRadExchange");
+            if (numEnclosureSurfaces < 1) {
+                ShowSevereError(state, format("{}No surfaces in enclosure={}.", RoutineName, thisEnclosure.Name));
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc:504]: Some error message cleanup - should throw a severe here and set `ErrorsFound`, then fatal throws later.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 2]
```diff
@@ -558,9 +558,10 @@ namespace SurfaceGeometry {
         for (int ZoneNum = 1; ZoneNum <= state.dataGlobal->NumOfZones; ++ZoneNum) {
             auto &thisZone = state.dataHeatBal->Zone(ZoneNum);
             bool nonInternalMassSurfacesPresent = false;
+            bool internalMassSurfacesPresent = false;
             Real64 TotSurfArea = 0.0;
             thisZone.Centroid = Vector(0.0, 0.0, 0.0);
-            if (state.dataSurface->Surface(thisZone.AllSurfaceFirst).Sides > 0) {
+            if ((thisZone.AllSurfaceFirst > 0) && (state.dataSurface->Surface(thisZone.AllSurfaceFirst).Sides > 0)) {
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:564]: Check for valid subscript before using it.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 3]
```diff
@@ -573,8 +574,11 @@ namespace SurfaceGeometry {
 
                 for (int SurfNum = thisSpace.AllSurfaceFirst; SurfNum <= thisSpace.AllSurfaceLast; ++SurfNum) {
                     auto &thisSurface = state.dataSurface->Surface(SurfNum);
-                    if (thisSurface.Class == SurfaceClass::IntMass) continue;
-                    nonInternalMassSurfacesPresent = true;
+                    if (thisSurface.Class == SurfaceClass::IntMass) {
+                        internalMassSurfacesPresent = true;
+                        continue;
+                    }
+                    if (!thisSurface.IsAirBoundarySurf) nonInternalMassSurfacesPresent = true;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:581]: Clean up this check. Previously, the internal mass warning below was firing even when there was no internal mass in the zone (or any surfaces at all). Also, an air boundary surface shouldn't be counted as a valid `nonInternalMassSurface`.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 4]
```diff
@@ -2257,110 +2261,7 @@ namespace SurfaceGeometry {
             }
         }
 
-        //**********************************************************************************
-        //   Set up Zone Surface Pointers
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2261]: The methodology here for setting `*SurfaceFirst/Last` for zone and spaces was flawed, especially if a space had no surfaces. This has been redone and move to a new function `setSurfaceFirstLast`.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 5]
```diff
@@ -3011,15 +2912,67 @@ namespace SurfaceGeometry {
             // Add to Space's list of surfaces
             state.dataHeatBal->space(thisSurf.spaceNum).surfaces.emplace_back(surfNum);
         }
-        // TODO MJW: Is this necessary? Check that all Spaces have at least one Surface
-        for (int spaceNum = 1; spaceNum < state.dataGlobal->numSpaces; ++spaceNum) {
+        for (int spaceNum = 1; spaceNum <= state.dataGlobal->numSpaces; ++spaceNum) {
             if (int(state.dataHeatBal->space(spaceNum).surfaces.size()) == 0) {
-                ShowSevereError(state, format("{}Space = {} has no surfaces.", RoutineName, state.dataHeatBal->space(spaceNum).Name));
-                ErrorsFound = true;
+                ShowWarningError(state, format("{}Space={} has no surfaces.", RoutineName, state.dataHeatBal->space(spaceNum).Name));
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2917]: Changed this to allow a space with no surfaces to pass through. However, if an enclosure has no surfaces, that will severe/fatal out. This does open the possibility of having a space with no surfaces sharing the same enclosure with other space(s) that do have surfaces. So, is that something we really want to allow?

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 6]
```diff
@@ -3011,15 +2912,67 @@ namespace SurfaceGeometry {
...
             }
         }
     }
 
+    void setSurfaceFirstLast(EnergyPlusData &state)
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2922]: The new function with a more robust method.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 7]
```diff
@@ -8661,10 +8661,6 @@ TEST_F(EnergyPlusFixture, GetSurfaceData_SurfaceOrder)
 
     SetupZoneGeometry(*state, ErrorsFound);
     EXPECT_FALSE(ErrorsFound); // expect no errors
-
-    GetSurfaceData(*state, ErrorsFound); // setup zone geometry and get zone data
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:8665]: This function is already called from `SetupZoneGeometry`. Otherwise, no substantive changes to the exisiting `GetSurfaceData_SurfaceOrder` unit test.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 8]
```diff
@@ -9058,6 +9054,2395 @@ TEST_F(EnergyPlusFixture, GetSurfaceData_SurfaceOrder)
     EXPECT_FALSE(std::find(HTKivaSurfaces.begin(), HTKivaSurfaces.end(), thisSurface) != HTKivaSurfaces.end());
 }
 
+TEST_F(EnergyPlusFixture, GetSurfaceData_SurfaceOrder2)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:9057]: Added three new unit tests that are subsets of `GetSurfaceData_SurfaceOrder` where the first zone/space has no surfaces (`GetSurfaceData_SurfaceOrder2`), the middle zone has no surfaces (`GetSurfaceData_SurfaceOrder3`), and the last zone has no surfaces (`GetSurfaceData_SurfaceOrder4`).

**Review by mjwitte — COMMENTED** [review]
Code walk through.

**Comment by mjwitte** [comment]
CI is all green. Ready for review.

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HeatBalanceIntRadExchange.cc:504]: That's a nice addition - let it find more errors on the first pass.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 9]
```diff
@@ -3011,15 +2912,67 @@ namespace SurfaceGeometry {
...
+                    } else {
+                        thisSpace.OpaqOrWinSurfaceLast = SurfNum;
+                    }
+                }
+                state.dataHeatBal->Zone(ZoneNum).AllSurfaceLast = thisSpace.AllSurfaceLast;
+            }
+            int firstSpaceNum = state.dataHeatBal->Zone(ZoneNum).spaceIndexes(1);
+            state.dataHeatBal->Zone(ZoneNum).AllSurfaceFirst = state.dataHeatBal->space(firstSpaceNum).AllSurfaceFirst;
+        }
+    }
```
Comment (Myoldmopar) [inline src/EnergyPlus/SurfaceGeometry.cc:2974]: It's a little difficult to grasp the changes since the code is moved entirely, but I understand that this is a positive move.  And your unit tests are fleshed out heavily, so that builds confidence.

**Review by Myoldmopar — APPROVED** [review]
This looks great to me.  Thanks @mjwitte

**Comment by Myoldmopar** [comment]
CI is 100% green, and this branch is up to date with develop, so this goes right in.  Thanks @mjwitte
