### PR TITLE
Cycling ratio is applied twice during cycling operation for `HeatPump:PlantLoop:EIR:*` objects

### LINKED ISSUE #11202: Incorrect cycling calculation for `HeatPump:PlantLoop:EIR:*`objects
### Issue overview

The defect file includes a `HeatPump:PlantLoop:EIR:Heating` which is setup with a reference COP of 1.0 and with no capacity and EIR degradation (curves output = 1). It has a minimum PLR of 0.5. I would expect to see that below the minimum part load ratio that the compressor would cycle proportionally to the load, however, it does not appear to be the case, see the figure below.

Image

### Operating System (Multiple choices)

MacOS

### Operating System Version

15.6.1

### Version of EnergyPlus

25.1 and lastest develop

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[large_office_vav_hw_reheat_const_spd_awhp.txt](https://github.com/user-attachments/files/22226141/large_office_vav_hw_reheat_const_spd_awhp.txt)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11202

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lymereJ** [comment]
Results with this branch are shown in blue:

image

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 1]
```diff
@@ -656,7 +656,7 @@ void EIRPlantLoopHeatPump::calcPowerUsage(EnergyPlusData &state)
     // compute power usage
     if (this->thermosiphonDisabled(state)) {
         this->powerUsage = (this->loadSideHeatTransfer / this->referenceCOP) * eirModifierFuncPLR * eirModifierFuncTemp *
-                           this->defrostPowerMultiplier * this->cyclingRatio;
+                           this->defrostPowerMultiplier;
```
Comment (lymereJ) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: The `cyclingRatio` is already applied when calculating the `loadSideHeatTransfer`:

https://github.com/NREL/EnergyPlus/blob/e5c5f38d7ce6f007763ba80bada6e17a9fba0042/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L621-L622

**Review by rraustad — APPROVED** [review]
I agree with this, and is a result of using loadSideHeatTransfer in the equation instead of availableCapacity.

**Comment by Myoldmopar** [comment]
I'll pull develop in here which should clean up the false test failure listed there.  I'll mark it as waiting on CI as well.  Assuming it's happy, I'll get this merged.

**Review by Myoldmopar — APPROVED** [review]
