### PR TITLE
Fix Site:Precipitation divide-by-zero

### LINKED ISSUE #8038: Zero Site:Precipitation input results in very large outputs
Issue overview
--------------
When using a Site:Precipitation object in the idf, if the average total annual precipitation is set to zero, the output reported (using `Output:Variable,*,Site Precipitation Rate,hourly; !- HVAC Average [m/s]`) is a very large integer on EnergyPlus 9.3, and causes previous versions to crash. The idf snippet below demonstrates the idf input.
```
Site:Precipitation,
     ScheduleAndDesignLevel, !- Precipitation Model Type
     1.0,                    !- Design Level Total Annual Precipitation {m/yr}
     AlwaysOn,               !- Schedule Name for Precipitation Rates
     0.0;                    !- Average Total Annual Precipitation {m/yr}
```
### Details
Some additional details for this issue (if relevant):
 - Platform: 9.3
 - Version of EnergyPlus: 9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by ajscimone**
Pull request overview
---------------------
 - Fixes #8038
 - This pull request fixes a divide by zero error which occurs if the Site:Precipitation idf object is entered with a zero total annual precipitation. EnergyPlus will attempt to calculate the Rainfall CurrentRate each time the WaterManager::UpdatePrecipitation function is called, and perform a divide by zero error. This will result in the CurrentRate being set as a very large int for EnergyPlus 9.3 and will result in a crash for some older versions of EnergyPlus.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterManager.cc [hunk 1]
```diff
@@ -1000,7 +1000,12 @@ namespace WaterManager {
 
         if (RainFall.ModeID == RainSchedDesign) {
             schedRate = GetCurrentScheduleValue(RainFall.RainSchedID); // m/hr
-            ScaleFactor = RainFall.DesignAnnualRain / RainFall.NomAnnualRain;
+            if (RainFall.NomAnnualRain > 0.0){
+                ScaleFactor = RainFall.DesignAnnualRain / RainFall.NomAnnualRain;
+            }
+            else {
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterManager.cc]: If you could plop the `else {` up right after the `}` that would be great.  This change makes great sense.

File: tst/EnergyPlus/unit/CMakeLists.txt [hunk 2]
```diff
@@ -189,6 +189,7 @@ set( test_src
   Vector.unit.cc
   VentilatedSlab.unit.cc
   WaterCoils.unit.cc
+  WaterManager.unit.cc
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/CMakeLists.txt:194]: Another new unit test file, this is great.  I went to see if there was a clear_state in the water manager, but there isn't -- because the water manager doesn't hold any global state....at least that's how it "appears".  There are a number of static variables inside functions inside WaterManager that could cause the simulation state to go haywire.  I would like to see those extracted into the global state and a new clear_state method that will call it to reset the water manager.  It doesn't necessarily have to be in this PR, but if not, then in a quick follow-up PR.  And if you aren't able to accommodate it right now, I'll open a PR and do it.

File: tst/EnergyPlus/unit/WaterManager.unit.cc [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+        "Schedule:Constant,",
+        "PrecipitationSchd,",
+        ",",
+        "1;",
+    });
+    ASSERT_TRUE(process_idf(idf_objects));
+
+    WaterManager::GetWaterManagerInput();
+
+    ScheduleManager::Schedule.allocate(1);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/WaterManager.unit.cc]: I'm not sure what this line is doing.  The `GetWaterManagerInput` function calls `GetScheduleIndex`, which allocates and sets up the schedule array.  This line is doing nothing I think.  Please take it out, it should still work perfectly.

File: tst/EnergyPlus/unit/WaterManager.unit.cc [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+    Real64 ExpectedNomAnnualRain = 0.80771;
+    Real64 ExpectedCurrentRate = 1.0 * (0.75 / 0.80771) / DataGlobals::SecInHour;
+
+    Real64 NomAnnualRain = DataWater::RainFall.NomAnnualRain;
+    EXPECT_NEAR(NomAnnualRain, ExpectedNomAnnualRain, 0.000001);
+
+    Real64 CurrentRate = DataWater::RainFall.CurrentRate;
+    EXPECT_NEAR(CurrentRate, ExpectedCurrentRate, 0.000001);
+
+    ScheduleManager::Schedule.deallocate();
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/WaterManager.unit.cc]: This deallocate isn't necessary.  The schedule manager's state is cleared after each unit test, and the deallocate is happening over there.

File: tst/EnergyPlus/unit/WaterManager.unit.cc [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+    WaterManager::UpdatePrecipitation();
+
+    Real64 NomAnnualRain = DataWater::RainFall.NomAnnualRain;
+    EXPECT_NEAR(NomAnnualRain, 0.0, 0.000001);
+
+    Real64 CurrentRate = DataWater::RainFall.CurrentRate;
+    EXPECT_NEAR(CurrentRate, 0.0, 0.000001);
+
+    ScheduleManager::Schedule.deallocate();
+}
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/WaterManager.unit.cc:123]: Same comments about allocate/deallocate, but these are great unit tests!

**Review by Myoldmopar — CHANGES_REQUESTED** [review]
A couple very quick changes requested, and then a more broad question about the static variables inside the water manager.  I realize that probably falls into the scope of a follow-on issue/PR.

File: tst/EnergyPlus/unit/WaterManager.unit.cc (hunk 3 above)
Comment (ajscimone) [reply tst/EnergyPlus/unit/WaterManager.unit.cc]: Ah I think you're right. I don't need to allocate a second time here. Ill remove this.

File: tst/EnergyPlus/unit/WaterManager.unit.cc (hunk 4 above)
Comment (ajscimone) [reply tst/EnergyPlus/unit/WaterManager.unit.cc]: Roger that. These will be removed.

**Comment by Myoldmopar** [comment]
Something went awry with the Mac unit test.  A hybrid unit test failed.  Any thoughts why?  I will re-run Mac just to make sure, but that doesn't look to be one of the ones we tend to have issues with.

**Comment by Myoldmopar** [comment]
I just noticed you had noted my comments but not made the changes yet anyway.  No problem at all, I was just going to be moving to final review if CI was all happy and the changes were made.  Carry on...

**Comment by ajscimone** [comment]
@Myoldmopar Hey Edwin. Yeah sorry for the delay with pushing things up. The hybrid unit test passes on my Mac so im not quite sure whats going on with the CI there. Nothing we have done here should effect that code. All of the changes you mentioned have been made on my local branch except for the static variables/ clear_state function. I was waiting to get a chance to speak with Neal about what I was proposing to do there, but since that change is less related to this, I will push the other changes up and see if the failed unit tests are a false positive.

**Comment by ajscimone** [comment]
@Myoldmopar Looks like pushing your requested changes caused those failed tests to go away.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Everything looks great now.  Thanks for addressing my comments, and CI is happy.  Merging.
