### PR TITLE
LowTempRadiantSystem - Fix minor bug

### LINKED ISSUE #8462: Check should point to 'Cooling Design Capacity Per Floor Area' instead of 'Heating Control Throttling Range'.
Issue overview
--------------

https://github.com/NREL/EnergyPlus/blob/6163e5b3936402b6de5ab05403cfd1696e85b5f9/src/EnergyPlus/LowTempRadiantSystem.cc#L701

Based on the logic in the lines before and after this line, this line should check if 'Cooling Design Capacity Per Floor Area' (`Numbers(11)`) is not blank instead of 'Heating Control Throttling Range' (`Numbers(9)`).

Therefore, it should be 

`if (!lNumericBlanks(11)) {`

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus - 9.40 (6163e5b)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmythms**
Pull request overview
---------------------
 - Fixes #8462 
 - Minor bug/typo fix. The current code does not match with the logic of the code above and below it, this fixes it. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, the author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### CODE REVIEW

File: src/EnergyPlus/LowTempRadiantSystem.cc [hunk 1]
```diff
@@ -698,7 +698,7 @@ namespace LowTempRadiantSystem {
                 }
             } else if (UtilityRoutines::SameString(Alphas(12), "CapacityPerFloorArea")) {
                 thisRadSys.CoolingCapMethod = CapacityPerFloorArea;
-                if (!lNumericBlanks(9)) {
+                if (!lNumericBlanks(11)) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/LowTempRadiantSystem.cc:701]: Interesting that this wasn't causing any issues.  And interesting that no unit test caught this.  @RKStrand could you give a quick thumbs up/down on this?

@jmythms it would be really great to integrate testing of this in a unit test.  Is there an existing unit test that handles input processing of this that you could modify or mimic?  (Hint: there must be one because several lines of code around this line you changed are indeed covered by [unit test](http://energyplus.s3-website-us-east-1.amazonaws.com/coverage/2021-01-12-EnergyPlus-ec58f461aa-x86_64-gcc-7.5UTCD/EnergyPlus/LowTempRadiantSystem.cc.gcov.html).)

Comment (jmythms) [reply src/EnergyPlus/LowTempRadiantSystem.cc:701]: Thank you for the review! Working on the unit test now. 

While working on this, I also just came across [this line](https://github.com/NREL/EnergyPlus/blob/ec58f461aa80708e4ef10c7d96e489bed71d5965/src/EnergyPlus/LowTempRadiantSystem.cc#L703), which I am not sure should have been 

`if (thisRadSys.ScaledCoolingCapacity <= 0.0) {` 
instead of 
`if (thisRadSys.CoolingCapMethod <= 0.0) {`.

I think this second change would generate the error message intended:
image

for this input object:
image

Comment (RKStrand) [reply src/EnergyPlus/LowTempRadiantSystem.cc:701]: @Myoldmopar I would agree that this is a bug that needs to be fixed.  It should be changed as @jmythms is suggesting.

My guess (and it's just a guess because I don't think I was the one to add all of the sizing mods that did things on a floor area, etc. basis) is that there simply isn't a test that exercises all of the potential options for both correct and incorrect input for low temperature radiant systems.  Is there one for a different input object like baseboards or something similar, maybe and if so, it would be good to implement such a unit testing scheme here.

Comment (RKStrand) [reply src/EnergyPlus/LowTempRadiantSystem.cc:701]: @jmythms Yes, I agree with your second recommended change also.  It should not be looking at CoolingCapMethod but ScaledCoolingCapacity.

Comment (jmythms) [reply src/EnergyPlus/LowTempRadiantSystem.cc:701]: Thank you!

**Comment by Myoldmopar** [comment]
@jmythms let me know if you need anything on this.  It's just a bug fix, so there's no urgency to get it in, but I am trying to get the PR list down and this would be a quick fix.  I already pulled in develop and ran tests locally.

**Comment by jmythms** [comment]
> @jmythms let me know if you need anything on this. It's just a bug fix, so there's no urgency to get it in, but I am trying to get the PR list down and this would be a quick fix. I already pulled in develop and ran tests locally.

Sorry, I got sidetracked with the other projects, will get this ready quick.

**Comment by jmythms** [comment]
> @jmythms let me know if you need anything on this. It's just a bug fix, so there's no urgency to get it in, but I am trying to get the PR list down and this would be a quick fix. I already pulled in develop and ran tests locally.

@Myoldmopar This is ready for review, can you take a look please?

**Comment by Myoldmopar** [comment]
This looks ready to go.  Thanks for adding the unit test.  I'm going to do a quick build of this with develop pulled in just to make sure nothing happened with the unit test.  Then I'll merge.  Thanks @jmythms

**Comment by jmythms** [comment]
> This looks ready to go. Thanks for adding the unit test. I'm going to do a quick build of this with develop pulled in just to make sure nothing happened with the unit test. Then I'll merge. Thanks @jmythms

Thanks very much @Myoldmopar

**Comment by Myoldmopar** [comment]
Built with develop pulled in locally, no issues.  Ran unit tests serially then the whole test suite in parallel, all passing.  Merging.
