### PR TITLE
Fix air boundary: interior window, FullInteriorExterior beam solar, and zone grouping

### LINKED ISSUE #7725: Construction:AirBoundary solar not working correctly for all cases
Issue overview
--------------
 - [x] Construction:AirBoundary "Solar and Daylighting Method" = GroupedZones works as expected with Solar Distribution = Full Exterior, but not with FullInteriorAndExterior. User comments:

> Using either FullExterior or InteriorAndExterior, the sum of Surface Inside Face Solar Radiation Heat Gain Rate plus Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate is nearly equal to Zone Windows Total Transmitted Solar Radiation Rate. For both solar distribution methods, the former is always ~1-2% smaller than the later. Why?
> Using FullExterior all floors in a solar enclosure receive Surface Inside Face Beam Solar Radiation Heat Gain Rate, and no other surfaces receive beam solar. Surface Inside Face Solar Radiation Heat Gain Rate per Area is equal for all floor surfaces, confirming that beam solar is distributed equally across all floor surfaces.
Using InteriorAndExterior Surface Inside Face Beam Solar Radiation Heat Gain Rate reports reasonable values for appropriate surfaces in exterior zones, but no surfaces in the interior zones receive beam solar.

 - [x] Construction:AirBoundary "Solar and Daylighting Method" = InteriorWindow does not work. It was disabled for the 9.2 release.

*3. With plain old interior windows, there are significant non-zero values of Surface Inside Face Solar Radiation Heat Gain Energy at night when they should all be zero. (This is not related to the airwall work, see #7865.)*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 9.2.0
 - Unmethours [41171](https://unmethours.com/question/41171/constructionairboundary-solar-enclosures-for-grouped-zones-solar-distribution/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached here:

[7725-AirWall-BeamSolar.zip](https://github.com/NREL/EnergyPlus/files/4357865/7725-AirWall-BeamSolar.zip) - this shows the beam solar working in the interior zones with FullExteriorAndInterior:

  7725-FullExt-5ZoneAirCooled_AirBoundaries_Daylighting - beam solar only on the floor surfaces (see column HI F5-1:Surface Inside Face Beam Solar Radiation Heat Gain Rate [W](Hourly))

  7725-FullIntExt-5ZoneAirCooled_AirBoundaries_Daylighting - beam solar showing in the interior zones (see columns GY, HD, and HI for example)
  7725-FullIntExt-5ZoneAirCooled_CombineZones_Daylighting - this is the same file with the zones actually merged (no air boundaries) - and, after the fix, wait for it . . . .
  All of the Surface Inside Face Solar Radiation Heat Gain Energy and Surface Inside Face Beam Solar Radiation Heat Gain Rate variables are the *same* as the file above using air boundaries!

[7725-AirBoundaryInteriorWindow.zip](https://github.com/NREL/EnergyPlus/files/4357891/7725-AirBoundaryInteriorWindow.zip)

5ZoneAirCooled_AirBoundaries_Daylighting-IntWindow
5ZoneAirCooled_Daylighting-ActualIntWindow - uses actual walls with interior windows instead of air boundary InteriorWindow
After fix:
  SPACE5-1 DAYLIGHTING CONTROL:Daylighting Reference Point 1 Illuminance - values are similar between the two files. They are not identical, because the properties of the implied window from the InteriorWindow option are perfectly transmitting, which can't be reproduced with an explicit window.
  F5-1:Surface Inside Face Solar Radiation Heat Gain Energy is similar in both files when the sun is shining. The file with the actual interior window shows values at night (issue #7865 which isn't fixed yet).
  
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #7843: Construction:AirBoundary enclosure grouping algorithm is not general enough
Issue overview
--------------
User file fails with
```
   ** Severe  ** SetupRadiantEnclosuresAndAirBoundaries: Radiant enclosure grouping error for Surface="MEDICAL OFFICE BUILDING_ZONE 2-25_WALL223_{00341}".This surface enclosure num=3. Other side enclosure num=2
   ** Severe  ** SetupRadiantEnclosuresAndAirBoundaries: Radiant enclosure grouping error for Surface="MEDICAL OFFICE BUILDING_ZONE 2-28_WALL259_{00385}".This surface enclosure num=2. Other side enclosure num=3
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.
```

This file has 23 zones and many air boundary surfaces.

Some initial debugging reveals that the grouping logic is not general enough in `SurfaceGeometry::SetupRadiantEnclosuresAndAirBoundaries`. Let's say zones 1-5 are all connected with air boundaries. If a surface between zones 1 and 2 has an air boundary , then Zones 1 and 2 will be assigned to enclosure 1. Then, let's say zone 3 is connect to zone 4 and zone 4 is connected to zone 5, then enclosure 2 will hold zone 3-5. But if the last surface in zone 5 closes the loop and connects to zone 1, the grouping algorithm fails because this last surface is trying to put an air boundary between zone 1 which is in enclosure 1 and zone 5 which is in enclosure 2. So, I need to come up with a more general solution, or make a second pass to regroup.

`SetupSolarEnclosuresAndAirBoundaries` uses the same algorithm so it would fail the same way if the solar grouping is the same as the radiant rouping and SetupRadiantEnclosuresAndAirBoundaries didn't fatal out first.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 9.3.0-cc126b865c
 - Unmethours [41171](https://unmethours.com/question/41171/constructionairboundary-solar-enclosures-for-grouped-zones-solar-distribution/)
 - And Helpdesk ticket number 15415 (different users)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles\7843\
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Several fixes for Construction:AirBoundary

 - Fixes #7725 (defect files attached to the issue)
Solar and Daylighting Method = InteriorWindow is enabled.
With Solar and Daylighting Method = GroupedZones and Solar Distribution = FullInteriorAndExterior, beam solar now penetrates to all surfaces within the grouped zones (i.e. in the same solar enclosure).

 - Fixes #7843 (defect file in EnergyPlusDevSupport\DefectFiles\7843)
Previously, certain combinations of grouped zones could results in a fatal error "SetupRadiantEnclosuresAndAirBoundaries: Radiant enclosure grouping error".

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] ~If structural output changes, add to output rules file and add OutputChange label~
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceManager.cc [hunk 1]
```diff
@@ -7560,15 +7560,26 @@ namespace HeatBalanceManager {
...
+                    thisConstruct.TransSolBeamCoef = 0.0;
+                    thisConstruct.TransSolBeamCoef(1) = 1.0;
+                    thisConstruct.ReflSolBeamFrontCoef = 0.0;
+                    thisConstruct.ReflSolBeamBackCoef = 0.0;
+                    thisConstruct.TransVisBeamCoef = 0.0;
+                    thisConstruct.TransVisBeamCoef(1) = 1.0;
+                    thisConstruct.AbsBeamCoef = 0.0;
+                    thisConstruct.AbsBeamBackCoef = 0.0;
+                    thisConstruct.AbsDiff = 0.0;
+                    thisConstruct.AbsDiffBack = 0.0;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceManager.cc:7582]: Set window properties here for the InteriorWindow option

File: src/EnergyPlus/PackagedTerminalHeatPump.hh [hunk 2]
```diff
@@ -313,14 +313,15 @@ namespace PackagedTerminalHeatPump {
...
-              HotWaterCoilMaxIterIndex2(0), ActualFanVolFlowRate(0.0), HeatingSpeedRatio(1.0), CoolingSpeedRatio(1.0), NoHeatCoolSpeedRatio(1.0),
-              AvailStatus(0), HeatCoolMode(0), NumOfSpeedCooling(0), NumOfSpeedHeating(0), IdleSpeedRatio(0.0), IdleVolumeAirRate(0.0),
-              IdleMassFlowRate(0.0), FanVolFlow(0.0), CheckFanFlow(true), HeatVolumeFlowRate(MaxSpedLevels, 0.0),
-              HeatMassFlowRate(MaxSpedLevels, 0.0), CoolVolumeFlowRate(MaxSpedLevels, 0.0), CoolMassFlowRate(MaxSpedLevels, 0.0),
-              MSHeatingSpeedRatio(MaxSpedLevels, 0.0), MSCoolingSpeedRatio(MaxSpedLevels, 0.0), CompSpeedNum(0), CompSpeedRatio(0.0), ErrIndexCyc(0),
-              ErrIndexVar(0), ZonePtr(0), HVACSizingIndex(0), FirstPass(true), HeatCoilWaterFlowRate(0.0), ControlZoneMassFlowFrac(1.0),
+              CompPartLoadRatio(0.0), LastMode(0), AirFlowControl(0), ControlType(0), validASHRAECoolCoil(false), validASHRAEHeatCoil(false),
+              simASHRAEModel(false), CompPartLoadFrac(0.0), PlantCoilOutletNode(0), SuppCoilLoopNum(0), SuppCoilLoopSide(0), SuppCoilBranchNum(0),
```
Comment (mjwitte) [inline src/EnergyPlus/PackagedTerminalHeatPump.hh:317]: Add SingleZoneVAV variables to PTAC intialization to fix `AirTerminalSingleDuctMixer_SimPTAC_ATMInletSide` unit test.

File: src/EnergyPlus/SolarShading.cc [hunk 3]
```diff
@@ -5540,7 +5540,7 @@ namespace SolarShading {
                     if (!Surface(BackSurfaceNumber).HeatTransSurf) continue;              // Skip non-heat transfer surfaces
                     if (Surface(BackSurfaceNumber).BaseSurf == GRSNR) continue;           // Skip subsurfaces of this GRSNR
                     if (BackSurfaceNumber == GRSNR) continue;                             // A back surface cannot be GRSNR itself
-                    if (Surface(BackSurfaceNumber).Zone != Surface(GRSNR).Zone) continue; // Skip if back surface not in zone
+                    if (Surface(BackSurfaceNumber).SolarEnclIndex != Surface(GRSNR).SolarEnclIndex) continue; // Skip if back surface not in same solar enclosure
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:5543]: This is why beam solar wan't getting into the full enclosure, it was only going to the same zone as the window.

File: src/EnergyPlus/SolarShading.cc [hunk 4]
```diff
@@ -5772,7 +5771,6 @@ namespace SolarShading {
 
             SAREA(GRSNR) = 0.0;
 
-            NZ = Surface(GRSNR).Zone;
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:5775]: `NZ` was never used here.

File: src/EnergyPlus/SolarShading.cc [hunk 5]
```diff
@@ -8519,66 +8519,59 @@ namespace SolarShading {
                                     // Equivalent Layer window model has no distinction when treating windows with and
                                     // without shades (interior, inbetween and exterior shades)
 
-                                    if (Construct(ConstrNumBack).TypeIsAirBoundaryInteriorWindow) {
-                                        TransBeamWin = 1.0;
-                                        AbsBeamWinEQL = 0.0;
-                                        AbsBeamTotWin = 0.0;
-                                    }
-                                    else {
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:8527]: This didn't belong in here. Air boundary InteriorWindow options doesn't use the equivalent layer model.

File: src/EnergyPlus/SolarShading.cc [hunk 6]
```diff
@@ -8519,66 +8519,59 @@ namespace SolarShading {
...
+                                        IntBeamAbsByShadFac(BackSurfNum) = BOverlap * AbsSolBeamBackEQL(1, CFS(EQLNum).NL) /
+                                            (Surface(BackSurfNum).Area + SurfaceWindow(BackSurfNum).DividerArea);
+                                        BABSZone += BOverlap * AbsSolBeamBackEQL(1, CFS(EQLNum).NL);
+                                    }
+                                    //   Absorbed by the exterior shade layer of back exterior window
+                                    if (CFS(EQLNum).L(1).LTYPE != ltyGLAZE) {
+                                        IntBeamAbsByShadFac(BackSurfNum) =
+                                            BOverlap * AbsSolBeamBackEQL(1, 1) / (Surface(BackSurfNum).Area + SurfaceWindow(BackSurfNum).DividerArea);
+                                        BABSZone += BOverlap * AbsSolBeamBackEQL(1, 1);
+                                    }
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:8550]: This is all just reducing the indent because the surrounding `if` was removed.

File: src/EnergyPlus/SolarShading.cc [hunk 7]
```diff
@@ -8616,6 +8609,10 @@ namespace SolarShading {
                                 // Opaque surface
 
                                 AISurf(FloorNum) += BTOTWinZone * ISABSF(FloorNum) / Surface(FloorNum).Area; //[-]
+                            } else if (Construct(FlConstrNum).TypeIsAirBoundaryInteriorWindow) {
+                                    TransBeamWin = 1.0;
+                                    AbsBeamWinEQL = 0.0;
+                                    AbsBeamTotWin = 0.0;
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:8615]: This sets the window properties in the correct place.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 8]
```diff
@@ -12660,12 +12660,26 @@ namespace SurfaceGeometry {
         }
     }
 
-    void SetupRadiantEnclosuresAndAirBoundaries(bool &ErrorsFound)
+    void SetupEnclosuresAndAirBoundaries(Array1D<DataViewFactorInformation::ZoneViewFactorInformation> &Enclosures, // Radiant or Solar Enclosures
+                                         SurfaceGeometry::enclosureType const &EnclosureType,                       // Radiant or Solar
+                                         bool &ErrorsFound)                                                         // Set to true if errors found
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:12665]: Replace two very similar functions `SetupRadiantEnclosuresAndAirBoundaries` and `SetupSolarEnclosuresAndAirBoundaries` with a single function that's called twice, `SetupEnclosuresAndAirBoundaries`.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 9]
```diff
@@ -12684,157 +12699,136 @@ namespace SurfaceGeometry {
...
+                                Zone(Surface(surf.ExtBoundCond).Zone).SolarEnclosureNum = otherSideEnclosureNum;
+                            }
                         } else if (thisSideEnclosureNum != otherSideEnclosureNum) {
-                            // This should never happen
-                            ErrorsFound = true;
-                            ShowSevereError(RoutineName + ": Solar enclosure grouping error for Surface=\"" + surf.Name + "\"." +
-                                            "This surface enclosure num=" + General::RoundSigDigits(thisSideEnclosureNum) +
-                                            ". Other side enclosure num=" + General::RoundSigDigits(otherSideEnclosureNum));
+                            // If both sides are already assigned to an enclosure, then merge the two enclosures
+                            auto &thisEnclosure(Enclosures(thisSideEnclosureNum));
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:12783]: The following section merges two enclosures that are later found to be connected, fixing 7843.

File: src/EnergyPlus/WindowManager.cc [hunk 10]
```diff
@@ -1887,6 +1887,7 @@ namespace WindowManager {
         for (ConstrNum = 1; ConstrNum <= TotConstructs; ++ConstrNum) {
             if (Construct(ConstrNum).FromWindow5DataFile) continue;
             if (Construct(ConstrNum).WindowTypeBSDF) continue;
+            if (Construct(ConstrNum).TypeIsAirBoundaryInteriorWindow) continue;
```
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc:1890]: This is the main reason InteriorWindow wasn't working - this was zeroing out all of the window contruction properties that had been set before.

File: tst/EnergyPlus/unit/HeatBalanceManager.unit.cc [hunk 11]
```diff
@@ -1838,11 +1838,8 @@ TEST_F(EnergyPlusFixture, HeatBalanceManager_GetAirBoundaryConstructData)
     EXPECT_TRUE(UtilityRoutines::SameString(DataHeatBalance::Construct(constrNum).Name, "Non-Grouped Air Boundary"));
     EXPECT_TRUE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundary);
     EXPECT_FALSE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundaryGroupedRadiant);
-    // InteriorWindow option currently disabled
-    EXPECT_TRUE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundarySolar);
-    EXPECT_FALSE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundaryInteriorWindow);
-    //EXPECT_FALSE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundarySolar);
-    //EXPECT_TRUE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundaryInteriorWindow);
+    EXPECT_FALSE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundarySolar);
+    EXPECT_TRUE(DataHeatBalance::Construct(constrNum).TypeIsAirBoundaryInteriorWindow);
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/HeatBalanceManager.unit.cc:1842]: Reactivate InteriorWindow unit tests.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 12]
```diff
@@ -5125,17 +5129,267 @@ TEST_F(EnergyPlusFixture, HeatBalanceIntRadExchange_SetupEnclosuresWithAirBounda
...
+    EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(1).ZoneNames[1], "Zone 3"));
+    EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(2).Name, "Zone 2"));
+    EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(2).ZoneNames[0], "Zone 2"));
+    EXPECT_EQ(DataHeatBalance::Zone(1).SolarEnclosureNum, 1);
+    EXPECT_EQ(DataHeatBalance::Zone(2).SolarEnclosureNum, 2);
+    EXPECT_EQ(DataHeatBalance::Zone(3).SolarEnclosureNum, 1);
+
+}
+
+TEST_F(EnergyPlusFixture, HeatBalanceIntRadExchange_SetupEnclosuresWithAirBoundaries3)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:5144]: New unit test to cover the enclosure merge operation (issue 7843).

**Review by mjwitte — COMMENTED** [review]
Code walkthrough.

**Comment by Myoldmopar** [comment]
CI is very happy.  Looking over the changes now.

**Comment by Myoldmopar** [comment]
Building locally and running unit tests, I encountered a unit test failure in the hybrid unitary object that wouldn't go away.  I found that that module had **no** `clear_state` function, so I added it quickly and now unit tests pass successfully.  Will continue testing and still doing code review.

File: src/EnergyPlus/HeatBalanceManager.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HeatBalanceManager.cc:7582]: So transmitted is just straight 1.0 for this window.

File: src/EnergyPlus/PackagedTerminalHeatPump.hh (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PackagedTerminalHeatPump.hh:317]: :+1:

File: src/EnergyPlus/SolarShading.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SolarShading.cc:5543]: Interesting, OK so you are matching against the enclosure index now, not the zone num.  :+1:

File: src/EnergyPlus/SolarShading.cc (hunk 4 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SolarShading.cc:5775]: :+1:

File: src/EnergyPlus/SolarShading.cc (hunk 5 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SolarShading.cc:8527]: Good cleanup in here

File: src/EnergyPlus/SolarShading.cc (hunk 6 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SolarShading.cc:8550]: :+1:

File: src/EnergyPlus/SolarShading.cc (hunk 7 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SolarShading.cc:8615]: OK, so it's not in the equivalent layer section anymore.

File: src/EnergyPlus/SurfaceGeometry.hh [hunk 13]
```diff
@@ -81,6 +82,12 @@ namespace SurfaceGeometry {
     extern int const UnreconciledZoneSurface; // interim value between entering surfaces ("Surface") and reconciling
     // surface names in other zones
 
+    enum enclosureType
+    {
+        RadiantEnclosures,
+        SolarEnclosures
+    };
```
Comment (Myoldmopar) [inline src/EnergyPlus/SurfaceGeometry.hh:89]: Yay! Enums!  We can in the future consider going to more `enum class`, but enums are definitely 10000% better than regular `int const` values.

File: src/EnergyPlus/WindowManager.cc (hunk 10 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WindowManager.cc:1890]: Sneaky

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 14]
```diff
@@ -5125,17 +5129,267 @@ TEST_F(EnergyPlusFixture, HeatBalanceIntRadExchange_SetupEnclosuresWithAirBounda
...
+        "    NoSun,                   !- Sun Exposure",
+        "    NoWind,                  !- Wind Exposure",
+        "    ,                        !- View Factor to Ground",
+        "    4,                       !- Number of Vertices",
+        "    0,0,0,              !- Vertex 1",
+        "    0,1,0,              !- Vertex 1",
+        "    0,1,1,              !- Vertex 1",
+        "    0,0,1;              !- Vertex 1",
+
+        });
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:5342]: This is a great list of just the few objects that are needed.  So nice.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 15]
```diff
@@ -5125,17 +5129,267 @@ TEST_F(EnergyPlusFixture, HeatBalanceIntRadExchange_SetupEnclosuresWithAirBounda
...
-    //EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(2).ZoneNames[0], "Zone 2"));
+    EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(1).ZoneNames[2], "Zone 5"));
+    EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(1).ZoneNames[3], "Zone 3"));
+    EXPECT_TRUE(UtilityRoutines::SameString(DataViewFactorInformation::ZoneSolarInfo(1).ZoneNames[4], "Zone 4"));
     EXPECT_EQ(DataHeatBalance::Zone(1).SolarEnclosureNum, 1);
-    //EXPECT_EQ(DataHeatBalance::Zone(2).SolarEnclosureNum, 2);
     EXPECT_EQ(DataHeatBalance::Zone(2).SolarEnclosureNum, 1);
     EXPECT_EQ(DataHeatBalance::Zone(3).SolarEnclosureNum, 1);
+    EXPECT_EQ(DataHeatBalance::Zone(4).SolarEnclosureNum, 1);
+    EXPECT_EQ(DataHeatBalance::Zone(5).SolarEnclosureNum, 1);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:5393]: Clean, efficient unit tests, that pass!

**Review by Myoldmopar — APPROVED** [review]
I'm going to run a file or two, but the code looks great, and unit tests are running well (now that I fixed a stray hybrid unitary problem).

**Comment by Myoldmopar** [comment]
Built and ran locally, everything looks good.  The error file in the 5ZoneAirBoundaries file has some minor sizing warnings that can be cleaned out later, but the results all look reasonable.  I'm going to merge this in.  I'll be pushing the unitary hybrid fix and merging without wasting another set of CI cycles.  Thanks for this effort @mjwitte.
