### PR TITLE
Fix #11244 - Allow building with AppleClang 17

### LINKED ISSUE #11244: can't build with Apple Clang 17+
### Issue overview

Sprintf is deprecated, and a warning is issued in glfw (from penumbra) and btcvb's xmlUtil

That warnings is raised as an error ultimately. It happens in Debug mode.

```
/Users/julien/Software/Others/EnergyPlus/third_party/penumbra/vendor/glfw/src/cocoa_joystick.m:484:9: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
  484 |         sprintf(guid, "03000000%.4s0000%.4s000000000000",
      |         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:278:1: note: 'sprintf' has been explicitly marked deprecated here
  278 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
```

```
/Users/julien/Software/Others/EnergyPlus/third_party/BCVTB/utilSocket.c:219:7: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
  219 |       sprintf(temCha,"%d ", booVal[i]);
      |       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:278:1: note: 'sprintf' has been explicitly marked deprecated here
  278 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
/Users/julien/Software/Others/EnergyPlus/third_party/BCVTB/utilSocket.c:226:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
  226 |   sprintf(temCha,"\n");
      |   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:278:1: note: 'sprintf' has been explicitly marked deprecated here
  278 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)
```

### Operating System (Multiple choices)

MacOS

### Operating System Version

Tahoe

### Version of EnergyPlus

develop

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fixes #11244 

### Description of the purpose of this PR

- Modernize the BCTVB C code
- Ignore deprecated declarations (`-Wno-deprecated-declarations`) for penumbra's glfw

**Review without the first commit, which is just clang format**

https://github.com/NREL/EnergyPlus/pull/11246/files/8d0e1c0208bae1d0d40159c4a62136ceaf833b30..3405fb1bf5546c80646a996282eefa9391720421

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: third_party/BCVTB/utilXml.c [hunk 1]
```diff
@@ -860,51 +857,72 @@ int check_variable_cfg_Validate(char const* const fileName) {
...
+
+    snprintf(dtdFileName, n_needed, "%s%s%s", BCVTB_HOME, xmlPath, dtdName);
+    FILE* dtdF = fopen(dtdFileName, "r");
+    if (!dtdF) {
+      fprintf(stderr, "Error: Cannot open '%s'.\n", dtdFileName);
+      free(dtdFileName);
+      return -1;
+    } else {
+      fclose(dtdF);
+    }
```
Comment (jmarrec) [inline third_party/BCVTB/utilXml.c:895]: Calculate the size needed properly, use snprintf not sprintf.

A test bed that will showcase the before/after is provided for convenience here: https://compiler-explorer.com/z/xoW58hn3j

Comment (jmarrec) [reply third_party/BCVTB/utilXml.c:895]: I'm also freeing as soon as I can, and scoping variables better.

File: third_party/BCVTB/utilXml.c [hunk 2]
```diff
@@ -860,51 +857,72 @@ int check_variable_cfg_Validate(char const* const fileName) {
...
-    fprintf(stderr,
-            "Error: Memory allocation failed in"
-            "       check_variable_cfg_Validate"
-            "       when parsing file '%s'.\n"
-            "       Program aborting.\n",
-            fileName);
-    return -1;
-  }
-  dtdFileName = (char*)malloc(sizeof(char) * (strlen(BCVTB_HOME) + 30));
-  if (NULL == command) {
```
Comment (jmarrec) [inline third_party/BCVTB/utilXml.c]: Note that this check on line 879 was wrong, it was checking the wrong variable...

Doesn't matter that much because malloc will never fail on the systems we run this on, but still

File: third_party/BCVTB/utilXml.c [hunk 3]
```diff
@@ -860,51 +857,72 @@ int check_variable_cfg_Validate(char const* const fileName) {
...
-    fclose(dtdF);
-  sprintf(command, "java -jar \"%s%s\" \"%s\" \"%s%s\"", BCVTB_HOME, jarPath, fileName, BCVTB_HOME, xmlPath);
-  ret = system(command);
+  char* command = NULL;
+  {
+    char const* const cmd_fmt = "java -jar \"%s%s\" \"%s\" \"%s%s\"";
+
+    // Add 1 for the null terminator
+    size_t n_needed = 18 + 2 * n_BCVTB_HOME + n_jarPath + n_xmlPath + n_fileName + 1;
+    // int n_needed = snprintf(NULL, 0, cmd_fmt, BCVTB_HOME, jarPath, fileName, BCVTB_HOME, xmlPath) + 1;
```
Comment (jmarrec) [inline third_party/BCVTB/utilXml.c:905]: I have considered calling snprintf with a null ptr and bufsize of zero to let it calculate the needed size for me, but this I have everything I need I decided not to.

File: third_party/penumbra/vendor/CMakeLists.txt [hunk 4]
```diff
@@ -30,6 +30,9 @@ target_include_directories(glfw PUBLIC
  ${PROJECT_SOURCE_DIR}/vendor/glfw/include
  ${PROJECT_SOURCE_DIR}/vendor/glfw/deps
 )
+if(NOT MSVC)
+  target_compile_options(glfw PRIVATE -Wno-deprecated-declarations)
+endif()
```
Comment (jmarrec) [inline third_party/penumbra/vendor/CMakeLists.txt:35]: For penumbra's glfw, just ignore deprecated declarations for now.

File: third_party/BCVTB/utilXml.c [hunk 5]
```diff
@@ -860,51 +857,72 @@ int check_variable_cfg_Validate(char const* const fileName) {
...
+    // Add 1 for the null terminator
+    size_t n_needed = n_BCVTB_HOME + n_xmlPath + n_dtdName + 1;
+
+    char* dtdFileName = (char*)malloc(sizeof(char) * n_needed);
+    if (!dtdFileName) {
+      fprintf(stderr,
+              "Error: Memory allocation for 'dtdFileName' failed in check_variable_cfg_Validate when parsing file '%s'. \n"
+              "       Program aborting.\n",
+              fileName);
+      // free(dtdFileName);
```
Comment (jmarrec) [inline third_party/BCVTB/utilXml.c:883]: I'm omitting this because it's pointless.

(Note that I *could* have left it, because `free` on a null pointer has no effect)

**Review by mitchute — APPROVED** [review]
