### PR TITLE
Fix GAHP flow request

### LINKED ISSUE #11067: Gas-Fired absorption heat pump flow control issue
### Issue overview

Two files are attached to this issue.  The only difference between these two models is the object used to produce hot water: one uses a boiler and the other one a gas-fired absorption heat pump (GAHP). Both the boiler and the GAHP are setup to run at an efficiency of 1.0 and no performance degradation is modeled. The boiler case show reasonable results, however, the GAHP one shows incorrect results.  The figures below show that the unit has flow rate/heat transfer when the sum of the `Coil:Heating:Water` heating rates are greater than 0.

Boiler case:

Image

GAHP case:

Image

### Operating System (Multiple choices)

Windows

### Operating System Version

11

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[defect_files.zip](https://github.com/user-attachments/files/20303222/defect_files.zip)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11067 

### Description of the purpose of this PR

Fix gas-fired absorption flow requests.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lymereJ** [comment]
Here are the results for the (GAHP) defect file after updating it to 25.2 and with this branch.

image

Here's the updated file: 
[large_office_6A_vav_hw_reheat_out_gahp.idf.zip](https://github.com/user-attachments/files/20354539/large_office_6A_vav_hw_reheat_out_gahp.idf.zip)

**Comment by lymereJ** [comment]
ESO diff explanation:
Unlike the defect file, in develop, the example file shows flow rate through the unit, but because the load on the loop is small the GAHP does not use any gas (see code change walk-through). With this branch, the unit has a fuel rate and heat transfer greater than 0 during these times which I think is correct. See screenshot below (develop is on top, results from this branch are at the bottom).

image

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 1]
```diff
@@ -245,7 +245,7 @@ void EIRPlantLoopHeatPump::setOperatingFlowRatesWSHP(EnergyPlusData &state, bool
             this->sourceSideMassFlowRate = (this->heatRecoveryHeatPump) ? state.dataLoopNodes->Node(this->sourceSideNodes.inlet).MassFlowRate
                                                                         : this->sourceSideDesignMassFlowRate;
 
-            if (!FirstHVACIteration && this->flowControl == DataPlant::FlowMode::VariableSpeedPump) {
+            if (!FirstHVACIteration && this->flowMode == DataPlant::FlowMode::VariableSpeedPump) {
```
Comment (lymereJ) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:248]: Use `flowMode` to be consistent with the enum class name.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 2]
```diff
@@ -361,6 +361,72 @@ void EIRPlantLoopHeatPump::setOperatingFlowRatesASHP(EnergyPlusData &state, bool
     }
 }
 
+void EIRFuelFiredHeatPump::setOperatingFlowRatesASHP(EnergyPlusData &state, bool FirstHVACIteration, Real64 const currentLoad)
```
Comment (lymereJ) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:364]: Set the flow rates at the same time as `EIRPlantLoopHeatPump`s. Move the logic from `EIRFuelFiredHeatPump::doPhysics` here.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 3]
```diff
@@ -2863,17 +2775,13 @@ void EIRFuelFiredHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
         eirAuxElecFuncPLR = 0.0;
     }
 
-    if (partLoadRatio < this->minPLR) {
-        this->fuelRate = 0.0;
-        this->powerUsage = 0.0;
-    } else {
-        this->fuelRate = this->loadSideHeatTransfer / (this->referenceCOP * CRF) * eirModifierFuncPLR * eirModifierFuncTemp * eirDefrost;
+    this->fuelRate = this->loadSideHeatTransfer / (this->referenceCOP * CRF) * eirModifierFuncPLR * eirModifierFuncTemp * eirDefrost;
```
Comment (lymereJ) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:2794]: The previous behavior was to zero out the fuel rate when the `partLoadRatio` was less than the `minPLR` which triggered instances where the unit was not using any energy.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 4]
```diff
@@ -4496,6 +4499,34 @@ TEST_F(EnergyPlusFixture, GAHP_HeatingSimulate_AirSource)
...
+        Real64 curLoad = 100;
+        bool runFlag = true;
+        Real64 constexpr specifiedLoadSetpoint = 45;
+        state->dataLoopNodes->Node(thisHeatingPLHP->loadSideNodes.outlet).TempSetPoint = specifiedLoadSetpoint;
+        state->dataLoopNodes->Node(thisHeatingPLHP->loadSideNodes.inlet).Temp = 40;
+        state->dataLoopNodes->Node(thisHeatingPLHP->sourceSideNodes.inlet).Temp = 30;
+        thisHeatingPLHP->simulate(*state, myLoadLocation, firstHVAC, curLoad, runFlag);
+        EXPECT_TRUE(thisHeatingPLHP->fuelRate > 0);
+        EXPECT_NEAR(5.0, thisHeatingPLHP->loadSideMassFlowRate, 0.001);
+    }
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:4515]: Test to check that `fuelRate` > 0 when `partLoadRatio` < `minPLR`.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 5]
```diff
@@ -4496,6 +4499,34 @@ TEST_F(EnergyPlusFixture, GAHP_HeatingSimulate_AirSource)
...
+        bool runFlag = true;
+        Real64 constexpr expectedLoadMassFlowRate = 0.0478;
+        Real64 constexpr specifiedLoadSetpoint = 45;
+        state->dataLoopNodes->Node(thisHeatingPLHP->loadSideNodes.outlet).TempSetPoint = specifiedLoadSetpoint;
+        state->dataLoopNodes->Node(thisHeatingPLHP->loadSideNodes.inlet).Temp = 35;
+        state->dataLoopNodes->Node(thisHeatingPLHP->sourceSideNodes.inlet).Temp = 30;
+        thisHeatingPLHP->flowMode = DataPlant::FlowMode::LeavingSetpointModulated;
+        thisHeatingPLHP->simulate(*state, myLoadLocation, firstHVAC, curLoad, runFlag);
+        EXPECT_NEAR(expectedLoadMassFlowRate, thisHeatingPLHP->loadSideMassFlowRate, 0.001);
+    }
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:4529]: Test to check the variable flow logic.

**Review by lymereJ — COMMENTED** [review]
Code changes walkthrough:

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 6]
```diff
@@ -2879,17 +2791,13 @@ void EIRFuelFiredHeatPump::doPhysics(EnergyPlusData &state, Real64 currentLoad)
...
 
-        this->powerUsage = this->nominalAuxElecPower * eirAuxElecFuncTemp * eirAuxElecFuncPLR;
-        if (this->defrostType == DefrostType::Timed) {
-            this->powerUsage += this->defrostResistiveHeaterCap * this->defrostOpTimeFrac * reportingInterval;
-        }
+    this->powerUsage = this->nominalAuxElecPower * eirAuxElecFuncTemp * eirAuxElecFuncPLR;
+    if (this->defrostType == DefrostType::Timed) {
+        this->powerUsage += this->defrostResistiveHeaterCap * this->defrostOpTimeFrac * reportingInterval;
```
Comment (rraustad) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: Why is `reportingInterval` included here? It was included before but looks odd. It seems that defrostOpTimeFrac * reportingInterval = seconds and J/s * s = joules. So powerUsage += joules ??

Comment (lymereJ) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: Yes, that does not seem correct. Should I make the change in this PR? Or, open an issue and fix it in a different one?

Comment (Myoldmopar) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: I think go ahead and make the change here rather than opening a new PR.

**Comment by Myoldmopar** [comment]
Alright, and with that fix in place, I think this is good to go in.  Thanks for spotting it @rraustad and thanks for the quick fix up @lymereJ.  This checks out locally and is ready to go, merging.
