### PR TITLE
Fix flow rate issue for fanless unitary system

### LINKED ISSUE #10823: Fan-free UnitarySystem on branch shuts down flow if No Load Supply Air Flow Rate is zero
Issue overview
--------------
Airloop with the following branch configuration never runs (fan power always zero):
```
Branch,
  Perim_1_WSHP Main Branch,               !- Name
  ,                                       !- Pressure Drop Curve Name
  AirLoopHVAC:OutdoorAirSystem,           !- Component Object Type 1
  Perim_1_WSHP OACtrl OA System,          !- Component Name 1
  Perim_1_WSHP Supply Side (Return Air) Inlet Node, !- Component Inlet Node Name 1
  Perim_1_WSHP_CoilClg Unitary Inlet Node, !- Component Outlet Node Name 1
  AirLoopHVAC:UnitarySystem,              !- Component Object Type 2
  Perim_1_WSHP_CoilClg Unitary,           !- Component Name 2
  Perim_1_WSHP_CoilClg Unitary Inlet Node, !- Component Inlet Node Name 2
  Perim_1_WSHP_CoilClg Unitary Outlet Node, !- Component Outlet Node Name 2
  AirLoopHVAC:UnitarySystem,              !- Component Object Type 3
  Perim_1_WSHP_CoilHtg Unitary,           !- Component Name 3
  Perim_1_WSHP_CoilClg Unitary Outlet Node, !- Component Inlet Node Name 3
  Perim_1_WSHP_CoilHtg Unitary Outlet Node, !- Component Outlet Node Name 3
  Fan:VariableVolume,                     !- Component Object Type 4
  Perim_1_WSHP_Fan,                       !- Component Name 4
  Perim_1_WSHP_CoilHtg Unitary Outlet Node, !- Component Inlet Node Name 4
  Perim_1_WSHP_Fan Outlet Node;           !- Component Outlet Node Name 4
```

One small change in both UnitarySystems makes it run. 
image

in v9.4, the system ran fine with either set of inputs.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 25.1.0-9c7c2a6d79
 - Helpdesk ticket number 16739

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #10823
 - Change setpoint controlled unitary system with no fan to leave inlet mass flow rate as is.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -916,8 +916,8 @@ namespace UnitarySystems {
                 this->m_IterationCounter = 0;
                 std::fill(this->m_IterationMode.begin(), this->m_IterationMode.end(), 0);
 
-                // for DX systems, just read the inlet node flow rate and let air loop decide flow
-                if (this->m_ControlType == UnitarySysCtrlType::Setpoint && this->m_sysType == SysType::Unitary) {
+                // for systems without a fan, just read the inlet node flow rate and let air loop decide flow
+                if (this->m_ControlType == UnitarySysCtrlType::Setpoint && this->m_sysType == SysType::Unitary && this->m_FanExists) {
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: Not sure this will work as expected. 1) if it's scheduled off it won't turn off at line 942?, 2) if the control zone is in the deadband the air flow should change to the no load flow at line 936/938 but that can't happen when using constant fan (which is used for Setpoint control) and the no load flow = 0, and 3) what if the unit does have a fan?. So I think you want to move the `&& this->m_FanExists` down to lines 936 (shown) and 938. The tests are if it can turn off when scheduled off, turn back on after flow = 0, and fixes the defect. And then what kind of warning if any to report for this configuration of no fan and no load flow = 0.

    if (this->m_FanExists && this->MaxNoCoolHeatAirMassFlow > 0.0) {
        state.dataLoopNodes->Node(this->AirInNode).MassFlowRate = this->MaxNoCoolHeatAirMassFlow;
    }

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: Oh, lines 936 and 938 are duplicates.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: Does my suggestion matter if a fan is present? If it's in the deadband or load is opposite to that unitarysystem and that unitary system does have a fan, should it turn off if there is a down stream system? This seems tricky.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: Just use the no flow check at line 936 and wait for the next defect?

    if (this->MaxNoCoolHeatAirMassFlow > 0.0) {

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc]: > Does my suggestion matter if a fan is present? If it's in the deadband or load is opposite to that unitarysystem and that unitary system does have a fan, should it turn off if there is a down stream system? This seems tricky.

It didn't seem tricky to me. If the unitary system doesn't have a fan, in my simple view it should not be touching mass flow rates. It should behave like CoilSystem:\*:\*. Or do we promise somewhere that a fanless unitary system should control a fan elsewhere on the branch?

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc]: I think at the very least the unit should turn off if not available and this is independent of a fan? Whether that is an issue with a down stream component or not is a question of coordination of availability managers. I guess another option is to modify this text and docs, where "off" only refers to capacity. With the current change I don't think the unit will ever turn off if desired (how does it turn on?, maybe FirstHVACIteration turns it on?) but then you could always schedule the fan for this configuration. I guess if this meets the current need and doesn't break anything then just forge ahead.

    AirLoopHVAC:UnitarySystem,
      A5,  \field Availability Schedule Name
       \type object-list
       \object-list ScheduleNames
       \note Availability schedule name for this system. Schedule value > 0 means the system is available.
       \note If this field is blank, the system is always available.
       \note A schedule value greater than zero (usually 1 is used) indicates that the unit is
       \note available to operate as needed. A value less than or equal to zero (usually zero
       \note is used) denotes that the unit must be off.

    Fan:SystemModel,
      A2 , \field Availability Schedule Name
       \note Availability schedule name for this fan. Schedule value > 0 means the fan is available.
       \note If this field is blank, the fan is always available.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc]: The availability schedule is checked again in `controlCoolingSystemToSP`
https://github.com/NREL/EnergyPlus/blob/4a17be908304e8ca2266863e76a7f790f2fcca19/src/EnergyPlus/UnitarySystem.cc#L12195-L12198
and in `controlHeatingSystemToSP`
https://github.com/NREL/EnergyPlus/blob/4a17be908304e8ca2266863e76a7f790f2fcca19/src/EnergyPlus/UnitarySystem.cc#L14011-L14014
and in `controlSuppHeatSystemToSP`
https://github.com/NREL/EnergyPlus/blob/4a17be908304e8ca2266863e76a7f790f2fcca19/src/EnergyPlus/UnitarySystem.cc#L14649-L14651

so I think the availability schedule question is covered. Without a fan, the unitary system is just a coil wrapper, so if it's off it should just pass through flow and conditions.

**Comment by mjwitte** [comment]
Defect file with develop:
image 
image

With this branch:
image
image

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 2]
```diff
@@ -1438,6 +1438,333 @@ TEST_F(ZoneUnitarySysTest, UnitarySystemModel_MultiSpeedDXCoolCoil_Only)
...
+                      latOut);
+
+    // no cooling, pass thru mass flow rate
+    EXPECT_EQ(state->dataLoopNodes->Node(thisSys->AirInNode).Temp, state->dataLoopNodes->Node(thisSys->AirOutNode).Temp);
+    EXPECT_NEAR(thisSys->m_CoolingCycRatio, 0.0, 0.001);
+    EXPECT_EQ(thisSys->m_CoolingSpeedRatio, 0);
+    EXPECT_EQ(thisSys->m_CoolingSpeedNum, 0);
+    EXPECT_EQ(state->dataLoopNodes->Node(thisSys->AirInNode).MassFlowRate, 1.2);
+    EXPECT_EQ(state->dataLoopNodes->Node(thisSys->AirInNode).MassFlowRate, state->dataLoopNodes->Node(thisSys->AirOutNode).MassFlowRate);
+}
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc]: This does appear to work as expected.

**Comment by nrel-bot-2** [comment]
@mjwitte it has been 16 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte it has been 7 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@Myoldmopar I've merged in develop, and there are still no CI diffs. This is ready as long as @rraustad is ok with it.

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -887,8 +887,8 @@ namespace UnitarySystems {
...
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:891]: When using SP control, for airloop equipment the node flow rate is used, for zone equipment the equipment flow rate is used. So my question here is if zone equipment still works with this change. See this at the bottom of UnitarySys::setAverageAirFlow. I;m not sure if there is an example file or unit test for this case.

        if (ScheduleManager::GetCurrentScheduleValue(state, this->m_SysAvailSchedPtr) > 0.0 &&
            ((FanOn || state.dataHVACGlobal->TurnFansOn) && !state.dataHVACGlobal->TurnFansOff)) {
            if (this->m_ControlType == UnitarySysCtrlType::Setpoint) {
                // set point based equipment should use VAV terminal units to set the flow.
                // zone equipment needs to set flow since no other device regulates flow (ZoneHVAC /= AirLoopEquipment)
                if (!this->m_AirLoopEquipment) {

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:891]: Maybe just add `&& this->m_AirLoopEquipment` here to cover this? But then zone equipment needs the fan so this looks like it is OK as is.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:891]: We have 2 example files with unitary zone equipment using load control, DOAToUnitarySystem and UnitarySystem_ZoneVSWSHP_wDOAS. Those run fine with no diffs here, as expected since it's load control.

Here's a new one with SP control. 
[UnitarySystem_ZoneVSWSHP_wDOAS-SPControl.idf.txt](https://github.com/user-attachments/files/18523254/UnitarySystem_ZoneVSWSHP_wDOAS-SPControl.idf.txt)
No diffs on this branch for design day and annual.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:891]: Perfect.

**Review by rraustad — APPROVED** [review]
This looks like the correct fix for this issue.

File: src/EnergyPlus/UnitarySystem.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:891]: Should we replace UnitarySystem_ZoneVSWSHP_wDOAS with this file? The change to SP control would still meet the zone SP.

image

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:891]: > Should we replace UnitarySystem_ZoneVSWSHP_wDOAS with this file? The change to SP control would still meet the zone SP.

It should work, but it's not. This is the SP control file, annual, with develop:
image

Since this branch produces the same result, I don't think this should hold up this PR, but it would be nice to figure out how to make this work.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:891]: I'm OK with merging this branch and following up with an issue to correct, or at least investigate,

**Comment by Myoldmopar** [comment]
OK, this one is next.  Testing now.

**Comment by Myoldmopar** [comment]
And again, happy here.  Thanks @mjwitte and @rraustad
