### PR TITLE
Fix 10168 zone multiplier incorrectly applies to water heater tank losses

### LINKED ISSUE #10168: Zone multiplier incorrectly applies to water heater tank losses
Issue overview
--------------
When you have a zone multiplier, all internal gains from e.g. `Equipment` objects are multiplied before the load is calculated for the HVAC system. Good.

However, water heater tank losses are calling the same zone internal gain method ([`SetupZoneInternalGain` method](https://github.com/NREL/EnergyPlus/blob/a87b71bfab996f95ed51e662780a8389550c5ded/src/EnergyPlus/WaterThermalTanks.cc#L5162) for the mixed tank water heater, for example), so the zone multiplier is being applied here as well. The tank losses should not be multiplied by the zone multiplier because, if you are actually trying to model a thermal zone that represents X units, each with its own water heater, you still have to either model 1 water heater with 4x the tank losses or model 4 water heaters -- so the zone multiplier ends up double counted.

A solution could be to update the [`WaterThermalTankData::setupZoneInternalGains` method](https://github.com/NREL/EnergyPlus/blob/a87b71bfab996f95ed51e662780a8389550c5ded/src/EnergyPlus/WaterThermalTanks.cc#L5156) and pass the tank losses divided by the zone multiplier to the `SetupZoneInternalGain` method to counteract that the zone multiplier will be applied. That said, there are probably other objects that have this issue too, so perhaps the `SetupZoneInternalGain` method needs to be updated instead.

cc @mjwitte 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by kevin-moos**
Pull request overview
---------------------

- Fixes #10168

### Description of the purpose of this PR

Fix a defect in which zone multipliers are incorrectly applied to water heater tank losses. Add unit test to show correctly adjusted space gain fraction.

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
@mjwitte this looks OK to me, but I'd defer to you on it.

File: src/EnergyPlus/HeatBalanceInternalHeatGains.cc [hunk 1]
```diff
@@ -76,6 +76,12 @@ void SetupZoneInternalGain(EnergyPlusData &state,
         if (state.dataHeatBal->Zone(ZoneNum).numSpaces > 1) {
             gainFrac = state.dataHeatBal->space(spaceNum).FloorArea / state.dataHeatBal->Zone(ZoneNum).FloorArea;
         }
+        if (std::find(AdjustTankLossMultipliers.begin(), AdjustTankLossMultipliers.end(), IntGainCompType) != AdjustTankLossMultipliers.end()) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceInternalHeatGains.cc]: The method here is sound, but a comment line to explain would be helpful here.
But should this be done at the space level instead of here?  At this point, only zone-level internal gain types call `SetupSpaceInternalGain` directly, so no multiplier adjustment is necessary. However, if at some point in the future the tank loss allows specifying a Zone Name or Space Name, then this adjustment will not get applied.
I think it would be better to move this into `SetupSpaceInternalGain`.

File: src/EnergyPlus/HeatBalanceInternalHeatGains.cc [hunk 2]
```diff
@@ -76,6 +76,12 @@ void SetupZoneInternalGain(EnergyPlusData &state,
...
+            int multiplier = state.dataHeatBal->Zone(ZoneNum).Multiplier * state.dataHeatBal->Zone(ZoneNum).ListMultiplier;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceInternalHeatGains.cc]: Nit picking, this can be `const`

File: src/EnergyPlus/HeatBalanceInternalHeatGains.hh [hunk 3]
```diff
@@ -83,6 +83,13 @@ void SetupSpaceInternalGain(EnergyPlusData &state,
                             int RetNodeNum = 0 // for return air heat gains
 );
 
+// Multipliers are double counted for tank losses - these are the internal gains that need adjust for this
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceInternalHeatGains.hh]: It's not that the multipliers are double counted, but rather the loss should be distributed across the multiplied zones/spaces. Not sure how to say that more simply.

File: src/EnergyPlus/HeatBalanceInternalHeatGains.hh [hunk 4]
```diff
@@ -83,6 +83,13 @@ void SetupSpaceInternalGain(EnergyPlusData &state,
...
+static constexpr std::array<DataHeatBalance::IntGainType, 4> AdjustTankLossMultipliers = {
+    DataHeatBalance::IntGainType::WaterHeaterMixed,
+    DataHeatBalance::IntGainType::WaterHeaterStratified,
+    DataHeatBalance::IntGainType::ThermalStorageChilledWaterMixed,
+    DataHeatBalance::IntGainType::ThermalStorageChilledWaterStratified};
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: If I'm following this correctly, any gain that comes from HVAC, electrical, refrigeration, etc. (anything other than the zone gains like lights, people, etc) should be included in this list. @shorowit ?

File: src/EnergyPlus/HeatBalanceInternalHeatGains.cc (hunk 1 above)
Comment (kevin-moos) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.cc]: Added a comment and moved to SetupSpaceInternalGain

File: src/EnergyPlus/HeatBalanceInternalHeatGains.cc (hunk 2 above)
Comment (kevin-moos) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.cc]: Fixed

File: src/EnergyPlus/HeatBalanceInternalHeatGains.hh (hunk 4 above)
Comment (kevin-moos) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: I did it this way so we could easily add/remove other gains as needed, but beyond water heaters I wasn't sure what to add.

Comment (mitchute) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: I guess this is because the tanks have an ambient zone specified, right? 

Doing a quick search for "Ambient Temperature Zone Name" in the IDD shows the following components:

Chiller:Electric:ASHRAE205
WaterHeater:Mixed
WaterHeater:Stratified
ThermalStorage:ChilledWater:Mixed
ThermalStorage:ChilledWater:Stratified
ThermalStorage:HotWater:Stratified
Pipe:Indoor

Searching "Ambient Zone Name" shows these: 

ZoneHVAC:ForcedAir:UserDefined
AirTerminal:SingleDuct:UserDefined
Coil:UserDefined
PlantComponent:UserDefined
Duct:Loss:Conduction

Do these get handled here too?

Also, we can put a 📌 in this, but we should probably unify these.

Comment (kevin-moos) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: I'll try to test these out and see if any should be added to the list.

**Comment by nrel-bot-2** [comment]
@kevin-moos it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/HeatBalanceInternalHeatGains.hh (hunk 4 above)
Comment (kevin-moos) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: Opened #11365 to address other components with ambient temperature zones

Comment (tanaya-mankad) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: @mitchute , we'd like to prevent this PR from expanding in complexity more than the Issue it was created to resolve, so there's a new issue documenting your concerns so we don't lose track of them. In the meantime, this particular set of changes is ready to finalize.

Comment (mitchute) [reply src/EnergyPlus/HeatBalanceInternalHeatGains.hh:91]: @tanaya-mankad that works. Thanks.

**Comment by mitchute** [comment]
OK, we're all good here. I tested the files from @shorowit [posted here](https://github.com/NREL/EnergyPlus/issues/10168#issuecomment-1715600567), adjusted the water heat factors as suggested, and it all lines up to be different by a factor of 10x, as expected. Adding my 26.1 versions of the files here for the archive.

[1x.idf.txt](https://github.com/user-attachments/files/24534946/1x.idf.txt)
[10x.idf.txt](https://github.com/user-attachments/files/24534961/10x.idf.txt)

Merging
