### PR TITLE
AirloopHVAC:UnitaryHeatCool:VAVChangeoverBypass incorrectly indexes zone loads

### LINKED ISSUE #7283: AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass copressor shuts off causing unmet cooling hours
Issue overview
--------------
AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass compressor turns off when there is still cooling demand. Schedule, Minimum Outlet Air Temperature During Cooling Operation are checked to not cause compress shutdown. There are no EMS in the model. EnergyPlus V8.5 and 9.1 are used to run the model. Attached file illustrates the defect.

Problem seems to be in `GetZoneLoads` in `HVACUnitaryBypassVAV.cc`. `CurDeadBandOrSetback` is checked for `ZoneNum` as opposed to `CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum)`. After making the following changes, the issue is resolved.

```
            if (!CurDeadBandOrSetback(ZoneNum)) {
                if (ZoneLoad > 0.0 && std::abs(ZoneLoad) > SmallLoad) {

```
changed to 
```
            if (!CurDeadBandOrSetback(CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum))) {
                if (ZoneLoad > 0.0 && std::abs(ZoneLoad) > SmallLoad) {

```
Workaround: If there is only 1 AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass object in the input, reorganize the Zone objects in the input file (idf) so that all controlled zones come before any uncontrolled zones. There is no workaround if there are more than 1 AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass in the input file.

[Office_Proposed.zip](https://github.com/NREL/EnergyPlus/files/3134119/Office_Proposed.zip)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
The change fixes #7283. Zone loads are not accounted for correctly when the order of the Zone objects in the EnergyPlus input file includes one or more unconditioned zones within the list or there are multiple systems in the same input file.

Example that will cause a problem in identifying zone loads:
Zone 1 - Conditioned
Zone 2 - Conditioned
Zone 3 - Unconditioned
Zone 4 - Conditioned

Workaround: For simulations that use a single system order the zone objects with conditioned zones first in the input file in the order of the Zone objects. Conditioned zones are those with a ZoneHVAC:EquipmentList object to specify the cooling and heating sequence of the zone equipment. No workaround exists if there are multiple AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass objects in the same file.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [x] Performance: CI Linux results include performance check
 - [x] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
Comparison of the defect file in develop and this branch is shown in #7283.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 1]
```diff
@@ -3522,10 +3523,10 @@ namespace HVACUnitaryBypassVAV {
                     ZoneLoad = 0.0;
                 }
             } else {
-                ZoneLoad = ZoneSysEnergyDemand(CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum)).RemainingOutputRequired;
+                ZoneLoad = ZoneSysEnergyDemand(actualZoneNum).RemainingOutputRequired;
             }
 
-            if (!CurDeadBandOrSetback(ZoneNum)) {
+            if (!CurDeadBandOrSetback(actualZoneNum)) {
```
Comment (rraustad) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc:3529]: Fundamental change that corrects zone indexing in the defect file, this line is what was broken. ZoneNum is the loop index, should have used CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum) here to point to the correct zone. This is why we should always test new features with TWO of them in the test file (e.g., 2 changeover bypass systems).

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 2]
```diff
@@ -3509,11 +3509,12 @@ namespace HVACUnitaryBypassVAV {
...
 
         for (ZoneNum = 1; ZoneNum <= CBVAV(CBVAVNum).NumControlledZones; ++ZoneNum) {
-            if ((CBVAV(CBVAVNum).ZoneSequenceCoolingNum(ZoneNum) > 0) && (CBVAV(CBVAVNum).ZoneSequenceHeatingNum(ZoneNum) > 0)) {
-                ZoneLoadToCoolSPSequenced = ZoneSysEnergyDemand(CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum))
-                                                .SequencedOutputRequiredToCoolingSP(CBVAV(CBVAVNum).ZoneSequenceCoolingNum(ZoneNum));
-                ZoneLoadToHeatSPSequenced = ZoneSysEnergyDemand(CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum))
-                                                .SequencedOutputRequiredToHeatingSP(CBVAV(CBVAVNum).ZoneSequenceHeatingNum(ZoneNum));
+            int actualZoneNum = CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum);
+            int coolSeqNum = CBVAV(CBVAVNum).ZoneSequenceCoolingNum(ZoneNum);
+            int heatSeqNum = CBVAV(CBVAVNum).ZoneSequenceHeatingNum(ZoneNum);
```
Comment (rraustad) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc:3514]: Added these locals to simplify code (and use actualZoneNum on line 3529)

**Comment by rraustad** [comment]
@Myoldmopar simple change here to correct indexing problem.

File: tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc [hunk 3]
```diff
@@ -68,6 +69,8 @@ TEST_F(EnergyPlusFixture, UnitaryBypassVAV_GetInputZoneEquipment)
 
     std::string const idf_objects = delimited_string({
 
+        "Zone,",
+        "  Zone 2;                                 !- Name",
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc:73]: Add another zone so "Zone 1" is the second zone in the Zone() and CurDeadBandOrSetback() arrays.

File: tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc [hunk 4]
```diff
@@ -204,12 +222,12 @@ TEST_F(EnergyPlusFixture, UnitaryBypassVAV_GetInputZoneEquipment)
...
-        "  0.02,                               !- No Load Supply Air Flow Rate {m3/s}",
-        "  0.01,                               !- Cooling Outdoor Air Flow Rate {m3/s}",
-        "  0.01,                               !- Heating Outdoor Air Flow Rate {m3/s}",
-        "  0.01,                               !- No Load Outdoor Air Flow Rate {m3/s}",
+        "  0.021,                               !- Cooling Supply Air Flow Rate {m3/s}",
+        "  0.022,                               !- Heating Supply Air Flow Rate {m3/s}",
+        "  0.023,                               !- No Load Supply Air Flow Rate {m3/s}",
+        "  0.011,                               !- Cooling Outdoor Air Flow Rate {m3/s}",
+        "  0.012,                               !- Heating Outdoor Air Flow Rate {m3/s}",
+        "  0.013,                               !- No Load Outdoor Air Flow Rate {m3/s}",
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc:230]: Just differentiating these so lines 445-450 can test that input was gotten correctly.

File: tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc [hunk 5]
```diff
@@ -397,10 +415,48 @@ TEST_F(EnergyPlusFixture, UnitaryBypassVAV_GetInputZoneEquipment)
...
+    EXPECT_EQ(0.021, cbvav.MaxCoolAirVolFlow);
+    EXPECT_EQ(0.022, cbvav.MaxHeatAirVolFlow);
+    EXPECT_EQ(0.023, cbvav.MaxNoCoolHeatAirVolFlow);
+    EXPECT_EQ(0.023, cbvav.FanVolFlow);
+
+    // test zone indexing for loads 
+    Real64 QZoneReq = 0.0;
+    HVACUnitaryBypassVAV::GetZoneLoads(CBVAVNum, QZoneReq);
+    // should return cooling load for zone 2
+    EXPECT_EQ(-1000.0, QZoneReq);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc:457]: Here's the defect test. Previous code would have found QZoneReq = 0 because CurDeadBandOrSetback(1) = true (and should have been looking at CurDeadBandOrSetback(2) = false). See line 3528/3529 above in HVACUnitaryBypassVAV.cc.

**Comment by nrel-bot-2** [comment]
@rraustad it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@rraustad it has been 8 days since this pull request was last updated.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HVACUnitaryBypassVAV.cc:3529]: Looks like a great, simple fix

File: tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc (hunk 5 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc:457]: This makes really good sense.  A good unit test.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Built and tested locally, verifying the improvement from the develop branch.  

From

image

to

image


CI is happy and code looks good.  Merging.
