### PR TITLE
Equipment Summary Air Heat Recovery Fixes

### LINKED ISSUE #10985: Equipment Summary - Air Heat Recovery table values
### Issue overview

Run any file that uses HeatExchanger:AirToAir:* object and this should properly populate the Equipment Summary - Air Heat Recovery table but several columns are not working.

The first column and the "Name" column seem to always be identical. Maybe we don't need both.

The "Input Object Type" just always shows "generic" instead of "HeatExchanger:AirToAir:SensibleAndLatent" or "HeatExchanger:AirToAir:FlatPlate" or any other.

The "Plate/Rotary" always says "Rotary" (in the test cases I have run) even when Heat Exchanger Type is set to Plate.

The "exhaust airflow" is always zero

The "outdoor airflow" is always zero.

I tried this with ASHRAE901_HotelLarge_STD2019_Denver, DOAToUnitarySystem, HVACStandAloneERV_Economizer example files.

### Operating System (Multiple choices)

Windows

### Operating System Version

10

### Version of EnergyPlus

24.2

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #10985

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Here is a sample of the current table for OutdoorAirUnit.idf.
image


Here are some samples of the revised table. Note the changes from `FlatPlate` to `Plate`, and from `[kg/s]` to `[m3/s]`.

DesiccantDehumidifierWithCompanionCoil
image

ASHRAE901_HotelLarge_STD2019_Denver
image

OutdoorAirUnit
image

File: src/EnergyPlus/HeatRecovery.hh [hunk 1]
```diff
@@ -154,7 +154,7 @@ namespace HeatRecovery {
         int CoolEffectSensibleCurveIndex = 0; // cooling sensible effectiveness multiplier curve to CoolEffectSensible100
         int CoolEffectLatentCurveIndex = 0;   // cooling latent effectiveness multiplier curve to CoolEffectLatent100
         // 1 = None, 2 = Bypass, 3 = Stop Rotary HX Rotation
-        HXConfigurationType ExchConfig = HXConfigurationType::Invalid; // parameter equivalent of HX configuration, plate or rotary
+        HXConfigurationType ExchConfig = HXConfigurationType::Rotary; // parameter equivalent of HX configuration, plate or rotary
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.hh]: Not standard but I assume this was done for the sake of the desiccant HX (as opposed to leaving this as invalid and setting Rotary in the desiccant HX getInput). If no other changes, which I don't expect since these changes and results look good, leave as is.

**Review by rraustad — APPROVED** [review]

File: src/EnergyPlus/HeatRecovery.hh (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/HeatRecovery.hh]: It was a punt to fix a unit test (maybe more than one?) that didn't do `getInput` and was throwing a vector error when trying to fill the table in `size`. I can undo this and set it properly in the unit test and add some `asserts` to protect that.

Comment (rraustad) [reply src/EnergyPlus/HeatRecovery.hh]: This change would be good to get into the latest release so I figured it could go as-is. There's still a few days left so it's up to you how you handle clean-up changes.

Comment (mjwitte) [reply src/EnergyPlus/HeatRecovery.hh]: But there are `OutputChanges` (delete duplicate Name column, and change units on two columns), so I'm not sure this will be allowed in for 25.1. @Myoldmopar?

Comment (rraustad) [reply src/EnergyPlus/HeatRecovery.hh]: OK, then you have plenty of time.

Comment (rraustad) [reply src/EnergyPlus/HeatRecovery.hh]: You can also consider whether to change "Outdoor Airflow" to "Supply AirFlow".

Comment (mjwitte) [reply src/EnergyPlus/HeatRecovery.hh]: > You can also consider whether to change "Outdoor Airflow" to "Supply AirFlow".

Hmm, so they're currently called "Exhaust" and "Outdoor", but the three HXs all use different terminology:
`HeatExchanger:AirToAir:FlatPlate`: Supply and Secondary
`HeatExchanger:AirToAir:SensibleAndLatent`: Supply and Exhaust
`HeatExchanger:Desiccant:BalancedFlow`: Process and Regeneration

@JasonGlazer Any preference?

Comment (JasonGlazer) [reply src/EnergyPlus/HeatRecovery.hh]: It would be good to use a consistent set of terms. I think AHRI probably has a standard on this, maybe we should see what terms it uses.

Comment (mjwitte) [reply src/EnergyPlus/HeatRecovery.hh]: > It would be good to use a consistent set of terms. I think AHRI probably has a standard on this, maybe we should see what terms it uses.

Supply and Exhaust, based on these two docs:
https://www.airxchange.com/wp-content/uploads/2019/07/AHRI-Guideline-W-2005.pdf
https://www.airxchange.com/wp-content/uploads/2019/07/AHRI-Standard-1060-I-P-2013.pdf

**Comment by mjwitte** [comment]
An updated example table.
image

**Comment by rraustad** [comment]
That looks very good. Why 0.63 and 0.43 in lower right corner? Never mind, that's the HX with both inputs.

**Comment by rraustad** [comment]
I just noticed you got rid of the duplicate name column. Put the header column title back as "Name" ?

**Comment by rraustad** [comment]
And maybe change the title "Input object type" to just "Type" like other tables.

**Comment by JasonGlazer** [comment]
Looking good!

**Comment by mjwitte** [comment]
> I just noticed you got rid of the duplicate name column. Put the header column title back as "Name" ?

Well, most table reports have no heading in the first column. 
image

I suppose we could change that. @JasonGlazer is there a way to place a header in the first column with current functions?


> And maybe change the title "Input object type" to just "Type" like other tables.
Ok, done (locally).

**Comment by mjwitte** [comment]
From https://github.com/NREL/EnergyPlus/issues/10985#issuecomment-2734293714
> > I'll go with repeating the nominal supply flow, unless you object.
> 
> Can we report the maximum flow also?

@JasonGlazer Is this still something we want here? It would be a simulation result rather than documenting an input.

**Comment by JasonGlazer** [comment]
> I suppose we could change that. @JasonGlazer is there a way to place a header in the first column with current functions?
> 
> >

I don't think there is a way to do that, but it could be added if it is important.  newPreDefSubTable() could have another optional argument that would be the first column heading. I have thought about this before but decided in the past that it probably didn't matter too much.

**Comment by JasonGlazer** [comment]
> @JasonGlazer Is this still something we want here? It would be a simulation result rather than documenting an input.

Results are welcome!

**Comment by mjwitte** [comment]
Here's the latest version of the table (for OutdoorAirUnit.idf):
image

This is ready for final review after v25.1 is released. (The output changes will need to be moved the the 25.2 file at some point).

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mjwitte @myoldmopar it has been 29 days since this pull request was last updated.

File: src/EnergyPlus/DataHVACGlobals.hh [hunk 2]
```diff
@@ -396,7 +396,7 @@ namespace HVAC {
     {
         Invalid = -1,
         AirToAir_FlatPlate,
-        AirToAir_Generic,
+        AirToAir_SensAndLatent,
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataHVACGlobals.hh:399]: That is a bit nicer naming.

File: src/EnergyPlus/HeatRecovery.cc [hunk 3]
```diff
@@ -1606,63 +1606,70 @@ namespace HeatRecovery {
...
             FieldNum = 1;
             PrintFlag = true;
-            CompName = state.dataHeatRecovery->BalDesDehumPerfData(BalDesDehumPerfIndex).Name;
-            CompType = state.dataHeatRecovery->BalDesDehumPerfData(BalDesDehumPerfIndex).PerfType;
-            SizingString = state.dataHeatRecovery->BalDesDehumPerfData(BalDesDehumPerfIndex).NumericFieldNames(FieldNum) + " [m3/s]";
-            TempSize = state.dataHeatRecovery->BalDesDehumPerfData(BalDesDehumPerfIndex).NomSupAirVolFlow;
+            CompName = thisBDDPerf.Name;
+            CompType = thisBDDPerf.PerfType;
+            SizingString = thisBDDPerf.NumericFieldNames(FieldNum) + " [m3/s]";
+            TempSize = thisBDDPerf.NomSupAirVolFlow;
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatRecovery.cc:1627]: Nice and readable here.

File: src/EnergyPlus/HeatRecovery.cc [hunk 4]
```diff
@@ -1606,63 +1606,70 @@ namespace HeatRecovery {
...
+            OutputReportPredefined::PreDefTableEntry(
+                state, state.dataOutRptPredefined->pdchAirHRLatEffAt100PerHeatAirFlow, this->Name, this->HeatEffectLatent100);
+            OutputReportPredefined::PreDefTableEntry(
+                state, state.dataOutRptPredefined->pdchAirHRLatEffAt100PerCoolAirFlow, this->Name, this->CoolEffectLatent100);
+        } else {
+            OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchAirHRSenEffAt100PerHeatAirFlow, this->Name, "N/A");
+            OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchAirHRSenEffAt100PerCoolAirFlow, this->Name, "N/A");
+            OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchAirHRLatEffAt100PerHeatAirFlow, this->Name, "N/A");
+            OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchAirHRLatEffAt100PerCoolAirFlow, this->Name, "N/A");
+        }
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatRecovery.cc:1674]: Good output report changes here.

File: tst/EnergyPlus/unit/HeatRecovery.unit.cc [hunk 5]
```diff
@@ -4000,6 +4005,22 @@ TEST_F(EnergyPlusFixture, SizeHeatRecovery)
...
+              OutputReportPredefined::RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchAirHRSenEffAt100PerHeatAirFlow, compName));
+    EXPECT_EQ("N/A",
+              OutputReportPredefined::RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchAirHRSenEffAt100PerCoolAirFlow, compName));
+    EXPECT_EQ("N/A",
+              OutputReportPredefined::RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchAirHRLatEffAt100PerHeatAirFlow, compName));
+    EXPECT_EQ("N/A",
+              OutputReportPredefined::RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchAirHRLatEffAt100PerCoolAirFlow, compName));
+
+    EXPECT_EQ("1.00", OutputReportPredefined::RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchAirHRSupplyAirflow, compName));
+    EXPECT_EQ("1.00", OutputReportPredefined::RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchAirHRExhaustAirflow, compName));
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/HeatRecovery.unit.cc:4023]: :+1:

**Review by Myoldmopar — APPROVED** [review]
All good here.  Will run some quick local testing, but expect this to merge shortly.

**Comment by Myoldmopar** [comment]
Needed to resolve conflicts just from the output changes file.  I'll let CI run, but this is all happy locally and should be good to merge shortly.

**Comment by Myoldmopar** [comment]
Alright, this seems ready to go now.  CI is happy, and I just did a sanity check right now.  Thanks @mjwitte !
