### PR TITLE
Fix #9538 ElectricEquipment:ITE:AirCooled Environmental Class Code Specifications

### LINKED ISSUE #9538: Misused Environmental Class code values for ElectricEquipment:ITE:AirCooled ITE Air Inlet Operating Range Exceeded Time and related variables reporting
Issue overview
--------------

While working on implementing Issue #9418 (via PR #9537), some unexpected diffs showed up from the CI regression run results. A further investigation reveals that this is due to a bug in the existing code, where misplaced code values were used in reporting these “exceed time” or “out-of-range” variables (e.g. “ITA Air Inlet Operating Range Exceed Time”). It was found that 27 “exceed time” or “out-of-range” reporting variables could be affected, for all the six Environmental Classes (A1, A2, A3, A4, B, C). 

In the code below, the indices (`EnvClass - 1`) are accidently subtracted one more for the arrays that contain the code specification values for Dry Bulb Temperature, Dewpoint Temperature, and Relative Humidity. The arrays (`DBMax` to `RHMin`) already have the zero-index values filled (for Class "None"). Therefore, the index `[EnvClass - 1]` used in the following code should just be `[EnvClass]`:
https://github.com/NREL/EnergyPlus/blob/d695545c5164c14ea0b88f307c4f782cfae65a4e/src/EnergyPlus/InternalHeatGains.cc#L7966-L7974
This change should also be extended to all the six `if` blocks (for `DBMax`, `DBMin`, `DPMax`, `DPMin`, `RHMax`, and `RHMin` code specification value arrays) from Line 7966 all the way to Line 8019 in the file above.

As a result, the code specification values used for the variable output will be incorrect , in that A2-class equipment will misuse A1 code values, A3 misuses A2’s, …, and C-class misuses B’s code values. The A1-class equipment will then misuse “None”-class code values, which means no restriction on the code values (and would most yield zero exceeding hours). 

The 27 affected output variables across ITE zone, zone report, and space levels are: 
"ITE Air Inlet Operating Range Exceeded Time",
"ITE Air Inlet Dry-Bulb Temperature Above Operating Range Time",
"ITE Air Inlet Dry-Bulb Temperature Below Operating Range Time",
"ITE Air Inlet Dewpoint Temperature Above Operating Range Time",
"ITE Air Inlet Dewpoint Temperature Below Operating Range Time",
"ITE Air Inlet Relative Humidity Above Operating Range Time",
"ITE Air Inlet Relative Humidity Below Operating Range Time",
"ITE Air Inlet Dry-Bulb Temperature Difference Above Operating Range",
"ITE Air Inlet Dry-Bulb Temperature Difference Below Operating Range",
"ITE Air Inlet Dewpoint Temperature Difference Above Operating Range",
"ITE Air Inlet Dewpoint Temperature Difference Below Operating Range",
"ITE Air Inlet Relative Humidity Difference Above Operating Range",
"ITE Air Inlet Relative Humidity Difference Below Operating Range",

"Zone ITE Any Air Inlet Operating Range Exceeded Time",
"Zone ITE Any Air Inlet Dry-Bulb Temperature Above Operating Range Time",
"Zone ITE Any Air Inlet Dry-Bulb Temperature Below Operating Range Time",
"Zone ITE Any Air Inlet Dewpoint Temperature Above Operating Range Time",
"Zone ITE Any Air Inlet Dewpoint Temperature Below Operating Range Time",
"Zone ITE Any Air Inlet Relative Humidity Above Operating Range Time",
"Zone ITE Any Air Inlet Relative Humidity Below Operating Range Time",

"Space ITE Any Air Inlet Operating Range Exceeded Time",
"Space ITE Any Air Inlet Dry-Bulb Temperature Above Operating Range Time",
"Space ITE Any Air Inlet Dry-Bulb Temperature Below Operating Range Time",
"Space ITE Any Air Inlet Dewpoint Temperature Above Operating Range Time",
"Space ITE Any Air Inlet Dewpoint Temperature Below Operating Range Time",
"Space ITE Any Air Inlet Relative Humidity Above Operating Range Time",
"Space ITE Any Air Inlet Relative Humidity Below Operating Range Time",

There might be a partial workaround---when inputting the `Environmental Class` field in ElectricEquipment:ITE:AirCooled, a higher class could be used instead---e.g. for actual A1-class equipment, input A2 in the `Environmental Class` field; for B-class equipment, input C; and for actual “None”-class equipment, input A1. This workaround should work for equipment classed from “None”- class to B (None, A1, A2, A3, A4, B). However, for actual C-class equipment, there is no workaround to do the trick. 

This bug should be fixed and tested clean, preferably prior to Issue #9418 work, since it is interfering with the diffs expectations for the new development. Code changes will be needed for a full fix, which will follow soon. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.2 pre-release, most recent develop branch
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (just use any of the following example test files: 1ZoneDataCenterCRAC_wApproachTemp.idf, 1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf, and 2ZoneDataCenterHVAC_wEconomizer.idf)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9538:
 - Fixed the indices for arrays that contains the building or equipment energy code specification values for ITE air-cooled equipment; 
 - Added a new test file that contains another two types of Environmental Classes---A1, and A2---by revising from one of the test files that original contains A3-class ITE equipment: considering which might be a better place to add, in current PR or PR 9537?
 - Potential diffs are expected on test files containing ElectricEquipment:ITE:AirCooled object(s); but would be from the expected correction. The newly added test file with A1 and A2 classes if compared (maybe not be run in the CI comparison since it is a new addition), should also exhibit some diffs, which are expected. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/InternalHeatGains.cc [hunk 1]
```diff
@@ -7963,55 +7963,55 @@ namespace InternalHeatGains {
...
                     state.dataHeatBal->ZoneITEq(Loop).TimeOutOfOperRange = state.dataGlobal->TimeStepZone;
-                    state.dataHeatBal->ZoneITEq(Loop).RHAboveDeltaRH = RHAirIn - RHMax[EnvClass - 1];
+                    state.dataHeatBal->ZoneITEq(Loop).RHAboveDeltaRH = RHAirIn - RHMax[EnvClass];
                     state.dataHeatBal->ZnRpt(NZ).ITEqTimeAboveRH = state.dataGlobal->TimeStepZone;
                     state.dataHeatBal->ZnRpt(NZ).ITEqTimeOutOfOperRange = state.dataGlobal->TimeStepZone;
                     state.dataHeatBal->spaceRpt(spaceNum).ITEqTimeAboveRH = state.dataGlobal->TimeStepZone;
                     state.dataHeatBal->spaceRpt(spaceNum).ITEqTimeOutOfOperRange = state.dataGlobal->TimeStepZone;
                 }
-                if (RHAirIn < RHMin[EnvClass - 1]) {
+                if (RHAirIn < RHMin[EnvClass]) {
```
Comment (jcyuan2020) [inline src/EnergyPlus/InternalHeatGains.cc:8011]: This is the key change--using the EnvClass without more subtraction.

File: testfiles/CMakeLists.txt [hunk 2]
```diff
@@ -17,6 +17,7 @@ add_simulation_test(IDF_FILE VSHeatPumpWaterToAirWithRHControl.idf EPW_FILE USA_
 add_simulation_test(IDF_FILE 1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf EPW_FILE USA_CO_Golden-NREL.724666_TMY3.epw)
 add_simulation_test(IDF_FILE 1ZoneDataCenterCRAC_wApproachTemp.idf EPW_FILE USA_CO_Golden-NREL.724666_TMY3.epw)
 add_simulation_test(IDF_FILE 2ZoneDataCenterHVAC_wEconomizer.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
+add_simulation_test(IDF_FILE 2ZoneDataCenterHVAC_wEconomizer_ClassA1A2.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
```
Comment (jcyuan2020) [inline testfiles/CMakeLists.txt:20]: The original test file set does not contain any case with any other class of ITE equipment other than A3. Here added one new test file that contains A1 and A2 by simply revising from a file that contains two A3 class ITE equipment. This could also help the CI to detect potential problems in future development.

File: tst/EnergyPlus/unit/InternalHeatGains.unit.cc [hunk 3]
```diff
@@ -2600,3 +2600,363 @@ TEST_F(EnergyPlusFixture, ITEwithUncontrolledZoneTest)
     EXPECT_NEAR(calculatedResult3, expectedResult3, tol);
     EXPECT_NEAR(calculatedResult4, expectedResult4, tol);
 }
+
+TEST_F(EnergyPlusFixture, ITE_Env_Class_Fix_41C)
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/InternalHeatGains.unit.cc:2604]: Two unit cases are added: the first one is for 41C supply air temperature, which will trigger the reporting in "exceed time"  reports; and the second one is for 39C supply air temperature, which after the fix, should not trigger any "exceed time" or "out-of-range" reports. However, the second unit test, if tested in the original code without the fix, would still trigger the reports (and the unit test will fail).

**Comment by Myoldmopar** [comment]
This has some unused variable build warnings that should be cleaned.  Otherwise CI is as expected with just a few data center files showing diffs.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 4]
```diff
@@ -7963,55 +7963,55 @@ namespace InternalHeatGains {
             // Check environmental class operating range limits (defined as parameters in this subroutine)
             EnvClass = state.dataHeatBal->ZoneITEq(Loop).Class;
             if (EnvClass > 0) {
-                if (TAirIn > DBMax[EnvClass - 1]) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/InternalHeatGains.cc:7966]: Off by one, classic.

File: tst/EnergyPlus/unit/InternalHeatGains.unit.cc [hunk 5]
```diff
@@ -2600,3 +2600,363 @@ TEST_F(EnergyPlusFixture, ITEwithUncontrolledZoneTest)
...
+        "  0.0,                     !- Minimum Value of x",
+        "  99.0;                    !- Maximum Value of x",
+    });
+
+    static constexpr std::array<Real64, 7> DBMin = {-99.0, 15.0, 10.0, 5.0, 5.0, 5.0, 5.0};           // Minimum dry-bulb temperature [C]
+    static constexpr std::array<Real64, 7> DBMax = {99.0, 32.0, 35.0, 40.0, 45.0, 35.0, 40.0};        // Maximum dry-bulb temperature [C]
+    static constexpr std::array<Real64, 7> DPMin = {-99.0, -99.0, -99.0, -12.0, -12.0, -99.0, -99.0}; // Minimum dewpoint temperature [C]
+    static constexpr std::array<Real64, 7> DPMax = {99.0, 17.0, 21.0, 24.0, 24.0, 28.0, 28.0};        // Maximum dewpoint temperature [C]
+    static constexpr std::array<Real64, 7> RHMin = {0.0, 20.0, 20.0, 8.0, 8.0, 8.0, 8.0};             // Minimum relative humidity [%]
+    static constexpr std::array<Real64, 7> RHMax = {99.0, 80.0, 80.0, 85.0, 90.0, 80.0, 80.0};        // Maximum relative humidity [%]
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/InternalHeatGains.unit.cc:2703]: These are the unused variables, did you intend on using them?

```suggestion

```

**Review by Myoldmopar — CHANGES_REQUESTED** [review]
Seems like a reasonable set of changes.  I'll mark it as request changes until we get rid of the build warnings, but then I would think this will merge.

File: tst/EnergyPlus/unit/InternalHeatGains.unit.cc (hunk 5 above)
Comment (jcyuan2020) [reply tst/EnergyPlus/unit/InternalHeatGains.unit.cc:2703]: Thanks! The unit test is now updated with more test lines added that would use these variables.

Comment (Myoldmopar) [reply tst/EnergyPlus/unit/InternalHeatGains.unit.cc:2703]: Got it.  Thanks.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Looks good now; assuming CI is happy then this should be ready to merge.

**Comment by Myoldmopar** [comment]
OK, this one next, pulling in latest develop and testing locally.

**Comment by Myoldmopar** [comment]
Everything very happy here, merging.  Thanks @jcyuan2020
