### PR TITLE
Corrects crash in DOAS fan sizing

### LINKED ISSUE #10814: AirLoopHVAC:DedicatedOutdoorAirSystem vector issue in sizing
Issue overview
--------------
User file fails here in debug:

https://github.com/NREL/EnergyPlus/blob/ec7398adcfbd2ba6bc71e72b57e3febb6cd99708/src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc#L779-L782

`this->curSysNum` = 2, but `state.dataSize->SysSizPeakDDNum` size is only 1.

Seems related to the  fixes in #10334 ?

Here's the call stack.
image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 25.1-ec7398a
 - Helpdesk ticket number 16791.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #10814
 - Fans used in DAOS were not accounted for during sizing

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc [hunk 1]
```diff
@@ -777,24 +777,63 @@ Real64 SystemAirFlowSizer::size(EnergyPlusData &state, Real64 _originalValue, bo
...
+                            // Parent object sets heating flow rate
+                            this->autoSizedValue = std::max(this->oaSysEqSizing(this->curOASysNum).CoolingAirVolFlow,
+                                                            this->oaSysEqSizing(this->curOASysNum).HeatingAirVolFlow);
+                        } else if (outsideAirSys(this->curOASysNum).AirLoopDOASNum > -1) {
+                            this->autoSizedValue =
+                                this->airloopDOAS[outsideAirSys(this->curOASysNum).AirLoopDOASNum].SizingMassFlow / state.dataEnvrn->StdRhoAir;
+                        } else {
+                            this->autoSizedValue = this->finalSysSizing(this->curSysNum).DesOutAirVolFlow;
+                        }
+                    } else {
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc:823]: The code change is from here to line 780 above. The below is just git confusion.

**Comment by rraustad** [comment]
The defect file now runs, and shows confusing fan sizing, since both fans are autosize, as:

image

And the peak day is of course blank:

image

**Comment by rraustad** [comment]
The DOAS fans are being read in as autosize

image

but when the extract fan gets to sizing it is set to a hard flow rate. I can't find where this is happening. The DOAS supply fan doesn't have this issue and sizes normally for an autosized fan (i.e., [the first table here](https://github.com/NREL/EnergyPlus/pull/10816#issuecomment-2462832594)).

image

**Comment by rraustad** [comment]
OK, the extract fan flow is getting set here, but I don't understand the timing or why this needs to be done. The supply fan doesn't get called in this order.

image

**Comment by rraustad** [comment]
If I comment out line 997 I get:

image

**Comment by nrel-bot-2** [comment]
@rraustad it has been 13 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Review by mjwitte — APPROVED** [review]
Works as advertised. Unit tests all pass. Thanks @rraustad  Will merge after CI completes another round.

**Comment by mjwitte** [comment]
@rraustad Is this kind of diff expected?
image

**Comment by rraustad** [comment]
@mjwitte I will have to look at that file.

**Comment by rraustad** [comment]
@mjwitte this is clean now. The 1 diff in SmallOffice_CentralDOAS is because the autosizing of the fan is not stomped on by the AirloopHVACDOAS code.

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      AirLoopHVAC DOAS,        !- Name
      AirLoopDOAS OA system,   !- AirLoopHVAC:OutdoorAirSystem Name

    AirLoopHVAC:OutdoorAirSystem,
      AirLoopDOAS OA system,   !- Name
      OA Sys 1 Controllers,    !- Controller List Name
      OA Sys 1 Equipment;      !- Outdoor Air Equipment List Name

    AirLoopHVAC:OutdoorAirSystem:EquipmentList,
      OA Sys 1 Equipment,      !- Name
      Fan:SystemModel,         !- Component 1 Object Type
      OA Supply Fan,           !- Component 1 Name

    Fan:SystemModel,
      OA Supply Fan,           !- Name
      Autosize,                !- Design Maximum Air Flow Rate {m3/s}

image

Code no longer writes to the fan object:

image

File: src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc [hunk 2]
```diff
@@ -777,13 +777,38 @@ Real64 SystemAirFlowSizer::size(EnergyPlusData &state, Real64 _originalValue, bo
...
 
                 } else {
-                    auto &sysSizPeakDDNum = state.dataSize->SysSizPeakDDNum(this->curSysNum);
-
-                    if (this->airLoopSysFlag) {
-                        auto const &unitarysysEqSizing = this->unitarySysEqSizing(this->curSysNum);
-                        if (unitarysysEqSizing.CoolingAirFlow && unitarysysEqSizing.HeatingAirFlow) {
-                            this->autoSizedValue = std::max(unitarysysEqSizing.CoolingAirVolFlow, unitarysysEqSizing.HeatingAirVolFlow);
-                            if (this->autoSizedValue == unitarysysEqSizing.CoolingAirVolFlow) {
+                    if (this->curOASysNum > 0) {
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc:780]: Feels a little weird to size the OA system fan using the air loop flow rate (instead of using DesOutAirVolFlow) but that's what happened before and is how the MaxOA gets sized for the OA controller.

**Review by mjwitte — APPROVED** [review]
Much better. Thanks @rraustad

**Review by Myoldmopar — APPROVED** [review]
OK, this seems fine.  Unit test included, so that is good to go.  I will do a quick local test, but intend on dropping this in shortly.

**Comment by Myoldmopar** [comment]
This is happy with latest develop in build, test, format, and code integrity checks.  Good to go in.  Thanks @rraustad and @mjwitte
