### PR TITLE
 Fixes Supervisory Control Logic Problem For AirSource Plants 

### LINKED ISSUE #10417: Supervisory Control Logic Problem For AirSource Plants
Issue overview
--------------
While testing, the supervisory control logic for AirSource Heat Pump dispatch shows that the AWHP cooling coil was off even when there was a building cooling load and a plant cooling load. 

Stepping through the code shows that the cooling plant equipment is off while the plant heating equipment is on. This control logic was determined primarily by comparing the building's heating and cooling loads. However, in this specific case, there is a building and the cooling plant cooling load, while there is a larger building heating load with no plant heating load. Since the plant equipment dispatch is based on the building load, this situation leads to turning off the AWHP cooling coil, and as a consequence, the cooling plant loop setpoints won't be met, and the cooling coil exhibits unrealistic air and water outlet node temperatures. See the plots below.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #10417
 - This change impacts simple AWHP cooling and AWHP heating equipment in the primary plant with no heat recovery HPs. 
 - The cooling plant is now dispatched instead of the heating plant, where no heating was required by the HW plant, even though the building cooling load is smaller than the building heating load and vice versa.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Nigusse** [comment]
The plot below shows the Cooling and Heating Coils Inlet and outlet air temperatures for develop and this branch. Also, the plot includes the CW inlet and outlet node water temperatures before and after the fix. The temperature profiles depict normal operation since the cooling plant equipment is On after the fix.

WaterCoilTempCompare

**Comment by Nigusse** [comment]
Cooling coil water inlet and outlet node temperatures and CW flow rate plots for the Develop branch and this Branch. After the fix shows, the cooling plant loop temperature setpoint is met, and the CW temperature difference across the coil is reasonable.

WaterCoilTempFlowCompare

File: src/EnergyPlus/Plant/EquipAndOperations.cc [hunk 1]
```diff
@@ -993,6 +993,28 @@ namespace DataPlant {
...
+        // override reset AirSourcePlantHeatingOnly to false and AirSourcePlantCoolingOnly to true if the plant cooling load is higher
+        // the plant heating load and the plant heating load is small.
+        if (!this->PlantOps.AirSourcePlantCoolingOnly && this->PlantOps.AirSourcePlantHeatingOnly &&
+            !this->PlantOps.AirSourcePlantSimultaneousHeatingAndCooling) { // all off
+            if (std::abs(this->Report.PrimaryPlantCoolingLoad) > this->Report.PrimaryPlantHeatingLoad &&
+                this->Report.PrimaryPlantHeatingLoad < DataHVACGlobals::SmallLoad) {
+                this->PlantOps.AirSourcePlantCoolingOnly = true;
+                this->PlantOps.AirSourcePlantHeatingOnly = false;
+            }
+        }
```
Comment (Nigusse) [inline src/EnergyPlus/Plant/EquipAndOperations.cc:1005]: This change is intended to turn the cooling plant equipment `ON` when the cooling plant loop load is larger than the heating plant loop load, and the plant heating load is very small or `zero.`  This change alters equipment dispatch determined based on the building's aggregate cooling and heating loads only.

File: src/EnergyPlus/Plant/EquipAndOperations.cc [hunk 2]
```diff
@@ -993,6 +993,28 @@ namespace DataPlant {
...
+        // override reset AirSourcePlantHeatingOnly to true and AirSourcePlantCoolingOnly to false if the plant heating load is higher
+        // the plant cooling load and the plant cooling load is small.
+        if (this->PlantOps.AirSourcePlantCoolingOnly && !this->PlantOps.AirSourcePlantHeatingOnly &&
+            !this->PlantOps.AirSourcePlantSimultaneousHeatingAndCooling) { // all off
+            if (this->Report.PrimaryPlantHeatingLoad > std::abs(this->Report.PrimaryPlantCoolingLoad) &&
+                this->Report.PrimaryPlantCoolingLoad > DataPrecisionGlobals::constant_minusone * DataHVACGlobals::SmallLoad) {
+                this->PlantOps.AirSourcePlantHeatingOnly = true;
+                this->PlantOps.AirSourcePlantCoolingOnly = false;
+            }
+        }
```
Comment (Nigusse) [inline src/EnergyPlus/Plant/EquipAndOperations.cc:1016]: Similarly, this change is intended to turn the heating plant equipment `ON` when the heating plant loop load is larger than the cooling plant loop load, and the plant cooling load is very small or `zero.`

**Comment by rraustad** [comment]
I have reviewed this code change and the results. I discussed this change with @Nigusse before changes were made and the results are as expected (i.e., the cooling plant is now dispached instead of the heating plant where no heating was required by the HW plant, even though the building loads showed there was a -2200 W zone cooling load to SP and a 7000 W ventilation load). This defect file is a simple AWHP cooling and AWHP heating equipment in the primary plant with no heat recovery HPs. This code change is an attempt to improve dispatch logic/controls without affecting existing logic. i.e., switch dispatch if the "plant" shows a load and the "building" loads dispatched wrong plant equipment but only if the equipment dispatched shows a 0 plant load, to avoid changing other logic for more complex plant configurations. Dispatch logic will likely continue to evolve over time. @EnergyArchmage should also review this change.

File: src/EnergyPlus/Plant/EquipAndOperations.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/Plant/EquipAndOperations.cc:1016]: This is an inconsequential suggestion and will not change results. But these 2 new IF blocks were inserted "between" 2 off blocks (the off block for cooling and off block for heating). From a code organization perspective it would have been better to place these new IF blocks above line 988. Wait for all comments before making any further changes, if any. If a unit test is planned, this change could be made at that time.

**Comment by Nigusse** [comment]
Minor annual energy use differences were observed for the defect IDF. Pump and fan annual electric energy use decreased while the annual (heating) natural gas use increased. Overall, this Branch has slightly more (0.96%) annual total energy use than Develop, but the annual total electric energy use has reduced.

EndUseComparison

**Comment by Nigusse** [comment]
The regression test shows that the `EvaluateChillerHeaterChangeoverOpSchemeTest` failed, but this unit test runs fine on my local machine in debug and release build modes.

**Comment by Myoldmopar** [comment]
Windows failure is unrelated.  I'll pull develop in here and get fresh results.

**Comment by Myoldmopar** [comment]
CI is all green, I'll take a look and see if this can also merge.

**Review by Myoldmopar — APPROVED** [review]
This is fine enough.  I agree with @rraustad that maybe we can organize it a bit better, but it's fine for now.

**Comment by Myoldmopar** [comment]
Thanks @Nigusse, merging.
