### PR TITLE
Correction of Defect in Transition Program and Recent Bug Fix

### LINKED ISSUE #8968: Sizing:Zone below-zero (degree C) Zone Cooling Design Supply Air Temperature scenarios for freezer spaces
Issue overview
--------------

For the Sizing:Zone object, there is a recent discussion on how to give warning messages on the zone cooling design supply air temperature that is below 0 degree C (#8855, #8827). A user recently sent in a simulation case modeling a freezer space which uses a -20 C design cooling supply temperature---which may call for the need to lift that restriction. 

Also, there is a running failure to report: 

During the process of diagnosing an issue the user reported (which is actually not related to Sizing:Zone design supply air temperature), the v9.5 case file was upgraded to pre-release v9.6 (commit ed3a9d36c8). Now there is another severe error message with “bad allocation”. The failing point seems to be an out-of-bound allocation at lines: 
https://github.com/NREL/EnergyPlus/blob/ed3a9d36c86aad48000128ae7975805818f1e207/src/EnergyPlus/SizingManager.cc#L3376-L3381

With this example file, the `(paramNum-2)` index will have a value of -1 (here `paramNum` is 1), which causes an out-of-bound (bad allocation) failure in this particular case. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): pre-release v9.6 only
 - Helpdesk ticket number: 15770

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/8000s/8968))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #8995: AIRLOOPHVAC:OUTDOORAIRSYSTEM transitions for the 3-line cases
Issue overview
--------------
In earlier versions, the AIRLOOPHVAC:OUTDOORAIRSYSTEM can take a block of either 3-line or 4-line inputs. The new transition for v9.6 is now dropping the last line (`Availability Manager List Name`) to make it a 3-line object. This is working well for the 4-line case---the newly transition filed will be reduced to a 3-line object by dropping the redundant `Availability Manager List Name` line. 

However, earlier versions also allow a 3-line version of the AIRLOOPHVAC:OUTDOORAIRSYSTEM without a fourth line (so no `Availability Manager List Name` line)—for example, according to v9.5 IOReferece, this 3-line version is also a valid input. Now there is a conversion problem. If this type of 3-line version is converted up to v9.6 (pre-release), it will be reduced to a 2-line object, which will immediately cause an error when running the newly transitioned idf case (since the third line is essential and should not be dropped). 

The root cause  should be here
https://github.com/NREL/EnergyPlus/blob/163a5b006fe9c924428b0e43410b2afd5a166ee0/src/Transition/CreateNewIDFUsingRulesV9_6_0.f90#L400
where `CurArgs` should be reduced by 1 only for the 4-line version, but be kept the same for the 3-line version. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): pre-release v9.6 (e.g. 163a5b006f)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #8995
 - Fixes #8968 
 - Minor issues with two recent defects.  In #8995, the transition program was truncating valid input for the AirLoopHVAC:OutdoorAirSystem.  The old input (pre-v9.6) had four fields.  The last field was never used and thus removed in the previous defect fix.  However, the transition program changes ended up with a truncated input line under certain conditions.  This is now fixed.  In #8968, there were a few minor bugs that didn't get noticed before merging.  These are also fixed with this PR.
 - Fixes error introduced for transitions older than v9.6 (introduced in #8394 )

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/Transition/CreateNewIDFUsingRulesV9_6_0.f90 [hunk 1]
```diff
@@ -397,7 +397,9 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
                   CALL GetNewObjectDefInIDD(ObjectName,NwNumArgs,NwAorN,NwReqFld,NwObjMinFlds,NwFldNames,NwFldDefaults,NwFldUnits)
                   nodiff=.false.
                   OutArgs(1:3)=InArgs(1:3)
-                  CurArgs = CurArgs - 1
+                  IF (CurArgs == 4) THEN
+                      CurArgs = 3
```
Comment (jcyuan2020) [inline src/Transition/CreateNewIDFUsingRulesV9_6_0.f90:401]: That looks good! I tested again on both a 4-line case and a 3-line case, it works fine on both cases.

**Review by mjwitte — APPROVED** [review]
Small changes, looks good on paper. When CI comes back green, will merge.

**Comment by mjwitte** [comment]
So, I realized that the transition changes to VCompareGlobalRoutines.f90 in the Space branch broke any transition prior to v9.6 when writing surface objects with grouped veritces (x,y,z on the same idf line) which is just about always. I added a fix to this branch to set the field numbers based on whether the transition version is <9.6. @jcyuan2020 @Myoldmopar I've tested locally, but a few random older transitions should be tested as well as the v9.6 transition to be sure this is all good.

File: src/EnergyPlus/SizingManager.cc [hunk 2]
```diff
@@ -3011,9 +3011,9 @@ void GetZoneSizingInput(EnergyPlusData &state)
                 if (state.dataIPShortCut->lNumericFieldBlanks(3)) {
                     state.dataSize->ZoneSizingInput(ZoneSizIndex).HeatDesTemp = 0.0;
                 } else if (state.dataSize->ZoneSizingInput(ZoneSizIndex).ZnHeatDgnSAMethod == SupplyAirTemperature) {
-                    ReportTemperatureInputError(state, cCurrentModuleObject, 1, lowTempLimit, false, ErrorsFound);
+                    ReportTemperatureInputError(state, cCurrentModuleObject, 3, lowTempLimit, false, ErrorsFound);
                     ReportTemperatureInputError(
-                        state, cCurrentModuleObject, 1, state.dataSize->ZoneSizingInput(ZoneSizIndex).CoolDesTemp, true, ErrorsFound);
+                        state, cCurrentModuleObject, 3, state.dataSize->ZoneSizingInput(ZoneSizIndex).CoolDesTemp, true, ErrorsFound);
                     state.dataSize->ZoneSizingInput(ZoneSizIndex).HeatDesTemp = state.dataIPShortCut->rNumericArgs(3);
```
Comment (jcyuan2020) [inline src/EnergyPlus/SizingManager.cc]: This is also been tested to working using a defect file that contains a -20C supply temperature in a Sizing:Zone object. 

In a quick summary it is working as expected and fixed the problem well---and actually in this defect file case, even though the Sizing:Zone has an input value of -20C for supply temperature, it should not cause a warning in the defect file as the defect file as the object actually specifies a "temperature difference" method---and this should also add to the point when it is a bug before. After the fix the problem is fixed; and no warning for the defect file on this zone (because it uses the temperature difference method): 
image

A little bit complication about this test file is that with the difference method, the user specified a 11.11C temperature difference in Sizing:Zone and the zone thermostat is set to 2C---this means that the supply is around -9.11. I original thought that this is the reason why the warning is flagged.--but actually it should not be. According to the code's original intention, it should only flag the below zero supply temperature with `SupplyAirTemperature` method. Therefore from this point it is also a bug. 

I think the new fix nice fixed this and it is now clear that the warning is given only when a below-zero supply air temperature is inputted together with the "SupplyAirTemperature" method. If a user selects the "temperature difference", then even though a negative supply air temperature is inferred from the inputs, it would not (and also probably should not) give a warning.

**Comment by jcyuan2020** [comment]
@mjwitte I will try a few cases on the space-related new transition changes next.

**Comment by jcyuan2020** [comment]
For the space-related transitions, I tried a few more cases with 9.4 version and it is confirmed working. Without the fix, it will have a long list of warnings complaining the geometry fields in the transition audit file when going to the point from 9.5->9.6---for example, like this:
```
Conversion 9.5 => 9.6
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- C:\EnergyPlus\_Code_Review\PR_8995_Transition_Fixes\Upgrade_Test_develop\5ZoneAirCooled.idf
   ** Warning ** Invalid Number in Numeric Field#4 (Vertex 1 Y-coordinate), value=BuildingSurface:Detailed, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#5 (Vertex 1 Z-coordinate), value=WALL-1PR, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#6 (Vertex 2 X-coordinate), value=WALL, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#7 (Vertex 2 Y-coordinate), value=WALL-1, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#8 (Vertex 2 Z-coordinate), value=PLENUM-1, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#9 (Vertex 3 X-coordinate), value=Outdoors, in BuildingSurface:Detailed=WALL-1PF
   ** Severe  ** Error detected in Object=BuildingSurface:Detailed, name=WALL-1PF
   **   ~~~   ** Field [Vertex 3 Y-coordinate] is required but was blank
   ** Warning ** Invalid Number in Numeric Field#11 (Vertex 3 Z-coordinate), value=SunExposed, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#12 (Vertex 4 X-coordinate), value=WindExposed, in BuildingSurface:Detailed=WALL-1PF
   ** Warning ** Invalid Number in Numeric Field#4 (Vertex 1 Y-coordinate), value=BuildingSurface:Detailed, in BuildingSurface:Detailed=WALL-1PL
   ** Warning ** Invalid Number in Numeric Field#5 (Vertex 1 Z-coordinate), value=TOP-1, in BuildingSurface:Detailed=WALL-1PL
   ** Warning ** Invalid Number in Numeric Field#6 (Vertex 2 X-coordinate), value=ROOF, in BuildingSurface:Detailed=WALL-1PL
   ** Warning ** Invalid Number in Numeric Field#7 (Vertex 2 Y-coordinate), value=ROOF-1, in BuildingSurface:Detailed=WALL-1PL
   ** Warning ** Invalid Number in Numeric Field#8 (Vertex 2 Z-coordinate), value=PLENUM-1, in BuildingSurface:Detailed=WALL-1PL
   ** Warning ** Invalid Number in Numeric Field#9 (Vertex 3 X-coordinate), value=Outdoors, in BuildingSurface:Detailed=WALL-1PL
   ** Severe  ** Error detected in Object=BuildingSurface:Detailed, name=WALL-1PL
   **   ~~~   ** Field [Vertex 3 Y-coordinate] is required but was blank
   ** Warning ** Invalid Number in Numeric Field#11 (Vertex 3 Z-coordinate), value=SunExposed, in BuildingSurface:Detailed=WALL-1PL
   ** Warning ** Invalid Number in Numeric Field#12 (Vertex 4 X-coordinate), value=WindExposed, in BuildingSurface:Detailed=WALL-1PL
...
```

Now with the fix, the transition results and audit reports will just come out clean: 
```
Conversion 9.5 => 9.6
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- C:\Users\jinch\Dropbox\Wk_GARD\EnergyPlus_Compile\_Code_Review\PR_8995_Transition_Fixes\Upgrade_Tests_MJW_8995\5ZoneAirCooled.idf
 Processing rvi -- C:\Users\jinch\Dropbox\Wk_GARD\EnergyPlus_Compile\_Code_Review\PR_8995_Transition_Fixes\Upgrade_Tests_MJW_8995\5ZoneAirCooled.rvi
```

**Comment by Myoldmopar** [comment]
I haven't looked at the diffs, but generally this seems fine.  Anything else needed here outside of a bit more testing?

**Comment by mjwitte** [comment]
@Myoldmopar Nothing more that I know of.

**Comment by mjwitte** [comment]
I wouldn't expect any diffs here, so this may need a fresh regression to be sure.

**Comment by Myoldmopar** [comment]
Pulled develop in, we'll see how it does

**Comment by rraustad** [comment]
@mjwitte this PR is independent of #9019 and can be merged as is? with no other changes expected? Once reviewed and tested that is.

**Comment by mjwitte** [comment]
@rraustad Yes, this is separate from #9019.

**Comment by Myoldmopar** [comment]
Obviously CI looks much happier now.  I will try to run a test this evening or in the morning and get this in.

File: src/Transition/VCompareGlobalRoutines.f90 [hunk 3]
```diff
@@ -799,31 +808,32 @@ SUBROUTINE CheckSpecialObjects(DifUnit,ObjectName,CurArgs,OutArgs,FieldNames,Fie
           CALL WriteOutIDFLinesAsSingleLine(DifUnit,ObjectName,CurArgs,OutArgs,FieldNames,FieldUnits)
 
         CASE('BUILDINGSURFACE:DETAILED')
+          NVertFieldNum = 10 + SurfaceSpaceFieldShift
           IF (MakeUPPERCase(OutArgs(11)) == 'AUTOCALCULATE') THEN
```
Comment (rraustad) [inline src/Transition/VCompareGlobalRoutines.f90]: What about this line? "11" has been replaced with NVertFieldNum and line 812 has OutArgs(11). For input files > V9.2 and < V9.6, this would be OutArgs(10), right? So OutArgs(NVertFieldNum) here as well.

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: Well, this does convert a V9.4 file to V9.5 so maybe this is OK.

image

Comment (mjwitte) [reply src/Transition/VCompareGlobalRoutines.f90]: @rraustad Good catch. I can fix shortly, or feel free to push a fix yourself.

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: Oh, it's when the number of vertices field is AutoCalculate when there is a problem. So this does need to change.

image

Comment (mjwitte) [reply src/Transition/VCompareGlobalRoutines.f90]: Try that same file with Number of Vertices = autocalculate.

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: I'll build and test this again before I commit.

Comment (mjwitte) [reply src/Transition/VCompareGlobalRoutines.f90]: Ok, thanks. Is the [IDF Editor error mentioned yesterday](https://github.com/NREL/EnergyPlus/pull/9019#issuecomment-910903398) still a problem?

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: I'm not sure, I was just updating an UnmetHours file and saw that. I actually think it was an ill formed input file. I guess I should also open the transitioned file in IDFEditor for this test as well. Can't hurt to check everything we can think of.

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: Transition worked but opening transitioned file in IDF Editor shows an error. 

image

Here is the transitioned OA Sys object. This is V9.4 -> V9.5.

  AirLoopHVAC:OutdoorAirSystem,
    Outside Air System,      !- Name
    Outside Air System Controllers,  !- Controller List Name
    Outside Air System Equipment,  !- Outdoor Air Equipment List Name
    Evap Cooler Availability List;  !- Availability Manager List Name

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: Sorry, was using V9.6 IDF Editor.

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: OK, the above issue is resolved using V9.5 IDF Editor and the transition above for V9.5 AirLoopHVAC:OutdoorAirSystem is correct.

Comment (rraustad) [reply src/Transition/VCompareGlobalRoutines.f90]: I can't think of anything else to test so am committing this change.

**Comment by mjwitte** [comment]
@rraustad Anything left to do here?

**Comment by rraustad** [comment]
Well, I still see the ConvectionAdaptiveSmallOffice issue on this branch. I guess we could assume that is not related and get this merged.

**Comment by mjwitte** [comment]
Hmm, the changes in this branch only show transition now. @RKStrand Looks like those changes already merged with https://github.com/NREL/EnergyPlus/pull/9026 ? Please confirm.
*those changes* --> *other Energyplus changes*

**Comment by RKStrand** [comment]
@mjwitte Yes, the changes to EnergyPlus were already merged with #9026.  This PR is only the correction of the transition program.
