### PR TITLE
4973 heatpump defrost bug

### LINKED ISSUE #4973: DX heating coil defrost operation causes increase in coil COP
I have noticed that DX heating coil defrost operation causes an unexpected increase in coil COP (applies to both SingleSpeed and MultiSpeed coils; not tested for VariableSpeed). The following plots are from testing a MultiSpeed coil with identical performance curves for the two speeds and no part load cycling losses.

This issue is best seen by plotting hourly coil COP (calculated as `Heating Coil Total Heating Energy` / `Heating Coil Electric Energy`) against the outdoor drybulb temperature. There is an increase in COP of ~0.5 for temperatures below 0ºC, when defrost operates. Compare this to the COP values resulting from the EIR vs. T curve output (shown in blue). I can't think of any reason why defrost operation should increase the coil COP. 
screen shot 2015-06-17 at 4 06 28 pm

The same effect can be seen when looking at a time-series plot:
screen shot 2015-06-17 at 4 06 40 pm
screen shot 2015-06-17 at 4 06 46 pm

The above results are using `Resistive` defrost with `Timed` control, but I see the same effect for `ReverseCycle` defrost and using `OnDemand` control. I confirmed that changing the maximum defrost temperature changes the temperature below which this increase in COP occurs.

idf and associated files to be uploaded by @nmerket.

### PR DESCRIPTION
**Pull request by nmerket**
Fixes #4973

I still owe you one more unit test for single speed heat pumps.

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -8203,6 +8203,7 @@ Label50: ;
 		Real64 AirVolumeFlowRate; // Air volume flow rate across the cooling coil [m3/s]
 		Real64 VolFlowperRatedTotCap; // Air volume flow rate divided by rated total cooling capacity [m3/s-W]
 		Real64 TotCap; // gross total cooling capacity at off-rated conditions [W]
+		Real64 TotCapAdj; // adjusted total cooling capacity at off-rated conditions [W]
 		Real64 TotCapTempModFac; // Total capacity modifier (function of entering drybulb, outside drybulb) depending
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8207]: TotCap is no longer needed?

File: src/EnergyPlus/DXCoils.cc [hunk 2]
```diff
@@ -8405,13 +8406,14 @@ Label50: ;
 			// Modify total heating capacity based on defrost heating capacity multiplier
 			// MaxHeatCap passed from parent object VRF Condenser and is used to limit capacity of TU's to that available from condenser
 			if ( present( MaxHeatCap ) ) {
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8408]: OK, yes TotCap is needed prior to these calculations. I hate this view.

File: src/EnergyPlus/DXCoils.cc [hunk 3]
```diff
@@ -8405,13 +8406,14 @@ Label50: ;
...
-				TotCap = min( MaxHeatCap, TotCap * HeatingCapacityMultiplier );
+				TotCapAdj = min( MaxHeatCap, TotCap * HeatingCapacityMultiplier );
+				TotCap = min( MaxHeatCap, TotCap );
 			} else {
-				TotCap *= HeatingCapacityMultiplier;
+				TotCapAdj = TotCap * HeatingCapacityMultiplier;
 			}
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8413]: Here we have a total heating capacity, unadjusted and adjusted due to defrost.

File: src/EnergyPlus/DXCoils.cc [hunk 4]
```diff
@@ -8405,13 +8406,14 @@ Label50: ;
...
 
 			// Calculate full load outlet conditions
-			FullLoadOutAirEnth = InletAirEnthalpy + TotCap / AirMassFlow;
+			FullLoadOutAirEnth = InletAirEnthalpy + TotCapAdj / AirMassFlow;
 			FullLoadOutAirHumRat = InletAirHumRat;
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8417]: This looks correct as it does the same thing as before.

File: src/EnergyPlus/DXCoils.cc [hunk 5]
```diff
@@ -8456,7 +8458,7 @@ Label50: ;
 			}
 			EIR = DXCoil( DXCoilNum ).RatedEIR( Mode ) * EIRTempModFac * EIRFlowModFac;
 			// Calculate modified PartLoadRatio due to defrost (reverse-cycle defrost only)
-			PLRHeating = min( 1.0, ( PartLoadRatio + LoadDueToDefrost / TotCap ) );
+			PLRHeating = min( 1.0, ( PartLoadRatio + LoadDueToDefrost / TotCapAdj ) );
 			if ( DXCoil( DXCoilNum ).DXCoilType_Num != CoilVRF_Heating ) {
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8462]: This one is tricky. What do we add to PLR? It's the heating load missed (assumed calculated correctly) to the available heating capacity. Here PLR is the ratio of load to available heating capacity wo defrost. So do we add load missed divided by available or adjusted heating capacity? I think it's the former, but your guess is as good as mine here. How do I resolve this one?

**Comment by nmerket** [comment]
@rraustad Thanks for the speedy review. I created an explanation of what I did here:
http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/4969350/notebooks/defrostcop.ipynb

File: src/EnergyPlus/DXCoils.cc [hunk 6]
```diff
@@ -10407,9 +10409,12 @@ Label50: ;
 		Real64 OutletAirHumRat; // outlet air humidity ratio [kg/kg]
 		Real64 TotCapHS; // total capacity at high speed [W]
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: Now this view has skipped to the multispeed coil function (so no more changes to CalcDXHeatingCoil). I have to go to the code to see what's next. This would make me ask why change the power calculation in Multispeed coil and not single-speed coil?

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: Remaining calc's are:

```
        // if cycling fan, send coil part-load fraction to on/off fan via HVACDataGlobals
        if ( FanOpMode == CycFanCycCoil ) OnOffFanPartLoadFraction = PLF;
        DXCoil( DXCoilNum ).ElecHeatingPower = TotCap * EIR * DXCoil( DXCoilNum ).HeatingCoilRuntimeFraction * InputPowerMultiplier;

        // Calculate crankcase heater power using the runtime fraction for this DX heating coil only if there is no companion DX coil.
        // Else use the largest runtime fraction of this DX heating coil and the companion DX cooling coil.

        if ( DXCoil( DXCoilNum ).CompanionUpstreamDXCoil == 0 ) {
            DXCoil( DXCoilNum ).CrankcaseHeaterPower = CrankcaseHeatingPower * ( 1.0 - DXCoil( DXCoilNum ).HeatingCoilRuntimeFraction );
        } else {
            DXCoil( DXCoilNum ).CrankcaseHeaterPower = CrankcaseHeatingPower * ( 1.0 - max( DXCoil( DXCoilNum ).HeatingCoilRuntimeFraction, DXCoil( DXCoil( DXCoilNum ).CompanionUpstreamDXCoil ).CoolingCoilRuntimeFraction ) );
        }

        AirMassFlow = DXCoil( DXCoilNum ).InletAirMassFlowRate;
        DXCoil( DXCoilNum ).TotalHeatingEnergyRate = AirMassFlow * ( OutletAirEnthalpy - InletAirEnthalpy );
        // Adjust defrost power to correct for DOE-2 bug where defrost power is constant regardless of compressor runtime fraction
        // Defrosts happen based on compressor run time (frost buildup on outdoor coil), not total elapsed time.
        DXCoil( DXCoilNum ).DefrostPower *= DXCoil( DXCoilNum ).HeatingCoilRuntimeFraction;

        DXCoil( DXCoilNum ).OutletAirTemp = OutletAirTemp;
        DXCoil( DXCoilNum ).OutletAirHumRat = OutletAirHumRat;
        DXCoil( DXCoilNum ).OutletAirEnthalpy = OutletAirEnthalpy;
        DXCoil( DXCoilNum ).CompressorPartLoadRatio = PartLoadRatio;
```

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: Let's assume that DXCoil( DXCoilNum ).ElecHeatingPower is calculated correctly for now. The only other thing that might need checking is crankcase heater power, based on RTF, which is based on PLRHeating. Again, how to resolve these as being correctly calculated.

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: This equation looks correct to me:
DXCoil( DXCoilNum ).ElecHeatingPower = TotCap \* EIR \* DXCoil( DXCoilNum ).HeatingCoilRuntimeFraction \* InputPowerMultiplier;

TotCap \* EIR is the power wo defrost, and TotCap \* EIR \* InputPowerMultiplier is the power with defrost.

I would add that the zone load does not change due to "resistive" defrost and the heating capacity needed to meet that load, purely for heating sake, should not change. Reverse cycle defrost is very different.

Lastly, COP is externally calculated so nothing else to review here.

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: I should probably stop here and let this sink in. What we decide here should then be applied to multispeed coils.

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: Looking at the 2 equations for InputPowerMult (B) and HeatingCapMult (y), Heating Capacity falls off more quickly (-107) than Power (-36) as delta w increases. This would result in COP decreasing with increasing delta w which makes sense. I think these are the tests needed to resolve which equations get modified (I'm still unsure of PLRHeating). Can we first plot existing capacity/power vs delta w to see what that looks like. Then modify equations and plot again. Each time noting COP.

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: Would either need full load operation or divide by RTF to get back there. Dividing by RTF is tricky since RTF is also modified by defrost operation. I'd have to see both versions.

File: src/EnergyPlus/DXCoils.cc (hunk 4 above)
Comment (nmerket) [inline src/EnergyPlus/DXCoils.cc:8417]: Yes, it does do the same thing as before--use an adjusted capacity for most of the calculations. The adjusted capacity was just stored in `TotCap` before so that any time it was used afterwards the adjusted capacity was used. I replaced all those instances with `TotCapAdj` to explicitly indicate that. The only different calculation is now `DXCoil( DXCoilNum ).ElecHeatingPower`, which uses `TotCap`, which is now the unadjusted capacity. Therefore that line didn't change and it's why you're not seeing it in this diff view.

File: src/EnergyPlus/DXCoils.cc (hunk 6 above)
Comment (nmerket) [inline src/EnergyPlus/DXCoils.cc:10410]: @rraustad I'm trying to get those plots, but capacity and delta w aren't energyplus outputs so it's turning out to be more effort that I would like.

File: src/EnergyPlus/DXCoils.cc (hunk 5 above)
Comment (nmerket) [inline src/EnergyPlus/DXCoils.cc:8462]: This PLR thing is a great question without a clear answer. It's not really part of the bug I'm fixing here, though. The reason this line changed is because I changed a variable name above (`TotCap` to `TotCapAdj`). The calculation here remains identical.

**Comment by nmerket** [comment]
@rraustad I added some plots of power vs. delta w to my [analysis notebook](http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/4969350/notebooks/defrostcop.ipynb). 

I think this is ready to go.

File: src/EnergyPlus/DXCoils.cc (hunk 5 above)
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8462]: Not part of the bug nor no clear answer, I agree. Changing to be the same as before is acceptable.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 7]
```diff
@@ -279,3 +279,525 @@ namespace EnergyPlus {
 	}
 
 }
+
+TEST( DXCoilsTest, TestMultiSpeedDefrostCOP )
```
Comment (mbadams5) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: @nmerket You need to move this and the other unit test within the `namespace EnergyPlus { }` in this unit test file. Also, if you switch this to `TEST_F( HVACFixture, DXCoils_TestMultiSpeedDefrostCOP )` the compile errors should go away.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 8]
```diff
@@ -279,3 +279,525 @@ namespace EnergyPlus {
...
+	EXPECT_LT( COPwDefrost, COPwoDefrost );
+	
+	// Defroster off
+	OutDryBulbTemp = 5.0; // not cold enough for defroster
+	CalcMultiSpeedDXCoilHeating( DXCoilNum, SpeedRatio, CycRatio, SpeedNum, FanOpMode );
+	COPwoDefrost = Coil.MSRatedCOP( SpeedNum ) / ( CurveValue(nEIRfT1, Coil.InletAirTemp, OutDryBulbTemp) * CurveValue(nEIRfFF1, 1));
+	COPwDefrost = Coil.TotalHeatingEnergyRate / Coil.ElecHeatingPower;
+	EXPECT_DOUBLE_EQ( COPwoDefrost, COPwDefrost );
+	
+	// Clean up
```
Comment (mbadams5) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: @nmerket If you use `TEST_F( HVACFixture, foo )` then you no longer need this clean up here. The Fixture will take care of it for you now. Same in the other unit test.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 9]
```diff
@@ -279,3 +279,525 @@ namespace EnergyPlus {
...
+	using CurveManager::NumCurves;
+	using EnergyPlus::DataEnvironment::OutHumRat;
+	using EnergyPlus::DataEnvironment::OutDryBulbTemp;
+	using EnergyPlus::DataEnvironment::OutBaroPress;
+	using DXCoils::CalcMultiSpeedDXCoilHeating;
+	int DXCoilNum;
+	
+	// Set up heating coil and curves.
+	
+	InitializePsychRoutines();
```
Comment (mbadams5) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: @nmerket The HVACFixture takes care of this as well so this is no longer needed here.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 10]
```diff
@@ -279,3 +279,525 @@ namespace EnergyPlus {
...
+	NumDXCoils = 1;
+	DXCoilNum = 1;
+	DXCoil.allocate( NumDXCoils );
+	DXCoilData & Coil = DXCoil( DXCoilNum );
+	
+	Coil.DXCoilType = "Coil:Heating:DX:MultiSpeed";
```
Comment (mbadams5) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: @nmerket Also, you could change all this follow code to build out the data structure of the Coil:Heating:DX:MultiSpeed and curves to use the new process_idf() unit test helper function. Examples are [here](https://github.com/NREL/EnergyPlus/blob/41b2d221b08550306859c207782e07ae05e18b93/tst/EnergyPlus/unit/Humidifiers.unit.cc#L151-186), [here](https://github.com/NREL/EnergyPlus/blob/41b2d221b08550306859c207782e07ae05e18b93/tst/EnergyPlus/unit/Humidifiers.unit.cc#L188-246), or [here](https://github.com/NREL/EnergyPlus/blob/41b2d221b08550306859c207782e07ae05e18b93/tst/EnergyPlus/unit/MixedAir.unit.cc#L15-98). That said, since you already have all this code completed and functioning it is not necessary to change to the new process_idf() approach. I would still change to the HVACFixture though to fix the compile errors and make sure all clean up of state variables happens automatically.

File: src/EnergyPlus/DXCoils.cc (hunk 3 above)
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8413]: Where is TotCap in the else part of this IF?

File: src/EnergyPlus/DXCoils.cc (hunk 6 above)
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: As best I can tell, since I'm not sure what power would have been wo defrost, that plot does appear to show that power is now slightly higher during defrost which makes sense. I imagine the wo defrost power line would split the two. Since capacity didn't change, I guess there is no reason to plot.

File: tst/EnergyPlus/unit/DXCoils.unit.cc (hunk 7 above)
Comment (mbadams5) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: You might still need to add `#include <DataEnvironment.hh>` to the top of this file to fix the compile errors, even with the change to HVACFixture.

File: src/EnergyPlus/DXCoils.cc (hunk 6 above)
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:10410]: Since all you did was split out TotCap w and wo defrost and then use them in appropriate places, I would agree that this looks correct.

File: src/EnergyPlus/DXCoils.cc (hunk 3 above)
Comment (nmerket) [inline src/EnergyPlus/DXCoils.cc:8413]: Oh, good point. It should be 

``` c++
TotCap = min( MaxHeatCap, TotCap );
```

here as well. I'll make that change.

Comment (nmerket) [inline src/EnergyPlus/DXCoils.cc:8413]: Actually it doesn't need to be changed because `TotCap` should remain the same in the else clause.

Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:8413]: OK, right. This IF only applies the limit of MaxHeatCap if VRF is used. Otherwise, TotCap remains the same.

**Comment by nmerket** [comment]
@Myoldmopar  I feel like this is ready. What's the next step on getting this merged?

**Comment by Myoldmopar** [comment]
Umm, looks like @rraustad reviewed this quite thoroughly, so I'd say assign this PR and the Pivotal ticket to him and ask him to push that big green button right there and accept the ticket.

**Comment by rraustad** [comment]
We still need a method to compare diff's in example files. One file does show eio diff's, which is an indicator that simulation results also changed (but by how much?). Since this issue was addressed through code changes to correct calculations, diff's are expected. Accepting changes and merging.
