### PR TITLE
Provide a correct field index to report field input in an error message for Coil:Cooling:DX:MultiSpeed

### LINKED ISSUE #10121: Wrong input in the error message in Coil:Cooling:DX:MultiSpeed
Issue overview
--------------
When I intended to input wrong names for the Speed x Part Load Fraction Correlation Curve Name fields in the Coil:Cooling:DX:MultiSpeed object by modifying an example file of MultiSpeedHeatPump.idf, the field inputs in the error message provide the inputs of Speed x Energy Input Ratio Function of Flow Fraction Curve Name fields:

Program Version,EnergyPlus, Version 23.1.0-87ed9199d4, YMD=2023.07.20 13:32,
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="HEAT PUMP ACDXCOIL 1", invalid
   **   ~~~   ** ...not found Speed 1 Part Load Fraction Correlation Curve Name="HPACCOOLEIRFF SPEED 1".
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="HEAT PUMP ACDXCOIL 1", invalid
   **   ~~~   ** ...not found Speed 2 Part Load Fraction Correlation Curve Name="HPACCOOLEIRFF SPEED 2".
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="HEAT PUMP ACDXCOIL 1", invalid
   **   ~~~   ** ...not found Speed 3 Part Load Fraction Correlation Curve Name="HPACCOOLEIRFF SPEED 3".
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="HEAT PUMP ACDXCOIL 1", invalid
   **   ~~~   ** ...not found Speed 4 Part Load Fraction Correlation Curve Name="HPACCOOLEIRFF SPEED 4".
   **  Fatal  ** GetDXCoils: Errors found in getting Coil:Cooling:DX:MultiSpeed input. Preceding condition(s) causes termination.

Correct error message is needed to provide right information for users to make correction.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (list location of defect file here)
 - [X] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
 - Fixes #10121 
 - Error checking finds an input error without PLR function for Coil:Cooling:DX:MultiSpeed. The reported PLR input is wrong due to incorrect index. The fix corrects index error.
 - The test file is uploaded

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ X] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ X] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -4194,7 +4194,7 @@ void GetDXCoils(EnergyPlusData &state)
                     ShowContinueError(state, format("...required {} is blank.", cAlphaFields(17 + (I - 1) * 6)));
                 } else {
                     ShowSevereError(state, format("{}{}=\"{}\", invalid", RoutineName, CurrentModuleObject, thisDXCoil.Name));
-                    ShowContinueError(state, format("...not found {}=\"{}\".", cAlphaFields(17 + (I - 1) * 6), Alphas(16 + (I - 1) * 6)));
+                    ShowContinueError(state, format("...not found {}=\"{}\".", cAlphaFields(17 + (I - 1) * 6), Alphas(17 + (I - 1) * 6)));
```
Comment (lgu1234) [inline src/EnergyPlus/DXCoils.cc:4197]: Wrong index for field A17

**Comment by Myoldmopar** [comment]
This is a simple, great fix, with a good test.  I pulled develop locally and everything tests happily.  Merging, thanks @lgu1234
