### PR TITLE
#7388 -  Non UTF-8 characters throwing false blank name error

### LINKED ISSUE #7388: Non UTF-8 characters throwing false blank name error
Issue overview
--------------
Non-UTF-8 characters causing false blank name error. The defect file from #7048 fails in v9.2.0-26151c5477 with this error:
```
   ** Severe  ** <root>[Construction] - Object contains properties that could not be validated using 'properties' or 'additionalProperties' constraints
   ** Severe  ** <root>[Construction] - Object name is required and cannot be blank or whitespace
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
```
@Nigusse [traced the problem](https://github.com/NREL/EnergyPlus/issues/7048#issuecomment-504454488) to this object:
```
  Construction,
    solaio pavimento(1°piano)/2°piano,  !- Name
```

@mbadams5 [commented](https://github.com/NREL/EnergyPlus/issues/7048#issuecomment-505223437): ... if the characters are UTF-8, it should just work. If they are not UTF-8 then it should still not be a blank name.

Using a text editor to convert the file to UTF-8 eliminates the blank name error. So, it appears that the original file is not UTF-8.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0-26151c5477

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
Note this file has been modified slightly to avoid the original problems in #7048. The ...UTF-8 file runs to completion, the other one fails with blank name.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7388 
 - Non UTF-8 characters throwing false blank name error

This PR includes #8005 which deals with the third party dependency bumps only.
A test was added.

The last commit is optional, and allows latin1 characters to go through. Basically RE2 (the regex engine used) is strict about UTF8 unless you tell it to parse as latin1.
valijson official uses std::regex, which is fine about non utf8 chars.

I'm not sure it is better to allow these non strictly-utf8 names through than throw a specific warning about encoding. The specific defect file on E+ DevSupport will run fine with the last commit though.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
@Myoldmopar @mbadams5 if you can, feel free to weigh in on the optional commit to allow latin1 characters. https://github.com/NREL/EnergyPlus/pull/8006/commits/3b74470783f89fc91d5acb7590ae20f6bdbcccea I'm not going to be able to say either way on that one.

I'm gonna do some testing locally.

**Comment by mbadams5** [comment]
I don't think we should allow Latin1 characters in validation. The JSON library can only handle UTF-8 characters, and while it can ignore or replace non-UTF-8 characters, I'd rather fail sooner. I think it is appropriate for validation to throw an error if it cannot parse as UTF-8 (with an appropriate error message).

**Comment by Myoldmopar** [comment]
> I'd rather fail sooner.

I'm all in favor of this.  If I understand correctly, we need to revert 3b7447078.  I can do that, pull in latest develop, and push.

**Comment by Myoldmopar** [comment]
Pulled in latest develop, reverted latin1 commit, and built.  Unit tests all pass.  I think this will be good to go if CI agrees.

File: src/EnergyPlus/InputProcessing/InputValidation.cc [hunk 1]
```diff
@@ -100,10 +104,12 @@ bool Validation::validate(json const &parsed_input)
                     context += *it;
 
                 errors_.emplace_back(context + " - " + error.description);
-                if (max_context == 2 &&
-                    error.description ==
-                        "Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: ''.") {
-                    errors_.emplace_back(context + " - Object name is required and cannot be blank or whitespace");
+                if (max_context == 2) {
+                    if (error.description == nameError) { // C++20: should mark this [[likely]]
```
Comment (Myoldmopar) [inline src/EnergyPlus/InputProcessing/InputValidation.cc:108]: In this case, since we are doing string comparisons, and also this is just in the input processing part of the run, and also this is not expected to be a common occurrence, I'm not sure we'll need to add the `[[likely]]` declaration.  But in any case, the error handling change is good.

File: tst/EnergyPlus/unit/InputProcessor.unit.cc [hunk 2]
```diff
@@ -623,6 +623,39 @@ TEST_F(InputProcessorFixture, parse_bad_utf_8_json_3)
...
 }
 
+TEST_F(InputProcessorFixture, parse_latin1_json)
+{
+
+    // Test for #7388 -  Non UTF-8 characters throwing false blank name error
+
+    std::string const idf(delimited_string({
+        "  Construction,",
+        "    \x31\xB0\x70\x69\x61\x6E\x6F,  !- Name",
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/InputProcessor.unit.cc:633]: Did someone let Elon Musk name this construction object?

File: tst/EnergyPlus/unit/InputProcessor.unit.cc [hunk 3]
```diff
@@ -623,6 +623,39 @@ TEST_F(InputProcessorFixture, parse_bad_utf_8_json_3)
...
+    EXPECT_EQ("<root>[Construction] - Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: '1\xB0piano'.", errors[0]);
+    EXPECT_EQ("<root>[Construction] - Object name is required and cannot be blank or whitespace, and must be UTF-8 encoded", errors[1]);
+
+
+    json &epJSON = getEpJSON();
+
+    auto it = epJSON.find("Construction");
+    ASSERT_NE(it, epJSON.end());
+    auto iit = it->begin();
+    EXPECT_EQ("1\xB0piano", iit.key());
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/InputProcessor.unit.cc:655]: :+1:

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Good to go.  Thanks @jmarrec for the fix and @mbadams5 for chiming in.

File: tst/EnergyPlus/unit/InputProcessor.unit.cc (hunk 2 above)
Comment (jmarrec) [reply tst/EnergyPlus/unit/InputProcessor.unit.cc:633]: :) I'm just faking a latin1 encoding here. In the Defect file, the only "problem" is the use of `°`  and the fact that the file is latin-1 encoded (well, a derivative, it's probably a Windows-1252 if I were to guess)
