### PR TITLE
Fix #9331 - Crash if window construction is zero due to bad construction name

### LINKED ISSUE #9331: Crash if window construction is zero due to bad construction name
Issue overview
--------------
If a window has an illegal construction name, it will crash with a zero construction number here:

https://github.com/NREL/EnergyPlus/blob/d93483085694987b6e2b4aeb8e294d2b2060d844/src/EnergyPlus/SurfaceGeometry.cc#L5936-L5944

This is actually a redundant check that happens earlier except this spot doesn't reset the divider num to zero so that could be added here and then delete the failing if block?

https://github.com/NREL/EnergyPlus/blob/d93483085694987b6e2b4aeb8e294d2b2060d844/src/EnergyPlus/SurfaceGeometry.cc#L5898-L5903

Stumbled across this while testing #9324 because I added a space to the Construction:WindowDataFile name, but forgot to change the construction name in the window and ran with a debug build.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.1-IOFreeze-Plus

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added - should fail with any file with a bad window construction name
     - MCVE at https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9331/mcve.idf   
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9331

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 1]
```diff
@@ -4997,7 +4997,10 @@ namespace SurfaceGeometry {
                                        cCurrentModuleObject,
                                        state.dataSurfaceGeometry->SurfaceTmp(SurfNum).Name,
                                        SurfaceNumProp));
+                // For the remaining of the routine, as soon as ErrorsFound is true, we just skip to the next subsurface
+                // no point in more checks, the subsurface is invalid, and it could lead to a crash (cf #9331). Eventually, a Fatal will be issued
                 ErrorsFound = true;
+                continue;
```
Comment (rraustad) [inline src/EnergyPlus/SurfaceGeometry.cc]: I don't have a problem with using a continue when "very" severe errors are found. But I wonder if there are some errors that won't show up until the user fixes the first one found. It may not be necessary to continue on some of these warnings so that as many warnings could be reported the first time through. Which one of these input errors actually causes the crash?

Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc]: I understand the sentiment here.  If we could issue all 3 errors up front on the subsurface, it would be good to let the user know all 3 errors right away.  Otherwise they will end up possibly running 3 iterations to solve all the issues.  But I also understand the idea of wanting to avoid issues from subsequent checking.  I could be swayed either way.  Perhaps some extra description of the exact errors we are bypassing by each `continue` would help.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 2]
```diff
@@ -10171,3 +10171,107 @@ TEST_F(EnergyPlusFixture, SurfaceGeometry_GetVerticesDropDuplicates)
...
+    EXPECT_TRUE(ErrorsFound);
+
+    std::string const error_string = delimited_string({
+        "   ** Severe  ** FenestrationSurface:Detailed=\"SURFACE 8 - TRIANGULARWINDOW\", invalid Construction Name=\"WRONG CONSTRUCTION\".",
+        "   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.",
+        "   ...Summary of Errors that led to program termination:",
+        "   ..... Reference severe error count=1",
+        "   ..... Last severe error=FenestrationSurface:Detailed=\"SURFACE 8 - TRIANGULARWINDOW\", invalid Construction Name=\"WRONG CONSTRUCTION\".",
+    });
+    EXPECT_TRUE(compare_err_stream(error_string, true));
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:10276]: :+1:

**Review by Myoldmopar — COMMENTED** [review]
Not marking this approved or not yet, I need to think about it a bit more.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 1 above)
Comment (jmarrec) [reply src/EnergyPlus/SurfaceGeometry.cc]: I am perfectly fine if we revert https://github.com/NREL/EnergyPlus/pull/9646/commits/dcbda05e987d9151667f8aa8348b4d939a5618c3, the https://github.com/NREL/EnergyPlus/pull/9646/commits/59f5c65ca8600189ff909a9621c20ec3cee2cef0 is enough to avoid the crash

Comment (jmarrec) [reply src/EnergyPlus/SurfaceGeometry.cc]: Side note: I actually have a stashed commit that went even further and wrapped every `GetXXX` call inside an `if (!ErrorsFound)` so it'll bail early here: https://github.com/NREL/EnergyPlus/blob/0c3de81b8389ee097c1f00f0172036ca5320444f/src/EnergyPlus/SurfaceGeometry.cc#L1284-L1347

Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc]: @jmarrec I think I will take the offer of just reverting the commit.  That will allow the fix to go in without having to worry about this new pattern.  I'll revert and test it out locally to make sure, then push it up and get this merged.

**Comment by Myoldmopar** [comment]
Everything happy after reverting that.  We can certainly discuss the idea of early exits, but for now this is a nice minimal change plus test.  Thanks!

**Comment by Myoldmopar** [comment]
Not waiting on any CI to run this, merging it in.
