### PR TITLE
Fix AirTerminal:SingleDuct:UserDefined crash (accessing uninitialized but unneeded AirDistUnit array)

### LINKED ISSUE #10507: AirTerminal:SingleDuct:UserDefined cannot find matching outlet node in ZoneHVAC:AirDistributionUnit
Issue overview
--------------
User file shows a severe warning that appears to be a result of reading in the UserDefined air terminal before the AirDistributionUnit object is read in. Also of note is that the UserDefined air terminal does not use the ADUNum struct variable as far as I can tell.

    ** Severe  ** GetUserDefinedComponents: No matching Air Distribution Unit for AirTerminal:SingleDuct:UserDefined = AIRMIXER
    **   ~~~   ** ...should have outlet node=TUNNELINLET

https://unmethours.com/question/98954/error-in-userdefined-hvac-objects-assembled/?answer=99039#post-id-99039

UserDefinedNodeError

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([test1.zip](https://github.com/NREL/EnergyPlus/files/15338228/test1.zip))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by tanaya-mankad**
Pull request overview
---------------------

- Fixes #10507 

### Description of the purpose of this PR

Two user-defined types were being initialized in the same function, GetUserDefinedComponents. This conflation led to AirTerminal objects having ZoneHVAC objects' needs being applied to them, when their members hadn't yet been sized. A solution was to pull the "Get" methods into two separate methods, fixing a copy-paste typo along the way. Also, since so many of the objects in UserDefinedComponents are wholesale duplication of code, we could consolidate a bit using a base struct.  (However, most of the duplication has been left alone.)

The issue seems to have been exposed due to a test file containing both types of user-defined air objects. Existing IDF test files that only contain one or the other seem to simulate normally.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UserDefinedComponents.cc [hunk 1]
```diff
@@ -2071,76 +2092,80 @@ namespace UserDefinedComponents {
...
-                }
-
-                // Fill the Zone Equipment data with the inlet node number of this unit.
-                for (int CtrlZone = 1; CtrlZone <= state.dataGlobal->NumOfZones; ++CtrlZone) {
-                    if (!state.dataZoneEquip->ZoneEquipConfig(CtrlZone).IsControlled) {
-                        continue;
+                    // one assumes if there isn't one assigned, it's an error?
+                    if (state.dataUserDefinedComponents->UserAirTerminal(CompLoop).ADUNum == 0) {
+                        ShowSevereError(state,
+                                        format("GetUserDefinedComponents: No matching Air Distribution Unit for {} = {}",
```
Comment (rraustad) [inline src/EnergyPlus/UserDefinedComponents.cc:2123]: I hate to do this but you renamed this function to GetUserDefinedAirTerminal. And yes, this is an error , the AirTerminal is specified in an ADU. That's the only place this object is listed as allowed. So this AirTerminal must not be listed in an ADU and therefore is an orphan object.

    ZoneHVAC:AirDistributionUnit,
       \memo Central air system air distribution unit, serves as a wrapper for a specific type of
       \memo air terminal unit. This object is referenced in a ZoneHVAC:EquipmentList.
       \min-fields 4
    A1 , \field Name
       \required-field
       \reference ZoneEquipmentNames
    A2 , \field Air Distribution Unit Outlet Node Name
       \required-field
       \type node
    A3 , \field Air Terminal Object Type
       \type choice
       \key AirTerminal:DualDuct:ConstantVolume
       \key AirTerminal:DualDuct:VAV
       \key AirTerminal:SingleDuct:ConstantVolume:Reheat
       \key AirTerminal:SingleDuct:ConstantVolume:NoReheat
       \key AirTerminal:SingleDuct:ConstantVolume:FourPipeBeam
       \key AirTerminal:SingleDuct:VAV:Reheat
       \key AirTerminal:SingleDuct:VAV:NoReheat
       \key AirTerminal:SingleDuct:SeriesPIU:Reheat
       \key AirTerminal:SingleDuct:ParallelPIU:Reheat
       \key AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction
       \key AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan
       \key AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat
       \key AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat
       \key AirTerminal:SingleDuct:ConstantVolume:CooledBeam
       \key AirTerminal:DualDuct:VAV:OutdoorAir
       \key AirTerminal:SingleDuct:UserDefined
       \key AirTerminal:SingleDuct:Mixer
       \required-field

File: src/EnergyPlus/UserDefinedComponents.cc [hunk 2]
```diff
@@ -2071,76 +2092,80 @@ namespace UserDefinedComponents {
...
 
-                int ADUNum = 0;
-                for (ADUNum = 1; ADUNum <= (int)state.dataDefineEquipment->AirDistUnit.size(); ++ADUNum) {
-                    if (state.dataUserDefinedComponents->UserAirTerminal(CompLoop).AirLoop.OutletNodeNum ==
-                        state.dataDefineEquipment->AirDistUnit(ADUNum).OutletNodeNum) {
-                        //        AirDistUnit(ADUNum)%InletNodeNum = IndUnitIUNum)%InletNodeNum
-                        state.dataUserDefinedComponents->UserAirTerminal(CompLoop).ADUNum = ADUNum;
+                if (state.dataUserDefinedComponents->NumUserAirTerminals > 0) { // Skip this code if the only User Defined type is ZoneHVAC
+                    int ADUNum = 0;
+                    for (ADUNum = 1; ADUNum <= (int)state.dataDefineEquipment->AirDistUnit.size(); ++ADUNum) {
```
Comment (rraustad) [inline src/EnergyPlus/UserDefinedComponents.cc]: I wasn't going to say anything since this was existing but you might as well fix this one while your in here, `for( int ADUNum`, line 2113 isn't needed.

File: src/EnergyPlus/UserDefinedComponents.cc [hunk 3]
```diff
@@ -1916,6 +1917,26 @@ namespace UserDefinedComponents {
...
+        Array1D_string cAlphaFieldNames;
+        Array1D_bool lAlphaFieldBlanks;
+        Array1D_string cAlphaArgs;
+        Array1D<Real64> rNumericArgs;
+        std::string cCurrentModuleObject;
+
+        if (state.dataUserDefinedComponents->GetPlantCompInput) {
+            GetUserDefinedPlantComponents(state);
+            state.dataUserDefinedComponents->GetPlantCompInput = false;
+        }
```
Comment (rraustad) [inline src/EnergyPlus/UserDefinedComponents.cc:1939]: We really do hurt ourselves by the choice of our example files. This is a good fix. So would be init_state.

**Review by rraustad — CHANGES_REQUESTED** [review]
@mitchute this looks good to go with a simple change.

**Comment by mitchute** [comment]
Thanks @rraustad. I'll kick it back to @tanaya-mankad for now, but feel free to ping me when ready and we'll get it in.

File: src/EnergyPlus/UserDefinedComponents.cc (hunk 1 above)
Comment (tanaya-mankad) [reply src/EnergyPlus/UserDefinedComponents.cc:2123]: Oops.
What do you think of GetUserDefinedAirComponent, or GetUserDefinedZoneAirComponent?

"There are only two hard things in Computer Science: cache invalidation and naming things."
-- Phil Karlton

**Comment by mitchute** [comment]
This is looking ready. We'll let CI finish then merge this.
