### PR TITLE
Correct logic checks to simulate StagedThermostat correctly

### LINKED ISSUE #9523: Invalid logic to check multiple speed HP index in UnitarySystem for stagedthermostat application
Issue overview
--------------
The m_DesignSpecMSHPIndex is 0-based. Any valid check should be m_DesignSpecMSHPIndex > -1.

Capture

The current code use a wrong logic for valid index:

m_DesignSpecMSHPIndex > 0

### Details

Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ X] Defect file added (list location of defect file here)

[9523.txt](https://github.com/NREL/EnergyPlus/files/9057901/9523.txt)

 - [X ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
 - Fixes #9523 and #9524 
 - The #9523 fix is to have a correct ligic check with 0-based MSHP index
 - The #9524 fix is to set up heating and heating flags correctly using load instead of StageNum
 - The test file is located inside #9523 
 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -10210,7 +10210,7 @@ namespace UnitarySystems {
         }
 
         // Determine the m_Staged status
-        if (allocated(state.dataZoneCtrls->StageZoneLogic) && this->m_DesignSpecMSHPIndex > 0) {
+        if (allocated(state.dataZoneCtrls->StageZoneLogic) && this->m_DesignSpecMSHPIndex > -1) {
```
Comment (lgu1234) [inline src/EnergyPlus/UnitarySystem.cc:10213]: 0 based index check

File: src/EnergyPlus/UnitarySystem.cc [hunk 2]
```diff
@@ -10234,7 +10234,7 @@ namespace UnitarySystems {
             } else {
                 QZnReq =
                     state.dataZoneEnergyDemand->ZoneSysEnergyDemand(this->ControlZoneNum).RemainingOutputRequired / this->ControlZoneMassFlowFrac;
-                if (this->m_StageNum > 0) {
+                if (QZnReq > 0.0) {
```
Comment (lgu1234) [inline src/EnergyPlus/UnitarySystem.cc:10237]: Load sign determines cooling and heating flags

File: src/EnergyPlus/UnitarySystem.cc (hunk 1 above)
Comment (Myoldmopar) [inline src/EnergyPlus/UnitarySystem.cc:10213]: From a purely personal preference standpoint, I'd prefer ` >= 0 ` rather than ` > -1 `, but it's totally fine here.

File: src/EnergyPlus/UnitarySystem.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/UnitarySystem.cc:10237]: Yeah that makes sense.  But this does imply that a zero load will set `.CoolingLoad` to true.  Is that what you want?  Or should there be a check for `abs(QZnReq) < SomeTolerance` to set both load flags to false?

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 3]
```diff
@@ -19280,3 +19280,331 @@ TEST_F(AirloopUnitarySysTest, WSHPVariableSpeedCoilSizing)
...
+                      OAUCoilOutTemp,
+                      ZoneEquipment,
+                      sensOut,
+                      latOut);
+
+    EXPECT_TRUE(thisSys->m_Staged);
+    EXPECT_EQ(thisSys->m_StageNum, 1);
+    EXPECT_TRUE(state->dataUnitarySystems->HeatingLoad);
+    EXPECT_FALSE(state->dataUnitarySystems->CoolingLoad);
+}
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:19610]: :+1:

**Review by Myoldmopar — COMMENTED** [review]
This seems like a good fix, I'm testing locally to verify.  I would like a response about the zero load condition before marking it approved.

File: src/EnergyPlus/UnitarySystem.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:10237]: The thermostat is sending the m_StageNum status just above here at line 10216 so this looks OK.

    this->m_StageNum = state.dataZoneEnergyDemand->ZoneSysEnergyDemand(this->ControlZoneNum).StageNum;

Comment (Myoldmopar) [reply src/EnergyPlus/UnitarySystem.cc:10237]: Thanks @rraustad, OK no reason to hold this up.

**Comment by Myoldmopar** [comment]
Thanks @lgu1234, merging this now.
