### PR TITLE
Fix 11300 - Crash When Adding Windows to Rotating Building Using Site:VariableLocation

### LINKED ISSUE #11300: EnergyPlus Crashes When Adding Windows to Rotating Building Model Using Site:VariableLocation
### Issue overview

**Overview**
The documentation mentions that [Site:VariableLocation](https://bigladdersoftware.com/epx/docs/25-1/input-output-reference/group-location-climate-weather-file-access.html#sitevariablelocation) is capable of modeling a rotating building. To test its capabilities, I ran experiments using both an older version (v9.1) and the latest version (v25.1). For debugging and testing, I started from the `VaryingLocationAndOrientation.idf` example file and modified it to represent a simple building with window surfaces, instead of a vessel with "Underwater" boundary conditions.

**Issue**
Two main issues:
1. Field Order Shift
The field order appears to be shifted by one compared to the IDD documentation. So the `Name` field takes a latitude schedule, the `Building Location Latitude Schedule` takes the Longitude schedule, etc. This was confirmed by checking the `Input Verification and Results Summary` in the EnergyPlus default tabular report. Also, in v25.1, if a non-schedule name is provided in the `Name` field, EnergyPlus throws a severe error:
```
** Severe  ** ReadVariableLocationOrientation: Site:VariableLocation = 
   **   ~~~   ** Name = VARIABLE, item not found.
```
2. Simulation Crashes with Window Surfaces
When using `Site:VariableLocation` with window geometry either using `FenestrationSurface:Detailed` or `Window`:
- In v9.1, any presence of a window object causes EnergyPlus to crash with a blank .err file.
- In v25.1, the simulation runs only if there is exactly one window or no windows. If more than one is defined, the simulation crashes.

To test functional equivalence of a v25.1 model considering a building with one window, I ran simulations comparing:
- A model with fixed 90° orientation using the `Building` object.
- A model with dynamic orientation (constant 90° schedule) using `Site:VariableLocation`.

For the output variable `Surface Outside Face Incident Solar Radiation Rate per Area [W/m2]`:
- Surfaces with windows showed major discrepancies between the two runs (Surface 4 in the graph below).
- Surfaces with no windows align better (surface 3)

Image

### Operating System (Multiple choices)

Windows

### Operating System Version

Win 11

### Version of EnergyPlus

9.1; 25.1

### Unmethours link or helpdesk ticket number

https://unmethours.com/question/102666/energyplus-crashes-when-adding-windows-to-rotating-building-model-using-sitevariablelocation/

### Defect file

[VaryingLocationAndOrientation_v9_1.idf.txt](https://github.com/user-attachments/files/23172695/VaryingLocationAndOrientation_v9_1.idf.txt)

[VaryingLocationAndOrientation_v25_1.idf.txt](https://github.com/user-attachments/files/23172717/VaryingLocationAndOrientation_v25_1.idf.txt)

### PR DESCRIPTION
**Pull request by kevin-moos**
Pull request overview
---------------------

- Fixes #11300

### Description of the purpose of this PR

Fix crash when using multiple windows with Site:VariableLocation. This was due to NewVertex not being allocated.
Fix defect in which fields are not processed in the correct order for Site:VariableLocation.
Add unit test to check for crashes.

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WeatherManager.cc [hunk 1]
```diff
@@ -288,22 +288,23 @@ namespace Weather {
...
         if (ipsc->lAlphaFieldBlanks(3)) {
-        } else if ((state.dataEnvrn->varyingOrientationSched = Sched::GetSchedule(state, ipsc->cAlphaArgs(3))) == nullptr) {
+        } else if ((state.dataEnvrn->varyingLocationLongSched = Sched::GetSchedule(state, ipsc->cAlphaArgs(3))) == nullptr) {
             ShowSevereItemNotFound(state, eoh, ipsc->cAlphaFieldNames(3), ipsc->cAlphaArgs(3));
         }
+
+        if (ipsc->lAlphaFieldBlanks(4)) {
+        } else if ((state.dataEnvrn->varyingOrientationSched = Sched::GetSchedule(state, ipsc->cAlphaArgs(4))) == nullptr) {
+            ShowSevereItemNotFound(state, eoh, ipsc->cAlphaFieldNames(4), ipsc->cAlphaArgs(4));
+        }
```
Comment (mitchute) [inline src/EnergyPlus/WeatherManager.cc:307]: Looks right. Interesting that this was never caught before.

**Review by mitchute — APPROVED** [review]
Looks good.

**Comment by JasonGlazer** [comment]
Thanks @kevin-moos and @mitchute
