### PR TITLE
Fixes ExtShadingSchedNum variable in SolarShading should be checked as an integer

### LINKED ISSUE #9517: ExtShadingSchedNum variable in SolarShading should be checked as integer
Issue overview
--------------
While working on another issue I saw the variable ExtShadingSchedNum is defined as integer but used as boolean in [SolarShading.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L589-L603). The following code:

```
            ExtShadingSchedNum = ScheduleManager::GetScheduleIndex(state, state.dataSurface->Surface(SurfNum).Name + "_shading");
            if (ExtShadingSchedNum) {
                state.dataSurface->SurfSchedExternalShadingFrac(SurfNum) = true;
                state.dataSurface->SurfExternalShadingSchInd(SurfNum) = ExtShadingSchedNum;
            } else {
``` 
should be replaced with
``` 
            ExtShadingSchedNum = ScheduleManager::GetScheduleIndex(state, state.dataSurface->Surface(SurfNum).Name + "_shading");
            if (ExtShadingSchedNum != 0) {
                state.dataSurface->SurfSchedExternalShadingFrac(SurfNum) = true;
                state.dataSurface->SurfExternalShadingSchInd(SurfNum) = ExtShadingSchedNum;
            } else {
``` 
### Details
Some additional details for this issue (if relevant):
 - Platform (Any, Develop)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9517
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Nigusse** [comment]
@Myoldmopar This is simple clean fix. This can go in if CI machine is happy.

File: src/EnergyPlus/SolarShading.cc [hunk 1]
```diff
@@ -586,11 +586,11 @@ void GetShadowingInput(EnergyPlusData &state)
         state.dataIPShortCut->cAlphaArgs(aNum) = "No";
         state.dataSysVars->ReportExtShadingSunlitFrac = false;
     }
-    int ExtShadingSchedNum;
     if (state.dataSysVars->shadingMethod == ShadingMethod::Imported) {
+        int ExtShadingSchedNum;
```
Comment (Myoldmopar) [inline src/EnergyPlus/SolarShading.cc:590]: Tightening the variable scope is a fine change.

File: src/EnergyPlus/SolarShading.cc [hunk 2]
```diff
@@ -586,11 +586,11 @@ void GetShadowingInput(EnergyPlusData &state)
...
         for (int SurfNum = 1; SurfNum <= state.dataSurface->TotSurfaces; ++SurfNum) {
             ExtShadingSchedNum = ScheduleManager::GetScheduleIndex(state, state.dataSurface->Surface(SurfNum).Name + "_shading");
-            if (ExtShadingSchedNum) {
+            if (ExtShadingSchedNum != 0) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/SolarShading.cc:593]: I'm not actually sure this has any change.  C++ is pretty [clear](https://en.cppreference.com/w/cpp/language/implicit_conversion#Boolean_conversions) about what happens to integers when they are cast to a boolean for this type of purpose, and 0 is going to be false while any other integer will be true.  That's the same thing you are doing by adding the `!= 0` operation here.

I made a small example to confirm that it behaves the same either way [here](https://godbolt.org/z/hsf6zcjGM).  

All that said, it is perfectly acceptable to explicitly check against the integer zero value, to avoid the implicit cast to boolean.

**Review by Myoldmopar — APPROVED** [review]
I don't have any problem with this tiny change.  Making the operation explicitly compare integers is fine.

**Comment by Myoldmopar** [comment]
As expected, CI is happy, since this had no functional change to the code.  Comparing integers directly does make it clear in this case, so it's a find change to make.  I'm going to drop in this tiny change.  Thanks @Nigusse
