### PR TITLE
fix Super high COP in VRFFluidTCtrl model

### LINKED ISSUE #10751: Super high heating cooling COP in VRFFluidTCtrl
Issue overview
--------------
The model show really high COP values during both heating and cooling operation: using the attached idf and New York weather, the heating COP could reach 14299 and cooling COP could reach 158.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number
 - Defect file:
[US+SF+CZ5B+hp+slab+IECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip](https://github.com/user-attachments/files/17067586/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip)
[eplusout_defect_output.csv](https://github.com/user-attachments/files/17067609/eplusout_defect_output.csv)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #10764: Many "Refrigerant is saturated at the given conditions" warnings for VRF FluidTCtrl model
Issue overview
--------------
Upgrading from 23.1 to 24.2, there are a lot more additional warnings about the refrigerant property:

```
   ** Warning ** RefrigProps::getSupHeatDensity: Refrigerant [R410A] is saturated at the given conditions, saturated density at given temperature returned. **
   **   ~~~   ** ...Called From:VRFOU_CapModFactor
   **   ~~~   ** Refrigerant temperature = -3.55
   **   ~~~   ** Refrigerant pressure = 962140
   **   ~~~   ** Returned Density value = 27.216
   **   ~~~   **  Environment=ANNUAL, at Simulation time=01/03 16:50 - 17:00
```

There are two aspects to the issue
- There should not be so many times refrigerant is saturated during the simulation
- The warnings didn't collapse to one recurring warning at the end. It shows up many many times instead (creating an error file of over 100MB). The recurring warning setup in this warning is problematic.

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac, 13.5.2)
 - Version of EnergyPlus (24.2 22e9501303d86afcec015a1247d6ae32f4e7aeee)
 - Unmethours link or helpdesk ticket number
 - Defect files: 
[US+SF+CZ5B+hp+slab+IECC_2021_VRFPhysics_v2_hrdsize_V2310.expidf.zip](https://github.com/user-attachments/files/17122055/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRFPhysics_v2_hrdsize_V2310.expidf.zip)
[US+SF+CZ5B+hp+slab+IECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip](https://github.com/user-attachments/files/17122056/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip)

The following is the error file for v24.2
[develop_eplusout.err.zip](https://github.com/user-attachments/files/17122085/develop_eplusout.err.zip)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #10767: This warning should not happen: Unable to find a unit conversion from Cooling Coil Type [1] into IP units
Issue overview
--------------
With the attached idf file, it produced warnings like the following. This shouldn't happen as the coil type is categorical and it shouldn't attempt to perform unit conversion.

```
** Warning ** Unable to find a unit conversion from Cooling Coil Type [1] into IP units
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac, 13.5.2)
 - Version of EnergyPlus (24.2)
 - Unmethours link or helpdesk ticket number
 - Defect file:
 
[US+SF+CZ5B+hp+slab+IECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip](https://github.com/user-attachments/files/17136728/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Fixes #10751
 - Fixes #10764
 - Fixes #10767
 
### 1. Fix of the super high COP problem

 The following shows the distribution of heating and cooling COP before vs after the fix (figure updated Mar. 11). For display purpose, the COP=0 points are removed.
image
[eplusout_defect_output_1025.csv](https://github.com/user-attachments/files/17525725/eplusout_defect_output_1025.csv)
[eplusout_fix_0311.csv](https://github.com/user-attachments/files/19196143/eplusout_fix_0311.csv)

COP is calculated as `this->TotalHeatingCapacity` divided by `this->ElecHeatingPower` and other auxiliary power. 
```
this->OperatingHeatingCOP = (this->TotalHeatingCapacity) /
                            (this->ElecHeatingPower + this->CrankCaseHeaterPower + this->EvapCondPumpElecPower + this->DefrostPower);
```
`this->ElecHeatingPower` is calculated as compressor power and outdoor fan power `this->ElecHeatingPower = this->Ncomp + this->OUFanPower;`

The following shows how `this->TotalHeatingCapacity` and `this->TotalCoolingCapacity`  are calculated in FluidTCtrl model and the curve-based model. This has led me to believe the super high COP is cause by numerator not multiplying the `CyclingRatio` term. **But it's NOT because of this.** 
```
// FluidTCtrl model
    this->TotalCoolingCapacity = TotalCondCoolingCapacity * CoolingPLR;
    this->TotalHeatingCapacity = TotalCondHeatingCapacity * HeatingPLR;
// curve-based model
    vrf.TotalCoolingCapacity = TotalCondCoolingCapacity * CoolingPLR * CyclingRatio;
    vrf.TotalHeatingCapacity = TotalCondHeatingCapacity * HeatingPLR * CyclingRatio;
```
#### heating COP fix
 
Even if here the cycling ratio is not multiplied, when plotting the "VRF Heat Pump Total Heating(Cooling) Rate" against cycling ratio, there's actually a positive linear relationship. However, the linear relationship between heating-rate and cycling ratio has a noticeable intercept, while the intercept for the compressor power and cycling ratio line is near zero. This would mean, when cycling ratio is very small, numerator in heating COP will be non-zero while the denominator approaches zero (compressor power and fan power both go to zero), the heating COP will thus blow up.

image

Comparing with v23.1, this non-zero intercept is also present in the heat pump heating rate and cycling ratio relationship. 
image

However, it didn't blow up as the outdoor unit fan power is always constant and not cycling with the coil even if the "Supply Air Fan Operating Mode Schedule Name" points to a constant-zero schedule (fan always cycles with coil). The following shows the comparison of heatingCOP vs cycling ratio relationship between current develop and v23-1. We can see when zoomed in, they both have the exponential decay pattern.

image

To fix it, the Ncomp multiplying by cycling ratio is moved to inside of the `VRFOU_CalcCompH` function. Previously (in the develop branch), Ncomp is calculated inside the function by multiplying the rated capacity and the power performance curve value, and the cycling ratio is multiplied to the calculated Ncomp after the `VRFOU_CalcCompH`. However, since the heating demand in `VRFOU_CalcCompH` involves the compressor heat release (`Q_evap_req = TU_load + Pipe_Q - Ncomp;`), if here `Ncomp` didn't multiply by cycling ratio, than the compressor heat release is overestimated, leading to an underestimation of the heating demand `Q_evap_req`, as a result, the computed cycling ratio will also be smaller than it should be, creating a mismatch between the cycling ratio and the heating rate. Whether the cycling ratio is multiplied inside or after `VRFOU_CalcCompH` will matter in the cycling ratio calculation in heating mode, but not in cooling mode as Ncomp was not in the demand calculation there.

After applied this fix, this is how the heating rate, compressor power, and COP look relative to cycling ratio

image

#### cooling COP fix

The cooling COP didn't go up as high as heating one but still with a maximum of 150+, which is too high to be realistic. The reason for the high cooling COP is likely the non-linearity between heat pump cooling rate and the cycling ratio when cycling ratio is very small. 

image

In the cycling ratio calculation, the code attempts to match the demand and capacity. If the they cannot match because the capacity is too large, then it will cycle and the cycling ratio is calculated as 

```
Cap_Eva0 = (TU_load + Pipe_Q) * C_cap_operation; // <- demand
Cap_Eva1 = this->CoffEvapCap * this->RatedEvapCapacity *
            CurveValue(state, this->OUCoolingCAPFT(CounterCompSpdTemp), T_discharge, T_suction); // <- capacity
CyclingRatio = Cap_Eva0 / Cap_Eva1;
```

When the cycling ratio is very small, this adjustment term `C_cap_operation` exhibits a exponential decay pattern as well and quickly goes to 0 as cycling ratio drops, which seems to be the cause of the non-linear pattern in the heat pump cooling rate-cycling ratio relationship (the following plot is in the develop branch, using debug prints to export value of cyclingRatio and C_cap_operation after line 11486 (`Q_h_OU *= CyclingRatio;` line)). The 6 subfigures on the right show how the 6 input variables vary with cycling ratio. `h_comp_in_real`, `P_evap_reql`, and `T_comp_in_rate` show some shoot up very high for when the cycling ratio is low.

image

Note that this multiplier `C_cap_operation` only trends to zero in cooling mode, not in heating mode. Maybe a threshold should be placed on this in cooling mode.

cyclingRatio_vs_C_cap_operation_heatcool_dev

after removing this multiplier, the cooling rate non-linear behavior is gone and COP vs cycling ratio plot is like the following

image

`C_cap_operation` is calculated in function `VRFOU_CapModFactor`, as `C_cap_operation = C_cap_density * C_cap_enthalpy;` in the test case (using ), `C_cap_density` is steadily around 1. `C_cap_enthalpy` exponential decays from 1 to 0 at low cycling ratio. So the problem is likely in `C_cap_enthalpy`.

image

`C_cap_enthalpy` is calculated as `C_cap_enthalpy = std::abs(h_evap_out_rate - h_evap_in_rate) / std::abs(h_comp_in_real - h_evap_in_real);`. Numerator roughly ranges from 180000 to 230000 linearly changing with cycling ratio. The denominator has the exponential decay pattern. `h_evap_in_real` (or `Pipe_h_IU_in`) linearly changes while `h_comp_in_real` or `Pipe_h_comp_in` has the exponential decay pattern. 

`Pipe_h_comp_in` is calculated as `Pipe_h_comp_in = Pipe_h_IU_out + Pipe_Q / Pipe_m_ref;` in the following function

```
                    // Re-calculate piping loss
                    this->VRFOU_PipeLossC(state,
                                          Pipe_m_ref,
                                          max(min(Pipe_Pe_assumed, RefPHigh), RefPLow),
                                          Pipe_h_IU_out,
                                          Pipe_SH_merged,
                                          OutdoorDryBulb,
                                          Pipe_Q,
                                          Pipe_DeltP,
                                          Pipe_h_comp_in); <- calculated here
```

The super high `Pipe_h_comp_in` is related to low refrigerant rate. When the refrigerant flow is very small, the ratio of `Pipe_Q / Pipe_m_ref` shoots up very high, making `Pipe_h_comp_in` very large. From this investigation, it seems the calculation of piping loss might not be correct when refrigerant flow rate is very small.

pipingLoss_refrig_flow
pipingLoss_refrig_flow_small_flow

Essentially `Pipe_h_comp_in = Pipe_h_IU_out + Pipe_Q / Pipe_m_ref` assumes that the heat loss through the pipe is due to the flow of the refrigerant and that 

heat loss through the pipe = enthalpy difference * refrigerant flow rate

But this is problematic when refrigerant flow rate is very small and close to zero. For example, in the following scatter plot, roughly there's a positive linear relationship between refrigerant flow rate (horizontal axis) and the pipe heat loss (Pipe_Q on the vertical axis). When refrigerant flow is near zero, Pipe_Q is not zero. `Pipe_Q / Pipe_m_ref` this term will blow up and create super high `Pipe_h_comp_in`.

pipingLoss_refrig_flow

The reason for low refrigerant flow rate is due to the small load: state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU)
```
                Pipe_m_ref_i = (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU) <= 0.0)
                                   ? 0.0
                                   : (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU) / (Pipe_h_IU_out_i - Pipe_h_IU_in));
                Pipe_m_ref = Pipe_m_ref + Pipe_m_ref_i;
```

According to Daikin engineers, once compressor reach its min speed, refrigerant mass flow will not drop any further. So the following bound is added in the refrigerant flow calculation

```
Real64 min_speed_capacity =
    this->CoffEvapCap * this->RatedEvapCapacity * CurveValue(state, this->OUCoolingCAPFT(1), T_discharge, T_suction);
Pipe_m_ref_i = (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU) <= 0.0)
                    ? 0.0
                    // refrigerant flow rate do not get smaller when the compressor needs to cycle.
                    : max(min_speed_capacity,
                          (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU)) /
                              (Pipe_h_IU_out_i - Pipe_h_IU_in));
```

----

The fact that cooling COP is a bit high might be how the performance data is set up.

The following shows the range of COP using the current range of condensing and evaporating temperature

```
heating mode
+        x            y           cyclingRatio        fanpower   comp.power.calc cooling.rate.calc      COP       
 Min.   :35   Min.   :-15.00   Min.   :0.01308   Min.   :119   Min.   :167.3   Min.   : 797.1    Min.   :2.455  
 1st Qu.:36   1st Qu.: -7.25   1st Qu.:0.27588   1st Qu.:119   1st Qu.:202.1   1st Qu.:1099.9    1st Qu.:3.277  
 Median :37   Median :  0.50   Median :0.49665   Median :119   Median :209.8   Median :1522.8    Median :4.500  
 Mean   :37   Mean   :  0.50   Mean   :0.50749   Mean   :119   Mean   :209.3   Mean   :1612.5    Mean   :4.957  
 3rd Qu.:38   3rd Qu.:  8.25   3rd Qu.:0.72511   3rd Qu.:119   3rd Qu.:219.0   3rd Qu.:2077.6    3rd Qu.:6.373  
 Max.   :39   Max.   : 16.00   Max.   :0.99268   Max.   :119   Max.   :230.5   Max.   :2797.2    Max.   :9.769  

cooling mode
+        x            y        cyclingRatio        fanpower   comp.power.calc cooling.rate.calc      COP        
 Min.   :16   Min.   :6.0   Min.   :0.01339   Min.   :119   Min.   : 71.7   Min.   :1920      Min.   : 5.899  
 1st Qu.:21   1st Qu.:6.0   1st Qu.:0.28550   1st Qu.:119   1st Qu.:106.2   1st Qu.:2080      1st Qu.: 7.109  
 Median :26   Median :6.5   Median :0.53528   Median :119   Median :140.2   Median :2211      Median : 8.534  
 Mean   :26   Mean   :6.5   Mean   :0.53092   Mean   :119   Mean   :140.0   Mean   :2209      Mean   : 8.833  
 3rd Qu.:31   3rd Qu.:7.0   3rd Qu.:0.77554   3rd Qu.:119   3rd Qu.:173.6   3rd Qu.:2335      3rd Qu.:10.370  
 Max.   :36   Max.   :7.0   Max.   :0.99191   Max.   :119   Max.   :206.5   Max.   :2495      Max.   :13.085  

```
The data files for the above summary is here
[dummuy_heating_data.csv](https://github.com/user-attachments/files/18592943/dummuy_heating_data.csv)
[dummuy_cooling_data.csv](https://github.com/user-attachments/files/18592944/dummuy_cooling_data.csv)

Note that in version 23.1, the cycling ratio is like the following

image 

### 2. Fix of the refrigerant warning

The issue is originated from the change of this line in PR#10416 the following line. The intention is to 

image

The intention of the change is to impose a lower bound in solving for an evaporating temperature when the heating load is small. Such a lower bound is necessary as otherwise, in many time steps when the system is cycling, the OU evaporating temperature will be -72C, which is too low to be feasible. However, using the value of the input field "Variable Evaporating Temperature Minimum for Indoor Unit" as the lower bound will trigger a bunch of refrigerant warnings.

To fix the refrigerant flow problem, it is observed that the following line might have been a mistake `CapMinPe = min(Pdischarge - this->CompMaxDeltaP, RefMinPe);`. `Pdischarge` is the compressor discharge pressure,
`this->CompMaxDeltaP` is the maximum compressor pressure rise. Then `Pdischarge - this->CompMaxDeltaP` is minimum compressor suction pressure considering pressure rise bound. The `RefMinPe` is minimum refrigerant evaporating pressure, which is a pressure lower bound considering physical feasibility. `CapMinPe` should be no less than both of them, so it should be max of them, not min.

In the code base, there are three places where `CapMinPe` is calculated (shown in the following). Two of them are max, one is min, hinting that the min might be a bug.

image

After imposing the right pressure bound, the refrigerant warnings are mostly gone. The following are the eplusout.err files from the develop and the feature branch. A difference can be seen just from the file size.

[fix_eplusout.err.zip](https://github.com/user-attachments/files/17122178/fix_eplusout.err.zip)
[develop_eplusout.err.zip](https://github.com/user-attachments/files/17122180/develop_eplusout.err.zip)

### 3. Fix of the recurring warning issue

The warning message keep showing up is the non-recurring warning (which should only be shown once or a few times).

The excessive amount of warning is produced by this chunk of code. The condition `this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest` decides whether it prints this warning. The right hand side of the inequality is 1, while the left hand side overflows to negative at some point to -2147450880. From then on, the condition just keeps evaluates to true and the warning keeps showing up. It overflows as it is not a counter, but a sum of all previous counter values. This makes it get large very quickly. When it overflows, the counter value of `df->SatErrCountGetSupHeatDensityRefrig` is 65536. This `this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest` is 1 + 2 + ... + 65536, which overflowed.

```
++df->SatErrCountGetSupHeatDensityRefrig;
// send warning
this->errors[(int)RefrigError::SatSupDensity].count += df->SatErrCountGetSupHeatDensityRefrig;
// send warning
if (this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest) {
    ShowWarningMessage(
        state,
        format("{}: Refrigerant [{}] is saturated at the given conditions, saturated density at given temperature returned. **",
                routineName,
                this->Name));
    ShowContinueError(state, fmt::format("...Called From:{}", CalledFrom));
    ShowContinueError(state, format("Refrigerant temperature = {:.2R}", Temperature));
    ShowContinueError(state, format("Refrigerant pressure = {:.0R}", Pressure));
    ShowContinueError(state, format("Returned Density value = {:.3R}", saturated_density));
    ShowContinueErrorTimeStamp(state, "");
}
```

### 4. Cooling Coil Type [1] IP to SI unit conversion warning

The warning is produced because the code assumes there is a unit of measure inside the bracket and will attempt to perform unit conversion. Here this is a categorical variable and should not attempt to do unit conversion, so [] is not appropriate. The problem if fixed by changing the "[]" into "()" in this "Cooling Coil Type [1]".

#### Table big diff and Table string diffs

There are 733 files have "ColumnHeadingDifference", leading to table big diffs and string diffs. This is caused by changing "Cooling Coil Type [1]" to "Cooling Coil Type (1)" in this feature branch. The diffs are expected.

#### meter diff

Meter diff happens in test idf "VariableRefrigerantFlow_FluidTCtrl_5Zone", in the following two fields.
- Electricity:Facility
- Electricity:HVAC    
The meter diff is caused by this change. The changes here will cause differences in compressor power, which will lead to changes in Electricity:HVAC and Electricity:Facility.
image
 
#### eso diff

in US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF, VariableRefrigerantFlow_FluidTCtrl_5Zone, and VariableRefrigerantFlow_FluidTCtrl_HR_5Zone, the following fields have eso diffs

- VRF HEAT PUMP:VRF Heat Pump Total Cooling Rate
- VRF HEAT PUMP:VRF Heat Pump Total Heating Rate
- VRF HEAT PUMP:VRF Heat Pump Heating Electricity Rate
- VRF HEAT PUMP:VRF Heat Pump Heating Electricity Energy
- VRF HEAT PUMP:VRF Heat Pump Compressor Electricity Rate
- VRF HEAT PUMP:VRF Heat Pump Outdoor Unit Evaporating Temperature

These diffs are expected as the numerator of the COP term (heating/cooling output) is changed in this feature: it is multiplied by the cycling ratio now. The changes in COP and heating cooling rate are both expected. Changes in Outdoor Unit Evaporating Temperature is due to the correction in refrigerant pressure lower bound, which is used in calculation of OU evaporating temperature. Heating electricity rate and energy difference happen in 1/21. Heating electricity rate is the sum of compressor power and outdoor unit fan power. As a result of the changing `MinOutdoorUnitTe` argument from `max(this->IUEvapTempLow, CapMinTe)` to `CapMinTe` in function `VRFOU_CalcCompH`, compressor power will change. So diffs in heating electricity rate is also expected.

#### err diffs

11 files have error diffs. This is because the following warning is removed as a result of the column header change of "Cooling Coil Type".

```
** Warning ** Unable to find a unit conversion from Cooling Coil Type [1] into IP units
```

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 1]
```diff
@@ -12198,8 +12198,8 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state, c
         }
     }
 
-    this->TotalCoolingCapacity = TotalCondCoolingCapacity * CoolingPLR;
-    this->TotalHeatingCapacity = TotalCondHeatingCapacity * HeatingPLR;
+    this->TotalCoolingCapacity = TotalCondCoolingCapacity * CoolingPLR * CyclingRatio;
+    this->TotalHeatingCapacity = TotalCondHeatingCapacity * HeatingPLR * CyclingRatio;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: OK, I can see this one being missed because it's multiplied by PLR and looked correct at first glance. If COP came back in line then it's likely that all the electricity reports are correctly adjusting for cycling. Although it's not a given, because things like defrost, cranckcase heater and evap condenser pump power are small compared to compressor power, and are most likely 0 in the test files. I would check those.  What else might have been missed? What happens to piping losses during cycling? What about something like compressor speed? should that also be adjusted by CyclingRatio?

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Crankcase heater seems to have considered cycling
```
        VRFRTF = min(1.0, (CyclingRatio / PartLoadFraction));
...
        this->CrankCaseHeaterPower = this->CCHeaterPower * (1.0 - VRFRTF);
```
Defrost seems to have its own "runtime fraction", the `FractionalDefrostTime`: 
```
                    this->DefrostPower = DefrostEIRTempModFac * (this->HeatingCapacity / 1.01667) * FractionalDefrostTime;

                } else { // Defrost strategy is resistive
                    this->DefrostPower = this->DefrostCapacity * FractionalDefrostTime;
                }
```

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Crankcase heater power looks good. I think defrost power needs a  CyclingRatio term. FractionalDefrostTime is the defrost time for a full time step. If the system doesn't run that time step (i.e., CyclingRatio = 0.000000001) then DefrostPower should be 0. You can check FractionalDefrostTime and see that it's a function of OA humidity ratio and has nothing to do with PLR or CyclingRatio. Of course you have to check my thinking before doing anything.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I think you're right. FractionalDefrostTime is either from the user input or from `OutdoorCoildw`. It should probably multiply by cycling ratio.

For `this->EvapCondPumpElecPower` term, since the FluidTCtrl model doesn't have the "Evaporative Condenser Pump Rated Power Consumption" field like the curve-based VRF, this term is always 0.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 2]
```diff
@@ -1192,10 +1192,9 @@ void CalcVRFCondenser(EnergyPlusData &state, int const VRFCond)
 
         vrf.ElecHeatingPower =
             (vrf.RatedHeatingPower * TotHeatCapTempModFac) * TotHeatEIRTempModFac * EIRFPLRModFac * HREIRAdjustment * VRFRTF * InputPowerMultiplier;
-
-        // adjust defrost power based on heating RTF
-        vrf.DefrostPower *= VRFRTF;
     }
+    // adjust defrost power based on RTF
+    vrf.DefrostPower *= VRFRTF;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:1197]: This looks correct.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 3]
```diff
@@ -11592,7 +11591,8 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state, c
         Tdischarge = this->refrig->getSatTemperature(state, max(min(Pdischarge, RefPHigh), RefPLow), RoutineName);
 
         // Evaporative capacity ranges_Min
-        CapMinPe = min(Pdischarge - this->CompMaxDeltaP, RefMinPe);
+        // suction pressure lower bound need to be no less than both terms in the following
+        CapMinPe = max(Pdischarge - this->CompMaxDeltaP, RefMinPe);
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11522]: This looks correct. Not sure why this didn't show up during the original model develolpment.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 4]
```diff
@@ -12237,6 +12236,7 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state, c
         this->ElecHeatingPower = 0;
     }
     this->VRFCondRTF = VRFRTF;
+    this->DefrostPower *= VRFRTF;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12165]: This looks correct. A plot of DefrostPower vs RTF or CyclingRatio would show it's working.

**Comment by rraustad** [comment]
This branch looks good now. I looked at fix_eplusout.err.zip and see this warning. Why is OutputReportTabular looking to convert a cooling coil type to IP units? This is probably a FluidTCtrl cooling coil. You could fix that here or file an issue.

    ** Warning ** Unable to find a unit conversion from Cooling Coil Type [1] into IP units

**Comment by rraustad** [comment]
@yujiex these warnings (develop_eplusout.err.zip) are set up as recurring warnings so that the err file does not contain thousands of messages. However, this file does contain thousands of messages (300,000 warnings). Can you please investigate, either here or a different branch.

    int RefrigErrorLimitTest = 1; // how many times error is printed with details before recurring called

    ++df->SatErrCountGetSupHeatDensityRefrig;
    // send warning
    this->errors[(int)RefrigError::SatSupDensity].count += df->SatErrCountGetSupHeatDensityRefrig;
    // send warning
    if (this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest) {
        ShowWarningMessage(

    ** Warning ** RefrigProps::getSupHeatDensity: Refrigerant [R410A] is saturated at the given conditions, saturated density at given temperature returned. **
    **   ~~~   ** ...Called From:VRFOU_CapModFactor
    **   ~~~   ** Refrigerant temperature = -3.55
    **   ~~~   ** Refrigerant pressure = 962140
    **   ~~~   ** Returned Density value = 27.216
    **   ~~~   **  Environment=ANNUAL, at Simulation time=01/03 16:50 - 17:00

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11522]: Yeah, I'm surprised as well.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12165]: This is a plot of heat pump defrost power vs cycling ratio

image

When the defrost power is non-zero, it is proportional to cycling ratio

The output file is here:
[eplusout_defrost_vs_cyclingRatio.xlsx](https://github.com/user-attachments/files/17135490/eplusout_defrost_vs_cyclingRatio.xlsx)

**Comment by yujiex** [comment]
> Unable to find a unit conversion from Cooling Coil Type [1] into IP units

Thanks for noticing this. I will fix it here too

**Comment by yujiex** [comment]
> @yujiex these warnings (develop_eplusout.err.zip) are set up as recurring warnings so that the err file does not contain thousands of messages. However, this file does contain thousands of messages (300,000 warnings). Can you please investigate, either here or a different branch.
> 
> ```
> int RefrigErrorLimitTest = 1; // how many times error is printed with details before recurring called
> 
> ++df->SatErrCountGetSupHeatDensityRefrig;
> // send warning
> this->errors[(int)RefrigError::SatSupDensity].count += df->SatErrCountGetSupHeatDensityRefrig;
> // send warning
> if (this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest) {
>     ShowWarningMessage(
> 
> ** Warning ** RefrigProps::getSupHeatDensity: Refrigerant [R410A] is saturated at the given conditions, saturated density at given temperature returned. **
> **   ~~~   ** ...Called From:VRFOU_CapModFactor
> **   ~~~   ** Refrigerant temperature = -3.55
> **   ~~~   ** Refrigerant pressure = 962140
> **   ~~~   ** Returned Density value = 27.216
> **   ~~~   **  Environment=ANNUAL, at Simulation time=01/03 16:50 - 17:00
> ```

Good point. I will make it recurring warnings

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12165]: Why is defrost electricity so small? at 6 E -9

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12165]: I used this test file. Its "Resistive Defrost Heater Capacity" is 0.0000001
 [US+SF+CZ5B+hp+slab+IECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip](https://github.com/user-attachments/files/17122056/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRFPhysics_v2_hrdsize_V2420.expidf.zip)

**Comment by yujiex** [comment]
@rraustad I've investigated the two issues

**SI to IP unit conversion warning**

I fixed the warning of "unit conversion from Cooling Coil Type [1] into IP units", by changing the [] to () in the column header "Cooling Coil Type [1]". The warning is produced because the code assumes there is a unit of measure inside the bracket and will attempt to perform unit conversion. Here this is a categorical variable and should not attempt to do unit conversion, so [] is not appropriate. It is changed to () per suggestion from @JasonGlazer 

**recurring warning shows too many times**

I also figured out the reason for the recurring warning message not showning as recurring. The messages keeps showing up is not produced by the `ShowRecurringWarningErrorAtEnd`, but by the following non-recurring part. The condition `this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest` decides wiether it will produce this warning. The right hand side of the inequality is 1, the left hand side overflows to negative at some point to -2147450880, and from then on, the condition just keeps evaluates to true and the warning keeps showing up. It overflows as it is not a counter, but a sum of all previous counter values. When it overflows, the counter value of `df->SatErrCountGetSupHeatDensityRefrig` is 65536. This `this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest` is 1 + 2 + ... + 65536, which overflowed.

I believe changing the condition to just `if (df->SatErrCountGetSupHeatDensityRefrig <= df->RefrigErrorLimitTest)` will solve the problem
```
++df->SatErrCountGetSupHeatDensityRefrig;
// send warning
this->errors[(int)RefrigError::SatSupDensity].count += df->SatErrCountGetSupHeatDensityRefrig;
// send warning
if (this->errors[(int)RefrigError::SatSupDensity].count <= df->RefrigErrorLimitTest) {
    ShowWarningMessage(
        state,
        format("{}: Refrigerant [{}] is saturated at the given conditions, saturated density at given temperature returned. **",
                routineName,
                this->Name));
    ShowContinueError(state, fmt::format("...Called From:{}", CalledFrom));
    ShowContinueError(state, format("Refrigerant temperature = {:.2R}", Temperature));
    ShowContinueError(state, format("Refrigerant pressure = {:.0R}", Pressure));
    ShowContinueError(state, format("Returned Density value = {:.3R}", saturated_density));
    ShowContinueErrorTimeStamp(state, "");
}
```

**Comment by yujiex** [comment]
The fix for the high COP part (https://github.com/NREL/EnergyPlus/issues/10751) might have some problem. Let me investigate some more. Please hold off on reviewing. Thanks.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 16 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@yujiex it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@yujiex let me know what you think about this PR status.  If it's worth pushing it forward, let me know how I can help.

**Comment by yujiex** [comment]
> @yujiex let me know what you think about this PR status. If it's worth pushing it forward, let me know how I can help.

Hi @Myoldmopar, the remaining issue to be fixed here is the cooling COP being too high (can reach 158). I have been investigating it and feels the piping loss calculation at low refrigerant flow rate had some issue and I proposed some fix in section "potential fix to cooling COP". I haven't implemented this fix in the code yet. But conceptually I feel it is likely to work. I'll try it out tomorrow afternoon.

**Comment by yujiex** [comment]
@rraustad and @mjwitte I have investigated the cooling high COP issue and I think it's related to how the piping loss is calculated at low-flow-rate calculation (explained in section "potential fix to cooling COP" in the PR introduction). Do you think this fix make sense? I have to choose a cutoff value for when it should be considered stationary flow but didn't find much info on the internet about what this cutoff should be. Any ideas on this? Thanks.

**Comment by yujiex** [comment]
Hi @mjwitte and @rraustad, I've added a bound for the refrigerant flow rate. As according to Daikin engineers, once compressor reach its min speed, refrigerant mass flow will not drop any further. So the following bound is added in the refrigerant flow calculation.
```
Real64 min_speed_capacity =
    this->CoffEvapCap * this->RatedEvapCapacity * CurveValue(state, this->OUCoolingCAPFT(1), T_discharge, T_suction);
Pipe_m_ref_i = (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU) <= 0.0)
                    ? 0.0
                    // refrigerant flow rate do not get smaller when the compressor needs to cycle.
                    : max(min_speed_capacity,
                          (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU)) /
                              (Pipe_h_IU_out_i - Pipe_h_IU_in));
```
Please see if this make sense. Thanks!

**Comment by dareumnam** [comment]
@rraustad, It would be greatly appreciated if you could review this so that it can potentially be merged before the code freeze next week. Thanks!

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 5]
```diff
@@ -14016,10 +14015,14 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
...
+                                Real64 min_speed_capacity =
+                                    this->CoffEvapCap * this->RatedEvapCapacity * CurveValue(state, this->OUCoolingCAPFT(1), T_discharge, T_suction);
                                 Pipe_m_ref_i = (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU) <= 0.0)
                                                    ? 0.0
-                                                   : (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU) /
-                                                      (Pipe_h_IU_out_i - Pipe_h_IU_in));
+                                                   // refrigerant flow rate do not get smaller when the compressor needs to cycle.
+                                                   : max(min_speed_capacity,
+                                                         (state.dataHVACVarRefFlow->TerminalUnitList(TUListNum).TotalCoolLoad(NumTU)) /
+                                                             (Pipe_h_IU_out_i - Pipe_h_IU_in));
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14025]: This may be the very change that corrects several issues with this model.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14025]: This fixed the super high cooling COP problem: from previous maximum of 158 to about 12 now.

**Review by Myoldmopar — APPROVED** [review]
I'll buy it.  I admittedly don't have the time to dive into every bit of detail here.  I'm grateful that this has gone through several rounds of reviews and reworks over the last few months, so a big thanks to @rraustad and @mjwitte for that.  @yujiex I'll do a quick build with latest develop as of right now to confirm things, but this should merge in this morning if it's all happy.

**Comment by Myoldmopar** [comment]
Yep, all happy, merging this.  Thanks @yujiex and all

**Comment by yujiex** [comment]
Thanks @Myoldmopar for compiling and merging! Also thanks @rraustad and @mjwitte for the comments and guidance.
