### PR TITLE
Trap inconsistent Do Space Heat Balance settings with SpaceHVAC objects

### LINKED ISSUE #10980: Missing ZoneAirHeatBalanceAlgorithm with spaces causes crash
### Issue overview

I was attempting to do a model utilizing spaces, including objects like `SpaceHVAC:ZoneEquipmentSplitter` and the like. I forgot to include the `ZoneAirHeatBalanceAlgorithm` object. This caused a crash at line 398 in DataZoneEquipment.cc

```
        auto &thisSpaceEquipConfig = state.dataZoneEquip->spaceEquipConfig(spaceNum);
```

I also tried tests where the `ZoneAirHeatBalanceAlgorithm` had one of the "Do space heat balance" fields set to No. I got a different crash for when Do Space Heat Balance for Sizing was `No` at line 1841 in DataZoneEquipment.cc. 

```
            spacesTotal += state.dataSize->FinalSpaceSizing(thisSpace.spaceIndex).DesCoolLoad;
```

Desired behavior would be a warning in the .err file that this object is missing, or that spaces are defined, and no space heat balance simulation is happening.

### Operating System (Multiple choices)

Windows

### Operating System Version

Windows 11 Pro 26100.3194

### Version of EnergyPlus

24.2

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[5ZoneAirCooledWithSpacesHVAC.idf.txt](https://github.com/user-attachments/files/19170651/5ZoneAirCooledWithSpacesHVAC.idf.txt)

This is file directly from the Examples, except I commented out the `ZoneAirHeatBalanceAlgorithm` object.

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #10980 

### Description of the purpose of this PR

 - Throw a warning when SpaceHVAC:* objects are present but "Do Space Heat Balance for Simulation = No". Here are the new warnings with the defect file:
```
   ** Warning ** SpaceHVAC:EquipmentConnections requires "Do Space Heat Balance for Simulation = Yes" in ZoneAirHeatBalanceAlgorithm. SpaceHVAC:EquipmentConnections objects will be ignored.
   ** Warning ** SpaceHVAC:ZoneEquipmentSplitter requires "Do Space Heat Balance for Simulation = Yes" in ZoneAirHeatBalanceAlgorithm. SpaceHVAC:ZoneEquipmentSplitter objects will be ignored.
   ** Warning ** SpaceHVAC:ZoneEquipmentMixer requires "Do Space Heat Balance for Simulation = Yes" in ZoneAirHeatBalanceAlgorithm. SpaceHVAC:ZoneEquipmentMixer objects will be ignored.
   ** Warning ** SpaceHVAC:ZoneReturnMixer requires "Do Space Heat Balance for Simulation = Yes" in ZoneAirHeatBalanceAlgorithm. SpaceHVAC:ZoneReturnMixer objects will be ignored.
```
 - Throw a fatal error if "Do Space Heat Balance for Sizing= No" and "Space Fraction Method" is DesignCoolingLoad or DesignHeatingLoad in SpaceHVAC:ZoneEquipmentSplitter or SpaceHVAC:ZoneEquipmentMixer and one or more space fractions is autosized. Here is the new error message with "Do Space Heat Balance for Sizing= No" and  "Do Space Heat Balance for Simulation = Yes":
```
   ** Severe  ** ZoneEquipmentSplitterMixer::size: DESIGNCOOLINGLOAD is unknown for SpaceHVAC:ZoneEquipmentSplitter=ZONE 5 ATU SPACE SPLITTER. Unable to autosize Space Fractions.
   **  Fatal  ** Set "Do Space Heat Balance for Sizing" to Yes in ZoneAirHeatBalanceAlgorithm or choose a different Space Fraction Method.
```

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Fixed the Clang Format issue.  Your description above looks good.  If this is clean I'll get it merged in this afternoon.

**Comment by Myoldmopar** [comment]
This is clean other than the errors that live in develop.  That appears to be nearly ready, pending some comments from @rraustad.  This is good to go though.  Thanks @mjwitte

File: src/EnergyPlus/DataZoneEquipment.cc [hunk 1]
```diff
@@ -352,6 +352,14 @@ void GetZoneEquipmentData(EnergyPlusData &state)
...
     for (int controlledSpaceLoop = 1; controlledSpaceLoop <= numControlledSpaces; ++controlledSpaceLoop) {
         CurrentModuleObject = "SpaceHVAC:EquipmentConnections";
+        if (!state.dataHeatBal->doSpaceHeatBalanceSimulation) {
+            ShowWarningError(
+                state,
+                format("{} requires \"Do Space Heat Balance for Simulation = Yes\" in ZoneAirHeatBalanceAlgorithm. {} objects will be ignored.",
+                       CurrentModuleObject,
+                       CurrentModuleObject));
+            break;
+        }
```
Comment (rraustad) [inline src/EnergyPlus/DataZoneEquipment.cc:362]: So if the ZoneAirHeatBalanceAlgorithm object is missing, or is present and Do Space Heat Balance for Simulation = No, and the inputs include any of the SpaceHVAC objects, then those space objects will be ignored and the simulation continues. This does sound reasonable since the space heat balance will not be executed and therefore no data available to assign to the space reporting. I was thinking if the SpaceHVAC inputs were NOT autosized then the simulation should still account for spaces, but that can only happen when Do Space Heat Balance for Simulation = Yes. Changes are Approved!
