### PR TITLE
Indexing issue when using multiple CoilSystem objects in OA System

### LINKED ISSUE #9738: Hard crash in MixedAir.cc, vector using incorrect 1-based index
Issue overview
--------------
Working a side project, was getting hard crash at this [line](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L682)  in MixedAir.cc.  Changing from using CompIndex to compNum appears to fix the problem. Like the pattern used above [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L653) 

Also occurs [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L704) 

Seems like the 8th argument in simulate() should be CompIndex, while the 5th arg should be compNum, as well as in the LHS vector of calls to simulate. 2 places.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (22.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9785: Indexing issue when using multiple UnitarySystem and/or CoilSystem as OASystem components
Issue overview
--------------
There appears to be an issue with pointer based components (e.g., UnitarySystem, CoilSystem, etc.) in the OASystem and maybe elsewhere.

In SimOASysComponents the value of state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) is passed into the function SimOAComponent. This value starts out as 0 and this call returns the index to the object. Then the value will be used to simulate the correct component in each object class.

    for (CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {
        CompType = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentType(CompNum);
        CompName = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum);
        SimOAComponent(state,
                       CompType,
                       CompName,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum),
                       FirstHVACIteration,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum), <---- this will initially be 0 for all OASys components
                       AirLoopNum,
                       Sim,
                       OASysNum,
                       OAHeatCoil,
                       OACoolCoil,
                       OAHX);
        if (OAHX) ReSim = true;
    }

Now inside SimOAComponent, this value is passed in as CompIndex. For example a heating coil will pass back it's component index.

    } else if (CompTypeNum == SimAirServingZones::CompType::Coil_GasHeat) { // 'Coil:Heating:Fuel'
        if (Sim) {
            //     stand-alone coils are temperature controlled (do not pass QCoilReq in argument list, QCoilReq overrides temp SP)
            SimulateHeatingCoilComponents(state, CompName, FirstHVACIteration, _, CompIndex); <-- the heating coil will pass back the index to the coil object since this is &CompIndex
        }

But for pointer based equipment, the factory pointer is stored in state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex], which should be the index of the component in the OASystem list.

    } else if (CompTypeNum == SimAirServingZones::CompType::DXSystem) { // CoilSystem:Cooling:DX
        if (Sim) {
            if (state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex] == nullptr) {
                UnitarySystems::UnitarySys thisSys;
                state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex] =
                    thisSys.factory(state, DataHVACGlobals::UnitarySys_AnyCoilType, CompName, false, 0);
                CompIndex = UnitarySystems::getUnitarySystemIndex(state, CompName) + 1;
                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompIndex) = CompIndex;
                UnitarySystems::UnitarySys::checkUnitarySysCoilInOASysExists(state, CompName, 0);
            }
            bool HeatingActive = false;
            bool CoolingActive = false;
            Real64 OAUCoilOutTemp = 0.0;
            bool ZoneEquipFlag = false;
            Real64 sensOut = 0.0;
            Real64 latOut = 0.0;
            int dummyCompIndex = 0; // TRANE
            state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex]->simulate(state, <-- now this will crash or fail for models with multiple UnitarySystem objects (i.e., PTAC, CoilSystem, etc.)

As a fix I propose to pass in CompNum instead of state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) and set these values inside SimOAComponent.

    for (CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {
        CompType = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentType(CompNum);
        CompName = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum);
        SimOAComponent(state,
                       CompType,
                       CompName,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum), <-- won't need this argument now
                       FirstHVACIteration,
                       CompNum, <---- pass this instead and set these other vars inside SimOACompnent

This pointer is also set in GetOutsideAirSysInputs where the factory is called for these pointer based objects. This may also correct this situation where CompIndex would not be used in the SimOAComponent function since the pointer has already been set. This is likely the better option for correcting this issue since this check is missing from the factory loop over each component in all OASystems in GetOutsideAirSysInputs. This would correct this issue. And the checks for NullPtr could be removed in SimOASystem.

    for (OASysNum = 1; OASysNum <= state.dataAirLoop->NumOASystems; ++OASysNum) {
        for (CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {

            } else if (state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::DXSystem)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9785. Also closes #9738 as duplicate issue.
 - Most objects used in the OA system are called using the index of the object. The CoilSystem:Cooling:DX, CoilSystem:Cooling:Water and AirloopHVAC:UnitarySystem are called using a pointer and this pointer is stored in the OA equipment list. This OA equipment list index can be different than the object index, for example with these objects are also used in the air loop. Then the OA equipment list index is typically different from the object index and the wrong component would be called, or a crash would occur if the object index was greater than the number of the equipment used in the OA system. These changes resolve the indexing issue.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/MixedAir.cc [hunk 1]
```diff
@@ -1186,8 +1173,12 @@ void GetOutsideAirSysInputs(EnergyPlusData &state)
...
                 state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompNum] = thisSys.factory(
                     state, DataHVACGlobals::UnitarySys_AnyCoilType, state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum), false, 0);
-                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) =
-                    UnitarySystems::getUnitarySystemIndex(state, state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum)) + 1;
+                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) = CompNum;
+            } else if (state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::DXSystem) {
+                UnitarySystems::UnitarySys thisSys;
+                state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompNum] = thisSys.factory(
+                    state, DataHVACGlobals::UnitarySys_AnyCoilType, state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum), false, 0);
+                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) = CompNum;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: Pass 1 is fix of issue, Pass 2 will clean up this function.

File: src/EnergyPlus/MixedAir.cc [hunk 2]
```diff
@@ -996,12 +957,12 @@ void GetOutsideAirSysInputs(EnergyPlusData &state)
     lAlphaBlanks.dimension(MaxAlphas, true);
     lNumericBlanks.dimension(MaxNums, true);
 
-    CurrentModuleObject = CurrentModuleObjects(static_cast<int>(CMO::ControllerList));
+    std::string_view CurrentModuleObject = CurrentModuleObjects(static_cast<int>(CMO::ControllerList));
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: Maybe I should have left this as a string since this gets modified again at line 1015. Or I could use 2 different string names? and set these as constexpr?

File: src/EnergyPlus/MixedAir.cc [hunk 3]
```diff
@@ -299,7 +299,8 @@ void SimOASysComponents(EnergyPlusData &state, int const OASysNum, bool const Fi
                        OASysNum,
                        OAHeatCoil,
                        OACoolCoil,
-                       OAHX);
+                       OAHX,
+                       CompNum);
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: These calls pass state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) as an index to a component. This index = 0 on the first call. In GetOutsideAirSysInputs, the pointer based objects call a factory and save the object pointer in the compPointer list using this index. So for pointer based objects ComponentIndex and compPointer are already set when we get here. However, this argument is a reference so the Array1D models can pass back an index into this array. The pointer based objects are stomping on this index.

File: src/EnergyPlus/MixedAir.cc [hunk 4]
```diff
@@ -637,56 +649,32 @@ void SimOAComponent(EnergyPlusData &state,
...
                                                                                         AirLoopNum,
-                                                                                        CompIndex,
+                                                                                        compNum,
                                                                                         HeatingActive,
                                                                                         CoolingActive,
-                                                                                        CompIndex,
+                                                                                        zoneOAUnitNum,
                                                                                         OAUCoilOutTemp,
                                                                                         ZoneEquipFlag,
                                                                                         sensOut,
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: Now here we are inside SimOAComponent. CompIndex is used as in index to the compPointer array as well as passed as an index to the object index. This call would simulate the CoilSystemWater object and pass back as a reference the object index into CompIndex at old line 686. This would then overwrite the value stored in state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) on the return from this function. Using a local here avoids this issue. Another possible solution would be to set all valid component indexes in GetOutsideAirSysInputs and not pass as reference the CompIndex, but that seemed to be a bigger change.

Comment (amirroth) [reply src/EnergyPlus/MixedAir.cc]: But that is ultimately what we need to do. Set up all objects and cross-indices in one or two passes and then use value indices from then on. The current approach is inefficient, redundant, and (as you've just seen but I didn't even anticipate) booby-trapped.

Comment (rraustad) [reply src/EnergyPlus/MixedAir.cc]: OK, I did start down that path and saw how many valid components are allowed in the OA system. I agree that is the best approach. Maybe it won't be as bad as first thought.

Comment (amirroth) [reply src/EnergyPlus/MixedAir.cc]: I wouldn't do this quite yet. This probably needs to be part of a "pass".

Comment (amirroth) [reply src/EnergyPlus/MixedAir.cc]: At the very least, there are a good number of other things I would do before I try to tackle this.

File: src/EnergyPlus/MixedAir.cc [hunk 5]
```diff
@@ -142,15 +142,15 @@ using namespace FaultsManager;
...
-                                           "OutdoorAir:Mixer"});
+const std::array<std::string_view, static_cast<int>(CMO::Num)> CurrentModuleObjects{"None",
+                                                                                    "AirLoopHVAC:OutdoorAirSystem",
+                                                                                    "AirLoopHVAC:OutdoorAirSystem:EquipmentList",
+                                                                                    "AirLoopHVAC:ControllerList",
+                                                                                    "AvailabilityManagerAssignmentList",
+                                                                                    "Controller:OutdoorAir",
+                                                                                    "ZoneHVAC:EnergyRecoveryVentilator:Controller",
+                                                                                    "Controller:MechanicalVentilation",
+                                                                                    "OutdoorAir:Mixer"};
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: constexpr here and const in `.hh`? or constexpr both places?

Comment (amirroth) [reply src/EnergyPlus/MixedAir.cc]: `const` in the `.hh`. In order for something to be `constexpr` it has to have the definition, i.e., the actual value.

File: src/EnergyPlus/HVACControllers.cc [hunk 6]
```diff
@@ -472,41 +456,28 @@ void GetControllerInput(EnergyPlusData &state)
...
     int NumNums;
     int NumArgs;
     int IOStat;
-    int AirLoopNum;            // DO index for each air loop
     bool ActuatorNodeNotFound; // true if no water coil inlet node match for actuator node
     Array1D<Real64> NumArray;
     Array1D_string AlphArray;
     Array1D_string cAlphaFields;     // Alpha field names
-    Array1D_string cNumericFields;   // Numeric field names
+    Array1D_string cNumericFields;   // Numeric field namesauto &
```
Comment (rraustad) [inline src/EnergyPlus/HVACControllers.cc]: whoops

File: src/EnergyPlus/MixedAir.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/MixedAir.cc]: This is confusing to explain. The state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) value needs to be set in GetOutsideAirSysInputs where the index to the OA equipment list component is known. This index is not known in SimOAComponent because it was not previously passed, the array value was passed. So because of this the object pointer is saved in compNum = 0 if it were not set in GetOutsideAirSysInputs:

    state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[compNum]->simulate() <-- compNum needs to be the OA system list index

compNum needs to be the index of the equipment in the OA System equipment list, not the equipment index.

In this loop, the loop counter CompNum needs to be saved in state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) because that is the index where the factory pointer is saved (in GetOutsideAirSysInputs). So if the factory is called in SimOAComponent, the index to the pointer = 0 because it has not yet been set.

    for (int CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {
        CompType = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentType(CompNum);
        CompName = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum);
        SimOAComponent(state,
                       CompType,
                       CompName,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum),
                       FirstHVACIteration,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum), <-- will be used in compPointer array

and when the factory is called, then the ComponentIndex should also be set:

    state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) = CompNum;

which feels redundant but not doing this is causing the indexing issue.

**Comment by rraustad** [comment]
This unit test, copied and replacing the develop branch test, fails as expected.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 7]
```diff
@@ -15952,25 +16014,29 @@ TEST_F(EnergyPlusFixture, Test_UnitarySystemModel_SubcoolReheatCoil)
...
-    state->dataLoopNodes->Node(1).Temp = 24.0;      // 24C db
-    state->dataLoopNodes->Node(1).HumRat = 0.01522; // 17C wb
-    state->dataLoopNodes->Node(1).Enthalpy = Psychrometrics::PsyHFnTdbW(state->dataLoopNodes->Node(1).Temp, state->dataLoopNodes->Node(1).HumRat);
-    state->dataLoopNodes->Node(1).Press = state->dataEnvrn->OutBaroPress;
+    int zoneNodeNum = state->dataZoneEquip->ZoneEquipConfig(1).ZoneNode;
+    state->dataLoopNodes->Node(zoneNodeNum).Temp = 24.0;      // 24C db
+    state->dataLoopNodes->Node(zoneNodeNum).HumRat = 0.01522; // 17C wb
+    state->dataLoopNodes->Node(zoneNodeNum).Enthalpy =
+        Psychrometrics::PsyHFnTdbW(state->dataLoopNodes->Node(zoneNodeNum).Temp, state->dataLoopNodes->Node(zoneNodeNum).HumRat);
+    state->dataLoopNodes->Node(zoneNodeNum).Press = state->dataEnvrn->OutBaroPress;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:16022]: I changed this section to look up the zoneNodeNum, so in the future if these nodes are read in a different order, the unit test still works.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 8]
```diff
@@ -15952,25 +16014,29 @@ TEST_F(EnergyPlusFixture, Test_UnitarySystemModel_SubcoolReheatCoil)
...
 
     state->dataZoneEnergyDemand->CurDeadBandOrSetback(1) = false;
     state->dataHeatBalFanSys->TempControlType.allocate(1);
     state->dataHeatBalFanSys->TempControlTypeRpt.allocate(1);
     state->dataHeatBalFanSys->TempControlType(1) = DataHVACGlobals::ThermostatType::DualSetPointWithDeadBand;
-    state->dataLoopNodes->Node(8).Temp = 23.822;      // 24C db
-    state->dataLoopNodes->Node(8).HumRat = 0.0145946; // 17C wb
-    state->dataLoopNodes->Node(8).Enthalpy = Psychrometrics::PsyHFnTdbW(state->dataLoopNodes->Node(8).Temp, state->dataLoopNodes->Node(8).HumRat);
-    state->dataLoopNodes->Node(8).Press = state->dataEnvrn->OutBaroPress;
+    int mixedAirNodeNum = state->dataMixedAir->OAMixer(1).MixNode;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:16034]: same lookup for correct node

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 9]
```diff
@@ -16073,6 +16141,51 @@ TEST_F(EnergyPlusFixture, Test_UnitarySystemModel_SubcoolReheatCoil)
     coilOutletEnthalpy = Psychrometrics::PsyHFnTdbW(coilOutletTemp, coilOutletHumRat);
     coilOutletTSat = Psychrometrics::PsyTsatFnHPb(*state, coilOutletEnthalpy, state->dataEnvrn->OutBaroPress);
     EXPECT_TRUE(coilOutletTemp >= coilOutletTSat);
+
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:16144]: New additions to unit test, same results as before up to this point. Check that the ComponentIndex and compPointer are looking at the correct object for the 2 new OA system objects added to this unit test OA equipment list (pointer based UnitarySystem objects).

**Comment by rraustad** [comment]
To the reviewer: this branch is 20 lines of bug fix and lots of clean up. CI is clean. 99.83% sure this is good. Unit test proves intent of fix. Merge at will (and pray a little bit that I have not made a mistake in this clean up).

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 10]
```diff
@@ -11110,13 +11110,12 @@ namespace AirflowNetwork {
...
         // Check number of fans specified in an AirLoop #6748
         int BranchNum;
-        int CompNum;
         int NumOfFans;
         std::string FanNames;
         for (BranchNum = 1; BranchNum <= m_state.dataAirSystemsData->PrimaryAirSystems(1).NumBranches; ++BranchNum) {
             NumOfFans = 0;
             FanNames = "";
-            for (CompNum = 1; CompNum <= m_state.dataAirSystemsData->PrimaryAirSystems(1).Branch(BranchNum).TotalComponents; ++CompNum) {
+            for (int CompNum = 1; CompNum <= m_state.dataAirSystemsData->PrimaryAirSystems(1).Branch(BranchNum).TotalComponents; ++CompNum) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:11118]: :+1: tighter scope

File: src/EnergyPlus/BranchNodeConnections.cc [hunk 11]
```diff
@@ -2081,11 +2081,11 @@ void TestInletOutletNodes(EnergyPlusData &state)
 }
 
 void TestCompSet(EnergyPlusData &state,
-                 std::string const &CompType,   // Component Type
-                 std::string_view CompName,     // Component Name
-                 std::string const &InletNode,  // Inlet Node Name
-                 std::string const &OutletNode, // Outlet Node Name
-                 std::string const &Description // Description of Node Pair (for warning message)
+                 std::string_view const CompType, // Component Type
```
Comment (Myoldmopar) [inline src/EnergyPlus/BranchNodeConnections.cc:2084]: Yeah, this makes sense.  If the comp type is a variable, the string will be stored somewhere and a string view into that string is a fine option for this argument.  If the comp type is a string view itself, like a hardcoded set of characters, then passing it in as-is works well.

File: src/EnergyPlus/DataAirLoop.hh [hunk 12]
```diff
@@ -203,11 +211,12 @@ namespace DataAirLoop {
...
         Array1D_string ControllerType;
-        Array1D_int ControllerIndex;    // Which one in list -- updated by routines called from here
-        Array1D_int InletNodeNum;       // component inlet node number
-        Array1D_int OutletNodeNum;      // component outlet node number
-        bool HeatExchangerFlag = false; // True to have a heat exchanger in the equipment list
-        int AirLoopDOASNum = -1;        // AirLoopHVAC:DedicatedOutdoorAirSystem number
+        EPVector<ControllerKind> controllerTypeEnum; // Controller:OutdoorAir or Controller:WaterCoil
+        Array1D_int ControllerIndex;                 // Which one in list -- updated by routines called from here
+        Array1D_int InletNodeNum;                    // component inlet node number
+        Array1D_int OutletNodeNum;                   // component outlet node number
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataAirLoop.hh:217]: Adding the EPVector is better than adding another Array1D.  Another possible improvement would be to change the other Array1D to EPVector -- in most cases it won't require major code changes.  Of course the ideal scenario would be to, sometime, do the full work in converting them to plain std::vector, but that requires index zero changes, so it's a bit more intrusive.  No problem, this is fine for now.

File: src/EnergyPlus/FanCoilUnits.cc [hunk 13]
```diff
@@ -3666,7 +3665,7 @@ namespace FanCoilUnits {
             }
             Node(FanCoil(FanCoilNum).AirReliefNode).MassFlowRate = Node(FanCoil(FanCoilNum).OutsideAirNode).MassFlowRate;
             AirMassFlow = Node(InletNode).MassFlowRate;
-            SimOAMixer(state, FanCoil(FanCoilNum).OAMixName, FirstHVACIteration, FanCoil(FanCoilNum).OAMixIndex);
+            MixedAir::SimOAMixer(state, FanCoil(FanCoilNum).OAMixName, FanCoil(FanCoilNum).OAMixIndex);
```
Comment (Myoldmopar) [inline src/EnergyPlus/FanCoilUnits.cc:3668]: Fantastic, a removed `using` and a removed argument :+1:

File: src/EnergyPlus/GeneralRoutines.cc [hunk 14]
```diff
@@ -664,7 +664,7 @@ void CheckSysSizing(EnergyPlusData &state,
     // Checks SysSizingRunDone flag. If false throws a fatal error.
 
     if (!state.dataSize->SysSizingRunDone) {
-        ShowSevereError(state, "For autosizing of " + CompType + ' ' + CompName + ", a system sizing run must be done.");
+        ShowSevereError(state, format("For autosizing of {} {}, a system sizing run must be done.", CompType, CompName));
```
Comment (Myoldmopar) [inline src/EnergyPlus/GeneralRoutines.cc:667]: Expected changes to accompany string views :+1:

File: src/EnergyPlus/HVACControllers.cc [hunk 15]
```diff
@@ -223,32 +223,15 @@ void ManageControllers(EnergyPlusData &state,
...
-
     // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
     // The Controller that you are currently loading input into
     int ControlNum;
-    int ControllerType;
 
     auto &ControllerProps(state.dataHVACControllers->ControllerProps);
-    auto &NumControllers(state.dataHVACControllers->NumControllers);
     auto &CheckEquipName(state.dataHVACControllers->CheckEquipName);
     auto &RootFinders(state.dataHVACControllers->RootFinders);
```
Comment (Myoldmopar) [inline src/EnergyPlus/HVACControllers.cc:236]: Some future work possibilities:
 - Don't use a reference to the ControllerProps array, just wait and get a reference to a particular controller
 - Eliminate the separate CheckEquipName array, and just add a single boolean to the controller struct.  That's one less array to allocate and manage and almost always eliminates a 'one-time' flag from state at the same time.
 - Look for simple conversions from functions that take ControlNum into member methods.  From a quick glance there are several that could be quickly converted.

This is just stuff for the future, not asking to add to this PR.

File: src/EnergyPlus/HVACControllers.cc [hunk 16]
```diff
@@ -762,82 +730,69 @@ void ResetController(EnergyPlusData &state, int const ControlNum, bool const DoW
...
+    RootFinders.CurrentPoint.Y = 0.0;
 
-    RootFinders(ControlNum).MinPoint.DefinedFlag = false;
-    RootFinders(ControlNum).MaxPoint.DefinedFlag = false;
-    RootFinders(ControlNum).LowerPoint.DefinedFlag = false;
-    RootFinders(ControlNum).UpperPoint.DefinedFlag = false;
+    RootFinders.MinPoint.DefinedFlag = false;
+    RootFinders.MaxPoint.DefinedFlag = false;
+    RootFinders.LowerPoint.DefinedFlag = false;
+    RootFinders.UpperPoint.DefinedFlag = false;
```
Comment (Myoldmopar) [inline src/EnergyPlus/HVACControllers.cc:795]: :+1:

File: src/EnergyPlus/HVACControllers.cc [hunk 17]
```diff
@@ -867,19 +822,14 @@ void InitController(EnergyPlusData &state, int const ControlNum, bool &IsConverg
...
+    bool &InitControllerOneTimeFlag(state.dataHVACControllers->InitControllerOneTimeFlag);
+    bool &InitControllerSetPointCheckFlag(state.dataHVACControllers->InitControllerSetPointCheckFlag);
     auto &ControllerProps(state.dataHVACControllers->ControllerProps);
     auto &RootFinders(state.dataHVACControllers->RootFinders);
-    auto &MyEnvrnFlag(state.dataHVACControllers->MyEnvrnFlag);
-    auto &MySizeFlag(state.dataHVACControllers->MySizeFlag);
-    auto &MyPlantIndexsFlag(state.dataHVACControllers->MyPlantIndexsFlag);
+    Array1D_bool &MyEnvrnFlag(state.dataHVACControllers->MyEnvrnFlag);
+    Array1D_bool &MySizeFlag(state.dataHVACControllers->MySizeFlag);
+    Array1D_bool &MyPlantIndexsFlag(state.dataHVACControllers->MyPlantIndexsFlag);
```
Comment (Myoldmopar) [inline src/EnergyPlus/HVACControllers.cc:832]: This is a fine change.  I'll repeat that in the future, it would be great to not have these separate arrays of flags.  Just add a `bool envrnFlag` and `bool sizeFlag` and `bool plantIndexFlag` to the controller structure.  That would eliminate 3 additional arrays that have to live out on state, and likely at least one or two boolean flags that already live on state that are only used to one-time allocate these arrays.  :pushpin:

File: src/EnergyPlus/MixedAir.hh [hunk 18]
```diff
@@ -140,133 +138,112 @@ namespace MixedAir {
...
+        Real64 MaxOAFracBySetPoint = 0.0;                      // The maximum OA fraction due to freezing cooling coil check
+        int MixedAirSPMNum = 0;                                // index of mixed air setpoint manager
+        bool CoolCoilFreezeCheck = false;                      // if true, cooling coil freezing is prevented by recalculating the amount of OA
+        bool EconoActive = false;                              // if true economizer is active
+        bool HighHumCtrlActive = false;                        // if true high humidity control is active
+        Array1D_int EconmizerFaultNum;                         // index to economizer fault
+        int NumFaultyEconomizer = 0;                           // total number of economizer faults
+        int CountMechVentFrac = 0;                             // Count when OA min fraction > mech vent fraction
+        int IndexMechVentFrac = 0;                             // Index when OA min fraction > mech vent fraction
+        int OALimitingFactor = 0; // OA controller limiting factor: 0=none, 1=limits, 2=exhaust flow, 3=economizer, 4=DCV, 5=high hum, 6=night vent,
```
Comment (Myoldmopar) [inline src/EnergyPlus/MixedAir.hh:245]: Nice constructor cleanup, thanks!

File: src/EnergyPlus/MixedAir.hh [hunk 19]
```diff
@@ -527,8 +484,8 @@ namespace MixedAir {
     int GetOAMixerMixedNodeNumber(EnergyPlusData &state, int const OAMixerNumber); // Which Mixer
 
     bool CheckForControllerWaterCoil(EnergyPlusData &state,
-                                     std::string const &ControllerType, // should be passed in as UPPERCASE
-                                     std::string const &ControllerName  // should be passed in as UPPERCASE
+                                     DataAirLoop::ControllerKind ControllerType, // should be passed in as UPPERCASE
```
Comment (Myoldmopar) [inline src/EnergyPlus/MixedAir.hh:487]: :+1: :+1:

**Review by Myoldmopar — APPROVED** [review]
This looks really good to me.  Lots and lots of good cleanup.  A majority of the changes are either good or loudly broken, not quietly wrong.  Changing the argument types and variable types to string views require changes to format, etc.  Using appropriate reference variables requires updating all the usage locations.  This all looks happy.

**Comment by Myoldmopar** [comment]
Local testing looks good.  There is one unused variable warning that I'm cleaning up locally now and one unused lambda capture I'm cleaning up then I'll push.  The only regression was a small diff in node numbering in one BND file, but no impact on results.  I'll push the change up and may wait until CI but I don't really think it's necessary.

**Comment by Myoldmopar** [comment]
OK, cleaning up the unused lambda capture led to an argument showing as unused.  I tagged it as maybe unused so I didn't have to unravel that right now.  Given the changes got a little deeper I think I will wait on CI.  If it's happy, this is ready to go.  Thanks @rraustad

**Comment by Myoldmopar** [comment]
Looks like it came back all happy.  Merging this.  Thanks @rraustad
