### PR TITLE
Add Space Component Loads Report and Fix Zone Component Loads when Enclosures Differ from Zones

### LINKED ISSUE #10784: Zone Component Loads Report may be incorrect when Zones and Enclosures are not the same
Issue overview
--------------
When zones and enclosures are not 1:1, the zone component loads report values for "Sensible-Delayed" internal gains (People, Lights, etc.) are incorrect. They are calculated using the zone's internal gain radiant intensities instead of the enclosure intensities. These values also affect the delayed envelope components as well. This may impact results in models with air boundary surfaces and/or zones with multiple spaces in them.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 24.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files are example files 5ZoneAirCooled_AirBoundaries, 5ZoneAirCooled_AirBoundaries_Daylighting, 5ZoneAirCooledWithSpaces, 5ZoneAirCooledWithSpacesDaylightingIntMass, and 5ZoneAirCooledWithSpacesHVAC.

 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Adds Space Component Loads Report. This report will be produced when the Zone Component Loads Report is requested and "Do Space Heat Balance for Sizing" is active.
 - Fixes #10784 
 - Replaced 33 `Array3D` with nested vectors of structs in `OutputReportsTabular`.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/InternalHeatGains.cc [hunk 1]
```diff
@@ -9494,7 +9506,23 @@ namespace InternalHeatGains {
...
+            for (int iZone = 1; iZone <= state.dataGlobal->NumOfZones; ++iZone) {
+                auto &znCLDayTS = state.dataOutRptTab->znCompLoads[iZone - 1].day[state.dataSize->CurOverallSimDay - 1].ts[TimeStepInDay - 1];
+                gatherCompLoadIntGain2(state, znCLDayTS, iZone);
+            }
+            if (state.dataHeatBal->doSpaceHeatBalanceSizing) {
+                for (int iSpace = 1; iSpace <= state.dataGlobal->NumOfZones; ++iSpace) {
+                    auto &spCLDayTS = state.dataOutRptTab->spCompLoads[iSpace - 1].day[state.dataSize->CurOverallSimDay - 1].ts[TimeStepInDay - 1];
+                    gatherCompLoadIntGain2(state, spCLDayTS, state.dataHeatBal->space(iSpace).zoneNum, iSpace);
+                }
+            }
```
Comment (rraustad) [inline src/EnergyPlus/InternalHeatGains.cc:8991]: I recall something about if space heat balance is active, then the zone HB results are overwritten with the sum of the spaces. If that's true then why bother processing the zones at all (line 9511) if those results are overwritten by 9516? Is line 9516 iSpace = 1 to NumOfZones, or 1 to numSpaces?

    If (state.dataHeatBal->doSpaceHeatBalanceSizing) {
        gather spaces, 9516 to 9519
    } else {
        gather zones, 9511 to 9514
    }

Comment (mjwitte) [reply src/EnergyPlus/InternalHeatGains.cc:8991]: That's possible. Baby steps at this point. Just trying to find all of the places that apply so that the space results are really just for the space.

File: src/EnergyPlus/CurveManager.cc [hunk 2]
```diff
@@ -53,7 +53,6 @@
 
 // ObjexxFCL Headers
 #include <ObjexxFCL/Array.functions.hh>
-#include <ObjexxFCL/Array3D.hh>
```
Comment (mjwitte) [inline src/EnergyPlus/CurveManager.cc:56]: Removed several stray includes that were no longer being used.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 3]
```diff
@@ -14940,20 +14865,16 @@ void WriteLoadComponentSummaryTables(EnergyPlusData &state)
 
     // Delayed components are moved into this function so that we can calculate them one zone at a time
     // with Array1D
-    Array1D<Real64> peopleDelaySeqHeat;
-    Array1D<Real64> peopleDelaySeqCool;
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc]: These arrays are temporary and used one at a time, collapsed into a single set to use for both heat and cool.

File: src/EnergyPlus/OutputReportTabular.hh [hunk 4]
```diff
@@ -489,6 +491,86 @@ namespace OutputReportTabular {
...
+
+    struct compLoadsTimeStepSurfaces
+    {
+        std::vector<compLoadsSurface> surf;
+    };
+
+    struct componentLoadsSurf
+    {
+        std::vector<compLoadsTimeStepSurfaces> ts;
+    };
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.hh:512]: New sets of nested vectors to replace a bunch of loose `Array3D`. This is for surfaces, similar ones for zone/spaces, and enclosures.

File: src/EnergyPlus/OutputReportTabular.hh [hunk 5]
```diff
@@ -1155,50 +1261,13 @@ struct OutputReportTabularData : BaseGlobalStruct
     // arrays related to pulse and load component reporting
     Array2D_int radiantPulseTimestep;
     Array2D<Real64> radiantPulseReceived;
-    Array3D<Real64> loadConvectedNormal;
-    Array3D<Real64> loadConvectedWithPulse;
-    Array3D<Real64> netSurfRadSeq;
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.hh:1159]: Replaced these and many other `Array3D` with nested `std::vector`.

File: src/EnergyPlus/OutputReportTabular.hh [hunk 6]
```diff
@@ -1155,50 +1261,13 @@ struct OutputReportTabularData : BaseGlobalStruct
...
-
-    Array3D<Real64> interZoneMixInstantSeq;
-    Array3D<Real64> interZoneMixLatentSeq;
-
-    Array3D<Real64> feneCondInstantSeq;
-    Array3D<Real64> feneSolarRadSeq;
+    std::vector<OutputReportTabular::componentLoadsSurf> surfCompLoads; // Surface component loads by day, timestep, then surface
+    std::vector<OutputReportTabular::componentLoadsSpZn> znCompLoads;   // Zone component loads by day, timestep, then zone
+    std::vector<OutputReportTabular::componentLoadsSpZn> spCompLoads;   // Space component loads by day, timestep, then space
+    std::vector<OutputReportTabular::componentLoadsEncl> enclCompLoads; // Enclosure component loads by day, timestep, then enclsoure
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.hh:1269]: New component loads vectors for surface, zone, space, and enclosure.

File: src/EnergyPlus/OutputReportTabular.hh [hunk 7]
```diff
@@ -1306,18 +1375,6 @@ struct OutputReportTabularData : BaseGlobalStruct
...
-    int TimeStepCLCDC = 0;
-    int TimeOfPulseCLCDC = 0;
-    int CoolDesSelectedCLCDC = 0; // design day selected for cooling
-    int HeatDesSelectedCLCDC = 0; // design day selected for heating
-    int iSurfGCLS = 0;
-    int ZoneNumGCLS = 0;
-    int TimeStepInDayGCLS = 0;
-    int iZoneGCLH = 0;
-    int TimeStepInDayGCLH = 0;
-    Array3D_bool adjFenDone;
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.hh:1319]: Moved out of `state`.

**Review by mjwitte — COMMENTED** [review]
Refactoring code walkthru . . .

File: src/EnergyPlus/InternalHeatGains.cc [hunk 8]
```diff
@@ -9229,6 +9303,32 @@ namespace InternalHeatGains {
         return SumRadiationGainRate;
     }
 
+    Real64 SumEnclosureInternalRadiationGainsByTypes(
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:8680]: New function to sum radiant gains by enclosure.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 9]
```diff
@@ -9494,120 +9594,57 @@ namespace InternalHeatGains {
...
+                gatherCompLoadIntGain2(state, znCLDayTS, iZone);
+            }
+            for (int iEncl = 1; iEncl <= state.dataViewFactor->NumOfRadiantEnclosures; ++iEncl) {
+                auto &enclCLDayTS = state.dataOutRptTab->enclCompLoads[state.dataSize->CurOverallSimDay - 1].ts[TimeStepInDay - 1].encl[iEncl - 1];
+                enclCLDayTS.peopleRadSeq = SumEnclosureInternalRadiationGainsByTypes(state, iEncl, IntGainTypesPeople);
+                enclCLDayTS.lightLWRadSeq = SumEnclosureInternalRadiationGainsByTypes(state, iEncl, IntGainTypesLight);
+                enclCLDayTS.equipRadSeq = SumEnclosureInternalRadiationGainsByTypes(state, iEncl, IntGainTypesEquip);
+                enclCLDayTS.hvacLossRadSeq = SumEnclosureInternalRadiationGainsByTypes(state, iEncl, IntGainTypesHvacLoss);
+                enclCLDayTS.powerGenRadSeq = SumEnclosureInternalRadiationGainsByTypes(state, iEncl, IntGainTypesPowerGen);
+            }
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:8984]: Save enclosure gain sequences by type for use later in component load calcs.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 10]
```diff
@@ -15645,17 +15647,19 @@ void GetDelaySequences(EnergyPlusData &state,
...
-                        equipConvFromSurf += ort->equipRadSeq(desDaySelected, sourceStep, zoneIndex) * thisQRadThermInAbsMult;
-                        hvacLossConvFromSurf += ort->hvacLossRadSeq(desDaySelected, sourceStep, zoneIndex) * thisQRadThermInAbsMult;
-                        powerGenConvFromSurf += ort->powerGenRadSeq(desDaySelected, sourceStep, zoneIndex) * thisQRadThermInAbsMult;
-                        lightLWConvFromSurf += ort->lightLWRadSeq(desDaySelected, sourceStep, zoneIndex) * thisQRadThermInAbsMult;
+                        auto &compLoadTS = szCLDay.ts[sourceStep - 1].spacezone[szNumMinus1];
+                        auto const &surfCLDayTS = surfCLDay.ts[sourceStep - 1].surf[jSurf - 1];
+                        auto const &enclCLDayTS = enclCLDay.ts[sourceStep - 1].encl[radEnclosureNum - 1];
+                        Real64 thisQRadThermInAbsMult =
+                            surfCLDayTS.TMULTseq * surfCLDayTS.ITABSFseq * state.dataSurface->Surface(jSurf).Area * decayCurve(mStepBack, jSurf);
+                        peopleConvFromSurf += enclCLDayTS.peopleRadSeq * thisQRadThermInAbsMult;
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc]: Use enclosure gain sequences now. Previously, zone gains were used which could be high or low depending on how the zones/spaces/enclosures align.

**Review by mjwitte — COMMENTED** [review]
Walkthru for fix #10784 . . .

File: src/EnergyPlus/HVACManager.cc [hunk 11]
```diff
@@ -2261,58 +2266,28 @@ void ReportAirHeatBalance(EnergyPlusData &state)
...
+        auto &znAirRpt = state.dataHeatBal->ZnAirRpt(zoneNum);
+        auto &znEquipConfig = state.dataZoneEquip->ZoneEquipConfig(zoneNum);
+        reportAirHeatBal1(state, znAirRpt, znEquipConfig, zoneNum);
+    }
+    if (state.dataHeatBal->doSpaceHeatBalance) {
+        for (int spaceNum = 1; spaceNum <= state.dataGlobal->numSpaces; ++spaceNum) {
+            auto &spAirRpt = state.dataHeatBal->spaceAirRpt(spaceNum);
+            auto &spEquipConfig = state.dataZoneEquip->spaceEquipConfig(spaceNum);
+            int zoneNum = state.dataHeatBal->space(spaceNum).zoneNum;
+            reportAirHeatBal1(state, spAirRpt, spEquipConfig, zoneNum, spaceNum);
```
Comment (mjwitte) [inline src/EnergyPlus/HVACManager.cc:2291]: Break up `ReportAirHeatBalance` into smaller functions that can be re-used for zones and spaces.

File: src/EnergyPlus/HVACManager.hh [hunk 12]
```diff
@@ -140,8 +153,6 @@ struct HVACManagerData : BaseGlobalStruct
     int ErrCount = 0; // Number of times that the maximum iterations was exceeded
     int MaxErrCount = 0;
     std::string ErrEnvironmentName;
-    Array1D<Real64> MixSenLoad; // Mixing sensible loss or gain
-    Array1D<Real64> MixLatLoad; // Mixing latent loss or gain
```
Comment (mjwitte) [inline src/EnergyPlus/HVACManager.hh:144]: Moved to `DataHeatBalance::AirReportVars`.

File: src/EnergyPlus/HeatBalanceAirManager.cc [hunk 13]
```diff
@@ -286,7 +286,7 @@ void GetSimpleAirModelInputs(EnergyPlusData &state, bool &ErrorsFound) // IF err
 
     // Following used for reporting
     state.dataHeatBal->ZnAirRpt.allocate(state.dataGlobal->NumOfZones);
-    if (state.dataHeatBal->doSpaceHeatBalanceSimulation) {
+    if (state.dataHeatBal->doSpaceHeatBalance) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceAirManager.cc]: Hmm, this is wrong, should be `doSpaceHeatBalanceSimulation || doSpaceHeatBalanceSizing`. It might be ok, but not safe if sizing is false and simulation is true. Will fix.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 14]
```diff
@@ -14788,85 +14729,69 @@ void GatherComponentLoadsHVAC(EnergyPlusData &state)
...
-        ort->infilLatentSeq(state.dataSize->CurOverallSimDay, state.dataOutRptTab->TimeStepInDayGCLH, state.dataOutRptTab->iZoneGCLH) =
-            ((state.dataHeatBal->ZnAirRpt(state.dataOutRptTab->iZoneGCLH).InfilLatentGain -
-              state.dataHeatBal->ZnAirRpt(state.dataOutRptTab->iZoneGCLH).InfilLatentLoss) /
-             TimeStepSysSec); // zone infiltration
+    int timeStepInDayGCLH = (state.dataGlobal->HourOfDay - 1) * state.dataGlobal->NumOfTimeStepInHour + state.dataGlobal->TimeStep;
+    auto &znCompLoadDayTS = state.dataOutRptTab->znCompLoads[state.dataSize->CurOverallSimDay - 1].ts[timeStepInDayGCLH - 1];
+    for (int iZoneGCLH = 1; iZoneGCLH <= state.dataGlobal->NumOfZones; ++iZoneGCLH) {
+        auto &znCompLoadDayTSZone = znCompLoadDayTS.spacezone[iZoneGCLH - 1];
+        auto &zoneAirRpt = state.dataHeatBal->ZnAirRpt(iZoneGCLH);
+        gatherSpaceZoneCompLoadsHVAC(znCompLoadDayTSZone, zoneAirRpt, state.dataHVACGlobal->TimeStepSysSec);
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc]: Another breakup into smaller functions.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 15]
```diff
@@ -15086,103 +15009,63 @@ void WriteLoadComponentSummaryTables(EnergyPlusData &state)
...
 
         // ZoneComponentLoadSummary
         if (ort->displayZoneComponentLoadSummary) {
+            if (state.dataHeatBal->doSpaceHeatBalanceSizing) {
+                for (int iSpace = 1; iSpace <= state.dataGlobal->numSpaces; ++iSpace) {
+                    // Yes, check if the zone is controlled, not the space for this
+                    int zoneNum = state.dataHeatBal->space(iSpace).zoneNum;
+                    if (!state.dataZoneEquip->ZoneEquipConfig(zoneNum).IsControlled) continue;
+                    if (allocated(state.dataSize->CalcFinalSpaceSizing)) {
+                        computeSpaceZoneCompLoads(state,
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc:15028]: This pattern repeats several times, called for either space of zone.

**Review by mjwitte — COMMENTED** [review]
Space component loads walkthru . . .

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mjwitte it has been 16 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mjwitte it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @mjwitte it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Pulled in develop to get the license year fixed.  Everything is passing locally so I expect this to be back to what it was before with just a few table diffs.  If so, I think this is probably ready to go in.  Any final thoughts from @mjwitte or anyone else?

**Comment by mjwitte** [comment]
> Pulled in develop to get the license year fixed. Everything is passing locally so I expect this to be back to what it was before with just a few table diffs. If so, I think this is probably ready to go in. Any final thoughts from @mjwitte or anyone else?

Nothing more from me.

**Comment by Myoldmopar** [comment]
Fully happy still with latest develop, merging.  Thanks @mjwitte !

File: src/EnergyPlus/InternalHeatGains.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc:8991]: @mjwitte you never answered "Is line 9516 iSpace = 1 to NumOfZones, or 1 to numSpaces?" and I still see that in develop. 

I see it as line 8986 now. Should be 1 to NumOfSpaces?

            if (state.dataHeatBal->doSpaceHeatBalanceSizing) {
                for (int iSpace = 1; iSpace <= state.dataGlobal->NumOfZones; ++iSpace) {

Comment (mjwitte) [reply src/EnergyPlus/InternalHeatGains.cc:8991]: > for (int iSpace = 1; iSpace <= state.dataGlobal->NumOfZones;

@rraustad Yikes! This pasteo is in the code three times . . .
image

I'll open branch to fix this. Thanks for remembering this.
