### PR TITLE
Set `MassFlowRateMaxAvail` and `MassFlowRateMinAvail` for downstream leakage

### LINKED ISSUE #11262: Downstream leakage issue with simple duct leakage model
### Issue overview

The attached file, which includes downstream leakage for one of the terminal, shows that the terminal flow rate (to the zone) appears to be incorrect. Comparing results with and without downstream leakage shows that
- **During dead-band operations**: The flow rate in the two cases is the same. I would expect the flow rate to be lower in the case with leakage. I think that the primary flow rate should be the same (at the minimum), but when leakage is modeled, I would expect the flow rate to the zone should be the minimum primary air flow rate minus the leakage.
- **During heating/cooling operations**: Simulation output shows that the terminal airflow rate to the zone when leakage is modeled can reach the terminal maximum air flow rate (see EIO excerpt below), however, I would expect it to be a maximum minus the leakage.

```
 Component Sizing Information, AirTerminal:SingleDuct:VAV:Reheat, SPACE1-1 VAV REHEAT, Design Size Maximum Air Flow Rate [m3/s], 0.34649
```
The results below show a case with no downstream leakage in blue, and with leakage in orange. `Space1-1 IN Node` is the `Zone Air Inlet Node`.

Image

### Operating System (Multiple choices)

MacOS

### Operating System Version

15.7

### Version of EnergyPlus

25.2 develop (86cc706c151bf343cb9f6bf4448b452c28aa7960)

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[defect_file.txt](https://github.com/user-attachments/files/22784484/defect_file.txt)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11262

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lymereJ** [comment]
Here are the updated charts from the issue.

image

The changes from this branch and shown in maroon (top panel) and dark green (bottom). During the dead-band operations, the terminal damper is at its minimum, and the flow rate is at the minimum primary flow rate minus the leakage (about 30% lower). Similarly, during cooling operation, the terminal damper opens all the way to 100%, and the air flow leaving the terminal is at the maximum minus the leakage (about 30% lower).

File: src/EnergyPlus/ZoneAirLoopEquipmentManager.cc [hunk 1]
```diff
@@ -575,8 +575,8 @@ namespace ZoneAirLoopEquipmentManager {
             MassFlowRateMaxAvail = 0.0;
             MassFlowRateMinAvail = 0.0;
             // check for no plenum
-            // set the max and min avail flow rates taking into acount the upstream leak
-            if (airDistUnit.UpStreamLeak) {
+            // set the max and min avail flow rates taking into account the upstream leak
+            if (airDistUnit.UpStreamLeak || airDistUnit.DownStreamLeak) {
```
Comment (lymereJ) [inline src/EnergyPlus/ZoneAirLoopEquipmentManager.cc:579]: Adding `airDistUnit.DownStreamLeak` allows `MassFlowRateMaxAvail` to be set, without this the following would never be true:

https://github.com/NREL/EnergyPlus/blob/05a67847d0a2b7024e9ed5e92e2e6647ff315b67/src/EnergyPlus/ZoneAirLoopEquipmentManager.cc#L749

File: tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc [hunk 2]
```diff
@@ -1189,4 +1189,127 @@ TEST_F(EnergyPlusFixture, AirTerminalSingleDuctCVNoReheat_SimSensibleOutPutTest)
...
+    // set inlet mass flow rate to zero
+    state->dataLoopNodes->Node(InletNode).MassFlowRate = 0.0;
+    FirstHVACIteration = true;
+    state->dataSingleDuct->GetInputFlag = false;
+    state->dataLoopNodes->Node(InletNode).MassFlowRateMaxAvail = MassFlowRateMaxAvail;
+    Real64 SysOutputProvided = 0.0;
+    Real64 NonAirSysOutput = 0.0;
+    Real64 LatOutputProvided = 0.0;
+    SimZoneAirLoopEquipment(*state, AirDistUnitNum, SysOutputProvided, NonAirSysOutput, LatOutputProvided, FirstHVACIteration, ZonePtr);
+    EXPECT_EQ(MassFlowRateMaxAvail * (1 - 0.29), state->dataLoopNodes->Node(thisAirTerminal.OutletNodeNum).MassFlowRate);
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc:1312]: New test; Checks that the terminal outlet is the inlet minus leakage.

**Review by lymereJ — COMMENTED** [review]
Walk-through:

**Comment by rraustad** [comment]
The TU leakage fractions are 0.05 and 0.07. The TU max flow is 0.35 m3/s (the no leakage case). So air entering the TU (or just after the TU entrance before the damper) should be 0.35 * (1 - 0.05) = 0.3325 m3/s. SPACE1-1 In Node is the node entering the zone so any downstream leakage would be happening within the TU or near the TU outlet node. 0.3325 * (1 - 0.07) = 0.3092 m3/s. So why does your figure show 0.25 m3/s? Questions: 1) where is this leakage going? 2) what is the magnitude of the leakage components (upstream and downstream output reports)? 3) What is the supply air flow rate leaving the air loop? 4) Which should equal the sum of the TU entering air flow rates? 5) What is the impact of leakage on zone air temperature if these TU dampers are at 100%.

    ZoneHVAC:AirDistributionUnit,
      SPACE1-1 ATU,            !- Name
      SPACE1-1 In Node,        !- Air Distribution Unit Outlet Node Name
      AirTerminal:SingleDuct:VAV:Reheat,  !- Air Terminal Object Type
      SPACE1-1 VAV Reheat,     !- Air Terminal Name
      0.05,                    !- Nominal Upstream Leakage Fraction
      0.07;                    !- Constant Downstream Leakage Fraction

    N1 , \field Nominal Upstream Leakage Fraction
       \note fraction at system design Flow; leakage Flow constant, leakage fraction
       \note varies with variable system Flow Rate.
       \type real
       \minimum 0
       \maximum 0.3
       \default 0
    N2 , \field Constant Downstream Leakage Fraction
       \type real
       \minimum 0
       \maximum 0.3
       \default 0

This is what I see in the eio file:

    Zone Sizing Information, SPACE1-1, Cooling, 2638.87262, 3430.53441, 0.22196, 0.28855
    Component Sizing Information, AirTerminal:SingleDuct:VAV:Reheat, SPACE1-1 VAV REHEAT, Design Size Maximum Air Flow Rate [m3/s], 0.28855

**Comment by lymereJ** [comment]
> ```
> ZoneHVAC:AirDistributionUnit,
>   SPACE1-1 ATU,            !- Name
>   SPACE1-1 In Node,        !- Air Distribution Unit Outlet Node Name
>   AirTerminal:SingleDuct:VAV:Reheat,  !- Air Terminal Object Type
>   SPACE1-1 VAV Reheat,     !- Air Terminal Name
>   0.05,                    !- Nominal Upstream Leakage Fraction
>   0.07;                    !- Constant Downstream Leakage Fraction
> 
> ```

@rraustad - Are you looking at the correct file? The defect file is setup as follows, there are no upstream leakage define in the model.

```
  ZoneHVAC:AirDistributionUnit,
    SPACE1-1 ATU,            !- Name
    SPACE1-1 In Node,        !- Air Distribution Unit Outlet Node Name
    AirTerminal:SingleDuct:VAV:Reheat,  !- Air Terminal Object Type
    SPACE1-1 VAV Reheat,     !- Air Terminal Name
    0.0,                    !- Nominal Upstream Leakage Fraction
    0.29;                    !- Constant Downstream Leakage Fraction
```

**Comment by rraustad** [comment]
Oh, I saw 5ZoneWarmest and looked at and ran the example file, in Chicago. 0.35 * (1-0.29) = 0.2485. Now the numbers make sense but I still would like to see the leakage plots just to make sure they do what we expect. I see what you did and why but we should make sure everything works correctly. I would think the SA flow rate equals the sum of TU entering air flow rate and suspect that would match because the simulation would go to max iterations if it didn't so you probably don't need to look at that. Does the leakage go to the zone (a cooling effect)? The plenum? Is it the correct flow rate?

    Zone Sizing Information, SPACE1-1, Cooling, 2634.04754, 3424.26181, 0.26406, 0.34328
    Component Sizing Information, AirTerminal:SingleDuct:VAV:Reheat, SPACE1-1 VAV REHEAT, Design Size Maximum Air Flow Rate [m3/s], 0.34328

Docs don't say where the leakage goes:

image

Here it is in the Eng Ref. Says the leakage goes to the plenum, but this is a downstream leak so where does that air go?

image

**Comment by rraustad** [comment]
Again from the Eng Ref, the leakage flows vanish. I suspect both upstream and downstream are added to the plenum but this suggests that at least the downstream leakage is not accounted for (because elsewhere it says upstream leakage goes to the plenum), which I think should either go to the zone of the plenum (if it exists). The last line says these leakage flows are added to the plenum.

image

File: src/EnergyPlus/ZoneAirLoopEquipmentManager.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/ZoneAirLoopEquipmentManager.cc:579]: The code below (580 - 604) is only looking at the upstream leakage fraction. If it's 0, as in the defect file, then the local variable MassFlowRateMaxAvail wont get set without this change and line 749 jumps to the else. So this change seems correct.

**Comment by rraustad** [comment]
@mitchute I've looked at this from all angles. This change looks correct.

**Review by rraustad — APPROVED** [review]

**Review by mitchute — APPROVED** [review]
Thanks, all. Merging.
