### PR TITLE
SizingPeriod:DesignDay Enthalpy at Maximum Dry-Bulb is not applied correctly - off by x1000

### LINKED ISSUE #7550: SizingPeriod:DesignDay Enthalpy at Maximum Dry-Bulb is not applied correctly - off by x1000
Issue overview
--------------
User noted that SizingPeriod:DesignDay with Humidity Condition Type=Enthalpy does not result in the entered value for Enthalpy at Maximum Dry-Bulb.

The design day in the defect file has an enthalpy input of 90500.0, so the output for Site Outdoor Air Enthalpy should never exceed this value and should match it at the max dry-bulb. Actual output is showing values as high as 117192 and the RH is always 100%

The problem is here in `WeatherManager::SetUpDesignDay` line 4451:
```
            } else if (SELECT_CASE_var == DDHumIndType_Enthalpy) {
                HumidityRatio = PsyWFnTdbH(DesDayInput(EnvrnNum).MaxDryBulb, DesDayInput(EnvrnNum).HumIndValue * 1000.0, RoutineNamePsyWFnTdbH);
                ConstantHumidityRatio = true;
```
Enthalpy at Maximum Dry-Bulb is entered in units of {J/kg}, so it does not need to be multiplied here by 1000.

### Workaround
Until this is fixed, enter Enthalpy at Maximum Dry-Bulb in kJ/kg instead of J/kg - but do that with care, because that will be incorrect after this is fixed.

So, a better workaround is to determine the equivalent humidity ratio and convert Enthalpy design days to use HumidityRatio instead. That way the file will continue to produce correct results after this is fixed.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.2.0
 - Helpdesk ticket number 15284

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached:   [7550-1ZoneUncontrolled.idf.txt](https://github.com/NREL/EnergyPlus/files/3708085/7550-1ZoneUncontrolled.idf.txt)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7550
 - When Humidity Indicating Type is "Enthalpy", the value is already in J/kg so no need to multiple it by 1000.0. Also, adjust the reporting to EIO (OutputFileInits) with didn't align with the header printed until now. Added unit test.

----
EIO change was added to OutputChange as well, but for convenience:

EIO before:
```
! <Environment:Design Day Data>, Max Dry-Bulb Temp {C}, Temp Range {dC}, Temp Range Ind Type, Hum Ind Value at Max Temp, Hum Ind Type,Pressure {Pa}, Wind Direction {deg CW from N}, Wind Speed {m/s}, Clearness, Rain, Snow
Environment:Design Day Data,33.00,6.60,DefaultMultipliers,100511,220,3.2,0.00,No,No
# Realign to header
Environment:Design Day Data,33.00,6.60,DefaultMultipliers,<MISSING>,<MISSING>,100511,220,3.2,0.00,No,No
```

EIO After:
```
! <Environment:Design Day Data>, Max Dry-Bulb Temp {C}, Temp Range {dC}, Temp Range Ind Type, Hum Ind Type, Hum Ind Value at Max Temp, Pressure {Pa}, Wind Direction {deg CW from N}, Wind Speed {m/s}, Clearness, Rain, Snow
Environment:Design Day Data,33.00,6.60,DefaultMultipliers,Enthalpy,90500.00 {J/kg},100511,220,3.2,0.00,No,No
```

Visual diff:

image

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - ~[ ] If feature, test running new feature, try creative ways to break it~
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - ~[ ] Check any new function arguments for performance impacts~
 - ~[ ] Verify IDF naming conventions and styles, memos and notes and defaults~
 - ~[ ] If new idf included, locally check the err file and other outputs~

### CODE REVIEW

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -1088,27 +1088,27 @@ namespace AirLoopHVACDOAS {
             // Summer design day
             if (DesDayInput(i).DayType == summerDesignDayTypeIndex && SummerDesignDayFlag) {
                 this->SizingCoolOATemp = DesDayInput(i).MaxDryBulb;
-                if (DesDayInput(i).HumIndType == 0) { // wet bulb temperature
+                if (DesDayInput(i).HumIndType == WeatherManager::DDHumIndType_WetBulb) { // wet bulb temperature
                     this->SizingCoolOAHumRat =
                         Psychrometrics::PsyWFnTdbTwbPb(this->SizingCoolOATemp, DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (DesDayInput(i).HumIndType == 1) { // dewpoint
+                } else if (DesDayInput(i).HumIndType == WeatherManager::DDHumIndType_DewPoint) { // dewpoint
```
Comment (jmarrec) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:1094]: Just cosmetic and more future proof: use the named `extern const int` instead of the integer value (should become an enum down the line probably, but replacements will be much easier)

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 2]
```diff
@@ -1088,27 +1088,27 @@ namespace AirLoopHVACDOAS {
...
                     this->SizingCoolOAHumRat = Psychrometrics::PsyWFnTdpPb(DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (DesDayInput(i).HumIndType == 3) {
+                } else if (DesDayInput(i).HumIndType == WeatherManager::DDHumIndType_HumRatio) {
                     this->SizingCoolOAHumRat = DesDayInput(i).HumIndValue;
-                }
+                } // else { // What about other cases?
```
Comment (jmarrec) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:1098]: This is a TODO: I noticed that it only checks 3 values out of the  8 possible `HumIndType`

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 3]
```diff
@@ -1088,27 +1088,27 @@ namespace AirLoopHVACDOAS {
...
                     this->HeatOutHumRat =
                         Psychrometrics::PsyWFnTdbTwbPb(this->HeatOutTemp, DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (DesDayInput(i).HumIndType == 1) { // dewpoint
+                } else if (DesDayInput(i).HumIndType == WeatherManager::DDHumIndType_DewPoint) { // dewpoint
                     this->HeatOutHumRat = Psychrometrics::PsyWFnTdpPb(DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (DesDayInput(i).HumIndType == 3) {
+                } else if (DesDayInput(i).HumIndType == WeatherManager::DDHumIndType_HumRatio) {
                     this->HeatOutHumRat = DesDayInput(i).HumIndValue;
-                }
+                } // else { // What about other cases?
```
Comment (jmarrec) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:1111]: This is a TODO: I noticed that it only checks 3 values out of the  8 possible `HumIndType`

File: src/EnergyPlus/WeatherManager.cc [hunk 4]
```diff
@@ -4135,7 +4135,7 @@ namespace WeatherManager {
         Real64 const ZHGlobalSolarConstant(1355.0);
         static ObjexxFCL::gio::Fmt EnvDDHdFormat(
             "('! <Environment:Design Day Data>, Max Dry-Bulb Temp {C}, ',   'Temp Range {dC}, Temp Range Ind Type, ',   "
-            "'Hum Ind Value at Max Temp, Hum Ind Type,Pressure {Pa}, ',   'Wind Direction {deg CW from N}, ',    'Wind "
+            "'Hum Ind Type, Hum Ind Value at Max Temp, Pressure {Pa}, ',   'Wind Direction {deg CW from N}, ',    'Wind "
```
Comment (jmarrec) [inline src/EnergyPlus/WeatherManager.cc]: EIO header change, to match how it's layed out later (but not reported until now)

File: src/EnergyPlus/WeatherManager.cc [hunk 5]
```diff
@@ -4324,12 +4324,14 @@ namespace WeatherManager {
...
             }
+
+            // Hum Ind Type, Hum Ind Value at Max Temp
             if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_WetBulb) {
                 StringOut = "Wetbulb," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {C},";
             } else if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_DewPoint) {
                 StringOut = "Dewpoint," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {C},";
             } else if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_Enthalpy) {
-                StringOut = "Enthalpy," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {kJ/kg},";
+                StringOut = "Enthalpy," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {J/kg},";
```
Comment (jmarrec) [inline src/EnergyPlus/WeatherManager.cc]: Adjust unit. An alternative is to do `RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue / 1000., 2) + " {kJ/kg}`

File: src/EnergyPlus/WeatherManager.cc [hunk 6]
```diff
@@ -4341,6 +4343,12 @@ namespace WeatherManager {
             } else if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_WBProfMul) {
                 StringOut = "WetBulbProfileMultiplierSchedule," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {C},";
             }
+            {
+                IOFlags flags;
+                flags.ADVANCE("No");
+                ObjexxFCL::gio::write(OutputFileInits, fmtA, flags) << StringOut;
+            }
+
```
Comment (jmarrec) [inline src/EnergyPlus/WeatherManager.cc:4351]: This wasn't output to EIO before (hence why it was missing)

File: tst/EnergyPlus/unit/WeatherManager.unit.cc [hunk 7]
```diff
@@ -678,3 +682,133 @@ TEST_F(EnergyPlusFixture, WeatherManager_NoLocation) {
...
+            if (WeatherManager::TomorrowOutRelHum(TS, Hour) < 100.) {
+                ++n_RH_not100;
+            }
+        }
+    }
+    EXPECT_TRUE(n_RH_not100 > 0) << "Expected at least one hour with RH below 100%";
+
+    SimulationManager::CloseOutputFiles();
+
+    // This actually doesn't end up in the EIO stream yet, it's written to a gio::out_stream
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WeatherManager.unit.cc:776]: Start of checking new EIO report

File: tst/EnergyPlus/unit/WeatherManager.unit.cc [hunk 8]
```diff
@@ -678,3 +682,133 @@ TEST_F(EnergyPlusFixture, WeatherManager_NoLocation) {
...
+    unsigned n_RH_not100 = 0;
+    for (int Hour = 1; Hour <= 24; ++Hour) {
+        for (int TS = 1; TS <= DataGlobals::NumOfTimeStepInHour; ++TS) {
+            EXPECT_GE(WeatherManager::TomorrowOutRelHum(TS, Hour), 0.);
+            EXPECT_LE(WeatherManager::TomorrowOutRelHum(TS, Hour), 100.);
+            if (WeatherManager::TomorrowOutRelHum(TS, Hour) < 100.) {
+                ++n_RH_not100;
+            }
+        }
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WeatherManager.unit.cc:771]: Reproduces defect file condition. By multiplying (wrongly) J/kg by 1000 before, it was giving always 100% RH.

**Comment by nrel-bot-2** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/WeatherManager.cc [hunk 9]
```diff
@@ -4324,12 +4324,14 @@ namespace WeatherManager {
...
+            // Hum Ind Type, Hum Ind Value at Max Temp
             if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_WetBulb) {
                 StringOut = "Wetbulb," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {C},";
             } else if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_DewPoint) {
                 StringOut = "Dewpoint," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {C},";
             } else if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_Enthalpy) {
-                StringOut = "Enthalpy," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {kJ/kg},";
+                StringOut = "Enthalpy," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 2) + " {J/kg},";
             } else if (DesDayInput(EnvrnNum).HumIndType == DDHumIndType_HumRatio) {
                 StringOut = "HumidityRatio," + RoundSigDigits(DesDayInput(EnvrnNum).HumIndValue, 4) + " {},";
```
Comment (mjwitte) [inline src/EnergyPlus/WeatherManager.cc]: Units for this should be kgWater/kgDryAir (per IDD)

File: src/EnergyPlus/WeatherManager.cc (hunk 5 above)
Comment (mjwitte) [reply src/EnergyPlus/WeatherManager.cc]: Units here should be J/kgDryAir to be thorough.

File: src/EnergyPlus/WeatherManager.cc (hunk 4 above)
Comment (mjwitte) [reply src/EnergyPlus/WeatherManager.cc]: Good to add this. Since the units are variable and can't be declared in the header, there should be an additional column for "Hum Ind Value Units" (or similar).  This will ensure that numbers and strings are kept separate for easier parsing of the eio.

File: src/EnergyPlus/WeatherManager.cc (hunk 5 above)
Comment (mjwitte) [reply src/EnergyPlus/WeatherManager.cc]: All of these should have a comma before the units per comments above - want to keep strings and numerics separate in this output.

**Review by mjwitte — COMMENTED** [review]
@jmarrec Nice fix. Some minor changes requested below. 
I was going to suggest that the IDD units for this field should be "J/kgDryAir" but then that will break the IDF Editor units conversions, so let's leave the IDD alone.

File: src/EnergyPlus/WeatherManager.cc (hunk 9 above)
Comment (jmarrec) [reply src/EnergyPlus/WeatherManager.cc]: Done, tested that it outputs `HumidityRatio,8.0000E-003,{kgWater/kgDryAir}`

**Comment by jmarrec** [comment]
Merged develop and resolved small conflict in markdown file.

Address @mjwitte's review comments by breaking up Value v. Units in https://github.com/NREL/EnergyPlus/pull/7577/commits/6acc5301c821cd33c4a39758c8e63c383ce791ea

**Comment by mjwitte** [comment]
@jmarrec Thanks - the changes look good. One more thing, please upate the OutputRules file to match the final changes.
CI is having issues this week, so don't be concerned about the test failures.

**Comment by jmarrec** [comment]
@mjwitte Updated Output Changes in https://github.com/NREL/EnergyPlus/pull/7577/commits/edaaf4978f0e2c25c3edd85c81703cc63733967a

Thanks for the review.

**Review by mjwitte — APPROVED** [review]
Finally got a full set of CI results on the substantive changes (before the last commit to OutputRules). Some extra diffs are creeping in because develop is moving quickly. Ready to merge this one.
