### PR TITLE
Fix #7511 which shows warning for too many controlled shades

### LINKED ISSUE #7511: EnergyPlus shading control errors - too many controlled shaded windows in zone
### Overview
The attached defect file generates these types of warnings:
```
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE

   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
```

### Workaround
The first warning is a true warning, review WindowShadingControl objects to be sure that "Zone Name" is consistent with both the "Daylighting Control Object Name" and the listed Fenestration Surfaces.

The second warning is a false warning and may be ignored.

### Details

 - Platform: Windows 8.1, Windows 10, ArchLinux
 - Version of EnergyPlus: v9.0 & v9.1

I encountered an issue that EnergyPlus **randomly** crashes on my model. I really cannot figure out where the problem comes from. The wired thing is that sometimes it ran successfully, but sometimes it didn't. This occurred both on my linux and windows machine, for both EnergyPlus v9.0 and v9.1.

I am not sure if this is related to https://github.com/NREL/EnergyPlus/issues/7223. But I believe there is something going wrong in daylighting controls. As you can see from the error message, there is several warning messages saying that there are too many controlled shaded windows for zone `Zone 1-Office` and empty map for windows for zone `Zone 3-3`.

I searched the code base and found that these messages were generated by function `MapShadeDeploymentOrderToLoopNumber`:

https://github.com/NREL/EnergyPlus/blob/65479e0be49b834870ffc79170785a64ab62634e/src/EnergyPlus/DaylightingManager.cc#L10845-L10878

I have double checked that all fenestration surfaces listed in `WindowShadingControl` belongs to the right zone. So I did not know where I should start for debugging my model.

Below is the model file. 
[test.txt](https://github.com/NREL/EnergyPlus/files/3630138/test.txt)

<details>
  <summary>Contents of error messages</summary>
<p>

```
Program Version,EnergyPlus, Version 9.1.0-08d2e308bb, YMD=2019.09.19 15:02,
   ************* Beginning Zone Sizing Calculations
   ** Warning ** Site:GroundTemperature:BuildingSurface: Some values fall outside the range of 15-25C.
   **   ~~~   ** These values may be inappropriate.  Please consult the Input Output Reference for more details.
   ** Warning ** CheckUsedConstructions: There are 3 nominally unused constructions in input.
   **   ~~~   ** Each Unused construction is shown.
   ************* Construction=ZEB_GLASS_DOOR
   ************* Construction=ZEB_DOOR
   ************* Construction=ZEB_IRTSURFACE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
   ** Warning ** Calculated design heating load for zone=MEETING_ROOM_1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=MEETING_ROOM_2 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=MEETING_ROOM_3 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=SERVER_ROOM is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 1-OFFICE is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 1-PANTRY is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 2 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 3-1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 3-3 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ************* Beginning System Sizing Calculations
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AHU 1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AHU 2 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AHU 3 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=FCU 5 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=FCU 4 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ************* Beginning Plant Sizing Calculations
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 1
   **   ~~~   ** User-Specified Design Inlet Air Temperature [C] = 33.00000
   **   ~~~   ** differs from Design Size Design Inlet Air Temperature [C] = 29.03919
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 1
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 1.08000E-003
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 8.46274E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water ZONE 1
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 1.552048E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9876
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5116
   **   ~~~   **                                    Wair,out = 8.692330E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME 1
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 1.17000
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.39515
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 2
   **   ~~~   ** User-Specified Design Inlet Air Temperature [C] = 33.00000
   **   ~~~   ** differs from Design Size Design Inlet Air Temperature [C] = 29.08417
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 2
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 1.42000E-003
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 9.78993E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water ZONE 2
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 1.561284E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9877
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5116
   **   ~~~   **                                    Wair,out = 8.692362E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME 2
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 1.61000
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.45425
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 3
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 1.80000E-003
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 9.21295E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water ZONE 3
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 1.827733E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9916
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5132
   **   ~~~   **                                    Wair,out = 8.693280E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME 3
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 2.08000
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.36186
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water MEETING_ROOM_1
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 2.90000E-004
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 1.48857E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water MEETING_ROOM_1
   **   ~~~   ** User-Specified Design Air Flow Rate [m3/s] = 1.36000E-003
   **   ~~~   ** differs from Design Size Design Air Flow Rate [m3/s] = 5.08446E-002
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water MEETING_ROOM_1
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 2.087994E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9954
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5148
   **   ~~~   **                                    Wair,out = 8.694169E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME OF FCU 5
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 1.36000E-003
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 5.08446E-002
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeDXCoil: Potential issue with equipment sizing for Coil:Cooling:DX:SingleSpeed DX COIL FOR SERVER_ROOM
   **   ~~~   ** User-Specified Gross Rated Total Cooling Capacity [W] = 5000.00000
   **   ~~~   ** differs from Design Size Gross Rated Total Cooling Capacity [W] = 1369.74521
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** Sizing: Coil:Cooling:DX:SingleSpeed "DX COIL FOR SERVER_ROOM": Rated air volume flow rate per watt of rated total cooling capacity is out of range.
   **   ~~~   ** Min Rated Vol Flow Per Watt=[4.027E-005], Rated Vol Flow Per Watt=[5.053E-006], Max Rated Vol Flow Per Watt=[6.041E-005]. See Input Output Reference Manual for valid range.
   ** Warning ** For object = Coil:Cooling:DX:SingleSpeed, name = "DX COIL FOR SERVER_ROOM"
   **   ~~~   ** Calculated outlet air relative humidity greater than 1. The combination of
   **   ~~~   ** rated air volume flow rate, total cooling capacity and sensible heat ratio yields coil exiting
   **   ~~~   ** air conditions above the saturation curve. Possible fixes are to reduce the rated total cooling
   **   ~~~   ** capacity, increase the rated air volume flow rate, or reduce the rated sensible heat ratio for this coil.
   **   ~~~   ** If autosizing, it is recommended that all three of these values be autosized.
   **   ~~~   ** ...Inputs used for calculating cooling coil bypass factor.
   **   ~~~   ** ...Inlet Air Temperature     = 26.67 C
   **   ~~~   ** ...Outlet Air Temperature    = -115.05 C
   **   ~~~   ** ...Inlet Air Humidity Ratio  = 1.125000E-002 kgWater/kgDryAir
   **   ~~~   ** ...Outlet Air Humidity Ratio = 1.000000E-005 kgWater/kgDryAir
   **   ~~~   ** ...Total Cooling Capacity used in calculation = 5000.00 W
   **   ~~~   ** ...Air Mass Flow Rate used in calculation     = 2.922675E-002 kg/s
   **   ~~~   ** ...Air Volume Flow Rate used in calculation   = 2.526892E-002 m3/s
   **   ~~~   ** ...Air Volume Flow Rate per Watt of Rated Cooling Capacity is also out of bounds at = 5.0537846E-006 m3/s/W
   **   ~~~   **  During Warmup, Environment=DESIGN_DAY_APR, at Simulation time=04/21 00:00 - 00:15
   **   ~~~   ** CalcCBF: SHR adjusted to achieve valid outlet air properties and the simulation continues.
   **   ~~~   ** CalcCBF: initial SHR = 0.49908
   **   ~~~   ** CalcCBF: adjusted SHR = 0.83243
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume DX FAN
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 8.10000E-004
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 2.52689E-002
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water SERVER_ROOM
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 2.152708E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9963
   **   ~~~   **                                  
```

</p>
</details>

Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
 - Fixes #7511

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@amirroth refactoring of all the Fortran variable names in the daylighting routines is really needed. It really makes the code unnecessarily difficult to follow. I added a suggestion to #9152

**Comment by JasonGlazer** [comment]
The only diff is SolarShadingTestGPU is on Linux so I think this is ready for review. 

Almost all of the source code changes shown are just added if blocks to protect a "loop" of zero.

File: src/EnergyPlus/DaylightingManager.cc [hunk 1]
```diff
@@ -10394,10 +10414,13 @@ void MapShadeDeploymentOrderToLoopNumber(EnergyPlusData &state, int const enclNu
                 for (auto listOfExtWin : thisDaylightCtrl.ShadeDeployOrderExtWins) {
                     for (auto IWinShdOrd : listOfExtWin) {
                         ++count;
-                        if (count > thisEnclDaylight.NumOfDayltgExtWins)
+                        if (count > thisEnclDaylight.NumOfDayltgExtWins) {
                             ShowWarningError(state,
                                              "MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in enclosure " +
                                                  thisSolEnclosureName);
+                            ShowContinueError(state, "Check the list of surfaces in WindowShadingControl: " + thisDaylightCtrl.Name);
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc]: This should be the window shading control name, not `thisDaylightCtrl.Name` Is that known here?

This group of warnings repeats for every surface that's beyond the limit. Not a huge deal, but it would be easier to follow if this just wrote the main warning first, then used the continue error below to list all of the excess surfaces. These first warnings could be moved up to a new if block that checks `if(listOfExtWin.size > thisEnclDaylight.NumOfDayltgExtWins`.

File: src/EnergyPlus/DaylightingManager.cc [hunk 2]
```diff
@@ -10413,13 +10436,6 @@ void MapShadeDeploymentOrderToLoopNumber(EnergyPlusData &state, int const enclNu
                                              "MapShadeDeploymentOrderToLoopNumber: found unassociated window for enclosure " + thisSolEnclosureName);
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc]: It would be helpful to include the surface name in this warning. This check seems inefficient. I know it only happens during inits, but this is looping through all windows in the enclosure for every window that has a shading control. But I see how it's a crosscheck that the shaded surface is actually an exterior window for this enclosure. So, ok. But adding the surface name here would be very useful.

File: src/EnergyPlus/DaylightingManager.cc [hunk 3]
```diff
@@ -6706,20 +6706,21 @@ void DayltgInteriorIllum(EnergyPlusData &state,
...
-                if (state.dataSurface->Surface(IWin).HasShadeControl) {
-                    if (state.dataSurface->SurfWinShadingFlag(IWin) == WinShadingType::GlassConditionallyLightened &&
-                        state.dataSurface->WindowShadingControl(ICtrl).ShadingControlType == WindowShadingControlType::MeetDaylIlumSetp &&
-                        !previously_shaded(loop)) {
-                        DILLSW(igroup) += thisDaylightControl.IllumFromWinAtRefPt(loop, IS, 1);
-                        previously_shaded(loop) = true;
-                    } else {
-                        if (!previously_shaded(loop)) {
-                            DILLUN(igroup) += thisDaylightControl.IllumFromWinAtRefPt(loop, IS, 1);
+                if (loop > 0) {
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc]: Seems like `loop` should be declared locally every time it's set to avoid misuse outside the main loops or carryover from one to the next?

**Review by mjwitte — COMMENTED** [review]
Used my new power to hide indentation whitespace diffs from the new if loop > 0 checks. (thanks @mitchute !!) 

Tested this with the user's file as-it-was and with the corrected zone name. 

The `found empty map` warnings are gone now. 

And the `too many controlled shaded windows` provide more details now.

And the `found unassociated window` warnings are unchanged.

Should any of these warning conditions be a severe/fatal instead?

**Review by mjwitte — APPROVED** [review]
@JasonGlazer Much nicer. Thanks. Merging soon.

**Comment by mjwitte** [comment]
Not waiting for any more CI results, previous round was clean.
