### PR TITLE
#7902 - Fix inappopriate severe error: Heater Control Type for WaterHeater:Stratified must be CYCLE

### LINKED ISSUE #7892: Python File in EnergyPlus src Directory
Issue overview
--------------
There's a Python file mixed in with the EnergyPlus source, potentially a mistaken commit:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Untitled.ipynb

If it is intentional, then it should probably be elsewhere.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #7902: Error: Heater Control Type for WaterHeater:Stratified must be CYCLE?
Issue overview
--------------
I've got this error:

   ** Severe  ** WaterHeater:HeatPump:WrappedCondenser = PLANTHEATPUMPWATERHEATER:
   **   ~~~   ** Heater Control Type for WaterHeater:Stratified = WATER HEATER TANK must be CYCLE.

on a fairly simple model, where I have I think completely copied the heat pump water heater components from the WaterHeaterHeatPumpWrappedCondensor example file (which has both a wrapped condenser heater and a stratified water heater tank, just like my model). This is why this error is confusing me, because it says the tank must have a cycle control, but that is only available in a WaterHeater:Mixed, not a WaterHeater:Stratefied - and somehow this combination is working fine int he example file. I wasn't able to find anything explaining the requirement in the documentation, so I'm at a bit of a loss. Any idea what might trigger this requirement in the heat pump settings or somewhere else? 

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - version 9.1 (used in current version of CBECC-Com - haven't tested in newer E+ versions)
 - https://unmethours.com/question/43617/error-heater-control-type-for-waterheaterstratified-must-be-cycle/

[HotSml-03-ECM207_idf.txt](https://github.com/NREL/EnergyPlus/files/4429346/HotSml-03-ECM207_idf.txt)

### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7902/HotSml-03-ECM207.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #7902
 - The main thing is that two different things are stored in the same int `WaterThermalTanksData::ControlType`: the `ControlTypeEnum` (Cycle / Modulate, for WaterHeater:Mixed) and the `PriorityEnum` (MasterSlave / Simultaneous, for WaterHeater:Stratified)

(Also Fix #7892)

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterThermalTanks.hh [hunk 1]
```diff
@@ -93,14 +93,16 @@ namespace WaterThermalTanks {
...
 
     // order of ControlTypeEnum and PriorityEnum must be enforced
+    // WaterThermalTankData uses the same int ControlType to assign either ControlTypeEnum (WaterHeater:Mixed) or PriorityEnum
+    // (WaterHeater:Stratified), so in order to avoid problems, start the int value here as 2 so they don't risk collapsing.
     enum PriorityEnum
     {
-        MasterSlave, // water heater only, master-slave priority control of heater elements
+        MasterSlave = 2, // water heater only, master-slave priority control of heater elements
         Simultaneous // water heater only, simultaneous control of heater elements
     };
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.hh:108]: Avoid future collapses. (We should perhaps make a habit of using enum classes instead...)

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 2]
```diff
@@ -4238,8 +4238,8 @@ namespace WaterThermalTanks {
                         BranchNodeConnections::SetUpCompSets(
                             HPWH.Type, HPWH.Name, HPWH.TankType, HPWH.TankName, HPWH.OutletNodeName1, HPWH.InletNodeName1, "HPWH To Tank");
 
-                        // do not allow modulating control for HPWH's (i.e. modulating control usually used for tankless WH's)
-                        if (Tank.ControlType == ControlTypeEnum::Modulate) {
+                        // If WaterHeaterMixed: do not allow modulating control for HPWH's (i.e. modulating control usually used for tankless WH's)
+                        if ((Tank.TypeNum == DataPlant::TypeOf_WtrHeaterMixed) && (Tank.ControlType == ControlTypeEnum::Modulate)) {
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.cc:4243]: Be specific in the check here (this would have fixed the specific issue by itself too)

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 3]
```diff
@@ -4485,3 +4485,523 @@ TEST_F(EnergyPlusFixture, CrashCalcStandardRatings_HPWH_and_Standalone)
         Tank.initialize(FirstHVACIteration);
     }
 }
+
+// Test for #7902: If the Stratified Tank Priority Mode is Simultaneous, it hits a check meant to test
+// for ControlTypeEnum::Modulate (for WH:Mixed) because these two enums are the same int values and stored in
+// the same int WaterThermalTankData::ControlType
+TEST_F(EnergyPlusFixture, HPWH_Wrapped_Stratified_Simultaneous)
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:4493]: One test for HPWH:WrappedCondenser

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 4]
```diff
@@ -4485,3 +4485,523 @@ TEST_F(EnergyPlusFixture, CrashCalcStandardRatings_HPWH_and_Standalone)
...
+        //"   **   ~~~   ** Heater Control Type for WaterHeater:Stratified = HPWHWRAPPED STRATIFIED TANK must be CYCLE.",
+    //});
+
+    EXPECT_TRUE(compare_err_stream("", true));
+}
+
+// Test for #7902: If the HPWH is Pumped, and it has a Stratified Tank which  Priority Mode is Simultaneous,
+// it hits a check meant to test for ControlTypeEnum::Modulate (for WH:Mixed)
+// because these two enums are the same int values and stored in the same int WaterThermalTankData::ControlType
+TEST_F(EnergyPlusFixture, HPWH_Pumped_Stratified_Simultaneous)
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:4739]: One test for HPWH:PumpedCondenser

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/WaterThermalTanks.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterThermalTanks.cc:4243]: Looks fine to me.

File: src/EnergyPlus/WaterThermalTanks.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterThermalTanks.hh:108]: Yes, we should definitely do enum classes.  But I appreciate that that change is likely out of scope for this little defect fix.

**Review by Myoldmopar — APPROVED** [review]
Code changes make sense, great unit tests, and thanks for cleaning out that Python notebook while you were in there.

**Comment by Myoldmopar** [comment]
Pulled in develop locally, resolved one unit test build problem.  Ran the defect file with develop and found the severe error tucked in there with the other warnings/errors.  Ran the defect file with this branch and that specific error is gone.  As expected the file still fails for other reasons.  Also ran the unit test suite with this branch and it passes fine.  I'm pushing it up just to make sure CI is happy with my merge but I anticipate this will merge today.  Thanks @jmarrec.

**Comment by Myoldmopar** [comment]
All happy here, Windows CI failures are the known MTD regulars.  Merging.
