### PR TITLE
Fix Coil Sizing Report for Coil:Heating:Gas:MultiStage and Coil:Heating:Electric:MultiStage

### LINKED ISSUE #11062: Incorrect Coil Sizing Report for Coil:Heating:Gas:MultiStage
### Issue overview

For this type of coil, data from the `ReportCoilSelection` object was ignored because the coil "ModelType" was set as "GasMultistage" rather than "Gas:MultiStage" and "Coil:Heating:GasMultistage" is not a valid coil type. Example from the testfile `MultiSpeedACFurnace.idf`. 

Image

Note the missing fields for HVAC Type, HVAC Name, and Total and Sensible Capacity for HEAT PUMP HEATING COIL 1. Here are the fields when "ModelType" is changed to "Gas:MultiStage".

Image

A similar problem occurs for th "Coil:Heating:Electric:MultiStage" in several other test files.

### Operating System (Multiple choices)

Any

### Operating System Version

Any

### Version of EnergyPlus

25.1.0

### Unmethours link or helpdesk ticket number

N/A

### Defect file

This occurs the testfile `MultiStageACFurnace.idf`.

### PR DESCRIPTION
**Pull request by amirroth**
Pull request overview
---------------------

### Description of the purpose of this PR

- Fixes #11062. The fix and its effects are described in the issue itself. 
- There are no output changes other than the Coil Sizing Summary, Details, and Connections reports for MultiStage coils. 
- There are no result diffs.

### CODE REVIEW

File: src/EnergyPlus/HeatingCoils.cc [hunk 1]
```diff
@@ -475,7 +475,7 @@ namespace HeatingCoils {
             }
 
             heatingCoil.HeatingCoilType = "Heating";
-            heatingCoil.HeatingCoilModel = "ElectricMultiStage";
+            heatingCoil.HeatingCoilModel = "Electric:MultiStage";
```
Comment (amirroth) [inline src/EnergyPlus/HeatingCoils.cc:478]: This results in a `CompType` of `Coil:Heating:ElectricMultistage` in the sizing routines which leads to information in the CoilSelectionReport object to be ignored because that is not a valid coil type name.

**Review by rraustad — APPROVED** [review]
Good catch.

**Comment by rraustad** [comment]
Diffs are attributed to correction of coil type:

    - Component Sizing Information, Coil:Heating:GasMultiStage, HEAT PUMP HEATING COIL 1, User-Specified Stage 1 Nominal Capacity [W], 45000.00000
    + Component Sizing Information, Coil:Heating:Gas:MultiStage, HEAT PUMP HEATING COIL 1, User-Specified Stage 1 Nominal Capacity [W], 45000.00000

Need to check what the result is from this branch for:

image

**Comment by rraustad** [comment]
There are still issues with the reporting of sizing data but the coil type has been corrected. Total and Sensible capacity should both show 45000 W and the air flow and conditions used during sizing should be reported correctly, this is a separate issue.

    Component Sizing Information, Coil:Heating:Gas:MultiStage, HEAT PUMP HEATING COIL 1, User-Specified Stage 1 Nominal Capacity [W], 45000.00000

image

**Comment by amirroth** [comment]
I do not know how to address this other issue. Someone else will have to do that.

**Comment by rraustad** [comment]
@Myoldmopar this branch is ready to merge.

**Comment by Myoldmopar** [comment]
Looks like Decent decided it wanted one more pass here.  I'll give it a few more minutes, then this can merge.

**Comment by Myoldmopar** [comment]
Alright, good to go in.  Thanks @amirroth  and @rraustad
