### PR TITLE
CppCheck HVACUnitaryBypassVAV

### LINKED ISSUE #10020: AirloopHVAC:UnitaryHeatCool:VAVChangeoverBypass not working with Coil:Cooling:DX inside HX assisted coil wrapper
Issue overview
--------------
This parent object will likely not work when CoilSystem:Cooling:DX:HeatExchangerAssisted is used and the coil in this heat exchanger assisted object uses Coil:Cooling:DX.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #10020 and CppCheck issues
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 1]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
+                    fanOutletNode = state.dataHVACFan->fanObjs[thisCBVAV.FanIndex]->outletNodeNum;
+                    thisCBVAV.FanVolFlow = state.dataHVACFan->fanObjs[thisCBVAV.FanIndex]->designAirVolFlowRate;
                 } else {
-                    Fans::GetFanType(
-                        state, CBVAV(CBVAVNum).FanName, CBVAV(CBVAVNum).FanType_Num, FanErrFlag, CurrentModuleObject, CBVAV(CBVAVNum).Name);
-                    CBVAV(CBVAVNum).FanInletNodeNum = Fans::GetFanInletNode(state, CBVAV(CBVAVNum).FanType, CBVAV(CBVAVNum).FanName, FanErrFlag);
-                    fanOutletNode = Fans::GetFanOutletNode(state, CBVAV(CBVAVNum).FanType, CBVAV(CBVAVNum).FanName, ErrorsFound);
-                    Fans::GetFanIndex(state, CBVAV(CBVAVNum).FanName, CBVAV(CBVAVNum).FanIndex, FanErrFlag);
-                    Fans::GetFanVolFlow(state, CBVAV(CBVAVNum).FanIndex, CBVAV(CBVAVNum).FanVolFlow);
+                    Fans::GetFanType(state, thisCBVAV.FanName, thisCBVAV.FanType_Num, FanErrFlag, CurrentModuleObject, thisCBVAV.Name);
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: This API seems backwards to me. The first thing you should do is get the `FanIndex`, once you have that you can get everything else using `FanIndex`. Right now, only `getFanVolumeFlow` is doing that.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 2]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
+                    thisCBVAV.FanInletNodeNum = Fans::GetFanInletNode(state, thisCBVAV.FanType, thisCBVAV.FanName, FanErrFlag);
+                    fanOutletNode = Fans::GetFanOutletNode(state, thisCBVAV.FanType, thisCBVAV.FanName, ErrorsFound);
+                    Fans::GetFanIndex(state, thisCBVAV.FanName, thisCBVAV.FanIndex, FanErrFlag);
+                    Fans::GetFanVolFlow(state, thisCBVAV.FanIndex, thisCBVAV.FanVolFlow);
                 }
             }
 
             if (UtilityRoutines::SameString(Alphas(12), "BlowThrough")) {
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: This should be an enumeration with `getEnumValue`.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 3]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
+                thisCBVAV.MaxHeatAirVolFlow != DataSizing::AutoSize) {
                 ShowWarningError(state, format("{}: {} cannot be greater than {}", CurrentModuleObject, cNumericFields(5), cNumericFields(2)));
                 ShowContinueError(state, format(" {} is reset to the fan flow rate and the simulation continues.", cNumericFields(5)));
-                ShowContinueError(state, format("Occurs in {} = {}", CurrentModuleObject, CBVAV(CBVAVNum).Name));
-                CBVAV(CBVAVNum).HeatOutAirVolFlow = CBVAV(CBVAVNum).FanVolFlow;
+                ShowContinueError(state, format("Occurs in {} = {}", CurrentModuleObject, thisCBVAV.Name));
+                thisCBVAV.HeatOutAirVolFlow = thisCBVAV.FanVolFlow;
             }
 
             if (UtilityRoutines::SameString(Alphas(14), "Coil:Cooling:DX:SingleSpeed") ||
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: This should also probably be an enumeration with `getEnumerationValue` because you are uppercasing stuff all over the place here, as well as doing the same string comparisons multiple times.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 4]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
+                thisCBVAV.DXCoolCoilType = Alphas(14);
+                thisCBVAV.DXCoolCoilName = Alphas(15);
 
                 if (UtilityRoutines::SameString(Alphas(14), "Coil:Cooling:DX:SingleSpeed")) {
-                    CBVAV(CBVAVNum).DXCoolCoilType_Num = DataHVACGlobals::CoilDX_CoolingSingleSpeed;
-                    CBVAV(CBVAVNum).DXCoilInletNode =
-                        DXCoils::GetCoilInletNode(state, CBVAV(CBVAVNum).DXCoolCoilType, CBVAV(CBVAVNum).DXCoolCoilName, DXErrorsFound);
-                    CBVAV(CBVAVNum).DXCoilOutletNode =
-                        DXCoils::GetCoilOutletNode(state, CBVAV(CBVAVNum).DXCoolCoilType, CBVAV(CBVAVNum).DXCoolCoilName, DXErrorsFound);
+                    thisCBVAV.DXCoolCoilType_Num = DataHVACGlobals::CoilDX_CoolingSingleSpeed;
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: Make this `Type` and get rid of the string field.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 5]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
+                thisCBVAV.MaxNoCoolHeatAirVolFlow != DataSizing::AutoSize && thisCBVAV.MaxNoCoolHeatAirVolFlow != 0.0) {
                 ShowWarningError(state, format("{}: {} cannot be greater than {}", CurrentModuleObject, cNumericFields(6), cNumericFields(3)));
                 ShowContinueError(state, format(" {} is reset to the fan flow rate and the simulation continues.", cNumericFields(6)));
-                ShowContinueError(state, format("Occurs in {} = {}", CurrentModuleObject, CBVAV(CBVAVNum).Name));
-                CBVAV(CBVAVNum).NoCoolHeatOutAirVolFlow = CBVAV(CBVAVNum).FanVolFlow;
+                ShowContinueError(state, format("Occurs in {} = {}", CurrentModuleObject, thisCBVAV.Name));
+                thisCBVAV.NoCoolHeatOutAirVolFlow = thisCBVAV.FanVolFlow;
             }
 
             if (UtilityRoutines::SameString(Alphas(16), "Coil:Heating:DX:SingleSpeed") ||
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: Same comment here.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 6]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
-                        VariableSpeedCoils::GetVSCoilMinOATCompressor(state, CBVAV(CBVAVNum).DXHeatCoilIndexNum, DXCoilErrFlag);
-                    CBVAV(CBVAVNum).HeatingCoilInletNode = VariableSpeedCoils::GetCoilInletNodeVariableSpeed(
-                        state, CBVAV(CBVAVNum).HeatCoilType, CBVAV(CBVAVNum).HeatCoilName, DXCoilErrFlag);
-                    CBVAV(CBVAVNum).HeatingCoilOutletNode = VariableSpeedCoils::GetCoilOutletNodeVariableSpeed(
-                        state, CBVAV(CBVAVNum).HeatCoilType, CBVAV(CBVAVNum).HeatCoilName, DXCoilErrFlag);
-                    if (DXCoilErrFlag) ShowContinueError(state, format("...occurs in {} \"{}\"", CBVAV(CBVAVNum).UnitType, CBVAV(CBVAVNum).Name));
+                    thisCBVAV.DXHeatCoilIndexNum =
+                        VariableSpeedCoils::GetCoilIndexVariableSpeed(state, thisCBVAV.HeatCoilType, thisCBVAV.HeatCoilName, DXCoilErrFlag);
+                    thisCBVAV.MinOATCompressor = VariableSpeedCoils::GetVSCoilMinOATCompressor(state, thisCBVAV.DXHeatCoilIndexNum, DXCoilErrFlag);
+                    thisCBVAV.HeatingCoilInletNode =
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: Same comment here. You already have the heating coil index, there is no need to find it again using name and type.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 7]
```diff
@@ -564,647 +556,613 @@ namespace HVACUnitaryBypassVAV {
...
             //   Initialize last mode of compressor operation
-            CBVAV(CBVAVNum).LastMode = HeatingMode;
+            thisCBVAV.LastMode = HeatingMode;
 
-            if (CBVAV(CBVAVNum).FanType_Num != DataHVACGlobals::FanType_SimpleOnOff &&
-                CBVAV(CBVAVNum).FanType_Num != DataHVACGlobals::FanType_SimpleConstVolume &&
-                CBVAV(CBVAVNum).FanType_Num != DataHVACGlobals::FanType_SystemModelObject) {
-                ShowSevereError(state, format("{} illegal {} in fan object = {}", CurrentModuleObject, cAlphaFields(10), CBVAV(CBVAVNum).FanName));
-                ShowContinueError(state, format("Occurs in {} = {}", CurrentModuleObject, CBVAV(CBVAVNum).Name));
+            if (thisCBVAV.FanType_Num != DataHVACGlobals::FanType_SimpleOnOff &&
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: `FanType`

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 8]
```diff
@@ -1437,15 +1392,14 @@ namespace HVACUnitaryBypassVAV {
                    bool const FirstHVACIteration, // TRUE if first HVAC iteration
                    int const AirLoopNum,          // air loop index
                    Real64 &OnOffAirFlowRatio,     // Ratio of compressor ON airflow to average airflow over timestep
-                   bool &HXUnitOn                 // flag to enable heat exchanger
+                   bool const HXUnitOn            // flag to enable heat exchanger
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc:1336]: 👍

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 9]
```diff
@@ -1493,71 +1445,54 @@ namespace HVACUnitaryBypassVAV {
         }
 
         if (state.dataHVACUnitaryBypassVAV->MyPlantScanFlag(CBVAVNum) && allocated(state.dataPlnt->PlantLoop)) {
-            if ((CBVAV(CBVAVNum).HeatCoilType_Num == DataHVACGlobals::Coil_HeatingWater) ||
-                (CBVAV(CBVAVNum).HeatCoilType_Num == DataHVACGlobals::Coil_HeatingSteam)) {
-                if (CBVAV(CBVAVNum).HeatCoilType_Num == DataHVACGlobals::Coil_HeatingWater) {
+            if ((cBVAV.HeatCoilType_Num == DataHVACGlobals::Coil_HeatingWater) || (cBVAV.HeatCoilType_Num == DataHVACGlobals::Coil_HeatingSteam)) {
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: `HeatCoilType`

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 10]
```diff
@@ -2444,223 +2329,221 @@ namespace HVACUnitaryBypassVAV {
...
-                                      (Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(CBVAV(CBVAVNum).DXCoilOutletNode).Temp,
-                                                                  state.dataLoopNodes->Node(CBVAV(CBVAVNum).DXCoilOutletNode).HumRat) -
-                                       Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(CBVAV(CBVAVNum).DXCoilInletNode).Temp,
-                                                                  state.dataLoopNodes->Node(CBVAV(CBVAVNum).DXCoilOutletNode).HumRat));
+                    Real64 NoOutput = state.dataLoopNodes->Node(cBVAV.DXCoilInletNode).MassFlowRate *
+                                      (Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(cBVAV.DXCoilOutletNode).Temp,
+                                                                  state.dataLoopNodes->Node(cBVAV.DXCoilOutletNode).HumRat) -
+                                       Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(cBVAV.DXCoilInletNode).Temp,
+                                                                  state.dataLoopNodes->Node(cBVAV.DXCoilOutletNode).HumRat));
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc:2355]: Should this be Inlet node? Maybe not, I'm seeing this a bunch below as well.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 11]
```diff
@@ -2771,67 +2654,66 @@ namespace HVACUnitaryBypassVAV {
...
+                                                       cBVAV.Name));
                                             ShowContinueError(state,
                                                               format("Estimated low speed cycling ratio = {:.3R}", TempSpeedReqst / TempSpeedOut));
                                             ShowContinueErrorTimeStamp(state,
                                                                        "The estimated low speed cycling ratio will be used and the simulation "
                                                                        "continues. Occurrence info:");
                                         }
                                         ShowRecurringWarningErrorAtEnd(state,
-                                                                       CBVAV(CBVAVNum).DXCoolCoilType + " \"" + CBVAV(CBVAVNum).DXCoolCoilName +
+                                                                       cBVAV.DXCoolCoilType + " \"" + cBVAV.DXCoolCoilName +
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: `format`

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 12]
```diff
@@ -3114,147 +2990,146 @@ namespace HVACUnitaryBypassVAV {
...
                                                 0.0,
                                                 0,
-                                                CBVAV(CBVAVNum).CoolCoilCompIndex,
+                                                cBVAV.CoolCoilCompIndex,
                                                 DataHVACGlobals::ContFanCycCoil);
-                    state.dataHVACUnitaryBypassVAV->SaveCompressorPLR = state.dataDXCoils->DXCoilPartLoadRatio(CBVAV(CBVAVNum).DXCoolCoilIndexNum);
-                } else if (CBVAV(CBVAVNum).DXCoolCoilType_Num == DataHVACGlobals::Coil_CoolingAirToAirVariableSpeed) {
+                    state.dataHVACUnitaryBypassVAV->SaveCompressorPLR = state.dataDXCoils->DXCoilPartLoadRatio(cBVAV.DXCoolCoilIndexNum);
+                } else if (cBVAV.DXCoolCoilType_Num == DataHVACGlobals::Coil_CoolingAirToAirVariableSpeed) {
                     Real64 QZnReq(0.0);                // Zone load (W), input to variable-speed DX coil
```
Comment (amirroth) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc]: Look mom, I'm calling the Real64 constructor!

**Comment by rraustad** [comment]
@Myoldmopar these diffs are far too big to let slip through. No diffs is the goal so this branch is on hold until the problem is found.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/HVACUnitaryBypassVAV.cc]: Done

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/HVACUnitaryBypassVAV.cc]: Needs review after I push the next commit

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc (hunk 7 above)
Comment (rraustad) [reply src/EnergyPlus/HVACUnitaryBypassVAV.cc]: std::string FanType;                     // Type of fan
        int FanType_Num = 0;                     // Fan type number (see DataHVACGlobals)

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc (hunk 12 above)
Comment (rraustad) [reply src/EnergyPlus/HVACUnitaryBypassVAV.cc]: [[90297ce](https://github.com/NREL/EnergyPlus/pull/10018/commits/90297ce757aad7cd7d65963604c1b71eff63b914)](https://github.com/NREL/EnergyPlus/pull/10018/commits/90297ce757aad7cd7d65963604c1b71eff63b914)

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc (hunk 9 above)
Comment (rraustad) [reply src/EnergyPlus/HVACUnitaryBypassVAV.cc]: These may take a little time to unwind. No need for the string when an enum holds the same information.

        std::string HeatCoilType;                        // Type of heating coil
        int HeatCoilType_Num = 0;                        // Numeric equivalent for DX heating coil type

**Comment by rraustad** [comment]
It's the save variable lastDayOfSim that causes these diffs from [this commit](https://github.com/NREL/EnergyPlus/pull/10018/commits/5cbd8a6e66201fa2b01eee55341bcd026da4ea4b). I reverted that change locally and now have no diffs.

File: src/EnergyPlus/HVACUnitaryBypassVAV.cc [hunk 13]
```diff
@@ -356,20 +351,16 @@ namespace HVACUnitaryBypassVAV {
...
 
-        auto &CBVAV(state.dataHVACUnitaryBypassVAV->CBVAV);
-
         // Update Num in state and make local convenience copy
         int NumCBVAV = state.dataHVACUnitaryBypassVAV->NumCBVAV =
             state.dataInputProcessing->inputProcessor->getNumObjectsFound(state, CurrentModuleObject);
 
         // allocate the data structures
-        CBVAV.allocate(NumCBVAV);
+        state.dataHVACUnitaryBypassVAV->CBVAV.resize(NumCBVAV);
```
Comment (rraustad) [inline src/EnergyPlus/HVACUnitaryBypassVAV.cc:358]: I was getting a failure in debug and had to change this to resize. This happened in the middle of the Type refactors.

**Comment by Myoldmopar** [comment]
OK, going to try to chip away at the PR list today, and these CppCheck ones are the easiest wins.  This one quietly had a compiler warning about an unused variable, so I cleaned that up, pulled develop in and ran tests.  Unit and regressions all came back totally clean, no more regressions, so this should be good to go in.  Thanks @rraustad
