### PR TITLE
9202 9222 reset delete state python

### LINKED ISSUE #9202: reset_state does not work
Issue overview
--------------
I am using EnergyPlus Python API. When I try to reset the state using api.state_manager.reset_state(state), I receive OSError: exception: access violation reading 0x0000000000000010 error. 

### Details
Some additional details for this issue (if relevant):
Windows 10
EnergyPlus 9.6.0
Python 3.9.9 64-bit

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9202
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9222: delete_state() causing crashes in Linux
Issue overview
--------------
A recently reported issue is about reset_state() fail to run properly in v9.6 (#9202). Following the work-around suggestions in issue the discussion (https://github.com/NREL/EnergyPlus/issues/9202#issuecomment-985785648) and using the new_state() and delete_state() combination, a user recently reported that the delete_state() would cause crash in a Linux version/system. The problem did not show up in Windows systems. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Linux
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6 only, EnergyPlus-9.6.0-f420c06a69-Linux-Ubuntu18.04-x86_64.sh
 - Related helpdesk tickets: 16098; 16069

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files added (list location of defect files [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9222))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9202 
 - Fixes #9222

Avoid a segfault when calling reset_state / delete_state **from python**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/PluginManager.hh [hunk 1]
```diff
@@ -243,6 +245,9 @@ struct PluginManagerData : BaseGlobalStruct
     bool apiErrorFlag = false;
     std::vector<std::string> const objectsToFind = {
         "PythonPlugin:OutputVariable", "PythonPlugin:SearchPaths", "PythonPlugin:Instance", "PythonPlugin:Variables", "PythonPlugin:TrendVariable"};
+
+    bool eplusRunningViaPythonAPI = false;
```
Comment (jmarrec) [inline src/EnergyPlus/PluginManager.hh:249]: This is on PluginManagerData, only so I can forward it to to PluginManager when it is finally instantiated.

When `stateNewPython` is called, the `std::unique_ptr<PluginManagement::PluginManager> pluginManager` isn't initialized yet, that's done later by the SimulationManager.

File: src/EnergyPlus/PluginManager.hh [hunk 2]
```diff
@@ -209,6 +209,8 @@ namespace PluginManagement {
         static int getLocationOfUserDefinedPlugin(EnergyPlusData &state, std::string const &_programName);
         static void runSingleUserDefinedPlugin(EnergyPlusData &state, int index);
         static bool anyUnexpectedPluginObjects(EnergyPlusData &state);
+
+        bool eplusRunningViaPythonAPI = false;
```
Comment (jmarrec) [inline src/EnergyPlus/PluginManager.hh:213]: This is on the PluginManager class

File: src/EnergyPlus/PluginManager.cc [hunk 3]
```diff
@@ -648,7 +648,9 @@ PluginManager::PluginManager(EnergyPlusData &state)
 PluginManager::~PluginManager()
 {
 #if LINK_WITH_PYTHON
-    Py_FinalizeEx();
+    if (!this->eplusRunningViaPythonAPI) {
+        Py_FinalizeEx();
+    }
```
Comment (jmarrec) [inline src/EnergyPlus/PluginManager.cc]: This is really only so we do call `Py_FinalizeEx` in the PluginManager destructors when not running from a **python** api: it's to be safe (when running from C API or not from api at all), but I think we would get away with not doing it at all...

File: src/EnergyPlus/PluginManager.cc [hunk 4]
```diff
@@ -402,7 +402,7 @@ void PluginManager::setupOutputVariables([[maybe_unused]] EnergyPlusData &state)
 #endif
 }
 
-PluginManager::PluginManager(EnergyPlusData &state)
+PluginManager::PluginManager(EnergyPlusData &state) : eplusRunningViaPythonAPI(state.dataPluginManager->eplusRunningViaPythonAPI)
```
Comment (jmarrec) [inline src/EnergyPlus/PluginManager.cc:405]: Ctor initializes the boolean from the PluginManagerData, so we can access it in the Dtor

File: src/EnergyPlus/api/state.cc [hunk 5]
```diff
@@ -59,6 +59,13 @@ EnergyPlusState stateNew()
     return reinterpret_cast<EnergyPlusState>(state);
 }
 
+EnergyPlusState stateNewPython()
+{
+    auto *state = new EnergyPlus::EnergyPlusData;
+    state->dataPluginManager->eplusRunningViaPythonAPI = true;
+    return reinterpret_cast<EnergyPlusState>(state);
+}
+
```
Comment (jmarrec) [inline src/EnergyPlus/api/state.cc:68]: When running from Python, set the boolean to true.

File: src/EnergyPlus/api/state.py [hunk 6]
```diff
@@ -85,7 +85,7 @@ def new_state(self) -> c_void_p:
 
         :return: A pointer to a new state object in memory
         """
-        return self.api.stateNew()
+        return self.api.stateNewPython()
```
Comment (jmarrec) [inline src/EnergyPlus/api/state.py:88]: state_new in python calls stateNewPython... That's unfortunate to add another extern C method, but given the lack of support in C for default argument values...

File: src/EnergyPlus/CMakeLists.txt [hunk 7]
```diff
@@ -976,9 +976,22 @@ if(BUILD_TESTING)
   add_executable(TestAPI_Runtime_C ${PROJECT_SOURCE_DIR}/tst/EnergyPlus/api/TestRuntime.c)
   target_link_libraries(TestAPI_Runtime_C PRIVATE energyplusapi project_options project_fp_options)
   # target_compile_options(TestAPI_Runtime_C PRIVATE -Wall -Wextra -Wno-unused)
-
   add_test(NAME "API.TestRuntimeC" COMMAND TestAPI_Runtime_C -d "${TEST_DIR}" -w "${EPW_FILE}" -D "${IDF_FILE}")
 
+  set(TEST_DIR "${PROJECT_BINARY_DIR}/tst/api/runtimeresetpython")
```
Comment (jmarrec) [inline src/EnergyPlus/CMakeLists.txt:981]: I added 4 tests:
* stateDelete in both C and python
* stateReset in both C and python

Without the fix the C ones pass, the python ones are exhibiting the segfault (tested ubuntu 20.04)

**Comment by jmarrec** [comment]
Running a file with state_new and delete_state 10 times in a for loop (cf https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9222/example_1zone.py)


image

---

Here is the reset state equivalent (https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9202/example_1zone.py)

image

File: src/EnergyPlus/CMakeLists.txt (hunk 7 above)
Comment (Myoldmopar) [reply src/EnergyPlus/CMakeLists.txt:981]: I always love TDD.

File: src/EnergyPlus/PluginManager.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PluginManager.hh:249]: Interesting.  This isn't code that is commonly touched, so I'm not going to rigor over an extra variable, but I am a bit unsure why you can't just always use the one from state, and not have one on the plugin manager at all.  I guess it's because the plugin manager dtor doesn't take a state argument...so there is no state to access, only local members.

File: src/EnergyPlus/PluginManager.hh (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PluginManager.hh:213]: Again, it seems this is so that the dtor has access to a copy of the flag.

File: src/EnergyPlus/PluginManager.cc (hunk 4 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PluginManager.cc:405]: It's all making sense now.  Nice.

File: src/EnergyPlus/PluginManager.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PluginManager.cc]: I personally think we could go without it entirely as well......but yeah, this is the safer option.

File: src/EnergyPlus/api/state.cc (hunk 5 above)
Comment (Myoldmopar) [reply src/EnergyPlus/api/state.cc:68]: Nice.

File: src/EnergyPlus/api/state.py (hunk 6 above)
Comment (Myoldmopar) [reply src/EnergyPlus/api/state.py:88]: Yeah, it's not a big deal to me at all.  This is hidden within the API anyway, so all good.

File: tst/EnergyPlus/api/TestRuntimeResetState.py [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+print("RESETTING STATE")
+api.state_manager.reset_state(state)
+
+api.runtime.callback_progress(state, progress_handler)
+v = api.runtime.run_energyplus(state, sys.argv[1:])
+if v != 0:
+    print("EnergyPlus Failed!")
+    sys.exit(1)
+
+print("MUTED E+ RUN 2 DONE")
```
Comment (Myoldmopar) [inline tst/EnergyPlus/api/TestRuntimeResetState.py:83]: Awesome new test scripts!

**Review by Myoldmopar — APPROVED** [review]
This is awesome and looks ready to go.  I had to walk through it pretty carefully to understand, but I get it now.  Adding the member variable to the plugin manager class itself allows the dtor to respond to it, where it couldn't access state before to check anything.  All good!  Thanks!

**Comment by Myoldmopar** [comment]
Looks like the two new C API tests failed on Linux. The Windows build message looks unrelated.  Let me know if you want me to test it out on Linux or anything, @jmarrec.  I assume when those are running fine this will merge.  Thanks!

**Comment by jmarrec** [comment]
> Looks like the two new C API tests failed on Linux. The Windows build message looks unrelated. Let me know if you want me to test it out on Linux or anything, @jmarrec. I assume when those are running fine this will merge. Thanks!

@Myoldmopar damn... `Fatal Python error: Py_Initialize: can't initialize sys`. I would bet this is related to the specific version of Python that the linux runner has versus what mine is. Do you know what Python is used on that runner? Is this an Ubuntu 18.04 with system python (= python 3.6)?

**Comment by mbadams5** [comment]
@jmarrec, what version of python are you using locally? I wonder if this bug is the cause or not (it was fixed in 3.7 and up)? https://bugs.python.org/issue32849

**Comment by jmarrec** [comment]
While testing this I was testing using 3.9.7...

**Comment by jmarrec** [comment]
I built on Ubuntu 20.04 with 3.6.7, and indeed it crashes on the second PyInitialize_Ex (but Py_FinalizeEx is called like it was before...). I'm not sure what changed between develop and this, but I suspect develop would throw on this test as well. I'm building the  develop+tests (no other changes right now)

```c++
Fatal Python error: Py_Initialize: can't initialize sys

Current thread 0x00007fffe51067c0 (most recent call first):
Process 225027 stopped
* thread #1, name = 'TestAPI_Runtime', stop reason = signal SIGABRT
    frame #0: 0x00007fffe59dc03b libc.so.6`raise + 203
libc.so.6`raise:
->  0x7fffe59dc03b <+203>: movq   0x108(%rsp), %rax
    0x7fffe59dc043 <+211>: xorq   %fs:0x28, %rax
    0x7fffe59dc04c <+220>: jne    0x7fffe59dc074            ; <+260>
    0x7fffe59dc04e <+222>: movl   %r8d, %eax
(lldb) bt
* thread #1, name = 'TestAPI_Runtime', stop reason = signal SIGABRT
  * frame #0: 0x00007fffe59dc03b libc.so.6`raise + 203
    frame #1: 0x00007fffe59bb859 libc.so.6`abort + 299
    frame #2: 0x00007fffe51e7ba2 libpython3.6m.so.1.0`Py_FatalError(msg=<unavailable>) at pylifecycle.c:1462:5
    frame #3: 0x00007fffe5302bd4 libpython3.6m.so.1.0`_Py_InitializeEx_Private at pylifecycle.c:401:9
    frame #4: 0x00007fffe5302a42 libpython3.6m.so.1.0`_Py_InitializeEx_Private(install_sigs=0, install_importlib=1) at pylifecycle.c:305
    frame #5: 0x00007fffec75c68e libenergyplusapi.so.22.1.0`EnergyPlus::PluginManagement::PluginManager::PluginManager(this=0x0000555556c4f450, state=0x0000555556be01b0) at PluginManager.cc:437:24
    frame #6: 0x00007fffecd5157e libenergyplusapi.so.22.1.0`std::_MakeUniq<EnergyPlus::PluginManagement::PluginManager>::__single_object std::make_unique<EnergyPlus::PluginManagement::PluginManager, EnergyPlus::EnergyPlusData&>((null)=0x0000555556be01b0) at unique_ptr.h:962:30
    frame #7: 0x00007fffecd24cc6 libenergyplusapi.so.22.1.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x0000555556be01b0) at SimulationManager.cc:287:111
    frame #8: 0x00007fffeb4c2399 libenergyplusapi.so.22.1.0`runEnergyPlusAsLibrary(state=0x0000555556be01b0, argc=7, argv=0x00007fffffffcc38) at EnergyPlusPgm.cc:445:56
    frame #9: 0x00007fffeb1f23a1 libenergyplusapi.so.22.1.0`::energyplus(state=0x0000555556be01b0, argc=7, argv=0x00007fffffffcc38) at runtime.cc:75:34
    frame #10: 0x000055555555670c TestAPI_RuntimeDeleteState_C`main(argc=7, argv=0x00007fffffffcc38) at TestRuntimeDeleteState.c:83:5
    frame #11: 0x00007fffe59bd0b3 libc.so.6`__libc_start_main + 243
    frame #12: 0x00005555555564de TestAPI_RuntimeDeleteState_C`_start + 46
(lldb) fr select 5
frame #5: 0x00007fffec75c68e libenergyplusapi.so.22.1.0`EnergyPlus::PluginManagement::PluginManager::PluginManager(this=0x0000555556c4f450, state=0x0000555556be01b0) at PluginManager.cc:437:24
   434 	    // If arg 0, it skips init registration of signal handlers, which might be useful when Python is embedded.
   435 	    bool alreadyInitialized = (Py_IsInitialized() != 0);
   436 	    if (!alreadyInitialized) {
-> 437 	        Py_InitializeEx(0);
   438 	    }
   439 	
   440 	    // Take control of the global interpreter lock while we are here, make sure to release it...
(lldb) 

```

**Comment by jmarrec** [comment]
yup, if you take the C tests only (no other changes) and run them with develop with 3.6.7: they throw...

@Myoldmopar now that we pin the python version on github (to 3.8 currently), can we just get the decent_ci runners to use the same version?

**Comment by Myoldmopar** [comment]
Or we could just include the CPython source and always build the exact same version every single time.

**Comment by Myoldmopar** [comment]
Just kidding, but that is indeed part of the reason why I wanted to do that in the first place.  Anyway, yes, we can do that.  I'll need to determine how we'll make sure Decent CI uses the correct version when it builds.

**Comment by jmarrec** [comment]
@Myoldmopar pass `-DPYTHON_VERSION:STRING=3.8 -DPython_ROOT_DIR:PATH=/path/to/python_root/` eg `-DPython_ROOT_DIR:PATH=~/.pyenv/versions/3.8.12/` (under which you have the include/ lib/ bin/ subfolders)

If you use pyenv, make sure you pass --enable-shared, eg `PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.8.12` or when linking E+ you'll get

```
relocation R_X86_64_PC32 against symbol `_PyRuntime' can not be used when making a shared object; recompile with -fPIC
```

File: CMakeLists.txt [hunk 9]
```diff
@@ -161,8 +161,12 @@ endif()
...
   # find_package(Python) has the problem that on github actions in particular it'll pick up the most recent python (eg 3.9) from the tool cache
   # even if you have used the setup-python action and set it to 3.8, so we make the exact version required
-  if(PYTHON_VERSION)
-    find_package(Python ${PYTHON_VERSION} EXACT COMPONENTS Interpreter Development REQUIRED)
+  set(Python_REQUIRED_VERSION "" CACHE STRING "The specific Python version you want to link to (Optional)")
+  set(Python_ROOT_DIR "" CACHE PATH "The path to the root installation of your python version, if you want to explicitly set it (Optional)")
+  mark_as_advanced(Python_REQUIRED_VERSION)
+  mark_as_advanced(Python_ROOT_DIR)
+  if(Python_REQUIRED_VERSION)
+    find_package(Python ${Python_REQUIRED_VERSION} EXACT COMPONENTS Interpreter Development REQUIRED)
```
Comment (mitchute) [inline CMakeLists.txt:169]: Do we still need to expose `PYTHON_INCLUDE_DIR`, `PYTHON_LIBRARY`, and `PYTHON_LIBRARY_DEBUG` or are those no longer needed?

Comment (jmarrec) [reply CMakeLists.txt:169]: @mitchute Those are artifacts from when the deprecated `find_package(PythonInterp)` and `find_package(PythonLibs)` were used. You don't see them on a clean build. 

cf https://cmake.org/cmake/help/latest/module/FindPythonLibs.html

**Comment by Myoldmopar** [comment]
Now we're talking, look at that green!  I assume this will merge shortly once the integration tests complete. (They were already happy before anyway...)

File: CMakeLists.txt [hunk 10]
```diff
@@ -161,8 +161,12 @@ endif()
...
   else()
     find_package(Python 3.6 COMPONENTS Interpreter Development REQUIRED)
```
Comment (mbadams5) [inline CMakeLists.txt:171]: My only comment is that this should probably be 3.7 and not 3.6 now since Python 3.6 reached End of Life Dec 2021 (https://endoflife.date/python). But this doesn't have to change in this PR necessarily.

Comment (jmarrec) [reply CMakeLists.txt:171]: That would be annoying for people on Ubuntu 18 04 (or Gort, until yesterday) as the system python is 3.6. I personally dont care, I always use pyenv and much more recent pythons

Comment (Myoldmopar) [reply CMakeLists.txt:171]: @mbadams5 I do hear you there.  Once Ubuntu 22.04 is released next month I plan to reimage our CI machines up to 20.04.  That would still be one full LTS behind, which seems pretty safe.  In that case, I'd be fully in support of going to 3.7 here.  Let's chat about that soon.

**Comment by Myoldmopar** [comment]
Alright, aside from @mbadams5 's comment, which will be brought back up soon, this is ready to go.  Thanks for these fixes @jmarrec !!!  Merging this one in.
