### PR TITLE
Fix Window Heat Transfer and Solar Out Window output reporting

### LINKED ISSUE #10333: "Surface Window Net Heat Transfer Energy" does not account for all heat transfer across the windows
Issue overview
--------------
After [not finding an explanation on Unmethours](https://unmethours.com/question/97631/help-with-constructing-the-simplest-load-balance-with-energyplus/), I'm fairly confident that there is either something is incorrect in the E+ docs or there is a bug related to the following E+ output:

[`Surface Window Net Heat Transfer Energy`](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-thermal-zone-description-geometry.html#surface-window-net-heat-transfer-rate-j)

This output is consistently missing some amount of energy transferred out of the windows in order to account for the complete heat flow across the window.

### Details
The easiest way to replicate and understand the issue is to build a model where all of the heat flow in and out of the zone should be across the windows. That is, a single-zone model without any HVAC, internal loads, or infiltration. If the model has an adiabatic floor and ceiling and walls with 100% glazing ratio, then the `Surface Window Net Heat Transfer Energy` should account for all of the zone heat flow in the model. So summing the values of `Surface Window Net Heat Transfer Energy`  for every month should give something close to zero if EnergyPlus is respecting the first law of thermodynamics and the energy in = energy out when the temperature of the zone is not significantly changing. Here is an IDF for one such model:
https://drive.google.com/file/d/1c_RsW1Jo_dcOAwDu1XZZnQcuwz1wjTwO/view?usp=sharing

And here's a screenshot of what it looks like:
image

When we look at the monthly values of `Surface Window Net Heat Transfer Energy` for this model, we consistently get positive values, which are a significant fraction of the overall heat balance of the model and indicate that some energy that's flowing out of the windows is not accounted for in the `Surface Window Net Heat Transfer Energy`. Here are the monthly totals in kWh when running the IDF above using the Boston EPW file from DoE:

- Jan: 499
- Feb: 713
- Mar: 787
- Apr: 500
- May: 903
- Jun: 809
- Jul: 750
- Aug: 699
- Sep: 547
- Oct: 542
- Nov: 344
- Dec: 523

And you can visualize the overall heat balance of the model in the flowing chart where "Solar" is the `Zone Windows Total Transmitted Solar Radiation Energy`, "Window Loss" is the `Surface Window Net Heat Transfer Energy` minus the "Solar" and "Unidentified Heat Loss" is the remaining term that would be needed to make the monthly results sum to zero and respect the first law of thermodynamics.

image

It is important to note that, while the IDF example I uploaded is the simplest way to see the issue, I consistently get the the `Surface Window Net Heat Transfer Energy` being more positive than it should be. This is true no matter which EPW file I use or whether the zone is conditioned. As long as the glazing ratio of the model is high enough, this imbalance becomes noticeable and it doesn't go away with a higher simulation timestep or more advanced solar distribution calculations.

I have also noticed that combining the following E+ outputs gives me something consistently positive, which makes me think that one of them might not be reporting everything that it should:

* Surface Window Transmitted Solar Radiation Rate
* Surface Window Inside Face Glazing Zone Convection Heat Gain Rate
* Surface Window Inside Face Glazing Net Infrared Heat Transfer Rate
* Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate

Note that I subtract the `Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate` since it comes out of the simulation as a positive term while the other 3 have the appropriate sign.

It's also possible that there's just another term that I should be accounting for outside of these 4 that would make everything balanced. However, I have been unable to come up with what I'm missing after racking my brain for a week and no one has had any suggestions on Unmethours. Faced with the current situation, I have just started using a fudge factor to get rid of the  "Unidentified Heat Loss" in the load balances I create from EnergyPlus and I'm inclined to think this is a bug. Or perhaps the E+ docs are missing some important details (eg. maybe the `Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate` does not include all shortwave solar that makes it out though each window).

Some clarification on this would be much appreciated.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #10333 
 - Correct "Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate" (`state.dataHeatBal->SurfWinInitialDifSolInTransReport, SurfWinInitialDifSolInTrans`) and "Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate" (`state.dataSurface->SurfWinLossSWZoneToOutWinRep`) to be (1-Reflected) solar. Previously, these were calculated using the diffuse transmittance which omits the solar absorbed in the glass on the way out.
 - When using full interior solar distribution, some direct beam solar can leave the zone when it is incident on the inside face of a window (interior or exterior). This component is now added to "Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate".
 - Correct "Surface Window Net Heat Transfer Rate" and related outputs to subtract "Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate". Previously, this term was omitted, so the window heat gain was overstated. Related outputs include "Surface Window Heat Gain Rate/Energy" and "Surface Window Heat Loss Rate/Energy". *Note that there may be significant changes in these outputs for highly glazed enclosures.*
 - Fixes eio output for WindowConstruction to write the values for Solar Transmittance at Normal Incidence and Visible Transmittance at Normal Incidence. Previously, the format did not have enough terms, so the last two values were not written. This happened in v22.1 when "Conductance (Before Adjusted) {W/m2-K}" and "Convection Coefficient Adjustment Ratio" were added in https://github.com/NREL/EnergyPlus/pull/9117.

### Expected Diffs
 - **NO mtr diffs** because none of the impacted calculations are actually used in the heat balance, they are all side calcs used to generate various output variables.
 - **eio diffs** due to missing terms in the WindowConstruction report. And equivalent table diffs in the Initialization Summary report, e.g. PurchAirWindowBlind:
 ```
- WindowConstruction,WIN-CON-SINGLEPANE,5,1,VerySmooth,5.894,5.894,1.000,0.919
+ WindowConstruction,WIN-CON-SINGLEPANE,5,1,VerySmooth,5.894,5.894,1.000,0.919,0.900,0.900
 ```
image

 - **eso diffs** for any of the affected output variables
 - **Table diffs** for the Sensible Heat Gain Summary, because Surface Window Heat Gain Energy (and Loss) are used for the "Window Heat Addition/Loss" columns in this report, e.g.  percent diff output for _5ZoneAirCooled_annual:
 
image

### ToDo List
 - [ ] Unit test
 - [ ] I/O Ref updates, maybe Engineering Ref?
 - [ ] Confirm that the correct reflectance values have been used for the various window types (normal, complex, and equivalent layer).
 - [ ] Demonstrate solar and energy balances with defect file.
 - [ ] Check results for all variations of solar distribution (so far FullExterior looks good).
 - [ ] Demonstrate solar and energy balances with defect file.
 - [ ] Some minor refactoring to avoid extra multiplications.
 - [ ] A separate no-diff PR with some additional code cleanup (e.g. reduced variable scope, reference assignments, avoid duplicate code where possible, etc.).

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Tagging this for v24.1, because the change in the Window Heat Gain/Loss outputs is dramatic for highly glazed spaces. But there is still some QA work to be done on these changes, so it may need to wait for v24.2. There is a small output change that can be reverted if this is a go for v24.1.

**Comment by rraustad** [comment]
Could you provide a walk-thru, and discuss the "* transmittance" versus "* (1 - Reflectance)" changes and why.

**Comment by shorowit** [comment]
I'm really looking forward to these improvements. We've been providing [disaggregated heating/cooling loads by component](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_outputs.html#annual-component-building-loads) for many years and have never gotten the sum of all components to perfectly match the total building load, with windows being the primary culprit.

It would be nice if the somewhere in the documentation it clearly stated which individual heat transfer components add up to the total window heat transfer.

**Comment by shorowit** [comment]
I'm also happy to test these changes across a range of our residential models, let me know when you think it is worth testing.

**Comment by rraustad** [comment]
I noticed this in CppCheck. If no other changes this can be cleaned out later.
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L6734-L6737

**Comment by mjwitte** [comment]
> I noticed this in CppCheck. If no other changes this can be cleaned out later. https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L6734-L6737

Well, that's only been in there for 3 yrs. Removed.

**Comment by mjwitte** [comment]
> Could you provide a walk-thru, and discuss the "* transmittance" versus "* (1 - Reflectance)" changes and why.

Here's the I/O Reference definition for Window Heat Gain for an unshaded window:

> The total heat flow to the zone from the glazing, frame and divider of an exterior window when the total
> heat flow is positive.
> For a window without an interior shading device, this heat flow is equal to:
> • [Surface Window Transmitted Solar Radiation Rate (see definition, above)]
> • [Convective heat flow to the zone from the zone side of the glazing]
> • [Net IR heat flow to the zone from zone side of the glazing]
> • [Short-wave radiation from zone transmitted back out the window]
> • [Convection to zone from window frame and divider, if present]
> Here, short-wave radiation is that from lights and diffuse interior solar radiation.
> The total window heat flow can also be thought of as the sum of the solar and conductive gain to the
> zone from the window.

The first term, solar transmitted into the zone, as well as the convective and IR heat flow, are at the boundary volume of the inside face of the window surface. So the shortwave that leaves the zone should also be at the inside face, thus `OutgoingSolarOrShortwave*(1-Reflectance)`. Any energy absorbed in the glass on the way in or out will be accounted for in the glass temperature that impacts the convective and IR heat flow.

Stepping back from the heat gain, I first tried to balance just the solar components, expecting that:
Zone Windows Total Transmitted Solar Radiation Energy = Sum Opaque Surface Inside Face Solar Radiation Heat Gain Energy + Sum Surface Window Shortwave from Zone Back Out Window Heat Transfer Energy + Sum Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Energy.

Here's the solar balance before and after for the defect file (which is a box with four walls that are nearly 100% glazing) with FullExterior solar distribution:
Develop:
image
This Branch:
image

Not perfect, but balancing within 0.2% is much better than 8%.

Then I tried the same with FullInteriorAndExterior, and the imbalance ranges from 0.8 to 6%, highest in the winter months. Looks like we need yet another window variable to track *beam* solar that leaves out a window. <sigh>

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 1]
```diff
@@ -8100,26 +8100,24 @@ void CalcHeatBalanceInsideSurf2(EnergyPlusData &state,
 
                 Real64 const Sigma_Temp_4(Constant::StefanBoltzmann * pow_4(state.dataHeatBalSurf->SurfTempIn(SurfNum) + Constant::Kelvin));
 
-                // Calculate window heat gain for TDD:DIFFUSER since this calculation is usually done in WindowManager
-                state.dataSurface->SurfWinHeatGain(SurfNum) =
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:8104]: Move this down, because all of the components are being calculated twice.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 2]
```diff
@@ -8100,26 +8100,24 @@ void CalcHeatBalanceInsideSurf2(EnergyPlusData &state,
...
                 state.dataSurface->SurfWinGainConvGlazToZoneRep(SurfNum) =
                     HConvIn_surf * surface.Area * (state.dataHeatBalSurf->SurfTempIn(SurfNum) - state.dataHeatBalSurfMgr->RefAirTemp(SurfNum));
                 state.dataSurface->SurfWinGainIRGlazToZoneRep(SurfNum) =
                     state.dataConstruction->Construct(surface.Construction).InsideAbsorpThermal * surface.Area *
                     (Sigma_Temp_4 - (state.dataSurface->SurfWinIRfromParentZone(SurfNum) + state.dataHeatBalSurf->SurfQdotRadHVACInPerArea(SurfNum)));
-                state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) = state.dataHeatBal->EnclSolQSWRad(surface.SolarEnclIndex) * surface.Area *
-                                                                           state.dataConstruction->Construct(surface.Construction).TransDiff;
+                state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) =
+                    state.dataHeatBal->EnclSolQSWRad(surface.SolarEnclIndex) * surface.Area *
+                    (1 - state.dataConstruction->Construct(surface.Construction).ReflectSolDiffBack);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Here and below, calcs just for TDD:Diffuser. Switch this component to use `(1-ReflectSolDiffBack)` instead of `TransDiff`.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 3]
```diff
@@ -8100,26 +8100,24 @@ void CalcHeatBalanceInsideSurf2(EnergyPlusData &state,
...
+
+                // Calculate window heat gain for TDD:DIFFUSER since this calculation is usually done in WindowManager
+                state.dataSurface->SurfWinHeatGain(SurfNum) =
+                    state.dataSurface->SurfWinTransSolar(SurfNum) + state.dataSurface->SurfWinGainConvGlazToZoneRep(SurfNum) +
+                    state.dataSurface->SurfWinGainIRGlazToZoneRep(SurfNum) - state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) -
+                    surface.Area * state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(SurfNum);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:8120]: Calculate `SurfWinHeatGain` here, after all of the components have been calculated to avoid duplicate calcs. Also add the ` - surface.Area * state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(SurfNum)` term.

File: src/EnergyPlus/SolarShading.cc [hunk 4]
```diff
@@ -6731,10 +6731,6 @@ void CalcInteriorSolarDistribution(EnergyPlusData &state)
                                                   (AbsBlDiffBack * RGlDiffFront / (1.0 - RhoBlDiffBack * RGlDiffFront)) *
                                                       (RGlFront * TBlBmBm * RhoBlBack + TBlBmDiff);
                                 state.dataSolarShading->SurfWinExtBeamAbsByShadFac(SurfNum) = AbsShade * CosInc * SunLitFract * InOutProjSLFracMult;
-                                if (state.dataEnvrn->Month == 7 && state.dataEnvrn->DayOfMonth == 21 && state.dataGlobal->HourOfDay == 8) {
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:6734]: Remove old debug code.

File: src/EnergyPlus/SolarShading.cc [hunk 5]
```diff
@@ -11913,18 +11909,16 @@ void CalcWinTransDifSolInitialDistribution(EnergyPlusData &state)
...
-                            } // this is an interior window surface
+                            // Calc transmitted Window and Zone total distributed diffuse solar to check for
+                            // conservation of energy This is not very effective since it assigns whatever
+                            // distributed diffuse solar has not been absorbed or reflected to transmitted.
+                            // Should be just total less reflected
+                            Real64 DifSolarTransIntoW = WinDifSolarTrans_Factor - DifSolarReflW;
 
                             // Accumulate transmitted diffuse solar for reporting
-                            state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(HeatTransSurfNum) += DifSolarTransW * per_HTSurfaceArea;
+                            state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(HeatTransSurfNum) += DifSolarTransIntoW * per_HTSurfaceArea;
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:11942]: Use total incoming minus reflected for initial solar out window. Similar calcs appear in multiple places for different window types.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc (hunk 2 above)
Comment (rraustad) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Isn't part of (1-ReflectSolDiffBack) absorbed by the window on the way out? and therefore doesn't make it out?

File: src/EnergyPlus/WindowComplexManager.cc [hunk 6]
```diff
@@ -3338,8 +3339,10 @@ namespace WindowComplexManager {
             // END IF
             state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) =
                 state.dataHeatBal->EnclSolQSWRad(state.dataSurface->Surface(SurfNum).SolarEnclIndex) * state.dataSurface->Surface(SurfNum).Area *
-                TransDiff;
-            state.dataSurface->SurfWinHeatGain(SurfNum) -= state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum);
+                (1 - ReflDiff);
+            state.dataSurface->SurfWinHeatGain(SurfNum) -=
+                (state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) +
+                 state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(SurfNum) * state.dataSurface->Surface(SurfNum).Area);
```
Comment (mjwitte) [inline src/EnergyPlus/WindowComplexManager.cc]: Use (1-Reflectance) for Shortwave from Zone Out Window, and also subtract the Initial Diffuse Out Window term from `SurfWinHeatGain`. This appears in multiple places.

File: src/EnergyPlus/WindowManager.cc [hunk 7]
```diff
@@ -7371,7 +7379,7 @@ namespace WindowManager {
                         state.dataConstruction->Construct(ThisNum).VisTransNorm = TransVisNorm;
                         state.dataConstruction->Construct(ThisNum).SolTransNorm = TransSolNorm;
 
-                        static constexpr std::string_view Format_700(" WindowConstruction,{},{},{},{},{:.3R},{:.3R},{:.3R},{:.3R}\n");
+                        static constexpr std::string_view Format_700(" WindowConstruction,{},{},{},{},{:.3R},{:.3R},{:.3R},{:.3R},{:.3R},{:.3R}\n");
```
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc:7376]: Extend format so that Solar and Visible Transmittance values are written to eio for the WindowConstruction report.

**Review by mjwitte — COMMENTED** [review]
First walkthru.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: > Isn't part of (1-ReflectSolDiffBack) absorbed by the window on the way out? and therefore doesn't make it out?

Yes, some is absorbed. If your boundary volume is the inside face, then (1-Reflected) has already made it out. If some gets absorbed, then that's accounted for in the convective/radiative exchange for the glass.

**Comment by mjwitte** [comment]
> I noticed this in CppCheck. If no other changes this can be cleaned out later. https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L6734-L6737

Done.

File: doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex [hunk 8]
```diff
@@ -3549,101 +3549,63 @@ \subsubsection{Surface Window Gap Convective Heat Transfer Energy {[}J{]}}\label
 
 For an airflow window, the forced convective heat flow from the gap through which airflow occurs. This is the heat gained (or lost) by the air from the glass surfaces (and between-glass shading device surfaces, if present) that the air comes in contact with as it flows through the gap. If the gap airflow goes to the zone indoor air, the gap convective heat flow is added to the zone load. Applicable to exterior windows only.
 
-\subsubsection{Surface Window Heat Gain Rate {[}W{]}}\label{surface-window-heat-gain-rate-w}
+\subsubsection{Surface Window Net Heat Transfer Rate {[}W{]}}\label{surface-window-net-heat-transfer-rate-w}
 
-\subsubsection{Surface Window Heat Gain Energy {[}J{]}}\label{surface-window-heat-gain-energy-j}
+\subsubsection{Surface Window Net Heat Transfer Energy {[}J{]}}\label{surface-window-net-heat-transfer-rate-j}
```
Comment (mjwitte) [inline doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex:3554]: Update this section use actual output variable names for the components, add missing components, and delete duplicate list of components. Reviewers, please read these doc changes carefully to see if they make sense.

File: doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex [hunk 9]
```diff
@@ -3803,7 +3765,7 @@ \subsubsection{Surface Storm Window On Off Status {[]}}\label{surface-storm-wind
...
 
-As of Version 2.1, the diffuse solar transmitted through exterior windows that is initially distributed to another window in the zone and transmitted out of the zone through that window. For exterior windows, this transmitted diffuse solar is ``lost'' to the exterior environment For interior windows, this transmitted diffuse solar is distributed to heat transfer surfaces in the adjacent zone, and is part of the Surface Inside Face Initial Transmitted Diffuse Absorbed Solar Radiation Rate for these adjacent zone surfaces.
+As of Version 2.1, the diffuse solar transmitted through exterior windows that is initially distributed to another window in the zone and transmitted out of the zone through the inside face of the window. Some of this will be absorbed in the window layers and some will be transmitted through. For exterior windows, transmitted diffuse solar is ``lost'' to the exterior environment. For interior windows, this transmitted diffuse solar is distributed to heat transfer surfaces in the adjacent zone, and is part of the Surface Inside Face Initial Transmitted Diffuse Absorbed Solar Radiation Rate for these adjacent zone surfaces.
```
Comment (mjwitte) [inline doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex:3768]: Update the description for Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate to explain that the boundary volume is the inside face of the glass or window assembly.

File: doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex [hunk 10]
```diff
@@ -3819,11 +3781,11 @@ \subsubsection{Surface Window Inside Face Glazing Net Infrared Heat Transfer Rat
...
 
 \subsubsection{Surface Window Inside Face Frame and Divider Zone Heat Gain Rate {[}W{]}}\label{surface-window-inside-face-frame-and-divider-zone-heat-gain-rate-w}
 
-This is the heat transfer from any frames and/or dividers to the zone in watts. This output variable is the term called ``{[}Conduction to zone from window frame and divider, if present{]}'' under the description above for Surface Window Heat Gain Rate output variable. (The word ``conduction'' here is used because the models is simplified compared to the complexities of surface convection and radiation.)
+This is the convective heat transfer from any frames and/or dividers to the zone in watts. Negative values imply heat flow to the exterior. The Surface Window Frame Inside Temperature and Surface Window Divider Inside Temperature are computed from a heat balance on the frame/divider that includes solar radiation, long-wave radiation, convection, and conduction. The frame/divider is then included in the zone heat balance via convection at this inside temperature. See Engineering Reference ``Window Frame and Divider Calculation'' for more details.
```
Comment (mjwitte) [inline doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex:3788]: Add some clarification to Surface Window Inside Face Frame and Divider Zone Heat Gain Rate.

File: doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex [hunk 11]
```diff
@@ -3819,11 +3781,11 @@ \subsubsection{Surface Window Inside Face Glazing Net Infrared Heat Transfer Rat
 
 \subsubsection{Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate {[}W{]}}\label{surface-window-shortwave-from-zone-back-out-window-heat-transfer-rate-w}
 
-This is the short-wave radiation heat transfer from the zone back out the window in watts. This is a measure of the diffuse short-wave light (from reflected solar and electric lighting) that leave the zone through the window. This output variable is the term called ``{[}Short-wave radiation from zone transmitted back out the window{]}'' under the description above for Surface Window Heat Gain Rate output variable.
+This is the short-wave radiation heat transfer from the zone back out the inside face of the window in watts. This is a measure of the diffuse short-wave light (from beam and diffuse solar and electric lighting) that leaves the zone through the window.
```
Comment (mjwitte) [inline doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex:3784]: Update Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate to add interior incident beam (from FullInterior solar distribution) and explain the inside face boundary volume.

File: src/EnergyPlus/SolarShading.cc [hunk 12]
```diff
@@ -7465,8 +7461,9 @@ void CalcInteriorSolarDistribution(EnergyPlusData &state)
                                 int ConstrNumBackShRaw = state.dataSurface->SurfWinActiveShadedConstruction(BackSurfNum);
                                 int const ConstrNumBackSh = ConstrNumBackShRaw == 0 ? ConstrNumBack : ConstrNumBackShRaw;
                                 state.dataSolarShading->SurfWinAbsBeam.dimension(state.dataHeatBal->MaxSolidWinLayers, 0.0);
-                                Real64 TransBeamWin = 0.0;  // Beam solar transmittance of a window
-                                Real64 AbsBeamTotWin = 0.0; // Sum of window glass layer beam solar absorptances
+                                Real64 TransBeamWin = 0.0;           // Beam solar transmittance of a window
+                                Real64 AbsBeamTotWin = 0.0;          // Sum of window glass layer beam solar absorptances
+                                Real64 backSurfBeamSolInTrans = 0.0; // Fraction of BeamSolarRad transmitted out through window inside face [W]
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:7466]: Track interior beam solar that enters a back surface that's a window.

File: src/EnergyPlus/WindowEquivalentLayer.cc [hunk 13]
```diff
@@ -821,7 +821,9 @@ void EQLWindowSurfaceHeatBalance(EnergyPlusData &state,
     ConvHeatGainWindow = state.dataSurface->Surface(SurfNum).Area * HcIn * (SurfInsideTemp - TaIn);
     // Window heat gain (or loss) is calculated here
     state.dataSurface->SurfWinHeatGain(SurfNum) =
-        state.dataSurface->SurfWinTransSolar(SurfNum) + ConvHeatGainWindow + NetIRHeatGainWindow + ConvHeatFlowNatural;
+        state.dataSurface->SurfWinTransSolar(SurfNum) + ConvHeatGainWindow + NetIRHeatGainWindow + ConvHeatFlowNatural -
+        (state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) +
+         state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(SurfNum) * state.dataSurface->Surface(SurfNum).Area);
```
Comment (mjwitte) [inline src/EnergyPlus/WindowEquivalentLayer.cc:826]: Subtract missing solar leaving components from `SurfWinHeatGain` for equivalent layer windows.

File: src/EnergyPlus/WindowManager.cc [hunk 14]
```diff
@@ -3842,31 +3841,34 @@ namespace WindowManager {
...
+                                    state.dataConstruction->Construct(ConstrNumSh).ReflectSolDiffBack);
             }
             // shouldn't this be + outward flowing fraction of absorbed SW? -- do not know whose comment this is?  LKL (9/2012)
             state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) =
                 state.dataHeatBal->EnclSolQSWRad(state.dataSurface->Surface(SurfNum).SolarEnclIndex) * state.dataSurface->Surface(SurfNum).Area *
-                TransDiff;
-            state.dataSurface->SurfWinHeatGain(SurfNum) -= state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum);
+                    (1 - reflDiff) +
+                state.dataHeatBalSurf->SurfWinInitialBeamSolInTrans(SurfNum);
+            state.dataSurface->SurfWinHeatGain(SurfNum) -=
```
Comment (mjwitte) [inline src/EnergyPlus/WindowManager.cc:3869]: Subtract missing solar leaving components from `SurfWinHeatGain` for regular windows.

File: src/EnergyPlus/WindowComplexManager.cc [hunk 15]
```diff
@@ -3338,8 +3338,11 @@ namespace WindowComplexManager {
             // END IF
             state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum) =
                 state.dataHeatBal->EnclSolQSWRad(state.dataSurface->Surface(SurfNum).SolarEnclIndex) * state.dataSurface->Surface(SurfNum).Area *
-                TransDiff;
-            state.dataSurface->SurfWinHeatGain(SurfNum) -= state.dataSurface->SurfWinLossSWZoneToOutWinRep(SurfNum);
+                    (1 - ReflDiff) +
+                state.dataHeatBalSurf->SurfWinInitialBeamSolInTrans(SurfNum);
+            state.dataSurface->SurfWinHeatGain(SurfNum) -=
```
Comment (mjwitte) [inline src/EnergyPlus/WindowComplexManager.cc:3343]: Subtract missing solar leaving components from `SurfWinHeatGain` for complex windows.

**Review by mjwitte — COMMENTED** [review]
Walkthru part 2. This still needs some unit tests, but I'm marking this ready for review. I'll add another comment showing some before/after results for solar and energy balance.

**Comment by mjwitte** [comment]
See https://github.com/NREL/EnergyPlus/pull/10444#issuecomment-2013290345 for before/after results with FullExterior solar distribution. Zip of working folder attached (with idfs, outputs, and xlsx).
[After Fixes 5-Final.zip](https://github.com/NREL/EnergyPlus/files/15133265/After.Fixes.5-Final.zip)

Results after fix for FullInteriorAndExterior. Not perfect, but all within 1% balance. Results are similar for FullInteriorAndExteriorWithReflections.
image

image

**Comment by shorowit** [comment]
I tested this on one of our residential files and, using the output variables described in the documentation, got excellent agreement between the individual window heat transfer components and the net heat transfer energy. Looks good to me, thanks @mjwitte!

File: src/EnergyPlus/SolarShading.cc (hunk 4 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SolarShading.cc:6734]: lol

File: src/EnergyPlus/SolarShading.cc [hunk 16]
```diff
@@ -12603,7 +12618,7 @@ void CalcInteriorWinTransDifSolInitialDistribution(EnergyPlusData &state,
 
                 // Accumulate transmitted diffuse solar for reporting
                 state.dataHeatBalSurf->SurfWinInitialDifSolInTrans(HeatTransSurfNum) +=
-                    (DifSolarTransW / state.dataSurface->Surface(HeatTransSurfNum).Area);
+                    (SolarTrans_ViewFactor - DifSolarReflW / state.dataSurface->Surface(HeatTransSurfNum).Area);
```
Comment (Myoldmopar) [inline src/EnergyPlus/SolarShading.cc]: Are the parentheses wrong on this one?  It is different from the others.

**Review by Myoldmopar — COMMENTED** [review]
I'm going to hold from approve/reject to hear back about the parentheses issue.  Otherwise this looks fine.

File: src/EnergyPlus/SolarShading.cc (hunk 16 above)
Comment (vidanovic) [reply src/EnergyPlus/SolarShading.cc]: @Myoldmopar You are right, the parentheses are wrong. It seem that it should be:
(SolarTrans_ViewFactor - DifSolarReflW) / state.dataSurface->Surface(HeatTransSurfNum).Area;
I did not run example to confirm this. However, there are other parts using the same equation:
https://github.com/NREL/EnergyPlus/blob/f3c55b306880c1e210aeaafc77f97b212ce44643/src/EnergyPlus/SolarShading.cc#L12441-L12442
and
https://github.com/NREL/EnergyPlus/blob/f3c55b306880c1e210aeaafc77f97b212ce44643/src/EnergyPlus/SolarShading.cc#L12511-L12512

Comment (mjwitte) [reply src/EnergyPlus/SolarShading.cc]: Thanks, good catch! Fixed. This line is in a section of code that is distributing initial diffuse from an interior window to another window in the receiving zone that has a shading device. This is not currently covered by unit or integration tests. Hoping to improve the coverage.

**Review by vidanovic — APPROVED** [review]
I have no further comments. Approving this merge.

**Comment by Myoldmopar** [comment]
Diffs don't look to have changed since before, and everything is happy on CI.  Thanks for fixing the parentheses and adding the some extra testing.  Let's call this one done.  Thanks @mjwitte and @rraustad and @vidanovic!
