### PR TITLE
Fix bad subscript in ZoneVentilation:DesignFlowRate warning

### LINKED ISSUE #11132: Bad allocation failure
### Issue overview

Original v23.2.0 idf:

[in_V2320.idf.txt](https://github.com/user-attachments/files/21432685/in_V2320.idf.txt)

Updated v25.1.0 idf:

[in.idf.txt](https://github.com/user-attachments/files/21432696/in.idf.txt)

### Operating System (Multiple choices)

Windows

### Operating System Version

Edition	Windows 11 Pro Version	24H2 OS build	26100.4770 Experience	Windows Feature Experience Pack 1000.26100.197.0

### Version of EnergyPlus

25.1.0, Bug Fix Edition

### Unmethours link or helpdesk ticket number

N/A

### Defect file

Updated a file created using E+ 23.2.0 using the E+ 25.1.0 IDFVersionUpdater.  When the original file is run in E+ 23.2.0 the file completes successfully.  When the updated file is run in E+ 25.1.0, a  severe bad allocation error is produced and a fatal node error.  The files are as follows:

in.txt (idf file updated to 25.1.0, rename to in.idf)

[in.txt](https://github.com/user-attachments/files/21432587/in.txt)

in_V2320.txt (original E+ 23.2.0 file, rename to in_V2320.idf)

[in_V2320.txt](https://github.com/user-attachments/files/21432601/in_V2320.txt)

in.err.txt (error file when updated idf file is run in E+ 25.1.0, rename to in.err)

[in.err.txt](https://github.com/user-attachments/files/21432625/in.err.txt)

Link to weather file used:
https://climate.onebuilding.org/WMO_Region_4_North_and_Central_America/CAN_Canada/QC_Quebec/CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.zip

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #11132

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceAirManager.cc [hunk 1]
```diff
@@ -1781,7 +1781,7 @@ void GetSimpleAirModelInputs(EnergyPlusData &state, bool &ErrorsFound) // IF err
                         ShowWarningCustom(
                             state,
                             eoh,
-                            format("Both {} and {} provided, {} will be used.", cAlphaFieldNames(10), cNumericFieldNames(15), cAlphaFieldNames(15)));
+                            format("Both {} and {} provided, {} will be used.", cAlphaFieldNames(10), cNumericFieldNames(15), cAlphaFieldNames(10)));
```
Comment (rraustad) [inline src/EnergyPlus/HeatBalanceAirManager.cc:1784]: That looks correct, especially when A15 does not exist.

    ZoneVentilation:DesignFlowRate,
      A9 , \field Minimum Outdoor Temperature Schedule Name
      N15, \field Maximum Outdoor Temperature
      A10, \field Maximum Outdoor Temperature Schedule Name
      N16; \field Maximum Wind Speed

**Review by rraustad — APPROVED** [review]
