### PR TITLE
Correction of Bug in HW Baseboard Get Input Routine

### LINKED ISSUE #9742: ZoneHVAC:Baseboard:RadiantConvective:Water problem unless unless the proportion of radiant energy falling on people is 0.3
Issue overview
--------------
Since version 9.5, using ZoneHVAC:Baseboard:RadiantConvective:Water, the proportion of radiant heat falling on people is set in ZoneHVAC:Baseboard:RadiantConvective:Water:Design object  while the proportion of radiant heat falling on surfaces is set in the zone baseboard object. Regression tests with earlier versions indicate incompatible results unless the proportion on people is 0.3 (as in the examples).  In my test (attached) at 8.9, reducing the people proportion  from 0.3 to 0.1 increases gas use by 1%. At 22.2  the same change reduces gas use by 15%. 

### Details
This is probably not relevant
 - MacOS 12.6
 - First appears in 9.5, when the design object was split out. I have been using 22.2

### Checklist
Two files attached which I have used to demonstrate the issue. cube-8.9.imf and cube-22.2.imf. The latter was generated by converting the former. They both have a macro set at the top for radiantPropOnPeople. Set this is 0.3 for compatible results, something else e.g. 0.1 to show the problem.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)
[bug.zip](https://github.com/NREL/EnergyPlus/files/10031091/bug.zip)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #9742 
 - A user noticed that changes to the fraction of radiant energy to people in the radiant/convective hot water baseboard unit resulted in large changes to the energy consumption of the system that was not present previously.  In an older version, changes to this parameter from 0.3 to 0.1 resulted in a reasonable 1% difference in the results.  In the latest version of EnergyPlus, the change was nearly 15%.  This was traced back to an error in the way the fraction of heat added via convection to the zone was being calculated and was introduced when the baseboard input object was split into two part--basic and design parameters.  As a result, the baseboard unit was not conserving energy.  This is now corrected and the differences are back to what they were before and should be (roughly 1%).  Along with a unit test to verify that this is now working properly, one of the test suite input files was altered to specifically examine at the situation that caused the problem.  So, in the ci results, that specific file does show differences as expected.  No other files show differences, even in the files that contain radiant convective hot water baseboard units because in all of those other files the fraction radiant and the fraction of radiant to people were both set to 0.3, masking the problem.  The other radiant convective baseboard units were also checked and they do not have the same problem that the hot water radiant convective baseboard unit had.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HWBaseboardRadiator.cc [hunk 1]
```diff
@@ -605,7 +605,7 @@ namespace HWBaseboardRadiator {
                 HWBaseboardDesignDataObject.FracRadiant = MaxFraction;
                 thisHWBaseboard.FracConvect = 0.0;
             } else {
-                thisHWBaseboard.FracConvect = 1.0 - AllFracsSummed;
+                thisHWBaseboard.FracConvect = 1.0 - HWBaseboardDesignDataObject.FracRadiant;
```
Comment (rraustad) [inline src/EnergyPlus/HWBaseboardRadiator.cc:606]: You no longer need line 598 since AllFracsSummed is also set at line 636. I see this same code in ChilledCeilingPanelSimple so what is the plan for other objects?

Comment (rraustad) [reply src/EnergyPlus/HWBaseboardRadiator.cc:606]: Correction: the code in ChilledCeilingPanelSimple does use FracRadiant in this part of the code.

Comment (RKStrand) [reply src/EnergyPlus/HWBaseboardRadiator.cc:606]: @rraustad I can get rid of line 598, not a problem.  I did check on the other radiant convective baseboard units and these were correct.  It seems like this was a one-off issue when the baseboard object was split into two pieces.

Comment (RKStrand) [reply src/EnergyPlus/HWBaseboardRadiator.cc:606]: @rraustad Got rid of line 598 and standardized all of the models that use this code in the latest commit.

File: tst/EnergyPlus/unit/HWBaseboardRadiator.unit.cc [hunk 2]
```diff
@@ -190,3 +194,123 @@ TEST_F(EnergyPlusFixture, HWBaseboardRadiator_HWBaseboardWaterFlowResetTest)
...
+
+    ZoneEquipmentManager::GetZoneEquipment(*state);
+
+    GetHWBaseboardInput(*state);
+
+    ASSERT_NEAR(state->dataHWBaseboardRad->HWBaseboard(1).FracDistribToSurf(1), 0.8, absTol);
+    ASSERT_NEAR(state->dataHWBaseboardRad->HWBaseboardDesignObject(1).FracRadiant, 0.4, absTol);
+    ASSERT_NEAR(state->dataHWBaseboardRad->HWBaseboardDesignObject(1).FracDistribPerson, 0.2, absTol);
+    ASSERT_NEAR(state->dataHWBaseboardRad->HWBaseboard(1).FracConvect, 0.6, absTol);
+}
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HWBaseboardRadiator.unit.cc:316]: Unit test looks OK.

**Review by mjwitte — APPROVED** [review]
Tested defect file with 0.3 and 0.1, got expected changes in results. Updated the branch, will let CI run one more round.

**Comment by mjwitte** [comment]
CI results are as expected, all green except diffs in one file. Merging.
