### PR TITLE
OA Limiting Factor enum and Related Cleanup

### LINKED ISSUE #8802: Air System Outdoor Air Limiting Factor can be wrong for simple OA controls due to tiny differences
Issue overview
--------------
Air System Outdoor Air Limiting Factor uses several < or > tests to determine if the OA flow rate has been constrained by a particular limiting factor (e.g. economizer, OA schedule, etc.). For simple OA controllers with no economizer, no min OA schedule, and no other constraints, this should always be zero. But occasional 1s show up due to tiny differences in comparing two values which should be equal, but due to different calculation paths for the two values, they differ out in the 10th decimal or so. Probably need to add a tolerance to one or more of these comparisons, and review the entire logic for this output.

Also, this output is reset to zero every time step inside `CalcOAController` which I'm pretty sure is not called if an airloop is off. Need a test file to prove this.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.6.0-b8f984adb5
 - Discovered while investigating unexpected diffs in #8759 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Closes #8802 
 The original defect file for this was a bit of a red herring, because it is an airflownetwork MultizoneWithDistribution model. So, the AFN connection causes slight changes in the mixed air mass flow rate which leads to the supposed anomalies in the OA limiting factor output.  Even through the mass flow differences are tiny, the OA controller logic is doing what it is supposed to. So, 8802 can be closed as-designed.
 - Move OA limiting factor to an enum
 - Minor refactoring of `CalcMechVentController`

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/MixedAir.cc [hunk 1]
```diff
@@ -3924,6 +3906,15 @@ void VentilationMechanicalProps::CalcMechVentController(
 
                                         // Calculate zone maximum target CO2 concentration in PPM
                                         if (this->SystemOAMethod == DataSizing::SysOAMethod::ProportionalControlDesOcc) {
+                                            // Accumulate CO2 generation from people at design occupancy and current activity level
+                                            Real64 CO2PeopleGeneration = 0.0;
+                                            for (int PeopleNum = 1; PeopleNum <= state.dataHeatBal->TotPeople; ++PeopleNum) {
```
Comment (amirroth) [inline src/EnergyPlus/MixedAir.cc:3885]: Can probably do `for (auto const &people : state.dataHeatBal->People)`.

File: src/EnergyPlus/MixedAir.cc [hunk 2]
```diff
@@ -3924,6 +3906,15 @@ void VentilationMechanicalProps::CalcMechVentController(
...
+                                                if (state.dataHeatBal->People(PeopleNum).ZonePtr != ZoneNum) continue;
```
Comment (amirroth) [inline src/EnergyPlus/MixedAir.cc:3886]: There are no per-zone PeopleNum lists I guess.

File: src/EnergyPlus/MixedAir.hh [hunk 3]
```diff
@@ -125,17 +125,22 @@ namespace MixedAir {
...
-    constexpr int limitFactorHighHum = 5;     // High humidity economizer control
-    constexpr int limitFactorDCV = 6;         // Demand-controlled ventilation
-    constexpr int limitFactorNightVent = 7;   // Night ventilation
-    constexpr int limitFactorDemandLimit = 8; // Demand-limiting
-    constexpr int limitFactorEMS = 9;         // EMS override
+    // stored as int since it is used in SetupOutputVariable()
+    enum class OALimitFactor
+    {
+        Invalid = -1,
+        None = 0,        // No limit other than fixed OA amount
```
Comment (amirroth) [inline src/EnergyPlus/MixedAir.hh:130]: Don't need the numbers.

File: src/EnergyPlus/MixedAir.hh [hunk 4]
```diff
@@ -154,8 +159,7 @@ namespace MixedAir {
         std::string Name;
         std::string ControllerType;
```
Comment (amirroth) [inline src/EnergyPlus/MixedAir.hh]: Probably don't need `ControllerType` (and can rename `ControllerType_Num` to `controllerType`).

File: src/EnergyPlus/MixedAir.hh [hunk 5]
```diff
@@ -311,9 +315,8 @@ namespace MixedAir {
         Real64 Evz = 1.0;      // zone ventilation efficiency
         Real64 SysDesOA = 0.0; // System design OA
 
-        void CalcMechVentController(EnergyPlusData &state,
-                                    Real64 &SysSA,             // System supply air mass flow rate [kg/s]
-                                    Real64 &MechVentOAMassFlow // outside air mass flow rate calculated by mechanical ventilation object [kg/s]
+        Real64 CalcMechVentController(EnergyPlusData &state,
+                                      Real64 &SysSA // System supply air mass flow rate [kg/s]
```
Comment (amirroth) [inline src/EnergyPlus/MixedAir.hh]: I don't think this needs to be passed by reference.

File: src/EnergyPlus/MixedAir.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc:3886]: > There are no per-zone PeopleNum lists I guess.

It does seem wrong to loop through *all* People statements for all zones. Options include making `CO2PeopleGeneration` an array and looping though once, storing the values, but this is a system-level thing here, so it only needs the zones on this systems, and a different system might use a different control option. So, per-zone PeopleNum lists are probably the best way to solve this, esp, because 99% of the time, it's a list of one element.

File: src/EnergyPlus/MixedAir.hh (hunk 3 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.hh:130]: > Don't need the numbers.

Yes, but these get used as output variable values which are documented in the I/O Ref, so the numbers are here to emphasize that these shouldn't be rearranged or have anything inserted in the middle of the list.

File: src/EnergyPlus/MixedAir.hh (hunk 5 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.hh]: I thought the same at first, but this function does have places that change `SysSA` (not that I understand why).

Comment (rraustad) [reply src/EnergyPlus/MixedAir.hh]: VRP can increase the system OA flow rate and the supply air flow rate needs to be at least equal to the OA flow rate. See #9959.

    // System supply air flow rate is always greater than or equal the system outdoor air flow rate
    if ((SysSA > 0.0) && (SysSA < (SysOAuc * state.dataEnvrn->StdRhoAir))) SysSA = SysOAuc * state.dataEnvrn->StdRhoAir;

Comment (mjwitte) [reply src/EnergyPlus/MixedAir.hh]: Ok, but how does that flow back up into the rest of the system?

Comment (amirroth) [reply src/EnergyPlus/MixedAir.hh]: > I thought the same at first, but this function does have places that change `SysSA` (not that I understand why).

Oh, I didn't see that. Sorry.

Comment (rraustad) [reply src/EnergyPlus/MixedAir.hh]: I didn't say it was implemented correctly. Once this returns back it's never used. At least the developer knew that there could be a problem (I think I did mech vent but not sure if I did this).

Comment (mjwitte) [reply src/EnergyPlus/MixedAir.hh]: So, should I un-reference `SysSA` (but not make it const)?

Comment (amirroth) [reply src/EnergyPlus/MixedAir.hh]: If you are not using the modified value then yes.

File: src/EnergyPlus/MixedAir.hh (hunk 4 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.hh]: I should know this, but I'll ask anyway. 
`std::string ControllerType` is used frequently in error messages (probably the only way it's used). 
So we'd rather write the error message with `MixedAirControllerTypeNames[static_cast<int>(ControllerType)]` than storing the string on the controller struct?

Comment (amirroth) [reply src/EnergyPlus/MixedAir.hh]: Yes and yes.

File: src/EnergyPlus/MixedAir.hh [hunk 6]
```diff
@@ -241,8 +242,8 @@ namespace MixedAir {
         int NumFaultyEconomizer = 0;                           // total number of economizer faults
         int CountMechVentFrac = 0;                             // Count when OA min fraction > mech vent fraction
         int IndexMechVentFrac = 0;                             // Index when OA min fraction > mech vent fraction
-        int OALimitingFactor = 0; // OA controller limiting factor: 0=none, 1=limits, 2=exhaust flow, 3=economizer, 4=DCV, 5=high hum, 6=night vent,
-                                  // 7=demand limiting, 8=EMS
+        OALimitFactor OALimitingFactor = OALimitFactor::None;  // OA controller limiting factor
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.hh]: Initialize to Invalid? OALimitingFactor and OALimitingFactorReport will get set in CalcOAController and there are only output reports (and pre-defined reports for tables?) when OAControllers exist in the input.

**Comment by mjwitte** [comment]
@rraustad This is ready for review assuming CI comes back clean. 
Due to possible bug #9969, saving the People loop changes for a different PR.

File: src/EnergyPlus/MixedAir.cc [hunk 7]
```diff
@@ -3648,6 +3617,7 @@ void VentilationMechanicalProps::CalcMechVentController(
     // new local variables for DCV
     // Zone OA flow rate based on each calculation method [m3/s]
     std::array<Real64, static_cast<int>(DataSizing::OAFlowCalcMethod::Num)> ZoneOACalc{0.0};
+    Real64 CO2PeopleGeneration = 0; // CO2 generation from people at design level
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:3611]: Keeping this here at the top, will move while addressing #9969

File: src/EnergyPlus/MixedAir.cc [hunk 8]
```diff
@@ -3776,85 +3753,74 @@ void VentilationMechanicalProps::CalcMechVentController(
...
-                                                                                                this->ZoneOAPeopleRate(ZoneIndex) * curZoneOASchValue;
+                        ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerPerson)] =
+                            state.dataHeatBal->ZoneIntGain(ZoneNum).NOFOCC * multiplier * thisMechVentZone.ZoneOAPeopleRate;
                     } else {
-                        ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerPerson)] = curZone.TotOccupants * curZone.Multiplier *
-                                                                                                curZone.ListMultiplier *
-                                                                                                this->ZoneOAPeopleRate(ZoneIndex) * curZoneOASchValue;
-                        if (this->SystemOAMethod == DataSizing::SysOAMethod::ProportionalControlDesOcc) {
-                            // Accumulate CO2 generation from people at design occupancy and current activity level
-                            for (int PeopleNum = 1; PeopleNum <= state.dataHeatBal->TotPeople; ++PeopleNum) {
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:3802]: This was moved lower, but left unchanged for now.

File: src/EnergyPlus/MixedAir.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc:3886]: Will address this with #9969

**Review by mjwitte — COMMENTED** [review]
Selected developer comments

File: src/EnergyPlus/HVACStandAloneERV.cc [hunk 9]
```diff
@@ -874,8 +874,7 @@ void GetStandAloneERV(EnergyPlusData &state)
         auto &thisOAController = state.dataMixedAir->OAController(OutAirNum);
 
         thisOAController.Name = Alphas(1);
-        thisOAController.ControllerType = CurrentModuleObject;
-        thisOAController.ControllerType_Num = MixedAir::MixedAirControllerType::ControllerStandAloneERV;
+        thisOAController.ControllerType = MixedAir::MixedAirControllerType::ControllerStandAloneERV;
```
Comment (rraustad) [inline src/EnergyPlus/HVACStandAloneERV.cc:877]: Combine type and num into one variable.

File: src/EnergyPlus/MixedAir.cc [hunk 10]
```diff
@@ -140,6 +140,9 @@ using namespace FaultsManager;
 
 constexpr std::array<std::string_view, static_cast<int>(ControllerKind::Num)> ControllerKindNamesUC{"CONTROLLER:WATERCOIL", "CONTROLLER:OUTDOORAIR"};
 
+constexpr std::array<std::string_view, static_cast<int>(MixedAirControllerType::Num)> MixedAirControllerTypeNames{
+    "Controller:OutdoorAir", "ZoneHVAC:EnergyRecoveryVentilator:Controller"};
+
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:145]: and either is available with the new enum and type array

File: src/EnergyPlus/MixedAir.cc [hunk 11]
```diff
@@ -1398,36 +1401,22 @@ void GetOAControllerInputs(EnergyPlusData &state)
...
-            thisVentilationMechanical.ZoneADEffCooling.dimension(MechVentZoneCount, 1.0);
-            // Zone air distribution effectiveness in heating mode
-            thisVentilationMechanical.ZoneADEffHeating.dimension(MechVentZoneCount, 1.0);
-            // Indices to the zone air distribution effectiveness schedules
-            thisVentilationMechanical.ZoneADEffSchPtr.dimension(MechVentZoneCount, 0);
-            // Zone air secondary recirculation ratio, added 3/2012
-            thisVentilationMechanical.ZoneSecondaryRecirculation.dimension(MechVentZoneCount, 0.0);
-            thisVentilationMechanical.ZoneDesignSpecADObjName.allocate(MechVentZoneCount);
-            thisVentilationMechanical.ZoneDesignSpecADObjIndex.dimension(MechVentZoneCount, 0);
+            thisVentilationMechanical.VentMechZone.allocate(MechVentZoneCount);
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:1404]: move all these mech vent arrays to a new class

File: src/EnergyPlus/MixedAir.cc [hunk 12]
```diff
@@ -1398,36 +1401,22 @@ void GetOAControllerInputs(EnergyPlusData &state)
...
                 if (ZoneNum > 0) {
-                    if (any_eq(thisVentilationMechanical.VentMechZone, ZoneNum)) {
+                    bool found = false;
+                    for (auto &thisVMZone : thisVentilationMechanical.VentMechZone) {
+                        if (thisVMZone.zoneNum == ZoneNum) {
+                            found = true;
+                            break;
+                        }
+                    }
+                    if (found) {
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: CppCheck says this could be done with any_of but will address that when the time comes.

    [src/EnergyPlus/MixedAir.cc:1414]:(style),[useStlAlgorithm],Consider using std::any_of algorithm instead of a raw loop.

File: src/EnergyPlus/MixedAir.cc [hunk 13]
```diff
@@ -1439,44 +1428,38 @@ void GetOAControllerInputs(EnergyPlusData &state)
                     } else {
                         //          Store unique zone names
                         ++MechVentZoneCount;
-                        thisVentilationMechanical.VentMechZone(MechVentZoneCount) = ZoneNum;
-                        thisVentilationMechanical.VentMechZoneName(MechVentZoneCount) = state.dataHeatBal->Zone(ZoneNum).Name;
+                        auto &thisMechVentZone = thisVentilationMechanical.VentMechZone(MechVentZoneCount);
+                        thisMechVentZone.zoneNum = ZoneNum;
+                        thisMechVentZone.name = state.dataHeatBal->Zone(ZoneNum).Name;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:1428]: begin saving data into new struct

File: src/EnergyPlus/MixedAir.cc [hunk 14]
```diff
@@ -1771,39 +1756,38 @@ void GetOAControllerInputs(EnergyPlusData &state)
             "Name,DSZAD Name");
         print(state.files.eio, "{}\n", Format_700);
         for (int VentMechNum = 1; VentMechNum <= state.dataMixedAir->NumVentMechControllers; ++VentMechNum) {
-            print(state.files.eio,
-                  " Controller:MechanicalVentilation,{},{},",
-                  state.dataMixedAir->VentilationMechanical(VentMechNum).Name,
-                  state.dataMixedAir->VentilationMechanical(VentMechNum).SchName);
+            auto &thisVentilationMechanical(state.dataMixedAir->VentilationMechanical(VentMechNum));
+            print(state.files.eio, " Controller:MechanicalVentilation,{},{},", thisVentilationMechanical.Name, thisVentilationMechanical.SchName);
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:1750]: reference each mech vent object to report each parameter

File: src/EnergyPlus/MixedAir.cc [hunk 15]
```diff
@@ -2277,7 +2261,7 @@ void ProcessOAControllerInputs(EnergyPlusData &state,
             if (!AirNodeFound) {
                 ShowSevereError(state,
                                 format("Did not find Air Node (Zone with Humidistat), {} = \"{}\"",
-                                       state.dataMixedAir->OAController(OutAirNum).ControllerType,
+                                       MixedAirControllerTypeNames[static_cast<int>(state.dataMixedAir->OAController(OutAirNum).ControllerType)],
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:2254]: @Myoldmopar can comment on use of static_cast with this new enum and whether that's OK for use throughout code. Seems OK here.

File: src/EnergyPlus/MixedAir.cc [hunk 16]
```diff
@@ -2626,9 +2614,8 @@ void InitOAController(EnergyPlusData &state, int const OAControllerNum, bool con
     }
 
     if (state.dataGlobal->BeginEnvrnFlag && state.dataMixedAir->OAControllerMyEnvrnFlag(OAControllerNum)) {
-        Real64 RhoAirStdInit = state.dataEnvrn->StdRhoAir;
-        thisOAController.MinOAMassFlowRate = thisOAController.MinOA * RhoAirStdInit;
-        thisOAController.MaxOAMassFlowRate = thisOAController.MaxOA * RhoAirStdInit;
+        thisOAController.MinOAMassFlowRate = thisOAController.MinOA * state.dataEnvrn->StdRhoAir;
+        thisOAController.MaxOAMassFlowRate = thisOAController.MaxOA * state.dataEnvrn->StdRhoAir;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: I'm thinking the local was good but not exactly sure.

File: src/EnergyPlus/MixedAir.cc [hunk 17]
```diff
@@ -3329,19 +3301,17 @@ void OAControllerProps::CalcOAController(EnergyPlusData &state, int const AirLoo
...
 
     // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
-    Real64 OASignal;                // Outside air flow rate fraction (0.0 to 1.0)
-    bool AirLoopCyclingFan;         // Type of air loop fan (TRUE if Fan:OnOff)
-    bool HighHumidityOperationFlag; // TRUE if zone humidistat senses a high humidity condition
-    Real64 MixedAirTempAtMinOAFlow; // - mixed air temperature at min flow rate, used for custom economizer control calculation
-    Real64 SysSA(0.0);              // System supply air mass flow rate [kg/s]
+    Real64 OASignal = 0.0;                  // Outside air flow rate fraction (0.0 to 1.0)
+    bool AirLoopCyclingFan = false;         // Type of air loop fan (TRUE if Fan:OnOff)
+    bool HighHumidityOperationFlag = false; // TRUE if zone humidistat senses a high humidity condition
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3297]: some scope reduction scattered through here

File: src/EnergyPlus/MixedAir.cc [hunk 18]
```diff
@@ -3448,7 +3419,7 @@ void OAControllerProps::CalcOAController(EnergyPlusData &state, int const AirLoo
     }
     if (MechVentOutsideAirMinFrac > OutAirMinFrac) {
         OutAirMinFrac = MechVentOutsideAirMinFrac;
-        this->OALimitingFactor = limitFactorDCV;
+        this->OALimitingFactor = OALimitFactor::DCV;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3413]: another new enum

File: src/EnergyPlus/MixedAir.cc [hunk 19]
```diff
@@ -3634,12 +3604,11 @@ void OAControllerProps::CalcOAController(EnergyPlusData &state, int const AirLoo
...
     this->RelLatentLossRate = this->RelTotalLossRate - this->RelSensiLossRate;
+    this->OALimitingFactorReport = static_cast<int>(OALimitingFactor);
 }
 
-void VentilationMechanicalProps::CalcMechVentController(
-    EnergyPlusData &state,
-    Real64 &SysSA,             // System supply air mass flow rate [kg/s]
-    Real64 &MechVentOAMassFlow // outside air mass flow rate calculated by mechanical ventilation object [kg/s]
+Real64 VentilationMechanicalProps::CalcMechVentController(EnergyPlusData &state,
+                                                          Real64 SysSA // System supply air mass flow rate [kg/s]
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3602]: change to real function and pass back MechVentOAMassFlow parameter

File: src/EnergyPlus/MixedAir.cc (hunk 7 above)
Comment (rraustad) [reply src/EnergyPlus/MixedAir.cc:3611]: Understood

File: src/EnergyPlus/MixedAir.cc [hunk 20]
```diff
@@ -3660,42 +3630,45 @@ void VentilationMechanicalProps::CalcMechVentController(
...
             // IAQP for CO2 control
             for (int ZoneIndex = 1; ZoneIndex <= this->NumofVentMechZones; ++ZoneIndex) {
-                int ZoneNum = this->VentMechZone(ZoneIndex);
+                auto &thisMechVentZone = this->VentMechZone(ZoneIndex);
+                int ZoneNum = thisMechVentZone.zoneNum;
                 SysOAMassFlow += state.dataContaminantBalance->ZoneSysContDemand(ZoneNum).OutputRequiredToCO2SP *
-                                 GetCurrentScheduleValue(state, this->ZoneOASchPtr(ZoneIndex));
+                                 GetCurrentScheduleValue(state, thisMechVentZone.ZoneOASchPtr);
             }
             MechVentOAMassFlow = SysOAMassFlow;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3637]: Might? be able to substitute MechVentOAMassFlow for SysOAMassFlow but not sure at this point. Leave for now.

File: src/EnergyPlus/MixedAir.cc [hunk 21]
```diff
@@ -3660,42 +3630,45 @@ void VentilationMechanicalProps::CalcMechVentController(
...
             SysOAMassFlow = 0.0;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3657]: I see here both locals seem to be needed.

File: src/EnergyPlus/MixedAir.cc [hunk 22]
```diff
@@ -3706,46 +3679,50 @@ void VentilationMechanicalProps::CalcMechVentController(
...
-                    ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerZone)] +
-                    ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::ACH)];
-                ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::Max)] =
-                    max(ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerPerson)],
-                        ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerArea)],
-                        ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerZone)],
-                        ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::ACH)]);
+                ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerArea)] = curZone.FloorArea * thisMechVentZone.ZoneOAAreaRate;
+                ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::PerZone)] = thisMechVentZone.ZoneOAFlowRate;
+                ZoneOACalc[static_cast<int>(DataSizing::OAFlowCalcMethod::ACH)] = (thisMechVentZone.ZoneOAACHRate * curZone.Volume) / 3600.0;
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3691]: Here's what started it all, and a good move to where this is now.

File: src/EnergyPlus/MixedAir.cc [hunk 23]
```diff
@@ -4110,6 +4084,7 @@ void VentilationMechanicalProps::CalcMechVentController(
                     Real64 ZonePA = 0.0; // Zone primary air flow rate
                     Ep = 1.0;
                     if (ZoneEquipConfigNum > 0) {
+                        auto &curZoneEquipConfig(state.dataZoneEquip->ZoneEquipConfig(ZoneEquipConfigNum));
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: `auto &xxx =` is the new format

File: src/EnergyPlus/MixedAir.hh [hunk 24]
```diff
@@ -100,8 +100,6 @@ namespace MixedAir {
     enum class MixedAirControllerType
     {
         Invalid = -1,
-        None,
-        ControllerSimple,
         ControllerOutsideAir,
         ControllerStandAloneERV,
         Num,
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.hh:105]: And you don't need a water controller here.

File: src/EnergyPlus/MixedAir.hh [hunk 25]
```diff
@@ -264,6 +265,27 @@ namespace MixedAir {
...
+        Real64 ZoneADEffHeating = 1.0;           // Zone air distribution effectiveness in heating mode for each zone
+        int ZoneADEffSchPtr = 0;                 // Pointer to the zone air distribution effectiveness schedule for each zone
+        int ZoneDesignSpecADObjIndex = 0;        // index of the design specification zone air distribution object for each zone
+        std::string ZoneDesignSpecADObjName;     // name of the design specification zone air distribution object for each zone
+        Real64 ZoneSecondaryRecirculation = 0.0; // zone air secondary recirculation ratio for each zone
+        DataSizing::OAFlowCalcMethod ZoneOAFlowMethod = DataSizing::OAFlowCalcMethod::PerPerson; // OA flow method for each zone
+        int ZoneOASchPtr = 0;              // Index to the outdoor air schedule for each zone (from DesignSpecification:OutdoorAir or default)
+        Real64 OAPropCtlMinRateSchPtr = 0; // Outdoor design OA flow rate schedule from DesignSpecification:OutdoorAir
+    };
+
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.hh:288]: That's a lot of arrays changed to real.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 26]
```diff
@@ -6534,39 +6542,53 @@ void FillRemainingPredefinedEntries(EnergyPlusData &state)
...
                 if (time > 0) {
-                    avgFlow = state.dataSysRpts->SysPreDefRep(sysNum).MechVentTotAtLimitOcc[limitingFactorType] / (time * Constant::SecInHour);
+                    return state.dataSysRpts->SysPreDefRep(sysNum).MechVentTotAtLimitOcc[static_cast<int>(limitingFactorType)] /
+                           (time * Constant::SecInHour);
                 } else {
-                    avgFlow = 0.0;
+                    return 0.0;
                 }
-                return avgFlow;
             };
```
Comment (rraustad) [inline src/EnergyPlus/OutputReportTabular.cc:6553]: got rid of the lamda local

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 27]
```diff
@@ -5430,20 +5432,32 @@ TEST_F(EnergyPlusFixture, MechVentController_VRPNoCap)
...
         "    0.0003048006;            !- Outdoor Air Flow per Zone Floor Area {m3/s-m2}",
         "ZoneHVAC:AirDistributionUnit,",
-        "    Zone1TermReheat,         !- Name",
-        "    Zone 1 PIU Air Outlet Node,  !- Air Distribution Unit Outlet Node Name",
-        "    AirTerminal:SingleDuct:SeriesPIU:Reheat,  !- Air Terminal Object Type",
-        "    Zone 1 SPIU ATU;         !- Air Terminal Name",
+        "    Zone1ADU,                !- Name",
+        "    Zone 1 Air Supply Node,  !- Air Distribution Unit Outlet Node Name",
+        "    AirTerminal:SingleDuct:ConstantVolume:NoReheat,  !- Air Terminal Object Type",
+        "    Zone 1 CV ATU;           !- Air Terminal Name",
```
Comment (rraustad) [inline tst/EnergyPlus/unit/MixedAir.unit.cc:5438]: What prompted the change to the TU type?

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 28]
```diff
@@ -5486,32 +5500,95 @@ TEST_F(EnergyPlusFixture, MechVentController_VRPNoCap)
...
-    bool ErrorsFound(false);
+    Real64 OAMassFlow = 0.0; // OA mass flow rate [kg/s]
+    bool ErrorsFound = false;
 
     GetZoneData(*state, ErrorsFound);
     GetOARequirements(*state);
     GetZoneEquipment(*state);
     GetOAControllerInputs(*state);
+    ZoneAirLoopEquipmentManager::GetZoneAirLoopEquipment(*state);
+    SingleDuct::GetSysInput(*state);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/MixedAir.unit.cc:5511]: I see, so you could call single duct for both TUs.

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 29]
```diff
@@ -5486,32 +5500,95 @@ TEST_F(EnergyPlusFixture, MechVentController_VRPNoCap)
...
+    state->dataLoopNodes->Node(primaryInletNode1).MassFlowRate = SupplyMassFlow1;
+    state->dataLoopNodes->Node(primaryInletNode2).MassFlowRate = SupplyMassFlow2;
+    state->dataLoopNodes->Node(primaryOutletNode1).MassFlowRate = SupplyMassFlow1;
+    state->dataLoopNodes->Node(primaryOutletNode2).MassFlowRate = SupplyMassFlow2;
+    SysMassFlow = SupplyMassFlow1 + SupplyMassFlow2;                           // System supply mass flow rate [kg/s]
+    state->dataMixedAir->VentilationMechanical(1).SysDesOA = DesignOAMassFlow; // Set design outdoor air flow rate
+    OAMassFlow = state->dataMixedAir->VentilationMechanical(1).CalcMechVentController(*state, SysMassFlow);
+
+    EXPECT_TRUE(OAMassFlow > DesignOAMassFlow); // Expect that the system OA is greater than the design OA air flow
+    EXPECT_TRUE(OAMassFlow == SysMassFlow);     // Expect that the system OA is less than the system air flow
```
Comment (rraustad) [inline tst/EnergyPlus/unit/MixedAir.unit.cc]: Well, comment says OA is less than system flow, but they are equal. Copy-paste.

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 30]
```diff
@@ -5646,37 +5723,30 @@ TEST_F(EnergyPlusFixture, MechVentController_IAQPTests)
     GetOAControllerInputs(*state);
 
     // Case 1 - System OA method = IndoorAirQualityProcedure, SOAM_IAQP, controls to OutputRequiredToCO2SP
-    OAMassFlow = 0.0;
     EXPECT_EQ(SysOAMethod::IAQP, state->dataMixedAir->VentilationMechanical(1).SystemOAMethod);
-    state->dataMixedAir->VentilationMechanical(1).CalcMechVentController(*state, SysMassFlow, OAMassFlow);
+    OAMassFlow = state->dataMixedAir->VentilationMechanical(1).CalcMechVentController(*state, SysMassFlow);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/MixedAir.unit.cc:5728]: now OA flow is returned from the function

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 31]
```diff
@@ -5646,37 +5723,30 @@ TEST_F(EnergyPlusFixture, MechVentController_IAQPTests)
...
+    state->dataMixedAir->VentilationMechanical(1).VentMechZone(2).ZoneOASchPtr = 1;
 
-    OAMassFlow = 0.0;
     state->dataMixedAir->VentilationMechanical(1).SystemOAMethod = SysOAMethod::IAQPCOM;
-    state->dataMixedAir->VentilationMechanical(1).CalcMechVentController(*state, SysMassFlow, OAMassFlow);
+    OAMassFlow = state->dataMixedAir->VentilationMechanical(1).CalcMechVentController(*state, SysMassFlow);
     EXPECT_EQ(0.0, OAMassFlow);
-
-    state->dataContaminantBalance->ZoneSysContDemand.deallocate();
-    state->dataScheduleMgr->Schedule.deallocate();
```
Comment (rraustad) [inline tst/EnergyPlus/unit/MixedAir.unit.cc:5679]: clean up unnecessary deallocate at end of unit test

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 32]
```diff
@@ -5486,32 +5500,95 @@ TEST_F(EnergyPlusFixture, MechVentController_VRPNoCap)
...
+    EXPECT_TRUE(OAMassFlow < SysMassFlow);      // Expect that the system OA is less than the system air flow
+
+    // Starve one zone so that OAMassFlow = SysMassFlow
+    SupplyMassFlow1 = DesignOAMassFlow1 * 0.5;
+    SupplyMassFlow2 = DesignOAMassFlow2 / 0.2;
+    state->dataLoopNodes->Node(primaryInletNode1).MassFlowRate = SupplyMassFlow1;
+    state->dataLoopNodes->Node(primaryInletNode2).MassFlowRate = SupplyMassFlow2;
+    state->dataLoopNodes->Node(primaryOutletNode1).MassFlowRate = SupplyMassFlow1;
+    state->dataLoopNodes->Node(primaryOutletNode2).MassFlowRate = SupplyMassFlow2;
+    SysMassFlow = SupplyMassFlow1 + SupplyMassFlow2;                           // System supply mass flow rate [kg/s]
```
Comment (rraustad) [inline tst/EnergyPlus/unit/MixedAir.unit.cc:5587]: Not sure of the need for code duplication here, lines 5565-5572 and 5580-5585. I don't think those would have changed from previous test. You lost me on the "Starve one zone" comment

**Review by rraustad — APPROVED** [review]
Looks good.

**Comment by rraustad** [comment]
Only diff is SolarShading, with no warnings.

File: tst/EnergyPlus/unit/MixedAir.unit.cc (hunk 32 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/MixedAir.unit.cc:5587]: Oh, I see, before SupplyMassFlow1 was /0.5 and now it's *0.5. That makes sense. So the "1" vars changed.

File: src/EnergyPlus/MixedAir.cc (hunk 12 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc]: Done

File: src/EnergyPlus/MixedAir.cc (hunk 16 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc]: You're right, I mis-applied this rule from [wiki/Local-Shortcut-Variables](https://github.com/NREL/EnergyPlus/wiki/Local-Shortcut-Variables%3A-When-to-Use-a-Value-Copy-and-When-to-Use-a-Reference#the-rules)
"A local shortcut to a scalar should be a value copy unless you need to write into the scalar, in which case don't use a shortcut at all because it's confusing!"

I'll revert that.

File: tst/EnergyPlus/unit/MixedAir.unit.cc (hunk 28 above)
Comment (mjwitte) [reply tst/EnergyPlus/unit/MixedAir.unit.cc:5511]: > I see, so you could call single duct for both TUs.

And keep the connections simple, and not need a fan object, etc.

**Comment by rraustad** [comment]
It must be the any_of that caused these new diffs?

File: src/EnergyPlus/MixedAir.cc [hunk 33]
```diff
@@ -1471,15 +1466,9 @@ void GetOAControllerInputs(EnergyPlusData &state)
                     if (ZoneListNum > 0) {
                         for (int ScanZoneListNum = 1; ScanZoneListNum <= state.dataHeatBal->ZoneList(ZoneListNum).NumOfZones; ++ScanZoneListNum) {
                             // check to make sure zone name is unique (not listed more than once)...
-                            int ZoneNum = state.dataHeatBal->ZoneList(ZoneListNum).Zone(ScanZoneListNum);
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:1491]: So, I mistakenly deleted this line. How did it build, then? Is there another `ZoneNum` that's still in scope here?

Comment (rraustad) [reply src/EnergyPlus/MixedAir.cc:1491]: Wise choice to change the var name. Same name in the outer loop.

**Comment by rraustad** [comment]
@Myoldmopar this appears to be clean now so should be ready for merge soon.

**Comment by nrel-bot-2c** [comment]
@mjwitte it has been 8 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Wow, this is great!  I'll get on this one now

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Everything looks good locally, let's get this in.  Merging it now, thanks @mjwitte and @rraustad
