### PR TITLE
Correct Merkel cooling tower sizing crash and reporting issue for U-Factor Times Area at Free Convection

### LINKED ISSUE #6905: CoolingTower:VariableSpeed:Merkel fails sizing when Performance Input Method = UFactorTimesAreaAndDesignWaterFlowRate
Issue overview
--------------
User file for HelpDesk Ticket 12968 fails to size free convection regime tower UA because the Free Convection Nominal Capacity input is blank. This field should not be needed when Performance Input Method = UFactorTimesAreaAndDesignWaterFlowRate. The use of local variables to store specific input field data also leads to confusion for when one input field is autosized and others are not.

Example file CoolingTower_MerkelVariableSpeed has a similar issue where the tower nominal capacity is not reported when the tower is hard sized.

  CoolingTower:VariableSpeed:Merkel,
    TowerWaterSys CoolTower1,!- Name
    TowerWaterSys Pump-TowerWaterSys CoolTowerNode,  !- Water Inlet Node Name
    TowerWaterSys Supply Equipment Outlet Node,  !- Water Outlet Node Name
    NominalCapacity,         !- Performance Input Method
    1.25,                    !- Heat Rejection Capacity and Nominal Capacity Sizing Ratio
    1874400.0,                !- Nominal Capacity {W}

  CoolingTower:VariableSpeed:Merkel,
    TowerWaterSys CoolTower2,!- Name
    TowerWaterSys Pump-TowerWaterSys CoolTowerNode2,  !- Water Inlet Node Name
    TowerWaterSys Supply Equipment Outlet Node2,  !- Water Outlet Node Name
    NominalCapacity,         !- Performance Input Method
    1.25,                    !- Heat Rejection Capacity and Nominal Capacity Sizing Ratio
    autosize,                !- Nominal Capacity {W}

merkelsizing

[6905-Ticket 12968-CoolingTower_MerkelVariableSpeed_UseUAPerfInputMethod_V261.idf.txt](https://github.com/user-attachments/files/26382770/6905-Ticket.12968-CoolingTower_MerkelVariableSpeed_UseUAPerfInputMethod_V261.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (GitHub\EnergyPlusDevSupport\DefectFiles\6000s\6905)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------

- Fixes #6905

### Description of the purpose of this PR

The CoolingTower:VariableSpeed:Merkel was crashing when the tower Performance Input Method = UFactorTimesAreaAndDesignWaterFlowRate and also reporting a -99999.0 for U-Factor Times Area Value at Free Convection Air Flow Rate. These have been corrected.

[6905-Ticket 12968-CoolingTower_MerkelVariableSpeed_UseUAPerfInputMethod_V261.idf.txt](https://github.com/user-attachments/files/26384444/6905-Ticket.12968-CoolingTower_MerkelVariableSpeed_UseUAPerfInputMethod_V261.idf.txt)

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Sizing results now report U-Factor Times Area Value at Free Convection Air Flow Rate properly (i.e., no longer -99999.0):

{FB604BCC-E82B-4BBE-947F-66AEE18C02DB}

File: src/EnergyPlus/CondenserLoopTowers.cc [hunk 1]
```diff
@@ -4094,7 +4094,7 @@ namespace CondenserLoopTowers {
                         ShowSevereError(state, "Bad starting values for UA");
                         ShowFatalError(state, EnergyPlus::format("Autosizing of cooling tower UA failed for free convection tower {}", this->Name));
                     }
-                    this->LowSpeedTowerUA = UA;
+                    this->FreeConvTowerUA = UA;
```
Comment (rraustad) [inline src/EnergyPlus/CondenserLoopTowers.cc:4097]: LowSpeedTowerUA is used for 2-speed tower, FreeConvTowerUA is used for Merkel model.

File: src/EnergyPlus/CondenserLoopTowers.cc [hunk 2]
```diff
@@ -1497,7 +1497,7 @@ namespace CondenserLoopTowers {
                 tower.TowerNominalCapacityWasAutoSized = true;
             }
             tower.TowerFreeConvNomCap = NumArray(3);
-            if (tower.TowerFreeConvNomCap == DataSizing::AutoSize) {
+            if (s_ipsc->lNumericFieldBlanks(3) || tower.TowerFreeConvNomCap == DataSizing::AutoSize) {
                 tower.TowerFreeConvNomCapWasAutoSized = true;
```
Comment (rraustad) [inline src/EnergyPlus/CondenserLoopTowers.cc:1501]: Avoids the crash when using Performance Input Method = UFactorTimesAreaAndDesignWaterFlowRate and properly sizes tower free convection nominal capacity and shows up in html table shown in PR discussion.

**Review by mitchute — APPROVED** [review]
Thanks @rraustad. This look right.
