### PR TITLE
Address DOAS Zone Load Calculation Uses Incorrect Mass Flow Rate

### LINKED ISSUE #10028: DOAS Zone Load Calculation Uses Incorrect Mass Flow Rate
Issue overview
--------------
While working on Issue #9948 I found that volume flow rate is used instead of mass flow rate in the DOAS sensible, latent and total load outputs calculation [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneEquipmentManager.cc#L488-L506). The DOAS volume flow rate should have been multiplied by the appropriate air density.

Currently uses:
`DOASMassFlowRate = state.dataSize->CalcFinalZoneSizing(ControlledZoneNum).MinOA;`

It should have been multiplied air density as shown below:
`DOASMassFlowRate = state.dataSize->CalcFinalZoneSizing(ControlledZoneNum).MinOA * state.dataEnvrn->StdRhoAir;`

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, any)
 - Version of EnergyPlus (https://github.com/NREL/EnergyPlus/commit/30121d24747514e5cbeb8c1a6f502ec479c0da3c)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #10028 
 - This fix corrects the DOAS mass flow rate used in the calculation of the DOAS direct contribution to zone loads. Prior to the fix DOAS volume flow rate was used when it should have been the mass flow rate. 
 -  Diffs are expected with `Sizing:Zone` input field `Account for Dedicated Outdoor Air System` set to `Yes`.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 1]
```diff
@@ -485,7 +485,7 @@ void SizeZoneEquipment(EnergyPlusData &state)
             // set the DOAS mass flow rate and supply temperature and humidity ratio
             HR90H = PsyWFnTdbRhPb(state, calcZoneSizing.DOASHighSetpoint, 0.9, state.dataEnvrn->StdBaroPress);
             HR90L = PsyWFnTdbRhPb(state, calcZoneSizing.DOASLowSetpoint, 0.9, state.dataEnvrn->StdBaroPress);
-            DOASMassFlowRate = state.dataSize->CalcFinalZoneSizing(ControlledZoneNum).MinOA;
+            DOASMassFlowRate = state.dataSize->CalcFinalZoneSizing(ControlledZoneNum).MinOA * state.dataEnvrn->StdRhoAir;
```
Comment (Nigusse) [inline src/EnergyPlus/ZoneEquipmentManager.cc:487]: Added missing air density to convert the DOAS volume flow rate into mass flow rate.

File: tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc [hunk 2]
```diff
@@ -215,6 +215,7 @@ TEST_F(EnergyPlusFixture, DOASEffectOnZoneSizing_SizeZoneEquipment)
     state->dataSize->CalcZoneSizing(state->dataSize->CurOverallSimDay, 2).DOASHighSetpoint = 14.4;
     state->dataSize->CalcZoneSizing(state->dataSize->CurOverallSimDay, 2).DOASLowSetpoint = 12.2;
     state->dataEnvrn->StdBaroPress = 101325.;
+    state->dataEnvrn->StdRhoAir = 1.0;
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc:218]: Set air density to fix a failed unit test. The air density was set to 1.0 to avoid introducing additional diffs.

File: tst/EnergyPlus/unit/HeatRecovery.unit.cc [hunk 3]
```diff
@@ -3891,7 +3891,7 @@ TEST_F(EnergyPlusFixture, HeatRecoveryHXOnMainBranch_SimHeatRecoveryTest)
     ASSERT_NEAR(-17.300, state->dataHeatRecovery->ExchCond(1).SupInTemp, 0.001); // Heat Recovery Exchanger Primary Air Inlet Temp
     ASSERT_GT(state->dataHeatRecovery->ExchCond(1).SupOutTemp,
               state->dataHeatRecovery->ExchCond(1).SupInTemp);                  // Heat Recovery Exchanger is On in heating mode
-    ASSERT_NEAR(23.000, state->dataHeatRecovery->ExchCond(1).SecInTemp, 0.001); // Heat Recovery Exchanger Secondary Air Inlet Temp
+    ASSERT_NEAR(22.947, state->dataHeatRecovery->ExchCond(1).SecInTemp, 0.001); // Heat Recovery Exchanger Secondary Air Inlet Temp
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/HeatRecovery.unit.cc:3894]: The heat recovery HX secondary air outlet temperature changed due to changes in the primary air mass flow rate. Primary air mass flow rate increase will lead to a decrease in the secondary air HX exit temperature.

**Review by Nigusse — COMMENTED** [review]
Code change walk-through:
- corrected DOAS mass flow rate calculation
- modified unit tests failed due to OA mass flow rate change

**Comment by Nigusse** [comment]
Diffs are expected in input files with `Account for Dedicated Outdoor Air System` input field in `Sizing:zone` object set to `Yes`.  The following 15 regression test input files are expected to show diffs because of this fix. 

```
5ZoneAirCooledWithDOASAirLoop.idf
5ZoneAirCooledWithDOASAirLoop_ExhaustSystem.idf
5ZoneFanCoilDOASCool.idf
5ZoneFanCoilDOAS_ERVOnAirLoopMainBranch.idf
5ZoneFanCoilDOAS_HumidifierOnOASystem.idf
5ZoneSystemNodeReset.idf
DOAS_wNeutralSupplyAir_wFanCoilUnits.idf
DOAToFanCoilSupply.idf
DOAToPTAC.idf
DOAToPTAC_DrawReturnAir.idf
DOAToPTHP.idf
DOAToUnitVentilator.idf
DOAToUnitarySystem.idf
DOAToVRF.idf
DOAToWaterToAirHPSupply.idf
```

**Comment by Nigusse** [comment]
This fix impacts the zone sizing design loads and design mass flow rates, hence the impact cascades to the simulation results including `eio`, `eso`, `mtr` and tabular output files. Sample zone sizing results comparison between develop and this branch based on the defect file are shown below:

**Zone Sizing Heating:**
SizingZoneHeat

**Zone Sizing Cooling:**
SizingZoneCool

File: tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc (hunk 2 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc:218]: Got it.  This is a clever change to get the effect in there without breaking the unit test :)

**Review by Myoldmopar — APPROVED** [review]
Missing density seems fixed here, with accompanying unit tests in place.  I'll test it locally.

**Comment by Myoldmopar** [comment]
@Nigusse I thought this might be ready to go.  But during local testing, once I pulled in develop, a unit test is consistently failing.  I am wondering if one of the other recent changes in develop might necessitate a change in this branch.  I pushed up the merged branch and will wait on CI to confirm what I am seeing, and go from there.

**Comment by Myoldmopar** [comment]
OK, so CI is showing the same unit test failure as I was getting.  This is essentially good news :)

I'll take a quick look and see if I can resolve it.  I'm curious if it might have been the recent enum refactor.  There was one unit test in that branch that had to be updated because a variable was not properly initialized once converted to an enum.  (Maybe @dareumnam will know more about that since it was her PR)

**Comment by Myoldmopar** [comment]
OK, so actually this unit test failure is really just showing a change in a value that might be meaningful.  @Nigusse I saw you had to modify a couple unit tests to get them to pass with the changes here.  Do you think you could step in to the code and see why this unit test is now failing?

**Comment by Nigusse** [comment]
@Myoldmopar I just tested by removing density to ensure this is not caused by changes made elsewhere. You are right; the failure is caused by the density difference introduced in this fix that was not captured in the failed unit test. I will change the test values or set the density to 1.0 to avoid the differences.

**Comment by Myoldmopar** [comment]
Thanks @Nigusse !  I thought it might have something to do with it.  If you want to just set to to 1.0, that's fine with me, but either way is fine.

File: tst/EnergyPlus/unit/OutputReportTabular.unit.cc [hunk 4]
```diff
@@ -11650,7 +11650,7 @@ TEST_F(SQLiteFixture, DOASDirectToZone_ZoneMultiplierRemoved)
                                        "  AND RowName = 'DOAS Direct to Zone'");
     // check the value from result records
     Real64 return_val_sensible_instant = execAndReturnFirstDouble(query_sensible_instant);
-    EXPECT_EQ(return_val_sensible_instant, 517.05);
+    EXPECT_EQ(return_val_sensible_instant, 600.28);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/OutputReportTabular.unit.cc:11653]: Corrected the test values due to the introduction of missing standard air density in the DOAS load calculation.

File: tst/EnergyPlus/unit/OutputReportTabular.unit.cc [hunk 5]
```diff
@@ -11640,7 +11640,7 @@ TEST_F(SQLiteFixture, DOASDirectToZone_ZoneMultiplierRemoved)
                             "  AND RowName = 'DOAS Direct to Zone'");
     // check the value from result records
     Real64 return_val_total = execAndReturnFirstDouble(query_total);
-    EXPECT_EQ(return_val_total, 515.19);
+    EXPECT_EQ(return_val_total, 598.2);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/OutputReportTabular.unit.cc:11643]: The change is to account for standard air density in the DOAS load calculation. Example `515.19  * 1.161125 = 598.20`.

**Comment by Myoldmopar** [comment]
Thanks @Nigusse , it's happy again.  Merging this.
