### PR TITLE
Follow up fix for PR 9905 checkSubSurfAzTiltNorm()

### LINKED ISSUE #9893: Several potential issues in checkSubSurfAzTiltNorm()
Issue overview
--------------
Several issues found in the checkSubSurfAzThiltNorm():

Issue No. 1:
While examining some surface geometry related code lines, the following was spotted as a possible typo here:
https://github.com/NREL/EnergyPlus/blob/0c9cf289dbe7d3a146b6f91b3109d320d6fcb7e0/src/EnergyPlus/SurfaceGeometry.cc#L3044

The context is like this:
```
        Vectors::CompareTwoVectors(baseSurface.NewellSurfaceNormalVector, subSurface.NewellSurfaceNormalVector, sameSurfNormal, 0.001);
        if (sameSurfNormal) { // copy lcs vectors
            // Prior logic tested for azimuth difference < 30 and then skipped this - this caused large diffs in
            // CmplxGlz_MeasuredDeflectionAndShading Restoring that check here but will require further investigation (MJW Dec 2015)
            if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
                subSurface.lcsx = baseSurface.lcsx;
                subSurface.lcsy = baseSurface.lcsy;
                subSurface.lcsy = baseSurface.lcsy;
            }
```

The three lines is basically  assigning local coordinates axis vectors of the base surface to the subsurface, so it make sense that all `x`, `y`, and `z` coordinate vectors get assigned. Other wise the third line would just be redundant and can be removed.

A little bit further digging in the legacy vectors/surface processing code reveals that `.lcsz` vector of a surface is actually the surface's normal vector.

So this typo was probably not really causing a big problem, due to the condition of `sameSurfNormal` has to be true for these three lines to be executed. From the vector comparison above, the normal vectors should be very close (about a tolerance of `0.001`). So the missing `.lcsz` (basically the normal vector) assigning will probably still give very close results in most cases. But still, this typo should be fixed (or as a redundant line and gets removed).

Further, a minor issue No. 2 here: 
https://github.com/NREL/EnergyPlus/blob/c3360fbc6b67956065ab00dda8cdaf533d397c3c/src/EnergyPlus/SurfaceGeometry.cc#L1603-L1605

and also here:
https://github.com/NREL/EnergyPlus/blob/c3360fbc6b67956065ab00dda8cdaf533d397c3c/src/EnergyPlus/SurfaceGeometry.cc#L1782

These two place are little bit confusing in what the `Loop` variable really stands for (without looking for the comments and the code context). However, since there are already `enum` types and values defined for this, it would be much clearer to use the `enum` type to revise these two loops, such as:
```
for (const DataSurfaces::SurfaceClass Loop : state.dataSurfaceGeometry->BaseSurfIDs) {
```

Another issue No.3 here:
https://github.com/NREL/EnergyPlus/blob/0c9cf289dbe7d3a146b6f91b3109d320d6fcb7e0/src/EnergyPlus/SurfaceGeometry.cc#L3047-L3053

These should not be done. Actually, the angle it changed before and after are not the same angle, it will cause the surface orientation to be shifted (although small, < 0.02 degree). However, the changes are not necessary and these lines can be removed. I think the original intention might be to set the small angles close to the north to zero---in this case, it could be just set these two angles to zero instead to clear the small angle, rather than the expression to set it to a small angle even further from the original value. But anyway, removing these lines might be a better resolution in general.

And then Issue No.4 here:
https://github.com/NREL/EnergyPlus/blob/0c9cf289dbe7d3a146b6f91b3109d320d6fcb7e0/src/EnergyPlus/SurfaceGeometry.cc#L3037-L3045

For the `if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance)` condition, it should (will) never be true in this block, IF the Azimuth angles (see PR #9606) and the Azimuth angles difference (see Issue #9910) are both calculated correctly. This  because this block is under the condition that the parent `if (sameSurfNormal)` needs to be true. Given that `warningTolerance` is 30 degrees of angle, with a `sameSurfNormal` difference smaller than the tolerance of 0.001, the azimuth angle differences should never reached to that high to 30 degrees.

For here, if all the other logics were corrected (Azimuth angle calculation, Azimuth angles difference calculation), this block will not execute for sure. Or on the other hand, the block content can be set to always execute by removing the Azimuth angles comparison `if`, since the logic meaning of this block is to set the `lcsx`, `lcsy`, and `lcxz` to be the same if the `sameSurfNormal` is true (a much smaller tolerance of 0.001).

In addition, the `CmplxGlz_MeasuredDeflectionAndShading` mentioned in the comment note no longer exists after a couple of text search in throughout the entire code solution. So probably it would not cause more diffs that contributes to this function in this regard.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v23.1 pre-release, possibly been in older version for a while as well.
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - This is a follow up on original PR #9905 that tried to fix several issues in checkSubSurfAzTiltNorm(), originally described in Issue #9893. 
 - Fixes #9893 
 - The change was originally included in early versions of #9905, but was later reverted due to CI diffs
 - This commit is now singled out to analyze the diffs after other changes were merged into develop
 - The main argument here is that the `if` condition in the original code should be removed in the affected block.
 - Here are some explanations about why the affected code should be revised. Two potential issues with this `if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance)` block are as follows, which make it quite “illy” functioned for nearly all the surfaces:
1. For non-horizontal surfaces: The `warningTolerance` for the azimuth angles of the sub- and the base- surfaces is 30 degrees. When the code reached to the point of `if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance)`, the parent `if (sameSurfNormal)` needs to be true. However, this `sameSurfNormal` being `true` is a very tight condition---it actually requires that difference of the two azimuth angles (sub-surface’s and base-suface’s) to be no more than 0.001rad (or 0.057 degree). Therefore, the `>30` azimuth angle difference will never be achieved (for a pair of non-horizontal surface), and the content inside the `if` block will never be executed in this scenario. This is especially the case when the `std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance` should actually be replaced by a “rotational” angle difference instead.
2. For horizontal surfaces (or : This is the only exception is the scenario where at least one of the surfaces (either the sub-surface, or the base surface, or both) is (a) horizontal surface(s). In this scenario, it could be possible that: (I). `sameSurfNormal` is true; and at the same time (II) the azimuth angle difference between the sub-surface and the base-surface gets over 30 degrees. However, this behavior is very random behavior in EnergyPlus due to the “practical” way that the azimuth angle of a horizontal surface is finally computed (or taken). Theoretically, the Azimuth angle for a horizontal surface is kind of `arbitrary` mathematically. In EnergyPlus code, the azimuth angle of a horizontal surface is practically determined by the pointing direction of the first edge of the (horizontal) surface. Here is where the random behavior comes from: the azimuth angle will then be dependent on the direction of the first edge---this is very random and dependent on the order that the vertices are input. What’s more, the `random` behavior will also show up that for the same (horizontal) surface, if the same surface defined with a different starting vertex, the azimuth angle computed by (or finally chosen by) EnergyPlus will be a different value, since it will be dependent on the direction of the new first edge.

In summary, the problem may impact nearly all types of sub-surfaces that come with a base surface, such as normal windows or skylights.

A unit test is added to illustrate Point 2 (for horizontal surfaces) above about the potential random behavior on this block of code when a “same” surface is defined from a different vertex.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 23 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 12 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jcyuan2020 please advise on the status of this draft PR.  Looks like it was primarily just for investigative purposes to isolate one change and look at diffs.  If so, can you close the PR?  If not, feel free to keep working and let me know when it's ready for review.

**Comment by jcyuan2020** [comment]
> @jcyuan2020 please advise on the status of this draft PR. Looks like it was primarily just for investigative purposes to isolate one change and look at diffs. If so, can you close the PR? If not, feel free to keep working and let me know when it's ready for review.

I will continue a little bit more on this, by at least adding a couple of paragraphs to explain on why this change is needed, which is summarized as 1) for non-horizontal surfaces, this `if()` condition will never be true; 2) for horizontal surfaces, it will have a random behavior when checking the `if` criterion. I will also see if a unit test is needed to illustrate something.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 1]
```diff
@@ -3052,13 +3052,13 @@ namespace SurfaceGeometry {
         // Check if base surface and subsurface have the same normal
         Vectors::CompareTwoVectors(baseSurface.NewellSurfaceNormalVector, subSurface.NewellSurfaceNormalVector, sameSurfNormal, 0.001);
         if (sameSurfNormal) { // copy lcs vectors
-            // Prior logic tested for azimuth difference < 30 and then skipped this - this caused large diffs in
-            // CmplxGlz_MeasuredDeflectionAndShading Restoring that check here but will require further investigation (MJW Dec 2015)
-            if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
-                subSurface.lcsx = baseSurface.lcsx;
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc:3058]: The main change in this PR is the removal of this ` if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance)` condition, which originally would cause some issues with both the "non-horizontal" and "horizontal" sub-surfaces such as normal wall windows, or skylights. For "non-horizontal" surfaces, this `if()` condition will never be true so the block will not be executed; and 2) for "horizontal" surfaces, it will have a random behavior when checking the azimuth angle differences. See the descriptions in the top comment for more details.

Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:3058]: Interesting, and I get your point.  I am OK with removing this check based on all the investigation you've done, and the unit test.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 2]
```diff
@@ -11701,3 +11701,108 @@ TEST_F(EnergyPlusFixture, SurfaceGeometry_SurroundingSurfacesViewFactorTest)
...
+    // These should pass
+    EXPECT_FALSE(surfaceError);
+    EXPECT_FALSE(has_err_output());
+
+    // At least one of the following tests are expected to fail in the original develop branch without PR 10104 fix
+    // But with PR 10104 fix they should all pass
+    // The base and the sub surfaces now should be adjusted to be exactly the same
+    EXPECT_DOUBLE_EQ(BaseSurface.lcsz.z, SubSurface_Same.lcsz.z);
+    EXPECT_DOUBLE_EQ(BaseSurface.lcsz.y, SubSurface_Same.lcsz.y);
+    EXPECT_DOUBLE_EQ(BaseSurface.lcsz.x, SubSurface_Same.lcsz.x);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:11807]: This is a fantastic unit test, great stuff!

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Everything builds and runs fine here, let's get this in now.  Thanks @jcyuan2020, merging.
