### PR TITLE
Fixed NAN causing fatal error due to negative velocity in CrossVentilation RoomAirModel

### LINKED ISSUE #5520: NaN causing assertion failure in PsyRhovFnTdbWPb_fast
The user file stops at an assertion failure when running in develop because a NaN (shown in Windows as a -1.#IND000000000000) was passed to PsyRhovFnTdbWPb_fast. The file was provided by a user as an 8.1 file that crashed. Tested on Windows.
- [X] Defect file added see: EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5520
- [x] Ticket added to Pivotal for defect (development team task)
- [X] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addressed a NaN (crash on not a number) that was occurring in PsyRhovFnTdbWPb_fast to an expression in the EvolveParaUCSDCV() routine in CrossVentMgr.cc that was computing a log of a ratio of lengths that were outside of the range of the correlation. Addresses #5520.
- [x] Code style (parentheses padding, variable names)
- [x] Functional code review (it has to work!)
- [x] If defect, results of running current develop vs this branch should exhibit the fix
- [x] CI status: all green or justified
- [x] Performance: CI Linux results include performance check -- verify this
- [x] Unit Test(s)

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar or @mjwitte This one looks like it is ready to be reviewed and merged.

**Comment by nrel-bot-3** [comment]
@JasonGlazer @lgentile it has been 14 days since this pull request was last updated.

File: src/EnergyPlus/CrossVentMgr.cc [hunk 1]
```diff
@@ -569,11 +577,11 @@ namespace CrossVentMgr {
 
 		// Calculate the opening area for all apertures
 		for ( Ctd = 1; Ctd <= AirflowNetworkSurfaceUCSDCV( 0, ZoneNum ); ++Ctd ) {
-			CompNum = AirflowNetworkLinkageData( Ctd ).CompNum;
-			TypeNum = AirflowNetworkCompData( CompNum ).TypeNum;
-			if ( AirflowNetworkCompData( CompNum ).CompTypeNum == CompTypeNum_DOP ) {
+			EvolveParaUCSDCV_CompNum = AirflowNetworkLinkageData( Ctd ).CompNum;
```
Comment (mjwitte) [inline src/EnergyPlus/CrossVentMgr.cc]: @JasonGlazer If I'm following correctly, CompNum and TypeNum are only used inside this for loop.  So they could be declared within the loop and don't need to be in the anonymous namespace nor in clear_state

Comment (mjwitte) [inline src/EnergyPlus/CrossVentMgr.cc]: And TypeNum isn't even used anywhere - it can go away.  Or it should be set to .CompTypeNum and used in the ifs that follow.

File: src/EnergyPlus/CrossVentMgr.cc [hunk 2]
```diff
@@ -588,7 +596,7 @@ namespace CrossVentMgr {
 		// Droom the distance between the average point of the base surface of the airflow network Surface (if the base surface
 		// is a Window or Door it looks for the second base surface).
 		// Dstar is Droom corrected for wind angle
-		Wroom = Zone( ZoneNum ).Volume / Zone( ZoneNum ).FloorArea;
+		EvolveParaUCSDCV_Wroom = Zone( ZoneNum ).Volume / Zone( ZoneNum ).FloorArea;
```
Comment (mjwitte) [inline src/EnergyPlus/CrossVentMgr.cc]: Same for Wroom, Aroom, NodeNum1, and NodeNum2.  They are always set before they are used, so no need to put them in clear_state.

File: src/EnergyPlus/CrossVentMgr.cc [hunk 3]
```diff
@@ -1015,6 +1027,25 @@ namespace CrossVentMgr {
 
 	}
 
+	// Clears the global data in MixedAir.
+	// Needed for unit tests, should not be normally called.
+	void
+	clear_state()
+	{
+		HAT_J =  0.0 ;
```
Comment (mjwitte) [inline src/EnergyPlus/CrossVentMgr.cc:1029]: HAT_J, HA_J, HAT_R, and HA_R get reset at the beginning of every call to CrossVentMgr::HcUCSDCV so they don't need to be here.

File: src/EnergyPlus/CrossVentMgr.cc [hunk 4]
```diff
@@ -760,10 +768,14 @@ namespace CrossVentMgr {
 			}
 		for ( Ctd = 1; Ctd <= AirflowNetworkSurfaceUCSDCV( 0, ZoneNum ); ++Ctd ) {
 			if ( CVJetRecFlows( Ctd, ZoneNum ).Uin != 0 ) {
-				CVJetRecFlows( Ctd, ZoneNum ).Vjet = CVJetRecFlows( Ctd, ZoneNum ).Uin * std::sqrt( CVJetRecFlows( Ctd, ZoneNum ).Area ) * 6.3 * std::log( Dstar( ZoneNum ) / ( 6.0 * std::sqrt( CVJetRecFlows( Ctd, ZoneNum ).Area ) ) ) / Dstar( ZoneNum );
-				CVJetRecFlows( Ctd, ZoneNum ).Yjet = Cjet1 * std::sqrt( CVJetRecFlows( Ctd, ZoneNum ).Area / Aroom ) * CVJetRecFlows( Ctd, ZoneNum ).Vjet / CVJetRecFlows( Ctd, ZoneNum ).Uin + Cjet2;
-				CVJetRecFlows( Ctd, ZoneNum ).Yrec = Crec1 * std::sqrt( CVJetRecFlows( Ctd, ZoneNum ).Area / Aroom ) * CVJetRecFlows( Ctd, ZoneNum ).Vjet / CVJetRecFlows( Ctd, ZoneNum ).Uin + Crec2;
-				CVJetRecFlows( Ctd, ZoneNum ).YQrec = CrecFlow1 * std::sqrt( CVJetRecFlows( Ctd, ZoneNum ).Area * Aroom ) * CVJetRecFlows( Ctd, ZoneNum ).Vjet / CVJetRecFlows( Ctd, ZoneNum ).Uin + CrecFlow2;
+				Real64 dstarexp = Dstar( ZoneNum ) / ( 6.0 * std::sqrt( CVJetRecFlows( Ctd, ZoneNum ).Area ) );
+				if ( dstarexp < 1.0 ) {
```
Comment (mjwitte) [inline src/EnergyPlus/CrossVentMgr.cc]: @Myoldmopar Is there any difference in performance for this if block vs a max statement?  Or wrapping the line above with a max( . . . ., 1.0)?

File: src/EnergyPlus/CrossVentMgr.cc (hunk 3 above)
Comment (JasonGlazer) [inline src/EnergyPlus/CrossVentMgr.cc:1029]: HAT_J, HA_J, HAT_R and HA_R are also used in CalcUCSDCV() without being reset to zero so I don't think that it is safe to assume that they are reset always by HcUCSDCV()

File: src/EnergyPlus/CrossVentMgr.cc (hunk 4 above)
Comment (JasonGlazer) [inline src/EnergyPlus/CrossVentMgr.cc]: I believe the max() should be faster

File: src/EnergyPlus/CrossVentMgr.cc (hunk 3 above)
Comment (mjwitte) [inline src/EnergyPlus/CrossVentMgr.cc:1029]: OK, I missed that some of them were in a different function.

**Comment by JasonGlazer** [comment]
@mjwitte The check in to fix the issues you spotted results in clean CI output.

**Comment by mjwitte** [comment]
@JasonGlazer Fixed some space padding.  Tested the fix and it works (no fatal error with NANs), but DataUCSDSharedData needs a clear_state to deallocate everything in it.

**Comment by JasonGlazer** [comment]
The CI test that is failing is EnergyPlusFixture.SiteGroundDomainBasement_CheckInputs_BadHorizInsMaterial but that unit test runs fine when I run it locally. I am going to merge develop and see if it goes through the CI clean.
