### PR TITLE
AirLoopHVAC:DedicatedOutdoorAirSystem does not size correctly when multiple DOAS systems are simulated

### LINKED ISSUE #9325: For multiple AirLoopHVAC:DedicatedOutdoorAirSystem, only the first finds weather information used for sizing.
Issue overview
--------------

In module AirloopHVACDOAS the member function GetDesignDayConditions finds the outdoor weather for component sizing. However, there are global flags, state.dataAirLoopHVACDOAS->SummerDesignDayFlag = false; and state.dataAirLoopHVACDOAS->WinterDesignDayFlag = false;, that are set the first time through and subsequent calls to this function does not find the weather conditions for other AirLoopHVAC:DedicatedOutdoorAirSystem systems.

In function CoolingWaterDesAirInletTempSizer, and others like it, this line works for the first outdoor air system but returns -999 for subsequent outdoor air systems.

    } else if (this->curSysNum > 0) {
        if (!this->wasAutoSized && !this->sizingDesRunThisAirSys) {
            this->autoSizedValue = _originalValue;
        } else {
            if (this->curOASysNum > 0) { // coil is in OA stream
                if (this->outsideAirSys(this->curOASysNum).AirLoopDOASNum > -1) {
           -->   this->autoSizedValue = this->airloopDOAS[this->outsideAirSys(this->curOASysNum).AirLoopDOASNum].SizingCoolOATemp;

This causes coil sizing to fail.

    ** Severe  ** SizeWaterCoil Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL, Developer Error: Component sizing incomplete.
    **   ~~~   ** SizingString = Design Inlet Air Temperature [C], SizingResult = -99998.9
    ** Severe  ** Developer Error: sizing of Design Inlet Air Temperature [C] failed.
    **   ~~~   ** Occurs in Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL
    ** Severe  ** SizeWaterCoil Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL, Developer Error: Component sizing incomplete.
    **   ~~~   ** SizingString = Design Inlet Air Humidity Ratio [kgWater/kgDryAir], SizingResult = -99998.9
    ** Severe  ** Developer Error: sizing of Design Inlet Air Humidity Ratio [kgWater/kgDryAir] failed.
    **   ~~~   ** Occurs in Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL
    ** Warning ** SizeWaterCoil: Coil="PAU_TOWER12_OFFICE_1 COOLING COIL", Cooling Coil has leaving humidity ratio > entering humidity ratio.
    **   ~~~   **     Wair,in =  -999.000000 [kgWater/kgDryAir]
    **   ~~~   **     Wair,out = 1.200000E-002 [kgWater/kgDryAir]
    **   ~~~   ** ....coil leaving humidity ratio will be reset to:
    **   ~~~   **     Wair,out = -999.000000 [kgWater/kgDryAir]

https://unmethours.com/question/70556/fansystemmodel-power-curve-does-not-work/

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (
[UnmetHours_20220304.idf.txt](https://github.com/NREL/EnergyPlus/files/8233097/UnmetHours_20220304.idf.txt)
)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9325
 - AirLoopHVAC:DedicatedOutdoorAirSystem was selecting the first design day condition instead of the max design day condition. Also, only the first AirLoopHVAC:DedicatedOutdoorAirSystem object would find design conditions used for siziing.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

**Comment by rraustad** [comment]
@Myoldmopar this should get in for next release, and is ready for review and merge.

**Comment by rraustad** [comment]
Running defect file in develop and this branch to save reviewer some time, this file takes a long time. The 3 DOAS systems are:

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      PAU_Tower12_Office_1,    !- Name

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      PAU_Tower12_Office_2,    !- Name

    AirLoopHVAC:DedicatedOutdoorAirSystem,
      PAU_Tower3_Office,       !- Name

Defect file in develop fatals out and reports partial sizing results. First water coils sizes fine, second fails.

    ** Severe  ** SizeWaterCoil Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL, Developer Error: Component sizing incomplete.
    **   ~~~   ** SizingString = Design Inlet Air Temperature [C], SizingResult = -99998.9
    ** Severe  ** Developer Error: sizing of Design Inlet Air Temperature [C] failed.
    **   ~~~   ** Occurs in Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL
    ** Severe  ** SizeWaterCoil Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL, Developer Error: Component sizing incomplete.
    **   ~~~   ** SizingString = Design Inlet Air Humidity Ratio [kgWater/kgDryAir], SizingResult = -99998.9
    ** Severe  ** Developer Error: sizing of Design Inlet Air Humidity Ratio [kgWater/kgDryAir] failed.
    **   ~~~   ** Occurs in Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL
    ** Warning ** SizeWaterCoil: Coil="PAU_TOWER12_OFFICE_1 COOLING COIL", Cooling Coil has leaving humidity ratio > entering humidity ratio.
    **   ~~~   **     Wair,in =  -999.000000 [kgWater/kgDryAir]
    **   ~~~   **     Wair,out = 1.200000E-002 [kgWater/kgDryAir]
    **   ~~~   ** ....coil leaving humidity ratio will be reset to:
    **   ~~~   **     Wair,out = -999.000000 [kgWater/kgDryAir]
    ** Severe  ** SizeWaterCoil Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL, Developer Error: Component sizing incomplete.
    **   ~~~   ** SizingString = Design Outlet Air Humidity Ratio [kgWater/kgDryAir], SizingResult = -99998.9
    ** Severe  ** Developer Error: sizing of Design Outlet Air Humidity Ratio [kgWater/kgDryAir] failed.
    **   ~~~   ** Occurs in Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL
    ** Severe  ** SizeWaterCoil Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL, Developer Error: Component sizing incomplete.
    **   ~~~   ** SizingString = Design Coil Load [W], SizingResult = -99998.9
    ** Severe  ** Developer Error: sizing of Design Coil Load [W] failed.
    **   ~~~   ** Occurs in Coil:Cooling:Water PAU_TOWER12_OFFICE_1 COOLING COIL
    **  Fatal  ** Preceding water coil sizing errors cause program termination

    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Inlet Air Temperature [C], 33.80000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.00000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Outlet Air Temperature [C], 17.50000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Inlet Air Humidity Ratio [kgWater/kgDryAir], 1.89191E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Outlet Air Humidity Ratio [kgWater/kgDryAir], 1.20000E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Coil Load [W], 5694944.15097
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Water Flow Rate [m3/s], 0.54270
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Air Flow Rate [m3/s], 138.20214
    Water Cooling Coil Capacity Information,Coil:Cooling:Water,PAU_TOWER3_OFFICE COOLING COIL,3380049.12,2241619.25,1138429.87,0.66,228683.93,2319.44

    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.00000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Outlet Air Temperature [C], 17.50000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Water Flow Rate [m3/s], 0.00000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Air Flow Rate [m3/s], 69.59639
    ! <Zone Surfaces>,Zone Name,# Surfaces

[9327-Develop.zip](https://github.com/NREL/EnergyPlus/files/8238780/9327-Develop.zip)

Defect file in this branch runs to completion and sizes all 3 coils.

    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Inlet Air Temperature [C], 33.80000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.00000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Outlet Air Temperature [C], 17.50000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Inlet Air Humidity Ratio [kgWater/kgDryAir], 1.89191E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Outlet Air Humidity Ratio [kgWater/kgDryAir], 1.20000E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Coil Load [W], 5694944.15097
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Water Flow Rate [m3/s], 0.54270
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER3_OFFICE COOLING COIL, Design Size Design Air Flow Rate [m3/s], 138.20214
    Water Cooling Coil Capacity Information,Coil:Cooling:Water,PAU_TOWER3_OFFICE COOLING COIL,3380049.12,2241619.25,1138429.87,0.66,228683.93,2319.44
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Inlet Air Temperature [C], 33.80000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.00000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Outlet Air Temperature [C], 17.50000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Inlet Air Humidity Ratio [kgWater/kgDryAir], 1.89191E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Outlet Air Humidity Ratio [kgWater/kgDryAir], 1.20000E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Coil Load [W], 2867882.90020
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Water Flow Rate [m3/s], 0.27329
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_1 COOLING COIL, Design Size Design Air Flow Rate [m3/s], 69.59639
    Water Cooling Coil Capacity Information,Coil:Cooling:Water,PAU_TOWER12_OFFICE_1 COOLING COIL,1702138.74,1128843.65,573295.09,0.66,115161.57,1168.03
    Component Sizing Information, Fan:SystemModel, PAU_TOWER12_OFFICE_1 SUPPLY FAN, User-Specified Design Maximum Air Flow Rate [m3/s], 69.59639
    Component Sizing Information, Fan:SystemModel, PAU_TOWER12_OFFICE_1 SUPPLY FAN, Design Electric Power Consumption [W], 119308.09507
    Component Sizing Information, Controller:WaterCoil, PAU_TOWER12_OFFICE_1 COOLING COIL CONTROLLER, Maximum Actuated Flow [m3/s], 0.27329
    Component Sizing Information, Controller:WaterCoil, PAU_TOWER12_OFFICE_1 COOLING COIL CONTROLLER, Controller Convergence Tolerance, 1.74241E-006
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Inlet Air Temperature [C], 33.80000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.00000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Outlet Air Temperature [C], 17.50000
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Inlet Air Humidity Ratio [kgWater/kgDryAir], 1.89191E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Outlet Air Humidity Ratio [kgWater/kgDryAir], 1.20000E-002
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Coil Load [W], 10240023.89426
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Water Flow Rate [m3/s], 0.97582
    Component Sizing Information, Coil:Cooling:Water, PAU_TOWER12_OFFICE_2 COOLING COIL, Design Size Design Air Flow Rate [m3/s], 248.49992
    Water Cooling Coil Capacity Information,Coil:Cooling:Water,PAU_TOWER12_OFFICE_2 COOLING COIL,6077633.57,4030633.86,2046999.71,0.66,411194.36,4170.56

[9327-ThisBranch.zip](https://github.com/NREL/EnergyPlus/files/8238789/9327-ThisBranch.zip)

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -1023,33 +1023,36 @@ namespace AirLoopHVACDOAS {
...
-                if (state.dataWeatherManager->DesDayInput(i).HumIndType == WeatherManager::DDHumIndType::WetBulb) { // wet bulb temperature
-                    this->SizingCoolOAHumRat = Psychrometrics::PsyWFnTdbTwbPb(
-                        state, this->SizingCoolOATemp, state.dataWeatherManager->DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (state.dataWeatherManager->DesDayInput(i).HumIndType == WeatherManager::DDHumIndType::DewPoint) { // dewpoint
-                    this->SizingCoolOAHumRat = Psychrometrics::PsyWFnTdpPb(
-                        state, state.dataWeatherManager->DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (state.dataWeatherManager->DesDayInput(i).HumIndType == WeatherManager::DDHumIndType::HumRatio) {
-                    this->SizingCoolOAHumRat = state.dataWeatherManager->DesDayInput(i).HumIndValue;
-                } // else { // What about other cases?
-                state.dataAirLoopHVACDOAS->SummerDesignDayFlag = false;
```
Comment (rraustad) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:1038]: This flag here, state.dataAirLoopHVACDOAS->SummerDesignDayFlag, and same for winter design day, found first design day object data and then disregarded the rest (because this global flag is included in the IF conditional test). If there were any other DOAS systems the design conditions could not be found/initialized.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 2]
```diff
@@ -1023,33 +1023,36 @@ namespace AirLoopHVACDOAS {
...
+            if (desDayInput.DayType == summerDesignDayTypeIndex) {
+                // keep design day humiditiy ratio from the same peak temperature design day (i.e., don't use a humrat from a different day)
+                if (desDayInput.MaxDryBulb > this->SizingCoolOATemp) {
```
Comment (rraustad) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:1030]: The new methodology is to search through all design days and select the peak condition and save both T and w to use for sizing. Because this function is only called once for sizing there is no need for the Summer/WinterDesignDayFlag. Also, T and w are always from the same design day, using the peak outdoor T as the indicator of peak and then saving w at the same time (i.e., T and w are not evaluated seperately).

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 3]
```diff
@@ -4304,4 +4305,161 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestOACompOutletNodeIndex)
     EXPECT_EQ(state->dataAirLoop->OutsideAirSys(1).OutletNodeNum(2), 23);
 }
 
+TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestGetDesignDayConditions)
```
Comment (rraustad) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:4308]: Unit test provides 100% coverage of GetDesignDayConditions member function and also tests 2 DOAS systems to make sure 2nd finds sizing data.

File: src/EnergyPlus/AirLoopHVACDOAS.hh [hunk 4]
```diff
@@ -174,7 +174,7 @@ namespace AirLoopHVACDOAS {
         // default constructor
         AirLoopDOAS() // constructor
             : SumMassFlowRate(0.0), PreheatTemp(-999.0), PrecoolTemp(-999.0), PreheatHumRat(-999.0), PrecoolHumRat(-999.0), SizingMassFlow(0.0),
-              SizingCoolOATemp(-999.0), SizingCoolOAHumRat(-999.0), HeatOutTemp(0.0), HeatOutHumRat(0.0), m_AirLoopDOASNum(0), m_OASystemNum(0),
+              SizingCoolOATemp(-999.0), SizingCoolOAHumRat(-999.0), HeatOutTemp(999.0), HeatOutHumRat(999.0), m_AirLoopDOASNum(0), m_OASystemNum(0),
```
Comment (rraustad) [inline src/EnergyPlus/AirLoopHVACDOAS.hh:177]: Since looking for max T for cooling and min T for heating, the heating initialization was changed to allow comparison to outdoor T (i.e., if OAT > SizingCoolOATemp then save cooling OA T and w, and if OAT < HeatOutTemp then save heating OA T and w).

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 5]
```diff
@@ -4338,6 +4337,21 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestGetDesignDayConditions)
     EXPECT_NEAR(thisDOAS.HeatOutTemp, state->dataWeatherManager->DesDayInput(4).MaxDryBulb, 0.000001);
     EXPECT_NEAR(thisDOAS.HeatOutHumRat, state->dataWeatherManager->DesDayInput(4).HumIndValue, 0.000001);
 
+    AirLoopHVACDOAS::AirLoopDOAS anotherDOAS;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:4342]: @Myoldmopar here's a question for unit tests, do these two instances (thisDOAS and anotherDOAS) need to be deleted at the end of the unit test?

**Comment by rraustad** [comment]
Here is a final thought on finding sizing data. This function loops through what I think are only design day objects. What if the user chooses to use the weather file as the design data? What if the user selected SizingPeriod:WeatherFileDays (state.dataWeatherManager->RunPeriodDesignInput) and did not use the design day objects? is that allowed? If this function needs to be expanded to include other choices of sizing data then a new issue should be opened.

    for (size_t i = 1; i <= state.dataWeatherManager->DesDayInput.size(); i++) {

**Comment by rraustad** [comment]
I believe I have a solution when using SizingPeriod:WeatherFileDays but will wait on this to merge since I expect there will be discussion of the best method to use for this new use case.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 6]
```diff
@@ -1023,33 +1023,36 @@ namespace AirLoopHVACDOAS {
...
-                    this->SizingCoolOAHumRat = Psychrometrics::PsyWFnTdbTwbPb(
-                        state, this->SizingCoolOATemp, state.dataWeatherManager->DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (state.dataWeatherManager->DesDayInput(i).HumIndType == WeatherManager::DDHumIndType::DewPoint) { // dewpoint
-                    this->SizingCoolOAHumRat = Psychrometrics::PsyWFnTdpPb(
-                        state, state.dataWeatherManager->DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (state.dataWeatherManager->DesDayInput(i).HumIndType == WeatherManager::DDHumIndType::HumRatio) {
-                    this->SizingCoolOAHumRat = state.dataWeatherManager->DesDayInput(i).HumIndValue;
-                } // else { // What about other cases?
-                state.dataAirLoopHVACDOAS->SummerDesignDayFlag = false;
+            if (desDayInput.DayType == summerDesignDayTypeIndex) {
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:1028]: I'm not a fan of relying on the design day type index (can just take the make of all design days for cooling and the min ODB of all design days for heating), nor of pulling from design day inputs, but that was the method before, so it can stand for this round.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 7]
```diff
@@ -1023,33 +1023,36 @@ namespace AirLoopHVACDOAS {
...
-                    this->HeatOutHumRat = Psychrometrics::PsyWFnTdpPb(
-                        state, state.dataWeatherManager->DesDayInput(i).HumIndValue, DataEnvironment::StdPressureSeaLevel);
-                } else if (state.dataWeatherManager->DesDayInput(i).HumIndType == WeatherManager::DDHumIndType::HumRatio) {
-                    this->HeatOutHumRat = state.dataWeatherManager->DesDayInput(i).HumIndValue;
-                } // else { // What about other cases?
-                state.dataAirLoopHVACDOAS->WinterDesignDayFlag = false;
+            if (desDayInput.DayType == winterDesignDayTypeIndex) {
+                // keep design day humiditiy ratio from the same peak temperature design day (i.e., don't use a humrat from a different day)
+                if (desDayInput.MaxDryBulb < this->HeatOutTemp) {
+                    this->HeatOutTemp = desDayInput.MaxDryBulb;
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc]: Should be `desDayInput.MaxDrybulb - desDayInput.DailyDBRange` in both lines.

File: src/EnergyPlus/AirLoopHVACDOAS.hh (hunk 4 above)
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.hh:177]: If per chance there are no design days, or no summer or no winter days, is there a check to quit or do something reasonable if one of these is still -999 or 999?

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 8]
```diff
@@ -4304,4 +4305,161 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestOACompOutletNodeIndex)
...
+
+    // test peak conditions used for sizing
+    thisDOAS.GetDesignDayConditions(*state);
+
+    EXPECT_NEAR(thisDOAS.SizingCoolOATemp, state->dataWeatherManager->DesDayInput(2).MaxDryBulb, 0.000001);
+    EXPECT_NEAR(thisDOAS.SizingCoolOAHumRat, state->dataWeatherManager->DesDayInput(2).HumIndValue, 0.000001);
+    EXPECT_NEAR(thisDOAS.HeatOutTemp, state->dataWeatherManager->DesDayInput(4).MaxDryBulb, 0.000001);
+    EXPECT_NEAR(thisDOAS.HeatOutHumRat, state->dataWeatherManager->DesDayInput(4).HumIndValue, 0.000001);
+
+    AirLoopHVACDOAS::AirLoopDOAS anotherDOAS;
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:4342]: This is local to the unit test, so it will be destroyed when the text exits (said the reviewer who really doesn't know for sure, but thinks this is true).

**Review by mjwitte — COMMENTED** [review]
@rraustad This looks good for the most part. I'm running the defect file in a debug build to make sure the coil sizing works (it's been running for hours, but it's on the last design day now).

A couple of minor comments and one critical one.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 6 above)
Comment (rraustad) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:1028]: All these review comments are valid. When making these changes I realized that SizingPeriod:WeatherFileDays were not included here and (after making these changes) created new variables to be set during the pass through the sizing periods during sizing. That works good but is very different from what is done here so I figured to get this fixed for the next release and post the new changes for further discussion. Since all sizing days are processed through the weather manager I figured I could capture the data there and not have to process raw SizingPeriod inputs. This of course could probably be improved so I was not able to get this ready by the next release.

        if (state.dataGlobal->CurrentTime == state.dataGlobal->TimeStepZone &&
                (state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).KindOfEnvrn ==
                    DataGlobalConstants::KindOfSim::RunPeriodDesign ||
            state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).KindOfEnvrn == DataGlobalConstants::KindOfSim::DesignDay)) {
            for (int i = 0; i < state.dataWeatherManager->TodayOutDryBulbTemp.size(); ++i) {
                if (state.dataWeatherManager->TodayOutDryBulbTemp[i] >
                    state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).maxCoolingOAT) {
                    state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).maxCoolingOAT =
                        state.dataWeatherManager->TodayOutDryBulbTemp[i];
                    state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).maxCoolingOADP =
                        state.dataWeatherManager->TodayOutDewPointTemp[i];
                }
                if (state.dataWeatherManager->TodayOutDryBulbTemp[i] <
                    state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).minHeatingOAT) {
                    state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).minHeatingOAT =
                        state.dataWeatherManager->TodayOutDryBulbTemp[i];
                    state.dataWeatherManager->Environment(state.dataWeatherManager->Envrn).minHeatingOADP =
                        state.dataWeatherManager->TodayOutDewPointTemp[i];
                }
            }
        }

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 7 above)
Comment (rraustad) [reply src/EnergyPlus/AirLoopHVACDOAS.cc]: I think I'll make this change now since it is the correct math, and will cause diffs but that is expected.

File: src/EnergyPlus/AirLoopHVACDOAS.hh (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/AirLoopHVACDOAS.hh:177]: No checks in this design, next round will improve on this.

**Comment by rraustad** [comment]
OK, no diffs then. SmallOffice_CentralDOAS.idf has no temp range in the heating DesignDay:

  SizingPeriod:DesignDay,
    CHICAGO Ann Htg 99.6% Condns DB,  !- Name
    1,                       !- Month
    21,                      !- Day of Month
    WinterDesignDay,         !- Day Type
    -20.6,                   !- Maximum Dry-Bulb Temperature {C}
    0.0,                     !- Daily Dry-Bulb Temperature Range {deltaC}

**Review by mjwitte — APPROVED** [review]
@rraustad Thanks for the fix (even if most winter design days have zero range). This is ready to drop in.
