### PR TITLE
Eliminate Input Order Dependency in AirflowNetwork Linkage Objects

### LINKED ISSUE #10652: Order-dependent input - AirflowNetwork:Distribution:Linkage
Issue overview
--------------
When there are multiple AirflowNetwork:Distribution:Linkage objects, they seem to be order-dependent in the input file. I get a fatal error when they are not entered in the correct order. This would conflict with "no order is needed in the input data file! Data that is not needed by a particular simulation is not processed." (Input/Output Reference, section 1.1.1)

Error message:
image

Input file with AirflowNetwork:Distribution:Linkage objects in wrong order: [US+SF+CZ5A+elecres+crawlspace+IECC_2021-Err.zip](https://github.com/user-attachments/files/16566277/US%2BSF%2BCZ5A%2Belecres%2Bcrawlspace%2BIECC_2021-Err.zip)

File with correct order: [US+SF+CZ5A+elecres+crawlspace+IECC_2021.zip](https://github.com/user-attachments/files/16566262/US%2BSF%2BCZ5A%2Belecres%2Bcrawlspace%2BIECC_2021.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) - Windows 11
 - Version of EnergyPlus (if using an intermediate build, include SHA) - 9.5 and 24.1
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------

- Fixes #10652

### Description of the purpose of this PR

A user noted that an error message was being produced by EnergyPlus that indicated that some of the input for AirFlowNetwork inputs were not in the correct order.  EnergyPlus has always functioned within the concept of the input can be in any order.  So, this violated that principle.  While there is an internal requirement within AFN that the first encountered Linkage object has a node that is connected to actual E+ HVAC equipment, this can be accommodated without enforcing that the input be in a particular order.  This solution fixes the problem by searching throughout the data that has been read from input (now using JSON directly) until it finds an AirLoopNum that pertains to the air flow network.  In testing, very tiny differences were noted in some sizing results.  A unit test verifies the fix and several existing unit tests that used hard-wired indices for making comparisons were adjusted since the input is read in a slightly different order now.

### Pull Request Author

 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 1]
```diff
@@ -12289,6 +12294,74 @@ namespace AirflowNetwork {
...
+                shiftResult = linkageNum;
+                break;
+            }
+            if (!lAlphaBlanks(5)) { // There might be a valid zone here which will also make this a "first" linkage in the input
+                shiftResult = linkageNum;
+                break;
+            }
+        }
+        return shiftResult;
+    }
```
Comment (rraustad) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:12459]: This just looks like it's finding the first AirflowNetwork:Distribution:Linkage that matches one of the AirflowNetwork:Distribution:Node objects and then reading the AirflowNetwork:Distribution:Linkage objects in order. I don't know how that aligns these objects in some manner or how this works for other random orders of AirflowNetwork:Distribution:Linkage objects so I can't comment more. I would ask that @jasondegraw look at this.

**Review by jasondegraw — CHANGES_REQUESTED** [review]
The issue does appear to be legitimate, and this PR does appear to fix the issue, but it's adding additional array-based input processing. I hate to be "that guy", but this really needs to be done with the JSON-based input processing, otherwise it'll have to be redone later.

**Comment by RKStrand** [comment]
@jasondegraw I have a question regarding your comment about this needing to be done in JSON as well.  Now, I'll be the first to admit that I'm not 100% up to speed on JSON yet, so if this question is dumb, at least you'll know why.  Since this fix does not alter in any way reading the data from JSON or the IDF but simply looks at what was contained in the input file, how will the input file format matter?  Isn't the get object routine simply going to one or the other but the data inside E+ is the same?  Otherwise, wouldn't every object have two different paths?  So, if this fix is simply looking at what has already been read in and then simply choosing to process the already read data into local arrays in a slightly different order, what does it matter whether the data came from a JSON file or an IDF?  I understand the concept of not wanting to have to come back and redo this later, but given what I am proposing to do here, I don't comprehend why this would need to be redone later.  Of course, I might not understand something about what JSON is doing.  Thanks for your feedback.

**Comment by Myoldmopar** [comment]
It's a valid request from @jasondegraw and a fine response from @RKStrand .  I'll try to clarify a bit.  

Right now, EnergyPlus accepts input files in traditional IDF, or JSON (or some binary formats as well).  Once inside EnergyPlus, the data is actually processed into a JSON-like object for any processing.  Right now input processing routines can either:
 - Read directly off the internal JSON-style key-value representation.  You can see various examples of this around the code, and it looks like this: 
 
```c++
    this->soil.k = j["soil_thermal_conductivity"].get<Real64>();
    this->soil.rho = j["soil_density"].get<Real64>();
    this->soil.cp = j["soil_specific_heat"].get<Real64>();
```

- Read values using some thin worker functions that are very key oriented, like this:

```c++
thisPLHP.loadSideDesignVolFlowRate = state.dataInputProcessing->inputProcessor->getRealFieldValue(fields, schemaProps, "load_side_reference_flow_rate");
if (thisPLHP.loadSideDesignVolFlowRate == DataSizing::AutoSize) {
  thisPLHP.loadSideDesignVolFlowRateWasAutoSized = true;
}
```

- And of course, use the standard GetObjectItem function, and then access fields based off of array index:

```c++
thisBoiler.VolFlowRate = s_ipsc->rNumericArgs(3);
```

So why are you being asked to change this code?  Well, we would _love_ to eliminate the GetObjectItem layer, and access everything based off of keys.  That requires going through every get input routine and converting it over, pretty much by hand.

One caveat: when you access things directly off of the JSON data structure, you need to explicitly tell EnergyPlus that you have "used" this object instance.  Otherwise there would be a warning at the end of the simulation that says "Object XYZ named ABC was not used".  It is as simple as:

```c++
state.dataInputProcessing->inputProcessor->markObjectAsUsed(cCurrentModuleObject, thisObjectName);
```

So what to do here?  Well, if you were just literally changing a line or an index or something, I would say maybe don't worry about converting it over to a key-value JSON-style input processing function.  Since it's a new function entirely, and it's pretty small, I think it's a great lightweight opportunity for you to make the conversion, so that you know how to do it on future work.  And it's one less function we have to convert later.....

**Comment by RKStrand** [comment]
@jasondegraw @Myoldmopar @rraustad Ok!  I believe that I have successfully completed this fix.  The input object that was causing the problem (AirflowNetwork:Distribution:Linkage) has been converted to using JSON.  The solution is not pretty but it really has to be a bit methodical to make sure the AirLoopNum get propagated throughout the network despite where the "start" of the loop is entered/read into the order.  This is a completely different solution than previously done with a new unit test as well.  I think this addresses all of the concerns expressed.  Please feel free to look through this when you have a chance and let me know if you see any issues.  Thanks!

**Comment by RKStrand** [comment]
@Myoldmopar Thanks so much for that explanation!  I think I understand much better now and I can see where doing it for this fix would give me a chance to figure this out on a small scale so that in future work I'll be a little more up to speed.  I have marked this as "waiting for developer" and will look to implement what @jasondegraw requested.  (Oops...this was supposed to go out several days ago, but I forgot to click "Comment")

Update: the work here is done and this was switched back to "Waiting on Reviewer".  Hopefully, this adequately addresses the concerns expressed previously.

**Review by jasondegraw — APPROVED** [review]
@RKStrand This will be better long term, thanks for being willing to go back over it.

**Comment by Myoldmopar** [comment]
@RKStrand I saw this was conflicted, so I merged in develop and resolved the conflict.  I also noticed CI was failing so I made a debug build, and found a divide by zero in the `AirflowNetwork_MULTIZONE_House_DuctSizing` test file. 

The divide by zero is on line Solver.cc:12808, which I don't think you directly modified, but somehow the logic is allowing the SupplyBranchArea variable to be zero at this point.

image

Let me know if you need anything else from me.

**Comment by Myoldmopar** [comment]
(Also I just pushed the conflict resolved branch, so make sure to pull before attempting any pushes.)

**Comment by nrel-bot-2c** [comment]
@RKStrand @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 2]
```diff
@@ -4838,96 +4838,98 @@ namespace AirflowNetwork {
...
+                    AirflowNetworkLinkageData(count).NodeHeights[0] = 0.0;
+                    AirflowNetworkLinkageData(count).NodeNames[1] = Util::makeUPPER(fields.at("node_2_name").get<std::string>());
+                    std::string tempNode2 = AirflowNetworkLinkageData(count).NodeNames[1];
+                    AirflowNetworkLinkageData(count).NodeHeights[1] = 0.0;
+                    AirflowNetworkLinkageData(count).CompName = Util::makeUPPER(fields.at("component_name").get<std::string>());
+                    std::string tempComp = AirflowNetworkLinkageData(count).CompName;
+                    AirflowNetworkLinkageData(count).ZoneName =
+                        Util::makeUPPER(m_state.dataInputProcessing->inputProcessor->getAlphaFieldValue(fields, schemaProps, "thermal_zone_name"));
+                    std::string tempZone = AirflowNetworkLinkageData(count).ZoneName;
+                    AirflowNetworkLinkageData(count).LinkNum = count;
```
Comment (rraustad) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:4902]: This conversion to json looks correct. There are some debugging statements sprinkled through (e.g., std::string tempName) that could be removed. The example files all pass and one unit test needs investigation/correction.

Comment (RKStrand) [reply src/EnergyPlus/AirflowNetwork/src/Solver.cpp:4902]: @rraustad I got rid of the temporary assignments and made corrections that should result in the unit tests all passing now I think.  Also, the divide by zero noted by @Myoldmopar on 9/4 above, I fixed this by changing SupplyBranchArea in line 12808 in Solver.cc to ReturnTrunkArea.  From a quick glance at the code, I think this was just a typo that somehow never got tripped.  But given that ReturnTrunkArea is calculated right above in line 12807, it would seem likely that this fix is legitimate.  Thoughts?  If you are all good with this and it comes back green, then I think we are ready for the final review and hopefully accept/merge.

**Comment by RKStrand** [comment]
@mitchute I just resolved the conflict I think.  I'm not sure why there was a conflict as I don't think I messed with anything here, but hopefully everything is fine now.

**Comment by mitchute** [comment]
@RKStrand it looks like there's still a test failure here to resolve. Pointing it back to you for now.

**Comment by mitchute** [comment]
@RKStrand seeing some new err diffs here.

```diff
    ************* No node connection errors were found.
    ************* Beginning Simulation
    ************* Simulation Error Summary *************
+   ************* There are 18 unused objects in input.
+   ************* Use Output:Diagnostics,DisplayUnusedObjects; to see them.
    *************
    ************* ===== Final Error Summary =====
    ************* The following error categories occurred.  Consider correcting or noting.
```

**Comment by RKStrand** [comment]
@mitchute Huh.  Well, I'm not sure what is causing that.  It's possible that making this one thing all caps caused other issues I guess.  I'll have to track that down but I'm guessing it will take some time.  That might mean this doesn't make the 26.2 release.

**Comment by mitchute** [comment]
Not sure. I just pulled in develop and we'll run it again here. I'll do some local testing in the meantime.

**Comment by RKStrand** [comment]
@mitchute I took a further look at this and it appears that there is a "difference" in the way I handled the "mark object as used" call.  Elsewhere in Solver.cpp, it sets the local data "name" to the upper case of "instance.key()" but then when it checks if the object is used, it uses the unmodified instance.key().  So...I'm going to pull your latest that merged in develop and then make this change to what I did.  Maybe this will be simpler than I thought???

**Comment by mitchute** [comment]
@RKStrand yeah, I think you can probably fix it up quick enough. I took the `makeUPPER` off of [this line](https://github.com/NREL/EnergyPlus/pull/11148/files#diff-e1efb8d61457e60529afd8b89b7ff9f3770dc9f1e1fbfba128dfaa82d5a3078eR4893), which cleaned up that warning, but now there are a couple other failures to figure out. I'll leave it to you for now.

**Comment by RKStrand** [comment]
@mitchute Ok, I've pulled the latest with develop merged in and made that change.  Hoping for a Halloween treat here and no more "tricks"!

**Comment by mitchute** [comment]
Just ran regressions locally, and it's all looking good so far.

**Comment by mitchute** [comment]
This is looking good. Those unused object diffs are now gone and the numerical diffs seem to be expected. We can merge this unless I hear otherwise from anyone.

**Comment by rraustad** [comment]
I was wondering why there were any diffs at all from these changes and then I reviewed and remembered you did this:

{CC8A19C4-B51E-4983-8160-11E3F313892B}
