### PR TITLE
Fix HVAC radiant heat gain with CondFD

### LINKED ISSUE #10304: Surface Inside Face System Radiation Heat Gain is always zero for ConductionFiniteDifference
Issue overview
--------------
User noted that there was no impact on the surface heat balance for the radiant output from ZoneHVAC:Baseboard:RadiantConvective:Electric. It turns out that the problem is with the ConductionFiniteDifference surface heat balance. The radiant HVAC system output term is zero (for all radiant system types). 

The problem was introduced in #8932 (v9.6.0) where a new function [`GetSurfQdotRadHVACInPerArea`](https://github.com/NREL/EnergyPlus/blob/08e876be40e78271d161cdd1a18c40c0b8f737c3/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L8986-L8990) was added to sum up the various radiant system outputs into a single value `SurfQdotRadHVACInPerArea(SurfNum)`, but `GetSurfQdotRadHVACInPerArea` never gets called for finite difference surfaces.

### Workaround
Use the ConductionTransferFunction heat balance algorithm (or any other one except ConductionFiniteDifference), or go back to v9.5.0.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 23.2
 - Helpdesk ticket number 16464.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #10304
 - Streamlines tracking of surfaces that receive radiant system heat gains and surfaces with SurfaceProperty:HeatBalanceSourceTerm.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DataHeatBalFanSys.hh [hunk 1]
```diff
@@ -89,6 +89,15 @@ namespace DataHeatBalFanSys {
         int DualPMVErrIndex = 0; // Dual PMV setpoint error index
     };
 
+    struct SurfQRadFromHVACData
```
Comment (mjwitte) [inline src/EnergyPlus/DataHeatBalFanSys.hh:92]: New struct to hold the old Array1Ds for SurfQHTRadSys, SurfQHWBaseboard, etc.

File: src/EnergyPlus/DataHeatBalance.hh [hunk 2]
```diff
@@ -698,10 +698,8 @@ namespace DataHeatBalance {
         int zoneOABalanceIndex = 0;       // Index to ZoneAirBalance for this zone, if any
 
         // Spaces
-        bool anySurfacesWithoutSpace = false; // True if any surfaces in a zone do not have a space assigned in input
-        bool anySurfacesWithSpace = false;    // True if any surfaces in a zone have a space assigned in input
```
Comment (mjwitte) [inline src/EnergyPlus/DataHeatBalance.hh:702]: Unrelated to the main defect, but moved these out of state.

File: src/EnergyPlus/DataSurfaces.hh [hunk 3]
```diff
@@ -1451,6 +1449,9 @@ struct SurfacesData : BaseGlobalStruct
     std::vector<int> AllHTKivaSurfaceList;             // List of all Kiva foundation surfaces
     std::vector<int> AllSurfaceListReportOrder;        // List of all surfaces - output reporting order
     std::vector<int> AllVaryAbsOpaqSurfaceList;        // List of all opaque exterior surfaces with dynamic coating
+    std::vector<int> allInsideSourceSurfaceList;       // List of all surfaces with SurfaceProperty:HeatBalanceSourceTerm for inside face
+    std::vector<int> allOutsideSourceSurfaceList;      // List of all surfaces with SurfaceProperty:HeatBalanceSourceTerm for outside face
+    std::vector<int> allGetsRadiantHeatSurfaceList;    // List of all surfaces that receive radiant HVAC output
```
Comment (mjwitte) [inline src/EnergyPlus/DataSurfaces.hh:1454]: New surface lists for special cases.

File: src/EnergyPlus/ElectricBaseboardRadiator.cc [hunk 4]
```diff
@@ -409,6 +409,7 @@ namespace ElectricBaseboardRadiator {
                 }
                 if (elecBaseboard.SurfacePtr(SurfNum) != 0) {
                     state.dataSurface->surfIntConv(elecBaseboard.SurfacePtr(SurfNum)).getsRadiantHeat = true;
+                    state.dataSurface->allGetsRadiantHeatSurfaceList.emplace_back(elecBaseboard.SurfacePtr(SurfNum));
```
Comment (mjwitte) [inline src/EnergyPlus/ElectricBaseboardRadiator.cc:412]: Example of building the `allGetsRadiantHeatSurfaceList` vector.

File: src/EnergyPlus/ElectricBaseboardRadiator.cc [hunk 5]
```diff
@@ -905,7 +906,12 @@ namespace ElectricBaseboardRadiator {
         Real64 constexpr SmallestArea(0.001); // Smallest area in meters squared (to avoid a divide by zero)
 
         // Initialize arrays
-        state.dataHeatBalFanSys->SurfQElecBaseboard = 0.0;
+        for (auto &elecBaseboard : state.dataElectBaseboardRad->ElecBaseboard) {
+            for (int radSurfNum = 1; radSurfNum <= elecBaseboard.TotSurfToDistrib; ++radSurfNum) {
+                int surfNum = elecBaseboard.SurfacePtr(radSurfNum);
+                state.dataHeatBalFanSys->surfQRadFromHVAC(surfNum).ElecBaseboard = 0.0;
```
Comment (mjwitte) [inline src/EnergyPlus/ElectricBaseboardRadiator.cc:912]: Instead of zeroing this for all surfaces, only need to touch the surfaces that actually receive radiant heat from electric baseboards. Similar changes for the other four equipment types (chilled panel, HW baseboard, Steam baseboard, high temp radiant).

File: src/EnergyPlus/ElectricBaseboardRadiator.cc [hunk 6]
```diff
@@ -918,8 +924,7 @@ namespace ElectricBaseboardRadiator {
                     if (state.dataSurface->Surface(SurfNum).Area > SmallestArea) {
                         Real64 ThisSurfIntensity =
                             (elecBaseboard.QBBElecRadSource * elecBaseboard.FracDistribToSurf(RadSurfNum) / state.dataSurface->Surface(SurfNum).Area);
-                        state.dataHeatBalFanSys->SurfQElecBaseboard(SurfNum) += ThisSurfIntensity;
-                        state.dataHeatBalSurf->AnyRadiantSystems = true;
+                        state.dataHeatBalFanSys->surfQRadFromHVAC(SurfNum).ElecBaseboard += ThisSurfIntensity;
```
Comment (mjwitte) [inline src/EnergyPlus/ElectricBaseboardRadiator.cc:927]: Previously `AnyRadiantSystems` was getting set to true for all surfaces more than once for every iteration.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 7]
```diff
@@ -6876,6 +6875,11 @@ void CalcHeatBalanceOutsideSurf(EnergyPlusData &state,
             state, state.dataHeatBalSurf->SurfInsideTempHist(1), 0, state.dataHeatBalSurf->SurfQdotRadNetLWInPerArea, _, Outside);
     }
 
+    // Calculate heat extract due to additional heat flux source term as the surface boundary condition
+    for (int surfNum : state.dataSurface->allOutsideSourceSurfaceList) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:6879]: Unrelated to the main defect here, but streamlined this for a rarely used surface property, same for inside surface source.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 8]
```diff
@@ -6903,13 +6907,6 @@ void CalcHeatBalanceOutsideSurf(EnergyPlusData &state,
                 state.dataHeatBalSurf->SurfHGrdExt(SurfNum) = 0.0;
                 state.dataHeatBalSurf->SurfQRadLWOutSrdSurfs(SurfNum) = 0.0;
 
-                // Calculate heat extract due to additional heat flux source term as the surface boundary condition
-
-                if (Surface(SurfNum).OutsideHeatSourceTermSchedule) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:6908]: No longer checking this for every surface, every iteration.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 9]
```diff
@@ -7571,11 +7568,12 @@ void CalcHeatBalanceInsideSurf(EnergyPlusData &state,
         state.dataHeatBalSurfMgr->calcHeatBalInsideSurEnvrnFlag = true;
     }
 
+    sumSurfQdotRadHVAC(state);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:7571]: This is the main fix for the defect. A new function to gather all of the radiant impacts on the pertinent surfaces. One call here no matter the surface type or the heat transfer algorithm.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 10]
```diff
@@ -7679,13 +7677,9 @@ void CalcHeatBalanceInsideSurf2(EnergyPlusData &state,
...
 
     // Calculate heat extract due to additional heat flux source term as the surface boundary condition
-    if (state.dataSurface->AnyHeatBalanceInsideSourceTerm) {
-        for (int SurfNum : HTSurfs) {
-            if (state.dataSurface->Surface(SurfNum).InsideHeatSourceTermSchedule) {
-                state.dataHeatBalSurf->SurfQAdditionalHeatSourceInside(SurfNum) =
-                    EnergyPlus::ScheduleManager::GetCurrentScheduleValue(state, state.dataSurface->Surface(SurfNum).InsideHeatSourceTermSchedule);
-            }
-        }
+    for (int surfNum : state.dataSurface->allInsideSourceSurfaceList) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:7680]: Streamline inside source.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 11]
```diff
@@ -7797,8 +7791,6 @@ void CalcHeatBalanceInsideSurf2(EnergyPlusData &state,
                             state, SurfNum, state.dataHeatBalSurf->SurfTempInTmp(SurfNum), MAT_zone, SurfTempInSat);
                     }
                     // Pre-calculate a few terms
-                    if (state.dataHeatBalSurf->AnyRadiantSystems(SurfNum))
-                        state.dataHeatBalSurf->SurfQdotRadHVACInPerArea(SurfNum) = GetSurfQdotRadHVACInPerArea(state, SurfNum);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:7801]: Replaced with new call to `sumSurfQdotRadHVAC`, here and several other places.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 12]
```diff
@@ -9042,11 +9020,14 @@ void CalcHeatBalanceInsideSurf2CTFOnly(EnergyPlusData &state,
     } // ...end of main inside heat balance iteration loop (ends when Converged)
 }
 
-Real64 GetSurfQdotRadHVACInPerArea(EnergyPlusData &state, int const SurfNum)
+void sumSurfQdotRadHVAC(EnergyPlusData &state)
 {
-    return state.dataHeatBalFanSys->SurfQHTRadSys(SurfNum) + state.dataHeatBalFanSys->SurfQHWBaseboard(SurfNum) +
-           state.dataHeatBalFanSys->SurfQSteamBaseboard(SurfNum) + state.dataHeatBalFanSys->SurfQElecBaseboard(SurfNum) +
-           state.dataHeatBalFanSys->SurfQCoolingPanel(SurfNum);
+    for (int surfNum : state.dataSurface->allGetsRadiantHeatSurfaceList) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:9025]: New function `sumSurfQdotRadHVAC` sums radiant fluxes only for pertinent surfaces.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 13]
```diff
@@ -2851,6 +2851,11 @@ namespace SurfaceGeometry {
     void CreateMissingSpaces(EnergyPlusData &state, Array1D<SurfaceGeometry::SurfaceData> &Surfaces)
     {
         // Scan surfaces to see if Space was assigned in input
+        EPVector<bool> anySurfacesWithSpace;    // True if any surfaces in a zone do not have a space assigned in input
+        EPVector<bool> anySurfacesWithoutSpace; // True if any surfaces in a zone have a space assigned in input
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2855]: Moved from state. Not related to the defect.

**Review by mjwitte — COMMENTED** [review]
Code walkthru.

**Comment by mjwitte** [comment]
Defect file results, before, Surface Inside Face System Radiation Heat Gain Rate is always zero.

image

And with this branch, now there are values.
image

File: src/EnergyPlus/DataHeatBalFanSys.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DataHeatBalFanSys.hh:92]: :) :) :)

File: src/EnergyPlus/DataHeatBalance.hh (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DataHeatBalance.hh:702]: :+1:

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 14]
```diff
@@ -547,17 +547,22 @@ void InitSurfaceHeatBalance(EnergyPlusData &state)
...
     } // ...end of Zone loop
 
+    for (int surfNum : state.dataSurface->allGetsRadiantHeatSurfaceList) {
+        auto &thisSurfQRadFromHVAC = state.dataHeatBalFanSys->surfQRadFromHVAC(surfNum);
+        thisSurfQRadFromHVAC.HTRadSys = 0.0;
+        thisSurfQRadFromHVAC.HWBaseboard = 0.0;
+        thisSurfQRadFromHVAC.SteamBaseboard = 0.0;
+        thisSurfQRadFromHVAC.ElecBaseboard = 0.0;
+        thisSurfQRadFromHVAC.CoolingPanel = 0.0;
+    }
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:564]: This is fine as is.  But if this is actually zeroing out every member variable, it could be nice to include a "reset" function on the struct that zeroes out all the members there.  It's not functionally different, but could future proof things.  If we add more member variables to the struct in the future, having the reset function right there in the struct would make it easier to remember to initialize them. Don't sweat it now unless there are more changes needed.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc (hunk 9 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc:7571]: :+1:

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 13 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:2855]: :heart:

**Review by Myoldmopar — APPROVED** [review]
This is wonderful.  Quite a few small cleanups to go along with the actual defect fix.  I am getting a little blurry about all the different lists of surfaces, but I understand it is helping the code move in the right direction.  I would be happy to brainstorm where these should go in the future to avoid the list becoming excessive, but I am not complaining about where it is at. 

I'll go ahead and confirm CI, and build/test locally, and see if this can go in.

**Comment by Myoldmopar** [comment]
CI was totally happy here when it ran.  I built and tested locally and it's happy.  Let's get this merged in as well.  Thanks @mjwitte !
