### PR TITLE
Fix file not found output message

### LINKED ISSUE #8282: EnergyPlus does not report a clear message about where it attempted to find files which were not found.
Issue overview
--------------
When given an idf which contains references to an external file, EnergyPlus does not report a clear message when it is unable to find that file. For example given an idf snippet such as:
> Table:IndependentVariable,
> VRFCoolCapFT_ODB,        !- Name
> Cubic,                   !- Interpolation Method
     Constant,                !- Extrapolation Method
     -25,                !- Minimum Value
     45,                !- Maximum Value
     35,                !- Normalization Reference Value
     Temperature,             !- Unit Type
     ../performanceTable_TC_168C.csv,                        !- External File Name
     1,                        !- External File Column Number
     2;                        !- External File Starting Row Number

Provided that EnergyPlus cannot find this file, the only message the will put put in the .err file is 
```   **  Fatal  ** File "../performanceTable_TC_168C.csv" : File not found.```
This does not give the user a very clear description of where EnergyPlus tried to find this file, or what went wrong during this process.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): develop
 - Unmethours link or helpdesk ticket number: None

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by ajscimone**
Pull request overview
---------------------
 - Fixes #8282 
 - This pull request fixes an issue with the `DataSystemVariables::CheckForActualFileName` function not outputting any information about where EnergyPlus searched for files it was unable to find. After this pull request, users can now pass in an optional vector which will be populated with locations that EnergyPlus looks for the file being checked, and a flag to ask for the function to output the checked locations as error messages. This will help users quickly identify why EnergyPlus cannot locate the files they are referencing in an idf.

The original idf file which caught this bug is posted here: 
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/5314871/in.idf.txt)

To demonstrate the effect of this pull request here is the .err output from develop  on the above idf before this pull request:
[eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/5314940/eplusout.err.txt)

And here is the .err file for this idf after this pull request.
[eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/5314936/eplusout.err.txt)

The result is a much clearer output in the err stream about the issues with the files not being found, as well as a more understandable fatal error.

Additionally, these two idfs also use this file checking function, and so additional .err outputs can be seen by running them (provided you don't let EnergyPlus find the actual files it's looking for.)

[ScheduleFileTest.idf.txt](https://github.com/NREL/EnergyPlus/files/5314895/ScheduleFileTest.idf.txt)
[SolarShadingTest.idf.txt](https://github.com/NREL/EnergyPlus/files/5314901/SolarShadingTest.idf.txt)

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DataSystemVariables.cc [hunk 1]
```diff
@@ -202,7 +202,9 @@ namespace DataSystemVariables {
     void CheckForActualFileName(IOFiles &ioFiles,
                                 std::string const &originalInputFileName, // name as input for object
                                 bool &FileFound,                          // Set to true if file found and is in CheckedFileName
-                                std::string &CheckedFileName              // Blank if not found.
+                                std::string &CheckedFileName,             // Blank if not found.
+                                std::vector<std::string> *pathsChecked,
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataSystemVariables.cc]: Please pass in a reference here instead of a pointer.

Comment (ajscimone) [reply src/EnergyPlus/DataSystemVariables.cc]: @Myoldmopar Neal and I actually decided to eliminate this parameter. Instead we are just putting the vector in the method. This makes things a lot simpler, and keeps the usage of the function more similar.

File: src/EnergyPlus/DataSystemVariables.cc [hunk 2]
```diff
@@ -255,81 +244,44 @@ namespace DataSystemVariables {
...
+        std::vector<std::pair<std::string, std::string>> pathsChecked;
+
+        const std::vector<std::pair<std::string, std::string>> pathsToCheck = {
+            {InputFileName, "InputFileName"},
+            {DataStringGlobals::inputDirPathName + InputFileName, "inputDirPathName"},
+            {envinputpath1 + InputFileName, "envinputpath1"},
+            {envinputpath2 + InputFileName, "envinputpath2"},
+            {envprogrampath + InputFileName, "envprogrampath"},
+            {CurrentWorkingFolder + InputFileName, "CurrentWorkingFolder"},
+            {ProgramPath + InputFileName, "ProgramPath"}
```
Comment (nealkruis) [inline src/EnergyPlus/DataSystemVariables.cc]: @ajscimone Here are more informative descriptions for each of the strings that describe where files are searched:

1. Current working directory
2. IDF directory
3. "epin" environment variable
4. "input_path" environment variable
5. <This variable is never used or set, I think it's supposed to be "program_path" environment variable initialized as `cProgramPath`, but that variable overwrites `ProgramPath` instead>
6. INI directory (if it exists) <from what I can tell this is always identical to [1] -- maybe we can drop it?>
7. "program" > "dir" from INI file

We should maybe add `exeDirectory` to the paths searched, too? I think that is the intent of [5] and [7], but neither of those seem reliable.

@Myoldmopar @mjwitte thoughts on any of this?

Separate question: Does/should this interact with the way python plug-in paths are searched?

File: src/EnergyPlus/CurveManager.cc [hunk 3]
```diff
@@ -1750,9 +1750,13 @@ namespace CurveManager {
                             std::size_t rowNum = indVarInstance.at("external_file_starting_row_number").get<std::size_t>() - 1;
 
                             if (!state.dataCurveManager->btwxtManager.tableFiles.count(filePath)) {
-                                state.dataCurveManager->btwxtManager.tableFiles.emplace(filePath, TableFile{state, filePath});
+                                TableFile tableFile;
+                                ErrorsFound |= tableFile.load(state, filePath);
```
Comment (Myoldmopar) [inline src/EnergyPlus/CurveManager.cc:1754]: Breaking the initialization into a separate `bool load()` function makes sense.

File: src/EnergyPlus/CurveManager.cc [hunk 4]
```diff
@@ -2040,19 +2049,15 @@ namespace CurveManager {
...
         filePath = path;
         bool fileFound;
         std::string fullPath;
-        DataSystemVariables::CheckForActualFileName(state, path, fileFound, fullPath);
-        if (!fileFound) {
-            ShowFatalError(state, "File \"" + filePath + "\" : File not found.");
+        std::string contextString = "CurveManager::TableFile::load: ";
+        DataSystemVariables::CheckForActualFileName(state, path, fileFound, fullPath, contextString);
+        if(!fileFound){
+            return true;
```
Comment (Myoldmopar) [inline src/EnergyPlus/CurveManager.cc:2060]: So `true` means error.  OK.  A little confusing maybe but not a big deal.  If other commits are needed here for anything, I'd suggest considering a clearer convention like `bool loadSuccess()` where true is clearly success.  Anyway, not a big deal if it's working.

File: src/EnergyPlus/DataSystemVariables.cc [hunk 5]
```diff
@@ -251,81 +240,51 @@ namespace DataSystemVariables {
...
+        const std::vector<std::pair<std::string, std::string>> pathsToCheck = {
+            {InputFileName, "Current Working Directory"},
+            {DataStringGlobals::inputDirPathName + InputFileName, "IDF Directory"},
+            {DataStringGlobals::exeDirectory + InputFileName, "EnergyPlus Executable Directory"},
+            {envinputpath1 + InputFileName, "\"epin\" Environment Variable"},
+            {envinputpath2 + InputFileName, "\"input_path\" Environment Variable"},
+            {envprogrampath + InputFileName, "\"program_path\" Environment Variable"},
+            {CurrentWorkingFolder + InputFileName, "INI File Directory"},
+            {ProgramPath + InputFileName, "\"program\", \"dir\" from INI File"}
+        };
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataSystemVariables.cc:257]: This is quite a small list, so it's not a big deal, but an array would've been acceptable here since I think this vector is staying fixed length.

File: src/EnergyPlus/ExternalInterface.cc [hunk 6]
```diff
@@ -1150,7 +1150,11 @@ namespace ExternalInterface {
                                               cNumericFieldNames);
                 // Get the FMU name
                 FMU(Loop).Name = cAlphaArgs(1);
-                CheckForActualFileName(state, cAlphaArgs(1), fileExist, tempFullFileName);
+
+                std::string contextString = cCurrentModuleObject + ", " + cAlphaFieldNames(1) + ": ";
+
+                CheckForActualFileName(state, cAlphaArgs(1), fileExist, tempFullFileName, contextString);
```
Comment (Myoldmopar) [inline src/EnergyPlus/ExternalInterface.cc:1156]: This makes sense, just needing to add a new context string.

File: src/EnergyPlus/ExternalInterface.cc [hunk 7]
```diff
@@ -1165,8 +1169,6 @@ namespace ExternalInterface {
                     }
                     fullFileName(Loop) = tempFullFileName;
                 } else {
-                    ShowSevereError(state, "ExternalInterface/InitExternalInterfaceFMUImport:");
-                    ShowContinueError(state, "file not located = \"" + cAlphaArgs(1) + "\".");
```
Comment (Myoldmopar) [inline src/EnergyPlus/ExternalInterface.cc:1169]: And then no longer needing to report the error details.

**Review by Myoldmopar — APPROVED** [review]
I'm OK with these changes, it looks like it won't affect the Python stuff at all, and it looks to be in good shape.  I had a couple suggestions in case additional changes are needed, but otherwise it's fine as-is.  I haven't tested it, I think @mitchute is going to verify the fix, but the code itself looks good.

**Comment by mitchute** [comment]
Confirmed that this works. One minor cosmetic issue that we might consider cleaning up if there are other commits required:

Break the "Paths searched:" string, here (https://github.com/NREL/EnergyPlus/pull/8324/files#diff-c3b9eb9daf6e23f579ad991f364fc70e9416d16a05619e9cc830960094e3bbb6R284) out into a separate ```ShowContinueError```. As it is, "Paths Searched:" comes out in the last error summary.

```
**  Fatal  ** GetCurveInput: Errors found in getting Curve Objects.  Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=4
   ..... Last severe error=CurveManager::TableFile::load: "../performanceTable_PI_168H.csv" not found. Paths searched:
```

File: src/EnergyPlus/CurveManager.cc (hunk 4 above)
Comment (nealkruis) [reply src/EnergyPlus/CurveManager.cc:2060]: I was kind of thinking of it as an error code return where `0`/`false` means success.

**Comment by mitchute** [comment]
I just confirmed the changes locally. The Kiva unit test failures aren't related to this and I think we're investigating that separately anyway, so I'm going to merge this.

**Comment by mjwitte** [comment]
I'm guessing this PR is the source of audit diffs that show up now on test files that access an external file. e.g. [HybridModel_4Zone_Solve_PeopleCount_with_HVAC](http://energyplus.s3-website-us-east-1.amazonaws.com/regressions/2020-11/283b64077bc031c2b6be032380370b8f2c8e6cac-a80eea35d6c8a97cf2cab493ce5a675b0691a269/HybridModel_4Zone_Solve_PeopleCount_with_HVAC/x86_64-MacOS-10.15-clang-11.0.0/eplusout.audit.diff.html) and [1ZoneUncontrolled_win_1](http://energyplus.s3-website-us-east-1.amazonaws.com/regressions/2020-11/283b64077bc031c2b6be032380370b8f2c8e6cac-a80eea35d6c8a97cf2cab493ce5a675b0691a269/1ZoneUncontrolled_win_1/x86_64-MacOS-10.15-clang-11.0.0/eplusout.audit.diff.html)

**Comment by mitchute** [comment]
Seems right to me. Comparing the diffs, the only real difference in the messages are the clone branch paths.

i.e. ```clone_baseline``` vs. ```clone_branch```

**Comment by mjwitte** [comment]
So, we'll need to add some rules to CI to understand that these are not substantive diffs and not warn. Otherwise, we'll never get a fully green report.

**Comment by Myoldmopar** [comment]
Got it: https://github.com/NREL/EnergyPlusRegressionTool/pull/60/commits/d04aae5924fc2244933f1075d3ab87bfd5bddecf

Once that PR merged, Decent CI will not show those diffs anymore.
