### PR TITLE
UnitarySystem used as single zone vav will crash with blank no load air flow method

### LINKED ISSUE #8566: Floating point divide by zero exception in calcSZVAVModel with UnitarySys
Issue overview
--------------

Floating point divide by zero exception in calcSZVAVModel with UnitarySys. This happens (obviously) in the worst possible test on the OpenStudio-resources: the autosizing test. The goal of this test is to add **ALL HVAC objects that might be autosized** to test the autosize / getAutosizeValue methods. This test is now failing with v9.5.0-IOFreeze

```
* thread #1, name = 'energyplus', stop reason = signal SIGFPE: floating point divide by zero
    frame #0: 0x00007ffff1d8ee1d libenergyplusapi.so.9.5.0`EnergyPlus::SZVAVModel::calcSZVAVModel(state=0x00007fffffffb890, SZVAVModel=0x00005555590637c8, SysIndex=0x00005555590637d0, FirstHVACIteration=0x00007fffffff8a68, CoolingLoad=0x00005555561714c5, HeatingLoad=0x00005555561714c4, ZoneLoad=0x00007fffffff8a58, OnOffAirFlowRatio=0x00007fffffff9be8, HXUnitOn=0x00007fffffff9bb4, AirLoopNum=0x00007fffffff8a6c, PartLoadRatio=0x00007fffffff8ac8, CompressorONFlag=0x00007fffffff8a88) at SZVAVModel.cc:1197:47
   1194	            // Step 2: Load is greater then allowed in region 1, determine boundary load for region 3
   1195	            // only difference in this calculation is using maxAirMassFlow instead of minAirMassFlow, just use the ratio to adjust previous
   1196	            // calculation
-> 1197	            boundaryLoadMet *= maxAirMassFlow / minAirMassFlow;
   1198	
   1199	            if ((CoolingLoad && boundaryLoadMet < ZoneLoad) || (HeatingLoad && boundaryLoadMet > ZoneLoad)) { // in Region 2 of figure
   1200	
```

```
(lldb) p thisSys.Name
(std::string) $7 = "AIR LOOP HVAC UNITARY SYSTEM 2"
```

minAirMassFlow is zero from here: https://github.com/NREL/EnergyPlus/blob/e003a916370b9bc68fa60e39e504bd8b2ae52ca9/src/EnergyPlus/SZVAVModel.cc#L988

You need fixes in https://github.com/NREL/EnergyPlus/pull/8565 in order to make this file run.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.5.0-IOFreeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/commit/0222b4740a764a62b879695e9ec6e1663337e8ac
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #8566
 - When UnitarySystem uses Control Type = SingleZoneVAV, the no load supply air flow rate method input field should not be blank, and the no load air flow rate should be non-zero or autosized.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Defect file 8566-UnitarySystem_SingleSpeedDX testing:

1. Defect file crashes in develop with divide by 0 fault where minAirMassFlow = 0 at line 1197 of SZVAVModel.cc.

    boundaryLoadMet *= maxAirMassFlow / minAirMassFlow;

2. Defect file runs to completion in this branch without error.

    AirLoopHVAC:UnitarySystem,
      SingleZoneVAV,                    !- Control Type
      ,       !- No Load Supply Air Flow Rate Method
      autosize,                !- No Load Supply Air Flow Rate {m3/s}

2. Defect file changed to this with appropriate warnings.

    AirLoopHVAC:UnitarySystem,
      ,       !- No Load Supply Air Flow Rate Method
      ,       !- No Load Supply Air Flow Rate {m3/s}

    ** Warning ** Input errors for AirLoopHVAC:UnitarySystem:SYS 1 FURNACE DX COOL UNITARY SYSTEM
    **   ~~~   ** Control Type = SingleZoneVAV
    **   ~~~   ** Input for No Load Supply Air Flow Rate cannot be blank.
    **   ~~~   ** Input for No Load Supply Air Flow Rate has been set to AutoSize and the simulation continues.

3. Defect file change to:

    AirLoopHVAC:UnitarySystem,
      ,       !- No Load Supply Air Flow Rate Method
      0,       !- No Load Supply Air Flow Rate {m3/s}

    ** Severe  ** Input errors for AirLoopHVAC:UnitarySystem:SYS 1 FURNACE DX COOL UNITARY SYSTEM
    **   ~~~   ** Control Type = SingleZoneVAV
    **   ~~~   ** Input for No Load Supply Air Flow Rate cannot be 0.
    **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -3112,6 +3112,26 @@ namespace UnitarySystems {
...
+                            ShowContinueError(state, "Input for No Load Supply Air Flow Rate has been set to AutoSize and the simulation continues.");
+                        } else if (loc_m_NoCoolHeatSAFMethod_SAFlow == 0.0) { // no load air flow for SZVAV cannot be 0
+                            thisSys.m_MaxNoCoolHeatAirVolFlow = DataSizing::AutoSize;
+                            thisSys.m_RequestAutoSize = true;
+                            ShowSevereError(state, "Input errors for " + cCurrentModuleObject + ":" + thisObjectName);
+                            ShowContinueError(state, "Control Type = " + loc_m_ControlType);
+                            ShowContinueError(state, "Input for No Load Supply Air Flow Rate cannot be 0.");
+                            errorsFound = true;
+                        }
+                    }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: Catch different cases where SZVAV model will not act as expected. Does this catch everything? This checks for autosize, blank and 0 so doesn't feel like it will overwrite anything user specified.

**Comment by rraustad** [comment]
@mjwitte other than (you, me, edwin, etc.) thinking about what other code changes might help users in the future, this is ready.

**Comment by rraustad** [comment]
5. Defect file change to this and simulation crashed same as in 1. above. So maybe not quite ready. Trying to cover all use cases.

AirLoopHVAC:UnitarySystem,
SupplyAirFlowRate, !- No Load Supply Air Flow Rate Method
0, !- No Load Supply Air Flow Rate {m3/s}

**Comment by rraustad** [comment]
New fatal for 5. above:

    ** Severe  ** Input errors for AirLoopHVAC:UnitarySystem:SYS 1 FURNACE DX COOL UNITARY SYSTEM
    **   ~~~   ** Control Type = SingleZoneVAV
    **   ~~~   ** Input for No Load Supply Air Flow Rate cannot be 0.
    **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs

**Comment by jmythms** [comment]
Results of testing this branch:

1. The unit test + defect file fails on the current develop branch.
2. The unit test + defect file (as-is on devsupport) runs to completion on this branch.

I changed the defect file to have:

1.

    AirLoopHVAC:UnitarySystem,
    SingleZoneVAV, !- Control Type
    , !- No Load Supply Air Flow Rate Method
    autosize, !- No Load Supply Air Flow Rate {m3/s}
	
Result:
Runs to completion. 
	
2.

     AirLoopHVAC:UnitarySystem,
     , !- No Load Supply Air Flow Rate Method
     , !- No Load Supply Air Flow Rate {m3/s}

Result:
** Warning ** Input errors for AirLoopHVAC:UnitarySystem:SYS 1 FURNACE DX COOL UNITARY SYSTEM
** ~~~ ** Control Type = SingleZoneVAV
** ~~~ ** Input for No Load Supply Air Flow Rate cannot be blank.
** ~~~ ** Input for No Load Supply Air Flow Rate has been set to AutoSize and the simulation continues.	

3.

    AirLoopHVAC:UnitarySystem,
    , !- No Load Supply Air Flow Rate Method
    0, !- No Load Supply Air Flow Rate {m3/s}	
	
Result:	
** Severe ** Input errors for AirLoopHVAC:UnitarySystem:SYS 1 FURNACE DX COOL UNITARY SYSTEM
** ~~~ ** Control Type = SingleZoneVAV
** ~~~ ** Input for No Load Supply Air Flow Rate cannot be 0.
** Fatal ** getUnitarySystemInputData: previous errors cause termination. Check inputs
	
4.

    AirLoopHVAC:UnitarySystem,
    FlowPerCoolingCapacity, !- No Load Supply Air Flow Rate Method
    , !- No Load Supply Air Flow Rate {m3/s}
	
Result:
Fatal error with message.	
	
5.

    AirLoopHVAC:UnitarySystem,
    FractionOfAutosizedCoolingValue, !- No Load Supply Air Flow Rate Method
    , !- No Load Supply Air Flow Rate {m3/s}
	
Result: 
Fatal error with message.

6. Merged latest develop, built locally.

7. Tested timed-out CI tests locally - 
1ZoneUncontrolledUTF8,  1ZoneUncontrolled_DD2009. LgOffVAVusingBasement, HospitalLowEnergy passed.

@Myoldmopar

File: src/EnergyPlus/UnitarySystem.cc [hunk 2]
```diff
@@ -6098,6 +6098,11 @@ namespace UnitarySystems {
                     thisSys.m_HeatingSAFMethod = state.dataUnitarySystems->None;
                     if (thisSys.m_HeatCoilExists && thisSys.m_MaxHeatAirVolFlow == 0) {
                         ShowSevereError(state, cCurrentModuleObject + " = " + thisObjectName);
+                        if (loc_m_HeatingSAFMethod == "") {
```
Comment (Myoldmopar) [inline src/EnergyPlus/UnitarySystem.cc:6101]: In the future, using `string.clear()` instead of comparing `string == ""` is preferred, but definitely not worth holding this up.

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -6281,6 +6286,24 @@ namespace UnitarySystems {
                     }
                 } else if (UtilityRoutines::SameString(loc_m_NoCoolHeatSAFMethod, "None") || loc_m_NoCoolHeatSAFMethod == "") {
                     thisSys.m_NoCoolHeatSAFMethod = state.dataUnitarySystems->None;
+                    if (thisSys.m_ControlType == ControlType::CCMASHRAE) {
+                        if (loc_m_NoCoolHeatSAFMethod_SAFlow == -99999.0) { // no load air flow is autosized
+                            thisSys.m_MaxNoCoolHeatAirVolFlow = DataSizing::AutoSize;
+                            thisSys.m_RequestAutoSize = true;
+                        } else if (loc_m_NoCoolHeatSAFMethod_SAFlow == -999.0) { // no load air flow is blank
```
Comment (Myoldmopar) [inline src/EnergyPlus/UnitarySystem.cc:6293]: The -99999 and -999 isn't necessarily great, but I realize it's likely just a part of the existing pattern.  It can stay.

File: src/EnergyPlus/UnitarySystem.cc [hunk 4]
```diff
@@ -7002,6 +7025,12 @@ namespace UnitarySystems {
                         thisSys.m_RunOnLatentLoad = false;
                         thisSys.m_RunOnLatentOnlyWithSensible = false;
                     }
+                    if (thisSys.m_MaxNoCoolHeatAirVolFlow == 0.0) { // 0 min air flow not allowed for SZVAV
+                        ShowSevereError(state, "Input errors for " + cCurrentModuleObject + ":" + thisObjectName);
+                        ShowContinueError(state, "Control Type = " + loc_m_ControlType);
+                        ShowContinueError(state, "Input for No Load Supply Air Flow Rate cannot be 0.");
+                        errorsFound = true;
```
Comment (Myoldmopar) [inline src/EnergyPlus/UnitarySystem.cc:7032]: And proper error handling.  OK

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 5]
```diff
@@ -6303,7 +6303,202 @@ TEST_F(EnergyPlusFixture, UnitarySystemModel_GetBadSupplyAirMethodInput)
...
+    EXPECT_TRUE(has_err_output(false));
+    std::string erroutput =
+        std::string("   ** Warning ** Input errors for AirLoopHVAC:UnitarySystem:UNITARY SYSTEM MODEL\n"
+                    "   **   ~~~   ** Control Type = SingleZoneVAV\n"
+                    "   **   ~~~   ** Input for No Load Supply Air Flow Rate cannot be blank.\n"
+                    "   **   ~~~   ** Input for No Load Supply Air Flow Rate has been set to AutoSize and the simulation continues.\n");
+    EXPECT_TRUE(compare_err_stream(erroutput, true));
+    EXPECT_EQ(thisSys->m_MaxCoolAirVolFlow, DataSizing::AutoSize);
+    EXPECT_EQ(thisSys->m_MaxHeatAirVolFlow, DataSizing::AutoSize);
+    EXPECT_EQ(thisSys->m_MaxNoCoolHeatAirVolFlow, DataSizing::AutoSize);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:6501]: Nice, succinct unit test! :+1:

**Review by Myoldmopar — APPROVED** [review]
Good to go from my end.

**Comment by jmythms** [comment]
Merged latest develop, it built fine. Merging. Thank you very much @rraustad
