### PR TITLE
Fix #9455 and #9456 - Address water-to-air cooling coils sizing related issues

### LINKED ISSUE #9455: Calculation of autosized volumetric flow rate of Coil:Cooling:WaterToAir:EquationFit uses wrong companion coil
Issue overview
--------------
When autosized, the volumetric flow rate of `Coil:Cooling:WaterToAir:EquationFit` is determined based on the coil's *cooling* companion coil instead of *heating* coil.

https://github.com/NREL/EnergyPlus/blob/43b09606e2a93a0a1b220949d5b6832d63c0a03a/src/EnergyPlus/WaterToAirHeatPumpSimple.cc#L2055-L2061

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9456: Variable speed water-to-air coils use outdoor air temperature to size rated total capacity
Issue overview
--------------
Unlike `Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed` objects, `Coil:Cooling:WaterToAir:VariableSpeedEquationFit` objects don't have condenser inlet node inputs so EnergyPlus uses the outdoor air dry-bulb temperature at design conditions instead of the rated inlet water temperature to size the rated total cooling capacity.

https://github.com/NREL/EnergyPlus/blob/43b09606e2a93a0a1b220949d5b6832d63c0a03a/src/EnergyPlus/VariableSpeedCoils.cc#L4760-L4764

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------
 - Fixes #9455 and #9456

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [x] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 1]
```diff
@@ -4757,7 +4757,9 @@ namespace VariableSpeedCoils {
                     }
                     MixWetBulb = PsyTwbFnTdbWPb(state, MixTemp, MixHumRat, state.dataEnvrn->OutBaroPress, RoutineName);
                     // need to use OutTemp for air-cooled and RatedInletWaterTemp for water-cooled
-                    if (state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).CondenserInletNodeNum != 0) {
+                    if (state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).CondenserInletNodeNum != 0 ||
+                        state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).VSCoilTypeOfNum ==
+                            DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit) {
```
Comment (lymereJ) [inline src/EnergyPlus/VariableSpeedCoils.cc:4762]: Add an exception for variable speed equation fit water-to-air cooling coils so the outdoor air dry-bulb temperature isn't used.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 2]
```diff
@@ -4841,7 +4843,9 @@ namespace VariableSpeedCoils {
 
                     MixWetBulb = PsyTwbFnTdbWPb(state, MixTemp, MixHumRat, state.dataEnvrn->OutBaroPress, RoutineName);
                     // need to use OutTemp for air-cooled and RatedInletWaterTemp for water-cooled
-                    if (state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).CondenserInletNodeNum != 0) {
+                    if (state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).CondenserInletNodeNum != 0 ||
+                        state.dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).VSCoilTypeOfNum ==
+                            DataHVACGlobals::Coil_CoolingWaterToAirHPVSEquationFit) {
```
Comment (lymereJ) [inline src/EnergyPlus/VariableSpeedCoils.cc:4848]: Add an exception for variable speed equation fit water-to-air cooling coils so the outdoor air dry-bulb temperature isn't used.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc [hunk 3]
```diff
@@ -2055,9 +2055,14 @@ namespace WaterToAirHeatPumpSimple {
...
-                        SystemCapacity =
-                            state.dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(simpleWatertoAirHP.CompanionCoolingCoilNum).RatedCapHeat;
+                    if (simpleWatertoAirHP.CompanionHeatingCoilNum > 0) {
+                        if (state.dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(simpleWatertoAirHP.CompanionHeatingCoilNum).RatedCapHeat ==
+                            DataSizing::AutoSize) {
+                            SystemCapacity = simpleWatertoAirHP.RatedCapCoolTotal;
+                        } else {
+                            SystemCapacity =
+                                state.dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(simpleWatertoAirHP.CompanionHeatingCoilNum).RatedCapHeat;
+                        }
```
Comment (lymereJ) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2065]: Fix the companion coil reference and handle cases where the heating companion coil has not yet been sized.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 4]
```diff
@@ -8114,6 +8096,32 @@ namespace VariableSpeedCoils {
...
+            return state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).OutTempAtCoolPeak;
+        } else {
+            ShowSevereError(state,
+                            "GetVSCoilRatedSourceTemp: Could not find rated source temperature, Type= VS DX Coil Name=\"" +
+                                state.dataVariableSpeedCoils->VarSpeedCoil(CoilIndex).Name + "\"");
+            ErrorsFound = true;
+            return 0.0;
+        }
+    }
+
```
Comment (lymereJ) [inline src/EnergyPlus/VariableSpeedCoils.cc:8124]: New function that determine which rated source temperature to use.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc (hunk 3 above)
Comment (lymereJ) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2065]: Fix wrong companion cooling coil reference: a cooling coil doesn't have a companion cooling coil.

File: tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc [hunk 5]
```diff
@@ -3008,4 +3012,852 @@ TEST_F(EnergyPlusFixture, VariableSpeedCoils_ContFanCycCoil_Test)
     EXPECT_NEAR(state->dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).OutletAirHumRat, 0.00810, 0.00001);
     EXPECT_NEAR(state->dataVariableSpeedCoils->VarSpeedCoil(DXCoilNum).OutletAirEnthalpy, 25597.58, 0.01);
 }
+
+TEST_F(EnergyPlusFixture, VariableSpeedCoils_RatedSource_Temp_ASHP_Cooling)
+{
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc:3013]: New unit tests to verify that the new function that determined the rated source temperature provides the correct value for all cases currently taken into account under the variable speed coils code.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 6]
```diff
@@ -4695,12 +4695,7 @@ namespace VariableSpeedCoils {
                         SupTemp -= FanCoolLoad / (CpAir * rhoair * VolFlowRate);
                     }
                     MixWetBulb = Psychrometrics::PsyTwbFnTdbWPb(state, MixTemp, MixHumRat, state.dataEnvrn->StdBaroPress, RoutineName);
-                    // need to use OutTemp for air-cooled and RatedInletWaterTemp for water-cooled
-                    if (varSpeedCoil.CondenserInletNodeNum != 0) {
-                        RatedSourceTempCool = RatedInletWaterTemp;
-                    } else {
-                        RatedSourceTempCool = OutTemp;
-                    }
+                    RatedSourceTempCool = GetVSCoilRatedSourceTemp(state, DXCoilNum, ErrorsFound);
```
Comment (lymereJ) [inline src/EnergyPlus/VariableSpeedCoils.cc:4698]: This block of code and the next one will create diffs. Previously, only coils with a condenser inlet node input were assigned `RatedInletWaterTemp` (29.4444C) as `RatedSourceTempCool`. `Coil:Cooling:WaterToAirEquationFitVariableSpeed` objects don't have such inputs so their `RatedInletWaterTemp` was set to `OutTemp`.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 7]
```diff
@@ -8114,6 +8104,37 @@ namespace VariableSpeedCoils {
...
+        default: {
+            ShowSevereError(state,
+                            "GetVSCoilRatedSourceTemp: Could not find rated source temperature, Type= VS DX Coil Name=\"" +
+                                state.dataVariableSpeedCoils->VarSpeedCoil(CoilIndex).Name + "\"");
+            ErrorsFound = true;
+            return 0.0;
+        }
+        }
+    }
+
```
Comment (lymereJ) [inline src/EnergyPlus/VariableSpeedCoils.cc]: New function that determine which rated source temperature to use.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 8]
```diff
@@ -4695,11 +4695,10 @@ namespace VariableSpeedCoils {
...
                     }
                     MixWetBulb = Psychrometrics::PsyTwbFnTdbWPb(state, MixTemp, MixHumRat, state.dataEnvrn->StdBaroPress, RoutineName);
-                    // need to use OutTemp for air-cooled and RatedInletWaterTemp for water-cooled
-                    if (varSpeedCoil.CondenserInletNodeNum != 0) {
-                        RatedSourceTempCool = RatedInletWaterTemp;
-                    } else {
+                    if (varSpeedCoil.CondenserType == DataHeatBalance::RefrigCondenserType::Air) {
                         RatedSourceTempCool = OutTemp;
+                    } else {
+                        RatedSourceTempCool = GetVSCoilRatedSourceTemp(state, DXCoilNum, ErrorsFound);
```
Comment (lymereJ) [inline src/EnergyPlus/VariableSpeedCoils.cc:4701]: Only coils with a condenser inlet node were using `RatedInletWaterTemp` (29.4444C) as the `RatedSourceTempCool`, `Coil:Cooling:WaterToAirEquationFitVariableSpeed` objects don't have such inputs so their `RatedInletWaterTemp` was set to `OutTemp`, the OAT at design conditions. Now, the intended value is returned by the function, and `OutTemp` is still used by air-cooled coils. This will trigger diffs for files using `Coil:Cooling:WaterToAirEquationFitVariableSpeed` coils.

Comment (lymereJ) [reply src/EnergyPlus/VariableSpeedCoils.cc:4701]: Similarly, `Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed` don't have a condenser inlet node so `OutTemp` was used. However, the model is expecting a condenser inlet water temperature as the second independent variables for the capacity curve as a function of the temperature, not an outdoor air temperature. This will trigger diffs for files using `Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed` objects.

**Comment by lymereJ** [comment]
Two regression tests failed:
- One model with `Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed` objects has very minor diffs in one of the report tables. Two of the reported total capacity modifiers are different because the OAT at design peak conditions used to be used in place of the actual model input.
- One model with `Coil:Cooling:WaterToAirEquationFitVariableSpeed` objects has much more diffs (coil sizes and rated flow rates end up being different) but for very similar reasons, that is, the OAT at design peak conditions used to be used in place of the assumed `RatedInletWaterTemp`.

File: src/EnergyPlus/VariableSpeedCoils.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/VariableSpeedCoils.cc:4701]: Good

File: src/EnergyPlus/VariableSpeedCoils.cc (hunk 7 above)
Comment (rraustad) [reply src/EnergyPlus/VariableSpeedCoils.cc]: This warning will never get used, correct? Better to assert(false) here?

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2065]: I'm probably over thinking this but the point here is to size the water flow rate. Not sure what this is trying to do, keep the flow rates the same for the cooling and heating coil or something else. It seems the model should just use the rated capacity. This was already here so no need to worry about it now.

**Review by rraustad — APPROVED** [review]
This looks pretty striaght-forward.

**Comment by rraustad** [comment]
@lymereJ are there any documentation updates required here? It seems likely.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 9]
```diff
@@ -8114,6 +8104,37 @@ namespace VariableSpeedCoils {
         return Speeds;
     }
 
+    Real64 GetVSCoilRatedSourceTemp(EnergyPlusData &state,
+                                    int const &CoilIndex, // index to cooling coil
```
Comment (rraustad) [inline src/EnergyPlus/VariableSpeedCoils.cc]: CoilIndex should just be passed by value, int const CoilIndex.

**Comment by rraustad** [comment]
2 small fixes to correct and then this can merge. Docs may not required editing.

**Comment by lymereJ** [comment]
@rraustad - Thanks for the review! I just pushed changes to address your comments.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 10]
```diff
@@ -8114,6 +8104,35 @@ namespace VariableSpeedCoils {
...
+        }
+        case DataHVACGlobals::Coil_HeatingAirToAirVariableSpeed: {
+            RatedSourceTemp = RatedAmbAirTempHeat;
+        }
+        default: {
+            assert(false);
+        }
+        }
+        return RatedSourceTemp;
+    }
```
Comment (rraustad) [inline src/EnergyPlus/VariableSpeedCoils.cc:8134]: You didn't need to change the returns. And I just noticed you didn't have break at the end of each case. So 1 more correction to fix. Either add the break, or revert to the return for each case. @amirroth if there is a return for each case, do you even need the break statement?

Comment (lymereJ) [reply src/EnergyPlus/VariableSpeedCoils.cc:8134]: Oops. Thanks for pointing it out, I just added them.

**Comment by rraustad** [comment]
I have tested example files with these changes and got expected results. Code is working as expected. Unit tests run to completion. CI is clean with justifications.

**Comment by rraustad** [comment]
Final changes won't change CI results. Merging.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 11]
```diff
@@ -4695,11 +4695,10 @@ namespace VariableSpeedCoils {
...
-                    if (varSpeedCoil.CondenserInletNodeNum != 0) {
-                        RatedSourceTempCool = RatedInletWaterTemp;
-                    } else {
+                    if (varSpeedCoil.CondenserType == DataHeatBalance::RefrigCondenserType::Air) {
                         RatedSourceTempCool = OutTemp;
+                    } else {
+                        RatedSourceTempCool = GetVSCoilRatedSourceTemp(state, DXCoilNum, ErrorsFound);
                     }
                     TotCapTempModFac =
                         CurveManager::CurveValue(state, varSpeedCoil.MSCCapFTemp(varSpeedCoil.NormSpedLevel), MixWetBulb, RatedSourceTempCool);
```
Comment (rraustad) [inline src/EnergyPlus/VariableSpeedCoils.cc:4704]: I just tried to pull the new function GetVSCoilRatedSourceTemp over to the generic sizing routines and realized that this is not correct. This is how it was before and this change simply followed that methodology. However, the TotCapTempModFac curve should use the actual peak conditions (i.e., outdoor T, inlet air WB, inlet water T) used to size the coil. The TotCapTempModFac result is then used to get to a rated coil size that will meet the load at those operating conditions (i.e., RatedCapCoolTotalDes = CoolCapAtPeak / TotCapTempModFac;). If the actual rating conditions are passed to the CapFT curve, the result should be close to 1 and there will be no adjustment to capacity.

Comment (lymereJ) [reply src/EnergyPlus/VariableSpeedCoils.cc:4704]: Agreed, I'm planning to address that in #9439 as per our previous discussion for single speed water-to-air coils. I can make the same change for VS coils too if need be. As you mentioned, in this PR I kept the methodology the same and only addressed the fact the the OAT was used in place a EWT.
