### PR TITLE
Fix VRF_FluidTCtrl cooling supply fan power calculation when cycling

### LINKED ISSUE #10106: VRF cooling issue: overestimate fan power at low load
Issue overview
--------------
The simulated fan power is larger than the calculated fan power for runtime fraction < 1 cases. The following shows the difference between simulated and calculated fan power when the terminal unit is in cooling mode (heating coil RTF = 0) and heating mode (cooling coil RTF = 0)

image

The minimum fan power is calculated using information from this object
```
Fan:VariableVolume,
    TU1 VRF Supply Fan,      !- Name
    VRFAvailSched,           !- Availability Schedule Name
    0.5,                     !- Fan Total Efficiency
    400,                     !- Pressure Rise {Pa}
    0.595,                !- Maximum Flow Rate {m3/s}
    FixedFlowRate,                !- Fan Power Minimum Flow Rate Input Method
    0,                       !- Fan Power Minimum Flow Fraction
    0.415,                       !- Fan Power Minimum Air Flow Rate {m3/s}
    0.9,                     !- Motor Efficiency
    1,                       !- Motor In Airstream Fraction
    0.09,                   !- Fan Power Coefficient 1
    0,                       !- Fan Power Coefficient 2
    0,                       !- Fan Power Coefficient 3
    0.91,                   !- Fan Power Coefficient 4
    0,                       !- Fan Power Coefficient 5
    TU1 VRF DX HCoil Outlet Node,  !- Air Inlet Node Name
    TU1 VRF Fan Outlet Node,         !- Air Outlet Node Name
    General;                 !- End-Use Subcategory
```

image

defect files
- idf and epw file:
[fan.zip](https://github.com/NREL/EnergyPlus/files/13821903/fan.zip)

- excel output:
[eplusout_before_fan_correct_cooling.xlsx](https://github.com/NREL/EnergyPlus/files/13821899/eplusout_before_fan_correct_cooling.xlsx)

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.3)
 - Version of EnergyPlus (22.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Partially fixes #10106

The fan issue in the cooling part is fixed by multiplying the runtime fraction of the cooling coil (which also equals the VRF condenser cycling ratio).

This PR transitions the variable volume fan model used in the Supply Air Fan Object Type of ZoneHVAC:TerminalUnit:VariableRefrigerantFlow of a VRF FluidTCtrl system into a equivalent Fan:SystemModel with "Speed Control Method" being "continuous".

Allowing cycling of the Fan:SystemModel with continuous speed control method will be done in another follow-up PR.

### Regression diff

Regression diffs appear in the following four files
- US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF
- VariableRefrigerantFlow_FluidTCtrl_5Zone
- VariableRefrigerantFlow_FluidTCtrl_HR_5Zone
- VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone

#### eplusout.csv diffs
In VariableRefrigerantFlow_FluidTCtrl_5Zone, the idf file has the following difference due to the fan type transitioning.
image

the relative difference in eplusout.csv that are larger than 1e-12 is as follows.
image

VRF Heat Pump Cooling Electricity Rate and Energy diffs are due to changes in outdoor fan power. Similarly, VRF Heat Pump Heating Electricity Rate and Energy diffs are also caused by outdoor fan power diffs. These are expected as the outdoor fan power is changed in this feature to account for system cycling. Cooling:Electricity is affected by VRF Heat Pump Cooling/Heating Electricity, so the diffs are also expected
image

#### meter difference
The following shows the percent meter difference summary in VariableRefrigerantFlow_FluidTCtrl_5Zone. The differences are mainly in electricity outputs where fan electricity is part of (cooling, HVAC, and facility electricity rate)

image

#### table diffs

Similar to the meter differences, the diffs happen in fan electricity and related outputs where fan electricity is part of.

The following is the table diffs in VariableRefrigerantFlow_FluidTCtrl_5Zone. The default fields and autosized fields diffs are caused by converting from Fan:VariableVolume to Fan:System model. 5 more curve objects are added as a result of the conversion. The number of autosized fields increased as the design electric power is also autosized in addition to max air flow rate.

image

#### audit diff
in VariableRefrigerantFlow_FluidTCtrl_5Zone, the audit diff is as follows. The numCompSizeTableEntry diffs are because the Fan:SystemModel has two autosized fields: Max air flow rate and design electric power, while the Fan:VariableVolume only have one autosized entry: max air flow rate.

image

#### bnd diff
in VariableRefrigerantFlow_FluidTCtrl_5Zone, the bnd diff is as follows. The diffs are due to the Fan:VariableVolume to Fan:SystemModel. 
image

#### eio diff
in VariableRefrigerantFlow_FluidTCtrl_5Zone, the eio diff is as follows. The eio diffs are mainly due to the difference in the autosized fields. There are also some very small warmup convergence differences.

image
...
image

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by yujiex** [comment]
@rraustad @mjwitte this PR is ready for an initial review. Thanks

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 1]
```diff
@@ -283,6 +283,29 @@ void SimulateVRF(EnergyPlusData &state,
...
+                int fanIndex = state.dataHVACVarRefFlow->VRFTU(TUNum).FanIndex;
+                // only deal with cooling for now. heating RTF might have some issue
+                // does Fan:SystemModel need adjustment as well? if so consider 0-indexing and it's in state.dataHVACFan->fanObjs vector
+                if (fanIndex > 0 && heatingCoil.HeatingCoilRuntimeFraction == 0.0) { // in cooling mode
+                    // here coolingCoil.CoolingCoilRuntimeFraction equals state.dataHVACVarRefFlow->VRF(VRFCond).VRFCondCyclingRatio
+                    // this is not the case for heating
+                    auto &fan = state.dataFans->Fan(fanIndex);
+                    fan.FanPower *= coolingCoil.CoolingCoilRuntimeFraction;
+                    fan.FanEnergy = fan.FanPower * state.dataHVACGlobal->TimeStepSysSec;
+                    fan.PowerLossToAir *= coolingCoil.CoolingCoilRuntimeFraction;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I'm not sure I like this since here again one model is changing the result of another. The only fan models that change the "fans" result based on cycling is Fan:OnOff and Fan:SystemModel. Should this apply to a fan that operates the entire time step? The fan does not necessarily cycle with the compressor. The way this is done in other models is to set the state.dataHVACGlobal->OnOffFanPartLoadFraction variable and let the fan model decide what to do with power/energy.

    ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
      A7 ,  \field Supply Air Fan Object Type
            \type choice
            \key Fan:SystemModel
            \key Fan:OnOff
            \key Fan:ConstantVolume
            \key Fan:VariableVolume

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The VRF Fluid control model terminal unit only accepts a Fan:VariableVolume object (otherwise there will be an error message
```
Fan Object Type must be Fan:VariableVolume if VRF AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl 
```
The `Fan:VariableVolume` object is simulated in the `SimVariableVolumeFan` function. But in this function, the `state.dataHVACGlobal->OnOffFanPartLoadFraction` was not used anywhere. So I modified the function to access this global variable which holds the coil runtime fraction.

Although this affects other non-VRF-FluidCtrl models as well, as the `SimVariableVolumeFan` is not specific to the VRF model.

**Comment by yujiex** [comment]
I think the difference in COP and compressor electricity rate are expected as the cycling and low-speed-no-cycling uses different evaporating temperature. 

I did the following investigation

We observed large difference between compressor electricity rate (compressor power), and COP when one model is cycling and the other model is not cycling. The x-axis is the index of timestamps.

image

I selected this time period for a closer look. During this period the compressor in the "curve 2" model is cycling and the compressor in the "curve 1" model is always running. Columns K and Q are the compressor power calculated using Te, Tc, and compressor power curves. Columns L and R are compressor power outputs from the simulation result file.

image

The following table and plot compare the evaporative capacity. Columns K and Q are the evaporative capacity calculated using Te, Tc, and evaporative capacity curves. Columns L and R are evaporative capacity outputs from the simulation result file.

image

I compared the COP in the following table and plot. Column L and N are the COP calculated using Te, Tc, and COP curves. Columns L and R are COP outputs from the simulation result file. The COP columns are calculated using the corresponding evaporative capacity / (compressor power + OU fan power)

image

So I think the COP and Heat Pump Cooling Electricity rate difference are expected as due to the change in the evaporating temperature.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 1 above)
Comment (dareumnam) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I agree with the idea of not applying a fan that operates for the entire time step and instead letting the fan model decide how to manage the power. Even though `state.dataHVACGlobal->OnOffFanPartLoadFraction` isn't used anywhere for now, it could be used elsewhere in the future . Any insights regarding this issue would be appreciated. @rraustad @mjwitte @EnergyArchmage @Myoldmopar

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I would agree. The cooling coil should set `state.dataHVACGlobal->OnOffFanPartLoadFraction`. And this should probably be done in a separate branch?

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: @rraustad Do you mean adding `state.dataHVACGlobal->OnOffFanPartLoadFraction` access in `SimVariableVolumeFan` function should be done in another separate branch and using cooling coil RTF to set `state.dataHVACGlobal->OnOffFanPartLoadFraction` should be on this branch?

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I just checked CalcVRFCoolingCoil and CalcVRFCoolingCoil_FluidTCtrl and both already have this:

        // If cycling fan, send coil part-load fraction to on/off fan via HVACDataGlobals
        if (fanOp == HVAC::FanOp::Cycling) state.dataHVACGlobal->OnOffFanPartLoadFraction = PLF;

So there is nothing to do since the fan models already include this variable where necessary. If other fan types are used for VRF the code is already set up to model correctly.

    ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
      A7 ,  \field Supply Air Fan Object Type
        \type choice
        \key Fan:SystemModel
        \key Fan:OnOff
        \key Fan:ConstantVolume
        \key Fan:VariableVolume
        \default Fan:ConstantVolume

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The following is the note in field A7, it indicates that the `Fan:VariableVolume` fan is only allowed in `AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl` and  `AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR`, not in the curve-based VRF terminal unit (`ZoneHVAC:TerminalUnit:VariableRefrigerantFlow`). 

```
        \note Supply Air Fan Object Type must be Fan:SystemModel, Fan:OnOff, or Fan:ConstantVolume
        \note if AirConditioner:VariableRefrigerantFlow is used to model VRF outdoor unit
        \note Supply Air Fan Object Type must be Fan:SystemModel or Fan:VariableVolume if
        \note AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl or
        \note AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR
        \note is used to model VRF outdoor unit
        \note Required for zone equipment. Leave blank if terminal unit is used in AirLoopHVAC:OutdoorAirSystem:EquipmentList.
        \note Also leave blank if terminal unit is used on main AirloopHVAC branch and terminal unit has no fan.
```

I did verify that the fan in the curve-based VRF terminal unit can work properly in cycling-fan-cycling-coil. There might still be some issue in the `Fan:VariableVolume` as it doesn't involve the `state.dataHVACGlobal->OnOffFanPartLoadFraction` in its calculation (`SimVariableVolumeFan`). Since the curve-based VRF TU doesn't use the VariableVolume fan, the issue in `Fan:VariableVolume` is not triggered there. For the \*FluidTemperatureControl\* terminal units that use Fan:VariableVolume, there might still be some problem? @rraustad

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The VAV fan was never intended to cycle during the time step and so OnOffFanPartLoadFraction was never added to that fan model. When using a VAV fan, does the fan ever operate for only a portion of the time step?

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Yes. I believe the VAV fan will cycle. In the [issue description](https://github.com/NREL/EnergyPlus/issues/10106), the minimum fan power of 189.81W is the lowest the fan can operate without cycling. When the coil is cycling, the fan should also cycle and output less power.

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I'm a little concerned about adding OnOffFanPartLoadFraction to the VAV fan since it should run the entire time step. For other equipment the VAV fan can only be used with constant fan operating mode. You could certainly try it but this might cause more problems than it's worth. I am not sure if when you add OnOffFanPartLoadFraction to this fan model, if results for other configurations would change (e.g., VAV with a DX coil). If you change the fan model to OnOff do you get expected results? I am also concerned about the energy balance in the air stream which I don't think we have really focused on (i.e., HP cooling energy versus sum of TU cooling energy).

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I will try to remove the constraint of fan type and try the OnOff fan to make sure that it can properly cycle (Currently the `AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl` won't allow OnOff fan). I'm guessing it could properly cycle but I will double check.

Another question is, is the following type of fix also considered bad? If so, and that adding OnOffFanPartLoadFraction to the VAV fan is also bad, do I create a separate fan type (similar to VAV but can cycle as well), and then use this type of fan for the variable volume fan in `AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl`?
image

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: We don't need another fan type, just need to think this through carefully. I did think of using VAVOnOffFanPartLoadFraction only for the fluid cooler model but I don't like that either since we don't need more globals. An optional argument that defaults to 1 in the SimFan call may be another option, but we don't need more optional arguments. So keep thinking.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: image
This is when the OnOff fan is used. The plot shows the fan power and cooling coil RTF when the system is in cooling mode. Fan power seems not proportional with the cooling coil RTF either. I will look deeper into it.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: > We don't need another fan type, just need to think this through carefully. I did think of using VAVOnOffFanPartLoadFraction only for the fluid cooler model but I don't like that either since we don't need more globals. An optional argument that defaults to 1 in the SimFan call may be another option, but we don't need more optional arguments. So keep thinking.

Is optional arguments bad? Is overloading better (two versions, one with another argument)?

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: That is an interesting fan power (flow) profile. I assume the fan is cycling below coil RTF = 0.2. I'd have to see fan power vs coil cycling ratio to be sure. I think you could pass coil PLF, based on coil cycling ratio, over to the fan and use that in the fan power calculation (using `* PLR/PLF`). I guess I would use the optional argument = 1 method for that but others could offer suggestions.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I did some experiment using the non-fluid-control VRF model
[VariableRefrigerantFlow_5Zone.idf.txt](https://github.com/user-attachments/files/15796409/VariableRefrigerantFlow_5Zone.idf.txt)
[USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw.txt](https://github.com/user-attachments/files/15796414/USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw.txt)
I changed the "VRFFanSchedule" to always be 0.0 (fan cycling with the coil). I kinda expect the fan power to be linear with the coil runtime fraction. Do you feel this is expected?

image

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I expect to see a curved arc above the linear line from 0,0 to 1,fan power. Something like this. Not sure what the group of data is at 0.9 RTF above 200 W. So this is closer to what I expect. Pardon my hand drawing.

image

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I see. Let me check on this. I felt I've seen it more linear-looking (without the rightmost high points) when I compared it with the non-curve-based VRF one some time ago. hmm maybe I misremembered.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: This is the fan power-cooling coil RTF plot for VariableRefrigerantFlow_5Zone.idf during the whole year (restricted to cooling coil RTF not equal to 0 or 1). Again I used the Supply Air Fan Operating Mode Schedule is set to 0.

image

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: > That is an interesting fan power (flow) profile. I assume the fan is cycling below coil RTF = 0.2. I'd have to see fan power vs coil cycling ratio to be sure. I think you could pass coil PLF, based on coil cycling ratio, over to the fan and use that in the fan power calculation (using `* PLR/PLF`). I guess I would use the optional argument = 1 method for that but others could offer suggestions.

I just pushed the commit using an operational argument to allow VAV fan to cycle in the VRFFuildTCtrl model. Please see if it looks okay.

Coil cycling ratio is not an existing output variable. I saw in the code that cooling coil runtime fraction is calculated as `thisDXCoil.CoolingCoilRuntimeFraction = CompCycRatio / PLF;` PLF is calculated with some curve 
```
        if (thisDXCoil.PLFFPLR(Mode) > 0 && CompCycRatio < 1.0) {
            PLF = CurveValue(state, thisDXCoil.PLFFPLR(Mode), CompCycRatio); // Calculate part-load factor
        } else {
            PLF = 1.0;
        }
```
However since object `Coil:Cooling:DX:VariableRefrigerantFlow:FluidTemperatureControl` doesn't have the `Part Load Fraction Correlation Curve Name` field, the PLF value is always 1. Cooling coil runtime fraction will just be the same as the compressor cycling ratio (and also coil cycling ratio)?

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The cycling of the fan should be the same as the coil/compressor. But looking at the figure, where fan power should be proportional to fan PLR (or fan air flow wrt max air flow), the fan PLR is much different from the coil PLR (coil PLR = coil RTF * coil PLF). This may be normal, I don't know. Plot the fan power versus coil cycling ratio to see what that looks like. I'm still not sure what to pass to the fan model.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The following plots the fan power and cooling coil cycling ratio. The fan her is a Fan:VariableVolume.
image
[eplusout_variableVolumeFan.xlsx](https://github.com/user-attachments/files/15876696/eplusout_variableVolumeFan.xlsx)

The following plots the relationship for the Fan:OnOff.
image
[eplusout_onOffFan.xlsx](https://github.com/user-attachments/files/15876698/eplusout_onOffFan.xlsx)
@rraustad

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: This is the Fan:OnOff results and must be using a unity PLF curve? Is this the fluid cooler model? I see coil RTF basically equal to HP cycling ratio which means no impact for startup losses. The only way I know that fan power can vary like this is if air flow is not proportional to coil PLR. I'm not saying that's bad, I just don't completely understand how air flow is controlled. If I assume air flow is independent of coil PLR, for example air flow is controlled to maintain a certain suction temperature, then I would think PLF should be passed to the fan and the fan calculate RTF = fan PLR/PLF.

image

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: The coil object Coil:Cooling:DX:VariableRefrigerantFlow:FluidTemperatureControl doesn't have the Part Load Fraction Correlation Curve Name field, the PLF value is always 1. This is the Fluid cooling model indeed. I'll look at the airflow as well

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: For the OnOff fan, the fan RTF and air mass flow both resemble the fan power shape.

The following is the fan air mass flow plotted against the cooling coil runtime fraction. 

image

The following is the fan runtime fraction plotted against cooling coil runtime fraction
image
[eplusout_onOffFan_fanAirFlow_vs_coilRTF.xlsx](https://github.com/user-attachments/files/15878200/eplusout_onOffFan_fanAirFlow_vs_coilRTF.xlsx)

[US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF_onOffFan.idf.zip](https://github.com/user-attachments/files/15878204/US%2BSF%2BCZ4A%2Bhp%2Bcrawlspace%2BIECC_2006_VRF_onOffFan.idf.zip)
@rraustad

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: > This is the Fan:OnOff results and must be using a unity PLF curve? Is this the fluid cooler model? I see coil RTF basically equal to HP cycling ratio which means no impact for startup losses. The only way I know that fan power can vary like this is if air flow is not proportional to coil PLR. I'm not saying that's bad, I just don't completely understand how air flow is controlled. If I assume air flow is independent of coil PLR, for example air flow is controlled to maintain a certain suction temperature, then I would think PLF should be passed to the fan and the fan calculate RTF = fan PLR/PLF.
> 
> image

Since this PR is more about the variable volume fan (the only non-system-model one accepted by the FluidTCtrl model, maybe we can first try to figure this part out in the current PR and discuss whether to allow for OnOff fans in another separate PR? (or do you feel using OnOff fan instead of variable volume fan should be part of the fix?) Do you feel the current fix in [this commit](https://github.com/NREL/EnergyPlus/pull/10341/commits/9de83a18a2dc02f4b9a180a76a45fd3f5dda19bd) is okay or still not general enough? @rraustad

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: This branch is fine for the fans allowed for this model. Fan:SystemModel or Fan:VariableVolume. I was just trying to figure out what the fan power and air flow should look like.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I see

File: src/EnergyPlus/Fans.cc [hunk 2]
```diff
@@ -1700,7 +1701,9 @@ void FanComponent::simulateConstant(EnergyPlusData &state)
     }
 } // FanComponent::simulateConstant
 
-void FanComponent::simulateVAV(EnergyPlusData &state, ObjexxFCL::Optional<Real64 const> _pressureRise)
+void FanComponent::simulateVAV(EnergyPlusData &state,
+                               ObjexxFCL::Optional<Real64 const> _pressureRise,
+                               ObjexxFCL::Optional<Real64 const> _onOffFanPartLoadFraction)
```
Comment (rraustad) [inline src/EnergyPlus/Fans.cc]: The original VAV fan model never cycled during a time step because it was used with systems that were either on the entire time step or off the entire time step. In the case of VRF, where a VAV fan is allowed for the fluid temperature control model, this fan type could cycle. For the normal VAV model (AirloopHVAC with VAV boxes) a DX coil could be used in the air loop but the fan will not cycle. In that case the DX coil could set OnOffFanPartLoadFraction to something other than 1 and the VAV fan will then multiply by this variable even though the fan is not cycling. It's not that correcting this for VRF systems is wrong, it's that using this code with normal VAV systems could lead to inaccurate fan energy. The addition of an optional argument, only for VRF, is OK since it's only used with the VRF fluid temperature control model. But this also opens up the future possibility that other developers may try to pass this argument. Also, you are passing RTF not PLF so the variable name is misleading. I'm actually not sure if using this optional argument is the better approach (compared to a warning and eventually allowing the OnOff fan with this VRF model). Maybe if you change the variable name to FanRunTimeFraction it would be a little more clear and avoid future issues. I think I would also add a comment in the header that this optional argument is only used with VRF_FluidTCtrl.

Comment (rraustad) [reply src/EnergyPlus/Fans.cc]: The more I think about this the more I think the VAV fan model should not be changed. The VRF_FluidTCtrl model does allow the Fan:SystemModel which does account for cycling. So maybe a warning when using the VAV fan and the system cycles is the better approach ([like this](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L3447-L3457)). The user should use the fan system model when they expect the VRF will cycle the fan.

Comment (yujiex) [reply src/EnergyPlus/Fans.cc]: Thanks @rraustad for the clarification. I changed the variable name to fanRunTimeFraction and added comments to it to make sure it's only used in VRFFluidTCtrl model, not normal VAV fan model. I will discuss with other colleagues who worked on this before to see if there's a reason to limit it to variable volume fans. If it should be allowed, I will open up another PR for it.

Comment (rraustad) [reply src/EnergyPlus/Fans.cc]: I see that. I am just wondering if we should change a 20 year old fan model for this corner case or guide the user to use the correct fan model.

Comment (yujiex) [reply src/EnergyPlus/Fans.cc]: Does this mean user will have to cope with the fact that cycling with variable volume fan is not possible if they used Fan:VariableVolume? If they need cycling fan cycling coil, then they should use Fan:SystemModel? And the fix in this PR will be to add some warning for the case where Fan:VariableVolume is used in cycling fan cycling coil mode?

Comment (yujiex) [reply src/EnergyPlus/Fans.cc]: Maybe we can ask how people feel about these two options in the coming technicality meeting? @rraustad

Comment (rraustad) [reply src/EnergyPlus/Fans.cc]: That is what I am thinking, use system model for cycling cases and VAV fan or system model for constant fan cases. In fact the system model was meant to replace most other fan types so users should get comfortable with using the system model fan exclusively.

Comment (yujiex) [reply src/EnergyPlus/Fans.cc]: I see

**Comment by Myoldmopar** [comment]
Hey @yujiex could you provide a quick status update of this PR as of today?  Thanks!

**Comment by yujiex** [comment]
> Hey @yujiex could you provide a quick status update of this PR as of today? Thanks!

Hi @Myoldmopar, per last technicality meeting's suggestions, I have the following two tasks to perform in this PR
- verify that using Fan:SystemModel to replace Fan:VariableVolume can give the same result.
- add the transition code to convert Fan:VariableVolume objects in "Supply Air Fan Object Type" in "ZoneHVAC:TerminalUnit:VariableRefrigerantFlow" from Fan:VariableVolume to Fan:SystemModel

**Comment by Myoldmopar** [comment]
Thanks!!

**Comment by yujiex** [comment]
I have compared the following two fan models

```
Fan:VariableVolume,
  TU1 VRF Supply Fan,      !- Name
  VRFAvailSched,           !- Availability Schedule Name
  0.5,                     !- Fan Total Efficiency
  400,                     !- Pressure Rise {Pa}
  0.595,                   !- Maximum Flow Rate {m3/s}
  FixedFlowRate,           !- Fan Power Minimum Flow Rate Input Method
  0,                       !- Fan Power Minimum Flow Fraction
  0.415,                   !- Fan Power Minimum Air Flow Rate {m3/s}
  0.9,                     !- Motor Efficiency
  1,                       !- Motor In Airstream Fraction
  0.09,                    !- Fan Power Coefficient 1
  0,                       !- Fan Power Coefficient 2
  0,                       !- Fan Power Coefficient 3
  0.91,                    !- Fan Power Coefficient 4
  0,                       !- Fan Power Coefficient 5
  TU1 VRF DX HCoil Outlet Node,  !- Air Inlet Node Name
  TU1 VRF Fan Outlet Node, !- Air Outlet Node Name
  General;                 !- End-Use Subcategory
```
vs
```
  Fan:SystemModel,
    TU1 VRF Supply Fan,      !- Name
    VRFAvailSched,           !- Availability Schedule Name
    TU1 VRF DX HCoil Outlet Node,  !- Air Inlet Node Name
    TU1 VRF Fan Outlet Node, !- Air Outlet Node Name
    0.595,                   !- Design Maximum Air Flow Rate {m3/s}
    Continuous,              !- Speed Control Method
    0.415,                   !- Electric Power Minimum Flow Rate Fraction
    400,                     !- Design Pressure Rise {Pa}
    0.9,                     !- Motor Efficiency
    1.0,                     !- Motor In Air Stream Fraction
    476,                     !- Design Electric Power Consumption {W}
    ,                        !- Design Power Sizing Method
    ,                        !- Electric Power Per Unit Flow Rate {W/(m3/s)}
    ,                        !- Electric Power Per Unit Flow Rate Per Unit Pressure {W/((m3/s)-Pa)}
    0.5,                     !- Fan Total Efficiency
    Fan Power Curve;         !- Electric Power Function of Flow Fraction Curve Name

  Curve:Quartic,
    Fan Power Curve , !- Name
    0.09,             !- Coefficient1 Constant
    0,                !- Coefficient2 x
    0,                !- Coefficient3 x**2
    0.91,             !- Coefficient4 x**3
    0,                !- Coefficient5 x**4
    0.0,              !- Minimum Value of x
    1.0,              !- Maximum Value of x
    0.0,              !- Minimum Curve Output
    1.0,              !- Maximum Curve Output
    Dimensionless,    !- Input Unit Type for X
    Dimensionless;    !- Output Unit Type

```

However, their behavior is different and the system model still didn't consider cycling
image

**Comment by EnergyArchmage** [comment]
I think you want to relax the limits on the power curve output. 

also the minimum is a fraction in the system model, and a flow rate in the legacy input. so it should be = 0.415 / 0.595

**Comment by yujiex** [comment]
> Maximum Flow Rate

Thanks @EnergyArchmage , I changed the fan power curve min x value and output range. Together with code change in [this commit](https://github.com/NREL/EnergyPlus/pull/10341/commits/733ec7ea190a9a1e1a77627869a667f293748fad), now the SystemModel fan behaves similar to the VariableVolume fan.

image

**Comment by mjwitte** [comment]
@yujiex I added the IDDChange label here and changed the milestone to 24.2 I/O Freeze.

**Comment by yujiex** [comment]
> @yujiex I added the IDDChange label here and changed the milestone to 24.2 I/O Freeze.

Thanks @mjwitte

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 3]
```diff
@@ -485,6 +550,97 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                      OutArgs(8) = '1.0'              !- Maximum Value of x
+                      OutArgs(9) = '0.0'              !- Minimum Curve Output
+                      OutArgs(10) = '5.0'             !- Maximum Curve Output
+                      OutArgs(11) = 'Dimensionless'   !- Input Unit Type for X
+                      OutArgs(12) = 'Dimensionless'   !- Output Unit Type
+                      CurArgs = 12
+                    ENDIF
+                  ENDDO
+                ENDIF
+
```
Comment (rraustad) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90:670]: Should the VAV fan comments be removed from the idd and maybe the docs? Also, should the old fan be deleted during the transition?

    ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
     A7 ,  \field Supply Air Fan Object Type
        \type choice
        \key Fan:SystemModel
        \key Fan:OnOff
        \key Fan:ConstantVolume
        \key Fan:VariableVolume
        \default Fan:ConstantVolume
        \note Supply Air Fan Object Type must be Fan:SystemModel, Fan:OnOff, or Fan:ConstantVolume
        \note if AirConditioner:VariableRefrigerantFlow is used to model VRF outdoor unit
        \note Supply Air Fan Object Type must be Fan:SystemModel or Fan:VariableVolume if
        \note AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl or
        \note AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR
        \note is used to model VRF outdoor unit

Comment (mjwitte) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90:670]: > Should the VAV fan comments be removed from the idd and maybe the docs? Also, should the old fan be deleted during the transition?

Yes and Yes.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 4]
```diff
@@ -485,6 +571,97 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                isVariableVolume = .FALSE.
+                CALL GetNewObjectDefInIDD(ObjectName, NwNumArgs, NwAorN, NwReqFld, NwObjMinFlds, NwFldNames, NwFldDefaults, NwFldUnits)
+                nodiff = .false.
+                OutArgs(1:13) = InArgs(1:13)
+                IF (SameString(InArgs(14), 'FAN:VARIABLEVOLUME')) THEN
+                  isVariableVolume = .TRUE.
+                  OutArgs(14) = 'FAN:SYSTEMMODEL'
+                  ! create a new fan object with a new name
+                  OutArgs(15) = TRIM(InArgs(15)) // '_sysModel'
+                  sysFanName = TRIM(InArgs(15)) // '_sysModel'
```
Comment (rraustad) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Now that you have deleted the old fan you can revert changing the VRF fan name using `// '_sysModel'` because if there is a report variable with this fan's name it will no longer work.

File: tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc [hunk 5]
```diff
@@ -18157,6 +18163,9 @@ TEST_F(EnergyPlusFixture, VRF_FluidTCtrl_SupplementalHtgCoilTest)
     GetVRFInput(*state);
     state->dataHVACVarRefFlow->GetVRFInputFlag = false;
 
+    state->dataHVACGlobal->OnOffFanPartLoadFraction = 1.0;
+    state->dataHVACVarRefFlow->VRF(VRFCond).VRFCondCyclingRatio = 1.0;
+
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc]: These lines here and below can be removed once you revert changes to the VAV fan model.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 4 above)
Comment (yujiex) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: makes sense. I will use the old fan name here.

File: tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc (hunk 5 above)
Comment (yujiex) [reply tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc]: Indeed. I reverted the optional arg changes in the VAV fan model and removed these too.

**Comment by yujiex** [comment]
Should I remove the "key Fan:VariableVolume" in "A7 ,  \field Supply Air Fan Object Type" of "ZoneHVAC:TerminalUnit:VariableRefrigerantFlow" in the idd? 

If it's removed, user will encounter some idf reading error when they have a variable volume fan here. Also vav fans in the unit tests will also need to be transitioned to system model.

Or do I keep this key and throw a warning when they have a variable volume fan? 
@rraustad @mjwitte

**Comment by mjwitte** [comment]
Are you requiring Fan:SytemModel for all VRF terminal units, or just for ones served by  AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:*?

**Comment by rraustad** [comment]
The VAV fan is not allowed in the legacy model. Need to check this now for FluidTCtrl to get this check right.

            if (thisVrfTU.VRFSysNum > 0) {
                // VRFTU Supply Air Fan Object Type must be Fan:VariableVolume if VRF Algorithm Type is AlgorithmTypeFluidTCtrl
                if (state.dataHVACVarRefFlow->VRF(thisVrfTU.VRFSysNum).VRFAlgorithmType == AlgorithmType::FluidTCtrl &&
                    !(thisVrfTU.fanType == HVAC::FanType::VAV || thisVrfTU.fanType == HVAC::FanType::SystemModel)) {
                    ShowSevereError(state, cCurrentModuleObject + " = " + thisVrfTU.Name);
                    ShowContinueError(state, "Fan type specified = " + cAlphaArgs(7));
                    ShowContinueError(
                        state, "Fan Object Type must be Fan:VariableVolume if VRF AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl");
                    ShowContinueError(state, "is used to model VRF outdoor unit.");
                    ErrorsFound = true;
                }
                // VRFTU Supply Air Fan Object Type must be Fan:OnOff or Fan:ConstantVolume if VRF Algorithm Type is AlgorithmTypeSysCurve
                if (state.dataHVACVarRefFlow->VRF(thisVrfTU.VRFSysNum).VRFAlgorithmType == AlgorithmType::SysCurve &&
                    !(thisVrfTU.fanType == HVAC::FanType::OnOff || thisVrfTU.fanType == HVAC::FanType::Constant ||
                      thisVrfTU.fanType == HVAC::FanType::SystemModel)) {
                    ShowSevereError(state, cCurrentModuleObject + " = " + thisVrfTU.Name);
                    ShowContinueError(state, "Fan type specified = " + cAlphaArgs(7));
                    ShowContinueError(state,
                                      "Fan Object Type must be Fan:SystemModel, Fan:OnOff, or Fan:ConstantVolume if VRF "
                                      "AirConditioner:VariableRefrigerantFlow");
                    ShowContinueError(state, "is used to model VRF outdoor unit.");
                    ErrorsFound = true;
                }
            }

**Comment by yujiex** [comment]
> Are you requiring Fan:SytemModel for all VRF terminal units, or just for ones served by AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:*?

Just the `AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:*` ones

**Comment by yujiex** [comment]
> VRFTU Supply Air Fan Object Type must be Fan:VariableVolume

I changed the error message and removed VAV fan here

**Comment by yujiex** [comment]
> The VAV fan is not allowed in the legacy model. Need to check this now for FluidTCtrl to get this check right.
> 
> ```
>         if (thisVrfTU.VRFSysNum > 0) {
>             // VRFTU Supply Air Fan Object Type must be Fan:VariableVolume if VRF Algorithm Type is AlgorithmTypeFluidTCtrl
>             if (state.dataHVACVarRefFlow->VRF(thisVrfTU.VRFSysNum).VRFAlgorithmType == AlgorithmType::FluidTCtrl &&
>                 !(thisVrfTU.fanType == HVAC::FanType::VAV || thisVrfTU.fanType == HVAC::FanType::SystemModel)) {
>                 ShowSevereError(state, cCurrentModuleObject + " = " + thisVrfTU.Name);
>                 ShowContinueError(state, "Fan type specified = " + cAlphaArgs(7));
>                 ShowContinueError(
>                     state, "Fan Object Type must be Fan:VariableVolume if VRF AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl");
>                 ShowContinueError(state, "is used to model VRF outdoor unit.");
>                 ErrorsFound = true;
>             }
>             // VRFTU Supply Air Fan Object Type must be Fan:OnOff or Fan:ConstantVolume if VRF Algorithm Type is AlgorithmTypeSysCurve
>             if (state.dataHVACVarRefFlow->VRF(thisVrfTU.VRFSysNum).VRFAlgorithmType == AlgorithmType::SysCurve &&
>                 !(thisVrfTU.fanType == HVAC::FanType::OnOff || thisVrfTU.fanType == HVAC::FanType::Constant ||
>                   thisVrfTU.fanType == HVAC::FanType::SystemModel)) {
>                 ShowSevereError(state, cCurrentModuleObject + " = " + thisVrfTU.Name);
>                 ShowContinueError(state, "Fan type specified = " + cAlphaArgs(7));
>                 ShowContinueError(state,
>                                   "Fan Object Type must be Fan:SystemModel, Fan:OnOff, or Fan:ConstantVolume if VRF "
>                                   "AirConditioner:VariableRefrigerantFlow");
>                 ShowContinueError(state, "is used to model VRF outdoor unit.");
>                 ErrorsFound = true;
>             }
>         }
> ```

I changed the error message and removed VAV fan here @rraustad

**Comment by yujiex** [comment]
@mjwitte @rraustad @Myoldmopar @dareumnam the unit test mentioned yesterday are fixed now. Please see if there are other issues to be addressed. Thanks.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 6]
```diff
@@ -485,6 +570,95 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                    IF (SameString(OldFanVO(Num3)%oldFanName, sysFanName)) THEN
+                      CALL GetNewObjectDefInIDD(ObjectName, NwNumArgs, NwAorN, NwReqFld, NwObjMinFlds, NwFldNames, NwFldDefaults, NwFldUnits)
+                      OutArgs(1) = TRIM(sysFanName)
+                      OutArgs(2) = OldFanVO(Num3)%availSchedule
+                      OutArgs(3) = OldFanVO(Num3)%inletAirNodeName
+                      OutArgs(4) = OldFanVO(Num3)%outletAirNodeName
+                      OutArgs(5) = OldFanVO(Num3)%maxAirFlow_str
+                      OutArgs(6) = 'Continuous'                             !- Speed Control Method
+                      IF (SameString(OldFanVO(Num3)%minFlowInputMethod, "FixedFlowRate")) THEN
+                        OutArgs(7) = OldFanVO(Num3)%maxAirFlow_str
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90:603]: This should be 
`OutArgs(7) = OldFanVO(NumOldFanVO)%fanPowerMinAirFlow_str / OldFanVO(Num3)%maxAirFlow_str`

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 7]
```diff
@@ -485,6 +570,95 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                  DO Num3 = 1, NumFanVariableVolume
+                    IF (SameString(OldFanVO(Num3)%oldFanName, sysFanName)) THEN
+                      CALL GetNewObjectDefInIDD(ObjectName, NwNumArgs, NwAorN, NwReqFld, NwObjMinFlds, NwFldNames, NwFldDefaults, NwFldUnits)
+                      OutArgs(1) = TRIM(sysFanName)
+                      OutArgs(2) = OldFanVO(Num3)%availSchedule
+                      OutArgs(3) = OldFanVO(Num3)%inletAirNodeName
+                      OutArgs(4) = OldFanVO(Num3)%outletAirNodeName
+                      OutArgs(5) = OldFanVO(Num3)%maxAirFlow_str
+                      OutArgs(6) = 'Continuous'                             !- Speed Control Method
+                      IF (SameString(OldFanVO(Num3)%minFlowInputMethod, "FixedFlowRate")) THEN
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90:602]: This field in Fan:SystemModel is "Electric Power Minimum Flow Rate Fraction", so
if the old fan is FixedFlowRate then the new field should be old `fanPowerMinAirFlow_str  \ `maxAirFlow_str`
If `maxAirFlow_str` is autosize, and `fanPowerMinAirFlow_str` is > 0, then throw a warning and set this field to 0

if the old fan is Fraction, then this field = old fan `minAirFlowFrac_str`.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 8]
```diff
@@ -485,6 +570,95 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                            WRITE(OutArgs(7), '(F15.5)') (maxAirFlow * minAirFlowFrac)
+                          ELSE ! don't know how to multiply fraction with autosize
+                            OutArgs(7) = ''
+                          ENDIF
+                        ENDIF
+                      ENDIF
+                      OutArgs(8) = OldFanVO(Num3)%pressureRise_str          !- Design Pressure Rise {Pa}
+                      OutArgs(9) = OldFanVO(Num3)%motorEfficiency           !- Motor Efficiency
+                      OutArgs(10) = OldFanVO(Num3)%motorInAirStreamFrac     !- Motor In Air Stream Fraction
+                      IF (.NOT. SameString(OldFanVO(Num3)%maxAirFlow_str, "AUTOSIZE")) THEN
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: No need to calculate a value for "Design Electric Power Consumption {W}" `OutArgs(11)`. It can be set to Autosize and then set the next field 12 "Design Power Sizing Method" to TotalEfficiencyAndPressure which is the method used by Fan:VariableVolume.
Set outargs 13 and 14 to blank.

**Review by mjwitte — CHANGES_REQUESTED** [review]
@yujiex I tested the transition with the four test files that use AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl* and US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF failed to run. See comments below which should fix this.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 8 above)
Comment (mjwitte) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Note that the example files will need to be re-transitioned.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 7 above)
Comment (yujiex) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90:602]: make sense. I will change it to this calculation logic

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 8 above)
Comment (yujiex) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Thanks. I just changed the `Design Electric Power Consumption` to use autosize and `Design Power Sizing Method` to `TotalEfficiencyAndPressure`. I'll also re-transition the example files

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 9]
```diff
@@ -485,6 +570,90 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                      ObjectName = 'Curve:Quartic'
+                      CALL GetNewObjectDefInIDD(ObjectName, NwNumArgs, NwAorN, NwReqFld, NwObjMinFlds, NwFldNames, NwFldDefaults, NwFldUnits)
+                      OutArgs(1) = TRIM(sysFanName) // '_curve'
+                      OutArgs(2) = OldFanVO(Num3)%coeff1             !- Coefficient1 Constant
+                      OutArgs(3) = OldFanVO(Num3)%coeff2             !- Coefficient2 x
+                      OutArgs(4) = OldFanVO(Num3)%coeff3             !- Coefficient3 x**2
+                      OutArgs(5) = OldFanVO(Num3)%coeff4             !- Coefficient4 x**3
+                      OutArgs(6) = OldFanVO(Num3)%coeff5             !- Coefficient5 x**4
+                      READ(OldFanVO(Num3)%fanPowerMinAirFlow_str, '(F15.5)') fanPowerMinAirFlow
+                      WRITE(OutArgs(7), '(F10.7)') (fanPowerMinAirFlow / maxAirFlow)  !- Minimum Value of x
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: I would just write 0.0 here. The min flow setting in the fan will limit this, and if the user changes that, they might not know to change this to match.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 10]
```diff
@@ -485,6 +570,90 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                        IF (.NOT. SameString(OldFanVO(Num3)%maxAirFlow_str, "AUTOSIZE")) THEN
+                          READ(OldFanVO(Num3)%fanPowerMinAirFlow_str, '(F15.5)') fanPowerMinAirFlow
+                          READ(OldFanVO(Num3)%maxAirFlow_str, '(F15.5)') maxAirFlow
+                          WRITE(OutArgs(7), '(F15.5)') (fanPowerMinAirFlow / maxAirFlow)
+                      ELSE ! maxAirFlow_stris autosize
+                          READ(OldFanVO(Num3)%fanPowerMinAirFlow_str, '(F15.5)') fanPowerMinAirFlow
+                          IF (.NOT. fanPowerMinAirFlow == 0) THEN ! don't know how to do division with autosize
+                            CALL writePreprocessorObject(DifLfn, PrognameConversion, 'Warning', &
+                                    'Cannot calculate Electric Power Minimum Flow Rate Fraction for' // sysFanName // &
+                                            'when Maximum Flow Rate is autosize and Fan Power Minimum Air Flow Rate is non-zero')
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: This should also call `ShowWarningError` so that the transition audit will show there was an issue.
Writing the preprocessor object also is good so that the warning will stay with the idf file, but I would add more context, something like:
Cannot calculate Electric Power Minimum Flow Rate Fraction for Fan:SystemModel=' // sysFanName // &
                                            'when old Fan:VariableVolume Maximum Flow Rate is autosize and Fan Power Minimum Air Flow Rate is non-zero'
Electric Power Minimum Flow Rate Fraction is set to zero.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 [hunk 11]
```diff
@@ -485,6 +570,90 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
...
+                      CALL GetNewObjectDefInIDD(ObjectName, NwNumArgs, NwAorN, NwReqFld, NwObjMinFlds, NwFldNames, NwFldDefaults, NwFldUnits)
+                      OutArgs(1) = TRIM(sysFanName)
+                      OutArgs(2) = OldFanVO(Num3)%availSchedule
+                      OutArgs(3) = OldFanVO(Num3)%inletAirNodeName
+                      OutArgs(4) = OldFanVO(Num3)%outletAirNodeName
+                      OutArgs(5) = OldFanVO(Num3)%maxAirFlow_str
+                      OutArgs(6) = 'Continuous'                             !- Speed Control Method
+                      IF (SameString(OldFanVO(Num3)%minFlowInputMethod, "FixedFlowRate")) THEN
+                        IF (.NOT. SameString(OldFanVO(Num3)%maxAirFlow_str, "AUTOSIZE")) THEN
+                          READ(OldFanVO(Num3)%fanPowerMinAirFlow_str, '(F15.5)') fanPowerMinAirFlow
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Nitpicking here, but it's better to use `ProcessNumber` instead of `READ` to protect against an incoming values that isn't really a number and could cause transition to crash. See example usage here:
https://github.com/NREL/EnergyPlus/blob/342372be71855580101fbeebcd3696bb94961b51/src/Transition/CreateNewIDFUsingRulesV8_8_0.f90#L980-L982

**Review by mjwitte — COMMENTED** [review]
@yujiex This is much better, the transitioned files with the new fan run now without errors.
When run with v24.1 with old fan and new fan, the results are nearly identical.
When run with this branch, the change in heating electricity seems high, so that needs further review.
Some further comments below.
And be sure to merge in develop so we get some updated diffs.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 9 above)
Comment (yujiex) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Make sense. I'll just set the min value for x 0.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 10 above)
Comment (yujiex) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Good point. I added the ShowWarningError and changed the error message content to provide more info.

File: src/Transition/CreateNewIDFUsingRulesV24_2_0.f90 (hunk 11 above)
Comment (yujiex) [reply src/Transition/CreateNewIDFUsingRulesV24_2_0.f90]: Thanks. I just changed the `READ` to `ProcessNumber`. I'll take a note of this function and remember to use it next time.

**Comment by yujiex** [comment]
@mjwitte I have addressed the recent three comments above. I will look into the high changes in heating electricity later today.

File: src/EnergyPlus/DXCoils.cc [hunk 12]
```diff
@@ -16880,7 +16880,7 @@ void CalcVRFCoolingCoil_FluidTCtrl(EnergyPlusData &state,
         }
 
         // If cycling fan, send coil part-load fraction to on/off fan via HVACDataGlobals
-        if (fanOp == HVAC::FanOp::Cycling) state.dataHVACGlobal->OnOffFanPartLoadFraction = PLF;
+        if (fanOp == HVAC::FanOp::Cycling) state.dataHVACGlobal->OnOffFanPartLoadFraction = thisDXCoil.CoolingCoilRuntimeFraction;
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc]: I don't recall why this passes RTF now when it should pass PLF?

Comment (yujiex) [reply src/EnergyPlus/DXCoils.cc]: So that the runtime fraction can be passed into fan simulation here
image

**Review by mjwitte — APPROVED** [review]
With the outdoor fan adjustment removed, I'm good with this PR, but I have not reviewed the actual VRF code changes. Transition is good, and comparative results look good.

File: src/EnergyPlus/DXCoils.cc (hunk 12 above)
Comment (rraustad) [reply src/EnergyPlus/DXCoils.cc]: I see, you're passing the mass flow rate and RTF for speed 1 and then 0's for massflowrate2 and RTF2 to trick the fan model. But then the fan model also uses state.dataHVACGlobal->OnOffFanPartLoadFraction to calculate a local RTF. So don't change line 16883, leave it as PLF. Then in the call to the fan, pass the correct RTF. Actually, I don't think this is correct because `thisDXCoil.CoolingCoilRuntimeFraction` will not be the same as `_locRuntimeFrac` (that may not be a bad thing). I think you should pass PLF to the fan (using state.dataHVACGlobal->OnOffFanPartLoadFraction) and then let the fan calculate the _locRuntimeFrac to use for energy calculations, but I'm not actually sure since the coil PLF applies to the load and the fan PLF applies to the air flow. When the coil load and air flow are disconnected like they are in this VRF model, all bets are off as to what is happening.

    Real64 _locRuntimeFrac = (state.dataHVACGlobal->OnOffFanPartLoadFraction >= 1.0)
                                 ? _localFlowFrac
                                 : max(0.0, min(1.0, _localFlowFrac / state.dataHVACGlobal->OnOffFanPartLoadFraction));

Comment (yujiex) [reply src/EnergyPlus/DXCoils.cc]: In the case where the fan is Continuous (the one corresponding to VAV fan in the VRF FluidTCtrl model), this is is how the _locRuntimeFrac is currently computed
```
                if (_useFlowRatiosAndRunTimeFracs) {
                    _locFlowRatio = _localFlowRatio[mode];
                    _locRuntimeFrac = _localRuntimeFrac[mode];
                } else {
                    _locFlowRatio = _localFlowFrac;
                    _locRuntimeFrac = 1.0;
                }
```
and the `_localRuntimeFrac` is calculated like this
```
        if (present(_flowRatio1) && present(_flowRatio2) && present(_runTimeFrac1) && present(_runTimeFrac2)) {
            _useFlowRatiosAndRunTimeFracs = true;
            _localRuntimeFrac[0] = _runTimeFrac1;
            _localRuntimeFrac[1] = _runTimeFrac2;
            _localFlowRatio[0] = _flowRatio1;
            _localAirMassFlow[0] = _localFlowRatio[0] * maxAirMassFlowRate * _localRuntimeFrac[0];
            _localFlowRatio[1] = _flowRatio2;
            _localAirMassFlow[1] = _localFlowRatio[1] * maxAirMassFlowRate * _localRuntimeFrac[1];
        } else {
            _localRuntimeFrac[0] = 1.0; // if runTimeFracs are not present, assume single-mode operation
            _localRuntimeFrac[1] = 0.0; // if runTimeFracs are not present, assume single-mode operation
        }
```
Should I change these to using the calculation like in the Discrete fan case like this?
```
Real64 _locRuntimeFrac = (state.dataHVACGlobal->OnOffFanPartLoadFraction >= 1.0)
                             ? _localFlowFrac
                             : max(0.0, min(1.0, _localFlowFrac / state.dataHVACGlobal->OnOffFanPartLoadFraction));
```
@rraustad

Comment (rraustad) [reply src/EnergyPlus/DXCoils.cc]: I would not change the fan model. I am just pointing out what I see that looks odd. PLF and RTF are an energy adjustment and I am trying to understand how coil PLR/PLF = RTF affect the fan energy. In other cycling coil/system models the fan air flow and coil load are dependent/proportional. In this model they are independent. I think just pass PLF over to the fan and leave it there for now.

Comment (yujiex) [reply src/EnergyPlus/DXCoils.cc]: So I think this VRF coil doesn't have a "Part Load Fraction Correlation Curve Name" field. 
PLF is computed like this
```
        if (thisDXCoil.PLFFPLR(Mode) > 0 && CompCycRatio < 1.0) {
            PLF = CurveValue(state, thisDXCoil.PLFFPLR(Mode), CompCycRatio); // Calculate part-load factor
        } else {
            PLF = 1.0;
        }

        if (PLF < 0.7) {
            if (thisDXCoil.ErrIndex2 == 0) {
                ShowWarningMessage(
                    state,
                    format(
                        "The PLF curve value for the DX cooling coil {} ={:.3R} for part-load ratio ={:.3R}", thisDXCoil.Name, PLF, PartLoadRatio));
                ShowContinueErrorTimeStamp(state, "PLF curve values must be >= 0.7. PLF has been reset to 0.7 and simulation is continuing.");
                ShowContinueError(state, "Check the IO reference manual for PLF curve guidance [Coil:Cooling:DX:SingleSpeed].");
            }
            ShowRecurringWarningErrorAtEnd(
                state, thisDXCoil.Name + ", DX cooling coil PLF curve < 0.7 warning continues...", thisDXCoil.ErrIndex2, PLF, PLF);
            PLF = 0.7;
        }
```
So PLF will constantly be 1. But the coil do cycle. So I feel fan should not have `PLF = 1` be passed into the system fan calculation all the time. Is this right? @rraustad

Comment (Myoldmopar) [reply src/EnergyPlus/DXCoils.cc]: @yujiex @rraustad just pinging here to see if there is still work to do here and try to get this wrapped.

**Comment by dareumnam** [comment]
@yujiex, It would be appreciated if you could update the plots following your recent commits that addressed @rraustad's comments.

**Comment by yujiex** [comment]
> @yujiex, It would be appreciated if you could update the plots following your recent commits that addressed @rraustad's comments.

@dareumnam, I'm still confirming with Rich about the role of PLF on this fan. I will update the plot in a bit after I finalized it.

**Comment by yujiex** [comment]
Thanks for the discussions today.

To summarize, the original issue was that the TU supply fan (Fan:VariableVolume) was set to run on cycling fan cycling coil mode, and we observed that when coil's runtime fraction is < 1, the fan power stays the same.

I transitioned it to system model hoping it can do cycling as well. I achieved it by passing in the coil RTF as follows
```
if (fanOp == HVAC::FanOp::Cycling) state.dataHVACGlobal->OnOffFanPartLoadFraction = thisDXCoil.CoolingCoilRuntimeFraction;
...
if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).fanOp == HVAC::FanOp::Cycling) {
        OnOffFanPartLoadFraction = state.dataHVACGlobal->OnOffFanPartLoadFraction;
    }
// if draw through, simulate coils then fan
if (this->fanPlace == HVAC::FanPlace::DrawThru) {
    auto *fan = state.dataFans->fans(state.dataHVACVarRefFlow->VRFTU(VRFTUNum).FanIndex);
    if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).fanType == HVAC::FanType::SystemModel) {
        if (OnOffAirFlowRatio > 0.0) {
            fan->simulate(state,
                          FirstHVACIteration,
                          _,
                          _,
                          _,
                          fan->inletAirMassFlowRate,
                          OnOffFanPartLoadFraction,    // <- pass in the coil RTF here for now to account for the cycling temporarily
                          0,
                          0,
                          _);
        ...
        }
    ...
    }
...
}
```

According to @rraustad and @EnergyArchmage , the variable volume fan transitioned to the continuous mode Fan:System model should still run all the time when coil cycles. There should be a warning telling user that they should not use cycling fan mode when they have variable volume fan (Fan:System model with continuous mode). 

If this is the intention of how the system fan model works, then I guess the major contribution to the PR would be to throw a warning telling user that they shouldn't expect the fan to cycle because they used a wrong type of fan.

If the intention is to allow a continuous system fan (transitioned from the variable volume fan) to also cycle on off when it's at lowest speed, then we can do it like the code chunk above?

The reason I thought the continuous system fan is capable of cycling is that inside the `calcSimpleSystemFan` function, the fan power is computed like this where a `_locRuntimeFrac` was multiplied in.
```
Real64 _localFanPower =
    max(0.0, _locRuntimeFrac * _localPowerFrac * maxAirMassFlowRate * _localPressureRise[mode] / (_localTotalEff * rhoAirStdInit));
...
totalPower += _localFanPower;
```
and the `_locRuntimeFrac` gets value from the input argument of the function
```
void FanSystem::calcSimpleSystemFan(
    EnergyPlusData &state,
    ObjexxFCL::Optional<Real64 const> _flowFraction, // Flow fraction for entire timestep (not used if flow ratios are present)
    ObjexxFCL::Optional<Real64 const> _pressureRise, // Pressure difference to use for DeltaPress
    ObjexxFCL::Optional<Real64 const> _flowRatio1,   // Flow ratio in operating mode 1
    ObjexxFCL::Optional<Real64 const> _runTimeFrac1, // Run time fraction in operating mode 1
    ObjexxFCL::Optional<Real64 const> _flowRatio2,   // Flow ratio in operating mode 2
    ObjexxFCL::Optional<Real64 const> _runTimeFrac2, // Run time fraction in operating mode 2
    ObjexxFCL::Optional<Real64 const> _pressureRise2 // Pressure difference to use for operating mode 2
) {
  ...

  if (present(_flowRatio1) && present(_flowRatio2) && present(_runTimeFrac1) && present(_runTimeFrac2)) {
      _useFlowRatiosAndRunTimeFracs = true;
      _localRuntimeFrac[0] = _runTimeFrac1;
      _localRuntimeFrac[1] = _runTimeFrac2;
      _localFlowRatio[0] = _flowRatio1;
      _localAirMassFlow[0] = _localFlowRatio[0] * maxAirMassFlowRate * _localRuntimeFrac[0];
      _localFlowRatio[1] = _flowRatio2;
      _localAirMassFlow[1] = _localFlowRatio[1] * maxAirMassFlowRate * _localRuntimeFrac[1];
  } else {
  ...
  }
  ...
  if (_useFlowRatiosAndRunTimeFracs) {
      _locFlowRatio = _localFlowRatio[mode];
      _locRuntimeFrac = _localRuntimeFrac[mode];
  } else {
      _locFlowRatio = _localFlowFrac;
      _locRuntimeFrac = 1.0;
  }
  ...
}
```

**Comment by Myoldmopar** [comment]
@rraustad quick check here.  Do you want to discuss this on a call before this proceeds?  I'm inclined to one of two options:
 - Discuss this further on a call today, or worse Monday
 - Get this cleaned up enough to go in today and deal with any further internal changes after IO freeze

**Comment by rraustad** [comment]
Well, @yujiex has a good point. Passing in the RTF of the coil allows the VAV fan to cycle. E+ never allowed the VAV fan to cycle because it was intended to run the entire time step. If passing in RTF simulates a cycling VAV fan (i.e., a Fan:SystemModel set to continuous) then I think it's OK to allow that. We just did not allow this before because we didn't think outside the box. This will only affect VRF FluidTCtrl for now but allows a method to cycle a VAV fan (via the system fan model) for other parent equipment if needed. I think this is OK.

**Comment by EnergyArchmage** [comment]
I can't really form an opinion on this on a useful timescale. I pulled the branch but am bogged down trying to digest these changes to fan calling.

**Comment by yujiex** [comment]
Currently, I have reverted the part where the coil RTF is passed in. So right now, the continuous-mode system fan does not allow cycling at minimum fan power. 

Do we put the part where the fan cycling is allowed (by passing in the coil RTF) in a follow-up non-IO PR? Or if we decided we still don't allow that in the end, we'll put a warning or error message in that follow-up non-IO PR?

**Comment by rraustad** [comment]
@yujiex I am relying on the testing being done with VRF FluidTCtrl to determine what improvements are needed for that model. Constant and cycling fan can certainly be modeled now and if you think it's necessary to allow cycling of a Fan:SystemModel using continuous mode then that is acceptable as long as the results show proper results. There is no need to add that functionality back in to this branch.

**Comment by yujiex** [comment]
@rraustad I see. If we decided to allow continuous Fan:SystemModel to cycle, I'll do it in another PR. This current PR will just be the transition part.

**Comment by yujiex** [comment]
I just pulled develop. If there's not major unexpected regression diffs, would this PR be good to go as is?

**Comment by Myoldmopar** [comment]
OK, this doesn't appear to affect anything outside of the expected few files. I'm inclined to merge.  If anyone wants to hold this up, speak up soon.  Otherwise this will go in with follow-ups as needed.

**Comment by Myoldmopar** [comment]
Alright, tested fine, let the merging continue.  Thanks @yujiex for this set of changes.  I know there may still be follow-up work to do.  @dareumnam, thanks for helping keep me updated on this PR.  And @mjwitte and @rraustad thanks for looking this over!  Merging!

**Comment by yujiex** [comment]
Thanks @rraustad @mjwitte @Myoldmopar @dareumnam for reviewing. I'll work on the followup PR and hope I can resolve that part soon.
