### PR TITLE
Fix several issues in checkSubSurfAzTiltNorm() and GetSurfaceData() (lcsz assignment, enum loop etc)

### LINKED ISSUE #9893: Several potential issues in checkSubSurfAzTiltNorm()
Issue overview
--------------
Several issues found in the checkSubSurfAzThiltNorm():

Issue No. 1:
While examining some surface geometry related code lines, the following was spotted as a possible typo here:
https://github.com/NREL/EnergyPlus/blob/0c9cf289dbe7d3a146b6f91b3109d320d6fcb7e0/src/EnergyPlus/SurfaceGeometry.cc#L3044

The context is like this:
```
        Vectors::CompareTwoVectors(baseSurface.NewellSurfaceNormalVector, subSurface.NewellSurfaceNormalVector, sameSurfNormal, 0.001);
        if (sameSurfNormal) { // copy lcs vectors
            // Prior logic tested for azimuth difference < 30 and then skipped this - this caused large diffs in
            // CmplxGlz_MeasuredDeflectionAndShading Restoring that check here but will require further investigation (MJW Dec 2015)
            if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
                subSurface.lcsx = baseSurface.lcsx;
                subSurface.lcsy = baseSurface.lcsy;
                subSurface.lcsy = baseSurface.lcsy;
            }
```

The three lines is basically  assigning local coordinates axis vectors of the base surface to the subsurface, so it make sense that all `x`, `y`, and `z` coordinate vectors get assigned. Other wise the third line would just be redundant and can be removed.

A little bit further digging in the legacy vectors/surface processing code reveals that `.lcsz` vector of a surface is actually the surface's normal vector.

So this typo was probably not really causing a big problem, due to the condition of `sameSurfNormal` has to be true for these three lines to be executed. From the vector comparison above, the normal vectors should be very close (about a tolerance of `0.001`). So the missing `.lcsz` (basically the normal vector) assigning will probably still give very close results in most cases. But still, this typo should be fixed (or as a redundant line and gets removed).

Further, a minor issue No. 2 here: 
https://github.com/NREL/EnergyPlus/blob/c3360fbc6b67956065ab00dda8cdaf533d397c3c/src/EnergyPlus/SurfaceGeometry.cc#L1603-L1605

and also here:
https://github.com/NREL/EnergyPlus/blob/c3360fbc6b67956065ab00dda8cdaf533d397c3c/src/EnergyPlus/SurfaceGeometry.cc#L1782

These two place are little bit confusing in what the `Loop` variable really stands for (without looking for the comments and the code context). However, since there are already `enum` types and values defined for this, it would be much clearer to use the `enum` type to revise these two loops, such as:
```
for (const DataSurfaces::SurfaceClass Loop : state.dataSurfaceGeometry->BaseSurfIDs) {
```

Another issue No.3 here:
https://github.com/NREL/EnergyPlus/blob/0c9cf289dbe7d3a146b6f91b3109d320d6fcb7e0/src/EnergyPlus/SurfaceGeometry.cc#L3047-L3053

These should not be done. Actually, the angle it changed before and after are not the same angle, it will cause the surface orientation to be shifted (although small, < 0.02 degree). However, the changes are not necessary and these lines can be removed. I think the original intention might be to set the small angles close to the north to zero---in this case, it could be just set these two angles to zero instead to clear the small angle, rather than the expression to set it to a small angle even further from the original value. But anyway, removing these lines might be a better resolution in general.

And then Issue No.4 here:
https://github.com/NREL/EnergyPlus/blob/0c9cf289dbe7d3a146b6f91b3109d320d6fcb7e0/src/EnergyPlus/SurfaceGeometry.cc#L3037-L3045

For the `if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance)` condition, it should (will) never be true in this block, IF the Azimuth angles (see PR #9606) and the Azimuth angles difference (see Issue #9910) are both calculated correctly. This  because this block is under the condition that the parent `if (sameSurfNormal)` needs to be true. Given that `warningTolerance` is 30 degrees of angle, with a `sameSurfNormal` difference smaller than the tolerance of 0.001, the azimuth angle differences should never reached to that high to 30 degrees.

For here, if all the other logics were corrected (Azimuth angle calculation, Azimuth angles difference calculation), this block will not execute for sure. Or on the other hand, the block content can be set to always execute by removing the Azimuth angles comparison `if`, since the logic meaning of this block is to set the `lcsx`, `lcsy`, and `lcxz` to be the same if the `sameSurfNormal` is true (a much smaller tolerance of 0.001).

In addition, the `CmplxGlz_MeasuredDeflectionAndShading` mentioned in the comment note no longer exists after a couple of text search in throughout the entire code solution. So probably it would not cause more diffs that contributes to this function in this regard.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v23.1 pre-release, possibly been in older version for a while as well.
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes a few code issues described in #9893 
 - Fixed a code typo where the z-axis `lcsz` values of the sub-surface (e.g. a window) were not properly assigned to the base surface's z-axis `lcsz` values. In the original code there is a repeated lines for `lcsy` assignment by mistake---which is supposed to be `lcsz` according to the context.
 - Also revised a couple of loops for surface types (wall, floor, roof) where integers were originally used, which is largely affect the code readability---and actually also represent a gap (by implicitly assuming that wall, floor, and roof types are corresponding to integers 1, 2, 3 by default). Since there are already an `enum` class type and values set up for these, it would be better to revise these two loops using the `enum`s.
 - Another change is the removal of a few code lines that was originally probably intended for bringing some azimuth angles very close to the North (close to 360 degree but still in the Northwest quadrant) to zero---but it is likely that these code line are doing so in correctly---and possibly unnecessarily increased the "artificial adjustment" magnitude by doubling the difference. These lines actually could be removed.

Diffs: To investigate the diffs, the original last commit (0c84ea9) was reverted to reduce the complexity of the diff analysis.
There are some small math diffs in one file named "ASHRAE901_Warehouse_STD2019_Denver.idf". The details are like this:
```
Date/Time | Electricity:Facility [J](Hourly) | ElectricityNet:Facility [J](Hourly) | NaturalGas:Facility [J](Hourly)
average: | 9.69E-08 | 9.69E-08 | 5.72E-06
```
The case has a large horizontal roof that has many (>30?) skylight windows, where a few of the windows gets the following code block activated that caused the small energy usage diffs:
```
            if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
                subSurface.lcsx = baseSurface.lcsx;
                subSurface.lcsy = baseSurface.lcsy;
                subSurface.lcsy = baseSurface.lcsy; // original code; new code would be "subSurface.lcsz = baseSurface.lcsz;" instead
            }
```
For example, the computation of the .lcsz was slightly off for a baseSurface (named "SKYLIGHT_R6C2" in the idf) but was well within the tolerance (the x-value): `lcsz	{x=-5.5690501951681650e-16 y=0.0000000000000000 z=1.0000000000000000 }`
This will corrected by the above code lines to have the same value as the base surface's value  of `{x=0.0000000000000000 y=0.0000000000000000 z=1.0000000000000000 }`. 

Similar changes will also apply to a few other another skylight windows, such as one named "SKYLIGHT_R7C2". These very minor corrections caused the very changes in the heat balance via the skylight windows and the roof, which was then reflected on the minor diffs on the electricity and natural gas usage.

Note that here there is a commit 0c84ea94b684b9 got reverted for the reason of explaining the diffs. The commit deals with removing the following `if` condition in the code:
```
            // Prior logic tested for azimuth difference < 30 and then skipped this - this caused large diffs in
            // CmplxGlz_MeasuredDeflectionAndShading Restoring that check here but will require further investigation (MJW Dec 2015)
            if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
```

This commit was originally also included in the current PR. However, with this commit it will have much more diffs mingled with the previous changes. Therefore it should be nice to merge in what's currently in here first---and I will do a separate follow up PR for the reverted commit, wit separated diffs investigations.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 1]
```diff
@@ -3034,21 +3034,21 @@ namespace SurfaceGeometry {
...
+            // }
         } else {
-            // Not sure what this does, but keeping for now (MJW Dec 2015)
-            if (std::abs(subSurface.Azimuth - 360.0) < 0.01) {
-                subSurface.Azimuth = 360.0 - subSurface.Azimuth;
-            }
-            if (std::abs(baseSurface.Azimuth - 360.0) < 0.01) {
-                baseSurface.Azimuth = 360.0 - baseSurface.Azimuth;
-            }
+            // // Not sure what this does, but keeping for now (MJW Dec 2015)
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:3062]: This code was originally added in https://github.com/NREL/EnergyPlusArchive/commit/eadb8cebe8bcee13f1f60f3e932f08c1adfcfd70. There's no mention of a specific issue it was addressing.

**Comment by mjwitte** [comment]
There are a couple of files showing diffs.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 1 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc:3062]: I guess the original intention is trying to bring down a large angle close to 360 to something to a small angle. However, the problem is that is should equal to `baseSurface.Azimuth-360` instead (strictly speaking)---which is actually different from the angle `360-baseSurface.Azimuth`. This will introduce an error about 2 times `abs(baseSurface.Azimuth-360.0)` (which is small though)---if it has to be this way, then actually even setting the angle to zero would be better (with only 1 times `abs(baseSurface.Azimuth-360)` error introduced). 

But anyway, these lines are not needed at all, especially when the "rotational" angle difference is used (see Issue #9910 and PR #9920). I feel relatively confident that these line could (actually should) be removed without any problems.

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@jcyuan2020 This is still marked draft. Is it ready for final review?

**Comment by jcyuan2020** [comment]
> @jcyuan2020 This is still marked draft. Is it ready for final review?

Added a diff analysis to the top comments. It should be good for final review now.

**Comment by Myoldmopar** [comment]
@jcyuan2020 thanks for the diff analysis, and clear explanation of the basis of these changes.  I'll look over the code changes now.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:3062]: I am OK with this.  For our calculations, there really shouldn't be any special reason that we need to bring them to 360, and as you stated, it seems to be doing it slightly different than intended anyway.  If anyone has an issue with this, please speak up.  (@JasonGlazer?)

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 2]
```diff
@@ -3056,16 +3056,16 @@ namespace SurfaceGeometry {
             if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
                 subSurface.lcsx = baseSurface.lcsx;
                 subSurface.lcsy = baseSurface.lcsy;
-                subSurface.lcsy = baseSurface.lcsy;
+                subSurface.lcsz = baseSurface.lcsz;
```
Comment (Myoldmopar) [inline src/EnergyPlus/SurfaceGeometry.cc:3059]: Yes, clearly the right fix, thanks.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 3]
```diff
@@ -1744,12 +1744,12 @@ namespace SurfaceGeometry {
 
         //  For each Base Surface Type (Wall, Floor, Roof)
 
-        for (int Loop = 1; Loop <= 3; ++Loop) {
+        for (const DataSurfaces::SurfaceClass Loop : state.dataSurfaceGeometry->BaseSurfIDs) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/SurfaceGeometry.cc:1747]: This is a nice improvement, thanks.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 4]
```diff
@@ -11331,3 +11331,67 @@ TEST_F(EnergyPlusFixture, GetSurfaceData_ShadingSurfaceScheduleOutOfRange)
...
+    EXPECT_FALSE(surfaceError);
+    EXPECT_FALSE(has_err_output());
+
+    // Without the fix in PR 9905 the following would fail since they are not assigned to be exactly the same
+    EXPECT_DOUBLE_EQ(BaseSurface.lcsz.z, SubSurface.lcsz.z);
+    // The following two lines might pass in the original code, but probably not a consistent outcome
+    // In the new code (after PR 9905 fix, they should be consistently passing the tests
+    EXPECT_DOUBLE_EQ(BaseSurface.lcsz.y, SubSurface.lcsz.y);
+    EXPECT_DOUBLE_EQ(BaseSurface.lcsz.x, SubSurface.lcsz.x);
+}
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:11397]: And a great unit test with no IDF snippets required!  Wonderful!

**Review by Myoldmopar — APPROVED** [review]
I like these changes @jcyuan2020.  I'll wait a little while to see if anyone has comments about the commented out tolerance check, and if not this should merge in.  Thanks.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 1 above)
Comment (JasonGlazer) [reply src/EnergyPlus/SurfaceGeometry.cc:3062]: I think removing this code is fine. I think it was just trying to get both angles to use the same basis if they were close to 360 degrees. So that 360.1 and 0.1 were later evaluated as the same angle. And I think the rotAzmDiffDeg() function accomplishes the same thing now. 

@jcyuan2020 since it is using abs() I don't think any error is introduced.

Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc:3062]: The slightly problem in the original code might be the one with 359.991 degree. A 359.991 degree will be brought to a value of 0.009 (slightly smaller than 0.01). Here the error is introduced to be 2*0.009 in that that these two angles were NOT exactly the same (actually they were symmetrical with the North (0 degree) axis)---thinking about 359 degree and 1 degree for a magnified version and there would be 2 degree of an error introduced.

This is just quite a minor issue given that 0.01 (*2) would be quite small and it is usually not happening. But anyway, removing this block actually would be the clean way to eliminate the possible occurrence of a small error (especially after adapting calculating the diffs using rotational difference).

**Comment by jcyuan2020** [comment]
Note that here there is a commit 0c84ea94b684b9 got reverted for the reason of explaining the diffs.

The commit deals with removing the following `if` condition in the code:
```
            // Prior logic tested for azimuth difference < 30 and then skipped this - this caused large diffs in
            // CmplxGlz_MeasuredDeflectionAndShading Restoring that check here but will require further investigation (MJW Dec 2015)
            if (std::abs(baseSurface.Azimuth - subSurface.Azimuth) > warningTolerance) {
```

This commit was originally also included in the current PR. However, with this commit it will have much more diffs mingled with the previous changes. Therefore it should be nice to merge in what's currently in here first---and I will do a separate follow up PR for the reverted commit, wit separated diffs investigations.

**Comment by Myoldmopar** [comment]
@jcyuan2020 when I ran Clang Format locally it changed one line.  The line wasn't being flagged by our CI check, so I'm going to let it run before I merge.  Assuming it's clean, this will merge shortly, thanks!

**Comment by Myoldmopar** [comment]
Format appears happy, I don't think I need to wait for anything else, merging this.  Thanks @jcyuan2020
