### PR TITLE
Fix #7029 - IP conversion report units

### LINKED ISSUE #7029: ZoneInfiltration Airflow Stats Nominal section displaying wrong units
Issue overview
--------------

After changing the OutputControl:Table:Style object Unit Conversion to _InchPound_, the _ZoneInfiltration Airflow Stats Nominal_ included in the _AllSummary_ report displays some columns in SI units. The values displayed in the columns are the correct entered values in SI units. The fix will be complete when this report does the conversion for this columns.

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA): Energyplus 8.9.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added : `testfiles/5ZoneAutoDXVAV.idf`
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7029: Added "person/m2" to unitConv, and modified some units for eg  `m3/s/m2` to be `m3/s-m2` to be correctly picked up for conversion. Added the new unitConv to an existing Gtest.

After changes it correctly converts the units (the before can be seen in #7029) (both label and conversion factor are ok).

internal

infiltration

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@jmarrec I pulled the latest NREL/develop into this branch to get some fresh, cleaned up, CI results.  I'll take a peek at this later today after CI does its runs.

File: src/EnergyPlus/HeatBalanceAirManager.cc [hunk 1]
```diff
@@ -3462,7 +3462,7 @@ namespace HeatBalanceAirManager {
             if (Loop == 1)
                 gio::write(OutputFileInits, Format_721)
                     << "ZoneInfiltration"
-                    << "Design Volume Flow Rate {m3/s},Volume Flow Rate/Floor Area {m3/s/m2},Volume Flow Rate/Exterior Surface Area {m3/s/m2},ACH - "
+                    << "Design Volume Flow Rate {m3/s},Volume Flow Rate/Floor Area {m3/s-m2},Volume Flow Rate/Exterior Surface Area {m3/s-m2},ACH - "
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatBalanceAirManager.cc:3465]: OK, so `m3/s-m2` is already the accepted unit conversion in E+, this output was simply entered incorrectly in this string.  :+1:

File: src/EnergyPlus/OutputReportTabular.cc [hunk 2]
```diff
@@ -15351,7 +15351,7 @@ namespace OutputReportTabular {
 
         // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
         //    na
-        UnitConvSize = 115;
+        UnitConvSize = 116;
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:15354]: No problems here.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
CI is looking happy with it so far.  I'm building it locally and will mess around with it.

**Comment by Myoldmopar** [comment]
Tested locally using 1ZoneEvapCooler.idf as the test file.

### Baseline branch:
- Ran original file: got {m3/s/m2}
- Changed to InchPound: other units converted, but still got m3/s/m2

### This branch:
- Ran original file: got {m3/s-m2}  **GOOD**
- Changed to InchPound: got {ft3/min-ft2}  **GREAT!**

I don't see any red flags with this.  I'll let CI finish the integration coverage, which is the longest of the tests, but I suspect in an hour or so when it's done with that, and the custom-check test, it'll be green and I'll merge this in.

**Comment by Myoldmopar** [comment]
CI is _super_ happy.  Merging.
