### PR TITLE
Fix 9686 and 9724---Correct the zone ideal loads SA HumRat value calculation and the units in Total Outdoor Air by AirLoop report table

### LINKED ISSUE #9686: Potential Code Error: ZoneHVAC:IdealLoadsAirSystem incorrectly uses 'min' operation to set Humidity Ratio of Supply Air (when ZoneControl:Humidistat used)
Issue overview
--------------
Issue found during code review due to inconsistent results in detailed output of building energy simulation.

During building energy simulation timesteps with zone cooling demands - where 'ZoneHVAC:IdealLoadsAirSystem' with 'ZoneControl:Humidistat' are used - the Supply Air Humidity Ratio [`PurchAir(PurchAirNum).SupplyHumRat`] set by the simulation results in significant over-dehumidification, even when Supply Air remains well below saturation.

This is due in large part to an **incorrect "min" operation in the PurchasedAirManager.cc methods**. Specifically, 
_line 2395_
`	SupplyHumRatForDehum = min(SupplyHumRatForDehum, PurchAir(PurchAirNum).MinCoolSuppAirHumRat);`
- [https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PurchasedAirManager.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PurchasedAirManager.cc)
- [reviewed on 2022-09-09]

### Proposed fix
Simply change the `min` to `max` on _line 2395_:
`	SupplyHumRatForDehum = min(SupplyHumRatForDehum, PurchAir(PurchAirNum).MinCoolSuppAirHumRat);`
becomes
`	SupplyHumRatForDehum = max(SupplyHumRatForDehum, PurchAir(PurchAirNum).MinCoolSuppAirHumRat);`

All other checks and calculations appear consistent (including saturation checks and capacity limits), and should not be impacted by the fix.

### Explanation
This function takes as input `PurchAir(PurchAirNum).MinCoolSuppAirHumRat` from
- **object:**	'ZoneHVAC:IdealLoadsAirSystem'
- **field:**	'Minimum Cooling Supply Air Humidity Ratio {kgWater/kgDryAir}'
(per the InputOutputReference, the default would be "0.0077 kgWater/kgDryAir which corresponds to a 10C (50F) dew point.")

and the `SupplyHumRatForDehum` calculated to satisfy zone demand from _lines 2393-2394_:
`MdotZnDehumidSP = state.dataZoneEnergyDemand->ZoneSysMoistureDemand(ControlledZoneNum).RemainingOutputReqToDehumidSP;`
`SupplyHumRatForDehum = MdotZnDehumidSP / SupplyMassFlowRate + state.dataLoopNodes->Node(ZoneNodeNum).HumRat;`

The result is that any time a Humidity Ratio [`SupplyHumRatForDehum`] is calculated to be greater than the 'Minimum Cooling Supply Air Humidity Ratio' (which is almost always expected for part loads and/or higher airflows), the method ignores it and just uses the 'Minimum Cooling Supply Air Humidity Ratio' [`PurchAir(PurchAirNum).MinCoolSuppAirHumRat`] anyway (resulting in significantly more latent cooling than required).

A notable exception is where a Humidity Ratio [`SupplyHumRatForDehum`] is calculated to be even lower than the 'Minimum Cooling Supply Air Humidity Ratio' [`PurchAir(PurchAirNum).MinCoolSuppAirHumRat`] setpoint (which should only occur in some edge cases where the 'SupplyMassFlowRate' calculated for dehumidification [SupplyMassFlowRateForDehum] failed the logical checks [lines 2279-2289] (defaulting to '0')); however, this contradicts the intent described in the documentation (and defeats the purpose of the minimum constraint input).

### Temporary workaround
One temporary workaround for users of the current versions of EnergyPlus is to use an arbitrarily high 'Minimum Cooling Supply Air Humidity Ratio' setpoint in the Ideal Air Loads object. Although this will preclude it from influencing the calculation of 'SupplyMassFlowRate' and will mean there is no 'Minimum Cooling Supply Air Humidity Ratio' constraint (which could result in unrealistically low supply air humidity ratios), it does result in modulated dehumidification (while still subject to supply air saturation constraints).

### Other Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
	troubleshooting runs were done on Windows 10 Home Version 21H1
	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz Processor with 16.0 GB RAM
 - Version of EnergyPlus: defect appears still present in [https://github.com/NREL/EnergyPlus/releases/tag/v22.2.0](https://github.com/NREL/EnergyPlus/releases/tag/v22.2.0)
 [https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PurchasedAirManager.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PurchasedAirManager.cc) 
 [reviewed on 2022-09-09]

### LINKED ISSUE #9724: Total Outdoor Air by AirLoop table report unit errors
Issue overview
--------------
It was reported that in the "Total Outdoor Air by AirLoop table, the units for "Natural Ventilation" and "Total Ventilation" are incorrect: 
image

The related code is in OutputReportPredefined.cc:
```
        s->pdstOAtotAirByLoop = newPreDefSubTable(state, s->pdrOutsideAirDetails, "Total Outdoor Air by AirLoop");
        s->pdchOaTaAlMechVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Mechanical Ventilation [m3]");
        s->pdchOaTaAlNatVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Natural Ventilation [m3/s]");
        s->pdchOaTaAlTotVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Total Ventilation [m3/s]");
```

The last two lines should have unit in `[m3]` instead of `[m3/s]`.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.2
 - Helpdesk ticket number: 16256

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9686 
 - Fixes #9724 as well
 - The Supply Air Humidity Ratio can be incorrectly computed using the `min` function as reported by the issue above. The code is reexamined and confirms the proposed fix (in #9686) that that particular is to change the `min` function to a `max` function instead.
 - The units used for "Natural Ventilation" and "Total Ventilation" headers in the "Total Outdoor Air by AirLoop" report table are incorrect. They should be in `m3` instead of the current `m3/s`. This PR also fixes this issue.

- Diffs explanation: The first fix (Ideal Loads System) will only affect the test cases that have an ideal loads system that uses humidity stat controls. The second fix (Ventilation report headers) will have a massive impact, essentially to all the cases that outputs the "Total Outdoor Air by AirLoop" table.
 
**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 1]
```diff
@@ -795,8 +795,8 @@ namespace OutputReportPredefined {
 
         s->pdstOAtotAirByLoop = newPreDefSubTable(state, s->pdrOutsideAirDetails, "Total Outdoor Air by AirLoop");
         s->pdchOaTaAlMechVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Mechanical Ventilation [m3]");
-        s->pdchOaTaAlNatVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Natural Ventilation [m3/s]");
-        s->pdchOaTaAlTotVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Total Ventilation [m3/s]");
+        s->pdchOaTaAlNatVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Natural Ventilation [m3]");
+        s->pdchOaTaAlTotVent = newPreDefColumn(state, s->pdstOAtotAirByLoop, "Total Ventilation [m3]");
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportPredefined.cc:799]: Yep, that's a good fix.

File: src/EnergyPlus/PurchasedAirManager.cc [hunk 2]
```diff
@@ -2392,7 +2392,7 @@ void CalcPurchAirLoads(EnergyPlusData &state,
                 case HumControl::Humidistat: {
                     MdotZnDehumidSP = state.dataZoneEnergyDemand->ZoneSysMoistureDemand(ControlledZoneNum).RemainingOutputReqToDehumidSP;
                     SupplyHumRatForDehum = MdotZnDehumidSP / SupplyMassFlowRate + state.dataLoopNodes->Node(ZoneNodeNum).HumRat;
-                    SupplyHumRatForDehum = min(SupplyHumRatForDehum, PurchAir(PurchAirNum).MinCoolSuppAirHumRat);
+                    SupplyHumRatForDehum = max(SupplyHumRatForDehum, PurchAir(PurchAirNum).MinCoolSuppAirHumRat);
```
Comment (Myoldmopar) [inline src/EnergyPlus/PurchasedAirManager.cc:2395]: OK, so `MdotZnDehumidSP` is the kg of water per second mass flow to meet the humidity set-point.  Then we divide that by the total supply flow rate in kg of dry air per second to get the kg water per kg dry air.  Then we add the zone humidity ratio...is that right?  Maybe, I think I just need to pull out my psych chart.

psych_chart

Anyway, then you need to take the max of that value compared to the minimum cooling supply air humidity ratio.  Yes, obviously you want to max this to constrain it to that minimum.  And since this is the only line changed, I will just move on.

File: tst/EnergyPlus/unit/PurchasedAirManager.unit.cc [hunk 3]
```diff
@@ -1284,3 +1284,193 @@ TEST_F(ZoneIdealLoadsTest, IdealLoads_EMSOverrideTest_Revised_ZeroFlow)
...
+    state->dataLoopNodes->Node(1).Temp = 30;
+    state->dataLoopNodes->Node(1).HumRat = 0.012;
+
+    CalcPurchAirLoads(*state, 1, SysOutputProvided, MoistOutputProvided, 1);
+
+    EXPECT_EQ(state->dataPurchasedAirMgr->PurchAir(1).MinCoolSuppAirHumRat, 0.009);
+
+    EXPECT_EQ(state->dataPurchasedAirMgr->PurchAir(1).SupplyTemp, 20.228931255157292);
+    // Without the current fix, this SupplyHumRat value would be 0.009, which is incorrect:
+    EXPECT_EQ(state->dataPurchasedAirMgr->PurchAir(1).SupplyHumRat, 0.01);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/PurchasedAirManager.unit.cc:1462]: OK.

**Review by Myoldmopar — APPROVED** [review]
Seems like obvious fixes on the units and the max vs min.  Unit test appears to cover the issue.  This looks good here.

**Comment by Myoldmopar** [comment]
Unit and integration tests all pass.  Just lots of regressions, as expected.  Local testing underway.

**Comment by Myoldmopar** [comment]
Alrighty, the only math/EIO diff appears in the one file that has an ideal load dehumidifier.  This appears ready to go.  Heads up anyone who is about to push commits (@rraustad ), pull in develop after I merge this (now) to avoid lots of unrelated table diffs in your PR.  Thanks @jcyuan2020
