### PR TITLE
Addressed broken No Load Supply Air Flow Rate sizing methods in Unitary System

### LINKED ISSUE #7547: Some key choices for No Load Supply Air Flow Rate Method field in AirLoopHVAC:UnitarySystem are broken
Of the six choice keys in No Load Supply Air Flow Rate Method field only SupplyAirFlowRate and FlowPerFloorArea work correctly. The other four methods either fatal out or return zero flow rate.

Defects file tested using EnergyPlus V9.10 shows:
(1) If FractionOfAutosizedCoolingValue is selected this field is sized to 0.0 and simulation continuous 
(2) FractionOfAutosizedHeatingValue, FlowPerCoolingCapacity and FlowPerHeatingCapacity fatal out.

  A22, \field No Load Supply Air Flow Rate Method
       \type choice
       \key None
       \key SupplyAirFlowRate
       \key FlowPerFloorArea
       \key FractionOfAutosizedCoolingValue
       \key FractionOfAutosizedHeatingValue
       \key FlowPerCoolingCapacity
       \key FlowPerHeatingCapacity

Defect files tested using develop version shows:
(1) If FractionOfAutosizedCoolingValue is selected, E+ fatal out with the following error
Note that the error message is incorrect, it refers to wrong field for problem description. see below:

   ** Severe  ** AirLoopHVAC:UnitarySystem = THERMAL ZONE ONE SZ-VAV SYSTEM
   **   ~~~   ** Input for No Load Supply Air Flow Rate Method = FractionOfAutosizedCoolingValue.
   **   ~~~   ** Blank field not allowed for No Load Supply Air Flow Rate Per Unit of Capacity During Cooling Operation
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs

(2) If FractionOfAutosizedHeatingValue is selected, E+ fatal out with the following error
Note that the error message is incorrect, it refers to wrong field for problem description. see below:
   ** Severe  ** AirLoopHVAC:UnitarySystem = THERMAL ZONE ONE SZ-VAV SYSTEM
   **   ~~~   ** Input for No Load Supply Air Flow Rate Method = FractionOfAutosizedHeatingValue.
   **   ~~~   ** Blank field not allowed for No Load Supply Air Flow Rate Per Unit of Capacity During Heating Operation
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs
 

(3) If FlowPerCoolingCapacity is selected, E+ runs but No Load Supply Air Flow Rate is sized to 0.0. See below:
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size Supply Air Flow Rate [m3/s], 0.54651
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size Heating Supply Air Flow Rate [m3/s], 0.54651
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size Cooling Supply Air Flow Rate [m3/s], 0.54651
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 0.00000

(4) If FlowPerHeatingCapacity is selected, E+ fatal out with the following error.
Note that the error message says black field but it is not. see error message eblow:
   ** Severe  ** AirLoopHVAC:UnitarySystem = THERMAL ZONE ONE SZ-VAV SYSTEM
   **   ~~~   ** Input for No Load Supply Air Flow Rate Method = FlowPerHeatingCapacity.
   **   ~~~   ** Blank field not allowed for No Load Supply Air Flow Rate Per Unit of Capacity During Heating Operation
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (V9.1 and current develop)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview

- Fixes #7547. 
- This fix addressed broken sizing methods for No Load Supply Air Flow Rate in unitary systems. The following four broken sizing methods were addressed:

   - No Load Fraction of Autosized Cooling Supply Air Flow Rate
   - No Load Fraction of Autosized Heating Supply Air Flow Rate
   - No Load Supply Air Flow Rate Per Unit of Capacity During Cooling Operation {m3/s-W}
   - No Load Supply Air Flow Rate Per Unit of Capacity During Heating Operation {m3/s-W}

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If structural output changes, add to output rules file and add OutputChange label
### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally

### CODE REVIEW

**Comment by Nigusse** [comment]
Added more defect files.

**Comment by Nigusse** [comment]
FlowPerCoolingCapacity and FlowPerHeatingCapacity No Load Supply Air Flow Rate sizing methods were broken for water cooling and heating coils only.

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -1935,12 +1935,31 @@ namespace UnitarySystems {
                 SizingMethod = DataHVACGlobals::AutoCalculateSizing;
                 this->m_MaxNoCoolHeatAirVolFlow = DataSizing::AutoSize;
             } else if (this->m_NoCoolHeatSAFMethod == FlowPerCoolingCapacity) {
+                if ( EqSizing.DesCoolingLoad <= 0.0) {
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:1938]: water coil cooling capacity not sized yet. If not sized, size the water coil capacity here.

File: src/EnergyPlus/UnitarySystem.cc [hunk 2]
```diff
@@ -1935,12 +1935,31 @@ namespace UnitarySystems {
...
             } else if (this->m_NoCoolHeatSAFMethod == FlowPerHeatingCapacity) {
+                if ( EqSizing.DesHeatingLoad <= 0.0 ) {
+                    // water coil not sizing yet
+                    if ( this->m_HeatingCoilType_Num == DataHVACGlobals::Coil_HeatingWater ) {
+                        WaterCoils::SimulateWaterCoilComponents(
+                            this->m_HeatingCoilName, FirstHVACIteration, this->m_HeatingCoilIndex, QActual, this->m_FanOpMode, 1.0 );
+                        EqSizing.DesHeatingLoad = WaterCoils::GetWaterCoilCapacity(
+                            UtilityRoutines::MakeUPPERCase( DataHVACGlobals::cAllCoilTypes( this->m_HeatingCoilType_Num ) ), this->m_HeatingCoilName, ErrFound );
+                    }
+                }
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:1962]: water coil heating capacity not sized yet. If not sized, then size the water coil capacity here.

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -2840,13 +2859,13 @@ namespace UnitarySystems {
                 }
 
                 Real64 loc_m_NoCoolHeatSAFMethod_FracOfAutosizedCoolingSAFlow(-999.0);
-                if (fields.find("no_load_fraction_of_autosized_cooling_supply_air_flow") != fields.end()) { // not required field
-                    loc_m_NoCoolHeatSAFMethod_FracOfAutosizedCoolingSAFlow = fields.at("no_load_fraction_of_autosized_cooling_supply_air_flow");
+                if (fields.find("no_load_fraction_of_autosized_cooling_supply_air_flow_rate") != fields.end()) { // not required field
+                    loc_m_NoCoolHeatSAFMethod_FracOfAutosizedCoolingSAFlow = fields.at("no_load_fraction_of_autosized_cooling_supply_air_flow_rate");
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:2863]: "_rate" was missing. This change matches field name to the idd, and expected by the json input processor.

File: src/EnergyPlus/UnitarySystem.cc [hunk 4]
```diff
@@ -2840,13 +2859,13 @@ namespace UnitarySystems {
...
                 }
 
                 Real64 loc_m_NoCoolHeatSAFMethod_FracOfAutosizedHeatingSAFlow(-999.0);
-                if (fields.find("no_load_fraction_of_autosized_heating_supply_air_flow") != fields.end()) { // not required field
-                    loc_m_NoCoolHeatSAFMethod_FracOfAutosizedHeatingSAFlow = fields.at("no_load_fraction_of_autosized_heating_supply_air_flow");
+                if (fields.find("no_load_fraction_of_autosized_heating_supply_air_flow_rate") != fields.end()) { // not required field
+                    loc_m_NoCoolHeatSAFMethod_FracOfAutosizedHeatingSAFlow = fields.at("no_load_fraction_of_autosized_heating_supply_air_flow_rate");
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:2868]: the same as above.

File: src/EnergyPlus/UnitarySystem.cc [hunk 5]
```diff
@@ -2856,9 +2875,9 @@ namespace UnitarySystems {
                 }
 
                 Real64 loc_m_NoCoolHeatSAFMethod_FlowPerHeatingCapacity(-999.0);
-                if (fields.find("heating_supply_air_flow_rate_per_unit_of_capacity_during_heating_operation") != fields.end()) { // not required field
+                if (fields.find("no_load_supply_air_flow_rate_per_unit_of_capacity_during_heating_operation") != fields.end()) { // not required field
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:2878]: Replaced "heating" with "no_load" to match field name to the idd, and expected by the json input processor.

File: src/EnergyPlus/UnitarySystem.cc [hunk 6]
```diff
@@ -14838,9 +14857,14 @@ namespace UnitarySystems {
...
-                max(0.0, ((airMdot - (systemMaxAirFlowRate * lowSpeedRatio)) / ((1.0 - lowSpeedRatio) * systemMaxAirFlowRate)));
-
+            if ( lowSpeedRatio != 1.0 ) {
+                // division by zero when lowSpeedRatio == 1.0
+                thisSys.FanPartLoadRatio =
+                    max( 0.0, ((airMdot - (systemMaxAirFlowRate * lowSpeedRatio)) / ((1.0 - lowSpeedRatio) * systemMaxAirFlowRate)) );
+            }
+            else {
+                thisSys.FanPartLoadRatio = 1.0;
+            }
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:14867]: Running the defect file after the above changes caused division by zero. Thus, this logic was added.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 7]
```diff
@@ -188,6 +188,7 @@ class ZoneUnitarySysTest : public EnergyPlusFixture
         DataPlant::PlantLoop.allocate(DataPlant::TotNumLoops);
         DataSizing::PlantSizData.allocate(DataPlant::TotNumLoops);
         // int NumPltSizInput = DataPlant::TotNumLoops;
+        DataSizing::NumPltSizInput = 2;
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:191]: Added number of plant sizing object in the default constructor. The default constructor already has two plant loop sizing objects.

**Review by mjwitte — CHANGES_REQUESTED** [review]
@Nigusse This looks good so far, but I found some other problems with some other random tests:
```
   ** Severe  ** AirLoopHVAC:UnitarySystem = OFFICE RTU UNITARY
   **   ~~~   ** Input for Cooling Supply Air Flow Rate Method = FractionOfAutosizedCoolingValue.
   **   ~~~   ** Blank field not allowed for Cooling Fraction of Autosized Cooling Supply Air Flow Rate.
   ** Severe  ** AirLoopHVAC:UnitarySystem = OFFICE RTU UNITARY
   **   ~~~   ** Input for Heating Supply Air Flow Rate Method = FractionOfAutosizedHeatingValue
   **   ~~~   ** Blank field not allowed for Heating Fraction of Autosized Heating Supply Air Flow Rate
```
I've added my test files to the defect files folder. Two of them show that the fixes already in place work ok. The third one, instance-noloadB, fails. Again, it's due to a mismatch in the requested field name during input processing vs the actual field name in the IDD/schema. 

The new unit tests here are great, but we need one more that simply processes input for a unitary system object(s) that has inputs for every single field (with unique values) and tests to make sure the input value ends up in the right variable. I know for a long object like this that's a little tedious, but it would protect against invalid field names in the getinput.

**Comment by Nigusse** [comment]
@mjwitte Thanks. I did not see the other sizing fields had similar issues. I will address them.

**Comment by Nigusse** [comment]
We cannot capture fields with key choices in one unit test. We need multiple unit test to capture all combinations of key choices. @mjwitte right?

**Comment by mjwitte** [comment]
Well, that would be a second level. My original thought was just to check one case for each field. If one key choice makes it into the correct variable, then any other key choice should also make it in.

**Comment by Nigusse** [comment]
@mjwitte addressed the additional input fields failure and added one more unit test that cover all fields check. Obviously this unit test does not catch all key choices. If it is important, I will add more unit tests.

**Comment by mjwitte** [comment]
Getting warmer. These files run now, but I don't see the expected result. For instance-noloadB.idf, the inputs are:
````
           FractionOfAutosizedCoolingValue,       !- Supply Air Flow Rate Method During Cooling Operation
           Autosize,  !- Supply Air Flow Rate During Cooling Operation {m3/s}
           ,                        !- Supply Air Flow Rate Per Floor Area During Cooling Opertation
           0.9,                        !- Fraction of Autosized Design Cooling Supply Air Flow Rate
           ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Cooling Operation
           FractionOfAutosizedHeatingValue,       !- Supply Air Flow Rate Method During Heating Operation
           Autosize,  !- Supply Air Flow Rate During Heating Operation {m3/s}
           ,                        !- Supply Air Flow Rate Per Floor Area During Heating Operation
           0.5,                        !- Fraction of Autosized Design Heating Supply Air Flow Rate
           ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Heating Operation
  ````
And the resulting sizes are:
````
 Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size Supply Air Flow Rate [m3/s], 0.13253
 Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size Heating Supply Air Flow Rate [m3/s], 0.13253
 Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size Cooling Supply Air Flow Rate [m3/s], 0.13253
 Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size No Load Supply Air Flow Rate [m3/s], 3.31319E-002
````
I expected the heating supply air flow rate to be smaller than cooling.

**Comment by Nigusse** [comment]
@mjwitte I see problems in the defect files but it did not matter in the final results.  The cooling, heating and no-load supply air method field names were incorrect in the defect file. I think, the results look correct unless it is an issue by design:

           !FractionOfAutosizedCoolingValue,       !- Supply Air Flow Rate Method During Cooling Operation
		   FractionOfAutosizedCoolingValue,       !- Cooling Supply Air Flow Rate Method
           Autosize,  !- Supply Air Flow Rate During Cooling Operation {m3/s}
           ,                        !- Supply Air Flow Rate Per Floor Area During Cooling Opertation
           0.9,                        !- Fraction of Autosized Design Cooling Supply Air Flow Rate
           ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Cooling Operation
           !FractionOfAutosizedHeatingValue,       !- Supply Air Flow Rate Method During Heating Operation
		   FractionOfAutosizedHeatingValue,       !- Heating Supply Air Flow Rate Method
           Autosize,  !- Supply Air Flow Rate During Heating Operation {m3/s}
           ,                        !- Supply Air Flow Rate Per Floor Area During Heating Operation
           0.5,                        !- Fraction of Autosized Design Heating Supply Air Flow Rate
           ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Heating Operation
           !FractionOfAutosizedHeatingValue,       !- Supply Air Flow Rate Method When No Cooling or Heating is Required
		   FractionOfAutosizedHeatingValue,       !- No Load Supply Air Flow Rate Method
           Autosize,  !- Supply Air Flow Rate When No Cooling or Heating is Required {m3/s}
           ,                        !- Supply Air Flow Rate Per Floor Area When No Cooling or Heating is Required
           0.5,                         !- Fraction of Autosized Design Cooling Supply Air Flow Rate
           0.25,                        !- Fraction of Autosized Design Heating Supply Air Flow Rate
           ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Cooling Operation
           ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Heating Operation

Below are the results and the approach used in the sizing:


    Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size Supply Air Flow Rate [m3/s], 0.13253
    Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size Heating Supply Air Flow Rate [m3/s], 0.13253
    Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size Cooling Supply Air Flow Rate [m3/s], 0.13253
    Component Sizing Information, AirLoopHVAC:UnitarySystem, OFFICE RTU UNITARY, Design Size No Load Supply Air Flow Rate [m3/s], 3.31319E-002


     Autosized design cooling supply air flow rates: 0.14725310725090809
     EqSizing.CoolingAirVolFlow = 0.9 * 0.14725310725090809 = 0.13252779652581728

     Autosized design heating supply air flow rates: = 0.048965078132461239
     EqSizing.HeatingAirVolFlow  = 0.5 * 0.048965078132461239 = 0.024482539066230619

     design no-load supply air flow rates: = 0.25 * 0.13252779652581728 = 0.033131949131454320
     this->m_MaxNoCoolHeatAirVolFlow *= EqSizing.HeatingAirVolFlow;

unitary system uses the maximum of cooling and heating design supply air flow rates determined as follows. See also the link [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/UnitarySystem.cc#L1805-L1806):

        EqSizing.CoolingAirVolFlow = max(EqSizing.CoolingAirVolFlow, EqSizing.HeatingAirVolFlow);
        EqSizing.HeatingAirVolFlow = EqSizing.CoolingAirVolFlow; 


So the results are correct by design, I think.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 8]
```diff
@@ -10961,3 +10962,482 @@ TEST_F(EnergyPlusFixture, UnitarySystemModel_GetInputZoneEquipmentBlankCtrlZone)
...
+        "    Coil:Cooling:Water,                     !- Cooling Coil Object Type",
+        "    Water Cooling Coil,                     !- Cooling Coil Name",
+        "    No,                                     !- Use DOAS DX Cooling Coil",
+        "    7.0,                                    !- Minimum Supply Air Temperature {C}",
+        "    SensibleOnlyLoadControl,                !- Latent Load Control",
+        "    Coil:Heating:Fuel,                      !- Supplemental Heating Coil Object Type",
+        "    Supplemental Heating Coil,              !- Supplemental Heating Coil Name",
+        "    FractionOfAutosizedCoolingValue,        !- Cooling Supply Air Flow Rate Method",
+        "    ,                                       !- Cooling Supply Air Flow Rate {m3/s}",
+        "    ,                                       !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}",
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:11284]: @Nigusse I was expecting to see a value in every field for this test. But now I realize that these fields are initially stored in a local variable but ultimately, one struct variable holds one of several field inputs. So now I understand why you were asking about testing every method option. At some point, we need a more robust test, but that may involve refactoring `getUnitarySystemInputData`, and you've done enough for this particular issue.

**Review by mjwitte — APPROVED** [review]
@rraustad  I'm puzzled by the lines forcing both heating and cooling flow to be the same. That seems to defeat the whole purpose of having separate inputs. But that would be a separate issue from this one.

The code here addresses the problem at hand, so I'll merge this.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc (hunk 8 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/UnitarySystem.unit.cc:11284]: I see the max flow rate used here and also comments as to why it's there. I guess maybe it's time to relax that constraint so that users can choose the air flow rate. I looked around and variability of air flow in cooling/heating is typical of variable speed units, [pg 4 here](https://www.shareddocs.com/hvac/docs/1009/Public/01/25VNA-05PD.pdf). I didn't see where constant speed or even 2-speed units have different flow rates in cooling/heating [pg 12 and 13 here](https://www.shareddocs.com/hvac/docs/1009/Public/0A/50VG-04SI.pdf) but I didn't spend much time looking at manufacturers data, except for choosing what I was going to say here. Maybe Carrier and Trane could add more information on choices for air flow rates.
