### PR TITLE
Two ScheduleAPI Fixes and a Comment

### LINKED ISSUE #10982: ZoneHVAC:CoolingPanel:RadiantConvective:Water change of behavior for Cooling Control Temperature Schedule Name
### Issue overview

```
ZoneHVAC:CoolingPanel:RadiantConvective:Water,
  [...]
  A6 , \field Control Type
       \note Temperature on which unit is controlled
       \type choice
       \key MeanAirTemperature
       \key MeanRadiantTemperature
       \key OperativeTemperature
       \key OutdoorDryBulbTemperature
       \key OutdoorWetBulbTemperature
       \key ZoneTotalLoad
       \key ZoneConvectiveLoad
       \default MeanAirTemperature
  N8 , \field Cooling Control Throttling Range
       \units deltaC
       \minimum 0.5
       \default 0.5
  A7 , \field Cooling Control Temperature Schedule Name
       \type object-list
       \object-list ScheduleNames
```

*  #10848 made a change to the Schedule API, and this diff popped up

https://github.com/NREL/EnergyPlus/commit/2d1b4c3bdf9aee611241cb387c29879da33b5081#diff-6853c0296326896c602b7e725a03773599fb532c0860798b4dd31b07d2ea93fcR498

Image

This is not equivalent, and a file that used to run in 24.2.0 now doesn't run in 25.1.0

### Operating System (Multiple choices)

Any

### Operating System Version

N/A

### Version of EnergyPlus

25.1.0-IOFreeze

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[zone_hvac_cooling_panel.osm_24.2.0.idf.txt](https://github.com/user-attachments/files/19184737/zone_hvac_cooling_panel.osm_24.2.0.idf.txt)

Running Transition, which produces the EXACT same file after reformating:

[zone_hvac_cooling_panel.osm_25.1.0.idf.txt](https://github.com/user-attachments/files/19184738/zone_hvac_cooling_panel.osm_25.1.0.idf.txt)

### LINKED ISSUE #10983: ScheduleDayInterval new error
### Issue overview

An OpenStudio-resources regression test that ran fine on 24.2.0 is now failing in 25.1.0.

```
$ /home/julien/Software/Others/EnergyPlus-build-release/Products/energyplus -x -w $chig_epw -d out-2510 output_objects_2.osm_25.1.0.idf 
ExpandObjects Started.
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished. Time:     0.040
EnergyPlus Starting
EnergyPlus, Version 25.1.0-c76913e29d, YMD=2025.03.11 15:01
Segmentation fault (core dumped)
```

* Seem related to the Schedule API PR #10848

Backtrace in debug

```
(lldb) bt
error: libenergyplusapi.so.25.1.0 0x003f57da: DW_TAG_member '_M_local_buf' refers to type 0x0000000000456ec7 which extends beyond the bounds of 0x003f57d0
* thread #1, name = 'energyplus', stop reason = signal SIGABRT
  * frame #0: 0x00007fffe7e9eb2c libc.so.6`__GI___pthread_kill [inlined] __pthread_kill_implementation(no_tid=0, signo=6, threadid=<unavailable>) at pthread_kill.c:44:76
    frame #1: 0x00007fffe7e9eae8 libc.so.6`__GI___pthread_kill [inlined] __pthread_kill_internal(signo=6, threadid=<unavailable>) at pthread_kill.c:78:10
    frame #2: 0x00007fffe7e9eae8 libc.so.6`__GI___pthread_kill(threadid=<unavailable>, signo=6) at pthread_kill.c:89:10
    frame #3: 0x00007fffe7e4527e libc.so.6`__GI_raise(sig=6) at raise.c:26:13
    frame #4: 0x00007fffe7e288ff libc.so.6`__GI_abort at abort.c:79:7
    frame #5: 0x00007fffe82a906f libstdc++.so.6`__gnu_debug::_Error_formatter::_M_error() const (.cold) at debug.cc:1320:10
    frame #6: 0x00007fffebb598b9 libenergyplusapi.so.25.1.0`std::__debug::vector<EnergyPlus::Sched::ScheduleType*, std::allocator<EnergyPlus::Sched::ScheduleType*>>::operator[](this=0x000055555587aaa0 size=7, __n=18446744073709551615) at vector:442:2
    frame #7: 0x00007fffeca16663 libenergyplusapi.so.25.1.0`EnergyPlus::Sched::ReportScheduleDetails(state=0x00007fffffffa8d0, LevelOfDetail=TimeStep) at ScheduleManager.cc:2178:113
    frame #8: 0x00007fffeca0e834 libenergyplusapi.so.25.1.0`EnergyPlus::Sched::ProcessScheduleInput(state=0x00007fffffffa8d0) at ScheduleManager.cc:2044:38
    frame #9: 0x00007fffebac0c84 libenergyplusapi.so.25.1.0`EnergyPlus::ScheduleManagerData::init_state(this=0x000055555587aa40, state=0x00007fffffffa8d0) at ScheduleManager.hh:527:36
    frame #10: 0x00007fffebab6fb9 libenergyplusapi.so.25.1.0`EnergyPlus::EnergyPlusData::init_state(this=0x00007fffffffa8d0, state=0x00007fffffffa8d0) at EnergyPlusData.cc:849:32
    frame #11: 0x00007fffecaa23dd libenergyplusapi.so.25.1.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffffa8d0) at SimulationManager.cc:211:25
    frame #12: 0x00007fffeba9b798 libenergyplusapi.so.25.1.0`RunEnergyPlus(state=0x00007fffffffa8d0, filepath="") at EnergyPlusPgm.cc:421:56
    frame #13: 0x00007fffeba99657 libenergyplusapi.so.25.1.0`EnergyPlusPgm(args=size=7, filepath="") at EnergyPlusPgm.cc:242:25
    frame #14: 0x00005555555abfb2 energyplus`main(argc=7, argv=0x00007fffffffbff8) at main.cc:60:25
    frame #15: 0x00007fffe7e2a1ca libc.so.6`__libc_start_call_main(main=(energyplus`main at main.cc:54:1), argc=7, argv=0x00007fffffffbff8) at libc_start_call_main.h:58:16
    frame #16: 0x00007fffe7e2a28b libc.so.6`__libc_start_main_impl(main=(energyplus`main at main.cc:54:1), argc=7, argv=0x00007fffffffbff8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffbfe8) at libc-start.c:360:3
    frame #17: 0x00005555555abd95 energyplus`_start + 37
```

```
(lldb) f 7
frame #7: 0x00007fffeca16663 libenergyplusapi.so.25.1.0`EnergyPlus::Sched::ReportScheduleDetails(state=0x00007fffffffa8d0, LevelOfDetail=TimeStep) at ScheduleManager.cc:2178:113
   2175	                    }
   2176	                }
   2177	                std::string_view constexpr SchDFmtdata0("DaySchedule,{},{},{},{}");
-> 2178	                print(
   2179	                    state.files.eio, SchDFmtdata0, daySched->Name, s_sched->scheduleTypes[daySched->schedTypeNum]->Name, NoAverageLinear, "Values:");
   2180	
   2181	                switch (LevelOfDetail) {
(lldb) 
frame #7: 0x00007fffeca16663 libenergyplusapi.so.25.1.0`EnergyPlus::Sched::ReportScheduleDetails(state=0x00007fffffffa8d0, LevelOfDetail=TimeStep) at ScheduleManager.cc:2178:113
   2175	                    }
   2176	                }
   2177	                std::string_view constexpr SchDFmtdata0("DaySchedule,{},{},{},{}");
-> 2178	                print(
   2179	                    state.files.eio, SchDFmtdata0, daySched->Name, s_sched->scheduleTypes[daySched->schedTypeNum]->Name, NoAverageLinear, "Values:");
   2180	
   2181	                switch (LevelOfDetail) {
(lldb) p *daySched
(EnergyPlus::Sched::DaySchedule) {
  EnergyPlus::Sched::DayOrYearSchedule = {
    EnergyPlus::Sched::ScheduleBase = (Name = "SCHEDULE DAY 2", Num = 11, isUsed = false, maxVal = 0, minVal = 0, isMinMaxSet = false)
  }
  schedTypeNum = -1
  interpolation = No
  tsVals = size=96 {
    [0] = 0
    [1] = 0
    [2] = 0
[...]
```

### Operating System (Multiple choices)

Any

### Operating System Version

N/A

### Version of EnergyPlus

25.1.0-IOFreeze

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[output_objects_2.osm_24.1.0.idf.txt](https://github.com/user-attachments/files/19184852/output_objects_2.osm_24.1.0.idf.txt)

Transition to 25.1.0, exact same file after reformating:

[output_objects_2.osm_25.1.0.idf.txt](https://github.com/user-attachments/files/19184853/output_objects_2.osm_25.1.0.idf.txt)

### PR DESCRIPTION
**Pull request by amirroth**
This PR fixes two issues created by PR [#10848](https://github.com/NREL/EnergyPlus/pull/10848):
- [#10982](https://github.com/NREL/EnergyPlus/issues/10982)
- [#10983](https://github.com/NREL/EnergyPlus/issues/10983)

### CODE REVIEW

File: src/EnergyPlus/Data/EnergyPlusData.hh [hunk 1]
```diff
@@ -574,8 +574,35 @@ struct EnergyPlusData : BaseGlobalStruct
...
+    // framework.  There are a good number of fixture objects that do
+    // a lot of setup before reading the IDF snippet, and that setup
+    // often requires some of hte constant objects.  The unit testing
+    // framework calls init_constant_state in
+    // EnergyPlusFixture::Setup() and then inidividual unit tests call
+    // init_state() after calling process_idf().  In fact, we can
+    // probably move init_state() into process_idf().
+
+    // init_constant_state() also needs to be appropriately called by
+    // the API, e.g., in resetState.
```
Comment (jmarrec) [inline src/EnergyPlus/Data/EnergyPlusData.hh:602]: thanks

File: src/EnergyPlus/ChilledCeilingPanelSimple.cc [hunk 2]
```diff
@@ -485,7 +485,9 @@ void GetCoolingPanelInput(EnergyPlusData &state)
         }
 
         thisCP.ColdSetptSchedName = s_ipsc->cAlphaArgs(7);
-        if ((thisCP.coldSetptSched = Sched::GetSchedule(state, thisCP.ColdSetptSchedName)) == nullptr) {
+        if (s_ipsc->lAlphaFieldBlanks(7)) {
+            thisCP.coldSetptSched = Sched::GetScheduleAlwaysOff(state);
+        } else if ((thisCP.coldSetptSched = Sched::GetSchedule(state, thisCP.ColdSetptSchedName)) == nullptr) {
```
Comment (jmarrec) [inline src/EnergyPlus/ChilledCeilingPanelSimple.cc:490]: This will avoid the fatal when it's blank.

Question left is whether it should be AlwaysOff or AlwaysOn.

Comment (jmarrec) [reply src/EnergyPlus/ChilledCeilingPanelSimple.cc:490]: https://github.com/NREL/EnergyPlus/blob/e7ecb2d53b6b2f4666bf5a56fc9b3ba35cf34190/src/EnergyPlus/ChilledCeilingPanelSimple.hh#L109

https://github.com/NREL/EnergyPlus/blob/e7ecb2d53b6b2f4666bf5a56fc9b3ba35cf34190/src/EnergyPlus/ScheduleManager.hh#L72

Comment (jmarrec) [reply src/EnergyPlus/ChilledCeilingPanelSimple.cc:490]: All good!

File: src/EnergyPlus/ScheduleManager.cc [hunk 3]
```diff
@@ -2174,8 +2174,12 @@ namespace Sched {
...
                 }
                 std::string_view constexpr SchDFmtdata0("DaySchedule,{},{},{},{}");
-                print(
-                    state.files.eio, SchDFmtdata0, daySched->Name, s_sched->scheduleTypes[daySched->schedTypeNum]->Name, NoAverageLinear, "Values:");
+                print(state.files.eio,
+                      SchDFmtdata0,
+                      daySched->Name,
+                      (daySched->schedTypeNum == SchedNum_Invalid) ? "" : s_sched->scheduleTypes[daySched->schedTypeNum]->Name,
+                      NoAverageLinear,
+                      "Values:");
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:2183]: Ok

File: src/EnergyPlus/ScheduleManager.cc [hunk 4]
```diff
@@ -2216,7 +2220,11 @@ namespace Sched {
                 assert(schedDetailed != nullptr);
 
                 int NumF = 1;
-                print(state.files.eio, "Schedule,{},{}", schedDetailed->Name, s_sched->scheduleTypes[sched->schedTypeNum]->Name);
+                print(state.files.eio,
+                      "Schedule,{},{}",
+                      schedDetailed->Name,
+                      (sched->schedTypeNum == SchedNum_Invalid) ? "" : s_sched->scheduleTypes[sched->schedTypeNum]->Name);
+
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc]: Ok. I think that's the last one in the codebase that wasn't protected by a schedTypeNum == Sched::SchedNum_Invalid  (or `-1` which is subpar but whatever) block. 

```
$ rg "scheduleTypes\[" -B5
ScheduleManager.hh
535-
536-        ScheduleInputProcessed = false;
537-        ScheduleFileShadingProcessed = false;
538-
539-        for (int i = 0; i < (int)scheduleTypes.size(); ++i)
540:            delete scheduleTypes[i];

OutputProcessor.cc
4309-        auto *sched = Sched::GetSchedule(state, nameUC);
4310-        if (sched != nullptr) {
4311-            numKeys = 1;
4312-            varType = VariableType::Schedule;
4313-            if (sched->schedTypeNum != Sched::SchedNum_Invalid) {
4314:                std::string const &schedTypeName = state.dataSched->scheduleTypes[sched->schedTypeNum]->Name;

ScheduleManager.cc
93-    // MODULE PARAMETER DEFINITIONS
94-    int GetScheduleTypeNum(EnergyPlusData &state, std::string const &name)
95-    {
96-        auto const &s_sched = state.dataSched;
97-        for (int i = 0; i < (int)s_sched->scheduleTypes.size(); ++i)
98:            if (s_sched->scheduleTypes[i]->Name == name) return i;
--
163-    bool DaySchedule::checkValsForLimitViolations(EnergyPlusData &state) const
164-    {
165-        auto &s_sched = state.dataSched;
166-
167-        if (this->schedTypeNum == SchedNum_Invalid) return false;
168:        auto *schedType = s_sched->scheduleTypes[this->schedTypeNum];
--
176-
177-    bool DaySchedule::checkValsForBadIntegers(EnergyPlusData &state) const
178-    {
179-        auto &s_sched = state.dataSched;
180-        if (this->schedTypeNum == SchedNum_Invalid) return false;
181:        auto *schedType = s_sched->scheduleTypes[this->schedTypeNum];
--
2008-        // Validate by ScheduleLimitsType
2009-        for (auto *sched : s_sched->schedules) {
2010-
2011-            if (sched->schedTypeNum == SchedNum_Invalid) continue;
2012-
2013:            auto const *schedType = s_sched->scheduleTypes[sched->schedTypeNum];
--
2175-                }
2176-                std::string_view constexpr SchDFmtdata0("DaySchedule,{},{},{},{}");
2177-                print(state.files.eio,
2178-                      SchDFmtdata0,
2179-                      daySched->Name,
2180:                      (daySched->schedTypeNum == SchedNum_Invalid) ? "" : s_sched->scheduleTypes[daySched->schedTypeNum]->Name,
--
2221-
2222-                int NumF = 1;
2223-                print(state.files.eio,
2224-                      "Schedule,{},{}",
2225-                      schedDetailed->Name,
2226:                      (sched->schedTypeNum == SchedNum_Invalid) ? "" : s_sched->scheduleTypes[sched->schedTypeNum]->Name);

SQLiteProcedures.cc
186-        }
187-        for (auto *sched : state.dataSched->schedules) {
188-            state.dataSQLiteProcedures->sqlite->addScheduleData(
189-                sched->Num,
190-                sched->Name,
191:                (sched->schedTypeNum == -1) ? "" : state.dataSched->scheduleTypes[sched->schedTypeNum]->Name,

OutputReportTabular.cc
6859-        PreDefTableEntry(state, state.dataOutRptPredefined->pdchLeedGenData, "Total gross floor area [m2]", "-");
6860-    }
6861-    // LEED schedule sub table
6862-    for (auto *sched : state.dataSched->schedules) {
6863-        if (sched->schedTypeNum == -1) continue;
6864:        if (!Util::SameString(state.dataSched->scheduleTypes[sched->schedTypeNum]->Name, "FRACTION")) continue;

**Review by jmarrec — APPROVED** [review]
LGTM, thanks!

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
This one has at least a format issue, but Linux also seems to be complaining.  I'll check it out.

**Comment by Myoldmopar** [comment]
I fixed the Clang format issue, but could not reproduce any build issues.  It's been a long time since I've rebooted the Linux CI machines so I'll do that if it comes back weird this time.  And if we need to tweak anything from the other schedule manager PR that just merged, I can do that here.

File: src/EnergyPlus/Data/EnergyPlusData.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/Data/EnergyPlusData.hh:602]: Yeah that's helpful for sure.

File: src/EnergyPlus/ScheduleManager.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/ScheduleManager.cc:2183]: I'd be inclined to say it's a little bit easier to read if this evaluation was split into a little const var just before this print call, but it's definitely not worth messing with now.

**Review by Myoldmopar — APPROVED** [review]
Looks good to me as well.  Thanks @amirroth, and @jmarrec for looking it over.
