### PR TITLE
Fixes DOAS system coils report cooling/heating power when system is off

### LINKED ISSUE #9339: DOAS system fan mass flow output does not match fan outlet system node mass flow rate output
Issue overview
--------------
A user recently reported that in a Dedicated Outdoor Air system case, the fan mass flow rate report does not match the system node mass flow report for the fan outlet node: the fan outputs reported a positive mass flow rate and also positive fan power; but the fan's outlet system node reported zero flow rate. 

This can be demonstrated by the slightly revised from the SmallOffice_CentralDOAS.idf example (with only output variables modifications): 
image
The fan output reports 0.3235 mass flow rate (it also reports a postive 235.81W fan energy); but the fan outlet system node reports 0 mass flow rate. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.4 to v22.1 iofreeze, or newer e.g. bfab14b526
 - Helpdesk ticket number: 16149

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file: see example file  SmallOffice_CentralDOAS.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9342: DOAS system coils report cooling/heating power when system is off
Issue overview
--------------
Output of 'Heating Coil Heating Rate' and 'Cooling Coil Total Cooling Rate' for coils on AirLoopHVAC:DedicatedOutdoorAirSystem will show the value of the last timestep that the system was on (i.e. flow thru the DOAS), through the period that it's off. This only happens when the coil availability is 'on'. As far as I can tell the total coil energy is correct, though. 

Tested with SmallOffice_CentralDOAS.idf:
image
image

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6.0

[SmallOffice_CentralDOAS_mod_idf.txt](https://github.com/NREL/EnergyPlus/files/8336062/SmallOffice_CentralDOAS_mod_idf.txt)

Maybe related to https://github.com/NREL/EnergyPlus/issues/9339

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9342 
 - Fixes #9339
 - AirLoopHVAC:DedicatedOutdoorAirSystem equipment list were not simulated if the DOAS flow rate is zero. Thus, report variables for equipment in the DOAS carry over report variable values from the previous time step. Allowing to simulate the components when there is no supply flow, component's Init function resets the report variables to zeros. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] ~Check any new function arguments for performance impacts~
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

**Comment by Nigusse** [comment]
This fix will investigate issue #9339 as well.

**Comment by Nigusse** [comment]
Sample results show plots of develop and this branch demonstrating the fix.  This branch shows zero heating coil heating rate when there is no supply air flow rate through the DOAS airloop.

Feb_OA_FlowRateHtgCoilHeatRate

Similarly, this branch shows zero total cooling rate when there is no supply air flow rate through the DOAS airloop.

July_OA_FlowRateClgCoilTotalCoolingRate

**Comment by Nigusse** [comment]
This fix addresses Issue #9339 as well. Now supply air fan flow rate and supply fan power values are reset to zero, when the AirLoopHVAC:DedicatedOutdoorAirSystem flow rate is zero.  See supply fan flow rate plots before and after the fix for the month of February and July.

Feb_OA_Airloop_SupplyFan_FlowRate


July Results:

July_OA_Airloop_SupplyFan_FlowRate

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -110,7 +110,7 @@ namespace AirLoopHVACDOAS {
 
         if (this->SumMassFlowRate == 0.0 && !state.dataGlobal->BeginEnvrnFlag) {
             state.dataLoopNodes->Node(this->m_CompPointerAirLoopMixer->OutletNodeNum).MassFlowRate = 0.0;
-            return;
+            if (state.dataGlobal->KickOffSimulation) return;
         }
 
         this->CalcAirLoopDOAS(state, FirstHVACIteration);
```
Comment (Nigusse) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:115]: This fix allows to execute *CalcAirLoopDOAS* function even if the *SumMassFlowRate* is zero and the *KickOffSimulation* is set to *FALSE*. Previously, the function  *CalcAirLoopDOAS* is not executed if the supply air flow rate is zero. Thereby, report variables for any component on the DOAS system will not be reset to zero, instead values of previous time step is carried over until the system flow rate is > 0.

**Comment by Nigusse** [comment]
Plots below demonstrate that report variable *Fan Electricity Rate* is zero when there is no DOAS air flow for this branch.

Feb_OA_AirloopFlowRate_FanPower

**Comment by Nigusse** [comment]
Diffs are expected in idfs with *AirLoopHVAC:DedicatedOutdoorAirSystem* object. Example file *SmallOffice_CentralDOAS.idf* has diffs because of this fix. Diffs shown in example file *SolarShadingTestGPU.idf* is not related to this fix

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 2]
```diff
@@ -110,7 +110,7 @@ namespace AirLoopHVACDOAS {
 
         if (this->SumMassFlowRate == 0.0 && !state.dataGlobal->BeginEnvrnFlag) {
             state.dataLoopNodes->Node(this->m_CompPointerAirLoopMixer->OutletNodeNum).MassFlowRate = 0.0;
-            return;
+            if (state.dataGlobal->KickOffSimulation) return;
         }
```
Comment (rraustad) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:113]: Shouldn't any report variables that need to be reset be done in initAirLoopDOAS? and then if there is no DOAS flow rate you could return here all the time. Would that work?

    if (this->SumMassFlowRate == 0.0) return;

Comment (Nigusse) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:113]: These are report variables of child objects such as fans, heating and cooling coils and are reported by the components themselves. `if (this->SumMassFlowRate == 0.0) return;` is already in the current code and did not work.

Comment (Nigusse) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:113]: Unless you simulate the child objects (Components on DOAS), report variables of child objects carry over values from the previous time step. I think, we also need to reset flow rates at the nodes of all child objects in the airloop.

**Comment by Nigusse** [comment]
Added unit test. Run the unit test suite in my machine and all passed.

**Comment by Nigusse** [comment]
This fix is ready for review. The diffs in example file (*SmallOffice_CentralDOAS.idf*) is expected and justified. However, I also see another example (*SolarShadingTestGPU.idf*) showing diffs but the later should not have been impacted by this fix.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: Why `return` when `KickOffSimulation` is true? My understanding of the kick off is to make sure that every component (including child components) is simulated at least once to make sure all input if processed and initialized.

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 3]
```diff
@@ -4462,4 +4464,3979 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestGetDesignDayConditions)
...
+    state->dataSurfaceGeometry->SinZoneRelNorth = 0.0;
+    state->dataSurfaceGeometry->CosBldgRelNorth = 1.0;
+    state->dataSurfaceGeometry->SinBldgRelNorth = 0.0;
+    SurfaceGeometry::GetSurfaceData(*state, ErrorsFound);
+    EXPECT_FALSE(ErrorsFound);
+
+    ZoneEquipmentManager::GetZoneEquipment(*state);
+    SimAirServingZones::GetAirPathData(*state);
+    // OA inlet node
+    state->dataLoopNodes->Node(2).MassFlowRate = 0.1;
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc]: The unit test is good, except node numbers can change. Instead of hard numbers, these should be integer lookups, e.g.
`    int zoneInlet = UtilityRoutines::FindItemInList("ZONE EQUIP INLET 1", state->dataLoopNodes->NodeID, state->dataLoopNodes->NumOfNodes);`

Comment (Nigusse) [reply tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc]: @mjwitte Thanks for reviewing this PR. I will update the unit test as suggested.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 1 above)
Comment (Nigusse) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: My first attempt was to remove the return statement altogether but the simulation fatal out because of SetPointManager has not yet set the controlled nodes set-point values. The `KickOffSimulation` flag allows to circumvent that situation. Is there any other way to do the same?

Comment (mjwitte) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: Not sure. I see `KickOffSimulation` checks scattered throughout the code, but nearly all of them as related for fault adjustments. Leave this as-is and I'll try to figure out why other systems don't fail during kickoff but this one does.

Comment (Nigusse) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: I reproduced the severe error message I was getting when I commented out the `return` statement. See below:

```
   ** Severe  ** HVACControllers: Missing temperature setpoint for controller type=Controller:WaterCoil Name="OA HC CONTROLLER 1"
   **   ~~~   ** Node Referenced (by Controller)=OA HEATING COIL 1 AIR OUTLET NODE
   **   ~~~   **   use a Setpoint Manager with Control Variable = "Temperature" to establish a setpoint at the controller sensed node.
   ** Severe  ** HVACControllers: Missing temperature setpoint for controller type=Controller:WaterCoil Name="OA CC CONTROLLER 1"
   **   ~~~   ** Node Referenced (by Controller)=AIRLOOPDOASSPLITTERINLET
   **   ~~~   **   use a Setpoint Manager with Control Variable = "Temperature" to establish a setpoint at the controller sensed node.
```

Comment (mjwitte) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: Interesting. I'm curious why other controllers don't complain during kickoff. Or is the airloop DOAS calling sequence misplaced?
It doesn't appear to be, it's called [here](https://github.com/NREL/EnergyPlus/blob/797ffe32e8141c6c822db9f26ac62b7ed1603302/src/EnergyPlus/SimAirServingZones.cc#L2633) in `SimAirLoops` after all of the airloops have already been simulate. So, why don't the air loops choke on missing setpoints?

Comment (mjwitte) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: `ManageSetpoints` is called here [in `SimHVAC`](https://github.com/NREL/EnergyPlus/blob/797ffe32e8141c6c822db9f26ac62b7ed1603302/src/EnergyPlus/HVACManager.cc#L799-L821) before `SimSelectedEquipment` which ultimately calls `SimAirLoopHVACDOAS`. So it seems `ManageSetpoints` should have already initialized those setpoints.

Comment (mjwitte) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: Found it!! The DOAS is copying entire node structs [here](https://github.com/NREL/EnergyPlus/blob/797ffe32e8141c6c822db9f26ac62b7ed1603302/src/EnergyPlus/AirLoopHVACDOAS.cc#L944-L948) which overwrites the setpoints. I think this `if (this->SumMassFlowRate == 0.0) {` block can be deleted now. Are there any other places that are checking for `SumMassFlowRate == 0`?

Comment (Nigusse) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: @mjwitte Great!. There are only two places. The one you found out in `initAirLoopDOAS(state, FirstHVACIteration)` and the offending code for this issue in `AirLoopDOAS::SimAirLoopHVACDOAS` [here](https://github.com/NREL/EnergyPlus/blob/182064950_Issue9342/src/EnergyPlus/AirLoopHVACDOAS.cc#L111-L114).

Comment (Nigusse) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:115]: OK. I deleted the if block [here](https://github.com/NREL/EnergyPlus/blob/797ffe32e8141c6c822db9f26ac62b7ed1603302/src/EnergyPlus/AirLoopHVACDOAS.cc#L944-L948) and also deleted the `if (state.dataGlobal->KickOffSimulation) return` statement [here](https://github.com/NREL/EnergyPlus/blob/182064950_Issue9342/src/EnergyPlus/AirLoopHVACDOAS.cc#L113). The defect file run successfully but the original `return` statement has to be deleted as well. I will push the updated unit test and the fix shortly. @mjwitte Thanks.

**Review by mjwitte — APPROVED** [review]
@Nigusse Looks good, except CI is complaining about formatting in tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 4]
```diff
@@ -4462,4 +4464,4007 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestGetDesignDayConditions)
...
+        UtilityRoutines::FindItemInList("PSZ-AC:2_OARELIEF NODE", state->dataLoopNodes->NodeID, state->dataLoopNodes->NumOfNodes));
+    auto &PSZAC_OARelNode_3 = state->dataLoopNodes->Node(
+        UtilityRoutines::FindItemInList("PSZ-AC:3_OARELIEF NODE", state->dataLoopNodes->NodeID, state->dataLoopNodes->NumOfNodes));
+    auto &PSZAC_OARelNode_4 = state->dataLoopNodes->Node(
+        UtilityRoutines::FindItemInList("PSZ-AC:4_OARELIEF NODE", state->dataLoopNodes->NodeID, state->dataLoopNodes->NumOfNodes));
+    auto &PSZAC_OARelNode_5 = state->dataLoopNodes->Node(
+        UtilityRoutines::FindItemInList("PSZ-AC:5_OARELIEF NODE", state->dataLoopNodes->NodeID, state->dataLoopNodes->NumOfNodes));
+    // set OA relief node data
+    PSZAC_OARelNode_1.MassFlowRate = 0.1;
+    PSZAC_OARelNode_2.MassFlowRate = 0.1;
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:8414]: @Nigusse And nice approach here, referencing the node, robust and readable! R&R

**Comment by Nigusse** [comment]
@mjwitte Addressed Clang Format Warning of the unit test. Now the clang format check is happy.

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc (hunk 4 above)
Comment (Nigusse) [reply tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:8414]: @mjwitte Thanks. You suggested the idea. Mostly, there is better or best way of doing things.

**Comment by mjwitte** [comment]
All clean (except apparently unrelated windows build error). Merging.
