### PR TITLE
Surface Outside Face Convection Heat Gain Rate was fixed when rain flag is true & to be altered for OSCM as well

### LINKED ISSUE #6939: Surface outside face heat balance reporting is confusing when rain flag is true
Issue overview
--------------
Using example file, looking at the surface outside face heat balance, it all balances to near zero except when the rain flag is true, e.g. 04/27 afternoon. These four variables should sum to zero:
```
  Output:Variable,*,Surface Outside Face Convection Heat Gain Rate,timestep;
  Output:Variable,*,Surface Outside Face Net Thermal Radiation Heat Gain Rate,timestep;
  Output:Variable,*,Surface Outside Face Solar Radiation Heat Gain Rate,timestep;
  Output:Variable,*,Surface Outside Face Conduction Heat Transfer Rate,timestep;
```
It seems that the reported value for Surface Outside Face Convection Heat Gain Rate is wrong when the rain flag is true. For example, at 04/27 13:00:00
image

Using the temperatures and convection coefficient, seems that the Surface Outside Face Convection Heat Gain Rate should be:
1000*(6.654 - 6.7179) * 58.2 = -3719W, but the reported value is 27642W.
Surface LGSTORE1_WALL_1 net area is 58.20m2.

Looks like the output variable calculation may be using outdoor dry bulb instead of wet bulb at these times.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus  9.0.0-d62a9089b1 (IDD freeze)
 - Unmethours [33630](https://unmethours.com/question/33630/mismatch-in-outside-surface-heat-balance-in-energyplus/?comment=33762#post-id-33762)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file: [RefBldgStripMallNew2004_Chicago - Copy-Annual-v90.idf.txt](https://github.com/NREL/EnergyPlus/files/2338235/RefBldgStripMallNew2004_Chicago.-.Copy-Annual-v90.idf.txt), run with Chicago TMY3.

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by dareumnam**
Pull request overview
---------------------
 - Fixes #6939 reporting for Surface Outside Face Convection (and Per Area) when raining
 - Also fixes Surface Outside Face Convection when using OtherSideConditionsModel (OSCM), the per Area value was correct and remains unchanged.

 - HeatBalanceSurfaceManager.cc & HeatBalanceSurfaceManager.hh
   - Add a function for QdotConvOutRepPerArea to separate cases
     - If Optr is set, use OSCM boundary data
     - If Optr is not set, 
       - If it is raining, (IsRain = True): `Surface Outside Face Convection Heat Gain Rate` calculation uses outdoor wet bulb temp.
       - Otherwise (IsRain = False):  `Surface Outside Face Convection Heat Gain Rate` calculation uses outdoor dry bulb temp.
 - Add a unit test to HeatBalanceSurfaceManager.unit.cc
 - Expected Diffs:
   - ESO Diffs: .csv output files of regression tests
     - that have `Output: Variable` of `Surface Outside Face Convection Heat Gain Rate` or `Surface Outside Face Convection Heat Gain Rate per Area` &&
     - that use a weather file that has at least one rainy day
     - this is likely to introduce small diffs in the Per Area output, because the surface area is no longer multiplied in and then divided back out.
### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [X] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [X] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [X] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~~
 - [ ] ~~If structural output changes, add to output rules file and add OutputChange label~~
 - [ ] ~~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~~

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~~If feature, test running new feature, try creative ways to break it~~
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [x] Check any new function arguments for performance impacts
 - [ ] ~~Verify IDF naming conventions and styles, memos and notes and defaults~~
 - [ ] ~~If new idf included, locally check the err file and other outputs~~

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 1]
```diff
@@ -5707,17 +5707,29 @@ namespace HeatBalanceSurfaceManager {
...
             }
+
             QConvOutReport(SurfNum) = QdotConvOutRep(SurfNum) * TimeStepZoneSec;
         } // ...end of DO loop over all surface (actually heat transfer surfaces)
     }
 
+    Real64 GetQdotConvOutRep(int SurfNum)
+    {
+        if (IsRain) {
+            return -Surface(SurfNum).Area * HcExtSurf(SurfNum) * (TH(1, 1, SurfNum) - Surface(SurfNum).OutWetBulbTemp);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: It would be more efficient to leave area out of this, using this function to set `QdotConvOutRepPerArea`, then `QdotConvOutRep = QdotConvOutRepPerArea * ...Area`

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 2]
```diff
@@ -5707,17 +5707,29 @@ namespace HeatBalanceSurfaceManager {
             }
 
             // fill in reporting values for outside face
-            QdotConvOutRep(SurfNum) = -Surface(SurfNum).Area * HcExtSurf(SurfNum) * (TH(1, 1, SurfNum) - Surface(SurfNum).OutDryBulbTemp);
+            
+            QdotConvOutRep(SurfNum) = GetQdotConvOutRep(SurfNum);
 
             if (Surface(SurfNum).OSCMPtr > 0) { // Optr is set above in this case, use OSCM boundary data
                 QdotConvOutRepPerArea(SurfNum) = -OSCM(OPtr).HConv * (TH(1, 1, SurfNum) - OSCM(OPtr).TConv);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: It's wrong here that `QdotConvOutRepPerArea` is altered for OSCM but not `QdotConvOutRep` (not your error but another one here).  

I would move this if into the new function as well.  Then this area of code becomes 2 lines:
```
QdotConvOutRepPerArea(SurfNum) = GetQdotConvOutRep(SurfNum);
QdotConvOutRep(SurfNum) = QdotConvOutRepPerArea(SurfNum) * Surface(SurfNum).Area;
```

Please update the title and description to mention fixing this for OSCM.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 3]
```diff
@@ -5707,17 +5707,29 @@ namespace HeatBalanceSurfaceManager {
...
     }
 
+    Real64 GetQdotConvOutRep(int SurfNum)
+    {
+        if (IsRain) {
+            return -Surface(SurfNum).Area * HcExtSurf(SurfNum) * (TH(1, 1, SurfNum) - Surface(SurfNum).OutWetBulbTemp);
+        } else {
+            return -Surface(SurfNum).Area * HcExtSurf(SurfNum) * (TH(1, 1, SurfNum) - Surface(SurfNum).OutDryBulbTemp);
+        }
+        return Real64();
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Is this line necessary? @Myoldmopar ?

File: tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc [hunk 4]
```diff
@@ -2504,50 +2504,75 @@ TEST_F(EnergyPlusFixture, HeatBalanceSurfaceManager_TestSurfTempCalcHeatBalanceA
...
+    DataHeatBalSurface::HcExtSurf(1) = 1000;
+    DataHeatBalSurface::TH(1, 1, 1) = 6.71793958923051;
+    DataSurfaces::Surface(1).OutWetBulbTemp = 6.66143784594778;
+    DataSurfaces::Surface(1).OutDryBulbTemp = 7.2;
+   
+    // If Rain Flag = on, GetQdotConvOutRep uses Outdoor Air Wet Bulb Temp.
+    DataEnvironment::IsRain = true;
+    Real64 ExpectedQconv1 = -58.197 * 1000 * (6.71793958923051 - 6.66143784594778);
+
+    EXPECT_EQ(ExpectedQconv1, GetQdotConvOutRep(1));
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc]: For Real64 calcs like this, we prefer `EXPECT_NEAR` with a small tolerance reasonable for the expected result magnitude: `EXPECT_NEAR(ExpectedQconv1, GetQdotConvOutRep(1), 0.01);`

**Review by mjwitte — CHANGES_REQUESTED** [review]
Current code fixes the defect as expected (will retest after changes).
See comments below.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc (hunk 2 above)
Comment (dareumnam) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @mjwitte Thank you for all the reviews. I will fix these as you suggested.

**Review by mjwitte — APPROVED** [review]
@dareumnam Thanks - changes look good. I made one more small change adding const to the SurfNum agrument in the new function. Once CI completes, this will be merged.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 5]
```diff
@@ -5707,17 +5707,30 @@ namespace HeatBalanceSurfaceManager {
...
-                QdotConvOutRepPerArea(SurfNum) = -HcExtSurf(SurfNum) * (TH(1, 1, SurfNum) - Surface(SurfNum).OutDryBulbTemp);
-            }
             QConvOutReport(SurfNum) = QdotConvOutRep(SurfNum) * TimeStepZoneSec;
+
         } // ...end of DO loop over all surface (actually heat transfer surfaces)
     }
 
+    Real64 GetQdotConvOutRepPerArea(int const SurfNum) 
+    {
+        int OPtr = Surface(SurfNum).OSCPtr;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @dareumnam Some integration tests are failing. Here's the problem - this should be `.OSCMPtr`.

Comment (dareumnam) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @mjwitte Oops, thank you for letting me know. I'll fix it and push the branch again.

**Comment by mjwitte** [comment]
That's looking much better now - 2 files with small eso diffs. I'll let CI run its course here.

**Comment by dareumnam** [comment]
I am guessing that these ESO diffs are coming from .csv output files that have `Surface Outside Face Convection Heat Gain Rate (Per Area)` of rainy days (hopefully).  I'll wait and see the CI testing results.

**Comment by mjwitte** [comment]
Yep, the diffs are in Surface Outside Face Convection Heat Gain Rate, on the order of e-11 or less.
