### PR TITLE
Fix #9204 - Overcome StdOutputRecordCount's limit of about 2.1 billion

### LINKED ISSUE #9204: Overcome StdOutputRecordCount's limit of about 2.1 billion
Issue overview
--------------

Recent a user reports the needs to report a very large number of output variables (into eso, and/or possibly sql as well) that exceeds the integer type limits of 2 147 883 647. Therefore, a question was asked about changing the “int” type definition of the variable state.dataGlobal->StdOutputRecordCount to an even “longer” integer type, such as “long int” to solve the problem. 

The problem is related to the code here: 
https://github.com/NREL/EnergyPlus/blob/e6e681da8720400b505a5fae4274a9b65e2b5275/src/EnergyPlus/SimulationManager.cc#L1826-L1831

If the count hits above the 32-bit integer upper limit, it will execute the “else” block and delete the entire output file. Another possible solution provided by the user is to use `StdOutputRecordCount != 0`, instead of `StdOutputRecordCount > 0`, that could exploit the negative overflow the `int` type to avoid the `else{` block to be executed in an overflow condition. 

The case as described by the user is about a 30 000 square meter building with 1000 area, using a 5-minute timestep for simulations. The user outputted a set of variables for each zone for an in-house automatic tools to check comfort and efficiency in each zone. With the settings, at each timestep the outputs contains 105 120 000 records. The 2.1 billion limit was quickly consumed up.

A few thoughts about this:
1.	Change the definition of `state.dataGlobal->StdOutputRecordCount` from `int` to `unsigned int` might double the limit, which is about 4.3 billion records. 
2.	It might ok to exploit the negative overflow value, e.g. as a temporary solution for the unexpected output eso deletion. But it is in general not a good practice to leave an overflow condition unattended there. But still the screen output of the count would be negative and incorrect. 
3.	In general, “long int” might be subject to the compiler’s or the machines’ interpretation on its length. It is said to be “at least 32bit”, which means there might be a possibility that some systems/compilers might just use 32 bit, which would not help to extend the limit if this happened to be the case? 
4. A quick search in the code found that the variable `state.dataGlobal->StdOutputRecordCount` seems to be used just an increment counter, and it is not used in any array index or anything else. This helps in not complicating the issue. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): at  least from v8.9 to 9.6
 - Helpdesk ticket number: 16081

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9204 

It's pretty much all unit testing... the fix was trivial, the test was clearly not.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DataGlobals.hh [hunk 1]
```diff
@@ -112,8 +112,8 @@ struct DataGlobal : BaseGlobalStruct
     int TimeStep = 0;                // Counter for time steps (fractional hours)
     Real64 TimeStepZone = 0.0;       // Zone time step in fractional hours
     bool WarmupFlag = false;         // True during the warmup portion of a simulation
-    int StdOutputRecordCount = 0;    // Count of Standard output records
-    int StdMeterRecordCount = 0;     // Count of Meter output records
+    Int64 StdOutputRecordCount = 0;  // Count of Standard output records
+    Int64 StdMeterRecordCount = 0;   // Count of Meter output records
```
Comment (jmarrec) [inline src/EnergyPlus/DataGlobals.hh:116]: Change StdOutputRecordCount & StdMeterRecordCount to Int64 (std::int64_t)

This increases the limit from 2,147,483,648 to 9,223,372,036,854,775,808 records

File: src/EnergyPlus/ConfiguredFunctions.in.cc [hunk 2]
```diff
@@ -57,7 +57,7 @@ fs::path configured_source_directory()
 
 fs::path configured_build_directory()
 {
-    return ("${CMAKE_BUILD_DIR}");
+    return ("${CMAKE_BINARY_DIR}");
```
Comment (jmarrec) [inline src/EnergyPlus/ConfiguredFunctions.in.cc:60]: Unrelated but was incorrect. I tried to use that to use an actual eso & mtr file instead of the open_as_stringstream to see if the test could work fast enough, but no.

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 3]
```diff
@@ -5350,6 +5352,138 @@ namespace OutputProcessor {
...
+
+        // Demonstrate that it's not unreasonable to reach the INT_MAX limit at all
+        constexpr int numOfTimeStepInHour = 60;
+        constexpr int hoursInYear = 8760;
+        constexpr int numOutputVariables = 4200;
+        constexpr size_t totalRecords =
+            static_cast<size_t>(numOfTimeStepInHour) * static_cast<size_t>(hoursInYear) * static_cast<size_t>(numOutputVariables);
+
+        constexpr auto INT_MAX_AS_SIZE_T = static_cast<size_t>(INT_MAX);
+        EXPECT_GT(totalRecords, INT_MAX_AS_SIZE_T);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5374]: It's not unreasonable to hit the INT_MAX limit

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 4]
```diff
@@ -5350,6 +5352,138 @@ namespace OutputProcessor {
...
+            if (found_about_to_overflow) {
+                break;
+            }
+        }
+        ASSERT_TRUE(found_about_to_overflow);
+        EXPECT_EQ(numOutputVariables + 1, state->dataGlobal->StdOutputRecordCount);
+        EXPECT_EQ(1, state->dataGlobal->StdMeterRecordCount);
+        EXPECT_TRUE(has_eso_output(true));
+        state->dataGlobal->StdOutputRecordCount = records_written;
+        state->dataGlobal->StdMeterRecordCount = INT_MAX;
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5478]: Fake having written the record for all timesteps until it overflows. if I don't fake it, it's unbearably slow

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc [hunk 5]
```diff
@@ -5350,6 +5352,138 @@ namespace OutputProcessor {
...
+
+        ++state->dataGlobal->TimeStep;
+
+        UpdateMeterReporting(*state);
+        UpdateDataandReport(*state, TimeStepType::Zone);
+        EXPECT_GT(state->dataGlobal->StdOutputRecordCount, 0);
+        EXPECT_GT(state->dataGlobal->StdMeterRecordCount, 0);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/OutputProcessor.unit.cc:5485]: Get it to overflow over INT_MAX

File: src/EnergyPlus/ConfiguredFunctions.in.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/ConfiguredFunctions.in.cc:60]: Wow.  Good catch.

File: src/EnergyPlus/DataGlobals.hh (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DataGlobals.hh:116]: Hmmmm.  OK, I believe you.  I guess that should be big enough :laughing:

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc (hunk 3 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/OutputProcessor.unit.cc:5374]: OK OK I said I believed you.

File: tst/EnergyPlus/unit/OutputProcessor.unit.cc (hunk 5 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/OutputProcessor.unit.cc:5485]: :+1:

**Review by Myoldmopar — APPROVED** [review]
Looks great.  And testing locally for kicks.

**Comment by Myoldmopar** [comment]
All happy here.  Let's merge.  Thanks @jmarrec
