### PR TITLE
Correct WaterUse:Equipment hot/cold mixing logic

### LINKED ISSUE #9650: Unrealistic behavior of Wateruse:Equipment when Hot Water is colder than Cold Water
Issue overview
--------------
I have a model with a service water heating loop shown below. On the demand side, there is a Pipe:Indoor object (circled in red) with an ambient temperature of 80F to capture piping losses. This is followed by a WaterUse:Connection object referencing a WaterUse:Equipment object with a target temperature of 140F, and a water draw profile that goes to zero at night. On the supply side, there is a Pump:ConstantSpeed set to intermittent (assuming recirculation stops at night when no water draw is expected), followed by a WaterHeater:Mixed object with a setpoint of 140F.

image

What happens is that at the beginning of the year, the simulation behaves as expected. The pipe inlet (blue) is as-expected (~140F). The pipe outlet (orange) is as-expected, lower than the inlet, in this case the delta-T is high for illustration purposes. The water mains temperature (dark red) is taken from the .stat file, and goes from a low of ~60F in winter to a high of ~85F in summer.

During the winter, the "Hot" water coming into the WaterUse:Connections object from the pipe outlet is hotter than the "Cold" water from the water mains. The WaterIUse:Connections object functions as-expected, with all the flow coming from the "Hot" water side (light green). In this case it is unable to meet the 140F target temperature, and warnings are thrown, but that isn't the problem.  The problem is that as soon as the "Cold" water from the mains is hotter than the "Hot" water from the pipe outlet (due to the high heat loss from the pipes and the 80F ambient temperature, then the WaterUse:Connections object changes and decides that all flow should come from the "Cold" side (dark green) because it is closer to the target temperature.

water_heating

### Expected Behavior
In a typical building's service hot water system, if there is no recirculator, or if the recirculator turns off overnight when there is no water draw, the temperature of the water in the hot water piping system will drop down to roughly the ambient temperature where the pipes are located, typically ~70-80F. In the morning when the hot water draws start, the flow starts again and someone will leave it running long enough until this ambient-temperature water is cleared from the pipes and actual hot water starts coming out. Prior to EnergyPlus 9.6, this was the observed behavior. The current behavior is to see if the cold water is warmer, and if it is, use that instead of waiting for the hot water. By my judgment, this does not match how real buildings are typically operated. Whether the hot water system is properly designed so that a person doesn't have to wait a long time to get hot water is a separate issue. In my example model, the system isn't designed properly, which the warnings helped identify.

I believe that the behavior was changed as part of https://github.com/NREL/EnergyPlus/pull/8808.  I really like this PR because it adds lots of helpful warnings about the state of the SWH system. However, I believe that the behavior should be changed back to represent what is more common in real buildings. Users who aren't modeling piping losses will likely not be impacted, and users who have legitimate problems with hot water supply temperatures will still get the warnings.

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (22.1)

### Checklist
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/9507634/in.idf.txt)
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9650. Supersedes #9651.
 - Logic for WaterUse:Equipment was upgraded to include times when the hot water temperature was colder than the cold water temperature. For example when a conductive pipe (e.g., Pipe:Indoor) is used and stagnant hot water can become colder due to pipe losses.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterUse.cc [hunk 1]
```diff
@@ -603,6 +603,15 @@ namespace WaterUse {
...
         }
+        // need a good place to set a bool to calculate WaterUse hot and cold flow rates in CalcEquipmentFlowRates
+        // WaterUse can be used with or without WaterUse:Connections, with or without WaterUse:Equipment hot temp schedule
+        for (int WaterEquipNum = 1; WaterEquipNum <= state.dataWaterUse->numWaterEquipment; ++WaterEquipNum) {
+            // set logical if either hot water temp or target temp schedule are missing (will use cold water otherwise)
+            // if a connections object is used then don't need to hot temp schedule
+            state.dataWaterUse->WaterEquipment(WaterEquipNum).allowHotControl =
+                state.dataWaterUse->WaterEquipment(WaterEquipNum).TargetTempSchedule &&
+                (state.dataWaterUse->WaterEquipment(WaterEquipNum).HotTempSchedule || state.dataWaterUse->WaterEquipment(WaterEquipNum).Connections);
+        }
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:591]: Priority 1: need a flag set early to know whether to calculate hot/cold mixing. Where to do this is likely here, how to get this right is a question.

File: src/EnergyPlus/WaterUse.cc [hunk 2]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
         this->TotalMassFlowRate = this->TotalVolFlowRate * Psychrometrics::RhoH2O(DataGlobalConstants::InitConvTemp);
 
         // Calculate hot and cold water mixing at the tap
-        if (this->TotalMassFlowRate > 0.0) {
+        if (this->TotalMassFlowRate > 0.0 && this->allowHotControl) {
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:1079]: If hot water mixing is allowed, do this mixing, otherwise drop to end and set the else

File: src/EnergyPlus/WaterUse.cc [hunk 3]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
...
             // Calculate the flow rates needed to meet the target temperature
-            if (this->HotTemp == this->ColdTemp) { // Avoid divide by zero
-                // There is no hot water
+            if (this->TargetTemp <= this->ColdTemp + EPSILON) {
+                // don't need to mix (use cold) or hot water flow would be very small if within EPSILON above cold temp (use cold)
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:1082]: Here is the tier if block. What to do. It's a logical method using the target temp. If too cold, use cold. If too hot, use hot. If in between, use most relavent logic.

File: src/EnergyPlus/WaterUse.cc [hunk 4]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
...
-                TempDiff = this->ColdTemp - this->HotTemp;
-                this->HotMassFlowRate = 0;
                 if (!state.dataGlobal->WarmupFlag) {
-                    // print error for variables of hot water temperature
-                    ++this->CWHWTempErrorCount;
-                    if (this->CWHWTempErrorCount < 2) {
+                    // print error for variables of target water temperature
+                    ++this->TargetCWTempErrorCount;
+                    TempDiff = this->ColdTemp - this->TargetTemp;
+                    if (this->TargetCWTempErrorCount < 2) {
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:1088]: Existing warnings pulled in where appropriate

File: src/EnergyPlus/WaterUse.cc [hunk 5]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
...
+                                this->Name),
+                            this->TargetCWTempErrIndex,
                             TempDiff,
                             TempDiff);
                     }
                 }
-            } else if (this->TargetTemp > (this->HotTemp + EPSILON)) {
-                // Target temp is hotter than the hot water temp; can't meet target temperature
+            } else if (this->TargetTemp > this->HotTemp - EPSILON) {
+                // don't need to mix (use hot) or cold water flow would be very small (use hot), or need to purge stagnant hot water temps (use hot)
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc]: Gotta think if target temp > hot temp then use hot water flow. Maybe there are corner cases, idk.

File: src/EnergyPlus/WaterUse.cc [hunk 6]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
...
-                    } else {
-                        ShowRecurringWarningErrorAtEnd(
-                            state,
-                            format(
-                                "\"{}\" - Target water temperature should be greater than or equal to the cold water temperature error continues...",
-                                this->Name),
-                            this->TargetCWTempErrIndex,
-                            TempDiff,
-                            TempDiff);
+                // Check hot less than cold temp, else calculate hot flow.
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:1168]: and finally the else. if the hot temp is lower than cold temp, post warning, otherwise calculate hot flow.

File: src/EnergyPlus/WaterUse.cc [hunk 7]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
...
 
             this->ColdMassFlowRate = this->TotalMassFlowRate - this->HotMassFlowRate;
-
-            if (this->ColdMassFlowRate < 0.0) this->ColdMassFlowRate = 0.0;
-
             this->MixedTemp = (this->ColdMassFlowRate * this->ColdTemp + this->HotMassFlowRate * this->HotTemp) / this->TotalMassFlowRate;
+            // there should be no out of bounds results
+            assert(this->ColdMassFlowRate >= 0.0 && this->ColdMassFlowRate <= this->TotalMassFlowRate);
+            assert(this->HotMassFlowRate >= 0.0 && this->HotMassFlowRate <= this->TotalMassFlowRate);
+            assert(std::abs(this->HotMassFlowRate + this->ColdMassFlowRate - this->TotalMassFlowRate) < EPSILON);
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:1210]: based on previous logic, the calculation of HotMassFlow should be within 0 and max flow. I said should, but pretty confident at this point. Added asserts to help identify.

File: src/EnergyPlus/WaterUse.cc [hunk 8]
```diff
@@ -1092,117 +1099,142 @@ namespace WaterUse {
...
         } else {
             this->HotMassFlowRate = 0.0;
-            this->ColdMassFlowRate = 0.0;
+            this->ColdMassFlowRate = this->TotalMassFlowRate;
```
Comment (rraustad) [inline src/EnergyPlus/WaterUse.cc:1213]: And if not MassFlow > 0 || this->allowHotControl, then ColdMassFlowRate should be = to what was calculated before entering this if block.

... and done.

File: src/EnergyPlus/WaterUse.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/WaterUse.cc:1079]: Priority 2: get this logic right

File: src/EnergyPlus/WaterUse.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/WaterUse.cc:1082]: One more thing is the use of EPSILON here and other places should? mean that the final calculation will never be < 0 or > max. Fingers crossed.

    this->HotMassFlowRate = this->TotalMassFlowRate * (this->TargetTemp - this->ColdTemp) / (this->HotTemp - this->ColdTemp);

File: src/EnergyPlus/WaterUse.cc (hunk 1 above)
Comment (amirroth) [inline src/EnergyPlus/WaterUse.cc:591]: Can use `auto &thisWaterEquip` here for readability. Actually, if you are not even using the `WaterEquipNum` index for anything else, you can use a range loop (an @mjwitte favorite!) `for (auto &thisWaterEquip : state.dataWaterUse->WaterEquipment)`.

File: src/EnergyPlus/WaterUse.hh [hunk 9]
```diff
@@ -161,73 +155,64 @@ namespace WaterUse {
...
+        Real64 Energy = 0.0;      // Heating energy required to raise temperature from cold to hot (J)
+        int NumWaterEquipment = 0;
+        int MaxIterationsErrorIndex = 0; // recurring error index
         Array1D_int myWaterEquipArr;
-        PlantLocation plantLoc;
-        bool MyEnvrnFlag;
+        PlantLocation plantLoc{};
+        bool MyEnvrnFlag = true;
 
         WaterConnectionsType()
```
Comment (amirroth) [inline src/EnergyPlus/WaterUse.hh]: These empty declarations are not necessary.

File: src/EnergyPlus/WaterUse.hh [hunk 10]
```diff
@@ -271,28 +256,22 @@ namespace WaterUse {
...
-    int numWaterEquipment;
-    int numWaterConnections;
-    bool getWaterUseInputFlag;
-    bool MyEnvrnFlagLocal;
+    int numWaterEquipment = 0;
+    int numWaterConnections = 0;
+    bool getWaterUseInputFlag = true;
+    bool MyEnvrnFlagLocal = true;
     Array1D_bool CheckEquipName;
     Array1D<WaterUse::WaterEquipmentType> WaterEquipment;
```
Comment (amirroth) [inline src/EnergyPlus/WaterUse.hh]: Use `EPVector` instead of `Array1D` for objects.

File: tst/EnergyPlus/unit/WaterUse.unit.cc [hunk 11]
```diff
@@ -449,15 +449,24 @@ TEST_F(EnergyPlusFixture, WaterUse_WaterTempWarnings)
...
+        "   **   ~~~   ** ...hot water temperature        = 10.00 C",
         "   **   ~~~   ** ...cold water temperature       = 15.00 C",
-        "   **   ~~~   ** ...Note: hot water temperature should be greater than or equal to the cold water temperature",
         "   **   ~~~   ** ...Hot water temperature should be greater than or equal to the cold water temperature. Verify temperature setpoints and "
         "schedules.",
     });
 
     EXPECT_TRUE(compare_err_stream(error_string1, true));
 
+    // configuration allows hot water mixing. A target temp schedule exists with either a hot temp schedule or a connnections object
```
Comment (amirroth) [inline tst/EnergyPlus/unit/WaterUse.unit.cc:462]: Can/should use `auto &thisWaterEquip` in unit tests also.

File: src/EnergyPlus/WaterUse.cc (hunk 5 above)
Comment (rraustad) [reply src/EnergyPlus/WaterUse.cc]: Changed from (this->HotTemp - EPSILON) to (this->HotTemp + EPSILON) to minimize diffs (same 2 diffs as #9651). This should be - EPSILON (or don't use EPSILON) to ensure the target temp is between cold and hot temp. If target temp is slightly > hot temp (i.e., greater by less than 0.001), then the fraction (this->TargetTemp - this->ColdTemp) / (this->HotTemp - this->ColdTemp) will be > 1 (e.g., 1.00009). I tried getting rid of EPSILON and got lot's of diffs but then that is expected. The issue is to be sure that the multiplier below is between 0 and 1.

    this->HotMassFlowRate = this->TotalMassFlowRate * (this->TargetTemp - this->ColdTemp) / (this->HotTemp - this->ColdTemp);

Comment (rraustad) [reply src/EnergyPlus/WaterUse.cc]: Nope, I am getting an assert with this code the way it is. Have to change it and take the hit on diffs.

image

**Comment by rraustad** [comment]
Besides warmup convergence diffs and correcting the defect file and 2 example files as in #9651, I see these small blips of cold water flow at 1E-19 in develop but not in this branch. That looks like a valid correction to the model?

image

**Comment by Myoldmopar** [comment]
I certainly like seeing all the e-19 requests flattened out to zero.  Is the develop branch trying to simulate my kids leaving the faucets dripping?

**Comment by Myoldmopar** [comment]
I would love to see if we can sneak this fix in for the release.  Anyone else have interest in chiming in on either the code changes or the results impact?

File: src/EnergyPlus/WaterUse.hh [hunk 12]
```diff
@@ -87,58 +87,48 @@ namespace WaterUse {
...
+        Real64 LatentRateNoMultiplier = 0.0;
+        Real64 MoistureRate = 0.0;
+        Real64 MoistureMass = 0.0;
+        Real64 ColdVolume = 0.0;  // Water consumption (m3)
+        Real64 HotVolume = 0.0;   // Water consumption (m3)
+        Real64 TotalVolume = 0.0; // Water consumption (m3)
+        Real64 Power = 0.0;       // Heating rate required to meet the mixed water temperature (W)
+        Real64 Energy = 0.0;      // Heating energy required to meet the mixed water temperature (J)
+        bool setupMyOutputVars = true;
+        bool allowHotControl = false; // only certain configurations will use hot water flow and/or hot water temp schedule
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterUse.hh:131]: Initializing at the member declaration is always an appreciated cleanup.

File: src/EnergyPlus/WaterUse.hh [hunk 13]
```diff
@@ -271,28 +248,17 @@ namespace WaterUse {
...
-        this->MyEnvrnFlagLocal = true;
-        this->CheckEquipName.deallocate();
-        this->WaterEquipment.deallocate();
-        this->WaterConnections.deallocate();
-    }
-
-    // Default Constructor
-    WaterUseData() : numWaterEquipment(0), numWaterConnections(0), getWaterUseInputFlag(true), MyEnvrnFlagLocal(true)
-    {
+        new (this) WaterUseData();
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterUse.hh:261]: Placement new is OK in this member function, but we should be cautious as some folks might try to use it inside constructors to call other constructors, which is frowned upon.

File: tst/EnergyPlus/unit/WaterUse.unit.cc [hunk 14]
```diff
@@ -441,60 +441,68 @@ TEST_F(EnergyPlusFixture, WaterUse_WaterTempWarnings)
...
+        "   **   ~~~   ** ...target water temperature     = 0.00 C",
         "   **   ~~~   ** ...cold water temperature       = 15.00 C",
-        "   **   ~~~   ** ...Note: target water temperature should be greater than or equal to the cold water temperature",
         "   **   ~~~   ** ...Target water temperature should be greater than or equal to the cold water temperature. Verify temperature setpoints "
         "and schedules.",
     });
 
     EXPECT_TRUE(compare_err_stream(error_string3, true));
+    EXPECT_GT(thisWaterEquipment.ColdMassFlowRate, 0.0);
+    EXPECT_NEAR(thisWaterEquipment.ColdMassFlowRate + thisWaterEquipment.HotMassFlowRate, thisWaterEquipment.TotalMassFlowRate, 0.00000001);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/WaterUse.unit.cc:507]: Nice small cleanups here and added assertions.

File: src/EnergyPlus/WaterUse.cc [hunk 15]
```diff
@@ -133,24 +127,23 @@ namespace WaterUse {
         if (!state.dataGlobal->BeginEnvrnFlag) state.dataWaterUse->MyEnvrnFlagLocal = true;
 
         // Simulate all unconnected WATER USE EQUIPMENT objects
-        for (WaterEquipNum = 1; WaterEquipNum <= state.dataWaterUse->numWaterEquipment; ++WaterEquipNum) {
-            if (state.dataWaterUse->WaterEquipment(WaterEquipNum).Connections == 0) {
-                state.dataWaterUse->WaterEquipment(WaterEquipNum).CalcEquipmentFlowRates(state);
-                state.dataWaterUse->WaterEquipment(WaterEquipNum).CalcEquipmentDrainTemp(state);
+        for (auto &waterEquipment : state.dataWaterUse->WaterEquipment) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterUse.cc:130]: Yes!  For loops where we do not care about the index at all, and simply want to iterate over every object in a list, using range based loops with references to the objects helps avoid accidental indexing problems, and lets us rely on compilers for handling the underlying looping.  I know they may not always be preferred, but in this use case, they are awesome and simple.

File: src/EnergyPlus/WaterUse.cc [hunk 16]
```diff
@@ -133,24 +127,23 @@ namespace WaterUse {
...
-        for (WaterConnNum = 1; WaterConnNum <= state.dataWaterUse->numWaterConnections; ++WaterConnNum) {
-            auto &waterConnection = state.dataWaterUse->WaterConnections(WaterConnNum);
+        for (auto &waterConnection : state.dataWaterUse->WaterConnections) {
 
             if (!waterConnection.StandAlone) continue; // only model non plant connections here
 
             waterConnection.InitConnections(state);
 
-            NumIteration = 0;
+            int NumIteration = 0;
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterUse.cc:146]: Localized, :+1:

File: src/EnergyPlus/WaterUse.cc [hunk 17]
```diff
@@ -225,19 +216,18 @@ namespace WaterUse {
...
+                        waterEquipment.setupMyOutputVars = false;
                     }
                 }
             }
 
             if (state.dataWaterUse->numWaterConnections > 0) {
-                for (auto &e : state.dataWaterUse->WaterConnections)
-                    e.TotalMassFlowRate = 0.0;
+                for (auto &waterConnections : state.dataWaterUse->WaterConnections)
+                    waterConnections.TotalMassFlowRate = 0.0;
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterUse.cc:230]: Although braces aren't necessary here, I still like to have them.  In this case, it would be easy for someone to add another calculation to the next line and not realize they aren't adding it in that scope.  In that case, it may cause a compiler error due to variable scope, or compiler warning if the compiler figures out what happened, but still, braces are intentional and explicit.  Not necessary to change now unless there are other changes to be made.

File: src/EnergyPlus/WaterUse.cc [hunk 18]
```diff
@@ -548,16 +529,17 @@ namespace WaterUse {
 
                     if (WaterEquipNum == 0) {
                         ShowSevereError(
-                            state, "Invalid " + state.dataIPShortCut->cAlphaFieldNames(AlphaNum) + '=' + state.dataIPShortCut->cAlphaArgs(AlphaNum));
-                        ShowContinueError(state,
-                                          "Entered in " + state.dataIPShortCut->cCurrentModuleObject + '=' + state.dataIPShortCut->cAlphaArgs(1));
+                            state,
+                            format("Invalid {} = {}", state.dataIPShortCut->cAlphaFieldNames(AlphaNum), state.dataIPShortCut->cAlphaArgs(AlphaNum)));
```
Comment (Myoldmopar) [inline src/EnergyPlus/WaterUse.cc:533]: Nice format cleanups.

File: src/EnergyPlus/WaterUse.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterUse.cc:591]: OK, seems reasonable.

File: src/EnergyPlus/WaterUse.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterUse.cc:1079]: It's a bit tough to follow here on the GitHub view, but still, seems reasonable.

File: src/EnergyPlus/WaterUse.cc (hunk 6 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterUse.cc:1168]: OK

File: src/EnergyPlus/WaterUse.cc (hunk 7 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterUse.cc:1210]: Very nice.

File: src/EnergyPlus/WaterUse.cc (hunk 8 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WaterUse.cc:1213]: All cold here, :+1:

**Review by Myoldmopar — APPROVED** [review]
This seems like a fine set of changes.  I'm always surprised to find the amount of complexity required to simulate what seems like such a simple system in real life, but such is our world.  I won't claim to have thought through every possible corner case, but it looks like this has been well thought out, cleaned up, and tested, so I think it's good to go.

**Comment by Myoldmopar** [comment]
@rraustad so this overrides #9651 right?  That PR won't be needed based on your overhaul here.  

If anyone has additional thoughts, speak up, otherwise this will merge shortly.

**Comment by rraustad** [comment]
Yes to the over-ride, supersedes #9651. That's what got this in motion.

**Comment by Myoldmopar** [comment]
Thanks @rraustad I'm going to merge now.  This is good stuff.

File: src/EnergyPlus/WaterUse.cc [hunk 19]
```diff
@@ -1193,16 +1108,109 @@ namespace WaterUse {
...
             this->MixedTemp = (this->ColdMassFlowRate * this->ColdTemp + this->HotMassFlowRate * this->HotTemp) / this->TotalMassFlowRate;
+            // there should be no out of bounds results
+            assert(this->ColdMassFlowRate >= 0.0 && this->ColdMassFlowRate <= this->TotalMassFlowRate);
+            assert(this->HotMassFlowRate >= 0.0 && this->HotMassFlowRate <= this->TotalMassFlowRate);
+            assert(std::abs(this->HotMassFlowRate + this->ColdMassFlowRate - this->TotalMassFlowRate) < EPSILON);
         } else {
             this->HotMassFlowRate = 0.0;
-            this->ColdMassFlowRate = 0.0;
+            this->ColdMassFlowRate = this->TotalMassFlowRate;
             this->MixedTemp = this->TargetTemp;
```
Comment (mjwitte) [inline src/EnergyPlus/WaterUse.cc:1214]: Now that the line above sets `this->ColdMassFlowRate = this->TotalMassFlowRate;` this line should be 
`this->MixedTemp = this->ColdTemp`

Comment (rraustad) [reply src/EnergyPlus/WaterUse.cc:1214]: I agree with you but lines 1040 - 1057 dictate the target so a wrong target with a water use object that has no connections and no hot water temp or target schedules should come out with whatever the user incorrectly entered. Based on the logic at line 590. If both schedules are missing they will get the right answer. I guess a warning if one or the other schedule is entered that it won't be used and then fix that specific target temp logic.

Comment (mjwitte) [reply src/EnergyPlus/WaterUse.cc:1214]: Ok, I think I understand. You've examined this logic much more than I have, so Ok.
