### PR TITLE
Fix crash if number of ATUs on one airloop exceeds number of zones and Fix OA Details Report with Multipliers

### LINKED ISSUE #8048: An air loop serving more terminal units than the number of zones will exceed array bounds
Issue overview
--------------
User file includes a DOAS system serving two terminal units in each zone. This results in an array bounds error in [`SimAirServingZones`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SimAirServingZones.cc#L1785) because the various scratch arrays here have only been allocated to `NumOfZones`.

Workaround
---------------
Break up the air loop(s) so that no airloop serves more terminal units than the number of zones.

Developer Notes
-------------------
1. The simple fix may be to allocate [these arrays](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SimAirServingZones.cc#L1587-L1595) to the total number of terminal units. (Or refactor these to vectors and `push` to them.)
2. But it's not clear if duplicate zone numbers in `AirToZoneNodeInfo(AirLoopNum).CoolCtrlZoneNums` will cause problems elsewhere, so that may require some additional work.
3. And the zone air balances in `ZoneEquipmentManager::CalcZoneReturnFlows` and `ZoneEquipmentManager::CalcZoneMassBalance` need to be checked to see if it's a problem to have two terminal units from the same air loop in a zone.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 9.4.0 https://github.com/NREL/EnergyPlus/commit/5df9c2a505fdbc61ae00046ee9455992b0bac313
 - Helpdesk ticket number 15471.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9491: Outdoor Air Details total Design Zone Outdoor Airflow is incorrect with zone multipliers in some cases
Issue overview
--------------
In the Outdoor Air Details report, the total for "Design Zone Outdoor Airflow - Voz" is incorrect when multipliers are used (if the zones and ATUs are not aligned one-to-one. Shows up in ASHRAE901_ApartmentMidRise_STD2019_Denver, ASHRAE901_Hospital_STD2019_Denver, and ASHRAE901_OfficeLarge_STD2019_Denver.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v22.1.0
 - Discovered while working on #9487

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #8048
 - In `InitAirLoops`, the temporary arrays used to map ATUs to airloops were sized for the number of zones, but need to be sized to the number of ATUs.
 - Move these temporary arrays out of `state`, since they are used only in `InitAirLoops`.
 - Fixes #9491 An incorrect zone number in ManageSystemVentilationAdjustments was being used to apply zone multipliers when totaling Design Outdoor Air Flow Rate for the Output Details report. This causes diffs for simulations with multipliers > 1 where the zone ATUs do not align with the actual zones.
 - Added some references for readability.
 - Removed some unused using statements.
 - Lots of variable scope reduction

### Diffs and Fixes ##
For #9491 Diffs in ASHRAE901_ApartmentMidRise_STD2019_Denver, ASHRAE901_Hospital_STD2019_Denver, and ASHRAE901_OfficeLarge_STD2019_Denver. In the Output Details Report, the Total for "Design Zone Outdoor Airflow - Voz" was using the wrong multipliers. The files have zone or zonegroup multipliers.

For #8048 the defect file runs to completion with an array bounds crash.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] ~If structural output changes, add to output rules file and add OutputChange label~
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SizingManager.cc [hunk 1]
```diff
@@ -1857,170 +1852,171 @@ void ManageSystemVentilationAdjustments(EnergyPlusData &state)
...
                     // Outdoor Air Details Report - Design Zone Outdoor Airflow - Voz
                     Real64 VozMax = std::max(VozHtg, VozClg); // take larger of the heating and cooling Voz values
                     OutputReportPredefined::PreDefTableEntry(
-                        state, state.dataOutRptPredefined->pdchOaMvDesZnOa, TermUnitFinalZoneSizing(termUnitSizingIndex).ZoneName, VozMax, 4);
-                    state.dataOutRptPredefined->TotalVozMax +=
-                        VozMax * state.dataHeatBal->Zone(zoneNum).Multiplier * state.dataHeatBal->Zone(zoneNum).ListMultiplier;
+                        state, state.dataOutRptPredefined->pdchOaMvDesZnOa, thisTermUnitFinalZoneSizing.ZoneName, VozMax, 4);
+                    state.dataOutRptPredefined->TotalVozMax += VozMax *
+                                                               state.dataHeatBal->Zone(thisTermUnitFinalZoneSizing.ActualZoneNum).Multiplier *
+                                                               state.dataHeatBal->Zone(thisTermUnitFinalZoneSizing.ActualZoneNum).ListMultiplier;
```
Comment (rraustad) [inline src/EnergyPlus/SizingManager.cc:1986]: This seems like the same thing zoneNum -> thisTermUnitFinalZoneSizing.ActualZoneNum inside a loop of 1 to NumZones.

Comment (mjwitte) [reply src/EnergyPlus/SizingManager.cc:1986]: But it's not, because the original `ZoneNum` was looping over just the heated or cooled zones on an airloop. The loop counter is renamed here to `airLoopZoneNum `

File: src/EnergyPlus/SimAirServingZones.cc [hunk 2]
```diff
@@ -1515,14 +1516,15 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
         // Allocate scratch arrays for storing controlled zone numbers for each air loop.
-        state.dataSimAirServingZones->CtrlZoneNumsCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->CtrlZoneNumsHeat.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->ZoneInletNodesCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->ZoneInletNodesHeat.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermInletNodesCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermInletNodesHeat.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermUnitSizingNumsCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermUnitSizingNumsHeat.allocate(state.dataGlobal->NumOfZones);
+        int atuArraySize = max(state.dataGlobal->NumOfZones, state.dataDefineEquipment->AirDistUnit.size());
```
Comment (amirroth) [inline src/EnergyPlus/SimAirServingZones.cc]: Are all of these arrays always indexed by the same index? Or at least are all the ones that end in Heat or Cool always indexed by the same index? If so, suggest: 

```cpp
struct X { int CtrlZoneNum; int ZoneInletNode; int TermInletNode; int TermUnitSizingNum; } 
EPVector<struct X> XCool, XHeat;
```

I know that during the EnergyPlus 10X project I extolled the virtues of arrays of scalars over arrays of structs, but that was:
- For `struct`'s that had 200 fields, not 4. 
- For code in tight, high frequency loops that could potentially vectorize.

In general, I think EnergyPlus needs to swing the other way. Rather than a combination of arrays of giant `struct`'s and arrays of scalars, it would be better to have arrays of smaller, well-thought out `struct`'s. This would strike a good balance between array management and traversal overhead, cache/page locality, and code readability. This is exhibit A. </mini-rant>

Comment (mjwitte) [reply src/EnergyPlus/SimAirServingZones.cc]: Not all of them are indexed the same. There might be groupings to consider. But these don't even belong in `state`, because they are only used in this function. Moving them out of `state` in the next pass here, along with localizing loop indices and a bunch of other integers.

Comment (amirroth) [reply src/EnergyPlus/SimAirServingZones.cc]: I am primarily using this as an opportunity to make a general point. I don't know whether that point applies on a case-by-case basis, and it may not apply here. I will probably make this point several more times in different places, where again it probably will not apply. 🤷

File: src/EnergyPlus/SizingManager.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/SizingManager.cc:1986]: It sure is. That's definitely not 1 to NumZones.

    numZones = AirToZoneNodeInfo(AirLoopNum).NumZonesCooled; (or Heated)
    for (int airLoopZoneNum = 1; airLoopZoneNum <= numZones; ++airLoopZoneNum) {

File: src/EnergyPlus/SimAirServingZones.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/SimAirServingZones.cc]: structed as suggested in https://github.com/NREL/EnergyPlus/pull/9487/commits/7f8f512d79485d436441a8ca4a17cd0551291511

File: src/EnergyPlus/SimAirServingZones.cc [hunk 3]
```diff
@@ -1855,129 +1796,125 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
             // Allocate the subarrays in AirToZoneNodeInfo
-            AirToZoneNodeInfo(AirLoopNum).CoolCtrlZoneNums.allocate(NumZonesCool);
-            AirToZoneNodeInfo(AirLoopNum).HeatCtrlZoneNums.allocate(NumZonesHeat);
-            AirToZoneNodeInfo(AirLoopNum).CoolZoneInletNodes.allocate(NumZonesCool);
-            AirToZoneNodeInfo(AirLoopNum).HeatZoneInletNodes.allocate(NumZonesHeat);
-            AirToZoneNodeInfo(AirLoopNum).TermUnitCoolInletNodes.allocate(NumZonesCool);
-            AirToZoneNodeInfo(AirLoopNum).TermUnitHeatInletNodes.allocate(NumZonesHeat);
-            AirToZoneNodeInfo(AirLoopNum).TermUnitCoolSizingIndex.allocate(NumZonesCool);
-            AirToZoneNodeInfo(AirLoopNum).TermUnitHeatSizingIndex.allocate(NumZonesHeat);
+            thisAirToZoneNodeInfo.CoolCtrlZoneNums.allocate(NumZonesCool);
```
Comment (amirroth) [inline src/EnergyPlus/SimAirServingZones.cc:1810]: This pattern look familiar?

File: src/EnergyPlus/SimAirServingZones.cc [hunk 4]
```diff
@@ -2070,32 +1997,33 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
+        for (int AirLoopNum = 1; AirLoopNum <= numPrimaryAirSys; ++AirLoopNum) {
+            auto &thisPrimaryAirSys = state.dataAirSystemsData->PrimaryAirSystems(AirLoopNum);
             bool FoundCentralHeatCoil = false;
-            for (BranchNum = 1; !FoundCentralHeatCoil && BranchNum <= PrimaryAirSystems(AirLoopNum).NumBranches; ++BranchNum) {
-                for (CompNum = 1; !FoundCentralHeatCoil && CompNum <= PrimaryAirSystems(AirLoopNum).Branch(BranchNum).TotalComponents; ++CompNum) {
-                    CompTypeNum = PrimaryAirSystems(AirLoopNum).Branch(BranchNum).Comp(CompNum).CompType_Num;
+            for (int BranchNum = 1; !FoundCentralHeatCoil && BranchNum <= thisPrimaryAirSys.NumBranches; ++BranchNum) {
+                for (int CompNum = 1; !FoundCentralHeatCoil && CompNum <= thisPrimaryAirSys.Branch(BranchNum).TotalComponents; ++CompNum) {
+                    CompType CompTypeNum = thisPrimaryAirSys.Branch(BranchNum).Comp(CompNum).CompType_Num;
                     if (CompTypeNum == CompType::WaterCoil_SimpleHeat || CompTypeNum == CompType::Coil_ElectricHeat ||
```
Comment (amirroth) [inline src/EnergyPlus/SimAirServingZones.cc]: Oy vey! With this many terms, you are better off using a `switch/case`.

File: src/EnergyPlus/SizingManager.cc [hunk 5]
```diff
@@ -1857,170 +1852,171 @@ void ManageSystemVentilationAdjustments(EnergyPlusData &state)
...
-                                                             TermUnitFinalZoneSizing(termUnitSizingIndex).ZoneName,
+                                                             thisTermUnitFinalZoneSizing.ZoneName,
                                                              state.dataSize->VpzMinClgByZone(termUnitSizingIndex),
                                                              4); // Vpz-min
                     // Vpz-min, simplified procedure?
-                    if (TermUnitFinalZoneSizing(termUnitSizingIndex).VpzMinByZoneSPSized) {
+                    if (thisTermUnitFinalZoneSizing.VpzMinByZoneSPSized) {
                         OutputReportPredefined::PreDefTableEntry(
-                            state, state.dataOutRptPredefined->pdchS62zcdVpzminSPSize, TermUnitFinalZoneSizing(termUnitSizingIndex).ZoneName, "Yes");
+                            state, state.dataOutRptPredefined->pdchS62zcdVpzminSPSize, thisTermUnitFinalZoneSizing.ZoneName, "Yes");
```
Comment (amirroth) [inline src/EnergyPlus/SizingManager.cc:1884]: Was the name `pdchS62zcdVpzminSPSize` created using an automatic password generator?

File: src/EnergyPlus/SimAirServingZones.cc (hunk 3 above)
Comment (mjwitte) [reply src/EnergyPlus/SimAirServingZones.cc:1810]: Pin this - `AirToZoneNodeInfo` is used in many other places.

File: src/EnergyPlus/SizingManager.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/SizingManager.cc:1986]: `state.dataOutRptPredefined->TotalVozMax` is the total in the Outdoor Air Details report. Some of the ASHRAE901... test files that use multipliers are showing diffs here. ~This should probably go in a different PR that fixes some other Outdoor Air Reporting issues.Added this to issue #8528~

Comment (mjwitte) [reply src/EnergyPlus/SizingManager.cc:1986]: No, it can't. This fix has to be part of this PR. Otherwise, the defect file trips on array bounds here. So posted a new issue for that, #9491

File: src/EnergyPlus/DataZoneEquipment.cc [hunk 6]
```diff
@@ -108,7 +108,6 @@ void GetZoneEquipmentData(EnergyPlusData &state)
     // a zone
 
     // Using/Aliasing
-    using BranchNodeConnections::SetUpCompSets;
```
Comment (mjwitte) [inline src/EnergyPlus/DataZoneEquipment.cc:111]: Removed several unused `using`s

File: src/EnergyPlus/SimAirServingZones.cc [hunk 7]
```diff
@@ -1441,107 +1441,50 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
-    using Fans::GetFanIndex;
-    using General::FindNumberInList;
-    using Psychrometrics::PsyHFnTdbW;
-    using Psychrometrics::PsyRhoAirFnPbTdbW;
-    using SplitterComponent::SplitterConditions;
-    // using ZonePlenum::ZoneSupPlenCond;
-    using ZonePlenum::ZoneSupplyPlenumConditions;
-
-    // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
-    int NumAllSupAirPathNodes; // total number of nodes in a supply air path including duplicates
```
Comment (mjwitte) [inline src/EnergyPlus/SimAirServingZones.cc:1454]: Lots of code cleanup including references and local scoping for loop indexes.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 8]
```diff
@@ -1441,107 +1441,50 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
-    auto &AirLoopControlInfo(state.dataAirLoop->AirLoopControlInfo);
-
     // Do the one time initializations
     if (state.dataSimAirServingZones->InitAirLoopsOneTimeFlag) {
 
         // Figure out what zones are served by each primary air system (air loop) and
         // store the results in AirToZoneNodeInfo()%CoolCtrlZoneNums and AirToZoneNodeInfo()%HeatCtrlZoneNums
 
-        // Allocate scratch arrays for storing controlled zone numbers for each air loop.
-        state.dataSimAirServingZones->CtrlZoneNumsCool.allocate(state.dataGlobal->NumOfZones);
```
Comment (mjwitte) [inline src/EnergyPlus/SimAirServingZones.cc:1518]: This was the crux of the problem. These temporary arrays were not sized to allow for more ATUs than zones.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 9]
```diff
@@ -1441,107 +1441,50 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
-        state.dataSimAirServingZones->CtrlZoneNumsHeat.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->ZoneInletNodesCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->ZoneInletNodesHeat.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermInletNodesCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermInletNodesHeat.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermUnitSizingNumsCool.allocate(state.dataGlobal->NumOfZones);
-        state.dataSimAirServingZones->TermUnitSizingNumsHeat.allocate(state.dataGlobal->NumOfZones);
+        // Temporary air loop zone data
+        struct AirloopZone
```
Comment (mjwitte) [inline src/EnergyPlus/SimAirServingZones.cc:1456]: Per @amirroth suggestion, combined 8 arrays into two vectors of this struct.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 10]
```diff
@@ -1441,107 +1441,50 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
+        {
+            int ctrlZoneNum = 0;         // Controlled zone num
+            int zoneInletNode = 0;       // Zone supply inlet node
+            int termUnitInletNode = 0;   // Terminal unit inlet node
+            int termUnitSizingIndex = 0; // Terminal unit sizing index
+        };
+
+        EPVector<AirloopZone> cooledZone;
+        EPVector<AirloopZone> heatedZone;
+        size_t atuArraySize = max(static_cast<size_t>(state.dataGlobal->NumOfZones), state.dataDefineEquipment->AirDistUnit.size());
```
Comment (mjwitte) [inline src/EnergyPlus/SimAirServingZones.cc:1466]: Allocating to the max of number or zones or number of ATUs. Probably safe to go with just the number of ATUs, but not sure about that.
Everything else in this source file is code cleanup, scoping, referencing, etc.

File: src/EnergyPlus/SimAirServingZones.hh [hunk 11]
```diff
@@ -239,17 +239,6 @@ struct SimAirServingZonesData : BaseGlobalStruct
     Real64 Vou = 0.0;            // Uncorrected outdoor air intake for all zones per ASHRAE std 62.1
     Real64 Vot = 0.0;            // Required outdoor air intake at primary AHU per ASHRAE std 62.1
 
-    Array1D_int CtrlZoneNumsCool;
```
Comment (mjwitte) [inline src/EnergyPlus/SimAirServingZones.hh:242]: Removed these temporary arrays from `state` - they are used only in `InitAirLoops`.

File: src/EnergyPlus/SizingManager.cc [hunk 12]
```diff
@@ -1332,30 +1331,32 @@ void ManageSystemVentilationAdjustments(EnergyPlusData &state)
             // each zone
             for (int zoneNum = 1; zoneNum <= AirToZoneNodeInfo(AirLoopNum).NumZonesCooled; ++zoneNum) {
                 int termUnitSizingIndex = AirToZoneNodeInfo(AirLoopNum).TermUnitCoolSizingIndex(zoneNum);
+                auto &thisTermUnitFinalZoneSizing(state.dataSize->TermUnitFinalZoneSizing(termUnitSizingIndex));
```
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:1334]: Reference single element instead of entire array.

File: src/EnergyPlus/SizingManager.cc [hunk 13]
```diff
@@ -1823,30 +1820,28 @@ void ManageSystemVentilationAdjustments(EnergyPlusData &state)
             } else {
                 numZones = AirToZoneNodeInfo(AirLoopNum).NumZonesHeated;
             }
-            for (int zoneNum = 1; zoneNum <= numZones; ++zoneNum) {
+            for (int airLoopZoneNum = 1; airLoopZoneNum <= numZones; ++airLoopZoneNum) {
```
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:1823]: Changed name of loop counter to `airLoopZoneNum`. `ZoneNum` was not the real zone number, but rather the counter for heated or cooled zones on a given airloop. But `ZoneNum` was used below to (incorrectly) access zone multipliers.

File: src/EnergyPlus/SizingManager.cc (hunk 1 above)
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:1986]: Use the correct zone number here for multipliers.

File: tst/EnergyPlus/unit/SimAirServingZones.unit.cc [hunk 14]
```diff
@@ -1566,6 +1566,201 @@ TEST_F(EnergyPlusFixture, InitAirLoops_2AirLoop3ADUb)
     EXPECT_EQ(state->dataZoneEquip->ZoneEquipConfig(2).InletNodeAirLoopNum(2), 2);
 }
 
+TEST_F(EnergyPlusFixture, InitAirLoops_1AirLoop2Zones3ADU)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/SimAirServingZones.unit.cc:1569]: New unit test with more ADU than zones. Fails with develop.

**Review by mjwitte — COMMENTED** [review]
Walking, walking, just keep walking . . .

**Comment by mjwitte** [comment]
@rraustad @Myoldmopar Ready for final review.

**Comment by rraustad** [comment]
I've been reviewing each commit. I'll take another pass but this looks ready to merge.

File: src/EnergyPlus/SimAirServingZones.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/SimAirServingZones.cc:1518]: Noted and agreed.

File: src/EnergyPlus/SimAirServingZones.cc (hunk 9 above)
Comment (rraustad) [reply src/EnergyPlus/SimAirServingZones.cc:1456]: Very nice refactor.

File: src/EnergyPlus/SimAirServingZones.cc (hunk 10 above)
Comment (rraustad) [reply src/EnergyPlus/SimAirServingZones.cc:1466]: You could wind up with an array size larger than number of ATUs (via plenums and unconditioned zones), but that should not be an issue. Bigger picture is correct indexing of these arrays, which seems correct at the moment, just a little confusing. The only test I can think of, not as a requirement here but as a check if the indexing works, is to set up more zones than ATUs and put the non-ATU zone in the middle of the pack. Indexing should skip that zone. I don't see a problem with this as-is.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 15]
```diff
@@ -1441,107 +1441,50 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
             // all nodes (including duplicates)
-            for (CompNum = 1; CompNum <= state.dataZoneEquip->SupplyAirPath(SupAirPath).NumOfComponents; ++CompNum) {
+            for (int CompNum = 1; CompNum <= state.dataZoneEquip->SupplyAirPath(SupAirPath).NumOfComponents; ++CompNum) {
                 if (UtilityRoutines::SameString(state.dataZoneEquip->SupplyAirPath(SupAirPath).ComponentType(CompNum), "AirLoopHVAC:ZoneSplitter")) {
-                    SplitterNum = UtilityRoutines::FindItemInList(state.dataZoneEquip->SupplyAirPath(SupAirPath).ComponentName(CompNum),
-                                                                  state.dataSplitterComponent->SplitterCond,
-                                                                  &SplitterConditions::SplitterName);
+                    int SplitterNum = UtilityRoutines::FindItemInList(state.dataZoneEquip->SupplyAirPath(SupAirPath).ComponentName(CompNum),
+                                                                      state.dataSplitterComponent->SplitterCond,
+                                                                      &SplitterComponent::SplitterConditions::SplitterName);
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:1487]: Noting reference appears necessary.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 16]
```diff
@@ -1565,65 +1508,65 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
                     }
-                    for (SplitterOutNum = 1; SplitterOutNum <= state.dataSplitterComponent->SplitterCond(SplitterNum).NumOutletNodes;
+                    for (int SplitterOutNum = 1; SplitterOutNum <= state.dataSplitterComponent->SplitterCond(SplitterNum).NumOutletNodes;
                          ++SplitterOutNum) {
                         ++SupAirPathNodeNum;
-                        state.dataSimAirServingZones->SupNode(SupAirPathNodeNum) =
-                            state.dataSplitterComponent->SplitterCond(SplitterNum).OutletNode(SplitterOutNum);
-                        state.dataSimAirServingZones->SupNodeType(SupAirPathNodeNum) = DataZoneEquipment::AirNodeType::Invalid;
+                        supNode(SupAirPathNodeNum) = state.dataSplitterComponent->SplitterCond(SplitterNum).OutletNode(SplitterOutNum);
+                        supNodeType(SupAirPathNodeNum) = DataZoneEquipment::AirNodeType::Invalid;
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:1533]: These lines, 1533 and 1546, seem to be just initializing supNodeType (as done before, with Invalid). Would there be a faster way to initialize the supNodeType array to Invalid and delete these 2 lines? Probably not much savings if any.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 17]
```diff
@@ -1638,80 +1581,82 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
 
             // transfer data from the local SupNode array to the SupplyAirPath data structure
-            for (SupNodeIndex = 1; SupNodeIndex <= NumAllSupAirPathNodes; ++SupNodeIndex) {
-                if (state.dataSimAirServingZones->SupNodeType(SupNodeIndex) == DataZoneEquipment::AirNodeType::PathInlet ||
-                    state.dataSimAirServingZones->SupNodeType(SupNodeIndex) == DataZoneEquipment::AirNodeType::Intermediate ||
-                    state.dataSimAirServingZones->SupNodeType(SupNodeIndex) == DataZoneEquipment::AirNodeType::Outlet) {
+            for (int SupNodeIndex = 1; SupNodeIndex <= NumAllSupAirPathNodes; ++SupNodeIndex) {
+                if (supNodeType(SupNodeIndex) == DataZoneEquipment::AirNodeType::PathInlet ||
+                    supNodeType(SupNodeIndex) == DataZoneEquipment::AirNodeType::Intermediate ||
+                    supNodeType(SupNodeIndex) == DataZoneEquipment::AirNodeType::Outlet) {
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:1587]: BITF? (just practicing)

Comment (amirroth) [reply src/EnergyPlus/SimAirServingZones.cc:1587]: :fire: This is the borderline case and I would like to clean up BITF a bit before resuming making this comment, but as I said ... 🔥

File: src/EnergyPlus/SimAirServingZones.cc (hunk 3 above)
Comment (amirroth) [reply src/EnergyPlus/SimAirServingZones.cc:1810]: :fire:

File: src/EnergyPlus/SimAirServingZones.cc [hunk 18]
```diff
@@ -1720,20 +1665,19 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
+                                cooledZone(NumZonesCool).zoneInletNode = state.dataZoneEquip->ZoneEquipConfig(CtrlZoneNum).InletNode(ZoneInNum);
+                                cooledZone(NumZonesCool).termUnitInletNode =
                                     state.dataZoneEquip->ZoneEquipConfig(CtrlZoneNum).AirDistUnitCool(ZoneInNum).InNode;
-                                state.dataSimAirServingZones->TermUnitSizingNumsCool(NumZonesCool) =
+                                cooledZone(NumZonesCool).termUnitSizingIndex =
                                     state.dataZoneEquip->ZoneEquipConfig(CtrlZoneNum).AirDistUnitCool(ZoneInNum).TermUnitSizingIndex;
                                 if (AirLoopNum > 0) {
-                                    if (PrimaryAirSystems(AirLoopNum).OASysExists) {
+                                    if (thisPrimaryAirSys.OASysExists) {
                                         state.dataZoneEquip->ZoneEquipConfig(CtrlZoneNum).ZoneHasAirLoopWithOASys = true;
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:1681]: I don't see any mistakes translating these new arrays.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 19]
```diff
@@ -1855,129 +1796,125 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
                     }
                 ControlledZoneLoop2_exit:;
                 } // End of no supply air path case
+                if ((NumZonesCool + NumZonesHeat) == 0) {
+                    ShowSevereError(state, "An outlet node in AirLoopHVAC=\"" + thisPrimaryAirSys.Name + "\" is not connected to any zone");
+                    ShowContinueError(state,
+                                      "Could not match ZoneEquipGroup Inlet Node=\"" + state.dataLoopNodes->NodeID(ZoneSideNodeNum) +
+                                          "\" to any Supply Air Path or controlled zone");
+                    ErrorsFound = true;
+                }
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:1805]: format

File: src/EnergyPlus/SimAirServingZones.cc [hunk 20]
```diff
@@ -1855,129 +1796,125 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
-                AirToZoneNodeInfo(AirLoopNum).TermUnitHeatInletNodes(ZoneInSysIndex) =
-                    state.dataSimAirServingZones->TermInletNodesHeat(ZoneInSysIndex);
-                AirToZoneNodeInfo(AirLoopNum).TermUnitHeatSizingIndex(ZoneInSysIndex) =
-                    state.dataSimAirServingZones->TermUnitSizingNumsHeat(ZoneInSysIndex);
+            for (int ZoneInSysIndex = 1; ZoneInSysIndex <= NumZonesHeat; ++ZoneInSysIndex) {
+                thisAirToZoneNodeInfo.HeatCtrlZoneNums(ZoneInSysIndex) = heatedZone(ZoneInSysIndex).ctrlZoneNum;
+                thisAirToZoneNodeInfo.HeatZoneInletNodes(ZoneInSysIndex) = heatedZone(ZoneInSysIndex).zoneInletNode;
+                thisAirToZoneNodeInfo.TermUnitHeatInletNodes(ZoneInSysIndex) = heatedZone(ZoneInSysIndex).termUnitInletNode;
+                thisAirToZoneNodeInfo.TermUnitHeatSizingIndex(ZoneInSysIndex) = heatedZone(ZoneInSysIndex).termUnitSizingIndex;
             }
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:1831]: The above both look correct.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 21]
```diff
@@ -2070,98 +1997,127 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
-                for (CompNum = 1; !FoundCentralHeatCoil && CompNum <= PrimaryAirSystems(AirLoopNum).Branch(BranchNum).TotalComponents; ++CompNum) {
-                    CompTypeNum = PrimaryAirSystems(AirLoopNum).Branch(BranchNum).Comp(CompNum).CompType_Num;
-                    if (CompTypeNum == CompType::WaterCoil_SimpleHeat || CompTypeNum == CompType::Coil_ElectricHeat ||
-                        CompTypeNum == CompType::Coil_GasHeat || CompTypeNum == CompType::SteamCoil_AirHeat ||
-                        CompTypeNum == CompType::Coil_DeSuperHeat || CompTypeNum == CompType::DXHeatPumpSystem ||
-                        CompTypeNum == CompType::Furnace_UnitarySys_HeatOnly || CompTypeNum == CompType::Furnace_UnitarySys_HeatCool ||
-                        CompTypeNum == CompType::UnitarySystem_BypassVAVSys || CompTypeNum == CompType::UnitarySystem_MSHeatPump ||
-                        CompTypeNum == CompType::CoilUserDefined) {
+            bool unitaryCoolingCoilExists = false;
+            bool unitaryHeatingCoilExists = false;
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:2025]: I wondered whether these should be declared outside the loop scope where they are used. Since there are 2 loops (lines 2026 - 2093) that use these maybe it is better to declare once and be done.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 22]
```diff
@@ -2070,98 +1997,127 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
+        for (int AirLoopNum = 1; AirLoopNum <= numPrimaryAirSys; ++AirLoopNum) {
+            auto &thisPrimaryAirSys = state.dataAirSystemsData->PrimaryAirSystems(AirLoopNum);
+            auto &thisAirToZoneNodeInfo = state.dataAirLoop->AirToZoneNodeInfo(AirLoopNum);
             state.dataSimAirServingZones->SumZoneDesFlow = 0.0;
-            state.dataAirLoop->AirLoopFlow(AirLoopNum).DesSupply = PrimaryAirSystems(AirLoopNum).DesignVolFlowRate * state.dataEnvrn->StdRhoAir;
-            state.dataAirLoop->AirLoopFlow(AirLoopNum).DesReturnFrac = PrimaryAirSystems(AirLoopNum).DesignReturnFlowFraction;
-            for (ZoneInSysIndex = 1; ZoneInSysIndex <= AirToZoneNodeInfo(AirLoopNum).NumZonesCooled; ++ZoneInSysIndex) {
-                state.dataSimAirServingZones->TUInNode = AirToZoneNodeInfo(AirLoopNum).TermUnitCoolInletNodes(ZoneInSysIndex);
+            state.dataAirLoop->AirLoopFlow(AirLoopNum).DesSupply = thisPrimaryAirSys.DesignVolFlowRate * state.dataEnvrn->StdRhoAir;
+            state.dataAirLoop->AirLoopFlow(AirLoopNum).DesReturnFrac = thisPrimaryAirSys.DesignReturnFlowFraction;
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:2118]: Only 2 AirLoopFlow uses, no need to reference.

File: src/EnergyPlus/SimAirServingZones.cc [hunk 23]
```diff
@@ -2263,10 +2221,11 @@ void InitAirLoops(EnergyPlusData &state, bool const FirstHVACIteration) // TRUE
...
         // set the required flow (from zone equipment) at system outlet nodes
-        for (OutNum = 1; OutNum <= PrimaryAirSystems(AirLoopNum).NumOutletBranches; ++OutNum) {
-            OutBranchNum = PrimaryAirSystems(AirLoopNum).OutletBranchNum[OutNum - 1];
-            NodeNumOut = PrimaryAirSystems(AirLoopNum).Branch(OutBranchNum).NodeNumOut;
-            ZoneSideNodeNum = AirToZoneNodeInfo(AirLoopNum).ZoneEquipSupplyNodeNum(OutNum);
+        for (int OutNum = 1; OutNum <= thisPrimaryAirSys.NumOutletBranches; ++OutNum) {
+            int OutBranchNum = thisPrimaryAirSys.OutletBranchNum[OutNum - 1];
+            int NodeNumOut = thisPrimaryAirSys.Branch(OutBranchNum).NodeNumOut;
+            int ZoneSideNodeNum = thisAirToZoneNodeInfo.ZoneEquipSupplyNodeNum(OutNum);
+            Real64 MassFlowSet = 0.0;
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:2228]: Resetting MassFlowSet = 0 each iteration. Move back to declaration?

File: src/EnergyPlus/SimAirServingZones.hh (hunk 11 above)
Comment (rraustad) [reply src/EnergyPlus/SimAirServingZones.hh:242]: Yup

File: src/EnergyPlus/SizingManager.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/SizingManager.cc:1986]: agreed

File: tst/EnergyPlus/unit/SimAirServingZones.unit.cc [hunk 24]
```diff
@@ -1566,6 +1566,201 @@ TEST_F(EnergyPlusFixture, InitAirLoops_2AirLoop3ADUb)
...
+    EXPECT_TRUE(has_err_output(true));
+    SimAirServingZones::InitAirLoops(*state, true);
+    EXPECT_TRUE(compare_err_stream(""));
+    ASSERT_FALSE(ErrorsFound);
+    // And finally, all of this gymnastics just to check if the airloopnums get set correctly
+    // For this test, both ADUs should be connected airloop 1 which is the only one here
+    EXPECT_EQ(state->dataZoneEquip->ZoneEquipConfig(1).InletNodeAirLoopNum(1), 1);
+    EXPECT_EQ(state->dataZoneEquip->ZoneEquipConfig(2).InletNodeAirLoopNum(1), 1);
+}
+
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SimAirServingZones.unit.cc:1763]: Unit test looks good.

**Comment by rraustad** [comment]
All good @mjwitte. You contemplate whether to make a few small changes while I run the defect file. Otherwise this looks to merge soon.

**Review by rraustad — APPROVED** [review]
All looks good. Will run defect file now.

**Comment by rraustad** [comment]
Defect file: 

Fails in develop just after zone sizing completes with a blank err file.
Runs in this branch to completion.

Interesting warnings for many of the fan coil units that may point to a control issue. There is a handfull of warnings for each FCU, between a few and 20.

    ** Warning ** Part-load ratio heating control failed in fan coil unit MIDDLE EAST FAN COIL
    **   ~~~   **   Bad hot part-load ratio limits
    **   ~~~   ** ..Part-load ratio set to 0 During Warmup, Environment=VICTORIA INTL AP ANN HTG 99.6% CONDNS DB HVAC Sizing Pass 1, at Simulation time=12/21 22:10 - 22:20

**Comment by rraustad** [comment]
Regarding diffs. The ASHRAE901_OfficeLarge_STD2019_Denver example file has 8 AHUs and 23 zones. 1 AHU for each data center (4), 1 for basement, and 1 each for bottom, top and mid floors. The mid floor uses a zone multiplier of 10. The max zones on any AHU is 4. Multipliers for zones 1 - 4 are 1, 1, 10, 1 so each AHU with 4 zones would use these multipliers. Yes, the summation of total outdoor air for these zones would change. For this table report. The diffs show up in this branch only at the bottom of the table for the "Total Facility" row.

     Outdoor Air Details - Entire Facility - Mechanical Ventilation Parameters by Zone

    OutputReportPredefined::PreDefTableEntry(
        state, state.dataOutRptPredefined->pdchOaMvDesZnOa, "Total Facility", state.dataOutRptPredefined->TotalVozMax, 4);


    ! <Zone Information>,Zone Name,North Axis {deg},Origin X-Coordinate {m},Origin Y-Coordinate {m},Origin Z-Coordinate {m},Centroid X-Coordinate {m},Centroid Y-Coordinate {m},Centroid Z-Coordinate {m},Type,Zone Multiplier,Zone List Multiplier,Minimum X {m},Maximum X {m},Minimum Y {m},Maximum Y {m},Minimum Z {m},Maximum Z {m},Ceiling Height {m},Volume {m3},Zone Inside Convection Algorithm {Simple-Detailed-CeilingDiffuser-TrombeWall},Zone Outside Convection Algorithm {Simple-Detailed-Tarp-MoWitt-DOE-2-BLAST}, Floor Area {m2},Exterior Gross Wall Area {m2},Exterior Net Wall Area {m2},Exterior Window Area {m2}, Number of Surfaces, Number of SubSurfaces, Number of Shading SubSurfaces,  Part of Total Building Area
    Zone Information, BASEMENT,0.0,0.00,0.00,0.00,44.59,24.37,-1.22,1,1,1,16.08,73.11,0.00,48.74,-2.44,0.00,2.44,6779.02,TARP,TARP,2779.43,0.00,0.00,0.00,9,0,0,Yes
    Zone Information, CORE_BOTTOM,0.0,0.00,0.00,0.00,37.01,24.37,1.37,1,1,1,5.49,68.53,4.57,44.17,0.00,2.74,2.74,6849.35,TARP,TARP,2496.12,0.00,0.00,0.00,7,0,0,Yes
    Zone Information, CORE_MID,0.0,0.00,0.00,0.00,37.01,24.37,18.14,1,10,1,5.49,68.53,4.57,44.17,16.77,19.51,2.74,6849.35,TARP,TARP,2496.12,0.00,0.00,0.00,6,0,0,Yes
    Zone Information, CORE_TOP,0.0,0.00,0.00,0.00,37.01,24.37,34.91,1,1,1,5.49,68.53,4.57,44.17,33.54,36.28,2.74,6849.35,TARP,TARP,2496.12,0.00,0.00,0.00,6,0,0,Yes
    Zone Information, PERIMETER_BOT_ZN_3,0.0,0.00,0.00,0.00,36.55,46.54,1.37,1,1,1,0.00,73.11,44.17,48.74,0.00,2.74,2.74,860.00,TARP,TARP,313.41,200.61,76.91,115.90,8,9,0,Yes
    Zone Information, PERIMETER_BOT_ZN_2,0.0,0.00,0.00,0.00,70.95,24.37,1.37,1,1,1,68.53,73.11,0.00,48.74,0.00,2.74,2.74,554.22,TARP,TARP,201.98,133.74,52.57,77.26,6,5,0,Yes
    Zone Information, PERIMETER_BOT_ZN_1,0.0,0.00,0.00,0.00,36.55,2.20,1.37,1,1,1,0.00,73.11,0.00,4.57,0.00,2.74,2.74,860.02,TARP,TARP,313.42,200.61,76.91,115.90,8,9,0,Yes
    Zone Information, PERIMETER_BOT_ZN_4,0.0,0.00,0.00,0.00,2.16,24.37,1.37,1,1,1,0.00,4.57,0.00,48.74,0.00,2.74,2.74,554.22,TARP,TARP,201.98,133.74,52.57,77.26,6,5,0,Yes
    Zone Information, PERIMETER_MID_ZN_3,0.0,0.00,0.00,0.00,36.55,46.54,18.14,1,10,1,0.00,73.11,44.17,48.74,16.77,19.51,2.74,860.00,TARP,TARP,313.41,200.61,84.71,115.90,7,1,0,Yes
    Zone Information, PERIMETER_MID_ZN_2,0.0,0.00,0.00,0.00,70.95,24.37,18.14,1,10,1,68.53,73.11,0.00,48.74,16.77,19.51,2.74,554.22,TARP,TARP,201.98,133.74,56.47,77.26,6,1,0,Yes
    Zone Information, PERIMETER_MID_ZN_1,0.0,0.00,0.00,0.00,36.55,2.20,18.14,1,10,1,0.00,73.11,0.00,4.57,16.77,19.51,2.74,860.02,TARP,TARP,313.42,200.61,84.71,115.90,7,1,0,Yes
    Zone Information, PERIMETER_MID_ZN_4,0.0,0.00,0.00,0.00,2.16,24.37,18.14,1,10,1,0.00,4.57,0.00,48.74,16.77,19.51,2.74,554.22,TARP,TARP,201.98,133.74,56.47,77.26,6,1,0,Yes
    Zone Information, PERIMETER_TOP_ZN_3,0.0,0.00,0.00,0.00,36.55,46.54,34.91,1,1,1,0.00,73.11,44.17,48.74,33.54,36.28,2.74,860.00,TARP,TARP,313.41,200.61,84.71,115.90,7,1,0,Yes
    Zone Information, PERIMETER_TOP_ZN_2,0.0,0.00,0.00,0.00,70.95,24.37,34.91,1,1,1,68.53,73.11,0.00,48.74,33.54,36.28,2.74,554.22,TARP,TARP,201.98,133.74,56.47,77.26,6,1,0,Yes
    Zone Information, PERIMETER_TOP_ZN_1,0.0,0.00,0.00,0.00,36.55,2.20,34.91,1,1,1,0.00,73.11,0.00,4.57,33.54,36.28,2.74,860.02,TARP,TARP,313.42,200.61,84.71,115.90,7,1,0,Yes
    Zone Information, PERIMETER_TOP_ZN_4,0.0,0.00,0.00,0.00,2.16,24.37,34.91,1,1,1,0.00,4.57,0.00,48.74,33.54,36.28,2.74,554.22,TARP,TARP,201.98,133.74,56.47,77.26,6,1,0,Yes
    Zone Information, GROUNDFLOOR_PLENUM,0.0,0.00,0.00,0.00,36.55,24.37,3.35,1,1,1,0.00,73.11,0.00,48.74,2.74,3.96,1.22,4344.14,TARP,TARP,3563.11,297.11,297.11,0.00,11,0,0,No
    Zone Information, MIDFLOOR_PLENUM,0.0,0.00,0.00,0.00,36.55,24.37,20.12,1,10,1,0.00,73.11,0.00,48.74,19.51,20.73,1.22,4344.14,TARP,TARP,3563.11,297.11,297.11,0.00,11,0,0,No
    Zone Information, TOPFLOOR_PLENUM,0.0,0.00,0.00,0.00,36.55,24.37,36.89,1,1,1,0.00,73.11,0.00,48.74,36.28,37.50,1.22,4344.14,TARP,TARP,3563.11,297.11,297.11,0.00,11,0,0,No
    Zone Information, DATACENTER_BOT_ZN_6,0.0,5.49,44.17,0.00,5.03,24.37,1.37,1,1,1,4.57,5.49,4.57,44.17,0.00,2.74,2.74,99.34,TARP,TARP,36.20,0.00,0.00,0.00,6,0,0,Yes
    Zone Information, DATACENTER_MID_ZN_6,0.0,4.57,4.57,16.77,5.03,24.37,18.14,1,10,1,4.57,5.49,4.57,44.17,16.77,19.51,2.74,99.34,TARP,TARP,36.20,0.00,0.00,0.00,6,0,0,Yes
    Zone Information, DATACENTER_TOP_ZN_6,0.0,4.57,4.57,33.54,5.03,24.37,34.91,1,1,1,4.57,5.49,4.57,44.17,33.54,36.28,2.74,99.34,TARP,TARP,36.20,0.00,0.00,0.00,6,0,0,Yes
    Zone Information, DATACENTER_BASEMENT_ZN_6,0.0,16.08,0.00,-2.44,8.04,24.37,-1.22,1,1,1,0.00,16.08,0.00,48.74,-2.44,0.00,2.44,1911.37,TARP,TARP,783.68,0.00,0.00,0.00,10,0,0,Yes

image

The summation for Total Facility now adds up correctly.

**Comment by rraustad** [comment]
Code review complete, diffs explained and verified, comments addressed. Thanks @mjwitte for 2-bugs-in-1.
