### PR TITLE
Fixes `Output:JSON` tabular data output incorrectly dependent on `OutputControl:Files input`

### LINKED ISSUE #9393: `Output:JSON` tabular data output incorrectly dependent on `OutputControl:Files` input
Issue overview
--------------
I used the following object in my IDF file:

```
Output:JSON,
  TimeSeriesAndTabular,                   !- Option Type
  No,                                     !- Output JSON
  No,                                     !- Output CBOR
  Yes;                                    !- Output MessagePack
```

However, the resulting MessagePack output file will only include tabular data if, in the `OutputControl:Files` object, the "Output Tabular" field is set to "Yes". If It's set to "No", you do not get tabular data in the MessagePack output file.

Essentially this means that you cannot get tabular data in the MessagePack file without also producing the tabular HTM/CSV output file. This should ideally be allowed so that as many output files as possible can be suppressed when running very large simulation studies.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - EnergyPlus 22.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by shorowit**
Pull request overview
---------------------
 - Fixes #9393
 - Allows tabular data in JSON output files without also needing to create the tabular output file itself. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/EconomicTariff.cc [hunk 1]
```diff
@@ -2711,7 +2711,7 @@ void ComputeTariff(EnergyPlusData &state)
 
     Real64 annualAggregate;
 
-    if (!(state.files.outputControl.tabular || state.files.outputControl.sqlite)) {
+    if (!(state.files.outputControl.tabular || state.files.outputControl.sqlite || state.files.outputControl.json)) {
```
Comment (shorowit) [inline src/EnergyPlus/EconomicTariff.cc]: Just adding to the logic that is used for SQLite output.

**Comment by shorowit** [comment]
To test, add an `Output:JSON` object to any test file, like so:

```
Output:JSON,
  TimeSeriesAndTabular,                   !- Option Type
  Yes;                                    !- Output JSON
```

Note that you now get the same eplusout.json output whether you have:

```
OutputControl:Files,
  ,                                    !- Output CSV
  ,                                    !- Output MTR
  ,                                    !- Output ESO
  ,                                    !- Output EIO
  Yes;                                 !- Output Tabular
```

or

```
OutputControl:Files,
  ,                                    !- Output CSV
  ,                                    !- Output MTR
  ,                                    !- Output ESO
  ,                                    !- Output EIO
  No;                                  !- Output Tabular
```

File: src/EnergyPlus/EconomicTariff.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/EconomicTariff.cc]: Yeah, it seems like this was definitely leaving too early.  But what happens here if you have:

```
Output:JSON,
  TimeSeries,
  ...
```

In your input file.  That will set `outputControl.json` to true, right?  So then what if you have tabular turned off in the `OutputControl:Files` object?  What will happen in this function?  It _looks_ like the .json variable will be true, so this will try to write tabular outputs.  Even though we didn't want it.  

My question boils down to: Is there other protections that will make sure this works in this corner case?  Or do we need to create/check a different outputControl flag (json_tabular) to ensure we are specifically not wanting tabular outputs?

Comment (shorowit) [reply src/EnergyPlus/EconomicTariff.cc]: I have to admit that I didn't really try to understand the existing logic. My assumption was that the SQLite logic worked correctly and that equivalent logic should be applied to JSON output. Am I interpreting your comment correctly that you are essentially questioning the existing logic?

**Comment by JasonGlazer** [comment]
@shorowit I think the lines:
```
if (!(state.files.outputControl.tabular || state.files.outputControl.sqlite || state.files.outputControl.json)) 
```
should probably be something like
```
if (!(state.files.outputControl.tabular || state.files.outputControl.sqlite || (state.files.outputControl.json & state.dataResultsFramework->resultsFramework->timeSeriesAndTabularEnabled()) )) 
```

Honestly, the portion that says just says "state.files.outputControl.sqlite" doesn't seem quite correct to me for the same reason but I haven't tried testing that.

**Comment by Myoldmopar** [comment]
And if we go that way, I would prefer a valid version of something like this:

```c++
bool const htmlTabular = state.files.outputControl.tabular;
bool const jsonTabular = state.files.outputControl.json && state.dataResultsFramework->resultsFramework->timeSeriesAndTabularEnabled();
bool const sqliteTabular = state.files.outputControl.sqlite; // && @JasonGlazer thinks something else maybe?
if (!(htmlTabular || jsonTabular || sqliteTabular)) 
```

**Comment by shorowit** [comment]
@Myoldmopar @JasonGlazer Is [this](https://github.com/NREL/EnergyPlus/pull/10155/commits/51a6a084ca072d16180df3917a16a6df195ff1b5) what you had in mind? It seems weird to me that the code in four different places is setting `state.dataOutRptTab->WriteTabularFiles = false;`, but maybe that's fine. I'm not that familiar with what is going on.

**Comment by JasonGlazer** [comment]
@shorowit that seems like a nice approach keeping the logic in the function. I didn't mean to imply that I know that my suggestion will fix the problem that @Myoldmopar brought up but I think it will. I would recommend either running some test files to make sure it works as expected and then adding some unit tests. Some digging might be needed if the SQL is not working right.

File: src/EnergyPlus/IOFiles.cc [hunk 2]
```diff
@@ -319,6 +319,14 @@ std::vector<std::string> InputOutputFile::getLines()
...
 }
 
+bool IOFiles::OutputControl::writeTabular(EnergyPlusData &state)
+{
+    bool const htmlTabular = state.files.outputControl.tabular;
+    bool const jsonTabular = state.files.outputControl.json && state.dataResultsFramework->resultsFramework->timeSeriesAndTabularEnabled();
+    bool const sqliteTabular = state.files.outputControl.sqlite; // && @JasonGlazer thinks something else maybe?
+    return (htmlTabular || jsonTabular || sqliteTabular);
+}
+
```
Comment (rraustad) [inline src/EnergyPlus/IOFiles.cc:329]: Can someone please explain what the benefit of the above is compared to a one line:

    return (state.files.outputControl.tabular || (state.files.outputControl.json && state.dataResultsFramework->resultsFramework->timeSeriesAndTabularEnabled()) || state.files.outputControl.sqlite);

Comment (Myoldmopar) [reply src/EnergyPlus/IOFiles.cc:329]: To the compiler? Nothing. To the person trying to read that one long line and track the operators and parentheses depth? I think it's tough to read the long line.

**Comment by shorowit** [comment]
I don't have an immediate need for this improvement, and I'm not going to have a chance to further test this and bring it to completion in the near future. So I'm going to change the milestone to the next release. (If someone else wants to bring it to completion sooner, feel free to have at it.)

**Comment by nrel-bot-3** [comment]
@shorowit @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/EconomicTariff.cc [hunk 3]
```diff
@@ -2711,7 +2711,7 @@ void ComputeTariff(EnergyPlusData &state)
 
     Real64 annualAggregate;
 
-    if (!(state.files.outputControl.tabular || state.files.outputControl.sqlite)) {
+    if (!state.files.outputControl.writeTabular(state)) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/EconomicTariff.cc:2714]: Dumb question here...why is the `state.dataOutRptTab->WriteTabularFiles` being set here in a function called `ComputeTariff` inside `EconomicTariff.cc` anyway??  That alone seems _super_ weird.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 4]
```diff
@@ -323,7 +323,7 @@ void GetInputTabularMonthly(EnergyPlusData &state)
     // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
     auto &ort = state.dataOutRptTab;
 
-    if (!(state.files.outputControl.tabular || state.files.outputControl.sqlite)) {
+    if (!state.files.outputControl.writeTabular(state)) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:326]: I think I'd like to take a crack at this where `state.dataOutRptTab->WriteTabularFiles` is set once very early in the simulation and we don't need to keep calling this function.  As soon as we have read inputs, we should be able to assign that flag.  

I like that the function collects all the flags in one place -- that's always welcomed.  The flag checks themselves may need a little extra work as described above, but regardless it's a good step.

File: src/EnergyPlus/EconomicTariff.cc (hunk 3 above)
Comment (JasonGlazer) [reply src/EnergyPlus/EconomicTariff.cc:2714]: It is a good question. And I don't remember, I suppose this might be the first place that a call to something dependent on actually writing tabular reports occurs, although that does not seem likely.

File: src/EnergyPlus/IOFiles.cc (hunk 2 above)
Comment (JasonGlazer) [inline src/EnergyPlus/IOFiles.cc:329]: The only reason I was concerned is the Output:SQLite field "Option Type" has two options Simple, SimpleAndTabular and they don't seem to impact this.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 4 above)
Comment (JasonGlazer) [reply src/EnergyPlus/OutputReportTabular.cc:326]: Sounds good.

**Review by JasonGlazer — APPROVED** [review]
I have not tested it to make sure the files are produced as expected but the logic looks good to me. Thanks @shorowit and @Myoldmopar

**Comment by nrel-bot-2** [comment]
@Myoldmopar @shorowit @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
OK, this has lingered long enough.  It seems good.  I'm going to just pull and test and get this in.  If some further improvements are needed, they can come later.

**Comment by Myoldmopar** [comment]
Everything is running fine, merging this.  Thanks @shorowit and @JasonGlazer.
