### PR TITLE
Fixed Crash in CondFD for Interzone Surfaces for Very Specific Condition

### LINKED ISSUE #8919: EnergyPlus crash when having unused constructions and conduction finite difference algorithms
Issue overview
--------------
It was reported that while running an up-converted v9.5 idf, the program that uses conduction finite difference algorithms would crash. However, the original v9.1 file the program runs fine. 

An investigation reveals that the root cause for the crash is the "unused" construction surfaces in IDF files. EnergyPlus would not proceed to get a non-zero time finite difference time step when it encounters an "unused" construction--an "unused" construction means that the construction is defined but has never been referenced anyplace else in the idf. The zero finite difference time step will cause a divide-by-zero error in a function that will be called later, thus causing the program to crash. 

The associated code blocks for the problems are here: 
https://github.com/NREL/EnergyPlus/blob/2955d1ccfa97d6040981848d839116871f690986/src/EnergyPlus/HeatBalFiniteDiffManager.cc#L599
Here it will skip some blocks if the construction is "unused"; as a result of the skipping, the time step will not get updated and will still keep the zero initialization here: 
https://github.com/NREL/EnergyPlus/blob/2955d1ccfa97d6040981848d839116871f690986/src/EnergyPlus/HeatBalFiniteDiffManager.cc#L765

Then it will finally cause the div-by-zero error here and the program will crash: 
https://github.com/NREL/EnergyPlus/blob/2955d1ccfa97d6040981848d839116871f690986/src/EnergyPlus/HeatBalFiniteDiffManager.cc#L1083

This should be considered as a code bug as such "unused" constructions, although redundant, should still be tolerated and should not be even be treated as errors (some non-severe warning might be adequate). However, definitely it should not have caused a program crash. 

Some code changes are needed to fix the bug. However, for such an IDF file to run correctly, a temporary workaround is to check the construction definitions and remove all "unused" constructions. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): Recent versions such as v9.5 and v9.6 pre-release have the problem; some earlier versions such as v9.1 do not have such a problem.
 - Helpdesk ticket number: 15755

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #8919 
 -  Under a particular condition (CondFD used, interzone surface that has another zone as the outside boundary condition causing E+ to create it internally, and the user supplying the reversed construction but it isn't used by any user defined surface), a variable was not being set (IsUsed) for the reversed construction causing a crash (array index of zero).  This is now fixed and this particular case trapped by the new unit test.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DataHeatBalance.cc [hunk 1]
```diff
@@ -906,6 +906,7 @@ int AssignReverseConstructionNumber(EnergyPlusData &state,
         }
         if (Found) {
             NewConstrNum = Loop;
+            state.dataConstruction->Construct(Loop).IsUsed = true;
```
Comment (Myoldmopar) [inline src/EnergyPlus/DataHeatBalance.cc:909]: Seems quite reasonable.

File: tst/EnergyPlus/unit/DataHeatBalance.unit.cc [hunk 2]
```diff
@@ -985,3 +985,50 @@ TEST_F(EnergyPlusFixture, DataHeatBalance_setNodeSourceAndUserTemp)
...
+    //       to have the reversed construction.  If that reversed construction is
+    //       not used for any defined surface, the variable IsUsed is false.  However,
+    //       since it now is being used, IsUsed has to be set to true.  Prior to
+    //       work on Defect #8919, when using CondFD and a zone other side condition
+    //       for an interzone surface (implied or E+ internally created other side)
+    //       for a construction that was reversed in the input file but not used
+    //       for other defined surfaces, IsUsed was set to false and this construction
+    //       was then skipped in the CondFD routine that calculates the number of
+    //       nodes.  This led to a hard crash.  This test simply makes sure that
+    //       IsUsed is set to true when the reversed construction already exists.
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/DataHeatBalance.unit.cc:1014]: This helps me understand not only the fix you made, but also the intent of the unit test.  This is good stuff.  Thanks @RKStrand

File: tst/EnergyPlus/unit/DataHeatBalance.unit.cc [hunk 3]
```diff
@@ -985,3 +985,50 @@ TEST_F(EnergyPlusFixture, DataHeatBalance_setNodeSourceAndUserTemp)
     EXPECT_EQ(expectedNodeNumberAtSource, thisConstruct.NodeSource);
     EXPECT_EQ(expectedNodeNumberAtUserSpecifiedLocation, thisConstruct.NodeUserTemp);
 }
+
+TEST_F(EnergyPlusFixture, DataHeatBalance_AssignReverseConstructionNumberTest)
+{
+    int ConstrNum;
+    int expectedResultRevConstrNum;
+    int functionResultRevConstrNum;
+    bool ErrorsFound = false;
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/DataHeatBalance.unit.cc:994]: Don't forget, in C++, you don't have to declare the variables up here at the top of the function, just declare them at the point you use them.  :+1:

**Review by Myoldmopar — APPROVED** [review]
All good here.  I'll test this out and get it in the merge queue.

**Comment by Myoldmopar** [comment]
The defect file was apparently sent by email and not attached to the issue or this PR or put in DevSupport, so I cannot verify the fix, but I'm trusting that it has been fixed and will use the new unit test as verification for now.  Building and running...

**Comment by Myoldmopar** [comment]
All passing here.  Thanks @RKStrand
