### PR TITLE
Correct error in collection of AirflowNetwork element data

### LINKED ISSUE #9888: Intermittent hard crash with two specified volume flow objects
Issue overview
--------------
EnergyPlus intermittently hard crashes when two specified flow rate objects are included in the model.

### Details
Some additional details for this issue:
 - Windows 10
 - EnergyPlus v22.1.0
 - [Unmethours link](https://unmethours.com/question/88545/when-two-airflownetworkmultizonespecifiedflowrate-objeects-are-specified-energyplus-clashes/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added: [AirflowNetwork_MultiZone_SmallOffice_with_two_specifiedFlowRate.idf.txt](https://github.com/NREL/EnergyPlus/files/10984080/AirflowNetwork_MultiZone_SmallOffice_with_two_specifiedFlowRate.idf.txt)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jasondegraw**
Pull request overview
---------------------
 - Fixes #9888
 - Corrects an error in input processing of AirflowNetwork specified flow rate objects, the order of operations was wrong and the result was/is intermittent failures.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 1]
```diff
@@ -1172,16 +1172,20 @@ namespace AirflowNetwork {
...
-                    elements[thisObjectName] = &SpecifiedVolumeFlowData[i_vol]; // Yet another workaround
                     ++i_vol;
                 }
             }
+            for (auto &afe : SpecifiedMassFlowData) {
+                elements[afe.name] = &afe; // Yet another workaround
+            }
+            for (auto &afe : SpecifiedVolumeFlowData) {
+                elements[afe.name] = &afe; // Yet another workaround
+            }
```
Comment (jasondegraw) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:1188]: Unfortunately I was taking the address before I was done filling out the arrays, and that's bad. This changes the order that things are done in so that the address taking happens after all the vectors are filled in.

Comment (Myoldmopar) [reply src/EnergyPlus/AirflowNetwork/src/Solver.cpp:1188]: Makes perfect sense.  I tried running the defect file but even in develop it succeeded.  It was a release build so I assume it was just passing through with weird data.  Anyway, this fix is super clear and I'm going to get it in.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
I will give Decent a chance to run it once or twice and then merge it in.  Thanks @jasondegraw

**Comment by Myoldmopar** [comment]
All green, merging.  Thanks @jasondegraw
