### PR TITLE
Fix #9798 -  Conversion from std::string to heap-allocated char pointer is missing a +1

### LINKED ISSUE #9798: Conversion from std::string to heap-allocated char pointer is missing a +1
Issue overview
--------------

https://github.com/NREL/EnergyPlus/blob/98f434ed153c8162441d47566bf2e98d293343bd/src/EnergyPlus/api/datatransfer.cc#L116-L121

https://en.cppreference.com/w/cpp/string/byte/strlen

> Returns the length of the given byte string, that is, the number of characters in a character array whose first element is pointed to by str up to and not including the first null character

https://en.cppreference.com/w/cpp/string/byte/strcpy

> Copies the character string pointed to by src, including the null terminator, to the character array whose first element is pointed to by dest.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA): develop, Circa 22.2.0, 98f434ed153c8162441d47566bf2e98d293343bd
 - Unmethours link or helpdesk ticket number: https://unmethours.com/question/86636/client-programs-may-crash-by-calling-listallapidatacsv-of-energyplus-api/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9798

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/api/datatransfer.cc [hunk 1]
```diff
@@ -116,7 +116,8 @@ char *listAllAPIDataCSV(EnergyPlusState state)
     // note that we cannot just return a c_str to the local string, as the string will be destructed upon leaving
     // this function, and undefined behavior will occur.
     // instead make a deep copy, and the user must manage the new char * pointer
-    char *p = new char[std::strlen(output.c_str())];
+    // strcpy copies including the null-terminator, strlen doesn't include it
+    char *p = new char[std::strlen(output.c_str()) + 1];
```
Comment (jmarrec) [inline src/EnergyPlus/api/datatransfer.cc:120]: Here you go

Comment (Myoldmopar) [reply src/EnergyPlus/api/datatransfer.cc:120]: @jmarrec is this just draft because you haven't got a test for it yet?  Or is there additional work to do?  Thanks!

Comment (jmarrec) [reply src/EnergyPlus/api/datatransfer.cc:120]: I was just quick fixing (a unit test for this would be way overkilled), and I think my default github settings lately are open as draft, I didn't realize this was marked as draft.

Comment (Myoldmopar) [reply src/EnergyPlus/api/datatransfer.cc:120]: OK, that's fine.  This is a great obvious quick fix.  Thanks for it.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
All happy on CI and an obvious, exceedingly tiny fix.  Thanks @jmarrec, merging.
