### PR TITLE
Fix 9301 DX Coil incorrect curve that could result severe errors

### LINKED ISSUE #9301: Code Error in DXCoils.cc
Issue overview
--------------

In the source code DXCoils.cc, in module named "CalcTwoSpeedDXCoilStandardRating", there is one line of code as follow (Line [15282](https://github.com/NREL/EnergyPlus/blob/747398a414f97f8867b8b79c8a567e4a028df695/src/EnergyPlus/DXCoils.cc#L15282))

```c++
TotCapFlowModFac = CurveValue(state, state.dataDXCoils->DXCoil(DXCoilNum).CCapFTemp2, AirMassFlowRatio);
```

Looks like this line of code is to calculate the Capacity Ratio as a function of Flow Fraction, but it's referencing the Capacity Ratio as Function of Temperature curve.  This caused an error "Target and Gridded Data do not have the same dimensions" when I was running a simulation using lookup tables for the cooling coil performance. I think it is because the CAPFT requires two independent variables, whereas in this function call only one independent variable is provided.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9301))
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9301, which reports that in the standard rating calculation for Coil:Cooling:DX:TwoSpeed, an incorrect curved is used  for the function of capacity vs. air flow fraction.
 - Incorrect Capacity(Temperatures) curve was used for Capacity(FlowFrac) function evaluation in the original branch, which could result a severe/fatal error due to curve type incompatibility; the current branch fix this issue---by removing the problematic line of code, which is found to be redundant after some investigation;
 - In addition, a few curve check blocks are now added to warn and reset negative curve values.
 - There is another place in the code that a redundant function call could (and should) be removed.

- Diffs explanations: There are about 20 test files showing some difference. This could be explained. The original code used an incorrect curve to evaluate the Capacity over flow fraction function (which is a univariate function) for the low speed condition; while in the current PR this was corrected. Further, the curve that was missed used was a Capacity over temperatures function, which is a bivariate function. Therefore, the scenario in the original code is that a bivariate function (which are expecting two temperature input variables) is evaluated with only one single (flow fraction) input---this is obviously problematic---however, the code let is pass without any warning, because the second needed input variable is treated as "zeroes" (found via examining the curve evaluation function code lines). Therefore the result would be expected to be incorrect, but never got noticed by the user. In summary, the current code allowed a regular bivariate function to be evaluated with only one input variable, by automatically filling the other required input variable as zeros; but obviously yields incorrect results---and the worse, without giving any warnings about it.
-  The reason that the original issue #9301 reported an error message is that the curve is not a regular analytical function (with coefficients inputs), but rather a look-up table that strictly needs two independent variable inputs to look up in two independent variable functions. Now with the table-lookup function, the two independent variables are strictly required, and the code would complain with a fatal error is one is missing. This being said, the bug would have been buried there for much a longer time, if without the kind of test trials done in #9301.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -15329,11 +15383,40 @@ void CalcTwoSpeedDXCoilStandardRating(EnergyPlusData &state, int const DXCoilNum
                 EIR = 0.0;
             }
 
-            TotCapFlowModFac = CurveValue(state, state.dataDXCoils->DXCoil(DXCoilNum).CCapFTemp2, AirMassFlowRatio);
+            // TotCapFlowModFac = CurveValue(state, state.dataDXCoils->DXCoil(DXCoilNum).CCapFFlow(1), AirMassFlowRatio);
             TotCapTempModFac = CurveValue(state,
```
Comment (jcyuan2020) [inline src/EnergyPlus/DXCoils.cc:15387]: This is the major fix part for this problem---the final solution is actually to just remove this line of code, as it was already done once a couple of lines above and the value has not been changed since.

What's showing also showing here in the commented line (15386) is the first  trial to fix by just correct the curve name. However, it is later confirmed that this entire line of code could be complete removed as it is redundant.

File: src/EnergyPlus/DXCoils.cc [hunk 2]
```diff
@@ -15329,11 +15383,40 @@ void CalcTwoSpeedDXCoilStandardRating(EnergyPlusData &state, int const DXCoilNum
...
                                           state.dataDXCoils->DXCoil(DXCoilNum).CCapFTemp2,
                                           CoolingCoilInletAirWetBulbTempRated,
                                           OutdoorUnitInletAirDryBulbTempPLTestPoint(PartLoadTestPoint));
+            //    Warn user if curve output goes negative
+            if (TotCapTempModFac < 0.0) {
+                if (state.dataDXCoils->DXCoil(DXCoilNum).CCapFTempErrorIndex == 0) {
+                    ShowWarningMessage(
```
Comment (jcyuan2020) [inline src/EnergyPlus/DXCoils.cc:15394]: This and a flow other code blocks add the curve value bound check, so that a negative curve value could be intercepted with warning messages and the values reset to some proper values (mostly zeroes).

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 3]
```diff
@@ -4489,4 +4490,246 @@ TEST_F(EnergyPlusFixture, TwoSpeedDXCoilStandardRatingsTest)
     EXPECT_EQ("10.15", RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchDXCoolCoilIEERIP, coolcoilTwoSpeed.Name));
 }
 
+TEST_F(EnergyPlusFixture, TwoSpeedDXCoilStandardRatings_Curve_Fix_Test)
+{
+    // Test the PR 9694 that fixes Issue 9301; will report severe error if tested in original develop branch
+    std::string const idf_objects = delimited_string({
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/DXCoils.unit.cc:4496]: unit test.

File: src/EnergyPlus/DXCoils.cc [hunk 4]
```diff
@@ -15223,7 +15223,7 @@ void CalcTwoSpeedDXCoilStandardRating(EnergyPlusData &state, int const DXCoilNum
                 Real64 TotCapTempModFac = CurveManager::CurveValue(state, coil.CCapFTemp(1), wbRated, par3);
                 Real64 HighSpeedNetCoolingCap = coil.RatedTotCap(1) * TotCapTempModFac * TotCapFlowModFac - FanHeatCorrection;
 
-                TotCapFlowModFac = CurveManager::CurveValue(state, coil.CCapFFlow(1), AirMassFlowRatio);
+                // TotCapFlowModFac = CurveManager::CurveValue(state, coil.CCapFFlow(1), AirMassFlowRatio);
                 TotCapTempModFac = CurveManager::CurveValue(state, coil.CCapFTemp2, wbRated, par3);
```
Comment (jcyuan2020) [inline src/EnergyPlus/DXCoils.cc:15227]: This is another place where the line of code is redundant. This function call is not needed, as it was already evaluated four lines above (at Line 15222), and the value has not been changed since.

**Review by jcyuan2020 — COMMENTED** [review]
A quick walk-through.

File: src/EnergyPlus/DXCoils.cc (hunk 4 above)
Comment (mjwitte) [reply src/EnergyPlus/DXCoils.cc:15227]: @jcyuan2020 Do you understand why a local scope `TotCapFlowModFac` is defined in this block instead of using the function-level reference from line 14951? I'm surprised the compiler doesn't complain about a redefinition.

In general, I don't understand most of those references here in this function since the values all appear to be used locally for the standard rating calculation.

Also, if I'm following correctly, this fix only impacts the standard rating results. That should be made clear in the top comments of the PR.

Comment (mjwitte) [reply src/EnergyPlus/DXCoils.cc:15227]: > In general, I don't understand most of those references here in this function since the values all appear to be used locally for the standard rating calculation.

Ignore that question. I see there's a call to `CalcMultiSpeedDXCoil` which may need these referenced values.

Comment (jcyuan2020) [reply src/EnergyPlus/DXCoils.cc:15227]: @mjwitte For the scope question: I think it is valid to have the same name for the two variables of different scopes (although might not be a good practice in general). The more "local" one will take precedence in this case---the "local" scope will end at Line 15244 and before that, the more "local" will used by the compiler. So theoretically there should be no ambiguity to the compiler here.

So here if this should changed to the functional really depends on the author's original intent---it seems reasonable if the author's original intent is to keep this part local according to what happened before Line 15244. It is validly used locally and then destroyed automatically at the end of Line 15244. The wider-scoped functional one will not be affected.

For clarity purpose, the "local" ones could be renamed. But even without renaming the code and logic are still valid, though.

**Comment by mjwitte** [comment]
@jcyuan2020 Is this ready for final review? It is still marked "draft".

**Comment by nrel-bot-3** [comment]
@jcyuan2020 @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/DXCoils.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DXCoils.cc:15394]: OK that's fine.

File: src/EnergyPlus/DXCoils.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DXCoils.cc:15387]: Interesting fix.  I wasn't expecting the major fix to be removing lines of code, but I basically see what was going on here.

File: tst/EnergyPlus/unit/DXCoils.unit.cc (hunk 3 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/DXCoils.unit.cc:4496]: Would have been nice if you could produce the necessary unit test behavior with a smaller chunk of inputs, but in the grand scheme this isn't so bad.  And it works, so that's most important.

**Review by Myoldmopar — APPROVED** [review]
This seems reasonable to me.

**Comment by Myoldmopar** [comment]
Ran the defect with develop to demonstrate the failure :heavy_check_mark:  Built this branch with latest develop and verified the fix :heavy_check_mark:   Unit test suite passes with this branch :heavy_check_mark:   Regressions locally today look the same as before, and explained and reasonable :heavy_check_mark:   Merging this, thanks @jcyuan2020 and @mjwitte
