### PR TITLE
Fix VRF crankcase heater calculations for multiple compressors

### LINKED ISSUE #11020: VRF Crankcase heater operation is inconsistent with temperature limits
### Issue overview

From user (helpdesk ticket 16848):

> It seems that VRF Crankcase heaters only run if there indoor compressors are working. Is that an expected behaviour?
> 
> I have also taken a look at the source code and it seems that the calculation for energy form crankcase heater is skipped if there are no calculations for the indoor unit.
> 
> In the results attched, looking at the first hours of day 6:
> - The temperature is below the "maximum outdoor dry buld temperature for crankcase heater" (5ºC)
> - There is no VRF Heat Pump Heating Electricity Rate (VRF not operational)
> - Crankcase is not running, even though both conditions above should enable it.
> 
> What are the conditions that control the VRF crankcase heater in this case?
> I have also attached a simplified model in case you need a more detailed look.

Preliminary investigation by @yujiex:

According to the documentation, it seems the crankcase heater should be on when the following both of the two conditions are met
condition 1: outdoor temperature <= 5
condition 2: heat pump outdoor heating electricity rate == 0 (OU compressor is not running)

I see both cases where 
- (condition 1 AND condition 2) but crankcase heater is not running
- NOT (condition 1 AND condition 2) but crankcase heater is running

Image

### Operating System (Multiple choices)

Any

### Operating System Version

any

### Version of EnergyPlus

24.2

### Unmethours link or helpdesk ticket number

Helpdesk ticket 16848

### Defect file

EnergyPlusDevSupport\DefectFiles run with GBR_London.Gatwick.037760_IWEC.epw

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------

- Fixes #11020

### Description of the purpose of this PR

VRF Crankcase heater operation not as expected. Reported by help desk as issue 11020 and recently this unmet hours post.

https://unmethours.com/question/103176/vrf-crankcase-heater-operation/

Used example file VariableRefrigerantFlow_5Zone as defect file with Chicago weather.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 1]
```diff
@@ -1250,15 +1250,28 @@ void CalcVRFCondenser(EnergyPlusData &state, int const VRFCond)
 
     // calculate crankcase heater power
     if (vrf.MaxOATCCHeater > OutdoorDryBulb) {
-        // calculate crankcase heater power
-        vrf.CrankCaseHeaterPower = vrf.CCHeaterPower * (1.0 - VRFRTF);
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:1246]: These calculations start by adding in a baseline crankcase heater power. Then added in other values based on number of compressors. I could not follow what was intended so just came up with a different approach. Feel free to simplify code if a better method is conceived.

**Comment by rraustad** [comment]
VariableRefrigerantFlow_5Zone.idf:

    AirConditioner:VariableRefrigerantFlow,
      15,                      !- Crankcase Heater Power per Compressor {W}
      3,                       !- Number of Compressors {dimensionless}
      0.33,                    !- Ratio of Compressor Size to Total Compressor Capacity {W/W}

Showing before changes in develop branch and then what looks like the correct answer from this branch.

image

This branch:

image

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 2]
```diff
@@ -463,19 +464,21 @@ void CalcVRFCondenser(EnergyPlusData &state, int const VRFCond)
...
         CondAirMassFlow = RhoAir * vrf.EvapCondAirVolFlowRate;
         // (Outdoor wet-bulb temp from DataEnvironment) + (1.0-EvapCondEffectiveness) * (drybulb - wetbulb)
         CondInletTemp = OutdoorWetBulb + (OutdoorDryBulb - OutdoorWetBulb) * (1.0 - vrf.EvapCondEffectiveness);
         CondInletHumRat = PsyWFnTdbTwbPb(state, CondInletTemp, OutdoorWetBulb, OutdoorPressure);
+        OATForCCHeater = OutdoorDryBulb;
     } else if (vrf.CondenserType == DataHeatBalance::RefrigCondenserType::Water) {
         CondInletTemp = OutdoorDryBulb; // node inlet temp from above
         OutdoorWetBulb = CondInletTemp; // for watercooled
         CondWaterMassFlow = vrf.WaterCondenserDesignMassFlow;
+        OATForCCHeater = state.dataEnvrn->OutDryBulbTemp;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:476]: While creating the unit test I realized that for water-cooled VRF the condenser water inlet node was controlling the crankcase heater. So I added a variable specific to the VRF condenser type to control the crankcase heater.

File: tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc [hunk 3]
```diff
@@ -5058,7 +5065,7 @@ TEST_F(EnergyPlusFixture, VRFTest_SysCurve_WaterCooled)
         "  ,                        !- Piping Correction Factor for Height in Heating Mode Coefficient {1/m}",
         "  15,                      !- Crankcase Heater Power per Compressor {W}",
         "  3,                       !- Number of Compressors {dimensionless}",
-        "  0.33,                    !- Ratio of Compressor Size to Total Compressor Capacity {W/W}",
+        "  0.13,                    !- Ratio of Compressor Size to Total Compressor Capacity {W/W}",
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc:5066]: This input for Ratio of compressor size to total does have an effect on crankcase heater power. For this reason I had to use a more detailed calculation as my attempt at simplification did not take this input into account.

**Review by mitchute — APPROVED** [review]

**Comment by mitchute** [comment]
Thanks @rraustad. Merging.
