### PR TITLE
Fix the default parameter type for the exhaust control function

### LINKED ISSUE #9904: CalcZoneHVACExhaustControl is boolifying a Real64
Issue overview
--------------
The function `CalcZoneHVACExhaustControl` has this [signature](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ExhaustAirSystemManager.cc#L696):
```
void CalcZoneHVACExhaustControl(EnergyPlusData &state, int const ZoneHVACExhaustControlNum, ObjexxFCL::Optional<bool const> FlowRatio)
```
but the only place the optional argument is used is [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ExhaustAirSystemManager.cc#L444):
```
CalcZoneHVACExhaustControl(state, exhLegIndex, flowRatio);
```

and `flowRatio` is a `Real64`. That's probably not what is intended. Since we're in the process of removing `Optional` this should probably be replaced with something like `Real64 FlowRatio = 0.0` in the signature and have the internal logic updated accordingly. 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

@mjwitte @jcyuan2020

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9904 
 - Changes the optional `bool` type parameter `FlowRatio` to `Real64` type, and uses the default C++ way to do this.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 16 days since this pull request was last updated.

File: src/EnergyPlus/ExhaustAirSystemManager.cc [hunk 1]
```diff
@@ -695,7 +695,7 @@ namespace ExhaustAirSystemManager {
         Real64 Tin = state.dataZoneTempPredictorCorrector->zoneHeatBalance(thisExhCtrl.ZoneNum).ZT;
         Real64 thisExhCtrlAvailScheVal = ScheduleManager::GetCurrentScheduleValue(state, thisExhCtrl.AvailScheduleNum);
 
-        if (present(FlowRatio)) {
+        if (FlowRatio != 0.0) {
```
Comment (mjwitte) [inline src/EnergyPlus/ExhaustAirSystemManager.cc]: Is it possible that the calling routine would request a `FlowRatio` of zero? If so, this will behave differently than the optional. Would 1.0 be a better default?

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 10 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 9 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 18 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@jcyuan2020 it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@jcyuan2020 it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@jcyuan2020 it has been 10 days since this pull request was last updated.

File: src/EnergyPlus/ExhaustAirSystemManager.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/ExhaustAirSystemManager.cc]: > Is it possible that the calling routine would request a `FlowRatio` of zero? If so, this will behave differently than the optional. Would 1.0 be a better default?

@jcyuan2020 Asking again.

Comment (jcyuan2020) [reply src/EnergyPlus/ExhaustAirSystemManager.cc]: I think this line should still be kept as 0.0 (or remove this line, no `if` condition at all?)

Do you mean that for the declaration, the parameter should give a `FlowRatio = 1.0` for default? Something like this? :
```
void CalcZoneHVACExhaustControl(EnergyPlusData &state, int const ZoneHVACExhaustControlNum, Real64 const FlowRatio = 1.0)
```

Comment (mjwitte) [reply src/EnergyPlus/ExhaustAirSystemManager.cc]: Yes, that's what I was suggesting.

Comment (mjwitte) [reply src/EnergyPlus/ExhaustAirSystemManager.cc]: > I think this line should still be kept as 0.0 (or remove this line, no `if` condition at all?)
> 
> Do you mean that for the declaration, the parameter should give a `FlowRatio = 1.0` for default? Something like this? :
> 
> ```
> void CalcZoneHVACExhaustControl(EnergyPlusData &state, int const ZoneHVACExhaustControlNum, Real64 const FlowRatio = 1.0)
> ```

But looking at this again, this line should test for 1.0, not zero.
Previously, if  `FlowRatio` was passed in, then the flows would be ratioed, otherwise it would execute the `else`.
Now, if `FlowRatio` is passed in as 1.0 it will execute the `else` which is incorrect.
Also, if `FlowRatio` is passed in as 0.0 (which if I remember correctly could happen is the central exhaust fan is shut down?), then the `else` is also executed and the flow won't be set to zero.

Comment (jcyuan2020) [reply src/EnergyPlus/ExhaustAirSystemManager.cc]: @mjwitte Thanks! It looks that here our goal is to find a mechanism that could flag if the parameter `FlowRatio` is not given during the function call. It then looks that here it should pass in the default of `FlowRatio = -1.0` (or any negative number) and then test for `FlowRatio >= 0` to replace the original line of `if (present(FlowRatio)` (or the current `FlowRatio != 0.0`). (?)

File: src/EnergyPlus/ExhaustAirSystemManager.cc [hunk 2]
```diff
@@ -695,7 +695,7 @@ namespace ExhaustAirSystemManager {
         Real64 Tin = state.dataZoneTempPredictorCorrector->zoneHeatBalance(thisExhCtrl.ZoneNum).ZT;
         Real64 thisExhCtrlAvailScheVal = ScheduleManager::GetCurrentScheduleValue(state, thisExhCtrl.AvailScheduleNum);
 
-        if (FlowRatio != 0.0) {
+        if (FlowRatio >= 0.0) {
```
Comment (mjwitte) [inline src/EnergyPlus/ExhaustAirSystemManager.cc:698]: This will fail to zero out the flows if this is called with FlowRatio = 0.0 (which I think is a valid possible case).

Comment (mjwitte) [reply src/EnergyPlus/ExhaustAirSystemManager.cc:698]: Oh, whoops >= - sorry this will work.

**Comment by Myoldmopar** [comment]
I know there's been a lot of activity here, feel free to mark this ready for review whenever you are done.

**Review by mjwitte — APPROVED** [review]
@jcyuan2020 This looks good. No substantive diffs,
I've merged in develop for one last round.
@Myoldmopar this is ready to merge. Any further review?
