### PR TITLE
Fix zone exhaust air flow balance when system OA is limited, also fix chilled beam airflow

### LINKED ISSUE #6492: Unexpected interaction between Fan:ZoneExhaust and Controller:OutdoorAir
Found in v8.8 (made with OpenStudio v2.4.0)

I'm not entirely certain this is a bug, if not it's just really unexpected and confusing behavior.

I have a VAV with Reheat air loop serving multiple zones, where one zone also has a Fan:ZoneExhaust which is Decoupled from the System Availability Manager. I’ve set the Air Loop to follow an operation schedule, but cycle on at night to meet any heating/cooling loads. Everything is autosized, and the terminals set to control for outside air. I also want to shut down outside air at night, so I’ve set a schedule (same as the loop operation schedule) to the Controller:Outdoor Air ‘Maximum Fraction of Outside Air Schedule Name’.

Here’s the problem: If the Fan:ZoneExhaust attached to one of the zones does NOT have a ‘Flow Fraction Schedule Name’ schedule set, the entire air system will shut off during the outdoor air shutoff hours, even if the attached systems are showing a heating load:

image

If I DO set the exhaust fan ‘‘Flow Fraction Schedule Name’ to a schedule, which matches the system operation schedule, I get the correct air system operation: outdoor air off at night, but system cycles to meet heating loads:

image

Extra: if the exhaust fan operation schedule is different from the system operation/outdoor air schedule, say turns on at 4AM instead of 8, I get an air system which shuts down from 4AM to 8AM (the exhaust fan ON before system ON hours), then works normally the rest of the day:

image

@mjwitte I think this might have to do with the changes in https://github.com/NREL/EnergyPlus/pull/5794 (since the interaction seems to disappear when I don't define a schedule in Maximum Fraction of Outdoor Air Schedule of the Controller:OutdoorAir), but that's just a guess.

I can provide an example file if necessary.

### LINKED ISSUE #6574: Problems with Airloop operation with Zone Exhaust Fan and Cooled Beam
Issue overview
--------------
The AirloopHVAC will not operate when a ZoneHVAC:ExhaustFan is added.  There seems to be serious problems with zone return air node flow calculations when a zone exhaust fan is added to a zone served by AirTerminal:SingleDuct:ConstantVolume:CooledBeam.  The central fan does not operate and the air system provides no ventilation air to any of zones.  

Defect file adds one zone exhaust fan to example file 5ZoneCooledBeam.idf.  Problem is that after adding the zone exhaust the airloop central fan does not operate. 

After much debugging, the problem appears to be with MassFlowRateZSup term here https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneEquipmentManager.cc#L4487

Unclear why zero return air flow is propagating past the OA system and shutting down the air handler.   

### Workaround ###
Make the zone exhaust fan "balanced".

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (\EnergyPlusDevSupport\DefectFiles\6000s\6574\6574_5ZoneCoolBeam.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Fixes #6492 - Unexpected interaction between Fan:ZoneExhaust and Controller:OutdoorAir
Fixes #6574 - Problems with Airloop operation with Zone Exhaust Fan and Cooled Beam
This pull request replaces #6575.

### Summary of Issues Fixed
The main problem in both of these issues is that the airloop flow resolution assumed that the Maximum Outdoor Air Flow Rate would always be available as makeup air to replace air removed by exhaust fans. This generally works as long as the outdoor air controller is allowed to increase OA flow up to the maximum. But the use of `Controller:OutdoorAir` "Maximum Fraction of Outdoor Air Schedule Name" can limit the available OA. Both of the defect files set this schedule to zero during unoccupied hours, effectively shutting off any possible outdoor air. The air loop return flow resolution now accounts for the *currently available* maximum outdoor air for each air loop.

Note that OA controller does [increase OA flow to match zone exhaust](https://github.com/NREL/EnergyPlus/blob/a7c9cc14ce05cf09dca6623de97faa8546e2e1bb/src/EnergyPlus/MixedAir.cc#L3664-L3667) if other constraints allow just as it has before. At some point, this could be made an option, but not now.

In addition, missing air distribution unit indices for cooled beam units caused the zone air flow balance to see zero inlet flow and drive the return flow to zero.

### Defect files fixed
**Reviewers - note that updated defect files for both of these are in EnergyPlusDevSupport\DefectFiles\**

**Issue6492_noschedule.idf** (Denver epw): Before this fix, at the far right of the csv output, system "VAV WITH REHEAT" has zero flow on 01/01 from 00:00 to 08:00, and the zone air temperatures are well below the heating setpoint of 15.6C. After this fix, there is flow when the night cycle manager kicks in and the zone air temperatures reach setpoint before the system shuts off.

**Alt4MZVAVwoOAwhenOccupied-AddITESupplyNode** (St. Paul - Minneapolis epw):
See columns R:X in the csv output, on 01/01. Before the fix, there is no flow and all of the dampers are at zero. After the fix, there is flow. And columns H:Q show that the zones are cold before this fix, and at or near setpoint after.

### Diffs review:
**5ZoneAirCooledWithDOASAirLoop**: This has a recirc-only airloop and a DOAS airloop which has not return. By definition the return flow to the recirc-only airloop must equal the supply flow from that loop. In 9.0.1 that's not the case (add more output and compare columns BN (SPACE1-1 IN NODE flow) and GD (SPACE1-1 OUT NODE flow). These should always be equal. With this branch, they are. This file did reveal a false error for DOAS airloops with no OA system. That was fixed.

**PIUAuto**: Has small diffs.

**RefBldgLargeHotelNew2004_Chicago, RefBldgPrimarySchoolNew2004_Chicago, RefBldgSecondarySchoolNew2004_Chicago**: 
These all *had* new zone air balance warnings which was fixed by changing the test files to autosize the min flow fraction in the bathrooms (schools) and the dining room (hotel). This causes diffs in results.

**VariableRefrigerantFlow_FluidTCtrl_HR_5Zone**: Has the same zone unbalanced air flow warnings as before, but the warning content has changed.
*This is a real flow imbalance - there's not even an airloop - see #6301.*

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by mjwitte** [comment]
@rraustad Thanks! for catching the missing line and the typo. Looks like this is working. Will see what CI thinks of it.

**Comment by mjwitte** [comment]
@rraustad Some unexpected diffs to resolve.

**Comment by mjwitte** [comment]
### Diffs review:
*others moved to top comment*

~~DOAToFanCoilInlet~~ No more diffs.

**Comment by rraustad** [comment]
DOAToFanCoilInlet: so there are 2 competing fans here with their own availability schedule? Seems it was more correct before if the fan coil fans didn't start until 8AM. Which should prevail, zone equip or DOAS?

File: src/EnergyPlus/SimAirServingZones.cc [hunk 1]
```diff
@@ -4013,7 +4013,7 @@ namespace SimAirServingZones {
                                    ScalableSM + "Supply Air Flow Rate [m3/s]",
                                    PrimaryAirSystem(AirLoopNum).DesignVolFlowRate);
                 // Initialize MaxOutAir for DOAS loops with no actual OASys, systems with an OA controller will overwrite this is CalcOAController
-                if (PrimaryAirSystem(AirLoopNum).OASysExists)
+                if (PrimaryAirSystem(AirLoopNum).isAllOA)
```
Comment (rraustad) [inline src/EnergyPlus/SimAirServingZones.cc:4014]: Not sure what the difference here is. If it's all OA then isn't OASysExists = true? And if not all OA then OASysExists could be true or false. If false then MaxOutAir = 0 (or there is a DOAS?). So not sure this change has any affect.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 2]
```diff
@@ -4994,11 +4996,11 @@ namespace ZoneEquipmentManager {
...
 
-                    airLoopReturnFrac = DataAirLoop::AirLoopFlow(airLoop).DesReturnFrac;
-                    if (DataAirSystems::PrimaryAirSystem(airLoop).OASysExists) {
-                        // Set return flow as fraction of matching inlet node flow if there is an OA system
+                    airLoopReturnFrac = thisAirLoopFlow.DesReturnFrac;
+                    if (DataAirSystems::PrimaryAirSystem(airLoop).OASysExists && (thisAirLoopFlow.OAFlow > 0.0)) {
+                        // Set return flow as fraction of matching inlet node flow if there is an OA system and OA flow > 0.0
                         returnNodeMassFlow = airLoopReturnFrac * inletMassFlow;
-                        thisZoneEquip.TotAvailAirLoopOA = DataAirLoop::AirLoopFlow(airLoop).MaxOutAir;
+                        thisZoneEquip.TotAvailAirLoopOA += thisAirLoopFlow.OAFlow;
```
Comment (rraustad) [inline src/EnergyPlus/ZoneEquipmentManager.cc]: So if there are 2 zone equipment does each thisZoneEquip.TotAvailAirLoopOA = air loop OA? Wouldn't that somehow double count OA?

Comment (rraustad) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: How is "int airLoop = thisZoneEquip.ReturnNodeAirLoopNum(returnNum);" associated with a specific zone equipment?

File: src/EnergyPlus/SimAirServingZones.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/SimAirServingZones.cc:4014]: No, isAllOA means the branch inlet node is an OA node, no OA sys, no OA controller, no return. See 5ZoneAirCooledWithDOASAirLoop.idf.

**Comment by mjwitte** [comment]
Re: DOAToFanCoilInlet, the fan coil fans are running at 7am in both before and after.

File: src/EnergyPlus/ZoneEquipmentManager.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: Say there are two airloops serving a zone and both airloops have OA available, and there is an exhuast fan. The intent here is to reduce the return flows proportionally to the amount of OA each system is bringing in. Not sure as I'm writing this if TotAVailAirLoopOA should even be connected to a zone equip, it may just need to be a local value since this function goes zone-by-zone.  Need to review that.

**Comment by mjwitte** [comment]
@Myoldmopar @rraustad This is ready for review. See [top comment](https://github.com/NREL/EnergyPlus/pull/7059#issue-230909397) for discussion of changes, defect files and diffs.

**Comment by rraustad** [comment]
If OA is set to 0 at night and exhaust fan is left on, will this change bring in OA?

**Comment by mjwitte** [comment]
Good question. It should behave the same as before if using Min OA Schedule but should be zero OA if using Max Fraction OA Schedule.

**Comment by mjwitte** [comment]
By same as before I mean if the system is on it would open OA up to min of supply flow or max oa or the exhaust requirement. Probably need a test file to prove this.

File: src/EnergyPlus/HVACManager.cc [hunk 3]
```diff
@@ -3005,6 +3009,30 @@ namespace HVACManager {
         }
     }
 
+    void CheckAirLoopFlowBalance()
+    {
+        // Check for unbalanced airloop
+        if (!isPulseZoneSizing && !DataHeatBalance::ZoneAirMassFlow.EnforceZoneMassBalance && !DataGlobals::WarmupFlag && AirLoopsSimOnce) {
```
Comment (rraustad) [inline src/EnergyPlus/HVACManager.cc]: This is out of your scope but why don't we care about a mass imbalance if we are doing pulse sizing or enforcing mass balance?

File: src/EnergyPlus/HVACManager.cc [hunk 4]
```diff
@@ -3005,6 +3009,30 @@ namespace HVACManager {
...
+            for (int AirLoopNum = 1; AirLoopNum <= NumPrimaryAirSys; ++AirLoopNum) {
+                auto &thisAirLoopFlow(AirLoopFlow(AirLoopNum));
+                if (!thisAirLoopFlow.FlowError) {
+                    Real64 unbalancedExhaustDelta = thisAirLoopFlow.SupFlow - thisAirLoopFlow.OAFlow - thisAirLoopFlow.SysRetFlow;
```
Comment (rraustad) [inline src/EnergyPlus/HVACManager.cc:3092]: Also out of your scope, but this has been bothering me for some time. If a user adds mixing, cross mixing, or ventilation to this zone then exhaust might be balanced and we still tell them there is a problem.

File: src/EnergyPlus/HVACManager.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/HVACManager.cc]: One other comment, put an outside IF block using IF(thisAirLoopFlow.FlowError) so these multiple checks don't have to be evaluated each call.

File: src/EnergyPlus/MixedAir.cc [hunk 5]
```diff
@@ -3683,11 +3684,13 @@ namespace MixedAir {
...
 
         // Apply Maximum Fraction of Outdoor Air Schedule
+        Real64 currentMaxOAMassFlowRate = this->MaxOAMassFlowRate;
         if (this->MaxOAflowSchPtr > 0) {
             Real64 MaxOAflowfracVal = GetCurrentScheduleValue(this->MaxOAflowSchPtr);
             MaxOAflowfracVal = min(max(MaxOAflowfracVal, 0.0), 1.0);
+            currentMaxOAMassFlowRate = min(this->MaxOAMassFlowRate, this->MixMassFlow * MaxOAflowfracVal);
             OutAirMinFrac = min(MaxOAflowfracVal, OutAirMinFrac);
-            this->OAMassFlow = min(this->OAMassFlow, this->MixMassFlow * MaxOAflowfracVal);
+            this->OAMassFlow = min(this->OAMassFlow, currentMaxOAMassFlowRate);
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:3713]: Just talking out loud here. So if OA is limited by the max schedule then it will go to 0 if the user so chooses. This is good, but if the exhaust fan is still running then what happens?

File: src/EnergyPlus/ZoneEquipmentManager.hh [hunk 6]
```diff
@@ -129,7 +129,7 @@ namespace ZoneEquipmentManager {
                                     Optional_int_const EquipPriorityNum = _ // index in PrioritySimOrder for this update
     );
 
-    void CalcZoneMassBalance();
+    void CalcZoneMassBalance(bool const FirstHVACIteration);
```
Comment (rraustad) [inline src/EnergyPlus/ZoneEquipmentManager.hh:132]: Where did you use this new bool?

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 7]
```diff
@@ -4994,11 +4977,11 @@ namespace ZoneEquipmentManager {
...
-                        // Set return flow as fraction of matching inlet node flow if there is an OA system
+                    airLoopReturnFrac = thisAirLoopFlow.DesReturnFrac;
+                    if (DataAirSystems::PrimaryAirSystem(airLoop).OASysExists && (thisAirLoopFlow.MaxOutAir > 0.0)) {
+                        // Set return flow as fraction of matching inlet node flow if there is an OA system and available OA flow > 0.0
                         returnNodeMassFlow = airLoopReturnFrac * inletMassFlow;
-                        thisZoneEquip.TotAvailAirLoopOA = DataAirLoop::AirLoopFlow(airLoop).MaxOutAir;
+                        thisZoneEquip.TotAvailAirLoopOA += thisAirLoopFlow.MaxOutAir;
                     } else {
                         // Set return flow to matching inlet node flow
                         returnNodeMassFlow = inletMassFlow;
```
Comment (rraustad) [inline src/EnergyPlus/ZoneEquipmentManager.cc:5043]: What happens to unbalanced exhaust flow here?

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 8]
```diff
@@ -4994,11 +4977,11 @@ namespace ZoneEquipmentManager {
                         retNodeData.MassFlowRateMaxAvail = zoneNodeData.MassFlowRateMaxAvail;
                     }
 
-                    airLoopReturnFrac = DataAirLoop::AirLoopFlow(airLoop).DesReturnFrac;
-                    if (DataAirSystems::PrimaryAirSystem(airLoop).OASysExists) {
-                        // Set return flow as fraction of matching inlet node flow if there is an OA system
+                    airLoopReturnFrac = thisAirLoopFlow.DesReturnFrac;
+                    if (DataAirSystems::PrimaryAirSystem(airLoop).OASysExists && (thisAirLoopFlow.MaxOutAir > 0.0)) {
+                        // Set return flow as fraction of matching inlet node flow if there is an OA system and available OA flow > 0.0
                         returnNodeMassFlow = airLoopReturnFrac * inletMassFlow;
```
Comment (rraustad) [inline src/EnergyPlus/ZoneEquipmentManager.cc:5039]: I'm not feeling this. The airloopReturnFrac is a constant, If exhaust is present then how does this account for the mass imbalance? This is meant to adjust returns for multiple air loops per zone so how do we account for unbalanced exhaust flow here?

File: src/EnergyPlus/HVACManager.cc (hunk 3 above)
Comment (mjwitte) [reply src/EnergyPlus/HVACManager.cc]: Good question. This airloop balance check was originally in `ZoneEquipmentManager:::CalcZoneMassBalance` and this if came along for the ride. The only one here that should matter is AirLoopsSimOnce.  If `EnforceZoneMassBalance` is active, then the loop should still be balanced.

File: src/EnergyPlus/HVACManager.cc (hunk 4 above)
Comment (mjwitte) [reply src/EnergyPlus/HVACManager.cc:3092]: No, this check here is strictly inside the ductwork. It's basically a mass balance on the mixing box after all the pieces parts have finished. Is supply > return + OA?  The other check at the zone level accounts for the other flows.

File: src/EnergyPlus/MixedAir.cc (hunk 5 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc:3713]: Then the return is forced to match the supply minus available OA (if OA is zero, then return=supply). The zone has to make up the exhaust flow with infiltration/mixing/zoneventilation.  If there's not enough of that, then the zone balance warning should trip.

File: src/EnergyPlus/ZoneEquipmentManager.hh (hunk 6 above)
Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.hh:132]: Here in the [zone balance check](https://github.com/NREL/EnergyPlus/pull/7059/files#diff-e954944c50c5b52c35f6c9f2d1ad3bf5R4845).

File: src/EnergyPlus/ZoneEquipmentManager.cc (hunk 7 above)
Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.cc:5043]: Nothing yet. The return flows get adjusted in step 2 (or 10 or whatever) [below](https://github.com/NREL/EnergyPlus/pull/7059/files#diff-e954944c50c5b52c35f6c9f2d1ad3bf5L5046).

File: src/EnergyPlus/ZoneEquipmentManager.cc (hunk 8 above)
Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.cc:5039]: We don't yet. At this point, we're trying to apportion the total return to each airloop.

**Comment by mjwitte** [comment]
@rraustad Removed some of the flags in the `CheckAirBalance` if [here](https://github.com/NREL/EnergyPlus/pull/7059/commits/e9e8901097358304c5c0a08cbff966486654fd0a).

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by rraustad** [comment]
@mjwitte where do you feel this stands at the moment? I and @EnergyArchmage are interested in these changes.

File: src/EnergyPlus/HVACManager.cc [hunk 9]
```diff
@@ -3005,6 +3009,30 @@ namespace HVACManager {
...
+        if (!DataGlobals::WarmupFlag && AirLoopsSimOnce) {
+            for (int AirLoopNum = 1; AirLoopNum <= NumPrimaryAirSys; ++AirLoopNum) {
+                auto &thisAirLoopFlow(AirLoopFlow(AirLoopNum));
+                if (!thisAirLoopFlow.FlowError) {
+                    Real64 unbalancedExhaustDelta = thisAirLoopFlow.SupFlow - thisAirLoopFlow.OAFlow - thisAirLoopFlow.SysRetFlow;
+                    if (unbalancedExhaustDelta > SmallMassFlow) {
+                        ShowSevereError("CheckAirLoopFlowBalance: AirLoopHVAC " + DataAirSystems::PrimaryAirSystem(AirLoopNum).Name +
+                            " is unbalanced. Supply is > return plus outdoor air.");
+                        ShowContinueErrorTimeStamp("");
+                        ShowContinueError("  Flows [m3/s at standard density]: Supply=" + General::RoundSigDigits(thisAirLoopFlow.SupFlow * DataEnvironment::StdRhoAir, 6) +
```
Comment (rraustad) [inline src/EnergyPlus/HVACManager.cc]: The warning here says "Flows [m3/s at standard density]", and then does SupFlow *StdRhoAir. But SupFlow (and others) is already in kg/s isn't it?

From hh file:
        Real64 SupFlow;               // supply air flow rate (includes LeakFlow) [kg/s]

Comment (mjwitte) [reply src/EnergyPlus/HVACManager.cc]: @rraustad Good catch - these are all in kg/s, so need to *divide* by `StdRhoAir` to output m3/s.

**Comment by mjwitte** [comment]
OK, that's better, now diffs are back to where they were in December.

**Comment by rraustad** [comment]
Starting review with Alt4MZVAVwoOAwhenOccupied-AddITESupplyNode.idf.
I have questions. 

There is mixing (equal to exhaust fan flow) and no infiltration in the restrooms. The 2 restrooms are modeling as a single zone, GUID16_restrooms.

```
ZoneMixing,
  AirflowTransfer_GUID16_restrooms_2,     !- Name
  GUID16_restrooms,                       !- Zone Name
  Room Exhaust and Room Air Transfer - Available (100%), !- Schedule Name
  Flow/Zone,                              !- Design Flow Rate Calculation Method
  0.0330363210752851,                     !- Design Flow Rate {m3/s}
  ,                                       !- Flow Rate per Zone Floor Area {m3/s-m2}
  ,                                       !- Flow Rate per Person {m3/s-person}
  ,                                       !- Air Changes per Hour {1/hr}
  GUID12_Lobby;                           !- Source Zone Name

ZoneMixing,
  AirflowTransfer_GUID16_restrooms_1,     !- Name
  GUID16_restrooms,                       !- Zone Name
  Room Exhaust and Room Air Transfer - Available (100%), !- Schedule Name
  Flow/Zone,                              !- Design Flow Rate Calculation Method
  0.0330363210752851,                     !- Design Flow Rate {m3/s}
  ,                                       !- Flow Rate per Zone Floor Area {m3/s-m2}
  ,                                       !- Flow Rate per Person {m3/s-person}
  ,                                       !- Air Changes per Hour {1/hr}
  GUID12_Lobby;                           !- Source Zone Name

ZoneInfiltration:DesignFlowRate,
  Infiltration_GUID16_restrooms_Women 112_2, !- Name
  GUID16_restrooms,                       !- Zone or ZoneList Name
  Infiltration - Off (0%) All Hours,      !- Schedule Name
  Flow/Zone,                              !- Design Flow Rate Calculation Method
  0,                                      !- Design Flow Rate {m3/s}
  ,                                       !- Flow per Zone Floor Area {m3/s-m2}
  ,                                       !- Flow per Exterior Surface Area {m3/s-m2}
  ,                                       !- Air Changes per Hour {1/hr}
  1,                                      !- Constant Term Coefficient
  0,                                      !- Temperature Term Coefficient
  0,                                      !- Velocity Term Coefficient
  0;                                      !- Velocity Squared Term Coefficient

ZoneInfiltration:DesignFlowRate,
  Infiltration_GUID16_restrooms_Men 113_1, !- Name
  GUID16_restrooms,                       !- Zone or ZoneList Name
  Infiltration - Off (0%) All Hours,      !- Schedule Name
  Flow/Zone,                              !- Design Flow Rate Calculation Method
  0,                                      !- Design Flow Rate {m3/s}
  ,                                       !- Flow per Zone Floor Area {m3/s-m2}
  ,                                       !- Flow per Exterior Surface Area {m3/s-m2}
  ,                                       !- Air Changes per Hour {1/hr}
  1,                                      !- Constant Term Coefficient
  0,                                      !- Temperature Term Coefficient
  0,                                      !- Velocity Term Coefficient
  0;                                      !- Velocity Squared Term Coefficient

```

OK, so there is mixing all the time that is equal to the zone exhaust fan air flow.

Oddly, the warning for unbalanced flow is reported for the restroom first on 1/14 05:30.

    ** Warning ** In zone GUID16_RESTROOMS there is unbalanced air flow. Load due to induced outdoor air is neglected.
    **   ~~~   **  Environment=RUNPERIOD 1, at Simulation time=01/14 05:15 - 05:30
    **   ~~~   **   Flows [kg/s]: Inlets: 7.865924E-003  Unbalanced exhausts: 7.720463E-002  Returns: 7.865924E-003
    **   ~~~   **   Infiltration: 0.000000  Zone Ventilation: 0.000000  Mixing (incoming): 7.617664E-002
    **   ~~~   **   Imbalance (excess outflow): 1.027984E-003  Total system OA flow (for all airloops serving this zone): 0.000000
    **   ~~~   **   This error will only be reported once per zone.

The zone flow rates for the restroom are shown from the beginning of the simulation at 1/1 1:00.

When there is no outdoor air (grey) the return flow equals the supply flow. Good, the zone flows are balanced. 

1) When OA turns on at 1/2 7:00 the return flow goes to 0. This was the intent but if there is mixing making up for the zone exhaust, then shouldn't the return flow equal supply?
2) If the condition at 1/2 7:00 represents unbalanced zone flow then why did the unbalanced warning print for the first time on 1/14 5:30 ?

image

**Comment by rraustad** [comment]
Plot for 1/14 does not show a reason for the unbalanced exhaust warning?

image

**Comment by rraustad** [comment]
Is the zone inlet node mass flow rate based on current density and mixing based on standard density? Or the fact that the conditions to calculate mass using current density are different for these 2 airstreams which would also wind up with different mass flows for these 2 streams when the input intent is for them to be equal. Either of these could trip the warning.

**Comment by rraustad** [comment]
Looking at the lobby, where the mixing for the restrooms originates, I see a difference between supply and return but am not sure why. There is no infiltration in the lobby. The difference in flow is 0.021 m3/s which differs from the mixing flow to the restrooms. Difference should be 0.066 m3/s?

image

**Comment by Myoldmopar** [comment]
@mjwitte CI results make sense with your description.  I built with develop and this branch and confirmed your comments in the description as well.  I would like to wait until you resolve the comments from @rraustad before I review the code in case there is any other changes required.

**Comment by mjwitte** [comment]
@rraustad You pegged it - ZoneMixing shows a constant value for Zone Mixing Current Density Volume Flow Rate and the mixing mass flow rate varies with conditions of the source (or receiving or both) zone.  While the flow rate at the Fan:ZoneExhaust inlet node shows a constant mass flow rate and System Node Standard Density Volume Flow Rate. On a mass flow basis there *is* an imbalance for some hours, and not for others.

Do we change ZoneMixing (and crossmixing) to use standard density to calculate the mass flow rate? And cause massive diffs.
Do we change Fan:ZoneExhaust to use current density to calculate mass flow rate? And cause massive diffs.
Do we add some slop to this balanced flow check to allow for density impacts (even though technically the mass flow rates are indeed unbalanced)?
Other??

**Comment by rraustad** [comment]
I recall a problem with DX coils where the cfm/ton warnings were tripping on the same issue. Coil mass flow was calculated using std density and the volume used for the warning check was calculated using current density. The fix was to use std density to back calculate volume for warning purposes only. Now here the problem is similar. Per your suggestions, can't do 1) since that was a fix for an issue, can't recall which. I do like 2) since that's the way it should be but that probably won't correct this warning issue since the fan uses this zone's density and mixing uses the "from"? zone density. And for 3) a little slop should be added but not enough to correct this problem.

It would be nice to know what basis the mass flow is calculated for a particular model. Any of those that use std density can simply use that to back calculate volume. If a model uses current density then that density needs to be used to back calculate volume. So 4) Other: How hard would it be to add a density variable to the mixing object so that volume could be back calculated when needed (Volume = mixing.mass / mixing.density)? This, of course, just hides the fact that E+ uses different basis for mass calc's but it sounds easy enough to get past this warning.

**Comment by mjwitte** [comment]
The mixing density may not be available directly, but the mixing current density volume flow rate is. I'll tinker with this and see if the warning can be gone for now without adding too many extra calculations.

**Comment by rraustad** [comment]
The mixing density would be available if you saved it in a structure variable when mass was calculated, mixing.density. I don't particularly like this either but it meets the intent.

**Comment by mjwitte** [comment]
@rraustad Adding a volume flow check gets rid of the unbalanced flow warnings for defect file Alt4MZVAVwoOAwhenOccupied-AddITESupplyNode.idf but doesn't appear to have changed the new warnings in the test suite files. I'll look at those in more detail to see if they are justified. Remember when evaluating this, that none of these files have `ZoneAirMassFlowConservation` active, so return flows will not be adjusted based on infiltration or mixing flows, but these flow are included in the checks that generate the warning.

**Comment by rraustad** [comment]
I never did like that new object (which was created to avoid diff's when correcting something that was broken). I vote to internally turn on ZoneAirMassFlowConservation so we don't thumb our noses at the laws of conservation of mass/energy and eventually deprecate that object.

**Comment by mjwitte** [comment]
RefBldgPrimarySchoolNew2004_Chicago - Bath_ZN_1_FLR_1 has an exhaust fan at 0.2832 m3/s and a VAV box which sizes to a minimum flow of 0.15 and a maximum flow of 0.50. But there is no ZoneMixing object. So, anytime that the VAV box goes below 0.2832, there will be an imbalancein this zone. Could add a ZoneMixing object, or increase the min flow fraction for this zone.

RefBldgLargeHotelNew2004_Chicago - DINING_FLR_6 has an exhaust fan at 1.84352 m3/s (which matches a ZoneMixing object from Dining to the Kitchen), but the supply to dining is VAV box with min flow of 1.3 and max flow of 4.36. So, again the min flow doesn't match the exhaust flow. In this case, the dining supply is supposed to be providing makeup air to the kitchen, so the dining OA requirement should really be the greater of the mixing flow to the kitchen or the dining zone requirement. But Sizing:Zone for Dining has this:
`1.84779, !- Cooling Minimum Air Flow [m3/s]` which is *supposed to* put a limit on the min flow rate - so why is that not working? Because the VAV terminal unit min flow fraction is fixed at 0.3 - it should be autosize for the min flow to get applied. Will fix that - it gets rid of the unbalanced flow warnings. And, of course will cause diffs.

**Comment by mjwitte** [comment]
VariableRefrigerantFlow_FluidTCtrl_HR_5Zone should not have any unbalanced flow warnings, but that's nothing to do with this PR. VRF terminal units don't set the same inlet/outlet flows, see #6301.

**Comment by mjwitte** [comment]
@rraustad @Myoldmopar Final answer (hopefully). See comments at top regarding files with diffs.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 10]
```diff
@@ -4919,28 +4919,41 @@ namespace ZoneEquipmentManager {
                     !DataGlobals::WarmupFlag && !DataGlobals::DoingSizing && !FirstHVACIteration) {
                     if (!thisZoneEquip.FlowError) {
```
Comment (rraustad) [inline src/EnergyPlus/ZoneEquipmentManager.cc:4919]: Just a side note here. !DataGlobals::ZoneSizingCalc && !DataGlobals::SysSizingCalc are both set inside ManageSizing() while !DataGlobals::DoingSizing is set outside that function. Could remove ZoneSizingCalc and SysSizingCalc from this IF test.

        DoingSizing = true;
        ManageSizing();

        BeginFullSimFlag = true;
        SimsDone = false;
        if (DoDesDaySim || DoWeathSim || DoHVACSizingSimulation) {
            DoOutputReporting = true;
        }
        DoingSizing = false;

Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.cc:4919]: @rraustad Thanks. I will clean that up and check elsewhere.

Comment (rraustad) [reply src/EnergyPlus/ZoneEquipmentManager.cc:4919]: I didn't check but I wonder if isPulseZoneSizing is complete before BeginFullSimFlag = true is set? If so, could reduce this even futher.

Comment (rraustad) [reply src/EnergyPlus/ZoneEquipmentManager.cc:4919]: extern bool isPulseZoneSizing;                 // true during the set of zone sizing calcs that include the "pulse" for the load component report

Comment (rraustad) [reply src/EnergyPlus/ZoneEquipmentManager.cc:4919]: Forget BeginFullSimFlag, it's set and reset multiple times.

File: tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc [hunk 11]
```diff
@@ -660,21 +671,196 @@ TEST_F(EnergyPlusFixture, ZoneEquipmentManager_CalcZoneMassBalanceTest3)
...
+
+    CalcZoneReturnFlows(ZoneNum, StdTotalReturnMassFlow, FinalTotalReturnMassFlow);
+    EXPECT_EQ(FinalTotalReturnMassFlow, 0.0);
+    EXPECT_EQ(Node(returnNode1).MassFlowRate, 0.0);
+    EXPECT_EQ(Node(returnNode2).MassFlowRate, 0.0);
+    EXPECT_EQ(Node(returnNode3).MassFlowRate, 0.0);
+
+    // Case 2 - send sum of inlet flow back, except system 2 back at 0.9 
+    StdTotalReturnMassFlow = 0.0;
+    FinalTotalReturnMassFlow = 0.0;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc]: @mjwitte do this only if your making changes. These 2 lines not needed. Same with 2 at line 844.

**Comment by rraustad** [comment]
Confirmed defect file now operates at night when OA flow = 0 (root cause of defect).

image

File: src/EnergyPlus/ZoneEquipmentManager.cc (hunk 10 above)
Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.cc:4919]: Likewise, `isPulseZoneSizing` is only true inside ManageSizing, so `DoingSizing` covers that.

File: tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc (hunk 11 above)
Comment (mjwitte) [reply tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc]: Removed redundant lines in several places in the new test and in an older test (which is where this pattern got copied from . . . )

**Comment by rraustad** [comment]
Added zone inlet (blue), exhaust (green) and return (orange dotted) nodes to defect file and looked at zone volume balance. Return node is now offset from supply by amount of exhaust during the daytime hours (when OA flow exceeds exhaust). When OA node flow = 0 during the night (see above), the inlet and return node flows match. All good! Unit tests also keep this zone balance coordinated in case someone wants to change something in this part of the code. Very detailed warning to highlight the issue. Nice job @mjwitte. However, warning is first reported on 1/2 at 6 AM when imbalance is obvious at 1/1 00:06 AM. That one is a little confusing.

    ** Warning ** In zone THERMAL ZONE: STORY 1 CORE SPACE there is unbalanced air flow. Load due to induced outdoor air is neglected.
    **   ~~~   **  Environment=RUN PERIOD 1, at Simulation time=01/02 06:00 - 06:10
    **   ~~~   **   Flows [m3/s]: Inlets: 0.170361  Unbalanced exhausts: 4.719474E-002  Returns: 0.170361
    **   ~~~   **   Infiltration: 2.051160E-002  Zone Ventilation: 0.000000  Mixing (incoming): 0.000000
    **   ~~~   **   Imbalance (excess outflow): 2.668314E-002  Total system OA flow (for all airloops serving this zone): 0.000000
    **   ~~~   **   This error will only be reported once per zone.

image

**Comment by mjwitte** [comment]
Remember that infiltration also counts and mass flow balance is checked first. The infiltration in this file has this schedule which explains why there's no imbalance until 1/2 at 6am when the infiltration falls to 25%.
```
  Schedule:Day:Interval,
    Office Infil Quarter On Default Schedule,  !- Name
    Fraction,                !- Schedule Type Limits Name
    No,                      !- Interpolate to Timestep
    06:00,                   !- Time 1
    1,                       !- Value Until Time 1
    22:00,                   !- Time 2
    0.25,                    !- Value Until Time 2
    24:00,                   !- Time 3
    1;                       !- Value Until Time 3
```

**Comment by rraustad** [comment]
Sure enough, right at around 6 AM.

image

**Review by rraustad — APPROVED** [review]
Reviewed code and unit tests. Ran defect file with comments answered. Results provide expected results.

**Comment by mjwitte** [comment]
@rraustad Thanks.
@Myoldmopar Expecting this last commit to produce identical CI results as before. If not, there's a problem.

**Comment by rraustad** [comment]
@Myoldmopar I've noticed that the i386 CI isn't running the tests. Always comes back with no diff's. Did that comment I had a while ago ever get implemented? Where the folder gets deleted before the tests are ran because CMake has that folder locked? until the log files are written (or it recreates that folder)? That method seems to work fine here and we get identical results for i386 and Win64. I can't recall now where that was in the script.

**Comment by rraustad** [comment]
CI results are identical to previous result as expected. Considering this work complete.
