### PR TITLE
Fix an incorrect if Block Condition in VariableSpeedCoils.cc

### LINKED ISSUE #11459: Incorrect if Block Condition in VariableSpeedCoils.cc
### Issue overview

An issue Identified in `VariableSpeedCoils.cc`: [Incorrect Conditional Logic in `if` Block](https://github.com/NatLabRockies/EnergyPlus/blob/develop/src/EnergyPlus/VariableSpeedCoils.cc#L844)

`|| cFieldName.empty()` in the Condenser Type check probably meant `condenserType.empty()` I guess, as `cFieldName` has always have a value due to line 842 (2 lines above).

### Operating System (Multiple choices)

Windows

### Operating System Version

11

### Version of EnergyPlus

25.2

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by dareumnam**
Pull request overview
---------------------

- Fixes #11459

### Pull Request Author

 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by mitchute — APPROVED** [review]
Looks like a good fix

**Review by mitchute — APPROVED** [review]

**Comment by mitchute** [comment]
Looking a bit closer, that field will never come in blank since we have a default value set, so we don't even need that check.

```
   A7,  \field Condenser Type
        \type choice
        \key AirCooled
        \key EvaporativelyCooled
        \default AirCooled
```

Not spending more cycles on this one, but this is possibly another avenue for input cleanups going forward.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 1]
```diff
@@ -841,7 +841,7 @@ namespace VariableSpeedCoils {
 
                 cFieldName = "Condenser Type"; // cAlphaFields(6)
                 std::string const condenserType = s_ip->getAlphaFieldValue(fields, schemaProps, "condenser_type");
-                if ((Util::SameString(condenserType, "AirCooled")) || cFieldName.empty()) {
+                if ((Util::SameString(condenserType, "AirCooled")) || condenserType.empty()) {
```
Comment (rraustad) [inline src/EnergyPlus/VariableSpeedCoils.cc:844]: Nothing to do here. I am just reiterating IDD rules. This is not a required-field so the user can leave this field blank. Since it has a default a blank field will be filled with AirCooled by the input processor. So by the time code execution gets here (i.e., after the InputProcessor has executed) there are only 2 possible inputs, AirCooled or EvaporativelyCooled. This field can never be blank.

    Coil:Cooling:DX:VariableSpeed,
      A7,  \field Condenser Type
            \type choice
            \key AirCooled
            \key EvaporativelyCooled
            \default AirCooled

Comment (dareumnam) [reply src/EnergyPlus/VariableSpeedCoils.cc:844]: Thanks for the input. Maybe we can remove this check later.
