### PR TITLE
Space for IlluminanceMap and Internal Mass

### LINKED ISSUE #9140: Output:IlluminanceMap doesn't support Space
Issue overview
--------------

It wasn't terribly clear since it was part of https://github.com/NREL/EnergyPlus/issues/9119

> Additionally, Output:IlluminanceMap (including IDD) should probably be updated as well to support Space Names instead of just 'Zone Name' to match the new DaylightingControls capability to be added at Space level rather than at Zone level?

Trying to use a Space Name will issue a std::bad_alloc too.

```
   ** Severe  ** Output:IlluminanceMap="ILLUMINANCE MAP 1", invalid Zone Name="SPACE 2".
   ** Severe  ** std::bad_alloc
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9141: InternalMass should use a 'Zone or ZoneList or Space or SpaceList' name like loads do
Issue overview
--------------

Related: https://github.com/NREL/EnergyPlus/issues/9136

InternalMass should use a 'Zone or ZoneList or Space or SpaceList' name like loads do

Shouldn't InternalMass be changed from 

```
  A3 , \field Zone or ZoneList Name
       \required-field
       \type object-list
       \object-list ZoneAndZoneListNames
       \note Zone the surface is a part of.
       \note used to be Interior Environment
  A4 , \field Space or SpaceList Name
       \type object-list
       \object-list SpaceAndSpaceListNames
       \note Space the surface is a part of (optional, see description of Space object for more details).
       \note This field is ignored when a ZoneList Name is specified for Zone or ZoneList Name.
```

to 

```
  A3 , \field Zone or ZoneList or Space or SpaceList Name
       \required-field
       \type object-list
       \object-list ZoneAndZoneListNames
       \object-list SpaceAndSpaceListNames
       \note Zone the surface is a part of.
       \note used to be Interior Environment
```

**An IDD Change might not be a good idea at this point though.**

**But**: if you try to write 'Space Or Space List' field, input parser throws because Zone or Zone List field is empty

```
InternalMass,
  Interior Partition Surface 1,           !- Name
  Interior Partition,                     !- Construction Name
  ,                                       !- Zone or ZoneList Name
  Space 2,                                !- Space or SpaceList Name
  6;                                      !- Surface Area {m2}
```

```
Program Version,EnergyPlus, Version 9.6.0-c6e2aecb89, YMD=2021.10.18 11:20,
   ** Severe  ** <root>[InternalMass][Interior Partition Surface 1] - Missing required property 'zone_or_zonelist_name'.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
```

If I write both Zone and Space names, it seems to run. But then the IDD comment `\note This field is ignored when a ZoneList Name is specified for Zone or ZoneList Name.` is wrong no?

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #9140
 - Allow Output:IlluminanceMap to be for a zone or space.
 - Partially addresses #9141 
 - For InternalMass, Zone or ZoneList Name is no longer required. If Zone/ZoneList Name is entered without a space name, then the internal mass will be added to the last space that belongs to the Zone(s). If a Space/SpaceList name is entered, then the Zone/ZoneList name is ignored. The internal mass will be added to the zone that the space(s) belongs to.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DaylightingManager.cc [hunk 1]
```diff
@@ -4033,37 +4038,46 @@ void GetInputIlluminanceMap(EnergyPlusData &state, bool &ErrorsFound)
...
-
-            if (illumMap.zoneIndex == 0) {
-                ShowSevereError(state,
-                                format("{}=\"{}\", invalid {}=\"{}\".",
-                                       ipsc->cCurrentModuleObject,
-                                       ipsc->cAlphaArgs(1),
-                                       ipsc->cAlphaFieldNames(2),
-                                       ipsc->cAlphaArgs(2)));
-                ErrorsFound = true;
+            int const spaceNum = Util::FindItemInList(state.dataIPShortCut->cAlphaArgs(2), state.dataHeatBal->space);
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc]: Accept a Space Name for Output:IlluminanceMap.

File: src/EnergyPlus/DaylightingManager.cc [hunk 2]
```diff
@@ -4033,37 +4038,46 @@ void GetInputIlluminanceMap(EnergyPlusData &state, bool &ErrorsFound)
...
-                for (int spaceCounter = 2; spaceCounter <= state.dataHeatBal->Zone(zoneNum).numSpaces; ++spaceCounter) {
-                    int spaceNum = state.dataHeatBal->Zone(zoneNum).spaceIndexes(spaceCounter);
-                    if (enclNum != state.dataHeatBal->space(spaceNum).solarEnclosureNum) {
-                        ShowSevereError(state,
-                                        format("{}=\"{}\" All spaces in the zone must be in the same enclosure for daylighting illuminance maps.",
-                                               ipsc->cCurrentModuleObject,
-                                               ipsc->cAlphaArgs(1)));
-                        ErrorsFound = true;
-                        break;
+                illumMap.zoneIndex = Util::FindItemInList(ipsc->cAlphaArgs(2), state.dataHeatBal->Zone);
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc]: If name is not a space, then lookup a zone.

File: src/EnergyPlus/DaylightingManager.cc [hunk 3]
```diff
@@ -4308,6 +4322,7 @@ void GetInputIlluminanceMap(EnergyPlusData &state, bool &ErrorsFound)
         }
     }
     ZoneMsgDone.deallocate();
+    if (ErrorsFound) return;
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc:4324]: This was too late, and could cause an array bounds error in the eio printing below.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 4]
```diff
@@ -2846,7 +2846,8 @@ namespace SurfaceGeometry {
 
         for (int surfNum = 1; surfNum <= state.dataSurface->TotSurfaces; ++surfNum) {
             auto &thisSurf = Surfaces(surfNum);
-            if (!thisSurf.HeatTransSurf) continue; // ignore shading surfaces
+            if (!thisSurf.HeatTransSurf) continue;                               // ignore shading surfaces
+            if (thisSurf.Class == DataSurfaces::SurfaceClass::IntMass) continue; // skip internal mass surfaces for this check
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2850]: When checking the surface space assignments, don't want a stray InternalMass object to trigger adding a new -Remainder space.

**Review by mjwitte — COMMENTED** [review]
Code walkthru. Small changes to clean up space handling. Added a new testfile 5ZoneAirCooledWithSpacesDaylightingIntMass.idf to test various applications of these inputs.

File: src/EnergyPlus/DaylightingManager.cc (hunk 1 above)
Comment (jmarrec) [reply src/EnergyPlus/DaylightingManager.cc]: The way you ordered the if-else ladder seem to imply it would be more common now to use a Space Name rather than a Zone Name. Is that so?

File: src/EnergyPlus/DaylightingManager.cc [hunk 5]
```diff
@@ -4033,37 +4038,46 @@ void GetInputIlluminanceMap(EnergyPlusData &state, bool &ErrorsFound)
...
+                    for (int spaceCounter = 2; spaceCounter <= state.dataHeatBal->Zone(zoneNum).numSpaces; ++spaceCounter) {
+                        int spaceNum = state.dataHeatBal->Zone(zoneNum).spaceIndexes(spaceCounter);
+                        if (enclNum != state.dataHeatBal->space(spaceNum).solarEnclosureNum) {
+                            ShowSevereError(state,
+                                            format("{}=\"{}\" All spaces in the zone must be in the same enclosure for daylighting illuminance maps.",
+                                                   ipsc->cCurrentModuleObject,
+                                                   ipsc->cAlphaArgs(1)));
+                            ShowContinueError(
+                                state,
+                                format("Zone=\"{}\" spans multiple enclosures. Use a Space Name instead.", state.dataHeatBal->Zone(zoneNum).Name));
```
Comment (jmarrec) [inline src/EnergyPlus/DaylightingManager.cc]: Nice.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 4 above)
Comment (jmarrec) [reply src/EnergyPlus/SurfaceGeometry.cc:2850]: I don't really understand this, but it does seem to make sense.

File: src/Transition/InputRulesFiles/Rules24-1-0-to-24-2-0.md [hunk 6]
```diff
@@ -50,7 +50,8 @@ There are three new optional heat recovery fields at the end which transition wi
 
 # Object Change: ObjectStartsWithN
 
-# Object Change: ObjectStartsWithO
+# epJSON Field Name Change: Output:IlluminanceMap
+`zone_name` --> `zone_or_space_name`
```
Comment (jmarrec) [inline src/Transition/InputRulesFiles/Rules24-1-0-to-24-2-0.md:54]: :+1:

(And no transition (fortran) needed because field didn't change location, and will continue to work)

File: testfiles/CMakeLists.txt [hunk 7]
```diff
@@ -51,6 +51,7 @@ add_simulation_test(IDF_FILE 5ZoneAirCooledConvCoef.idf EPW_FILE USA_CO_Golden-N
 add_simulation_test(IDF_FILE 5ZoneAirCooledConvCoef_VSFan.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
 add_simulation_test(IDF_FILE 5ZoneAirCooledKeepSiteLocation.idf EPW_FILE USA_CO_Golden-NREL.724666_TMY3.epw)
 add_simulation_test(IDF_FILE 5ZoneAirCooledWithSpaces.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
+add_simulation_test(IDF_FILE 5ZoneAirCooledWithSpacesDaylightingIntMass.idf EPW_FILE USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw)
```
Comment (jmarrec) [inline testfiles/CMakeLists.txt:54]: New test file, nice.

File: testfiles/5ZoneAirCooledWithSpacesDaylightingIntMass.idf
Comment (jmarrec) [inline testfiles/5ZoneAirCooledWithSpacesDaylightingIntMass.idf:1]: I diffed `5ZoneAirCooledWithSpaces.idf` and this one.

"Zone 1" and "Space 3" got new Daylighting:Controls, Daylighting:ReferencePoint, and Output:IlluminanceMap.

All Zones, and All Spaces, plus "Space 5 Office" and "Space 5 Conference" specifically, now have an InternalMass object.

```diff
--- 5ZoneAirCooledWithSpaces.idf	2024-05-16 17:56:08.849224791 +0200
+++ 5ZoneAirCooledWithSpacesDaylightingIntMass.idf	2024-08-19 11:16:50.565934236 +0200
@@ -126,7 +126,8 @@
   GlobalGeometryRules,
     UpperLeftCorner,         !- Starting Vertex Position
     CounterClockWise,        !- Vertex Entry Direction
-    Relative;                !- Coordinate System
+    Relative,                !- Coordinate System
+    Relative;                !- Daylighting Reference Point Coordinate System
 
   ScheduleTypeLimits,
     Any Number;              !- Name
@@ -924,9 +925,45 @@
     0.2,                     !- Return Air Fraction
     0.59,                    !- Fraction Radiant
     0.2,                     !- Fraction Visible
-    0,                       !- Fraction Replaceable
+    1.0,                     !- Fraction Replaceable
     GeneralLights;           !- End-Use Subcategory
 
+  Daylighting:Controls,
+    Zone 1 Daylighting Control,  !- Name
+    Zone 1,                  !- Zone or Space Name
+    SplitFlux,               !- Daylighting Method
+    ,                        !- Availability Schedule Name
+    Stepped,                 !- Lighting Control Type
+    0.3000,                  !- Minimum Input Power Fraction for Continuous or ContinuousOff Dimming Control
+    0.2000,                  !- Minimum Light Output Fraction for Continuous or ContinuousOff Dimming Control
+    3,                       !- Number of Stepped Control Steps
+    1.0000,                  !- Probability Lighting will be Reset When Needed in Manual Stepped Control
+    Zone 1 Reference Point1,  !- Glare Calculation Daylighting Reference Point Name
+    180,                     !- Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis {deg}
+    20,                      !- Maximum Allowable Discomfort Glare Index
+    ,                        !- DElight Gridding Resolution {m2}
+    Zone 1 Reference Point1,  !- Daylighting Reference Point 1 Name
+    1.0000,                  !- Fraction of Lights Controlled by Reference Point 1
+    400.0000;                !- Illuminance Setpoint at Reference Point 1 {lux}
+
+  Daylighting:ReferencePoint,
+    Zone 1 Reference Point1,  !- Name
+    Zone 1,                  !- Zone or Space Name
+    15.0,                    !- X-Coordinate of Reference Point {m}
+    3.0,                     !- Y-Coordinate of Reference Point {m}
+    0.7;                     !- Z-Coordinate of Reference Point {m}
+
+  Output:IlluminanceMap,
+    Zone 1 Daylit Map,       !- Name
+    Zone 1,                  !- Zone Name
+    0.8,                     !- Z height {m}
+    3.9,                     !- X Minimum Coordinate {m}
+    26.6,                     !- X Maximum Coordinate {m}
+    5,                       !- Number of X Grid Points
+    0.2,                     !- Y Minimum Coordinate {m}
+    3.5,                    !- Y Maximum Coordinate {m}
+    5;                      !- Number of Y Grid Points
+
   ElectricEquipment,
     All Spaces Elec Equip,   !- Name
     AllConditionedSpaces,    !- Zone or ZoneList or Space or SpaceList Name
@@ -1307,9 +1344,45 @@
     0.2,                     !- Return Air Fraction
     0.59,                    !- Fraction Radiant
     0.2,                     !- Fraction Visible
-    0,                       !- Fraction Replaceable
+    1.0,                     !- Fraction Replaceable
     GeneralLights;           !- End-Use Subcategory
 
+  Daylighting:Controls,
+    Space 3 Open Office 1 Daylighting Control,  !- Name
+    Space 3 Open Office 1,   !- Zone or Space Name
+    SplitFlux,               !- Daylighting Method
+    ,                        !- Availability Schedule Name
+    Stepped,                 !- Lighting Control Type
+    0.3000,                  !- Minimum Input Power Fraction for Continuous or ContinuousOff Dimming Control
+    0.2000,                  !- Minimum Light Output Fraction for Continuous or ContinuousOff Dimming Control
+    3,                       !- Number of Stepped Control Steps
+    1.0000,                  !- Probability Lighting will be Reset When Needed in Manual Stepped Control
+    Space 3 Open Office 1 Reference Point1,  !- Glare Calculation Daylighting Reference Point Name
+    180,                     !- Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis {deg}
+    20,                      !- Maximum Allowable Discomfort Glare Index
+    ,                        !- DElight Gridding Resolution {m2}
+    Space 3 Open Office 1 Reference Point1,  !- Daylighting Reference Point 1 Name
+    1.0000,                  !- Fraction of Lights Controlled by Reference Point 1
+    400.0000;                !- Illuminance Setpoint at Reference Point 1 {lux}
+
+  Daylighting:ReferencePoint,
+    Space 3 Open Office 1 Reference Point1,  !- Name
+    Space 3 Open Office 1,   !- Zone or Space Name
+    8.0,                     !- X-Coordinate of Reference Point {m}
+    12.5,                    !- Y-Coordinate of Reference Point {m}
+    0.7;                     !- Z-Coordinate of Reference Point {m}
+
+  Output:IlluminanceMap,
+    Space 3 Open Office 1 Daylit Map,  !- Name
+    Space 3 Open Office 1,   !- Zone or Space Name
+    0.8,                     !- Z height {m}
+    3.8,                     !- X Minimum Coordinate {m}
+    11.8,                     !- X Maximum Coordinate {m}
+    5,                       !- Number of X Grid Points
+    11.8,                     !- Y Minimum Coordinate {m}
+    15.0,                    !- Y Maximum Coordinate {m}
+    10;                      !- Number of Y Grid Points
+
   Lights,
     Space 3 Open Office 2 Lights,  !- Name
     Space 3 Open Office 2,   !- Zone or ZoneList or Space or SpaceList Name
@@ -1338,6 +1411,31 @@
     0,                       !- Fraction Replaceable
     GeneralLights;           !- End-Use Subcategory
 
+  Construction,
+    Furniture,               !- Name
+    WD10;                    !- Outside Layer
+
+  InternalMass,
+    Zone 3 Furniture,        !- Name
+    Furniture,               !- Construction Name
+    Zone 3,                  !- Zone or ZoneList Name
+    ,                        !- Space or SpaceList Name
+    77;                      !- Surface Area {m2}
+
+  InternalMass,
+    Misc Furniture,          !- Name
+    Furniture,               !- Construction Name
+    ,                        !- Zone or ZoneList Name
+    AllConditionedSpaces,    !- Space or SpaceList Name
+    5.0;                     !- Surface Area {m2}
+
+  InternalMass,
+    Misc Furniture 2,          !- Name
+    Furniture,               !- Construction Name
+    All Zones,               !- Zone or ZoneList Name
+    ,                        !- Space or SpaceList Name
+    2.0;                     !- Surface Area {m2}
+
   BuildingSurface:Detailed,
     BACK-1,                  !- Name
     WALL,                    !- Surface Type
@@ -1898,6 +1996,20 @@
     0,                       !- Fraction Replaceable
     GeneralLights;           !- End-Use Subcategory
 
+  InternalMass,
+    Space 5 Office Furniture,  !- Name
+    Furniture,               !- Construction Name
+    ,                        !- Zone or ZoneList Name
+    Space 5 Office,          !- Space or SpaceList Name
+    10.0;                    !- Surface Area {m2}
+
+  InternalMass,
+    Space 5 Conference Furniture,  !- Name
+    Furniture,               !- Construction Name
+    ,                        !- Zone or ZoneList Name
+    Space 5 Conference,      !- Space or SpaceList Name
+    5.0;                     !- Surface Area {m2}
+
   BuildingSurface:Detailed,
     C5-1,                    !- Name
     CEILING,                 !- Surface Type
```

**Review by jmarrec — APPROVED** [review]
Looks good to me!

File: src/EnergyPlus/DaylightingManager.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/DaylightingManager.cc]: > The way you ordered the if-else ladder seem to imply it would be more common now to use a Space Name rather than a Zone Name. Is that so?

Good question. I didn't pay much attention to this.
For `Daylighting:Controls` space is checked first.
For `Daylighting:ReferencePoint` zone is first.
For `Output:IlluminanceMap` space is first.
For internal gains (`Lights`, `People`, etc.) it is zone, then space, then zonelist, then spacelist.

I will change `Daylighting:Controls` and  `Output:IlluminanceMap` to check zone first, then space. That will be consistent with the order in the field name.

File: src/EnergyPlus/DaylightingManager.cc [hunk 8]
```diff
@@ -4381,59 +4394,60 @@ void GetDaylightingControls(EnergyPlusData &state, bool &ErrorsFound)
...
-            if (spaceHasDaylightingControl(spaceNum)) {
-                ShowSevereError(state,
-                                format("{}=\"{}\" Space==\"{}\" already has a {} object assigned to it. Only one per Space is allowed.",
-                                       ipsc->cCurrentModuleObject,
-                                       daylightControl.Name,
-                                       state.dataHeatBal->space(spaceNum).Name,
-                                       ipsc->cCurrentModuleObject));
-                ErrorsFound = true;
-                continue;
+        // Is it a zone or space name?
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc:4397]: Reverse the order for consistency with other objects, check for zone name match first, then space name.

File: src/EnergyPlus/DaylightingManager.cc [hunk 9]
```diff
@@ -4381,59 +4394,60 @@ void GetDaylightingControls(EnergyPlusData &state, bool &ErrorsFound)
...
+                if (spaceHasDaylightingControl(zoneSpaceNum)) {
+                    ShowWarningError(state,
+                                     format("{}=\"{}\" Space=\"{}\" already has a {} object assigned to it.",
+                                            ipsc->cCurrentModuleObject,
+                                            daylightControl.Name,
+                                            state.dataHeatBal->space(zoneSpaceNum).Name,
+                                            ipsc->cCurrentModuleObject));
+                    ShowContinueError(state, "This control will override the lighting power factor for this space.");
+                }
+                spaceHasDaylightingControl(zoneSpaceNum) = true;
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc:4428]: This check wasn't working at all before. Fixed the logic and changed to a warning.

File: src/EnergyPlus/DaylightingManager.cc [hunk 10]
```diff
@@ -4381,59 +4394,60 @@ void GetDaylightingControls(EnergyPlusData &state, bool &ErrorsFound)
...
+                if (spaceHasDaylightingControl(spaceNum)) {
+                    ShowWarningError(state,
+                                     format("{}=\"{}\" Space=\"{}\" already has a {} object assigned to it.",
+                                            ipsc->cCurrentModuleObject,
+                                            daylightControl.Name,
+                                            state.dataHeatBal->space(spaceNum).Name,
+                                            ipsc->cCurrentModuleObject));
+                    ShowContinueError(state, "This control will override the lighting power factor for this space.");
                 }
+                spaceHasDaylightingControl(spaceNum) = true;
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc:4450]: Same here. `spaceHasDaylightingControl` was never set to true before.

**Comment by Myoldmopar** [comment]
This really does seem fine and a minor IO change that would be good to drop in now.  Locally it's still all happy, so let's merge this.  Thanks @mjwitte
