### PR TITLE
9157 9191 simulation control adjustments

### LINKED ISSUE #9157: Confusing ERR log when no weather file provided
Issue overview
--------------
If you run EnergyPlus without a weather file, you can get output like this in the err file:

```
Program Version,EnergyPlus, Version 9.6.0-f420c06a69, YMD=2021.10.28 13:21,
   ** Warning ** Timestep: Requested number (1) is less than the suggested minimum of 4.
   **   ~~~   ** Please see entry for Timestep in Input/Output Reference for discussion of considerations.
   ** Warning ** CheckEnvironmentSpecifications: SimulationControl specified doing weather simulations; run periods for weather file specified; but no weather file specified.
   ** Warning ** Weather Environment(s) requested, but no weather file found
   ** Warning ** Output:Meter: invalid Key Name="ELECTRICITY:FACILITY" - not found.
   ** Warning ** Output:Meter: invalid Key Name="NATURALGAS:FACILITY" - not found.
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ** Severe  ** AirLoopHVAC:ZoneSplitter="CENTRAL AC AND FURNACE ZONE SPLITTER", not found on any AirLoopHVAC:SupplyPath.
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ** Severe  ** For AirLoopHVAC:ReturnPlenum = AIR LOOP HVAC RETURN PLENUM 1, Zone Name = CENTRAL AC AND FURNACE AIRLOOP RET AIR ZONE not found.
   **  Fatal  ** GetZonePlenumInput: Errors found in input.  Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=2
   ..... Last severe error=For AirLoopHVAC:ReturnPlenum = AIR LOOP HVAC RETURN PLENUM 1, Zone Name = CENTRAL AC AND FURNACE AIRLOOP RET AIR ZONE not found.
   ************* Fatal error -- final processing.  More error messages may appear.
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ** Severe  ** AirLoopHVAC:ZoneSplitter="CENTRAL AC AND FURNACE ZONE SPLITTER", not found on any AirLoopHVAC:SupplyPath.
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ** Severe  ** AirLoopHVAC:ReturnPlenum="AIR LOOP HVAC RETURN PLENUM 1", not found on any AirLoopHVAC:ReturnPath.
   ** Severe  ** AirLoopHVAC:ZoneMixer="CENTRAL AC AND FURNACE ZONE MIXER", not found on any AirLoopHVAC:ReturnPath, AirTerminal:SingleDuct:SeriesPIU:Reheat,
   **   ~~~   ** AirTerminal:SingleDuct:ParallelPIU:Reheat or AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction.
   ************* All Return Air Paths passed integrity testing
   ** Severe  ** Node Connection Error, Node="NODE 3", Inlet node did not find an appropriate matching "outlet" node.
   **   ~~~   ** If this is an outdoor air inlet node, it must be listed in an OutdoorAir:Node or OutdoorAir:NodeList object.
   **   ~~~   ** Reference Object=BRANCH, Name=CENTRAL AC AND FURNACE AIRLOOP MAIN BRANCH
   ** Severe  ** Node Connection Error, Node="NODE 10", Inlet node did not find an appropriate matching "outlet" node.
   **   ~~~   ** If this is an outdoor air inlet node, it must be listed in an OutdoorAir:Node or OutdoorAir:NodeList object.
   **   ~~~   ** Reference Object=BRANCH, Name=DHW LOOP SUPPLY INLET BRANCH
<many additional severe errors truncated>
```

While the root cause of the error message is available (`   ** Warning ** Weather Environment(s) requested, but no weather file found`), it can be hidden amongst many other warning messages and the user assumes that the severe errors (node connections, zone names, etc. in this case) are the cause of the issue. This results in wasted time looking at false positives. Note that when the weather file is properly provided, there are no severe errors, so it's especially confusing why a missing weather file causes these severe errors.

**Proposal**: Change the warning above to a severe error, such that the simulation terminates at this point with no other severe errors reported.

IDF/ERR files:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/7436853/in.idf.txt)
[eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/7436855/eplusout.err.txt)

### Details
Some additional details for this issue (if relevant):
 - Ubuntu 20.04
 - EnergyPlus v9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9191: Simulation crashes if no simulation is specified in SimulationControl.
Issue overview
--------------
Users may speed up reporting of sizing data by changing, in this example, Run Simulation for Weather File Run Periods = No, however the simulation will crash. It seems sizing information should be reported and the simulation should exit gracefully.

Test file was 5ZoneAirCooled_VRPSizing but crash will likely occur with many other example files.

  SimulationControl,
    Yes,                     !- Do Zone Sizing Calculation
    Yes,                     !- Do System Sizing Calculation
    Yes,                     !- Do Plant Sizing Calculation
    No,                      !- Run Simulation for Sizing Periods
    Yes,                     !- Run Simulation for Weather File Run Periods
    No,                      !- Do HVAC Sizing Simulation for Sizing Periods
    1;                       !- Maximum Number of HVAC Sizing Simulation Passes

Workaround: Perrform at leaset 1 of the 3 types of simulation.

If no simulations are performed the DoOutputReporting is never set true and several arrays are not allocated.

        if (state.dataGlobal->DoDesDaySim || state.dataGlobal->DoWeathSim || state.dataGlobal->DoHVACSizingSimulation) {
            state.dataGlobal->DoOutputReporting = true;
        }

Which later causes an attempt to access an unallocated Array1D.

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9157 
 - Fixes #9191 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SimulationManager.cc [hunk 1]
```diff
@@ -1609,16 +1609,15 @@ namespace SimulationManager {
                                  "file specified; but no weather file specified.");
             }
         }
-        if (!state.dataGlobal->DoDesDaySim && !state.dataGlobal->DoWeathSim) {
+
+        if (!state.dataGlobal->DoDesDaySim && !state.dataGlobal->DoWeathSim && !state.dataGlobal->DoHVACSizingSimulation) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/SimulationManager.cc]: This change seems reasonable, we just need to exit if we aren't doing _anything_.  I feel I should ping @EnergyArchmage for a quick thumbs up or down...

File: src/EnergyPlus/WeatherManager.cc [hunk 2]
```diff
@@ -5011,7 +5011,8 @@ namespace WeatherManager {
         if (!state.dataWeatherManager->WeatherFileExists) { // No weather file exists but the user requested one--print error message
 
             if (state.dataGlobal->DoWeathSim) {
-                ShowWarningError(state, "Weather Environment(s) requested, but no weather file found");
+                ShowSevereError(state, "GetNextEnvironment: Weather Environment(s) requested, but no weather file found");
+                ShowFatalError(state, "Due to previous error condition, simulation terminated");
```
Comment (Myoldmopar) [inline src/EnergyPlus/WeatherManager.cc:5012]: Yes, nicer.

File: tst/EnergyPlus/unit/WeatherManager.unit.cc [hunk 3]
```diff
@@ -1794,3 +1794,125 @@ TEST_F(EnergyPlusFixture, WeatherManager_SetRainFlag)
     WeatherManager::SetCurrentWeather(*state);
     ASSERT_FALSE(state->dataEnvrn->IsRain);
 }
+
+TEST_F(EnergyPlusFixture, WeatherRunPeriod_WeatherFile_OK)
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/WeatherManager.unit.cc:1798]: Tests are great.

**Review by Myoldmopar — APPROVED** [review]
No issues here, this is great.  If @EnergyArchmage has any comments on the hvac sizing condition on the error, that would be great, but otherwise I think this is good from a code review standpoint.

**Comment by Myoldmopar** [comment]
But we need Clang Format on the unit tests fixed up.  I can do that if there aren't any other changes required.

File: src/EnergyPlus/SimulationManager.cc (hunk 1 above)
Comment (EnergyArchmage) [reply src/EnergyPlus/SimulationManager.cc]: Well, I believe the issue 9191 is more than just fataling gracefully. What is desired is to be able to run just ideal loads sizing calcs with no full simulation of design days or run periods. And get component loads and equipment sizing results. It is big performance issue. 

I happen to also have been working on this just today and have it working. If you are interested in a more expansive interpretation of 9191 I will check if I can share.

Comment (Myoldmopar) [reply src/EnergyPlus/SimulationManager.cc]: I think it would be valuable if you are able to share it.  Mostly from a perspective of you not having to manage conflicting changes.  If you aren't able to share, I'd be happy to massage our changes to maximize their value in addressing 9191 and reducing the burden on your fork.  Let me know when you find out so we can proceed either way, and thanks!

**Comment by jmarrec** [comment]
@Myoldmopar I had missed this, sorry. I just merged develop in and clang formatted the unit test

**Comment by EnergyArchmage** [comment]
@jmarrec are you interested in picking up #9402 and combine with this?

**Comment by jmarrec** [comment]
@EnergyArchmage I apologize for the delay. I'm trying to reconcile both right now

**Comment by nrel-bot-2c** [comment]
@jmarrec @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
I was hoping that #9402 would be able to drop in to help reconcile what to do here, but that one is being held up by some unit test failures.  I suppose this will just hang out as well.

**Comment by Myoldmopar** [comment]
@jmarrec with the #9402 PR merged, could you reconcile any changes with this branch so we can get this pushed along as well?  Thanks!

File: src/EnergyPlus/SimulationManager.cc [hunk 4]
```diff
@@ -1516,15 +1516,17 @@ namespace SimulationManager {
...
-            ErrorsFound = true;
+            // This amounts to checking: (!DoHVACSizingSimulation && !DoZoneSizing && !DoSystemSizing)
+            if (!state.dataGlobal->DoHVACSizingSimulation && !state.dataGlobal->DoPureLoadCalc) {
+                ShowSevereError(state, "All elements of SimulationControl are set to \"No\". No simulations can be done. Program terminates.");
+                ErrorsFound = true;
+            } else {
+                ShowWarningError(state,
+                                 "\"Run Simulation for Sizing Periods\" and \"Run Simulation for Weather File Run Periods\" are both set to \"No\". "
+                                 "No simulations will be performed, and most input will not be read.");
+            }
```
Comment (Myoldmopar) [inline src/EnergyPlus/SimulationManager.cc:1529]: This logic seems fine to me.

File: src/EnergyPlus/WeatherManager.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WeatherManager.cc:5012]: Still nicer.

File: tst/EnergyPlus/unit/WeatherManager.unit.cc (hunk 3 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/WeatherManager.unit.cc:1798]: Tests are still great.

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
This seems like a great fix for the ERR file output when a weather file is not present.  Assuming CI finishes clean, I'll merge this.

**Comment by Myoldmopar** [comment]
Pulled and tested locally all good.  Verified that with develop, if you simply execute `./energyplus /path/to/9157.idf`, you get a bunch of nonsense in the ERR file.  With this branch, it's nice and concise.  

(As an aside, if I run `./energyplus -D /path/to/9157.idf`, even with develop, it gives a minimal good error report, but this is a fine fix for the general case.)

Merging this one, thanks @jmarrec
