### PR TITLE
Fixes failed unit tests when no cooling design day

### LINKED ISSUE #9952: Output Report - System Sizing Information Time of Peak Cooling and User Design Capacity In IP Units are Wrong
Issue overview
--------------
In the output report, the System Sizing Information, Peak Load User Design Capacity is wrong.  I am unable to find these values anywhere else in the report.

### Details
Some additional details for this issue (if relevant):
 - Windows 11 Pro
 - EnergyPlus, Version 22.2.0-aa78da9668
 - [Unmethours link or helpdesk ticket number](https://unmethours.com/question/85350/why-is-autosizing-leading-to-undersized-system/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([UnmetHours_32FMixedAirTemp_in.idf.zip](https://github.com/NREL/EnergyPlus/files/11223558/UnmetHours_32FMixedAirTemp_in.idf.zip))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9952 (IF THIS IS A DEFECT)
 - This fix is a followup to PR 9967
 - Addresses failed unit tests in debug mode due to the original fix.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Thanks @Nigusse, I'll let Decent do the work here and assuming those debug tests are passing now, I'll merge.

**Comment by Nigusse** [comment]
I tested the fix in debug and release mode, and all passed.

File: src/EnergyPlus/SizingManager.cc [hunk 1]
```diff
@@ -807,7 +807,7 @@ void ManageSizing(EnergyPlusData &state)
                 coolPeakDDDate = SysSizPeakDDNum(AirLoopNum).cTotCoolPeakDDDate;
                 coolPeakDD = SysSizPeakDDNum(AirLoopNum).TotCoolPeakDD;
                 coolCap = FinalSysSizing(AirLoopNum).TotCoolCap;
-                timeStepIndexAtPeakCoolLoad = SysSizPeakDDNum(AirLoopNum).TimeStepAtTotCoolPk(coolPeakDD);
+                if (coolPeakDD > 0) timeStepIndexAtPeakCoolLoad = SysSizPeakDDNum(AirLoopNum).TimeStepAtTotCoolPk(coolPeakDD);
```
Comment (rraustad) [inline src/EnergyPlus/SizingManager.cc:810]: Since it is possible that a user could provide only a heating SizingPeriod:DesignDay when doing a sizing simulation then this does seem like a reasonable correction.

Comment (mjwitte) [reply src/EnergyPlus/SizingManager.cc:810]: Is there similar protection elsewhere `if (heatPeakDD > 0)`?

Comment (rraustad) [reply src/EnergyPlus/SizingManager.cc:810]: I was thinking we should create a unit test (separate PR) with only a precool coil in the OA system and only a summer design day and see what happens. This change for issue #9952 was needed because you can size systems on total or sensible loads and heating only sizes on sensible. 

            int heatPeakDD = SysSizPeakDDNum(AirLoopNum).HeatPeakDD;
            if (heatPeakDD > 0) {

This same thing happens for cooling except you need to choose between total and sensible capacity before you get to that point.

            if (FinalSysSizing(AirLoopNum).coolingPeakLoad == DataSizing::PeakLoad::SensibleCooling) {
                coolPeakLoadKind = "Sensible";
                coolPeakDDDate = SysSizPeakDDNum(AirLoopNum).cSensCoolPeakDDDate;
                coolPeakDD = SysSizPeakDDNum(AirLoopNum).SensCoolPeakDD;
                coolCap = FinalSysSizing(AirLoopNum).SensCoolCap;
                timeStepIndexAtPeakCoolLoad = SysSizPeakDDNum(AirLoopNum).TimeStepAtSensCoolPk(coolPeakDD);
            } else if (FinalSysSizing(AirLoopNum).coolingPeakLoad == DataSizing::PeakLoad::TotalCooling) {
                if (FinalSysSizing(AirLoopNum).loadSizingType == DataSizing::LoadSizing::Latent && state.dataHeatBal->DoLatentSizing) {
                    coolPeakLoadKind = "Total Based on Latent";
                } else {
                    coolPeakLoadKind = "Total";
                }
                coolPeakDDDate = SysSizPeakDDNum(AirLoopNum).cTotCoolPeakDDDate;
                coolPeakDD = SysSizPeakDDNum(AirLoopNum).TotCoolPeakDD;
                coolCap = FinalSysSizing(AirLoopNum).TotCoolCap;
                timeStepIndexAtPeakCoolLoad = SysSizPeakDDNum(AirLoopNum).TimeStepAtTotCoolPk(coolPeakDD);
            }
            if (coolPeakDD > 0) {


But that doesn't mean heating is protected elsewhere from user inputs that don't include a heating design day. I would assume that has been tested before but can't be sure.

Comment (Nigusse) [reply src/EnergyPlus/SizingManager.cc:810]: Yes. Since the sensible and total are the same for heating, everything is wrapped within `if (heatPeakDD > 0)` statement.

**Comment by Myoldmopar** [comment]
CI is much much happier now.  Any reason to hold this up @rraustad @mjwitte ?  I'm open to further work on this, but if we can clean up the develop branch with this fix, that would make me breath a little easier.

**Comment by mjwitte** [comment]
> CI is much much happier now. Any reason to hold this up @rraustad @mjwitte ? I'm open to further work on this, but if we can clean up the develop branch with this fix, that would make me breath a little easier.

No objections here.

**Comment by Myoldmopar** [comment]
> No objections here.

Thanks, merging.  And thanks @rraustad  and @Nigusse .
