### PR TITLE
Fix Meter:Custom with mix of valid and invalid names

### LINKED ISSUE #10771: 'Invalid Output Variable or Meter Name' in Meter:Custom results in no meter output
Issue overview
--------------
In 23.1, a Meter:Custom with a mix of valid and invalid meter names would report the results from just the valid meters. In 24.1, no output for the custom meter is reported.

I added the following to the 5ZoneAirCooled.idf example file from both 23.1 and 24.1:
```
  Output:Meter,Cooling:Electricity,Timestep;
  Output:Meter,HeatRejection:Electricity,Timestep;
  Output:Meter,CoolingHVAC:Electricity,Timestep;
  Meter:Custom,
    CoolingHVAC:Electricity,                !- Name
    Electricity,                            !- Resource Type
    ,                                       !- Key Name 1
    Cooling:Electricity,                    !- Output Variable or Meter Name 1
    ,                                       !- Key Name 2
    HeatRejection:Electricity;              !- Output Variable or Meter Name 2
```
That file has no heat rejection equipment so the 'HeatRejection:Electricity' meter is invalid. Indeed both models generate the following warnings: 
```
   ** Warning ** Meter:Custom="COOLINGHVAC:ELECTRICITY", invalid Output Variable or Meter Name="HEATREJECTION:ELECTRICITY".
   **   ~~~   ** ...will not be shown with the Meter results.
   ** Warning ** Output:Meter: invalid Key Name="HEATREJECTION:ELECTRICITY" - not found.
```
In the 23.1 run, the meter output exists for the valid meter names. The 24.1 run, however, does not contain any output for the custom meter.

23.1 output csv:
image
23.1 output sql:
image

24.1 output csv:
image
24.1 output sql:
image

The previous functionality is important for automatically creating custom meters that give meaningful output without prior knowledge of what specific outputs are available (e.g. for stock modeling).

Possibly caused by recent Ouput Processor refactors: https://github.com/NREL/EnergyPlus/pull/10384

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): 24.1
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)
 
[5ZoneAirCooled_23_1.idf.txt](https://github.com/user-attachments/files/17156601/5ZoneAirCooled_23_1.idf.txt)
[5ZoneAirCooled_24_1.idf.txt](https://github.com/user-attachments/files/17156602/5ZoneAirCooled_24_1.idf.txt)

### PR DESCRIPTION
**Pull request by amirroth**
[PR #10384](https://github.com/NREL/EnergyPlus/pull/10384) changed the behavior of `Meter:Custom` so that meter creation fails if one of the component variables or meters is missing. According to [issue #10771](https://github.com/NREL/EnergyPlus/issues/10771), the desired behavior is to create the custom meter but ignore the missing component variable or meter. This behavior was restored.

### CODE REVIEW

File: src/EnergyPlus/OutputProcessor.cc [hunk 1]
```diff
@@ -803,7 +803,7 @@ namespace OutputProcessor {
 
                     // Has to be a summed variable
                     if (srcDDVar->storeType != StoreType::Sum) {
-                        ShowWarningCustomMessage(state,
+                        ShowWarningCustomMessage(state, // Is clang-format formatting things like this? This is gross.
```
Comment (amirroth) [inline src/EnergyPlus/OutputProcessor.cc:806]: Seriously, clang-format is not worth it if this is the result.

File: src/EnergyPlus/OutputProcessor.cc [hunk 2]
```diff
@@ -867,8 +867,7 @@ namespace OutputProcessor {
                                             ipsc->cAlphaFieldNames(fldIndex + 1),
                                             ipsc->cAlphaArgs(fldIndex + 1)));
                     ShowContinueError(state, "...will not be shown with the Meter results.");
-                    foundBadSrc = true;
```
Comment (amirroth) [inline src/EnergyPlus/OutputProcessor.cc:870]: One line fix. A missing component variable/meter no longer sets an error condition that prevents the custom meter from being created.

**Review by mjwitte — APPROVED** [review]
Tested with the defect file and with mismatched units. Works as advertised. 
Thanks @amirroth and @eringold!

**Comment by amirroth** [comment]
@mjwitte, you've already fixed one of my bugs. You shouldn't have to fix all of them.

File: src/EnergyPlus/OutputProcessor.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/OutputProcessor.cc:870]: Looks good to me!

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Test fine with latest develop pulled in, going in.  Thanks @amirroth
