### PR TITLE
Fix scheduled Output:Variable bug with JSON outputs

### LINKED ISSUE #7907: ResultsFramework exception when Output:Variable is scheduled
Issue overview
--------------
When an Output:Variable uses a Schedule, it causes an exception in the ResultsFramework. The framework currently expects all variables to have the same number of timeseries values, however, when there is a schedule on an Output:Variable it has fewer timeseries values. [This assumption causes the exception here](https://github.com/NREL/EnergyPlus/blob/be5b67255957ed53c59d16306878482e3b8634ad/src/EnergyPlus/ResultsSchema.cc#L439).

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mbadams5**
Pull request overview
---------------------
 - Fixes #7907 

This PR adds a new integration test, which now outputs JSON causing an exception in develop. So this PR now outputs `null` when there is a blank field due to scheduled Output:Variables.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ResultsSchema.cc [hunk 1]
```diff
@@ -436,7 +435,11 @@ namespace ResultsFramework {
             vals.clear();
 
             for (auto const &varMap : variableMap) {
-                vals.push_back(varMap.second.value(row));
+                if (row < varMap.second.numValues()) {
+                    vals.push_back(varMap.second.value(row));
+                } else {
+                    vals.push_back(nullptr);
```
Comment (Myoldmopar) [inline src/EnergyPlus/ResultsSchema.cc:441]: Makes good sense.

**Review by Myoldmopar — APPROVED** [review]
Having null come out instead of an exception is a move in the right direction.  Code changes look good.
