### PR TITLE
Fan:SystemModel with discrete speed flow fractions crashes when speeds >= 2

### LINKED ISSUE #10845: EnergyPlus Crashes with Fan:SystemModel with Discrete speeds
Issue overview
--------------
Please see https://unmethours.com/question/100609/how-to-implement-fansystemmodel-with-discrete-speeds/

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) Windows 11
 - Version of EnergyPlus (if using an intermediate build, include SHA)  24.2
 - Unmethours link or helpdesk ticket number https://unmethours.com/question/100609/how-to-implement-fansystemmodel-with-discrete-speeds/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (https://www.dropbox.com/t/mZ59GtQHkCVlT7E5) ([10845-in.idf.txt](https://github.com/user-attachments/files/18378578/10845-in.idf.txt))
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### Workaround:

 Autosizing cooling and heating air flow rate inputs mayy avoid this crash.

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #10845
 - Fan:SystemModel with multispeed flow fractions crashes when speeds >= 2 because fan has not sized yet.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 1]
```diff
@@ -4380,21 +4380,11 @@ void GetVRFInputData(EnergyPlusData &state, bool &ErrorsFound)
                             vrfTU.NumOfSpeedCooling = fanSystem->numSpeeds;
                             vrfTU.CoolVolumeFlowRate.resize(fanSystem->numSpeeds + 1);
                             vrfTU.CoolMassFlowRate.resize(fanSystem->numSpeeds + 1);
-                            if (vrfTU.MaxCoolAirVolFlow != DataSizing::AutoSize) {
-                                for (int i = 1; i <= vrfTU.NumOfSpeedCooling; ++i) {
-                                    vrfTU.CoolMassFlowRate[i] = fanSystem->massFlowAtSpeed[i - 1];
-                                }
-                            }
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:4382]: Crashes in these places in VRF GetInput because massFlowAtSpeed is allocated in the fan's set_size function and that has not been called yet.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 2]
```diff
@@ -6421,8 +6411,32 @@ void InitVRF(EnergyPlusData &state, int const VRFTUNum, int const ZoneNum, bool
...
+                                if (vrfTU.DXHeatCoilType_Num == HVAC::CoilVRF_Heating) {
+                                    if (vrfTU.MaxHeatAirVolFlow != DataSizing::AutoSize) {
+                                        for (int i = 1; i <= vrfTU.NumOfSpeedCooling; ++i) {
+                                            vrfTU.HeatMassFlowRate[i] = fanSystem->massFlowAtSpeed[i - 1];
+                                        }
+                                    }
+                                }
+                            }
+                        }
+                    }
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:6420]: So moved these initializations to Init where the code waits for the fan to size before setting up air flow variables.

File: tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc [hunk 3]
```diff
@@ -24377,10 +24377,11 @@ TEST_F(EnergyPlusFixture, VRF_MultispeedFan_Test)
     InitVRF(*state, VRFTUNum, ZoneNum, FirstHVACIteration, OnOffAirFlowRatio, QZnReq);
     EXPECT_EQ(QZnReq, -3000.0);
     SimVRF(*state, VRFTUNum, FirstHVACIteration, OnOffAirFlowRatio, SysOutputProvided, LatOutputProvided, QZnReq);
-    EXPECT_NEAR(state->dataLoopNodes->Node(state->dataHVACVarRefFlow->VRFTU[0].VRFTUOutletNodeNum).MassFlowRate, 0.29937661, 0.0001);
+    EXPECT_NEAR(
+        state->dataLoopNodes->Node(state->dataHVACVarRefFlow->VRFTU[0].VRFTUOutletNodeNum).MassFlowRate, 0.300008959, 0.0001); // was 0.29937661
     EXPECT_LT(abs(QZnReq - SysOutputProvided), 1.0);
     EXPECT_EQ(state->dataHVACVarRefFlow->VRFTU[0].SpeedNum, 2);
-    EXPECT_NEAR(state->dataHVACVarRefFlow->VRFTU[0].SpeedRatio, 0.7252535, 0.00001);
+    EXPECT_NEAR(state->dataHVACVarRefFlow->VRFTU[0].SpeedRatio, 0.7288976, 0.00001); // was 0.7252535
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc:24384]: Why would these answers change ?

File: tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc [hunk 4]
```diff
@@ -24431,7 +24432,1322 @@ TEST_F(EnergyPlusFixture, VRF_MultispeedFan_Test)
     EXPECT_LT(abs(QZnReq - SysOutputProvided), 1.0);
     EXPECT_EQ(state->dataHVACVarRefFlow->VRFTU[0].SpeedNum, 1);
     EXPECT_NEAR(state->dataHVACVarRefFlow->VRFTU[0].SpeedRatio, 0.0, 0.00001);
-    EXPECT_NEAR(state->dataHVACVarRefFlow->VRFTU[0].CycRatio, 0.713222413, 0.00001);
+    EXPECT_NEAR(state->dataHVACVarRefFlow->VRFTU[0].CycRatio, 0.713204045, 0.00001); // was 0.713222413
+}
+
+TEST_F(EnergyPlusFixture, VRF_MultispeedFan_Test_HardSized)
```
Comment (rraustad) [inline tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc:24438]: New unit test with hard-sized inputs for airflow, capacity and SHR that are duplicate of results from above unit test. These answers are a little different then when using autosize.

**Comment by rraustad** [comment]
A clue to the diffs on Mac CI for VRFMultispeedFan. TU2 fan is the only multispeed fan of the 5 TUs in this example file. No Cooling SA Flow Rate changed while No Heating SA Flow Rate did not. @Myoldmopar why is Mac CI picking up diffs while the other CIs do not?

    - Component Sizing Information, ZoneHVAC:TerminalUnit:VariableRefrigerantFlow, TU2, Design Size No Cooling Supply Air Flow Rate [m3/s], 0.21531
    + Component Sizing Information, ZoneHVAC:TerminalUnit:VariableRefrigerantFlow, TU2, Design Size No Cooling Supply Air Flow Rate [m3/s], 0.00000
      Component Sizing Information, ZoneHVAC:TerminalUnit:VariableRefrigerantFlow, TU2, Design Size No Heating Supply Air Flow Rate [m3/s], 0.21531

**Comment by mjwitte** [comment]
> A clue to the diffs on Mac CI for VRFMultispeedFan. TU2 fan is the only multispeed fan of the 5 TUs in this example file. No Cooling SA Flow Rate changed while No Heating SA Flow Rate did not. @Myoldmopar why is Mac CI picking up diffs while the other CIs do not?

Mac is the only one running regressions now.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 5]
```diff
@@ -7728,7 +7741,7 @@ void SizeVRF(EnergyPlusData &state, int const VRFTUNum)
                 } else {
                     auto *fanSystem = dynamic_cast<Fans::FanSystem *>(state.dataFans->fans(state.dataHVACVarRefFlow->VRFTU(VRFTUNum).FanIndex));
                     assert(fanSystem != nullptr);
-                    if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).CoolMassFlowRate[i] == 0.0) {
+                    if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).CoolMassFlowRate[i] == 0.0 && !fanSystem->massFlowAtSpeed.empty()) {
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:7725]: Just in case the fan has not yet been sized.

**Comment by nrel-bot-2** [comment]
@rraustad it has been 15 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@rraustad it has been 7 days since this pull request was last updated.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 5 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:7725]: Interesting.  Is that something that actually could happen for a normal IDF run?  Or is this just to proof it against missing inits in unit tests?

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:4382]: :+1:

**Review by Myoldmopar — APPROVED** [review]
This is fine as is.  I'm curious about the empty checks, but they aren't causing trouble.  I'll give this a quick check.

**Comment by Myoldmopar** [comment]
Good to go, thanks @rraustad !

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 5 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:7725]: This was a normal idf run. The massFlowAtSpeed array is not allocated until Fan::set_size is called. Which may not have been called yet at this point in VRF sizing.
