### PR TITLE
Correction of Condenser Load Dispatch Error for Two Speed Evaporative Fluid Coolers

### LINKED ISSUE #7688: Condenser plant load dispatch not working for two-speed evaporative fluid cooler tower
Issue overview
--------------
From user file and code inspection, the two speed evap fluid cooling tower model is not reporting back its max and optimum capacity for use in condenser load dispatch calculations.  

The problems are here
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeFluidCoolers.cc#L982
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeFluidCoolers.cc#L983

the code should be the same as for single speed fluid cooler, e.g.
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeFluidCoolers.cc#L974

If getDesignCapacities returns zero for MaxLoad and OptLoad the load based operation schemes will not work

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #7688 
 - This pull request deals with the correction of a condenser load dispatch error in the EvapFluidCoolerSpecs::getDesignCapacities routine.  The problem was that a bad cut and paste left MaxLoad and OptLoad zero when they should have had some value.  This issue is now fixed using similar code to the single speed unit in this same routine.  A unit test was added to show that the fix is working.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by EnergyArchmage — APPROVED** [review]
looks good.

File: src/EnergyPlus/EvaporativeFluidCoolers.cc [hunk 1]
```diff
@@ -978,9 +978,9 @@ namespace EvaporativeFluidCoolers {
 
             this->InitEvapFluidCooler();
             this->SizeEvapFluidCooler();
-            MinLoad = 0.0; // signifies non-load based model (i.e. forward
-            MaxLoad = 0.0; // heat exhanger model)
-            OptLoad = 0.0;
+            MinLoad = 0.0; // signifies non-load based model (i.e. forward heat exhanger model)
+            MaxLoad = this->HighSpeedStandardDesignCapacity * this->HeatRejectCapNomCapSizingRatio;
+            OptLoad = this->HighSpeedStandardDesignCapacity;
```
Comment (Myoldmopar) [inline src/EnergyPlus/EvaporativeFluidCoolers.cc:983]: Interesting, this has been zero since **at least** the 8.2 version when we came from Fortran.  I guess maybe since the very beginning of this code?  This does seem quite reasonable.

File: tst/EnergyPlus/unit/CMakeLists.txt [hunk 2]
```diff
@@ -70,6 +70,7 @@ set( test_src
   ElectricPowerServiceManager.unit.cc
   EMSManager.unit.cc
   EvaporativeCoolers.unit.cc
+  EvaporativeFluidCoolers.unit.cc
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/CMakeLists.txt:73]: :+1: New unit test files are getting rare these days, this is a good missing piece.

File: tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+
+#include "Fixtures/EnergyPlusFixture.hh"
+
+using namespace EnergyPlus;
+using namespace EnergyPlus::DataEnvironment;
+using namespace EnergyPlus::EvaporativeFluidCoolers;
+
+namespace EnergyPlus {
+
+class EvapFluidCoolersFixture : public EnergyPlusFixture
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc:73]: :sunglasses:

File: tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+    thisEFC.HeatRejectCapNomCapSizingRatio = 2.0;
+    ExpectedMaxLoad = 20902.8677;
+    ExpectedOptLoad = 10451.4338;
+    ExpectedMinLoad = 0.0;
+    
+    // Call the routine to be tested and see if the fix is correct
+    thisEFC.getDesignCapacities(pl, MaxLoad, MinLoad, OptLoad);
+    EXPECT_NEAR(MaxLoad,ExpectedMaxLoad,0.01);
+    EXPECT_NEAR(MinLoad,ExpectedMinLoad,0.01);
+    EXPECT_NEAR(OptLoad,ExpectedOptLoad,0.01);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc:167]: :+1: this is really great.

**Review by Myoldmopar — APPROVED** [review]
I'll build and test locally, but this looks like a really great fix and unit test.  Thanks @RKStrand !

**Comment by RKStrand** [comment]
@Myoldmopar @EnergyArchmage Thanks for the review!  Hope the merging process is as smooth as GitHub seems to suggest it should be.

File: tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc (hunk 3 above)
Comment (RKStrand) [reply tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc:73]: @Myoldmopar Just following what has been done in other unit test files.  Glad it was the right thing to do!

File: src/EnergyPlus/EvaporativeFluidCoolers.cc (hunk 1 above)
Comment (RKStrand) [reply src/EnergyPlus/EvaporativeFluidCoolers.cc:983]: @Myoldmopar Wow--that's interesting...maybe a little scary.  But I'm glad @EnergyArchmage found this and that it got fixed.

**Comment by Myoldmopar** [comment]
Ran new unit test locally and everything is in good shape.  I didn't have a defect file to test with, but the code changes are incredibly clear, and no CI issues related to these changes.  I'm going to merge this one.  Thanks @RKStrand and @EnergyArchmage.
