### PR TITLE
Partial Fix for GetChildrenData Sort Order

### LINKED ISSUE #11064: Sub-Components Not Topologically Sorted in Zone Equipment Component Arrangement Report
### Issue overview

Screenshot from testfile `TableLookups.idf`.

Image

According to the node connections, the sub-component order should be: outdoor-air-mixer, fan, cooling coil, heating coil, sup-heating coil. However, that is not the order displayed. The issue seems to be that the routine that sorts the sub-components topologically only does so when the inlet node of one of the components matches the parent component inlet node. If that is not the case (and it is not here) then the sub-components are listed in the order in which their comp-sets are created.

The fact that there is no sub-component whose inlet node matches the inlet node of the parent component seems like an issue in and of itself and what the solution is. In this particular case, one of the sub-components has an outlet-node that matches the outlet-node of the parent and so maybe matching on only one of the outlet nodes is okay but the routine does not check for this case.

However, if it is not, then a potential fix for this would be to traverse the components in reverse order from 

### Operating System (Multiple choices)

Any

### Operating System Version

Any

### Version of EnergyPlus

25.1.0

### Unmethours link or helpdesk ticket number

N/A

### Defect file

`LookupTables.idf` in the testfiles folder is a short example.

### LINKED ISSUE #11065: issue with example file: LookupTables.idf
### Issue overview

it appears that there is an inconsistency in the geometry for the example file LookupTables.idf

When imported into EP3, the geometry looks like this:

Image

inspection of the IDF file shows the following:

1.  East Zone has a non-zero X-origin
2. North Zone has a non-zero Y-origin
3. surfaces with East and North zones have coordinates would be consistent with a continuous building shape if the zone origins were all 0,0,0

Changing all Zone origins to zero in the file results in this geometry:

Image

For reference, EP3 shows correct geometry for another example file that has non-zero zone origins (ASHRAE901_ApartmentHighRise_STD2019_Denver.idf):

Image

### Operating System (Multiple choices)

Windows

### Operating System Version

Windows 11

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by amirroth**
Pull request overview
---------------------

- Fixes #11064

### Description of the purpose of this PR

Topological sort of child sub-components in a parent component was not functioning when parent component inlet-node did not match the inlet-node of any of the child components. This PR adds a backup case that sorts child components properly when the parent-component outlet-node matches the outlet node of one of the child components.

This is a partial fix because if neither parent inlet-node or outlet-node is matched the child components will be returned and displayed in the order in which they were registered into the CompSets list.
 
### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/BranchNodeConnections.cc [hunk 1]
```diff
@@ -1760,21 +1799,32 @@ void GetChildrenData(EnergyPlusData &state,
...
-                ChildCName.deallocate();
-                ChildInNodeName.deallocate();
-                ChildOutNodeName.deallocate();
-                ChildInNodeNum.deallocate();
-                ChildOutNodeNum.deallocate();
+            } else {
+                // No sub-component is connected to either the parent
+                // component's inlet- or outlet- nodes? Just copy the
+                // sub-components in the order in which they appear in
+                // the CompSets
```
Comment (mjwitte) [inline src/EnergyPlus/BranchNodeConnections.cc:1958]: Hmm, but this should never happen. The problem here is the OA mixer which has 2 inlets but only one entry in `CompSets`. [MixedAir.cc::2012](https://github.com/NREL/EnergyPlus/blob/2baa135f5395a22c25f474a7b2385084ec869252/src/EnergyPlus/MixedAir.cc#L2012-L2013)
```
            BranchNodeConnections::TestCompSet(
                state, CurrentModuleObject, state.dataMixedAir->OAMixer(OutAirNum).Name, AlphArray(3), AlphArray(2), "Air Nodes");
```
This is using "Outdoor Air Stream Node Name" as inlet and "Mixed Air Node Name" as outlet which makes sense when looking at the flow through OA system components, but not so much when it's in a parent unit like a PTHP or FanCoil. Adding another call here will likely break something else in the tangled web of CompSets and node connection checks. It might be possible to let the parent object(s) dictate the connection nodes.

For this case, adding the outlet node check works, because the last child component works here.
@amirroth I can tinker with this if you like. But maybe just take this fix and leave well-enough alone for now.

Comment (amirroth) [reply src/EnergyPlus/BranchNodeConnections.cc:1958]: For the record, I don't know if this fall-thru case where neither input-node or output-node match a child node happens in the wild or not (I guess we can print a warning and see if it shows up in .err). But this was effectively the fall-thru behavior when output-node was not checked so I kept it.

I can't speak to the tangled web of CompSets and will follow whatever recommendations you have.

File: src/EnergyPlus/BranchNodeConnections.cc [hunk 2]
```diff
@@ -1672,86 +1674,123 @@ void GetChildrenData(EnergyPlusData &state,
...
-                            //              Matched=.TRUE.
-                            MatchNodeName = ChildOutNodeName(Loop);
-                            break;
-                        }
-                    }
+
+                for (int Loop = 1; Loop <= NumChildren; ++Loop) {
+                    if (ChildMatched(Loop)) continue;
+                    ++CountNum;
+                    ChildrenCType(CountNum) = ChildCType(Loop);
```
Comment (mjwitte) [inline src/EnergyPlus/BranchNodeConnections.cc:1904]: Spot checked random set of files that were showing diffs. VSHeatPumpWaterHeater with debug build fails here with a vector error, `CountNum=5` but `NumChildren=4`.

Comment (amirroth) [reply src/EnergyPlus/BranchNodeConnections.cc:1904]: Hmmm. Why is this not showing up in the CI report? Or is it and I just don't know where to look?

Comment (amirroth) [reply src/EnergyPlus/BranchNodeConnections.cc:1904]: So this particular case crashes because there is a circularity in the node definitions:

- ParentInNodeName = "HPWHWATERINLETNODE"
- Component 2 "HPWHDXCOILVS", InNode = "HPWHWATERINLETNODE", OutNode = "HPWATEROUTLETNODE"
- Component 4 "HPWHTANK", InNode = "HPWATEROUTLETNODE", OutNode = "HPWHWATERINLETNODE"

The old code dealt with this issue by basically deleting sub-components from the temporary list if they have already been processed such that they could not be found again, and I could do something similar here. I assume this is a valid node configuration ...

Comment (rraustad) [reply src/EnergyPlus/BranchNodeConnections.cc:1904]: Yes, valid, intentional, as designed. The coil water nodes connect directly to the WH tank inlet/outlet nodes.

Comment (mjwitte) [reply src/EnergyPlus/BranchNodeConnections.cc:1904]: > Hmmm. Why is this not showing up in the CI report? Or is it and I just don't know where to look?

It didn't get caught in release builds on gha, and it looks like the linux CI tests are not running today. @Myoldmopar ?
But I'm not 100% certain it would have failed there either.

**Comment by mjwitte** [comment]
That file is fixed (and no longer has diffs along with a few others). I'll try to run a set of all files locally with a full debug build just to be sure this is all good.

**Comment by mjwitte** [comment]
Running debug build locally on all test files, lots of files failing. 5ZoneAirCooledDemandLimiting, Oh, but that's failing in EconomicTariff with subscript error (also in Fault_FoulingEvapCooler_StripMallZoneEvapCooler, so maybe worth looking into these separately) . 

And AirflowWindowsAndBetweenGlassBlinds fails in optical calcs with an unitialized variable. Ok, this will take some time to sort out and fix the failures. Can't tell easily if any are related to this PR or even if they are all tripping on the same thing.

**Comment by amirroth** [comment]
They have nothing to do with this PR. The tariff problem snuck in with #11040 (sorry). Julien has a branch with a fix for it. I think it is called Followup_11040. The other one also sounds familiar, albeit older. How are these not picked up by CI?

File: src/EnergyPlus/BranchNodeConnections.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/BranchNodeConnections.cc:1958]: > For the record, I don't know if this fall-thru case where neither input-node or output-node match a child node happens in the wild or not (I guess we can print a warning and see if it shows up in .err). But this was effectively the fall-thru behavior when output-node was not checked so I kept it.

Let's add a warning.

**Comment by Myoldmopar** [comment]
Alright, pulled in develop, resolved the conflicts, and applied formatting.  I think this should produce some really meaningful CI results now.

File: src/EnergyPlus/BranchNodeConnections.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/BranchNodeConnections.cc:1958]: Do we still need to add a warning here before this merges?

Comment (amirroth) [reply src/EnergyPlus/BranchNodeConnections.cc:1958]: Sorry, I did that locally but didn't pull/merge. Can you add that yourself please? Thanks.

**Comment by nrel-bot-2c** [comment]
@mjwitte @amirroth @myoldmopar it has been 33 days since this pull request was last updated.

**Review by mjwitte — APPROVED** [review]
@Myoldmopar @amirroth Status update:
1. Let's skip the warning for the fall-thru case. It would just confuse users and it's safer to leave the fall-thru code in place to cover use cases I haven't thought of.
2. I re-ran the random set of test files that I was using before and everything is fine. With a debug build, there's an unrelated failure but that's for another PR on another day.

@Myoldmopar Ready for your final review.

**Comment by Myoldmopar** [comment]
Thanks @mjwitte, doing a quick final check here now.

**Comment by Myoldmopar** [comment]
All happy here, merging in now.
