### PR TITLE
Fix water to air heat pump are sized to an infinite capacity

### LINKED ISSUE #9805: Water to air heat pump are sized to an infinite capacity
Issue overview
--------------
The defect file shows that the water-to-air coils serving the datacenters are sized to an infinite capacity.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows
 - Version of EnergyPlus: 22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [in.zip](https://github.com/NREL/EnergyPlus/files/10459917/in.zip)
 - [x] Pull request created

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------
 - Fixes #9805 

- Catch division by 0
- Unit test was added to check the fix

The capacity for the WAHP in the defect file are not sized to an infinite capacity anymore:
```
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, DATACENTER_BASEMENT_ZN_6 ZN PSZ-AC DATA CENTER WATER-TO-AIR HP CLG COIL, Design Size Rated Total Cooling Capacity [W], 644079.00801
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, DATACENTER_BASEMENT_ZN_6 ZN PSZ-AC DATA CENTER WATER-TO-AIR HP CLG COIL, Design Size Rated Sensible Cooling Capacity [W], 440549.15504
 Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:EQUATIONFIT, DATACENTER_BASEMENT_ZN_6 ZN PSZ-AC DATA CENTER WATER-TO-AIR HP HTG COIL 1193 CLG KBTU/HR 4.2COPH, Design Size Rated Heating Capacity [W], 609915.58258
```

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc [hunk 1]
```diff
@@ -2000,7 +2000,9 @@ namespace WaterToAirHeatPumpSimple {
 
                                 // adjust for system air flow -- capacity is based on heating design day calcs
                                 // adjust by ratio of system to heating air flow rate and temperature delta across the coil at these different airflow
-                                RatedCapCoolTotalDes *= (RatedAirVolFlowRateDes / HeatingAirVolFlowRateDes) * HeatdTratio;
+                                if (HeatingAirVolFlowRateDes > 0) {
+                                    RatedCapCoolTotalDes *= (RatedAirVolFlowRateDes / HeatingAirVolFlowRateDes) * HeatdTratio;
+                                }
```
Comment (rraustad) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2005]: I ran the defect file and HeatingAirVolFlowRateDes = 0. This change protects against zone and system loads that are zero.

File: tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc [hunk 2]
```diff
@@ -1502,3 +1502,214 @@ TEST_F(EnergyPlusFixture, WaterToAirHeatPumpSimpleTest_SizeHVACWaterToAirRatedCo
...
+    state->dataSize->PlantSizData(1).ExitTemp = 29.4;
+
+    WaterToAirHeatPumpSimple::SizeHVACWaterToAir(*state, 1);
+    WaterToAirHeatPumpSimple::SizeHVACWaterToAir(*state, 2);
+
+    EXPECT_NEAR(state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(2).RatedCapHeatAtRatedCdts /
+                    state->dataWaterToAirHeatPumpSimple->SimpleWatertoAirHP(1).RatedCapCoolAtRatedCdts,
+                1.23,
+                0.00001);
+}
```
Comment (rraustad) [inline tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc:1715]: This is actually a capacity related test:

    // determine adjusted cooling and heating coil capacity
    simpleWatertoAirHP.RatedCapHeatAtRatedCdts = RatedCapHeatDes * RatedHeatCapTempModFac;
    simpleWatertoAirHP.RatedCapCoolAtRatedCdts = RatedCapCoolTotalDes * RatedTotCapTempModFac;

**Review by rraustad — APPROVED** [review]
Tested defect file and reviewed unit test

**Comment by rraustad** [comment]
Pulled develop, unit tests are clean, CI has no diffs.
