### PR TITLE
Fix UnitarySystem Setpoint Control

### LINKED ISSUE #9793: UnitarySystem Setpoint control issues
Issue overview
--------------
1. User file has AirloopHVAC:UnitarySystem with Setpoint control and Coil:Cooling/Heating:WaterToAirHeatPump:EquationFit. The cooling coils do not operate. Eventually stumbled across [these changes](https://github.com/NREL/EnergyPlus/commit/e3a249bccbfbc89f1d816a968e5be119108d7827#diff-a4469a58b3b57ae5c4916cb9efb12f0c6ef79224175d09c796a7f6c2e1d3ec33R11606-R11616) in https://github.com/NREL/EnergyPlus/commit/e3a249bccbfbc89f1d816a968e5be119108d7827 (part of #8729, v9.6).

These lines were added:
```
                Real64 NoOutput = 0.0; // CoilSystem:Cooling:DX
                Real64 ReqOutput = 0.0;
                FullOutput = 0.0;
                if (this->m_sysType == SysType::CoilCoolingDX) {
                    NoOutput = state.dataLoopNodes->Node(InletNode).MassFlowRate *
                               (Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(OutletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat) -
                                Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(InletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat));
                    ReqOutput = state.dataLoopNodes->Node(InletNode).MassFlowRate *
                                (Psychrometrics::PsyHFnTdbW(DesOutTemp, state.dataLoopNodes->Node(OutletNode).HumRat) -
                                 Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(InletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat));
                }
```
`ReqOutput` is being redefined here and stomping on the value calculated back up in line 12411 of UnitarySystem.cc This breaks what appears to be the FullOutput pass for coil types `Coil_CoolingWaterToAirHPSimple` and `Coil_CoolingWaterToAirHP`, because these two coil types use `ReqOutput` as a parameter to the coil simulation function. The other coil types use some other variables such as the part load frac, so they are still working (not really confirmed, but assumed).

I think technically it's defining a new `ReqOutput` in a tighter scope which is supposedly legal code, but really bad, because any use of `ReqOutput` in the tighter scope uses the new one instead of the original. If there's a way to get the compilers to yell about this, that would be great (because this is the second bug introduced by the same problem).

I've started on a tentative fix locally. Just commented out the `Real64 ReqOutput = 0.0;` on line 12652.

2. UnitarySystem with Setpoint control and Coil;Heating:Electric as the supplemental heating coil generates this fatal error, but a control node input isn't supposed to be required when the coil is wrapped in a UnitarySystem.
```
   ** Severe  ** Coil:Heating:Electric "ELEC HTG COIL 13"
   **   ~~~   ** ... Missing control node for heating coil.
   **   ~~~   ** ... enter a control node name in the coil temperature setpoint node field for this heating coil.
   **   ~~~   ** ... use a Setpoint Manager to establish a setpoint at the coil temperature setpoint node.
   **  Fatal  ** ... errors found in heating coil input.
```

*WAHP companion coil sizing issue moved from here to #9849*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v22.2 (also v22.1 and v9.6 ~v9.5~).
 - [Unmethours 86434](https://unmethours.com/question/86434/unitary-system-water-air-cc-control-issues/)
 - Helpdesk tickets 16321 and 16322.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #9793
 - Fix UnitarySystem with Setpoint control problem where Coil:Cooling:WaterToAirHeatPump:EquationFit would never run. 
 See defect file 9793-in-v22.2.idf
 - Fix UnitarySystem with Setpoint control missing Control Node error when Coil:Heating:Electric (and likely some other coil types) is the supplemental heating coil. 
 See defect file ElectricSuppHeatingCoilControlNodeError-v22.2.idf

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
CI Diffs
* Five idf files were edited to remove unnecessary setpoint control node names and to clean up other unrelated warnings. This results in AUD, BND, and Table diffs. e.g. `regression.5Zone_Unitary_VSDesuperheater`
```
BND
- Node,8,REHEAT COIL AIR INLET NODE,Air,4
- Node,9,VAV SYS 1 OUTLET NODE,Air,7
+ Node,8,REHEAT COIL AIR INLET NODE,Air,3
+ Node,9,VAV SYS 1 OUTLET NODE,Air,6

Table (delta)
FullName:Object Count Summary_Entire Facility_Input Fields
Count
IDF Objects	2.0
```
* Four tests have err diffs, most are removing warnings, e.g.
```
-   ** Warning ** ProcessScheduleInput: Schedule:Constant="SUPPLY AIR HUM RATE SCHEDULE", Blank Schedule Type Limits Name input -- will not be validated.
-   ** Warning ** Coil:Heating:Fuel "MAIN HEATING COIL 1"
-   **   ~~~   **  The "Temperature Setpoint Node Name" input is not required for this heating coil.
-   **   ~~~   **  Leaving the input field "Temperature Setpoint Node Name" blank will eliminate this warning.
-   ** Warning ** The following Report Variables were requested but not generated -- check.rdd file
-   **   ~~~   ** Either the IDF did not contain these elements, the variable name is misspelled,
-   **   ~~~   ** or the requested variable is an advanced output which requires Output : Diagnostics, DisplayAdvancedReportVariables;
-   ************* Key=*, VarName=COOLING COIL SOURCE SIDE HEAT TRANSFER RATE, Frequency=Hourly
-   ************* Key=*, VarName=UNITARY SYSTEM CYCLING RATIO, Frequency=Hourly
-   ************* Key=*, VarName=UNITARY SYSTEM COMPRESSOR SPEED RATIO, Frequency=Hourly
-   ************* There are 2 unused schedules in input.
-   ************* Use Output:Diagnostics,DisplayUnusedSchedules; to see them.
```
And a slight change in error for `EMSSetpointBasedMultiSpeedDXCoilOverrideControl`
```
-   **   ~~~   ** Estimated part-load ratio  = 0.889
+   **   ~~~   ** Estimated part-load ratio  = 0.888
```
* One file has MTD diffs
```
- Meters for 1289,SUPPLY FAN 1:Fan Electricity Energy [J]
+ Meters for 1292,SUPPLY FAN 1:Fan Electricity Energy [J]
```
* And `WaterSideEconomizer_PreCoolCoil` has small eso diffs. Not sure why, but they're tiny, on the order of e-13.

**Comment by mjwitte** [comment]
Defect file results.
*9793-in-v22.2.idf*
develop, this branch
image      image

*ElectricSuppHeatingCoilControlNodeError-v22.2.idf*
develop
```
   ** Severe  ** Coil:Heating:Electric "ELEC HTG COIL 13"
   **   ~~~   ** ... Missing control node for heating coil.
   **   ~~~   ** ... enter a control node name in the coil temperature setpoint node field for this heating coil.
   **   ~~~   ** ... use a Setpoint Manager to establish a setpoint at the coil temperature setpoint node.
   **  Fatal  ** ... errors found in heating coil input.
   ************* EnergyPlus Terminated--Fatal Error Detected. 293 Warning; 4 Severe Errors; Elapsed Time=00hr 00min  7.66sec
```
this branch
```
   ************* EnergyPlus Completed Successfully-- 13784 Warning; 3 Severe Errors; Elapsed Time=00hr 01min 54.48sec
```

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -7657,8 +7657,15 @@ namespace UnitarySystems {
         int CoilType_Num = this->m_SuppHeatCoilType_Num;
 
         if ((CoilType_Num == DataHVACGlobals::Coil_HeatingGasOrOtherFuel) || (CoilType_Num == DataHVACGlobals::Coil_HeatingElectric)) {
-            HeatingCoils::SimulateHeatingCoilComponents(
-                state, CompName, FirstHVACIteration, _, this->m_SuppHeatCoilIndex, _, true, this->m_FanOpMode, this->m_SuppHeatPartLoadFrac);
+            HeatingCoils::SimulateHeatingCoilComponents(state,
+                                                        CompName,
+                                                        FirstHVACIteration,
+                                                        this->m_DesignSuppHeatingCapacity * this->m_SuppHeatPartLoadFrac,
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:7663]: In `calcUnitarySuppSystemToSP` pass the supp heat coil load argument here and several other places so the supp heating coil doesn't expect it's own setpoint node (and then generate a spurious error message about a missing setpoint).

File: src/EnergyPlus/UnitarySystem.cc [hunk 2]
```diff
@@ -12662,7 +12676,6 @@ namespace UnitarySystems {
                 NoLoadHumRatOut = state.dataLoopNodes->Node(OutletNode).HumRat;
 
                 Real64 NoOutput = 0.0; // CoilSystem:Cooling:DX
-                Real64 ReqOutput = 0.0;
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:12665]: This fixes the cooling coil setpoint control operation (this line creates a shadow of `ReqOutput` which masks the value set up in [line 12438](https://github.com/NREL/EnergyPlus/blob/197358237f1faf861ea76ba458d05bf057e4436d/src/EnergyPlus/UnitarySystem.cc#L12438-L12442).

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -15030,13 +15044,14 @@ namespace UnitarySystems {
                         HeatingCoils::SimulateHeatingCoilComponents(state,
                                                                     CompName,
                                                                     FirstHVACIteration,
-                                                                    DataLoopNode::SensedLoadFlagValue,
+                                                                    PartLoadFrac,
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:15047]: More supp heat setpoint control fixes in `controlSuppHeatSystemToSP`.

File: testfiles/5Zone_Unitary_HXAssistedCoil.idf [hunk 4]
```diff
@@ -604,19 +604,6 @@
     For: AllDays,            !- Field 2
     Until: 24:00,117.239997864; !- Field 3
 
-  Schedule:Compact,
```
Comment (mjwitte) [inline testfiles/5Zone_Unitary_HXAssistedCoil.idf:607]: Delete unused schedules in several testfiles.

File: testfiles/5Zone_Unitary_HXAssistedCoil.idf [hunk 5]
```diff
@@ -2715,22 +2683,21 @@
...
   SetpointManager:Scheduled,
-    Supply Air Hum Rate Manager 2,  !- Name
+    Supply Air HumRat Manager 2,  !- Name
     MaximumHumidityRatio,    !- Control Variable
-    Supply Air Hum Rate Schedule,  !- Schedule Name
+    Supply Air HumRat Schedule,  !- Schedule Name
     Main Heating Coil 1 Inlet Node;  !- Setpoint Node or NodeList Name
 
-  Schedule:Constant,Supply Air Hum Rate Schedule,,0.006;
+  Schedule:Constant,Supply Air HumRat Schedule,Any Number,0.006;
```
Comment (mjwitte) [inline testfiles/5Zone_Unitary_HXAssistedCoil.idf:2700]: Clean up schedule warning.

File: testfiles/5Zone_Unitary_HXAssistedCoil.idf [hunk 6]
```diff
@@ -2980,10 +2947,6 @@
 
   Output:Variable,*,Cooling Coil Runtime Fraction,hourly;
 
-  Output:Variable,*,Cooling Coil Basin Heater Electricity Rate,hourly;
```
Comment (mjwitte) [inline testfiles/5Zone_Unitary_HXAssistedCoil.idf:2983]: Clean up output variable warnings.

File: testfiles/5Zone_Unitary_HXAssistedCoil.idf [hunk 7]
```diff
@@ -2715,22 +2683,21 @@
     0.8,                     !- Burner Efficiency
     32000,                   !- Nominal Capacity {W}
     Reheat Coil Air Inlet Node,  !- Air Inlet Node Name
-    VAV Sys 1 Outlet Node,   !- Air Outlet Node Name
-    VAV Sys 1 Outlet Node;   !- Temperature Setpoint Node Name
+    VAV Sys 1 Outlet Node;   !- Air Outlet Node Name
```
Comment (mjwitte) [inline testfiles/5Zone_Unitary_HXAssistedCoil.idf:2686]: Delete setpoint node on unitary heating coil.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 8]
```diff
@@ -1280,6 +1281,8 @@ TEST_F(ZoneUnitarySysTest, UnitarySystemModel_MultiSpeedDXCoolCoil_Only)
     // the 'return' on FirstHVACIteration = true set FirstHVACIteration to false for unit testing to size water coils
     FirstHVACIteration = false;
     state->dataGlobal->BeginEnvrnFlag = false;
+    state->dataHVACGlobal->DoSetPointTest = true;
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc]: Tighten up unit test for sepoint control.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 9]
```diff
@@ -9630,6 +9664,449 @@ TEST_F(EnergyPlusFixture, UnitarySystemModel_WaterToAirHeatPump)
     EXPECT_EQ(thisSys->m_MinOATCompressorHeating, -1000.0);
 }
 
+TEST_F(EnergyPlusFixture, UnitarySystemModel_WaterToAirHeatPump_SetPointControl)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:9667]: New unit test.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 10]
```diff
@@ -18188,8 +18665,7 @@ TEST_F(ZoneUnitarySysTest, UnitarySystemModel_FuelHeatCoilStptNodeTest)
         "  1.0,                            !- Gas Burner Efficiency",
         "  autosize,                       !- Nominal Capacity",
         "  Heating Coil Air Inlet Node,    !- Air Inlet Node Name",
-        "  Zone 2 Inlet Node,              !- Air Outlet Node Name",
-        "  Zone 2 Inlet Node;              !- Temperature Setpoint Node Name",
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc]: Delete unused setpoint node name.

**Review by mjwitte — COMMENTED** [review]
Code walkthru

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 11]
```diff
@@ -4630,6 +4649,18 @@ SetpointManager:Scheduled,
...
+          Always Point004,              !- Name
+          Any Number,              !- Schedule Type Limits Name
+          Through: 12/31,          !- Field 1
+          For: AllDays,            !- Field 2
+          Until: 24:00, 0.004;      !- Field 3
+
+        SetpointManager:Scheduled,
+          CW Coil Humidity Setpoint Manager, !- Name
+          MaximumHumidityRatio, !- Control Variable
+          Always 20C, !- Schedule Name
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:4662]: Either this should be "Always Point004" or the new schedule isn't needed. The humrat SP gets written directly on the node so this must be needed for the new ManageSetPoints call?

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 12]
```diff
@@ -9625,6 +9658,449 @@ Curve:QuadLinear,
...
+                      CompIndex,
+                      HeatActive,
+                      CoolActive,
+                      ZoneOAUnitNum,
+                      OAUCoilOutTemp,
+                      ZoneEquipment,
+                      sensOut,
+                      latOut);
+
+    EXPECT_NEAR(outletNode.Temp, 30.0, 0.01); // higher than inlet due to fan heat
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc:10099]: "due to fan heat"? It's a blow thru fan, SP should be hit within tolerance.

File: src/EnergyPlus/UnitarySystem.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:7663]: OK, the parent has the SP, the child can just meet a load based on PLR. Except for the iteration implication (gas and elec will just return the correct outlet temp) this is fine. What implication? Out of scope but could have called gas or elec with a SP at their outlet node (internally set) and wouldn't need to iterate. Again, this is fine.

File: src/EnergyPlus/UnitarySystem.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:12665]: Agreed

File: src/EnergyPlus/UnitarySystem.cc [hunk 13]
```diff
@@ -14924,6 +14937,7 @@ namespace UnitarySystems {
         this->m_HeatingPartLoadFrac = PartLoadFrac;
         this->m_HeatingSpeedRatio = SpeedRatio;
         this->m_HeatingCycRatio = CycRatio;
+        HeatCoilLoad = ReqOutput;
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:14940]: What if the coil didn't meet ReqOutput? Looks like the other coils are doing the same thing.

File: src/EnergyPlus/UnitarySystem.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:15047]: If not SensedLoadFlagValue then this argument is the load. So should use capacity * PLR ? Are any of the diffs a result of this change ??

File: src/EnergyPlus/UnitarySystem.cc [hunk 14]
```diff
@@ -15030,13 +15044,14 @@ namespace UnitarySystems {
...
+                                                                    PartLoadFrac,
                                                                     CompIndex,
                                                                     QCoilActual,
                                                                     SuppHeatingCoilFlag,
                                                                     FanOpMode,
                                                                     PartLoadFrac); // QCoilReq= 0.0d0,  &
-                        if (!(this->m_SuppHeatCoilType_Num == DataHVACGlobals::Coil_HeatingDesuperheater)) {
+                        if (!(this->m_SuppHeatCoilType_Num == DataHVACGlobals::Coil_HeatingDesuperheater) &&
+                            (this->m_DesignSuppHeatingCapacity > 0)) {
                             PartLoadFrac = QCoilActual / this->m_DesignSuppHeatingCapacity;
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:15055]: Protecting divide by 0. I'll have to think this one through. Do we always know the design supp heat capacity for gas/elec? I think so. What if that coil sizes to 0? We could get PLR = 1 if there is a load from the else below? I guess not if coil size = 0 because QCoilActual should also be 0.

File: src/EnergyPlus/UnitarySystem.cc [hunk 15]
```diff
@@ -15106,13 +15121,15 @@ namespace UnitarySystems {
                             HeatingCoils::SimulateHeatingCoilComponents(state,
                                                                         CompName,
                                                                         FirstHVACIteration,
-                                                                        DataLoopNode::SensedLoadFlagValue,
+                                                                        this->m_DesignSuppHeatingCapacity,
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:15124]: Running at PLR=1 so this looks OK.

File: src/EnergyPlus/UnitarySystem.cc [hunk 16]
```diff
@@ -15106,13 +15121,15 @@ namespace UnitarySystems {
...
                                                                         CompIndex,
                                                                         QCoilActual,
                                                                         SuppHeatingCoilFlag,
                                                                         FanOpMode,
                                                                         PartLoadFrac);
-                            PartLoadFrac = QCoilActual / this->m_DesignSuppHeatingCapacity;
+                            if (this->m_DesignSuppHeatingCapacity > 0.0) {
+                                PartLoadFrac = QCoilActual / this->m_DesignSuppHeatingCapacity;
+                            }
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc:15132]: if design supp heat capacity = 0 then PartLoadFrac = 1 from above at line 15116. That would actually seem correct (i.e., tried to run coil full out).

**Review by rraustad — COMMENTED** [review]
I think just the 1 comment where PLR replaced SensedLoadFlagValue is suspicious [here](https://github.com/NREL/EnergyPlus/pull/9850/files#r1123449093).

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc (hunk 11 above)
Comment (mjwitte) [reply tst/EnergyPlus/unit/UnitarySystem.unit.cc:4662]: Good catch. This is needed, because `DoSetPointTest` is true now, but should be "Always Point004". Fixed.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc (hunk 12 above)
Comment (mjwitte) [reply tst/EnergyPlus/unit/UnitarySystem.unit.cc:10099]: That comment must be left over from an earlier iteration of this test. The outlet is matching the setpoint of 30.0 set a few lines before this. Comment deleted.

File: src/EnergyPlus/UnitarySystem.cc (hunk 3 above)
Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:15047]: > If not SensedLoadFlagValue then this argument is the load. So should use capacity * PLR ? Are any of the diffs a result of this change ??

This argument is `QCoilReq` in `SimulateHeatingComponents`. Technically this should be `PartLoadFrac * this->m_DesignSuppHeatingCapacity` but `PartLoadFrac = 0.0 here to get the no-load result, so just being lazy here. Updated the end-line comment to help clarify, maybe.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:15047]: I see. I didn't notice this was a PLR=0 call.

File: src/EnergyPlus/UnitarySystem.cc (hunk 14 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:15055]: If PLR = 0 then this IF block isn't even needed.

File: src/EnergyPlus/UnitarySystem.cc (hunk 16 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:15132]: Here also, PartLoadFrac = 1 so there is no need to calculate it.

**Comment by rraustad** [comment]
Unit tests run to completion. Defect file now shows supp heat coil operation. No reason to hold this up for more clean up in UnitarySystem. Plenty of clean up needed there anyway.

**Review by rraustad — APPROVED** [review]
Comments addressed and defect file now runs as expected. Will merge on CI completion.

File: src/EnergyPlus/UnitarySystem.cc (hunk 16 above)
Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:15132]: > Here also, PartLoadFrac = 1 so there is no need to calculate it.

Is it possible that it could deliver less than `DesignSuppHeatingCapacity` so calculating PLR might be useful?

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:15132]: Other than a high temperature limit on the child I don't think so but's it's also hard to know if this calculation was placed here for a reason. Leaving as is for further evaluation.
