### PR TITLE
Fix Bugs in Emmel and Blocken Convection Algorithms

### LINKED ISSUE #9106: Theta in Emmel Vertical Convection Coefficients Model is incorrectly determined
Issue overview
--------------
In the Emmel Vertical Model, from the outside adaptive convection algorithm, theta (the difference between the surface normal and the wind direction) is incorrectly determined (ConvectionCoefficients.cc, [code line 8838](https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/ConvectionCoefficients.cc#L8838)). First, the surface azimuth already points towards the surface normal, thus not requiring subtracting 90°. Second, the difference between the surface azimuth and the wind direction should be an absolute value (theta = abs(WindDirection - SurfaceAzimuth)). Third, in [code line 8839](https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/ConvectionCoefficients.cc#L8839), when theta is greater than 180°, then it should be theta = 360° - theta.

These issues have two consequentes:

1) When theta value is negative (up to -90°, when the difference between WindDirection and SurfaceAzimuth is less than 90°; theta = WindDirection - SurfaceAzimuth -90°), it then falls in the first if condition in [code line 8841](https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/ConvectionCoefficients.cc#L8841).

2) The convection coefficients intervals are repeated after 180° instead of being mirrored (0° to 180° or 0° to -180°) due to the condition of theta being greater than 180° (in [code line 8839](https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/ConvectionCoefficients.cc#L8839)), which results also in a negative value.

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Fixes #9106 
 - Emmel and Blocken convection correlations for external wind-driven convection have some bugs in the correlation values and the calculated angle between the surface normal and the wind direction.
 - This adds new unit tests and corrects the errors.

Emmel et al. Table 3 - Convection correlations for walls and roofs
Screen Shot 2021-10-13 at 10 19 18 AM

Blocken et al. Table 6 - Convection correlations for windward surfaces 
Screen Shot 2021-10-13 at 10 19 04 AM

### CODE REVIEW

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 1]
```diff
@@ -7013,12 +7013,12 @@ void CalcUserDefinedOutsideHcModel(EnergyPlusData &state, int const SurfNum, int
         break;
     case ConvectionConstants::RefWind::ParallelComp:
         // WindSpeed , WindDir, surface Azimuth
-        Theta = state.dataEnvrn->WindDir - Surface(SurfNum).Azimuth - 90.0; // TODO double check theta
+        Theta = CalcWindSurfaceTheta(state.dataEnvrn->WindDir, Surface(SurfNum).Azimuth);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc:7015]: This is the same theta angle calculation that was suspect before. Replacing it with the new unit-tested function.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 2]
```diff
@@ -7013,12 +7013,12 @@ void CalcUserDefinedOutsideHcModel(EnergyPlusData &state, int const SurfNum, int
...
         ThetaRad = Theta * DataGlobalConstants::DegToRadians;
         break;
     case ConvectionConstants::RefWind::ParallelCompAtZ:
         // Surface WindSpeed , Surface WindDir, surface Azimuth
-        Theta = state.dataSurface->SurfOutWindDir(SurfNum) - Surface(SurfNum).Azimuth - 90.0; // TODO double check theta
+        Theta = CalcWindSurfaceTheta(state.dataEnvrn->WindDir, Surface(SurfNum).Azimuth);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: Same

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 3]
```diff
@@ -8758,8 +8758,21 @@ Real64 CalcMitchell(EnergyPlusData &state, Real64 const WindAtZ, Real64 const Le
...
+    // Should always be a value between 0-180 deg
+
+    Real64 theta = std::abs(WindDir - SurfAzimuth);
+    if (theta > 180) {
+        return abs(theta - 360);
+    } else {
+        return theta;
+    }
+}
+
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: New function for calculating the angle theta between the wind direction and the surface azimuth.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 4]
```diff
@@ -8787,16 +8800,15 @@ Real64 CalcBlockenWindward(Real64 const WindAt10m,
 
     Real64 Theta; // angle between wind and surface azimuth
 
-    Theta = WindDir - SurfAzimuth - 90.0; // TODO double check theta
-    if (Theta > 180.0) Theta -= 360.0;
+    Theta = CalcWindSurfaceTheta(WindDir, SurfAzimuth);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: Update suspect theta calculation.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 5]
```diff
@@ -8787,16 +8800,15 @@ Real64 CalcBlockenWindward(Real64 const WindAt10m,
...
     if (Theta <= 11.25) {
         Hf = 4.6 * std::pow(WindAt10m, 0.89);
-    } else if ((11.25 < Theta) && (Theta <= 33.75)) {
+    } else if (Theta <= 33.75) {
         Hf = 5.0 * std::pow(WindAt10m, 0.8);
-    } else if ((33.75 < Theta) && (Theta <= 56.25)) {
+    } else if (Theta <= 56.25) {
         Hf = 4.6 * std::pow(WindAt10m, 0.84);
-    } else if ((56.25 < Theta) && (Theta <= 100.0)) {
+    } else if (Theta <= 90.0) {
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: A few things here:
- Don't need multiple bounding checks on theta at each condition. It should successively fall through until it hits the right one.
- This is a "windward" function, so an upper bound of 100 deg seems inappropriate. 90 deg should be the max a "windward" surface could see.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 6]
```diff
@@ -8828,25 +8840,24 @@ Real64 CalcEmmelVertical(EnergyPlusData &state,
...
+    //   Energy and Buildings 39 (2007) 335- 342
 
     // Return value
     Real64 Hf;
 
     Real64 Theta; // angle between wind and surface azimuth
 
-    Theta = WindDir - SurfAzimuth - 90.0; // TODO double check theta
-    if (Theta > 180.0) Theta -= 360.0;
+    Theta = CalcWindSurfaceTheta(WindDir, SurfAzimuth);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: Update theta calculation.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 7]
```diff
@@ -8828,25 +8840,24 @@ Real64 CalcEmmelVertical(EnergyPlusData &state,
...
+    } else if (Theta <= 67.5) {
         Hf = 3.34 * std::pow(WindAt10m, 0.84);
-    } else if ((67.5 < Theta) && (Theta <= 112.5)) {
+    } else if (Theta <= 112.5) {
         Hf = 4.78 * std::pow(WindAt10m, 0.71);
-    } else if ((112.5 < Theta) && (Theta <= 157.5)) {
+    } else if (Theta <= 157.5) {
         Hf = 4.05 * std::pow(WindAt10m, 0.77);
-    } else if ((157.5 < Theta) && (Theta <= 180.0)) {
+    } else if (Theta <= 180.0) {
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: Remove duplicative checks here.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 8]
```diff
@@ -8894,19 +8905,18 @@ Real64 CalcEmmelRoof(EnergyPlusData &state,
 
     Real64 Theta; // angle between wind and surface azimuth
 
-    Theta = WindDir - LongAxisOutwardAzimuth - 90.0; // TODO double check theta
-    if (Theta > 180.0) Theta -= 360.0;
+    Theta = CalcWindSurfaceTheta(WindDir, LongAxisOutwardAzimuth);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: Update suspect theta calculation here.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 9]
```diff
@@ -8894,19 +8905,18 @@ Real64 CalcEmmelRoof(EnergyPlusData &state,
...
-        Hf = 3.54 * std::pow(WindAt10m, 0.76);
+        Hf = 5.11 * std::pow(WindAt10m, 0.78);
+    } else if (Theta <= 67.5) {
+        Hf = 4.60 * std::pow(WindAt10m, 0.79);
+    } else if (Theta <= 112.5) {
+        Hf = 3.67 * std::pow(WindAt10m, 0.85);
+    } else if (Theta <= 157.5) {
+        Hf = 4.60 * std::pow(WindAt10m, 0.79);
+    } else if (Theta <= 180.0) {
+        Hf = 5.11 * std::pow(WindAt10m, 0.78);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: Looks like a pasteo error. Based on the paper, these are the numbers for a vertical surface, not a roof surface.

File: src/EnergyPlus/ConvectionCoefficients.cc [hunk 10]
```diff
@@ -8919,7 +8929,7 @@ Real64 CalcEmmelRoof(EnergyPlusData &state,
                                       "CalcEmmelRoof: Convection model wind angle calculation suspect and high theta correlation",
                                       state.dataConvectionCoefficient->CalcEmmelRoofErrorIDX);
 
-        Hf = 3.54 * std::pow(WindAt10m, 0.76);
+        Hf = 3.67 * std::pow(WindAt10m, 0.85);
```
Comment (mitchute) [inline src/EnergyPlus/ConvectionCoefficients.cc]: I'm not sure it can even make it here, TBH. I updated this to pull from the roof correlation, but this probably needs to be double-checked (by me) and removed if it's inaccessible.

File: tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc [hunk 11]
```diff
@@ -2630,3 +2631,178 @@ TEST_F(ConvectionCoefficientsFixture, TestSetAdaptiveConvectionAlgoCoefficient)
     expected_curve = UtilityRoutines::FindItemInList("NUSSELTJURGESDUPCURVE", state->dataConvectionCoefficient->HcOutsideUserCurve);
     ASSERT_EQ(algorithm_identifier, expected_curve);
 }
+
```
Comment (mitchute) [inline tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc:2634]: You get a unit test, and you get a unit test. Everybody gets a unit test.

**Review by mitchute — COMMENTED** [review]
Ready for review.

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/ConvectionCoefficients.cc]: Could have combined 8001-8003 as Real64 Theta = ...

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 5 above)
Comment (rraustad) [reply src/EnergyPlus/ConvectionCoefficients.cc]: upper bound, rounding, what if Theta comes out as 90.0000000001 ?

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/ConvectionCoefficients.cc]: 8906-8908

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/ConvectionCoefficients.cc]: This argument should be SurfOutWindDir?

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 5 above)
Comment (mitchute) [reply src/EnergyPlus/ConvectionCoefficients.cc]: Agreed, that makes sense. So... 91? Back to 100?

Comment (rraustad) [reply src/EnergyPlus/ConvectionCoefficients.cc]: And YOU get a unit test! That's up to you, I guess 91 should be adequate but 100 should never hurt anything, unless you want to use 91 and assert on an else.

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 4 above)
Comment (mitchute) [reply src/EnergyPlus/ConvectionCoefficients.cc]: Thanks. Fixed.

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 5 above)
Comment (mitchute) [reply src/EnergyPlus/ConvectionCoefficients.cc]: Thanks. I backed it down to 100 deg. Who knows how often these things are actually used, but 100 isn't unreasonable.

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 8 above)
Comment (mitchute) [reply src/EnergyPlus/ConvectionCoefficients.cc]: Fixed.

File: src/EnergyPlus/ConvectionCoefficients.cc (hunk 10 above)
Comment (mitchute) [reply src/EnergyPlus/ConvectionCoefficients.cc]: I updated the error handling in these functions and fixed the theta angle calculation so that it's always bounded between 0-180.

**Comment by mitchute** [comment]
@rraustad Thanks for the reviews. I made a few updates based on your comments. Let me know if you have anything else.

**Comment by rraustad** [comment]
Yeah, looks like 0 diffs here and a final review did not find anything that stands out. Good to go.

**Comment by Myoldmopar** [comment]
Another one that looks fully ready.   Thanks for all the review here @rraustad.  I'll pull develop into this one as well for due diligence.  Assuming it is clean, I'll get it in the queue.

**Comment by Myoldmopar** [comment]
I pulled develop in locally, ran all the tests and everything passed.  I ran regressions against develop so that I didn't have to wait on CI and it came out perfect, no diffs.  Merging this, thanks @mitchute
