### PR TITLE
Fix #8111 - E+ Crash w/ RunPeriodControl:DaylightSavingTime that wraps around year

### LINKED ISSUE #8111: E+ Crash w/ RunPeriodControl:DaylightSavingTime that wraps around year
Issue overview
--------------
Using a `RunPeriodControl:DaylightSavingTime` object is sometimes causing an EnergyPlus crash.

It appears to work fine if the end date is after the start date (representative of the northern hemisphere) like so:

```
RunPeriodControl:DaylightSavingTime,
  Mar 15,                                 !- Start Date
  Oct 15;                                 !- End Date
```

But EnergyPlus crashes if the end date is before the start date (representative of the southern hemisphere) like so:

```
RunPeriodControl:DaylightSavingTime,
  Oct 15,                                 !- Start Date
  Mar 15;                                 !- End Date
```

Note that the documentation suggests it should work -- see the example for Brazil [here](https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-location-climate-weather-file-access.html#field-end-date).

IDF file that causes a crash:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/4833928/in.idf.txt)

cc @joseph-robertson

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 9.3.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #8111
 - E+ Crash w/ RunPeriodControl:DaylightSavingTime that wraps around year

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ScheduleManager.cc [hunk 1]
```diff
@@ -2877,6 +2878,12 @@ namespace ScheduleManager {
             thisHolidayIndex = DataEnvironment::HolidayIndexTomorrow;
         }
 
+        // In the case where DST is applied on 12/31 at 24:00, which is the case for a Southern Hemisphere location for eg
+        // (DayOfYear_Schedule is a bit weird, ScheduleManager always assumes LeapYear)
+        if (thisDayOfYear == 367) {
+            thisDayOfYear = 1;
+        }
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:2885]: Rough way (initial)

File: src/EnergyPlus/ScheduleManager.cc [hunk 2]
```diff
@@ -2877,6 +2878,12 @@ namespace ScheduleManager {
             thisHolidayIndex = DataEnvironment::HolidayIndexTomorrow;
         }
 
+        // In the case where DST is applied on 12/31 at 24:00, which is the case for a Southern Hemisphere location for eg
+        // (DayOfYear_Schedule is a bit weird, ScheduleManager always assumes LeapYear)
+        if (thisDayOfYear == 367) {
+            thisDayOfYear = DataEnvironment::RunPeriodStartJDay;
+        }
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc]: Optional second way of doing it... I'm just wary of cases where you might have used some kind of Schedule that doesn't have entries for all days, such as using a Schedule:Year with Schedule:Week:Daly and Schedule:Day: it's possible that January 1 isn't set...

Though by definition, the day after December 31 should be January 1... so the first way should be more correct.

**Comment by jmarrec** [comment]
## Note

https://github.com/NREL/EnergyPlus/pull/8118/commits/fcad093296b8ffe56a09c18825a12a1fefbe1b72 should probably get reverted, but I wanted to illustrate it so we can have an informed conversation and decision.

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 3]
```diff
@@ -804,3 +806,445 @@ TEST_F(EnergyPlusFixture, Schedule_GetCurrentScheduleValue_DST)
...
+        "  Until: 24:00,            !- Field 7",
+        "  2;                       !- Field 8",
+    });
+
+    ASSERT_TRUE(process_idf(idf_objects));
+
+    DataGlobals::NumOfTimeStepInHour = 4;    // must initialize this to get schedules initialized
+    DataGlobals::MinutesPerTimeStep = 15;    // must initialize this to get schedules initialized
+    DataGlobals::TimeStepZone = 0.25;
+    DataGlobals::TimeStepZoneSec = DataGlobals::TimeStepZone * DataGlobals::SecInHour;
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:831]: Simple test for #8111

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 4]
```diff
@@ -804,3 +806,445 @@ TEST_F(EnergyPlusFixture, Schedule_GetCurrentScheduleValue_DST)
...
+    //    [...]
+    //   Through: 12/31,
+    //   For: AllDays,
+    //    Until: 1:00, 8761,
+    //    [...]
+    //    Until: 24:00, 8784;
+
+    // # 'THROUGH" => Number of additional week schedules
+    // # 'FOR' => Number of additional day schedules
+    // So we use 366 Week Schedules, all with one day (LeapYear)
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:887]: Test a ramp up schedule for 8784 hourly values (leap year), checking every hour in the DST and non DST case.

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 5]
```diff
@@ -804,3 +806,445 @@ TEST_F(EnergyPlusFixture, Schedule_GetCurrentScheduleValue_DST)
...
+    //    [...]
+    //   Through: 12/31,
+    //   For: AllDays,
+    //    Until: 1:00, 8737,
+    //    [...]
+    //    Until: 24:00, 8760.0;
+
+    // # 'THROUGH" => Number of additional week schedules
+    // # 'FOR' => Number of additional day schedules
+    // So we use 366 Week Schedules, all with one day (LeapYear)
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:1068]: Test a ramp up schedule for 8760 hourly values (no leap year), checking every hour in the DST and non DST case.

Comment (jmarrec) [reply tst/EnergyPlus/unit/ScheduleManager.unit.cc:1068]: This was (perhaps weirdly) harder than the leap case since ScheduleManager always assumes Leap Year in its internal structure. Day 60 (ordinal day corresponding to Feb 29) will just NOT be used if it's not a leap year.

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 6]
```diff
@@ -804,3 +806,445 @@ TEST_F(EnergyPlusFixture, Schedule_GetCurrentScheduleValue_DST)
...
+
+    // March 1
+    EXPECT_EQ(61, ScheduleManager::Schedule(1).WeekSchedulePointer(61));
+    EXPECT_EQ(60, ScheduleManager::WeekSchedule(61).DaySchedulePointer(1));
+    EXPECT_EQ(60*24.0, ScheduleManager::DaySchedule(60).TSValue(4, 24));
+
+
+    EXPECT_EQ(366, ScheduleManager::Schedule(1).WeekSchedulePointer(366));
+    EXPECT_EQ(365, ScheduleManager::WeekSchedule(366).DaySchedulePointer(1));
+    EXPECT_EQ(8760.0, ScheduleManager::DaySchedule(365).TSValue(4, 24));
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:1132]: Start by checking feb 28, Feb 29 (ordinal day 60, unused here), and the end of year value.

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 7]
```diff
@@ -804,3 +806,445 @@ TEST_F(EnergyPlusFixture, Schedule_GetCurrentScheduleValue_DST)
...
+                        EXPECT_EQ(HourOfYear, ScheduleManager::LookUpScheduleValue(1, DataGlobals::HourOfDay, DataGlobals::TimeStep));
+                        EXPECT_EQ(HourOfYear, ScheduleManager::Schedule(1).CurrentValue);
+                        EXPECT_EQ(HourOfYear, ScheduleManager::GetCurrentScheduleValue(1));
+                    }
+                }
+            }
+        }
+
+        EXPECT_EQ(8760.0, HourOfYear);
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:1200]: Check each hourly&timestep values in the non DST case

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 8]
```diff
@@ -804,3 +806,445 @@ TEST_F(EnergyPlusFixture, Schedule_GetCurrentScheduleValue_DST)
...
+                        ScheduleManager::UpdateScheduleValues();
+                        int thisHourOfYear = HourOfYear + 1;
+                        if (thisHourOfYear > 8760.0) {
+                            thisHourOfYear = 1;
+                        }
+                        EXPECT_EQ(thisHourOfYear, ScheduleManager::LookUpScheduleValue(1, DataGlobals::HourOfDay, DataGlobals::TimeStep));
+                        EXPECT_EQ(thisHourOfYear, ScheduleManager::Schedule(1).CurrentValue);
+                        EXPECT_EQ(thisHourOfYear, ScheduleManager::GetCurrentScheduleValue(1));
+                    }
+                }
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:1238]: Same for the DST case, checking the special case at the last timestep which should be January 1 as a result (value == 1)

File: src/EnergyPlus/ScheduleManager.cc (hunk 2 above)
Comment (jmarrec) [reply src/EnergyPlus/ScheduleManager.cc]: https://github.com/NREL/EnergyPlus/commit/fcad093296b8ffe56a09c18825a12a1fefbe1b72 should probably be reverted

Comment (jmarrec) [reply src/EnergyPlus/ScheduleManager.cc]: @rraustad @mjwitte @Myoldmopar any thoughts on this comment and the one just above please?

Comment (rraustad) [reply src/EnergyPlus/ScheduleManager.cc]: That's an interesting logic problem. What is the next day of the simulation after Dec 31? Yeah, It's always Jan 1, if Jan 1 is in the simulation. The RunPeriod could be 2/1 - 12/31 or 4/1 - 3/30. I guess you'd only need that if block using my second RunPeriod dates example.

Comment (mjwitte) [reply src/EnergyPlus/ScheduleManager.cc]: Seems like it should use Jan 1.  EnergyPlus expects schedules to be fully defined for the entire year and warns if they are not (at least that was the case long ago, I assume it still is). Perhaps a note in the I/O ref? "If DST is active on Dec 31, then hour 24 will use the schedule values for Jan 1, hour 1."

Comment (jmarrec) [reply src/EnergyPlus/ScheduleManager.cc]: You're right, I just tried ahving a Schedule:Year with missing days:

```
Program Version,EnergyPlus, Version 9.4.0-db88b719ab, YMD=2020.06.30 18:02,
   ** Severe  ** ProcessScheduleInput: Schedule:Year="SOUTHZONE-CONTROL SCHED" has missing days in its schedule pointers
   ** Severe  ** ProcessScheduleInput: Schedule:Year="SOUTHZONE-SETPOINTS" has missing days in its schedule pointers
   **  Fatal  ** ProcessScheduleInput: Preceding Errors cause termination.

```

I'll revert fcad093 then

**Comment by Myoldmopar** [comment]
Now that you went ahead and reverted that commit, I _think_ this is ready to go.  The change is minimal, sensible, and there is a plethora of quality unit tests.  I haven't tested or tried to break anything yet.  Does anyone have any strong opinion on this before I do final review/testing?

**Comment by Myoldmopar** [comment]
Pulled develop into the branch locally, rebuilt and ran unit tests, no problem.  Tested the defect file with develop, confirmed the crash.  Tested with this branch and confirmed the fix.  I think this is good to go in.  Thanks @jmarrec !
