### PR TITLE
Address UnitarySystem used as zone equipment does not allow NightCycle availability manager control

### LINKED ISSUE #9971: UnitarySystem used as zone equipment does not allow NightCycle availability manager control
Issue overview
--------------
Testing has confirmed that AvailabilityManager:NightCycle does not work with packaged zone equipment. A test file shows the fan does not turn on at night when zone temperature exceeds the thermostat set point temperature. This test file uses the Fan:SystemModel object.

image

Correcting the problem in setAverageAirFlow to "set" the zone equipment availability manager flags corrects the problem.

        // combine above and below into 1 logical
        bool turnFansOn = false;
        bool turnFansOff = false;
        if (this->m_IsZoneEquipment) {
            turnFansOn = state.dataHVACGlobal->ZoneCompTurnFansOn;
            turnFansOff = state.dataHVACGlobal->ZoneCompTurnFansOff;
            state.dataHVACGlobal->TurnFansOn = turnFansOn;   // <---- HERE
            state.dataHVACGlobal->TurnFansOff = turnFansOff; // <---- and HERE
        } else {
            turnFansOn = state.dataHVACGlobal->TurnFansOn;
            turnFansOff = state.dataHVACGlobal->TurnFansOff;
        }

image

Zone equipment affected:

 - AirloopHVAC:UnitarySystem configured as zone equipment
 - ZoneHVAC:PackagedTerminalAirConditioner
 - ZoneHVAC:PackagedTerminalHeatPump
 - ZoneHVAC:WaterToAirHeatPump

Work around:

Set fan availability schedule to always on and set fan operating mode to cycling during unoccupied hours or change the fan type to other than the `Fan:SystemModel`.

Issue post courtesy of Trane North America

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ((https://github.com/NREL/EnergyPlus/files/11279558/PackagedTerminalAirConditioner_NightCycle.idf.zip))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9971
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by rraustad — COMMENTED** [review]
This looks good. The UnitarySystem is now managing the availability manager flags for zone equipment instead of testing whether the parent is zone equipment and passing those flags in the fan call. This is one step closer to removing those optional arguments in the fan model, however, all zone equipment would need to manage these flags before those optional arguments could be removed from simulate fan.

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -11053,6 +11053,9 @@ namespace UnitarySystems {
         if (this->m_IsZoneEquipment) {
             turnFansOn = state.dataHVACGlobal->ZoneCompTurnFansOn;
             turnFansOff = state.dataHVACGlobal->ZoneCompTurnFansOff;
+            // set global flag to act on the fan operation
+            state.dataHVACGlobal->TurnFansOn = turnFansOn;
+            state.dataHVACGlobal->TurnFansOff = turnFansOff;
```
Comment (mjwitte) [inline src/EnergyPlus/UnitarySystem.cc:11058]: Wouldn't it be better to continue passing explicit flags to `SimulateFanComponents` instead of relying on a global signal?

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:11058]: But I guess we're not doing that in very many places. My concern is whether the global flags are getting reset properly after a particular piece of zone equipment (like here) touches them.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: I checked and the flags are managed properly for zone and air loop equipment. Whether we should set a flag or pass a flag is another question. I think doing it this way is cleaner, I don't have to check whether the fan is in zone equipment before calling the fan object. This is the same way Fan:SystemModel is handeled (i.e., don't check for zone equipment) which created this issue. Of course, this is up for debate.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Ok, as you were.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Maybe the parent object doesn't need to set these flags at all? Where ZoneCompTurnFansOn/Off are set in ZoneEquipmentManager, maybe these flags could be set there and unload the parent object completely from this little management piece.

Comment (Nigusse) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Quick search shows that these flag variables are set in [SimAirServingZones](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SimAirServingZones.cc#L2494-L2507) and [ZoneEquipmentManager](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneEquipmentManager.cc#L3105-L3122), elsewhere they are just.

Comment (Nigusse) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Except that we are resetting them in `UnitarySystem` now.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Yeah, I think if these are set at line 3123 in ZoneEquipmentManger:

    state.dataHVACGlobal->TurnFansOn = TurnFansOn;
    state.dataHVACGlobal->TurnFansOff = TurnFansOff;

and also reset these before the check of SAMs at line 3104 the result would be the same. The parent object could then use these flags to control the fan, that is, for those zone objects that use this flag to control the fan.

Maybe this type of change should be tested in a different branch? I guess it's a pretty small change so maybe it's worth a try.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: As I think about this more, I don't think the availability manager flags need to be seperate for zone and air loop equipment since zone equipment is called in their own loop, and airloop equipment is called in their own loop. Inside each of these loops the availability manager status is checked. So using a single set of flags should be adequate.

I don't expect this to be addressed in this branch.

Zone equipment:

    state.dataHVACGlobal->ZoneCompTurnFansOn
    state.dataHVACGlobal->ZoneCompTurnFansOn

Air loop equipment:

    state.dataHVACGlobal->TurnFansOn
    state.dataHVACGlobal->TurnFansOff

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Where does `CycleOnZoneFansOnly` fit into this?

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: IIRC, that is only used with zone exhaust fans.

Comment (mjwitte) [reply src/EnergyPlus/UnitarySystem.cc:11058]: > IIRC, that is only used with zone exhaust fans.

And PIU fans.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Yeah, maybe it's more complicated than first thought.

    bool PIUTurnFansOn =
        (state.dataHVACGlobal->TurnFansOn || state.dataHVACGlobal->TurnZoneFansOnlyOn); // If True, overrides fan schedule and cycles PIU fan on
    bool const PIUTurnFansOff = state.dataHVACGlobal->TurnFansOff; // If True, overrides fan schedule and PIUTurnFansOn and cycles PIU fan off

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Maybe it would be safer to save the correct avail manager flag in the UnitarySystem struct and always pass these 2 variables to the fan model? 

    if (this->isZoneEquipment) {
        this->availManagerTurnOn = state.dataHVACGlobal->ZoneCompTurnFansOn;
        this->availManagerTurnOff = state.dataHVACGlobal->ZoneCompTurnFansOff;
    } else {
        this->availManagerTurnOn = state.dataHVACGlobal->TurnFansOn;
        this->availManagerTurnOff = state.dataHVACGlobal->TurnFansOff;
    }

The PIU issue gives me some concern. What if there are 2 air loops, how is this single flag managed on the PIU call? It looks to me as if all zone equipment are simulated, and not by air loop. So I am wondering now if there is a problem with the PIU unit.

    for (int ControlledZoneNum = 1; ControlledZoneNum <= state.dataGlobal->NumOfZones; ++ControlledZoneNum) {

        auto &TurnFansOn = state.dataHVACGlobal->TurnFansOn;
        auto &TurnFansOff = state.dataHVACGlobal->TurnFansOff;
        auto &TurnZoneFansOnlyOn = state.dataHVACGlobal->TurnZoneFansOnlyOn;

            case ZoneEquip::AirDistUnit: { // 'ZoneHVAC:AirDistributionUnit'
                // Air loop system availability manager status only applies to PIU and exhaust fans
                // Check to see if System Availability Managers are asking for fans to cycle on or shut off
                // and set fan on/off flags accordingly.
                if (state.dataZoneEquip->ZoneEquipAvail(ControlledZoneNum) == DataHVACGlobals::CycleOn ||
                    state.dataZoneEquip->ZoneEquipAvail(ControlledZoneNum) == DataHVACGlobals::CycleOnZoneFansOnly) {
                    TurnFansOn = true;
                }
                if (state.dataZoneEquip->ZoneEquipAvail(ControlledZoneNum) == DataHVACGlobals::CycleOnZoneFansOnly) {
                    // Currently used only by parallel powered induction unit
                    TurnZoneFansOnlyOn = true;
                }
                if (state.dataZoneEquip->ZoneEquipAvail(ControlledZoneNum) == DataHVACGlobals::ForceOff) {
                    TurnFansOff = true;
                }

                ZoneAirLoopEquipmentManager::ManageZoneAirLoopEquipment(state,

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: I see, each air loop sets ZoneEquipAvail for each zone attached to the air loop. And this value is used to set TurnFansOn/Off in the above code for each PIU. This still leads me to believe only 1 set of global flags are needed but not sure at this point.

SystemAvailabilityManager.cc

            // loop over the zones served by the system and set the zone equipment availability
            for (ZoneInSysNum = 1; ZoneInSysNum <= state.dataAirLoop->AirToZoneNodeInfo(PriAirSysNum).NumZonesCooled; ++ZoneInSysNum) {

                CtrldZoneNum = state.dataAirLoop->AirToZoneNodeInfo(PriAirSysNum).CoolCtrlZoneNums(ZoneInSysNum);
                state.dataZoneEquip->ZoneEquipAvail(CtrldZoneNum) = state.dataAirLoop->PriAirSysAvailMgr(PriAirSysNum).AvailStatus;
            }

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: After what I learned on #9976, this is one correct fix. Using TurnFansOn/Off here will not impact any other equipment. This methodology is taken one step further in 9976 by removing these flags from fan calls. For now this works just fine.

**Review by rraustad — APPROVED** [review]
This change does correct this issue.

**Comment by rraustad** [comment]
@Nigusse are you finished with this issue? I'd like to get this out of the way so that #9976 is clear to merge. Is there a tweak to a unit test that you could add here to finish this up?

**Comment by Nigusse** [comment]
@rraustad I am working on unit test and should be ready in a couple of hours.

**Comment by Nigusse** [comment]
@rraustad added unit test and ran the unit test suite local and all passed.

File: tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc [hunk 2]
```diff
@@ -4681,4 +4683,391 @@ TEST_F(EnergyPlusFixture, ZonePTHP_ElectricityRateTest)
...
+    state->dataHVACGlobal->ZoneComp(ZoneEquipType).ZoneCompAvailMgrs(1).AvailStatus = DataHVACGlobals::CycleOn;
+    // run to set zone night cycle manager
+    ZoneEquipmentManager::SimZoneEquipment(*state, true, SimAir);
+    // test global zone fan control variables are turned on
+    EXPECT_TRUE(state->dataHVACGlobal->TurnFansOn);
+    EXPECT_FALSE(state->dataHVACGlobal->TurnFansOff);
+    EXPECT_TRUE(state->dataHVACGlobal->ZoneCompTurnFansOn);
+    EXPECT_FALSE(state->dataHVACGlobal->ZoneCompTurnFansOff);
+}
+
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc:5071]: Added unit test that illustrates the `state->dataHVACGlobal->TurnFansOn` and `state->dataHVACGlobal->TurnFansOff` variables are reset correctly.

File: src/EnergyPlus/UnitarySystem.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:11058]: Note that [this comment](https://github.com/NREL/EnergyPlus/pull/9974/files#r1174004991) is what spawned the work on #9976.

**Comment by rraustad** [comment]
The impact of night cycle is obvious on zone temp and matches what is shown in the issue description. The night cycle manager is operating.

image

**Review by rraustad — APPROVED** [review]
Code looks as expected and unit tests run to completion with develop pulled in.
