### PR TITLE
Warn when Pixel counting used with shading surface transmittance schedule

### LINKED ISSUE #9059: Unexpected behavior when using shading surfaces with transmittance schedule and PixelCounting
Issue overview
--------------
When using shading surfaces with a transmittance schedule and the PixelCounting shading calculation method, the transmittance schedule seems to be ignored and all surfaces are made fully opaque. To me this seems to be a bug or at least unexpected behavior. When using PolygonClipping the transmittance schedule works as expected.

### Details
Some additional details for this issue:
 - Windows 10
 - EnergyPlus 9.5 via OpenStudio 3.2.0 via Ladybug Tools 1.3.0 in Grasshopper.
 - As indicated on the Ladybug Tools Discourse [here](https://discourse.ladybug.tools/t/tip-dont-use-pixelcounting-in-combination-with-transmittance-schedule/15871)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9059 
 - This seems to be a high priority issue that needs to have proper severe warning messages when the pixel counting shading calculation method is used. In the scenario, due to the limitation of the underlying library used for pixel counting, the transmittance of the shading surfaces would not be taken into account. Currently, there does not seems to a solution for the fundamental issue in the underlying library that the pixel counting method is built on (according to the discussions in [#9059](https://github.com/NREL/EnergyPlus/issues/9059#issuecomment-1114998237). Warning messages are added to warn about this combination choice and potential inaccuracies in the simulation results. 
 - Also updated the "outdated" descriptions about the shading surfaces objects in the code comments.
 - Some "tuning" has been made in order for find a proper time to get the shadow calculation method input, since here this sequence does matter quite a bit---for example, some significant diffs or crashes could occur if the original calling sequence is disturbed. In the end, the problem was solved by adding a simplified version of shadow calculation input (and a separate flag variable) to handle the field of the the shadow calculation method field of the object---and this simplified version is only used in the surface geometry to retrieve the first input field of the ShadowCalculation object.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [x] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
image

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 1]
```diff
@@ -68,6 +68,7 @@
 #include <EnergyPlus/DataIPShortCuts.hh>
 #include <EnergyPlus/DataLoopNode.hh>
 #include <EnergyPlus/DataReportingFlags.hh>
+#include <EnergyPlus/DataSystemVariables.hh>
 #include <EnergyPlus/DataViewFactorInformation.hh>
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc]: This is added to allow access the shading method definition in `dataSysVars`.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 2]
```diff
@@ -84,6 +85,7 @@
 #include <EnergyPlus/OutputProcessor.hh>
 #include <EnergyPlus/OutputReportPredefined.hh>
 #include <EnergyPlus/ScheduleManager.hh>
+#include <EnergyPlus/SolarShading.hh>
 #include <EnergyPlus/SurfaceGeometry.hh>
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc:88]: This is added to access `GetShadowingInput()` defined in the Solar Shading module.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 3]
```diff
@@ -3280,52 +3283,64 @@ namespace SurfaceGeometry {
...
+        //        \minimum 3
+        //        \note Rules for vertices are given in GlobalGeometryRules coordinates --
+        //        \note For this object all surface coordinates are relative to the building origin (0,0,0)
+        //        \note and will rotate with the BUILDING north axis.
+        //   N2,  \field Vertex 1 X-coordinate
+        //        \begin-extensible
+        //        \required-field
+        //        \units m
+        //        \type real
+        //   N3-N361; as indicated by the N2 value
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc]: Update the comments description, since the IDD items quotes are quite out-dated.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 4]
```diff
@@ -3348,6 +3363,15 @@ namespace SurfaceGeometry {
...
+
+        if (state.dataSolarShading->GetInputFlag) {
+            SolarShading::GetShadowingInput(state);
+            state.dataSolarShading->GetInputFlag = false;
+            state.dataSolarShading->MaxHCV =
+                (((max(15, state.dataSurface->MaxVerticesPerSurface) + 16) / 16) * 16) - 1; // Assure MaxHCV+1 is multiple of 16 for 128 B alignment
+            assert((state.dataSolarShading->MaxHCV + 1) % 16 == 0);
+        }
+
         auto &cCurrentModuleObject = state.dataIPShortCut->cCurrentModuleObject;
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc:3297]: This is needed since in the original running sequence, the shadow calculation module inputs are not processed yet when the surface geometry input processing is conducted. Therefore, need to first process the shadow calculation inputs first. Flag is set so this operation does not need to duplicated in later encounters.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 5]
```diff
@@ -3411,6 +3435,21 @@ namespace SurfaceGeometry {
...
+                                                   state.dataIPShortCut->cAlphaFieldNames(2),
+                                                   state.dataIPShortCut->cAlphaArgs(2)));
+                            ShowContinueError(state, "The Shading Calculation Method of choice is \"PixelCounting\". With this choice, ");
+                            ShowContinueError(
+                                state,
+                                "the shading surfaces will be treated as completely opaque (transmittance = 0) during the shading calculation, ");
+                            ShowContinueError(state, "which may result in significant inaccurate or unexpected results.");
+                            ShowContinueError(state, "It is suggested to use another Shading Calculation Method, such as \"PolygonClipping\".");
+                        }
                     }
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc]: This is the adequate location to add the warning, for the `Detached` shading surfaces types.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 6]
```diff
@@ -6328,33 +6368,40 @@ namespace SurfaceGeometry {
...
+        //        \minimum 3
+        //        \note vertices are given in GlobalGeometryRules coordinates -- if relative, all surface coordinates
+        //        \note are "relative" to the Zone Origin. if world, then building and zone origins are used
+        //        \note for some internal calculations, but all coordinates are given in an "absolute" system.
+        //   N2,  \field Vertex 1 X-coordinate
+        //        \begin-extensible
+        //        \required-field
+        //        \units m
+        //        \type real
+        //   N3-N361; as indicated by the N2 value
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc]: Update IDD items quotations again. Now for the attached shading surface type.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 7]
```diff
@@ -6372,6 +6419,14 @@ namespace SurfaceGeometry {
...
         Real64 SchedMaxValue;
 
+        if (state.dataSolarShading->GetInputFlag) {
+            SolarShading::GetShadowingInput(state);
+            state.dataSolarShading->GetInputFlag = false;
+            state.dataSolarShading->MaxHCV =
+                (((max(15, state.dataSurface->MaxVerticesPerSurface) + 16) / 16) * 16) - 1; // Assure MaxHCV+1 is multiple of 16 for 128 B alignment
+            assert((state.dataSolarShading->MaxHCV + 1) % 16 == 0);
+        }
+
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc]: Same logic above for the detached shading surfaces. The shadow calculation methods input needs to be process first before executing logic for the warning. This will make sure the shadow calculation inputs has been processed first and the state variable will have updated value to ensure the logic outcome is determined using correct values.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 8]
```diff
@@ -6458,6 +6513,20 @@ namespace SurfaceGeometry {
...
+                                               state.dataSurfaceGeometry->SurfaceTmp(SurfNum).Name,
+                                               state.dataIPShortCut->cAlphaFieldNames(3),
+                                               state.dataIPShortCut->cAlphaArgs(3)));
+                        ShowContinueError(state, "The Shading Calculation Method of choice is \"PixelCounting\". With this choice, ");
+                        ShowContinueError(
+                            state, "the shading surfaces will be treated as completely opaque (transmittance = 0) during the shading calculation, ");
+                        ShowContinueError(state, "which may result in significant inaccurate or unexpected results.");
+                        ShowContinueError(state, "It is suggested to use another Shading Calculation Method, such as \"PolygonClipping\".");
+                    }
                 }
```
Comment (jcyuan2020) [inline src/EnergyPlus/SurfaceGeometry.cc]: This is the adequate location to add the warning for attached shading surfaces.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 9]
```diff
@@ -3476,3 +3477,405 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CTRANS)
...
+        "    Suburbs,                 !- Terrain",
+        "    3.9999999E-02,           !- Loads Convergence Tolerance Value",
+        "    4.0000002E-03,           !- Temperature Convergence Tolerance Value {deltaC}",
+        "    FullExterior,            !- Solar Distribution",
+        "    ,                        !- Maximum Number of Warmup Days",
+        "    6;                       !- Minimum Number of Warmup Days",
+
+        "  ShadowCalculation,",
+        "    PixelCounting, !-Shading Calculation Method",
+        "    Periodic, !-Shading Calculation Update Frequency Method",
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:3499]: Unit test. Here the `PixelCounting` method is used.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 10]
```diff
@@ -3476,3 +3477,405 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CTRANS)
...
+        "    1.2,                     !- Ratio of Divider-Edge Glass Conductance to Center-Of-",
+        "    0.8,                     !- Divider Solar Absorptance",
+        "    0.8,                     !- Divider Visible Absorptance",
+        "    0.9;                     !- Divider Thermal Hemispherical Emissivity",
+
+        "  Shading:Zone:Detailed,",
+        "    Zn001:Wall-South:Shade001,  !- Name",
+        "    Zn001:Wall-South,        !- Base Surface Name",
+        "    SunShading,              !- Transmittance Schedule Name",
+        "    4,                       !- Number of Vertices",
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:3813]: Here it is an attached shading surface with scheduled transmittance values.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 11]
```diff
@@ -3476,3 +3477,405 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CTRANS)
...
+
+        "  ShadingProperty:Reflectance,",
+        "    Zn001:Wall-South:Shade001,  !- Shading Surface Name",
+        "    0.2,                     !- Diffuse Solar Reflectance of Unglazed Part of Shading",
+        "    0.2;                     !- Diffuse Visible Reflectance of Unglazed Part of Shading",
+
+        "  Shading:Site:Detailed,",
+        "    Zn001:Wall-South:Shade002,  !- Name",
+        "    SunShading,              !- Transmittance Schedule Name",
+        "    4,                       !- Number of Vertices",
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:3827]: Here it is a detached shading surface with scheduled transmittance values.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 12]
```diff
@@ -3476,3 +3477,405 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CTRANS)
...
+    SurfaceGeometry::GetSurfaceData(*state, FoundError);
+    EXPECT_FALSE(FoundError);
+
+    EXPECT_EQ(state->dataErrTracking->TotalWarningErrors, 1);
+    // Expect to have two severre errors, one for the detached Shading:Site:Detailed, and one for the attached Shading:Zone:Detailed
+    EXPECT_EQ(state->dataErrTracking->TotalSevereErrors, 2);
+    // The attached one will be the last severe error, since the "attached" function is called later than the "detached" one.
+    EXPECT_EQ(state->dataErrTracking->LastSevereError,
+              "Shading:Zone:Detailed=\"ZN001:WALL-SOUTH:SHADE001\" has an active Transmittance Schedule Name=\"SUNSHADING\";");
+
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:3874]: Expect to have two severe errors, one for the detached `Shading:Site:Detailed`, and one for the attached `Shading:Zone:Detailed`. 

The attached one will be the last severe error, since the "attached" function is called later than the "detached" one.

**Review by jcyuan2020 — COMMENTED** [review]
Code walk-through.

File: src/EnergyPlus/SolarShading.cc [hunk 13]
```diff
@@ -359,6 +359,71 @@ void InitSolarCalculations(EnergyPlusData &state)
...
+            state.dataSysVars->shadingMethod = ShadingMethod::PixelCounting;
+        } else {
+            //
+        }
+    } else {
+        state.dataSysVars->shadingMethod = ShadingMethod::PolygonClipping;
+    }
+}
+
 void GetShadowingInput(EnergyPlusData &state)
```
Comment (jcyuan2020) [inline src/EnergyPlus/SolarShading.cc:362]: Finally had to resort to adding a simplified version of input processing just for getting shadow calculation method (which belongs to the solar calculation module) to be used in the surface geometry processing stage, when a full-blown shadow ShadowCalculation input function would be premature and causing some problems (at least in some existing unit tests).

File: src/EnergyPlus/SolarShading.hh [hunk 14]
```diff
@@ -542,6 +545,7 @@ struct SolarShadingData : BaseGlobalStruct
         this->ShadowingDaysLeft = 0;      // Days left in current shadowing period
         this->debugging = false;
         this->GetInputFlag = true;
+        this->GetInputFlagforSurfGeom = true;
         this->firstTime = true;
```
Comment (jcyuan2020) [inline src/EnergyPlus/SolarShading.hh:547]: Add a separate flag for the added simplified input processing function, so no interfering with the main one.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 7 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc]: After last change and comments: Except now that it is calling a stripped-down version of input processing other than the full-blown one.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 4 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc:3297]: After the last batch of changes and comments: Except now that it is calling a stripped-down version of input processing other than the full-blown one.

**Review by jcyuan2020 — COMMENTED** [review]
Another walk-through on changes added after the last walk-through about two days ago.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 15]
```diff
@@ -3280,52 +3283,64 @@ namespace SurfaceGeometry {
 
         // REFERENCES:
         // Detached Shading Surface Definition(s)
-        // Surface:Shading:Detached:Fixed,
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:3283]: These types of comments can be deleted entirely.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 16]
```diff
@@ -6318,6 +6354,7 @@ namespace SurfaceGeometry {
         //       DATE WRITTEN   May 2000
         //       MODIFIED       na
         //       RE-ENGINEERED  na
+        //       ADDED WARNINGS and UPDATED DESCRIPTIONS in Sep 2022
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc]: we no longer add comments like this, you can also delete the ones with na.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 17]
```diff
@@ -3270,7 +3272,8 @@ namespace SurfaceGeometry {
         //       DATE WRITTEN   May 2000
         //       MODIFIED       na
         //       RE-ENGINEERED  na
-
+        //       ADDED WARNINGS and UPDATED DESCRIPTIONS in Sep 2022
+        //
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc]: Delete these.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 4 above)
Comment (mjwitte) [reply src/EnergyPlus/SurfaceGeometry.cc:3297]: Rather than adding a new function to partially process the ShadowCalculation method, it would be better to move the check to somewhere else after the normal input processing occurs. A simple approach would be to set a single flag values for something like `state.dataSolarShading->anyScheduledShadingSurface` and check that at the time PixelCounting is processed in it's full getinput.  I don't think it's necessary to warn for every shading surface that has a schedule.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 5 above)
Comment (mjwitte) [reply src/EnergyPlus/SurfaceGeometry.cc]: I would move this (well, move setting the global flag) to a separate `if(SchedMaxValue > 0.0) state.dataSolarShading->anyScheduledShadingSurface = true;`
If a surface has a transmittance schedule that is always zero, there's no need to warn, it will be opaque anyway.

File: tst/EnergyPlus/unit/SolarShading.unit.cc (hunk 12 above)
Comment (jcyuan2020) [reply tst/EnergyPlus/unit/SolarShading.unit.cc:3874]: With the new method implemented, there is only one severe message expected and it should come from `SolarShading::GetShadowingInput()`.

File: src/EnergyPlus/SolarShading.cc (hunk 13 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SolarShading.cc:362]: Use a new method suggested by the reviewer, now this new function is no longer needed.

File: src/EnergyPlus/SolarShading.cc [hunk 18]
```diff
@@ -485,6 +550,17 @@ void GetShadowingInput(EnergyPlusData &state)
...
+        ShowSevereError(state, "The Shading Calculation Method of choice is \"PixelCounting\";");
+        ShowContinueError(state, "and there is at least one shading surface of type ");
+        ShowContinueError(state, "Shading:Site:Detailed, Shading:Building:Detailed, or Shading:Zone:Detailed,");
+        ShowContinueError(state, "that has an active transmittance schedule value greater than zero.");
+        ShowContinueError(state, "With \"PixelCounting\" Shading Calculation Method, the shading surfaces will be treated as completely opaque (transmittance = 0) during the shading calculation, ");
+        ShowContinueError(state, "which may result in inaccurate or unexpected results.");
+        ShowContinueError(state, "It is suggested to use another Shading Calculation Method, such as \"PolygonClipping\".");
+    }
+
     aNum++;
```
Comment (jcyuan2020) [inline src/EnergyPlus/SolarShading.cc:497]: Implemented with the method suggested by the reviewer. The severe warning will now be reported only once; and only for shading surfaces that ACTUALLY has some transmittance value great than 0.0.

File: src/EnergyPlus/SolarShading.hh (hunk 14 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SolarShading.hh:547]: New implementation: the `anyScheduledShadingSurface` flag

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 5 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc]: Thanks! @mjwitte This method is now implemented.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 16 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc]: Will do a final clean up after testing all the changes.

**Review by jcyuan2020 — COMMENTED** [review]
@mjwitte Thanks for suggesting the new method. It is now implemented and the unit test is also updated based on that. Will do some clean-up in the final step.

File: src/EnergyPlus/SolarShading.cc [hunk 19]
```diff
@@ -485,6 +550,17 @@ void GetShadowingInput(EnergyPlusData &state)
         state.dataSysVars->shadingMethod = ShadingMethod::PolygonClipping;
     }
 
+    if (state.dataSysVars->shadingMethod == DataSystemVariables::ShadingMethod::PixelCounting &&
+        state.dataSolarShading->anyScheduledShadingSurface == true) {
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc]: Don't need `== true` here.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 20]
```diff
@@ -68,6 +68,7 @@
 #include <EnergyPlus/DataIPShortCuts.hh>
 #include <EnergyPlus/DataLoopNode.hh>
 #include <EnergyPlus/DataReportingFlags.hh>
+#include <EnergyPlus/DataSystemVariables.hh>
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc]: Is this still needed?

**Review by mjwitte — COMMENTED** [review]
@jcyuan2020 Much better! A couple more comments.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 20 above)
Comment (jcyuan2020) [reply src/EnergyPlus/SurfaceGeometry.cc]: Thanks! The two comments above are now addressed in a new commit, plus the code clean up.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 5 above)
Comment (rraustad) [reply src/EnergyPlus/SurfaceGeometry.cc]: Then this else can be removed?

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/SurfaceGeometry.cc]: And this else can be removed?

**Comment by rraustad** [comment]
Using Modified-ReflectiveAdjacentBuilding.idf test file shows severe/non-fatal warning with non-ideal inputs:

    ShadowCalculation,
      PixelCounting,         !- Shading Calculation Method
      Periodic,                !- Shading Calculation Update Frequency Method
      30;                      !- Shading Calculation Update Frequency

    Schedule:Compact,
      ShadowTrans,             !- Name
      Any Number,              !- Schedule Type Limits Name
      Through: 12/31,          !- Field 1
      For: Alldays,            !- Field 2
      Until: 24:00,0.50;       !- Field 3

    Shading:Site:Detailed,
      REFLECTIVE FACADE TO NORTH,  !- Name
    !    ,                        !- Transmittance Schedule Name
      ShadowTrans,                        !- Transmittance Schedule Name

[Modified-ReflectiveAdjacentBuilding.idf.txt](https://github.com/NREL/EnergyPlus/files/9568411/Modified-ReflectiveAdjacentBuilding.idf.txt)

    ** Severe  ** The Shading Calculation Method of choice is "PixelCounting"; 
    **   ~~~   ** and there is at least one shading surface of type 
    **   ~~~   ** Shading:Site:Detailed, Shading:Building:Detailed, or Shading:Zone:Detailed, 
    **   ~~~   ** that has an active transmittance schedule value greater than zero.
    **   ~~~   ** With "PixelCounting" Shading Calculation Method, the shading surfaces will be treated as 
    **   ~~~   ** completely opaque (transmittance = 0) during the shading calculation, 
    **   ~~~   ** which may result in inaccurate or unexpected results.
    **   ~~~   ** It is suggested switching to another Shading Calculation Method, such as "PolygonClipping".

Setting ShadowTrans schedule value = 0.0: no warning
Leaving Shading:Site:Detailed Transmittance Schedule Name blank: no warning

New unit test:

image

File: src/EnergyPlus/SolarShading.cc (hunk 18 above)
Comment (rraustad) [reply src/EnergyPlus/SolarShading.cc:497]: The method to report this method is as clean as could be expected. This has been tested and works as expected.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 15 above)
Comment (rraustad) [reply src/EnergyPlus/SurfaceGeometry.cc:3283]: Code cleaned up along the way.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 21]
```diff
@@ -3440,6 +3386,9 @@ namespace SurfaceGeometry {
                                             "\", has schedule values < 0.");
                         ShowContinueError(state, "...Schedule values < 0 have no meaning for shading elements.");
                     }
+                    if (SchedMaxValue > 0.0) {
+                        state.dataSolarShading->anyScheduledShadingSurface = true;
+                    }
```
Comment (rraustad) [inline src/EnergyPlus/SurfaceGeometry.cc:3391]: Simple method used to determine when warnings are reported.

File: tst/EnergyPlus/unit/SolarShading.unit.cc [hunk 22]
```diff
@@ -3476,3 +3477,411 @@ TEST_F(EnergyPlusFixture, SolarShadingTest_CTRANS)
...
+    // Expect no severe errors at this point
+    EXPECT_EQ(state->dataErrTracking->TotalSevereErrors, 0);
+
+    SolarShading::GetShadowingInput(*state);
+
+    EXPECT_EQ(state->dataErrTracking->TotalWarningErrors, 0);
+    // Now expect one severe error from GetShadowInput()
+    EXPECT_EQ(state->dataErrTracking->TotalSevereErrors, 1);
+    // There should be a severe warning reported about the PixelCounting and the scheduled shading surface tm values > 0.0 combination.
+    EXPECT_EQ(state->dataErrTracking->LastSevereError, "The Shading Calculation Method of choice is \"PixelCounting\"; ");
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SolarShading.unit.cc:3886]: Expected results in unit test.

**Review by rraustad — APPROVED** [review]
CI should come back clean.

**Comment by rraustad** [comment]
Diffs from #9639 are showing up here, at least on Mac CI.

**Comment by rraustad** [comment]
I get 0 diffs on local Windows regressions. Not sure if I should update the branch and run this again just to see clean CI diffs.

**Comment by rraustad** [comment]
@Myoldmopar this is reviewed and approved. The Mac diffs are from the merge of #9639 after the final commit of this branch. I see no need for another round of CI.

**Comment by Myoldmopar** [comment]
I concur, this is good.  Thanks @jcyuan2020 and @rraustad, merging.

**Comment by Myoldmopar** [comment]
A unit test failure accidentally made it into develop from this branch.  At least on Windows...everything passes fine for me on Linux.

@jcyuan2020 or @rraustad are you able to reproduce this unit test failure?  https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-e7d2f8748448aef9dc9de39710cc0f2ad6eeb604-Win64-Windows-10-VisualStudio-16.html

**Comment by rraustad** [comment]
I ran the unit tests successfully before. I will check again and open a new PR if needed.

**Comment by rraustad** [comment]
Well, I don't see a failure.

From CI:

image

From my local PC (release):

image

**Comment by Myoldmopar** [comment]
Yeah...smells suspicious given the GPU file _sometimes_ shows diffs.  Feels like something being used uninitialized in there.  @nealkruis ?

**Comment by jcyuan2020** [comment]
I also just tested it on my local PC and it passed. However, I think one possible explanation is due to the Preprocessor Directives here:
https://github.com/NREL/EnergyPlus/blob/681a49cc9b89de6b26b05202212af28073f3b139/src/EnergyPlus/SolarShading.cc#L449

If the CI machine is of different architecture and has this directive activated (No OpenGL), the shading method would be reset to "PolygonClipping" instead. And the unit test results will exactly match what CI failure message says.

There might be another one here but I think the one above is more likely the one that's actually got activated in the CI:
https://github.com/NREL/EnergyPlus/blob/681a49cc9b89de6b26b05202212af28073f3b139/src/EnergyPlus/SolarShading.cc#L456

If this is the issue, then the fix would probably be to included the same Preprocessor Diretives branches in the unit test (feasible?); and then test the different outcomes from there. And it has to be tested in a new PR and in the CI to know if it works.

**Comment by Myoldmopar** [comment]
@jcyuan2020 you want to try to demonstrate it?  If we know for sure that addresses it, it would be an easier discussion on the best path forward.

**Comment by jcyuan2020** [comment]
Sure, I am actually trying it out to see if it could work.

**Comment by rraustad** [comment]
Can we use the same directives in the unit test?

**Comment by jcyuan2020** [comment]
Looks like a Yes---this is being tested in #9659.
