### PR TITLE
Fix EMS pump pressure override crash

### LINKED ISSUE #10318: EMS cannot override Headered Pumps Head correctly
When we try to override Pump Pressure Rise of HeaderedPumps:VariableSpeed or HeaderedPumps:ConstantSpeed with any value by EMS, Pump Electricity Rate becomes almost 0 W, probably because Pump Pressure Rise becoms almost 0 Pa.
Please refer to the Unmethours link below for more details.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus: V23-2-0
 - Unmethours link: [EMS cannot override Headered Pumps Head correctly](https://unmethours.com/question/97640/ems-cannot-override-headered-pumps-head-correctly/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (Please refer to the unmethours link above.)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
 - Fixes #10318 
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

The EMS pump pressure override caused E+ crash in the Debug run. The pump power was zero before a fix. The cause is no initialization for a local variable. The outputs of pump power are correct after the fix.   

The code change is very obvious, so that no code walk through is provided.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ X] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [X ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [X ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/Pumps.cc [hunk 1]
```diff
@@ -1919,6 +1919,9 @@ void CalcPumps(EnergyPlusData &state, int const PumpNum, Real64 const FlowReques
         FracFullLoadPower = thisPump.PartLoadCoef[0] + thisPump.PartLoadCoef[1] * PartLoadRatio + thisPump.PartLoadCoef[2] * pow_2(PartLoadRatio) +
                             thisPump.PartLoadCoef[3] * pow_3(PartLoadRatio);
         daPumps->Power = (FullLoadPowerRatio * daPumps->NumPumpsFullLoad + FracFullLoadPower) * FullLoadPower;
+        if (thisPump.EMSPressureOverrideOn) {
+            VolFlowRate = PartLoadVolFlowRate;
+        }
```
Comment (Myoldmopar) [inline src/EnergyPlus/Pumps.cc:1924]: How does the EMS Pressure override value end up meaning the pump should operate at `PartLoadVolFlowRate`?

**Comment by Myoldmopar** [comment]
I'd like this fixed, but I am still unsure about how the logic works.  If the EMS actuator is ON, it ends up using a different variable value to assign the flow rate?  I would have thought it would use the EMS actuated value?  Maybe I'm missing something.  I'm going to reassign this for later but if it gets discussed/addressed, it can still sneak in.

File: src/EnergyPlus/Pumps.cc (hunk 1 above)
Comment (lgu1234) [reply src/EnergyPlus/Pumps.cc:1924]: @Myoldmopar I think the PartLoadVolFlowRate is the flow rate from the pump based on load. When the power is calculated, it should be flowrate * Pressure head / motor efficiency. In other words, the current flow rate should be used, instead of full load flow rate. Of course, when EMS is used, the override pressure head can be a constant or variable, which depends on user input. We may discuss this issue in the next technicalities call.

**Comment by nrel-bot-2** [comment]
@lgu1234 @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/Pumps.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/Pumps.cc:1924]: OK.  So just use values that would have been calculated from an overridden pressure head.  This makes sense in general, and I am willing to accept it.  Anyone else have any comments here before this moves toward merge?

**Comment by Myoldmopar** [comment]
Alright, I pulled in develop and will get fresh results to confirm things, then this should be good to go.

**Comment by Myoldmopar** [comment]
All good here.  CI is happy other than an unrelated Windows warning.  I'll get this one merged in.  Thanks @lgu1234
