### PR TITLE
Fix for 11016; Set correct water flow rate of companion cooling coils for WAHP applications using the `AirloopHVAC:UnitarySystem`

### LINKED ISSUE #11016: No water flow rate during cooling operation when heating coil water flow rate is hardsized
### Issue overview

When using an `AirLoopHVAC:UnitarySystem` with `Coil:*:WaterToAirHeatPump:EquationFit` coil objects and when the heating coil water flow rate is hard sized, the cooling water flow rate is always 0.

### Operating System (Multiple choices)

Windows

### Operating System Version

11

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[unit_system_defect.zip](https://github.com/user-attachments/files/19554186/unit_system_defect.zip)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11016: Fix for; Set correct water flow rate of companion cooling coils for WAHP applications using the `AirloopHVAC:UnitarySystem`.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lymereJ** [comment]
Water flow rate for the defect file ...

... With the current develop:
current_develop

... With this branch:
with_fix

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc [hunk 1]
```diff
@@ -2957,18 +2957,17 @@ namespace WaterToAirHeatPumpSimple {
...
+                } else {
+                    companionCoolingCoil.RatedWaterVolFlowRate = simpleWatertoAirHP.RatedWaterVolFlowRate;
                     PlantUtilities::RegisterPlantCompDesignFlow(
                         state, companionCoolingCoil.WaterInletNodeNum, 0.5 * simpleWatertoAirHP.RatedWaterVolFlowRate);
                 }
-            } else if (simpleWatertoAirHP.WAHPType == WatertoAirHP::Cooling) {
-                PlantUtilities::RegisterPlantCompDesignFlow(
-                    state, simpleWatertoAirHP.WaterInletNodeNum, 0.5 * simpleWatertoAirHP.RatedWaterVolFlowRate);
             }
+            PlantUtilities::RegisterPlantCompDesignFlow(state, simpleWatertoAirHP.WaterInletNodeNum, 0.5 * simpleWatertoAirHP.RatedWaterVolFlowRate);
```
Comment (lymereJ) [inline src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2901]: This routine is called sequentially for each coil, so set the flow rate of each coil based on the larger of the two companion coils.

**Review by lymereJ — COMMENTED** [review]
Walkthrough:

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2901]: This is off topic but if the Sizing:Plant object uses different delta T's shouldn't the flow rate in each operating mode be different (i.e., to actually operate at the Sizing:Plant delta T specified)? This is of course outside the scope of this issue but I think it's important to think of things like that. I guess it would be good to check manufacturers data to see if different water flow rates are ever possible or if 2-speed pumps are ever used. Using the same flow rate for cooling and heating does seem like the right choice. Although I do wonder if there are times when the first coil would post it's result to the eio before the companion coil got a chance to update the water flow rate?

Comment (lymereJ) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2901]: I could very well be wrong but I don't think that this issue could arise. Stepping through the debugger I see that, when we have companion coils, because the cooling coil is always evaluated first and its final capacity is only fully determined after the heating coil has been sized, I think that the process to output the flow to the EIO file is only done then (meaning after both coils have been sized) and only once.

On a different note, I see comments in the block of code above this one related to the system capacity used to determined the flow rate. I think these comments are valid: we're currently using the evaporator capacity but we should use the condenser capacity. Should a different PR be created to address these?

Comment (rraustad) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2901]: I would create a different PR for changing the condenser flow sizing method.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lymereJ @myoldmopar it has been 29 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @lymereJ @myoldmopar it has been 35 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lymereJ @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lymereJ @myoldmopar it has been 42 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@Myoldmopar @lymereJ @myoldmopar it has been 33 days since this pull request was last updated.

File: src/EnergyPlus/WaterToAirHeatPumpSimple.cc (hunk 1 above)
Comment (mitchute) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2901]: @rraustad anything else to look at here?

Comment (rraustad) [reply src/EnergyPlus/WaterToAirHeatPumpSimple.cc:2901]: I think this is worthy of slight pressure on the green button below.
