### PR TITLE
Fix EIO airflow and capacity reporting for `Coil:Cooling:DX:Multispeed`

### LINKED ISSUE #10035: `Coil:Cooling:DX:Multispeed` air flow rate and capacity is mislabeled in EIO file
Issue overview
--------------
The air flow rate at each speed is mislabeled for `Coil:Cooling:DX:Multispeed` objects.

For example, the following is currently reported for the "defect" file.

```
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 4 Gross Rated Total Cooling Capacity [m3/s], 0.22951
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 3 Gross Rated Sensible Heat Ratio [m3/s], 0.17213
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 2 Gross Rated Cooling COP [m3/s], 0.11475
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Rated Air Flow Rate [m3/s], 5.73769E-002
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 3 Evaporative Condenser Effectiveness [W], 5699.22359
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 2 Evaporative Condenser Air Flow Rate [W], 4274.41769
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Rated Evaporative Condenser Pump Power Consumption [W], 2849.61179
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Gross Rated Total Cooling Capacity [W], 1424.80590
``` 

The following should be reported:
```
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 4 Rated Air Flow Rate [m3/s], 0.22951
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 3 Rated Air Flow Rate [m3/s], 0.17213
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 2 Rated Air Flow Rate [m3/s], 0.11475
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Rated Air Flow Rate [m3/s], 5.73769E-002
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 4 Gross Rated Total Cooling Capacity [W], 5699.22359
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 3 Gross Rated Total Cooling Capacity [W], 4274.41769
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 2 Gross Rated Total Cooling Capacity [W], 2849.61179
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Gross Rated Total Cooling Capacity [W], 1424.80590
```

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 11
 - Version of EnergyPlus: 23.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [in.txt](https://github.com/NREL/EnergyPlus/files/11527153/in.txt)
 - [x] Pull request created

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------
 - Fixes #10035 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by lymereJ** [comment]
Content of the EIO file after fix for the defect file. We see the same changes in the EIO diffs.

```
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 4 Rated Air Flow Rate [m3/s], 0.22951
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 3 Rated Air Flow Rate [m3/s], 0.17213
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 2 Rated Air Flow Rate [m3/s], 0.11475
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Rated Air Flow Rate [m3/s], 5.73769E-002
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 4 Gross Rated Total Cooling Capacity [W], 5699.22359
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 3 Gross Rated Total Cooling Capacity [W], 4274.41769
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 2 Gross Rated Total Cooling Capacity [W], 2849.61179
 Component Sizing Information, Coil:Cooling:DX:MultiSpeed, SYS 3 HEAT PUMP AIR SOURCE COOLING COIL, Design Size Speed 1 Gross Rated Total Cooling Capacity [W], 1424.80590
```

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -7963,7 +7963,7 @@ void SizeDXCoil(EnergyPlusData &state, int const DXCoilNum)
             CompName = thisDXCoil.Name;
             CompType = thisDXCoil.DXCoilType;
             if (Mode == thisDXCoil.NumOfSpeeds) {
-                FieldNum = 10 + (Mode - 1) * 13;
+                FieldNum = 10 + (Mode - 1) * 14;
```
Comment (lymereJ) [inline src/EnergyPlus/DXCoils.cc]: A new input was recently added so a change in the increment needed to be changed.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 2]
```diff
@@ -3585,6 +3585,35 @@ TEST_F(EnergyPlusFixture, TestMultiSpeedCoilsAutoSizingOutput)
...
+            " Component Sizing Information, Coil:Cooling:DX:MultiSpeed, ASHP CLG COIL, Design Size Speed 2 Rated Evaporative Condenser Pump Power "
+            "Consumption [W], 139.63434",
+            "! <DX Cooling Coil Standard Rating Information>, Component Type, Component Name, Standard Rating (Net) Cooling Capacity {W}, Standard "
+            "Rated Net COP {W/W}, EER {Btu/W-h}, SEER User {Btu/W-h}, SEER Standard {Btu/W-h}, IEER {Btu/W-h}",
+            " DX Cooling Coil Standard Rating Information, Coil:Cooling:DX:MultiSpeed, ASHP CLG COIL, 31065.3,  ,  , 16.52, 16.03,  ",
+            " DX Cooling Coil Standard Rating Information, Coil:Cooling:DX:MultiSpeed, ASHP CLG COIL, 30783.3, 3.66, 12.50, 15.20, 15.30, "
+            "11.950323501582877",
+        },
+        delim);
+    EXPECT_TRUE(compare_eio_stream(clg_coil_eiooutput, true));
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: Testing that the EIO output is correct.

File: src/EnergyPlus/DXCoils.cc [hunk 3]
```diff
@@ -8085,7 +8085,7 @@ void SizeDXCoil(EnergyPlusData &state, int const DXCoilNum)
                 // cooling capacity at lower speeds
                 PrintFlag = true;
                 SizingMethod = CoolingCapacitySizing;
-                FieldNum = 7 + (Mode - 1) * 13;
+                FieldNum = 7 + (Mode - 1) * 14;
```
Comment (Myoldmopar) [inline src/EnergyPlus/DXCoils.cc:8088]: :+1:

File: tst/EnergyPlus/unit/DXCoils.unit.cc (hunk 2 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/DXCoils.unit.cc]: Where possible, I would just compare against a raw string literal, like:

```
constexpr std::string_view clg_coil_eio = R"EIO(! <Component Sizing Information>, Component Type, Component Name, Input Field Description, Value
Component Sizing Information, Coil:Cooling:DX:MultiSpeed, ASHP CLG COIL, Design Size Speed 2 Rated Air Flow Rate [m3/s], 1.75000
Component Sizing Information, Coil:Cooling:DX:MultiSpeed, ASHP CLG COIL, Design Size Speed 1 Rated Air Flow Rate [m3/s], 0.87500
...etc...
 DX Cooling Coil Standard Rating Information, Coil:Cooling:DX:MultiSpeed, ASHP CLG COIL, 30783.3, 3.66, 12.50, 15.20, 15.30, 11.950323501582877)EIO"

EXPECT_TRUE(compare_eio_stream(clg_coil_eio, true));
```

I _think_ we can use a string_view there, but if not just a const string is a reasonable compromise...for now :)

I'm going to pull develop into this branch anyway to get some clean CI results.  I think I'll make this change before pushing.

**Review by Myoldmopar — COMMENTED** [review]
This seems like a straightforward change.  I'm going to do a quick cleanup on the EIO text and pull in develop to get clean results.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 4]
```diff
@@ -3579,6 +3579,24 @@ TEST_F(EnergyPlusFixture, TestMultiSpeedCoilsAutoSizingOutput)
     // Design Capacity at speed 2 and speed 1
     EXPECT_NEAR(32731.91, state->dataDXCoils->DXCoil(1).MSRatedTotCap(2), 0.01);
     EXPECT_NEAR(16365.95, state->dataDXCoils->DXCoil(1).MSRatedTotCap(1), 0.01);
+    // Check EIO reporting
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/DXCoils.unit.cc:3582]: @lymereJ OK, I just pushed a commit to this branch which uses raw string literals for comparing chunks of text rather than the delimited string approach.  I came across one "gotcha", and I'm going to tag a few other people who write a lot of unit tests so they see what is going on.

@rraustad @mjwitte @Nigusse 

In a unit test, if you want to compare a multiline bit of text, such as an EIO section, raw string literals are nice:

```c++
std::string const eio_text = R"EIO(First Line
Second Line
Third Line
)EIO";
EXPECT_TRUE(compare_eio_stream(eio_text));
```

This makes it very easy to paste in a chunk of EIO text without having to worry about the delimited string calls and breaking it up into individual quoted lines.

However, there is one gotcha, which is if the section of raw text has a trailing string, as this example does after the 16.03 on the next to last line.  Most editors will try to clean off trailing spaces from lines, which is problematic, because now this chunk of raw text won't exactly match.  We could have a discussion about whether the EIO should have trailing spaces, but that's for a different day.  For now, you'll notice it doesn't actually have trailing spaces -- it has pipe symbols "||".  This rarely used character is used as a placeholder for the trailing spaces so that the editor won't chop them off.  I then added a tiny worker function in the unit test fixture to replace them at runtime with spaces, so that the unit test matches.  So now it is:

```c++
std::string const eio_text = R"EIO(First Line
Second Line with 3 trailing spaces|||
Third Line with 1 trailing space|
)EIO";
replace_pipes_with_spaces(eio_text);
EXPECT_TRUE(compare_eio_stream(eio_text));
```

File: tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh [hunk 5]
```diff
@@ -265,6 +265,22 @@ protected:
...
+        // For example, if you have an EIO output to compare, you can just paste it right into a variable and compare
+        // However, if the raw literal has trailing spaces on any line, editors tend to remove them
+        // I tried disabling clang-format for sections of code, I tried using an .editorconfig file, and still
+        // the editor would remove them on saving the file.  And for my editor, I _can_ disable that, but only for all
+        // files, which is not preferred.  We do want trailing spaces stripped, just not inside raw string literals.
+        // Anyway, the solution I came up with is a small worker function here.  In the string literal, just put in
+        // pipe characters ( "|" ) where the trailing spaces would be.  Then pass your string literal into this
+        // function, and it will programmatically replace them with strings.  You can then do asserts as needed.
+        std::replace(stringLiteral.begin(), stringLiteral.end(), '|', ' '); // replace the trailing || with spaces
+    }
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh:282]: This could be made a bit more general purpose, but I think the simpler the better in this case.  This should help clean up the long chunks of delimited strings and allow them to be raw string literals throughout the unit test suite.

**Review by Myoldmopar — APPROVED** [review]
This is good to go now.  I'm going to wait on CI to make sure I didn't break anything in my little tweaks, but it should merge later if happy.

File: tst/EnergyPlus/unit/DXCoils.unit.cc (hunk 4 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/DXCoils.unit.cc:3582]: I see that and was also wondering why there are trailing spaces. I see those in Format_991 and Format_995. This is a good work around for now.

**Comment by Myoldmopar** [comment]
OK, CI looks happy here, just the expected EIO/Table diffs.  Merging this, thanks @lymereJ
