### PR TITLE
Fix coil user defined node registration problem

### LINKED ISSUE #9359: Coil:UserDefined node registry problem causing node connection check failure
Issue overview
--------------
It was discovered that the Coil:UserDefined has a problem in registering the secondary flow nodes, which will cause a node check failure under certain configurations (if both primary and secondary airflows are used):
```
   ** Severe  ** (Developer) Node Connection Error, Object=COIL:USERDEFINED:xxx
   **   ~~~   ** Object has multiple connections on both inlet and outlet fluid streams.
   **   ~~~   ** ...occurs in Fluid Stream [1].
```

The root cause is due to that the secondary flow nodes were registered as primary for the coil. 

Currently there is no workaround for the issue. Code change is needed to fix the problem. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): Tested on v9.6 and v22.1
 - Discovered while working helpdesk ticket 16143

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9359/9359_in_2Plus1.idf))
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9359 
 - In the original code the Coil:UserDefined air side secondary nodes were registered to the incorrect fluid stream. This PR fixes the issue.
 - Also explicitly added a fluid stream type (tier) since it might be used in some objects. 

BND diffs are expected (in two example test files that contain Coil:UserDefined objects---both indicating that the coils' water connection fluid stream type changed from 2 (Secondary) to 3 (Tertiary):

EMSUserDefined5ZoneAirCooled
```
--- 
+++ 
@@ -558,16 +558,16 @@
  Non-Parent Node Connection,CENTRAL CHILLER CONDENSER OUTLET NODE,PLANTCOMPONENT:USERDEFINED,CENTRAL CHILLER,ReliefAir,1
  Non-Parent Node Connection,OA HEATING COIL 1 AIR OUTLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Inlet,1
  Non-Parent Node Connection,OA MIXING BOX 1 INLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Outlet,1
- Non-Parent Node Connection,OA COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Inlet,2
- Non-Parent Node Connection,OA COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Outlet,2
+ Non-Parent Node Connection,OA COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Inlet,3
+ Non-Parent Node Connection,OA COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Outlet,3
  Non-Parent Node Connection,MIXED AIR NODE 1,COIL:USERDEFINED,MAIN COOLING COIL 1,Inlet,1
  Non-Parent Node Connection,MAIN COOLING COIL 1 OUTLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Outlet,1
- Non-Parent Node Connection,MAIN COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Inlet,2
- Non-Parent Node Connection,MAIN COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Outlet,2
+ Non-Parent Node Connection,MAIN COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Inlet,3
+ Non-Parent Node Connection,MAIN COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Outlet,3
  Non-Parent Node Connection,MAIN COOLING COIL 1 OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Inlet,1
  Non-Parent Node Connection,MAIN HEATING COIL 1 OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Outlet,1
- Non-Parent Node Connection,MAIN HEATING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Inlet,2
- Non-Parent Node Connection,MAIN HEATING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Outlet,2
+ Non-Parent Node Connection,MAIN HEATING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Inlet,3
+ Non-Parent Node Connection,MAIN HEATING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Outlet,3
  Non-Parent Node Connection,CW PUMP OUTLET NODE,CONNECTOR:SPLITTER,CW LOOP SPLITTER,Inlet,1
  Non-Parent Node Connection,CENTRAL CHILLER INLET NODE,CONNECTOR:SPLITTER,CW LOOP SPLITTER,Outlet,1
  Non-Parent Node Connection,CW SUPPLY BYPASS INLET NODE,CONNECTOR:SPLITTER,CW LOOP SPLITTER,Outlet,1
```

PythonPluginUserDefined5ZoneAirCooled:
```
--- 
+++ 
@@ -558,16 +558,16 @@
  Non-Parent Node Connection,CENTRAL CHILLER CONDENSER OUTLET NODE,PLANTCOMPONENT:USERDEFINED,CENTRAL CHILLER,ReliefAir,1
  Non-Parent Node Connection,OA HEATING COIL 1 AIR OUTLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Inlet,1
  Non-Parent Node Connection,OA MIXING BOX 1 INLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Outlet,1
- Non-Parent Node Connection,OA COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Inlet,2
- Non-Parent Node Connection,OA COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Outlet,2
+ Non-Parent Node Connection,OA COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Inlet,3
+ Non-Parent Node Connection,OA COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,OA COOLING COIL 1,Outlet,3
  Non-Parent Node Connection,MIXED AIR NODE 1,COIL:USERDEFINED,MAIN COOLING COIL 1,Inlet,1
  Non-Parent Node Connection,MAIN COOLING COIL 1 OUTLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Outlet,1
- Non-Parent Node Connection,MAIN COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Inlet,2
- Non-Parent Node Connection,MAIN COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Outlet,2
+ Non-Parent Node Connection,MAIN COOLING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Inlet,3
+ Non-Parent Node Connection,MAIN COOLING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN COOLING COIL 1,Outlet,3
  Non-Parent Node Connection,MAIN COOLING COIL 1 OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Inlet,1
  Non-Parent Node Connection,MAIN HEATING COIL 1 OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Outlet,1
- Non-Parent Node Connection,MAIN HEATING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Inlet,2
- Non-Parent Node Connection,MAIN HEATING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Outlet,2
+ Non-Parent Node Connection,MAIN HEATING COIL 1 WATER INLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Inlet,3
+ Non-Parent Node Connection,MAIN HEATING COIL 1 WATER OUTLET NODE,COIL:USERDEFINED,MAIN HEATING COIL 1,Outlet,3
  Non-Parent Node Connection,CW PUMP OUTLET NODE,CONNECTOR:SPLITTER,CW LOOP SPLITTER,Inlet,1
  Non-Parent Node Connection,CENTRAL CHILLER INLET NODE,CONNECTOR:SPLITTER,CW LOOP SPLITTER,Outlet,1
  Non-Parent Node Connection,CW SUPPLY BYPASS INLET NODE,CONNECTOR:SPLITTER,CW LOOP SPLITTER,Outlet,1
```

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UserDefinedComponents.cc [hunk 1]
```diff
@@ -1069,7 +1069,7 @@ namespace UserDefinedComponents {
                                                                 state.dataUserDefinedComponents->UserCoil(CompLoop).Name,
                                                                 DataLoopNode::NodeFluidType::Air,
                                                                 DataLoopNode::ConnectionType::Inlet,
-                                                                NodeInputManager::CompFluidStream::Primary,
+                                                                static_cast<NodeInputManager::CompFluidStream>(ConnectionLoop),
```
Comment (rraustad) [inline src/EnergyPlus/UserDefinedComponents.cc:1072]: Yes, primary for Connection 1 Inlet Node, A4, and secondary for Connection 2 Inlet Node, A6.

File: src/EnergyPlus/UserDefinedComponents.cc [hunk 2]
```diff
@@ -1160,7 +1160,7 @@ namespace UserDefinedComponents {
                                                                 cAlphaArgs(1),
                                                                 DataLoopNode::NodeFluidType::Water,
                                                                 DataLoopNode::ConnectionType::Inlet,
-                                                                NodeInputManager::CompFluidStream::Secondary,
+                                                                NodeInputManager::CompFluidStream::Tertiary,
```
Comment (rraustad) [inline src/EnergyPlus/UserDefinedComponents.cc:1158]: For Coil:UserDefined, I understand the change to the air-side fluid stream type above but for Plant Connection Inlet Node, A9, why is this changed from Secondary to Tertiary? I only see the word Tertiary used in the EvaporativeCoolers code so am wondering what this node fluid stream connection type represents. 

            EvapCond(EvapCoolNum).TertiaryInletNode = GetOnlySingleNode(state,
                                                                        state.dataIPShortCut->cAlphaArgs(12),
                                                                        ErrorsFound,
                                                                        cCurrentModuleObject,
                                                                        state.dataIPShortCut->cAlphaArgs(1),
                                                                        DataLoopNode::NodeFluidType::Air,
                                                                        DataLoopNode::NodeConnectionType::Inlet,
                                                                        3,
                                                                        ObjectIsNotParent);
 

The water coils use Secondary and I would think this component would use the same?

        state.dataWaterCoils->WaterCoil(CoilNum).WaterInletNodeNum = GetOnlySingleNode(state,
                                                                                       AlphArray(3),
                                                                                       ErrorsFound,
                                                                                       CurrentModuleObject,
                                                                                       AlphArray(1),
                                                                                       DataLoopNode::NodeFluidType::Water,
                                                                                       DataLoopNode::NodeConnectionType::Inlet,
                                                                                       2,
                                                                                       ObjectIsNotParent);
        state.dataWaterCoils->WaterCoil(CoilNum).WaterOutletNodeNum = GetOnlySingleNode(state,
                                                                                        AlphArray(4),
                                                                                        ErrorsFound,
                                                                                        CurrentModuleObject,
                                                                                        AlphArray(1),
                                                                                        DataLoopNode::NodeFluidType::Water,
                                                                                        DataLoopNode::NodeConnectionType::Outlet,
                                                                                        2,
                                                                                        ObjectIsNotParent);

Comment (jcyuan2020) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: My understanding is that these connection types have "local" meanings to each particular object. They are probably just used to identify how many fluid streams go through one object. So for the water coil only primary and secondary are needed since there is only one air fluid stream. 

Across different objects, my understanding (maybe incorrect?) is that these stream tags are not universally aligned--e.g. one object's secondary fluid stream (or even primary stream) does not mean it has to be on the same stream on another object's secondary fluid stream. 

One thing for sure is that if there are two inlets and two outlets on the same fluid stream for the same object, the Node connection Check 10 will give a fatal error--that is what the check is for. So for Coil:UserDefined, if there there are both primary and secondary air streams (secondary air stream is optional for this object), and if water stream is assigned to secondary again, the node connection check 10 will just fail.

Comment (jcyuan2020) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: Another example of Tertiary (or even Quaternary) fluid stream is AirTerminal:SingleDuct:UserDefined. By looking at the following code, it could be inferred that there are Tertiary water side flow connections, or Quaternary connections (this is also one of the reasons why a "Quaternary" fluid stream type enum is added in this PR):
``` 
                int NumPlantConnections = std::floor(rNumericArgs(1));
                state.dataUserDefinedComponents->UserAirTerminal(CompLoop).NumPlantConnections = NumPlantConnections;
                if ((NumPlantConnections >= 1) && (NumPlantConnections <= 2)) {
                    state.dataUserDefinedComponents->UserAirTerminal(CompLoop).Loop.allocate(NumPlantConnections);
                    for (int ConnectionLoop = 1; ConnectionLoop <= NumPlantConnections; ++ConnectionLoop) {
                        int aArgCount = (ConnectionLoop - 1) * 2 + 8;
                        state.dataUserDefinedComponents->UserAirTerminal(CompLoop).Loop(ConnectionLoop).InletNodeNum =
                            NodeInputManager::GetOnlySingleNode(state,
                                                                cAlphaArgs(aArgCount),
                                                                ErrorsFound,
                                                                DataLoopNode::ConnectionObjectType::AirTerminalSingleDuctUserDefined,
                                                                cAlphaArgs(1),
                                                                DataLoopNode::NodeFluidType::Water,
                                                                DataLoopNode::ConnectionType::Inlet,
                                                                static_cast<NodeInputManager::CompFluidStream>(ConnectionLoop + 2),
                                                                DataLoopNode::ObjectIsNotParent,
                                                                cAlphaFieldNames(aArgCount));
                        state.dataUserDefinedComponents->UserAirTerminal(CompLoop).Loop(ConnectionLoop).OutletNodeNum =
                            NodeInputManager::GetOnlySingleNode(state,
                                                                cAlphaArgs(aArgCount + 1),
                                                                ErrorsFound,
                                                                DataLoopNode::ConnectionObjectType::AirTerminalSingleDuctUserDefined,
                                                                cAlphaArgs(1),
                                                                DataLoopNode::NodeFluidType::Water,
                                                                DataLoopNode::ConnectionType::Outlet,
                                                                static_cast<NodeInputManager::CompFluidStream>(ConnectionLoop + 2),
                                                                DataLoopNode::ObjectIsNotParent,
                                                                cAlphaFieldNames(aArgCount + 1));
```

Comment (jcyuan2020) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: Do these tags affect how the overall air loops or plants are simulated? Maybe--but it seems that if within each object the nodes are handled properly (hopefully in simulation they do not only relay on this tag type to identify fluid stream across elements), it should be fine. I checked the Coil:UserDefined code and this does not seem to be a problem. Some comments are welcome about if this could be an issue to other objects?

Comment (rraustad) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: I think the FluidStream is used to help draw the HVACDiagram. I don't think it is used anywhere in E+. It would be better if @mjwitte or @JasonGlazer commented on how this data is used.

Comment (mjwitte) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: The FluidStream is used in EnergyPlus for connection checking for each object, and it is used in HVACDiagram, but it's just a way to distinguish different fluid streams within a given object to check if inlets and outlets make sense. HVACDiagram doesn't care about the actual integer values for this, it just cares that inlets a and b go together on the same stream, and so on. There can be a gap in the numbering on a given object. Before this was `enum`ized it was just an integer and there were hard numbers in the `getOnlySingleNode` calls, or, in this case there were loop indices which is how this got broken during the `enum` sweep.

Comment (rraustad) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: Ok, I see the node connection check [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/BranchNodeConnections.cc#L122-L129). This code is looking for another node already registered that matches the same FluidStream for the same object. The 3rd check is for ConnectionType (inlet or outlet) and since Coil:UserDefined can have 3 sets of node pairs, this check gets tripped up. It seems there should not be an issue between air and water nodes, but because this check does not look for NodeFluidType, then the node connection check fails for this object if 2 air streams and a water stream are used (so you can't use secondary here for FluidStream). Since the integer value does not matter then it seems this is OK.

Comment (rraustad) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: I'm still suspicous of this change because the first check in this block of code is for NodeNumber. The air and water node numbers should not match. I'll leave it there.

Comment (jcyuan2020) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: The "Check 10" below will check inlets and outlets of an object and accumulate counts into fluidstream "bins". There the air and the water streams are not distinguished other than "fluidstream" tag numbers: 
https://github.com/NREL/EnergyPlus/blob/44de4f7d8067ad59f1bb2ed1a4c6e83740eb3c6b/src/EnergyPlus/BranchNodeConnections.cc#L698-L722 

If >1 inlets and >1 outlets are detected at the same time in the same fluidstream bin, the error will be thrown. So air secondary + water secondary should also trigger this error. The original code triggers the error slightly differently, by doing "air primary + air primary".

Comment (rraustad) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: I'm no longer suspicious!

File: src/EnergyPlus/UserDefinedComponents.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/UserDefinedComponents.cc:1072]: I wonder about some alternative ways to call this to avoid the static cast here.  I understand that at some level, we have to go from raw integers to the enum, and I'm not saying we definitely need to change anything.  Seeing this as an argument in the function call just makes me pause and think.  I do understand it is necessary to not just pass `::Primary` each time though.  :+1:

File: src/EnergyPlus/UserDefinedComponents.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/UserDefinedComponents.cc:1158]: I'm glad this conversation wrapped up nicely :smile:

File: tst/EnergyPlus/unit/PlantManager.unit.cc [hunk 3]
```diff
@@ -218,4 +222,119 @@ namespace PlantManager {
...
+        EMSManager::ManageEMS(*state, EMSManager::EMSCallFrom::BeginNewEnvironment, anyRan, ObjexxFCL::Optional_int_const());
+
+        GetUserDefinedPlantComponents(*state);
+        ASSERT_FALSE(ErrorsFound);
+
+        // Five Node Connections
+        EXPECT_EQ(5, state->dataBranchNodeConnections->NumOfNodeConnections);
+
+        // OA Node
+        EXPECT_EQ(static_cast<int>(NodeInputManager::CompFluidStream::Primary),
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/PlantManager.unit.cc]: All these casts makes it really tough to read.  It would be much better to use `EXPECT_TRUE(compare_enums(a, b));`  Could you make that change?  Or let me know and I can.

**Review by Myoldmopar — COMMENTED** [review]
For now I'm not marking this approved or rejected.  I want to think about how we are looping over the connection types, and I would also like to see all the casts cleaned up in the unit test.  Either way this is very close.

File: tst/EnergyPlus/unit/PlantManager.unit.cc (hunk 3 above)
Comment (jcyuan2020) [reply tst/EnergyPlus/unit/PlantManager.unit.cc]: Sure, I will make the change.

File: src/EnergyPlus/NodeInputManager.hh [hunk 4]
```diff
@@ -76,6 +76,7 @@ namespace NodeInputManager {
         Primary = 1,
```
Comment (amirroth) [inline src/EnergyPlus/NodeInputManager.hh:76]: Do these have to start at 1? Why can they not start at 0?

File: tst/EnergyPlus/unit/PlantManager.unit.cc (hunk 3 above)
Comment (amirroth) [reply tst/EnergyPlus/unit/PlantManager.unit.cc]: Can you make a shorthand `EXPECT_EQ_ENUM`?

File: src/EnergyPlus/NodeInputManager.hh (hunk 4 above)
Comment (jcyuan2020) [reply src/EnergyPlus/NodeInputManager.hh:76]: Here is my tentative answer on this: 
According to @mjwitte 's explanation in a comment above, this numbering actually had occurred long time ago and had been the mere identification for quite a while; and the `enum` was a more recent addition to map the actual numbers. I would probably interpret the `enum` names (Primary to Quaternary) as the "keys" the existing numbers instead, with the current setting of:
```
    enum class CompFluidStream
    {
        Invalid = -1,
        Primary = 1,
        Secondary = 2,
        Tertiary = 3,
        Quaternary = 4,
        Num
    };
```

Actually it seems the actual numbering is more important the `enum` name. One problem I see when changing the numbering (to start from `0`) is that there are many code lines are actually dependent on actual numbers and then there could probably be a lot more code lines that need to be examined and changed.

Comment (amirroth) [reply src/EnergyPlus/NodeInputManager.hh:76]: By the last statement you mean that the code is written like `== 1` as opposed to `== CompFluidStream::Primary`? Yikes! If that is the case, then that also needs to change because starting at 0 or not, that's just poor programming hygiene. Not sure what the best way of doing that is though other than whackamole.

Comment (jcyuan2020) [reply src/EnergyPlus/NodeInputManager.hh:76]: I believe so---the older code probably originally just used `==1`. Actually there are still some mixed uses in the current code: some are like `CompFluidStream::Primary`---the new way; but there are quite some places where the numbers are directly used (with a static cast to `enum` though), such as `static_cast<NodeInputManager::CompFluidStream>(ConnectionLoop + 2)` shown in the code block mentioned in [this comment](https://github.com/NREL/EnergyPlus/pull/9364#discussion_r844074385) above.

Comment (mjwitte) [reply src/EnergyPlus/NodeInputManager.hh:76]: As the original author of the node connections, this was intended to be an integer tag, simply to group nodes that belong to the same fluid stream within a given component. It's used for connection checking and it's also written as integers to the bnd output for HVAC Diagram. There's really no limit the number of possible fluid streams, so converting this to a fixed set of enum values made the calls to `getOnlySingleNode` look nice, but it broke this place where it's based on looping through a set of nodes and incrementing the fluidstream.

It's stored as an enum in `state.dataBranchNodeConnections->NodeConnections(Count).FluidStream` so I think any values (including zero) would be safe to use as far as EnergyPlus is concerned. But it could trip up places where it's interpreted from a loop index as @jcyuan2020 noted. It's bit tricky to scan the code for cases where this argument is set through a `cast`.

And I'm not sure if HVACDiagram would choke on zero values or not.

In looking at the code, there's an optional `IncrementFluidStream` in `NodeInputManager::GetNodeNums` that will fail if it's called with a node list of more than 3 (or now 4) nodes. See [code here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/NodeInputManager.cc#L194-L196). Based on a quick check, it looks like [outside air nodes](https://github.com/NREL/EnergyPlus/blob/c2a7f6078341696d5b1d26736216175c622072be/src/EnergyPlus/OutAirNodeManager.cc#L216-L234) are the only place that use the `IncrementFluidStream` argument. I'm surprised this doesn't fail the integration tests, but maybe we don't have any inputs that use a nodelist name in that object?  `IncrementFluidStream` is also used [here](https://github.com/NREL/EnergyPlus/blob/c2a7f6078341696d5b1d26736216175c622072be/src/EnergyPlus/OutAirNodeManager.cc#L278-L290).

Comment (mjwitte) [reply src/EnergyPlus/NodeInputManager.hh:76]: @amirroth I guess I don't fully (partly?) understand what happens with enums at run-time. Based on the above comments, this input from _SmallOffice_Dulles.idf violates the enum list, because it will set the fluid stream values to 1,2,3,4:
```
  NodeList,
    OutsideAirInletNodes,    !- Name
    OAInletNode_SouthZone_1stFloor,  !- Node 1 Name
    OAInletNode_NorthZone_1stFloor,  !- Node 2 Name
    OAInletNode_SouthZone_2ndFloor,  !- Node 3 Name
    OAInletNode_NorthZone_2ndFloor;  !- Node 4 Name
```
Are enums only validated at compile time?

Comment (amirroth) [reply src/EnergyPlus/NodeInputManager.hh:76]: - To @mjwitte's question first. I assume that when you say "validation" you mean "type-checking".  In C++, type-checking happens at compile-time. In C/C++, `enum` is a subtype of `int`. As with any sub-typing relationship, you can safely use an `enum` as an `int` (i.e., use an `enum` anywhere that expects an `int` like an index into an array). You can even do so without casting! However, you cannot do it the other way around (i.e., use an `int` in a place that expects an `enum`). In C++, an `enum class` is not technically a subtype of `int` but it is for all intents and purposes and you can safely use an `enum class` as an `int` although you have to add `static_cast<int>(compFluidStream)`. However, you still cannot use an `int` as an `enum class` and so `static_cast<enum class CompFluidStream>(i)` is not a safe thing to do. By using `static_cast` you are telling the compiler to let you do this unsafe thing anyway because "you know what you're doing" even though in this case you obviously don't. In this specific case, you cannot take arbitrary integers and safely use them as `enum class CompFluidStream`. If something doesn't break, it's just luck.
- What to do in this case? If `CompFluidStream` can really be an arbitrary integer then it should be an `int` and not an `enum class`. If you want to use `enum class` for some reason, then you should check in the `NodeList getInput` function that the range of this `enum class` is not violated.

File: tst/EnergyPlus/unit/PlantManager.unit.cc (hunk 3 above)
Comment (jcyuan2020) [reply tst/EnergyPlus/unit/PlantManager.unit.cc]: I changed the unit test code to use EXPECT_TRUE(compare_enums(a, b)) for the enum comparisons, which works fine. However, still not so sure how to create a new short hand EXPECT_EQ_ENUM() after looking into gtest.cc. Maybe some guidance on how to do it?

Comment (Myoldmopar) [reply tst/EnergyPlus/unit/PlantManager.unit.cc]: I agree this would be a nice addition.  But I don't think you need to worry about adding that in this particular PR.  We can make that in a separate PR, and we'll sweep the unit tests and update all of them to use the new macro.

**Comment by mjwitte** [comment]
@Myoldmopar Do you want any other changes here?

**Comment by Myoldmopar** [comment]
@mjwitte if the enum issues are settled then I'm happy with it. If that still needs work then maybe it would be worth a quick chat to get it resolved.

**Comment by mjwitte** [comment]
The `enum` vs `int` questions are bigger than this PR, so that's a 📌

**Comment by jcyuan2020** [comment]
One additional note for the final merge of this PR to develop: there is another PR #9363 which might be better to get reviewed (or merged) before finally merging the current PR (#9364) to develop. The reason is that the defect file for #9363 will no longer be an example to show the problem if the current PR gets merged into develop first.

**Comment by Myoldmopar** [comment]
Verified the issue on develop, and confirmed the fix here with this PR.  I pulled in develop and built and ran tests locally, all is well.  I think this is ready to go.  There are some comments above about the enum/int, but I agree that doesn't need to be part of this bug fix.  Merging this.  Thanks!
