### PR TITLE
Fix VRFFluidCtrl cooling cycling issue by moving cycling ratio calc in compressor spd calc

### LINKED ISSUE #10105: VRF cooling issue: same cooling power with different min-speed curve at low cooling load
Issue overview
--------------

**Cycling issue at the lowest fan speed**

The two idf files reproducing this problem is derived from the "US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf". They differ at the performance curves at the lowest compressor speed, the speed_1920.idf is created by removing the lowest speed as follows:

image

Row 2-7 shows the simulation results when the minimum compressor minimum speed is 900 with speed curve 1. Row 9-14 shows the simulation results when the compressor minimum speed is 1920 and using performance curve 2. Note that the capacity curves of speed levels are in the order of ascending capacity. We can see that even if the two settings have different compressor curves for the minimum speed, they output the same cooling rates, yet very different cooling electricity rate and COP. The heat pump runtime fraction and cycling ratio are 1 in both cases.  For the same cooling demand (both the zone and outdoor temperature are the same), if it runs fulltime in speed_900.idf, it should only run part of the time in speed_1920.idf, as its min capacity is larger than the former. They can't both run fulltime. 

image
 
### Defect files

[simulation_with_different_speeed_update.zip](https://github.com/NREL/EnergyPlus/files/14543997/simulation_with_different_speeed_update.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.3)
 - Version of EnergyPlus (22.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Fixes #10105 
 - The range of the outdoor evaporating temperature is updated to match the valid range of the indoor unit evaporating temperature.

The following shows the relevant code flow chart. We observed a problem of non-matching minimum-speed compressor capacity at two places

image

For the same timestep, in the cycling ratio calculation, the demand is larger than minimum speed capacity, and the compressor is considered not cycling. However in the compressor speed calculation later on, the demand is smaller than the minimum speed capacity, and the compressor is considered cycling

image

The difference in the minimum-speed-capacity is caused by the difference in the evaporating temperature.

image

To fix this, we propose to move the cycling calculation inside the compressor speed calculation as is shown in the following diagram.

image

### Effect of the fix

The following shows the output before the fix

image

The following shows the output after the fix. 

image

After the fix, runtime fractions are different now, where the lower-capacity one runs longer. For the same cooling rate, the heat pump cooling electricity rate and COP are more similar. The evaporating temperature output also reflected the following Te adjustment when the compressor is at the lowest speed (minimum loading index)

image
 

### Regression diffs

The regression diffs happen in the following files with VRF FluidTCtrl models
- US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF
- VariableRefrigerantFlow_FluidTCtrl_5Zone
- VariableRefrigerantFlow_FluidTCtrl_HR_5Zone
- VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone

The four files all have table diffs in electricity rate. The following is in the table diff in  VariableRefrigerantFlow_FluidTCtrl_5Zone. These are anticipated as the cycling ratio calculation is modified and the cooling electricity rate should change.  As a result, the total electricity rate should also change.

image
image

Meter difference happens in the following two files. The differences are in Cooling:Electricity, Electricity:HVAC, and Electricity:Facility. The diffs are expected as cycling ratio can affect the cooling electricity rate, which leads to changes in these "Electricity:*" variables.
- VariableRefrigerantFlow_FluidTCtrl_5Zone
- VariableRefrigerantFlow_FluidTCtrl_HR_5Zone

The following is from the output of the "VariableRefrigerantFlow_FluidTCtrl_5Zone.idf".

image

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 1]
```diff
@@ -283,6 +283,25 @@ void SimulateVRF(EnergyPlusData &state,
...
+    auto const &thisTU = state.dataHVACVarRefFlow->VRFTU(VRFTUNum);
+    auto &coolingCoil = state.dataDXCoils->DXCoil(thisTU.CoolCoilIndex);
+    int PLF;
+    if (coolingCoil.PLFFPLR(1) > 0 && state.dataHVACVarRefFlow->VRF(VRFCondenser).VRFCondCyclingRatio < 1.0) {
+        PLF = Curve::CurveValue(
+            state, coolingCoil.PLFFPLR(1), state.dataHVACVarRefFlow->VRF(VRFCondenser).VRFCondCyclingRatio); // Calculate part-load factor
+    } else {
+        PLF = 1.0;
+    }
+    if (coolingCoil.TotalCoolingEnergyRate > 0.0) {
```
Comment (yujiex) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: this keeps the coil RTF up-to-date with the condenser side

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 2]
```diff
@@ -14429,12 +14440,19 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
                     goto Label13;
                 }
 
-                if (CapDiff > (Tolerance * Cap_Eva0)) NumIteCcap = 999;
+                if (CapDiff > (Tolerance * Cap_Eva0)) {
```
Comment (yujiex) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: cycling ratio calculation is moved to here

**Comment by mjwitte** [comment]
@yujiex For the defect file attached to #10105 these code changes don't alter the relative behavior between the two defect files (i.e. the stated speed at load range 1 has no impact on results other than the reported speed value, see https://github.com/NREL/EnergyPlus/issues/10105#issuecomment-1984151211). The results in both the 900 and 1320 file both change the same way.

But this PR does expose the fact that the initial check of load vs min-capacity has a significantly different value for `CompEvaporatingCAPSpdMin` than the equivalent check later on in the speed-selection pass. Looking at the code in develop, here's the first block in `VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl`:
https://github.com/NREL/EnergyPlus/blob/769463d9e9b6ec7059494f2db11ce8fa506b5a44/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L11531-L11543

And here's the second block:
https://github.com/NREL/EnergyPlus/blob/769463d9e9b6ec7059494f2db11ce8fa506b5a44/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L11838-L11842

So my question would be why the first one is using `CapMinTc = OutdoorDryBulb + this->SC` to evaluate the capacity curve, while the second block is using `Tdischarge` where
```
        Tdischarge = GetSatTemperatureRefrig(state, this->RefrigerantName, max(min(Pdischarge, RefPHigh), RefPLow), RefrigerantIndex, RoutineName);
```

**Comment by yujiex** [comment]
> @yujiex For the defect file attached to #10105 these code changes don't alter the relative behavior between the two defect files (i.e. the stated speed at load range 1 has no impact on results other than the reported speed value, see [#10105 (comment)](https://github.com/NREL/EnergyPlus/issues/10105#issuecomment-1984151211)). The results in both the 900 and 1320 file both change the same way.
> 
> But this PR does expose the fact that the initial check of load vs min-capacity has a significantly different value for `CompEvaporatingCAPSpdMin` than the equivalent check later on in the speed-selection pass. Looking at the code in develop, here's the first block in `VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl`:
> 
> https://github.com/NREL/EnergyPlus/blob/769463d9e9b6ec7059494f2db11ce8fa506b5a44/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L11531-L11543
> 
> And here's the second block:
> 
> https://github.com/NREL/EnergyPlus/blob/769463d9e9b6ec7059494f2db11ce8fa506b5a44/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L11838-L11842
> 
> So my question would be why the first one is using `CapMinTc = OutdoorDryBulb + this->SC` to evaluate the capacity curve, while the second block is using `Tdischarge` where
> 
> ```
>         Tdischarge = GetSatTemperatureRefrig(state, this->RefrigerantName, max(min(Pdischarge, RefPHigh), RefPLow), RefrigerantIndex, RoutineName);
> ```

My understanding is the CompEvaporatingCAPSpdMin check in the first block before entering the compressor speed calculation might be a rougher guess and the second place considers the piping loss and is more accurate.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 3]
```diff
@@ -283,6 +283,27 @@ void SimulateVRF(EnergyPlusData &state,
         if (state.dataHVACVarRefFlow->VRF(VRFCondenser).CondenserType == DataHeatBalance::RefrigCondenserType::Water)
             UpdateVRFCondenser(state, VRFCondenser);
     }
+    // yujie: update coil and IU evaporating temperature, also keep coil RTF updated with the condenser side cycling ratio, for the FluidTCtrl model
```
Comment (mjwitte) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Current practice is to leave names out of comments.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 4]
```diff
@@ -14429,12 +14442,20 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
...
+                if (CapDiff > (Tolerance * Cap_Eva0)) {
+                    NumIteCcap = 999;
+                    CyclingRatio = (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1;
+                } else {
+                    CyclingRatio = 1.0;
+                }
 
-                Ncomp = this->RatedCompPower * CurveValue(state, this->OUCoolingPWRFT(CounterCompSpdTemp), T_discharge, T_suction);
+                Ncomp = this->RatedCompPower * CurveValue(state, this->OUCoolingPWRFT(CounterCompSpdTemp), T_discharge, T_suction) * CyclingRatio;
+                OUCondHeatRelease = Cap_Eva1 * CyclingRatio;
```
Comment (mjwitte) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I don't think this is correct. Earlier `OUCondHeatRelease = TU_load + Pipe_Q + Ncomp;`
Possibly `OUCondHeatRelease  *= CyclingRatio;` would be correct here?

File: testfiles/speed_1320.idf [hunk 5]
```diff
@@ -0,0 +1,7429 @@
+!- ---------------------------------------------------------------------------------------------------------
+!- The Residential Prototype Building Models were developed by Pacific Northwest National Laboratory (PNNL),
```
Comment (mjwitte) [inline testfiles/speed_1320.idf]: The defect files got added by mistake.

**Review by mjwitte — COMMENTED** [review]
A few more comments. I would like @rraustad to review also.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: or would it be Ncomp + Cap_Eva1 * CyclingRatio? similar to the load > maximum capacity case
```
    if (CounterCompSpdTemp > NumOfCompSpdInput) {
        // Required load is beyond the maximum system capacity
        CompEvaporatingCAPSpd(NumOfCompSpdInput) =
            this->CoffEvapCap * this->RatedEvapCapacity * CurveValue(state, this->OUCoolingCAPFT(NumOfCompSpdInput), T_discharge, T_suction);
        OUCondHeatRelease = Ncomp + CompEvaporatingCAPSpd(NumOfCompSpdInput);
        CompSpdActual = this->CompressorSpeed(NumOfCompSpdInput);
        Ncomp = CompEvaporatingPWRSpd(NumOfCompSpdInput);
    }
```

Ncomp is updated inside `VRFOU_CalcCompC`, so maybe that part needs to use the updated `Ncomp`?, When it is cycling,  `CyclingRatio = (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1`, then `Ncomp + Cap_Eva1 * CyclingRatio` would evaluates to `Ncomp + (TU_load + Pipe_Q) * C_cap_operation`, with the updated `Ncomp` and the `TU_load + Pipe_Q` considering the difference between the rated and real condition (`C_cap_operation`)

File: testfiles/speed_1320.idf (hunk 5 above)
Comment (yujiex) [reply testfiles/speed_1320.idf]: let me remove it

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I'll remove the name

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (mjwitte) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: That sounds ok. This function is very hard to follow, so I'll trust you on that.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 6]
```diff
@@ -283,6 +283,27 @@ void SimulateVRF(EnergyPlusData &state,
...
+        if (coolingCoil.PLFFPLR(1) > 0 && state.dataHVACVarRefFlow->VRF(VRFCondenser).VRFCondCyclingRatio < 1.0) {
+            PLF = Curve::CurveValue(
+                state, coolingCoil.PLFFPLR(1), state.dataHVACVarRefFlow->VRF(VRFCondenser).VRFCondCyclingRatio); // Calculate part-load factor
+        } else {
+            PLF = 1.0;
+        }
+        if (coolingCoil.TotalCoolingEnergyRate > 0.0) {
+            coolingCoil.CoolingCoilRuntimeFraction = state.dataHVACVarRefFlow->VRF(VRFCondenser).VRFCondCyclingRatio / PLF;
+        }
+    }
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: This is a strange placement of code in the Sim routine. Shouldn't any updates be completed in the Calc routine?

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I just put this into the Calc routine.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: This logic does not seem right to me. At line 14439 this same conditional is used. It says if the capacity difference is greater than some tolerance keep iterating. So when we get to line 14447, it's either due to max iterations or the capacity difference is less than tolerance. I guess if capacity difference is less than tolerance then we converged on the capacity that requires the compressor to run the entire time step. But if `(NumIteCcap >= 30)` then what does that mean? I'm not sure it means the compressor is cycling. I think it might mean the compressor is cycling if `Cap_Eva1 - Cap_Eva0` is positive but you don't know that since `CapDiff = std::abs(Cap_Eva1 - Cap_Eva0);` I would think that should be accounted for here. I'm not sure though since this is a very detailed model.

if (CapDiff > (Tolerance * Cap_Eva0) && (Cap_Eva1 - Cap_Eva0) >= 0.0)

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 7]
```diff
@@ -12572,6 +12558,25 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state)
...
+
+        int PLF;
+        if (coolingCoil.PLFFPLR(1) > 0 && this->VRFCondCyclingRatio < 1.0) {
+            PLF = Curve::CurveValue(state, coolingCoil.PLFFPLR(1), this->VRFCondCyclingRatio); // Calculate part-load factor
+        } else {
+            PLF = 1.0;
+        }
+        if (coolingCoil.TotalCoolingEnergyRate > 0.0) {
+            coolingCoil.CoolingCoilRuntimeFraction = this->VRFCondCyclingRatio / PLF;
+        }
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12354]: I don't see CoolingCoilRuntimeFraction getting set to 0 anywhere. So if TotalCoolingEnergyRate = 0, then CoolingCoilRuntimeFraction will be used from the last time step the compressor operated. I would set CoolingCoilRuntimeFraction = 0.0 in Init.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 8]
```diff
@@ -14268,14 +14277,17 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
...
+                // Te can't be smaller than user input lower bound
+                MinOutdoorUnitTe = max(this->IUEvapTempLow, MinOutdoorUnitTe);
 
                 auto f = [&state, T_discharge_new, CondHeat, CAPFT](Real64 const T_suc) {
                     return CompResidual_FluidTCtrl(state, T_discharge_new, CondHeat, CAPFT, T_suc);
                 };
 
                 General::SolveRoot(state, 1.0e-3, MaxIter, SolFla, SmallLoadTe, f, MinOutdoorUnitTe,
-                                   T_suction);   // SmallLoadTe is the updated Te'
-                if (SolFla < 0) SmallLoadTe = 6; // MinOutdoorUnitTe; //SmallLoadTe( Te'_new ) is constant during iterations
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:13997]: This is poor logic for a SolveRoot failure. -1 means iteration limit exceeded and -2 means it can't find a solution. Using SolFla < 0 captures both and assumes there is a small load. Maybe this works, maybe it doesn't, I don't know. This is a separate issue, if this is actually an issue.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 9]
```diff
@@ -14186,7 +14193,8 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
     Real64 RefPHigh;                       // High Pressure Value for Ps (max in tables) [Pa]
     Real64 T_discharge_new;                // Condensing temperature, for temporary use in iterations [C]
     Real64 Tfs;                            // Temperature of the air at the coil surface [C]]
-    Real64 Tolerance(0.05);                // Tolerance for condensing temperature calculation [C}
+    Real64 Tolerance(0.05);                // Tolerance for condensing temperature calculation [C]
+    Real64 TeTol(0.5);                     // Tolerance for the difference between Te and SmallLoadTe
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: These should be constexpr

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 10]
```diff
@@ -11719,6 +11703,8 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state)
         }
 
         // Key outputs of this subroutine
+        Ncomp *= CyclingRatio;
+        Q_h_OU *= CyclingRatio;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11478]: Ncomp is power. Ncomp should multiply by RTF.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 11]
```diff
@@ -14429,12 +14442,20 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
...
-                if (CapDiff > (Tolerance * Cap_Eva0)) NumIteCcap = 999;
+                if (CapDiff > (Tolerance * Cap_Eva0)) {
+                    NumIteCcap = 999;
+                    CyclingRatio = (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1;
+                } else {
+                    CyclingRatio = 1.0;
+                }
 
                 Ncomp = this->RatedCompPower * CurveValue(state, this->OUCoolingPWRFT(CounterCompSpdTemp), T_discharge, T_suction);
+                OUCondHeatRelease = Ncomp + Cap_Eva1;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14165]: Condenser heat rejection = power + evap capacity. How does this calculation relate to lines 11706 and 11707? Is OUCondHeatRelease the same as Q_h_OU at line 11707? And where is Q_c_OU *= cyclingRatio? I am getting confused as to which variables account for cycling and which don't. Does `OUCondHeatRelease = Ncomp + Cap_Eva1;` account for cycling?

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 12]
```diff
@@ -14429,12 +14442,20 @@ void VRFCondenserEquipment::VRFOU_CalcCompC(EnergyPlusData &state,
                     goto Label13;
                 }
 
-                if (CapDiff > (Tolerance * Cap_Eva0)) NumIteCcap = 999;
+                if (CapDiff > (Tolerance * Cap_Eva0)) {
+                    NumIteCcap = 999;
+                    CyclingRatio = (TU_load + Pipe_Q) * C_cap_operation / Cap_Eva1;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: This math is confusing. (TU_load + Pipe_Q) is the load the compressor must meet. And Cap_Eva1 already includes CapFT. So shouldn't this be `(TU_load + Pipe_Q) / Cap_Eva1` ? or just `Cap_Eva0 / Cap_Eva1` ?

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 7 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12354]: It is set to 0 in this function: CalcVRFCoolingCoil_FluidTCtrl
```
    // Initialize coil air side parameters
    CondInletTemp = 0.0;
    CondInletHumRat = 0.0;
    AirMassFlow = thisDXCoil.InletAirMassFlowRate;
    InletAirDryBulbTemp = thisDXCoil.InletAirTemp;
    InletAirEnthalpy = thisDXCoil.InletAirEnthalpy;
    InletAirHumRat = thisDXCoil.InletAirHumRat;
    state.dataHeatBal->HeatReclaimDXCoil(DXCoilNum).AvailCapacity = 0.0;
    thisDXCoil.CoolingCoilRuntimeFraction = 0.0;
```

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12354]: Oh, I see. This is updating the coil model RTF, from the parent object. We should not do that. So why did you have to update the coil RTF? VRFCondCyclingRatio is already passed to SimDXCoil so the coil RTF should already be accurate, if that call is passing the updated cycling ratio.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 8 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:13997]: I will separate out SolFla=-1 and SolFla=-2 case. When it is -1 I will throw an error message of not reaching convergence. When it is -2, it would be the case where the load is small. 

In the -2 case, f(MinOutdoorUnitTe) and f(T_suction) can't be both positive as f(T_suction) > 0 would mean 
```
Q_evap_req * C_cap_operation / this->RatedEvapCapacity > CurveValue(state, this->OUCoolingCAPFT(CounterCompSpdTemp), T_discharge, T_suction)
```
, which is 
```
Q_evap_req * C_cap_operation > this->RatedEvapCapacity * CurveValue(state, this->OUCoolingCAPFT(CounterCompSpdTemp), T_discharge, T_suction)
```
If this is the case, it shouldn't have been in `if (Q_evap_req * C_cap_operation <= CompEvaporatingCAPSpd(CounterCompSpdTemp)) {`

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 9 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: changed to constexpr

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 12 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: `Cap_Eva0 / Cap_Eva1` probably better

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: It would be a nice test to plot some of the available report variables through a transition from CyclingRatio = 1 at some time step to CyclingRatio < 1 at future time steps to see if these report variables have a smooth transition from compressor on to compressor cycling. Whichever reports capture the equations being questioned here. Not sure why a component model is not reporting refrigerant pressures which could help in diagnostics. We should add refrigerant temperature/pressure reporting at some point.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 10 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11478]: RTF was calculated later in the function. Should I follow this code and compute RTF here so that RTF is accessible here? Also I'm not sure why it is written like this instead of `VRFRTF = min(1.0, CyclingRatio)`

```
    VRFRTF = 0.0;
    // VRF Cooling and Heating Electric Power (output variables)
    if (this->OperatingMode == ModeCoolingOnly) {
        PartLoadFraction = 1.0;
        VRFRTF = min(1.0, (CyclingRatio / PartLoadFraction));

        this->ElecCoolingPower = state.dataHVACVarRefFlow->VRF(VRFCond).Ncomp + this->OUFanPower;
        this->ElecHeatingPower = 0;

    } else if (this->OperatingMode == ModeHeatingOnly) {
        PartLoadFraction = 1.0;
        VRFRTF = min(1.0, (CyclingRatio / PartLoadFraction));

        this->ElecCoolingPower = 0;
        this->ElecHeatingPower = this->Ncomp + this->OUFanPower;

    } else if (this->OperatingMode == ModeCoolingAndHeating) {
        PartLoadFraction = 1.0;
        VRFRTF = min(1.0, (CyclingRatio / PartLoadFraction));

        this->ElecCoolingPower = (this->Ncomp + this->OUFanPower) * this->IUEvapHeatRate / (this->IUCondHeatRate + this->IUEvapHeatRate);
        this->ElecHeatingPower = (this->Ncomp + this->OUFanPower) * this->IUCondHeatRate / (this->IUCondHeatRate + this->IUEvapHeatRate);

    } else {
        this->ElecCoolingPower = 0;
        this->ElecHeatingPower = 0;
    }
    this->VRFCondRTF = VRFRTF;
```

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 2 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Indeed. If Cap_Eva1 - Cap_Eva0 < 0 then it should not cycle.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: good idea. I will produce some plot showing how CyclingRatio transition from 1 to < 1 and the other way

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 11 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14165]: Ncomp should probably account for cycling
OUCondHeatRelease was computed as the following in the `CounterCompSpdTemp > NumOfCompSpdInput case`
```
OUCondHeatRelease = Ncomp + CompEvaporatingCAPSpd(NumOfCompSpdInput);
```
So I basically followed this in the low-load approach. Originally I have the Ncomp and `OUCondHeatRelease` multiply by CyclingRatio (or maybe it should be RTF) in CalcCompH() function, but since the flow of the code is like 

```
        Ncomp = TU_CoolingLoad / this->CoolingCOP;
        Ncomp_new = Ncomp;
    Label10:;
        Q_h_OU = Q_c_TU_PL + Ncomp_new; // Ncomp_new may be updated during Iteration_Ncomp Label10

        ...

        // *VEF OU Compressor Simulation at cooling mode: Specify the compressor speed and power consumption
        this->VRFOU_CalcCompC(state,
                              TU_CoolingLoad,
                              Tsuction,
                              this->CondensingTemp,
                              Psuction,
                              T_comp_in,
                              h_comp_in,
                              h_IU_evap_in,
                              Pipe_Q_c,
                              CapMaxTc,
                              Q_h_OU,
                              CompSpdActual,
                              Ncomp,
                              CyclingRatio);

        if ((std::abs(Ncomp - Ncomp_new) > (Tolerance * Ncomp_new)) && (Counter < 30)) {
            Ncomp_new = Ncomp;
            Counter = Counter + 1;
            goto Label10;
        }
```
As the initial value of Ncomp (Ncomp = TU_CoolingLoad / this->CoolingCOP) does not have CyclingRatio in it, and the compressor is indeed going to cycling, then the cycling ratio will get multiplied multiple times, once each label10 loop. So I moved them to after the loop is completed.

```
OUCondHeatRelease = Ncomp + Cap_Eva1 = Ncomp + Cap_Eva0 / CyclingRatio;
```

```
OUCondHeatRelease * CyclingRatio = Ncomp * CyclingRatio + Cap_Eva0 = Ncomp * CyclingRatio + TU_load + Pipe_Q
```

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 10 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11478]: I don't know why it's written like this either. This is in the heat recovery code so maybe it is assumed the compressor runs the entire time step. Don't use this code without modifying `PartLoadFraction = 1.0;`. PLF needs to be calculated from the performance curve as a function of CyclingRatio as `PartLoadFraction = max(0.7, CurveValue(state, vrf.CoolPLFFPLR, CyclingRatio));`.

RTF = PLR/PLF. For VRF CyclingRatio is PLR so RTF = CyclingRatio/PLF.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 11 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14165]: The plots you make of a transition from CyclingRatio = 1 to CyclingRatio < 1 (later in a day when the cooling load is decreasing) will show if these equations are correct. Maybe start there to determine how these equations need to be organized.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 7 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:12354]: The condenser side cycling ratio is updated in `CalcVRFCondenser_FluidTCtrl`. This took place after SimDXCoil, so the coil RTF is updated here to keep up with the updated condenser side cycling ratio

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: image

[output change for cycling ratio from non-1 to 1.xlsx](https://github.com/NREL/EnergyPlus/files/14577311/output.change.for.cycling.ratio.from.non-1.to.1.xlsx)

I plotted two snapshot with cycling ratio changing from < 1 to 1 then back to < 1. The cooling electricity rate and condenser heat release seems to be smooth

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 11 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14165]: The plot is in this comment https://github.com/NREL/EnergyPlus/pull/10353#discussion_r1521980123

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 10 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11478]: In the component or physics-based VRF model, the OU doesn't have a curve for part load fraction. The available curves are the following
- Outdoor Unit Evaporating Temperature Function of Superheating Curve Name
- Outdoor Unit Condensing Temperature Function of Subcooling Curve Name
- Defrost Energy Input Ratio Modifier Function of Temperature Curve Name
- Loading Index i Evaporative Capacity Multiplier Function of Temperature Curve Name
- Loading Index i Compressor Power Multiplier Function of Temperature Curve Name

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11478]: OK, so there is no cycling/start-up losses in this model. Using CyclingRatio is OK here.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11478]: right.

**Comment by nrel-bot-2c** [comment]
@yujiex @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by yujiex** [comment]
@rraustad @mjwitte would you mind looking at this PR again? Thanks.

**Comment by yujiex** [comment]
I examined the fix using the following two test idf files and the NY epw file in the weather folder.
[speed_900.idf.txt](https://github.com/NREL/EnergyPlus/files/15299905/speed_900.idf.txt)
[speed_1920.idf.txt](https://github.com/NREL/EnergyPlus/files/15299906/speed_1920.idf.txt)

The two idf files differ at the capacity multiplier curves at the lowest speed
image

The following plot shows the cooling and power multiplier curves at three different temperature

image

The plot on the left shows the cooling capacity curve divided by the power curves. The right one shows the distribution of the condensing and evaporating temperature. According to the distribution plot, the 30F and 35F curve 1 and curve 2 are more relevant at evaporating temperature near 10F (yellow highlighted). The plots later on are produced for the timestamps when the higher-capacity one is cycling (cycling ratio between 0 and 1).

image 

In this branch, the cycling ratio, electricity rate, and COP are as follows, for a simulation period over July. x axis are indices of timesteps.
image

image

image


COP shouldn’t have such large discrepancy when the file using curve 1 is fully run and the other file is cycling
The spikes in the electricity rate plots are also not right. Investigating this issue now.

**Comment by rraustad** [comment]
The VRF Heat Pump Cycling Ratio and Cooling Coil Total Cooling Rate figures make sense. The cycling ratio is higher with Curve 1 since there is a lower capacity multiplier and the coil provides the same cooling capacity to meet the same load. The other figures are harder to understand since there are 2 curves involved. It is also not clear at what speed the compressor is operating in these figures.

**Comment by yujiex** [comment]
> The VRF Heat Pump Cycling Ratio and Cooling Coil Total Cooling Rate figures make sense. The cycling ratio is higher with Curve 1 since there is a lower capacity multiplier and the coil provides the same cooling capacity to meet the same load. The other figures are harder to understand since there are 2 curves involved. It is also not clear at what speed the compressor is operating in these figures.

I added a compressor speed plot at the bottom. It was using the "timestep" resolution.

I added a COP curve plot (cooling capacity curves divided by power curves).

**Comment by rraustad** [comment]
The compressor speed is nearly constant in both cases? In order for the cooling capacity to change the suction pressure/temperature would have to change. And would look similar to the cooling rate plots. I don't see a minimum compressor speed in the inputs so I assume it's the Compressor Speed at Loading Index 1 (and if that's true then why did the Curve 2 compressor speed fall well below 1920?). I thought VRF systems modulated compressor speed, not suction conditions? I also thought that suction pressure and/or temperature was the control point in the VRF control algorithm and compressor speed would modulate to hold that condition constant. Maybe since this system is operating at the minimum speed that this is how it needs to be when the system operates. Can you plot suction pressure and temperature? I would expect the Curve 1 suction temperature to be constant at a minimum value when compressor speed increases above the minimum speed.

      A5 , \field Refrigerant Temperature Control Algorithm for Indoor Unit
           \type choice
           \key ConstantTemp
           \key VariableTemp
           \default VariableTemp
      N9 , \field Reference Evaporating Temperature for Indoor Unit
      N10, \field Reference Condensing Temperature for Indoor Unit
      N11, \field Variable Evaporating Temperature Minimum for Indoor Unit
      N12, \field Variable Evaporating Temperature Maximum for Indoor Unit
      N13, \field Variable Condensing Temperature Minimum for Indoor Unit
      N14, \field Variable Condensing Temperature Maximum for Indoor Unit

      N32, \field Compressor Speed at Loading Index 1
           \required-field
           \type real
           \begin-extensible
           \note Minimum compressor speed

**Comment by yujiex** [comment]
> The compressor speed is nearly constant in both cases? In order for the cooling capacity to change the suction pressure/temperature would have to change. And would look similar to the cooling rate plots. I don't see a minimum compressor speed in the inputs so I assume it's the Compressor Speed at Loading Index 1 (and if that's true then why did the Curve 2 compressor speed fall well below 1920?). I thought VRF systems modulated compressor speed, not suction conditions? I also thought that suction pressure and/or temperature was the control point in the VRF control algorithm and compressor speed would modulate to hold that condition constant. Maybe since this system is operating at the minimum speed that this is how it needs to be when the system operates. Can you plot suction pressure and temperature? I would expect the Curve 1 suction temperature to be constant at a minimum value when compressor speed increases above the minimum speed.
> 
> ```
>   A5 , \field Refrigerant Temperature Control Algorithm for Indoor Unit
>        \type choice
>        \key ConstantTemp
>        \key VariableTemp
>        \default VariableTemp
>   N9 , \field Reference Evaporating Temperature for Indoor Unit
>   N10, \field Reference Condensing Temperature for Indoor Unit
>   N11, \field Variable Evaporating Temperature Minimum for Indoor Unit
>   N12, \field Variable Evaporating Temperature Maximum for Indoor Unit
>   N13, \field Variable Condensing Temperature Minimum for Indoor Unit
>   N14, \field Variable Condensing Temperature Maximum for Indoor Unit
> 
>   N32, \field Compressor Speed at Loading Index 1
>        \required-field
>        \type real
>        \begin-extensible
>        \note Minimum compressor speed
> ```

The compressor speed at the loading index 1 is the minimum speed of the VRF compressor. The VRF system will first modulate compressor speed to match the demand. If the demand is smaller than the minimum speed, then it starts to update the indoor unit evaporating temperature to further change the capacity to meet the low demand. If the lowest capacity after adjusting Te is still larger than the demand, it will start cycling.

These are the IU evaporating temperature and OU condensing temperature plot with the compressor speed, at detailed timestep resolution. It seems there are no pressure output variables.

image

**Comment by yujiex** [comment]
I did some more investigation on the COP

I think the difference in COP and compressor electricity rate are expected as the cycling and low-speed-no-cycling uses different evaporating temperatures. 

I did the following investigation

We observed a large difference between compressor electricity rate (compressor power), and COP when one model is cycling and the other model is not cycling. The x-axis is the index of timestamps.

image

I selected this time period for a closer look. During this period the compressor in the "curve 2" model is cycling and the compressor in the "curve 1" model is always running. Columns K and Q are the compressor power calculated using Te, Tc, and compressor power curves. Columns L and R are compressor power outputs from the simulation result file.

image

The following table and plot compare the evaporative capacity. Columns K and Q are the evaporative capacity calculated using Te, Tc, and evaporative capacity curves. Columns L and R are evaporative capacity outputs from the simulation result file.

image

I compared the COP in the following table and plot. Columns L and N are the COP calculated using Te, Tc, and COP curves. Columns L and R are COP outputs from the simulation result file. The COP columns are calculated using the corresponding evaporative capacity / (compressor power + OU fan power)

image

So I think the COP and Heat Pump Cooling Electricity rate difference are expected due to the change in the evaporating temperature.

The following is a excel with my calculation
[eplusout_comparing COP curve calculated and output.xlsx](https://github.com/NREL/EnergyPlus/files/15358285/eplusout_comparing.COP.curve.calculated.and.output.xlsx)

In the previous version of this comment, there were some noticeable differences between the simulated and calculated compressor power. It is because some of the timesteps the compressor is already above the minimum speed. The compressor power involves interpolation between both the first and second loading index curves. After considering this, the compressor power results between the calculated (in the excel) and the simulation output are really similar now. There are still some small differences in the evaporative capacity. This leads to some differences in the calculated and simulated COP

There are also some differences in the VRF heat pump's total cooling rate. This is likely due to the differences in the zone temperature.

image

**Comment by yujiex** [comment]
@rraustad and @mjwitte . In the [comment above](https://github.com/NREL/EnergyPlus/pull/10353#issuecomment-2113118732), I added some more plots to verify the COP, cooling rate, and compressor power against the calculated results from using the curves. The evaporative capacity and power curves are in [this comment](https://github.com/NREL/EnergyPlus/pull/10353#issuecomment-2108794924). Please see if they make sense. Thanks.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (dareumnam) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I'm curious why the VRF heat pump's cooling electricity rate is higher when the cycling ratio is less than 1 (for example, on 4/9 at 14:00 and 15:00) compared to when the cycling ratio is exactly 1 (on 4/9 at 16:00 and 17:00).

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 11 above)
Comment (dareumnam) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:14165]: It doesn't seem like the cycling ratio is double-counted. If we want to make sure, maybe we could double-check the output result against the hand calculation result at a certain fixed timestep.

**Comment by dareumnam** [comment]
I believe @rraustad's insight on [Yujie's comment above](https://github.com/NREL/EnergyPlus/pull/10353#issuecomment-2113118732) is crucial for us to proceed with this PR. Any additional input would be greatly appreciated @rraustad.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: That's a good question. From [this figure](https://github.com/NREL/EnergyPlus/pull/10353#issuecomment-2110831149) suction temperature is also changing which will change the refrigerant mass flow rate at the same volumetric flow rate. So there are other things changing in this model. I guess I would add suction temperature and refrigerant mass flow rate to these plots to see if something can be identified as the driving force for the difference in cooling electricity rate. I also see 2 variables for OU fan power. I'm not sure what N_fan_OU_evap and m_air_evap are regarding the outdoor unit performance but I see that these variables are related to air mass flow rates. Are these variables also changing at these times? I think you will have to dig a little deeper into the model to understand if the Heat Pump Electricity Rate shown above is correct or not.

    // OU fan power
    N_fan_OU = N_fan_OU_evap + N_fan_OU_cond;

        N_fan_OU_evap = this->RatedOUFanPower * m_air_evap / m_air_rated;
        N_fan_OU_cond = this->RatedOUFanPower * m_air_cond / m_air_rated;

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Oh, and add outdoor temperature since that is also a driving force of performance.

Comment (rraustad) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Also add VRF Heat Pump Outdoor Unit Evaporator Heat Extract Rate so we can see what is happening at the evaporator.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: @dareumnam and @rraustad. I created the following plots. There is not an output variable for refrigerant flow. I will add some custom outputs later. The Outdoor Unit Evaporator Heat Extract Rate is 0 during cooling mode, in both periods, 04/06 and 04/09.

The following are a few plots for the 04/09 period. The fact that heat pump electricity is higher when cycling ratio < 1 than when cycling ratio = 1, seems to originate from the compressor power, which also has this behavior. I will dig deeper into this.

image
[compare_outputs_cyclingRatio_non1to2_update.xlsx](https://github.com/user-attachments/files/15778642/compare_outputs_cyclingRatio_non1to2_update.xlsx)

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I looked at the following two points, at 4/6 12:20 and 4/6/ 14:20. The former has heat pump cycling ratio = 0.949, the latter has cycling ratio of 1.0. The former has higher compressor power (which leads to higher heat pump electricity rate) than the latter. 
image

This is because its evaporating temperature is lower. The condensing temperature is pretty similar, lower evaporating temperature will lead to higher curve value (see the following compressor curve at this speed). 

image

As the compressor electricity rate is computed as the following, the compressor power (before multiplying cycling ratio is higher) at the 12:20 due to lower evaporating temperature.
```
Ncomp = this->RatedCompPower * CurveValue(state, this->OUCoolingPWRFT(CounterCompSpdTemp), T_discharge, T_suction);
```

The evaporating temperature is lowered during cycling as there was a low-load modification mechanism in the fluid control VRF, where they enlarge the compressor evaporating capacity by changing the evaporating temperature (see the red shaded part), so that the equipment can cycle less.
image

@rraustad @dareumnam

**Comment by rraustad** [comment]
This effort got a little off the rails with discussion. The original issue was a difference in power/COP with a change in the min speed curve limit. This is very hard to understand for a model that is changing coil air flow to meet a load, and the refrigerant side property (Te), which could then impact the condensing temp (Tc). The cycling issue with PLF should not change the energy use magnitude much because it's just a startup loss so comparing cycling to not cycling is just a small difference (more energy if cycling), if everything else is the same. But with this model, everything else is not the same. We should back up to the original issue and compare a develop to this branch result. Is energy use now as expected? Annual energy difference? Are the code changes reasonable?, etc.

**Comment by yujiex** [comment]
> This effort got a little off the rails with discussion. The original issue was a difference in power/COP with a change in the min speed curve limit. This is very hard to understand for a model that is changing coil air flow to meet a load, and the refrigerant side property (Te), which could then impact the condensing temp (Tc). The cycling issue with PLF should not change the energy use magnitude much because it's just a startup loss so comparing cycling to not cycling is just a small difference (more energy if cycling), if everything else is the same. But with this model, everything else is not the same. We should back up to the original issue and compare a develop to this branch result. Is energy use now as expected? Annual energy difference? Are the code changes reasonable?, etc.

Regarding the original issue. The speed_900.idf has 8 speed levels, the lowest speed level curve is curve set 1. The speed_1920.idf has 7 speed levels, the lowest speed level curve is curve set 2. speed_1920.idf is derived from speed_900.idf by removing the lowest speed level curve set (there are two curves for each speed level). The following are the "Evaporative Capacity Multiplier Function of Temperature Curve Name" and "Compressor Power Multiplier Function of Temperature Curve Name" of Curve 1 and 2 at 35F are most relevant.
image

The following is the develop branch output. We can see that both of them have cycling ratio=1. However, with different lowest-speed curves, they still deliver the same total cooling rate. This is unreasonable. 
image

The following is the feature branch output. We can see in both cases the VRF system is cycling. Since curve set 1 can supply lower cooling capacity for the same evaporating, condensing temperature combination, it should cycle less, which is indeed the case here. Compressor power for the speed_900 output is slightly larger than the speed_1920 one as it runs for longer period and that the power curve is higher.
image

Annual energy difference is shown in the following table
image

The following attaches the input idfs and output tables
[ouput_dev.zip](https://github.com/user-attachments/files/15974163/ouput_dev.zip)
[output_feature.zip](https://github.com/user-attachments/files/15974164/output_feature.zip)
[input.zip](https://github.com/user-attachments/files/15974169/input.zip)

@rraustad

**Comment by yujiex** [comment]
@Myoldmopar  and @dareumnam would you mind taking another look at this PR? Thanks.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (dareumnam) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Are the refrigerant mass flow rates the same at both points? (4/6 12:20 and 4/6/ 14:20)

**Comment by dareumnam** [comment]
So, in the original issue, the min-compressor-speed capacity was different at two points in the code flow. To fix this, you moved the cycling ratio calculation inside the compressor speed calculation. After the fix, the output from this branch shows a different cycling ratio, which seems reasonable. Could you please explain a bit more about whether the energy use or VRF cooling electricity rate are as expected? I would like to be convinced that the Heat Pump Electricity Rate shown above is correct.
@rraustad, do you have any further comments or suggestions?

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 4 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Hi @dareumnam, there is not a refrigerant flow rate output variable. I used some debug prints to output this variable (`m_ref_IU_evap_i ` and `m_ref_IU_evap` in cooling mode). The refrigerant flow at 12:20 is 0.01058698505294939, and the refrigerant flow at 14:20 is 0.012904189061317716.

**Comment by yujiex** [comment]
> So, in the original issue, the min-compressor-speed capacity was different at two points in the code flow. To fix this, you moved the cycling ratio calculation inside the compressor speed calculation. After the fix, the output from this branch shows a different cycling ratio, which seems reasonable. Could you please explain a bit more about whether the energy use or VRF cooling electricity rate are as expected? I would like to be convinced that the Heat Pump Electricity Rate shown above is correct. @rraustad, do you have any further comments or suggestions?

@dareumnam Looking at the tables in this [comment](https://github.com/NREL/EnergyPlus/pull/10353#issuecomment-2189590504). Compressor power become much more similar after the fix. This is anticipated, as according to the power multiplier curve plots in the same comment, the curve 1 value is around 0.07 and the curve 2 value is around 0.1 (a 0.7 to 1 relationship). The curve value need to multiply the rated compressor power and cycling ratio to get the compressor power. The cycling ratio of the two example files are about 0.55 to 0.81 (see first row of the second table below the curve plots in that same comment), which is a 1 to 0.68 relationship. Since the power curve values are 0.7 to 1 (between the two examples) and the cycling ratios are 1 to 0.68, the final compressor power should be pretty similar.

This leads to very similar heat pump cooling electricity rate after the fix. This is reasonable as the cooling electricity rate is the sum of compressor power and fan power. Fan power here is the same. Compressor power is very similar as is explained above, heat pump cooling electricity rate should also be similar.

**Comment by dareumnam** [comment]
Thanks for the detailed explanation which makes sense to me. I built this branch locally, and everything looks clean. The diffs are expected and well-explained. I appreciate your hard work on the VRF models, @yujiex. I believe this is ready to be merged. @Myoldmopar

**Comment by yujiex** [comment]
Thanks @dareumnam

File: src/EnergyPlus/Material.cc [hunk 13]
```diff
@@ -211,7 +211,7 @@ void GetMaterialData(EnergyPlusData &state, bool &ErrorsFound) // set to true if
         state.dataMaterial->TotMaterials += 1 + TotFfactorConstructs + TotCfactorConstructs;
     }
 
-    // yujie: This looks kind of silly, but we need it to keep the Materials array in IDF order.
+    // This looks kind of silly, but we need it to keep the Materials array in IDF order.
```
Comment (Myoldmopar) [inline src/EnergyPlus/Material.cc]: This caused a conflict.  I'll fix it.

Comment (Myoldmopar) [reply src/EnergyPlus/Material.cc]: Actually maybe it wasn't this...?

**Comment by Myoldmopar** [comment]
Alright, resolved the conflict and built/tested.  Everything is all happy.  This will merge assuming CI stays clean.

**Comment by Myoldmopar** [comment]
Alright, merging here. Thanks @yujiex , and @dareumnam.

**Comment by yujiex** [comment]
Thanks @Myoldmopar
