### PR TITLE
Fix #9489 - Construction:AirBoundary fails for fenestration surfaces

### LINKED ISSUE #9489: Construction:AirBoundary fails for fenestration surfaces
Issue overview
--------------
The I/O Reference states that Construction:AirBoundary "may be used for base surfaces and fenestration surfaces." This fails for both window and door surfaces.

For a window, it's rejected because the materials are not window materials.
```
   ** Severe  ** FenestrationSurface:Detailed="SB21-W1" has an opaque surface construction; it should have a window construction.
   ** Severe  ** FenestrationSurface:Detailed="SB12-W1" has an opaque surface construction; it should have a window construction.
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.
```

For a door, there is a surface alignment issue. 
```
   ** Severe  ** GetSurfaceData: Subsurface="SB12-W1" exterior condition [interzone surface] in a base surface="TOP-1" with exterior condition [ExternalEnvironment]
   **   ~~~   ** ...calculations for heat balance would be compromised.
   ** Severe  ** GetSurfaceData: Subsurface="SB21-W1" exterior condition [interzone surface] in a base surface="F1-1" with exterior condition [Ground]
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.
```
SB12-W1 is on base surface SB12, not TOP-1. And SB21-W1 is on base surface SB21.

This likely was broken when Construction:AirBoundary was condensed to remove the solar and radiant enclosure fields. Should this be allowed? Maybe, maybe not. If the opening is large relative to the base surface, then it makes sense to group the spaces into the same enclosure. But if the opening is small, does it make sense to combine the entire enclosure?

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.1.0
 - Direct e-mail from user on 06 Jun 2022.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files attached: [5ZoneAirCooled_AirBoundaries-Fenestration-Window.idf.txt](https://github.com/NREL/EnergyPlus/files/8902718/5ZoneAirCooled_AirBoundaries-Fenestration-Window.idf.txt)
[5ZoneAirCooled_AirBoundaries-Fenestration-Door.idf.txt](https://github.com/NREL/EnergyPlus/files/8902719/5ZoneAirCooled_AirBoundaries-Fenestration-Door.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #9489
 - Fixes missing "Parent Surface" column in Envelope Summary - Interior Fenestration table. This will cause table diffs for any file with an interior window.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I know this has been discussed a good amount on Slack, but it would be good to recap the status here on the PR.  @jmarrec or @mjwitte if you could update this with your thoughts on the latest status I'll get to reviewing it soon.  Thanks!

**Comment by mjwitte** [comment]
@Myoldmopar We discussed some solutions and roadblocks on slack, but I have not looked at the PR yet. Feel free to go ahead or assign to me for review next week.

**Comment by Myoldmopar** [comment]
Sounds good.  Let's just plan on getting this reviewed up next week, whether it's you or me.  I'll just need to take some time to grok the conversation and make sure the PR is up to date with the outcomes of the discussion.

File: src/EnergyPlus/DataSurfaces.hh [hunk 1]
```diff
@@ -1773,7 +1773,7 @@ struct SurfacesData : BaseGlobalStruct
     Array1D<Real64> SurfWinDividerHeatLoss;
     Array1D<Real64> SurfWinTCLayerTemp;           // The temperature of the thermochromic layer of the window
     Array1D<Real64> SurfWinSpecTemp;              // The specification temperature of the TC layer glass Added for W6 integration June 2010
-    Array1D<Real64> SurfWinWindowModelType;       // if set to WindowBSDFModel, then uses BSDF methods
+    Array1D<int> SurfWinWindowModelType;          // if set to WindowBSDFModel, then uses BSDF methods
```
Comment (mjwitte) [inline src/EnergyPlus/DataSurfaces.hh:1776]: Somewhat unrelated, but this should have always been `int`. At some point it will be `enum`ed, but not here.

File: src/EnergyPlus/DaylightingManager.cc [hunk 2]
```diff
@@ -4058,8 +4058,7 @@ void GetDaylightingParametersInput(EnergyPlusData &state)
             max(state.dataViewFactor->EnclSolInfo(enclNum).TotalEnclosureDaylRefPoints, state.dataDaylightingManager->maxNumRefPtInAnyEncl);
     }
 
-    for (int SurfNum = 1; SurfNum <= state.dataSurface->TotSurfaces; ++SurfNum) {
-        if (state.dataSurface->Surface(SurfNum).Class != SurfaceClass::Window) continue;
+    for (int SurfNum : state.dataSurface->AllHTWindowSurfaceList) {
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc:4061]: This saves an if, and it fixes the need to skip air boundary sub-surfaces (which aren't included by this point in HT surface lists).

File: src/EnergyPlus/HeatBalanceManager.cc [hunk 3]
```diff
@@ -6443,19 +6443,11 @@ namespace HeatBalanceManager {
...
-            auto &thisSurface(state.dataSurface->Surface(SurfNum));
-            if (thisSurface.Class == DataSurfaces::SurfaceClass::Window) {
-                auto &thisConstruct(thisSurface.Construction);
-                if (!state.dataConstruction->Construct(thisConstruct).WindowTypeBSDF) {
-                    state.dataHeatBal->SurfWinFenLaySurfTempFront(SurfNum, 1) = state.dataHeatBalSurf->SurfOutsideTempHist(1)(SurfNum);
-                    state.dataHeatBal->SurfWinFenLaySurfTempBack(SurfNum, state.dataConstruction->Construct(thisConstruct).TotLayers) =
-                        state.dataHeatBalSurf->SurfInsideTempHist(1)(SurfNum);
-                }
-            }
+        for (int SurfNum : state.dataSurface->AllHTWindowSurfaceList) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceManager.cc:6446]: Simplify this function, again, eliminating air boundary sub-surfaces from the loop.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 4]
```diff
@@ -1570,6 +1569,12 @@ namespace SurfaceGeometry {
         Array1D<bool> SurfaceTmpClassMoved; // Tmp class is moved
         SurfaceTmpClassMoved.dimension(state.dataSurface->TotSurfaces, false);
 
+        // Old SurfNum to New SurfNum
+        // Old = order in state.dataSurfaceGeometry->SurfaceTmp
+        // New = order in state.dataSurface->Surface
+        EPVector<int> oldToNewSurfNums;
+        oldToNewSurfNums.resize(state.dataSurface->TotSurfaces, -1);
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:1577]: Simplify the surface sorting process and fix sorting of air-boundary subsurfaces and tracking of their base surfaces.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 5]
```diff
@@ -6965,6 +6965,670 @@ TEST_F(EnergyPlusFixture, HeatBalanceIntRadExchange_SetupEnclosuresWithAirBounda
     EXPECT_EQ(state->dataViewFactor->EnclSolInfo(2).TotalSurfArea, enclTotSurfArea);
 }
 
+TEST_F(EnergyPlusFixture, TwoZones_With_AirDoor)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:6968]: 2 new units tests, nice.

**Review by mjwitte — COMMENTED** [review]
This is a good start, but it still fails for the 5ZoneAirCooled_AirBoundaries-Fenestration-Window defect file.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 6]
```diff
@@ -1051,24 +1051,28 @@ void GatherForPredefinedReport(EnergyPlusData &state)
...
                         }
+                        PreDefTableEntry(state, state.dataOutRptPredefined->pdchIntFenSHGC, surfName, SHGCSummer, 3);
+                        PreDefTableEntry(state, state.dataOutRptPredefined->pdchIntFenVisTr, surfName, TransVisNorm, 3);
+                        // compute totals for area weighted averages
+                        intShgcArea += SHGCSummer * windowAreaWMult;
+                        intVistranArea += TransVisNorm * windowAreaWMult;
                     }
-                    PreDefTableEntry(state, state.dataOutRptPredefined->pdchIntFenSHGC, surfName, SHGCSummer, 3);
-                    PreDefTableEntry(state, state.dataOutRptPredefined->pdchIntFenVisTr, surfName, TransVisNorm, 3);
                     PreDefTableEntry(state, state.dataOutRptPredefined->pdchIntFenParent, surfName, Surface(iSurf).BaseSurfName);
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:1072]: This line was here all along to report the parent surface name.

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 7]
```diff
@@ -190,6 +190,7 @@ namespace OutputReportPredefined {
         s->pdchIntFenUfact = newPreDefColumn(state, s->pdstIntFen, "Glass U-Factor [W/m2-K]");
         s->pdchIntFenSHGC = newPreDefColumn(state, s->pdstIntFen, "Glass SHGC");
         s->pdchIntFenVisTr = newPreDefColumn(state, s->pdstIntFen, "Glass Visible Transmittance");
+        s->pdchIntFenParent = newPreDefColumn(state, s->pdstIntFen, "Parent Surface");
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportPredefined.cc:193]: But this line was missing in the initial table setup, so the parent surface column wasn't there.

File: src/EnergyPlus/OutputReportPredefined.hh [hunk 8]
```diff
@@ -1226,913 +1226,7 @@ struct OutputReportPredefinedData : BaseGlobalStruct
...
-        this->TotalAllAirLoopsAtVozDynOccForOA = 0.0;
-        this->TotalAnyAirLoopAboveVozDynOccForOA = 0.0;
-        this->TotalAnyAirLoopVentUnoccForOA = 0.0;
-        this->reportName.deallocate();
-        this->subTable.deallocate();
-        this->columnTag.deallocate();
-        this->tableEntry.deallocate();
-        this->CompSizeTableEntry.deallocate();
-        this->ShadowRelate.deallocate();
+        *this = OutputReportPredefinedData();
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportPredefined.hh:1229]: I thought I would need to add `pdchIntFenParent` as a new variable, but it was already there. Trimmed down the `clear_state` function anyway.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 9]
```diff
@@ -2282,7 +2287,10 @@ namespace SurfaceGeometry {
                     if (state.dataHeatBal->Zone(ZoneNum).AllSurfaceFirst == 0) {
                         state.dataHeatBal->Zone(ZoneNum).AllSurfaceFirst = SurfNum;
                     }
-                    if (state.dataSurface->Surface(SurfNum).IsAirBoundarySurf) continue;
+                    if (state.dataSurface->Surface(SurfNum).IsAirBoundarySurf) {
+                        state.dataSurface->Surface(SurfNum).HeatTransSurf = false;
+                        continue;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2292]: Need to set `HeatTransSurf = false` sooner here so that the HT surface lists are built correctly.

**Review by mjwitte — COMMENTED** [review]
@Myoldmopar @jmarrec Found and fixed the issue with 5ZoneAirCooled_AirBoundaries-Fenestration-Window. The air boundary window was still showing up in `AllHTWindowSurfaceList` (and any HT surface list), because `Surface(SurfNum).HeatTransSurf` wasn't set to false soon enough in the process.

Also, fixed up the Interior Fenestration table in the Envelope Summary. If CI comes back clean (will have table diffs for any test with interior windows) then this is ready for @Myoldmopar 's final review.

**Comment by Myoldmopar** [comment]
CI does look happy here.  Windows is showing a stray, certainly unrelated, issue.  I'll do some review now.

File: src/EnergyPlus/DaylightingManager.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DaylightingManager.cc:4061]: :+1:

File: src/EnergyPlus/HeatBalanceManager.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HeatBalanceManager.cc:6446]: :+1:

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 10]
```diff
@@ -1051,24 +1051,28 @@ void GatherForPredefinedReport(EnergyPlusData &state)
...
                     PreDefTableEntry(state, state.dataOutRptPredefined->pdchIntFenUfact, surfName, nomUfact, 3);
-                    // if the construction report is requested the SummerSHGC is already calculated
-                    if (state.dataConstruction->Construct(curCons).SummerSHGC != 0) {
-                        SHGCSummer = state.dataConstruction->Construct(curCons).SummerSHGC;
-                        TransVisNorm = state.dataConstruction->Construct(curCons).VisTransNorm;
-                    } else {
-                        // must calculate Summer SHGC
-                        if (!state.dataConstruction->Construct(curCons).WindowTypeEQL) {
-                            CalcNominalWindowCond(state, curCons, 2, nomCond, SHGCSummer, TransSolNorm, TransVisNorm, errFlag);
+                    if (!state.dataConstruction->Construct(curCons).TypeIsAirBoundary) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:1054]: OK, so just protect the code from executing when we don't want it.  :+1:

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 4 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:1577]: I get the point here.  I won't claim to be closely tracking all the different arrays of indices to different groups of surfaces, but I understand their intent and appreciate them from a performance standpoint.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 9 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:2292]: :+1:

**Review by Myoldmopar — APPROVED** [review]
No issue with this.  Wrapping up local testing, but this should merge shortly if all is well.

**Comment by Myoldmopar** [comment]
Verified the issue in develop and the fix with this branch.  This is good to go.  Merging, thanks @jmarrec and @mjwitte .
