### PR TITLE
Issue severe errors for component node connection in AirLoopHVAC:OutdoorAirSystem:EquipmentList

### LINKED ISSUE #9994: AirLoopHVAC:DedicatedOutdoorAirSystem does not work with draw through fan placement
Issue overview
--------------
AirLoopHVAC:DedicatedOutdoorAirSystem does not work when the fan placement is draw through. Please refer to the Unmethours link below for mroe details on the issue.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: V22-2-0
 - Unmethours link: [AirLoopHVAC:DedicatedOutdoorAirSystem does not work with draw through fan placement](https://unmethours.com/question/90738/airloophvacdedicatedoutdoorairsystem-does-not-work-with-draw-through-fan-placement/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lgu1234**
Pull request overview
---------------------
 - Fixes #9994 
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

When the component order in AirLoopHVAC:OutdoorAirSystem:EquipmentList is switched, all component nodes should be re-configurated. For example, the inlet node in the first component should be one of outdoor air node, and the outlet node should be the inlet node of AirLoopHVAC:Splitter. The current code does not issue any error messages after component order switch only.

The fix issues severe error messages.

More node connections are checked to ensure the outlet node in the previous component should be the same as the inlet node in the current component. Otherwise, a severe error is issued. 

The defect file is uploaded. 

The above fix provides error messages for node connection check. The issue of zero fan mass flow in all component nodes, except for outdoor air node, has not been solved, when the fan is not placed as blow thorough. The cause is incorrect set up of inlet node values of both MassFlowRateMax and MassFlowRateMaxAvail. After correcting these values in the "CalcAirLoopDOAS", the issue is fixed.

The defect file is also uploaded.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [X ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [X ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -782,6 +784,38 @@ namespace AirLoopHVACDOAS {
...
+                if (!OutletnodeFound) {
+                    ShowSevereError(
+                        state,
+                        format("Outlet node is not the inlet node of AirLoopHVAC:Splitter in {} = {}", CurrentModuleObject, thisDOAS.Name));
+                    ShowContinueError(state,
+                                      format("The outlet node name is {}, and the inlet node name of AirLoopHVAC:Splitter is {}",
+                                             state.dataLoopNodes->NodeID(thisDOAS.m_OutletNodeNum),
+                                             state.dataLoopNodes->NodeID(thisDOAS.m_CompPointerAirLoopSplitter->InletNodeNum)));
+                    errorsFound = true;
+                }
```
Comment (lgu1234) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:824]: Issue severe errors to ensure the inlet node of the first component is one of outdoor air nodes and the outlet node of the last component is the inlet node of AirLoopHVAC:Splitter.

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 2]
```diff
@@ -4340,6 +4340,9 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestOACompOutletNodeIndex)
     state->dataAirSystemsData->PrimaryAirSystems(3).Name = "PSZ-AC:3";
     state->dataAirSystemsData->PrimaryAirSystems(4).Name = "PSZ-AC:4";
     state->dataAirSystemsData->PrimaryAirSystems(5).Name = "PSZ-AC:5";
+    state->dataOutAirNodeMgr->NumOutsideAirNodes = 1;
+    state->dataOutAirNodeMgr->OutsideAirNodeList.allocate(1);
+    state->dataOutAirNodeMgr->OutsideAirNodeList(1) = 1;
```
Comment (lgu1234) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:4345]: Set up the node number for outdoor air node

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 3]
```diff
@@ -8759,6 +8762,10 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestOACompFanNoDrawAndBlow)
     state->dataAirSystemsData->PrimaryAirSystems(4).Name = "PSZ-AC:4";
     state->dataAirSystemsData->PrimaryAirSystems(5).Name = "PSZ-AC:5";
 
+    state->dataOutAirNodeMgr->NumOutsideAirNodes = 1;
+    state->dataOutAirNodeMgr->OutsideAirNodeList.allocate(1);
+    state->dataOutAirNodeMgr->OutsideAirNodeList(1) = 1;
+
```
Comment (lgu1234) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:8768]: Set up the node number for outdoor air node

**Comment by nrel-bot-2b** [comment]
@lgu1234 it has been 23 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@lgu1234 it has been 7 days since this pull request was last updated.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 4]
```diff
@@ -382,6 +383,7 @@ namespace AirLoopHVACDOAS {
 
                 thisSplitter.name = UtilityRoutines::makeUPPER(thisObjectName);
                 thisSplitter.InletNodeName = UtilityRoutines::makeUPPER(fields.at("inlet_node_name").get<std::string>());
+                thisSplitter.InletNodeNum = UtilityRoutines::FindItemInList(thisSplitter.InletNodeName, state.dataLoopNodes->NodeID);
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:386]: Why use `FindItemInList` instead of `GetOnlySingleNode` (which will register this node connection in the BND output)?

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 5]
```diff
@@ -782,6 +799,38 @@ namespace AirLoopHVACDOAS {
...
                 state.dataAirLoopHVACDOAS->airloopDOAS.push_back(thisDOAS);
+
+                // ensure the inlet node should be an outdoor air node
+                bool OAnodeFound = false;
+                for (int OutsideAirNodeNum = 1; OutsideAirNodeNum <= state.dataOutAirNodeMgr->NumOutsideAirNodes; ++OutsideAirNodeNum) {
+                    if (thisDOAS.m_InletNodeNum == state.dataOutAirNodeMgr->OutsideAirNodeList(OutsideAirNodeNum)) {
+                        OAnodeFound = true;
+                        break;
+                    }
+                }
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc]: There is a function for this:
`if(!OutAirNodeManager::CheckOutAirNodeNumber(state, thisDOAS.m_InletNodeNum) {`

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 6]
```diff
@@ -782,6 +799,38 @@ namespace AirLoopHVACDOAS {
...
+                                           CurrentModuleObject,
+                                           thisDOAS.Name));
+                    errorsFound = true;
+                }
+                // Ensure the outlet node is the splitter inlet node
+                bool OutletnodeFound = false;
+                if (thisDOAS.m_OutletNodeNum == thisDOAS.m_CompPointerAirLoopSplitter->InletNodeNum) {
+                    OutletnodeFound = true;
+                }
+                if (!OutletnodeFound) {
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc]: Minor, but `OutletnodeFound` isn't necessary here, just collapse this into a single `if`.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 7]
```diff
@@ -695,6 +697,21 @@ namespace AirLoopHVACDOAS {
                         ShowSevereError(state, format("Outlet node number is not found in {} = {}", CurrentModuleObject, CompName));
                         errorsFound = true;
                     }
+                    // Check node connection to ensure that the outlet node of the previous component is the inlet node of the current component
+                    if (CompNum > 1) {
+                        if (thisOutsideAirSys.InletNodeNum(CompNum) != thisOutsideAirSys.OutletNodeNum(CompNum - 1)) {
+                            ShowSevereError(state,
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:703]: The error message here and below should include the routinename and lead with the name of the DOAS System, e.g.:
```
getAirLoopMixer:  Node connection error in AirLoopHVAC:DedicatedOutdoorAirSystem=AirLoopHVAC DOAS.
Inlet node . . . .
```

**Review by mjwitte — COMMENTED** [review]
@lgu1234 When testing the defect files, I see the new error messages from 9994.idf.
Comparing before and after for 9994_MassFLow.idf, what changes should I look for?

**Comment by lgu1234** [comment]
@mjwitte The 9994_MassFLow.idf is used to test mass flow rate in all components listed in AirLoopHVAC:OutdoorAirSystem:EquipmentList:
 
  AirLoopHVAC:OutdoorAirSystem:EquipmentList,
    OA Sys 1 Equipment,      !- Name
    Coil:Heating:Water,      !- Component 2 Object Type
    OA Heating Coil 1,       !- Component 2 Name
    Coil:Cooling:Water,      !- Component 3 Object Type
    OA Cooling Coil 1,       !- Component 3 Name
    Fan:SystemModel,         !- Component 1 Object Type
    OA Supply Fan;           !- Component 1 Name

The fix show all node mass flow rates are the same. However, the mass flow rate before the fix in the OA Cooling Coil 1 Air Outlet Node is zero.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 4 above)
Comment (lgu1234) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:386]: The GetOnlySingleNode requires an enum of DataLoopNode::ConnectionObjectType. The current object of AirLoopHVAC:Splitter is not listed in the connection type. I am going to post a new issue to add more objects in the connection type. I will make changes after new objects are listed in the connection type. For the time being, I keep as is.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 5 above)
Comment (lgu1234) [reply src/EnergyPlus/AirLoopHVACDOAS.cc]: @mjwitte Done. Thanks.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 6 above)
Comment (lgu1234) [reply src/EnergyPlus/AirLoopHVACDOAS.cc]: @mjwitte Done.

**Comment by mjwitte** [comment]
> @mjwitte The 9994_MassFLow.idf is used to test mass flow rate in all components listed in AirLoopHVAC:OutdoorAirSystem:EquipmentList:
> The fix show all node mass flow rates are the same. However, the mass flow rate before the fix in the OA Cooling Coil 1 Air Outlet Node is zero.

@lgu1234 Thanks, I see it now.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 7 above)
Comment (lgu1234) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:703]: @mjwitte Done.

**Review by mjwitte — APPROVED** [review]
@lgu1234 Thanks for the cleanups. Please remember to post a new issue about the DataLoopNode::ConnectionObjectType missing AirLoopHVAC:Splitter. I'll let CI finish, then merge this.
