### PR TITLE
Fix #7195 - Table output file incorrectly reports capacity of water-to-water heat pumps

### LINKED ISSUE #7195: Table output file incorrectly reports capacity of water-to-water heat pumps
Table output file incorrectly reports capacity of water-to-water heat pumps
--------------
In the Table output file, it appears that the capacity of water-to-water heat pumps is incorrectly reported.

In the Central Plant section of the Table output file, there is a column with heading "Nominal Capacity". 
 When central plant objects of the class HeatPump:WaterToWater:EquationFit:Cooling are present, it appears that the values appearing in this column do not properly reflect the IDF field "Reference Cooling Capacity" in that object class, but rather the IDF field "Reference Cooling Power Consumption".

Therefore, in the case of water-to-water heat pumps, the value appearing in the "Nominal Capacity" column in the Table output file is not actually the Nominal Capacity, but rather the Nominal Capacity divided by the COP.

We also observed all of the above with HeatPump:WaterToWater:EquationFit:Heating.  Please correct me if I am wrong?  Otherwise please confirm our observations of this error?

Thanks in advance, Matt

### Details
 - Windows 10
 - EnergyPlus v. 8.7.0

----

**Edit Julien M:**

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: `testfiles/WWHPSimpleAuto.idf` exhibits this behavior
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #7195 - Table output file incorrectly reports capacity of water-to-water heat pumps (previous versions report power instead of capacity)

Reporting issue only, no impact on simulation.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [x] Functional code review (it has to work!)
 - [x] If defect, results of running current develop vs this branch should exhibit the fix
 - [x] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add to input rules file for interfaces
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Required documentation updates?
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by rraustad** [comment]
Ran defect file (WWHPSimpleAuto.idf):

```
 Component Sizing Information, HeatPump:WaterToWater:EquationFit:Cooling, GSHPCLG, Design Size Nominal Capacity [W], 22602.54060
 Component Sizing Information, HeatPump:WaterToWater:EquationFit:Heating, GSHPHEATING, Design Size Nominal Capacity [W], 22156.62963
```

image

File: src/EnergyPlus/HeatPumpWaterToWaterSimple.cc [hunk 1]
```diff
@@ -1576,7 +1576,7 @@ namespace HeatPumpWaterToWaterSimple {
             // create predefined report
             OutputReportPredefined::PreDefTableEntry(OutputReportPredefined::pdchMechType, this->Name, "HeatPump:WaterToWater:EquationFit:Heating");
             OutputReportPredefined::PreDefTableEntry(OutputReportPredefined::pdchMechNomEff, this->Name, this->refCOP);
-            OutputReportPredefined::PreDefTableEntry(OutputReportPredefined::pdchMechNomCap, this->Name, this->RatedPowerHeat);
+            OutputReportPredefined::PreDefTableEntry(OutputReportPredefined::pdchMechNomCap, this->Name, this->RatedCapHeat);
```
Comment (rraustad) [inline src/EnergyPlus/HeatPumpWaterToWaterSimple.cc:1579]: Ouch, corrected typo.

**Review by rraustad — APPROVED** [review]
Changes correct reported capacity for WWHP.

**Comment by rraustad** [comment]
Reviewed code and unit test.
