### PR TITLE
Fixing cooling mode cooling coil cooling rate much higher than heat pump cooling rate and OU capacity

### LINKED ISSUE #10187: VRF fluid control model cooling rate at terminal unit is much higher than cooling rate at system level
Issue overview
--------------
The terminal unit cooling rate is higher than the system cooling rate when the system cannot meet the load. The following output is produced when the "Rated Evaporative Capacity {W}" is set to 500W while "Rated Total Cooling Capacity {W}" is 10023 W. The "Cooling Coil Total Cooling Rate" is much larger than "VRF Heat Pump Total Cooling Rate".

image

With the following idf setting

image

### Defect file
[US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf.txt](https://github.com/NREL/EnergyPlus/files/12479284/US%2BSF%2BCZ4A%2Bhp%2Bcrawlspace%2BIECC_2006_VRF.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #10607: sensible + latent output doesn't match total output energy in VRF
Issue overview
--------------

The following is how the sensible and latent output is computed in `CalcVRF_FluidTCtrl` and `CalcVRF`
```
    LoadMet = AirMassFlow * PsyDeltaHSenFnTdb2W2Tdb1W1(TempOut, SpecHumOut, TempIn, SpecHumIn); // sensible {W}
    LatentLoadMet = AirMassFlow * (SpecHumOut - SpecHumIn);                                     // latent {kgWater/s}
```
The `LatentLoadMet` in kgWater/s is converted to W in function `ReportVRFTerminalUnit`
```
    Real64 const H2OHtOfVap = PsyHgAirFnWTdb(0.0, TempOut);
    // convert latent in kg/s to watts
    TotalConditioning = SensibleConditioning + (LatentConditioning * H2OHtOfVap);

    if (TotalConditioning <= 0.0) {
        state.dataHVACVarRefFlow->VRFTU(VRFTUNum).TotalCoolingRate = std::abs(TotalConditioning);
        state.dataHVACVarRefFlow->VRFTU(VRFTUNum).TotalHeatingRate = 0.0;
    ...
```
This is different from the calculation in the `GeneralRoutines.cc` as follows

```
        TotalOutput = MassFlow * (Psychrometrics::PsyHFnTdbW(TDB2, W2) - Psychrometrics::PsyHFnTdbW(TDB1, W1)); // total addition/removal rate, {W};
        SensibleOutput = MassFlow * Psychrometrics::PsyDeltaHSenFnTdb2W2Tdb1W1(TDB2, W2, TDB1, W1); // sensible addition/removal rate, {W};
        LatentOutput = TotalOutput - SensibleOutput;                                                // latent addition/removal rate, {W}
```

However when adding the sensible output to this latent output computed as the above as `(AirMassFlow * (SpecHumOut - SpecHumIn)) * PsyHgAirFnWTdb(0.0, TempOut)`, the total does not match the TotalOutput computed as follows.
```
TotalOutput = AirMassFlow * (Psychrometrics::PsyHFnTdbW(TempOut, SpecHumOut) - Psychrometrics::PsyHFnTdbW(TempIn, SpecHumIn)); // total addition/removal rate, {W};
```

This can be observed by adding this to the code and running the `US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf` example file using weather file `USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw`:

```
    // calculate sensible load met using delta enthalpy
    LoadMet = AirMassFlow * PsyDeltaHSenFnTdb2W2Tdb1W1(TempOut, SpecHumOut, TempIn, SpecHumIn); // sensible {W}
    LatentLoadMet = AirMassFlow * (SpecHumOut - SpecHumIn);                                     // latent {kgWater/s}
    // debug print
    if (AirMassFlow > 0.0) {
        Real64 diff = abs(LoadMet + LatentLoadMet * PsyHgAirFnWTdb(0.0, TempOut) -
                          AirMassFlow * (Psychrometrics::PsyHFnTdbW(TempOut, SpecHumOut) - Psychrometrics::PsyHFnTdbW(TempIn, SpecHumIn)));
        if (diff > 10) {
            fmt::print("too large difference at {}: diff = {}, TempOut={}, SpecHumOut={}, TempIn={}, SpecHumIn={}\n",
                       state.dataEnvrn->CurMnDyHr,
                       diff,
                       TempOut,
                       SpecHumOut,
                       TempIn,
                       SpecHumIn);
        }
    }
```

This txt file has all has the output with the debugging print
[large_diff.txt](https://github.com/user-attachments/files/16240158/large_diff.txt)

The following is an instance with large difference between the TotalOutput and the SensibleOutput + LatentOutput

```
diff = 10.083951937490237, 
TempOut=18.710784212366956, 
SpecHumOut=0.012661531422619608, 
TempIn=23.888585998167404, 
SpecHumIn=0.014184600203099161
```

### Defect file
US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf  with USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac, 13.5.2)
 - Version of EnergyPlus (24.1)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by yujiex**
Pull request overview
---------------------
 - Fixes #10187 
 - Fixes #10607

For both the original and the fluid-control VRF model, terminal unit capacity should have been constrained by condenser capacity, where a maximum allowable terminal unit capacity is calculated in `LimitTUCapacity(.)` for each VRF system. The maximum allowable terminal unit capacity is stored in `state.dataHVACVarRefFlow->MaxCoolingCapacity(VRFCond)` and passed into `SimDXCoil(.)` which is NOT passed into `CalcVRFCoolingCoil_FluidTCtrl(.)`, as compared with the non-fluid-control VRF model, `CalcVRFCoolingCoil(.)`

This PR will add an optional argument `MaxCoolCap` to `CalcVRFCoolingCoil_FluidTCtrl(.)` as is in CalcVRFCoolingCoil(.) and use this quantity to constrain the cooling coil capacity.
 
The following shows the effect of the fix: before the fix, cooling coil cooling rate is much higher than heat pump cooling rate; after the fix, the two cooling rate are similar. The test file used here is the US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf example file, using NY weather epw input. The "Rated Evaporative Capacity" of the "AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl" is adjusted to 500W.

image

### Regression diff

The following files have regression diff
- DOASDXCOIL_wADPBFMethod
- DOASDXCOIL_wADPBFMethod_NoReturnPath
- DOAToVRF
- HVACTemplate-5ZoneVRF
- US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF
- VRFMultispeedFan
- VariableRefrigerantFlow_5Zone
- VariableRefrigerantFlow_5Zone_wAirloop
- VariableRefrigerantFlow_FluidTCtrl_5Zone
- VariableRefrigerantFlow_FluidTCtrl_HR_5Zone
- VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone
- VariableRefrigerantFlow_wSuppHeater_5Zone
- _DOASDXCOIL_wUserSHRMethod

#### ESO difference

The following files have ESO diffs in Zone VRF Air Terminal Total(Latent) Cooling(Heating) Rate. These are expected as a result of the changes in the total and latent system output calculation which fixed the problem of total != sensible + latent output.

- DOASDXCOIL_wADPBFMethod
- DOASDXCOIL_wADPBFMethod_NoReturnPath
- DOAToVRF
- HVACTemplate-5ZoneVRF
- VRFMultispeedFan
- VariableRefrigerantFlow_5Zone
- VariableRefrigerantFlow_5Zone_wAirloop
- VariableRefrigerantFlow_wSuppHeater_5Zone
- _DOASDXCOIL_wUserSHRMethod

The 4 files with fluidTCtrl VRF model (
US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF, VariableRefrigerantFlow_FluidTCtrl_5Zone, VariableRefrigerantFlow_FluidTCtrl_HR_5Zone, VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone
) have difference in many more fields as follows. The core difference is the coil cooling rate and the VRF air terminal cooling rate. The cooling coil cooling rate difference (due to a capacity limit added in this feature) will also cause difference in compressor side cooling output, such as cooling rate, cooling electricity rate, etc. Piping correction is also affected as it's calculated as (coil cooling rate) / (coil cooling rate + piping loss). The coil cooling rate difference will also cause the temperature and air flow difference in corresponding nodes. The coil cooling rate difference will affect zone temperature as well (In the extreme case, when OU capacity is very small, the zone might not be able to control to setpoint temperature any more. This won't happen if coil has unlimited capacity like before the fix). Zone temperature difference would result in slight difference in heating coil and supplemental heating coil heating rate as well.

  - Zone Air Temperature 
- Zone Air Relative Humidity 
- Zone Air Temperature 
- Zone Air Relative Humidity 
- Zone Air System Sensible Heating Rate 
- Zone Air System Sensible Cooling Rate 
- Zone Predicted Sensible Load to Setpoint Heat Transfer Rate 
- Zone Predicted Sensible Load to Heating Setpoint Heat Transfer Rate 
- Zone Predicted Sensible Load to Cooling Setpoint Heat Transfer Rate 
- Fan Electricity Rate 
- Cooling Coil Total Cooling Rate 
- Cooling Coil Sensible Cooling Rate 
- Cooling Coil Latent Cooling Rate 
- Cooling Coil Runtime Fraction 
- Zone VRF Air Terminal Cooling Electricity Rate 
- Zone VRF Air Terminal Cooling Electricity Energy 
- Zone VRF Air Terminal Total Cooling Rate 
- Zone VRF Air Terminal Sensible Cooling Rate 
- Zone VRF Air Terminal Latent Cooling Rate 
- Zone VRF Air Terminal Heating Electricity Rate 
- Zone VRF Air Terminal Heating Electricity Energy 
- Zone VRF Air Terminal Total Heating Rate 
- Zone VRF Air Terminal Sensible Heating Rate 
- Zone VRF Air Terminal Latent Heating Rate 
- VRF Heat Pump Total Cooling Rate 
- VRF Heat Pump Total Heating Rate 
- VRF Heat Pump Cooling Electricity Rate 
- VRF Heat Pump Cooling Electricity Energy 
- VRF Heat Pump Heating Electricity Rate 
- VRF Heat Pump Heating Electricity Energy 
- VRF Heat Pump Compressor Electricity Rate 
- VRF Heat Pump Compressor Rotating Speed 
- VRF Heat Pump Outdoor Unit Condensing Temperature 
- VRF Heat Pump Outdoor Unit Evaporating Temperature 
- System Node Standard Density Volume Flow Rate 
- System Node Wetbulb Temperature 
- System Node Standard Density Volume Flow Rate 

#### EIO difference

EIO difference are in the four idfs with FluidTCtrl model. There are some warmup differences in each zone in the model. This is expected as the coil cooling rate difference will change the zone temperature, which affects the warmup convergence.

#### Meter diff

Meter diffs happen in two of the idfs with VRF FluidTCtrl object. It is expected as the cooling coil cooling rate difference will also affect its electricity rate, and corresponding HVAC, Facility electricity rate part of which is coil electricity rate.

#### Table string diffs

These table diffs happen in the four idfs with VRF FluidTCtrl objects. The diffs are in warmup statistics and electricity rate, which are explained in the eio diff and meter diff sections.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -231,7 +231,7 @@ void SimDXCoil(EnergyPlusData &state,
         CalcDXHeatingCoil(state, DXCoilNum, PartLoadRatio, fanOp, AirFlowRatio, MaxCap);
     } break;
     case HVAC::CoilVRF_FluidTCtrl_Cooling: {
-        CalcVRFCoolingCoil_FluidTCtrl(state, DXCoilNum, HVAC::CompressorOp::On, FirstHVACIteration, PartLoadRatio, fanOp, CompCycRatio, _, _);
+        CalcVRFCoolingCoil_FluidTCtrl(state, DXCoilNum, HVAC::CompressorOp::On, FirstHVACIteration, PartLoadRatio, fanOp, CompCycRatio, _, _, MaxCap);
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:234]: I'm not sure why the max capacity is not always passed into the coil. It's either 1.0e+20 or it's a value. That's for another day.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 2]
```diff
@@ -11374,9 +11374,6 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state)
         if (Q_c_TU_PL > CompEvaporatingCAPSpdMax) {
             // Required load is beyond the max system capacity
 
-            Q_c_TU_PL = CompEvaporatingCAPSpdMax;
-            TU_CoolingLoad = CompEvaporatingCAPSpdMax;
-            this->TUCoolingLoad = TU_CoolingLoad;
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11372]: Should TU_CoolingLoad be reset here or not? This var is used at line 11385 below. For a VRF system with 1 TU this might make sense but for multiple TUs this will likely have no impact.

File: src/EnergyPlus/DXCoils.cc (hunk 1 above)
Comment (yujiex) [reply src/EnergyPlus/DXCoils.cc:234]: I just changed MaxCoolCap to regular non-optional arguments. @rraustad

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc [hunk 3]
```diff
@@ -11540,9 +11537,9 @@ void VRFCondenserEquipment::CalcVRFCondenser_FluidTCtrl(EnergyPlusData &state)
         this->PipingCorrectionCooling = TU_CoolingLoad / (TU_CoolingLoad + Pipe_Q_c);
         state.dataHVACVarRefFlow->MaxCoolingCapacity(VRFCond) = this->CoolingCapacity; // for report, maximum evaporating capacity of the system
 
-        this->HeatingCapacity = 0.0;         // Include the piping loss
-        this->PipingCorrectionHeating = 1.0; // 1 means no piping loss
-        state.dataHVACVarRefFlow->MaxHeatingCapacity(VRFCond) = 0.0;
+        this->HeatingCapacity = 0.0;                                 // Include the piping loss
+        this->PipingCorrectionHeating = 1.0;                         // 1 means no piping loss
+        state.dataHVACVarRefFlow->MaxHeatingCapacity(VRFCond) = 0.0; // yujie: might be wrong here too, should be MaxCap = 1e+20
```
Comment (rraustad) [inline src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Please check where MaxHeatingCapacity and MaxCoolingCapacity get set to MaxCap(1.0e+20). That will answer your question. It should either be set to MaxCap or not set at all. Maybe this is the reason that MaxCap is an optional argument, because it's 0 at times. If this var were never set to 0, and only set to MaxCap when reset is needed, and only reduced when the system is overloaded, then MaxCap could always be passed to the coil model and NOT be an optional argument.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 2 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc:11372]: It shouldn't be reset here. Similar to the situation in the heating side, which we fixed a while ago: https://github.com/NREL/EnergyPlus/pull/10154
I copied in the relative discussion here:
image

This upper bounding will cause the compressor to reduce its output at more extreme weather, which is bad. So this upper bounding needs to be removed.

**Comment by rraustad** [comment]
This change did improve the results based on the data shown in the description. This may be for a different issue, but how can coil capacity ever exceed HP capacity? Isn't it sum of coil capacity + piping losses = HP capacity? So coil capacity should always be less than or equal to HP capacity.

**Comment by yujiex** [comment]
> This change did improve the results based on the data shown in the description. This may be for a different issue, but how can coil capacity ever exceed HP capacity? Isn't it sum of coil capacity + piping losses = HP capacity? So coil capacity should always be less than or equal to HP capacity.

Indeed, I'll look into this. There might still be something not quite right. Coil cooling rate should be no more than heat pump cooling rate

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: I just changed MaxCoolCap to non-optional.
I think this initialization here (`state.dataHVACVarRefFlow->MaxHeatingCapacity(VRFCond) = 0.0`) might be just an error. The default for capacity limit should be a really large number, so that no limit is placed.

**Comment by yujiex** [comment]
> This change did improve the results based on the data shown in the description. This may be for a different issue, but how can coil capacity ever exceed HP capacity? Isn't it sum of coil capacity + piping losses = HP capacity? So coil capacity should always be less than or equal to HP capacity.

I investigated this and found the issue might be caused by this 0.65 min fan speed ratio constraint. 

```
    FanSpdRatioMin = min(max(OAMassFlow / Garate, 0.65), 1.0); // ensure that coil flow rate is higher than OA flow rate
```

After removing this constraint, the difference become smaller and the coil cooling rate is slightly smaller than HP cooling rate

image

@rraustad

**Comment by Myoldmopar** [comment]
@yujiex in addition to the diffs in a handful of files, there are 3 unit tests that are now failing and must be dealt with before this goes much further.  And at least one of the test failures is quite a significant change.  We can discuss on technicalities if needed.

**Comment by yujiex** [comment]
> @yujiex in addition to the diffs in a handful of files, there are 3 unit tests that are now failing and must be dealt with before this goes much further. And at least one of the test failures is quite a significant change. We can discuss on technicalities if needed.

Hi @Myoldmopar. The unit test failing is caused by this change (if you revert this part, the unit test can run through).

image

Previously the coil TotalCoolingEnergyRate and SensCoolingEnergyRate uses the InletAirMassFlowRate (shown in the following code chunk) instead of the AirMassFlow computed using the `FanSpdRatio` output from function `ControlVRFIUCoil`

```
        Real64 AirMassFlowRate = thisDXCoil.InletAirMassFlowRate;
        // Coil total/sensible/latent cooling rates
        CalcComponentSensibleLatentOutput(AirMassFlowRate,
                                          InletAirDryBulbTemp,
                                          InletAirHumRat,
                                          OutletAirTemp,
                                          OutletAirHumRat,
                                          thisDXCoil.SensCoolingEnergyRate,
                                          thisDXCoil.LatCoolingEnergyRate,
                                          thisDXCoil.TotalCoolingEnergyRate);

```

This might be wrong. The air flow should be changed to meet the cooling demand.

For example, in heating mode, the heating energy rate is actually computed using the `AirMassFlow` from function `ControlVRFIUCoil`

```
        ControlVRFIUCoil(state,
                         DXCoilNum,
                         QCoilReq,
                         thisDXCoil.InletAirTemp,
                         thisDXCoil.InletAirHumRat,
                         thisDXCoil.CondensingTemp,
                         AirMassFlowMin,
                         FanSpdRatio,
                         OutletAirHumRat,
                         OutletAirTemp,
                         OutletAirEnthalpy,
                         ActualSH,
                         ActualSC);
        AirMassFlow = FanSpdRatio * thisDXCoil.RatedAirMassFlowRate(Mode);
        ...
        thisDXCoil.TotalHeatingEnergyRate = AirMassFlow * (OutletAirEnthalpy - InletAirEnthalpy) * PartLoadRatio;
```

**Comment by Myoldmopar** [comment]
@yujiex does this have any more status updates after the technicalities call last week?

**Comment by yujiex** [comment]
> @yujiex does this have any more status updates after the technicalities call last week?

Hi @Myoldmopar , I am working on resolving this unit test "VRF_FluidTCtrl_ReportOutputVerificationTest". The other two has been fixed. For this unit test, I found that in addition to the air mass flow rate variable cause I have identified last time, this line below also fails (mismatching between coil and TU cooling rate). I am trying to figure out the source and try to fix it today.
```
    EXPECT_NEAR(thisDXCoolingCoil.TotalCoolingEnergyRate, (thisVRFTU.TotalCoolingRate + thisFan->totalPower), 0.0001);
```

**Comment by yujiex** [comment]
@Myoldmopar I fixed the unit tests.

**Comment by yujiex** [comment]
Hi @Myoldmopar, would you mind taking another look? Thanks.

**Comment by nrel-bot-2c** [comment]
@Myoldmopar @yujiex @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/HVACVariableRefrigerantFlow.cc (hunk 3 above)
Comment (dareumnam) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: Have you checked where `MaxHeatingCapacity` and `MaxCoolingCapacity` are set to MaxCap(1.0e+20)? Or if you believe this initialization is an error, I think you can correct the code line and delete the comment in this code.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: It should be 1.0e+20. I'll change it and remove the comment.

Comment (yujiex) [reply src/EnergyPlus/HVACVariableRefrigerantFlow.cc]: @dareumnam. I corrected the code line and removed the comment on the 4th. Sorry I forgot to ping you. Please see if it looks okay. Thanks

**Comment by dareumnam** [comment]
@rraustad, Do you have any further comments on this? I think it's good to go after @Myoldmopar's final review, unless you have additional feedback.

**Comment by Myoldmopar** [comment]
This has now got conflicts from all the other merges.  @yujiex could you resolve them?  If so this might be ready.

**Comment by yujiex** [comment]
@Myoldmopar I will resolve the conflict in a bit (on bus now)

**Comment by yujiex** [comment]
@Myoldmopar I just resolved the conflict.

**Comment by Myoldmopar** [comment]
Thanks, let's see how CI responds in like 30 minutes.

**Comment by Myoldmopar** [comment]
image

OK OK 35 minutes not 30.  

So there are 2 more files now showing big diffs.  I wonder what's caused that.  Do you have any idea?

**Comment by yujiex** [comment]
@Myoldmopar It's strange, as the additional diffs happen in "CentralChillerHeaterSystem_Cooling_Heating" and "CentralChillerHeaterSystem_Simultaneous_Cooling_Heating", which doesn't have the VRF objects. Could it be because I'm not up-to-date with the develop?

I just pulled develop and again and run regression on those two locally, they don't show diffs.

**Comment by Myoldmopar** [comment]
Hmmm.  Now that you mention it, maybe so.  I was just bragging about how we wouldn't see diffs just from being behind develop.  But maybe there's still a way.  When the CI system is doing the build, it checks out the current develop as the baseline.  Because CI is a bit bogged down right now, develop has definitely been moving fast.  So yeah, it's possible.  In most scenarios it won't be happening, just if develop moves really really fast.

**Comment by yujiex** [comment]
> Hmmm. Now that you mention it, maybe so. I was just bragging about how we wouldn't see diffs just from being behind develop. But maybe there's still a way. When the CI system is doing the build, it checks out the current develop as the baseline. Because CI is a bit bogged down right now, develop has definitely been moving fast. So yeah, it's possible. In most scenarios it won't be happening, just if develop moves really really fast.

seems develop is getting many things merged in today

**Comment by Myoldmopar** [comment]
Back to the 11 ESO big diffs like above.  Seems like that took care of it.  Thanks @yujiex

**Comment by yujiex** [comment]
Thanks @Myoldmopar

**Comment by Myoldmopar** [comment]
This has a conflict in the unit test.  I'm doing a final quick test on #10416 and then try to resolve the conflict.  If it's minor I'll handle it, but if it's more complex, I'll toss it back over to you.

**Comment by Myoldmopar** [comment]
I resolved the test conflicts and everything is passing locally.  I'm going to stop for lunch and let CI catch up and get fresh results to confirm I've got this ready.  If CI is clean this can go in.

**Comment by yujiex** [comment]
Thanks for handling the conflict @Myoldmopar

**Comment by Myoldmopar** [comment]
Looks like I didn't break anything with my conflict resolution, merging this.  Thanks @yujiex
