### PR TITLE
EnergyPlus crash when CoilSystem:Cooling:DX or AirloopHVAC:UnitarySystem is used in OutdoorAirSystem

### LINKED ISSUE #9074: New segfault with 9.6.0-IOFreeze with COILSYSTEM:COOLING:DX
Issue overview
--------------

An OpenStudio-resources regression test that was running with 9.5 is now segfaulting with 9.6. There is little change happening when I manually VT the 9.5 idf, aside from the Space Name being added and the `AirLoopHVAC:OutdoorAirSystem` availability manager list that is a removed field.

Segfault is here: 
https://github.com/NREL/EnergyPlus/blob/9779acae724bcb169287783dca83e0371122e17c/src/EnergyPlus/AirLoopHVACDOAS.cc#L619-L624

```
Process 104128 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff0dcf7f0 libenergyplusapi.so.9.6.0`EnergyPlus::AirLoopHVACDOAS::AirLoopDOAS::getAirLoopDOASInput(state=0x00007fffffffb700) at AirLoopHVACDOAS.cc:624:144
   621 	                            state.dataAirLoop->OutsideAirSys(thisDOAS.m_OASystemNum)
   622 	                                .compPointer[CompNum]
   623 	                                ->getAirInNode(
-> 624 	                                    state, state.dataAirLoop->OutsideAirSys(thisDOAS.m_OASystemNum).ComponentName(CompNum), 0, InletNodeErrFlag);
```

Last commit that touched it is https://github.com/NREL/EnergyPlus/commit/93540c3fd2a00ec8206655ac426308c698ca4d43 from #8729

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 20.04
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6.0-IOFreeze, also occurs with v9.6.0-RC2 (9779acae724bcb169287783dca83e0371122e17c)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9074
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9074
 - Improper access to CoilSystem:Cooling:DX and AirloopHVAC:UnitarySystem when used in outdoor air system equipment list

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Expecting 0 diffs since no unit test or example files exist for this issue.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -617,6 +618,11 @@ namespace AirLoopHVACDOAS {
                         state.dataAirLoop->OutsideAirSys(thisDOAS.m_OASystemNum).OutletNodeNum(CompNum) =
                             HVACHXAssistedCoolingCoil::GetCoilOutletNode(state, CompType, CompName, OutletNodeErrFlag);
                     } else if (SELECT_CASE_var == "COILSYSTEM:COOLING:DX") {
+                        if (state.dataAirLoop->OutsideAirSys(thisDOAS.m_OASystemNum).compPointer[CompNum] == nullptr) {
+                            UnitarySystems::UnitarySys thisSys;
+                            state.dataAirLoop->OutsideAirSys(thisDOAS.m_OASystemNum).compPointer[CompNum] =
+                                thisSys.factory(state, DataHVACGlobals::UnitarySys_AnyCoilType, CompName, false, 0);
+                        }
```
Comment (rraustad) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:625]: Must set the compPointer in 2 places. I guess the IF NULL isn't needed since this is looping through the OA system equipment list for the first and only time. Clean this out when unit test AND example file are created.

**Comment by rraustad** [comment]
Defect resolution description: Calls to UnitarySystem getAirInNode and getAirOutNode in AirLoopHVACDOAS.cc use pointer access to these member functions, however, the compPointer was never set so that these functions could be called.

**Comment by rraustad** [comment]
@Myoldmopar @mjwitte back to you.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:625]: :+1:

**Comment by Myoldmopar** [comment]
@jmarrec confirmed this fix, not waiting on anything else.  Unit tests and new or modified integration files can be added anytime.  But for now, merging.  Thanks for the quick fix @rraustad !
