### PR TITLE
Fix plant heat storage tracking

### LINKED ISSUE #7931: Plant excessive heat storage tracking issues
Issue overview
--------------
There are a few problems with the tracking for these warnings:
```
** Warning ** Plant Loop: CONDENSER WATER LOOP Demand Side is storing excess heat the majority of the time.
** Warning ** Plant Loop: CONDENSER WATER LOOP Supply Side is storing excess heat the majority of the time.
```
1. The supply side and demand side warnings are both testing the demand side data [here](https://github.com/NREL/EnergyPlus/blob/185e20e71c38982ae12f355ab950587cc20caa7f/src/EnergyPlus/Plant/PlantManager.cc#L4344-L4354).

2. `LoopSideInlet_CapExcessStorageTime` and `LoopSideInlet_TotalTime` accumulate on every plant iteration and during warmup. They should only accumulate after warmup and at the end of each system timestep.

3. Loops which are maintaining a constant loop supply temp are reporting non-zero values for " . . .  Plant Demand Side Lumped Capacitance Excessive Storage Time" (and Supply side).

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.3.0
 - Noticed this while working on #7653.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files attached:
[5ZoneBoilerOutsideAirReset-ddays.idf.txt](https://github.com/NREL/EnergyPlus/files/4481072/5ZoneBoilerOutsideAirReset-ddays.idf.txt)
[PlantComponentTemperatureSource.idf.txt](https://github.com/NREL/EnergyPlus/files/4481073/PlantComponentTemperatureSource.idf.txt)

 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #7931
 - Changes method to calculate excessive plant storage. New method is sensitive to small flows and direction of storage flows.
 - Corrects time accounting. Previously every iteration counted time towards excess storage. This fix only counts once per iteration.

Diffs
---------------------
Annual simulations run locally on Windows, 1 test files has new excess heat storage warnings, and 41 have warnings removed.
[annual-composite-err.diff.txt](https://github.com/NREL/EnergyPlus/files/6135248/annual-composite-err.diff.txt)

For design day simulations, 5 files have new warnings (all are derivatives of WindACAuto, and 42 have warnings removed.
```
+   ** Warning ** Plant Loop: HOT WATER LOOP Supply Side is storing excess heat the majority of the time.
+   **   ~~~   ** Excesss Storage Time=12.83[hr], Total Loop Active Time=24.00[hr]
```
[ddaysonly-composite-err.diff.txt](https://github.com/NREL/EnergyPlus/files/6135245/ddaysonly-composite-err.diff.txt)

Much much better.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/Plant/PlantManager.cc [hunk 1]
```diff
@@ -4348,8 +4344,8 @@ namespace EnergyPlus {
                     ShowWarningError("Plant Loop: " + PlantLoop(LoopNum).Name +
                                      " Demand Side is storing excess heat the majority of the time.");
                 }
-                if (PlantLoop(LoopNum).LoopSide(DemandSide).LoopSideInlet_CapExcessStorageTime >
-                    PlantLoop(LoopNum).LoopSide(DemandSide).LoopSideInlet_TotalTime / 2) {
+                if (PlantLoop(LoopNum).LoopSide(SupplySide).LoopSideInlet_CapExcessStorageTime >
+                    PlantLoop(LoopNum).LoopSide(SupplySide).LoopSideInlet_TotalTime / 2) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/Plant/PlantManager.cc]: The C++ compiler should've understood our intention here and told us to put `SupplySide` instead.

File: src/EnergyPlus/HVACInterfaceManager.cc [hunk 2]
```diff
@@ -717,21 +717,11 @@ namespace HVACInterfaceManager {
...
-        // Determine excessive storage
-        if (PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_MdotCpDeltaT <
-            PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_McpDTdt) {
-            PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_CapExcessStorageTimeReport = TimeStepSys;
-            PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_CapExcessStorageTime += TimeStepSys;
-        } else {
-            PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_CapExcessStorageTimeReport = 0;
-        }
-        PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_TotalTime += TimeStepSys;
-
```
Comment (Myoldmopar) [inline src/EnergyPlus/HVACInterfaceManager.cc:720]: So I guess you moved this because the hvac interface is being called too often, and this is overcounting?

File: src/EnergyPlus/Plant/PlantManager.cc [hunk 3]
```diff
@@ -2728,43 +2728,39 @@ namespace EnergyPlus {
...
+                                side.LoopSideInlet_CapExcessStorageTime += TimeStepSys;
+                            } else {
+                                side.LoopSideInlet_CapExcessStorageTimeReport = 0;
+                            }
+                        } else {
+                            side.LoopSideInlet_CapExcessStorageTimeReport = 0;
+                        }
+                    }
+                }
+            }
```
Comment (Myoldmopar) [inline src/EnergyPlus/Plant/PlantManager.cc:2735]: This seems a reasonable spot to me; I see you modified the logic a bit too.

File: tst/EnergyPlus/unit/HVACInterfaceManager.unit.cc [hunk 4]
```diff
@@ -80,15 +81,19 @@ TEST_F(EnergyPlusFixture, ExcessiveHeatStorage_Test)
...
     DataLoopNode::Node.allocate(TotNumLoops);
     DataLoopNode::Node(1).Temp = 100;
     DataLoopNode::Node(1).MassFlowRate = 10;
+    PlantLoop(1).OutletNodeFlowrate = 10;
 
     // LoopSideInlet_MdotCpDeltaT should be < LoopSideInlet_McpDTdt
     // Therefore CapExcessStorageTime AND TotalTime will increase by 1 timestep
     UpdateHalfLoopInletTemp(1, 1, TankOutletTemp);
+    // Excess storage calcs moved here
+    PlantManager::UpdateNodeThermalHistory();
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/HVACInterfaceManager.unit.cc]: Interesting that you didn't see any change at all in expected results.

**Review by Myoldmopar — COMMENTED** [review]
I don't necessarily have any issues with the changes, but it would be great to chat to help me understand them fully.

**Comment by Myoldmopar** [comment]
I was scanning through the CI results and with all the ERR diffs I was hoping to find many false positives had been removed/reduced, but it looks like they are almost entirely adding more demand side results.  I need to understand the logic changes a little more.

File: src/EnergyPlus/HVACInterfaceManager.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/HVACInterfaceManager.cc:720]: Correct.

**Comment by mjwitte** [comment]
> I was scanning through the CI results and with all the ERR diffs I was hoping to find many false positives had been removed/reduced, but it looks like they are almost entirely adding more demand side results. I need to understand the logic changes a little more.

@Myoldmopar Correct, I don't think this is the correct logic yet. See additional discussion over in #7931

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Searching the err diff results from a local regression suite (ddays only) finds 86 new warnings in 78 files, and 76 removed warnings in 47 files. 
[Tests-DDOnly_20200831-100049-err diff results.txt](https://github.com/NREL/EnergyPlus/files/5151377/Tests-DDOnly_20200831-100049-err.diff.results.txt).
Will review some of the files that have new warnings to see what's up.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
Um, that's impossible. More diffs on Mac than Linux? And my local windows results are somewhere in between. Lovely.
```
FixPlantHeatStorageTracking-7931 (mjwitte) - x86_64-MacOS-10.15-clang-11.0.0: OK (2990 of 2990 tests passed, 97 test warnings)
97 tests had: ERR diffs.

FixPlantHeatStorageTracking-7931 (mjwitte) - x86_64-Linux-Ubuntu-18.04-gcc-7.5: OK (3029 of 3030 tests passed, 51 test warnings)
51 tests had: ERR diffs.

```

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@mjwitte @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@Myoldmopar @mitchute Finally finished with this, ready for final review.

File: src/EnergyPlus/HVACInterfaceManager.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/HVACInterfaceManager.cc:720]: Still valid I see.

File: src/EnergyPlus/Plant/PlantManager.cc [hunk 5]
```diff
@@ -2694,48 +2694,45 @@ namespace EnergyPlus::PlantManager {
...
             }
+            if (state.dataPlnt->TotNumLoops > 0 && !state.dataGlobal->WarmupFlag) {
+                for (auto &loop : state.dataPlnt->PlantLoop) {
+                    for (auto &side : loop.LoopSide) {
+                        if (loop.OutletNodeFlowrate > DataHVACGlobals::SmallMassFlow) {
+                            // Accumulate total time loop is active
+                            side.LoopSideInlet_TotalTime += TimeStepSys;
+                            // Determine excessive storage - if both are moving in the same direction and McpDTdt is larger than MdotCpDeltaT
+                            if ((abs(side.LoopSideInlet_MdotCpDeltaT) > DataHVACGlobals::SmallLoad) &&
+                                ((side.LoopSideInlet_McpDTdt / side.LoopSideInlet_MdotCpDeltaT) > 1.1)) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/Plant/PlantManager.cc:2724]: Some improved logic, nice.

File: tst/EnergyPlus/unit/HVACInterfaceManager.unit.cc [hunk 6]
```diff
@@ -81,16 +84,20 @@ TEST_F(EnergyPlusFixture, ExcessiveHeatStorage_Test)
...
     DataLoopNode::Node(1).MassFlowRate = 10;
+    state->dataPlnt->PlantLoop(1).OutletNodeFlowrate = 10;
 
     // LoopSideInlet_MdotCpDeltaT should be < LoopSideInlet_McpDTdt
     // Therefore CapExcessStorageTime AND TotalTime will increase by 1 timestep
     UpdateHalfLoopInletTemp(*state, 1, 1, TankOutletTemp);
-    EXPECT_NEAR(-500, state->dataPlnt->PlantLoop(1).LoopSide(2).LoopSideInlet_MdotCpDeltaT, 0.001);
+    // Excess storage calcs moved here
+    PlantManager::UpdateNodeThermalHistory(*state);
+    EXPECT_NEAR((2928.82-500), state->dataPlnt->PlantLoop(1).LoopSide(2).LoopSideInlet_MdotCpDeltaT, 0.001);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/HVACInterfaceManager.unit.cc:100]: Excellent use of existing heat storage unit test.

**Review by Myoldmopar — APPROVED** [review]
Looks great!

**Comment by Myoldmopar** [comment]
The code changes looks great, and the CI results are showing great reduction in the heat storage warnings, including the temperature source plant component object example file, which is one of the original defect files.  No other CI issues, all green.  Merging this, thanks @mjwitte !
