### PR TITLE
Bug fixing in ElectricEquipment:ITE:AirCooled calculations

### LINKED ISSUE #7581: Wrong unit in the calculation of ITE Air Inlet Relative Humidity
Issue overview
--------------
The declared unit of the reportable variable `ITE Air Inlet Relative Humidity` is percentage.

`Output:Variable,*,ITE Air Inlet Relative Humidity,hourly; !- Zone Average [%]`

In the current implementation, it is calculated as decimal [0, 1]. Need a quick fix to be multiplied by 100%.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by xuanluo113**
Pull request overview
---------------------
 - Fixes #7581 and #7561 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [ ] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [x] Check any new function arguments for performance impacts
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] I~f new idf included, locally check the err file and other outputs~

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@XuanLuoLBL @lgentile it has been 28 days since this pull request was last updated.

**Comment by xuanluo113** [comment]
@mjwitte Mike, this bug fixing PR is ready for review. We fixed the non-converging issue by
1. Enlarged the component sizing with consideration of the ITE load determined by user input performance curves.
2. Revert the overwrite of the zone return node temperature at HVAC time steps by zone time step values.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 1]
```diff
@@ -5831,11 +5840,45 @@ namespace InternalHeatGains {
                 }
             }
             TDPAirIn = PsyTdpFnWPb(WAirIn, StdBaroPress, RoutineName);
-            RHAirIn = PsyRhFnTdbWPb(TAirIn, WAirIn, StdBaroPress, RoutineName);
+            RHAirIn = 100.0 * PsyRhFnTdbWPb(TAirIn, WAirIn, StdBaroPress, RoutineName); // RHAirIn is %
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc:5827]: @xuanluo113 Moved this correction here so that the relative humidity range outputs are also correct. This should result in more diffs in the test suite data center files.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 2]
```diff
@@ -5831,11 +5840,45 @@ namespace InternalHeatGains {
...
+                Real64 FanPowerAtDesign =
+                        max(ZoneITEq(Loop).DesignFanPower * OperSchedFrac * CurveManager::CurveValue(ZoneITEq(Loop).FanPowerFFCurve, AirVolFlowFracDesignT), 0.0);
+
+
+                if (FanPowerAtDesign + CPUPowerAtDesign > ZoneITEq(Loop).DesignTotalPower) {
+                    DesignTotalPower = FanPowerAtDesign + CPUPowerAtDesign;
+                }
+
+            }
+
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc]: Why repeat all of this every sizing timestep here in `CalcZoneITEq` when it's already been done in `GetInternalHeatGainsInput`? 

Seems you could add variables to the `ZoneITEq` struct and save the result there to use here. This may not even require new variables, seems like the adjusted values could be saved once to `ZoneITEq(Loop).DesignTAirIn,  ZoneITEq(Loop).DesignTotalPower, and  ZoneITEq(Loop).DesignAirVolFlowRate`. What's changing here and what's not?

At a minimum, search the setpoint managers in `GetInternalHeatGainsInput` and save the SPM index for use here. And the block in `GetInternalHeatGainsInput` shouldn't be querying current schedule values - that has no meaning during get input. So maybe some of the code there needs to be removed?

**Review by mjwitte — COMMENTED** [review]
@xuanluo113 I've merged in develop and added a change to place the `*100.0` in the correct place.
I've tested this before and after and the chiller is now larger and the unmet cooling hours drop by 10x.
So, in general this seems to work. Also ran all unit tests successfully.

See more comments below.

**Comment by mjwitte** [comment]
@xuanluo113 Looking at the bnd diffs below, this indicates GetOnlySingleNode is being used repeatedly somewhere that it should not be. Likely the new section in `CalcZoneITEq `?
```
! <Node>,<NodeNumber>,<Node Name>,<Node Fluid Type>,<# Times Node Referenced After Definition>
- Node,4,WEST ZONE DEC OUTLET NODE,Air,6
- Node,5,WEST ZONE IEC OUTLET NODE,Air,7
- Node,6,WEST ZONE CCOIL AIR OUTLET NODE,Air,7
- Node,7,WEST AIR LOOP OUTLET NODE,Air,6
- Node,8,EAST ZONE INLET NODE,Air,5
+ Node,4,WEST ZONE DEC OUTLET NODE,Air,1357
+ Node,5,WEST ZONE IEC OUTLET NODE,Air,1358
+ Node,6,WEST ZONE CCOIL AIR OUTLET NODE,Air,1358
+ Node,7,WEST AIR LOOP OUTLET NODE,Air,2708
+ Node,8,EAST ZONE INLET NODE,Air,1356
```

**Comment by nrel-bot-2b** [comment]
@xuanluo113 it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
Some of these regressions are related to other PRs.  We can pull in develop again and let it re-run, but I would suggest holding off until everyone is satisfied with the code changes.

**Comment by mjwitte** [comment]
@xuanluo113 Much cleaner code now - thanks. A question about the "... Internal Gains Nominal" report, looking at defect file ite-1zone-autosize coil outlet:
```
! <ElectricEquipment:ITE:AirCooled Internal Gains Nominal>,Name,Schedule Name,Zone Name,Zone Floor Area {m2},# Zone Occupants,Equipment Level {W},Equipment/Floor Area {W/m2},Equipment per person {W/person},Fraction Convected,CPU End-Use SubCategory,Fan End-Use SubCategory,UPS End-Use SubCategory,Nominal Minimum Equipment Level {W},Nominal Maximum Equipment Level {W}, Design Air Volume Flow Rate {m3/s}

Develop: 
ElectricEquipment:ITE:AirCooled Internal Gains Nominal, LARGEDATACENTERHIGHITE STANDALONEDATACENTER IT EQUIPMENT 1,DATACENTER EQUIPMENT_SCH,DATACENTER ZN,557.42,0.0,3000000.000,5381.955,1.0,ITE-CPU,ITE-Fans,ITE-UPS,3000000.000,3000000.000,300.0000000000

This branch last week: 
 ElectricEquipment:ITE:AirCooled Internal Gains Nominal, LARGEDATACENTERHIGHITE STANDALONEDATACENTER IT EQUIPMENT 1,DATACENTER EQUIPMENT_SCH,DATACENTER ZN,557.42,0.0,3910935.240,7016.159,1.0,ITE-CPU,ITE-Fans,ITE-UPS,3000000.000,3000000.000,300.0000000000

This branch today:
 ElectricEquipment:ITE:AirCooled Internal Gains Nominal, LARGEDATACENTERHIGHITE STANDALONEDATACENTER IT EQUIPMENT 1,DATACENTER EQUIPMENT_SCH,DATACENTER ZN,557.42,0.0,3000000.000,5381.955,1.0,ITE-CPU,ITE-Fans,ITE-UPS,3000000.000,3000000.000,300.0000000000
```
Looking at the value for "Equipment Level", it is 3000000.000 in develop and now in this branch, but last week in this branch it was 3910935.240. Is the current value correct?

**Comment by xuanluo113** [comment]
@mjwitte Yes. That's expected. With the approach temperature, the sizing is now enlarged to the actual internal heat gain based on the enlarged ITE Fan and CPU power, which are a function of `TAirInDesign` according to input perf curve.  With the approach temperature, `TAirInDesign` is set to the maximum setpoint temperature + approach temperature [here](https://github.com/NREL/EnergyPlus/blob/2145a4498979afe5bd3ba5e4a46a1cc40dfe03ad/src/EnergyPlus/InternalHeatGains.cc#L5834). And the internal heat gain is set [accordingly](https://github.com/NREL/EnergyPlus/blob/2145a4498979afe5bd3ba5e4a46a1cc40dfe03ad/src/EnergyPlus/InternalHeatGains.cc#L5907).

This only applies to the sizing with approach temperature according to input perf curve to avoid the undersizing issue (#7561). So the other two ITE models are not affected and the regression changes only apply to relative humidity.

**Comment by mjwitte** [comment]
@xuanluo113 Your reply is unclear. Which number is correct, 3000000.000 or 3910935.240. This branch is currently reporting 3000000.000.

**Comment by Myoldmopar** [comment]
@xuanluo113 please clarify so we can move forward and get this PR off the todo list.  Thanks.

**Comment by xuanluo113** [comment]
@mjwitte Yes. I misunderstood. The change is also expected. The `NomMaxDesignLevel`  is calculated by [DesignTotalPower](https://github.com/NREL/EnergyPlus/blob/2145a4498979afe5bd3ba5e4a46a1cc40dfe03ad/src/EnergyPlus/InternalHeatGains.cc#L3769).

The commit a week ago I overwrite the `DesignTotalPower` at `GetInternalHeatGainsInput` stage, which was calculated by the maximum setpoint temperature as `TAirInDesign`. In the modified implementation, the at `GetInternalHeatGainsInput` stage,  only the maximum `TAirInDesign` is calculated. The actual  ITE total power is calculated during sizing, based on curve based TAirInlet.

So this indicates the the `DesignTotalPower` only represents the user input value. I wonder if that makes sense.

**Comment by mjwitte** [comment]
@xuanluo113 Ok, thanks for the explanation. I think it's reasonable for the eio output to reflect the user input. Please pull in develop for one final round of CI, then I'll merge.

**Review by mjwitte — APPROVED** [review]
CI looks as expected so far, merging.
