### PR TITLE
Address HSPF2 calculation problems for multispeed DX system

### LINKED ISSUE #9909: HSPF2 calculation problems for multispeed DX systems
Issue overview
--------------
The HSPF2 calculation problems for Multispeed DX system:
- when building load is greater than the full speed capacity [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L3796-L3811) is suspicious compared to the 2023 AHRI Std 210/240 document. I expected three temperature bins: `> 17F`, `5 - 17F` and `< 5F`. 
- Found equations in the current code do not match those in the 2023 AHRI standards 210/240 in three places.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, any)
 - Version of EnergyPlus (develop, [c3360fb](https://github.com/NREL/EnergyPlus/commit/c3360fbc6b67956065ab00dda8cdaf533d397c3c))

#### Excerpts from 2023 AHRI Std 210/240
image

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #10651: StandardsRatings: calculation of metrics can crash if certain preconditions aren't met
Issue overview
--------------

* Found in #10648

Take MultiSpeedHeatPump, for the First Coil:Heating:DX:Multispeed you find, use a flat efficiency curve for both CapFT and CapFFlow.

Run with floating point exceptions:

```patch
diff --git a/testfiles/MultiSpeedHeatPump.idf b/testfiles/MultiSpeedHeatPump.idf
index 79db2f81bd..c5d4a6a04d 100644
--- a/testfiles/MultiSpeedHeatPump.idf
+++ b/testfiles/MultiSpeedHeatPump.idf
@@ -1391,8 +1391,8 @@
     0.45,                    !- Speed 1 Rated Air Flow Rate {m3/s}
     345.0,                   !- Speed 1 Rated Supply Air Fan Power Per Volume Flow Rate {W/(m3/s)}
     934.4,                   !- 2023 Rated Evaporator Fan Power Per Volume Flow {W/(m3/s)}
-    HPACHeatCapFT Speed 1,   !- Speed 1 Heating Capacity Function of Temperature Curve Name
-    HPACHeatCapFF Speed 1,   !- Speed 1 Heating Capacity Function of Flow Fraction Curve Name
+    Flat Curve Always 1,     ! Speed 1 Heating Capacity Function of Temperature Curve Name
+    Flat Curve Always 1,     ! Speed 1 Heating Capacity Function of Flow Fraction Curve Name
     HPACHeatEIRFT Speed 1,   !- Speed 1 Energy Input Ratio Function of Temperature Curve Name
     HPACHeatEIRFF Speed 1,   !- Speed 1 Energy Input Ratio Function of Flow Fraction Curve Name
     HPACHeatPLFFPLR Speed 1, !- Speed 1 Part Load Fraction Correlation Curve Name
@@ -1435,6 +1435,15 @@
     0.2,                     !- Speed 4 Rated Waste Heat Fraction of Power Input {dimensionless}
     HAPCHeatWHFT Speed 4;    !- Speed 4 Waste Heat Function of Temperature Curve Name
 
+  Curve:Cubic,
+    Flat Curve Always 1,     !- Name
+    1,                       !- Coefficient1 Constant
+    0.0,                     !- Coefficient2 x
+    0.0,                     !- Coefficient3 x**2
+    0.0,                     !- Coefficient4 x**3
+    0.5,                     !- Minimum Value of x
+    1.5;                     !- Maximum Value of x
+
   Curve:Cubic,
     HPACHeatCapFT Speed 1,   !- Name
     0.758746,                !- Coefficient1 Constant
```

div by zero:

```
* thread #1, name = 'energyplus', stop reason = signal SIGFPE: invalid floating point operation
    frame #0: 0x00007fffef503378 libenergyplusapi.so.24.2.0`EnergyPlus::StandardRatings::MultiSpeedDXHeatingCoilHSPF2(state=0x00007fffffffabb0, nsp=4, MSFanPowerPerEvapAirFlowRateInput_2023=const ObjexxFCL::Array1A<> @ 0x00007fffffff3de0, CapFTempCurveIndex=ObjexxFCL::Array1A_int @ 0x00007fffffff3e30, CapFFlowCurveIndex=ObjexxFCL::Array1A_int @ 0x00007fffffff3e80, RatedTotalCapacity=const ObjexxFCL::Array1A<> @ 0x00007fffffff3ed0, RatedAirVolFlowRate=const ObjexxFCL::Array1A<> @ 0x00007fffffff3f20, EIRFFlowCurveIndex=ObjexxFCL::Array1A_int @ 0x00007fffffff3f70, EIRFTempCurveIndex=ObjexxFCL::Array1A_int @ 0x00007fffffff3fc0, RatedCOP=const ObjexxFCL::Array1A<> @ 0x00007fffffff4010, RegionNum=ObjexxFCL::Optional_int_const @ 0x00007fffffff3d50, MinOATCompressor=Optional<double const> @ 0x00007fffffff3d60, OATempCompressorOn=Optional<double const> @ 0x00007fffffff3d70, OATempCompressorOnOffBlank=ObjexxFCL::Optional_bool_const @ 0x00007fffffff3d80, DefrostControl=Optional<const EnergyPlus::StandardRatings::HPdefrostControl> @ 0x00007fffffff3d90) at StandardRatings.cc:6345:34
   6342	                    q_H1_low + (q_H0_low - q_H1_low) * ((1.67 - (8.33)) / (16.67 - (8.33)));
   6343	
   6344	                // Equation 11.191 AHRI-2023
-> 6345	                Real64 N_Hq = min(1.0, (q_H2_int - q_35_low) / (q_H2_full - q_35_low));
   6346	                N_Hq = max(0.0, N_Hq);
   6347	                // Equation 11.190 AHRI-2023
   6348	                Real64 M_Hq = (q_H0_low - q_H1_low) / (16.66 - 8.33) * (1.0 - N_Hq) + (q_H2_full - q_H3_full) / (1.66 - (-8.33)) * N_Hq;
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): eb6665f392fc51eb6727ec5d8f7af21722941d79

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9909 
 - Corrects the HSPF2 calculation procedure for multi-speed DX heating coils to match the 2023 AHRI standards 210/240
 - HSPF2 value diffs are expected 
- Fix #10651

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/StandardRatings.cc [hunk 1]
```diff
@@ -6469,18 +6469,30 @@ namespace StandardRatings {
...
+                        q_full = q_H3_full + (q_H2_full - q_H3_full) * t_ratio;
+                        // Equation 11.202 AHRI-2023
+                        p_full = p_H3_full + (p_H2_full - p_H3_full) * t_ratio;
+                    } else if (t >= t_ob || t == (-8.33)) {
+                        Real64 t_ratio = (t - (-8.33)) / (8.33 - (-8.33));
+                        // Equation 11.199 AHRI-2023
+                        q_full = q_H3_full + (q_H1_full - q_H3_full) * t_ratio;
+                        // Equation 11.200 AHRI-2023
+                        p_full = p_H3_full + (p_H1_full - p_H3_full) * t_ratio;
                     }
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc:6499]: The current code for Case III looks incorrect based on the review of the AHRI 2023 (2020) Standard for Performance Rating of Unitary Air-conditioning & Air-source Heat Pump Equipment. This code change matches the AHRI standard and corrects the logic flaws.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 2]
```diff
@@ -4656,7 +4656,7 @@ TEST_F(EnergyPlusFixture, TestMultiSpeedCoilsAutoSizingOutput)
 ! <DX Heating Coil Standard Rating Information>, Component Type, Component Name, High Temperature Heating (net) Rating Capacity {W}, Low Temperature Heating (net) Rating Capacity {W}, HSPF {Btu/W-h}, Region Number
  DX Heating Coil Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 34415.4, 20666.4, 6.56, 4
 ! <DX Heating Coil AHRI 2023 Standard Rating Information>, Component Type, Component Name, High Temperature Heating (net) Rating Capacity {W}, Low Temperature Heating (net) Rating Capacity {W}, HSPF2 {Btu/W-h}, Region Number
- DX Heating Coil AHRI 2023 Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 34697.2, 20948.1, 5.34, 4
+ DX Heating Coil AHRI 2023 Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 34697.2, 20948.1, 5.35, 4
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/DXCoils.unit.cc]: Modified a failed unit test.

**Review by Nigusse — COMMENTED** [review]
Code change walkthrough:
- the code change now match the 2023 AHRI Standard

File: src/EnergyPlus/StandardRatings.cc [hunk 3]
```diff
@@ -6332,17 +6332,17 @@ namespace StandardRatings {
...
                 Real64 q_H1_low = Q_H1_Low(spnum);
                 Real64 q_H2_int = Q_H2_Int(spnum);
-                Real64 q_H1_full = Q_H1_Full(spnum);
-                Real64 q_H2_full = Q_H2_Full(spnum);
-                Real64 q_H3_full = Q_H3_Full(spnum);
-                Real64 q_H4_full = Q_H4_Full(spnum);
+                Real64 q_H1_full = Q_H1_Full(spnum + 1);
+                Real64 q_H2_full = Q_H2_Full(spnum + 1);
+                Real64 q_H3_full = Q_H3_Full(spnum + 1);
+                Real64 q_H4_full = Q_H4_Full(spnum + 1);
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc:6313]: The full heating capacity must be evaluated at the next available speed, not at the current speed. It should be different from the low speed.

File: src/EnergyPlus/StandardRatings.cc [hunk 4]
```diff
@@ -6351,17 +6351,17 @@ namespace StandardRatings {
...
                 Real64 p_H1_low = P_H1_Low(spnum);
                 Real64 p_H2_int = P_H2_Int(spnum);
-                Real64 p_H1_full = P_H1_Full(spnum);
-                Real64 p_H2_full = P_H2_Full(spnum);
-                Real64 p_H3_full = P_H3_Full(spnum);
-                Real64 p_H4_full = P_H4_Full(spnum);
+                Real64 p_H1_full = P_H1_Full(spnum + 1);
+                Real64 p_H2_full = P_H2_Full(spnum + 1);
+                Real64 p_H3_full = P_H3_Full(spnum + 1);
+                Real64 p_H4_full = P_H4_Full(spnum + 1);
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc:6332]: The full electric power input must be evaluated at the next available speed, not at the current speed. It should be different from the low speed.

File: src/EnergyPlus/StandardRatings.cc [hunk 5]
```diff
@@ -6332,17 +6332,17 @@ namespace StandardRatings {
...
+                Real64 q_H3_full = Q_H3_Full(spnum + 1);
+                Real64 q_H4_full = Q_H4_Full(spnum + 1);
                 // Equation 11.177 AHRI-2023
                 //?? (replaced 62 with 35) in Ratio expression // (t=>35-47/62-47)
                 Real64 q_35_low = // q_H1_low + (q_H0_low - q_H1_low) * ((t - (8.33)) / (1.66 - (8.33)));
                     q_H1_low + (q_H0_low - q_H1_low) * ((1.67 - (8.33)) / (16.67 - (8.33)));
 
                 // Equation 11.191 AHRI-2023
-                Real64 N_Hq = min(1.0, (q_H2_int - q_35_low) / (q_H2_full - q_35_low));
+                Real64 N_Hq = (q_H2_full != q_35_low) ? min(1.0, (q_H2_int - q_35_low) / (q_H2_full - q_35_low)) : 0.0;
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc:6320]: Modified to allow evaluation of the HSPF2 with flat heating capacity modifier curves function of temperature.

File: src/EnergyPlus/StandardRatings.cc [hunk 6]
```diff
@@ -6351,17 +6351,17 @@ namespace StandardRatings {
...
+                Real64 p_H3_full = P_H3_Full(spnum + 1);
+                Real64 p_H4_full = P_H4_Full(spnum + 1);
                 // Equation 11.178 AHRI - 2023
                 //?? (replaced 62 with 35) in Ratio expression (t=>35 F-47/35-47)
                 Real64 p_35_low = // p_H1_low + (p_H0_low - p_H1_low) * ((t - (8.33)) / (1.66 - (8.33)));
                     p_H1_low + (p_H0_low - p_H1_low) * ((1.67 - (8.33)) / (16.67 - (8.33)));
 
                 // Equation 11.194 AHRI-2023
-                Real64 N_HE = min(1.0, (p_H2_int - p_35_low) / (p_H2_full - p_35_low));
+                Real64 N_HE = (p_H2_int != p_35_low) ? min(1.0, (p_H2_int - p_35_low) / (p_H2_full - p_35_low)) : 0.0;
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc]: It was modified to allow the evaluation of the HSPF2 with flat heating capacity modifier curves function of temperature.

File: src/EnergyPlus/StandardRatings.cc [hunk 7]
```diff
@@ -6375,35 +6375,63 @@ namespace StandardRatings {
...
+                    // equation 11.180
+                    q_low = Q_H2_Int(spnum) + ((Q_H0_Low(spnum) - Q_H1_Low(spnum)) * ratio);
+                    // equation 11.183
+                    p_low = P_H2_Int(spnum) + ((P_H0_Low(spnum) - P_H1_Low(spnum)) * ratio);
+                } else if (t < 1.67) {
+                    // for now Q_H2_Int is replaced with Q_H_Int, no equation for the later
+                    // equation 11.181
+                    q_low = Q_H2_Int(spnum);
+                    // equation 11.184
+                    p_low = P_H2_Int(spnum);
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc:6374]: It was modified the equations used to calculate delivered heat and energy input at the `Low Speed` to match the 2023 AHRI Standard 210/240.

File: src/EnergyPlus/StandardRatings.cc [hunk 8]
```diff
@@ -6375,35 +6375,63 @@ namespace StandardRatings {
...
+                    p_hs = P_H3_Full(spnum + 1) + ((P_H2_Full(spnum + 1) - P_H3_Full(spnum + 1)) * ratio);
+                } else if ((t >= t_ob) && (t <= -8.33)) {
+                    Real64 ratio = // ((t - (-8.33)) / (8.33 - (-8.33)));
+                        (t - HeatingOutdoorCoilInletAirDBTempH3Test) /
+                        (HeatingOutdoorCoilInletAirDBTempRated - HeatingOutdoorCoilInletAirDBTempH3Test);
+                    // equation 11.199
+                    q_hs = Q_H3_Full(spnum + 1) + ((Q_H1_Full(spnum + 1) - Q_H3_Full(spnum + 1)) * ratio);
+                    // equation 11.200
+                    p_hs = P_H3_Full(spnum + 1) + ((P_H1_Full(spnum + 1) - P_H3_Full(spnum + 1)) * ratio);
                 }
```
Comment (Nigusse) [inline src/EnergyPlus/StandardRatings.cc:6410]: Modified the equations used to calculate delivered heat and energy input at the `High Speed` to match the 2023 AHRI Standard 210/240.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 9]
```diff
@@ -4656,7 +4656,7 @@ TEST_F(EnergyPlusFixture, TestMultiSpeedCoilsAutoSizingOutput)
 ! <DX Heating Coil Standard Rating Information>, Component Type, Component Name, High Temperature Heating (net) Rating Capacity {W}, Low Temperature Heating (net) Rating Capacity {W}, HSPF {Btu/W-h}, Region Number
  DX Heating Coil Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 34415.4, 20666.4, 6.56, 4
 ! <DX Heating Coil AHRI 2023 Standard Rating Information>, Component Type, Component Name, High Temperature Heating (net) Rating Capacity {W}, Low Temperature Heating (net) Rating Capacity {W}, HSPF2 {Btu/W-h}, Region Number
- DX Heating Coil AHRI 2023 Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 34697.2, 20948.1, 5.34, 4
+ DX Heating Coil AHRI 2023 Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 34697.2, 20948.1, 5.76, 4
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/DXCoils.unit.cc:4740]: Modified the HSPF2 values unit test to match latest results. Now the difference between HSPF and HSPF2 reduced to 12.2% from 18.6%.

File: tst/EnergyPlus/unit/DXCoils.unit.cc [hunk 10]
```diff
@@ -6880,4 +6880,773 @@ TEST_F(EnergyPlusFixture, Test_DHW_End_Use_Cat_Removal)
...
+! <DX Heating Coil Standard Rating Information>, Component Type, Component Name, High Temperature Heating (net) Rating Capacity {W}, Low Temperature Heating (net) Rating Capacity {W}, HSPF {Btu/W-h}, Region Number
+ DX Heating Coil Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 14996.6, 8946.7, 8.57, 4
+! <DX Heating Coil AHRI 2023 Standard Rating Information>, Component Type, Component Name, High Temperature Heating (net) Rating Capacity {W}, Low Temperature Heating (net) Rating Capacity {W}, HSPF2 {Btu/W-h}, Region Number
+ DX Heating Coil AHRI 2023 Standard Rating Information, Coil:Heating:DX:MultiSpeed, ASHP HTG COIL, 14996.6, 8946.7, 7.66, 4
+)EIO";
+
+    EXPECT_TRUE(compare_eio_stream(htg_coil_eio_output, true));
+}
+
 } // namespace EnergyPlus
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/DXCoils.unit.cc:7743]: Added three unit tests. These unit tests evaluate HSPF values for various compressor operation control minimum outdoor air temperature and fan power inputs. The unit tests demonstrate that the HSPF2 values are now closer to the HSPF values.

**Review by Nigusse — COMMENTED** [review]
Code change walkthrough for additional issues identified while working on the original defect.

**Comment by Nigusse** [comment]
See below comparison of the HSPF2 values of develop and this branch:

Develop: percent difference between HSPF and HSPF2 is about 19.0%.
Develop

Branch: percent difference between HSPF and HSPF2 is about 8.9%.
Branch

**Comment by Nigusse** [comment]
See below comparison of the HSPF2 calculation intermediate outputs for develop and this branch:

Develop:
Develop

Branch:
Branch

The delivered heating rate is 4979.8W, the same for development and this branch. However, the total electric power input (compressor electric power + electric resistance heater power) decreased to 2389.0W from 2690.4W, resulting in an increased HSPF2 value. Note that the electric resistance heater power input has decreased more than the compressor electric power input increase.

**Comment by Nigusse** [comment]
Attached is a test file used to generate sample results demonstrating the fix.
 
[Issue9909_in.idf.txt](https://github.com/user-attachments/files/16378355/Issue9909_in.idf.txt)

**Comment by Nigusse** [comment]
The regression test results show that 18 example files have diffs in the HSPF2 values. All these 18 example files have Multispeed DX Heating Coils. We found only six unique HSPF2 values since the inputs are similar in multiple example files. Below is a summary of the results based on the six files. The absolute diffs range 0.07 – 0.4 Btu/W-h, and the percent diffs range 1.0% - 8.1%. All the 18 example files with Multispeed DX heating coils in the branch showed increased HSPF2 values. However, they are less than the HSPF values. These results are consistent with the expectations.

image

**Comment by Nigusse** [comment]
This branch is ready for review.

File: src/EnergyPlus/StandardRatings.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/StandardRatings.cc:6313]: It makes sense, and I believe you, but it would be great to get a second opinion on it.  Anyone have thoughts on this?

File: src/EnergyPlus/StandardRatings.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/StandardRatings.cc:6499]: Thanks @Nigusse

**Review by Myoldmopar — APPROVED** [review]
This is fine to me, and I know you've done your due diligence in these changes.  I'd _like_ another review opinion on the changes to speed lookups and such, but if not, it's OK.

File: src/EnergyPlus/StandardRatings.cc (hunk 5 above)
Comment (jmarrec) [reply src/EnergyPlus/StandardRatings.cc:6320]: This fixes #10651


FWIW, and this looks like undefined behavior, but I was finding that in a release build with no floating point exceptions enabled, when you had the same Cap FT / Fflow curves, N_Hq was 0 but N_HE was 1.

**Comment by Myoldmopar** [comment]
@Nigusse I was going to merge this in, but during local testing I found 3 tests failing.  I spent about 30 minutes trying to diagnose the issue, looking at other changes made recently that might interact, but couldn't solve it quick enough.  While doing that I also found like 20+ variables in SizeDXCoil that were simply unused.  (Assigned but never accessed)  So I removed them just because.

If these 3 tests still fail, and you are able to look at them, that would be great.  If not, I'll have to do some further testing to figure out what I need to do to the unit tests to get them to work.  

Extra info:
 - This is the obvious culprit, but I couldn't tell quick enough what was needed on the HSPF tests.  
 - If I need to debug further, I'm likely going to roll back to the unmerged version of this branch to get it to pass, then more carefully bring in commits from develop to see exactly what is triggering the failures.

Anyway, I'm going to move on to other PRs for now.

**Comment by Nigusse** [comment]
@Myoldmopar I will look at it.

**Comment by Nigusse** [comment]
@Myoldmopar I will update the branch. If the failed unit tests are the new unit tests added, then I know what the problem is. I will look at it later today.

**Comment by Nigusse** [comment]
@Myoldmopar The failed unit test must have impacted by changes somewhere else. Now, the heating capacity is sized to zero. Maybe these unit tests need to be modified.

**Comment by Nigusse** [comment]
@Myoldmopar I modified the failed unit tests and all pass now. I ran the unit tests serially and all happy. This is good to go, albeit the format issue.

**Comment by Nigusse** [comment]
@Myoldmopar The failed unit tests and format warning message are addressed. This is ready for merging, I think.

File: src/EnergyPlus/StandardRatings.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/StandardRatings.cc:6313]: I don't know the standard but what will these values be used for? i.e., these would be used in some equation, so show the equation to support this change. For example, q_H1_full looks to be the capacity at speed 1 so why would we use speed 2 capacity?

File: src/EnergyPlus/StandardRatings.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/StandardRatings.cc:6410]: OK, so here I see the equations. I still don't know if Q_H1_Full should be the "full" capacity at the speed being evaluated or the full capacity at the next highest speed. What in the standard prompted this change?

**Comment by Myoldmopar** [comment]
@Nigusse I'm going to have to figure out the last item here.  One test file is appearing to fail or something on Mac only.  I can't reproduce on Linux.  I'll take a look.

**Comment by Myoldmopar** [comment]
I built on Mac and everything is still happy.  I'm hoping it's a fluke and I triggered a Mac rebuild.  Let's see.

File: src/EnergyPlus/StandardRatings.cc (hunk 3 above)
Comment (Nigusse) [reply src/EnergyPlus/StandardRatings.cc:6313]: These capacities (H1, 2, 3, 4) are used to estimate the full capacity at a specified outdoor a condition through interpolation. The full capacity is then used to bracket the `building load` to get a speed level of the machine that matches the `building load`.

File: src/EnergyPlus/StandardRatings.cc (hunk 8 above)
Comment (Nigusse) [reply src/EnergyPlus/StandardRatings.cc:6410]: My understanding is that the next higher speed level should be used to get the full speed capacity that bounds the current `building load`.

Comment (rraustad) [reply src/EnergyPlus/StandardRatings.cc:6410]: But if PLR at speed x is < 1 then the full capacity at that same speed would bound the current building load. So where in the standard does it say to use the next highest speed level?

**Comment by Nigusse** [comment]
@Myoldmopar The Mac machine regression run has three additional example files showing diffs. I am not expecting any diffs in the following IDFs because changes in this branch do not impact them.

```
PurchAirWindowBlind_BlockBeamSolar.idf
PurchAirWindowBlind2.idf
PurchAirWindowBlind3.idf
```

File: src/EnergyPlus/StandardRatings.cc (hunk 8 above)
Comment (Nigusse) [reply src/EnergyPlus/StandardRatings.cc:6410]: In the standard, different sections may apply to this code: one for a two-speed (two-capacity) machine and another one for a variable-speed machine. They are not an exact match for a discrete-speed machine with more than the two-speed. The HSPF2 calculation is based on the variable speed section of the standard, and it requires some interpretation to fit the discrete multispeed DX heating coil model we have in EnergyPlus. It requires some judgment on how to account for the difference between the EnergyPlus model and the variable speed machine procedure in the AHRI standard. Simply, it needs interpretation of the procedure for implementation in EnergyPlus. 

In a variable-speed machine, you have just one full speed, like the two-speed DX cooling coil model in EnergyPlus. In the multispeed DX heating coil, your full speed is a moving target, and depending on your load, it is the next available higher-speed capacity. Let's say a given load is bound between two-speed levels; the full load should point to the higher speed level, not the lower speed. This is my interpretation of how it should be. The current full capacity assignment was to the current speed, so I changed it to the next higher-speed capacity.

**Comment by Myoldmopar** [comment]
I think CI has magically calmed itself down, so I'm pulling develop in to get some fresh results here.

**Comment by Nigusse** [comment]
@Myoldmopar Resolved the conflict and the 18 example files diffs are expected per the original fix.

File: src/EnergyPlus/DXCoils.cc [hunk 11]
```diff
@@ -7549,22 +7487,19 @@ void SizeDXCoil(EnergyPlusData &state, int const DXCoilNum)
             PrintFlag = true;
             state.dataSize->DataTotCapCurveIndex = thisDXCoil.CCapFTemp(Mode);
             if (thisDXCoil.DXCoilType_Num == HVAC::CoilDX_CoolingTwoStageWHumControl) {
-                SizingMethod = HVAC::CoolingCapacitySizing;
```
Comment (mjwitte) [inline src/EnergyPlus/DXCoils.cc:7552]: @Nigusse @rraustad Are these changes to DXCoils.cc supposed to be in this PR?

Comment (rraustad) [reply src/EnergyPlus/DXCoils.cc:7552]: It looks like cleaning up unused information. I guess this can be done here as long as diffs show only for HSPF calculations.

Comment (Nigusse) [reply src/EnergyPlus/DXCoils.cc:7552]: No. I did not make this change.

Comment (Nigusse) [reply src/EnergyPlus/DXCoils.cc:7552]: > @Nigusse @rraustad Are these changes to DXCoils.cc supposed to be in this PR?

I think, @Myoldmopar might have made sizing related cleanup.

Comment (mjwitte) [reply src/EnergyPlus/DXCoils.cc:7552]: Ah, ok, I see that commit.

**Comment by Myoldmopar** [comment]
No conflicts here :tada: , but I'll still pull develop in locally to check nothing broke with the big refactor that just merged.

**Comment by Myoldmopar** [comment]
(
And if you ever see a failure like that

image

You should be able to just click the Details tab and choose to re run the Jobs on the right side:

image
)

Anyway, pulled and it's all happy, merging this in.  Thanks for your patience @Nigusse
