### PR TITLE
Correction of Water Thermal Tank Underflow Problem

### LINKED ISSUE #8844: Dividing by tiny values causing water thermal tank model failure and yielding negative energy usage results
Issue overview
--------------
It was reported in a case that EnergyPlus got negative water heating related energy usage for unknown reasons.  

The root cause is found to be in the water tank model, where a line of calculation code has a normal (double) float divided by a tiny double (float) which leads to a floating-point overflow:
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/WaterThermalTanks.cc#L7240

And before that, the tiny value of `b` (and also `a`) was obtained at the following code lines: 
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/WaterThermalTanks.cc#L7218-L7219

So in the reported case, the program actually continued running under this overflow condition and finished the simulation, but with obviously incorrect results.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v8.9-v9.6
 - Helpdesk ticket number: 15599

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #8844 
 - A user running the water thermal tank using a heat pump was running into a NaN crash during a run.  Debugging showed that a very low flow rate (e-300+) was resulting in the NaN problem that was causing the crash.  The fix here was to make sure that the flow rate coming out of a function that was setting the flow rate was limiting things so that if a very small flow rate was being returned that this was reset to zero to avoid these problems.  After the fix, the user's input file runs successfully to completion with no errors.  Pending ci results are showing no differences as anticipated.  A unit test shows that the fix is working and appropriate.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 1]
```diff
@@ -10755,6 +10755,9 @@ Real64 WaterThermalTankData::PlantMassFlowRatesFunc(EnergyPlusData &state,
         }
     }
 
+    Real64 const minFlow = 1.0e-20; // Catch underflow problems
+    if (FlowResult < minFlow) FlowResult = 0.0;
```
Comment (jcyuan2020) [inline src/EnergyPlus/WaterThermalTanks.cc]: This is a valid fix and would fix the problem and prevent the flow to take very small values.

Comment (jcyuan2020) [reply src/EnergyPlus/WaterThermalTanks.cc]: (This is beyond this one fix). I think there could be some global small-value defined so that it could also be used in some other places. 

I did a quick search in the code. There are a few places where a SMALL value of 1e-10 defined in some local functions such as in General.hh; but in most locations it is made only local to a function such as safe divisions: 
https://github.com/NREL/EnergyPlus/blob/cbd1174e5e3266057c2e5656fb1a06f9787f6ed2/src/EnergyPlus/General.cc#L909

Maybe making a few of such SMALL values global (with different names and values for different types of physics) might be helpful in the future? @RKStrand @mjwitte @Myoldmopar

Comment (rraustad) [reply src/EnergyPlus/WaterThermalTanks.cc]: In DataHVACGlobals:

    Real64 constexpr SmallMassFlow(0.001);
    Real64 constexpr VerySmallMassFlow(1.0E-30);
    Real64 constexpr SmallWaterVolFlow(1.0E-9);

Comment (RKStrand) [reply src/EnergyPlus/WaterThermalTanks.cc]: Thanks @rraustad!  I'll change this to the VerySmallMassFlow and recommit.

Comment (jcyuan2020) [reply src/EnergyPlus/WaterThermalTanks.cc]: Thanks @rraustad and @RKStrand !

A side issue that I noticed when running a defect file is about the AIRLOOPHVAC:OUTDOORAIRSYSTEM transition program is that it cuts off the third line for a 3-line version--which calls a little bit treatment on the 3-line case. See #8995.

Comment (RKStrand) [reply src/EnergyPlus/WaterThermalTanks.cc]: @jcyuan2020 I have made a commit on this that changes to the existing VerySmallMassFlow constant.  So, this should be good to go.

Thanks for the heads-up on #8995.  I'm going to start working on that as soon as possible so that it can be done today.

**Comment by jcyuan2020** [comment]
Thanks @RKStrand ! I also finished running the defect file. It now finishes the simulation without problems---in the develop branch it will crash on div-by-zero when running the debug version. So the current fix is successful. I think it should be good to go in. 

One thing I noticed that the negative water electric reporting (in html) in the defect file still does not go way---it yields the same reporting result as before (by looking at the original helpdesk 15999 issue complaint). But I think this probably should be left to a new investigation regarding reporting on water electricity energy. I originally replied the user to advise that that they might have specified too low a flow rate to the domestic water heater, which could be one of the reasons for the observed abnormalities. The water tank div-by-zero issue is the first problem I encountered that prevented the code to be executed further---and essential that's what been reported in the original issue. 

I think the current fix paved the way for further investigations of the issues reported in the original helpdesk ticket. I will probably transfer the original GitHub issue post to an updated one with the currently known progress---and someone may also take a look at the electricity reporting problem later.

**Comment by RKStrand** [comment]
Thanks, @jcyuan2020.  Strange that it still has negative water electric, but I think that is a separate issue.  Yes, please add another issue.  I still have some defects to work on before the code freeze, so I might take that on since that work is still somewhat fresh in my mind.  Just wish the user input file didn't take 2 hours to run on my machine!

**Comment by RKStrand** [comment]
@jcyuan2020 Oh...I missed this before.  It seems like there is a unit test issue.  I'll look into that and make another commit as soon as I can.

**Comment by RKStrand** [comment]
@jcyuan2020 Ok, that was a simple problem that was related to using the existing constant to check for minimum flow.  A new commit was made.  Should be good now.

**Review by jcyuan2020 — APPROVED** [review]
This is great! I will issue an update on the original reported issue for the next steps.

**Comment by mjwitte** [comment]
Haven't seen a no-diff ci result on this branch. Merged in latest develop.

**Comment by mjwitte** [comment]
Ok, Mac CI came back with no diffs, but develop has moved again now. Merging.
