### PR TITLE
Fix #9835 - The "value" datatype is incorrect in TabularData

### LINKED ISSUE #9835: The "value" datatype is incorrect  in TabularData table of eplusout.sql
Issue overvie
--------------

The dataype of column "value" is "TEXT VALUE TEXT" in TabularData table of eplusout.sql
 
image

### Details

This bus was introduced into EnergyPlus by commit [aa1aeb6](https://github.com/NREL/EnergyPlus/commit/aa1aeb69e4b667a51809eca210f0b78ad26b52c3)

image

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by piaoger**
Pull request overview
---------------------
 -  Fix #9835 
 - The dataype of column "value" is "TEXT VALUE TEXT" in TabularData table of eplusout.sql. It should be "TEXT" instead.
 - This bus was introduced into EnergyPlus by commit [aa1aeb6](https://github.com/NREL/EnergyPlus/commit/aa1aeb69e4b667a51809eca210f0b78ad26b52c3)

 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I'm going to mark this for 23.1 IO freeze, but that could be too quick, next week.  @piaoger could you email me at:  

edwin dot lee at nrel dot gov

So that we can discuss your contribution here?  Thanks!

**Comment by piaoger** [comment]
> I'm going to mark this for 23.1 IO freeze, but that could be too quick, next week. @piaoger could you email me at:
> 
> edwin dot lee at nrel dot gov
> 
> So that we can discuss your contribution here? Thanks!

Just sent the mail a few minutes ago.

**Comment by Myoldmopar** [comment]
Contribution policy in place, thanks.  CI is all happy here, just spurious GPU file diffs.  The GitHub Action failure is not anything to worry about here, not sure why the action couldn't identify the PR number.  Reviewing the changes now and building/testing locally.

File: src/EnergyPlus/SQLiteProcedures.cc [hunk 1]
```diff
@@ -1221,7 +1221,6 @@ void SQLite::initializeTabularDataTable()
                              "SimulationIndex INTEGER, "
                              "RowId INTEGER, "
                              "ColumnId INTEGER, "
-                             "Value TEXT "
```
Comment (Myoldmopar) [inline src/EnergyPlus/SQLiteProcedures.cc:1224]: So this line was added as part of a large performance refactor from @mbadams5 (#4610).  This line does look wrong, though I'll say from inspection it looks more like it should just have a comma added rather than the line being removed entirely.  I'm not saying this patch is wrong, just saying I may have guessed wrong.  I'll need to pull the database and look at it to verify.  

@mbadams5 or @jmarrec if either of you have a minute to also peek at this, it would be appreciated.

**Comment by Myoldmopar** [comment]
Dug down into the SQL outputs from develop and this branch.  I can confirm that the tables look identical, it's just the column type specifier that is wrong in develop and now correct in this branch.  This is good to go in.  Thanks @piaoger !
