### PR TITLE
Address set sky and ground surfaces view factors for surfaces property object

### LINKED ISSUE #9437: Incorrect use of sky view factor variable to set ground view factor for surrounding surfaces property object
Issue overview
--------------
The sky view factor of Surrounding Surfaces Property object variable is incorrectly used to set surrounding surfaces property ground view factor in three window models [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WindowManager.cc#L2638-L2640), [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WindowEquivalentLayer.cc#L755-L758) and [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WindowComplexManager.cc#L2783-L2786). Note that these codes are executed every time step if there is Surrounding Surfaces Property object but exterior surfaces view factor to the ground and sky are constant values.

### Details
Some additional details for this issue (if relevant):
 - Platform (Any)
 - Version of EnergyPlus (Develop)

### Quick Test
- Created defect file but did not produce any diffs even though the code is incorrect. Maybe the ground view factor is already set else where. Further testing shows that they are actually initialized [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L310-L349).
- Commenting out the redundant codes resulted unit test `WindowManager_SrdLWRTest` to fail. Suspect this is because the [code section](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L310-L349) never  executed for this unit test and as the result the view factors are not set.
- At least these codes need to move else where to avoid repeated execution.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #9437 
 - Removed redundant codes from three separate sections
 - Refactored the code that sets the sky and ground surfaces to exterior surfaces

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 1]
```diff
@@ -294,56 +294,18 @@ void InitSurfaceHeatBalance(EnergyPlusData &state)
...
-                } else if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor < 0 &&
-                           state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor >= 0) {
-                    // If only ground view factor defined, sky view factor = 1 - all other defined view factors.
-                    Surface(SurfNum).ViewFactorGroundIR = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
-                    Surface(SurfNum).ViewFactorSkyIR = 1 - SrdSurfsViewFactor;
-                } else {
-                    // If neither ground or sky view factor define, continue to use the original proportion.
-                    Surface(SurfNum).ViewFactorSkyIR *= 1 - SrdSurfsViewFactor;
-                    Surface(SurfNum).ViewFactorGroundIR *= 1 - SrdSurfsViewFactor;
-                }
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:346]: Refactored by creating a new function `InitSurfacePropertyViewFactors(state)` used above. Also the new function is used to address failed unit test due to deleted redundant code as part of this fix.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 2]
```diff
@@ -294,56 +294,18 @@ void InitSurfaceHeatBalance(EnergyPlusData &state)
 
     SetSurfaceWindSpeedAt(state);
     SetSurfaceWindDirAt(state);
+    InitSurfacePropertyViewFactors(state);
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: New function `InitSurfacePropertyViewFactors(state)` replaced the deleted code below.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 3]
```diff
@@ -294,56 +294,18 @@ void InitSurfaceHeatBalance(EnergyPlusData &state)
...
-                    // If neither ground or sky view factor define, continue to use the original proportion.
-                    Surface(SurfNum).ViewFactorSkyIR *= 1 - SrdSurfsViewFactor;
-                    Surface(SurfNum).ViewFactorGroundIR *= 1 - SrdSurfsViewFactor;
-                }
+                auto &linkedNode = state.dataLoopNodes->Node(state.dataSurface->SurfLinkedOutAirNode(SurfNum));
+                state.dataSurface->SurfOutDryBulbTemp(SurfNum) = linkedNode.OutAirDryBulb;
+                state.dataSurface->SurfOutWetBulbTemp(SurfNum) = linkedNode.OutAirWetBulb;
+                state.dataSurface->SurfOutWindSpeed(SurfNum) = linkedNode.OutAirWindSpeed;
+                state.dataSurface->SurfOutWindDir(SurfNum) = linkedNode.OutAirWindDir;
             }
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:308]: Compact and readable.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 4]
```diff
@@ -8874,4 +8836,56 @@ void GatherComponentLoadsSurfAbsFact(EnergyPlusData &state)
...
+                } else {
+                    // If neither ground or sky view factor define, continue to use the original proportion.
+                    Surface.ViewFactorSkyIR *= 1 - SrdSurfsViewFactor;
+                    Surface.ViewFactorGroundIR *= 1 - SrdSurfsViewFactor;
+                }
+            }
+        }
+    }
+}
+
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:8896]: New function that replaced a deleted code (refactored).

File: src/EnergyPlus/WindowComplexManager.cc [hunk 5]
```diff
@@ -2776,21 +2776,11 @@ namespace WindowComplexManager {
...
-                            state.dataSurface->Surface(SurfNum).ViewFactorGroundIR =
-                                state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
-                        }
-                        for (SrdSurfNum = 1; SrdSurfNum <= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).TotSurroundingSurface;
-                             SrdSurfNum++) {
-                            SrdSurfViewFac = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SurroundingSurfs(SrdSurfNum).ViewFactor;
-                            SrdSurfTempAbs =
-                                GetCurrentScheduleValue(
-                                    state, state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SurroundingSurfs(SrdSurfNum).TempSchNum) +
-                                DataGlobalConstants::KelvinConv;
```
Comment (Nigusse) [inline src/EnergyPlus/WindowComplexManager.cc:2793]: This deleted code section is redundant because the view factors are already set at this stage. The view factors are constant; no need to reset them every time a window surface is simulated.

File: src/EnergyPlus/WindowComplexManager.cc [hunk 6]
```diff
@@ -2776,21 +2776,11 @@ namespace WindowComplexManager {
...
+                        auto &SrdSurfsProperty = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum);
+                        for (SrdSurfNum = 1; SrdSurfNum <= SrdSurfsProperty.TotSurroundingSurface; SrdSurfNum++) {
+                            SrdSurfViewFac = SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).ViewFactor;
+                            SrdSurfTempAbs = GetCurrentScheduleValue(state, SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).TempSchNum) +
+                                             DataGlobalConstants::KelvinConv;
                             OutSrdIR += DataGlobalConstants::StefanBoltzmann * SrdSurfViewFac * (pow_4(SrdSurfTempAbs));
```
Comment (Nigusse) [inline src/EnergyPlus/WindowComplexManager.cc:2784]: No functional change; modified for readability.

File: src/EnergyPlus/WindowEquivalentLayer.cc [hunk 7]
```diff
@@ -749,19 +749,11 @@ void EQLWindowSurfaceHeatBalance(EnergyPlusData &state,
             if (state.dataGlobal->AnyLocalEnvironmentsInModel) {
                 if (state.dataSurface->SurfHasSurroundingSurfProperties(SurfNum)) {
                     SrdSurfsNum = state.dataSurface->SurfSurroundingSurfacesNum(SurfNum);
-                    if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                        state.dataSurface->Surface(SurfNum).ViewFactorSkyIR = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
-                    }
-                    if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                        state.dataSurface->Surface(SurfNum).ViewFactorGroundIR =
-                            state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
-                    }
```
Comment (Nigusse) [inline src/EnergyPlus/WindowEquivalentLayer.cc:758]: Same here, deleted redundant code.

File: src/EnergyPlus/WindowEquivalentLayer.cc [hunk 8]
```diff
@@ -749,19 +749,11 @@ void EQLWindowSurfaceHeatBalance(EnergyPlusData &state,
...
-                        SrdSurfViewFac = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SurroundingSurfs(SrdSurfNum).ViewFactor;
-                        SrdSurfTempAbs =
-                            GetCurrentScheduleValue(
-                                state, state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SurroundingSurfs(SrdSurfNum).TempSchNum) +
-                            DataGlobalConstants::KelvinConv;
+                    auto &SrdSurfsProperty = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum);
+                    for (SrdSurfNum = 1; SrdSurfNum <= SrdSurfsProperty.TotSurroundingSurface; SrdSurfNum++) {
+                        SrdSurfViewFac = SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).ViewFactor;
+                        SrdSurfTempAbs = GetCurrentScheduleValue(state, SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).TempSchNum) +
+                                         DataGlobalConstants::KelvinConv;
```
Comment (Nigusse) [inline src/EnergyPlus/WindowEquivalentLayer.cc:756]: No functional change; modified for readability.

File: src/EnergyPlus/WindowManager.cc [hunk 9]
```diff
@@ -2631,20 +2631,11 @@ namespace WindowManager {
...
-                            SrdSurfTempAbs =
-                                GetCurrentScheduleValue(
-                                    state, state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SurroundingSurfs(SrdSurfNum).TempSchNum) +
-                                DataGlobalConstants::KelvinConv;
+                        auto &SrdSurfsProperty = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum);
+                        for (SrdSurfNum = 1; SrdSurfNum <= SrdSurfsProperty.TotSurroundingSurface; SrdSurfNum++) {
+                            SrdSurfViewFac = SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).ViewFactor;
+                            SrdSurfTempAbs = GetCurrentScheduleValue(state, SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).TempSchNum) +
+                                             DataGlobalConstants::KelvinConv;
                             OutSrdIR += state.dataWindowManager->sigma * SrdSurfViewFac * pow_4(SrdSurfTempAbs);
```
Comment (Nigusse) [inline src/EnergyPlus/WindowManager.cc:2639]: No functional change; modified for readability.

File: src/EnergyPlus/WindowManager.cc [hunk 10]
```diff
@@ -2631,20 +2631,11 @@ namespace WindowManager {
                 if (state.dataGlobal->AnyLocalEnvironmentsInModel) {
                     if (state.dataSurface->SurfHasSurroundingSurfProperties(SurfNum)) {
                         SrdSurfsNum = state.dataSurface->SurfSurroundingSurfacesNum(SurfNum);
-
-                        if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                            surface.ViewFactorSkyIR = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
-                        }
-                        if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                            surface.ViewFactorGroundIR = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
-                        }
```
Comment (Nigusse) [inline src/EnergyPlus/WindowManager.cc:2640]: Same here, deleted redundant code.

File: tst/EnergyPlus/unit/WindowManager.unit.cc [hunk 11]
```diff
@@ -2836,6 +2836,8 @@ TEST_F(EnergyPlusFixture, WindowManager_SrdLWRTest)
     state->dataScheduleMgr->Schedule(1).CurrentValue = 25.0; // Srd Srfs Temp
     // Calculate temperature based on supply flow rate
 
+    HeatBalanceSurfaceManager::InitSurfacePropertyViewFactors(*state);
+
     WindowManager::CalcWindowHeatBalance(*state, surfNum2, state->dataHeatBalSurf->SurfHConvInt(surfNum2), inSurfTemp, outSurfTemp);
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/WindowManager.unit.cc:2841]: Need to reset the sky and ground surface view factors for exterior surface. This unit test failed due to deletion of the redundant code.

File: src/EnergyPlus/WindowComplexManager.cc [hunk 12]
```diff
@@ -2776,21 +2776,11 @@ namespace WindowComplexManager {
...
                     if (state.dataSurface->SurfHasSurroundingSurfProperties(SurfNum)) {
                         SrdSurfsNum = state.dataSurface->SurfSurroundingSurfacesNum(SurfNum);
-                        if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                            state.dataSurface->Surface(SurfNum).ViewFactorSkyIR =
-                                state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
-                        }
-                        if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                            state.dataSurface->Surface(SurfNum).ViewFactorGroundIR =
-                                state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
-                        }
```
Comment (Nigusse) [inline src/EnergyPlus/WindowComplexManager.cc:2786]: This deleted code section is redundant because the view factors are already set at this stage. The view factors are constant; no need to reset them every time a window surface is simulated.

**Comment by Nigusse** [comment]
@Myoldmopar This branch is ready for review.

**Comment by Nigusse** [comment]
@amirroth This is the PR that addressed #9441.

File: src/EnergyPlus/DataSurfaces.hh [hunk 13]
```diff
@@ -1323,7 +1323,7 @@ namespace DataSurfaces {
         Array1D<SurroundingSurfProperty> SurroundingSurfs;
 
         // Default Constructor
-        SurroundingSurfacesProperty() : SkyViewFactor(-1.0), SkyTempSchNum(0), GroundViewFactor(-1.0), GroundTempSchNum(0), TotSurroundingSurface(0)
+        SurroundingSurfacesProperty() : SkyViewFactor(0.0), SkyTempSchNum(0), GroundViewFactor(0.0), GroundTempSchNum(0), TotSurroundingSurface(0)
```
Comment (Nigusse) [inline src/EnergyPlus/DataSurfaces.hh]: Changed view factor initialization to 0.0, instead of -1.0. This change also requires some logic change elsewhere.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 14]
```diff
@@ -8874,4 +8836,60 @@ void GatherComponentLoadsSurfAbsFact(EnergyPlusData &state)
...
+    //   Initializes sky and ground surfaces view factors of exterior surfaces
+    //   used by SurfaceProperty:LocalEnvironment
+    //   view factors are constant hence should be set only once
+
+    if (!state.dataGlobal->AnyLocalEnvironmentsInModel) {
+        return;
+    }
+    if (!state.dataHeatBalSurfMgr->InitSurfaceHeatBalancefirstTime) {
+        return;
+    }
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:8851]: Modified per @amirroth review comment.

File: src/EnergyPlus/SolarShading.cc [hunk 15]
```diff
@@ -10441,10 +10441,10 @@ void SkyDifSolarShading(EnergyPlusData &state)
 
         if (state.dataSurface->SurfHasSurroundingSurfProperties(SurfNum)) {
             SrdSurfsNum = state.dataSurface->SurfSurroundingSurfacesNum(SurfNum);
-            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
+            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != 0) {
                 state.dataSurface->Surface(SurfNum).ViewFactorSkyIR *= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
             }
-            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor != -1) {
+            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor != 0) {
```
Comment (Nigusse) [inline src/EnergyPlus/SolarShading.cc]: Sky and ground view factors are no more initialized to -1.0, so needed these logic changes as well.

Comment (amirroth) [reply src/EnergyPlus/SolarShading.cc]: I think you misunderstood my comment. Do the addition without the if. It’s faster to add 0 than it is to test if something is not 0 and only add in that case.

Comment (Nigusse) [reply src/EnergyPlus/SolarShading.cc]: I did I understand your comment but there is a reason that this check is needed because it is overriding an existing value. I am actually looking a way to delete this view factor reset.

Comment (Nigusse) [reply src/EnergyPlus/SolarShading.cc]: The view factors update in `SolarShading.cc` module above are hit prior to `state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor` and `state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor` variables are reset due to the current calling order. Thus, the calling point of the new function `InitSurfacePropertyViewFactors()` should move up before calling `SkyDifSolarShading()`, preferably in `InitHeatBalance()`. Quick test shows diffs will be introduced but it is justifiable, I think. I will get rid of the view factor update from `SolarShading.cc`  and see its impact.

File: src/EnergyPlus/SolarShading.cc [hunk 16]
```diff
@@ -10438,16 +10438,6 @@ void SkyDifSolarShading(EnergyPlusData &state)
             state.dataSurface->Surface(SurfNum).ViewFactorSkyIR *= state.dataSolarShading->SurfDifShdgRatioIsoSkyHRTS(1, 1, SurfNum);
         }
         state.dataSurface->Surface(SurfNum).ViewFactorGroundIR = 1.0 - state.dataSurface->Surface(SurfNum).ViewFactorSkyIR;
```
Comment (Nigusse) [inline src/EnergyPlus/SolarShading.cc:10439]: At this point the `state.dataSurface->Surface(SurfNum).ViewFactorSkyIR` is already set due to the change in calling order of surface view factors reset function `InitSurfacePropertyViewFactors(state)` and it is done only once. There is no need to check and update again.

Comment (Nigusse) [reply src/EnergyPlus/SolarShading.cc:10439]: The code below is not needed now because the code above already operated on the updated `Surface(SurfNum).ViewFactorSkyIR`.

File: tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc [hunk 17]
```diff
@@ -2483,6 +2483,8 @@ TEST_F(EnergyPlusFixture, HeatBalanceSurfaceManager_TestSurfPropertySrdSurfLWR)
     state->dataSurface->SurfTAirRef(2) = DataSurfaces::RefAirTemp::AdjacentAirTemp;
     state->dataSurface->SurfTAirRef(3) = DataSurfaces::RefAirTemp::ZoneSupplyAirTemp;
 
+    InitSurfacePropertyViewFactors(*state);
+
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc:2487]: Added view factor init function to fix an existing failed unit test.

File: tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc [hunk 18]
```diff
@@ -4769,4 +4771,514 @@ TEST_F(EnergyPlusFixture, HeatBalanceSurfaceManager_TestTDDSurfWinHeatGain)
...
+    EXPECT_DOUBLE_EQ(0.3, SrdSurfsProperty_3.SkyViewFactor);
+    EXPECT_DOUBLE_EQ(0.3, SrdSurfsProperty_3.GroundViewFactor);
+    // test exterior surfaces sky and ground view factors reset
+    EXPECT_DOUBLE_EQ(0.3, Surface_1.ViewFactorSkyIR);
+    EXPECT_DOUBLE_EQ(0.1, Surface_1.ViewFactorGroundIR);
+    EXPECT_DOUBLE_EQ(0.2, Surface_2.ViewFactorSkyIR);
+    EXPECT_DOUBLE_EQ(0.2, Surface_2.ViewFactorGroundIR);
+    EXPECT_DOUBLE_EQ(0.3, Surface_3.ViewFactorSkyIR);
+    EXPECT_DOUBLE_EQ(0.3, Surface_3.ViewFactorGroundIR);
+}
```
Comment (Nigusse) [inline tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc:5293]: This unit test demonstrates the new function `InitSurfacePropertyViewFactors(*state)`.

File: src/EnergyPlus/WindowComplexManager.cc (hunk 12 above)
Comment (Myoldmopar) [reply src/EnergyPlus/WindowComplexManager.cc:2786]: :+1:

**Review by Myoldmopar — APPROVED** [review]
This is a nice set of cleanups.  Centralizing the logic to a new function and handling the view factors properly has led to a lot of deleted redundant code.  Great stuff.  If there is a defect file I'll need to run it to wrap up the review, but this is a great set of code changes.

**Comment by Myoldmopar** [comment]
CI is showing there is a build warning: `unused variable ‘SrdSurfsNum’ [-Wunused-variable]`

CI is also showing diffs in the EIO file for a couple surfaces where it appears the view factor has changed from zero to one.  I suppose this is the intention of this fix.

I see there's not really a defect file, so I'll instead just take a deeper look at the CI change and go from there.

**Comment by Nigusse** [comment]
@Myoldmopar I am still looking at the code change in the solar shading module. I may have to revert the change for this section based on a new unit test.

**Comment by Nigusse** [comment]
The example file `SurfacePropTest_SurfLWR.idf` captures most of the changes made.

File: src/EnergyPlus/SolarShading.cc [hunk 19]
```diff
@@ -10440,13 +10439,14 @@ void SkyDifSolarShading(EnergyPlusData &state)
...
 
         if (state.dataSurface->SurfHasSurroundingSurfProperties(SurfNum)) {
+            int SrdSurfsNum;
+            Real64 SrdSurfsViewFactor = 0.0;
             SrdSurfsNum = state.dataSurface->SurfSurroundingSurfacesNum(SurfNum);
-            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
-                state.dataSurface->Surface(SurfNum).ViewFactorSkyIR *= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
-            }
-            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor != -1) {
-                state.dataSurface->Surface(SurfNum).ViewFactorGroundIR *= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
```
Comment (Nigusse) [inline src/EnergyPlus/SolarShading.cc:10448]: The deleted section does not guaranty view factors identity because it proportionally adjusts the sky and ground surfaces view factors only.

File: src/EnergyPlus/SolarShading.cc [hunk 20]
```diff
@@ -10440,13 +10439,14 @@ void SkyDifSolarShading(EnergyPlusData &state)
...
+            auto &SrdSurfsProperty = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum);
+            for (int SrdSurfNum = 1; SrdSurfNum <= SrdSurfsProperty.TotSurroundingSurface; SrdSurfNum++) {
+                SrdSurfsViewFactor += SrdSurfsProperty.SurroundingSurfs(SrdSurfNum).ViewFactor;
             }
+            state.dataSurface->Surface(SurfNum).ViewFactorGroundIR = 1.0 - state.dataSurface->Surface(SurfNum).ViewFactorSkyIR - SrdSurfsViewFactor;
         }
```
Comment (Nigusse) [inline src/EnergyPlus/SolarShading.cc:10450]: This new code instead, if there is surrounding surfaces view factors defined, takes the updated sky view factor and backs out the ground surface view factor accounting for the surrounding surfaces view factor.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 21]
```diff
@@ -8874,4 +8835,59 @@ void GatherComponentLoadsSurfAbsFact(EnergyPlusData &state)
...
+        // Check if the sum of all defined view factors > 1.0
+        if (SrdSurfsViewFactor > 1.0) {
+            ShowSevereError(state, "Illegal surrounding surfaces view factors for " + Surface.Name + ".");
+            ShowContinueError(state, " The sum of sky, ground, and all surrounding surfaces view factors should be less than or equal to 1.0.");
+        }
+        if (SrdSurfsProperty.SkyViewFactor > 0.0 && SrdSurfsProperty.GroundViewFactor > 0.0) {
+            // If both surface sky and ground view factor defined, overwrite with the defined value
+            Surface.ViewFactorSkyIR = SrdSurfsProperty.SkyViewFactor;
+            Surface.ViewFactorGroundIR = SrdSurfsProperty.GroundViewFactor;
+        } else if (SrdSurfsProperty.SkyViewFactor > 0.0 && SrdSurfsProperty.GroundViewFactor == 0.0) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @Nigusse Zero is not the same as blank in the current code:
`GroundViewFactor` and `SkyViewFactor` were initialized to -1, then in [`GetSurfaceSrdSurfsData`](https://github.com/NREL/EnergyPlus/blob/43b09606e2a93a0a1b220949d5b6832d63c0a03a/src/EnergyPlus/SurfaceGeometry.cc#L8179-L8192) if the input field is blank, the value remains at -1 and that property is left at the normal value. But if the user input a zero value, then the value would be set to zero.

This isn't a great design, especially since the IDD defaults are 0.5. So I'm not sure what the best solution is here, but the changes here alter the behavior.

Comment (Nigusse) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: @mjwitte The initialization to -1 were used to preserve the default values (not to alter the values) until the [`GetSurfaceSrdSurfsData`](https://github.com/NREL/EnergyPlus/blob/43b09606e2a93a0a1b220949d5b6832d63c0a03a/src/EnergyPlus/SurfaceGeometry.cc#L8179-L8192) resets them. The proposed change in [here](https://github.com/NREL/EnergyPlus/blob/182223803_Issue9437/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L8838-L8891) did not alter the logic how they are reset and still captures the logic when the fields are blank, I think. Deleting the view factors check and resets codes in the three windows modules were necessary since the view factor reset refactor can be called early and also used to for unit tests otherwise, would fail due to the proposed changes.  But the changes in [SkyDifSolarShading](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L10442-L10450) is the one that is changing the behavior for two reasons.

Comment (mjwitte) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: How does the revised code distinguish between blank and an input value of 0.0?

Comment (Nigusse) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Below are the two reasons:
- First, in the existing code (`Develop`) the simulation hits `SkyDifSolarShading` function prior to the view factors reset calculation is done. Therefore, the check was necessary in the existing code (`Develop`) since the view factors values could be -1. 
- Second, I think the reset equation is incorrect, we can debate on the logic here.

The proposed code ( `the branch`) alters two things: (1) moves the view factors reset calculation earlier than the `SkyDifSolarShading` call such that it avoids the need to check for view factor is -1. (2) altered how the view factor were reset such that the view factor identity is maintained. In the existing code (`Develop`) , the reset equation does not guarantee the view factor identity. Note that the `Surface.SkyViewFactor` and `Surface.ViewFactorGroundIRr` are already reset at this stage and scaling them would violate the view factor identity, I think. See below:

```
        if (state.dataSurface->SurfHasSurroundingSurfProperties(SurfNum)) {
            SrdSurfsNum = state.dataSurface->SurfSurroundingSurfacesNum(SurfNum);
            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor != -1) {
                state.dataSurface->Surface(SurfNum).ViewFactorSkyIR *= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
            }
            if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor != -1) {
                state.dataSurface->Surface(SurfNum).ViewFactorGroundIR *= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
            }
        }
```

Comment (Nigusse) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc]: So, the only changes that altered the behavior are those changes in SkyDifSolarShading() function.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 22]
```diff
@@ -300,50 +300,11 @@ void InitSurfaceHeatBalance(EnergyPlusData &state)
...
-                for (int SrdSurfNum = 1; SrdSurfNum <= state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).TotSurroundingSurface; SrdSurfNum++) {
-                    SrdSurfsViewFactor += state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SurroundingSurfs(SrdSurfNum).ViewFactor;
-                }
-                // Check if the sum of all defined view factors > 1.0
-                if (SrdSurfsViewFactor > 1.0) {
-                    ShowSevereError(state, "Illegal surrounding surfaces view factors for " + Surface(SurfNum).Name + ".");
-                    ShowContinueError(state, " The sum of sky, ground, and all surrounding surfaces view factors should be less than 1.0.");
-                }
-                if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor >= 0 &&
-                    state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor >= 0) {
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:328]: Previously, blank values hold -1 at this point, so an input value of 0 for `SkyViewFactor` and/or `GroundViewFactor` will make one of these `if/else if` be true, and it would not execute the `else` at the end.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 23]
```diff
@@ -300,50 +300,11 @@ void InitSurfaceHeatBalance(EnergyPlusData &state)
...
-                } else if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor >= 0 &&
-                           state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor < 0) {
-                    // If only sky view factor defined, ground view factor = 1 - all other defined view factors.
-                    Surface(SurfNum).ViewFactorSkyIR = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor;
-                    Surface(SurfNum).ViewFactorGroundIR = 1 - SrdSurfsViewFactor;
-                } else if (state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).SkyViewFactor < 0 &&
-                           state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor >= 0) {
-                    // If only ground view factor defined, sky view factor = 1 - all other defined view factors.
-                    Surface(SurfNum).ViewFactorGroundIR = state.dataSurface->SurroundingSurfsProperty(SrdSurfsNum).GroundViewFactor;
-                    Surface(SurfNum).ViewFactorSkyIR = 1 - SrdSurfsViewFactor;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:341]: For example if `SkyViewFactor` was blank and `GroundViewFactor` was 0.0, the old logic would execute this block and the end result would be `ViewFactorGroundIR = 0.0` and `ViewFactorSkyIR = 1.01 - SrdSurfsViewFactor`.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 24]
```diff
@@ -8874,4 +8835,59 @@ void GatherComponentLoadsSurfAbsFact(EnergyPlusData &state)
...
+            Surface.ViewFactorSkyIR = SrdSurfsProperty.SkyViewFactor;
+            Surface.ViewFactorGroundIR = 1 - SrdSurfsViewFactor;
+            SrdSurfsProperty.GroundViewFactor = Surface.ViewFactorGroundIR;
+        } else if (SrdSurfsProperty.SkyViewFactor == 0.0 && SrdSurfsProperty.GroundViewFactor > 0.0) {
+            // If only ground view factor defined, sky view factor = 1 - all other defined view factors.
+            Surface.ViewFactorGroundIR = SrdSurfsProperty.GroundViewFactor;
+            Surface.ViewFactorSkyIR = 1 - SrdSurfsViewFactor;
+            SrdSurfsProperty.SkyViewFactor = Surface.ViewFactorSkyIR;
+        } else {
+            // If neither ground nor sky view factor specified, continue to use the original proportion.
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:8886]: With the new code, if I am following correctly, the same inputs (`SkyViewFactor` is blank and `GroundViewFactor` is 0.0) will fall to this `else` block and the end result would be `ViewFactorGroundIR` and `ViewFactorSkyIR` proportioned.

Comment (Nigusse) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc:8886]: @mjwitte I agree, the proposed logic doesn't hold always. There are two options to fix the logic: (1) add two flag variables that can be set to true if these view factor fields are blank, or (2) revert, the view factors initialization to -1. In both approaches we can keep the other code changes as is.

Comment (Nigusse) [reply src/EnergyPlus/HeatBalanceSurfaceManager.cc:8886]: @mjwitte Addressed using option 1 above.

File: src/EnergyPlus/DataSurfaces.hh [hunk 25]
```diff
@@ -1318,12 +1318,16 @@ namespace DataSurfaces {
         Real64 SkyViewFactor;
         int SkyTempSchNum; // schedule pointer
         Real64 GroundViewFactor;
-        int GroundTempSchNum;      // schedule pointer
-        int TotSurroundingSurface; // Total number of surrounding surfaces defined for an exterior surface
+        int GroundTempSchNum;         // schedule pointer
+        int TotSurroundingSurface;    // Total number of surrounding surfaces defined for an exterior surface
+        bool IsSkyViewFactorSet;      // false if the sky view factor field is blank
+        bool IsGroundViewFactorSet; // false if the ground view factor field is blank
```
Comment (Nigusse) [inline src/EnergyPlus/DataSurfaces.hh:1324]: Added `IsSkyViewFactorSet` and `IsGroundViewFactorSet` member variables for checking blank view factor fields. These variables will be reset to true once the actual view factor values are determined in `InitSurfacePropertyViewFactors()` function. The unit tests were also modified to check for these flag variables.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 26]
```diff
@@ -8874,4 +8835,63 @@ void GatherComponentLoadsSurfAbsFact(EnergyPlusData &state)
...
+            SrdSurfsProperty.SkyViewFactor = Surface.ViewFactorSkyIR;
+            SrdSurfsProperty.IsSkyViewFactorSet = true;
+        } else {
+            // If neither ground nor sky view factor specified, continue to use the original proportion.
+            Surface.ViewFactorSkyIR *= 1 - SrdSurfsViewFactor;
+            Surface.ViewFactorGroundIR *= 1 - SrdSurfsViewFactor;
+            SrdSurfsProperty.SkyViewFactor = Surface.ViewFactorSkyIR;
+            SrdSurfsProperty.GroundViewFactor = Surface.ViewFactorGroundIR;
+            SrdSurfsProperty.IsSkyViewFactorSet = true;
+            SrdSurfsProperty.IsGroundViewFactorSet = true;
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc:8892]: The `IsSkyViewFactorSet` and `IsGroundViewFactorSet` variables are reset to true once the actual view factor values are updated as shown above.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 27]
```diff
@@ -8179,6 +8179,7 @@ namespace SurfaceGeometry {
                 // N1: sky view factor
                 if (!state.dataIPShortCut->lNumericFieldBlanks(1)) {
                     state.dataSurface->SurroundingSurfsProperty(Loop).SkyViewFactor = state.dataIPShortCut->rNumericArgs(1);
+                    state.dataSurface->SurroundingSurfsProperty(Loop).IsSkyViewFactorSet = true;
```
Comment (Nigusse) [inline src/EnergyPlus/SurfaceGeometry.cc:8182]: The `IsSkyViewFactorSet` variable is set to `false` if the sky view factor field is blank.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 28]
```diff
@@ -8189,6 +8190,7 @@ namespace SurfaceGeometry {
                 // N2: ground view factor
                 if (!state.dataIPShortCut->lNumericFieldBlanks(2)) {
                     state.dataSurface->SurroundingSurfsProperty(Loop).GroundViewFactor = state.dataIPShortCut->rNumericArgs(2);
+                    state.dataSurface->SurroundingSurfsProperty(Loop).IsGroundViewFactorSet = true;
```
Comment (Nigusse) [inline src/EnergyPlus/SurfaceGeometry.cc:8193]: Same as above.

**Comment by Myoldmopar** [comment]
ERR diff is just the warning removal, nice.  EIO diffs look to be just the expected change plus some small diffs on warmup convergence.  This is all just contained in the one example file, no change to other files.  I'm OK with these changes.  Anything left to do here @Nigusse @mjwitte ?

**Comment by Nigusse** [comment]
@Myoldmopar That is all from me if @mjwitte is satisfied with final changes I made.

**Review by mjwitte — APPROVED** [review]
@Nigusse @Myoldmopar The changes look good to me. I merged in develop for one more round of CI testing.

**Comment by Myoldmopar** [comment]
There's an extra diff popping up here with the merge from develop.  Is that somehow expected with the merge from develop?  It looks like #9457 did have a couple files with [similar diffs](https://github.com/NREL/EnergyPlus/commit/79e8537f3c08cede9c9db25265b9fac037d6792e#commitcomment-75736350), although Decent CI cleaned up those results, and I'm not inclined to go looking through the results history unless it's needed.  And this branch is already 38 commits behind develop, so I believe this is simply due to that PR.  

I will do a quick build/regression run locally with very latest develop pulled in.

**Comment by Myoldmopar** [comment]
Built locally with the branch as-is and reproduced the extra diffs.  Then pulled develop in and reran regressions, back to where we were before.  This is good to go.  Thanks @Nigusse and @mjwitte.
