### PR TITLE
Correct Kiva::setMessageCallback std:pair argument

### LINKED ISSUE #9309: Crash on Kiva error messaging
Issue overview
--------------
A Kiva model was crashing when hitting the warning "The weights of associated Kiva instances do not add to unity--check exposed perimeter values."  The error was tracked back to and error in the `Kiva::setMessageCallback` function and the second argument needing to be a `std::pair` instead of a `std::string`.

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by matthew-larson**
Pull request overview
---------------------
 - Fixes #9309 
 - This pull request modifies the Kiva::setMessageCallback function argument which requires a std::pair consisting of the `state `pointer and std:string instead of just a std:string that is currently being passed in.  This is the only location a std::pair needs to be passed in.  A unit test was also created to confirm the Kiva messaging is working correctly.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 
### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally

### CODE REVIEW

File: src/EnergyPlus/HeatBalanceKivaManager.cc [hunk 1]
```diff
@@ -1243,8 +1243,8 @@ void KivaManager::calcKivaSurfaceResults(EnergyPlusData &state)
 {
     for (int surfNum = 1; surfNum <= (int)state.dataSurface->Surface.size(); ++surfNum) {
         if (state.dataSurface->Surface(surfNum).ExtBoundCond == DataSurfaces::KivaFoundation) {
-            std::string contextStr = "Surface=\"" + state.dataSurface->Surface(surfNum).Name + "\"";
-            Kiva::setMessageCallback(kivaErrorCallback, &contextStr);
+            std::pair<EnergyPlusData *, std::string> contextPair{&state, "Surface=\"" + state.dataSurface->Surface(surfNum).Name + "\""};
```
Comment (amirroth) [inline src/EnergyPlus/HeatBalanceKivaManager.cc:1246]: :pushpin: use a lambda here instead of this custom pattern? (similar to the Par pattern currently used for calculating residuals in solvers, yes?)

**Comment by mitchute** [comment]
I pulled develop in here locally and ran unit tests, which includes the new test added here. Everything looks good. Anything else before this merges? There are no conflicts and this is a pretty isolated change, so I'm not going to merge up with develop before this goes in.

**Comment by mitchute** [comment]
Merging.
