### PR TITLE
Addresses zone air mass flow balance enforcing problem when there is "balanced" exhaust flow

### LINKED ISSUE #8567: Total site energy doubled between v9.4.0 and v9.5.0-IOFreeze in file with ZoneMixing
Issue overview
--------------

This seems like a massive deviation that perhaps should be investigated to make sure there isn't something wrong.

An OpenStudio-resources regression test shows an increase of 178.819% of total site energy in v9.5.0-IOFreeze compared to v9.4.0. This test has a FanZoneExhaust and some ZoneMixing objects

https://github.com/NREL/OpenStudio-resources/blob/develop/model/simulationtests/zone_fan_exhaust.rb#L52-L86

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.0-IOFreeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: EnergyPlusDevSupport/DefectFiles/8000s/8567
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #8567
 - This code change addresses zone air mass flow balancing enforcing problem when there is user specified "balanced" exhaust flow. Now the zones in the defect files have balanced flow, zones air temperatures are well controlled and the annual electric energy consumption is within 1.47% of EnergyPlus V9.40. 

*Note that this bug was introduced during v9.5.0 development and was present in v9.5.0-IOFreeze.*

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] ~Check any new function arguments for performance impacts~
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

**Comment by Nigusse** [comment]
See below core zone supply air flow rates comparison develop vs EPlusV9.40 and branch (Issue8567) vs EPlusV9.40. The fix, which is the second plot, shows the expected flow rates.

SAFlow_CoreZone

**Comment by Nigusse** [comment]
See below core zone mass flow balance residual comparison develop vs EPlusV9.40 and branch (Issue8567) vs EPlusV9.40. The first plot shows that the core zone in develop is not balanced while the second plot shows the branch also balanced flow for the core zone.

AirFlowBalanceResidual_CoreZone

File: src/EnergyPlus/DataHeatBalance.hh [hunk 1]
```diff
@@ -1377,11 +1377,13 @@ namespace DataHeatBalance {
         int ZoneFlowAdjustment;      // specifies how zone air flow balance is determined (AdjustMixingOnly, AdjustReturnOnly, AdjustMixingThenReturn, AdjustReturnThenMixing, None)
         int InfiltrationTreatment;   // determines how infiltration is treated for zone mass balance
         int InfiltrationZoneType;    // specifies which types of zones allow infiltration to be changed
+        bool AdjustZoneMixingFlow; // used to adjust zone mixing air flows to enforce air flow balance
+        bool AdjustZoneInfiltrationFlow; // used to adjust zone infiltration air flows to enforce air flow balance
```
Comment (Nigusse) [inline src/EnergyPlus/DataHeatBalance.hh:1058]: Added these two member variables that replaced variables defined at module level.

File: src/EnergyPlus/DataHeatBalance.hh [hunk 2]
```diff
@@ -1377,11 +1377,13 @@ namespace DataHeatBalance {
...
                                      // Note, unique global object
 
         // Default Constructor
         ZoneAirMassFlowConservation()
-            : EnforceZoneMassBalance(false), ZoneFlowAdjustment(0), InfiltrationTreatment(0), InfiltrationZoneType(0)
+            : EnforceZoneMassBalance(false), ZoneFlowAdjustment(0), InfiltrationTreatment(0), InfiltrationZoneType(0), AdjustZoneMixingFlow(false), AdjustZoneInfiltrationFlow(false)
```
Comment (Nigusse) [inline src/EnergyPlus/DataHeatBalance.hh:1063]: Initialized the new member variables.

File: src/EnergyPlus/DataHeatBalance.hh [hunk 3]
```diff
@@ -1399,6 +1401,7 @@ namespace DataHeatBalance {
         int NumSourceZonesMixingObject;        // number of zone mixing object references as a source zone
         int NumReceivingZonesMixingObject;     // number of zone mixing object references as a receiving zone
         bool IsOnlySourceZone;                 // true only if used only as a source zone in zone mixing object
+        bool IsSourceAndReceivingZone;         // true only if a zone is used as a source and receiving zone in zone mixing objects
```
Comment (Nigusse) [inline src/EnergyPlus/DataHeatBalance.hh:1081]: Added new flag member variable. This flag is set to true when zone is used as a source and receiving zone and is used to re-order the zone.

File: src/EnergyPlus/HeatBalanceAirManager.cc [hunk 4]
```diff
@@ -2822,6 +2822,10 @@ namespace HeatBalanceAirManager {
                         MassConservation(ZoneNum).ZoneMixingReceivingPtr(Loop) = ZoneMixingNum(Loop);
                     }
                 }
+                // flag zones used as both source and receiving zone
+                if (MassConservation(ZoneNum).NumSourceZonesMixingObject > 0 && MassConservation(ZoneNum).NumReceivingZonesMixingObject > 0) {
+                    MassConservation(ZoneNum).IsSourceAndReceivingZone = true;
+                }
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceAirManager.cc:2721]: Set to true if a zone serves as a source and receiving zone.

File: src/EnergyPlus/HeatBalanceAirManager.cc [hunk 5]
```diff
@@ -2830,7 +2834,13 @@ namespace HeatBalanceAirManager {
...
         Loop = 0;
         for (ZoneNum = 1; ZoneNum <= state.dataGlobal->NumOfZones; ++ZoneNum) {
-            if (!MassConservation(ZoneNum).IsOnlySourceZone) {
+            if (!MassConservation(ZoneNum).IsOnlySourceZone && !MassConservation(ZoneNum).IsSourceAndReceivingZone) {
+                Loop += 1;
+                ZoneReOrder(Loop) = ZoneNum;
+            }
+        }
+        for (ZoneNum = 1; ZoneNum <= state.dataGlobal->NumOfZones; ++ZoneNum) {
+            if (MassConservation(ZoneNum).IsSourceAndReceivingZone) {
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceAirManager.cc]: Used to re-order the zone. Now the order is receiving zones first, followed by zones used as a source and receiving, and finally zones used as a source zone only.

File: src/EnergyPlus/HeatBalanceManager.cc [hunk 6]
```diff
@@ -1309,6 +1309,7 @@ namespace HeatBalanceManager {
                         ShowWarningError(state, CurrentModuleObject + ": Invalid input of " + cAlphaFieldNames(1) + ". The default choice is assigned = None");
                     }
                 }
+                if (ZoneAirMassFlow.ZoneFlowAdjustment != DataHeatBalance::NoAdjustReturnAndMixing) ZoneAirMassFlow.AdjustZoneMixingFlow = true;
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceManager.cc]: Now the "AdjustZoneMixingFlow" member variable is set once and will be true only when the flow adjustment method is not "None"

File: src/EnergyPlus/HeatBalanceManager.cc [hunk 7]
```diff
@@ -1366,6 +1367,7 @@ namespace HeatBalanceManager {
         } else {
             ZoneAirMassFlow.EnforceZoneMassBalance = false;
         }
+        if (ZoneAirMassFlow.InfiltrationTreatment != DataHeatBalance::NoInfiltrationFlow) ZoneAirMassFlow.AdjustZoneInfiltrationFlow = true;
```
Comment (Nigusse) [inline src/EnergyPlus/HeatBalanceManager.cc]: Now the "AdjustZoneInfiltrationFlow" member variable is set once and will be true only when the infiltration flow treatment method is not "None".

File: src/EnergyPlus/SimulationManager.cc [hunk 8]
```diff
@@ -3105,7 +3105,7 @@ void Resimulate(EnergyPlusData &state,
         // HVAC simulation
         ManageZoneAirUpdates(state, iGetZoneSetPoints, ZoneTempChange, false, UseZoneTimeStepHistory, 0.0);
         if (state.dataContaminantBalance->Contaminant.SimulateContaminants) ManageZoneContaminanUpdates(state, iGetZoneSetPoints, false, UseZoneTimeStepHistory, 0.0);
-        CalcAirFlowSimple(state, 0, ZoneAirMassFlow.EnforceZoneMassBalance, ZoneAirMassFlow.EnforceZoneMassBalance);
+        CalcAirFlowSimple(state, 0, ZoneAirMassFlow.AdjustZoneMixingFlow, ZoneAirMassFlow.AdjustZoneInfiltrationFlow);
```
Comment (Nigusse) [inline src/EnergyPlus/SimulationManager.cc]: Replaced with the correct variable.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 9]
```diff
@@ -2632,11 +2632,6 @@ namespace EnergyPlus::ZoneEquipmentManager {
 
         // Determine flow rate and temperature of supply air based on type of damper
 
-        //bool AdjustZoneMassFlowFlag(true); // holds zone mixing and infiltration flow calc status
-
-        bool AdjustZoneMixingFlowFlag(true); // holds zone mixing air flow calc status
-        bool AdjustZoneInfiltrationFlowFlag(true); // holds zone infiltration air flow calc status
-
         FirstCall = true;
```
Comment (Nigusse) [inline src/EnergyPlus/ZoneEquipmentManager.cc:2625]: Removed replaced module variables.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 10]
```diff
@@ -2685,9 +2680,11 @@ namespace EnergyPlus::ZoneEquipmentManager {
         // and controllers
 
         if (ZoneAirMassFlow.EnforceZoneMassBalance) {
-            if (ZoneAirMassFlow.ZoneFlowAdjustment == DataHeatBalance::NoAdjustReturnAndMixing) AdjustZoneMixingFlowFlag = false;
-            if (ZoneAirMassFlow.ZoneFlowAdjustment == DataHeatBalance::NoInfiltrationFlow) AdjustZoneInfiltrationFlowFlag = false;
-            CalcAirFlowSimple(state, 0, AdjustZoneMixingFlowFlag, AdjustZoneInfiltrationFlowFlag);
```
Comment (Nigusse) [inline src/EnergyPlus/ZoneEquipmentManager.cc:2680]: Already set at get input. No need to do it here.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 11]
```diff
@@ -2685,9 +2680,11 @@ namespace EnergyPlus::ZoneEquipmentManager {
...
+            if (FirstHVACIteration) {
+                CalcAirFlowSimple(state, 0);
+            } else {
+                CalcAirFlowSimple(state, 0, ZoneAirMassFlow.AdjustZoneMixingFlow, ZoneAirMassFlow.AdjustZoneInfiltrationFlow);
+            }
```
Comment (Nigusse) [inline src/EnergyPlus/ZoneEquipmentManager.cc:2676]: Adjust the zone mixing and infiltration air flows only when "FirstHVACIteration" is false.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 12]
```diff
@@ -4009,9 +4006,14 @@ namespace EnergyPlus::ZoneEquipmentManager {
...
-                                         (TotExhaustAirMassFlowRate - state.dataZoneEquip->ZoneEquipConfig(ZoneNum).ZoneExhBalanced);
+                if (ZoneAirMassFlow.EnforceZoneMassBalance) {
+                    // do not include adjusted for "balanced" exhaust flow
+                    StdTotalReturnMassFlow = TotInletAirMassFlowRate + ZoneMixingNetAirMassFlowRate - TotExhaustAirMassFlowRate;
+                } else {
+                    // Calculate standard return air flow rate using default method of inlets minus exhausts adjusted for "balanced" exhaust flow
+                    StdTotalReturnMassFlow = TotInletAirMassFlowRate + ZoneMixingNetAirMassFlowRate -
+                        (TotExhaustAirMassFlowRate - state.dataZoneEquip->ZoneEquipConfig( ZoneNum ).ZoneExhBalanced);
+                }
                 if (!ZoneAirMassFlow.EnforceZoneMassBalance) {
```
Comment (Nigusse) [inline src/EnergyPlus/ZoneEquipmentManager.cc]: Do not include the "balanced" exhaust flow term in the zone air mass balancing enforcing equation if "EnforceZoneMassBalance" is true.

Comment (Nigusse) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: Probably I should use "ZoneAirMassFlow.ZoneFlowAdjustment != DataHeatBalance::NoAdjustReturnAndMixing" to allow the existing equation when using infiltration treatment methods only to enforce zone air flow balance.

Comment (Nigusse) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: This will be revised in the next push cycle along with unit tests.

**Comment by Nigusse** [comment]
This check in removes unused variables in one of the unit tests added. This branch will be ready for review once the regression run completes.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 13]
```diff
@@ -4001,9 +3997,14 @@ namespace EnergyPlus::ZoneEquipmentManager {
                 Node(ZoneNode).MassFlowRateMin = TotInletAirMassFlowRateMin;
                 Node(ZoneNode).MassFlowRateMinAvail = TotInletAirMassFlowRateMinAvail;
 
-                // Calculate standard return air flow rate using default method of inlets minus exhausts adjusted for "balanced" exhaust flow
-                StdTotalReturnMassFlow = TotInletAirMassFlowRate + ZoneMixingNetAirMassFlowRate -
-                                         (TotExhaustAirMassFlowRate - state.dataZoneEquip->ZoneEquipConfig(ZoneNum).ZoneExhBalanced);
+                if (state.dataHeatBal->ZoneAirMassFlow.ZoneFlowAdjustment != DataHeatBalance::NoAdjustReturnAndMixing) {
+                    // do not include adjusted for "balanced" exhaust flow
```
Comment (mjwitte) [inline src/EnergyPlus/ZoneEquipmentManager.cc]: So, if I'm following correctly, this change means that exhaust fan balancing will be ignored whenever ZoneAirMassFlowConservation is active? If that's what we want, then there should be a warning in the exhaust fan input processing that the balancing schedule will be ignored. But I'm wondering if a better solution would be to remove the balanced exhaust flow higher up from the mass conservation exhaust flow so it just disappears from the mass conservation balance up front.

Comment (Nigusse) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: In this defect file the exhaust fan balancing terms leads to convergence problem and without the limit that I added on the zone return flow, the zone return flow rate could have been higher than the values we observed.

Comment (Nigusse) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: OK. I will work to remove the balanced exhaust flow higher up from the mass conservation exhaust flow.

Comment (mjwitte) [reply src/EnergyPlus/ZoneEquipmentManager.cc]: Let's think this through before making more code changes. Maybe it's better to just warn that it's ignored when using ZoneAirMassFlowConservation. @EnergyArchmage @rraustad Any opinions on this?

**Comment by mjwitte** [comment]
Referring to https://github.com/NREL/EnergyPlus/pull/8607#issuecomment-799760085, that warning works for me.

**Comment by Nigusse** [comment]
OK. Here is a sample warning error message. Let me know if you want to alter the message:

```
   ** Warning ** GetFanInput: Fan:ZoneExhaust: invalid Balanced Exhaust Fraction Schedule Name = ALWAYS ON CONTINUOUS for Name=FAN ZONE EXHAUST 1
   **   ~~~   ** When zone air mass flow balance is enforced, this input field should be left blank.
   **   ~~~   ** This fraction schedule will be ignored in the simulation.
```

File: doc/input-output-reference/src/overview/group-fans.tex [hunk 14]
```diff
@@ -618,7 +618,7 @@ \subsubsection{Inputs}\label{inputs-3-014}
...
...infiltration, ventilation, or zone mixing. Unbalanced exhaust is then modeled as being provided by the outdoor air system in the central air system. The modeling of unbalanced will reduce the flow rates at the zone's return air node by the flow rate that is being exhausted and will ensure that the outdoor air flow rate is sufficient to serve the exhaust. If this field is used, then enter the name of a schedule with fractional values between 0.0 and 1.0, inclusive. This fraction is applied to the exhaust fan flow rate and the model tracks the portion of the exhaust that is balanced. Balanced exhaust is then modeled as being provided by simple airflows and does not impact the central air system return air or outdoor air flow rates. For example, if a kitchen zone with an exhaust fan is designed to draw half of its make up air from a neighboring dining room and the other half from the outdoor air system, then a schedule value of 0.5 could be used here. This input field must be blank when the zone air flow balance is enforced. If user specifies a schedule and zone air flow balance is enforced, then EnergyPlus throws a warning error message, ignores the schedule and simulation continues.
```
Comment (Nigusse) [inline doc/input-output-reference/src/overview/group-fans.tex:621]: Added a note that this input field must be left blank if the zone air mass flow balance is enforced.

File: src/EnergyPlus/Fans.cc [hunk 15]
```diff
@@ -591,18 +592,31 @@ namespace EnergyPlus::Fans {
...
-                        ShowContinueError(state, "Schedule values must be (>=0., <=1.)");
+
+                if (state.dataHeatBal->ZoneAirMassFlow.ZoneFlowAdjustment != DataHeatBalance::NoAdjustReturnAndMixing) {
+                    // do not include adjusted for "balanced" exhaust flow in the zone total return calculation
+                    ShowWarningError(state,
+                                     RoutineName + cCurrentModuleObject + ": invalid " + cAlphaFieldNames(9) + " = " + cAlphaArgs(9) +
+                                         " for " + cAlphaFieldNames(1) + '=' + cAlphaArgs(1));
+                    ShowContinueError(state, "When zone air mass flow balance is enforced, this input field should be left blank.");
+                    ShowContinueError(state, "This schedule will be ignored in the simulation.");
+                    Fan(FanNum).BalancedFractSchedNum = 0;
```
Comment (Nigusse) [inline src/EnergyPlus/Fans.cc:603]: If zone air mass flow conservation enforcement is request, this code forces the program to ignore the schedule and throws a warning error message.

File: src/EnergyPlus/Fans.cc [hunk 16]
```diff
@@ -591,18 +592,31 @@ namespace EnergyPlus::Fans {
...
                         ErrorsFound = true;
+                    } else if (Fan(FanNum).BalancedFractSchedNum > 0) {
+                        if (!CheckScheduleValueMinMax(state, Fan(FanNum).BalancedFractSchedNum, ">=", 0.0, "<=", 1.0)) {
+                            ShowSevereError(state,
+                                            RoutineName + cCurrentModuleObject + ": invalid " + cAlphaFieldNames(9) + " for " + cAlphaFieldNames(1) +
+                                                '=' + cAlphaArgs(1));
+                            ShowContinueError(state, "Error found in " + cAlphaFieldNames(9) + " = " + cAlphaArgs(9));
+                            ShowContinueError(state, "Schedule values must be (>=0., <=1.)");
+                            ErrorsFound = true;
+                        }
```
Comment (Nigusse) [inline src/EnergyPlus/Fans.cc:619]: Else the existing capability is supported.

File: src/EnergyPlus/VariableSpeedCoils.cc [hunk 17]
```diff
@@ -7472,8 +7472,8 @@ namespace VariableSpeedCoils {
             //   Calculate apparatus dew point conditions using TotCap and CBF
             Real64 hDelta = TotCapCalc / AirMassFlow;                       // Change in air enthalpy across the cooling coil [J/kg]
             Real64 hADP = InletEnthalpy - hDelta / (1.0 - localCBF);        // Apparatus dew point enthalpy [J/kg]
-            Real64 tADP = PsyTsatFnHPb(state, hADP, Pressure);                     // Apparatus dew point temperature [C]
-            Real64 wADP = PsyWFnTdbH(state, tADP, hADP);                           // Apparatus dew point humidity ratio [kg/kg]
+            Real64 tADP = PsyTsatFnHPb(state, hADP, Pressure, RoutineName); // Apparatus dew point temperature [C]
+            Real64 wADP = PsyWFnTdbH(state, tADP, hADP, RoutineName);       // Apparatus dew point humidity ratio [kg/kg]
```
Comment (Nigusse) [inline src/EnergyPlus/VariableSpeedCoils.cc:7478]: Added routine name such that PsyTsatFnHPb()  point to the offending function.

File: src/EnergyPlus/ZoneEquipmentManager.cc [hunk 18]
```diff
@@ -3993,7 +3989,8 @@ namespace EnergyPlus::ZoneEquipmentManager {
 
                 // Calculate standard return air flow rate using default method of inlets minus exhausts adjusted for "balanced" exhaust flow
                 StdTotalReturnMassFlow = TotInletAirMassFlowRate + ZoneMixingNetAirMassFlowRate -
-                                         (TotExhaustAirMassFlowRate - state.dataZoneEquip->ZoneEquipConfig(ZoneNum).ZoneExhBalanced);
+                    (TotExhaustAirMassFlowRate - state.dataZoneEquip->ZoneEquipConfig(ZoneNum).ZoneExhBalanced);
+
```
Comment (Nigusse) [inline src/EnergyPlus/ZoneEquipmentManager.cc:3993]: Reverted back to the original implementation since the exhaust balanced flow schedule is ignored at the get input if not needed.

**Comment by Nigusse** [comment]
@Myoldmopar I see documentation and Linux build failing but I don't understand what is causing the build problem. Any clue?

**Comment by Myoldmopar** [comment]
Github Action build issues are unrelated.  Looks like this branch is back to what we were seeing before, 2 files with expected diffs.  The new warning message looks good.  The results are obviously way better, I'm glad we are getting this back closer to 9.4.  @jmarrec FYI.

I'll be happy to build, test, and review the code changes.  Everyone else satisfied here?

**Comment by mjwitte** [comment]
@Myoldmopar I'll test and merge this one.

**Review by mjwitte — APPROVED** [review]
@Nigusse Tested locally, warning appears as expected when massflow conservation is active and the exhaust fan has a balanced flow schedule.  And doesn't appear when these conditions are not met.
Running unit tests locally, but I don't expect any problems. Merging.

**Comment by jmarrec** [comment]
Thanks for the fix @Nigusse! And @mjwitte for the review
