### PR TITLE
Fix heating energy calculation and reporting errors for gas fired and exhaust fired absorption chillerheater models

### LINKED ISSUE #8644: Heating report value NaN problem due to exhaust fired absorption chillerheater model floating point errors
Issue overview
--------------
It was reported in the defect file that the energy usage reporting tables got NaN values all the way. 

The root cause is identified for this problem. It is due to the floating point error when the chiller heater does not have sufficient heating capacity, for example, in case of hot summer days when the full cooling capacity is demanded for the chillerheater. 

Currently there is no walk-around for this problem. Code modifications are need to handle the float error case in order to fix. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA) V9.4, V9.5 pre-release, probably all earlier versions
 - Helpdesk ticket number 15668

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport/DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #8644
 - Fix the exhaust fired absorption chillerheater model heating energy calculation and reporting errors, which caused NaN values in tabular reports.
 - Similar problems could be encountered for the gas fired absorption chillerheater as well. The PR also included the fix for the the gas fired absorption chillerheat model. 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [ ] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] ~Check any new function arguments for performance impacts~
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

File: src/EnergyPlus/ChillerExhaustAbsorption.cc [hunk 1]
```diff
@@ -1888,7 +1888,13 @@ namespace EnergyPlus::ChillerExhaustAbsorption {
             }
 
             // Calculate operating part load ratio for cooling
-            lHeatPartLoadRatio = lHeatingLoad / lAvailableHeatingCapacity;
+            if (lAvailableHeatingCapacity <= 0.0) {
+                lAvailableHeatingCapacity = 0.0;
+                lHeatPartLoadRatio = 0.0;
+            } else
+            {
```
Comment (mjwitte) [inline src/EnergyPlus/ChillerExhaustAbsorption.cc:1895]: Straightforward change to protect against divide by zero here and in the next chiller.
Minor formatting issue here, but that will get cleaned up with a global clang format sweep, so not holding this up for that.

**Review by mjwitte — APPROVED** [review]
Tested the defect file before and after:
develop debug build crashes.
develop release build has NANs in BEPS.
this branch debug build completes without NANs.

**Comment by mjwitte** [comment]
Not waiting any longer for CI to finish, merging.
