### PR TITLE
Fix Reversed System and Zone Timesteps in OutputReportTabularAnnual

### LINKED ISSUE #11419: Reversed System and Zone Timestep Reporting in OutputReportTabularAnnual
### Issue overview

`getElapsedTime` and `getSecondsInTimeStep` in OutputReportTabularAnnual both show reversed logic for returning system vs the zone timestep.

https://github.com/NatLabRockies/EnergyPlus/blob/673d8f5dd7fcabc4706668a55023b74f2e829f9f/src/EnergyPlus/OutputReportTabularAnnual.cc#L612-L632

This likely should be reversed.

### Operating System (Multiple choices)

Any, Ubuntu

### Operating System Version

24.04

### Version of EnergyPlus

26.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------

- Fixes #11419 

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
I ran regressions locally and saw large changes in PurchAirTables_wAnnual.

File: src/EnergyPlus/OutputReportTabularAnnual.cc [hunk 1]
```diff
@@ -613,9 +614,9 @@ Real64 AnnualTable::getElapsedTime(EnergyPlusData &state, OutputProcessor::TimeS
 {
     Real64 elapsedTime;
     if (kindOfTimeStep == OutputProcessor::TimeStepType::Zone) {
-        elapsedTime = state.dataHVACGlobal->TimeStepSys;
-    } else {
         elapsedTime = state.dataGlobal->TimeStepZone;
+    } else {
+        elapsedTime = state.dataHVACGlobal->TimeStepSys;
```
Comment (rraustad) [inline src/EnergyPlus/OutputReportTabularAnnual.cc:619]: This certainly does look backwards.

Comment (mitchute) [reply src/EnergyPlus/OutputReportTabularAnnual.cc:619]: @JasonGlazer FYI

**Comment by rraustad** [comment]
Trying to verify what was fixed I see this between develop and this branch. The reported data in this branch does look correct. I am not sure why "develop" shows -9.9E-99 for the West Zone in [11422](https://github.com/NatLabRockies/EnergyPlus/pull/11422) but does not show that here. Anyway, this change does correct the maximum watts for lighting.

image

**Comment by rraustad** [comment]
Also noticed that if I sum the hourly lighting for the summer design day between hours 8 and 18 I get 14643 Whs (e.g., 10 hrs * 1464.375 Watts). And that is just 1 day, not the whole year. Whether this table is a sum or an average the result in the first column is wrong. I thought this table would sum the whole year (units is kWh) but maybe it's an average for a variable with units of watts and would be a sum for a report with units of joules. I think there may be other issues with this table. MIght be out of scope here but noted none the less. This variable is in joules so I would assume the sum over the environment.

    Zone,Sum,Zone Lights Electricity Energy [J]

    Output:Table:Annual,
      Zone Electric Annual Summary,  !- Name
      ,                        !- Filter
      INTERMITTENT,            !- Schedule Name
      Zone Lights Electricity Energy,  !- Variable or Meter or EMS Variable or Field 1 Name
      SumOrAverage,            !- Aggregation Type for Variable or Meter 1
      ,                        !- Digits After Decimal 1
      Zone Lights Electricity Energy,  !- Variable or Meter or EMS Variable or Field 2 Name
      Maximum,                 !- Aggregation Type for Variable or Meter 2
      ,                        !- Digits After Decimal 2
      Zone Electric Equipment Electricity Energy,  !- Variable or Meter or EMS Variable or Field 3 Name
      SumOrAverage,            !- Aggregation Type for Variable or Meter 3
      ,                        !- Digits After Decimal 3
      Zone Electric Equipment Electricity Energy,  !- Variable or Meter or EMS Variable or Field 4 Name
      Maximum,                 !- Aggregation Type for Variable or Meter 4
      ;                        !- Digits After Decimal 4

    Schedule:Compact,
      INTERMITTENT,            !- Name
      Fraction,                !- Schedule Type Limits Name
      Through: 12/31,          !- Field 1
      For: WeekDays SummerDesignDay WinterDesignDay, !- Field 2
      Until: 8:00,0.0,         !- Field 3
      Until: 18:00,1.00,       !- Field 5
      Until: 24:00,0.0,        !- Field 7
      For: AllOtherDays,       !- Field 9
      Until: 24:00,0.0;        !- Field 10

**Comment by rraustad** [comment]
OK, I assume my math is wrong. If I sum the total lighting J over the year for the East Zone (16,152,642,000 J) and convert to kWh I get 4486. However, the result of 3617 is for hours 8-18 which is nearly the peak of lighting output (i.e., schedule values close to 1 over this time period). So i can easily believe the result should be 3617 kWhs. Although I am having trouble getting to that value with time series data. Using some if logic in excel to only incllude hours 8 - 18, and subtract out weekends, I am coming up with 3617 kWhs.

So this seems to be verified as a good fix. Whew!

image

**Comment by mitchute** [comment]
Thanks for digging into that comparison @rraustad. Merging.
