### PR TITLE
Fix #10962 - Schedule:Constant is reset to zero when EMS Sensor is attached

### LINKED ISSUE #10962: E+ 25.1 HPWH simulations incorrect
### Issue overview

An IDF with a heat pump water heater (`WaterHeater:HeatPump:WrappedCondenser` and `WaterHeater:Stratified`) has new warnings and very different simulation results in E+ 25.1 vs 24.2.

Simulation results for Water Systems changed from 3.81 GJ (24.2) to 0.09 GJ (25.1).

Example warning in 25.1:
```
   ** Warning ** CalcEquipmentFlowRates: "DHW FIXTURES" - Target water temperature is greater than the hot water temperature by (29.06 C)
   **   ~~~   **  Environment=RUN PERIOD 1, at Simulation time=01/01 00:00 - 01:00
   **   ~~~   ** ...target water temperature     = 40.56 C
   **   ~~~   ** ...hot water temperature        = 11.50 C
   **   ~~~   ** ...Target water temperature should be less than or equal to the hot water temperature. Verify temperature setpoints and schedules.
```

~I did not see this issue for IDFs with conventional storage water heaters (`WaterHeater:Mixed`).~ Sounds like it could be a unit conversion bug?

### Operating System (Multiple choices)

Ubuntu

### Operating System Version

24.04

### Version of EnergyPlus

25.1 IO Freeze

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[in_24_2.idf.txt](https://github.com/user-attachments/files/19015536/in_24_2.idf.txt)
[in_25_1.idf.txt](https://github.com/user-attachments/files/19015539/in_25_1.idf.txt)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fixes #10962

### Description of the purpose of this PR

This issue only affects 25.1.0-IOFreeze, it wasn't in 24.2.0.

As I said here: https://github.com/NREL/EnergyPlus/issues/10962#issuecomment-2707006113

I finally found the root cause.
* It is due to ScheduleManager refactor: #10848 
* It only occurs because you have an EMS sensor on the Schedule Value

What happens:

* OutputProcessor sets up a report var which is linked to the sched->currentVal, and this is a non const ref
* `EnergyPlus::OutputProcessor::SetInternalVariableValue` will be called to reset it to zero: https://github.com/NREL/EnergyPlus/blob/9814fa5069b4cf52457ff0f9d18c7422f83eb33a/src/EnergyPlus/RuntimeLanguageProcessor.cc#L349
* The PR that updated the ScheduleManager modified getHrTsVal, and instead of getting the value from tsVals, for Schedule:Constant, it grabs currentVal. Which got reset to zero...
https://github.com/NREL/EnergyPlus/blob/9814fa5069b4cf52457ff0f9d18c7422f83eb33a/src/EnergyPlus/ScheduleManager.cc#L2459-L2462

----

## Defect files testing

I have confirmed that with the defect files provided I get correct results.  73.32 GJ in 24.2.0 and with this PR, and  60.54 with IOFreeze. The extra warnings in eplusout.err are gone too.

I also have created a MCVE idf that exhibits the issue, for which I'm plotting the Schedule Value. It is zero with IOFreeze, and the correct 40.56 C with this PR.

Before:

image

After:

image

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ScheduleManager.cc [hunk 1]
```diff
@@ -1802,14 +1802,15 @@ namespace Sched {
             }
 
             sched->currentVal = Numbers(1);
-            sched->tsVals.resize(Constant::iHoursInDay * s_glob->TimeStepsInHour);
-            for (int i = 0; i < Constant::iHoursInDay * s_glob->TimeStepsInHour; ++i)
-                sched->tsVals[i] = sched->currentVal;
+            sched->tsVals.assign(Constant::iHoursInDay * s_glob->TimeStepsInHour, sched->currentVal);
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc]: Replace with assign instead of looping. This will resize and fill it up.

File: src/EnergyPlus/ScheduleManager.cc [hunk 2]
```diff
@@ -1802,14 +1802,15 @@ namespace Sched {
...
 
             if (s_glob->AnyEnergyManagementSystemInModel) { // setup constant schedules as actuators
                 SetupEMSActuator(state, "Schedule:Constant", sched->Name, "Schedule Value", "[ ]", sched->EMSActuatedOn, sched->EMSVal);
             }
         }
+        // When InitConstantScheduleData is called, TimeStepsInHour is 0, so we delay it here
+        static_cast<ScheduleConstant *>(s_sched->schedules[SchedNum_AlwaysOff])->tsVals.assign(Constant::iHoursInDay * s_glob->TimeStepsInHour, 0.0);
+        static_cast<ScheduleConstant *>(s_sched->schedules[SchedNum_AlwaysOn])->tsVals.assign(Constant::iHoursInDay * s_glob->TimeStepsInHour, 1.0);
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:1813]: I also set the tsVals for the constant ones.

File: src/EnergyPlus/ScheduleManager.cc [hunk 3]
```diff
@@ -2458,7 +2459,8 @@ namespace Sched {
 
     Real64 ScheduleConstant::getHrTsVal([[maybe_unused]] EnergyPlusData &state, [[maybe_unused]] int hr, [[maybe_unused]] int ts) const
     {
-        return this->currentVal;
+        // cf #10962 - We can't use currentValue as it could be overwritten by the EMS Sensor
+        return this->tsVals.front();
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:2463]: And I grab the value like this.

File: tst/EnergyPlus/unit/EMSManager.unit.cc [hunk 4]
```diff
@@ -2604,3 +2604,235 @@ TEST_F(EnergyPlusFixture, EMSManager_TrendValue_to_Actuator)
     EXPECT_TRUE(schedIndirect->EMSActuatedOn);
     EXPECT_EQ(45.0, schedIndirect->EMSVal);
 }
+
+TEST_F(EnergyPlusFixture, EMSManager_Sensor_On_ScheduleConstant)
+{
+
+    // Test for #10962 - Make sure that assigning a Sensor on a Schedule:Constant does not reset it to zero
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/EMSManager.unit.cc:2611]: New test. It's hard to read because it's hard to set the conditions right.

File: tst/EnergyPlus/unit/EMSManager.unit.cc [hunk 5]
```diff
@@ -2604,3 +2604,235 @@ TEST_F(EnergyPlusFixture, EMSManager_TrendValue_to_Actuator)
...
+        "EnergyManagementSystem:Program,",
+        "  sch_test,                               !- Name",
+        "  SET DummyVal = ScheduleConstant_Sensor; !- Program Line 1",
+
+        "EnergyManagementSystem:ProgramCallingManager,",
+        "  sch_test_pcm,                           !- Name",
+        "  BeginTimestepBeforePredictor,           !- EnergyPlus Model Calling Point",
+        "  sch_test;                               !- Program Name 1",
+
+        "Output:Variable,*,Schedule Value,Timestep;",
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/EMSManager.unit.cc:2633]: Simple input. A schedule, and a EMS:Sensor on it.

File: tst/EnergyPlus/unit/EMSManager.unit.cc [hunk 6]
```diff
@@ -2604,3 +2604,235 @@ TEST_F(EnergyPlusFixture, EMSManager_TrendValue_to_Actuator)
...
+    state->init_state(*state);
+
+    OutputProcessor::SetupTimePointers(
+        *state, OutputProcessor::TimeStepType::Zone, state->dataGlobal->TimeStepZone); // Set up Time pointer for HB/Zone Simulation
+    OutputProcessor::SetupTimePointers(*state, OutputProcessor::TimeStepType::System, state->dataHVACGlobal->TimeStepSys);
+
+    // Read EMS first, it should NOT find the Schedule Value in the output processor.
+    bool anyEMSRan = false;
+    EMSManager::ManageEMS(*state, EMSManager::EMSCallFrom::BeginZoneTimestepBeforeInitHeatBalance, anyEMSRan, ObjexxFCL::Optional_int_const());
+    EXPECT_FALSE(anyEMSRan);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/EMSManager.unit.cc:2689]: First call to ManageEMS, I have to ensure I don't find the output variable yet, or CheckedOkay is set and the .sched is never resolved in ProcessEMSInput (don't ask me why it does it in two passes)

File: tst/EnergyPlus/unit/EMSManager.unit.cc [hunk 7]
```diff
@@ -2604,3 +2604,235 @@ TEST_F(EnergyPlusFixture, EMSManager_TrendValue_to_Actuator)
...
+    EXPECT_ENUM_EQ(EnergyPlus::OutputProcessor::VariableType::Real, sensor.VariableType);
+    EXPECT_TRUE(sensor.CheckedOkay);
+    EXPECT_NE(nullptr, sensor.sched);
+    EXPECT_EQ(schedDirect, sensor.sched);
+
+    EXPECT_EQ(0.0, schedDirect->currentVal);
+    EXPECT_FALSE(schedDirect->EMSActuatedOn);
+    EXPECT_EQ(0.0, schedDirect->EMSVal);
+    Sched::ReportScheduleVals(*state); // ReportScheduleVals will take care of adding the Output Variables
+    EXPECT_EQ(45.0, schedDirect->currentVal);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/EMSManager.unit.cc:2782]: First failure in the test  before fix. This would be 0.0


Full failure

```
[ RUN      ] EnergyPlusFixture.EMSManager_Sensor_On_ScheduleConstant
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2782: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->currentVal
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2783: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->getCurrentVal()
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2809: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->currentVal
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2810: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->getCurrentVal()
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2822: Failure
Expected equality of these values:
  45.0
    Which is: 45
  sensorErlVar.Value.Number
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2830: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->currentVal
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2834: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->currentVal
    Which is: 0
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/EMSManager.unit.cc:2835: Failure
Expected equality of these values:
  45.0
    Which is: 45
  schedDirect->getCurrentVal()
    Which is: 0
```

**Comment by jmarrec** [comment]
I have considered only modifying this block here:

https://github.com/NREL/EnergyPlus/blob/9814fa5069b4cf52457ff0f9d18c7422f83eb33a/src/EnergyPlus/RuntimeLanguageProcessor.cc#L347-L351

```diff
    for (SensorNum = 1; SensorNum <= state.dataRuntimeLang->NumSensors; ++SensorNum) {
+        if (state.dataRuntimeLang->Sensor(SensorNum).sched == nullptr) {
            SetInternalVariableValue(
                state, state.dataRuntimeLang->Sensor(SensorNum).VariableType, state.dataRuntimeLang->Sensor(SensorNum).Index, 0.0, 0);
+        }
    }
```

But it didn't seem too wise, and I didn't understand the implications.

**Comment by jmarrec** [comment]
I've got test issues... Working on it.

**Review by shorowit — APPROVED** [review]
I just compiled and tested both this PR and https://github.com/NREL/EnergyPlus/pull/10966 together. Confirmed that the 25.1 warnings have disappeared and the results match 24.2 again. Thanks for tracking this down and fixing it, @jmarrec!

**Comment by jmarrec** [comment]
So I've got a container overflow with ASAN enabled. If I disable that, it's a heap after use.

It occurs with TestAPI_RuntimeResetState_C.

I think there is an actual existing problem to begin with.

The Constant-0.0 and Constant-1.0 schedules are initialized in `ScheduleManagerData::init_constant_state` which calls `Sched::InitConstantScheduleData`.

But then are actually DELETED (delete pointer) in clear_state.

stateReset will call clear_state, but will NOT call init_constant_state, only init_state.

So these two schedules are actually GONE the second time E+ in run.

**Comment by jmarrec** [comment]
Unrelated but why is this one not virtual? https://github.com/NREL/EnergyPlus/blob/9814fa5069b4cf52457ff0f9d18c7422f83eb33a/src/EnergyPlus/ScheduleManager.hh#L343

File: src/EnergyPlus/ScheduleManager.hh [hunk 8]
```diff
@@ -517,16 +513,26 @@ struct ScheduleManagerData : BaseGlobalStruct
     std::map<std::string, int> dayScheduleMap;
     std::map<std::string, int> weekScheduleMap;
 
+    Sched::ScheduleConstant SchedAlwaysOff;
+    Sched::ScheduleConstant SchedAlwaysOn;
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.hh]: I'm going to be storing these on the stack, not the heap.

File: src/EnergyPlus/ScheduleManager.hh [hunk 9]
```diff
@@ -517,16 +513,26 @@ struct ScheduleManagerData : BaseGlobalStruct
...
+
     void init_constant_state(EnergyPlusData &state) override
     {
-        Sched::InitConstantScheduleData(state);
+        InitConstantScheduleData();
+        AddConstantSchedulesToContainers();
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.hh]: In init_constant_state, I will set the SchedAlwaysOff/On members.
Then I add them to schedules and schedulesMap

File: src/EnergyPlus/ScheduleManager.hh [hunk 10]
```diff
@@ -541,10 +547,14 @@ struct ScheduleManagerData : BaseGlobalStruct
...
 
-        for (int i = 0; i < (int)schedules.size(); ++i)
+        // Don't try to delete the constant schedules which were not malloced
+        for (int i = 2; i < (int)schedules.size(); ++i) {
             delete schedules[i];
+        }
         schedules.clear(); // Schedule Storage
         scheduleMap.clear();
+        // Put back the ConstantSchedules
+        AddConstantSchedulesToContainers();
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.hh]: In clear_state, I avoid trying to delete the stack objects. And I re-add them back in schedules/scheduleMap, so that it's back to the init_initial_state state.

File: src/EnergyPlus/ScheduleManager.cc [hunk 11]
```diff
@@ -2465,12 +2450,12 @@ namespace Sched {
 
     Sched::Schedule *GetScheduleAlwaysOn(EnergyPlusData &state)
     {
-        return state.dataSched->schedules[SchedNum_AlwaysOn];
+        return &state.dataSched->SchedAlwaysOn;
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc]: Both are equivalent, but it's probably faster not to go into the array.

File: src/EnergyPlus/ScheduleManager.cc [hunk 12]
```diff
@@ -2586,11 +2571,7 @@ namespace Sched {
 
     std::vector<Real64> const &ScheduleConstant::getDayVals(EnergyPlusData &state, [[maybe_unused]] int jDay, [[maybe_unused]] int dayofWeek)
     {
-        auto const &s_glob = state.dataGlobal;
-        if ((int)tsVals.size() != Constant::iHoursInDay * s_glob->TimeStepsInHour) {
-            this->tsVals.resize(Constant::iHoursInDay * s_glob->TimeStepsInHour);
-            std::fill(this->tsVals.begin(), this->tsVals.end(), this->currentVal);
-        }
+        assert((int)tsVals.size() == Constant::iHoursInDay * state.dataGlobal->TimeStepsInHour);
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:2589]: Because I make sure all of the tsVals for ScheduleConstant are set ONCE correctly, this can just be an assert now, which will be removed in release mode

File: src/EnergyPlus/ScheduleManager.cc [hunk 13]
```diff
@@ -3862,4 +3841,37 @@ namespace Sched {
...
+void ScheduleManagerData::AddConstantSchedulesToContainers() {
+    assert(Sched::SchedNum_AlwaysOff == (int)this->schedules.size());
+    this->schedules.push_back(&this->SchedAlwaysOff);
+    this->scheduleMap.insert_or_assign(std::move(Util::makeUPPER(this->SchedAlwaysOff.Name)), Sched::SchedNum_AlwaysOff);
+
+    assert(Sched::SchedNum_AlwaysOn == (int)this->schedules.size());
+    this->schedules.push_back(&this->SchedAlwaysOn);
+    this->scheduleMap.insert_or_assign(std::move(Util::makeUPPER(this->SchedAlwaysOn.Name)), Sched::SchedNum_AlwaysOn);
+}
+
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc]: New funcs

**Comment by amirroth** [comment]
> So I've got a container overflow with ASAN enabled. If I disable that, it's a heap after use.
> 
> It occurs with TestAPI_RuntimeResetState_C.
> 
> I think there is an actual existing problem to begin with.
> 
> The Constant-0.0 and Constant-1.0 schedules are initialized in `ScheduleManagerData::init_constant_state` which calls `Sched::InitConstantScheduleData`.
> 
> But then are actually DELETED (delete pointer) in clear_state.
> 
> stateReset will call clear_state, but will NOT call init_constant_state, only init_state.
> 
> So these two schedules are actually GONE the second time E+ in run.

So isn't the right fix to just have `stateReset` also call `init_constant_state()` as opposed to all of this other gymnastics? Seriously. What am I missing?

**Comment by jmarrec** [comment]
I didn't notice that the `init_constant_state` was new in your scheduleAPI PR (I think that's where it orginated), and assumed it was doing stuff for good reasons. It's hard to read 1000 files to make sure that's the case or not, but a quick grep seem to indicate it may only be used by `ScheduleManagerData`. Do you have insight to share there?

That being said:
* I don't understand the purpose of that pattern. Seems like you'd really want to do it in the Ctor for the struct in question.
* Schedule Always On/Off make more sense to be on the stack if they are meant to just be there
I re-add them to vector `schedules`/`scheduleMap` in `init_state` because that's what you were doing. Otherwise I'd have to put back some special cases in `GetSchedule(std::string)` and potentially a few other places (and some I might miss)
     * I think that's the bit you dislike? We could move it to the ctor, and clear_state could become `new (this) ScheduleManagerData();?`
* Having stateReset also call init_constant_state() seems weird and counter intuitive to me. Is it constant state if it's being called several times?


---

(related to placement new: I dislike the `std::vector<Schedule*>schedules` and similar. I understand storing pointers to base because you want polymorphism. But You have a single location  that stores the pointers, a vector of unique_ptr would have made it unnecessary to manage memory manually)

**Comment by amirroth** [comment]
> I didn't notice that the `init_constant_state` was new in your scheduleAPI PR (I think that's where it orginated), and assumed it was doing stuff for good reasons. It's hard to read 1000 files to make sure that's the case or not, but a quick grep seem to indicate it may only be used by `ScheduleManagerData`. Do you have insight to share there?

`init_constant_state()` is currently being used by Schedule (for On/Off) and by FluidProperties (for Water and Steam). It's what it sounds like. It's for the state that comes built-in to EnergyPlus as opposed to coming from the IDF file. The reason I split it off from `init_state()` in the Schedule refactor is that there were a bunch of test fixtures that were doing pretty complicated setup before calling `process_idf()`. When the schedules were referenced as indices, those would just set the index to 0 or -1 and everything would work. When I switched to using Schedules by object pointer that broke and so I split off `init_constant_state()` so that the On/Off objects would be available.

> 
> That being said:
> 
> * I don't understand the purpose of that pattern. Seems like you'd really want to do it in the Ctor for the struct in question.
> * Schedule Always On/Off make more sense to be on the stack if they are meant to just be there
>   I re-add them to vector `schedules`/`scheduleMap` in `init_state` because that's what you were doing. Otherwise I'd have to put back some special cases in `GetSchedule(std::string)` and potentially a few other places (and some I might miss)
>   

In my opinion, constructors should not be super complicated and allocate/initalize sub-objects and what not. That's not a great pattern in my opinion. An explicit `init()` function whose timing you can control is better. This is especially true for EnergyPlus where objects reference one another frequently.

>   * I think that's the bit you dislike? We could move it to the ctor, and clear_state could become `new (this) ScheduleManagerData();?`

I would dislike this even more if you moved it into the constructor. The stack thing is not great IMO, it's just a special case for no reason, and it will be ugly for the FluidProperties objects. But the thing that bothers me is that you are solving the problem of `stateReset` not calling `init_constant_state()` by doing all of this stuff and creating special cases instead of just ... you know ... calling `init_consant_state()`.

> * Having stateReset also call init_constant_state() seems weird and counter intuitive to me. Is it constant state if it's being called several times?

This is the thing about EnergyPlus that seems weird and counter-intuitive to you? Not the fact that we are in this rabbit hole because you can use an EMS *sensor* to change a schedule value? Anyways, `stateReset` was basically calling `init_constant_state()` earlier when that code was still part of `init_state()`. The Schedule stuff wasn't but the FluidProperties stuff was.  Nothing will change except for the name.

**Comment by amirroth** [comment]
> (related to placement new: I dislike the `std::vector<Schedule*>schedules` and similar. I understand storing pointers to base because you want polymorphism. But You have a single location that stores the pointers, a vector of unique_ptr would have made it unnecessary to manage memory manually)

This is a separate discussion so I am splitting it off. I wonder if you dislike raw pointers more than I dislike `unique_ptr` and `shared_ptr`. At least for EnergyPlus. One of the nice things about EnergyPlus is that in theory it has very simple memory management. By the time you've processed the IDF file you know every object you will ever need. You create those objects. You run the simulation. You destroy the objects. You shouldn't need `unique_ptr` wrappers to do memory management that is that simple. I am trying to peel away the layers of duct tape in EnergyPlus so I have been removing those in that spirit.

That said, the thing I actually care about here is that the schedule object pointers that are embedded in the objects that use schedules are `Schedule *`. If there is general sentiment for using `unique_ptr` in the arrays that hold the objects permanently just so that we don't have to have explicit delete loops in `clear_state()`, I guess I am okay with that. At that point `GetSchedule` would return `scheds[idx].get()` instead of `scheds[idx]`?

File: src/EnergyPlus/api/state.cc [hunk 14]
```diff
@@ -70,6 +70,7 @@ void stateReset(EnergyPlusState state)
 {
     auto *this_state = reinterpret_cast<EnergyPlus::EnergyPlusData *>(state);
     this_state->clear_state();
+    this_state->init_constant_state(*this_state);
```
Comment (amirroth) [inline src/EnergyPlus/api/state.cc:73]: Thanks. I think this is a lot cleaner. Sorry for not putting down more documentation about this new pattern to begin with.

Comment (jmarrec) [reply src/EnergyPlus/api/state.cc:73]: If you can think of something to write as a quick docstring here that'd be great: https://github.com/NREL/EnergyPlus/blob/9814fa5069b4cf52457ff0f9d18c7422f83eb33a/src/EnergyPlus/Data/EnergyPlusData.hh#L577

Something like:

"This will initialize a few things early and add them to the data structures. This is called in test fixtures. It will be called again if stateReset is called in the API".

**Comment by jmarrec** [comment]
> That said, the thing I actually care about here is that the schedule object pointers that are embedded in the objects that use schedules are `Schedule *`. If there is general sentiment for using `unique_ptr` in the arrays that hold the objects permanently just so that we don't have to have explicit delete loops in `clear_state()`, I guess I am okay with that. At that point `GetSchedule` would return `scheds[idx].get()` instead of `scheds[idx]`?

Yes, you'd use `unique_ptr.get()`  to return a raw pointer if that's what you want. (or  `std::optional<std::reference_wrapper<Schedule>>` <sup>[1]</sup>)

Anyways, no point in discussing this further, it's not a hill I'll die on, and you already have the vantage point :)

What's more interesting to me is that if I'm reading between the lines correctly, that means that instead of storing an `int` position into another std::vector<T>/std::vector<T*>, you'd rather store a pointer to  it`T*`. (`int GetSheduleIndex(string&)` -> `Schedule* GetSchdule(string&)`)? If so, I am going to try to remember this.


---

<sup>[1]</sup> `std::optional<std::reference_wrapper<Schedule>>`

<details>

<summary>Click to expand</summary>

Or you use `std::optional<std::reference_wrapper<Schedule>>`, there's actually a precedent in E+ which I wasn't really expecting to see to be honest: https://github.com/NREL/EnergyPlus/blob/9814fa5069b4cf52457ff0f9d18c7422f83eb33a/src/EnergyPlus/UtilityRoutines.hh#L133
I find the semantics a bit convoluted in this case TBH. It goes along the lines of

```c++
using OptionalScheduleRef = std::optional<std::reference_wrapper<Schedule>>;

OptionalScheduleRef sched_ = GetSchedule("ConstantB");
if (sched_.has_value()) {
  Schedule& sched = sched_->get();
  sched.Name = "ConstantB_renamed";
}
```
</details>

**Comment by amirroth** [comment]
> What's more interesting to me is that if I'm reading between the lines correctly, that means that instead of storing an `int` position into another std::vector/std::vector<T*>, you'd rather store a pointer to it`T*`. (`int GetSheduleIndex(string&)` -> `Schedule* GetSchdule(string&)`)? If so, I am going to try to remember this.

Yes, this is what we should move to to the extent possible and I have done this with some simple objects like `Schedule` and `FluidProperties` (look at how those are done now, we don't have FluidName/FluidIndex pairs anymore). `Curve` would be next. Storing the pointer directly removes multiple levels of indirection to access, `state`-to-`dataT`, `dataT`-to-`Tarray`, `Tarray`-to-`Telement`.   
 
> [1] `std::optional<std::reference_wrapper<Schedule>>`

Ab. Solutely not. This is a preposterous hack that exists only because there is no such thing as a null reference. But you know what does have a valid null value? A pointer! References are the original sin of C++. The language would be 40% better without them.

File: src/EnergyPlus/ScheduleManager.cc [hunk 15]
```diff
@@ -216,17 +216,22 @@ namespace Sched {
...
         auto const &s_sched = state.dataSched;
+        auto const &s_glob = state.dataGlobal;
 
         auto *sched = new ScheduleConstant;
         sched->Name = name;
+        sched->type = SchedType::Constant;
         sched->Num = (int)s_sched->schedules.size();
+        sched->currentVal = value;
+        // When InitConstantScheduleData is called, TimeStepsInHour is 0, so we ensure 24
+        sched->tsVals.assign(Constant::iHoursInDay * max(1, s_glob->TimeStepsInHour), value);
```
Comment (Myoldmopar) [inline src/EnergyPlus/ScheduleManager.cc:230]: Seems like a reasonable improvement to protect the setup of this stuff in unit testing.

File: src/EnergyPlus/ScheduleManager.cc [hunk 16]
```diff
@@ -280,14 +285,12 @@ namespace Sched {
     {
         // Create ScheduleAlwaysOn and ScheduleAlwaysOff
         // Create constant schedules
-        auto *schedOff = AddScheduleConstant(state, "Constant-0.0");
+        auto *schedOff = AddScheduleConstant(state, "Constant-0.0", 0.0);
```
Comment (Myoldmopar) [inline src/EnergyPlus/ScheduleManager.cc:288]: Yeah this is a nice tiny tweak.

**Review by Myoldmopar — APPROVED** [review]
All good here.  This turned out to be really clean.  Thanks @jmarrec and @amirroth

**Comment by Myoldmopar** [comment]
This one is all clean, ready to go in.  Thanks!

File: src/EnergyPlus/ScheduleManager.cc (hunk 15 above)
Comment (amirroth) [reply src/EnergyPlus/ScheduleManager.cc:230]: I don’t think this is robust. The IDF file will probably set the TimeStep to something greater than 1, at which point the simulation may want to grab values at indices that don’t exist in this array. This array should be resized after the actual time step of the simulation is known.

**Comment by shorowit** [comment]
> This is the thing about EnergyPlus that seems weird and counter-intuitive to you? Not the fact that we are in this rabbit hole because you can use an EMS _sensor_ to change a schedule value?

FWIW, the sensor is not used to change the schedule value, it's to perform a calculation in an EMS program based on the schedule value and actuate something else. Depending on inputs to our software, the schedule may or may not be constant, so we kept out code simple by using a sensor on the schedule in either situation.

File: src/EnergyPlus/ScheduleManager.cc (hunk 15 above)
Comment (jmarrec) [reply src/EnergyPlus/ScheduleManager.cc:230]: 1) In the GetInput routine, it will be resized.
2) Unit tests that would have this issue would be a) no GetInput called and b) A call to getDayVals is happening

Comment (amirroth) [reply src/EnergyPlus/ScheduleManager.cc:230]: Ok, as long as there is no vulnerability in EnergyPlus itself and the GetInput resize seems to take care of that! Thanks.
