### PR TITLE
Retrieve correct runtime fraction for `AirLoopHVAC:UnitaryHeatCool` to be used by AFN

### LINKED ISSUE #11363: Increased duct leakage result in decrease in heating energy use in cold climate
### Issue overview

The attached models (single-family home with a crawlspace and an attic) use an airflow network to model the impact of HVAC system distribution leaks. The HVAC system uses a cycling fan to meet the loads, and ventilation air is not provided by the system. The only difference between the cases is the effective leakage ratio input specified in the `AirflowNetwork:Distribution:Component:LeakageRatio` object, which is used to model air leakage from the crawlspace to the return side of the distribution system. The "baseline2" case assumes virtually no leakage, while the "baseline3" case assumes a high level of leakage.

Simulation results indicate that the high leakage case ("baseline3") uses less heating energy than the no-leakage case when simulated in Boise, ID. This outcome appears counterintuitive, if not incorrect.
The simulation output further reveals that, in the high leakage case ("baseline3"), the infiltration ACH for the only conditioned zone in the model is significantly lower than in the no-leakage case. To some degree, this reduction is expected, as introducing air from the crawlspace into the zone increases the pressure in the zone, thereby reducing infiltration. However, the observed difference in infiltration between the two cases seems disproportionately large and not well correlated with the fan operation (low or no fan operation should show infiltration rate that are similar).

In the figure below, the zone infiltration flow rates for the two models are shown on the top panel—blue represents the case with no leakage, while orange represents the case with leakage. The bottom panel illustrates the conditioned zone's average pressure (PLR-weighted average of zone pressure during on/off cycling operations)—dark green corresponds to the case with no leakage, and light green corresponds to the case with leakage. The chart also displays the total zone pressure for the high leakage case. For the no-leakage case, the average pressure is equal to the total pressure (as shown in the last figure below).

Focusing on the simulation period highlighted within the black rectangle, we observe that the average zone pressures in the two cases are nearly identical. Hence, one would expect the infiltration flow rates to be similar; however, as shown in the top panel, the flow rates differ substantially.

Image

If we plot the infiltration sensible losses during that time, we can observe the same trend: when the average zone pressures are nearly identical, the case with no leakage exhibits higher sensible losses compared to the case with high leakage.

Image

It seems that the infiltration ACH/sensible losses are more closely correlated with the total zone pressure rather than the average node pressure.

Image

### Operating System (Multiple choices)

MacOS

### Operating System Version

15.7.2

### Version of EnergyPlus

25.2

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[baseline2.idf.zip](https://github.com/user-attachments/files/24042432/baseline2.idf.zip)

[baseline3.idf.zip](https://github.com/user-attachments/files/24042433/baseline3.idf.zip)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11363

### Description of the purpose of this PR

The defect files highlighted two issues:

1. The maximum heating runtime fraction (RTF) used by the airflow network to calculate the impact of cycling fan operations, when using an `AirLoopHVAC:UnitaryHeatCool` furnace-type system, is currently determined by the heating coil code. However, during the furnace simulation, the furnace's full load output is calculated with the heating coil's `RTF == 1`. As a result, the maximum heating RTF is always set to 1 for the airflow network calculations, which does not appropriately capture the impact of cycling fan operations.
2. The `AirLoopHVAC:UnitaryHeatCool` nominal capacity does not account for the `Sizing:System`'s `Fraction of Autosized Heating Design Capacity` when the `Heating Design Capacity Method` is set to `FractionOfAutosizedHeatingCapacity`, whereas the heating coil does.

This pull request fixes both issues.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If structural output changes, add to output rules file and add OutputChange label

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 1]
```diff
@@ -6269,6 +6269,13 @@ namespace AirflowNetwork {
                                 OutputProcessor::TimeStepType::System,
                                 OutputProcessor::StoreType::Sum,
                                 Zone(i).Name);
+            SetupOutputVariable(m_state,
+                                "AFN Zone Infiltration Mass Flow Rate",
+                                Constant::Units::kg_s,
+                                AirflowNetworkZnRpt(i).infilMassFlow,
+                                OutputProcessor::TimeStepType::System,
+                                OutputProcessor::StoreType::Average,
+                                Zone(i).Name);
```
Comment (lymereJ) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:6278]: Add a new output variable so users don't have to manually calculate the mass flow rate from the ACH.

File: src/EnergyPlus/Furnaces.cc [hunk 2]
```diff
@@ -6273,6 +6319,12 @@ namespace Furnaces {
                     CheckSysSizing(state, HVAC::unitarySysTypeNames[(int)thisFurnace.type], thisFurnace.Name);
 
                     thisFurnace.DesignHeatingCapacity = state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).HeatCap;
+                    if (state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).FractionOfAutosizedHeatingCapacity > 0) {
+                        // apply sizing factor and reset it to 1.0 so it doesn't get apply again during heating coil sizing
+                        thisFurnace.DesignHeatingCapacity *=
+                            state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).FractionOfAutosizedHeatingCapacity;
+                        state.dataSize->FinalSysSizing(state.dataSize->CurSysNum).FractionOfAutosizedHeatingCapacity = 1.0;
+                    }
```
Comment (lymereJ) [inline src/EnergyPlus/Furnaces.cc:6333]: System size is determined first, then heating coil size is determined after. In the former, the `FractionOfAutosizedHeatingCapacity` is not taken into account when sizing the system, but it is when sizing the coil. If the coil is part of a system, the system size is used for the coil and is modified by `FractionOfAutosizedHeatingCapacity`. Here we're applying `FractionOfAutosizedHeatingCapacity` to the system size and reset to 1 so it doesn't get used again to size the heating coil.

With `develop`:
```
 Component Sizing Information, AirLoopHVAC:UnitaryHeatCool, ACANDF_UNIT1, Nominal Heating Capacity [W], 8519.83583
 Component Sizing Information, Coil:Heating:Fuel, MAIN FUEL HEATING COIL_UNIT1, Design Size Nominal Capacity [W], 10649.79479
```
With this branch:
```
 Component Sizing Information, AirLoopHVAC:UnitaryHeatCool, ACANDF_UNIT1, Nominal Heating Capacity [W], 10649.79479
 Component Sizing Information, Coil:Heating:Fuel, MAIN FUEL HEATING COIL_UNIT1, Design Size Nominal Capacity [W], 10649.79479
```

File: src/EnergyPlus/Furnaces.cc [hunk 3]
```diff
@@ -213,6 +213,12 @@ namespace Furnaces {
             state.dataFurnaces->GetFurnaceInputFlag = false;
         }
 
+        // Save the current AFNLoopHeatingCoilMaxRTF for comparison with the one calculated below
+        Real64 refAFNLoopHeatingCoilMaxRTF(0.0);
+        if (state.afn->distribution_simulated) {
+            refAFNLoopHeatingCoilMaxRTF = state.dataAirLoop->AirLoopAFNInfo(AirLoopNum).AFNLoopHeatingCoilMaxRTF;
+        }
+
```
Comment (lymereJ) [inline src/EnergyPlus/Furnaces.cc:221]: Save the maximum RTF that may have been previously determined from another component and use it later to determine the actual maximum RTF.

File: src/EnergyPlus/Furnaces.cc [hunk 4]
```diff
@@ -660,6 +666,42 @@ namespace Furnaces {
...
+                }
+            }
+            if (errorFound) {
+                ShowSevereError(state, format("The index of \"{}\" is not found", thisFurnace.SuppHeatCoilName));
+                ShowContinueError(state, format("...occurs for {}", thisFurnace.Name));
+                errorFound = false;
+            }
+            state.dataAirLoop->AirLoopAFNInfo(AirLoopNum).AFNLoopHeatingCoilMaxRTF =
+                max(refAFNLoopHeatingCoilMaxRTF, heatingCoilRTF, suppHeatingCoilRTF);
+        }
```
Comment (lymereJ) [inline src/EnergyPlus/Furnaces.cc:710]: Set the maximum RTF at the furnace level, overwriting the one calculated at the heating coil level (`==1`).

File: tst/EnergyPlus/unit/Furnaces.unit.cc [hunk 5]
```diff
@@ -1219,6 +1220,713 @@ TEST_F(EnergyPlusFixture, UnitaryHeatPumpAirToAir_MaxSuppAirTempTest)
...
+
+    // Simulate furnace
+    state->dataZoneEnergyDemand->ZoneSysEnergyDemand(1).SequencedOutputRequiredToCoolingSP(1) = 25000.0;
+    SimFurnace(*state, state->dataFurnaces->Furnace(1).Name, FirstHVACIteration, AirLoopNum, CompIndex);
+
+    // Check that the runtime fraction is less than one so the impact of cycling fan is correctly accounted for in the AFN
+    EXPECT_TRUE(state->dataAirLoop->AirLoopAFNInfo(1).AFNLoopHeatingCoilMaxRTF < 1);
+
+    // Check that the system heating capacity is the same as the heating coil
+    EXPECT_NEAR(state->dataHeatingCoils->HeatingCoil(1).NominalCapacity, state->dataFurnaces->Furnace(1).DesignHeatingCapacity, 1e-6);
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/Furnaces.unit.cc:1927]: New unit test that checks for both fixes. `develop` fails both assertions.

**Review by lymereJ — COMMENTED** [review]
Code changes walk-through:

**Comment by lymereJ** [comment]
Here's a plot of the conditioned zone infiltration sensible heat loss: in blue is shown the case with no leakage and in maroon the original case with leakage, and in orange is the case with leakage but from this branch. As expected, we do see still difference with the case with no leakage, but much less.


image


Simulation results of the defect case now show that the case with increased leakage uses more heating energy than the case with no leakage.

Big diffs are only shown for `AirflowNetwork_MultiZone_House_OvercoolDehumid.idf` which has the same issue as the defect file, thus the diffs are expected.

File: src/EnergyPlus/Furnaces.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/Furnaces.cc:710]: This does make sense for a parent with multiple heating coils and either or both could operate.

File: src/EnergyPlus/Furnaces.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/Furnaces.cc:6333]: This looks better.

**Comment by rraustad** [comment]
I'm not sure your item 1 in the description captures the issue. The correction from [this comment](https://github.com/NREL/EnergyPlus/pull/11367#discussion_r2615243272) is more likely the reason. Since it's so hard to figure out what should happen with infiltration when there is duct leakage I guess just go with these changes. A reduction in infiltration losses does seem appropriate for a crawlspace duct leak.

File: src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp [hunk 6]
```diff
@@ -86,8 +86,9 @@ namespace AirflowNetwork {
     struct AirflowNetworkReportVars
     {
         // Members
-        Real64 InfilVolume;         // Volume of Air {m3} due to infiltration
-        Real64 InfilMass;           // Mass of Air {kg} due to infiltration
+        Real64 InfilVolume; // Volume of Air {m3} due to infiltration
+        Real64 InfilMass;   // Mass of Air {kg} due to infiltration
+        Real64 infilMassFlow;
```
Comment (mitchute) [inline src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp]: Suggest you add a comment here, even if it's obvious the intent, so the other comments line up.

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp (hunk 1 above)
Comment (mitchute) [reply src/EnergyPlus/AirflowNetwork/src/Solver.cpp:6278]: Looks ok

File: src/EnergyPlus/Furnaces.cc [hunk 7]
```diff
@@ -660,6 +666,42 @@ namespace Furnaces {
         // Report the current Furnace output
         ReportFurnace(state, FurnaceNum, AirLoopNum);
 
+        // Get the actual maximum RTF for AFN simulations
+        if (state.afn->distribution_simulated) {
+            Real64 heatingCoilRTF = 0.0;
+            Real64 suppHeatingCoilRTF = 0.0;
+            bool errorFound(false);
+            if (thisFurnace.HeatingCoilType_Num == HVAC::Coil_HeatingGasOrOtherFuel ||
```
Comment (mitchute) [inline src/EnergyPlus/Furnaces.cc]: switch/case here?

File: src/EnergyPlus/Furnaces.cc [hunk 8]
```diff
@@ -4761,7 +4807,7 @@ namespace Furnaces {
             // Pass the fan cycling schedule index up to the air loop. Set the air loop unitary system flag.
             state.dataAirLoop->AirLoopControlInfo(AirLoopNum).cycFanSched = thisFurnace.fanOpModeSched;
             state.dataAirLoop->AirLoopControlInfo(AirLoopNum).UnitarySys = true;
-            // RR this is wrong, Op mode needs to be updated each time atep
+            // RR this is wrong, Op mode needs to be updated each time step
```
Comment (mitchute) [inline src/EnergyPlus/Furnaces.cc]: @rraustad is this still wrong?

**Review by mitchute — COMMENTED** [review]
The code changes look OK, other than maybe using a switch/case at that one spot. I'll check the defect files over on https://github.com/NREL/EnergyPlus/issues/11363 now.

File: src/EnergyPlus/Furnaces.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/Furnaces.cc]: That's a very old comment. Down at line 5211 is this code when the fan operating mode schedule != nullptr. So fanOp is getting updated each time step to be used at the air loop level via AirLoopControlInfo. If fanOpModeSched == nullptr then this code (line 4811) will set the air loop fanOp once (after system sizing is complete, which is OK) and line 5211 will not execute. So this looks OK now (or my comment was incorrect way back then). This comment can be removed.

        if (thisFurnace.fanOpModeSched != nullptr) {
            thisFurnace.fanOp = (thisFurnace.fanOpModeSched->getCurrentVal() == 0.0) ? HVAC::FanOp::Cycling : HVAC::FanOp::Continuous;
            if (AirLoopNum > 0) {
                state.dataAirLoop->AirLoopControlInfo(AirLoopNum).fanOp = thisFurnace.fanOp;
            }
        }

File: src/EnergyPlus/Furnaces.cc (hunk 7 above)
Comment (lymereJ) [reply src/EnergyPlus/Furnaces.cc]: Made the change. Thanks.

File: src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp (hunk 6 above)
Comment (lymereJ) [reply src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp]: Added a comment.

**Review by mitchute — APPROVED** [review]
