### PR TITLE
Fix search for ReadVarsESO in installed package directory structure.

### LINKED ISSUE #5058: ReadVarsESO not found through CLI
When I run EnergyPlus through the CLI on Mac and pass in '-r' to "Run ReadVarsESO after simulation" it doesn't actually find the ReadVarsESO executable. I get the following error...

ERROR: Could not find ReadVarsESO executable: /Applications/EnergyPlus-8-3-0/ReadVarsESO.

That isn't the correct path for the ReadVarsESO executable, which is in PostProcess. If I create a symlink in the location where EnergyPlus is expecting the executable, I get the following error message instead...

sh: /Applications/EnergyPlus-8-3-0/ReadVarsESO: cannot execute binary file

I will also say the CLI is very finicky about where it is run from since it will sometimes work perfectly and other times it hangs while at "Processing Input File" until I hit ctrl-c to break the execution.

### PR DESCRIPTION
**Pull request by nealkruis**
Fixes #5058.

@mbadams5 are you able to review and merge?

### CODE REVIEW

File: src/EnergyPlus/EnergyPlusPgm.cc [hunk 1]
```diff
@@ -395,27 +395,31 @@ EnergyPlusPgm( std::string const & filepath )
...
-    if (runReadVars) {
+	if (runReadVars) {
 		std::string readVarsPath = exeDirectory + "ReadVarsESO" + exeExtension;
 		bool FileExists;
 		{ IOFlags flags; gio::inquire( readVarsPath, flags ); FileExists = flags.exists(); }
 		if (!FileExists) {
-			DisplayString("ERROR: Could not find ReadVarsESO executable: " + getAbsolutePath(readVarsPath) + "." );
-			exit(EXIT_FAILURE);
+			readVarsPath = exeDirectory + "PostProcess" + pathChar + "ReadVarsESO" + exeExtension;
+			{ IOFlags flags; gio::inquire( readVarsPath, flags ); FileExists = flags.exists(); }
```
Comment (mbadams5) [inline src/EnergyPlus/EnergyPlusPgm.cc:404]: @nealkruis I know you just did the same as above, but why use gio::inquire to see if a file exists versus [FileSystem::pathExists](https://github.com/NREL/EnergyPlus/blob/6ce1086aa810e9d47f9fd46fa7c3905b2968f45f/src/EnergyPlus/FileSystem.hh#L36)? And I guess this is a more general question since I did use [FileSystem::pathExists in my unit testing fixture](https://github.com/NREL/EnergyPlus/blob/6ce1086aa810e9d47f9fd46fa7c3905b2968f45f/tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc#L339) instead of gio::inquire. @Myoldmopar @kbenne

**Comment by nealkruis** [comment]
@mbadams5 that's fair. I will convert to FileSystem::fileExists().

**Comment by mjwitte** [comment]
@mbadams5 There are many other instances in other parts of the code that use gio::inquire to check if a file exists.  Seems we should be consistent everywhere.  What's the difference?  Any implications across platforms?

**Comment by nealkruis** [comment]
@DeadParrot any thoughts on this? `gio::inquire` might have a better design than my `FileSystem::fileExists`. 

@mjwitte There are several places where `gio::inquire` is used to check both the IO status and whether the file exists.

**Comment by mbadams5** [comment]
@nealkruis I will say that your [FileSystem::pathExists](https://github.com/NREL/EnergyPlus/blob/6ce1086aa810e9d47f9fd46fa7c3905b2968f45f/src/EnergyPlus/FileSystem.cc#L168) is almost the exact same (except for the Windows side) to [gio::file_exists](https://github.com/NREL/EnergyPlus/blob/6ce1086aa810e9d47f9fd46fa7c3905b2968f45f/third_party/ObjexxFCL/src/ObjexxFCL/gio.cc#L653). For this kind of checking if a file exists or not, I would personally lean to one of these two options instead of gio::inquire, but maybe @DeadParrot has a better response.

**Comment by Myoldmopar** [comment]
@mbadams5 @mjwitte @DeadParrot @nealkruis This is yet another blurry discussion.  

On one hand we have the Objexx code that is in place and being used throughout E+.  The pros of this are that @DeadParrot has had time to extensively unit test his functions, and they match the pattern used throughout the code.  The con is that it propagates Fortran-ic styles that might seem confusing for developers coming on board.  

On the other hand, we have the functions that @nealkruis brought in with the CLI.  The pros are that the opaque ifdef pattern is more likely to be familiar than the Objexx Fortran-ic interface.  I think the only con is really that it goes against the pattern used in the rest of the source.

We simply have to decide which one to use moving forward.  In this case, I will decide that we stick with GIO for 3 reasons:
- It matches the rest of the source, so that devs have a clear pattern to follow,
- if we decide to reduce our use of Objexx at some point, we will have a uniform starting point to perform at least semi-automated moving, and
- less code to maintain and worry about.

Hooray!  Flame it up! :fire:

**Comment by nealkruis** [comment]
@Myoldmopar agreed. I can deprecate `fileExists` in another branch.

**Comment by Myoldmopar** [comment]
Thanks @nealkruis.  While there is some overlap, I think there is functionality in FileSystem that isn't available in GIO directly, so no drastic changes right away.  But if we can get to a single solution over time, I think it would be better for the team.  

And as @mbadams5 points out to me, C++ is wanting to bring in Boost's filesystem work, so once we have all this in standard lib, that's where we'll go.

**Comment by nealkruis** [comment]
That's great to hear. For reference, this seems to be the proposed inclusion of the [Filesystem library](http://en.cppreference.com/w/cpp/experimental/fs) in the C++ standard. The status is mentioned [here](https://isocpp.org/std/status).

**Comment by DeadParrot** [comment]
I'm late to the party but long term it would be good to have file system options outside of ObjexxFCL::gio for a few reasons:
- gio is specifically emulating Fortran's _global_ files and we all know global is evil
- gio::inquire is one of the weaker parts of gio because it is tricky to emulate INQUIRE with C++. Boost has probably done a better and certainly more C++-ish approach
- Fortran's i/o system is clunky and emulating it in gio doesn't make it much less clunky (IOFlags is kind of nice though). A clean C++ OO design would be nicer for EnergyPlus. Things like the Stream hierarchy in ObjexxFCL or a Boost analog would be useful.

If we don't want to wait for Filesystem to be in C++ this might be a good excuse for letting Boost in the door. Or having a simple C++-ish file system namespace of our own might suffice: maybe a combination of what @nealkruis did and things cribbed from ObjexxFCL and Boost would a good start.

**Comment by Myoldmopar** [comment]
@nealkruis I merged develop in just to get rid of the stray S3 errors showing up previously.   If CI passes this, is this OK to go in, @mbadams5?

**Comment by Myoldmopar** [comment]
OK, I have updated and rebooted all of our CI machines, and they seem to be behaving a bit better.  I pulled develop in and hopefully that will clean up the CI results finally.

**Comment by mbadams5** [comment]
Now that CI machines have finally come back (more or less clean), I think this is good to go in.
