### PR TITLE
Fixes issue 10055 - If zone sizing is zero and system sizing is zero there is a fatal error leaving no information to help diagnose why

### LINKED ISSUE #10055: If zone sizing is zero and system sizing is zero there is a fatal error leaving no information to help diagnose why
Issue overview
--------------
A user file with a single conditioned zone, and only one design day, generates this error file, and the eio doesn't report zone sizing results when they are zero.
```
   ** Warning ** Calculated design cooling load for zone=THERMAL ZONE 1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=THERMAL ZONE 1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ************* Beginning System Sizing Calculations
   ** Warning ** ManageSizing: Calculated Cooling Design Air Flow Rate for System=AIR LOOP CLG TZ1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AIR LOOP CLG TZ1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Cooling Design Air Flow Rate for System=AIR LOOP HTG TZ1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AIR LOOP HTG TZ1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ************* Beginning Plant Sizing Calculations
   ** Severe  ** SizeAirLoopBranches: AirLoopHVAC AIR LOOP CLG TZ1 has air flow less than 1.0000E-003 m3/s.
   **   ~~~   ** Primary air system volumetric flow rate = 0.0000 m3/s.
   **   ~~~   ** Check flow rate inputs for components in this air loop and,
   **   ~~~   ** if autosized, check Sizing:Zone and Sizing:System objects and related inputs.
   **  Fatal  ** Previous condition causes termination.
```
Because this stops before running any simulations, it's difficult to diagnose why the zone design loads are zero.

In this case, there is a single design day at 23C outdoor dry bulb, no solar, and a thermostat cooling setpoint of 29.3C. At these conditions, the zone temperature never reaches 29.3C, so there is never any cooling load.

1. Can the fatal be removed and allow the simulation to run with the zero air loop flow rate? This would allow adding some output variables to see what's happening in the zone during the design day(s).
2. When zone sizing reports a zero load, are there some pertinent values that could be gleaned from the sizing seq data to help give a hint?

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 23.2.0-5d7c5ad03d
 - Helpdesk ticket 16324

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by KarenWGard**
Pull request overview
---------------------
 - Fixes #10055
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SimAirServingZones.cc [hunk 1]
```diff
@@ -4090,7 +4089,6 @@ void SizeAirLoopBranches(EnergyPlusData &state, int const AirLoopNum, int const
                               format("Primary air system volumetric flow rate = {:.4R} m3/s.", PrimaryAirSystems(AirLoopNum).DesignVolFlowRate));
             ShowContinueError(state, "Check flow rate inputs for components in this air loop and,");
             ShowContinueError(state, "if autosized, check Sizing:Zone and Sizing:System objects and related inputs.");
-            ShowFatalError(state, "Previous condition causes termination.");
```
Comment (KarenWGard) [inline src/EnergyPlus/SimAirServingZones.cc:4093]: remove the FatalError so that the simulation can continue.  Allowing the simulation to continue with 0 flow for the AirLoop is consistent with the way 0 flow at the PlantLoop is currently handled

File: tst/EnergyPlus/unit/SimAirServingZones.unit.cc [hunk 2]
```diff
@@ -1033,6 +1033,142 @@ TEST_F(EnergyPlusFixture, InitAirLoops_2AirLoop2ADU)
...
+    // Expect warnings about 0 airflow
+    std::string error_msg = delimited_string({
+        "   ** Severe  ** SizeAirLoopBranches: AirLoopHVAC VAV SYS 1 has air flow less than 1.0000E-003 m3/s.",
+        "   **   ~~~   ** Primary air system volumetric flow rate = 0.0000 m3/s.",
+        "   **   ~~~   ** Check flow rate inputs for components in this air loop and,",
+        "   **   ~~~   ** if autosized, check Sizing:Zone and Sizing:System objects and related inputs.",
+    });
+    EXPECT_TRUE(compare_err_stream(error_msg));
+}
+
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/SimAirServingZones.unit.cc:1171]: new unit test created to make sure the correct error is given when AirLoop flow is 0.

**Review by KarenWGard — COMMENTED** [review]
developper code review

File: src/EnergyPlus/SimAirServingZones.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/SimAirServingZones.cc:4093]: I agree with this. It's never good to stop the simulation just because loads were 0.

Comment (Myoldmopar) [reply src/EnergyPlus/SimAirServingZones.cc:4093]: I still feel like if we are handling the problem and continuing the simulation, that itself is a warning, not an error.  But I won't hold this up for that.  I agree that continuing the simulation itself is an improvement.

**Review by Myoldmopar — APPROVED** [review]
I'll check it out now and see if we can get this in.

**Comment by Myoldmopar** [comment]
CI was all happy when it ran last, just the compiler warnings that were present in develop at that time.  Everything builds happily and tests out fine locally now with develop pulled in, and this is getting merged now.  Thanks @KarenWGard
