### PR TITLE
Fix opaque cloud cover

### LINKED ISSUE #8760: Opaque Cloud Cover output problem in v9.5
Issue overview
--------------
For v9.5, a bug is spotted when outputting the Opaque Cloud Cover value. When selected the "Opaque Cloud Cover" as the output, the actual outputted value is the Total Cloud Cover, which has different physical meanings and also usually has different value (from Opaque Cloud Cover). 

The problem only occurs in v9.5. This feature of reporting Total Cloud Cover and Opaque Cloud cover values was added to v9.4 and it has been working fine in v9.4. However, some accidental changes happened after the v9.4 release, and altered the original working version. The route cause is an erroneous value assignment in weather manager that gets the Total Cloud Cover incorrectly assigned to Opaque Cloud Cover in the weather manager: 
```
        state.dataWeatherManager->TodayTotalSkyCover = state.dataWeatherManager->TomorrowTotalSkyCover;
        state.dataWeatherManager->TodayOpaqueSkyCover = state.dataWeatherManager->TomorrowTotalSkyCover;
```

This might indicate that it is be possible that some calculations that need Opaque Cloud Cover could also be affected by this erroneous value assignment. 

There is currently no workaround. A code change is needed to fix the problem. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.5 only
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added use1ZoneUncontrolled.idf from #8762.
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #8760
 - Added a new test unit
 - Modified two test files to include sky covers outputs

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WeatherManager.cc [hunk 1]
```diff
@@ -2035,7 +2035,7 @@ namespace WeatherManager {
         state.dataWeatherManager->TodayDifSolarRad = state.dataWeatherManager->TomorrowDifSolarRad;
         state.dataWeatherManager->TodayLiquidPrecip = state.dataWeatherManager->TomorrowLiquidPrecip;
         state.dataWeatherManager->TodayTotalSkyCover = state.dataWeatherManager->TomorrowTotalSkyCover;
-        state.dataWeatherManager->TodayOpaqueSkyCover = state.dataWeatherManager->TomorrowTotalSkyCover;
+        state.dataWeatherManager->TodayOpaqueSkyCover = state.dataWeatherManager->TomorrowOpaqueSkyCover;
```
Comment (Myoldmopar) [inline src/EnergyPlus/WeatherManager.cc:2038]: Yeah great fix!

File: testfiles/1ZoneUncontrolled.idf [hunk 2]
```diff
@@ -364,6 +364,10 @@
 
   Output:Variable,*,Site Outdoor Air Drybulb Temperature,hourly;
 
+  Output:Variable,*,Site Total Sky Cover,hourly;
+
+  Output:Variable,*,Site Opaque Sky Cover,hourly;
+
```
Comment (Myoldmopar) [inline testfiles/1ZoneUncontrolled.idf:370]: Ideally these would be added to the develop branch in a separate PR so you could see the diffs.  But that's a lot of extra work, and the fix here is pretty obvious.  Either way it's good to add them here at least.

File: tst/EnergyPlus/unit/WeatherManager.unit.cc [hunk 3]
```diff
@@ -1148,3 +1148,113 @@ TEST_F(EnergyPlusFixture, Add_and_InterpolateWeatherInputOutputTest)
...
+
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowTotalSkyCover(4, 4), expected_TSC, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowOpaqueSkyCover(4, 4), expected_OSC, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowTotalSkyCover(3, 4), 8.25, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowOpaqueSkyCover(3, 4), 8.00, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowTotalSkyCover(2, 4), 8.50, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowOpaqueSkyCover(2, 4), 8.00, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowTotalSkyCover(1, 4), 8.75, 1e-6);
+    EXPECT_NEAR(state->dataWeatherManager->TomorrowOpaqueSkyCover(1, 4), 8.00, 1e-6);
+}
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/WeatherManager.unit.cc:1260]: Nice. :+1:

**Review by Myoldmopar — APPROVED** [review]
These changes look good to me.  I will pull develop in locally, run regressions and the unit test suite.  I will also try to run the defect file (I haven't verified there is one...)

File: testfiles/1ZoneUncontrolled.idf (hunk 2 above)
Comment (jcyuan2020) [reply testfiles/1ZoneUncontrolled.idf:370]: Thanks! @Myoldmopar Since the testfiles' changes are in the last two commits, I can easily revert to the commit before the one before that (actually already did it locally and ready to push if needed). Then after merging of this one I can add back the two last ones in a new PR.

Comment (Myoldmopar) [reply testfiles/1ZoneUncontrolled.idf:370]: I don't think it's necessary.  This is an obvious fix, and adding the output variables to the IDFs is a nice bonus over the unit test.  I think this is already ready to go.  CI looks good too, with just the new output variables causing "diffs".  I still need to run it locally but I think it's good.

**Comment by Myoldmopar** [comment]
Thanks for this fix @jcyuan2020, merging.
