### PR TITLE
Fix the resource portion of end-use subcategory meter names in v9.3 to v9.4 transition

### LINKED ISSUE #8271: Followup Transitions for End-Use Subcategory Names
Issue overview
--------------
Follow up to #8240.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by dareumnam**
Pull request overview
---------------------
 - Fixes #8271 
 - The tricky part of this issue is that it is not about converting a whole meter name but about converting only a resource portion of end-use subcategory meter names, which makes report variables CSV file or a subroutine like [FixFuelTypes function](https://github.com/NREL/EnergyPlus/blob/258bfbd709ccbe822de446e57c1d0b5d995345c0/src/Transition/CreateNewIDFUsingRulesV9_3_0.f90#L1801-L1854) with SameString() not work. 
 - By adding ReplaceFuelNameWithEndUseSubcategory Subroutine, resource names that were fixed for this release 9.4.0 get converted.
   - Electric to Electricity
   - Gas to NaturalGas
   - FuelOil#1 to FuelOilNo1
   - FuelOil#2 to FuelOilNo2
 - Other resource names can also be added to this subroutine if needed.
 - Locally tested transitioning a v9.3 testfile that contains "Electric", "Gas", "FuelOil#1", and "FuelOil#2" in end-use subcategory meter names. 
[RefBldgSmallOfficeNew2004_Chicago_fixed.idf.txt](https://github.com/NREL/EnergyPlus/files/5236368/RefBldgSmallOfficeNew2004_Chicago_fixed.idf.txt)

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [X] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
Looks like @dareumnam has the solution in hand here.

RefBldgSmallOfficeNew2004_Chicago variables are changed as below:

| Old                                                      | New                                                         |
|----------------------------------------------------------|-------------------------------------------------------------|
| Output:Meter,Gas:Facility,HOURLY;                        | Output:Meter,NaturalGas:Facility,HOURLY;                    |
| Output:Meter,Heating:Gas,HOURLY;                         | Output:Meter,Heating:NaturalGas,HOURLY;                     |
| Output:Meter,InteriorEquipment:Gas,HOURLY;               | Output:Meter,InteriorEquipment:NaturalGas,HOURLY;           |
| Output:Meter,Water Heater:WaterSystems:Gas,HOURLY;       | Output:Meter,Water Heater:WaterSystems:NaturalGas,HOURLY;   |
| Output:Variable,*,Air System Fan Electric Energy,HOURLY; | Output:Variable,*,Air System Fan Electricity Energy,HOURLY; |

Transition now works on my local machine, whereas it failed on the last PR. 🤷‍♂️ .  Anything else to discuss here before it goes in?

File: src/Transition/CreateNewIDFUsingRulesV9_4_0.f90 [hunk 1]
```diff
@@ -126,6 +126,7 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
   CHARACTER(len=MaxNameLength) :: OutputDiagnosticsName
   CHARACTER(len=MaxNameLength), ALLOCATABLE, DIMENSION(:) :: OutputDiagnosticsNames
   LOGICAL :: alreadyProcessedOneOutputDiagnostic=.false.
+  INTEGER :: nE, nEC, nG, nNG, nFO, nFON
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV9_4_0.f90:129]: Minor detail - I think these could be declared in the Subroutine instead of here, but if no other changes are needed, and it's working, then OK.

File: src/Transition/CreateNewIDFUsingRulesV9_4_0.f90 [hunk 2]
```diff
@@ -1185,3 +1189,26 @@ SUBROUTINE CreateNewIDFUsingRules(EndOfFile,DiffOnly,InLfn,AskForInput,InputFile
   RETURN
 
 END SUBROUTINE CreateNewIDFUsingRules
+
+SUBROUTINE ReplaceFuelNameWithEndUseSubcategory(InOutArg, NoDiffArg)
```
Comment (mjwitte) [inline src/Transition/CreateNewIDFUsingRulesV9_4_0.f90:1193]: Nice solution!

**Review by mjwitte — APPROVED** [review]

**Comment by mitchute** [comment]
This is ready. Merging.

File: src/Transition/CreateNewIDFUsingRulesV9_4_0.f90 (hunk 1 above)
Comment (dareumnam) [reply src/Transition/CreateNewIDFUsingRulesV9_4_0.f90:129]: ~~Just moved and pushed again.~~ Oops, already merged. I was 4 mins late.
