### PR TITLE
Report some electricity usage in kW W or kWh in IP units options

### LINKED ISSUE #9988: Proper IP units for reporting lighting electricity rate and electricity usage (energy)
Issue overview
--------------
Following the discussion [here](https://github.com/NREL/EnergyPlus/issues/9952#issuecomment-1527825033), it seems that currently in the html and sql reports, the IP (Imperial) lighting electricity rate is reported in `Btu/hr-ft2` in places where they correspond to a SI (International) `W/m2` if an "inchpound" unit conversion is used. However, the convention, especially in specifying the sizing or design level for lighting in IP unit system, the more appropriate unit to report lighting electricity levels should be `W/ft2` instead.  Basically this will involve making a few changes (or exceptions) for the "inchpound" unit conversion option in the output control table style.

This also brings up an issue on what is more appropriate a unit for reporting lighting electricity energy usage, and also the electricity usage in general (in SI this is usually `J`, `GJ`, or `kWh`). Currently, the electricity usages in most of the places in the html and sql reports, IP unit system electricity energy usage (and for most of the lighting electricity usages as well) is reported in `kBtu`. It seems that using `kWh` would be for what's typically shown in a typical electricity utility bill, where the electricity energy would still be `kWh` in most cases. So probably some investigation or discussions might be needed to determine a possibly better (or more convenient) IP units for electricity energy usages in the reports.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v23.1 and earlier versions as well
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Tries to fix #9988 
 - Keeps some electricity usage in reporting with IP-Unit system options to still being report in kW or KWh
 - A new unit convertion choice named InchPoudExceptElectricity are added for tabular and SQL outputs. With the option, the electricity usage are presented in kWh in an inch-pound environment (and some electricity power rates W)---this is more closely aligned with the usual conventions found in utility bills.
- Separating the predefined tables are generally a challenged to do at this stage; therefore they are not specifically adjusted  this change since the information is too granule to capture if it is electric usage---and some of them are electric type but in some occurrences—e.g. sizing, it is arguable to say if this should be kept using Watt or should it be converted to the IP equivalent. However, they are already some built-in unit conversion mechanism capability with regular InchPound unit conversion choice (e.g. based on heading texts) ---the new choice of InchPoundExceptElectricity also inherited the same treatment method. 

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/OutputReportTabular.cc [hunk 1]
```diff
@@ -1412,6 +1412,8 @@ UnitsStyle SetUnitsStyleFromString(std::string const &unitStringIn)
         unitsStyleReturn = UnitsStyle::JtoGJ;
     } else if (UtilityRoutines::SameString(unitStringIn, "INCHPOUND")) {
         unitsStyleReturn = UnitsStyle::InchPound;
+    } else if (UtilityRoutines::SameString(unitStringIn, "INCHPOUNDEXCEPTELECTRICITY")) {
+        unitsStyleReturn = UnitsStyle::InchPoundExceptElectricity;
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc]: May as well delete `SetUnitsStyleFromString` and use `getEnumValue` here.

**Review by mjwitte — COMMENTED** [review]
So, if I'm following correctly, there's no change to the existing InchPound conversions, but instead a new option InchPoundExceptElectricity has been added. InchPound does make some exceptions already for electricity. Do we need a new option, or do we just need to add a few more exceptions to InchPound?

Using 5ZoneAirCooled, this table is not converting every value correctly with InchPoundExceptElectricity.
image

In the  Input Verification and Results Summary, do we want Lighting to be in W/ft2?
and Plug and Process Loads? These could be all electricity, or a mix or fuel types, so unless we make a new column just for ElectricEquipment, we can't sort that out here.

Should [W] be [kW]? e.g. Demand End Use Components Summary.

In the Initialization Summary, Zone Internal Gains Nominal, Lighting and Electric load are still Btu/h-ft2.  Same for Lights Internal Gains Nominal and ElectricEquipment Internal Gains Nominal subtables.

 Lighting Summary?

The Energy Meters report already shows Electricity in kWh for InchPound.

in LEED Summary, Performance Rating Method Compliance subtable, the electricity columns are already in W for InchPound. With InchPoundExceptElectricity, the values are wrong.
Energy Use Summary subtable, values change, but headings don't. Same for Energy Use Intensity - Electricity.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 1 above)
Comment (jcyuan2020) [reply src/EnergyPlus/OutputReportTabular.cc]: @mjwitte Some general answers for now: 

Yes, the original InchPound option does have some capability to do something different (e.g. kW) for electricity---this is based on the string sent in to convert in a couple of special convert functions. However, there are a couple of limitations in the original code: 1). To do this, the code needs to call a special (or two) function call rather than plain conversion; 2). and this is not applied consistently across the report, e.g. in a few large reports such as the end use reports.

I think some of the "unconverted" ones might be in pre-defined tables (see a note in the past paragraph of the top comment) (or this could be some missing ones that could be specially treated in `InchPoundExceptElectrcity` option. For pre-defined tables, it is a little bit (or actually quite difficult) to do something specially for a particular unit in the tabular output section, except that the original `InchPound` way (string based identification for some kW) can be applied (and was already applied in the original code) to do the conversion for electricity. The `InchPoundExceptElectricity` option would just inherit the same treatments as the plain `InchPound` option. Also, for predefined table (or wherever this is applicable), the conversion were be 100 percent correct since it is based on search for a couple of special substrings (like `elec` or `light` etc).

During the development, I realized this issue later in the development process after some more understanding on what the code does. A few thoughts were given to this and it could make the implementation slightly different---for example, this mechanism maybe applied to a few deferent places---but still not 100 percent effective. On the other hand, the InchPoundExceptElectricty option does explicitly do the electricty kW conversion in some tables (e.g. notable ones might be end use, end use sub, and source use tables etc).

**Comment by jcyuan2020** [comment]
> So, if I'm following correctly, there's no change to the existing InchPound conversions, but instead a new option InchPoundExceptElectricity has been added. InchPound does make some exceptions already for electricity. Do we need a new option, or do we just need to add a few more exceptions to InchPound?

The new InchPoundExceptElectricity option does do something that the other options does not, especially for a few major end use tables. The original InchPound has a few mixed treatment methods including treating predefined entries automatically, but for the few major tables the kBtu type unit is used. It looks like that right now it is hard to go backward one step to keep the `InchPound` and the new `InchPoundExceptElectricity` cleanly distinugish to each other for everything.

 I think for now the principle I am trying to use is the following: within the current PR, I am trying to keep the original options untouched (JtoKWH to InchPound)---so they would behave exactly the same as before; the changes occurs only when the new InchPoundExceptElectricity option is chose.

There could some strength of the auto-conversion in the regular InchPound (so as well applied to InchPoundExceptElectricity)---this would help with a few of items to be discussed below. But rather that would cause significant diffs to show up and I would test out in a new PR for that. 

> Using 5ZoneAirCooled, this table is not converting every value correctly with InchPoundExceptElectricity. 
This table is now correctly converted.

> In the Input Verification and Results Summary, do we want Lighting to be in W/ft2? and Plug and Process Loads? These could be all electricity, or a mix or fuel types, so unless we make a new column just for ElectricEquipment, we can't sort that out here.

I agree and this change has been applied now. I looked at the IP version ASHRAE 90.1 2018 version and it looks that the lighting and equipment plug load are given in W/ft2; also for internal load data source the standard cited there, it shows that "misc. Load" given in W/f2:
image

> Should [W] be [kW]? e.g. Demand End Use Components Summary.

Yes. This now converted---kW seems to the counterpart for kBtu/h used for the other resources.
 
> In the Initialization Summary, Zone Internal Gains Nominal, Lighting and Electric load are still Btu/h-ft2. Same for Lights Internal Gains Nominal and ElectricEquipment Internal Gains Nominal subtables.

This actually finally got processed by the predefined table--so that's the automatic conversion part. 

> Lighting Summary?

Same here predefined tables and automatic conversion. 

One possible way to deal with some of the Btu/h-ft2 is to add a conversion rule for the auto-conversion. But this would also affect regular `InchPound` option (and would expect many diffs), which I would like to try in another PR instead.

> The Energy Meters report already shows Electricity in kWh for InchPound.

Yes---auto-convervted as well. So I think it would be good to just inherit the treatment from regular InchPound. For regular InchPound, I would leave this as is---reverting anything will actually be a big change.

> in LEED Summary, Performance Rating Method Compliance subtable, the electricity columns are already in W for InchPound. With InchPoundExceptElectricity, the values are wrong. Energy Use Summary subtable, values change, but headings don't. Same for Energy Use Intensity - Electricity.

The `Energy Use Intensity - Electricity` subtable is fixed. However, we have some complication for "Energy Use Summary" here in that with different units in the new `InchPoundExceptElectricity` option, the table rows cannot be added to get the last row---we have to give up something here:
image

**Comment by jcyuan2020** [comment]
@mjwitte @Myoldmopar It is suggested to merge PR #10261 before the current PR. It will help checking the changes in this PR in general.

**Comment by mjwitte** [comment]
@Myoldmopar This is ready for your review.

**Comment by nrel-bot-3** [comment]
@Myoldmopar @jcyuan2020 @myoldmopar it has been 28 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@jcyuan2020 I pulled this branch and started resolving conflicts, but they became a little more than I was expecting.  Could you take a pass at pulling develop in and resolving them?  They will likely be super easy since you were the one making these changes.  If you aren't able to, I'll give it another dedicated pass.  Thanks!

**Comment by jcyuan2020** [comment]
@Myoldmopar  Sure. I am starting to get these resolved.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 2]
```diff
@@ -7823,16 +7826,17 @@ void WriteBEPSTable(EnergyPlusData &state)
 
         // convert units into GJ (divide by 1,000,000,000) if J otherwise kWh
         for (int iResource = 1; iResource <= 13; ++iResource) { // don't do water
+            Real64 ipElectricityAdjust = (iResource == 1) ? ipElectricityConversionFactor : 1.0;
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:7829]: OK, so here is where we are adjusting it for electricity or not.  The iResource as 1 and 13 look.....funny.  Is there really not a named enum we can use for (iResource == 1) ?

File: src/EnergyPlus/OutputReportTabular.cc [hunk 3]
```diff
@@ -3354,7 +3345,7 @@ void WriteTableOfContents(EnergyPlusData &state)
                         for (int jTable = 1; jTable <= ort->OutputTableBinned(iInput).numTables; ++jTable) {
                             int const curTable = ort->OutputTableBinned(iInput).resIndex + (jTable - 1);
                             std::string curName;
-                            if (ort->unitsStyle == UnitsStyle::InchPound) {
+                            if ((ort->unitsStyle == UnitsStyle::InchPound) || (ort->unitsStyle == UnitsStyle::InchPoundExceptElectricity)) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:3348]: This repeated pattern is probably fine.  I'm inclined to say you could add a little worker method to the ort class to clean this code up.  Consider this example:

```
#include <iostream>

enum class UnitsStyle {InchPound, InchPoundExceptElectricity, SI};

struct ORT {
    UnitsStyle unitsStyle;
    ORT(UnitsStyle us) : unitsStyle(us) {}
    bool ip() const {
        return this->unitsStyle == UnitsStyle::InchPound || this->unitsStyle == UnitsStyle::InchPoundExceptElectricity;
    }
};

int main() {
    ORT ort1(UnitsStyle::InchPound);
    std::cout << ort1.ip() << std::endl;
    ORT ort2(UnitsStyle::InchPoundExceptElectricity);
    std::cout << ort2.ip() << std::endl;
    ORT ort3(UnitsStyle::SI);
    std::cout << ort3.ip() << std::endl;
}
```

That way all of these if checks would just be replaced with:

```
if (ort->ip()) {
```

Which is a lot less to digest.  Notes:

- I didn't look up the actual ort struct name, that's just a quick example
- I'm not saying `ip` is really the right function name, just a quick guess 

Do you think this change is worth it here?

File: tst/EnergyPlus/unit/OutputReportTabular.unit.cc [hunk 4]
```diff
@@ -13144,3 +13141,474 @@ TEST_F(EnergyPlusFixture, OutputReportTabular_Test_SetupUnitConversion_Fix)
...
+    }
+
+    {
+        std::string query("SELECT Value From TabularDataWithStrings"
+                          "  WHERE TableName = 'End Uses'"
+                          "  AND ReportName = 'DemandEndUseComponentsSummary'"
+                          "  AND RowName = 'Heating'");
+        auto result = queryResult(query, "TabularDataWithStrings");
+
+        ASSERT_EQ(14u, result.size()) << "Failed for query: " << query;
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/OutputReportTabular.unit.cc:13615]: Some of this testing feels unrelated, but maybe I'm missing something.  Anyway, it looks like at least some of the rates are being compared properly, so I'll take it.

**Review by Myoldmopar — COMMENTED** [review]
OK, so this is almost all good.  I had two comments that you can respond to, either in reply, or code changes:
- I dislike the magic number 1 being used in the electricity detection.  Do we not have a named variable that already points to the electricity resource type?  I'd love to have that dynamically defined so that if we ever change the resource type numbers, it won't break that calculation.
- With the many repeated checks on `if (ip or ip_except_elec)` being added in ORT, I feel like it's worth doing it as nicely as possible.  In this case, I do think a worker method would be a very nice touch.  Let me know what you think.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 3 above)
Comment (jcyuan2020) [reply src/EnergyPlus/OutputReportTabular.cc:3348]: I think I got the idea here. Probably worth a try---except the "ORT" struct name could be a little bit confusing here as there are many similar names of "ort" or something alike that are already used in this(these) file(s).

Comment (Myoldmopar) [reply src/EnergyPlus/OutputReportTabular.cc:3348]: The ORT is just a dummy name I put in that sample code.  Take the `ort` variable...it is some type.  Is it an instance of a `struct OutputReportTabular`?  If so, then my example is meant to add a method as such:

```
struct OutputReportTabular {
  bool ip() const {
    /// etc.
  }
}
```

Basically - add the new method to whatever struct the `ort` variable is.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 2 above)
Comment (jcyuan2020) [reply src/EnergyPlus/OutputReportTabular.cc:7829]: I do feel that using enums (or values converted from enum to int) should be the way to go in general. However I would also tread with caution for now, for two reasons. 1. from the original definition, it has a mix of number 14 and EndUse:Num (which is also 14). This means that there are some initial activities started on changing this to use enum already---but probably not complete for some reasons (probably due to the complexity in this piece of code?):
image

2. There are some mapping which is not perfectly aligned for the index e.g. from 1 (electricity) ->1; 2->2, demonstrated in the following lines: 
image

There you can observe that the index mapping from one vector (left) to that for the other vector (or multi-dim array/vector) is not completely aligned. There are 3->6; 4-8, and 5->9; and more.  There are at least a few more blocks that look like this.

This in one hand probably does mean that using enum could be a better solution for some scenarios in this big file. But on the other hand, it also added complexity to go over the code to make sure at each these are done correctly for all of them. 

Probably it would be an overall effort of refactoring the numbers like this in this file to enum. (I think @amir at some point also mentioned about this last year). I generally feel this undertake might be a separate refactoring pr or something like that.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 5]
```diff
@@ -1414,20 +1414,11 @@ void GetInputTabularStyle(EnergyPlusData &state)
...
-    } else if (Util::SameString(unitStringIn, "JTOMJ")) {
-        unitsStyleReturn = UnitsStyle::JtoMJ;
-    } else if (Util::SameString(unitStringIn, "JTOGJ")) {
-        unitsStyleReturn = UnitsStyle::JtoGJ;
-    } else if (Util::SameString(unitStringIn, "INCHPOUND")) {
-        unitsStyleReturn = UnitsStyle::InchPound;
-    } else {
+    UnitsStyle unitsStyleReturn = static_cast<UnitsStyle>(getEnumValue(UnitsStyleNamesUC, Util::makeUPPER(unitStringIn)));
+    if (unitsStyleReturn == UnitsStyle::Invalid) {
         unitsStyleReturn = UnitsStyle::NotFound;
```
Comment (amirroth) [inline src/EnergyPlus/OutputReportTabular.cc:1419]: Why not just replace uses of `NotFound` with `Invalid`?

File: src/EnergyPlus/OutputReportTabular.cc [hunk 6]
```diff
@@ -7867,22 +7871,22 @@ void WriteBEPSTable(EnergyPlusData &state)
...
         // convert to GJ
-        ort->gatherPowerFuelFireGen /= largeConversionFactor;
-        ort->gatherPowerPV /= largeConversionFactor;
-        ort->gatherPowerWind /= largeConversionFactor;
-        ort->gatherPowerHTGeothermal /= largeConversionFactor;
-        ort->gatherPowerConversion /= largeConversionFactor;
-        ort->gatherElecProduced /= largeConversionFactor;
-        ort->gatherElecPurchased /= largeConversionFactor;
-        ort->gatherElecSurplusSold /= largeConversionFactor;
+        ort->gatherPowerFuelFireGen /= (largeConversionFactor / ipElectricityConversionFactor);
```
Comment (amirroth) [inline src/EnergyPlus/OutputReportTabular.cc:7874]: The compiler is going to do this for you anyway, but for readability you should probably define `Real64 convFactor = ipElectricityConversionFactor / largeConversionFactor;`. At that point you could also multiply rather than divide which is both faster and higher bandwidth, i.e., the processor has more multipliers than dividers because multiplication is common and also each multiplier is faster than each divider.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 7]
```diff
@@ -8426,6 +8438,22 @@ void WriteBEPSTable(EnergyPlusData &state)
             columnHead(13) = "District Heating Steam [kBtu]";
             columnHead(14) = "Water [gal]";
         } break;
+        case UnitsStyle::InchPoundExceptElectricity: {
+            columnHead(1) = "Electricity [kWh]";
```
Comment (amirroth) [inline src/EnergyPlus/OutputReportTabular.cc:8442]: I'm going to have to do something about this. Not today though.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 8]
```diff
@@ -10114,34 +10227,40 @@ void WriteDemandEndUseSummary(EnergyPlusData &state)
...
-            collapsedEndUse(6, jEndUse) = ort->gatherDemandEndUse(10, jEndUse) * powerConversion;  // fuel oil no 1
-            collapsedEndUse(7, jEndUse) = ort->gatherDemandEndUse(11, jEndUse) * powerConversion;  // fuel oil no 2
-            collapsedEndUse(8, jEndUse) = ort->gatherDemandEndUse(12, jEndUse) * powerConversion;  // propane
-            collapsedEndUse(9, jEndUse) = ort->gatherDemandEndUse(13, jEndUse) * powerConversion;  // otherfuel1
-            collapsedEndUse(10, jEndUse) = ort->gatherDemandEndUse(14, jEndUse) * powerConversion; // otherfuel2
-            collapsedEndUse(11, jEndUse) = ort->gatherDemandEndUse(3, jEndUse) * powerConversion;  // purchased cooling
-            collapsedEndUse(12, jEndUse) = ort->gatherDemandEndUse(4, jEndUse) * powerConversion;  // district heating water
-            collapsedEndUse(13, jEndUse) = ort->gatherDemandEndUse(5, jEndUse) * powerConversion;  // district heating steam
-            collapsedEndUse(14, jEndUse) = ort->gatherDemandEndUse(7, jEndUse) * flowConversion;   // water
+            collapsedEndUse(1, jEndUse) = ort->gatherDemandEndUse(1, jEndUse) * (powerConversion / ipElectricityConversion); // electricity
```
Comment (amirroth) [inline src/EnergyPlus/OutputReportTabular.cc:10245]: You don't need to fix this now but this 1, 2, 6, 8 business is not good. At all.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 2 above)
Comment (amirroth) [reply src/EnergyPlus/OutputReportTabular.cc:7829]: The `EndUse::Num` stuff is from me, from the `EndUse` refactor PR. I didn't do the entire file (which is enormous) only the loops that I actually changed.

Similarly, I am not suggesting you do this as part of this PR. This should probably be a separate effort. 

But it *should* be an effort because new people are going to need to add to and modify this module and they will also need to learn what all of these numbers mean. It's bad coding practice to use numbers instead of `enum` values, which have meaning that you don't have to  look up. It's a form of self-documentation. Same reason for using meaningful names for variables and functions.

**Comment by Myoldmopar** [comment]
This isn't quite right.  I'll fix it up in the morning.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 5 above)
Comment (jcyuan2020) [reply src/EnergyPlus/OutputReportTabular.cc:1419]: That could be from the legacy---`NotFound` was the original way of dealing with blacks or something invalid before the `enum` ear and here it was assigned to a higher value (than all valid entries). Then `Invalid` becomes the standard values to be included in an `enum` as -1. Probably it is time to revisit again to see--actually I do find a note three years ago (likely from me myself) about the use of `NotFound` and seemed to have some reason to keep it at that time: 
image

File: src/EnergyPlus/OutputReportTabular.cc (hunk 6 above)
Comment (jcyuan2020) [reply src/EnergyPlus/OutputReportTabular.cc:7874]: Thanks! A good point to use multiplication whenever possible.

File: src/EnergyPlus/OutputReportTabular.hh [hunk 9]
```diff
@@ -970,6 +973,11 @@ struct OutputReportTabularData : BaseGlobalStruct
 {
 
     OutputReportTabular::UnitsStyle unitsStyle = OutputReportTabular::UnitsStyle::None;
+    bool ip() const
+    {
+        return this->unitsStyle == OutputReportTabular::UnitsStyle::InchPound ||
+               this->unitsStyle == OutputReportTabular::UnitsStyle::InchPoundExceptElectricity;
+    }
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.hh:980]: @jcyuan2020 this is what I meant.  Add a member method to the existing ort-based structure, not adding a whole new struct.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 10]
```diff
@@ -5536,7 +5527,7 @@ void FillWeatherPredefinedEntries(EnergyPlusData &state)
             lnPtr = index(lineIn.substr(12), 'm');
             if (lnPtr != std::string::npos) {
                 curNameWithSIUnits = "Elevation (m) " + lineIn.substr(12 + lnPtr + 2);
-                if (ort->unitsStyle == UnitsStyle::InchPound) {
+                if (ort->ip()) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:5530]: This is what I wanted it to look like.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 11]
```diff
@@ -7069,7 +7060,8 @@ void WriteMonthlyTables(EnergyPlusData &state)
                         curAggString = " {" + stripped(curAggString) + '}';
                     }
                     // do the unit conversions
-                    if (unitsStyle_cur == UnitsStyle::InchPound) {
+                    if (unitsStyle_cur == OutputReportTabular::UnitsStyle::InchPound ||
+                        unitsStyle_cur == OutputReportTabular::UnitsStyle::InchPoundExceptElectricity) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:7064]: Keep in mind though, that the ip() function only checks the value of unitsStyle defined currently on the ORT state instance.  So if you are comparing some other style, that function isn't the right one to use, so I just left these remaining ones as `if(thisUnitsStyle == A || thisUnitsStlye == B)`

**Review by Myoldmopar — APPROVED** [review]
Everything works locally, and the ip() function is fixed up.  It could be enhanced further for the remaining locations, but that can certainly come later.  If CI is happy with my last commit I think this can go right in.

**Comment by Myoldmopar** [comment]
Alright, merging this right in.  Thanks @jcyuan2020 and all reviewers.
