### PR TITLE
#11054 - Part 2 - Crash with schedule with missing day types

### LINKED ISSUE #11054: Crash with schedule with missing day types
### Issue overview

Schedule with missing day types generates warning in v24.2, crashes in v25.1.
```
  Schedule:Compact,
    WindowVentSched,         !- Name
    Any Number,              !- Schedule Type Limits Name
    Through: 12/31,          !- Field 1
    For: Monday Tuesday Wednesday Thursday Friday Saturday, !- Field 2
    Until: 8:30,0,           !- Field 3
    Until: 11:30,1,          !- Field 5
    Until: 12:00,0,          !- Field 7
    Until: 13:00,1,          !- Field 9
    Until: 19:00,0,          !- Field 11
    Until: 20:00,1,          !- Field 13
    Until: 24:00,0;          !- Field 15


Program Version,EnergyPlus, Version 24.2.0-94a887817b, YMD=2025.05.13 12:58,

   ** Warning ** ProcessScheduleInput: Schedule:Compact="WINDOWVENTSCHED" has missing day types in Through=12/31
   **   ~~~   ** Last "For" field=FOR: MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY
   **   ~~~   ** Missing day types="Sunday","Holiday","SummerDesignDay","WinterDesignDay","CustomDay1","CustomDay2"
   **   ~~~   ** Missing day types will have 0.0 as Schedule Values
```

Adding this to the schedule object fixes the crash:
```
    For: AllOtherDays, Until: 24:00, 0;
```

### Operating System (Multiple choices)

Any

### Operating System Version

any

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

Helpdesk ticket 16894

### Defect file

EnergyPlusDevSupport\DefectFiles\

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fixes #11054 
- #11085 had fixed it for the defect file at that time
- But another defect file was supplied a month later (https://github.com/NREL/EnergyPlus/issues/11054#issuecomment-3020355559), which has a Schedule:Compact with missing day types **AND** a `ScheduleTypeLimits`, and will fail in `setMinMaxVals`

### Description of the purpose of this PR

The approach taken here is to:

* `InitConstantScheduleData` adds a `DaySchedule` "MissingDaySchedule-0.0" at index 0 in `Sched::daySchedules`.
* `AddWeekSchedule` initializes `WeekSchedule::dayScheds` to this missing day type 
* The warning about missing day types is retained, but there will never be a null `DaySchedule` pointer in the `WeekSchedule::dayScheds`
    * Caveat: Aside from that DayType `Unused` weirdness  https://github.com/NREL/EnergyPlus/blob/acf7908bedc967ed80ec691f4441ec01702ec23c/src/EnergyPlus/ScheduleManager.hh#L75

Defect file segfaults without fix, works with fix, `eplusout.err` correctly references the missing day types

```
   ** Warning ** ProcessScheduleInput: Schedule:Compact = NUMBER OF PEOPLE
   **   ~~~   ** has missing day types in Through=12/31
   **   ~~~   ** Last "For" field=FOR: WEEKENDS
   **   ~~~   ** Missing day types= "Holiday", "SummerDesignDay", "WinterDesignDay", "CustomDay1", "CustomDay2"
   **   ~~~   ** Missing day types will have 0.0 as Schedule Values
```

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/ScheduleManager.cc [hunk 1]
```diff
@@ -313,6 +320,10 @@ namespace Sched {
         auto *schedOn = AddScheduleConstant(state, "Constant-1.0", 1.0);
         assert(schedOn->Num == SchedNum_AlwaysOn);
         schedOn->isUsed = true; // Suppress unused warnings
+
+        auto *missingDaySchedule = AddDaySchedule(state, "MissingDaySchedule-0.0");
+        assert(missingDaySchedule->Num == SchedNum_AlwaysOff);
+        missingDaySchedule->isUsed = true;
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:326]: InitConstantScheduleData: Add a missingDaySchedule at index 0 in dataSched->daySchedules

File: src/EnergyPlus/ScheduleManager.cc [hunk 2]
```diff
@@ -295,6 +297,11 @@ namespace Sched {
         auto *weekSched = new WeekSchedule;
         weekSched->Name = name;
 
+        // Fill the dayScheds with the Missing Day Schedule (Always Off)
+        for (int iDayType = 1; iDayType < (int)DayType::Num; ++iDayType) {
+            weekSched->dayScheds[iDayType] = s_sched->daySchedules[SchedNum_AlwaysOff];
+        }
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:303]: AddWeekSchedule initializes the dayScheds to that missing schedule (except the "Unused" day type...)

File: src/EnergyPlus/ScheduleManager.cc [hunk 3]
```diff
@@ -283,7 +284,8 @@ namespace Sched {
         s_sched->daySchedules.push_back(daySched);
         s_sched->dayScheduleMap.insert_or_assign(std::move(Util::makeUPPER(daySched->Name)), daySched->Num);
 
-        daySched->tsVals.resize(Constant::iHoursInDay * s_glob->TimeStepsInHour);
+        // When InitConstantScheduleData is called, TimeStepsInHour is 0, so we ensure 24
+        daySched->tsVals.assign(Constant::iHoursInDay * max(1, s_glob->TimeStepsInHour), 0.0);
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:288]: Perhaps I should have kept resize only, but the assign is clearer and initializes.

File: src/EnergyPlus/ScheduleManager.cc [hunk 4]
```diff
@@ -1210,6 +1221,9 @@ namespace Sched {
         //  A4 , \field Complex Field #2
         //  A5 , \field Complex Field #3
 
+        // When InitConstantScheduleData is called, TimeStepsInHour is 0, so we delay it here
+        static_cast<DaySchedule *>(s_sched->daySchedules[SchedNum_AlwaysOff])->tsVals.assign(Constant::iHoursInDay * s_glob->TimeStepsInHour, 0.0);
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:1225]: In ProcessScheduleInput, I reassign the DaySchedule to the right size now that we know the TimeStepsInHour.

File: src/EnergyPlus/ScheduleManager.cc [hunk 5]
```diff
@@ -2379,10 +2393,6 @@ namespace Sched {
 
         auto const *weekSched = this->weekScheds[thisDayOfYear];
         auto const *daySched = (thisHolidayNum > 0) ? weekSched->dayScheds[thisHolidayNum] : weekSched->dayScheds[thisDayOfWeek];
-        if (daySched == nullptr) {
-            // We already warned in ProcessScheduleInput that there were missing days: Missing day types will have 0.0 as Schedule Values
-            return 0.0;
-        }
```
Comment (jmarrec) [inline src/EnergyPlus/ScheduleManager.cc:2385]: daySched checking for nullptr is no longer needed.

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 6]
```diff
@@ -1741,11 +1746,15 @@ TEST_F(EnergyPlusFixture, ScheduleCompact_MissingDayTypes)
...
+        "  Fraction,                !- Name",
+        "  0,                       !- Lower Limit Value",
+        "  1,                       !- Upper Limit Value",
+        "  Continuous,              !- Numeric Type",
+        "  percent;                 !- Unit Type",
 
         "Schedule:Compact,",
         "  WindowVentSched,         !- Name",
-        "  Any Number,              !- Schedule Type Limits Name",
+        "  Fraction,                !- Schedule Type Limits Name",
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:1757]: Mod the previous test to add that ScheduleTypeLimits validation which makes it crash before fix in setMinMaxVals like the new defect file does

File: tst/EnergyPlus/unit/ScheduleManager.unit.cc [hunk 7]
```diff
@@ -1785,24 +1794,31 @@ TEST_F(EnergyPlusFixture, ScheduleCompact_MissingDayTypes)
...
+    EXPECT_EQ(0, missingDaySchedule->maxVal);
+    EXPECT_EQ(4 * 24, missingDaySchedule->tsVals.size());
+    for (auto v : missingDaySchedule->tsVals) {
+        EXPECT_EQ(0.0, v);
+    }
+
+    EXPECT_EQ(0, weekSched->minVal);
+    EXPECT_EQ(1, weekSched->maxVal);
+
+    EXPECT_EQ(missingDaySchedule, weekSched->dayScheds[(int)Sched::DayType::Sunday]);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/ScheduleManager.unit.cc:1809]: We check that the missingDaySchedule in question is properly all zeroes with the right size.

The weekSched min/maxVal are ok. 

And the Missing day types all point to that missingDaySchedule

**Comment by rraustad** [comment]
Alternate defect file Ticket 16879.idf runs successfully after fixing the coil UA issues (Sizing:Plant with 70C and 6.222C). 11054 defect file in-v25.1 runs to completion with:

    ** Warning ** ProcessScheduleInput: DecodeHHMMField, Invalid "until" field value is not a multiple of the minutes for each timestep: 5:05
    **   ~~~   ** Other errors may result. Occurred in Day Schedule=10012_100_24_24
    ** Warning ** ProcessScheduleInput: Schedule:Compact = WINDOWVENTSCHED
    **   ~~~   ** has missing day types in Through=12/31
    **   ~~~   ** Last "For" field=FOR: MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY
    **   ~~~   ** Missing day types= "Sunday", "Holiday", "SummerDesignDay", "WinterDesignDay", "CustomDay1", "CustomDay2"
    **   ~~~   ** Missing day types will have 0.0 as Schedule Values

**Comment by rraustad** [comment]
New entry in eio file for missing day schedule:

    +DaySchedule - Timestep,MissingDaySchedule-0.0,,No,Values:,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

**Review by rraustad — APPROVED** [review]
Defect files run correctly with associated warnings reported to err file.

**Comment by Myoldmopar** [comment]
Looks good to me, I'll do a quick check locally.

**Comment by Myoldmopar** [comment]
Happy to get this fix in.  Thanks @jmarrec, and @rraustad for looking it over.
