### PR TITLE
Fix Controller:MechanicalVentilation with DesignSpecification:OutdoorAir:SpaceList

### LINKED ISSUE #11018: DesignSpecification:OutdoorAir:SpaceList does not work with Controller:MechanicalVentilation
### Issue overview

DesignSpecification:OutdoorAir:SpaceList with Controller:MechanicalVentilation results in zero requested OA flow rate in v24.2. In v25.1 it causes a crash, because it's calling `Schedule::getCurrentVal` with a null pointer.

* The basic problem is that Controller:MechanicalVentilation is set up to copy values from the DesignSpecification:OutdoorAir object(s) into the `VentilationMechanical` struct to do certain OA component calcs. This doesn't work for DesignSpecification:OutdoorAir:SpaceList. It needs a whole new approach to evaluate the OA requirements by calling `OARequirementsData::calcOAFlowRate` or similar function(s). 
* Perhaps the whole DSOA:SpaceList approach needs to be revisited.
* And this is another use-case not covered by testing.
* @amirroth Would it be acceptable (possible?) to initialize schedule pointers to `Sched::GetScheduleAlwaysOn(state)` in the declaration? Not that it would fix the zero OA issue here . . . 

### Operating System (Multiple choices)

Any

### Operating System Version

any

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

Helpdesk 16870

### Defect file

EnergyPlusDevSupport/DefectFiles

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------

- Fixes #11018 
- Refactors Controller:MechanicalVentilation to use methods on `OARequirements` (DesignSpecification:OutdoorAir) instead of copying single values from `OARequirements` into the `VentilationMechanical` data structure. This makes support of DesignSpecification:OutdoorAir:SpaceList possible.
- Modify table output for System Summary report, "Demand Controlled Ventilation using Controller:MechanicalVentilation" subtable to use ZoneName for zones with a simple DSOA reference, and ZoneName:SpaceName for the spaces in a DSOA:SpaceList.

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/MixedAir.cc [hunk 1]
```diff
@@ -1363,64 +1363,65 @@ void GetOAControllerInputs(EnergyPlusData &state)
...
-
-                    if (ObjIndex == 0) {
-                        ShowSevereError(state, format("{}{}=\"{}\", invalid", RoutineName, CurrentModuleObject, thisVentilationMechanical.Name));
-                        ShowContinueError(state,
-                                          format("... not found {}=\"{}\".",
-                                                 cAlphaFields((groupNum - 1) * 3 + 6),
-                                                 state.dataMixedAir->DesignSpecOAObjName(groupNum)));
-                        ErrorsFound = true;
+                    std::string_view designSpecOAObjName = AlphArray((groupNum - 1) * 3 + 6);
+                    if (designSpecOAObjName.empty()) {
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: How can this string be empty when line 1379 says it's not blank? I think you want to remove the outer IF block.

File: src/EnergyPlus/MixedAir.cc [hunk 2]
```diff
@@ -1566,100 +1556,105 @@ void GetOAControllerInputs(EnergyPlusData &state)
...
-                    thisVentMechZone.ZoneSecondaryRecirculation = 0.0;
-                    ShowWarningError(state, format("{}{}=\"{}\"", RoutineName, CurrentModuleObject, thisVentilationMechanical.Name));
-                    ShowContinueError(
-                        state,
-                        format("Cannot locate a matching DesignSpecification:ZoneAirDistribution object for Zone=\"{}\".", thisVentMechZone.name));
-                    ShowContinueError(state, "Using default zone air distribution effectiveness of 1.0 for heating and cooling.");
+                assert(thisVentMechZone.ZoneDesignSpecOAObjIndex > 0);
+                auto &curOARequirements = state.dataSize->OARequirements(thisVentMechZone.ZoneDesignSpecOAObjIndex);
+                zoneOAAreaRate = curOARequirements.desFlowPerZoneArea(state, thisVentMechZone.zoneNum);
+                zoneOAPeopleRate = curOARequirements.desFlowPerZonePerson(state, thisVentMechZone.zoneNum);
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc]: Can't you just declare these Real64 here and delete 1559 and 1560? Cppcheck will tag those declarations with "assigned a value that is never used" (I think).

File: src/EnergyPlus/MixedAir.cc (hunk 1 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc]: > How can this string be empty when line 1379 says it's not blank? I think you want to remove the outer IF block.

Well, it can't. That's what I get for blindly moving things around. Fixed.

File: src/EnergyPlus/MixedAir.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc]: > Can't you just declare these Real64 here and delete 1559 and 1560? Cppcheck will tag those declarations with "assigned a value that is never used" (I think).

Yes, thanks. Leftover from an earlier iteration on this. Removed.

File: src/EnergyPlus/MixedAir.cc [hunk 3]
```diff
@@ -2763,41 +2732,34 @@ void InitOAController(EnergyPlusData &state, int const OAControllerNum, bool con
...
-
-                // added for new DCV inputs
-                if (thisMechVentZone.zoneADEffSched != nullptr) {
-                    OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchDCVZoneADEffCooling, zoneName, "");
-                    OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchDCVZoneADEffHeating, zoneName, "");
+                std::string const zoneName = state.dataHeatBal->Zone(thisMechVentZone.zoneNum).Name;
+                auto &dsoa = state.dataSize->OARequirements(thisMechVentZone.ZoneDesignSpecOAObjIndex);
+                // Loop through spaces if DesignSpecification:OutdoorAir:Spacelist, or just once for simple DSOA
+                for (int n = 0; n <= dsoa.numDSOA; ++n) {
+                    std::string const zsName = dsoa.numDSOA > 0 ? format("{}:{}", zoneName, dsoa.dsoaSpaceNames[n]) : zoneName;
```
Comment (jmarrec) [inline src/EnergyPlus/MixedAir.cc]: @mjwitte I'm trying this PR on a file (3.10-alpha-4219-DSOA.idf) that @mdahlhausen provided here: https://github.com/NREL/OpenStudio/pull/5384#issuecomment-2895522330

Hitting an EPVector assert on this line here.

```
Initializing Simulation
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 2) >= this->size() (which is 2)
Process 462089 stopped
* thread #1, name = 'energyplus', stop reason = signal SIGABRT
    frame #0: 0x00007fffe7a9eb2c libc.so.6`__GI___pthread_kill [inlined] __pthread_kill_implementation(no_tid=0, signo=6, threadid=<unavailable>) at pthread_kill.c:44:76


(lldb) backtrace
error: libenergyplusapi.so.25.2.0 0x04bae016: DW_TAG_member '_M_local_buf' refers to type 0x0000000004c9831f which extends beyond the bounds of 0x04bae00c
* thread #1, name = 'energyplus', stop reason = signal SIGABRT
  * frame #0: 0x00007fffe7a9eb2c libc.so.6`__GI___pthread_kill [inlined] __pthread_kill_implementation(no_tid=0, signo=6, threadid=<unavailable>) at pthread_kill.c:44:76
    frame #1: 0x00007fffe7a9eae8 libc.so.6`__GI___pthread_kill [inlined] __pthread_kill_internal(signo=6, threadid=<unavailable>) at pthread_kill.c:78:10
    frame #2: 0x00007fffe7a9eae8 libc.so.6`__GI___pthread_kill(threadid=<unavailable>, signo=6) at pthread_kill.c:89:10
    frame #3: 0x00007fffe7a4527e libc.so.6`__GI_raise(sig=6) at raise.c:26:13
    frame #4: 0x00007fffe7a288ff libc.so.6`__GI_abort at abort.c:79:7
    frame #5: 0x00007fffe7ea5ff5 libstdc++.so.6`__gnu_cxx::__verbose_terminate_handler() (.cold) at vterminate.cc:95:10
    frame #6: 0x00007fffe7ebb0da libstdc++.so.6`__cxxabiv1::__terminate(void (*)()) at eh_terminate.cc:48:15
    frame #7: 0x00007fffe7ea5a55 libstdc++.so.6`std::terminate() at eh_terminate.cc:58:27
    frame #8: 0x00007fffe7ebb391 libstdc++.so.6`__cxxabiv1::__cxa_throw(obj=0x000055555a5c3290, tinfo=0x00007fffe806eea0, dest=(libstdc++.so.6`std::out_of_range::~out_of_range() at stdexcept.cc:65:3)) at eh_throw.cc:98:18
    frame #9: 0x00007fffe7ea94a0 libstdc++.so.6`std::__throw_out_of_range_fmt(__fmt="vector::_M_range_check: __n (which is %zu) >= this->size() (which is %zu)") at functexcept.cc:101:27
    frame #10: 0x00005555555fe0bf energyplus`std::__cxx1998::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>::_M_range_check(this=0x000055555882b210 size=0, __n=2) const at stl_vector.h:1158:28
    frame #11: 0x00007fffecad941b libenergyplusapi.so.25.2.0`std::__cxx1998::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>::at(this=0x000055555882b210 size=0, __n=2) at stl_vector.h:1180:16
    frame #12: 0x00007fffecad47b1 libenergyplusapi.so.25.2.0`EnergyPlus::EPVector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>::operator[](this=0x000055555882b1f8, n=2) at EPVector.hh:79:34
    frame #13: 0x00007fffee51a925 libenergyplusapi.so.25.2.0`EnergyPlus::MixedAir::InitOAController(state=0x00007fffffffa880, OAControllerNum=1, FirstHVACIteration=true, AirLoopNum=1) at MixedAir.cc:2739:119
    frame #14: 0x00007fffee4f289e libenergyplusapi.so.25.2.0`EnergyPlus::MixedAir::SimOAController(state=0x00007fffffffa880, CtrlName="BUILDING STORY 1 PVAV_REHEAT (SYS5) OA CONTROLLER", CtrlIndex=0x000055555a6dc6f0, FirstHVACIteration=true, AirLoopNum=1) at MixedAir.cc:837:21
    frame #15: 0x00007fffee4ebd4b libenergyplusapi.so.25.2.0`EnergyPlus::MixedAir::SimOutsideAirSys(state=0x00007fffffffa880, OASysNum=1, FirstHVACIteration=true, AirLoopNum=1) at MixedAir.cc:355:24
    frame #16: 0x00007fffee4ead4a libenergyplusapi.so.25.2.0`EnergyPlus::MixedAir::ManageOutsideAirSystem(state=0x00007fffffffa880, OASysName="BUILDING STORY 1 PVAV_REHEAT (SYS5) OA SYSTEM", FirstHVACIteration=true, AirLoopNum=1, OASysNum=0x000055555a6f8604) at MixedAir.cc:272:21
    frame #17: 0x00007fffeeb2e31e libenergyplusapi.so.25.2.0`EnergyPlus::SimAirServingZones::SimAirLoopComponent(state=0x00007fffffffa880, CompName="BUILDING STORY 1 PVAV_REHEAT (SYS5) OA SYSTEM", CompType_Num=OAMixer_Num, FirstHVACIteration=true, AirLoopNum=1, CompIndex=0x000055555a6f8604, CompPointer=0x0000000000000000, airLoopNum=1, branchNum=1, compNum=1) at SimAirServingZones.cc:3437:31
    frame #18: 0x00007fffeeb2e0b7 libenergyplusapi.so.25.2.0`EnergyPlus::SimAirServingZones::SimAirLoopComponents(state=0x00007fffffffa880, AirLoopNum=1, FirstHVACIteration=true) at SimAirServingZones.cc:3360:32
    frame #19: 0x00007fffeeb2934c libenergyplusapi.so.25.2.0`EnergyPlus::SimAirServingZones::SolveAirLoopControllers(state=0x00007fffffffa880, FirstHVACIteration=true, AirLoopNum=1, AirLoopConvergedFlag=0x0000555556a4fcc8, IterMax=0x0000555556a4fcbc, IterTot=0x0000555556a4fcc0, NumCalls=0x0000555556a4fcc4) at SimAirServingZones.cc:2847:83
    frame #20: 0x00007fffeeb286ef libenergyplusapi.so.25.2.0`EnergyPlus::SimAirServingZones::SimAirLoop(state=0x00007fffffffa880, FirstHVACIteration=true, AirLoopNum=1, AirLoopPass=1, AirLoopIterMax=0x00007fffffff93dc, AirLoopIterTot=0x00007fffffff93e0, AirLoopNumCalls=0x00007fffffff93e4) at SimAirServingZones.cc:2699:32
    frame #21: 0x00007fffeeb2716e libenergyplusapi.so.25.2.0`EnergyPlus::SimAirServingZones::SimAirLoops(state=0x00007fffffffa880, FirstHVACIteration=true, SimZoneEquipment=0x0000555555710c3b) at SimAirServingZones.cc:2504:23
    frame #22: 0x00007fffeeaffa54 libenergyplusapi.so.25.2.0`EnergyPlus::SimAirServingZones::ManageAirLoops(state=0x00007fffffffa880, FirstHVACIteration=true, SimAir=0x0000555555710c38, SimZoneEquipment=0x0000555555710c3b) at SimAirServingZones.cc:174:20
    frame #23: 0x00007fffedd90ffd libenergyplusapi.so.25.2.0`EnergyPlus::HVACManager::SimSelectedEquipment(state=0x00007fffffffa880, SimAirLoops=0x0000555555710c38, SimZoneEquipment=0x0000555555710c3b, SimNonZoneEquipment=0x0000555555710c3c, SimPlantLoops=0x0000555555710c3a, SimElecCircuits=0x0000555555710c39, FirstHVACIteration=0x00007fffffff9645, LockPlantFlows=false) at HVACManager.cc:1786:43
    frame #24: 0x00007fffedd82a75 libenergyplusapi.so.25.2.0`EnergyPlus::HVACManager::SimHVAC(state=0x00007fffffffa880) at HVACManager.cc:826:25
    frame #25: 0x00007fffedd79e4f libenergyplusapi.so.25.2.0`EnergyPlus::HVACManager::ManageHVAC(state=0x00007fffffffa880) at HVACManager.cc:272:12
    frame #26: 0x00007fffedfd9615 libenergyplusapi.so.25.2.0`EnergyPlus::HeatBalanceAirManager::CalcHeatBalanceAir(state=0x00007fffffffa880) at HeatBalanceAirManager.cc:4491:32
    frame #27: 0x00007fffedf8888a libenergyplusapi.so.25.2.0`EnergyPlus::HeatBalanceAirManager::ManageAirHeatBalance(state=0x00007fffffffa880) at HeatBalanceAirManager.cc:158:23
    frame #28: 0x00007fffee11c502 libenergyplusapi.so.25.2.0`EnergyPlus::HeatBalanceSurfaceManager::ManageSurfaceHeatBalance(state=0x00007fffffffa880) at HeatBalanceSurfaceManager.cc:171:48
    frame #29: 0x00007fffee0475d6 libenergyplusapi.so.25.2.0`EnergyPlus::HeatBalanceManager::ManageHeatBalance(state=0x00007fffffffa880) at HeatBalanceManager.cc:206:33
    frame #30: 0x00007fffec845dc7 libenergyplusapi.so.25.2.0`EnergyPlus::SimulationManager::SetupSimulation(state=0x00007fffffffa880, ErrorsFound=0x00007fffffffa5d3) at SimulationManager.cc:1903:30
    frame #31: 0x00007fffec827c90 libenergyplusapi.so.25.2.0`EnergyPlus::SimulationManager::ManageSimulation(state=0x00007fffffffa880) at SimulationManager.cc:270:24
    frame #32: 0x00007fffeb7aa460 libenergyplusapi.so.25.2.0`RunEnergyPlus(state=0x00007fffffffa880, filepath="") at EnergyPlusPgm.cc:421:56
    frame #33: 0x00007fffeb7a831f libenergyplusapi.so.25.2.0`EnergyPlusPgm(args=size=6, filepath="") at EnergyPlusPgm.cc:242:25
    frame #34: 0x00005555555abfb2 energyplus`main(argc=6, argv=0x00007fffffffbfa8) at main.cc:60:25
    frame #35: 0x00007fffe7a2a1ca libc.so.6`__libc_start_call_main(main=(energyplus`main at main.cc:54:1), argc=6, argv=0x00007fffffffbfa8) at libc_start_call_main.h:58:16
    frame #36: 0x00007fffe7a2a28b libc.so.6`__libc_start_main_impl(main=(energyplus`main at main.cc:54:1), argc=6, argv=0x00007fffffffbfa8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffbf98) at libc-start.c:360:3
    frame #37: 0x00005555555abd95 energyplus`_start + 37


(lldb) f 13
frame #13: 0x00007fffee51a925 libenergyplusapi.so.25.2.0`EnergyPlus::MixedAir::InitOAController(state=0x00007fffffffa880, OAControllerNum=1, FirstHVACIteration=true, AirLoopNum=1) at MixedAir.cc:2739:119
   2736	                auto &dsoa = state.dataSize->OARequirements(thisMechVentZone.ZoneDesignSpecOAObjIndex);
   2737	                // Loop through spaces if DesignSpecification:OutdoorAir:Spacelist, or just once for simple DSOA
   2738	                for (int n = 0; n <= dsoa.numDSOA; ++n) {
-> 2739	                    std::string const zsName = dsoa.numDSOA > 0 ? format("{}:{}", zoneName, dsoa.dsoaSpaceNames[n]) : zoneName;
   2740	                    auto &dsoa2 = dsoa.numDSOA > 0 ? state.dataSize->OARequirements(dsoa.dsoaIndexes[n]) : dsoa;
   2741	                    OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchDCVventMechName, zsName, vent_mech.Name);
   2742	                    OutputReportPredefined::PreDefTableEntry(
```

Comment (jmarrec) [reply src/EnergyPlus/MixedAir.cc]:
```
(lldb) p dsoa.numDSOA
(int) 2
(lldb) p dsoa.dsoaSpaceNames
(EnergyPlus::EPVector<std::basic_string<char> >) {
  std::__debug::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > = size=2 {
    [0] = "101N CORRIDOR"
    [1] = "118 CUSTODIAL"
  }
  m_allocated = false
}
(lldb) p n
(int) 2
```
Obviously this fails, `dsoa.dsoaSpaceNames[n]` is past the end.

Comment (jmarrec) [reply src/EnergyPlus/MixedAir.cc]: Here is a MCVE I created:
* develop: does not use the OutdoorAir:SpaceList, and runs
* dsoa: uses the OutdoorAirSpaceList, and exhibits that EPVector issue

[mcve_develop.idf.txt](https://github.com/user-attachments/files/20389833/mcve_develop.idf.txt)
[mcve_dsoa.idf.txt](https://github.com/user-attachments/files/20389834/mcve_dsoa.idf.txt)

This is a shoebox model, I created 5 spaces in 3 thermal zones

```
{
  'Zone1_2': ['Space1', 'Space2'],
  'Zone3': ['Space3'],
  'Zone4_5': ['Space4', 'Space5'],
 }
```

Each Space is assigned a specific DesignSpecificationOutdoorAir


image

Zone1 is assigned to a PSZ-AC (Sys3)

image

Zone2 and Zone3 are assigned to PVAV (Sys5):

image

Comment (jmarrec) [reply src/EnergyPlus/MixedAir.cc]: Actually I can reproduce with this even smaller example that keeps only the Zone1 (PSZ), and uses the same construction and no loads (800 lines)

[super_mcve_develop.idf.txt](https://github.com/user-attachments/files/20389985/super_mcve_develop.idf.txt)
[super_mcve_dsoa.idf.txt](https://github.com/user-attachments/files/20389986/super_mcve_dsoa.idf.txt)

Comment (jmarrec) [reply src/EnergyPlus/MixedAir.cc]: I find it a bit scary that none of our unit tests or integration tests crash in debug?

File: src/EnergyPlus/MixedAir.cc [hunk 4]
```diff
@@ -2763,41 +2732,34 @@ void InitOAController(EnergyPlusData &state, int const OAControllerNum, bool con
...
-                    OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchDCVOASchName, zoneName, "");
-                }
-
-                // added for new DCV inputs
-                if (thisMechVentZone.zoneADEffSched != nullptr) {
-                    OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchDCVZoneADEffCooling, zoneName, "");
-                    OutputReportPredefined::PreDefTableEntry(state, state.dataOutRptPredefined->pdchDCVZoneADEffHeating, zoneName, "");
+                std::string const zoneName = state.dataHeatBal->Zone(thisMechVentZone.zoneNum).Name;
+                auto &dsoa = state.dataSize->OARequirements(thisMechVentZone.ZoneDesignSpecOAObjIndex);
+                // Loop through spaces if DesignSpecification:OutdoorAir:Spacelist, or just once for simple DSOA
```
Comment (jmarrec) [inline src/EnergyPlus/MixedAir.cc:2758]: This is a good candidate for a lambda actually. I'm going to make a PR pointing to this one.

File: src/EnergyPlus/MixedAir.cc (hunk 3 above)
Comment (mjwitte) [reply src/EnergyPlus/MixedAir.cc]: > I find it a bit scary that none of our unit tests or integration tests crash in debug?

* The defect file crashes with debug. It helps to run that. 
* The new unit test doesn't touch this code. I'll see if I can modify an existing one or move this code. 
* And none of the existing integration tests use MechVent with DSOA:Spacelist yet, working on that.

**Comment by mjwitte** [comment]
@jmarrec Revised unit test [fails with a vector error](https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-72f08c2560e2d6c98b5d5ac3d1edacb9a0de9315-x86_64-Linux-Ubuntu-24.04-gcc-13.3-UnitTestsCoverage-RelWithDebInfo.html).

**Comment by mjwitte** [comment]
Modified testfile 5ZoneAirCooledWithSpacesHVAC to use Controller:MechanicalVentilation with DesignSpecification:OutdoorAir:SpaceList. It should fail at this point.

**Comment by mjwitte** [comment]
- Audit diffs are expected for any file with a Controller:MechanicalVentilation object, because some blank values are no longer being written as "" to the demand controlled ventilation sub-table output.
- Other diffs are expected in 5ZoneAirCooledWithSpacesHVAC because the OA controls have been changed to demand-controlled  with a Controller:MechanicalVentilation object.
- The defect file no longer crashes (v25.1) and no longer results in zero outdoor air (v24.2).
v24.2
image
image

This branch
image
image

File: src/EnergyPlus/DataSizing.cc [hunk 5]
```diff
@@ -621,14 +622,16 @@ Real64 ZoneAirDistributionData::calculateEz(EnergyPlusData &state, int const Zon
...
+Real64
+calcDesignSpecificationOutdoorAir(EnergyPlusData &state,
+                                  int const DSOAPtr,           // Pointer to DesignSpecification:OutdoorAir object
+                                  int const ActualZoneNum,     // Zone index
+                                  bool const UseOccSchFlag,    // Zone occupancy schedule will be used instead of using total zone occupancy
+                                  bool const UseMinOASchFlag,  // Use min OA schedule in DesignSpecification:OutdoorAir object
+                                  bool const PerPersonNotSet,  // when calculation should not include occupants (e.g., dual duct)
+                                  bool const MaxOAVolFlowFlag, // TRUE when calculation uses occupancy schedule  (e.g., dual duct)
+                                  int const spaceNum,          // Space index (if applicable)
+                                  bool const calcIAQMethods)   // For IAQProcedure, PCOccSch, and PCDesOcc, calculate if true, return zero if false
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:642]: New argument for `calcDesignSpecificationOutdoorAir` to return zero for certain methods.

File: src/EnergyPlus/DataSizing.cc [hunk 6]
```diff
@@ -649,88 +653,301 @@ Real64 calcDesignSpecificationOutdoorAir(EnergyPlusData &state,
...
+                                                     thisDSOA.dsoaSpaceIndexes(dsoaCount),
+                                                     calcIAQMethods);
             }
         }
         return totOAFlowRate;
     }
 }
 
-Real64 OARequirementsData::desFlowPerZoneArea(EnergyPlusData &state, int const zoneNum, int const spaceNum)
+int getDefaultOAReq(EnergyPlusData &state)
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:728]: New function to return index to "default" OA requirements (previously these defaults were applied directly in the `VentilationMechanical` data structure.

File: src/EnergyPlus/DataSizing.cc [hunk 7]
```diff
@@ -649,88 +653,301 @@ Real64 calcDesignSpecificationOutdoorAir(EnergyPlusData &state,
...
 {
-    Real64 desFlowPA = 0.0;
+    if (state.dataSize->OARequirements_Default == 0) {
+        SizingManager::GetOARequirements(state); // get the OA requirements object and set up the default
+    }
+    return state.dataSize->OARequirements_Default;
+}
+
+Real64 OARequirementsData::oaFlowArea(EnergyPlusData &state,
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:736]: New method to calculate oa based on floor area. Code pulled from existing `desFlowPerZoneArea` which calls this method now.

File: src/EnergyPlus/DataSizing.cc [hunk 8]
```diff
@@ -649,88 +653,301 @@ Real64 calcDesignSpecificationOutdoorAir(EnergyPlusData &state,
...
+                sumArea += spaceArea;
+            }
+        }
+    }
+    auto &thisZone = state.dataHeatBal->Zone(zoneNum);
+    sumArea = sumArea * thisZone.Multiplier * thisZone.ListMultiplier;
+    return sumArea;
+}
+
+Real64 OARequirementsData::desFlowPerZoneArea(EnergyPlusData &state, int const zoneNum, int const spaceNum)
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:804]: Existing method to calculate design flow per area, easy for a simple DSOA, but needs to average across spaces for a DSAO:SpaceList.

File: src/EnergyPlus/DataSizing.cc [hunk 9]
```diff
@@ -649,88 +653,301 @@ Real64 calcDesignSpecificationOutdoorAir(EnergyPlusData &state,
...
+        Real64 sumArea = this->floorArea(state, zoneNum, spaceNum);
+        if (sumArea > 0.0) {
             desFlowPA = sumAreaOA / sumArea;
         }
     }
     return desFlowPA;
 }
 
-Real64 OARequirementsData::desFlowPerZonePerson(EnergyPlusData &state, int const actualZoneNum, int const spaceNum)
+Real64 OARequirementsData::oaFlowPeople(EnergyPlusData &state,
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:825]: Similar  methods for OA flow for people, per zone, and ACH.

File: src/EnergyPlus/DataSizing.cc [hunk 10]
```diff
@@ -1094,4 +1317,64 @@ Real64 OARequirementsData::calcOAFlowRate(EnergyPlusData &state,
     return OAVolumeFlowRate;
 }
 
+Sched::Schedule *OARequirementsData::getZoneFlowFracSched(EnergyPlusData &state, bool notAllSame)
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:1388]: Some of the iaq methods apply the zone OA flow schedule to the OA requirements for CO2 or contaminants.

File: src/EnergyPlus/DataSizing.cc [hunk 11]
```diff
@@ -1094,4 +1317,64 @@ Real64 OARequirementsData::calcOAFlowRate(EnergyPlusData &state,
...
+            if (dsoaCount == 1) {
+                schedPtr = thisDSOA.oaFlowFracSched;
+            } else {
+                if (schedPtr != thisDSOA.oaFlowFracSched) {
+                    notAllSame = true;
+                    ShowWarningError(state,
+                                     format("getZoneFlowFracSched: Outdoor Air Schedules are not the same for all spaces in "
+                                            "DesignSpecification:OutdoorAir:SpaceList={}.",
+                                            this->Name));
+                    ShowContinueError(state, format("Using the first space schedule={}", schedPtr->Name));
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.cc:1408]: If the spaces in the DSOA:SpaceList do not all use the same schedule, then throw a warning and return the first one, because contaminants are currently only tracked at the zone level. Should probably extend those to spaces (someday).

File: src/EnergyPlus/DataSizing.hh [hunk 12]
```diff
@@ -208,10 +208,6 @@ namespace DataSizing {
     // parameter for (time-of-peak) sizing format
     static constexpr std::string_view PeakHrMinFmt("{:02}:{:02}:00");
 
-    // Zone Outdoor Air Method
-    constexpr int ZOAM_ProportionalControlDesOcc(9); // Use ASHRAE Standard 62.1-2004 or Trane Engineer's newsletter (volume 34-5)
```
Comment (mjwitte) [inline src/EnergyPlus/DataSizing.hh:209]: This was leftover from the past, never used.

File: src/EnergyPlus/MixedAir.cc [hunk 13]
```diff
@@ -1363,64 +1363,62 @@ void GetOAControllerInputs(EnergyPlusData &state)
             // Zone maximum outdoor air fraction
             thisVentilationMechanical.ZoneMaxOAFraction = NumArray(1);
 
-            state.dataMixedAir->VentMechZoneOrListName.allocate(NumGroups);
-            state.dataMixedAir->DesignSpecOAObjName.allocate(NumGroups);
-            state.dataMixedAir->DesignSpecOAObjIndex.dimension(NumGroups, 0);
-            state.dataMixedAir->DesignSpecZoneADObjName.allocate(NumGroups);
-            state.dataMixedAir->DesignSpecZoneADObjIndex.dimension(NumGroups, 0);
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:1379]: These are all just temporary for input processing. They're just locals now.

File: src/EnergyPlus/MixedAir.cc [hunk 14]
```diff
@@ -1566,100 +1553,103 @@ void GetOAControllerInputs(EnergyPlusData &state)
...
-                int zoneOAReqObjIndex = thisVentMechZone.ZoneDesignSpecOAObjIndex;
-                if (zoneOAReqObjIndex > 0) {
-                    auto const &curOARequirements(state.dataSize->OARequirements(zoneOAReqObjIndex));
-                    thisVentMechZone.ZoneOAAreaRate = curOARequirements.OAFlowPerArea;
-                    thisVentMechZone.ZoneOAPeopleRate = curOARequirements.OAFlowPerPerson;
-                    thisVentMechZone.ZoneOAFlowRate = curOARequirements.OAFlowPerZone;
-                    thisVentMechZone.ZoneOAACHRate = curOARequirements.OAFlowACH;
-                    thisVentMechZone.ZoneOAFlowMethod = curOARequirements.OAFlowMethod;
-                    thisVentMechZone.zoneOASched = curOARequirements.oaFlowFracSched;
-                    thisVentMechZone.oaPropCtlMinRateSched = curOARequirements.oaPropCtlMinRateSched;
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:1587]: No longer need to copy values into the mech vent controller, just access everything from the `ZoneDesignSpecOAObjIndex`.

**Review by mjwitte — COMMENTED** [review]
Walkthru - part 1

File: src/EnergyPlus/MixedAir.cc [hunk 15]
```diff
@@ -3715,63 +3670,37 @@ Real64 VentilationMechanicalProps::CalcMechVentController(EnergyPlusData &state,
...
             // for system OA methods: Zone_Sum, VRP, CO2 methods
             // new code for DCV method complying with the VRP defined in ASHRAE Standard 62.1-2010
+            bool const useOccSch = this->DCVFlag && (this->SystemOAMethod != DataSizing::SysOAMethod::ProportionalControlDesOcc);
 
             // Loop through each zone first to calc uncorrected system OA flow rate
-            SysOAuc = 0.0;
-            SysOA = 0.0;
+            SysOAuc = 0.0; // [m3/s]
+            SysOA = 0.0;   // [m3/s]
             for (int ZoneIndex = 1; ZoneIndex <= this->NumofVentMechZones; ++ZoneIndex) {
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:3711]: In `CalcMechVentController` replace blocks code to calculate OA flow rates . . .

File: src/EnergyPlus/MixedAir.cc [hunk 16]
```diff
@@ -3715,63 +3670,37 @@ Real64 VentilationMechanicalProps::CalcMechVentController(EnergyPlusData &state,
...
-                }
+                int const ZoneNum = thisMechVentZone.zoneNum;
+
+                // Use calcDesignSpecificationOutdoorAir function to support simple DSOA and DSOA:SpaceList
+                bool const useOASch = true;
+                bool const perPersonNotSet = false;  // placeholder function argument
+                bool const maxOAVolFlowFlag = false; // placeholder function argument
+                int constexpr spaceNum = 0;          // placeholder function argument
+                bool const calcIAQMethods = false;   // If the zone or space OA method is IAQProcedure, PCOccSch or PCDesOcc then return zero
+                thisMechVentZone.zoneOABZ = DataSizing::calcDesignSpecificationOutdoorAir(state,
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:3721]: . . . with a call to `calcDesignSpecificationOutdoorAir`, and save `zoneOABZ` for later use.

File: src/EnergyPlus/MixedAir.cc [hunk 17]
```diff
@@ -3802,49 +3731,6 @@ Real64 VentilationMechanicalProps::CalcMechVentController(EnergyPlusData &state,
                     // Assign references
                     auto &curZone(state.dataHeatBal->Zone(ZoneNum));
                     auto &curZoneSysEnergyDemand(state.dataZoneEnergyDemand->ZoneSysEnergyDemand(ZoneEquipConfigNum));
-                    Real64 multiplier = curZone.Multiplier * curZone.ListMultiplier * thisMechVentZone.zoneOASched->getCurrentVal();
```
Comment (mjwitte) [inline src/EnergyPlus/MixedAir.cc:3842]: Remove a bunch of code and use the saved value of `zoneOABZ`.

File: src/EnergyPlus/SizingManager.cc [hunk 18]
```diff
@@ -2171,12 +2171,21 @@ void GetOARequirements(EnergyPlusData &state)
     lAlphaBlanks.dimension(NumAlphas, true);
     lNumericBlanks.dimension(NumNumbers, true);
 
-    if (state.dataSize->NumOARequirements > 0) {
+    // Create default OASpec for use by Controller:MechanicalVentilation if needed, put at the end of OARequirements
+    state.dataSize->NumOARequirements += 1;
```
Comment (mjwitte) [inline src/EnergyPlus/SizingManager.cc:2207]: Create default OA requirements.

File: testfiles/5ZoneAirCooledWithSpacesHVAC.idf [hunk 19]
```diff
@@ -3193,7 +3193,32 @@ ZoneAirHeatBalanceAlgorithm,
...
     NoLockout,               !- Lockout Type
     FixedMinimum,            !- Minimum Limit Type
-    Min OA Sched;            !- Minimum Outdoor Air Schedule Name
+    ,                        !- Minimum Outdoor Air Schedule Name
+    ,                        !- Minimum Fraction of Outdoor Air Schedule Name
+    ,                        !- Maximum Fraction of Outdoor Air Schedule Name
+    Controller Mechanical Ventilation 1;  !- Mechanical Ventilation Controller Name
+
+  Controller:MechanicalVentilation,
+    Controller Mechanical Ventilation 1,  !- Name
```
Comment (mjwitte) [inline testfiles/5ZoneAirCooledWithSpacesHVAC.idf:3202]: Add a Controller:MechanicalVentilation to testfiles/5ZoneAirCooledWithSpacesHVAC.idf

File: testfiles/5ZoneAirCooledWithSpacesHVAC.idf [hunk 20]
```diff
@@ -3193,7 +3193,32 @@ ZoneAirHeatBalanceAlgorithm,
...
+    SZ DSOA Zone 2,          !- Design Specification Outdoor Air Object Name 2
+    ,                        !- Design Specification Zone Air Distribution Object Name 2
+    Zone 3,                  !- Zone or ZoneList 3 Name
+    SZ DSOA Zone 3,          !- Design Specification Outdoor Air Object Name 3
+    ,                        !- Design Specification Zone Air Distribution Object Name 3
+    Zone 4,                  !- Zone or ZoneList 4 Name
+    SZ DSOA Zone 4,          !- Design Specification Outdoor Air Object Name 4
+    ,                        !- Design Specification Zone Air Distribution Object Name 4
+    Zone 5,                  !- Zone or ZoneList 5 Name
+    SZ DSOA Zone 5 List,     !- Design Specification Outdoor Air Object Name 5
```
Comment (mjwitte) [inline testfiles/5ZoneAirCooledWithSpacesHVAC.idf:3220]: And use a DSOA:SpaceList.

File: tst/EnergyPlus/unit/MixedAir.unit.cc [hunk 21]
```diff
@@ -6445,6 +6465,208 @@ TEST_F(EnergyPlusFixture, MechVentController_ZoneSumTests)
     state->dataHeatBal->ZoneIntGain.deallocate();
 }
 
+TEST_F(EnergyPlusFixture, MechVentController_ZoneSumTests_DSOASpaceList)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/MixedAir.unit.cc:6469]: New unit test.

File: tst/EnergyPlus/unit/Standard621SimplifiedProcedure.unit.cc [hunk 22]
```diff
@@ -2976,12 +3016,18 @@ TEST_F(EnergyPlusFixture, SimplifiedProcedureTest3)
...
         " ",
         "DesignSpecification:OutdoorAir,",
-        "  Spacex10 DSOA Design OA Spec,  !- Name",
+        "  Spacex10 DSOA,  !- Name",
         "  sum,                           !- Outdoor Air Method",
         "  0.008,                         !- Outdoor Air Flow per Person {m3/s-person}",
         "  0.0009,                        !- Outdoor Air Flow per Zone Floor Area {m3/s-m2}",
         "  0;                             !- Outdoor Air Flow per Zone {m3/s}",
         " ",
+        "DesignSpecification:OutdoorAir:SpaceList,",
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/Standard621SimplifiedProcedure.unit.cc:3025]: Modify an existing unit test to use a DSOA :SpaceList.

**Review by mjwitte — COMMENTED** [review]
Walkthru - part 2

**Comment by Myoldmopar** [comment]
Pulled in develop to make sure it's still happy with formatting changes.

**Comment by Myoldmopar** [comment]
image


?? :) I'll take a look

**Comment by Myoldmopar** [comment]
It's completely happy here.  I may need to give the CI machine a reboot.

**Comment by Myoldmopar** [comment]
This will still have a few spurious table diffs, but hopefully Decent is clean and this can be ready to go in.

**Comment by nrel-bot-2c** [comment]
@mjwitte @myoldmopar it has been 34 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
My local regressions are showing more table diffs than before. I'm going to push it up and let CI confirm my findings before investigating any further.

**Comment by mjwitte** [comment]
@Myoldmopar The diffs here look like they are back to normal.
```
Regression Summary
Audit: 27
EIO: 1
ERR: 1
RDD: 1
ESO Big Diffs: 1
MTR Big Diffs: 1
Table Big Diffs: 1
Table String Diffs: 1
```

**Comment by nrel-bot-2** [comment]
@mjwitte @myoldmopar it has been 30 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@mjwitte @myoldmopar it has been 33 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@mitchute Conflicts resolved, CI looks good so far. Ready for review.

File: src/EnergyPlus/DataSizing.cc [hunk 23]
```diff
@@ -1149,7 +1370,7 @@ Real64 OARequirementsData::calcOAFlowRate(EnergyPlusData &state,
     }
 
     // Apply zone multipliers and zone list multipliers
-    // TODO MJW: this looks like it's double-counting the multipliers
+    // TODO MJW: this looks like it's double-counting the multipliers - it *is* double counting for methods PCOccSch and PCDesOcc
```
Comment (mitchute) [inline src/EnergyPlus/DataSizing.cc:1373]: Is this worth cleaning up? May also make sure where it's being double counted is noted, and relevant reasoning.

**Review by mitchute — APPROVED** [review]

File: src/EnergyPlus/DataSizing.cc (hunk 23 above)
Comment (mjwitte) [reply src/EnergyPlus/DataSizing.cc:1373]: > Is this worth cleaning up? May also make sure where it's being double counted is noted, and relevant reasoning.

How about a followup-PR? I see there's an open issue related to multipliers that I should address anyway.
See #https://github.com/NREL/EnergyPlus/issues/10799

Comment (mitchute) [reply src/EnergyPlus/DataSizing.cc:1373]: Works for me. Thanks!
