### PR TITLE
Fix issues with zero floor area or zero surfaces due to air boundaries

### LINKED ISSUE #9335: Fatal Error When Zone is Composed Entirely of Construction:AirBoundary
Issue overview
--------------
When an IDF contains a Zone composed entirely of Surfaces using `Construction:AirBoundary` , EnergyPlus will fail to simulate and will return a Fatal Error like the following:

```
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=ROOM_59_353B10B5
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=GetSurfaceData: Zone has no surfaces, Zone=ROOM_59_353B10B5
```

### Details

I'll admit that I'm not sure if returning a fatal error is the intended behavior for this case. I can understand why it happens because the zone-grouping operation that underlies the use of `Construction:AirBoundary` essentially removes all Zone Surfaces in the solar and radiant calculations, causing EnergyPlus to think there is a zero-Surface Zone.

However, there are a few situations where being able to simulate such cases would be handy. For example, here is a sample IDF from E+ 9.6 that can recreate the fatal error above:
https://drive.google.com/file/d/1Newt7ahsSmGpwkK5I-8X4d5M0PaP0KP8/view?usp=sharing
The model has a central atrium with a few floors surrounding it:
image
The AirBoundary surfaces are all in the middle and the very center zone is composed entirely of AirBoundaries:
image
It can be helpful to break up the central atrium with air boundaries in order to assess the heat contributions of each surrounding floor at each level of the atrium. This level of detail would be lost if the entire atrium had to be modeled as one Zone.

Granted, I'll respect the decision if we ultimately decide that this case should not be simulate-able. As in the example above, there's usually a way of merging the AirBoundary Zones together that won't dramatically alter the simulation.

However, at a minimum, it would be nice to have a clearer message if the simulation fails because of a Zone composed entirely of AirBoundaries. When I first received the error message above, I kept trying to find a Zone in the IDF that had no Surfaces associated with it and couldn't find it.

### Checklist

 - [x] Defect file added (see Google Drive link above for an IDF that recreates the issue)
 v22.2 file added to EnergyPlusDevSupport
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #9335 
 - Allow a space or zone with zero heat transfer surfaces which can result if all sides of a space or zone are Construction:AirBoundary surfaces.
 - Handle the case of zero floor area correctly when all of the floor surfaces in a space or zone are Construction:AirBoundary surfaces. The fix uses the phantom surfaces for geometric calculations such as volume, height, and centroid.

Diffs and Defect Files
--------------------
No diffs are expected.

9335-9793-in-v22.2-DivideByZeroFloorArea.idf
* Crashes in develop (debug) with div by zero.
* Runs to completion with this branch, with expected warning about zero floor area.
```
   ** Warning ** No floor exists in Zone="THERMAL ZONE: CLASSROOM_C", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
```

air_boundary_fatal_error.idf
* Crashes in develop (debug) with div by zero. (same as the other defect file).
* Severe error, but then ultimately crashes.
```
   ** Severe  ** GetSurfaceData: Zone has no heat transfer surfaces, Zone=ROOM_59_353B10B5
```
* Runs to completion with this branch, with expected warnings.
```
   ** Warning ** No floor exists in Zone="ROOM_59_353B10B5", zone floor area is zero. All values for this zone that are entered per floor area will be zero.
   ** Warning ** No floor exists in Zone="ROOM_60_2C1A1886", zone floor area is zero. All values for this zone that are entered per floor area will be zero.

   ** Warning ** Zone areas*inside surface emissivities are summing to zero, for Zone="ROOM_59_353B10B5"
   **   ~~~   ** As a result, MRT will be set to MAT for that zone
```
And more about zero people, zero infiltration, zero outdoor air.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] ~If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label~
 - [ ] ~If structural output changes, add to output rules file and add OutputChange label~
 - [ ] ~If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies~

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 1]
```diff
@@ -435,7 +405,8 @@ namespace SurfaceGeometry {
                 thisZone.HasWindow = true;
                 thisSpace.totalSurfArea += state.dataSurface->SurfWinFrameArea(SurfNum);
             }
-            if (thisSurface.Class == SurfaceClass::Roof) ZoneCeilingArea(thisSurface.Zone) += thisSurface.GrossArea;
+            if (thisSurface.Class == SurfaceClass::Roof) thisZone.geometricCeilingArea += thisSurface.GrossArea;
+            if (thisSurface.Class == SurfaceClass::Floor) thisZone.geometricFloorArea += thisSurface.GrossArea;
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc]: This can be an `else if`. Not a big deal, but ... just saying.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 2]
```diff
@@ -496,103 +467,102 @@ namespace SurfaceGeometry {
 
         for (int ZoneNum = 1; ZoneNum <= state.dataGlobal->NumOfZones; ++ZoneNum) {
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc]: If you are not using `ZoneNum` anywhere (I don't see it) can just make this a range loop.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 3]
```diff
@@ -496,103 +467,102 @@ namespace SurfaceGeometry {
...
                 // Use AllSurfaceFirst which includes air boundaries
                 for (int SurfNum = thisSpace.AllSurfaceFirst; SurfNum <= thisSpace.AllSurfaceLast; ++SurfNum) {
                     auto &thisSurface = state.dataSurface->Surface(SurfNum);
 
                     if (thisSurface.Class == SurfaceClass::Roof) {
                         // Use Average Z for surface, more important for roofs than floors...
                         ++CeilCount;
-                        Z1 = minval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
-                        Z2 = maxval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
+                        Real64 Z1 = minval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc]: Why slice here? Isn't this the entire vertex array?

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 4]
```diff
@@ -2436,14 +2409,14 @@ namespace SurfaceGeometry {
         Real64 constexpr floorAreaTolerance(0.05);
         Real64 constexpr floorAreaPercentTolerance(floorAreaTolerance * 100.0);
         if (!SurfError) {
-            for (int ZoneNum = 1; ZoneNum <= state.dataGlobal->NumOfZones; ++ZoneNum) {
-                auto &thisZone = state.dataHeatBal->Zone(ZoneNum);
+            for (auto &thisZone : state.dataHeatBal->Zone) {
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc:2410]: :+1:

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 5]
```diff
@@ -2454,15 +2427,13 @@ namespace SurfaceGeometry {
                 }
             }
             ErrCount = 0;
-            for (int spaceNum = 1; spaceNum <= state.dataGlobal->numSpaces; ++spaceNum) {
-                if (state.dataHeatBal->space(spaceNum).userEnteredFloorArea != DataGlobalConstants::AutoCalculate) {
+            for (auto &thisSpace : state.dataHeatBal->space) {
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc:2428]: 👍

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 6]
```diff
@@ -12631,7 +12601,7 @@ namespace SurfaceGeometry {
                         }
                     }
                 }
-            } else if (CeilingHeightEntered(ZoneNum)) { // User did not enter zone volume, but entered ceiling height
+            } else if (state.dataHeatBal->Zone(ZoneNum).ceilingHeightEntered) { // User did not enter zone volume, but entered ceiling height
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc]: `auto &thisZone`?

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 7]
```diff
@@ -13848,7 +13817,6 @@ namespace SurfaceGeometry {
                                       Vector &CompCoordTranslVector // Coordinate Translation Vector
     )
     {
-
         // SUBROUTINE INFORMATION:
         //       AUTHOR         George Walton, BLAST
         //       DATE WRITTEN   August 1976
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc:13793]: 1976! That was a good year!

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 3 above)
Comment (mjwitte) [reply src/EnergyPlus/SurfaceGeometry.cc]: > Why slice here? Isn't this the entire vertex array?

Looks like this was done to support a certain compiler back in the day and just carried forward through all the conversions. https://github.com/NREL/EnergyPlusArchive/commit/dc94f2092324ca6d039e4699305a9c4200348664

I'll try changing all of these wherever they may show up.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 8]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
             print(state.files.debug, "{}\n", "Zone,ExtWallArea,ExtWindowArea");
         }
 
-        for (int ZoneNum = 1; ZoneNum <= state.dataGlobal->NumOfZones; ++ZoneNum) {
-            auto &thisZone = state.dataHeatBal->Zone(ZoneNum);
+        for (auto &thisZone : state.dataHeatBal->Zone) {
+            int CeilCount = 0.0;
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc]: strange to initialize an `int` with `0.0`.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 9]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
                         //        ZFlrAvg=ZFlrAvg+(Z1+Z2)/2.d0
-                        ZFlrAvg += ((Z1 + Z2) / 2.0) * (thisSurface.Area / thisZone.FloorArea);
+                        ZFlrAvg += ((Z1 + Z2) / 2.0) * (thisSurface.GrossArea / thisZone.geometricFloorArea);
                     }
                     if (thisSurface.Class == SurfaceClass::Wall) {
                         // Use Wall calculation in case no roof & floor in zone
-                        ++Count;
-                        if (Count == 1) {
+                        ++WallCount;
+                        if (WallCount == 1) {
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc:504]: Did you know you can do `if (++WallCount == 1)` and it would be the same thing?

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 10]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
-                if (CeilCount > 0.0 && FloorCount > 0.0) {
-                    AverageHeight = ZCeilAvg - ZFlrAvg;
-                } else {
-                    AverageHeight = (ZMax - ZMin);
-                }
-                if (AverageHeight <= 0.0) {
-                    AverageHeight = (ZMax - ZMin);
-                }
+            }
+            if (CeilCount > 0.0 && FloorCount > 0.0) {
```
Comment (amirroth) [inline src/EnergyPlus/SurfaceGeometry.cc]: Comparing `int` to `0.0`

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 3 above)
Comment (amirroth) [reply src/EnergyPlus/SurfaceGeometry.cc]: Yes please. Slices create copies and we should avoid them to the extent possible. They're a convenient shorthand perhaps but quite inefficient.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 9 above)
Comment (mjwitte) [reply src/EnergyPlus/SurfaceGeometry.cc:504]: > Did you know you can do `if (++WallCount == 1)` and it would be the same thing?

No, I did not. I don't expect an `if` statement to change any values within it, so that's confusing to me. Since these are one-time calculations, I'm inclined to let it be.

File: src/EnergyPlus/Construction.hh [hunk 11]
```diff
@@ -100,7 +100,7 @@ namespace Construction {
         Array1D<Real64> CTFOutside;   // Outside or X terms of the CTF equation
         Array1D<Real64> CTFSourceIn;  // Heat source/sink inside terms of CTF equation
         Array1D<Real64> CTFSourceOut; // Heat source/sink outside terms of CTF equation
-        Real64 CTFTimeStep;           // Time increment for stable simulation of construct (could be greater than TimeStep)
+        Real64 CTFTimeStep = 0.0;     // Time increment for stable simulation of construct (could be greater than TimeStep)
```
Comment (mjwitte) [inline src/EnergyPlus/Construction.hh:103]: Clean up compiler warning

File: src/EnergyPlus/DataHeatBalance.hh [hunk 12]
```diff
@@ -582,12 +582,15 @@ namespace DataHeatBalance {
...
-        Real64 CeilingArea = 0.0;   // Ceiling area for the zone
-        bool HasFloor = false;      // Has "Floor" surface
-        bool HasRoof = false;       // Has "Roof" or "Ceiling" Surface
-        bool HasWindow = false;     // Window(s) present in this zone
+        Real64 FloorArea = 0.0;            // Floor area used for area based internal gains and outputs
+        Real64 CalcFloorArea = 0.0;        // Calculated floor area excluding air boundary surfaces
+        Real64 geometricFloorArea = 0.0;   // Calculated floor area including air boundary surfaces
+        Real64 CeilingArea = 0.0;          // Ceiling area excluding air boundary surfaces
+        Real64 geometricCeilingArea = 0.0; // Ceiling area area including air boundary surfaces
+        bool ceilingHeightEntered = false; // True is user input ceiling height
```
Comment (mjwitte) [inline src/EnergyPlus/DataHeatBalance.hh:590]: Add new `geometric` areas that include air boundary surfaces.

File: src/EnergyPlus/DisplacementVentMgr.cc [hunk 13]
```diff
@@ -212,8 +212,8 @@ void HcUCSDDV(EnergyPlusData &state, int const ZoneNum, Real64 const FractionHei
             state.dataSurface->SurfTAirRef(SurfNum) = DataSurfaces::RefAirTemp::AdjacentAirTemp;
             state.dataSurface->SurfTAirRefRpt(SurfNum) = DataSurfaces::SurfTAirRefReportVals[state.dataSurface->SurfTAirRef(SurfNum)];
             if (SurfNum == 0) continue;
-            Z1 = minval(state.dataSurface->Surface(SurfNum).Vertex({1, state.dataSurface->Surface(SurfNum).Sides}), &Vector::z);
-            Z2 = maxval(state.dataSurface->Surface(SurfNum).Vertex({1, state.dataSurface->Surface(SurfNum).Sides}), &Vector::z);
+            Z1 = minval(state.dataSurface->Surface(SurfNum).Vertex, &Vector::z);
+            Z2 = maxval(state.dataSurface->Surface(SurfNum).Vertex, &Vector::z);
```
Comment (mjwitte) [inline src/EnergyPlus/DisplacementVentMgr.cc:216]: Eliminate slice-the-whole-array everywhere it occurs for the `minval/maxval` functions. (Not directly related to the fixes here.)

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 14]
```diff
@@ -293,35 +293,8 @@ namespace SurfaceGeometry {
         // This subroutine controls the processing of detached shadowing and
         // zone surfaces for computing their vertices.
 
-        using namespace DataVectorTypes;
-        using namespace OutputReportPredefined;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:297]: Code cleanup.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 15]
```diff
@@ -293,35 +293,8 @@ namespace SurfaceGeometry {
...
-        Real64 FloorCount;
-        Real64 TotSurfArea;
-        Real64 Z1;
-        Real64 Z2;
-        std::string String1;
-        std::string String2;
-        std::string String3;
-        int Count; // To count wall surfaces for ceiling height calculation
-        Array1D_bool ZoneCeilingHeightEntered;
-        Array1D<Real64> ZoneCeilingArea;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:316]: Moved these to the `Zone` struct.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 16]
```diff
@@ -430,13 +400,30 @@ namespace SurfaceGeometry {
 
             thisZone.TotalSurfArea += thisSurface.Area;
             thisSpace.totalSurfArea += thisSurface.Area;
+            if (thisSurface.Class == SurfaceClass::Roof) {
+                thisZone.geometricCeilingArea += thisSurface.GrossArea;
+            } else if (thisSurface.Class == SurfaceClass::Floor) {
+                thisZone.geometricFloorArea += thisSurface.GrossArea;
+            }
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:407]: Summing the `geometric` areas here - includes air boundary surfaces.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 17]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
                     if (thisSurface.Class == SurfaceClass::Roof) {
                         // Use Average Z for surface, more important for roofs than floors...
                         ++CeilCount;
-                        Z1 = minval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
-                        Z2 = maxval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
+                        Real64 Z1 = minval(thisSurface.Vertex, &Vector::z);
+                        Real64 Z2 = maxval(thisSurface.Vertex, &Vector::z);
                         //        ZCeilAvg=ZCeilAvg+(Z1+Z2)/2.d0
-                        ZCeilAvg += ((Z1 + Z2) / 2.0) * (thisSurface.GrossArea / ZoneCeilingArea(ZoneNum));
+                        ZCeilAvg += ((Z1 + Z2) / 2.0) * (thisSurface.GrossArea / thisZone.geometricCeilingArea);
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:491]: Use the geometric value here.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 18]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
                     if (thisSurface.Class == SurfaceClass::Floor) {
                         // Use Average Z for surface, more important for roofs than floors...
                         ++FloorCount;
-                        Z1 = minval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
-                        Z2 = maxval(thisSurface.Vertex({1, thisSurface.Sides}), &Vector::z);
+                        Real64 Z1 = minval(thisSurface.Vertex, &Vector::z);
+                        Real64 Z2 = maxval(thisSurface.Vertex, &Vector::z);
                         //        ZFlrAvg=ZFlrAvg+(Z1+Z2)/2.d0
-                        ZFlrAvg += ((Z1 + Z2) / 2.0) * (thisSurface.Area / thisZone.FloorArea);
+                        ZFlrAvg += ((Z1 + Z2) / 2.0) * (thisSurface.GrossArea / thisZone.geometricFloorArea);
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:499]: And here.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 19]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
-                    AverageHeight = ZCeilAvg - ZFlrAvg;
-                } else {
-                    AverageHeight = (ZMax - ZMin);
-                }
-                if (AverageHeight <= 0.0) {
-                    AverageHeight = (ZMax - ZMin);
-                }
+            }
+            if (CeilCount > 0 && FloorCount > 0) {
+                AverageHeight = ZCeilAvg - ZFlrAvg;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:514]: These `AverageHeight` calcs were incorrectly inside the space loop, move to the zone level. This didn't introduce any diffs here, because the only testfiles with multiples spaces in a zone has spaces of equal height.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 20]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
-                                String1 = format(ValFmt, thisZone.CeilingHeight);
-                                String2 = format(ValFmt, AverageHeight);
-                                ShowContinueError(
-                                    state,
-                                    format("{}Entered Ceiling Height={}, Calculated Ceiling Height={}, entered height will be used in calculations.",
-                                           RoutineName,
-                                           String1,
-                                           String2));
-                            }
+            if (thisZone.CeilingHeight > 0.0) {
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:522]: Same here, moved from space to zone level.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 21]
```diff
@@ -494,105 +464,103 @@ namespace SurfaceGeometry {
...
                 }
-                if ((thisZone.CeilingHeight <= 0.0) && (AverageHeight > 0.0)) thisZone.CeilingHeight = AverageHeight;
-                // Need to add check here - don't touch if already user-specified
             }
+            if ((thisZone.CeilingHeight <= 0.0) && (AverageHeight > 0.0)) thisZone.CeilingHeight = AverageHeight;
+            // Need to add check here - don't touch if already user-specified
         }
 
-        CalculateZoneVolume(state, ZoneCeilingHeightEntered); // Calculate Zone Volumes
+        CalculateZoneVolume(state); // Calculate Zone Volumes
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:556]: Don't need to pass this array, the values are in `Zone` now.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 22]
```diff
@@ -2411,23 +2386,19 @@ namespace SurfaceGeometry {
...
-            for (int spaceNum : state.dataHeatBal->Zone(ZoneNum).spaceIndexes) {
-                auto &thisSpace = state.dataHeatBal->space(spaceNum);
                 if (thisSpace.HTSurfaceFirst > 0) {
-                    zoneSurfCount += (thisSpace.HTSurfaceLast - thisSpace.HTSurfaceFirst + 1);
-                }
-                if (zoneSurfCount == 0) {
-                    ShowSevereError(state,
-                                    format("{}Zone has no heat transfer surfaces, Zone={}", RoutineName, state.dataHeatBal->Zone(ZoneNum).Name));
-                    SurfError = true;
+                    thisSpace.OpaqOrWinSurfaceFirst = thisSpace.HTSurfaceFirst;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2390]: Make sure the `...SurfaceFirst/Last` accounting is correct.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 23]
```diff
@@ -2411,23 +2386,19 @@ namespace SurfaceGeometry {
...
+                    thisSpace.OpaqOrWinSurfaceLast = std::max(thisSpace.OpaqOrIntMassSurfaceLast, thisSpace.WindowSurfaceLast);
+                    thisSpace.HTSurfaceLast = thisSpace.AllSurfaceLast;
+                } else {
+                    // If no heat transfer surfaces, make sure all others are set correctly
+                    thisSpace.HTSurfaceLast = -1;
+                    thisSpace.WindowSurfaceFirst = 0;
+                    thisSpace.WindowSurfaceLast = -1;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2397]: For spaces that end up with no heat transfer surfaces, make sure that the various `...SurfaceFirst = -1` and `...SurfaceLast = 0` so any loops across these will be skipped.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 24]
```diff
@@ -2454,15 +2425,13 @@ namespace SurfaceGeometry {
                 }
             }
             ErrCount = 0;
-            for (int spaceNum = 1; spaceNum <= state.dataGlobal->numSpaces; ++spaceNum) {
-                if (state.dataHeatBal->space(spaceNum).userEnteredFloorArea != DataGlobalConstants::AutoCalculate) {
+            for (auto &thisSpace : state.dataHeatBal->space) {
+                if (thisSpace.userEnteredFloorArea != DataGlobalConstants::AutoCalculate) {
                     // Check entered vs calculated
-                    if (state.dataHeatBal->space(spaceNum).userEnteredFloorArea > 0.0) { // User entered Space floor area,
+                    if (thisSpace.userEnteredFloorArea > 0.0) { // User entered Space floor area,
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2431]: Nothing to see here, just some referencing.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 25]
```diff
@@ -2980,6 +2945,10 @@ namespace SurfaceGeometry {
                 }
             }
         }
+        if (SurfError || ErrorsFound) {
+            ErrorsFound = true;
+            ShowFatalError(state, format("{}Errors discovered, program terminates.", RoutineName));
+        }
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:2951]: There is another check like this inside an `if(!SurfError)`, but none outside that if. If `SurfError` was set true early on, the fatal never tripped. So added another check here at the end of `GetSurfaceData`.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 26]
```diff
@@ -12399,9 +12368,8 @@ namespace SurfaceGeometry {
     }
 
     // Calculates the volume (m3) of a zone using the surfaces as possible.
-    void CalculateZoneVolume(EnergyPlusData &state, const Array1D_bool &CeilingHeightEntered)
+    void CalculateZoneVolume(EnergyPlusData &state)
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:12371]: A bunch of code cleanup here with some substantive changes noted below.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 27]
```diff
@@ -12620,34 +12566,33 @@ namespace SurfaceGeometry {
...
+                                                     thisZone.Volume,
                                                      CalcVolume));
                         }
                     }
                 }
-            } else if (CeilingHeightEntered(ZoneNum)) { // User did not enter zone volume, but entered ceiling height
-                if (state.dataHeatBal->Zone(ZoneNum).FloorArea > 0.0) {
-                    state.dataHeatBal->Zone(ZoneNum).Volume =
-                        state.dataHeatBal->Zone(ZoneNum).FloorArea * state.dataHeatBal->Zone(ZoneNum).CeilingHeight;
+            } else if (thisZone.ceilingHeightEntered) { // User did not enter zone volume, but entered ceiling height
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:12580]: Get `ceilingHeightEntered` from `Zone` instead of passed-in array.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 28]
```diff
@@ -12656,57 +12601,53 @@ namespace SurfaceGeometry {
                 if (thisSpace.Volume > 0.0) continue;
                 if (thisZone.numSpaces == 1) {
                     thisSpace.Volume = thisZone.Volume;
-                } else if (thisZone.FloorArea > 0.0) {
-                    thisSpace.Volume = thisZone.Volume * thisSpace.floorArea / thisZone.FloorArea;
+                } else if (thisZone.geometricFloorArea > 0.0) {
+                    thisSpace.Volume = thisZone.Volume * thisSpace.floorArea / thisZone.geometricFloorArea;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:12605]: Use geometric area here.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 29]
```diff
@@ -12450,87 +12401,82 @@ namespace SurfaceGeometry {
...
+            Real64 distanceBetweenOppositeWalls = 0.0;
 
             bool areWallsSameHeight = areWallHeightSame(state, ZoneStruct);
 
             std::vector<EdgeOfSurf> listOfedgeNotUsedTwice;
             bool isZoneEnclosed = isEnclosedVolume(ZoneStruct, listOfedgeNotUsedTwice);
             ZoneVolumeCalcMethod volCalcMethod;
 
+            Real64 floorAreaForVolume = (thisZone.FloorArea > 0.0) ? thisZone.FloorArea : thisZone.geometricFloorArea;
+            Real64 ceilingAreaForVolume = (thisZone.CeilingArea > 0.0) ? thisZone.CeilingArea : thisZone.geometricCeilingArea;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:12458]: For volume calcs, use geometric area if area based on HT surfs or user input is zero.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 30]
```diff
@@ -10290,3 +10280,460 @@ TEST_F(EnergyPlusFixture, Wrong_Window_Construction)
     });
     EXPECT_TRUE(compare_err_stream(error_string, true));
 }
+TEST_F(EnergyPlusFixture, CalculateZoneVolume_WithAirBoundaries)
```
Comment (mjwitte) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:10283]: A couple of new unit tests.

**Review by mjwitte — COMMENTED** [review]
Code walkthrough (sorry this got a little long).
Ready for review.

File: src/EnergyPlus/Construction.hh (hunk 11 above)
Comment (Myoldmopar) [reply src/EnergyPlus/Construction.hh:103]: That's fine.  Sometimes this just indicates the variable is too broadly scoped, but no worries here.

File: src/EnergyPlus/DataHeatBalance.hh (hunk 12 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DataHeatBalance.hh:590]: OK, so Zone() has a few extra things.  No problem.

File: src/EnergyPlus/DisplacementVentMgr.cc (hunk 13 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DisplacementVentMgr.cc:216]: Hmm, I don't recall the contents of that array, but is this still doing essentially the same thing?

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 15 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:316]: Yes, makes good sense to have them there with the zone rather than allocated in here.

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 21 above)
Comment (Myoldmopar) [reply src/EnergyPlus/SurfaceGeometry.cc:556]: Much nicer :)

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 31]
```diff
@@ -2436,14 +2407,14 @@ namespace SurfaceGeometry {
...
-                auto &thisZone = state.dataHeatBal->Zone(ZoneNum);
+            for (auto &thisZone : state.dataHeatBal->Zone) {
                 for (int spaceNum : thisZone.spaceIndexes) {
                     auto &thisSpace = state.dataHeatBal->space(spaceNum);
                     for (int SurfNum = thisSpace.HTSurfaceFirst; SurfNum <= thisSpace.HTSurfaceLast; ++SurfNum) {
                         auto &thisSurf = state.dataSurface->Surface(SurfNum);
                         if (thisSurf.Class == SurfaceClass::Floor) {
                             thisZone.HasFloor = true;
+                            thisSpace.hasFloor = true;
                             state.dataHeatBal->space(spaceNum).calcFloorArea += thisSurf.Area;
```
Comment (Myoldmopar) [inline src/EnergyPlus/SurfaceGeometry.cc]: Why not `thisSpace` here on this line too?

**Review by Myoldmopar — APPROVED** [review]
This looks really good!  Could you elaborate a little bit on the change to avoid array slicing before we get this in?  Is it doing the same thing?  Was there anything you had to change to make it still do the same thing?

File: src/EnergyPlus/SurfaceGeometry.cc (hunk 31 above)
Comment (mjwitte) [reply src/EnergyPlus/SurfaceGeometry.cc]: > Why not `thisSpace` here on this line too?

I dunno. Will fix.

File: src/EnergyPlus/DisplacementVentMgr.cc (hunk 13 above)
Comment (mjwitte) [reply src/EnergyPlus/DisplacementVentMgr.cc:216]: As far as I can tell, it's passing the entire array either way. See [prior comments here](https://github.com/NREL/EnergyPlus/pull/9855#discussion_r1117824269).

Comment (Myoldmopar) [reply src/EnergyPlus/DisplacementVentMgr.cc:216]: Hmmm OK.  Thanks I hadn't seen that comment. :+1:

**Review by Myoldmopar — APPROVED** [review]
:+1:

**Comment by Myoldmopar** [comment]
CI looks all clean.  Pulled develop in and building/testing locally real quick.  I anticipate this merging in just a few minutes.

**Comment by Myoldmopar** [comment]
Clean and merging, thanks @mjwitte
