### PR TITLE
Fix public linkage of energypluslib to energyplus.exe

### LINKED ISSUE #9287: PUBLIC linkage of energypluslib propagates lib dependency to all clients of energyplusapi
Issue overview
--------------
EnergyPlus (exe) links to both energypluslib (statically) and energyplusapi (dynamically) for duplicated and sometimes conflicting access to the same objects. (This occurs because the default linkage of energypluslib into energyplusapi is currently  PUBLIC.)

### Details
 - Discovered during defect resolution for Issue 9091; exists in branch develop (7627a7d1).
 - 
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by tanaya-mankad**
Pull request overview
---------------------
 - Fixes #9287 
 - Decoupling the static energypluslib from the EP executable guarantees that the same objects may not be created from two different "modules," reducing the risk of internal global variable bifurcation (issue #9091). The application should only access energyplusapi(.dll/.so).

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts

### CODE REVIEW

**Review by tanaya-mankad — COMMENTED** [review]
1. When _exe_ linked PUBLIC-ly to _lib_, all the `target_include_directories` from _lib_ were also available publicly to _exe_. It would be nice if all of _lib's_ header files could also be decoupled from the _exe_, but in the meantime one needed to be added explicitly to _exe's_ configuration. (Windows)
2. EnergyPlusData (the **state**) requires a destructor to be defined in a translation unit where all of its members have full type definitions, because its members are all unique_ptrs that require a std::default_deleter. We were getting away without it because CommonIncludes.hh was everywhere alongside EnergyPlusData.hh!
3. **state** creation moved inside the API where it won't conflict with anything, and unneeded headers removed from main.

**Comment by Myoldmopar** [comment]
@tanaya-bigladder it looks like the unit test binary is failing to build.  Right now it links to the dll, but really...I think it should just link directly to the static library, no need to go through the dll I think.  

You may already be well on your way toward that, and if so, please send this to /dev/null.  I thought it was at least worth a mention though.

Thanks!

**Comment by tanaya-mankad** [comment]
> 

Hi @Myoldmopar , thanks, that's exactly what I've ended up doing! (I'm just having some build issues on my local PC and didn't want to push the changes until I can be sure the CI will be happy.)

**Comment by Myoldmopar** [comment]
Awesome!  I'm actually so happy that's where you ended up too.  I've always thought it was odd that the unit tests were linking to the DLL, but things "worked", so it was tough to justify time digging into it.  This will be great.  If I can help test or anything, I'm happy to do it, and don't worry about pushing commits that may fail on CI, it's just part of the process in my view.

**Comment by tanaya-mankad** [comment]
Thanks, then I'll go ahead and push the changes. My goal was to try to isolate each component's linkage to either the LIB or the DLL (but not both), and that seems in line with your view!

**Comment by Myoldmopar** [comment]
@tanaya-bigladder let me know if there is anything I can help test or debug or anything on here.  I definitely want to get this great fix into this release.  We've got about 10 days to freeze, so it's not urgent, just let me know if I can do anything.  Thanks!

**Comment by tanaya-mankad** [comment]
Thanks @Myoldmopar - the current issue seems to be that LINK_WITH_PYTHON tests are directly using API functionality, which might be why the linkage for _all_ tests got set with that dependency. The Python tests are only built for Linux-like systems. So, my questions are:
1. Is it reasonable to set the dependencies one way for LINK_WITH_PYTHON and another for non-Python-api builds?
2. What caused the Python tests to be omitted from a Windows build and should they actually be unified (a separate Issue of course)

File: src/EnergyPlus/test_ep_as_library.cc [hunk 1]
```diff
@@ -63,16 +62,17 @@ void progress_callback_handler(int const progress)
 int main(int argc, char *argv[])
 {
     std::cout << "Using EnergyPlus as a library." << std::endl;
-    EnergyPlus::EnergyPlusData state;
-    StoreMessageCallback(state, message_callback_handler);
-    StoreProgressCallback(state, progress_callback_handler);
+    EnergyPlus::EnergyPlusData *state{reinterpret_cast<EnergyPlus::EnergyPlusData *>(stateNew())};
```
Comment (Myoldmopar) [inline src/EnergyPlus/test_ep_as_library.cc:65]: Could this line just be: `EnergyPlusState state = stateNew();`?  That's the way we have it in our API test code.

File: src/EnergyPlus/test_ep_as_library.cc [hunk 2]
```diff
@@ -63,16 +62,17 @@ void progress_callback_handler(int const progress)
...
+    StoreProgressCallback(*state, progress_callback_handler);
 
     int status(EXIT_FAILURE);
     if (argc < 2) {
         std::cout << "Call this with a path to run EnergyPlus as the only argument" << std::endl;
         return EXIT_FAILURE;
     } else {
-        status = RunEnergyPlus(state, argv[1]);
+        status = RunEnergyPlus(*state, argv[1]);
+        stateDelete(reinterpret_cast<EnergyPlusState>(state));
```
Comment (Myoldmopar) [inline src/EnergyPlus/test_ep_as_library.cc:75]: And if you declare the state variable as an `EnergyPlusState` alias type, then this should be doable with just `stateDelete(state)`, no reinterpret necessary.

File: tst/EnergyPlus/unit/CMakeLists.txt [hunk 3]
```diff
@@ -252,14 +252,14 @@ set(test_src
     ZoneTempPredictorCorrector.unit.cc
     main.cc)
 
-set(test_dependencies energyplusapi)
+set(test_dependencies energypluslib)
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/CMakeLists.txt:255]: Yep, this is better!

File: tst/EnergyPlus/unit/CMakeLists.txt [hunk 4]
```diff
@@ -252,14 +252,14 @@ set(test_src
...
 
 if(LINK_WITH_PYTHON)
   add_definitions("-DLINK_WITH_PYTHON")
   find_package(PythonLibs 3 REQUIRED)
   include_directories(${Python_INCLUDE_DIRS})
   if(CMAKE_HOST_UNIX)
-    list(APPEND test_src api/datatransfer.unit.cc)
+    #list(APPEND test_src api/datatransfer.unit.cc) # Requires API; will be moved
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/CMakeLists.txt:262]: Definitely, the tests here just need to be pulled into external API calling scripts.  We have a collection of those, thanks to @jmarrec, so the stuff in here may not even be necessary anymore.

**Review by Myoldmopar — APPROVED** [review]
So far this is looking like what I was expecting.  I'm glad the unit test suite will just be linked to the static lib, not the API.  It all makes sense.  Do you have more changes to make here or is this ready to go if CI is happy?

File: src/EnergyPlus/test_ep_as_library.cc (hunk 1 above)
Comment (tanaya-mankad) [reply src/EnergyPlus/test_ep_as_library.cc:65]: I started changing this and then realized that this file must have created an EnergyPlusData object rather than an EnergyPlusState because that's the type `StoreMessageCallback`, `StoreProgressCallback`, and `RunEnergyPlus` have to take as input arguments. So by using the DLL's creation mechanism (`stateNew`) we're stuck with a reinterpret_cast somewhere.

**Comment by mjwitte** [comment]
@tanaya-bigladder Anything more to add before this merges?

**Comment by tanaya-mankad** [comment]
@mjwitte No, it's complete from my end!
