### PR TITLE
Fix `Fan:ZoneExhaust` AFN validation 

### LINKED ISSUE #10660: `Fan:ZoneExhaust` node validation issue with Airflow Network
Issue overview
--------------
The defect file shows some validation issue with a `Fan:ZoneExhaust`. Its inlet node is part of a `NodeList`. It looks like a if statement is misplaced and triggers an error if the fan inlet node isn't the first one listed in the `NodeList` object, see below.

https://github.com/NREL/EnergyPlus/blob/52fee4b00a1d679d545dfaf69a3704227b11ff4c/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L11221-L11234

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: Latest develop

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [US+SF+CZ5B+hp+slab+IECC_2021_VRF.zip](https://github.com/user-attachments/files/16607912/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRF.zip)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request cre
ated (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------
 - Fixes #10660 
 - The defect file runs without (fatal) error in this branch

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 1]
```diff
@@ -11225,13 +11225,15 @@ namespace AirflowNetwork {
...
-                            }
+                        }
+                        if (!found) {
+                            ShowSevereError(m_state, format("{}Fan:ZoneExhaust is not defined in {}", RoutineName, CurrentModuleObject));
+                            ShowContinueError(
+                                m_state,
+                                format("The inlet node of the {} Fan:ZoneExhaust is not defined in the {}'s ZoneHVAC:EquipmentConnections",
+                                       m_state.dataZoneEquip->ZoneEquipList(j).EquipName,
+                                       m_state.dataZoneEquip->ZoneEquipConfig(j).ZoneName));
+                            ErrorsFound = true;
```
Comment (lymereJ) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:11236]: Moved this verification so it can be done _after_ iterating through all exhaust nodes.

File: tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc [hunk 2]
```diff
@@ -19752,6 +19759,60 @@ TEST_F(EnergyPlusFixture, AirflowNetwork_ZoneOrderTest)
...
+        "    Dehumidifier Outlet Node,!- Air Outlet Node Name",
+        "    50.16,                   !- Rated Water Removal {L/day}",
+        "    3.412,                   !- Rated Energy Factor {L/kWh}",
+        "    0.12036,                 !- Rated Air Flow Rate {m3/s}",
+        "    ZoneDehumidWaterRemoval, !- Water Removal Curve Name",
+        "    ZoneDehumidEnergyFactor, !- Energy Factor Curve Name",
+        "    ZoneDehumidPLFFPLR,      !- Part Load Fraction Correlation Curve Name",
+        "    10.0,                    !- Minimum Dry-Bulb Temperature for Dehumidifier Operation {C}",
+        "    32.0,                    !- Maximum Dry-Bulb Temperature for Dehumidifier Operation {C}",
+        "    0.0;                     !- Off-Cycle Parasitic Electric Load {W}",
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc:19780]: Add a dehumidifier to this test to create the same situation as the defect file (multiple exhaust nodes). The defect file uses a VRF terminal.

File: tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc [hunk 3]
```diff
@@ -19766,6 +19827,12 @@ TEST_F(EnergyPlusFixture, AirflowNetwork_ZoneOrderTest)
     state->afn->AirflowNetworkNodeData(2).EPlusNodeNum = 4;
     // Attic_Unit1
     state->afn->AirflowNetworkNodeData(3).EPlusNodeNum = 0;
+
+    // Check that the validation fails if the AFN exhaust fan is not well setup
+    int exhaustFanInletNodeIndex = state->afn->MultizoneCompExhaustFanData(1).InletNode;
+    state->afn->MultizoneCompExhaustFanData(1).InletNode = 6;
+    state->afn->ValidateExhaustFanInputOneTimeFlag = true;
+    EXPECT_THROW(state->afn->validate_exhaust_fan_input(), std::runtime_error);
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc:19835]: Mess with the exhaust fan node to make sure that the if statement that was moved still creates a fatal error.

**Review by lymereJ — COMMENTED** [review]
Code walkthrough.

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/AirflowNetwork/src/Solver.cpp:11236]: :+1: reasonable!

File: tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc (hunk 2 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc:19780]: Nice job just modifying an existing test here.

**Review by Myoldmopar — APPROVED** [review]
I'm happy with this, any objections?

**Comment by Myoldmopar** [comment]
No objections, and it's still clean when I pull in develop and test.  Thanks @lymereJ, merging.
