### PR TITLE
Fix excess fluid properties warnings leading to huge err file size

### LINKED ISSUE #10941: Fluid properties reports temperature out of range for every occurrence leading to very large err file size
### Issue overview

The err file can be very large when fluid properties are out of range. The issue is shown in example file PipeHeatTransfer_Outair.idf.

### Operating System (Multiple choices)

Windows

### Operating System Version

Windows 10

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

_No response_

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------

- Fixes #10941
- Corrects refactor issue with errors reported before recurring warnings start counting.

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/FluidProperties.cc [hunk 1]
```diff
@@ -4195,7 +4195,7 @@ namespace Fluid {
 
         // Error handling
         if (error != GlycolError::Invalid && !state.dataGlobal->WarmupFlag) {
-            df->glycolErrorLimits[(int)error] = this->errors[(int)error].count;
+            df->glycolErrorLimits[(int)error] = ++this->errors[(int)error].count;
```
Comment (rraustad) [inline src/EnergyPlus/FluidProperties.cc:4198]: Why is df->glycolErrorLimits[ ] even needed? Line 4201 could be:

    if (++this->errors[(int)error].count <= df->GlycolErrorLimitTest) {

**Comment by rraustad** [comment]
Thanks to CI for finding a defect file. PipeHeatTransfer_Outair shows the issue with a 71 kB err file. This branch shows a 4 kB error file:

    ** Warning ** GlycolProps::getSpecificHeat: Temperature is out of range (too low) for fluid [WATER] specific heat supplied values **
    **   ~~~   ** ..Called From:NodeReportingCalc:HTPIPE OUTLET NODE,Temperature=[-17.30], supplied data range=[0.00,125.00]
    **   ~~~   **  Environment=CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB, at Simulation time=01/21 00:00 - 00:15
    ** Warning ** GlycolProps::getDensity: Temperature is out of range (too low) for fluid [WATER] density **
    **   ~~~   ** ..Called From:NodeReportingCalc:HTPIPE OUTLET NODE,Temperature=[-17.30], supplied data range=[0.00,100.00]
    **   ~~~   **  Environment=CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB, at Simulation time=01/21 00:00 - 00:15
    ************* Simulation Error Summary *************
    *************
    ************* ===== Recurring Error Summary =====
    ************* The following recurring error messages occurred.
    *************
    *************  ** Warning ** GlycolProps::getSpecificHeat: Temperature out of range (too low) for fluid [WATER] specific heat **
    *************  **   ~~~   **   This error occurred 1 total times;
    *************  **   ~~~   **   during Warmup 0 times;
    *************  **   ~~~   **   during Sizing 0 times.
    *************  **   ~~~   **   Max=-17.300000 {C}  Min=-17.300000 {C}
    *************
    *************  ** Warning ** GlycolProps::getDensity: Temperature out of range (too low) for fluid [WATER] density **
    *************  **   ~~~   **   This error occurred 192 total times;
    *************  **   ~~~   **   during Warmup 0 times;
    *************  **   ~~~   **   during Sizing 0 times.
    *************  **   ~~~   **   Max=-17.300000 {C}  Min=-17.300000 {C}
    *************

File: src/EnergyPlus/FluidProperties.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/FluidProperties.cc:4198]: That's a fine question, but this definitely cleaned up those files.  I'm going to get this merged but if you want to continue investigating if glycolErrorLimits is really needed, that can happen later.

**Review by Myoldmopar — APPROVED** [review]
