### PR TITLE
Fix #11156 - WaterThermalTanks's GetWaterThermalTankInput should trap ErrorsFound and throw a FatalError

### LINKED ISSUE #11156: WaterThermalTanks.cc never traps ErrorsFound
### Issue overview

Stumbled across this by accidentally deleting the schedule object referenced in a WaterHeater:Mixed object. The simulation crashed. Watching in the debugger, `ErrorsFound` was set to true and returned by `getWaterHeaterMixedInputs` which is then returned by `GetWaterThermalTankInput` but it's never checked during a simulation. The return value is used in unit tests, but never even captured in the main code.

e.g. https://github.com/NREL/EnergyPlus/blob/acf7908bedc967ed80ec691f4441ec01702ec23c/src/EnergyPlus/WaterThermalTanks.cc#L135-L141

a. The simple fix is to change `GetWaterThermalTankInput` to `void` and add a fatal error at the end of `GetWaterThermalTankInput`, but this will break the unit tests that are checking the return value (about 26 occurrences).
b. Another option would be to wrap the approx 10 calls to `GetWaterThermalTankInput` with a function that checks the return value and throws a fatal error.

### Operating System (Multiple choices)

Any

### Operating System Version

any

### Version of EnergyPlus

25.2.0-acf7908 pre-release

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[WaterHeaterStandAlone-Error.idf.txt](https://github.com/user-attachments/files/21870636/WaterHeaterStandAlone-Error.idf.txt)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix #11156

### Description of the purpose of this PR

The defect file in DevSupport segfaults before fix. After fix it fatals out as expected.

```
$ $ep_build_rel/Products/energyplus -w $chig_epw -d out-new WaterHeaterStandAlone-Error.idf 
EnergyPlus Starting
EnergyPlus, Version 25.2.0-aa87688ddd, YMD=2025.08.26 11:08
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Program terminated: EnergyPlus Terminated--Error(s) Detected.
```

```
$ cat out-new/eplusout.err 
Program Version,EnergyPlus, Version 25.2.0-aa87688ddd, YMD=2025.08.26 11:08,
   ** Warning ** Version: in IDF="25.1" not the same as expected="25.2"
   ** Warning ** Version: in IDF="25.1" not the same as expected="25.2"
   ** Severe  ** getWaterHeaterMixedInputs: WaterHeater:Mixed = MIXED GAS TANK
   **   ~~~   ** Setpoint Temperature Schedule Name = HOT WATER XYZ SETPOINT TEMP SCHEDULE, item not found.
   **  Fatal  ** GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=getWaterHeaterMixedInputs: WaterHeater:Mixed = MIXED GAS TANK
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 2 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.08sec
```

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [x] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [x] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [x] If structural output changes, add to output rules file and add OutputChange label
 - [x] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 1]
```diff
@@ -4041,7 +4041,7 @@ bool getWaterTankStratifiedInput(EnergyPlusData &state)
     return ErrorsFound;
 }
 
-bool GetWaterThermalTankInput(EnergyPlusData &state)
+void GetWaterThermalTankInput(EnergyPlusData &state)
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.cc:4044]: void

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 2]
```diff
@@ -4902,7 +4902,9 @@ bool GetWaterThermalTankInput(EnergyPlusData &state)
         }
     } // get input flag
 
-    return ErrorsFound;
+    if (ErrorsFound) {
+        ShowFatalError(state, format("GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input."));
+    }
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.cc]: And throw

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 3]
```diff
@@ -732,7 +732,7 @@ TEST_F(EnergyPlusFixture, HPWHEnergyBalance)
     state->init_state(*state);
     state->dataEnvrn->StdRhoAir = 1.0;
 
-    ASSERT_FALSE(WaterThermalTanks::GetWaterThermalTankInput(*state));
+    WaterThermalTanks::GetWaterThermalTankInput(*state);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:735]: No need to wrap into "EXPECT_NO_THROW". We just rely on gtest catching the exception if needed. This is what we do in most tests right now

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 4]
```diff
@@ -1048,6 +1048,9 @@ TEST_F(EnergyPlusFixture, HPWHSizing)
     Real64 LatLoadMet = 0;
     HeatBalanceManager::GetZoneData(*state, ErrorsFound);
     ASSERT_FALSE(ErrorsFound);
+    DataZoneEquipment::GetZoneEquipmentData(*state);
+    ASSERT_FALSE(ErrorsFound);
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc]: Missing call to GetZoneEquipmentData here, GetWaterThermalTankInput would eventually  complain that ZoneEquipConfig isn't allocated

https://github.com/NREL/EnergyPlus/blob/acf7908bedc967ed80ec691f4441ec01702ec23c/src/EnergyPlus/WaterThermalTanks.cc#L1974-L1976

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 5]
```diff
@@ -1244,20 +1247,23 @@ TEST_F(EnergyPlusFixture, HPWHOutdoorAirMissingNodeNameWarning)
...
+        "   **   ~~~   ** When Inlet Air Configuration=\"OUTDOORAIRONLY\".",
+        "   **   ~~~   ** Outdoor Air Node Name and Exhaust Air Node Name must be specified.",
+        "   ** Severe  ** WaterHeater:HeatPump:PumpedCondenser=\"ZONE4HEATPUMPWATERHEATER\":",
+        "   **   ~~~   ** Heat pump water heater fan outlet node name does not match next connected component.",
+        "   **   ~~~   ** Fan outlet node name = ZONE4AIRINLETNODE",
+        "   **  Fatal  ** GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input.",
+        "   ...Summary of Errors that led to program termination:",
+        "   ..... Reference severe error count=2",
+        "   ..... Last severe error=WaterHeater:HeatPump:PumpedCondenser=\"ZONE4HEATPUMPWATERHEATER\":",
+    });
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:1265]: HPWHOutdoorAirMissingNodeNameWarning: change to capture the FatalError

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc [hunk 6]
```diff
@@ -4245,14 +4251,14 @@ TEST_F(EnergyPlusFixture, HPWH_Both_Pumped_and_Wrapped_InputProcessing)
...
-        "  ZoneAirOnly,             !- Inlet Air Configuration",
-        "  HPWHPumped Air Inlet Node,  !- Air Inlet Node Name",
-        "  HPWHPumped Air Outlet Node,  !- Air Outlet Node Name",
-        "  ,                        !- Outdoor Air Node Name",
-        "  ,                        !- Exhaust Air Node Name",
+        "  OutdoorAirOnly,          !- Inlet Air Configuration",
+        "  ,                        !- Air Inlet Node Name",
+        "  ,                        !- Air Outlet Node Name",
+        "  HPWHPumped Air Inlet Node, !- Outdoor Air Node Name",
+        "  HPWHPumped Air Outlet Node,!- Exhaust Air Node Name",
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:4257]: HPWH_Both_Pumped_and_Wrapped_InputProcessing: change to Outdoors so it doesn't fatal due to missing zone

Initial err stream

```
+   ** Severe  ** WaterHeater:HeatPump:PumpedCondenser=\"HPWHPUMPED\", not found
+   **   ~~~   ** Inlet Air Zone Name=\"ZONE1\".
+   ** Severe  ** WaterHeater:HeatPump:WrappedCondenser=\"HPWHWRAPPED\", not found
+   **   ~~~   ** Inlet Air Zone Name=\"ZONE1\".
+   ** Severe  ** WaterHeater:Mixed = HPWHPUMPED MIXED TANK:  Ambient Temperature Zone not found = ZONE1
+   ** Severe  ** WaterHeater:Stratified = HPWHWRAPPED STRATIFIED TANK:  Ambient Temperature Zone not found = ZONE1
+   ** Severe  ** WaterHeater:HeatPump:PumpedCondenser = HPWHPUMPED:
+   **   ~~~   ** ZoneHVAC:EquipmentList and ZoneHVAC:EquipmentConnections objects are required when Inlet Air Configuration is either ZoneAirOnly or ZoneAndOutdoorAir.
+   ** Severe  ** WaterHeater:HeatPump:WrappedCondenser = HPWHWRAPPED:
+   **   ~~~   ** ZoneHVAC:EquipmentList and ZoneHVAC:EquipmentConnections objects are required when Inlet Air Configuration is either ZoneAirOnly or ZoneAndOutdoorAir.
+   **  Fatal  ** GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input
```

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc (hunk 4 above)
Comment (rraustad) [reply tst/EnergyPlus/unit/WaterThermalTanks.unit.cc]: You need to remove the format from the new fatal at WaterThermalTanks.cc line 4906 so you might as well also remove line 1052 above since it doesn't do anything (i.e., GetZoneEquipmentData doesn't have the ErrorsFound argument so of course ErrorsFound is still false). Other than that this is good to go.

File: src/EnergyPlus/WaterThermalTanks.cc [hunk 7]
```diff
@@ -4902,7 +4902,9 @@ bool GetWaterThermalTankInput(EnergyPlusData &state)
         }
     } // get input flag
 
-    return ErrorsFound;
+    if (ErrorsFound) {
+        ShowFatalError(state, format("GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input."));
```
Comment (jmarrec) [inline src/EnergyPlus/WaterThermalTanks.cc]:
```suggestion
        ShowFatalError(state, "GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input.");
```

**Review by rraustad — APPROVED** [review]
Good to go.

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc (hunk 3 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:735]: Yep, let it fail if it's gonna fail.

File: tst/EnergyPlus/unit/WaterThermalTanks.unit.cc (hunk 5 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/WaterThermalTanks.unit.cc:1265]: This is fine, although in the future if you want to just match some small portion of it and not worry about the ERR formatting, you can use `compare_err_stream_substring`... :)

**Review by Myoldmopar — APPROVED** [review]
Nice.

**Comment by Myoldmopar** [comment]
All happy here with develop pulled in.  Thanks @jmarrec
