### PR TITLE
Fix circular include in BaseGroundTemperatureModel.hh

### LINKED ISSUE #9751: Circular Include Detected
Issue overview
--------------
 - [BaseGroundTemperatureModel.hh includes GroundTemperatureModelManager.hh](https://github.com/NREL/EnergyPlus/blob/3212070ad9d39a21d61bc705482e424f0694dec3/src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh#L54)
- [GroundTemperatureModelManager.hh includes BaseGroundTemperatureModel.hh](https://github.com/NREL/EnergyPlus/blob/3212070ad9d39a21d61bc705482e424f0694dec3/src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh#L61)

Build seems OK, but it should be cleaned up, something is wrong there.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: 3212070ad9d39a21d61bc705482e424f0694dec3

### PR DESCRIPTION
**Pull request by mitchute**
Pull request overview
---------------------
 - Fixes #9751 

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh [hunk 1]
```diff
@@ -51,7 +51,6 @@
 // EnergyPlus Headers
 #include <EnergyPlus/DataGlobals.hh>
 #include <EnergyPlus/EnergyPlus.hh>
-#include <EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh>
```
Comment (amirroth) [inline src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh:54]: Defect file? Unit test?

Comment (rraustad) [reply src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh:54]: What does the compiler do with this recursive code?

Comment (amirroth) [reply src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh:54]: It's not actually recursive because it is guarded by 

```cpp
#ifndef GROUND_TEMPERATURE_MODEL_MANAGER_hh_INCLUDED
```

So the second recursive include would just include a blank file and the recursion would terminate. If it were actually recursive, the preprocessor would probably complain.

Comment (Myoldmopar) [reply src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh:54]: For sure, it's compiling fine here, it's just that this indicates some weird coupled dependency, so it's nice to figure out why it is there, and remove if possible.  No defect files here sorry :laughing:

File: src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh [hunk 2]
```diff
@@ -74,20 +74,11 @@ namespace GroundTemperatureManager {
...
-                                                                "Site:GroundTemperature:Deep",
-                                                                "Site:GroundTemperature:FCfactorMethod",
-                                                                "Site:GroundTemperature:Undisturbed:Xing"});
-
     std::vector<std::shared_ptr<BaseGroundTempsModel>> groundTempModels;
 
     void clear_state() override
     {
-        this->groundTempModels.clear();
+        *this = GroundTemperatureManagerData();
```
Comment (mitchute) [inline src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh]: I was looking through the coverage test results and noticed that 1) none of these `clear_state` calls are appearing in the coverage results (though they surely have to be being hit), and 2) this one was inconsistent with the other `clear_state` calls. This fixes up this inconsistency.

File: src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh [hunk 3]
```diff
@@ -70,6 +70,15 @@ enum class GroundTempObjType
...
 
+constexpr std::array<std::string_view, static_cast<int>(GroundTempObjType::Num)> groundTempModelNamesUC = {
+    "SITE:GROUNDTEMPERATURE:UNDISTURBED:KUSUDAACHENBACH",
+    "SITE:GROUNDTEMPERATURE:UNDISTURBED:FINITEDIFFERENCE",
+    "SITE:GROUNDTEMPERATURE:BUILDINGSURFACE",
+    "SITE:GROUNDTEMPERATURE:SHALLOW",
+    "SITE:GROUNDTEMPERATURE:DEEP",
+    "SITE:GROUNDTEMPERATURE:FCFACTORMETHOD",
+    "SITE:GROUNDTEMPERATURE:UNDISTURBED:XING"};
+
```
Comment (mitchute) [inline src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh]: After making the `clear_state` change mentioned previously, my compiler started complaining about the `Array1D_string` member variable holding these. Something about "cannot be assigned because its copy assignment operator is implicitly deleted". 

So., I moved them to an array of `string_view` objects, which is the current recommendation for these things.

File: src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc [hunk 4]
```diff
@@ -100,7 +100,7 @@ FiniteDiffGroundTempsModel::FiniteDiffGTMFactory(EnergyPlusData &state, GroundTe
 
     // Search through finite diff models here
     std::string const cCurrentModuleObject =
-        state.dataGrndTempModelMgr->CurrentModuleObjects(static_cast<int>(GroundTempObjType::FiniteDiffGroundTemp));
+        static_cast<std::string>(groundTempModelNamesUC[static_cast<int>(GroundTempObjType::FiniteDiffGroundTemp)]);
```
Comment (mitchute) [inline src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc]: All of these ground temp models are hanging out on the `EnergyPlus` namespace. I should probably fix that at some point. Also, all of this business with pointers should probably be cleaned up at some point, too. 2015 @mitchute was too clever by half, it seems.

**Review by mitchute — COMMENTED** [review]
Nerd snipe over. Please review/merge.

File: src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh (hunk 2 above)
Comment (amirroth) [reply src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh]: Actually, we are using this now instead `new (this) GroundTemperatureManagerData();`. It calls the default constructor on `this` directly rather than allocating a new object and then assigning it to `this`.

File: src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh (hunk 3 above)
Comment (amirroth) [reply src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh]: `std::string` cannot be `constexpr`. That's what it was complaining about indirectly.

File: src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc (hunk 4 above)
Comment (amirroth) [reply src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc]: Don't cast this to a `std::string`. Keep `cCurrentModuleObject` as a `std::string_view` (input processor routines should accept it). You're not the only the one on that corner, there are all sorts of things in EnergyPlus that I would categorize as "too clever by half".

File: src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc [hunk 5]
```diff
@@ -83,30 +83,28 @@ namespace GroundTemperatureManager {
         // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
         GroundTempObjType objectType(GroundTempObjType::Invalid);
 
-        auto &CurrentModuleObjects = state.dataGrndTempModelMgr->CurrentModuleObjects;
-
         std::string objectType_str_UPPERCase = UtilityRoutines::MakeUPPERCase(objectType_str);
```
Comment (amirroth) [inline src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc]: Replace all of this with `getEnumerationValue`. That's what that is for.

File: src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc [hunk 6]
```diff
@@ -127,7 +127,7 @@ KusudaGroundTempsModel::KusudaGTMFactory(EnergyPlusData &state, GroundTempObjTyp
                 Real64 maxSurfTemp(-100); // Set low initially but will get updated
 
                 std::shared_ptr<BaseGroundTempsModel> shallowObj = GetGroundTempModelAndInit(
-                    state, state.dataGrndTempModelMgr->CurrentModuleObjects(static_cast<int>(GroundTempObjType::SiteShallowGroundTemp)), "");
+                    state, static_cast<std::string>(groundTempModelNamesUC[static_cast<int>(GroundTempObjType::SiteShallowGroundTemp)]), "");
```
Comment (amirroth) [inline src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc]: All of these should be left as `std::string_view`. If the function requires a `std::string const &` argument, change it to `std::string_view`.

File: src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc [hunk 7]
```diff
@@ -90,7 +90,7 @@ KusudaGroundTempsModel::KusudaGTMFactory(EnergyPlusData &state, GroundTempObjTyp
     // New shared pointer for this model object
     std::shared_ptr<KusudaGroundTempsModel> thisModel(new KusudaGroundTempsModel());
```
Comment (amirroth) [inline src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc:90]: FWIW I know you said this pointer stuff is "too cute by half". It's not. Pointers are the way to leverage inheritance and polymorphism, which I think should be possible to do here, since these are different implementations of ground temperature models that should all have similar APIs. The only thing that may be too cute by half here is the use of `shared_ptr`, which I am not sure is the right wrapper (I think `unique_ptr` might be more appropriate) or even necessary (memory management of these objects is not so complicated that it should require these wrappers).

File: src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc [hunk 8]
```diff
@@ -79,39 +97,11 @@ namespace GroundTemperatureManager {
...
-                   UtilityRoutines::MakeUPPERCase(CurrentModuleObjects(static_cast<int>(GroundTempObjType::SiteFCFactorMethodGroundTemp)))) {
-            objectType = GroundTempObjType::SiteFCFactorMethodGroundTemp;
-        } else if (objectType_str_UPPERCase ==
-                   UtilityRoutines::MakeUPPERCase(CurrentModuleObjects(static_cast<int>(GroundTempObjType::XingGroundTemp)))) {
-            objectType = GroundTempObjType::XingGroundTemp;
-        } else {
-            // Error out if no ground temperature object types recognized
-            ShowFatalError(state, "GetGroundTempsModelAndInit: Ground temperature object " + objectType_str + " not recognized.");
-        }
+        GroundTempObjType objectType =
```
Comment (Myoldmopar) [inline src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc:101]: Nice.

**Review by Myoldmopar — APPROVED** [review]
@mitchute thanks for the circular fix followed by lots of cleanups.  This is good stuff and certainly ready to go in.  A quick local build and then I'll merge.

**Comment by Myoldmopar** [comment]
All happy locally, merging this.  Thanks @mitchute
