### PR TITLE
Fix issues with meters reporting during warmup 

### LINKED ISSUE #11141: `Output:Diagnostics`'s `ReportDuringWarmup` option impact annual energy use
### Issue overview

The reported energy use for the defect file is different when `ReportDuringWarmup` is used:

With:
Image

Without:
Image

### Operating System (Multiple choices)

MacOS

### Operating System Version

15.5

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file
[defect_file.txt](https://github.com/user-attachments/files/22674226/defect_file.txt)

### PR DESCRIPTION
**Pull request by lymereJ**
Pull request overview
---------------------

- Fixes #11141

### Pull Request Author

 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/OutputProcessor.cc [hunk 1]
```diff
@@ -3396,7 +3396,8 @@ void UpdateDataandReport(EnergyPlusData &state, OutputProcessor::TimeStepType co
         }
 
         // Update meters on the TimeStep  (Zone)
-        if (op->meterValues.capacity() > 0) {
+        if (op->meterValues.capacity() > 0 and
+            (!state.dataSysVars->ReportDuringWarmup || (state.dataSysVars->ReportDuringWarmup and !state.dataGlobal->WarmupFlag))) {
```
Comment (rraustad) [inline src/EnergyPlus/OutputProcessor.cc]: When did we change to using `and` instead of `&&`?  Instead of holding off meter reporting I think the meters need to be reset after the warmup period (i.e., you shouldn't need to change this line). That must be done somewhere?

    // for simulations that last longer than a week, identify when the last year of the simulation is started
    if ((state.dataGlobal->DayOfSim > 365) && ((state.dataGlobal->NumOfDayInEnvrn - state.dataGlobal->DayOfSim) == 364) &&
        !state.dataGlobal->WarmupFlag) {
        DisplayString(state, "Starting last  year of environment at:  " + state.dataGlobal->DayOfSimChr);
        OutputReportTabular::ResetTabularReports(state);
    }

Comment (lymereJ) [reply src/EnergyPlus/OutputProcessor.cc]: I presume that this can be done with `ResetAccumulationWhenWarmupComplete`. A cursory search shows that it is not currently being used.

Comment (lymereJ) [reply src/EnergyPlus/OutputProcessor.cc]: I just pushed some changes to do the reset after the warmup period instead. Both this approach and the approach from the initial commit "fix" the issue: all non-HVAC end-use energy consumption is the same whether or not `ReportDuringWarmup` is used, but some of the HVAC end-use energy consumption is still slightly different. I'm not sure **yet** what the cause of it is. I tried a simpler model (without a plant loop) and don't see the issue, (i.e., with this fix the report energy use is identical whether or not `ReportDuringWarmup` is used). Thoughts?

Comment (rraustad) [reply src/EnergyPlus/OutputProcessor.cc]: I would start by reverting the initial change. Then look to see what meters have differences and find where those meters are reset (or not) after warmup.

Comment (lymereJ) [reply src/EnergyPlus/OutputProcessor.cc]: As far as I can tell they were not being reset after the warmup period, I could see large values associated with the meters right at the beginning of the simulation.

I pushed some changes to reset them after the warmup period and I get the same results as with the initial changes (i.e., much better than with develop, but still diffs for HVAC end-uses).

What's interesting is that the first few days of the simulation show identical results, they only start to deviate after about 10 days for the defect file. When I say that the results are different it's not just the reported meter values, but actual equipment level variables (fans, boiler, etc.). I'm not yet sure how resetting meters (or holding off from reporting) would lead to equipment behaving differently. I'll keep looking.

**Comment by nrel-bot-2** [comment]
@lymereJ @myoldmopar it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/SimulationManager.cc [hunk 2]
```diff
@@ -454,6 +454,9 @@ namespace SimulationManager {
                     state.dataReportFlag->cWarmupDay = fmt::to_string(state.dataReportFlag->NumOfWarmupDays);
                     DisplayString(state, "Warming up {" + state.dataReportFlag->cWarmupDay + '}');
                 } else if (state.dataGlobal->DayOfSim == 1) {
+                    if (state.dataSysVars->ReportDuringWarmup) {
+                        OutputProcessor::ResetAccumulationWhenWarmupComplete(state);
+                    }
```
Comment (lymereJ) [inline src/EnergyPlus/SimulationManager.cc:459]: Use (unused) existing function to reset the meters when warmup is complete.

File: tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc [hunk 3]
```diff
@@ -10079,7 +10098,11 @@ TEST_F(EnergyPlusFixture, AirLoopHVACDOAS_TestFanHeatAddeToCoolingCoilSize)
     // OA flow rate
     EXPECT_NEAR(state->dataUnitarySystems->unitarySys[0].m_MaxCoolAirVolFlow, 0.65598, 0.001);
     // Cooling capacity
-    EXPECT_NEAR(state->dataUnitarySystems->unitarySys[0].m_DesignCoolingCapacity, 24885.6323, 0.05);
+    EXPECT_NEAR(state->dataUnitarySystems->unitarySys[0].m_DesignCoolingCapacity, 24883.6371, 0.05);
+
+    // Check meter accumulation
+    // Lights are 1W so the meter should be 3600 [J] * 24 hours
+    EXPECT_TRUE(state->dataOutputProcessor->meters[4]->periodFinYrSM.Value == 3600 * 24);
```
Comment (lymereJ) [inline tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc:10105]: Piggy-back on an existing unit test; A 1 W light object is used to check that the meters are being reset.

**Review by lymereJ — COMMENTED** [review]
Code walk-through:

**Comment by lymereJ** [comment]
The defect file was updated to v25.2: [defect_file_252.txt](https://github.com/user-attachments/files/22674331/defect_file_252.txt).

When using this branch, the results are the same whether `ReportDuringWarmup` is selected as input or not.

image

These are the same results that we get when using `develop` and `ReportDuringWarmup` isn't selected.

File: src/EnergyPlus/SimulationManager.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/SimulationManager.cc:459]: Pretty slick placement of this meter reset. I would rather see this in UpdateMeters but it would require another flag and reset logic for that flag. So this is fine.

    if (state.dataGlobal->WarmupFlag) {
        state.dataOutputProcessor.resetMeters = true;         <- new flag
        return;
    }
    if (state.dataOutputProcessor.resetMeters) {
        ResetAccumulationWhenWarmupComplete(state);
        state.dataOutputProcessor.resetMeters = false;
    }

**Review by mitchute — APPROVED** [review]
This looks good. Tests all run and pass locally after pulling in develop. No need to do that again here. Merging.
