### PR TITLE
Correction of Calculation Error when using Multiple Swimming Pools

### LINKED ISSUE #9797: Using multiple SwimmingPool:Indoor objects gives unexpected results
Issue overview
--------------

I took this regression test: https://github.com/NREL/OpenStudio-resources/blob/1eaedc8590a23abf7d9f398d182cca5521ec2b39/model/simulationtests/swimmingpool_indoor.rb

It has 5 zones. The core zone has a swimming pool object attached to its floor, which I call "1Pool". I then added two variations:

* 2Pools: I split the floor surface of the core zone and added a second swimming pool object (by cloning the original swimming pool object and assigning it on an extra branch on the demand side of the heating loop)
* 2Pools2zones: I left the core zone swimming pool untouched, but I added a swimming pool object to the East perimeter zone

In both of these cases, one of the pools is meeting it's target pool water temperature setpoint, the other is not.

All pools have a temperature setpoint of 27°C.

image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 22.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9797
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #9797 
 - When using more than one swimming pool, a user noticed that the first swimming pool would not arrive at the desired setpoint while the second pool entered would.  This was noticed when the pools were in the same zone and even when they were in separate zones.  In the original defect description for #9797, the user provided both the input files and a graph of what was being seen.  The erroneous results were confirmed with the latest version of EnergyPlus.  After investigation of the problem, it was determined that there was a bug in the way that the two variables were being averaged over the zone time step and then assigned to other variables.  This was corrected, an the results after the fix was made show that the pool temperature was going to the setpoint temperature as expected (see #9797 conversation for graphs of pre- and post-fix results).  This work included both a unit test to verify the fix as well as a thorough review (edits and additions) of both the Input Output Reference and the Engineering Reference sections for the indoor swimming pool.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [X] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [X] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/SwimmingPool.cc [hunk 1]
```diff
@@ -1056,23 +1056,22 @@ void UpdatePoolSourceValAvg(EnergyPlusData &state, bool &SwimmingPoolOn) // .TRU
     // SUBROUTINE LOCAL VARIABLE DECLARATIONS:
     SwimmingPoolOn = false;
 
-    // If this was never allocated, then there are no radiant systems in this input file (just RETURN)
+    // If this was never allocated, then there are no swimming pools in this input file (just RETURN)
     for (int PoolNum = 1; PoolNum <= state.dataSwimmingPools->NumSwimmingPools; ++PoolNum) {
         if (!allocated(state.dataSwimmingPools->Pool(PoolNum).QPoolSrcAvg)) return;
```
Comment (Myoldmopar) [inline src/EnergyPlus/SwimmingPool.cc:1061]: QPoolSrcAvg shouldn't be a standalone array...right?  It should just be a plain Real64 sitting on the actual pool struct.  That would be one less array sitting out in state that has to be allocated, cleared, and checked.  I'd actually push to see that cleaned up here, or let me know why it shouldn't be that way.  While in there, I would encourage you to look for other things that are separately allocated but should just be member variables.  If you don't have time to do that for this bug fix, let me know and I could probably do it.

**Review by Myoldmopar — CHANGES_REQUESTED** [review]
The fix is great, but I'm marking it request changes because I think a small refactor is worthwhile here.  Let me know what you think @RKStrand

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
Per the iteration call, I will wait on my requests to be addressed as part of a follow-up PR.  Merging this one then, thanks @RKStrand

File: src/EnergyPlus/SwimmingPool.cc [hunk 2]
```diff
@@ -1056,23 +1056,22 @@ void UpdatePoolSourceValAvg(EnergyPlusData &state, bool &SwimmingPoolOn) // .TRU
...
                 SwimmingPoolOn = true;
+                state.dataHeatBalFanSys->QPoolSurfNumerator(SurfNum) = state.dataSwimmingPools->Pool(PoolNum).QPoolSrcAvg(SurfNum);
+                state.dataHeatBalFanSys->PoolHeatTransCoefs(SurfNum) = state.dataSwimmingPools->Pool(PoolNum).HeatTransCoefsAvg(SurfNum);
                 break; // DO loop
             }
         }
-
-        state.dataHeatBalFanSys->QPoolSurfNumerator = state.dataSwimmingPools->Pool(PoolNum).QPoolSrcAvg;
-        state.dataHeatBalFanSys->PoolHeatTransCoefs = state.dataSwimmingPools->Pool(PoolNum).HeatTransCoefsAvg;
     }
```
Comment (rraustad) [inline src/EnergyPlus/SwimmingPool.cc:1072]: @RKStrand this code is different now. Before the entire array was copied and now only the first surface with a non-zero value is copied (because of the break). Is that intentional?

Comment (RKStrand) [reply src/EnergyPlus/SwimmingPool.cc:1072]: @rraustad Thanks for taking a look at this.  This is all pretty subtle and because I'm also working on the ZeroSource and associated arrays, I was confused/concerned as soon as I saw your post.  In this case, because this is contained within a loop over all of the pools, this is actually correct for this bug.  There is only one surface that is valid for each pool (this should never been a loop in all honesty).  The problem with the array copy is that for any additional pools, the array copy overwrites valid information from the last pool which led to zeroes for vital, valid, non-zero information and causes the issue that the users noticed in this defect.  Basically, if you have more than one pool in an input file, then the last one always overwrites all the other ones and the pools do not control properly.

However, I am very glad you brought this up because with my work on the ZeroSource issue (#9926), I will need to be VERY careful about merging this file.  In fact, now that QPoolSrcAvg and HeatTransCoefsAvg should be a single value rather than an array, the looping over the surfaces is definitely not needed so that break should go away.  I will clean that up with the ZeroSource changes (no more loop).  Sound good?  I plan on flagging you for the potential review of #9926 so you can verify that I didn't forget.

Comment (rraustad) [reply src/EnergyPlus/SwimmingPool.cc:1072]: I'll have to rely on your expertise here for what is actually needed. I am happy to review the work though. Another question. Where you expting diffs from these changes? I would think if the example file(s) had only 1 pool then there would be no diffs.

**Comment by RKStrand** [comment]
No, I wasn't expecting any diffs.  As you pointed out, all of the input files have a single pool so the existing tests never tripped this problem.  It might be something to consider in the future--making sure that all models have multiple occurrences in a single file.
