### PR TITLE
Address AirloopHVAC:UnitarySystem CoolReheat Humidity Control Problem

### LINKED ISSUE #10016: AirloopHVAC:UnitarySystem (Single Zone CAV System) failed to control zone humidity
Issue overview
--------------
In the attached [example file](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/UnitarySystem_DXCoil_Dehumidification.IDF), I have a single zone (fitness center) with 24 hour single zone CAV system. The single zone CAV system is modeled with a DX Cooling Coil, Gas Heating Coil, Supply Fan  and Electric Dehumidification Reheat Coil. The zone temperature setpint is 70F(heating) - 80F (cooling), the zone max relative humidity setpoint is 50%. 

When I run designday simulation for all 12 months. I see the following issue:

**1.  The DX cooling coil sometimes jump to full speed running (run time fraction =1) when that is clearly not necessary. This gets the cooling coil outlet node air temperature to below freezing point. In the AirloopHVAC:UnitarySystem object, the minimum supply air temperature is set to 2 C.**

**Figure 1: June Designday Cooling Coil Run Time Fraction**
image

**Figure 2: June Designday Cooling Coil Outlet Node Temperature**
image

**This is especially severe in cooler months:
Figure 3: January Designday Cooling Coil Run Time Fraction**
image

**Figure 4: January Designday Cooling Coil Outlet Node Temperature**
image

**2.  As a consequence of the cooling coil operation, the zone relative humidity is not controlled to setpoint of 50%**

**Figure 5: June Designday Zone Relative Humidity**
image

**Figure 6: January Designday Zone Relative Humidity**
image

In cooler months, the high cooling coil run time fraction even can get the zone air temperature to below heating setpoint (21.1 C).
**Figure 7: January Zone Drybulb Temperature**
image

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (23.10)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X ] Defect file added ([list location of defect file here](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/UnitarySystem_DXCoil_Dehumidification.IDF))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Nigusse**
Pull request overview
---------------------
 - Fixes #10016
 - Fixes zone humidity control problem when a unitary system configured as a packaged air conditioner and the `Dehumidification Control Type` is `CoolReheat`. Previously `CoolReheat` de-humidification control was working only for Unitary System as a heat pump. 
 - 
**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -10420,7 +10420,7 @@ namespace UnitarySystems {
 
         if (this->m_SuppCoilExists) {
             if (this->m_DehumidControlType_Num == DehumCtrlType::CoolReheat) {
-                if (state.dataUnitarySystems->MoistureLoad < 0.0 && this->m_HeatPump) {
+                if (state.dataUnitarySystems->MoistureLoad < 0.0 && this->m_CoolCoilExists) {
```
Comment (Nigusse) [inline src/EnergyPlus/UnitarySystem.cc:10423]: The unitary system does not have to be a heat pump for zone humidity control to work. Instead, at least check if cooling coil exists. Maybe the cooling coil check is not necessary.

**Comment by Nigusse** [comment]
Comparison of the zone air temperature and relative humidity between develop and this branch for the defect file. Now the temperature and RH are controlled to the specified set-points.  

ZoneTempAndRH

**Comment by Nigusse** [comment]
Cooling Coil Run Time fraction illustrates that the coil in this branch is behaving as expected, instead of oscillating as shown for develop case. The same trend is observed for each of the 12 months design day runs.

CoolingCoilRunTimeFraction

File: src/EnergyPlus/UnitarySystem.cc (hunk 1 above)
Comment (Nigusse) [reply src/EnergyPlus/UnitarySystem.cc:10423]: The unitary system in this defect file has a packaged air-conditioner with single speed DX cooling coil, gas heating coil, and an electric supplemental heating coil serving a single zone. Since the system is not a heat pump the `CoolReheat` humidity control is not activated when there is moisture load.

Comment (rraustad) [reply src/EnergyPlus/UnitarySystem.cc:10423]: I think supp heat coils were originally added for heat pumps. This seems like a reasonable change to instead check for a cooling coil.

Comment (Myoldmopar) [reply src/EnergyPlus/UnitarySystem.cc:10423]: Thanks @Nigusse and @rraustad

**Comment by Myoldmopar** [comment]
Plots indicate things are working nicely.  This is good stuff.  Just some testing with latest develop to make sure the unit test is up to date (might need transition) and then this is good to go.

**Comment by Myoldmopar** [comment]
Everything is passing well with no changes, this is good to go.  Thanks @Nigusse
