### PR TITLE
Final path to Version 9.0

### LINKED ISSUE #6795: Windows install has old links in start menu shortcuts for example file lists
Issue overview
--------------
The links in the windows start menu shortcuts for the example file lists are broken, still pointing to the old spreadsheet versions.

image001

These should now point to
\ExampleFiles\ExampleFiles.html (and drop "spreadsheet" from the shortcut name)
\ExampleFiles\ExampleFiles-ObjectsLink.html

### Details
Some additional details for this issue (if relevant):
 - Platform Windows
 - Version of EnergyPlus v8.9.0
 - Helpdesk ticket number 12869

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #6919: Blank report name in Output:Table:SummaryReports results in fatal error with no error message identifying the problem
Issue overview
--------------
This object
```
Output:Table:SummaryReports,
    AnnualBuildingUtilityPerformanceSummary,  !- Report 1 Name
    ZoneHeatingSummaryMonthly,  !- Report 2 Name
    ZoneElectricSummaryMonthly,  !- Report 3 Name
    ZoneCoolingSummaryMonthly,  !- Report 4 Name
    SensibleHeatGainSummary, !- Report 5 Name
    ,!- Report 6 Name
    SpaceGainsMonthly,       !- Report 7 Name
    EnvelopeSummary,         !- Report 8 Name
    ObjectCountSummary,      !- Report 9 Name
    ComponentCostEconomicsSummary,  !- Report 10 Name
    AllSummary;              !- Report 11 Name
```
results in this error file
```
Program Version,EnergyPlus, Version 8.9.0-40101eaafd, YMD=2018.08.21 10:40,
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  0.14sec
```

Help desk ticket 13045 has blank meter names in Output:Table:Monthly and Output:Table:Annual

Output:Table:Monthly,
  Overall HVAC System Energy,  !- Name
  3,                       !- Digits After Decimal
  Cooling:Electricity,     !- Variable or Meter 1 Name
  SumOrAverage,            !- Aggregation Type for Variable or Meter 1
  ,                        !- Variable or Meter 2 Name
  SumOrAverage;            !- Aggregation Type for Variable or Meter 2

Output:Table:Annual,
  OUTPUT TABLE 1,          !- Name
  ,                        !- Filter
  ,                        !- Schedule Name
  ,                        !- Variable or Meter or EMS Variable or Field 1 Name
  ,                        !- Aggregation Type for Variable or Meter 1
  2,                       !- Digits After Decimal 1
  ,                        !- Variable or Meter or EMS Variable or Field 2 Name
  ,                        !- Aggregation Type for Variable or Meter 2
  2,                       !- Digits After Decimal 2
  ,                        !- Variable or Meter or EMS Variable or Field 3 Name
  ,                        !- Aggregation Type for Variable or Meter 3
  2,                       !- Digits After Decimal 3
  ,                        !- Variable or Meter or EMS Variable or Field 4 Name
  ,                        !- Aggregation Type for Variable or Meter 4
  2,                       !- Digits After Decimal 4
  ,                        !- Variable or Meter or EMS Variable or Field 5 Name
  ,                        !- Aggregation Type for Variable or Meter 5
  2,                       !- Digits After Decimal 5
  ,                        !- Variable or Meter or EMS Variable or Field 6 Name
  ,                        !- Aggregation Type for Variable or Meter 6
  2,                       !- Digits After Decimal 6
  ,                        !- Variable or Meter or EMS Variable or Field 7 Name
  ,                        !- Aggregation Type for Variable or Meter 7
  2,                       !- Digits After Decimal 7
  ,                        !- Variable or Meter or EMS Variable or Field 8 Name
  ,                        !- Aggregation Type for Variable or Meter 8
  2,                       !- Digits After Decimal 8
  ,                        !- Variable or Meter or EMS Variable or Field 9 Name
  ,                        !- Aggregation Type for Variable or Meter 9
  2,                       !- Digits After Decimal 9
  ,                        !- Variable or Meter or EMS Variable or Field 10 Name
  ,                        !- Aggregation Type for Variable or Meter 10
  2,                       !- Digits After Decimal 10
  ,                        !- Variable or Meter or EMS Variable or Field 11 Name
  ,                        !- Aggregation Type for Variable or Meter 11
  2,                       !- Digits After Decimal 11
  ,                        !- Variable or Meter or EMS Variable or Field 12 Name
  ,                        !- Aggregation Type for Variable or Meter 12
  2,                       !- Digits After Decimal 12
  ,                        !- Variable or Meter or EMS Variable or Field 13 Name
  ,                        !- Aggregation Type for Variable or Meter 13
  2,                       !- Digits After Decimal 13
  ,                        !- Variable or Meter or EMS Variable or Field 14 Name
  ,                        !- Aggregation Type for Variable or Meter 14
  2,                       !- Digits After Decimal 14
  ,                        !- Variable or Meter or EMS Variable or Field 15 Name
  ,                        !- Aggregation Type for Variable or Meter 15
  2;                       !- Digits After Decimal 15
Error file results:

Program Version,EnergyPlus, Version 9.0.0-63db0a5a1f, YMD=2018.08.24 09:46,
 ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
 ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
 ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
 ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
 ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min 11.61sec

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus v8.9.0
 - Unmethours [33505](https://unmethours.com/question/33505/energyplus-89-crashes-after-using-updated-88-idf-file/?comment=33608#post-id-33608)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached here 
[6919-1ZoneUncontrolled-v89.idf.txt](https://github.com/NREL/EnergyPlus/files/2307019/6919-1ZoneUncontrolled-v89.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by Myoldmopar**
Pull request overview
---------------------
This will be the final PR for version 9.0 sometime shortly.  Right now this PR:

 - Fixes #6795 (start menu links)
 - Incremental fix for #6919 (blank report names -- now they are fatal errors)
 - Updates README, other minor cleanups for release
 - Incremental fix for #6899 (blank cell instead of test message)

### CODE REVIEW

File: src/EnergyPlus/InputProcessing/InputProcessor.cc [hunk 1]
```diff
@@ -1461,7 +1461,11 @@ void InputProcessor::preScanReportingVariables()
         for (auto obj = epJSON_object.begin(); obj != epJSON_object.end(); ++obj) {
             json const &fields = obj.value();
             for (auto const &extensions : fields[extension_key]) {
-                addRecordToOutputVariableStructure("*", extensions.at("variable_or_meter_name"));
+                try {
```
Comment (Myoldmopar) [inline src/EnergyPlus/InputProcessing/InputProcessor.cc:1464]: @mjwitte The input processor was blindly assuming that the report names would be present here.  We could add in logic to test for the key then try to add the record, but in this case a try block is essentially the same process, and quicker.  This change simply allows the code to continue, blank records have no effect at this point.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 2]
```diff
@@ -868,6 +868,9 @@ namespace OutputReportTabular {
             // add to the data structure
             curTable = AddMonthlyReport(AlphArray(1), int(NumArray(1)));
             for (jField = 2; jField <= NumAlphas; jField += 2) {
+                if (AlphArray(jField).empty()) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/OutputReportTabular.cc:871]: Here, however, if the input field is blank, we throw a fatal error.  I confirmed this by editing some test files for the three objects: summary, monthly, and annual.  They all fatal error with this message indicating it was because of a blank report name.  Let me know if that seems reasonable @mjwitte, keeping in mind that we are short on time, and the current behavior is to silently crash with no explanation given.

File: src/Transition/InputRulesFiles/Rules8-9-0-to-9-0-0.md [hunk 3]
```diff
@@ -4,29 +4,54 @@ Input Changes
 This file documents the structural changes on the input of EnergyPlus that could affect interfaces, etc.
 This was previously an Excel workbook that made for very difficult version control, especially during busy times around code freezes.
 
-# Object Change: `Boiler:HotWater`
 
-The only change is for field F7, which was N3.  Logic to apply:
+# Object Change: `AirflowNetwork:Distribution:Component:OutdoorAirFlow`
```
Comment (Myoldmopar) [inline src/Transition/InputRulesFiles/Rules8-9-0-to-9-0-0.md:8]: This whole file just got kinda mangled, so this just reorders objects and cleans up spacing.

File: src/EnergyPlus/OutputReportTabular.cc (hunk 2 above)
Comment (mjwitte) [reply src/EnergyPlus/OutputReportTabular.cc:871]: I'd prefer if we could just skip blank names with no error, but if that's too complicated, then this is better than v8.9 behavior.

Comment (Myoldmopar) [reply src/EnergyPlus/OutputReportTabular.cc:871]: I'm not going to be able to get anything beyond this done for 9.0 myself.  I'll open up a follow-on ticket.

**Comment by Myoldmopar** [comment]
OK, I think CI might have gotten confused about which commit was HEAD on this branch, and it might be quite a while before it finishes.  Seeing Marvin have success with this branch makes me feel good enough.  I'm merging this, and the View3D PR, and I'm going to tag 9.0 RC1.  We'll get immediate feedback about the package situation and we'll have time this week to resolve any issues.  Goodnight, and happy building, CI!
