### PR TITLE
Fix logic for FlowFromSystem choice for ElectricEquipment:ITE:AirCooled

### LINKED ISSUE #7041: Suspect calculations in ElectricEquipment:ITE:AirCooled when Air Flow Calculation Method = FlowFromSystem
Issue overview
--------------
Working in branch ZoneAirFlow6574 in case this has already been corrected in develop.

Test file shows a break in the debugger for uninitialized variable in the CalcZoneITEq routine where TSupply is uninitialized.

    if (abs(TAirOut - TSupply) < SmallTempDiff) {
        TAirOut = TSupply;
    }

In GetInput this input sets FlowControlWithApproachTemps = false (which is redundant based on class constructor)

                // IT equipment design level calculation method.
                if (lAlphaFieldBlanks(3)) {
                    ZoneITEq(Loop).FlowControlWithApproachTemps = false;
                } else {
                    if (UtilityRoutines::SameString(AlphaName(3), "FlowFromSystem")) {
                        ZoneITEq(Loop).FlowControlWithApproachTemps = false;
                    } else if (UtilityRoutines::SameString(AlphaName(3), "FlowControlWithApproachTemperatures")) {
                        ZoneITEq(Loop).FlowControlWithApproachTemps = true;
                        Zone(ZoneITEq(Loop).ZonePtr).HasAdjustedReturnTempByITE = true;
                        Zone(ZoneITEq(Loop).ZonePtr).NoHeatToReturnAir = false;
                    } else {
                        ShowSevereError(RoutineName + CurrentModuleObject + "=\"" + AlphaName(1) + "\": invalid calculation method: " + AlphaName(3));
                        ErrorsFound = true;
                    }
                }

and later in GetInput checks are made for Supply Air Node Name (alpha 14) to ensure it is available when needed.

                if (lAlphaFieldBlanks(14)) {
                    if (ZoneITEq(Loop).AirConnectionType == ITEInletAdjustedSupply) {
                        ShowSevereError(RoutineName + CurrentModuleObject + ": " + AlphaName(1));
                        ShowContinueError("For " + cAlphaFieldNames(11) + "= AdjustedSupply, " + cAlphaFieldNames(14) +
                                          " is required, but this field is blank.");
                        ErrorsFound = true;
                    } else if (ZoneITEq(Loop).FlowControlWithApproachTemps) {
                        ShowSevereError(RoutineName + CurrentModuleObject + ": " + AlphaName(1));
                        ShowContinueError("For " + cAlphaFieldNames(3) + "= FlowControlWithApproachTemperatures, " + cAlphaFieldNames(14) +
                                          " is required, but this field is blank.");
                        ErrorsFound = true;
                    } else {
                        ZoneITEq(Loop).SupplyAirNodeNum = 0;
                    }

Then in the CalcZoneITEq routine checks are made for the specific configuration to set up local variables. Also, checks are made here in the Calc routine for SupplyNodeNum > 0 which should be done in GetInput or a one time Init to save execution time, these checks should be moved. Note here that for FlowControlWithApproachTemps = false and AirConnection == ITEInletZoneAirNode that TSupply is not initialized (last ELSE).

            if (ZoneITEq(Loop).FlowControlWithApproachTemps) {
                if (SupplyNodeNum != 0) {
                    TSupply = Node(SupplyNodeNum).Temp;
                    WSupply = Node(SupplyNodeNum).HumRat;
                } else {
                    ShowSevereError(RoutineName + ": ElectricEquipment:ITE:AirCooled " + ZoneITEq(Loop).Name);
                    ShowContinueError("Air Inlet Connection Type = AdjustedSupply but no Supply Air Node is specified.");
                    ShowFatalError("Program terminates due to above conditions.");
                }
                if (ZoneITEq(Loop).SupplyApproachTempSch != 0) {
                    TAirIn = TSupply + GetCurrentScheduleValue(ZoneITEq(Loop).SupplyApproachTempSch);
                } else {
                    TAirIn = TSupply + ZoneITEq(Loop).SupplyApproachTemp;
                }
                WAirIn = Node(SupplyNodeNum).HumRat;
            } else {
                if (AirConnection == ITEInletAdjustedSupply) {
                    if (SupplyNodeNum != 0) {
                        TSupply = Node(SupplyNodeNum).Temp;
                        WSupply = Node(SupplyNodeNum).HumRat;
                    } else {
                        ShowSevereError(RoutineName + ": ElectricEquipment:ITE:AirCooled " + ZoneITEq(Loop).Name);
                        ShowContinueError("Air Inlet Connection Type = AdjustedSupply but no Supply Air Node is specified.");
                        ShowFatalError("Program terminates due to above conditions.");
                    }
                    if (ZoneITEq(Loop).RecircFLTCurve != 0) {
                        RecircFrac = ZoneITEq(Loop).DesignRecircFrac * CurveValue(ZoneITEq(Loop).RecircFLTCurve, CPULoadSchedFrac, TSupply);
                    } else {
                        RecircFrac = ZoneITEq(Loop).DesignRecircFrac;
                    }
                    TRecirc = MAT(NZ);
                    WRecirc = ZoneAirHumRat(NZ);
                    TAirIn = TRecirc * RecircFrac + TSupply * (1.0 - RecircFrac);
                    WAirIn = WRecirc * RecircFrac + WSupply * (1.0 - RecircFrac);
                } else if (AirConnection == ITEInletRoomAirModel) {
                    // Room air model option not implemented yet
                    TAirIn = MAT(NZ);
                    WAirIn = ZoneAirHumRat(NZ);
                } else { // Default to ITEInletZoneAirNode
                    TAirIn = MAT(NZ);
                    WAirIn = ZoneAirHumRat(NZ);
                }

then comes the debugger issue for uninitialized variable

    if (abs(TAirOut - TSupply) < SmallTempDiff) {
        TAirOut = TSupply;
    }

this was corrected with a simple test and initialization at top of routine

        Real64 TSupply(0.0);                              // Supply air temperature [C]

            if ((SupplyNodeNum != 0) && abs(TAirOut - TSupply) < SmallTempDiff) {
                TAirOut = TSupply;
            }

however, later in Calc are these types of calculations which will be reported.

            ZoneSumTinMinusTSup(NZ) += (TAirIn - TSupply) * AirVolFlowRate;
            ZoneSumToutMinusTSup(NZ) += (TAirOut - TSupply) * AirVolFlowRate;

and later the report variables

        // Zone-level sensible heat index
        for (Loop = 1; Loop <= NumOfZones; ++Loop) {
            if (ZoneSumToutMinusTSup(Loop) != 0.0) {
                ZnRpt(Loop).ITEqSHI = ZoneSumTinMinusTSup(Loop) / ZoneSumToutMinusTSup(Loop);
            }
        }

So something needs to be done here to 1) protect against the unitialized variable, 2) move tests for SupplyNodeNum == 0 to GetInput, and 3) resolve the reporting when Air Flow Calculation Method = FlowFromSystem.

No defect file here, ITE object is:

ElectricEquipment:ITE:AirCooled,
  ATM 104_Misc. Equipment,           !- Name
  Server_Room,                !- Zone Name
  FlowFromSystem,                         !- Air Flow Calculation Method
  Watts/Unit,                             !- Design Power Input Calculation Method
  3000,                                   !- Watts per Unit {W}
  1,                                      !- Number of Units
  ,                                       !- Watts per Zone Floor Area {W/m2}
  ,                                       !- Design Power Input Schedule Name
  ,                                       !- CPU Loading  Schedule Name
  Schedule1,   !- CPU Power Input Function of Loading and Air Temperature Curve Name
  0,                                      !- Design Fan Power Input Fraction
  0.001,                                  !- Design Fan Air Flow Rate per Power Input {m3/s-W}
  Schedule2,   !- Air Flow Function of Loading and Air Temperature Curve Name
  Schedule3, !- Fan Power Input Function of Flow Curve Name
  15,                                     !- Design Entering Air Temperature {C}
  None,                                   !- Environmental Class
  ZoneAirNode,                            !- Air Inlet Connection Type
  ,                                       !- Air Inlet Room Air Model Node Name
  ,                                       !- Air Outlet Room Air Model Node Name
  ,                                       !- Supply Air Node Name
  ,                                       !- Design Recirculation Fraction
  Schedule4,   !- Recirculation Function of Loading and Supply Temperature Curve Name
  1,                                      !- Design Electric Power Supply Efficiency
  Schedule5, !- Electric Power Supply Efficiency Function of Part Load Ratio Curve Name
  1,                                      !- Fraction of Electric Power Supply Losses to Zone
  ITE-CPU,                                !- CPU End-Use Subcategory
  ITE-Fans,                               !- Fan End-Use Subcategory
  ITE-UPS;                                !- Electric Power Supply End-Use Subcategory

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by YanfeiNREL**
Pull request overview
---------------------
 - Fixes #7041
 - Initialize the TSupply; adding logic for FlowFromSystem choice for ElectricEquipment:ITE:AirCooled.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Label the PR with at least one of: Defect.

 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
**Line 6134, Line 6281 to 6295**

 - [ ] New unit test (required)
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
I made a fake input module to validate my work:
input_snapshot
I can run successfully as below:
Sucessful

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub

 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
an IDF input file is given here. (version 9.1)
[in.zip](https://github.com/NREL/EnergyPlus/files/3643367/in.zip)

### CODE REVIEW

**Comment by mjwitte** [comment]
@YanfeiNREL Is this urgent for v9.2 or can it wait until after release? There are some formatting problems.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 1]
```diff
@@ -6309,10 +6309,14 @@ namespace InternalHeatGains {
                     TAirIn = TRecirc * RecircFrac + TSupply * (1.0 - RecircFrac);
                     WAirIn = WRecirc * RecircFrac + WSupply * (1.0 - RecircFrac);
                 } else if (AirConnection == ITEInletRoomAirModel) {
-                    // Room air model option not implemented yet
+                    // Room air model option: TAirIn=TAirZone, according to EngineeringRef 17.1.4 (Yanfei Li, 09/05/2019)
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc]: And we don't tag lines with name and date - we let git history track that. Here and below.

Comment (YanfeiNREL) [reply src/EnergyPlus/InternalHeatGains.cc]: oh thanks. this is not urgent. We can wait after 9.2 release. I will fix the format issue then.

**Comment by nrel-bot-3** [comment]
@YanfeiNREL @lgentile it has been 28 days since this pull request was last updated.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 2]
```diff
@@ -6187,6 +6187,8 @@ namespace InternalHeatGains {
         Array1D<Real64> ZoneSumToutMinusTSup(NumOfZones); // Denominator for zone-level sensible heat index (SHI)
 
         std::map<int, std::vector<int>> ZoneITEMap;
+        
+	//int ZoneAirInletNode = DataZoneEquipment::ZoneEquipConfig(NZ).InletNode(1);
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc]: Delete this, please.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 3]
```diff
@@ -6309,10 +6311,14 @@ namespace InternalHeatGains {
...
-                    // Room air model option not implemented yet
+                    // Room air model option: TAirIn=TAirZone, according to EngineeringRef 17.1.4
                     TAirIn = MAT(NZ);
+		    TSupply = TAirIn;
                     WAirIn = ZoneAirHumRat(NZ);
-                } else { // Default to ITEInletZoneAirNode
+                } else { 
+		    // TAirIn = TRoomAirNodeIn, according to EngineeringRef 17.1.4
+		    int ZoneAirInletNode = DataZoneEquipment::ZoneEquipConfig(NZ).InletNode(1);
+		    TSupply = Node(ZoneAirInletNode).Temp;
```
Comment (mjwitte) [inline src/EnergyPlus/InternalHeatGains.cc]: The indentation is still not correct here. Looks like there may be tabs instead of spaces? Do you have clang format active in your development environment?

**Review by mjwitte — COMMENTED** [review]
@YanfeiNREL See comments below, and please merge in develop.

**Comment by mjwitte** [comment]
@YanfeiNREL Also, this needs a unit test.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 4]
```diff
@@ -6161,7 +6172,7 @@ namespace InternalHeatGains {
         Real64 OperSchedFrac;                             // Operating schedule fraction
         Real64 CPULoadSchedFrac;                          // CPU loading schedule fraction
         Real64 AirConnection;                             // Air connection type
-        Real64 TSupply;                                   // Supply air temperature [C]
+        Real64 TSupply(0.0);                              // Supply air temperature [C]
```
Comment (Myoldmopar) [inline src/EnergyPlus/InternalHeatGains.cc:5653]: Applying clang format resulted in quite a lot of changes, but this is one of the functional changes.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 5]
```diff
@@ -6309,10 +6322,14 @@ namespace InternalHeatGains {
...
-                    // Room air model option not implemented yet
+                    // Room air model option: TAirIn=TAirZone, according to EngineeringRef 17.1.4
                     TAirIn = MAT(NZ);
+                    TSupply = TAirIn;
                     WAirIn = ZoneAirHumRat(NZ);
-                } else { // Default to ITEInletZoneAirNode
+                } else {
+                    // TAirIn = TRoomAirNodeIn, according to EngineeringRef 17.1.4
+                    int ZoneAirInletNode = DataZoneEquipment::ZoneEquipConfig(NZ).InletNode(1);
+                    TSupply = Node(ZoneAirInletNode).Temp;
```
Comment (Myoldmopar) [inline src/EnergyPlus/InternalHeatGains.cc:5794]: Applying clang format resulted in quite a lot of changes, but this section is one of the functional changes.

**Comment by nrel-bot-2b** [comment]
@YanfeiNREL @lgentile it has been 28 days since this pull request was last updated.

**Comment by mjwitte** [comment]
@YanfeiNREL What's the status on this PR? It still needs a unit test and it now has conflicts now.

**Comment by YanfeiNREL** [comment]
Thanks for reminder. Let me check/spend some time and finish it next week. @mjwitte

**Comment by nrel-bot-2** [comment]
@YanfeiNREL it has been 8 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@YanfeiNREL @mjwitte I used the Github online conflict resolver to pull develop in.  The conflicts appeared to just be conflicting between @lefticus changes to I/O and the formatting change that was applied here.  In any case, this would still need a unit test.  Given how much time we have left prior to release, I'm going to mark this for the next E+ release, but if we can get it done this week, it can certainly still drop in now.

**Comment by nrel-bot-3** [comment]
@YanfeiNREL @lgentile it has been 29 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@YanfeiNREL @lgentile it has been 28 days since this pull request was last updated.

**Comment by mitchute** [comment]
@rraustad I think this now addresses the items you noted in the original issue (#7041). If you and CI are satisfied, I'll move on to unit tests, and maybe a few other general cleanups.

**Comment by rraustad** [comment]
From a quick review it looks like Tsupply is accounted for with all ITE equipment types.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 6]
```diff
@@ -6012,9 +6008,10 @@ namespace InternalHeatGains {
         } // ZoneITEq calc loop
 
         // Zone-level sensible heat index
-        for (Loop = 1; Loop <= NumOfZones; ++Loop) {
-            if (ZoneSumToutMinusTSup(Loop) != 0.0) {
-                ZnRpt(Loop).ITEqSHI = ZoneSumTinMinusTSup(Loop) / ZoneSumToutMinusTSup(Loop);
+        for (Loop = 1; Loop <= NumZoneITEqStatements; ++Loop) {
+            int ZN = ZoneITEq(Loop).ZonePtr;
+            if (ZoneSumToutMinusTSup(ZN) != 0.0) {
+                ZnRpt(ZN).ITEqSHI = ZoneSumTinMinusTSup(ZN) / ZoneSumToutMinusTSup(ZN);
```
Comment (rraustad) [inline src/EnergyPlus/InternalHeatGains.cc]: much better!

Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: Do these arrays really need to be allocated to NumOfZones ? Could just save that information with each ITE object?

    Array1D<Real64> ZoneSumTinMinusTSup(NumOfZones)
    Array1D<Real64> ZoneSumToutMinusTSup(NumOfZones)

Comment (mitchute) [reply src/EnergyPlus/InternalHeatGains.cc]: Yeah, that would be better. I'll address that.

Comment (mitchute) [reply src/EnergyPlus/InternalHeatGains.cc]: This was addressed here: d51577b49f74f35ed74d393323e8d73027baf6fe

File: src/EnergyPlus/DataHeatBalance.hh [hunk 7]
```diff
@@ -2565,6 +2565,9 @@ namespace DataHeatBalance {
         Real64 CO2Rate;
         Real64 GCRate;
 
+        Real64 SumTinMinusTSup;  // Numerator for zone-level sensible heat index (SHI)
```
Comment (mitchute) [inline src/EnergyPlus/DataHeatBalance.hh:2568]: Data in local arrays made member variables here.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 8]
```diff
@@ -150,15 +148,6 @@ namespace InternalHeatGains {
 
     static std::string const BlankString;
 
-    // SUBROUTINE SPECIFICATIONS FOR MODULE InternalHeatGains
```
Comment (mitchute) [inline src/EnergyPlus/InternalHeatGains.cc:153]: Lots of comment cleanups throughout.

File: src/EnergyPlus/InternalHeatGains.cc [hunk 9]
```diff
@@ -3879,14 +3844,25 @@ namespace InternalHeatGains {
...
                         ErrorsFound = true;
-                    } else {
-                        ZoneITEq(Loop).SupplyAirNodeNum = 0;
                     }
                 } else {
                     ZoneITEq(Loop).SupplyAirNodeNum = GetOnlySingleNode(
                         AlphaName(14), ErrorsFound, CurrentModuleObject, AlphaName(1), NodeType_Air, NodeConnectionType_Sensor, 1, ObjectIsNotParent);
                 }
 
+                // Post-assign-SupplyAirNode-check. may be redundant
```
Comment (mitchute) [inline src/EnergyPlus/InternalHeatGains.cc]: I need a second set of eyes here. This is only needed if there's a chance ```GetOnlySingleNode``` returns a 0. If it never returns 0, then this should not be needed.

**Review by mitchute — COMMENTED** [review]
Ready for review.

File: src/EnergyPlus/InternalHeatGains.cc (hunk 9 above)
Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: If Alpha(14) is not blank then GetOnlySingleNode won't return 0. It will either return the node number of a real supply air node in a zone, or a non-0 number representing the Alpha(14) string (which could be mis-spelled). What is more important is that the supply air node in the ITE object match a real zone supply node.

From 1ZoneDataCenterCRAC_wApproachTemp.idf:

    ElectricEquipment:ITE:AirCooled,
      Main Zone Inlet Node,    !- Supply Air Node Name

    ZoneHVAC:EquipmentConnections,
      Main Zone Inlet Node,    !- Zone Air Inlet Node or NodeList Name

Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: Maybe I have that backwards. If the node name is mis-spelled then it would return a 0. I'd have to test that to be sure.

Comment (mitchute) [reply src/EnergyPlus/InternalHeatGains.cc]: Thanks, @rraustad. I'll do some testing on that to confirm behavior.

Comment (mitchute) [reply src/EnergyPlus/InternalHeatGains.cc]: If it has to match a zone supply node, then shouldn't ```NodeConnectionType_ZoneInlet``` be the correct connection type in ```GetOnlySingleNode```?

Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: No, there has to be an inlet and an outlet for the same node name.

Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: I see, so they used `NodeConnectionType_Sensor` to avoid conflicts with the other inlet and outlet nodes using this same node name. The zone inlet node and the TU outlet node, and then this node used here which is the 3rd occurrence of this node name.

Comment (mitchute) [reply src/EnergyPlus/InternalHeatGains.cc]: I guess there's also ```ZodeConnectionType_ZoneNode```, which is what ```GetZoneEquipmentData``` is using to set the ```ZoneNode``` variable. I'm not sure if that would be better, or if it even matters for this.

It looks like we should be checking node number returned by ```GetOnlySingleNode``` against ```GetControlledZoneIndex```. If they don't match and the Air Node Connection Type == "AdjustedSupply" or the Calculation Method == "FlowControlWithApproachTemperatures", fatal. Otherwise, pass by, or maybe even throw a warning to say that the non-blank name given doesn't match any zone node names.

Comment (rraustad) [reply src/EnergyPlus/InternalHeatGains.cc]: Yes, but it's node number returned against the zone's `supply` air nodes.

Comment (mjwitte) [reply src/EnergyPlus/InternalHeatGains.cc]: @mitchute @rraustad `NodeConnectionType_Sensor` is correct here, because this object is only getting information from that node (if I remember correctly). Don't get hung up on the node connect types here, to confirm this is really a zone inlet node, query the pertinent `ZoneEquipConfig(ZoneNum).InletNode` (which is an array of inlet node nums).

Comment (mitchute) [reply src/EnergyPlus/InternalHeatGains.cc]: Thanks, @mjwitte. I did find the ```ZoneEquipConfig``` data and I think I've gotten the logic down. I'm working on unit tests now and hoping to push soon.

**Comment by mitchute** [comment]
This is ready for another review. I've run the tests locally on all three platforms and am not seeing any of the failures noted above. I think most of them are MTR file errors that have crept into CI, but the ```EnergyPlusFixture.AirTerminalSingleDuctMixer_SimFCU_ATMInletSideTest``` doesn't look to be related to that and I can't reproduce it. BND diffs are also unexpected, but the diffs are due to items being reordered so there isn't a net change on the files.

File: src/EnergyPlus/DataHeatBalance.hh (hunk 7 above)
Comment (Myoldmopar) [reply src/EnergyPlus/DataHeatBalance.hh:2568]: :+1:

File: src/EnergyPlus/InternalHeatGains.cc [hunk 10]
```diff
@@ -6006,9 +5978,10 @@ namespace InternalHeatGains {
         } // ZoneITEq calc loop
 
         // Zone-level sensible heat index
-        for (Loop = 1; Loop <= NumOfZones; ++Loop) {
-            if (ZoneSumToutMinusTSup(Loop) != 0.0) {
-                ZnRpt(Loop).ITEqSHI = ZoneSumTinMinusTSup(Loop) / ZoneSumToutMinusTSup(Loop);
+        for (Loop = 1; Loop <= NumZoneITEqStatements; ++Loop) {
+            int ZN = ZoneITEq(Loop).ZonePtr;
+            if (ZnRpt(NZ).SumToutMinusTSup != 0.0) {
+                ZnRpt(ZN).ITEqSHI = ZnRpt(NZ).SumTinMinusTSup / ZnRpt(NZ).SumToutMinusTSup;
```
Comment (Myoldmopar) [inline src/EnergyPlus/InternalHeatGains.cc:5984]: The `ZN` and `NZ` is a bit icky, but not too bad since `ZN` is contained to this section.

**Review by Myoldmopar — APPROVED** [review]
I don't have anything further on this.  I'll build/run it locally right quick, but assuming that's all good I'll merge it.

**Comment by Myoldmopar** [comment]
Built and ran tests locally, all good.  I'm going to merge this.  Thanks @YanfeiNREL and @mitchute and @rraustad.
