### PR TITLE
OA Systems with HXAssisted coils fail when both water and DX coils are used leading to invalid warnings and fatal error

### LINKED ISSUE #918: Improved error trapping for window constructions with between-glass shade/blind. (CR #6121)
## 
#### Description

main-MJW-delete 2nd failed window-noblinds-onegaslayer.err - Another crash, just deleted the windowblind layer but did not turn off the shade controls
12/2/2003 - MJW - Sent to FCW via e-mail.  

forrtl: severe (161): Program Exception - array bounds exceeded
Image              PC        Routine            Line        Source
EnergyPlus.exe     00AE78E8  SURFACEGEOMETRY_m        3408  SurfaceGeometry.f90

Input/Output --> test files\defect files\6121-NoBlinds-OneGasLayer
Weather --> DEU Munich IWEC
## 

External Ref: USR#1710, tempel@gebaeudephysik.de, 07Oct2003
Addressed in `03.12.20 V1.2.0.006` by F Winkelmann
Last build tested: `03.12.24 V1.2.0.007`

### LINKED ISSUE #10145: Outside air system using CoilSystem and both types of HX assisted coils cause false warnings
Issue overview
--------------
A user file has a false fatal error:

    ** Severe  ** CheckWaterCoilIsOnAirLoop: = Coil:Cooling:Water = GUID11_SYS4OAHXC-1_COOLING.
    **   ~~~   ** The water coil or coil system is neither on primary air branch nor on outdoor air system hence does not require 'Controller:WaterCoil' object.
    **   ~~~   ** Controller:WaterCoil = GUID11_SYS4OAHXC-1WATERCOILCONTROL. Invalid water controller entry.
    **  Fatal  ** Program terminated for previous condition.

This occurs because the HX assisted coils are not correctly read in.

The model first checks for the number of each type of HX assisted coils, either DX or water:

    NumHXAssistedDXCoils = state.dataInputProcessing->inputProcessor->getNumObjectsFound(state, "CoilSystem:Cooling:DX:HeatExchangerAssisted");
    NumHXAssistedWaterCoils =
        state.dataInputProcessing->inputProcessor->getNumObjectsFound(state, "CoilSystem:Cooling:Water:HeatExchangerAssisted");
    state.dataHVACAssistedCC->TotalNumHXAssistedCoils = NumHXAssistedDXCoils + NumHXAssistedWaterCoils;

Then loops through each. In this defect file there is 1 of each type. The code finds the first coil system.

    // Get the data for the Coil:DX:CoolingHeatExchangerAssisted objects
    CurrentModuleObject = "CoilSystem:Cooling:DX:HeatExchangerAssisted";

    for (HXAssistedCoilNum = 1; HXAssistedCoilNum <= NumHXAssistedDXCoils; ++HXAssistedCoilNum) {

Then looks for inputs in the water assisted coil model.

    // Get the data for the Coil:Water:CoolingHeatExchangerAssisted objects
    CurrentModuleObject = "CoilSystem:Cooling:Water:HeatExchangerAssisted";

However, here, the loop goes from 2 (NumHXAssistedDXCoils + 1) to 1 (NumHXAssistedWaterCoils) and skips this section.

    for (HXAssistedCoilNum = NumHXAssistedDXCoils + 1; HXAssistedCoilNum <= NumHXAssistedWaterCoils; ++HXAssistedCoilNum) {

This last loop should use:

    for (HXAssistedCoilNum = NumHXAssistedDXCoils + 1; HXAssistedCoilNum <= state.dataHVACAssistedCC->TotalNumHXAssistedCoils;
         ++HXAssistedCoilNum) {

This is why the simulation could not find the water coil. The work around for now is to use all the same type HX assisted coil models.

Once this issue is corrected there are several other warnings issued.

    ** Severe  ** GUID11_SYS4OAHXC-1_COOLING_PARENTHX with object type CoilSystem:Cooling:Water:HeatExchangerAssisted duplicates a name in object type CoilSystem:Cooling:Water:HeatExchangerAssisted
    ** Severe  ** AirLoopHVAC:OutdoorAirSystem has a duplicate field GUID12_SYS28OA SYSTEM CONTROLS
    ** Severe  ** AirLoopHVAC:OutdoorAirSystem has a duplicate field GUID12_SYS30OA SYSTEM CONTROLS
    ** Severe  ** AirLoopHVAC:OutdoorAirSystem has a duplicate field GUID12_SYS26OA SYSTEM CONTROLS
    ** Severe  ** AirLoopHVAC:OutdoorAirSystem has a duplicate field GUID12_SYS25OA SYSTEM CONTROLS
    ** Severe  ** AirLoopHVAC:OutdoorAirSystem has a duplicate field GUID12_SYS34OA SYSTEM CONTROLS
    ** Severe  ** AirLoopHVAC:OutdoorAirSystem has a duplicate field GUID11_SYS4OA SYSTEM CONTROLS

This results from the UnitarySystem factory getting called inside GetOutsideAirSysInputs where the UnitarySystem processes the CoilSystem:Cooling:Water:HeatExchangerAssisted object which processes the water cooling coil which calls a function that calls GetOutsideAirSysInputs again. The simulation also terminated with an exception.

The exception occurred here where DXCoilPartLoadRatio was attempted access before that array was allocated.

            } else if (CompanionCoilIndex > 0) {
                // VS coil issue here?
                HXPartLoadRatio = state.dataDXCoils->DXCoilPartLoadRatio(CompanionCoilIndex);
            }

and finally protecting the array access violation allowed the simulation to proceed.

            } else if (CompanionCoilIndex > 0 && !state.dataDXCoils->DXCoilPartLoadRatio.empty()) {
                // VS coil issue here?
                HXPartLoadRatio = state.dataDXCoils->DXCoilPartLoadRatio(CompanionCoilIndex);
            }

Issue and correction courtesy of Trane North America

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #10145
 - Corrects reading of CoilSystem:Cooling:Water:HeatExchangerAssisted when CoilSystem:Cooling:DX:HeatExchangerAssisted also exists in input file. Also corrects an issue with outdoor air systems using CoilSystem that can have invalid warnings and fatal error when one of these HXs is used in the outdoor air system and the other (CoilSystem:Cooling:Water:HeatExchangerAssisted) also exists.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by rraustad** [comment]
Defect file now runs successfully:

    ************* EnergyPlus Completed Successfully-- 670 Warning; 3 Severe Errors; Elapsed Time=00hr 03min 54.51sec

File: src/EnergyPlus/HVACHXAssistedCoolingCoil.cc [hunk 1]
```diff
@@ -611,12 +611,14 @@ namespace HVACHXAssistedCoolingCoil {
         // Get the data for the Coil:Water:CoolingHeatExchangerAssisted objects
         CurrentModuleObject = "CoilSystem:Cooling:Water:HeatExchangerAssisted";
 
-        for (HXAssistedCoilNum = NumHXAssistedDXCoils + 1; HXAssistedCoilNum <= NumHXAssistedWaterCoils; ++HXAssistedCoilNum) {
+        for (HXAssistedCoilNum = NumHXAssistedDXCoils + 1; HXAssistedCoilNum <= state.dataHVACAssistedCC->TotalNumHXAssistedCoils;
+             ++HXAssistedCoilNum) {
+            int thisWaterHXNum = HXAssistedCoilNum - NumHXAssistedDXCoils;
```
Comment (rraustad) [inline src/EnergyPlus/HVACHXAssistedCoolingCoil.cc:616]: This is the 2nd loop in getInput. If the input file had both flavors on HXAssisted coil, this loop was skipped. For example if there were one of each flavor the DX version would get read in and then here the Water version would be skipped.

    for (HXAssistedCoilNum = 2, HXAssistedCoilNum < 1; ++ HXAssistedCoilNum)

File: src/EnergyPlus/HeatRecovery.cc [hunk 2]
```diff
@@ -2612,7 +2612,7 @@ namespace HeatRecovery {
                 HXPartLoadRatio = max(0.0, HXPartLoadRatio);
                 HXPartLoadRatio = min(1.0, HXPartLoadRatio);
 
-            } else if (CompanionCoilIndex > 0) {
+            } else if (CompanionCoilIndex > 0 && !state.dataDXCoils->DXCoilPartLoadRatio.empty()) {
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.cc]: And a crash occurred here during issue investigation. An alternate approach would be to ensure the DX coil were read in prior to calling HeatRecovery. I chose to protect here instead of executing another call to an object's getInput (since that happened a lot in this file and caused the issue).

File: src/EnergyPlus/MixedAir.cc [hunk 3]
```diff
@@ -1050,8 +1050,6 @@ void GetOutsideAirSysInputs(EnergyPlusData &state)
                        OASys.ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::UnitarySystemModel ||
                        OASys.ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::DXSystem) {
                 OASys.ComponentIndex(CompNum) = CompNum;
-                OASys.compPointer[CompNum] =
-                    UnitarySystems::UnitarySys::factory(state, DataHVACGlobals::UnitarySys_AnyCoilType, OASys.ComponentName(CompNum), false, 0);
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:1054]: This caused a recursive loop. This factory call to UnitarySystem, to manage the CoilSystem object, which had a HXAssisted object as a child, called the UnitarySystem, which called the CoilSystem, which called the HXAssisted, which requested the controller name and index for the water coil, which called the OAControllers, which called the OASystem to wind up right back here ... because the OASystem getInput had not completed yet and `state.dataMixedAir->GetOASysInputFlag` was still true on subsequent mining calls within this call stack decsribed here. The fix was to move the call to the factory below after where `state.dataMixedAir->GetOASysInputFlag = false`. There may be a better fix for this but this seems to work as expected. As more components get scooped up into UnitarySystem I think we should keep an eye out for this type of recursive calling.

    if (state.dataMixedAir->GetOASysInputFlag) {
        GetOutsideAirSysInputs(state);
        state.dataMixedAir->GetOASysInputFlag = false;
    }

File: src/EnergyPlus/MixedAir.cc [hunk 4]
```diff
@@ -1094,6 +1092,19 @@ void GetOutsideAirSysInputs(EnergyPlusData &state)
...
+    for (int OASysNum = 1; OASysNum <= state.dataAirLoop->NumOASystems; ++OASysNum) {
+        for (int CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {
+            if (state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::CoilSystemWater ||
+                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::UnitarySystemModel ||
+                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::DXSystem) {
+                state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompNum] = UnitarySystems::UnitarySys::factory(
+                    state, DataHVACGlobals::UnitarySys_AnyCoilType, state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum), false, 0);
+            }
+        }
+    }
```
Comment (rraustad) [inline src/EnergyPlus/MixedAir.cc:1107]: Moved to the bottom of function GetOutsideAirSysInputs after ` state.dataMixedAir->GetOASysInputFlag = false;`

**Review by rraustad — COMMENTED** [review]
Walk-thru

File: src/EnergyPlus/HeatRecovery.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/HeatRecovery.cc]: The logic of this if/else if block seems flawed.

    if (!state.dataHeatRecovery->CalledFromParentObject) {
    } else if (CompanionCoilIndex > 0) {
    }

The SimHeatRecovery function determines how CalledFromParentObject is set using:

        if (present(HXUnitEnable)) {
            HXUnitOn = HXUnitEnable;
            //   When state.dataHeatRecovery->CalledFromParentObject is TRUE, this SIM routine was called by a parent object that passed in
            //   HXUnitEnable. HX will use the DX coil part-load ratio (optional CompanionCoilIndex must be present) or PLR passed in if not used with
            //   DX coil (optional CompanionCoilIndex must not be present).
            state.dataHeatRecovery->CalledFromParentObject = true;
        } else {
            //   HX is placed on a BRANCH, optional arguments are not passed in from SimAirServingZones.
            //   HX will calculate its own part-load ratio if optional HXUnitEnable flag is not present
            HXUnitOn = true;
            state.dataHeatRecovery->CalledFromParentObject = false;
        }

And if this DX coil is inside a HXAssisted object, that optional argument is always passed:

            HeatRecovery::SimHeatRecovery(state,
                                          thisHXCoil.HeatExchangerName,
                                          FirstHVACIteration,
                                          thisHXCoil.HeatExchangerIndex,
                                          FanOpMode,
                                          PartLoadRatio,
                                          HXUnitOn,

Which means the else if will be used at line 2615 above. This also means HXPartLoadRatio is determined by the coil object (line 2617 below). Except that for VS DX coils, the DXCoilPartLoadRatio array is not used. So since VS DX coils are allowed in the DX HXAssisted object, and CalledFromParentObject is always true for this configuration (i.e., the `else if` is hit), the model is either using the wrong PLR (assuming other non-VS DX coil exist), or there will be a crash. So I think the crash here revealed something much deeper than just array allocation timing.

    CoilSystem:Cooling:DX:HeatExchangerAssisted,
      A4 , \field Cooling Coil Object Type
           \required-field
           \type choice
           \key Coil:Cooling:DX
           \key Coil:Cooling:DX:SingleSpeed
           \key Coil:Cooling:DX:VariableSpeed

File: src/EnergyPlus/HeatRecovery.cc [hunk 5]
```diff
@@ -165,8 +165,8 @@ namespace HeatRecovery {
             }
         }
 
-        int CompanionCoilNum = present(CompanionCoilIndex) ? int(CompanionCoilIndex) : 0; // Index to companion cooling coil
-        int companionCoilType = present(CompanionCoilType_Num) ? int(CompanionCoilType_Num) : 0;
+        int CompanionCoilNum = present(CompanionCoilIndex) ? int(CompanionCoilIndex) : -1; // Index to companion cooling coil
+        int companionCoilType = present(CompanionCoilType_Num) ? int(CompanionCoilType_Num) : -1;
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.cc:169]: Use -1 to include new 0-indexed coil model

File: src/EnergyPlus/HeatRecovery.cc [hunk 6]
```diff
@@ -178,7 +178,7 @@ namespace HeatRecovery {
         } else {
             //   HX is placed on a BRANCH, optional arguments are not passed in from SimAirServingZones.
             //   HX will calculate its own part-load ratio if optional HXUnitEnable flag is not present
-            HXUnitOn = true;
+            HXUnitOn = (HXPartLoadRatio > 0.0);
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.cc]: If HXUnitOn is true then the HX gets modeled even when PLR = 0, and in this case calculates the Sensible Effectiveness and reports that data. Existing example files show SensEff = 0 when the HX is off so this change retains that result.

File: src/EnergyPlus/HeatRecovery.cc [hunk 7]
```diff
@@ -199,8 +199,16 @@ namespace HeatRecovery {
...
+            thisExch.CalcDesiccantBalancedHeatExch(state,
+                                                   HXUnitOn,
+                                                   FirstHVACIteration,
+                                                   FanOpMode,
+                                                   PartLoadRatio,
+                                                   CompanionCoilNum,
+                                                   companionCoilType,
+                                                   RegInIsOANode,
+                                                   EconomizerFlag,
+                                                   HighHumCtrlFlag);
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.cc:215]: Added companionCoilType as argument.

File: src/EnergyPlus/HeatRecovery.cc [hunk 8]
```diff
@@ -1494,10 +1502,9 @@ namespace HeatRecovery {
                 }
             }
 
-            if ((((CompanionCoilType_Num == DataHVACGlobals::CoilDX_CoolingSingleSpeed) ||
-                  (CompanionCoilType_Num == DataHVACGlobals::Coil_CoolingAirToAirVariableSpeed)) &&
-                 (CompanionCoilIndex > 0)) ||
-                ((CompanionCoilType_Num == DataHVACGlobals::CoilDX_Cooling) && (CompanionCoilIndex > -1))) {
+            if ((CompanionCoilIndex > -1) && ((CompanionCoilType_Num == DataHVACGlobals::CoilDX_CoolingSingleSpeed) ||
+                                              (CompanionCoilType_Num == DataHVACGlobals::Coil_CoolingAirToAirVariableSpeed) ||
+                                              (CompanionCoilType_Num == DataHVACGlobals::CoilDX_Cooling))) {
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.cc:1511]: Rearrainged conditionals using new default -1 instead of looking at > 0 for old coils and -1 for new coil.

File: src/EnergyPlus/HeatRecovery.cc [hunk 9]
```diff
@@ -2612,9 +2620,14 @@ namespace HeatRecovery {
...
-                // VS coil issue here?
-                HXPartLoadRatio = state.dataDXCoils->DXCoilPartLoadRatio(CompanionCoilIndex);
+            } else if (CompanionCoilType > 0 && CompanionCoilIndex > -1) {
+                if (CompanionCoilType == DataHVACGlobals::CoilDX_Cooling) {
+                    HXPartLoadRatio = state.dataCoilCooingDX->coilCoolingDXs[CompanionCoilIndex].partLoadRatioReport;
+                } else if (CompanionCoilType == DataHVACGlobals::Coil_CoolingAirToAirVariableSpeed) {
+                    HXPartLoadRatio = state.dataVariableSpeedCoils->VarSpeedCoil(CompanionCoilIndex).PartLoadRatio;
+                } else {
+                    HXPartLoadRatio = state.dataDXCoils->DXCoilPartLoadRatio(CompanionCoilIndex);
+                }
```
Comment (rraustad) [inline src/EnergyPlus/HeatRecovery.cc:2634]: Find correct coil PLR.

**Review by rraustad — COMMENTED** [review]
Updates to previous walk-thru

**Comment by rraustad** [comment]
To test this I dropped a CoilSystem:Cooling:DX on the AirloopHVAC branch upstream of the UnitarySystem. This is example file 5Zone_Unitary_HXAssistedCoil with Chicago Ohare weather. The CoilSystem:Cooling:DX does not control humidity ratio and uses a set point of 17 C at the outlet of the HX supply side (coil inlet node). This answer looks very good. Then looking at the UnitarySystem that also uses a DX HX assisted object using CoolReheat with a VS DX cooling coil it appears there is something wrong. The coil outlet temperature is very cold.

image

But if I look at the humidity ratios, that are controlling to 0.006, it's controlling perfectly. The problem here is that there is no lower limit on cooling coil outlet temperature, which is a problem, but outside the scope of this issue.

image

**Comment by rraustad** [comment]
The defect file still runs successfully without invalid warnings or crash. This should be ready for review and comment.

**Comment by nrel-bot-2b** [comment]
918-Invalid-warnings-and-fatal (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4: Tests Failed (0 of 0 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html'>Test Badge</a>

**Comment by nrel-bot-2b** [comment]
918-Invalid-warnings-and-fatal (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug: Tests Failed (0 of 0 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Test Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Coverage Badge</a>

**Comment by nrel-bot-2b** [comment]
918-Invalid-warnings-and-fatal (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug: Tests Failed (0 of 0 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Test Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Coverage Badge</a>

**Comment by Myoldmopar** [comment]
Ahhhh look at that, Decent CI messages showing up on the PR page!  Obviously still something wrong, but it's a step in the right direction.

**Comment by nrel-bot-2b** [comment]
918-Invalid-warnings-and-fatal (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4: OK (3318 of 3487 tests passed, 221 test warnings)

Messages:\n
 * 169 tests had: Table big diffs.
 * 199 tests had: AUD diffs.
 * 190 tests had: MDD diffs.
 * 194 tests had: MTD diffs.
 * 195 tests had: RDD diffs.
 * 167 tests had: Table small diffs.
 * 27 tests had: EIO diffs.
 * 20 tests had: ERR diffs.
 * 20 tests had: ESO big diffs.
 * 15 tests had: MTR big diffs.
 * 6 tests had: ESO small diffs.
 * 3 tests had: MTR small diffs.
 * 2 tests had: IDF diffs.

Failures:\n

regression Test Summary
 * Passed: 623
 * Failed: 169


<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html'>Test Badge</a>

**Comment by Myoldmopar** [comment]
Ahh that's good stuff, looks right to me, but we'd need to pull in develop to get a clean set of results.

**Comment by nrel-bot-2b** [comment]
918-Invalid-warnings-and-fatal (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug: OK (1900 of 1900 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Test Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Coverage Badge</a>

**Comment by nrel-bot-2b** [comment]
918-Invalid-warnings-and-fatal (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug: OK (776 of 776 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Test Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-fa1607effb2cd68f5467bc44168e1f198c7f2cf0-PR10144-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Coverage Badge</a>

**Comment by Myoldmopar** [comment]
When CI ran on this a month ago, it was 100% green and clean.  It got a little muddy while I was trying to convince Decent to report right on the PR page.  I'm not sure we need additional CI results.  I will be happy to run regressions locally on this.  @rraustad thanks for demonstrating the fix and providing all the evidence above, that's very helpful.

**Comment by Myoldmopar** [comment]
I pulled latest develop in just now and tested it out.  Everything is happy, Regressions are all clean.  Merging this one in.
