### PR TITLE
#9957 #9998 - get_construction_handle should be available to the EnergyPlus API and not limited to PythonPlugin + API fixes

### LINKED ISSUE #9957: get_construction_handle should be available to the EnergyPlus API and not limited to PythonPlugin
Issue overview
--------------

Given the location in the code and the time as which it was added, I think it may be a copy paste error that lead to `get_construction_handle` being limited to the PythonPlugin and not available to running as API. 
Around it are `get_global_handle` and `get_global_value` which do require a PythonPlugin::GlobalVariable to be defined in the IDF.

 I can't think of a reason why `get_construction_handle` would not allowed in run as API context, but I may be missing something

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 23.1.0
 - Unmethours link or helpdesk ticket number: https://unmethours.com/question/89960/energyplus-python-data-transfer-api-construction-handle/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9998: apiDataFullyReady has a very counter-intuitive return and does not match I/O reference docs
Issue overview
--------------

in C/C++:
* 0 means false
* anything (eg 1) means  true

`apiDataFullyReady` does the exact opposite

https://github.com/NREL/EnergyPlus/blob/af674b952fea904d4d0bb3af11166583e4444e37/src/EnergyPlus/api/datatransfer.cc#L125-L132

This leads to horrendous things to read like this comment: https://github.com/NREL/EnergyPlus/blob/af674b952fea904d4d0bb3af11166583e4444e37/tst/EnergyPlus/unit/api/datatransfer.unit.cc#L321

This also means that in this test, we actually NEVER get past this point and read the handles (the test does nothing):

https://github.com/NREL/EnergyPlus/blob/af674b952fea904d4d0bb3af11166583e4444e37/tst/EnergyPlus/api/TestDataTransfer.c#L64

The same code is in the I/O ref: https://github.com/NREL/EnergyPlus/blob/af674b952fea904d4d0bb3af11166583e4444e37/doc/input-output-reference/src/overview/api-usage.tex#L283

I suggest flipping the return, so that int can be converted to a bool properly

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): develop, af674b952fea904d4d0bb3af11166583e4444e37
 - Found while fixing #9957

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------
 - Fixes #9957 
 - Fixes #9998

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/api/datatransfer.cc [hunk 1]
```diff
@@ -126,9 +126,9 @@ int apiDataFullyReady(EnergyPlusState state)
 {
     auto *thisState = reinterpret_cast<EnergyPlus::EnergyPlusData *>(state);
     if (thisState->dataPluginManager->fullyReady) {
-        return 0;
+        return 1;
     }
-    return 1;
+    return 0;
```
Comment (jmarrec) [inline src/EnergyPlus/api/datatransfer.cc:131]: #9998

File: src/EnergyPlus/api/datatransfer.cc [hunk 2]
```diff
@@ -829,7 +829,7 @@ int getConstructionHandle(EnergyPlusState state, const char *constructionName)
             return handle;
         }
     }
-    return 0;
+    return -1; // return -1 if it wasn't found
```
Comment (jmarrec) [inline src/EnergyPlus/api/datatransfer.cc:832]: getConstructionHandle was returning 0 instead of -1, unlike other similar methods + the python user facing docs

https://github.com/NREL/EnergyPlus/issues/9998#issuecomment-1534398312

File: src/EnergyPlus/api/datatransfer.py [hunk 3]
```diff
@@ -608,8 +607,6 @@ def get_construction_handle(self, state: c_void_p, var_name: Union[str, bytes])
         :param var_name: Name of the construction to look up
         :return: An integer ID for this construction, or -1 if one could not be found.
         """
-        if not self.running_as_python_plugin:
-            raise EnergyPlusException("get_construction_handle is only available as part of a Python Plugin workflow")
```
Comment (jmarrec) [inline src/EnergyPlus/api/datatransfer.py:612]: Actual fix for #9957

File: tst/EnergyPlus/api/TestDataTransfer.c [hunk 4]
```diff
@@ -87,5 +112,9 @@ int main(int argc, const char *argv[])
     requestVariable(state, "SITE OUTDOOR AIR DRYBULB TEMPERATURE", "ENVIRONMENT");
     requestVariable(state, "SITE OUTDOOR AIR DEWPOINT TEMPERATURE", "ENVIRONMENT");
     energyplus(state, argc, argv);
+    if (handlesRetrieved == 0) {
+        fprintf(stderr, "We never got ANY handles\n");
+        return 1;
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.c:118]: This is to catch any problem getting the handle. Before any change, this was throwing!

File: tst/EnergyPlus/api/TestDataTransfer.c [hunk 5]
```diff
@@ -55,18 +55,35 @@
...
 int handlesRetrieved = 0;
 
 void afterZoneTimeStepHandler(EnergyPlusState state)
 {
     printf("STARTING A NEW TIME STEP\n");
     if (handlesRetrieved == 0) {
-        if (!apiDataFullyReady(state)) return;
+        if (!apiDataFullyReady(state)) {
+            return;
+        }
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.c:69]: Because here this would always return!

File: tst/EnergyPlus/api/TestDataTransfer.c [hunk 6]
```diff
@@ -55,18 +55,35 @@
...
         outdoorDewPointActuator = getActuatorHandle(state, "Weather Data", "Outdoor Dew Point", "Environment");
         outdoorTempSensor = getVariableHandle(state, "SITE OUTDOOR AIR DRYBULB TEMPERATURE", "ENVIRONMENT");
         outdoorDewPointSensor = getVariableHandle(state, "SITE OUTDOOR AIR DEWPOINT TEMPERATURE", "ENVIRONMENT");
-        printf("Got handles %d, %d, %d", outdoorDewPointActuator, outdoorTempSensor, outdoorDewPointSensor);
-        if (outdoorDewPointActuator == -1 || outdoorTempSensor == -1 || outdoorDewPointSensor == -1) {
+
+        zone1_wall1Actuator = getActuatorHandle(state, "Surface", "Construction State", "Zn001:Wall001");
+        wallConstruction = getConstructionHandle(state, "R13WALL");
+        floorConstruction = getConstructionHandle(state, "FLOOR");
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.c:76]: get construction handles

File: tst/EnergyPlus/api/TestDataTransfer.c [hunk 7]
```diff
@@ -78,6 +95,14 @@ void afterZoneTimeStepHandler(EnergyPlusState state)
...
     Real64 simTime = currentSimTime(state);
     printf("Current Sim Time: %0.2f \n", simTime);
+
+    if (oa_temp > 10) {
+        printf("Setting Zn001:Wall001 construction (%d) to R13WALL (%d)", zone1_wall1Actuator, wallConstruction);
+        setActuatorValue(state, zone1_wall1Actuator, wallConstruction);
+    } else {
+        printf("Setting Zn001:Wall001 construction (%d) to FLOOR (%d)", zone1_wall1Actuator, floorConstruction);
+        setActuatorValue(state, zone1_wall1Actuator, floorConstruction);
+    }
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.c:105]: dummy program

File: tst/EnergyPlus/api/TestDataTransfer.py [hunk 8]
```diff
@@ -102,4 +144,8 @@ def time_step_handler(state):
 api.exchange.request_variable(state, "SITE OUTDOOR AIR DEWPOINT TEMPERATURE", "ENVIRONMENT")
 # trim off this python script name when calling the run_energyplus function so you end up with just
 # the E+ args, like: -d /output/dir -D /path/to/input.idf
-api.runtime.run_energyplus(state, sys.argv[1:])
+return_code = api.runtime.run_energyplus(state, sys.argv[1:])
+if return_code != 0:
+    raise RuntimeError("E+ Simulation failed to run")
+if not ok:
+    raise RuntimeError('DataTransfer failed') from exception
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.py:151]: Similarly, before changing the control flow of the python test, any EnergyPlusException raised from python would just be swallowed silently by E+. You'd get LOOOOOOTS of messages written to the console. but the E+ suceeds, and the test too.

File: tst/EnergyPlus/api/TestDataTransfer.py [hunk 9]
```diff
@@ -57,31 +57,63 @@
...
+        if (
+            outdoor_temp_sensor == -1
+            or outdoor_dew_point_sensor == -1
+            or outdoor_dew_point_actuator == -1
+            or zone1_wall1_actuator_handle == -1
+            or wall_construction_handle == -1
+            or floor_construction_handle == -1
+        ):
+            ok = False
+            return
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.py:115]: changing the control flow + getting some construction handles

File: tst/EnergyPlus/api/TestDataTransfer.py [hunk 10]
```diff
@@ -93,6 +125,16 @@ def time_step_handler(state):
...
+    if oa_temp > 10:
+        print(
+            f"Setting Zn001:Wall001 construction ({zone1_wall1_actuator_handle}) to R13WALL ({wall_construction_handle}"
+        )
+        api.exchange.set_actuator_value(state, zone1_wall1_actuator_handle, wall_construction_handle)
+    else:
+        print(
+            f"Setting Zn001:Wall001 construction ({zone1_wall1_actuator_handle}) to FLOOR ({floor_construction_handle}"
+        )
+        api.exchange.set_actuator_value(state, zone1_wall1_actuator_handle, floor_construction_handle)
```
Comment (jmarrec) [inline tst/EnergyPlus/api/TestDataTransfer.py:137]: dummy program

File: tst/EnergyPlus/unit/api/datatransfer.unit.cc [hunk 11]
```diff
@@ -318,7 +318,8 @@ TEST_F(DataExchangeAPIUnitTestFixture, DataTransfer_TestListAllDataInCSV)
 TEST_F(DataExchangeAPIUnitTestFixture, DataTransfer_TestApiDataFullyReady)
 {
     // basically, the data should not be ready at the beginning of a unit test -- ever, so just check that for now
-    EXPECT_EQ(1, apiDataFullyReady((void *)this->state)); // 1 is false
+    EXPECT_EQ(0, apiDataFullyReady((void *)this->state)); // 0 is false
+    EXPECT_FALSE(apiDataFullyReady((void *)this->state));
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/api/datatransfer.unit.cc:322]: Doesn't that make more sense? The EXPECT_FALSE speaks for itself. Before changing the return of apiDataFullyReady that one would fail

File: src/EnergyPlus/api/datatransfer.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/api/datatransfer.cc:131]: Yeah.  I do agree this is more meaningful.  In my mind, 0 means success and 1 means failure, which translated to 0 being true and 1 being false.   I understand the confusion and I think I support this change.  But.  This will be a breaking change for any user programs which assume the other.  A correction, yes, but still a breaking change.

File: src/EnergyPlus/api/datatransfer.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/api/datatransfer.cc:832]: OK

File: src/EnergyPlus/api/datatransfer.py [hunk 12]
```diff
@@ -265,8 +265,7 @@ def api_data_fully_ready(self, state: c_void_p) -> bool:
         :param state: An active EnergyPlus "state" that is returned from a call to `api.state_manager.new_state()`.
         :return: Returns a boolean value to indicate whether variables, actuators, and other data are ready for access.
         """
-        success = self.api.apiDataFullyReady(state)
-        if success == 0:
+        if self.api.apiDataFullyReady(state) == 1:
```
Comment (Myoldmopar) [inline src/EnergyPlus/api/datatransfer.py:268]: I do like that the change is concealed inside the Python code so that the Python API doesn't change.  I would say that of the API consumers, it's surely like > 90% or 95%, maybe more.  We get very few questions about the C API, and I give almost zero demos/discussions about the C layer.  This definitely makes me feel better about this change.

File: src/EnergyPlus/api/datatransfer.py (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/api/datatransfer.py:612]: OK.  I don't recall exactly why I only had this in place for plugin applications.  But if it's working in your tests, I'm happy with this.

File: tst/EnergyPlus/api/TestDataTransfer.py (hunk 9 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/api/TestDataTransfer.py:115]: This is fine but a bit funny looking.  I think it would be nicer as:

```python
handles = [
    outdoor_temp_sensor,
    outdoor_dew_point_sensor,
    outdoor_dew_point_actuator,
    zone1_wall1_actuator_handle,
    wall_construction_handle,
    floor_construction_handle
]
if -1 in handles:
    ...
```

No need to change it here, just pointing out my preferred style.

File: tst/EnergyPlus/api/TestDataTransfer.py (hunk 10 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/api/TestDataTransfer.py:137]: :+1:

File: tst/EnergyPlus/api/TestDataTransfer.py (hunk 8 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/api/TestDataTransfer.py:151]: Got it.  Good catch.

File: tst/EnergyPlus/unit/api/datatransfer.unit.cc (hunk 11 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/api/datatransfer.unit.cc:322]: Yes, of course, it looks great now!

**Review by Myoldmopar — APPROVED** [review]
Yeah, it took me a minute to convince myself of the breaking change, but since it is just in the C API, which is much less utilized than the Python API, I can get behind it.  This looks good to go.

**Comment by Myoldmopar** [comment]
Everything tests happily, merging this one in.  Thanks for already having the APIChange label on there.
