### PR TITLE
Fix EMS control of shading surface transmittance

### LINKED ISSUE #5185: EMS Schedule actuator does not work with shading surface transmittance schedule
Helpdesk ticket 10763
User file has EMS program to actuate the transmittance schedule for a shading surface.  Results show that base schedule is always used, not the EMS actuated value.  This occurs even when the ShadowCalculation is TimestepFrequency.  

Traced the problem in the code to the use of LookUpScheduleValue here in [SolarShading](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L4334-L4345) instead of GetCurrentScheduleValue.  LookUpScheduleValue is used because shadowing calculations are often looking ahead and not using the current time, so it has an hour argument.

Possible fix is to use GetCurrentScheduleValue when TimestepFrequency is set.

No workaround is apparent.

Defect files in EnergyPlusDevSupport\DefectFiles\5000\5185

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes #5185 
 - If the transmittance schedule applied to a shading surface is always 1.0, the surface is tagged transparent and it is skipped during shading calculations. But there was no check to see if the schedule might be controlled by EMS or the like.
 -  Now if there is an EMS or ExternalActuator assigned to the schedule then the surface is not tagged as transparent and the global flags for `state.dataSolarShading->anyScheduledShadingSurface` and `state.dataSurface->ShadingTransmittanceVaries` are set to true. (These flags are used to generate warnings about incompatible ShadowCalculation settings.)
 - New functions were added to check the transmittance schedules for actuators. `SolarShading::checkShadingSurfaceSchedules` and `EMSManager:isScheduleManaged`.
 - If any Python plugin or API callbacks are active, it's not possible to tell if a particular schedule is acted on, so assume it's possible and set flags accordingly so that the schedule will be evaluated and used in the simulation. Added a new flag `state.dataGlobal->anyPluginsOrCallbacksInModel` for this.
 - Added a new warning about using Timestep shadow calculations if any shading surface schedules vary.
 - Modied the existing warnings about transparent shading surfaces, DetailedSkyDiffuseModeling, and PixelCounting with a scheduled shading surface.
 - Added EMS support to `ScheduleManager:LookUpScheduleValue` which is used in shading calculations (instead of the more common `GetCurrentScheduleValue`).
 - And finally, to avoid a lag, shading transmittance schedule overrides should use calling point `BeginZoneTimestepBeforeInitHeatBalance` which is before the shading calculations. The original defect file(s) were using `BeginTimestepBeforePredictor` which caused la ag of one zone timestep in the shading impact.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [x] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
Defect file ShadingControlTest4VX1_EMS1.idf (base schedule is always 1.0)
err diffs
```
-   ** Warning ** Shading:Building:Detailed="SHADINGVERTICALSOUTH", Transmittance Schedule Name="SH SOUTHTM", is always transparent.

+   ** Warning ** GetShadowingInput: The shading transmittance for shading devices may change throughout the year.
+   **   ~~~   ** Simulation has been reset to use DetailedSkyDiffuseModeling. Simulation continues.
+   **   ~~~   ** Choose DetailedSkyDiffuseModeling in the ShadowCalculation object to remove this warning.
```
Sunlit fraction was always 1.0, now varies with actuated schedule.
image

**Comment by rraustad** [comment]
So instead of this schedule setting the shading transmittance:

    Schedule:Constant,SH SouthTM,Fraction,1;

The EMS program sets the shading transmittance:

    EnergyManagementSystem:Program,
      ShadingControl,          !- Name
      SET SHSouthStatus=0,     !- Program Line 1
      SET wait=0,              !- Program Line 2
      SET wait=0,              !- <none>
      SET wait=0,              !- <none>
      SET wait=0,              !- <none>
      IF (DirSolRad>400)&&(LRoomTemp<26),  !- <none>
        SET wait=1,              !- <none>
        SET wait=1,              !- <none>
        SET wait=1,              !- <none>
        SET SHSouthStatus=1,     !- <none>
        SET wait=1,              !- <none>
      ENDIF;                   !- <none>

Question: If the EMS program sets shading transmittance to either 0 or 1, why in your figure is WF1:Surface Outside Face Sunlit Fraction not always 0 or 1? Are there times when the surface is not completely covered by the shading device?

**Comment by mjwitte** [comment]
> Question: If the EMS program sets shading transmittance to either 0 or 1, why in your figure is WF1:Surface Outside Face Sunlit Fraction not always 0 or 1? Are there times when the surface is not completely covered by the shading device?

Correct, the shading surface doesn't fully block WF1. Maybe the window surface is a better example. There's a different defect file on the way.

File: src/EnergyPlus/EMSManager.cc [hunk 1]
```diff
@@ -1619,6 +1623,24 @@ namespace EMSManager {
         return FoundControl;
     }
 
+    bool isScheduleManaged(EnergyPlusData &state, int const scheduleNum)
+    {
+        // Check if a specific schedule has an EMS or External Interface actuator assigned to it
+        bool foundControl = false;
```
Comment (rraustad) [inline src/EnergyPlus/EMSManager.cc]: If you have other changes, delete this line.

File: src/EnergyPlus/EMSManager.cc [hunk 2]
```diff
@@ -1619,6 +1623,24 @@ namespace EMSManager {
...
+        static constexpr std::string_view cControlTypeName = "SCHEDULE VALUE";
+        std::string_view cSchedName = state.dataScheduleMgr->Schedule(scheduleNum).Name;
+
+        for (int Loop = 1; Loop <= state.dataRuntimeLang->numActuatorsUsed + state.dataRuntimeLang->NumExternalInterfaceActuatorsUsed; ++Loop) {
+            if ((UtilityRoutines::SameString(state.dataRuntimeLang->EMSActuatorUsed(Loop).UniqueIDName, cSchedName)) &&
+                (UtilityRoutines::SameString(state.dataRuntimeLang->EMSActuatorUsed(Loop).ControlTypeName, cControlTypeName))) {
+                foundControl = true;
+                break;
```
Comment (rraustad) [inline src/EnergyPlus/EMSManager.cc]: return true; here

File: src/EnergyPlus/EMSManager.cc [hunk 3]
```diff
@@ -1619,6 +1623,24 @@ namespace EMSManager {
...
+            }
+        }
+
+        return foundControl;
```
Comment (rraustad) [inline src/EnergyPlus/EMSManager.cc]: and return false; here.

File: src/EnergyPlus/SolarShading.cc [hunk 4]
```diff
@@ -363,6 +365,32 @@ void InitSolarCalculations(EnergyPlusData &state)
...
+{
+    // Shading surfaces with a transmittance schedule that is always 1.0 are marked IsTransparent during shading surface input processing
+    // Now that EMS (and other types) actuators are set up, check to see if the schedule has an actuator and reset if needed
+    for (int surfNum = state.dataSurface->ShadingSurfaceFirst; surfNum <= state.dataSurface->ShadingSurfaceLast; ++surfNum) {
+        auto &thisSurface = state.dataSurface->Surface(surfNum);
+        if (!thisSurface.IsTransparent) continue;
+        if (state.dataGlobal->AnyEnergyManagementSystemInModel &&
+            (EMSManager::isScheduleManaged(state, thisSurface.SchedShadowSurfIndex) || state.dataGlobal->anyPluginsOrCallbacksInModel)) {
+            // Transmittance schedule defintely has an actuator or may have one via python plugin or API
+            // Set not transparent so it won't be skipped during shading calcs
```
Comment (rraustad) [inline src/EnergyPlus/SolarShading.cc:378]: Is it wise to include anyPluginsOrCallbacksInModel if you don't know if python or API acts on this surface?

Comment (mjwitte) [reply src/EnergyPlus/SolarShading.cc:378]: There's no way to know ahead of time if it will be acted on via Python or API, but if we don't assume that, then any code there will have zero impact. If the schedule is not acted on, the only extra cost is a `LookupScheduleValue` during the shading calcs. If the schedule value is 1.0, then the surface gets skipped.

**Comment by mjwitte** [comment]
Defect file ShadingControlTest4VX1_EMSMatchStdSched2.idf with EMS override should have the same results as ShadingControlTest4VX1_StdSched2.idf which uses a schedule without EMS override.

image

**Comment by mjwitte** [comment]
Defect file PythonPluginCustomSchedule-PlusShading.idf
err diffs
```
-   ** Warning ** Shading:Building:Detailed="SHADINGVERTICALSOUTH", Transmittance Schedule Name="SH SOUTHTM", is always transparent.

+   ** Warning ** GetShadowingInput: The shading transmittance for shading devices may change throughout the year.
+   **   ~~~   ** Simulation has been reset to use DetailedSkyDiffuseModeling. Simulation continues.
+   **   ~~~   ** Choose DetailedSkyDiffuseModeling in the ShadowCalculation object to remove this warning.

```

image

ThisBranch-PythonSchedule matches Develop-RegularSchedule. But these both look wrong compared to Develop-PythonSchedule (which is the same as if there was no shading surface at all). When the shading schedule is 0.8, the sunlit fraction is greater than if there were no shading surface at all. But that's for another issue and another PR.

File: src/EnergyPlus/DataGlobals.hh [hunk 5]
```diff
@@ -149,6 +149,7 @@ struct DataGlobal : BaseGlobalStruct
     bool AnyEnergyManagementSystemInModel = false; // true if there is any EMS or Erl in model.  otherwise false
     bool AnySurfPropOverridesInModel = false;      // true if there is any EMS or Erl overriding the surface properties for any surface.
     bool AnyConstrOverridesInModel = false;        // true if there is any EMS or Erl overriding the constructions for any surface.
+    bool anyPluginsOrCallbacksInModel = false;     // true if there is any plugin or active callback
```
Comment (mjwitte) [inline src/EnergyPlus/DataGlobals.hh:152]: New global

File: src/EnergyPlus/DataSurfaces.hh [hunk 6]
```diff
@@ -1267,7 +1267,7 @@ struct SurfacesData : BaseGlobalStruct
     int BuildingShadingCount = 0;    // Total number of Building External Shades
     int FixedShadingCount = 0;       // Total number of Fixed External Shades
     int AttachedShadingCount = 0;    // Total number of Shades attached to Zones
-    int ShadingSurfaceFirst = -1;    // Start index of shading surfaces (Building External Shades, Fixed External Shades and Shades attached to Zone)
+    int ShadingSurfaceFirst = 0;     // Start index of shading surfaces (Building External Shades, Fixed External Shades and Shades attached to Zone)
     int ShadingSurfaceLast = -1;     // End index of shading surfaces (Building External Shades, Fixed External Shades and Shades attached to Zone)
```
Comment (mjwitte) [inline src/EnergyPlus/DataSurfaces.hh:1271]: Defaults should be such that a for loop on `ShadingSurfaceFirst` to `ShadingSurfaceLast` should be skipped.

File: src/EnergyPlus/EMSManager.cc [hunk 7]
```diff
@@ -221,6 +221,10 @@ namespace EMSManager {
             state.dataGlobal->AnyEnergyManagementSystemInModel = false;
         }
 
+        if ((numPythonPlugins + numActiveCallbacks) > 0) {
+            state.dataGlobal->anyPluginsOrCallbacksInModel = true;
```
Comment (mjwitte) [inline src/EnergyPlus/EMSManager.cc:225]: Set the new global.

File: src/EnergyPlus/EMSManager.cc [hunk 8]
```diff
@@ -1619,6 +1623,21 @@ namespace EMSManager {
         return FoundControl;
     }
 
+    bool isScheduleManaged(EnergyPlusData &state, int const scheduleNum)
```
Comment (mjwitte) [inline src/EnergyPlus/EMSManager.cc:1626]: New function to check is a schedule is managed by EMS or ExternalInterface.

File: src/EnergyPlus/ScheduleManager.cc [hunk 9]
```diff
@@ -2821,9 +2792,17 @@ namespace ScheduleManager {
             state.dataScheduleMgr->ScheduleInputProcessed = true;
         }
 
+        if (state.dataScheduleMgr->Schedule(ScheduleIndex).EMSActuatedOn) {
+            return state.dataScheduleMgr->Schedule(ScheduleIndex).EMSValue;
```
Comment (mjwitte) [inline src/EnergyPlus/ScheduleManager.cc:2796]: Add EMS support to `LookUpScheduleValue`.

File: src/EnergyPlus/ScheduleManager.cc [hunk 10]
```diff
@@ -2821,9 +2792,17 @@ namespace ScheduleManager {
...
+        }
+
         //  so, current date, but maybe TimeStep added
 
         // Hourly Value
+        if (ThisHour > 24) {
```
Comment (mjwitte) [inline src/EnergyPlus/ScheduleManager.cc:2802]: Move this later after other ifs with returns.

File: src/EnergyPlus/SolarShading.cc [hunk 11]
```diff
@@ -363,6 +365,32 @@ void InitSolarCalculations(EnergyPlusData &state)
     state.dataSolarShading->firstTime = false;
 }
 
+void checkShadingSurfaceSchedules(EnergyPlusData &state)
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:368]: New function to check shading surface transmittance schedules and issues warnings, runs after EMS input is processed.

File: src/EnergyPlus/SolarShading.cc [hunk 12]
```diff
@@ -715,17 +743,23 @@ void GetShadowingInput(EnergyPlusData &state)
         }
     }
 
+    if (!state.dataSysVars->DetailedSolarTimestepIntegration && state.dataSurface->ShadingTransmittanceVaries &&
+        state.dataHeatBal->SolarDistribution != DataHeatBalance::Shadowing::Minimal) {
+
+        ShowWarningError(state, "GetShadowingInput: The shading transmittance for shading devices may change throughout the year.");
+        ShowContinueError(state,
+                          format("Choose Shading Calculation Update Frequency Method = Timestep in the {} object to capture all shading impacts.",
```
Comment (mjwitte) [inline src/EnergyPlus/SolarShading.cc:751]: New warning to use TimeStep shading calcs.

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 13]
```diff
@@ -341,7 +341,7 @@ namespace SurfaceGeometry {
         state.dataSurface->BuildingShadingCount = 0;
         state.dataSurface->FixedShadingCount = 0;
         state.dataSurface->AttachedShadingCount = 0;
-        state.dataSurface->ShadingSurfaceFirst = -1;
+        state.dataSurface->ShadingSurfaceFirst = 0;
         state.dataSurface->ShadingSurfaceLast = -1;
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:345]: Not sure why these are being set to the initial values here, but left them just to be safe.

**Review by mjwitte — COMMENTED** [review]
Code walkthru

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 14]
```diff
@@ -10771,3 +10773,561 @@ TEST_F(EnergyPlusFixture, Test_Rotational_Azimuth_Diffs)
...
+    GetZoneData(*state, ErrorsFound); // read zone data
+    EXPECT_FALSE(ErrorsFound);        // expect no errors
+
+    SetupZoneGeometry(*state, ErrorsFound);
+    SolarShading::checkShadingSurfaceSchedules(*state);
+    std::string const error_string = delimited_string(
+        {"   ** Warning ** Shading Surface=\"SITESHADE:FLATSHADESURFACE\", Transmittance Schedule Name=\"ALWAYSONE\", is always transparent.",
+         "   **   ~~~   ** This shading surface will be ignored.",
+         "   ** Warning ** Shading Surface=\"ZONESHADE:LIVING:SOUTH:SHADE002\", Transmittance Schedule Name=\"ALWAYSONE\", is always transparent.",
+         "   **   ~~~   ** This shading surface will be ignored."});
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:11061]: The 2 shading surfaces with schedule = 1 show a warning. Makes sense.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 15]
```diff
@@ -10771,3 +10773,561 @@ TEST_F(EnergyPlusFixture, Test_Rotational_Azimuth_Diffs)
...
+                                                                  "BuildingShade:TiltedShadeSurface2",
+                                                                  "SiteShade:FlatShadeSurface2"};
+    static constexpr std::array<bool, 8> isTransparent{false, true, false, false, false, true, false, false};
+
+    for (int surf = 0; surf < 8; ++surf) {
+        int surfNum = UtilityRoutines::FindItemInList(UtilityRoutines::MakeUPPERCase(surfacenames[surf]), state->dataSurface->Surface);
+        EXPECT_EQ(state->dataSurface->Surface(surfNum).IsTransparent, isTransparent[surf]);
+    }
+    EXPECT_TRUE(state->dataSolarShading->anyScheduledShadingSurface);
+    EXPECT_TRUE(state->dataSurface->ShadingTransmittanceVaries);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:11081]: Code finds shading surfaces are transparent as expected.

File: tst/EnergyPlus/unit/SurfaceGeometry.unit.cc [hunk 16]
```diff
@@ -10771,3 +10773,561 @@ TEST_F(EnergyPlusFixture, Test_Rotational_Azimuth_Diffs)
...
+         "   **   ~~~   ** "
+         "...Schedule values > 1 have no meaning for shading elements.",
+         "   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.",
+         "   "
+         "...Summary of Errors that led to program termination:",
+         "   ..... Reference severe error count=6",
+         "   ..... Last severe error=Shading:Zone:Detailed=\"ZONESHADE:LIVING:SOUTH:SHADE001\", Base Surface Name=\"LIVING:SOUTH\", has schedule "
+         "values > 1."});
+
+    compare_err_stream(error_string);
```
Comment (rraustad) [inline tst/EnergyPlus/unit/SurfaceGeometry.unit.cc:11331]: And most or all warnings report as intended.

File: src/EnergyPlus/SolarShading.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/SolarShading.cc:378]: This response covers my hesitation.

**Review by rraustad — APPROVED** [review]
Code looks quite good and most plots show expected results.

**Comment by rraustad** [comment]
Except for defect file PythonPluginCustomSchedule-PlusShading.idf this all looks good. Opened #10022 to correct.

**Comment by rraustad** [comment]
@Myoldmopar noting that unit tests run to full completion on this branch using Windows!
