### PR TITLE
HeatPump:PlantLoop:EIR:* objects using the same inlet/outlet source node is incorrect 9740

### LINKED ISSUE #9740: Performance curve input for air-source HeatPump:PlantLoop:EIR:* objects using the same inlet/outlet source node is incorrect
Issue overview
--------------
The second input of performance curves function of temperature for air-source `HeatPump:PlantLoop:EIR:*` objects that are using the same inlet/outlet source node is incorrect.  The following figure compares the OA DBT to the second input of the capacity performance curve of the `HeatPump:PlantLoop:EIR:Cooling` object included in the `PlantLoopHeatPump_EIR_AirSource.idf` example object when both source side nodes are the same outdoor air node.

image

This is only occurring when the source side nodes are the same. Perhaps this should not be allowed and caught during input validation?

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows
 - Version of EnergyPlus: 22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [PlantLoopHeatPump_EIR_AirSource.zip](https://github.com/NREL/EnergyPlus/files/10016469/PlantLoopHeatPump_EIR_AirSource.zip)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by KarenWGard**
Pull request overview
---------------------
 - Fixes #9740
 - 9740 identified that with HeatPump:PlantLoop:EIR, AirSource heat pumps were allowed to have the same source inlet and outlet nodes.  A fatal error has been incoporated to prevent this from happening.
 - during the course of providing this fix, I noticed that there was no check that the source inlet node be an outdoor air node, despite the label.  If the source inlet node is not present elsewhere in the IDF, the source inlet temperature is always 0C.  I added a check to see if the source inlet node is an OutdoorAirNode.  This is a severe, not fatal error, because there could be cases where the choice of source inlet node is intentionally something other than an OA node.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 1]
```diff
@@ -74,6 +74,7 @@
 #include <EnergyPlus/PlantUtilities.hh>
 #include <EnergyPlus/Psychrometrics.hh>
 #include <EnergyPlus/UtilityRoutines.hh>
+#include <EnergyPlus/OutAirNodeManager.hh>
```
Comment (KarenWGard) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: allows the OA node check

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 2]
```diff
@@ -1471,6 +1471,12 @@ void EIRPlantLoopHeatPump::processInputForEIRPLHP(EnergyPlusData &state)
                     condenserNodeType = DataLoopNode::NodeFluidType::Air;
                     condenserNodeConnectionType_Inlet = DataLoopNode::ConnectionType::OutsideAir;
                     condenserNodeConnectionType_Outlet = DataLoopNode::ConnectionType::OutsideAir;
+                    if (sourceSideInletNodeName == sourceSideOutletNodeName) {
+                        ShowSevereError(state, format("PlantLoopHeatPump {} has the same inlet and outlet node.", thisObjectName));
+                        ShowContinueError(state, format("Node Name: {}", sourceSideInletNodeName));
+                        ShowFatalError(state, "Previous condition causes termination.");
+                        errorsFound = true;
+                    }
```
Comment (KarenWGard) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1478]: check for whether the two source side nodes are the same - this check is functional here, but I wonder if it would be better do do it in another location, in parallel with other node checks.  In this case, the simulation will stop once it reaches this error, adding an iteration for the modeler if there are other node errors.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc [hunk 3]
```diff
@@ -1486,6 +1492,15 @@ void EIRPlantLoopHeatPump::processInputForEIRPLHP(EnergyPlusData &state)
...
                                                                                      DataLoopNode::ObjectIsNotParent);
+                if (condenserNodeType == DataLoopNode::NodeFluidType::Air) {
+                    if (!OutAirNodeManager::CheckOutAirNodeNumber(state, thisPLHP.sourceSideNodes.inlet)) {
+                        ShowSevereError(
+                            state,
+                            format(
+                                "Air Source PlantLoop:HeatPump: {} inlet node: {} is not an OutdoorAir:Node.", thisPLHP.name, sourceSideInletNodeName));
+                        ShowContinueError(state, "Confirm that this is the intended source for the outdoor air stream.");
+                    }
+                }
```
Comment (KarenWGard) [inline src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: check for whether the inlet node is an outdoor air node - it is currently a severe, not fatal error in case the choice was intentional.  Thoughts on whether this is the appropriate approach?

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 4]
```diff
@@ -400,6 +401,188 @@ TEST_F(EnergyPlusFixture, CatchErrorsOnBadCurves)
...
+    std::string error_msg = delimited_string({
+        "   ** Severe  ** PlantLoopHeatPump hp cooling side has the same inlet and outlet node.",
+        "   **   ~~~   ** Node Name: NODE 3",
+        "   **  Fatal  ** Previous condition causes termination.",
+        "   ...Summary of Errors that led to program termination:",
+        "   ..... Reference severe error count=1",
+        "   ..... Last severe error=PlantLoopHeatPump hp cooling side has the same inlet and outlet node.",
+    });
+    EXPECT_TRUE(compare_err_stream(error_msg));
+}
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:467]: new unit test to check wether the source air nodes are the same

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 5]
```diff
@@ -400,6 +401,188 @@ TEST_F(EnergyPlusFixture, CatchErrorsOnBadCurves)
...
+
+    // the init call expects a "from" calling point
+    PlantLocation myLocation = PlantLocation(1, DataPlant::LoopSideLocation::Supply, 1, 1);
+    // setup the outdoor air nodes
+    OutAirNodeManager::SetOutAirNodes(*state);
+    // call the factory with a valid name to trigger reading inputs
+    // expects fatal error due to same node names
+    EIRPlantLoopHeatPump::factory(*state, DataPlant::PlantEquipmentType::HeatPumpEIRCooling, "HP COOLING SIDE");
+    EXPECT_TRUE(compare_err_stream(""));
+}
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:525]: new unit test to ensure that no errors are given when the air source node is an OutdoorAirNode

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 6]
```diff
@@ -400,6 +401,188 @@ TEST_F(EnergyPlusFixture, CatchErrorsOnBadCurves)
...
+    // call the factory with a valid name to trigger reading inputs
+    // expects fatal error due to same node names
+    EIRPlantLoopHeatPump::factory(*state, DataPlant::PlantEquipmentType::HeatPumpEIRCooling, "HP COOLING SIDE");
+    // expect error related to OA node not being an OutdoorAirNode
+    std::string error_msg = delimited_string({
+        "   ** Severe  ** Air Source PlantLoop:HeatPump: HP COOLING SIDE inlet node: NODE 3 is not an OutdoorAir:Node.",
+        "   **   ~~~   ** Confirm that this is the intended source for the outdoor air stream.",
+    });
+    EXPECT_TRUE(compare_err_stream(error_msg));
+}
```
Comment (KarenWGard) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:592]: new unit test to ensure that the severe error is given when the air source inlet node is not an Outdoor air node

**Review by KarenWGard — COMMENTED** [review]
developer review

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 2 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1478]: I agree, it might be nice to formalize this in one location.  Not sure that's feasible in the context of a small bug fix like this, so I say let's leave it.  I would think this is a pretty uncommon error for a user too.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 3 above)
Comment (Myoldmopar) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: Although we don't enforce it in the code in any way, moving forward, it would be nice if we only issue severe errors that will ultimately result in a fatal.  If the simulation is able to continue to run without stopping, make it a warning.  I think it's worth changing that before merging this, but I'm open to discussion.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc (hunk 6 above)
Comment (Myoldmopar) [reply tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc:592]: These are nice, compact unit tests, great!  Obviously if the severe is changed to a warning above, this text will change slightly, so update that as well.

File: tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc [hunk 7]
```diff
@@ -500,6 +683,7 @@ TEST_F(EnergyPlusFixture, Initialization)
     EXPECT_NEAR(expectedSourceSideMassFlow, state->dataLoopNodes->Node(thisCoolingPLHP->sourceSideNodes.inlet).MassFlowRateMaxAvail, flowTol);
 }
 
+
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc]: Not sure why this extra new line popped in.  Take it out...or leave it...I don't care :)

**Review by Myoldmopar — CHANGES_REQUESTED** [review]
The changes are good, but I am requesting a change from severe error to warning for the node check on the OA node.  After that, this should be ready to test/merge.

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 3 above)
Comment (KarenWGard) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: I'm open to changing the error, I think it makes sense to discuss whether it should be a fatal error, or simply a warning.

If the inlet node is not an outdoor air node, then the inlet sees 0C for all timesteps.  Perhaps we could extend the check beyond Outdoor air nodes?  In this case, we issue a warning if the inlet node is something other than an Outdoor Air Node, and issue a Severe (followed by Fatal) if the inlet node is not found anywhere else in the model.

Comment (mjwitte) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: So, the root problem here is the [calls to `getOnlySingleNode`](https://github.com/NREL/EnergyPlus/blob/dddf02031ab8bbde658a486d41ce0b1c4553649e/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L2803-L2820) for the air-cooled condenser case. If these were `DataLoopNode::ConnectionType::Inlet and Outlet` instead of `DataLoopNode::ConnectionType::OutsideAir` the regular node checking would warn about an inlet that's not connected to anything, and it would fatal (I'm 99% certain) if the same node is used a an inlet and outlet on the same equipment.

You may still want to issue a warning if the inlet is connected to something other than outdoor air, or maybe not.

The next question then is whether the conditions are properly set on the air-cooled condenser outlet node? If not, that may be why they were set to `OutsideAir` instead of `inlet/outlet`. Do we have an air volume flow rate for the air cooled condenser?

Comment (rraustad) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: Source side outlet condition is set in doPhysics. I agree that these should be inlet/outlet. P.S. there are some `// TRANE` comments in simulate (around line 100) that can be removed.

Comment (KarenWGard) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: @mjwitte - what do you mean "do we have an air volume flow rate for the air cooled condenser?"  

EnergyPlus certainly calculates a source side mass flow rate when the heat pump source is Air:

`Output:Variable,*,Heat Pump Source Side Mass Flow Rate,hourly; !- HVAC Average [kg/s]`

Comment (mjwitte) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: Ok. So, it should be valid to set that as generic inlet and outlet nodes and let the user connect them to whatever they want. 

I just wasn't sure about this equipment, because some air-cooled equipment (like DX coils) doesn't calculate any condenser flow rate or condenser outlet conditions, it just uses the condenser inlet conditions to feed into the performance curves.

**Comment by Myoldmopar** [comment]
Alright, looks like things have settled out in the comment above, and the node call arguments can be updated accordingly.    When this is done, please try to update the format issues that Clang is complaining about (or let me know after you push and I can do a quick style/commit/push myself).  Then this should be good to go.  I'll mark this as waiting on dev for the moment, but feel free to alert me if I've missed something above.  Thanks!

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 3 above)
Comment (KarenWGard) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc]: I changed:

```
                    condenserNodeConnectionType_Inlet = DataLoopNode::ConnectionType::OutsideAir;
                    condenserNodeConnectionType_Outlet = DataLoopNode::ConnectionType::OutsideAir;
```

to:

```
                    condenserNodeConnectionType_Inlet = DataLoopNode::ConnectionType::Inlet;
                    condenserNodeConnectionType_Outlet = DataLoopNode::ConnectionType::Outlet;
```

Standard node checking takes care of the missing OutdoorAirNode.  It does not take care of the issue of the same node name on the inlet and outlet, so I have left that in.

Using DataLoopNode::ConnectionType::Inlet and Outlet means that when there is a severe error when paired heat pumps share matching inlet and outlet nodes:

```
   ** Severe  ** Node Connection Error, Node="OUTDOOR AIR INLET NODE", The same node appears as a non-parent Inlet node more than once.
   **   ~~~   ** Reference Object=HeatPump:PlantLoop:EIR:Cooling, Name=COOLING COIL
   **   ~~~   ** Reference Object=HeatPump:PlantLoop:EIR:Heating, Name=HEATING COIL
   ** Severe  ** Node Connection Error, Node="OUTDOOR AIR OUTLET NODE", The same node appears as a non-parent Outlet node more than once.
   **   ~~~   ** Reference Object=HeatPump:PlantLoop:EIR:Cooling, Name=COOLING COIL
   **   ~~~   ** Reference Object=HeatPump:PlantLoop:EIR:Heating, Name=HEATING COIL
```

Is this why node connection errors were handeled independently instead of relying on `BranchNodeConnections::CheckNodeConnections`?

File: src/EnergyPlus/PlantLoopHeatPumpEIR.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1478]: IMHO, we should not allow this to happen, given that there is a heat balance at those nodes that would not be available if these nodes used the same node. That said, delete the ShowFatalError here since when errorsFound = true (leave this line here) the program terminates after all EIR HPs are read in after the getInput loop.

    if (errorsFound) {
        // currently there are no straightforward unit tests possible to get here
        // all curves are required and inputs are validated by the input processor
        // obviously this will stay here but I don't feel like counting it against coverage
        ShowFatalError(state, "Previous EIR PLHP errors cause program termination"); // LCOV_EXCL_LINE
    }

Comment (rraustad) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1478]: In addition, we need a way to determine if a dangling node exists (not connected to anything else) so we can correctly report warnings or setup said node as an outdoor air node.

                if (!OutAirNodeManager::CheckOutAirNodeNumber(state, thisFurnace.CondenserNodeNum)) {
                    ShowSevereError(state, format("For {} = {}", CurrentModuleObject, Alphas(1)));
                    ShowContinueError(state, format(" Node name of outdoor dry-bulb temperature sensor not valid outdoor air node= {}", Alphas(14)));
                    ShowContinueError(state, "...does not appear in an OutdoorAir:NodeList or as an OutdoorAir:Node.");
                    ErrorsFound = true;
                }

                OutAirNodeManager::CheckAndAddAirNodeNumber(state, thisChiller.CondInletNodeNum, Okay);

Comment (mjwitte) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1478]: If it's tagged as an Inlet node, that already happens in the general node checking.
```
            ShowSevereError(state,
                            format("{}{}{}",
                                   "Node Connection Error, Node=\"",
                                   state.dataBranchNodeConnections->NodeConnections(Loop1).NodeName,
                                   R"(", Inlet node did not find an appropriate matching "outlet" node.)"));
            ShowContinueError(state, "If this is an outdoor air inlet node, it must be listed in an OutdoorAir:Node or OutdoorAir:NodeList object.");
```

Comment (KarenWGard) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1479]: > In addition, we need a way to determine if a dangling node exists (not connected to anything else) so we can correctly report warnings or setup said node as an outdoor air node.
> 
> ```
>             if (!OutAirNodeManager::CheckOutAirNodeNumber(state, thisFurnace.CondenserNodeNum)) {
>                 ShowSevereError(state, format("For {} = {}", CurrentModuleObject, Alphas(1)));
>                 ShowContinueError(state, format(" Node name of outdoor dry-bulb temperature sensor not valid outdoor air node= {}", Alphas(14)));
>                 ShowContinueError(state, "...does not appear in an OutdoorAir:NodeList or as an OutdoorAir:Node.");
>                 ErrorsFound = true;
>             }
> 
>             OutAirNodeManager::CheckAndAddAirNodeNumber(state, thisChiller.CondInletNodeNum, Okay);
> ```

@rraustad - if we made this change, I think it would need to be considered an input change - even the example file (PlantLoopHeatPump_EIR_AirSource.idf) has the same inlet and outlet node names for the heating and cooling source inlets and outlets

Comment (KarenWGard) [reply src/EnergyPlus/PlantLoopHeatPumpEIR.cc:1478]: in `BranchNodeConnections::CheckNodeConnections`, there is a check for an inlet node that exists elsewhere.  If there is no node match, there is a Severe error (but no fatal):

```
        "   ** Severe  ** Node Connection Error, Node=\"NODE 1\", Inlet node did not find an appropriate matching \"outlet\" node.",
        "   **   ~~~   ** If this is an outdoor air inlet node, it must be listed in an OutdoorAir:Node or OutdoorAir:NodeList object.",
        "   **   ~~~   ** Reference Object=HeatPump:PlantLoop:EIR:Cooling, Name=HP COOLING SIDE",
```

There doesn't seem to be a check to make sure that the outlet node exists elsewhere in the file, but I think this is ok.

**Review by Myoldmopar — APPROVED** [review]
Looks good now.

**Comment by Myoldmopar** [comment]
Everything passes with latest develop, merging this one in.  Thanks @KarenWGard
