### PR TITLE
Fixes multispeed DX coil defrost calculation when using ReverseCycle w/ Timed control

### LINKED ISSUE #10182: `Coil:Heating:DX:MultiSpeed` Resistive Defrost Heater Capacity input affects results when Defrost Strategy is not Resistive
Issue overview
--------------
In the following IDF file that has a `Coil:Heating:DX:MultiSpeed` object, if you change the "Resistive Defrost Heater Capacity" input from Autosize to 200 to 2000, the Heating Coil Defrost Electricity Energy output changes. According to [the documentation](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-heating-and-cooling-coils.html#field-resistive-defrost-heater-capacity-1), "This numeric field defines the capacity of the resistive defrost heating element in Watts. **This input field is used only when the selected defrost strategy is resistive (see input field Defrost Strategy above)**." In this file, the Defrost Strategy is ReverseCycle, so it should not affect results.

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/12469905/in.idf.txt)

When using a `Coil:Heating:DX:SingleSpeed` object instead, the "Resistive Defrost Heater Capacity" input is correctly ignored.

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus Version 23.1.0-87ed9199d4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by shorowit**
Pull request overview
---------------------
 - Fixes #10182
 - Fixes multispeed DX coil so that the combination of ReverseCycle and Timed control works the same as the single speed coil.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DXCoils.cc [hunk 1]
```diff
@@ -13811,8 +13811,7 @@ void CalcMultiSpeedDXCoilHeating(EnergyPlusData &state,
 
                 if (FractionalDefrostTime > 0.0) {
                     // Calculate defrost adjustment factors depending on defrost control strategy
-                    if (thisDXCoil.DefrostStrategy == StandardRatings::DefrostStrat::ReverseCycle &&
-                        thisDXCoil.DefrostControl == StandardRatings::HPdefrostControl::OnDemand) {
+                    if (thisDXCoil.DefrostStrategy == StandardRatings::DefrostStrat::ReverseCycle) {
```
Comment (rraustad) [inline src/EnergyPlus/DXCoils.cc:13814]: This look right to me. If any diffs pop up, check the inputs.

**Comment by shorowit** [comment]
Running [this file](https://github.com/NREL/EnergyPlus/files/12469905/in.idf.txt) in E+ 23.1 gives zero defrost energy use (because Resistive Defrost Heater Capacity is set to Autosize and is treated as zero, when it should be ignored):

image

Running this branch on the same file (transitioned to E+ 23.2) correctly ignores the Resistive Defrost Heater Capacity input and shows non-zero energy use:

image

So it looks like it's working.

**Comment by rraustad** [comment]
@shorowit can you show coil PLR next to the defrost electicity energy to be sure of the result?

**Comment by shorowit** [comment]
E+ 23.1:

image

This branch:

image

Here's the test file I'm using, transitioned to E+ 23.2: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/12479507/in.idf.txt). I'm running it w/ a Denver TMY3.

**Comment by rraustad** [comment]
The math is deeper than just PLR, the first few reports as a constant 335571.7468 threw me. The defrost would be a function of outdoor w and PLR. So the fact that it appears to be reporting now is good enough.

    ReverseCycle,                           !- Defrost Strategy
    Timed,                                  !- Defrost Control
    0.058333,                               !- Defrost Time Period Fraction
    AutoSize,                               !- Resistive Defrost Heater Capacity {W}

File: src/EnergyPlus/DXCoils.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/DXCoils.cc:13814]: I am documenting the defrost code from CalcDXHeatingCoil so that it is clear that these models use the same defrost code. It seems to me that these are now using the same model/conditionals/etc.

        // Check outdoor temperature to determine of defrost is active
        if (OutdoorDryBulb <= thisDXCoil.MaxOATDefrost && thisDXCoil.CondenserType(Mode) != DataHeatBalance::RefrigCondenserType::Water) {
            // Calculate defrost adjustment factors depending on defrost control type
            if (thisDXCoil.DefrostControl == StandardRatings::HPdefrostControl::Timed) {
                FractionalDefrostTime = thisDXCoil.DefrostTime;
                if (FractionalDefrostTime > 0.0) {
                    HeatingCapacityMultiplier = 0.909 - 107.33 * OutdoorCoildw;
                    InputPowerMultiplier = 0.90 - 36.45 * OutdoorCoildw;
                }
            } else { // else defrost control is on-demand
                FractionalDefrostTime = 1.0 / (1.0 + 0.01446 / OutdoorCoildw);
                HeatingCapacityMultiplier = 0.875 * (1.0 - FractionalDefrostTime);
                InputPowerMultiplier = 0.954 * (1.0 - FractionalDefrostTime);
            }

            if (FractionalDefrostTime > 0.0) {
                // Calculate defrost adjustment factors depending on defrost control strategy
                if (thisDXCoil.DefrostStrategy == StandardRatings::DefrostStrat::ReverseCycle) {
                    LoadDueToDefrost = (0.01 * FractionalDefrostTime) * (7.222 - OutdoorDryBulb) * (thisDXCoil.RatedTotCap(Mode) / 1.01667);
                    DefrostEIRTempModFac = CurveValue(state, thisDXCoil.DefrostEIRFT, max(15.555, InletAirWetBulbC), max(15.555, OutdoorDryBulb));
                    thisDXCoil.DefrostPower = DefrostEIRTempModFac * (thisDXCoil.RatedTotCap(Mode) / 1.01667) * FractionalDefrostTime;
                } else { // Defrost strategy is resistive
                    thisDXCoil.DefrostPower = thisDXCoil.DefrostCapacity * FractionalDefrostTime;
                }
            } else { // Defrost is not active because (FractionalDefrostTime .EQ. 0.0)
                thisDXCoil.DefrostPower = 0.0;
            }
        }

**Comment by rraustad** [comment]
Running defect file using Denver Intl, annual simulation. This seems realistic. Defrost energy increases for speed 1 as RTF increases, and then for speed 2, picks up where speed 1 leaves off and continues to increase as speed 2 RTF increases. Defrost is only active when ambient w is low. This is a timed reverse cycle defrost. So the HP will activate defrost for a fixed amount of time and should be proportional to PLR/RTF. I am not seeing anything here that gives me pause.

image

**Comment by rraustad** [comment]
And 1 more vs speed ratio (PLR indicator at speed 2), when defrost energy is non-zero for speed 2, and shows proportional defrost energy with speed ratio during speed 2 operation.

image

**Review by rraustad — APPROVED** [review]
@Myoldmopar I don't see anything wrong with this change. And it matches what the other DX heating coil model does. So this should be good to go.

**Comment by rraustad** [comment]
This is an interesting figure. I tried to isolate defrost during speed 1 (left), and then speed 2 operation (right), to compare to the middle figure above just to make sure it made sense. For speed 1 defrost is perfectly linear with RTF. But for speed 2 defrost energy is not linear with RTF, which I would expect because of the PLF curve. In this defect file, the Apply PLF to Speeds Greater than 1 field is set to No. So I would expect to see the defrost energy non-linearity at speed 1 and NOT speed 2 (where PLR should = RTF). I either don't understand what is happening in this model or there is something wrong with how the PLF curve is applied. This is out of scope for this issue but seems like it should be looked at.

    ReverseCycle,            !- Defrost Strategy
    Timed,                   !- Defrost Control
    0.058333,                !- Defrost Time Period Fraction
    AutoSize,                !- Resistive Defrost Heater Capacity {W}
    No,                      !- Apply Part Load Fraction to Speeds Greater than 1

image

**Comment by Myoldmopar** [comment]
The general trends of defrost energy and fact that it's nonzero are both good.  I mostly grok your points about the expected (non-)linearity, but agree that's probably beyond scope here.  Let's call it.  I'll just do a quick build with the latest commits to develop and get this one ready next.

**Comment by Myoldmopar** [comment]
Everything is happy, let's get this one in.  Thanks @shorowit and @rraustad
