### PR TITLE
Fix fluid property interpolation for single concentration case

### LINKED ISSUE #9532: Fluid Properties interpolation failed to deal with single concentration case and may yield erratic  results
Issue overview
--------------

It was found that if the FluidProperties:Concentration only have data for one concentration, the program would have an array-out-of-bound exception. This error can be caught in the debug mode. However, for the release version, EnergyPlus can run through with the array out of bound, but may have caused erratic results, including some strange warnings that saying a valid temperature is not in range (with the range being incorrect). 

This will affect all the interpolated fluid properties, including density, specific heat, viscosity, and conductivity. A temporary workaround would be to add another set(s) of concentration data that contain the same values, but with a distinguishable concentration level difference, to allow the existing fluid interpolation working properly. 

It is advisable to revise the code to handle the single-concentration case, in that it might not be an uncommon scenario that only one fluid concentration is needed or available. Also, EnergyPlus requires a specific order for the concentration data to be ordered in ascending order, which makes the (working) workaround even more unnecessarily inconvenient (maybe slightly but still more). A code revision for tentative fix will follow soon. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6 and v22.1
 - Discovered while working on helpdesk ticket number 16125

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9532))
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jcyuan2020**
Pull request overview
---------------------
 - Fixes #9532 
 - Tentative fix to the fluid property interpolation issue when there is only data are present or available for only a single concentration value.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/FluidProperties.cc [hunk 1]
```diff
@@ -4744,7 +4744,12 @@ namespace FluidProperties {
                     break; // LoopC DO loop
                 }
             }
-            if (std::abs(RawConcData(HiIndex) - RawConcData(HiIndex - 1)) >= ConcToler) {
+
```
Comment (jcyuan2020) [inline src/EnergyPlus/FluidProperties.cc:4747]: Add a condition for single-concentration case, so it could be processed properly. In this scenario, it will just take that set of data. 
This might not be an uncommon scenario for supplying just one concentration of data, or just have fluid of a single concentration to use.

File: tst/EnergyPlus/unit/FluidProperties.unit.cc [hunk 2]
```diff
@@ -116,3 +116,43 @@ TEST_F(EnergyPlusFixture, FluidProperties_GetSpecificHeatGlycol)
     EXPECT_NEAR(4082, GetSpecificHeatGlycol(*state, "GLHXFLUID", 105.0, FluidIndex, "UnitTest"), 0.01);
     EXPECT_NEAR(4137, GetSpecificHeatGlycol(*state, "GLHXFLUID", 125.0, FluidIndex, "UnitTest"), 0.01);
 }
+
```
Comment (jcyuan2020) [inline tst/EnergyPlus/unit/FluidProperties.unit.cc:119]: Unit test to test the single-concentration scenario.

File: src/EnergyPlus/FluidProperties.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/FluidProperties.cc:4747]: I have a strong suspicion that if I look too hard at the code around this change, I'm going to find lots of things I want to change.  So I'll try to keep my review to just these lines.

File: src/EnergyPlus/FluidProperties.cc [hunk 3]
```diff
@@ -4744,7 +4744,12 @@ namespace FluidProperties {
...
+            if (HiIndex == 1) {
+                for (LoopT = 1; LoopT <= NumOfTemps; ++LoopT) {
+                    InterpData(LoopT) = RawPropData(HiIndex, LoopT);
+                }
+            } else if (std::abs(RawConcData(HiIndex) - RawConcData(HiIndex - 1)) >= ConcToler) {
```
Comment (Myoldmopar) [inline src/EnergyPlus/FluidProperties.cc:4752]: Yes, your new line for `HiIndex == 1` seems like it would indeed work better and not have an array out of bounds issue.  Good.

File: tst/EnergyPlus/unit/FluidProperties.unit.cc [hunk 4]
```diff
@@ -116,3 +116,43 @@ TEST_F(EnergyPlusFixture, FluidProperties_GetSpecificHeatGlycol)
...
+                              ConData,  // concentrations for raw data
+                              PropData, // raw property data (temperature,concentration)
+                              ActCon,   // concentration of actual fluid mix
+                              Result);  // interpolated output data at proper concentration
+
+    EXPECT_NEAR(1020.0, Result(1), 1e-6);
+    EXPECT_NEAR(1010.0, Result(2), 1e-6);
+    EXPECT_NEAR(1000.0, Result(3), 1e-6);
+    EXPECT_NEAR(990.0, Result(4), 1e-6);
+    EXPECT_NEAR(980.0, Result(5), 1e-6);
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/FluidProperties.unit.cc:157]: Yes!!! Fantastic unit test!

**Review by Myoldmopar — APPROVED** [review]

**Comment by Myoldmopar** [comment]
This is all clean, and code changes look good.  I think I'll drop this one in right now, thanks @jcyuan2020 .
