### PR TITLE
Defect - Fix 11185 incorrect severe tariff error

### LINKED ISSUE #11185: UtilityRate:Tariff schedule name mismatch produces incorrect severe error message
### Issue overview

When there's a name mismatch error in your schedules, the Tariff code produces a severe error message referring to a `SurfaceProperty:Underwater` object class instead of a `UtilityCost:Tariff` object class. The `SurfaceProperty:Underwater` object class doesn't even exist in the idf.

Attached idfs show the error.

   ** Warning ** Processing Monthly Tabular Reports: Variable names not valid for this simulation
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual variables.
   ** Severe  ** GetInputEconomicsTariff: SurfaceProperty:Underwater = EXAMPLED
   **   ~~~   ** Season Schedule Name = TWOSEASONSCHEDULE, item not found.

### Operating System (Multiple choices)

Any

### Operating System Version

Any

### Version of EnergyPlus

25.1

### Unmethours link or helpdesk ticket number

N/A

### Defect file

[5ZoneEconomicsTariffAndLifeCycleCosts-Fails1.idf.txt](https://github.com/user-attachments/files/22100709/5ZoneEconomicsTariffAndLifeCycleCosts-Fails1.idf.txt)
[5ZoneEconomicsTariffAndLifeCycleCosts-Fails2.idf.txt](https://github.com/user-attachments/files/22100708/5ZoneEconomicsTariffAndLifeCycleCosts-Fails2.idf.txt)
[5ZoneEconomicsTariffAndLifeCycleCosts-Working.idf.txt](https://github.com/user-attachments/files/22100710/5ZoneEconomicsTariffAndLifeCycleCosts-Working.idf.txt)

### PR DESCRIPTION
**Pull request by GaryMarksBigladder**
Pull request overview
---------------------

- Fixes #11185

### Description of the purpose of this PR

Missing item severe tariff error doesn't display the missing item and instead displays some default information. The fix adds the item that's missing to the severe error.

### Pull Request Author

 - [ X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by JasonGlazer** [comment]
The test files provided recreated the original error in develop and work properly in the branch with the revised code.

**Comment by JasonGlazer** [comment]
@GaryMarksBigladder, is this a specific case of a general problem with using ShowSevereItemNotFound() that has now just been fixed for this specific case? The ShowSevereItemNotFound() is widely used. I don't think we want a little bandaid over a big problem.

**Comment by GaryMarksBigladder** [comment]
To the best of my knowledge, ShowSevereItemNotFound is working for other parts of the code. I noticed that just fixing the usage of ShowSevereItemNotFound, in this case, would still leave the user searching for information from warnings higher up instead of just giving them all the information they needed to fix their idf in the severe error message itself. That's why I made a new function that other code can call if they feel it makes sense in their usage. We could change  ShowSevereItemNotFound for everyone, but I don't know if there is code out there that is programmatically looking for specific verbiage in the error, so it seemed safer to me to change it for this specific use case while allowing others in the future to decide which severe error message best fits their use case.  Please let me know if that was not the correct course of action.

**Review by JasonGlazer — APPROVED** [review]

**Comment by JasonGlazer** [comment]
Thanks @GaryMarksBigladder

File: src/EnergyPlus/UtilityRoutines.cc [hunk 1]
```diff
@@ -1682,6 +1682,11 @@ void ShowSevereItemNotFound(EnergyPlusData &state, ErrorObjectHeader const &eoh,
     ShowContinueError(state, format("{} = {}, item not found.", fieldName, fieldVal));
 }
 
+void ShowDetailedSevereItemNotFound(EnergyPlusData& state, ErrorObjectHeader const& eoh, std::string_view fieldName, std::string_view fieldVal)
+{
+    ShowSevereError(state, format("{}: {} = {}, item not found.", eoh.routineName, fieldName, fieldVal));
+    ShowContinueError(state, format("{} = {}, item not found.", fieldName, fieldVal));
```
Comment (Myoldmopar) [inline src/EnergyPlus/UtilityRoutines.cc:1688]: I'll be honest - I'm not sure I understand.  This is repeating the same line twice?  Except in the first it just shows the routine name?  That seems odd to me.  Maybe I'm missing something.

Comment (rraustad) [reply src/EnergyPlus/UtilityRoutines.cc:1688]: ShowSevereItemNotFound:

    ShowSevereError(state, format("{}: {} = {}", eoh.routineName, eoh.objectType, eoh.objectName));
    ShowContinueError(state, format("{} = {}, item not found.", fieldName, fieldVal));

**Comment by nealkruis** [comment]
@Myoldmopar any idea what's happening with the regression error in the CI? It doesn't look like the regression files were uploaded.

**Comment by JasonGlazer** [comment]
The formatting fix (from the static code analysis) can be downloaded from the patch file and shows:

```
diff --git a/src/EnergyPlus/UtilityRoutines.cc b/src/EnergyPlus/UtilityRoutines.cc
index bf2f0fb..772467e 100644
--- a/src/EnergyPlus/UtilityRoutines.cc
+++ b/src/EnergyPlus/UtilityRoutines.cc
@@ -1682,7 +1682,7 @@ void ShowSevereItemNotFound(EnergyPlusData &state, ErrorObjectHeader const &eoh,
     ShowContinueError(state, format("{} = {}, item not found.", fieldName, fieldVal));
 }
 
-void ShowDetailedSevereItemNotFound(EnergyPlusData& state, ErrorObjectHeader const& eoh, std::string_view fieldName, std::string_view fieldVal)
+void ShowDetailedSevereItemNotFound(EnergyPlusData &state, ErrorObjectHeader const &eoh, std::string_view fieldName, std::string_view fieldVal)
 {
     ShowSevereError(state, format("{}: {} = {}, item not found.", eoh.routineName, fieldName, fieldVal));
     ShowContinueError(state, format("{} = {}, item not found.", fieldName, fieldVal));

```

A minor quick fix. I'm not sure I understand the other issues being reported on the Build and Test related to a forked repo. When I google that it seems to be pointing to the fact that the pull request is coming from the bigladder repo and maybe there is a permission issue.

**Comment by tanaya-mankad** [comment]
Formatting fixed!

File: src/EnergyPlus/UtilityRoutines.hh [hunk 2]
```diff
@@ -287,6 +287,15 @@ void ShowSevereEmptyField(EnergyPlusData &state,
...
 void ShowSevereItemNotFound(EnergyPlusData &state, ErrorObjectHeader const &eoh, std::string_view fieldName, std::string_view fieldValue);
+/// <summary>
+/// Similar to ShowSevereItemNotFound, except for the severe error added to the list contains the information about
+/// what item is missing.
+/// </summary>
+/// <param name="state">EnergyPus state, used for tracking the severe error</param>
+/// <param name="eoh">Error object header, used to get the routineName</param>
+/// <param name="fieldName">Name of the unmatched field</param>
+/// <param name="fieldValue">Value of the unmatched field</param>
+void ShowDetailedSevereItemNotFound(EnergyPlusData &state, ErrorObjectHeader const &eoh, std::string_view fieldName, std::string_view fieldValue);
```
Comment (mitchute) [inline src/EnergyPlus/UtilityRoutines.hh:298]: I could see this being pretty useful if we had it propagated throughout the code, but I'm having trouble seeing where this would kick in, and IDD/IDF file validation would end. This is fine to go in... I'm just thinking out loud..

**Review by mitchute — APPROVED** [review]
GTG. Merging.
