### PR TITLE
AirloopHVAC:UnitarySystem crashes when no heating coil exists and CoolReheat or Multimode dehumidification is used

### LINKED ISSUE #10118: EnergyPlus Calculation Crashes Inconsistently for  AirLoopHVAC:UnitarySystem with no heating coil
Issue overview
--------------
In the IDF file attached to this ticket, there are multiple AirLoopHVAC:UnitarySystem objects with no heating coil specified.  Originally I have the IDF file in EnergyPlus 9.5 format. When I run the IDF with the release version of EnergyPlus 9.5 with EPLaunch, most of the times it will crash, but sometimes it will run successfully.  So I downloaded the source code of EnergyPlus 9.5 and tried to run the IDF in debug mode in Visual Studio. It always fails at the following line of code:
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/UnitarySystem.cc#L9654
I think it failed because the HeatCoilOutletNodeNum is 0, and in fact the unitary system does not have a heating coil at all. 

Then I updated the IDF file to version 23.1 and with release version of 23.1, I tried multiple times and the simulation always run successfully. However, when I ran the IDF in debug mode with 23.1 source code, it again reliably fails at the same line of code:
https://github.com/NREL/EnergyPlus/blob/b7a30cf169f81fec733cee276d77bb4b8152dc64/src/EnergyPlus/UnitarySystem.cc#L9936

Looking through the code,  in a different place the same quantity is calculated in a different way:
https://github.com/NREL/EnergyPlus/blob/b7a30cf169f81fec733cee276d77bb4b8152dc64/src/EnergyPlus/UnitarySystem.cc#L8333
In this block of code, it first calculates the CoolingOnlySensibleOutput based on Zone Node and the Cooling Coil Outlet Node, then the if statement below will add the heating coil load only when a heating coil exists.  

My questions are:

1. Is there an explanation of why EnergyPlus 9.5 release does not fail consistently?
2. With Version 23.1, the release version seems like always run successfully, is that expected given the that the source code really did not change?
3. To avoid potential crashes, I think the code at line 9936 should be written the same way as in line 8333. Can you confirm?

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10, version)
 - Version of EnergyPlus (EnergyPlus 9.5 and 23.1)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (1. [EnergyPlus9.5 IDF](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DesigndayCalc_V950.idf), 2. [EnergyPlus23.1 IDF](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DesigndayCalc_V23.1.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #10118
 - Caculations for reheat coil load assume heating coil exists. This causes an array access exception and the program crashes.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/UnitarySystem.cc [hunk 1]
```diff
@@ -8330,14 +8330,14 @@ namespace UnitarySystems {
...
         Real64 CoolingOnlySensibleOutput =
             state.dataLoopNodes->Node(this->CoolCoilInletNodeNum).MassFlowRate * CpAir *
-            (state.dataLoopNodes->Node(this->NodeNumOfControlledZone).Temp - state.dataLoopNodes->Node(this->CoolCoilOutletNodeNum).Temp);
-        if (this->m_HeatCoilExists) {
-            CoolingOnlySensibleOutput -=
-                state.dataLoopNodes->Node(this->CoolCoilInletNodeNum).MassFlowRate * CpAir *
-                (state.dataLoopNodes->Node(this->HeatCoilOutletNodeNum).Temp - state.dataLoopNodes->Node(this->HeatCoilInletNodeNum).Temp);
-        }
+            ((state.dataLoopNodes->Node(this->NodeNumOfControlledZone).Temp - state.dataLoopNodes->Node(this->CoolCoilOutletNodeNum).Temp) -
+             heatCoildT);
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: This issue was already corrected here previously. The change here updates the method to avoid a crash. If heating coil does not exist, HeatCoilOutletNodeNum and HeatCoilInletNodeNum = 0 and an array access exception occurs.

File: src/EnergyPlus/UnitarySystem.cc [hunk 2]
```diff
@@ -9933,10 +9932,14 @@ namespace UnitarySystems {
...
-        CoolingOnlySensibleOutput =
+        Real64 heatCoildT =
+            (this->m_HeatCoilExists)
+                ? (state.dataLoopNodes->Node(this->HeatCoilOutletNodeNum).Temp - state.dataLoopNodes->Node(this->HeatCoilInletNodeNum).Temp)
+                : 0.0;
+        Real64 CoolingOnlySensibleOutput =
             state.dataLoopNodes->Node(this->CoolCoilInletNodeNum).MassFlowRate * CpAir *
             ((state.dataLoopNodes->Node(this->NodeNumOfControlledZone).Temp - state.dataLoopNodes->Node(this->CoolCoilOutletNodeNum).Temp) -
-             (state.dataLoopNodes->Node(this->HeatCoilOutletNodeNum).Temp - state.dataLoopNodes->Node(this->HeatCoilInletNodeNum).Temp));
+             heatCoildT);
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: Same change as above.

File: src/EnergyPlus/UnitarySystem.cc [hunk 3]
```diff
@@ -8371,20 +8371,19 @@ namespace UnitarySystems {
...
+        Real64 TempLoad;                // represents either a sensible or latent load [W]
+        Real64 TempSysOutput;           // represents either a sensible or latent capacity [W]
+        Real64 TempSensOutput;          // iterative sensible capacity [W]
+        Real64 TempLatOutput;           // iterative latent capacity [W]
+        Real64 TempMinPLR;              // iterative minimum PLR
+        Real64 TempMaxPLR;              // iterative maximum PLR
+        Real64 CpAir;                   // specific heat of air [J/kg_C]
+        Real64 FullLoadAirOutletTemp;   // saved full load outlet air temperature [C]
+        Real64 FullLoadAirOutletHumRat; // saved full load outlet air humidity ratio [kg/kg]
+        Real64 NoLoadOutletTemp;        // outlet temp of system with coils off [C]
```
Comment (rraustad) [inline src/EnergyPlus/UnitarySystem.cc]: Moved declaration of CoolingOnlySensibleOutput to local.

File: tst/EnergyPlus/unit/UnitarySystem.unit.cc [hunk 4]
```diff
@@ -6202,7 +6208,71 @@ Curve:Biquadratic,
...
+    EXPECT_NEAR(state->dataHeatingCoils->HeatingCoil(thisSys->m_HeatingCoilIndex).HeatingCoilRate, 0.0, 0.1);
+    EXPECT_NEAR(state->dataHeatingCoils->HeatingCoil(thisSys->m_SuppHeatCoilIndex).HeatingCoilRate, 18268.1, 0.1);
+    Real64 ReheatNeded = sensOut - ExcessSensibleCapacity;
+    EXPECT_NEAR(ReheatNeded, 18268.1, 11.0); // same 11 watt difference as above, is this error due to tolerance?
+
+    // remove heating coil to test cooling only application
+    thisSys->m_HeatCoilExists = false;
+    thisSys->m_HeatingCoilIndex = 0;
+    thisSys->HeatCoilInletNodeNum = 0;
+    thisSys->HeatCoilOutletNodeNum = 0;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/UnitarySystem.unit.cc]: Beefed up this unit test a little to better understand what was happening and added this last test to remove heating coil and perform calculations again. This unit test fails without this branch's code change.

**Comment by rraustad** [comment]
Defect file symptom is a recurring crash in debug and no crash or intermittant crash in release.

**Develop branch:**

**Release:**

    ************* EnergyPlus Completed Successfully-- 258 Warning; 0 Severe Errors; Elapsed Time=00hr 02min 11.12sec

**Debug:**

image

**This Branch:**

**Release:**

    ************* EnergyPlus Completed Successfully-- 258 Warning; 0 Severe Errors; Elapsed Time=00hr 02min  7.11sec

**Debug:**

    ************* EnergyPlus Completed Successfully-- 258 Warning; 0 Severe Errors; Elapsed Time=00hr 18min 16.25sec

And given the obvious array access violation I was curious how the results changed in a release build. This variable (CoilOnlySensibleOutput) is used to determine this report variable:

        SetupOutputVariable(state,
                            "Unitary System Dehumidification Induced Heating Demand Rate",
                            OutputProcessor::Unit::W,
                            state.dataUnitarySystems->unitarySys[sysNum].m_DehumidInducedHeatingDemandRate,
                            OutputProcessor::SOVTimeStepType::System,
                            OutputProcessor::SOVStoreType::Average,
                            state.dataUnitarySystems->unitarySys[sysNum].Name);

        CoolingOnlySensibleOutput =
            state.dataLoopNodes->Node(this->CoolCoilInletNodeNum).MassFlowRate * CpAir *
            ((state.dataLoopNodes->Node(this->NodeNumOfControlledZone).Temp - state.dataLoopNodes->Node(this->CoolCoilOutletNodeNum).Temp) -
             (state.dataLoopNodes->Node(this->HeatCoilOutletNodeNum).Temp - state.dataLoopNodes->Node(this->HeatCoilInletNodeNum).Temp));
        if (state.dataUnitarySystems->QToHeatSetPt < 0.0) {
            //   Calculate the reheat coil load wrt the heating setpoint temperature. Reheat coil picks up
            //   the entire excess sensible cooling (DX cooling coil and impact of outdoor air).
            this->m_DehumidInducedHeatingDemandRate = max(0.0, (CoolingOnlySensibleOutput + state.dataUnitarySystems->QToHeatSetPt));
            //   Heating mode and dehumidification is required
        } else {
            //   Calculate the reheat coil load as the sensible capacity of the DX cooling coil only. Let
            //   the heating coil pick up the load due to outdoor air.
            this->m_DehumidInducedHeatingDemandRate = max(0.0, CoolingOnlySensibleOutput);
        }

And the results for this report using develop and this branch:

image

**Comment by rraustad** [comment]
This branch has 0 diffs, failures or warnings. The defect file was run in develop and this branch with results posted above (to save the reviewer some time). Code changes are ready for review.

**Comment by nrel-bot-2b** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@rraustad it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
@rraustad it has been 12 days since this pull request was last updated.

**Comment by nrel-bot-2b** [comment]
10118-crash-when-no-heating-coil (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4: OK (3519 of 3538 tests passed, 762 test warnings)

Messages:\n
 * 781 tests had: AUD diffs.
 * 430 tests had: EIO diffs.
 * 220 tests had: MDD diffs.
 * 243 tests had: MTD diffs.
 * 143 tests had: BND diffs.
 * 156 tests had: RDD diffs.
 * 3 tests had: PERF_LOG diffs.
 * 3 tests had: ERR diffs.
 * 2 tests had: EDD diffs.
 * 19 tests had: Table big diffs.
 * 1 test had: ESO small diffs.

Failures:\n

regression Test Summary
 * Passed: 784
 * Failed: 19


<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4.html'>Test Badge</a>

**Comment by nrel-bot-2b** [comment]
10118-crash-when-no-heating-coil (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug: OK (1929 of 1929 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Test Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4-UnitTestsCoverage-Debug.html'>Coverage Badge</a>

**Comment by nrel-bot-2b** [comment]
10118-crash-when-no-heating-coil (rraustad) - x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug: OK (787 of 787 tests passed, 0 test warnings)






<a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Build Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Test Badge</a> <a href='https://myoldmopar.github.io/EnergyPlusBuildResults/EnergyPlus-f5332a725a82064cc6558a0dde139fd2436631fb-x86_64-Linux-Ubuntu-22.04-gcc-11.4-IntegrationCoverage-Debug.html'>Coverage Badge</a>

**Review by mjwitte — APPROVED** [review]
@rraustad Straightforward fix. I've updated with develop and fixed formatting. This is good to go.

**Comment by Myoldmopar** [comment]
This is showing one small table diff now, is that expected or was there already a merge today that caused that?

**Comment by mjwitte** [comment]
> This is showing one small table diff now, is that expected or was there already a merge today that caused that?

It's the random bouncing heat emissions table output. This is good to go in whenever you're ready.

**Comment by rraustad** [comment]
No diffs were expected. I'll have to look at UnitarySystem_MultiSpeedDX_EconoStaging in the area of code where these changes are.
