### PR TITLE
TDD surface reordering and bug fixing

### LINKED ISSUE #8526: TDD diffuser and dome inside and outside surface heat balance calculations not consistent with EngRef
Issue overview
--------------
According to the Engineering Reference,

> For conductive and convective heat gain, TDDs are treated as one entity with an effective thermal resistance (i.e. R-value) between the outside and inside surfaces. The outside face temperature of the dome and the inside face temperature of the diffuser are calculated as usual by the outside and inside heat balances respectively. The temperatures are then copied to the inside face of the dome and the outside face of the diffuser.

However, in EnergyPlus inside and outside surface heat balance calculations...

First, the surface outside temperature calculation is [bypassed for TDD surface](https://github.com/NREL/EnergyPlus/blob/687fc3951cac3f4fa8b818dd9e7bdd1a86c6eec8/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L6051) as their `HeatTransferAlgorithm` is assigned as `HeatTransferModel_TDD`. [The TDD branch never](https://github.com/NREL/EnergyPlus/blob/687fc3951cac3f4fa8b818dd9e7bdd1a86c6eec8/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L8000) gets accessed. These temperature values are initialized and remain static.
Then the values are [copied to the TDD diffuser's outside temperature](https://github.com/NREL/EnergyPlus/blob/687fc3951cac3f4fa8b818dd9e7bdd1a86c6eec8/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L6889).

Second, the inside surf temperature of the diffuser is [copied to the dome](https://github.com/NREL/EnergyPlus/blob/687fc3951cac3f4fa8b818dd9e7bdd1a86c6eec8/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L6885) in the diffuser zone loop (e.g. Zone(1)), but later in the dome surface zone loop (e.g. Zone(2)), the inside surf temperature of the dome is [recalculated and assigned](https://github.com/NREL/EnergyPlus/blob/687fc3951cac3f4fa8b818dd9e7bdd1a86c6eec8/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L6873) to the reported value, overwriting the previously copied value.

Here is a snapshot of the summer design day results for the testfile _DaylightingDeviceTubular.idf_. The outside temperature of the diffuser and dome, and the inside temperature of the dome are not calculated correctly.

Picture1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by xuanluo113**
Pull request overview
---------------------
This branch includes the following refactoring and bug fixing features.
- Zone surface reorder: The Zone Surface array is reordered to the sequence of "Airwall, Opaq (exterior -> interior), Win (ext -> int), TDD_Diffuser (Win), TDD_Dome"
- Fixed the bug in inside and outside heat HB calculation of TDD surfaces (issue #8526)
- Applied the new zone surface reorder in heat balance and daylighting functions.

In particular, for the model `DaylightingDeviceTubular.idf` in the current testfile list, the outside and inside surface temperature of the TDD surfaces are:
Before - 
image
After - 
image

We also developed a new test file for tdd surface attached to test the bug fixing. If needed, the new file can be included in the current test suite.
[5ZoneWithAttic_DaylightingDeviceDiffuser.idf.txt](https://github.com/NREL/EnergyPlus/files/6046002/5ZoneWithAttic_DaylightingDeviceDiffuser.idf.txt)

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by xuanluo113** [comment]
@mjwitte Would you mind reviewing one more branch? :grinning:

File: src/EnergyPlus/ElectricBaseboardRadiator.cc [hunk 1]
```diff
@@ -1141,7 +1141,7 @@ namespace ElectricBaseboardRadiator {
 
         SumHATsurf = 0.0;
 
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/ElectricBaseboardRadiator.cc]: This if can be deleted.

File: src/EnergyPlus/HWBaseboardRadiator.cc [hunk 2]
```diff
@@ -1791,7 +1791,7 @@ namespace HWBaseboardRadiator {
 
         SumHATsurf = 0.0;
 
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/HWBaseboardRadiator.cc]: Another if to delete.

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 3]
```diff
@@ -545,7 +545,7 @@ namespace HeatBalanceIntRadExchange {
             }
             int numEnclosureSurfaces = 0;
             for (int zoneNum : thisEnclosure.ZoneNums) {
-                for (int surfNum = Zone(zoneNum).SurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
+                for (int surfNum = Zone(zoneNum).HTSurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
                     if (Surface(surfNum).HeatTransSurf) ++numEnclosureSurfaces;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc]: The if portion here can be deleted, keep `++numEnclosureSurfaces;`

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 4]
```diff
@@ -568,13 +568,13 @@ namespace HeatBalanceIntRadExchange {
             int enclosureSurfNum = 0;
             for (int const zoneNum : thisEnclosure.ZoneNums) {
                 int priorZoneTotEnclSurfs = enclosureSurfNum;
-                for (int surfNum = Zone(zoneNum).SurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
+                for (int surfNum = Zone(zoneNum).HTSurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
                     if (!Surface(surfNum).HeatTransSurf) continue;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc]: Delete.

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 5]
```diff
@@ -568,13 +568,13 @@ namespace HeatBalanceIntRadExchange {
...
                     ++enclosureSurfNum;
                     thisEnclosure.SurfacePtr(enclosureSurfNum) = surfNum;
                 }
                 // Store SurfaceReportNums to maintain original reporting order
-                for (int allSurfNum = Zone(zoneNum).SurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; allSurfNum <= surfNum_end; ++allSurfNum) {
+                for (int allSurfNum = Zone(zoneNum).HTSurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; allSurfNum <= surfNum_end; ++allSurfNum) {
                     if (!Surface(DataSurfaces::AllSurfaceListReportOrder[allSurfNum - 1]).HeatTransSurf) continue;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc]: Delete?

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 6]
```diff
@@ -847,7 +847,7 @@ namespace HeatBalanceIntRadExchange {
             }
             int numEnclosureSurfaces = 0;
             for (int zoneNum : thisEnclosure.ZoneNums) {
-                for (int surfNum = Zone(zoneNum).SurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
+                for (int surfNum = Zone(zoneNum).HTSurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
                     // Include only heat transfer surfaces
                     if (Surface(surfNum).HeatTransSurf) ++numEnclosureSurfaces;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc]: Remove if, keep ++

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 7]
```diff
@@ -867,7 +867,7 @@ namespace HeatBalanceIntRadExchange {
             int enclosureSurfNum = 0;
             for (int const zoneNum : thisEnclosure.ZoneNums) {
                 int priorZoneTotEnclSurfs = enclosureSurfNum;
-                for (int surfNum = Zone(zoneNum).SurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
+                for (int surfNum = Zone(zoneNum).HTSurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; surfNum <= surfNum_end; ++surfNum) {
                     // Do not include non-heat transfer surfaces
                     if (!Surface(surfNum).HeatTransSurf) continue;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc]: Delete.

File: src/EnergyPlus/HeatBalanceIntRadExchange.cc [hunk 8]
```diff
@@ -877,7 +877,7 @@ namespace HeatBalanceIntRadExchange {
                     Surface(surfNum).SolarEnclIndex = enclosureNum;
                 }
                 // Store SurfaceReportNums to maintain original reporting order
-                for (int allSurfNum = Zone(zoneNum).SurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; allSurfNum <= surfNum_end; ++allSurfNum) {
+                for (int allSurfNum = Zone(zoneNum).HTSurfaceFirst, surfNum_end = Zone(zoneNum).SurfaceLast; allSurfNum <= surfNum_end; ++allSurfNum) {
                     if (!Surface(DataSurfaces::AllSurfaceListReportOrder[allSurfNum - 1]).HeatTransSurf) continue;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceIntRadExchange.cc]: Delete?

File: src/EnergyPlus/LowTempRadiantSystem.cc [hunk 9]
```diff
@@ -5814,7 +5814,7 @@ namespace LowTempRadiantSystem {
         // Return value
         Real64 sumHATsurf(0.0);
 
-        for (int surfNum = Zone(ZoneNum).SurfaceFirst; surfNum <= Zone(ZoneNum).SurfaceLast; ++surfNum) {
+        for (int surfNum = Zone(ZoneNum).HTSurfaceFirst; surfNum <= Zone(ZoneNum).SurfaceLast; ++surfNum) {
             if (!Surface(surfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/LowTempRadiantSystem.cc]: Delete?

File: src/EnergyPlus/RoomAirModelAirflowNetwork.cc [hunk 10]
```diff
@@ -1180,7 +1180,7 @@ namespace RoomAirModelAirflowNetwork {
         SumHmARa = 0.0;
         SumHmARaW = 0.0;
 
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non - heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/RoomAirModelAirflowNetwork.cc]: Delete?

File: src/EnergyPlus/SteamBaseboardRadiator.cc [hunk 11]
```diff
@@ -1438,7 +1438,7 @@ namespace SteamBaseboardRadiator {
 
         SumHATsurf = 0.0;
 
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/SteamBaseboardRadiator.cc]: Delete?

File: src/EnergyPlus/SwimmingPool.cc [hunk 12]
```diff
@@ -1001,7 +1001,7 @@ namespace EnergyPlus::SwimmingPool {
 
         Real64 SumHATsurf = 0.0; // Return value
 
-        for (int SurfNum = DataHeatBalance::Zone(ZoneNum).SurfaceFirst; SurfNum <= DataHeatBalance::Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (int SurfNum = DataHeatBalance::Zone(ZoneNum).HTSurfaceFirst; SurfNum <= DataHeatBalance::Zone(ZoneNum).SurfaceLast; ++SurfNum) {
             if (!DataSurfaces::Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/SwimmingPool.cc]: Delete?

File: src/EnergyPlus/ThermalChimney.cc [hunk 13]
```diff
@@ -671,7 +671,7 @@ namespace ThermalChimney {
                 }
             }
 
-            for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+            for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
 
                 if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/ThermalChimney.cc]: Delete?

File: src/EnergyPlus/ThermalComfort.cc [hunk 14]
```diff
@@ -1901,7 +1901,7 @@ namespace ThermalComfort {
         // Note that area*emissivity needs to be recalculated because of the possibility of changes to the emissivity via the EMS
         SumAET = 0.0;
         ZoneAESum(ZoneNum) = 0.0;
-        for (SurfNum2 = Zone(ZoneNum).SurfaceFirst; SurfNum2 <= Zone(ZoneNum).SurfaceLast; ++SurfNum2) {
+        for (SurfNum2 = Zone(ZoneNum).HTSurfaceFirst; SurfNum2 <= Zone(ZoneNum).SurfaceLast; ++SurfNum2) {
             if ((Surface(SurfNum2).HeatTransSurf) && (SurfNum2 != SurfNum)) {
```
Comment (mjwitte) [inline src/EnergyPlus/ThermalComfort.cc]: Delete `(Surface(SurfNum2).HeatTransSurf) &&` ?

File: src/EnergyPlus/VentilatedSlab.cc [hunk 15]
```diff
@@ -4453,7 +4453,7 @@ namespace VentilatedSlab {
 
         SumHATsurf = 0.0;
 
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/VentilatedSlab.cc]: Delete?

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 16]
```diff
@@ -2721,8 +2721,8 @@ namespace ZoneTempPredictorCorrector {
 
             for (Loop = 1; Loop <= state.dataGlobal->NumOfZones; ++Loop) {
                 FirstSurfFlag = true;
-                if (Zone(Loop).SurfaceFirst > 0) {
-                    for (SurfNum = Zone(Loop).SurfaceFirst; SurfNum <= Zone(Loop).SurfaceLast; ++SurfNum) {
+                if (Zone(Loop).HTSurfaceFirst > 0) {
+                    for (SurfNum = Zone(Loop).HTSurfaceFirst; SurfNum <= Zone(Loop).SurfaceLast; ++SurfNum) {
                         if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc]: Delete?

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 17]
```diff
@@ -6246,7 +6246,7 @@ namespace ZoneTempPredictorCorrector {
             SumSysMCpT /= ZoneMult;
         }
         // Sum all surface convection: SumHA, SumHATsurf, SumHATref (and additional contributions to SumIntGain)
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
 
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc]: Delete?

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 18]
```diff
@@ -6542,7 +6542,7 @@ namespace ZoneTempPredictorCorrector {
         SumNonAirSystem = NonAirSystemResponse(ZoneNum) + SumConvHTRadSys(ZoneNum) + SumConvPool(ZoneNum);
 
         // Sum all surface convection: SumHA, SumHATsurf, SumHATref (and additional contributions to SumIntGain)
-        for (SurfNum = Zone(ZoneNum).SurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
+        for (SurfNum = Zone(ZoneNum).HTSurfaceFirst; SurfNum <= Zone(ZoneNum).SurfaceLast; ++SurfNum) {
 
             if (!Surface(SurfNum).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc]: Deete?

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 19]
```diff
@@ -1443,10 +1443,30 @@ namespace SurfaceGeometry {
 
                 if (SurfaceTmpClassMoved(SubSurfNum)) continue;
                 if (state.dataSurfaceGeometry->SurfaceTmp(SubSurfNum).Zone != ZoneNum) continue;
+                if (state.dataSurfaceGeometry->SurfaceTmp(SubSurfNum).ExtBoundCond > 0) continue; // Exterior
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc]: The comments above starting at line 1318 should describe these new groupings/order.

File: src/EnergyPlus/DataHeatBalance.hh [hunk 20]
```diff
@@ -696,12 +696,15 @@ namespace DataHeatBalance {
...
         //            Pointers to Surface Data Structure
         int AllSurfaceFirst;       // First surface in zone including air boundaries
-        int SurfaceFirst;          // First Heat Transfer Surface in Zone
+        int HTSurfaceFirst;          // First Heat Transfer Surface in Zone
         int SurfaceLast;           // Last  Heat Transfer Surface in Zone
         int NonWindowSurfaceFirst; // First Non-Window Heat Transfer Surface in Zone
         int NonWindowSurfaceLast;  // Last  Non-Window Heat Transfer Surface in Zone
         int WindowSurfaceFirst;    // First Window Heat Transfer Surface in Zone
         int WindowSurfaceLast;     // Last  Window Heat Transfer Surface in Zone
+        int NonDomeLast;          // Last non TDD Dome Surface in Zone
```
Comment (mjwitte) [inline src/EnergyPlus/DataHeatBalance.hh]: The comments here need to be very clear about what's included in each group since some of these overlap.

**Review by mjwitte — COMMENTED** [review]
Ran unit tests locally - all OK.

Reviewed results for the defect file and for testfile DaylightingDeviceTubular before and after this fix. Changes look reasonable and dome and diffuser surface temps match each other now (not perfect, but as designed).

Some code comments below.

File: src/EnergyPlus/DataHeatBalance.hh (hunk 20 above)
Comment (amirroth) [reply src/EnergyPlus/DataHeatBalance.hh]: For clarity and self-documentation purposes, I suggest that these things be done in pairs, XFirst/XLast. Even if some combination of XFirst and YFirst or XLast and YLast are redundant, that is better than having to remember which combination of XFirst and YLast corresponds to which subset. The name X can be the descriptive name of the subset.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 21]
```diff
@@ -7062,7 +7061,7 @@ namespace HeatBalanceSurfaceManager {
         for (int zoneNum = FirstZone; zoneNum <= LastZone; ++zoneNum) {
             // loop over all heat transfer surface except TDD Dome.
             int const firstSurf = Zone(zoneNum).HTSurfaceFirst;
-            int const lastSurf = Zone(zoneNum).NonDomeLast;
+            int const lastSurf = Zone(zoneNum).OpaqOrWinSurfaceLast;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: `HTSurfaceFirst` --> `OpaqOrWinSurfaceFirst`

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 22]
```diff
@@ -7484,7 +7483,7 @@ namespace HeatBalanceSurfaceManager {
                 }
 
                 int const firstSurf = Zone(zoneNum).HTSurfaceFirst;
-                int const lastSurf = Zone(zoneNum).NonDomeLast;
+                int const lastSurf = Zone(zoneNum).OpaqOrWinSurfaceLast;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: Same here.

File: src/EnergyPlus/HeatBalanceSurfaceManager.cc [hunk 23]
```diff
@@ -7581,7 +7580,7 @@ namespace HeatBalanceSurfaceManager {
         // Set various surface output variables and other record keeping - after iterations are complete - all HT surfaces
         for (int zoneNum = FirstZone; zoneNum <= LastZone; ++zoneNum) {
             int const firstSurf = Zone(zoneNum).HTSurfaceFirst;
-            int const lastSurf = Zone(zoneNum).NonDomeLast;
+            int const lastSurf = Zone(zoneNum).OpaqOrWinSurfaceLast;
```
Comment (mjwitte) [inline src/EnergyPlus/HeatBalanceSurfaceManager.cc]: And here.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 24]
```diff
@@ -13797,7 +13797,7 @@ namespace EnergyPlus::OutputReportTabular {
                 Real64 adjFeneSurfNetRadSeq = 0.0;
 
                 // code from ComputeDelayedComponents starts
-                for (int jSurf = Zone(zoneIndex).HTSurfaceFirst; jSurf <= Zone(zoneIndex).SurfaceLast; ++jSurf) {
+                for (int jSurf = Zone(zoneIndex).HTSurfaceFirst; jSurf <= Zone(zoneIndex).HTSurfaceLast; ++jSurf) {
                     if (!Surface(jSurf).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc]: Delete.

File: src/EnergyPlus/OutputReportTabular.cc [hunk 25]
```diff
@@ -14011,7 +14011,7 @@ namespace EnergyPlus::OutputReportTabular {
 
             // opaque surfaces - must combine individual surfaces by class and other side conditions
             delayOpaque = 0.0;
-            for (int kSurf = Zone(zoneIndex).HTSurfaceFirst; kSurf <= Zone(zoneIndex).SurfaceLast; ++kSurf) {
+            for (int kSurf = Zone(zoneIndex).HTSurfaceFirst; kSurf <= Zone(zoneIndex).HTSurfaceLast; ++kSurf) {
                 if (!Surface(kSurf).HeatTransSurf) continue; // Skip non-heat transfer surfaces
```
Comment (mjwitte) [inline src/EnergyPlus/OutputReportTabular.cc]: Delete.

File: src/EnergyPlus/ThermalComfort.cc (hunk 14 above)
Comment (mjwitte) [reply src/EnergyPlus/ThermalComfort.cc]: Delete first part of `if`

File: src/EnergyPlus/SurfaceGeometry.cc [hunk 26]
```diff
@@ -1458,27 +1453,8 @@ namespace SurfaceGeometry {
...
-                SurfaceTmpClassMoved(SubSurfNum) = true; // 'Moved'
-                // Reset BaseSurf to it's positive value (set to negative earlier)
-                Surface(MovedSurfs).BaseSurf = -Surface(MovedSurfs).BaseSurf;
-                state.dataSurfaceGeometry->SurfaceTmp(SubSurfNum).BaseSurf = -1;
-                // Find and replace negative SubSurfNum with new MovedSurfs num in surface list for reporting
-                std::replace(DataSurfaces::AllSurfaceListReportOrder.begin(), DataSurfaces::AllSurfaceListReportOrder.end(), -SubSurfNum, MovedSurfs);
-            }
-
-            // The window subsurfaces (includes SurfaceClass::TDD_Diffuser)
+            // The exterior window subsurfaces (includes SurfaceClass::Window and SurfaceClass::GlassDoor) goes next
```
Comment (mjwitte) [inline src/EnergyPlus/SurfaceGeometry.cc:1461]: Remember to edit the comment block at the top of this function to be current and it should mention the various first/last variables.

File: src/EnergyPlus/DataHeatBalance.hh [hunk 27]
```diff
@@ -696,15 +696,17 @@ namespace DataHeatBalance {
...
         int AllSurfaceFirst;       // First surface in zone including air boundaries
-        int HTSurfaceFirst;          // First Heat Transfer Surface in Zone
-        int SurfaceLast;           // Last  Heat Transfer Surface in Zone
-        int NonWindowSurfaceFirst; // First Non-Window Heat Transfer Surface in Zone
-        int NonWindowSurfaceLast;  // Last  Non-Window Heat Transfer Surface in Zone
+        int AllSurfaceLast;        // Last  surface in zone including air boundaries
+        int HTSurfaceFirst;        // First Heat Transfer Surface in Zone
+        int HTSurfaceLast;         // Last  Heat Transfer Surface in Zone
+        int OpaqOrIntMassSurfaceFirst; // First Opaque or Interior Mass Heat Transfer Surface in Zone
+        int OpaqOrIntMassSurfaceLast;  // Last  Opaque or Interior Mass Heat Transfer Surface in Zone
```
Comment (mjwitte) [inline src/EnergyPlus/DataHeatBalance.hh]: Just be clear, I would add `(including doors)`

**Review by mjwitte — APPROVED** [review]
@xuanluo113 This is a great improvement - loop intent is soooo much clearer now. 

I've noted a few things below that can be cleaned up later. 

Mac CI looks good, but I'll let Linux finish before merging this today.

**Comment by Myoldmopar** [comment]
Alright, lots of conflicts, but they were all tiny and easy to resolve as expected.  I've got them nearly done and I'll push it up and let CI have another pass tonight.

**Comment by xuanluo113** [comment]
@Myoldmopar Thanks.

**Comment by Myoldmopar** [comment]
Ran all unit and integration tests, they pass.  Spot checked regressions, they look similar to what was happening on here.  If CI agrees, then I believe this will be ready to go in later.

**Comment by xuanluo113** [comment]
@Myoldmopar Thanks. Added a commit of minor updates of some code comments.

File: src/EnergyPlus/DaylightingManager.cc [hunk 28]
```diff
@@ -2142,8 +2142,8 @@ namespace EnergyPlus::DaylightingManager {
                 }
                 if (ExtWinType == DataDaylighting::iExtWinType::AdjZoneExtWin) {
                     // Does ray pass through an interior window in zone (ZoneNum) containing the ref point?
-                    for (IntWin = Zone(ZoneNum).WindowSurfaceFirst; IntWin <= Zone(ZoneNum).WindowSurfaceLast; ++IntWin) {
-                        if (Surface(IntWin).ExtBoundCond >= 1) {
+                    for (IntWin = state.dataHeatBal->Zone(ZoneNum).WindowSurfaceFirst; IntWin <= state.dataHeatBal->Zone(ZoneNum).WindowSurfaceLast; ++IntWin) {
+                        if (Surface(IntWin).ExtBoundCond >= 1) { // in develop this was Surface(IntWin).Class == SurfaceClass::Window && Surface(IntWin).ExtBoundCond >= 1
```
Comment (mjwitte) [inline src/EnergyPlus/DaylightingManager.cc:2146]: @Myoldmopar Right, the `if==Window` is redundant now, because the loop is over just window surfaces.

File: src/EnergyPlus/ZoneTempPredictorCorrector.cc [hunk 29]
```diff
@@ -2721,8 +2721,8 @@ namespace ZoneTempPredictorCorrector {
 
             for (Loop = 1; Loop <= state.dataGlobal->NumOfZones; ++Loop) {
                 FirstSurfFlag = true;
-                if (Zone(Loop).HTSurfaceFirst > 0) {
-                    for (SurfNum = Zone(Loop).HTSurfaceFirst; SurfNum <= Zone(Loop).HTSurfaceLast; ++SurfNum) {
+                if (state.dataHeatBal->Zone(Loop).HTSurfaceFirst > 0) {
```
Comment (mjwitte) [inline src/EnergyPlus/ZoneTempPredictorCorrector.cc]: @xuanluo113 Is this line still necessary?

Comment (xuanluo113) [reply src/EnergyPlus/ZoneTempPredictorCorrector.cc]: it's okay to remove.

**Comment by Myoldmopar** [comment]
1 file with diffs, just like before.  However, there is one unit test that was failing with an array index problem in the previous commit, unrelated to bringing in develop.  @xuanluo113 it looks like it might've been introduced with the "address comments" commit (https://github.com/NREL/EnergyPlus/pull/8540/commits/8b9fde0d7f6f5051929036ff2d0b6d81b6d000e9).  That'll need to be addressed before merging this.

**Comment by mitchute** [comment]
@Myoldmopar I built and ran unit tests here locally. They all ran successfully.

```
[----------] Global test environment tear-down
[==========] 1510 tests from 26 test suites ran. (140266 ms total)
[  PASSED  ] 1510 tests
```

**Comment by mitchute** [comment]
Debug also passess

```
[----------] Global test environment tear-down
[==========] 1510 tests from 26 test suites ran. (789286 ms total)
[  PASSED  ] 1510 tests.
```

**Comment by Myoldmopar** [comment]
OK, so Ci is way too bogged down right now.  We're going to take evidence from multiple sources here to get this merged.
 - The one diff is what was being seen before, no problem
 - @mitchute confirmed that the unit test passes in a debug build, thanks
 - I ran some sampled performance runs locally, and I didn't have time to run the full suites, but I did run chunks of annual runs.  The results were basically a wash, no real major gains across the board, but some files did show a few percent improvement. 

I am going to merge this now so we can move on.  Thanks @xuanluo113 and @mjwitte

**Comment by mjwitte** [comment]
Linux results finally came through. Performance improvement is 0.2136%. Not huge, but moving in the right direction.

**Comment by amirroth** [comment]
A couple of things. 

First, I thought the point of this particular PR was to fix a bug because TDD_dome was being included in the wrong calculations.

Second, performance-wise getting one data-driven branch out of a loop is good because you are not hitting branch mispredictions and pipeline flushes as often. But it is not enough to optimizations like vectorization going. You need to get all of these types of branches (and crazy function calls like the `EvalInsideMovableInsulation`) out before that stuff kicks in. Just looking over `HeatBalanceSurfaceManager`, there are still multiple places where we do `if (!Surface(SurfNum).HeatTransSurf) continue;` and I am sure we are still doing it in other files as well. I was not expecting a big performance improvement just from this specific PR, but it is a performance design pattern that we need to establish. Along with other code/documentation design patterns like matching First/Last pairs, and positive descriptors for variables. 

I am happy with this PR.
