### PR TITLE
Crash when using ITE in an Uncontrolled Zone

### LINKED ISSUE #8986: Hard crash in ITE equipment for uncontrolled zone.
Issue overview
--------------
User file had ITE equipment in a zone with no HVAC equipment, ie. not a controlled zone.  Got a hard crash in the following code block. 

Need a trap in case zoneEqIndex  returns 0 so it won't then crash in the next lines. 

```
                // check supply air node for matches with zone equipment supply air node
                int zoneEqIndex =
                    DataZoneEquipment::GetControlledZoneIndex(state, state.dataHeatBal->Zone(state.dataHeatBal->ZoneITEq(Loop).ZonePtr).Name);
                auto itStart = state.dataZoneEquip->ZoneEquipConfig(zoneEqIndex).InletNode.begin();
                auto itEnd = state.dataZoneEquip->ZoneEquipConfig(zoneEqIndex).InletNode.end();
```

When that gets trapped, it then crashes again here 

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/InternalHeatGains.cc#L6810

Of course the ITE closet with no cooling blows up eventually but it will terminate gracefully rather than hard crash. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by RKStrand**
Pull request overview
---------------------
 - Fixes #8986
 - A user noted that when using ITE with an uncontrolled zone that EnergyPlus crashes.  A test idf was constructed to verify that was happening (this has been added to the development GitHub site in a new folder for this defect).  The code was modified to allow users to define ITE for uncontrolled zones and the test file now runs to completion.  A unit test was also created to verify this code modification.  Finally, during the analysis of this defect, it was noticed that the code does not allow users to use the RoomAirModel option for the air inlet connection type field.  The documentation was modified to reflect that restriction.  A new issue will be added to deal with at a later date.  No differences are expected in the ci output.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [X] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [X] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] ~If feature, test running new feature, try creative ways to break it~
 - [x] CI status: all green or justified
 - [x] Check that performance is not impacted (CI Linux results include performance check)
 - [x] Run Unit Test(s) locally
 - [ ] ~Check any new function arguments for performance impacts~
 - [ ] ~Verify IDF naming conventions and styles, memos and notes and defaults~
 - [ ] ~If new idf included, locally check the err file and other outputs~

### CODE REVIEW

**Review by EnergyArchmage — APPROVED** [review]

File: src/EnergyPlus/InternalHeatGains.cc [hunk 1]
```diff
@@ -7761,8 +7763,14 @@ namespace InternalHeatGains {
                     WAirIn = state.dataHeatBalFanSys->ZoneAirHumRat(NZ);
                 } else {
                     // TAirIn = TRoomAirNodeIn, according to EngineeringRef 17.1.4
-                    int ZoneAirInletNode = state.dataZoneEquip->ZoneEquipConfig(NZ).InletNode(1);
-                    TSupply = state.dataLoopNodes->Node(ZoneAirInletNode).Temp;
+                    int zoneEqIndex =
+                        DataZoneEquipment::GetControlledZoneIndex(state, state.dataHeatBal->Zone(state.dataHeatBal->ZoneITEq(Loop).ZonePtr).Name);
```
Comment (rraustad) [inline src/EnergyPlus/InternalHeatGains.cc]: Would be faster to save the zoneEqIndex in the ZoneITEq struct than to look it up each iteration for each IT equipment.

File: tst/EnergyPlus/unit/InternalHeatGains.unit.cc [hunk 2]
```diff
@@ -2473,3 +2473,132 @@ TEST_F(EnergyPlusFixture, InternalHeatGains_WarnMissingInletNode)
...
+    state->dataHeatBalFanSys->MAT.allocate(1);
+    state->dataHeatBalFanSys->ZoneAirHumRat.allocate(1);
+
+    state->dataHeatBalFanSys->MAT(1) = 24.0;
+    state->dataHeatBalFanSys->ZoneAirHumRat(1) = 0.008;
+
+    InternalHeatGains::GetInternalHeatGainsInput(*state);
+    ASSERT_FALSE(ErrorsFound);
+
+    state->dataGlobal->numSpaces = 0;
```
Comment (rraustad) [inline tst/EnergyPlus/unit/InternalHeatGains.unit.cc]: One would not think to add this line, numSpaces=0, since it initializes to 0, so out of curiosity, did you need to add this line for some reason?

Comment (RKStrand) [reply tst/EnergyPlus/unit/InternalHeatGains.unit.cc]: @rraustad There was no specific reason.  I was being very "definitive" just to make sure that I had control over that variable.  I can try removing it--if it's initialized properly then there should be no change in how the test runs.

Comment (rraustad) [reply tst/EnergyPlus/unit/InternalHeatGains.unit.cc]: I wasn't suggesting a change but I suspect you will save the zoneEqIndex (or zoneEqConfigIndex?) to speed things up. You can delete this line for that commit.

File: src/EnergyPlus/InternalHeatGains.cc (hunk 1 above)
Comment (Myoldmopar) [reply src/EnergyPlus/InternalHeatGains.cc]: I concur, if this lookup is happening often we should definitely modify it so that it looks up the index once.  If this isn't happening multiple times then this is obviously fine.

Comment (RKStrand) [reply src/EnergyPlus/InternalHeatGains.cc]: It's definitely not a one-time thing.  I'll fix that (hopefully today) and make another commit (that will include getting rid of the =0 thing in the unit test as well).

File: tst/EnergyPlus/unit/InternalHeatGains.unit.cc (hunk 2 above)
Comment (RKStrand) [reply tst/EnergyPlus/unit/InternalHeatGains.unit.cc]: Confirming here that getting rid of that line does not cause any problems.  So, this removal will get updated in the next commit.

File: src/EnergyPlus/InternalHeatGains.cc (hunk 1 above)
Comment (RKStrand) [reply src/EnergyPlus/InternalHeatGains.cc]: This now looks up and saves the value, avoiding doing this more than once per ZoneITEq.  Change has been committed, branch updated to develop, and all of that pushed so that CI will run.  Hopefully this resolves this.  Thanks!

File: src/EnergyPlus/InternalHeatGains.cc [hunk 3]
```diff
@@ -7762,8 +7764,17 @@ namespace InternalHeatGains {
                     WAirIn = state.dataHeatBalFanSys->ZoneAirHumRat(NZ);
                 } else {
                     // TAirIn = TRoomAirNodeIn, according to EngineeringRef 17.1.4
-                    int ZoneAirInletNode = state.dataZoneEquip->ZoneEquipConfig(NZ).InletNode(1);
-                    TSupply = state.dataLoopNodes->Node(ZoneAirInletNode).Temp;
+                    if (!state.dataHeatBal->ZoneITEq(Loop).gotControlledZoneIndex) { // Do the following only once to save time
+                        state.dataHeatBal->ZoneITEq(Loop).zoneEqIndex =
+                            DataZoneEquipment::GetControlledZoneIndex(state, state.dataHeatBal->Zone(state.dataHeatBal->ZoneITEq(Loop).ZonePtr).Name);
+                        state.dataHeatBal->ZoneITEq(Loop).gotControlledZoneIndex = true;
+                    }
```
Comment (rraustad) [inline src/EnergyPlus/InternalHeatGains.cc]: I was thinking of doing this around line 2918 where the zoneEqIndex is already found early on. Initializing there would remove this conditional here at lines 7767-7771 and also remove the need for the new bool gotControlledZoneIndex. Unless there is some reason zoneEqIndex cannot be reliably found there, of course.

Comment (RKStrand) [reply src/EnergyPlus/InternalHeatGains.cc]: Well, that is definitely what I should have done before--much cleaner and no need for the extra bool variable.  Kicking myself because I had looked at that code at one point but then forgot that it was there.  The code around line 2918 basically is assuming the information is available.  If not, there's another problem with the code.  Fixed this and made another commit just now.  Hopefully CI comes back clean.

**Comment by rraustad** [comment]
This looks good now.

**Comment by rraustad** [comment]
Confirmed:

- Defect file hard crashes at old line 2918 in develop branch

image

- Defect file runs to completion in this branch using Chicago and Denver weather
- Unit tests run to completion with latest develop
- New unit test correctly exercises new code and with zoneEqIndex = 0, uses MAT as TSupply at line 7772.

image

**Comment by rraustad** [comment]
The prior commit has a -2% performance improvement, which makes sense with previous code changes, so will wait on CI before this merges.

**Review by rraustad — APPROVED** [review]
This all looks good. Waiting on CI to verify no negative impact on performance. Anyone can merge once linux CI shows no performance hit.

**Comment by rraustad** [comment]
@Myoldmopar @mjwitte this seems suspiciously high. Any comments?

image

**Comment by mjwitte** [comment]
My guess is that CI hasn't gotten around to running develop for a while and that number doesn't include #8996 yet, but this branch does include it. Give CI a few hours or wait until tomorrow and this will show near zero change. (The number shown here for develop is "dynamic" it shows whatever the latest value is for develop regardless of when this branch was run).

**Comment by rraustad** [comment]
This branch is behind develop so I assume that is the reason for this result. There is nothing in this branch that would change execution time more than minimally. For this reason, the work is finished.

**Comment by rraustad** [comment]
Out of curiosity, I will wait on the merge.

**Comment by rraustad** [comment]
CI now shows expected result for performance improvement.

image
