### PR TITLE
Fix 9669 - Crash when running a simulation with MultiZoneWithoutDistribution and fan

### LINKED ISSUE #9669: Crash when running a simulation with MultiZoneWithoutDistribution and a fan
Issue overview
--------------
Simulating the defect file(s) results in a hard crash of EnergyPlus. The file uses the `MultiZoneWithoutDistribution` airflow network simulation control option and includes a fan object. Running the file through the  debugger shows that `LoopOnOffFanRunTimeFraction` is needed when a fan is included in the airflow network, however, no allocation is made when the `MultiZoneWithoutDistribution` option is used (see [here](https://github.com/NREL/EnergyPlus/blob/v9.5.0/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L1960-L1971) for 9.5 and [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L2029-L2068) for current code).

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: 9.5 and 22.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [defect_files.zip](https://github.com/NREL/EnergyPlus/files/9628693/defect_files.zip)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by kevin-moos**
Pull request overview
---------------------

- Fixes #9669 

### Description of the purpose of this PR

When distribution_simulated is false, LoopOnOffFanRunTimeFraction is not allocated so these nested loops can be skipped. Even if we instead allocate LoopOnOffFanRunTimeFraction, the default value of 0 still wouldn't meet the conditions for anything to reported so I just added a check for !distribution_simulated.

### Pull Request Author

 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies
 - [ ] If adding/removing any output files (e.g., eplustbl.*)
   - [ ] Update ..\scripts\Epl-run.bat
   - [ ] Update ..\scripts\RunEPlus.bat
   - [ ] Update ..\src\EPLaunch\ MainModule.bas, epl-ui.frm, and epl.vbp (VersionComments)
   - [ ] Update ..\.github\workflows\energyplus.py

### Reviewer

 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Review by tanaya-mankad — APPROVED** [review]

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp [hunk 1]
```diff
@@ -9049,7 +9049,7 @@ namespace AirflowNetwork {
         }
 
         for (AirLoopNum = 1; AirLoopNum <= NumPrimaryAirSys; ++AirLoopNum) {
-            if (DisSysNumOfCVFs == 0) {
+            if (DisSysNumOfCVFs == 0 || !distribution_simulated) {
```
Comment (rraustad) [inline src/EnergyPlus/AirflowNetwork/src/Solver.cpp:9052]: This looks like a good fix. I guess another way would be to make sure whatever array crashed (assuming that is what happened) was allocated? This is probably the easiest and cleanest fix, so this is good.

        CurrentModuleObject = "AirflowNetwork:Distribution:Component:Fan";
        DisSysNumOfCVFs = m_state.dataInputProcessing->inputProcessor->getNumObjectsFound(m_state, CurrentModuleObject);

I wonder if other components could cause the same type of crash? Maybe not since the AFN Coil component works in the unit test. For example:

  AirflowNetwork:Distribution:Component:HeatExchanger
  AirflowNetwork:Distribution:Component:TerminalUnit

**Review by rraustad — APPROVED** [review]

File: src/EnergyPlus/AirflowNetwork/src/Solver.cpp (hunk 1 above)
Comment (mitchute) [reply src/EnergyPlus/AirflowNetwork/src/Solver.cpp:9052]: Agreed. This looks OK. `distribution_simulated` is checked in a bunch of different places, so this is inline with what we're already doing.

**Review by mitchute — APPROVED** [review]
