### PR TITLE
Fix PixelCounting exception thrown by OpenGL destruction in Windows.

### LINKED ISSUE #8788: err and audit outputs are empty with PixelCounting on Windows
Issue overview
--------------
SolarShadingTestGPU (or any file with PixelCounting) completes successfully, but the err and audit output files are empty, only on Windows. 

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 10 ( (tested on 3 different machines, 2 AMD and 1 Intel)
 - Linux and Mac are fine.
 - And v9.4.0 on windows is fine.
 - EnergyPlus 9.5.0 release, and develop at 9.6.0-0adfd25d1c are not fine (on Windows)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### LINKED ISSUE #9091: SolarShadingGPU File "Fails"
Issue overview
--------------
On Windows, with 9.6 (and also even back with 9.5), the GPU test file "fails".  I put quotes, because it looks like it runs fine, but the ERR file comes out empty and it doesn't produce an END file.  This was noticed a few weeks back when I spun up the new Windows CI instance, but I assumed it was a config problem on that machine since it didn't seem to occur elsewhere.  But when doing final testing of 9.6, it seems to be occurring on other machines as well.

### PR DESCRIPTION
**Pull request by tanaya-mankad**
Pull request overview
---------------------
 - Fixes #9091 
 - Also fixed #8788 (duplicate issue).
 - This modification addresses the duplication of the GLAD global state in energypluslib and energyplusdll, by using existing DLL functions to instantiate an EnergyPlus::EnergyPlusData object in main(). In existing code, the declaration of `state` was handled by a copy of the statically linked _energypluslib_ unique to the executable, while the global OpenGL state was handled by a separate object in the dynamically linked _energyplusapi_. On Windows, since global variables are not shared by default, `main()` was effectively trying to deallocate an uninitialized copy of the GLAD globals when it returned.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/main.cc [hunk 1]
```diff
@@ -50,21 +50,24 @@
 #include <EnergyPlus/Data/EnergyPlusData.hh>
 #include <EnergyPlus/DataStringGlobals.hh>
 #include <EnergyPlus/api/EnergyPlusPgm.hh>
+#include <EnergyPlus/api/state.h>
 
 int main(int argc, const char *argv[])
 {
-    EnergyPlus::EnergyPlusData state;
+    EnergyPlus::EnergyPlusData *state = reinterpret_cast<EnergyPlus::EnergyPlusData*>(stateNew());
```
Comment (Myoldmopar) [inline src/EnergyPlus/main.cc]: This is indeed interesting.  The elimination of global variable usage certainly cleaned up the possibility of having multiple copies all over the place, but I didn't imagine state itself would have been the culprit in this.  I believe you, but will need to do some testing to also convince myself.  Since you are calling the state API, you can also just use the `EnergyPlusState` typedef to round out the whole situation.

File: src/EnergyPlus/main.cc [hunk 2]
```diff
@@ -50,21 +50,24 @@
...
-        state.dataStrGlobals->CurrentDateTime = " unknown date/time";
+        state->dataStrGlobals->CurrentDateTime = " unknown date/time";
     }
-    state.dataStrGlobals->VerStringVar = EnergyPlus::DataStringGlobals::VerString + "," + state.dataStrGlobals->CurrentDateTime;
-    EnergyPlus::CommandLineInterface::ProcessArgs(state, argc, argv);
-    return EnergyPlusPgm(state);
+    state->dataStrGlobals->VerStringVar = EnergyPlus::DataStringGlobals::VerString + "," + state->dataStrGlobals->CurrentDateTime;
+    EnergyPlus::CommandLineInterface::ProcessArgs(*state, argc, argv);
+    auto ep_ret = EnergyPlusPgm(*state);
+    stateDelete(reinterpret_cast<EnergyPlusState>(state));
```
Comment (Myoldmopar) [inline src/EnergyPlus/main.cc:71]: So is this _actually_ necessary for `main()` to go through the process of cleaning up state when the next line will terminate the program?

Comment (tanaya-mankad) [reply src/EnergyPlus/main.cc:71]: An intentional memory leak is _actually_ still a memory leak. I don't love the stateDelete and casting shenanigans, but I'd prefer at least a comment if we remove them and rely on termination cleanup. 
These functions happened to be available to us, but are clearly intended for binding through a C interface. The whole thing could be a lot less awkward if the state manipulation in main() could be moved into the DLL entirely. Or, if we had an RAII EnergyPlusState generator class exported from the DLL.

**Comment by Myoldmopar** [comment]
There's a small Clang Format warning that will need to be resolved, but other than that, I see this as a step in the right direction.  If you want to fix that formatting and mark the PR as ready to review, we'll get this in.  Thanks.

**Comment by Myoldmopar** [comment]
Alright, let's mark this one done and merge it.  Thanks @tanaya-bigladder, I would say let's keep talking about the library linkage issues and see if we can get the entire build workflow tightened up ahead of this release.
