### PR TITLE
Fix #8599 - Incorrect psychrometric calculation causes error

### LINKED ISSUE #8599: Incorrect psychrometric calculation causes error
Issue overview
--------------
One of our models generates the following error:
```
   ** Severe  ** SetOutBulbTempAt: Zone Outdoor Temperatures < -100 C
   **   ~~~   ** ...check Zone Heights - Maximum Zone Height=[5].
   **  Fatal  ** Program terminates due to preceding condition(s).
```
The zone height and geometry are fine, so the note about checking zone heights is a red herring.

The file generates an error when I use the [Dover EPW](https://energyplus.net/weather-location/north_and_central_america_wmo_region_4/USA/DE/USA_DE_Dover.AFB.724088_TMY3) but A) the IDF works fine if I use the [Wilmington EPW](https://energyplus.net/weather-location/north_and_central_america_wmo_region_4/USA/DE/USA_DE_Wilmington-New.Castle.County.AP.724089_TMY3) and B) the Dover EPW works fine with another IDF. So it’s somehow the combination of this IDF w/ the Dover EPW that generates the error.

Model:
[data_point.zip](https://github.com/NREL/EnergyPlus/files/6110030/data_point.zip)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus v9.4.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: EnergyPlusDevSupport
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix #8599 - Incorrect psychrometric calculation causes error
- Change PsyPsatFnTemp to correctly use the triple-point of water (0.01°C) to evaluate the two equations 5 and 6 from ASHRAE HoF thus eliminating the discontinuity

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [x] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [x] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [x] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [x] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [x] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/DataGlobalConstants.hh [hunk 1]
```diff
@@ -164,16 +164,17 @@ namespace DataGlobalConstants {
...
-    Real64 constexpr AutoCalculate = -99999.0;        // automatically calculate some fields.
-    Real64 constexpr CWInitConvTemp = 5.05;           // [deg C], standard init chilled water vol to mass flow conversion temp
-    Real64 constexpr HWInitConvTemp = 60.0;           // [deg C], standard init hot water vol to mass flow conversion temp
-    Real64 constexpr SteamInitConvTemp = 100.0;       // [deg C], standard init steam vol to mass flow conversion temp
-    Real64 constexpr StefanBoltzmann = 5.6697E-8;     // Stefan-Boltzmann constant in W/(m2*K4)
-    Real64 constexpr UniversalGasConst = 8314.462175; // Universal Gas Constant (J/mol*K)
-    Real64 constexpr convertJtoGJ = 1.0E-9;           // Conversion factor for J to GJ
-    int constexpr MaxSpeedLevels = 10;                // Maximum number of speed that supports
-    int constexpr ScheduleAlwaysOn = -1;              // Value when passed to schedule routines gives back 1.0 (on)
+    Real64 constexpr TriplePointOfWaterTempKelvin = 273.16; // The triple point of water, in Kelvin
```
Comment (jmarrec) [inline src/EnergyPlus/DataGlobalConstants.hh:167]: New constant

File: src/EnergyPlus/General.cc [hunk 2]
```diff
@@ -972,7 +972,9 @@ void Iterate(Real64 &ResultX,  // ResultX is the final Iteration result passed b
 
         // New guess calculated from LINEAR FIT of most recent two points
         DY = Y0 - Y1;
-        if (std::abs(DY) < small) DY = small;
+        if (std::abs(DY) < small) {
+            DY = small;
+        }
```
Comment (jmarrec) [inline src/EnergyPlus/General.cc:976]: Unrelated, but it's handy to put a debugger breakpoint... (We should have clang-format do that everywhere IMHO)

File: src/EnergyPlus/Psychrometrics.cc [hunk 3]
```diff
@@ -570,10 +573,9 @@ namespace Psychrometrics {
             WBT = ResultX;
 
             // If converged, leave iteration loop.
-            if (icvg == 1) break;
-
-            // Error Trap for the Discontinuous nature of PsyPsatFnTemp function (Sat Press Curve) at ~0 Deg C.
-            if ((PSatstar > 611.000) && (PSatstar < 611.25) && (std::abs(error) <= 0.0001) && (iter > 4)) break;
+            if (icvg == 1) {
+                break;
+            }
```
Comment (jmarrec) [inline src/EnergyPlus/Psychrometrics.cc:531]: Removed the "Error Trap for the Discontinuous nature of PsyPsatFnTemp function (Sat Press Curve) at ~0 Deg C." since it's no longer discontinuous.

File: src/EnergyPlus/Psychrometrics.cc [hunk 4]
```diff
@@ -728,6 +730,11 @@ namespace Psychrometrics {
         // Compared to Table 3 values (August 2007) with average error of 0.00%, max .30%,
         // min -.39%.  (Spreadsheet available on request - Lawrie).
 
+        // Note: the ASHRAE Handbook of Fundamentals  is being slightly inaccurate in its wording,
+        // and referring to Eq 5 applying to -100°C to 0°C and Eq 6 applying to 0°C to 200°C
+        // In fact, it is **not** 0°C, but the triple-point of water, which is 0.01°C. Evaluating the Eq 5 and 6 up to and from the triple-point
+        // is removing the discontinuity altogether.
```
Comment (jmarrec) [inline src/EnergyPlus/Psychrometrics.cc:690]: New note

File: src/EnergyPlus/Psychrometrics.cc [hunk 5]
```diff
@@ -780,21 +787,21 @@ namespace Psychrometrics {
...
             // If below freezing, calculate saturation pressure over ice.
-        } else if (Tkel < DataGlobalConstants::KelvinConv) { // Tkel >= 173.15
-            Real64 const C1(-5674.5359);                     // Coefficient for TKel < KelvinConvK
-            Real64 const C2(6.3925247);                      // Coefficient for TKel < KelvinConvK
-            Real64 const C3(-0.9677843e-2);                  // Coefficient for TKel < KelvinConvK
-            Real64 const C4(0.62215701e-6);                  // Coefficient for TKel < KelvinConvK
-            Real64 const C5(0.20747825e-8);                  // Coefficient for TKel < KelvinConvK
-            Real64 const C6(-0.9484024e-12);                 // Coefficient for TKel < KelvinConvK
-            Real64 const C7(4.1635019);                      // Coefficient for TKel < KelvinConvK
+        } else if (Tkel < DataGlobalConstants::TriplePointOfWaterTempKelvin) { // Tkel >= 173.15, Tkel < 273.16 (0.01°C)
```
Comment (jmarrec) [inline src/EnergyPlus/Psychrometrics.cc:747]: The actual fix

File: src/EnergyPlus/Psychrometrics.cc [hunk 6]
```diff
@@ -780,21 +787,21 @@ namespace Psychrometrics {
 
         // If below -100C,set value of Pressure corresponding to Saturation Temperature of -100C.
         if (Tkel < 173.15) {
-            Pascal = 0.0017;
+            Pascal = 0.001405102123874164;
```
Comment (jmarrec) [inline src/EnergyPlus/Psychrometrics.cc:744]: @rraustad and I noted that the value below -100°C does not match the evaluation of the equation at -100°C. So align.

File: src/EnergyPlus/Psychrometrics.cc [hunk 7]
```diff
@@ -803,6 +810,11 @@ namespace Psychrometrics {
             Real64 const C12(-0.14452093e-7); // Coefficient for TKel >= KelvinConvK
             Real64 const C13(6.5459673);      // Coefficient for TKel >= KelvinConvK
             Pascal = std::exp(C8 / Tkel + C9 + Tkel * (C10 + Tkel * (C11 + Tkel * C12)) + C13 * std::log(Tkel));
+
+            // If above 200C, set value of Pressure corresponding to Saturation Temperature of 200C.
+        } else { // Tkel >= 173.15 // Tkel >= KelvinConv // Tkel > 473.15
+            Pascal = 1555073.745636215;
+        }
```
Comment (jmarrec) [inline src/EnergyPlus/Psychrometrics.cc]: @rraustad and I noted that the value below +200°C does not match the evaluation of the equation at +200°C. So align:
* One value if using the ASHRAE method: `1555073.745636215`
* Another value if using the IF97 method  : `  1554671.8682698254`
* (the ASHRAE and IF97 equations give slightly different values at +200°C)

**Comment by jmarrec** [comment]
The json big diffs: I think the epregression script is unreasonable: https://github.com/NREL/EnergyPlusRegressionTool/blob/237b8a38c280fd0ce6563b6849ae51376e326d66/epregressions/runtests.py#L630-L643

It assumes an absolute difference > 0.0001 is a big diff. This for eg:

image

It's categorized as a big diff, but in fact it's a 1e-12 difference in %...

```python
In [1]: f_1 = 30310597.103115804

In [2]: f_2 = 30310597.102913737

In [3]: abs(f_1 - f_2) > 0.00001
Out[6]: True

In [7]: (f_1 - f_2) / f_1
Out[7]: 6.6665528125937005e-12
```

**Comment by jmarrec** [comment]
The RefrigeratedWarehouse one seems to be unstable to begin with. Lots of warnings about Zone Air Heat Balance is out of balance. The biggest thing I noticed in the html diff are the initialization summary diffs, and especially the number of warmup  days that goes from 8 to 17. I think that may be because it would go into the error trap at iter 4 before. 
Simulation time stays about the same (47s to 52s).



Most of the small mathdiffs seem to be in the EIO, Warmup Convergence Information is slightly different.


```diff
+                                                                                                                                                      v
- Warmup Convergence Information,CORE_MID,SizingPeriod: CHICAGO ANN CLG .4% CONDNS WB=>MDB,0.2742978374,0.4207863935,Pass,Pass,0.2199779749,0.5291400272,Pass,Pass
+ Warmup Convergence Information,CORE_MID,SizingPeriod: CHICAGO ANN CLG .4% CONDNS WB=>MDB,0.2742978374,0.4207863935,Pass,Pass,0.2199779749,0.5291400273,Pass,Pass
```

File: src/EnergyPlus/Psychrometrics.cc (hunk 5 above)
Comment (jmarrec) [reply src/EnergyPlus/Psychrometrics.cc:747]: image

File: src/EnergyPlus/General.cc (hunk 2 above)
Comment (rraustad) [reply src/EnergyPlus/General.cc:976]: Agreed. It's standard practice but not enforced.

File: src/EnergyPlus/Psychrometrics.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:531]: I vaguely remember this. It looks like the unit tests hits this so good there. Gotta check it though.

File: src/EnergyPlus/Psychrometrics.cc (hunk 4 above)
Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:690]: I think you were actually the one that found this critical point. Nice!

**Comment by rraustad** [comment]
This is important to be included. I'd vote for sooner than later. I can't recall all the details here but I think @jmarrec has hit the nail.

**Comment by rraustad** [comment]
I'm OK with these changes. I am trying to think up a test to verify this works, other than a unit test. I do have a high degree of confidence in what this fixes,

**Comment by rraustad** [comment]
@jmarrec help me out here, it's been a while. If this corrects an issue of T=0 C (or 0 - 0.1 C), then how could I verify that this now works? I am torn between accepting this and doing some tests to make sure this is correct. I see what you did here and it looks correct, I just need to verify before sending this home. Details.

**Comment by rraustad** [comment]
Comparing outdoor weather data between this branch and develop doesn't show an obvious issue.

image

Yet, zooming in does show a difference.

image

**Review by rraustad — APPROVED** [review]
@Myoldmopar @mjwitte I recall the reason for this change and agree with these changes.

File: src/EnergyPlus/Psychrometrics.cc [hunk 8]
```diff
@@ -734,29 +741,34 @@ namespace Psychrometrics {
...
             // If below freezing, calculate saturation pressure over ice.
-        } else if (Tkel < DataGlobalConstants::KelvinConv) { // Tkel >= 173.15
-            Real64 constexpr C1(-5674.5359);                 // Coefficient for TKel < KelvinConvK
-            Real64 constexpr C2(6.3925247);                  // Coefficient for TKel < KelvinConvK
-            Real64 constexpr C3(-0.9677843e-2);              // Coefficient for TKel < KelvinConvK
-            Real64 constexpr C4(0.62215701e-6);              // Coefficient for TKel < KelvinConvK
-            Real64 constexpr C5(0.20747825e-8);              // Coefficient for TKel < KelvinConvK
-            Real64 constexpr C6(-0.9484024e-12);             // Coefficient for TKel < KelvinConvK
-            Real64 constexpr C7(4.1635019);                  // Coefficient for TKel < KelvinConvK
+        } else if (Tkel < DataGlobalConstants::TriplePointOfWaterTempKelvin) { // Tkel >= 173.15, Tkel < 273.16 (0.01°C)
```
Comment (rraustad) [inline src/EnergyPlus/Psychrometrics.cc:747]: Why leave this comment as is?  // Tkel >= 173.15, ...

File: src/EnergyPlus/Psychrometrics.cc [hunk 9]
```diff
@@ -734,29 +741,34 @@ namespace Psychrometrics {
...
+            Real64 constexpr C3(-0.9677843e-2);
+            Real64 constexpr C4(0.62215701e-6);
+            Real64 constexpr C5(0.20747825e-8);
+            Real64 constexpr C6(-0.9484024e-12);
+            Real64 constexpr C7(4.1635019);
             Pascal = std::exp(C1 / Tkel + C2 + Tkel * (C3 + Tkel * (C4 + Tkel * (C5 + C6 * Tkel))) + C7 * std::log(Tkel));
 
             // If above freezing, calculate saturation pressure over liquid water.
-        } else if (Tkel <= 473.15) { // Tkel >= 173.15 // Tkel >= KelvinConv
+        } else if (Tkel <= 473.15) { // Tkel >= 173.15 // Tkel >= TriplePointOfWaterTempKelvin
```
Comment (rraustad) [inline src/EnergyPlus/Psychrometrics.cc:758]: The else if above is Tkel < Real64 constexpr TriplePointOfWaterTempKelvin = 273.16; and this is <= 473.15 ... oh yeah, this is the top end so comment is wrong.

File: src/EnergyPlus/Psychrometrics.cc [hunk 10]
```diff
@@ -734,29 +741,34 @@ namespace Psychrometrics {
...
+            Real64 constexpr C8(-5800.2206);
+            Real64 constexpr C9(1.3914993);
+            Real64 constexpr C10(-0.048640239);
+            Real64 constexpr C11(0.41764768e-4);
+            Real64 constexpr C12(-0.14452093e-7);
+            Real64 constexpr C13(6.5459673);
             Pascal = std::exp(C8 / Tkel + C9 + Tkel * (C10 + Tkel * (C11 + Tkel * C12)) + C13 * std::log(Tkel));
+
+            // If above 200C, set value of Pressure corresponding to Saturation Temperature of 200C.
+        } else { // Tkel >= 173.15 // Tkel >= TriplePointOfWaterTempKelvin // Tkel > 473.15
```
Comment (rraustad) [inline src/EnergyPlus/Psychrometrics.cc:769]: So shouldn't this be the top end? 473.15 ?

Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:769]: Oh, it's only a comment issue.

**Comment by rraustad** [comment]
Let's see what the follow up responses are before merging this one.

**Comment by rraustad** [comment]
I'd say this is good except for lingering comments in code.

File: src/EnergyPlus/Psychrometrics.cc (hunk 3 above)
Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:531]: Yeah, I remember this now, this is a check for where this used to have a problem. Now that the problem is corrected, this check is no longer needed.

**Comment by rraustad** [comment]
In the zoomed in plot [above](https://github.com/NREL/EnergyPlus/pull/8833#issuecomment-913089847) there is an outlier at X= -0.43128 (develop), Y= -0.10992 (this branch). This occurred on 4/3 19:07:30 at row 11669 (and similar point at row 11670 - 19:15:00). Plotting rows 11660 - 11680 shows the WB traces for both branches. This branch smooths out the calculated wet-bulb temperature.

image

Note: additional reports added to diagnose problem and corrective fix.

    Output:Variable,Outside Air Inlet Node 1,System Node Humidity Ratio,detailed;
    Output:Variable,Outside Air Inlet Node 1,System Node Pressure,detailed;
    Output:Variable,Outside Air Inlet Node 1,System Node Wetbulb Temperature,detailed;
    Output:Variable,Outside Air Inlet Node 1,System Node Dewpoint Temperature,detailed;

The outdoor conditions at this same time show that OA WB should be smooth and this branch shows the correct result. If I were to do this again I would use System Node OA temp instead of weather OAT to fill in the gaps in the zone timestep environment report. But this is good enough to show this branch corrects the problem.

image

File: src/EnergyPlus/Psychrometrics.cc (hunk 8 above)
Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:747]: OK, this one is OK, this is the -200C point (173.15 K) not the triple point.

File: src/EnergyPlus/Psychrometrics.cc (hunk 9 above)
Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:758]: These comments are a little confusing but a second looks shows they say what they said before with updates to what was changed. I'd say this is OK.

File: src/EnergyPlus/Psychrometrics.cc (hunk 10 above)
Comment (rraustad) [reply src/EnergyPlus/Psychrometrics.cc:769]: Same for this comment, these are each true and true as a whole.

**Review by rraustad — APPROVED** [review]
Code reviewed and tested using example file. Results show an improvement in calculated wet-bulb temperature.

File: src/EnergyPlus/Psychrometrics.cc (hunk 9 above)
Comment (jmarrec) [reply src/EnergyPlus/Psychrometrics.cc:758]: I think the comments provide little value overall here, but there were pre-existing. and they should be correct.
