### PR TITLE
ZoneHVAC:FourPipeFanCoil shows a fatal sizing error when autosized coil inlet temperature is negative

### LINKED ISSUE #9464: Fan coil fatal sizing error
Issue overview
--------------
The attached input file from the ASHRAE Standard 140 air-side equipment (AE) tests ran fine in v8.5, but fails in v22.1.0:
```
   ** Severe  ** SizeWaterCoil Coil:Cooling:Water ZONE ONE COOLING COIL, Developer Error: Component sizing incomplete.
   **   ~~~   ** SizingString = Design Inlet Air Temperature [C], SizingResult = -99998.9
   ** Severe  ** Developer Error: sizing of Design Inlet Air Temperature [C] failed.
   **   ~~~   ** Occurs in Coil:Cooling:Water ZONE ONE COOLING COIL
```
Not sure what the issue is with this particular file. Other fan coil test files (such as HVACTemplate-5ZoneFanCoil.idf) run fine with a fully autosized cooling coil. In this file, the cooling coil is fully autosized except the air flow rate has a hard value, and the cooling load happens to be zero for this test case.

### Workaround
Filling in all of the autosized fields in the cooling coil object gets around the problem. This is a special case, so that was possible here.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.1.0-10c89547de

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached: 
[CaseAET101a-FanCoil-Broken.idf.txt](https://github.com/NREL/EnergyPlus/files/8809510/CaseAET101a-FanCoil-Broken.idf.txt)
[CaseAET101a-FanCoil-Workaround.idf.txt](https://github.com/NREL/EnergyPlus/files/8809511/CaseAET101a-FanCoil-Workaround.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by rraustad**
Pull request overview
---------------------
 - Fixes #9464
 - A negative value for an autosized input field may result in a fatal message from the sizing routines as "Developer Error". This specific instance of a false message was corrected.

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/Autosizing/Base.cc [hunk 1]
```diff
@@ -413,6 +413,9 @@ void BaseSizer::selectSizerOutput(EnergyPlusData &state, bool &errorsFound)
                 }
             }
             if (!this->wasAutoSized) this->autoSizedValue = this->originalValue;
+        } else if (this->wasAutoSized && this->autoSizedValue != DataSizing::AutoSize) {
+            this->reportSizerOutput(
+                state, this->compType, this->compName, "Design Size " + this->sizingStringScalable + this->sizingString, this->autoSizedValue);
```
Comment (rraustad) [inline src/EnergyPlus/Autosizing/Base.cc:418]: This opens up the possibility that an autosized value can be negative. I find it 1) hard to believe we haven't seen this before and 2) whether it is smart to allow a negative number for all autosizable fields or just some (e.g., temperature).

I guess since the autosized value was "something" other than DataSizing::AutoSize then the sizing routine did do something and should be reported.

**Comment by rraustad** [comment]
There is another issue in this defect file. The fan coil air flow and OA flow are hard-sized, yet sizing is using the FinalZoneSizing data (i.e., the autosized zone air flow) to calculate the coil inlet temperature (i.e., find the OA frac to do mixing). Since the autosized air flow is less than the hard-sized OA flow, OA frac = 1 and the coil inlet temperature results in the value of outdoor air temperature, which is clearly wrong given the hard-sized flow rates.

File: tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc [hunk 2]
```diff
@@ -76,6 +76,47 @@ using namespace EnergyPlus::DataSizing;
...
+    // set up inputs used for sizing
+    Real64 TempSize = DataSizing::AutoSize;
+
+    // call the selectSizerOutput function to make sure this input configuration is caught
+    thisSizer.initializeWithinEP(*state, CompType, CompName, PrintFlag, RoutineName);
+    Real64 autoSizedValue = thisSizer.size(*state, TempSize, errorsFound);
+
+    EXPECT_EQ(-1.0, autoSizedValue);
+    EXPECT_TRUE(compare_enums(AutoSizingResultType::NoError, thisSizer.errorType));
+}
```
Comment (Myoldmopar) [inline tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc:118]: There's a special place in my heart for EnergyPlus unit tests that don't have IDF snippets and simply operate directly on objects and methods.

**Review by Myoldmopar — APPROVED** [review]
This seems reasonable and has a great unit test.

**Comment by Myoldmopar** [comment]
> There is another issue in this defect file.

@rraustad are you saying that there is something else we need to modify in code to handle the bad inputs?  Or just that the defect file has issues.  Either way, you aren't planning on addressing any other issues in this PR, right?  Seems ready to merge, and I will start testing it out locally.

**Comment by rraustad** [comment]
This PR addresses the fatal error. I did notice while working on this that the OA fraction used to size the coil was incorrect. This is a result of this fan-coil defect file hard-sizing the air flow rates while the sizing routine uses the autosized air flow rate and is passed the hard-sized OA flow rate. This resulted in OAfrac = 1 and the negative temp that caused sizing to fatal out with the "Developer Error" warning. I'll post another issue to correct this other defect. See #9496.

This is another StdRhoAir change where some components are not using the same sizing methodology as other components. The fan coil uses the zone design mass flow rate while other components use the volume flow rate passed by the parent multipled (now) by StdRhoAir. These are 2 very different values for hard-sized equipment as the comment shows.

    } else if (this->zoneEqFanCoil) {
        // use fan coil flow (i.e., set by parent) or flow used during sizing?
        Real64 DesMassFlow = this->finalZoneSizing(this->curZoneEqNum).DesCoolMassFlow;

This should be as easy as changing this line to use DesVolFlow * StdRhoAir but will likely cause diffs that will need review. And this is also part of the sizing routine clean up that we have been planning for years. The PTUnit to UnitarySystem conversion forced my hand at starting this now.

**Comment by Myoldmopar** [comment]
That all sounds great @rraustad, I built it with latest develop and everything is good.  No reason to hold this up, merging.  Thanks!
