### PR TITLE
Fix #8586 - Z format fails when requested with zero or one significant digits

### LINKED ISSUE #8586: Z format fails when requested with zero significant digits
Issue overview
--------------
If the Z format is requested with zero significant digits, a release build will output an incorrect value such as "1E00" and a debug build will fail (on windows):
image

The offending call is [here in `PreDefTableEntry`](https://github.com/NREL/EnergyPlus/blob/78d2a6a8347bbeefc756a319c421dc7ac9dd086d/src/EnergyPlus/OutputReportPredefined.cc#L1293) with `sigDigitCount=0`.

The Z format is intended to mimic the older E format such as 0.11E+09 so requesting it with 0 significant digits is nonsense. Forcing a minimum of 2 sig digits is probably the best approach along with re-evaluating why the OA details report author thought zero was a good idea.

### Details
Some additional details for this issue (if relevant):
 - Win64 (build with VS2019 16.8.6)
 - Version of EnergyPlus 9.5.0-a12bdf0a7d
 - Stumbled across while reviewing #8577.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fix #8586 - Z format fails when requested with zero or one significant digits

### Gtests before fix:

<details>
<summary>Click to see results</summary>

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from EnergyPlusFixture
[ RUN      ] EnergyPlusFixture.OutputFiles_Expected_Formatting_Tests
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/OutputFiles.unit.cc:200: Failure
Expected equality of these values:
  format("{:12.1Z}", 100.0 )
    Which is: "       1E00\0"
  "     0.1E+03"
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/OutputFiles.unit.cc:205: Failure
Expected equality of these values:
  format("{:12.1Z}", 123.456)
    Which is: "       1E00\0"
  "     0.1E+03"
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/OutputFiles.unit.cc:210: Failure
Expected equality of these values:
  format("{:12.1Z}", 0.0 )
    Which is: "       0E00\0"
  "     0.0E+00"
[  FAILED  ] EnergyPlusFixture.OutputFiles_Expected_Formatting_Tests (145 ms)
[----------] 1 test from EnergyPlusFixture (145 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (145 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EnergyPlusFixture.OutputFiles_Expected_Formatting_Tests

 1 FAILED TEST

    Start 1767: EnergyPlusFixture.OutputReportTabularTest_PredefinedTable_SigDigits_Force_NonZero
2/2 Test #1767: EnergyPlusFixture.OutputReportTabularTest_PredefinedTable_SigDigits_Force_NonZero ...***Failed    0.16 sec
Note: Google Test filter = EnergyPlusFixture.OutputReportTabularTest_PredefinedTable_SigDigits_Force_NonZero
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from EnergyPlusFixture
[ RUN      ] EnergyPlusFixture.OutputReportTabularTest_PredefinedTable_SigDigits_Force_NonZero
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/OutputReportTabular.unit.cc:9809: Failure
Expected equality of these values:
  "0.12E+09"
  RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchPlantSizMeasVdot, "MyPlant Sizing Pass 1")
    Which is: "1E00\0"
/home/julien/Software/Others/EnergyPlus/tst/EnergyPlus/unit/OutputReportTabular.unit.cc:9813: Failure
Expected equality of these values:
  "0.12E+09"
  RetrievePreDefTableEntry(*state, state->dataOutRptPredefined->pdchPlantSizCalcVdot, "MyPlant Sizing Pass 1")
    Which is: "1E00\0"
[  FAILED  ] EnergyPlusFixture.OutputReportTabularTest_PredefinedTable_SigDigits_Force_NonZero (143 ms)
[----------] 1 test from EnergyPlusFixture (143 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (143 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EnergyPlusFixture.OutputReportTabularTest_PredefinedTable_SigDigits_Force_NonZero
```

</details>

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/IOFiles.cc [hunk 1]
```diff
@@ -613,9 +614,15 @@ class custom_arg_formatter : public arg_formatter
...
-                if (specs()->precision > 0) {
+                bool initialPrecisionWas1 = false;
+                if (specs()->precision > 1) {
                     // reduce the precision to get rounding behavior
                     --specs()->precision;
+                } else {
+                    // We need AT LEAST one in precision so we capture a '.' below
+                    initialPrecisionWas1 = true;
+                    specs()->precision = 1;
+                    ++specs()->width;
```
Comment (jmarrec) [inline src/EnergyPlus/IOFiles.cc:625]: Another path: if requested precision is 1 (which can be understandable perhaps) or (0 which makes no sense...)

File: src/EnergyPlus/OutputReportPredefined.cc [hunk 2]
```diff
@@ -1322,6 +1322,11 @@ namespace OutputReportPredefined {
             state.dataOutRptPredefined->tableEntry(state.dataOutRptPredefined->numTableEntry).charEntry =
                 format("{:#12.{}F}", tableEntryReal, sigDigitCount);
         } else {
+            // Formatting in scientific notation, zero sigDigits makes zero sense.
+            // **for something greater than 1E+08**, one sigDigits is very unhelpful (you're having an accuracy of 0.5E+07 at best)
+            if (sigDigitCount < 2) {
+                sigDigitCount = 2;
+            }
```
Comment (jmarrec) [inline src/EnergyPlus/OutputReportPredefined.cc:1329]: In PreDefTableEntry, if the value we passed is > 1e+08, and we requested an original precision below 2 digits, we reset to 2 digits.

File: tst/EnergyPlus/unit/OutputFiles.unit.cc [hunk 3]
```diff
@@ -192,5 +193,23 @@ TEST_F(EnergyPlusFixture, OutputFiles_Expected_Formatting_Tests)
...
+
+    EXPECT_EQ(format("{:12.1Z}", 123.456), "     0.1E+03");
+    EXPECT_EQ(format("{:12.2Z}", 123.456), "    0.12E+03"); // Why not 12E
+    EXPECT_EQ(format("{:12.3Z}", 123.456), "   0.123E+03");
+    EXPECT_EQ(format("{:12.4Z}", 123.456), "  0.1235E+03");
+
+    EXPECT_EQ(format("{:12.1Z}",   0.0  ), "     0.0E+00");
+    EXPECT_EQ(format("{:12.2Z}",   0.0  ), "    0.00E+00"); // Why not 12E
+    EXPECT_EQ(format("{:12.3Z}",   0.0  ), "   0.000E+00");
+    EXPECT_EQ(format("{:12.4Z}",   0.0  ), "  0.0000E+00");
```
Comment (jmarrec) [inline tst/EnergyPlus/unit/OutputFiles.unit.cc]: New unit tests for the Z format

File: src/EnergyPlus/OutputReportPredefined.cc (hunk 2 above)
Comment (jmarrec) [reply src/EnergyPlus/OutputReportPredefined.cc:1329]: This the root cause of #8586. The author of the code figured that 0 precision was good enough because the value was large enough. eg if `12345.6789` is passed, then `12345.` is issued (`{:#12.0F}` is used). But if you suddenly pass a very large value, then it automatically switches to scientific notation, in which case the sigDigits=0 is senseless

**Comment by jmarrec** [comment]
Some python code to check all occurrences of Calling PreDefTableEntry with numSigDigits <= 1: to run in src/EnergyPlus directly. It issues a few false positives.

```python
import glob as gb
import re
files = gb.glob('*.cc')

regex_predef = re.compile(r'PreDefTableEntry\([^,;]+,[^,;]+,[^,;]+,[^,;]+,[^,;]*(\d+)[^,;]*\);')

for fname in files:
    msgs = []
    with open(fname, 'r') as f:
        content = f.read()
    lines = content.splitlines()
    for i, line in enumerate(lines):
        
        if 'PreDefTableEntry' in line:
            nls = [lines[i]]
            while ";" not in lines[i]:
                nls.append(lines[i+1])
                i += 1
            
            
            for m in regex_predef.finditer("\n".join(nls)):
                if int(m.groups()[0]) == 1:
                    g = m.group()
                    cleaned = " ".join([x.strip() for x in g.split('\n')])
                    msgs.append(f'L{i}: {cleaned}')
            
    if msgs:
        print(f'\n========= {fname} ========')
        for msg in msgs:
            print(f'  - {msg}')
        print('\n')
```

### Output:

#### SigDigits = 0

```c++
SizingAnalysisObjects.cc#L630: PreDefTableEntry(state,
                             state.dataOutRptPredefined->pdchPlantSizPkTimeMin,
                             state.dataPlnt->PlantLoop(plantLoopIndex).Name + " Sizing Pass " + chIteration,
                             newFoundMassFlowRateTimeStamp.stepStartMinute,
                             0
SizingAnalysisObjects.cc#L650: PreDefTableEntry(state,
                             state.dataOutRptPredefined->pdchPlantSizPkTimeMin,
                             state.dataPlnt->PlantLoop(plantLoopIndex).Name + " Sizing Pass " + chIteration,
                             NewFoundMaxDemandTimeStamp.stepStartMinute,
                             0
```

#### SigDigits = 1

```c++
========= StandardRatings.cc ========
  - L2497: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSI, CompName, CoolCapVal, 1);
  - L2525: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXHeatCoilHighCap, CompName, HighHeatingCapVal, 1);
  - L2526: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXHeatCoilLowCap, CompName, LowHeatingCapVal, 1);
  - L2547: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSI, CompName, CoolCapVal, 1);
  - L2650: PreDefTableEntry(state, pdchDXCoolCoilNetCapSIA, CompNameNew, format("{:.1R}", NetCoolingCapRated(Num + 1)));
  - L2650: PreDefTableEntry(state, pdchDXCoolCoilNetCapSIA, CompNameNew, format("{:.1R}", NetCoolingCapRated(Num + 1)));
  - L2651: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSIA, CompNameNew, NetCoolingCapRated(Num + 1), 1);
  - L2652: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSIB, CompNameNew, NetCoolingCapRated(Num + 2), 1);
  - L2653: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSIC, CompNameNew, NetCoolingCapRated(Num + 3), 1);
  - L2654: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSID, CompNameNew, NetCoolingCapRated(Num + 4), 1);
  - L2657: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilElecPowerA, CompNameNew, TotElectricPowerRated(Num + 1), 1);
  - L2658: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilElecPowerB, CompNameNew, TotElectricPowerRated(Num + 2), 1);
  - L2659: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilElecPowerC, CompNameNew, TotElectricPowerRated(Num + 3), 1);
  - L2660: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilElecPowerD, CompNameNew, TotElectricPowerRated(Num + 4), 1);



========= DXCoils.cc ========
  - L14889: PreDefTableEntry(state, state.dataOutRptPredefined->pdchDXCoolCoilNetCapSI, state.dataDXCoils->DXCoil(DXCoilNum).Name, NetCoolingCapRated, 1);



========= SizingManager.cc ========
  - L665: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClCalcDesLd, curName, 0.0, 1);
  - L666: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClUserDesLd, curName, 0.0, 1);
  - L667: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClUserDesLdPerArea, curName, 0.0, 1);
  - L668: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClCalcDesAirFlow, curName, 0.0, 1);
  - L669: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClUserDesAirFlow, curName, 0.0, 1);
  - L672: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkTstatTemp, curName, 0.0, 1);
  - L673: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkIndTemp, curName, 0.0, 1);
  - L674: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkIndHum, curName, 0.0, 1);
  - L675: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkOATemp, curName, 0.0, 1);
  - L676: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkOAHum, curName, 0.0, 1);
  - L677: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkOAMinFlow, curName, 0.0, 1);
  - L678: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnClPkDOASHeatGain, curName, 0.0, 1);
  - L749: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtCalcDesLd, curName, 0.0, 1);
  - L750: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtUserDesLd, curName, 0.0, 1);
  - L751: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtUserDesLdPerArea, curName, 0.0, 1);
  - L752: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtCalcDesAirFlow, curName, 0.0, 1);
  - L753: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtUserDesAirFlow, curName, 0.0, 1);
  - L756: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkTstatTemp, curName, 0.0, 1);
  - L757: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkIndTemp, curName, 0.0, 1);
  - L758: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkIndHum, curName, 0.0, 1);
  - L759: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkOATemp, curName, 0.0, 1);
  - L760: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkOAHum, curName, 0.0, 1);
  - L761: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkOAMinFlow, curName, 0.0, 1);
  - L762: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZnHtPkDOASHeatGain, curName, 0.0, 1)


========= ReportCoilSelection.cc ========
  - L171: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilFinalAirVolFlowRate, c->coilName_, c->coilRefAirVolFlowFinal, 1);
  - L179: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilFinalPlantVolFlowRate, c->coilName_, c->coilRefWaterVolFlowFinal, 1);
  - L190: PreDefTableEntry( state, state.dataOutRptPredefined->pdchFanAssociatedVdotSize, c->coilName_, c->fanSizeMaxAirVolumeFlow, 1);
  - L197: PreDefTableEntry( state, state.dataOutRptPredefined->pdchFanAssociatedMdotSize, c->coilName_, c->fanSizeMaxAirMassFlow, 1);
  - L222: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilAirMassFlowIdealPeak, c->coilName_, c->coilDesMassFlow, 1);
  - L229: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilAirVolumeFlowIdealPeak, c->coilName_, c->coilDesVolFlow, 1);
  - L239: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilEntHumRatIdealPeak, c->coilName_, c->coilDesEntHumRat, 1);
  - L244: PreDefTableEntry(state, state.dataOutRptPredefined->pdchCoilEntEnthalpyIdealPeak, c->coilName_, c->coilDesEntEnth, 1);
  - L250: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilLvgHumRatIdealPeak, c->coilName_, c->coilDesLvgHumRat, 1);
  - L255: PreDefTableEntry(state, state.dataOutRptPredefined->pdchCoilLvgEnthalpyIdealPeak, c->coilName_, c->coilDesLvgEnth, 1);
  - L258: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilWaterMassFlowIdealPeak, c->coilName_, c->coilDesWaterMassFlow, 1);
  - L280: PreDefTableEntry(state, state.dataOutRptPredefined->pdchCoilRatedAirMass, c->coilName_, c->ratedAirMassFlow, 1);
  - L289: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilRatedEntHumRat, c->coilName_, c->ratedCoilInHumRat, 1);
  - L295: PreDefTableEntry(state, state.dataOutRptPredefined->pdchCoilRatedEntEnthalpy, c->coilName_, c->ratedCoilInEnth, 1);
  - L300: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilRatedLvgHumRat, c->coilName_, c->ratedCoilOutHumRat, 1);
  - L306: PreDefTableEntry(state, state.dataOutRptPredefined->pdchCoilRatedLvgEnthalpy, c->coilName_, c->ratedCoilOutEnth, 1);
  - L310: PreDefTableEntry( state, state.dataOutRptPredefined->pdchPlantMassFlowMaximum, c->coilName_, c->plantDesMaxMassFlowRate, 1);
  - L323: PreDefTableEntry( state, state.dataOutRptPredefined->pdchCoilFlowPrcntPlantFlow, c->coilName_, c->coilFlowPrcntPlantFlow, 1);
  - L331: PreDefTableEntry(state, state.dataOutRptPredefined->pdchOAHumRatIdealPeak, c->coilName_, c->oaPeakHumRat, 1);
  - L338: PreDefTableEntry(state, state.dataOutRptPredefined->pdchOAVolFlowIdealPeak, c->coilName_, c->oaPeakVolFlow, 1);
  - L347: PreDefTableEntry( state, state.dataOutRptPredefined->pdchAirSysRAHumRatIdealPeak, c->coilName_, c->raPeakHumRat, 1);
  - L355: PreDefTableEntry(state, state.dataOutRptPredefined->pdchZoneAirHumRatIdealPeak, c->coilName_, c->rmPeakHumRat, 1);
  - L390: PreDefTableEntry( state, state.dataOutRptPredefined->pdch2CoilFinalAirVolFlowRate, c->coilName_, c->coilRefAirVolFlowFinal, 1);
  - L398: PreDefTableEntry( state, state.dataOutRptPredefined->pdch2CoilFinalPlantVolFlowRate, c->coilName_, c->coilRefWaterVolFlowFinal, 1);
  - L415: PreDefTableEntry( state, state.dataOutRptPredefined->pdch2CoilAirVolumeFlowIdealPeak, c->coilName_, c->coilDesVolFlow, 1);
  - L425: PreDefTableEntry( state, state.dataOutRptPredefined->pdch2CoilEntHumRatIdealPeak, c->coilName_, c->coilDesEntHumRat, 1);
  - L435: PreDefTableEntry( state, state.dataOutRptPredefined->pdch2CoilLvgHumRatIdealPeak, c->coilName_, c->coilDesLvgHumRat, 1);
  - L446: PreDefTableEntry(state, state.dataOutRptPredefined->pdch2OAHumRatIdealPeak, c->coilName_, c->oaPeakHumRat, 1);
  - L457: PreDefTableEntry( state, state.dataOutRptPredefined->pdch2ZoneAirHumRatIdealPeak, c->coilName_, c->rmPeakHumRat, 1);
```

**Comment by Myoldmopar** [comment]
From a CI perspective it looks great.  The new unit test looks to be passing just fine.  There is a weird build warning on Windows that I've never seen before and surely does not have anything to do with this change.

**Review by Myoldmopar — APPROVED** [review]
Code changes look good.  Kind of an odd bug, but good work getting it resolved, and the new unit tests look thorough.

**Comment by Myoldmopar** [comment]
OK, got the Clang Format done on the second pass.  Good to go.  Merging.
