### PR TITLE
Fix DOAS system sizing and add reporting

### LINKED ISSUE #10782: AirLoopHVAC:DedicatedOutdoorAirSystem Sizing Mixing up Mass and Volume Flow Rates, no reporting
Issue overview
--------------
Noticed that SizingAirLoopDOAS is treating a volume flow rate a mass flow rate.  

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/AirLoopHVACDOAS.cc#L990

There is also no reporting of the sizing outcomes for DOAS system to the EIO or summary tables  so it is hard to point to the incorrect sizing result.  

Need to fix volume vs mass flow problem and add reporting,

### Details
[in.zip](https://github.com/user-attachments/files/17246677/in.zip)

Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

### PR DESCRIPTION
**Pull request by EnergyArchmage**
Pull request overview

Code fixes for volume vs mass flow rate mix up.  add reporting of sizing results

---------------------
 - Fixes #10782
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

**NOTE: ENHANCEMENTS MUST FOLLOW A SUBMISSION PROCESS INCLUDING A FEATURE PROPOSAL AND DESIGN DOCUMENT PRIOR TO SUBMITTING CODE**

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mjwitte** [comment]
@EnergyArchmage Is this ready for review?

**Comment by rraustad** [comment]
@mjwitte this is ready for review. I have looked over it and it is the same as used in the other engine.

**Comment by EnergyArchmage** [comment]
This good to go, but may have a follow up to have both a max and min design size. Coils are getting oversized using only max oa flow.

**Comment by mjwitte** [comment]
There's a failing unit test, `AirLoopHVACDOAS_TestFanHeatAddeToCoolingCoilSize`.

File: src/EnergyPlus/AirLoopHVACDOAS.cc [hunk 1]
```diff
@@ -980,32 +981,35 @@ namespace AirLoopHVACDOAS {
...
             if (this->m_OACtrlNum[AirLoop - 1] > 0) {
-                sizingMassFlow += state.dataMixedAir->OAController(this->m_OACtrlNum[AirLoop - 1]).MaxOA;
+                sizingVolumeFlow +=
+                    state.dataMixedAir->OAController(this->m_OACtrlNum[AirLoop - 1]).MaxOA; // this is a volume flow rate not a mass flow rate
             }
         }
-        this->SizingMassFlow = sizingMassFlow;
+        this->SizingMassFlow = sizingVolumeFlow * state.dataEnvrn->StdRhoAir;
+
+        BaseSizer::reportSizerOutput(state, "AirLoopHVAC:DedicatedOutdoorAirSystem", this->Name, "Design Volume Flow Rate [m3/s]", sizingVolumeFlow);
```
Comment (mjwitte) [inline src/EnergyPlus/AirLoopHVACDOAS.cc:984]: Most (all?) other equipment reports sizing as "Design Size Air Flow Rate [m3/s]" or "Design Size Maximum Air Flow Rate". This should probably use similar language. @rraustad ?

**Review by mjwitte — COMMENTED** [review]
@EnergyArchmage Thanks for the unit test fix. This works as advertised. Posted #10802 but that's a separate issue.

File: src/EnergyPlus/AirLoopHVACDOAS.cc (hunk 1 above)
Comment (rraustad) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:984]: Usually it's "Design Size" or User-Specified"  pre-pended on the front end of the field names which are not uniform. But this object doesn't have a field for air flow so it's a sum of this field. I have no preference for this object since it's not autosized or hard-sized but I guess it could match what the air loop reports since that's what gets summed.

    AirLoopHVAC,
       N1, \field Design Supply Air Flow Rate

The air loop doesn't follow this naming convention either.

    Component Sizing Information, AirLoopHVAC, VAV SYS 1, Design Supply Air Flow Rate [m3/s], 1.08612

Unitary System looks like this:

    Component Sizing Information, AirLoopHVAC:UnitarySystem, DX COOLING COIL, Design Size Cooling Supply Air Flow Rate [m3/s], 1.34859
    Component Sizing Information, AirLoopHVAC:UnitarySystem, HEATPUMP DX COIL 1, Design Size Heating Supply Air Flow Rate [m3/s], 1.34859

TUs:

    Component Sizing Information, AirTerminal:SingleDuct:VAV:Reheat, SPACE1-1 VAV REHEAT, Design Size Maximum Air Flow Rate [m3/s], 0.20149

Comment (rraustad) [reply src/EnergyPlus/AirLoopHVACDOAS.cc:984]: Actually it's this field that gets summed:

    Controller:OutdoorAir,
      N2 , \field Maximum Outdoor Air Flow Rate

    Component Sizing Information, Controller:OutdoorAir, OA CONTROLLER 1, Maximum Outdoor Air Flow Rate [m3/s], 1.08612
    Component Sizing Information, Controller:OutdoorAir, OA CONTROLLER 1, Minimum Outdoor Air Flow Rate [m3/s], 0.26412

**Comment by nrel-bot-2** [comment]
@mjwitte @EnergyArchmage it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@mjwitte @EnergyArchmage it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2c** [comment]
@mjwitte @EnergyArchmage it has been 7 days since this pull request was last updated.

**Review by mjwitte — APPROVED** [review]
Assuming linux CI results are green, this is ready to merge.

**Comment by Myoldmopar** [comment]
I'll try to tackle the conflicts here and get this merged in, but with diffs, I anticipate it falling in line behind the log1p and expm1 minimal PRs that also throw diffs.

**Comment by Myoldmopar** [comment]
I was able to resolve the conflict.  Looks like it was primarily just a fan refactor moved the indexes to 1 based, so I had to merge that with the changes here in only one spot.  I'll double check it of course, building now.

**Comment by Myoldmopar** [comment]
Alright, got the conflict resolved, and ran the full test suite, with everything passing happily.  I ran regressions and got the same exact regressions in the CentralDOAS file that was showing up here.  This seems good to go.  I'll push and merge.  Thanks @EnergyArchmage for the changes, and @rraustad and @mjwitte for reviewing.
